### ISSUE TITLE
Integration to volkszaehler

### ISSUE THREAD

**Issue by Franzformator** [jomjol/AI-on-the-edge-device#1]
Hi!

I really like your project und I am impressed of all the work you have done since now!

A big improvement I think would be a connection/integration of your sensor to https://www.volkszaehler.org/.

Volkszaehler is a great tool to monitor consumption meters (I am using it for my electric meter - EHZ)

Thank you for your Work!

**Comment by jomjol** [comment]
Good idea in principle. At the moment this is still too much beta, as it will take several versions to get really stable and usable for "non neerds". I'll keep it in my mind for a later time.
If you like to support, I could implement a dedicated interface to connect to the volkszaehler and somebody else could do the integration. This would be faster and easier to do for me.
Just let me know if somebody would like to support

For the time beeing I will close this issue.
