### ISSUE TITLE
Werte nach erfolgreichem Erkennen und Änderung zum letzten lesen via MQTT senden

### ISSUE THREAD

**Issue by d0m1n1qu3** [jomjol/AI-on-the-edge-device#10]
Hi,

hast du das selber schon vor oder wäre das was was ich selbst einbauen soll/kann?

Ich würde lieber die Werte bei Änderung bekommen statt dauernd pollen zu müsen ;-)

Was hällst du davon?

**Comment by jomjol** [comment]
Keine schlechte Idee. Ich verfolge das nicht aktiv, auch weil ich es nicht benötige und erstmal eine Testumgebung aufbauen müsste.

Wenn du das übernehmen willst, gerne!

**Comment by jomjol** [comment]
Schließe Issue da Thema in anderem Issue angegangen wird: https://github.com/jomjol/AI-on-the-edge-device/issues/21
