### ISSUE TITLE
Implement Ideas from Peter (fhem forum)

### ISSUE THREAD

**Issue by jomjol** [jomjol/AI-on-the-edge-device#100]
Noch ein paar Ideen für's Wiki die ich so im Laufe der Zeit aus verschiedenen Postings bzw. als Info von Dir gesammelt habe:
- Die SD-Karte sollte ein FAT32 Filesystem haben.
- Das Power Supply sollte mindestens 500 mA pro Device hergeben (hat Wasserhexe gemessen).
- Die Stromversorgung sollte für Spitzen ggf. mit einem Elko gestützt werden (mehrere Hundert µF).
- Die LED kann mittels weißem Filzpuffer (gibt es für Möbel) abgedunkelt werden. Wenn einer nicht hilft, nimm einen zweiten dickeren.

Du hast da übrigens noch ein File mit einem Leerezeichen im Namen in Deinem Filesystem:

sylvester:/tmp/AI-on-the-edge-device # find . -name "* *"
./sd-card/html/setup - Kopie.html
sylvester:/tmp/AI-on-the-edge-device #

**Comment by audi2010** [comment]
Danke für deine Arbeit. Ist ja leicht zu installieren.
Ich habe eben mal einen Beitrag im IP-Symcon-Forum veröffentlich:
https://www.symcon.de/forum/threads/45746-Wasseruhr-auslesen-mit-einem-ESP32-CAM

**Comment by jomjol** [comment]
Done!
