### ISSUE TITLE
Tests in CI/CD pipeline

### ISSUE THREAD

**Issue by caco3** [jomjol/AI-on-the-edge-device#1001]
@haverland, @jomjol 

We have now a build pipeline, see https://github.com/jomjol/AI-on-the-edge-device/actions

I know you have some tests implemented. 
Is it possible to run some of them without areal device?
I just found , but I would need to know how to call them which relies on real hardware.

We then could also run them in the pipeline.

**Comment by haverland** [comment]
Theoretical it could run without any esp32 device. The difference in components and the dependencies to other components makes it not easy to use. The test-cases must be moved in path of the component.

https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/linux-host-testing.html

Overall it need more than a few changes to integrate it.

**Comment by haverland** [comment]
The freertos is available for linux, but not all esp-idf components, especially esp32-cam.

` ERROR: Component "esp32-camera-master" does not support target linux`

The only way to integrate regression testing would be to extract the code into the lib folder, but it would not good to cluster the code more at it is.

**Comment by caco3** [comment]
I see :(

Thanks for looking into it.
It was just an idea but i see the complexity and effort which does not weight the benefits.

I will close it for now.
