### ISSUE TITLE
Value increasing above the logically possible

### ISSUE THREAD

**Issue by cbho** [jomjol/AI-on-the-edge-device#1005]
Hi,
(First: Yes, I know that the focus looks awful, but it can't be better, it's something with the LCD itself that causes this and I've tried _everything_ to get it better - but as you can se, the numbers in that are looking really bad (the kWh reading), are actually interpreted by the AI absolutely correct all the time - pretty cool, actually! - this is the focus that gives the best readings overall - but that isn't the issue here anyway, I would say)

**Issue**
just noticed an odd value on my device monitoring a digital power meter:
A number has jumped to a value above what I think would be logically impossible (or, perhabs more precise: _should_ be logically impossible:

The kW number displayed is X.XX and ROIs are defined accordingly.
However, while the raw value is the correct (0.37) the adjusted value has increased to 10.37:

![10_37](https://user-images.githubusercontent.com/29979509/189516363-f571e801-37c0-48a0-97a4-d3ca308274f2.png)

While creating this issue, I wanted to take another picture than the one above, as the adjusted value wasn't included.
However, now the adjusted value had increased yet another kW to 11.35:
(That the last digit is interpreted as 5, while it is 9 is a minor error and, I think, an understandable thing).

![11_35](https://user-images.githubusercontent.com/29979509/189516415-32a446cb-53ce-447e-89e6-f09d70dcb664.png)

A little later, the adjusted value has decreased again to 1.35

![1_35](https://user-images.githubusercontent.com/29979509/189516953-97a0b2d9-e697-4cd6-b64c-7df0ae8f2ff5.png)

A little later yet, everything looks just perfect again:
![image](https://user-images.githubusercontent.com/29979509/189517295-668033b1-e67a-4686-b1bd-415985742405.png)

**Proposal to solution**
Given that there is only defined 1 ROI before the period, it is logically not possible that the value before the period could include two significant numbers.
It is therefore suggested, that the algorithm checkning for consistency include, that the number cannot increase above the logically impossible.

**Version Info**
Git-Base-Branch: master - v11.2.0 - 2022-08-28
Build Time: 2022-08-28 19:59
HTML Version 15.1.0

**Settings**
[Digits]
Model = /config/dig-class11_1411_s2_q.tflite

[PostProcessing]
kWh.DecimalShift = -2
kW.DecimalShift = -2
PreValueUse = true
PreValueAgeStartup = 720
AllowNegativeRates = true
kWh.MaxRateValue = 10
kW.MaxRateValue = 100
kWh.MaxRateType = AbsoluteChange
kW.MaxRateType = AbsoluteChange
kWh.ExtendedResolution = false
kW.ExtendedResolution = false
kWh.IgnoreLeadingNaN = true
kW.IgnoreLeadingNaN = true
ErrorMessage = false
CheckDigitIncreaseConsistency = true

Add:
I just noticed that my kW,MaxRateValue is set to 100 (don't know why I've set that value back in time).
Don't know if that can be part of the problem, as that kind of implies there could be more significant numbers before the period. However, still, I think the logic in the problem is still relevant :-)

**Comment by jomjol** [comment]
Can you post a screenshot of the menue point "Recognition"? I wnat to see, what the neural network actually detected.

That would help in error detection.

**Comment by cbho** [comment]
At present all values are correct:
![image](https://user-images.githubusercontent.com/29979509/189520628-d046cf01-0230-4d6e-88a4-52cb845e79c4.png)

I guess the most helpful would have been a screenshot while the error was present - unfortunately, I didn't think about that taking that.
However, as far as I remember, it looked correct (= the same as the raw value), when I checked.

**Comment by jomjol** [comment]
Yep, look good, so the problem is in the algo. 
You should disable "CheckDigitConsistency" at least for the kW measurement. As you don't have an analog counter, this should not cause problems. I assume in this part of the algo, there is the problem.

**Comment by cbho** [comment]
The "CheckDigitConsistency" is only available as a general setting:
![image](https://user-images.githubusercontent.com/29979509/189521197-9d17d5d9-43a6-4401-ae0e-a2dbd7a27314.png)

Does it work, if you change it in the config-file directly to
```
kW.CheckDigitIncreaseConsistency = false
kWh.CheckDigitIncreaseConsistency = true
```

And, btw, does it work, if you do that also with AllowNegativeRates?
e.g.:
```
kW.AllowNegativeRates = true
kWh.;AllowNegativeRates = false
```

**Comment by jomjol** [comment]
You are right, this value is currently an overall parameter and cannot be set to subnumbers. Something in the backlog :-(

**Comment by stefanbode** [comment]
CheckDigitIncreaseConsistency = true also kicks my ass with not understanding what was happening. For me it looks like even if the explanation is more than correct TOOOOOO many users click this TRUE to expect to get something gets better and at the end it just made it worse. Maybe a big WARNING in the documentation will make it

**Comment by jomjol** [comment]
current rolling (20220916) has now a check for not usefull checkincrease consisteny.
