### ISSUE TITLE
Photo for gas meter drifting away

### ISSUE THREAD

**Issue by plin2** [jomjol/AI-on-the-edge-device#101]
My gas meter implementation is quite instable. I wrote a script fetching the photo from the Digitizer every 5 minutes:

![ESP32_gas_pictures](https://user-images.githubusercontent.com/3195189/106384328-8b819100-63ca-11eb-8404-9582286bbed9.PNG)

The last proper reading propagated via MQTT is 34500.953.

When I turn the device off/on by removing power it starts all over again.

My **config.ini**:

[MakeImage]
;LogImageLocation = /log/source
;LogfileRetentionInDays = 15
WaitBeforeTakingPicture = 5
ImageQuality = 5
ImageSize = VGA

[Alignment]
InitialRotate = 177
/config/ref0.jpg 40 188
/config/ref1.jpg 432 420
SearchFieldX = 25
SearchFieldY = 25
AlignmentAlgo = Fast

[Digits]
Model = /config/dig0721s1.tflite
;LogImageLocation = /log/digit
;LogfileRetentionInDays = 3
ModelInputSize = 20 32
digit1 45 303 37 67
digit2 106 304 37 67
digit3 170 303 37 66
ROI3 234 303 37 66
ROI4 295 303 37 66
ROI5 358 303 37 66
ROI6 420 303 37 66
ROI7 494 303 37 66

;[Analog]
Model = /config/ana0630s2.tflite
;LogImageLocation = /log/analog
;LogfileRetentionInDays = 3
ModelInputSize = 32 32
analog1 444 225 92 92
analog2 391 329 92 92
analog3 294 369 92 92
analog4 168 326 92 92
ExtendedResolution = false

[PostProcessing]
DecimalShift = -3
PreValueUse = true
PreValueAgeStartup = 720
AllowNegativeRates = false
MaxRateValue = 9
ErrorMessage = true
CheckDigitIncreaseConsistency = true

[MQTT]
Uri = mqtt://192.168.3.10:1883
Topic = gaszaehler/zaehlerstand
TopicError = gaszaehler/error
ClientID = gas
;user = USERNAME
;password = PASSWORD

[AutoTimer]
AutoStart = true
Intervall = 5

[Debug]
Logfile = true
LogfileRetentionInDays = 3

[System]
TimeZone = CET-1CEST
;TimeServer = fritz.box
;Hostname = watermeter
;SetupMode = false

[Ende]

**Comment by jomjol** [comment]
Hello Peter,

reading out the pictures every 5 minutes is in the current setting not a good idea. To reduce the SD-card access, the image is then taken just in time. This takes 5-10 seconds and could interfere with the recognition itself. Although the web access is a frequent source of rebooting - reason is not know yet.

If you want to log the images, please use the writing of the files to the SD-card. You can access them via internal fileserver or by reading out the SD-card manually from time to time. The settings for this are:

```
[MakeImage]
LogImageLocation = /log/source
LogfileRetentionInDays = 3
WaitBeforeTakingPicture = 5
ImageQuality = 5
ImageSize = VGA
```

With this you would keep the last 3 days on the SD-card.

Beste regards,
  jomjol

**Comment by plin2** [comment]
config.ini is adjusted. Will do a soft reboot and then a hard reboot to be on the safe side.

**Comment by plin2** [comment]
update: I had the ESP running all night without any browser access. I have less black pictures, but several time they are upside down.
![ESP32_gas_pictures1](https://user-images.githubusercontent.com/3195189/106441893-ea064800-647a-11eb-8129-01d145dc9681.PNG)
![ESP32_gas_pictures2](https://user-images.githubusercontent.com/3195189/106441911-ee326580-647a-11eb-9c88-7723fc54780e.PNG)
When I compare the output from the gas meter and information from the heating system, there should be a more linear usage of gas
![Grafana_ESP32](https://user-images.githubusercontent.com/3195189/106442037-191cb980-647b-11eb-877e-9bd7d2d2c1f2.PNG)
Currently iÄm working with the following markers
![alg_roi_20210102_1040](https://user-images.githubusercontent.com/3195189/106442084-2afe5c80-647b-11eb-99ce-284d56403903.jpg)
I went from the 494 on the bottom to the 1994, because I thought it might be too close zo the edge. Now I'm wondering if these two markers don't have enough contrast to be suffient enough for alignment.

**Comment by plin2** [comment]
Well, I think to see one pattern: The first hour after a hard reset is fine. Approximately one hour after that I see the first upside down picture. Since yesterday evening I have ssen that pattern about 4 to 5 times. Hard resets are marked as blue lines.
![ESP32_gas_pictures11](https://user-images.githubusercontent.com/3195189/106488681-3fab1680-64b4-11eb-8266-3daa78e0cb67.PNG)
![ESP32_gas_pictures12](https://user-images.githubusercontent.com/3195189/106488694-433e9d80-64b4-11eb-8072-d5f0e78674c9.PNG)
![ESP32_gas_pictures16](https://user-images.githubusercontent.com/3195189/106488714-476abb00-64b4-11eb-926f-d4ae736d7924.PNG)
![ESP32_gas_pictures17](https://user-images.githubusercontent.com/3195189/106488730-4b96d880-64b4-11eb-815f-516da68a0dec.PNG)
I even cleaned the glas of the gas meter, but that didn't help ...

**Comment by jomjol** [comment]
Hello Peter,
it is hard for me to do here a remote debugging. I suggest to get in personal contact (e.g. skype) and discuss this problem there. Can you somehow send me a private message through another channel (via iobroker or fhem, ...) with your email, than I will contact you this way.
Best regards,
  jomjol

**Comment by jomjol** [comment]
Hallo Peter,
ich schließe den Issue mal nach unserer offline Diskussion und deiner positiven RM, dass es vermutlich eher an der Hardware liegt.
Beste Grüße,
  jomjol

**Comment by plin2** [comment]
Additional information for those that run into the same problem: How do you determine that your ESP32-CAM ist defect?
I used another ESP32-CAM with the old sd card. The problem didn't occur any more. 
Then I flashed the sample ESP32-CAM Webcam sketch onto the "defect" one. Even that stopped working after some time.
