### ISSUE TITLE
ROI positioning analog

### ISSUE THREAD

**Issue by busaku** [jomjol/AI-on-the-edge-device#1015]
I got some errors with the positioning of the analog ROI-settings:
![image](https://user-images.githubusercontent.com/25269085/190223057-798afea7-0ee4-440a-a85f-32ec5f11cddc.png)
![image](https://user-images.githubusercontent.com/25269085/190223090-670cec2f-2bce-4c28-ba63-f95752e1c0ec.png)

Later on main-page:
![image](https://user-images.githubusercontent.com/25269085/190223240-47781f2b-2def-4e94-b2fb-62f752ee6d71.png)

And recognition:
![image](https://user-images.githubusercontent.com/25269085/190223317-185d80b5-ae1d-44a4-8e99-cba103a03d4f.png)

I tried everything but its always moved in one way.
Did anyone got an idea?

**Comment by haverland** [comment]
It comes from alignment process. I would try to reconfigure reference image, alignment mark and ROIs.
The alignment marks should have a good contrast.

**Comment by busaku** [comment]
Worked! Can be closed :)
Played with alignment marks - and now its perfect.

**Comment by RosaEinhorn** [comment]
Hi @busaku, looks like we have the same water meter. Did you manage to make ai-on-the-edge recognize the third analog wheel correctly (the one with the magnet)? I am having issues with it. Thanks!

**Comment by busaku** [comment]
Hey,

no i dont get it.
But 2 Analog with the option to add one more number works fine :)

**Comment by RosaEinhorn** [comment]
Can you explain what you mean with "the option to add one more number" and point me into the right direction? :)

**Comment by busaku** [comment]
Yh, just go to 

Configuration and enable "ExtendedResolution",
So the AI will use first two analog numbers and calculate the third

You will get the water usage to the liter exactly :)
