### ISSUE TITLE
Wasseruhr in IP-Symcon

### ISSUE THREAD

**Issue by audi2010** [jomjol/AI-on-the-edge-device#102]
Danke für deine Arbeit. Ist ja leicht zu installieren.
Ich habe eben mal einen Beitrag im IP-Symcon-Forum veröffentlich:
https://www.symcon.de/forum/threads/45746-Wasseruhr-auslesen-mit-einem-ESP32-CAM
Gruss Rainer

**Comment by jomjol** [comment]
Hallo Rainer,
gerne und vielen Dank!
Beste Grüße,
  jomjol

**Comment by jomjol** [comment]
@audi2010 
Nachtrag: habe gerade gesehen, dass im Forum gefragt wird, ob auch andere Zähler funktionieren --> ja geht!
Du kannst du analogen Zeiger abschalten und damit auch normale Strom- oder Gaszähler auslesen.

Wenn du willst, kannst du das gerne dort posten.

Beste Grüße,
  jomjol

**Comment by audi2010** [comment]
Gleich erledigt.
Ich werde das mit meinem Gaszähler gleich auch mal machen.
Gut. dass ich noch ein ESP32Cam übrig habe. Liegt bei mir schon fast ein Jahr und wartet.
Irgendwie wusste ich, dass der Kauf damals sinnvoll war.

**Comment by MMeinhardt1** [comment]
@audi2010
[Hier](https://forum.iobroker.net/topic/36622/wasserzähler-version-2-all-in-device) mal der link zum Thread im iobroker Forum für den Fall das Fragen aufkommen sollten in eurem Forum.

Und haben ist immer besser als brauchen 🤣
