### ISSUE TITLE
Backwards running dial

### ISSUE THREAD

**Issue by fsargent** [jomjol/AI-on-the-edge-device#1022]
Hiya, I have a pretty terrible gas meter, the B698-W via PG&E. It's got a digital display but then the analog meters are in 'half foot' and 'two feet' increments *and run counter clockwise*

Any suggestions on how I can get this to output something sensible?

![image](https://user-images.githubusercontent.com/273880/190728652-32e4950a-7aa4-4aa6-8672-9b73be2b47ac.png)

Thank you for building this!

**Comment by jomjol** [comment]
The newest version can also handle counter clockwise pointers, but this type might not be in the training data and therefore be probelamtic anyway.

**Comment by fsargent** [comment]
Any ideas on where to start? I don't really understand why this would work this way *anyway*
Why bother having half foot and two feet as a meter reading? I suppose it means that the top meter isn't continuous either. 

So it's 467000 + 2 + .5, so for one tick I need to see the two feet go round 50 times and the .5 go around 200 times? Bizarre.

**Comment by jomjol** [comment]
Sorry, I did not understand your full problem with half foot and two feet. 

There is no way, the current software can handle this directdly. What you could do is setting 3 numbers:
1) Digits as is; output: 476
2) Pointer half foot: output: 0
3) Pointer two feet: output 2.5

And then do the calculations on the server.
