### ISSUE TITLE
after update 11.3.0 device isn't reachable

### ISSUE THREAD

**Issue by skynet74** [jomjol/AI-on-the-edge-device#1023]
After firmware and html update the device isn't reachable anymore. (html & REST & ping)

is it possible to recover the system via SD card?

**Comment by jomjol** [comment]
From which version did you update? 
Did you firstly update the firmware and check, that it is actually running before updating the html?

**Comment by skynet74** [comment]
From 11.2.0

**Comment by kapet** [comment]
Same problem here. Previous firmware was 11.2 (flashed a couple days ago) using a fresh copy of the sd-card directory just pulled an hour ago. Interestingly the config wizard worked fine and the recognition worked, but now upgrading to 11.3 led to the device going awol.

**Comment by jomjol** [comment]
@kapet: did you update the firmeware first and then test if it is really running?

**Comment by kapet** [comment]
Yeah, it's not coming back from the reboot after just flashing the firmware. I didn't even get to the step of uploading the html zip yet.

**Comment by kapet** [comment]
(But as mentioned - I had just installed a new SD card this morning as the old one broke a few days ago, and used a fresh sd-card directory from github. So I guess I was running 11.2 with the most up to date html already? It worked fine, until I flashed the 11.3 firmware.)

**Comment by jomjol** [comment]
I did a quick test:
1) Freshly setup testdevice to v11.2.0 (firmware & sd-card)

2a) Update firmware.bin and html.zip in one step
2b) Update first firmware.bin --> reboot; then update html.zip

In both cases the new version was 11.3.0 and I could reach the web interfache without any problem.

**Comment by skynet74** [comment]
We wait for other people... :)

I can flash the ESP manually at monday, on a intel mac,.

**Comment by florie1706** [comment]
I came from 11.2 and just flashed 11.3 firmware.bin via ota. I thought you meant to reboot before uploading html.zip For now it did not come back online ...

**Comment by jomjol** [comment]
I testet both hand it works. What does not work for sure: using new html.zip with the old firmware.bin

**Comment by nliaudat** [comment]
Same problem. I've updated the firmware.bin rebooted and the device do not respond anymore.
After a hard power off, the device is still hanging.

**Comment by pfanntec** [comment]
After updating from 10.2.0 to 10.3.0 the ESP does not start for me either. I have flashed back the 10.2.0 via USB and it runs again.

**Comment by skynet74** [comment]
@pfanntec 11.x?

**Comment by pfanntec** [comment]
Sorry. Should of course be 11.2.0 and 11.3.0.

**Comment by nobodyman1** [comment]
I used a complete fresh installation with the new firmware and SD card files. The device doesn´t boot properly.
The last lines from the bootlog are:
```
I (1860) heap_init: Initializing. RAM available for dynamic allocation:
I (1867) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM
I (1873) heap_init: At 3FFC0308 len 0001FCF8 (127 KiB): DRAM
I (1879) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
I (1885) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (1892) heap_init: At 40097F64 len 0000809C (32 KiB): IRAM
I (1898) spiram: Adding pool of 4096K of external SPI memory to heap allocator
ets Jul 29 2019 12:21:46

rst:0x10 (RTCWDT_RTC_RESET),boot:0x3 (DOWNLOAD_BOOT(UART0/UART1/SDIO_REI_REO_V2))
waiting for download
```

**Comment by nliaudat** [comment]
I have a different reset boot loop : 

```
rst:0x10 (RTCWDT_RTC_RESET),boot:0x1b (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:7664
load:0x40078000,len:15360
load:0x40080400,len:3744
entry 0x4008067c
```

**Comment by kapet** [comment]
Manually flashed 11.3 - still will not boot. Flashed 11.2 and back in action. With HTML version 16.4.1.

**Comment by nliaudat** [comment]
Fresh upload of 11.3.0 firmware by UART get the same result.

Reboot after 
`[0;32mI (1841) spiram: Adding pool of 4096K of external SPI memory to heap allocator`

**Comment by haverland** [comment]
Could it be the bootloader is overwritten? I would try the complete Installation like described in wiki

**Comment by reserve85** [comment]
same here, even with manually fresh uploaded firmware -> reboot

**Comment by nliaudat** [comment]
I do not understand .... Downgrading to 11.2.0 has the same effect. 
I have not erased flashed before uploading. The only difference with wiki.

**Comment by reserve85** [comment]
you need a hard reset after the downgrade, then it is running again.

**Comment by nliaudat** [comment]
I have hard reseted, 
Confirm erasing the flash and then uploading works

**Comment by kapet** [comment]
Frank, I had flashed full 11.3 set with bootloader and all, no dice. Installing 11.3 flash like described in the wiki led to a non booting system.

**Comment by pos-ei-don** [comment]
Is this a 2mb RAM system? My 4mb flashes as expected, my 2mb is dead, but i am not at the location to Check the Logs.

**Comment by caco3** [comment]
So I also did some tests (always OTA from 11.2.0):
 - flashing 11.3.0 (files taken from https://github.com/jomjol/AI-on-the-edge-device/tree/v11.3.0/firmware) will lead to a watchdog reset => bad
 - flashing firmware from autobuild https://github.com/jomjol/AI-on-the-edge-device/actions/runs/3069129522 => ok!
 - flashing firmware from autobuild https://github.com/jomjol/AI-on-the-edge-device/actions/runs/3072672006 => ok!

**Comment by caco3** [comment]
@kapet, @nliaudat @nobodyman1 @pfanntec Could you try it with the autobuild from https://github.com/jomjol/AI-on-the-edge-device/actions/runs/3072884567?
Simply download [
firmware__extract_before_upload__only_needed_for_migration_from_11.2.0 ](https://github.com/jomjol/AI-on-the-edge-device/suites/8338109960/artifacts/366813414) extract it and flash it OTA over a 11.2.0 firmware.

I am not 100% sure, but maybe something got wrong when @jomjol build it locally and added the builds to the repo.

**Comment by jomjol** [comment]
Can you replace the files or remove the release? I don't have access to
GitHub for the next view hours.
Thanks in advance

CaCO3 ***@***.***> schrieb am Sa., 17. Sept. 2022, 15:28:

**Comment by caco3** [comment]
> Can you replace the files or remove the release? I don't have access to GitHub for the next view hours. Thanks in advance 

sure

**Comment by pfanntec** [comment]
The version that @caco3 has posted works for me. 11.3.0 Build Time 2022-09-17 09:36

**Comment by friedpa** [comment]
Which version should I take when I am coming from 11.1.1?

**Comment by haverland** [comment]
> @skynet74, @florie1706, @haverland, @pos-ei-don, @kapet, @nliaudat, @nobodyman1, @pfanntec Could you try it with the autobuild from https://github.com/jomjol/AI-on-the-edge-device/actions/runs/3072884567? Simply download [ firmware__extract_before_upload__only_needed_for_migration_from_11.2.0 ](https://github.com/jomjol/AI-on-the-edge-device/suites/8338109960/artifacts/366813414) extract it and flash it OTA over a 11.2.0 firmware.
> 
> I am not 100% sure, but maybe something got wrong when @jomjol build it locally and added the builds to the repo.
> 
> I added a warning to the [release page](https://github.com/jomjol/AI-on-the-edge-device/releases/tag/v11.3.0) and marked it as `pre-release`. But I am not going to touch the master branch as @jomjol is the maintainer of it.

I'd tried it yesterday, but from my fork, not 11.3.0. 
1.) Installed 11.2.0 on dev-device (complete like wiki installation)
2.) installed via OTA the firmware (update_firmware_only__2022-09-15_17-14-59__rolling_(3008952).zip)
3.) reboot. 
5.) Installed html (html__only_needed_for_migration_from_11.2.0__2022-09-15_17-14-59__rolling_(3008952).zip)

All runs fine. I can test tomorrow the tagged version.

**Comment by haverland** [comment]
> Which version should I take when I am coming from 11.1.1?

Best is to update first to 11.2.0 before to 11.3.0.

**Comment by friedpa** [comment]
Ok, thanks!

**Comment by nliaudat** [comment]
@caco3 : (https://github.com/jomjol/AI-on-the-edge-device/suites/8338109960/artifacts/366813414) works ! 👍🏻 
No problem with OTA update

**Comment by mpuff** [comment]
I habe also problems, not reachable, also after fresh install

**Comment by haverland** [comment]
Mhh.. don't know if has a real impact:
PlatformIO->Inspect:
 "The program size (1973801 bytes) is greater than maximum allowed (1945600 bytes)"

**Comment by nliaudat** [comment]
> Mhh.. don't know if has a real impact: PlatformIO->Inspect: "The program size (1973801 bytes) is greater than maximum allowed (1945600 bytes)"

As caco3 mentionned, I mean the local build from jomjol is corrupted. The one from autobuild action works without problem.

**Comment by haverland** [comment]
> > Mhh.. don't know if has a real impact: PlatformIO->Inspect: "The program size (1973801 bytes) is greater than maximum allowed (1945600 bytes)"
> 
> As caco3 mentionned, I mean the local build from jomjol is corrupted. The one from autobuild action works without problem.

As some users described, a reflash does not fix the problem. Only a complete erasing and reflashing of boot loader and partition table. I wonder if there is an overflow on the 2nd ota partition here and phy_init is overwritten.

**Comment by skynet74** [comment]
after erasing the flash with "esptool.py erase_flash" and new flashing 11.2 "esptool.py write_flash 0x01000 bootloader.bin 0x08000 partitions.bin 0x10000 firmware.bin" it's now running

**Comment by jomjol** [comment]
### I'm very sorry for this discrupted release !!!

It looks like the asset (`firmware.bin`) I attached was corrupted for some reason, that I cannot figure out anymore. I have just released a version v11.3.1, that has an update version attached. Please use this instead.

If you have used the broken version, only a erease and reflash can help, as the firmware does not start at all anymore.

### Once again sorry for the inconvenience!

**Comment by haverland** [comment]
@caco3 You working on release action? If not I could do it like https://github.com/haverland/collectmeterdigits/blob/main/.github/workflows/release.yml 

@jomjol the last action before release was testing? With such release action it will build and release it automatically if you tag the commit.

**Comment by caco3** [comment]
@haverland 
> "The program size (1973801 bytes) is greater than maximum allowed (1945600 bytes)"

I have seen this error before when I built it myself. Oddly, when I built again, it fit into the given flash. Its at over 95%, so we will need have a look on it sometimes.
From other compilers/toolchains I know that the binary does not get built at all in such case, but I haven't checked with esp32.

**Comment by caco3** [comment]
> @caco3 You working on release action? If not I could do it like https://github.com/haverland/collectmeterdigits/blob/main/.github/workflows/release.yml
> 
> @jomjol the last action before release was testing? With such release action it will build and release it automatically if you tag the commit.

I have not yet looked into release actions. Currently it builds on every commit/push. 
We should have a look on a better release process, see also https://github.com/jomjol/AI-on-the-edge-device/issues/1002#issuecomment-1250077827

N.B. your linked script uses [upload-release-asset](https://github.com/actions/upload-release-asset) which is no longer maintained. They suggest to use https://github.com/softprops/action-gh-release now!

**Comment by kapet** [comment]
Finally got to update to 11.3.1 - works fine for me, using OTA from 11.2. Thank you for fixing the issue! :-)

**Comment by haverland** [comment]
> N.B. your linked script uses [upload-release-asset](https://github.com/actions/upload-release-asset) which is no longer maintained. They suggest to use https://github.com/softprops/action-gh-release now!

Thanks for advice.
