### ISSUE TITLE
HTML update could potentially brick UI

### ISSUE THREAD

**Issue by caco3** [jomjol/AI-on-the-edge-device#1032]
The HTML update is not save.

Its first action is to delete all files in the html folder. Only afterwards it extracts the zip file. If the user refreshes the page during this time or another error occurs (eg. crash, restart), no web UI is available anymore.

We should instead extract to a 2nd folder and only at its end replace the html folder with the new folder.

**Comment by jomjol** [comment]
My plan with the new update modus is, that not the complete directory is deleted, but only the one file, that is in progress.

**Comment by caco3** [comment]
That is good, but still you should rename it only after it got fully written. A corrupted or incomplete `index.html` is nasty.

**Comment by haverland** [comment]
> My plan with the new update modus is, that not the complete directory is deleted, but only the one file, that is in progress.

I think @caco3 idea is safer
1.) create a folder html-new and unzip all in it
2.)move html to html-old
3.) move html-new to html
4.) remove the html-old folder

**Comment by jomjol** [comment]
I can do the renaming also on the file level. I don't want to  be forced, always to replace a complete directory.
Background: the new update algo can also do updates of the tflite files in the config directory and I cannot delete the config folder as I only want to inject single tflite files.
It is already working. Currently I'm doing the html. This is not ready yet. You can check the intermediate state in the file ota_page_new.html.

**Comment by caco3** [comment]
Just keep in mind that the ESP could restart while you are half way through the html file replacement!
some files then would already be new, other still old. And the user would have no way of knowing it!
Even more, an new version might not work with a partially old verson when we update filenames, links or css.

**Comment by jomjol** [comment]
To be honest: I'm going to take that risk!

It was never a severe problem in the past - update was always done with first deletion of the complete html and then unzipping. With the new algo the risk is only at one file combined with the above inconsistency.

Going the other ways would need to distiguish between html-updates and config updates and ... . Therefore I'm okay with the remaining risk of briking the device in more than rare cases.

**Comment by caco3** [comment]
On the weekend, when I tried different rollings, I had it 2..3 times (!) that the HTML update failed (unexpected reboot or other reasons) and then I had a non-working webinterface. I had to re-write the sd-card to fix it.

But I do not want to push you anywhere!
I will wait for your changes. If I will experience this issue again, I might create a PR :)

**Comment by jomjol** [comment]
ok for me :-)
