### ISSUE TITLE
OTA fails - server closed the connection abuptly

### ISSUE THREAD

**Issue by s0170071** [jomjol/AI-on-the-edge-device#1047]
Happens with  master - v11.2.0 - 2022-08-28
Steps to reproduce: 
1. choose new binary
2. upload. 
3. click flash button

The system will hang until the browser displays the message. After that it is unresponsive until a power cycle. 
After cycle, the device is back to the previous firmware.

**Comment by cbho** [comment]
Same experience here.
Tried also doing uploading only after having deleted the old firmware.bin menually - same result.

**Comment by s0170071** [comment]
No, I tried it with that hardware often in the past. Never worked. Usually I give up and hook it up to the usb.

**Comment by caco3** [comment]
Then I guess its either a HW issue or a bug in the ESP library used for the flashing. I had a look on it and saw that it just hangs in one of the library steps :(
