### ISSUE TITLE
Feature Request: MQTT Callback

### ISSUE THREAD

**Issue by stromzaehler** [jomjol/AI-on-the-edge-device#105]
Ein tolles Projekt. Speziell der "Fast AlignmentAlgo" ist eine Bereicherung :-)

Aus meiner Sicht wäre es noch praktisch einige Einstellungen, wie z.B. "Intervall" per MQTT Callback machen zu können, die dann zur Laufzeit die Werte aus der Config.ini überschreiben. Auch ein spontaner Abruf des Messwertes wäre super.

Danke.

**Comment by klausdm** [comment]
MQTT yes :-)

**Comment by jomjol** [comment]
Due to lack of capacity this is not followed currently. In order to not forget it, it is added to the feature request page: https://github.com/jomjol/AI-on-the-edge-device/blob/master/FeatureRequest.md

Meanwhile this issue will be closed, as it is not active currently.
