### ISSUE TITLE
huge jump in measurement

### ISSUE THREAD

**Issue by kapet** [jomjol/AI-on-the-edge-device#1062]
Hey,

After a long time with really impressively good recognition results I turned on PreValueUse and turned off AllowNegativeRates again, to let the device do the post-processing instead of passing all values through.

And very soon afterwards I got this impressive spike (Influx CSV dump):
```
,,0,2022-09-21T20:00:00Z,2022-09-21T21:00:00Z,2022-09-21T20:15:00Z,316.8849,value,wassermeter
,,0,2022-09-21T20:00:00Z,2022-09-21T21:00:00Z,2022-09-21T20:19:50Z,316.889,value,wassermeter
,,0,2022-09-21T20:00:00Z,2022-09-21T21:00:00Z,2022-09-21T20:24:40Z,11111.8916,value,wassermeter
```

It jumped from 316.889 m^2 to 11111.8916 m^2 within 5 minutes. :-)

This is the relevant config section:
```
[PostProcessing]
main.DecimalShift = 0
PreValueUse = true
;PreValueAgeStartup = 720
AllowNegativeRates = false
;main.MaxRateValue = 0.05
;main.MaxRateType = AbsoluteChange
;main.ExtendedResolution = false
;main.IgnoreLeadingNaN = true
ErrorMessage = true
CheckDigitIncreaseConsistency = false
```

So I was assuming that leaving the little checkboxes in the config menu disabled would give me the default values and then the rate limit should prevent this kind of jump. Is that actually the case or do I have to explicitly enable the MaxRateValue option?

(I must also say I find it a bit suspicious that it would mis-recognize all 5 digits as '1' at the same time - is this possible or could this hint at some bug in post-processing?)

Unfortunately detailed logs were not enabled, I've done that now in case it happens again.

**Comment by caco3** [comment]
Which version are you using?
There are some issues which will be fixed in the next release.
See also other open [issues](https://github.com/jomjol/AI-on-the-edge-device/issues).

**Comment by kapet** [comment]
11.3.1

ack, feel free to close if this is a dup. Thx.
