### ISSUE TITLE
After submodule implementation no build

### ISSUE THREAD

**Issue by jomjol** [jomjol/AI-on-the-edge-device#1066]
@caco3 : after merging https://github.com/jomjol/AI-on-the-edge-device/pull/1065 I still cannot build:
![grafik](https://user-images.githubusercontent.com/30766535/192118130-d91edb6f-cee2-495d-9356-2d2f49e0b866.png)

The esp32-cam-master is not init (empty directory after fresh clone):
![grafik](https://user-images.githubusercontent.com/30766535/192118159-32d3e328-e4af-4f19-b4cf-e996f35a2f13.png)

submodule update has been done:
![grafik](https://user-images.githubusercontent.com/30766535/192118214-36eee887-1afd-4ae6-8e1d-281fe4198d51.png)

**Comment by caco3** [comment]
try to delete the project folder and clone the project again. dont forget to init the submodules

**Comment by jomjol** [comment]
That was the trick! - Thanks

**Comment by caco3** [comment]
no problerm.
sometimes, with complex conflicts and so this is the easiest approach.
Thanks for your openness to learn new things!
