### ISSUE TITLE
Neural Network: zero or six?

### ISSUE THREAD

**Issue by benjholl** [jomjol/AI-on-the-edge-device#107]
Thanks alot for making this great project happen, i really love it and have two units up and running!
Unfortunately, on my watermeter the zero gets interpreted as 6 quite often. not always, but i would guess around 50% of the time it will output "6" instead of "0"

regarding to the neural network this is a zero: ![0_ROI1_20210207-101635](https://user-images.githubusercontent.com/11596197/107144992-f7ba4280-693e-11eb-9582-22b10fe77058.jpg) and this is a six: ![6_ROI1_20210207-120635](https://user-images.githubusercontent.com/11596197/107144934-ab6f0280-693e-11eb-8c4d-3dd964b68a15.jpg)

Is there a instruction on how someone can train the network (or maybe even create a new network) for this system?

**Comment by jomjol** [comment]
Hallo @benjholl,

the instructions can be found in this repository: https://github.com/jomjol/neural-network-digital-counter-readout

I update the tflite-files from time to time. So if yous send me some representatives of your digits (about 2-3 per digit), I will incorporate them in the next training. This can be done quite fast, as soon as I have the complete set of images.

Best regards,
  jomjol
