### ISSUE TITLE
Build broken on rolling 

### ISSUE THREAD

**Issue by haverland** [jomjol/AI-on-the-edge-device#1072]
I've used current rolling (fresh checkout). On Mac I get now following error

(mlp) [15:08:04] [~/workspaces/GitHub/AI-on-the-edge-device] git(master) ❱❱❱ cd code; platformio run --environment esp32cam
Processing esp32cam (platform: espressif32@4.4.0; board: esp32cam; framework: espidf)
------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp32cam.html
PLATFORM: Espressif 32 (4.4.0) > AI Thinker ESP32-CAM
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
DEBUG: Current (esp-prog) External (cmsis-dap, esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES:
 - framework-espidf @ 3.40302.0 (4.3.2)
 - tool-cmake @ 3.16.4
 - tool-esptoolpy @ 1.30300.0 (3.3.0)
 - tool-ninja @ 1.9.0
 - toolchain-esp32ulp @ 1.22851.191205 (2.28.51)
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch3
Reading CMake configuration...
-- Building ESP-IDF components for target esp32
-- Configuring incomplete, errors occurred!
See also "/Users/haverland/workspaces/GitHub/AI-on-the-edge-device/code/.pio/build/esp32cam/CMakeFiles/CMakeOutput.log".

fatal: not a git repository (or any of the parent directories): .git
CMake Error at /Users/haverland/.platformio/packages/framework-espidf@3.40302.0/tools/cmake/build.cmake:191 (message):
  Failed to resolve component 'tflite-lib'.
Call Stack (most recent call first):
  /Users/haverland/.platformio/packages/framework-espidf@3.40302.0/tools/cmake/build.cmake:217 (__build_resolve_and_add_req)
  /Users/haverland/.platformio/packages/framework-espidf@3.40302.0/tools/cmake/build.cmake:218 (__build_expand_requirements)
  /Users/haverland/.platformio/packages/framework-espidf@3.40302.0/tools/cmake/build.cmake:218 (__build_expand_requirements)
  /Users/haverland/.platformio/packages/framework-espidf@3.40302.0/tools/cmake/build.cmake:441 (__build_expand_requirements)
  /Users/haverland/.platformio/packages/framework-espidf@3.40302.0/tools/cmake/project.cmake:399 (idf_build_process)
  CMakeLists.txt:13 (project)

**Comment by caco3** [comment]
you forgot do checkout the submodules (thats something new, sry).
See https://github.com/jomjol/AI-on-the-edge-device/blob/rolling/code/README.md

**Comment by haverland** [comment]
Answered
