### ISSUE TITLE
new value is added to the previous value

### ISSUE THREAD

**Issue by mad2xlc** [jomjol/AI-on-the-edge-device#1076]
First of all, the new version response much better. Thank you :)

The downside is that with the new version the new value is added to the previous value.
1500m3 becomes 3001m3 instead of 1501m3
The next value becomes 4503m3 instead of 1502m3

I upgraded from a previous version.
Maybe a clean installation would fix this.

Git-Base-Branch: master - v11.3.1 - 2022-09-17
HTML Version: 2022-09-17 14:19:59
[AI_2022-09-25.txt](https://github.com/jomjol/AI-on-the-edge-device/files/9641289/AI_2022-09-25.txt)

**Comment by jomjol** [comment]
That is totally new to me! Can you turn on the logfile and post it here?

**Comment by haverland** [comment]
Could it be the checkDigitConsistency=true? Where is an issue on the function in 11.3.1. You can set it to false until the next release.

**Comment by mad2xlc** [comment]
Have you seen the logfile in my first post? 
Btw. I saved the complete sd card for further investigation and started with fresh content. Now the problem is gone.

**Comment by aendes** [comment]
I set checkDigitConsistency=true to false and everything works like expected.

**Comment by jomjol** [comment]
ok great - meanwhile clear, that this is a bug in the software. will be removed with the next release.
