### ISSUE TITLE
"Rate too high" even though read value is correct

### ISSUE THREAD

**Issue by anverx** [jomjol/AI-on-the-edge-device#1079]
Got a new watermeter, decided to update the code to v11.3.1.
The data is interpreted correctly, but an error is generated "Rate too high"
![edge-recognition](https://user-images.githubusercontent.com/6583434/192211756-103c5a1d-57c6-4f8f-8f48-9e5f26af9a6e.jpg)
![edge-overview](https://user-images.githubusercontent.com/6583434/192211740-d5e07075-b2a2-4d5f-af8b-f02718eb257b.jpg)

where is the "8" coming from?
[AI_2022-09-26.txt](https://github.com/jomjol/AI-on-the-edge-device/files/9643748/AI_2022-09-26.txt)

**Comment by anverx** [comment]
Is this a duplicate of https://github.com/jomjol/AI-on-the-edge-device/issues/1076 ?  I can't really tell but looks similar.

**Comment by friedpa** [comment]
Do you have CheckDigitIncreaseConsistency = true. If yes, disable.

**Comment by anverx** [comment]
seems fixed.  
Maybe disable this feature by default if it doesn't work yet?
