### ISSUE TITLE
Censor passwords in logs

### ISSUE THREAD

**Issue by caco3** [jomjol/AI-on-the-edge-device#1092]
We should censor all passwords in the logs (wifi, mqtt, influxdb, ...)

**Comment by jomjol** [comment]
Why? If you have access to the serial, then you can access the password anyway. I used them frequently for debugging.
You mean because people send us the logfiles and don't delete the passwords?

**Comment by friedpa** [comment]
I think that is the case :o) Look at all the Logs, you have a nice varity of passwords people using currenttly :o)

**Comment by caco3** [comment]
People are not aware that there might be confidential information stored in there.
It would be best practice to censor it (or remove that log line at all).

Being in your house and accessing the USB log is not a real issue :)
But abusing the password and use it with our email address on public website is something else!

**Comment by jomjol** [comment]
Has been solved for the current rolling.
But in the config.ini the password is still inside.
