### ISSUE TITLE
HomeAssistant integration code sample has an error

### ISSUE THREAD

**Issue by brandstaetter** [jomjol/AI-on-the-edge-device#1096]
https://github.com/jomjol/AI-on-the-edge-device/wiki/Integration-Home-Assistent has a small error in the binary sensor value template - this always evaluates to `unknown`

it works with 

```value_template: "{%if value != 'no error' -%}ON{%-else-%}OFF{%-endif%}"```

**Comment by jomjol** [comment]
I updated the page, but cannot test.

Thanks for you input.
