### ISSUE TITLE
Mqtt probleme

### ISSUE THREAD

**Issue by domiarduino** [jomjol/AI-on-the-edge-device#110]
Hallo, 

zu allererst vielen Dank für dieses tolle Projekt. Es funktioniert alles sehr gut. Leider bekomme ich keine Daten per mqtt übertragen, obwohl ich alle Daten soweit in das configfile eingetragen habe. Haben Sie evtl eine Idee ?

Viele Grüße

**Comment by jomjol** [comment]
Hallo,

beim MQTT bin ich kein Experte. Häufiges Thema ist, dass der ESP32 nur ein Client ist, der ausschließlich an einen Broker senden kann. D.h. man muss irgendwo einen Server haben, an den man die Daten sendet. Bitte ggf. mal den Teil der config.ini posten, dann kann ich sie mit meiner funktionierenden vergleichen.

**Comment by domiarduino** [comment]
Hallo,

Ich haben einen Server laufen, den ich mit anderen clients getestet habe. Die config sieht wie folgt aus : [MQTT]
Uri = 192.168.178.134:5007
Topic = wasserz
TopicError = wasserzer
ClientID = wasser
user = mqttuser
password = pwdk

Viele Grüße

**Comment by jomjol** [comment]
Du musst vermutlich die URI leicht anders codieren (mit `mqtt://`). Meine Config ist wie folgt:

```
[MQTT]
Uri = mqtt://123.456.789.01:1883
Topic = wasserzaehler/zaehlerstand
TopicError = wasserzaehler/error
ClientID = wasser
user = USERNAME
password = PASSWORD
```

**Comment by domiarduino** [comment]
Perfekt, das war es. Vielen Dank
