### ISSUE TITLE
"Rate to high error" but already worked

### ISSUE THREAD

**Issue by freaktech** [jomjol/AI-on-the-edge-device#1101]
hi i installed this yesterday
was woking fine  und tomorrow i have this error
Rate too high - Read: 
<img width="1199" alt="image" src="https://user-images.githubusercontent.com/33237257/192694487-8cc9c6cd-f62d-45dc-8508-27299714013f.png">

what should i do or is the problem, i don't understand the message
raw data i s OK
last value is OK
what is the problem?

thank you
tom

**Comment by skynet74** [comment]
Same here. (master - v11.3.0 - 2022-09-16)

raw data i s OK
last value is OK
But no value
<img width="989" alt="Bildschirmfoto 2022-09-28 um 07 35 18" src="https://user-images.githubusercontent.com/13029404/192696043-6a77e6e8-9282-4d70-a1b2-f31344caf60f.png">




[](url)

**Comment by friedpa** [comment]
ere is a bug currently in the SW. You have to set CheckDigitIncreaseConsistency = false

**Comment by freaktech** [comment]
this is my setting ?!?
![image](https://user-images.githubusercontent.com/33237257/192700416-87d22e63-5ca7-455f-be3e-d5cdcd29aef4.png)

**Comment by freaktech** [comment]
with this setting its the same 

![image](https://user-images.githubusercontent.com/33237257/192701159-7c62c3b1-7ef7-4de3-9f74-f0fc135eddbb.png)

**Comment by jomjol** [comment]
@freaktech : you have a different kind of problem. For some reason the last correct previous stored value is: 34513.977.
For some reason it was not updated (either a sudden high usage or false readings for some time) and now the new value is too large, as you have a MaxRate checkin enabled.
You can increase the maximum allowed rate change to a higher value (about 0.5 absolute) to accept the higher jump.

**Comment by freaktech** [comment]
thank you

its working again !
