### ISSUE TITLE
Problem with last 2-3 analog digits

### ISSUE THREAD

**Issue by ranax404** [jomjol/AI-on-the-edge-device#1109]
Hi there,

thanks for this great project. After reading and trying a lot to find a good fixture, the recognition is now nearly perfect.
But I have a problem with the rotating analog digits: I think the alignment is as good as recommended in the wiki, but it seems, that the afterpoint (angle detection) is sometimes faulty, especially for the last to digits. My example picture recognizes the value 116.9918, but the correct value is 116.9917. The recognition page shows more details. Is there any problem with my analog ROI alignment?
PS: I started logging the images now, if this could help for training data.

**Version**
latest v11.3.1

**Expected behavior**
better recognition of last 2-3 analog digits -> [1st] 9.9 seems good, [2nd] 9.7 should be 9.1, [3rd] 1.8 seems good, [4th] 8.8 should be 7.8 

**Screenshots**
![Bildschirmfoto 2022-09-29 um 16 48 21](https://user-images.githubusercontent.com/55350575/193068690-dc1213a0-e499-4bf1-a41a-59e63dcd32b9.png)

**Additional context**
n/a

**Comment by haverland** [comment]
Which models do you use?

**Comment by ranax404** [comment]
[Digits]
Model = /config/dig-class11_1411_s2_q.tflite

[Analog]
Model = /config/ana-cont_1101_s2_q.tflite

**Comment by haverland** [comment]
For digits you can try dig-class100-0130_s2_q.tflite or dig-cont_0570_s3.tflite. The models have not "NaN" values.

For analog could you try ana-class100_0130_s1_q.tflite

**Comment by haverland** [comment]
> EDIT: i think, i'm using the wrong analog class, right? but what is the difference between those two 100 classes?
The difference are in the models. jomol prefers cont (a sinus / cosinus) output. I prefer the classification 100 outputs of the model 0.0, 0.1 ... 9.9 = 100. 
What's the best? Try it for yourself.

**Comment by ranax404** [comment]
I have the following classes available and checked the first one now:
![Bildschirmfoto 2022-09-29 um 20 19 57](https://user-images.githubusercontent.com/55350575/193112607-6b6066c7-5500-40a5-afcc-7c13c423d26e.png)

This seems to be fine, also the "extended resolution" option returns good results.

Thanks for your help.

**Comment by haverland** [comment]
Sorry. I've copied from current master. Since a few minutes the new release is out.

**Comment by ranax404** [comment]
I'll try the new 12.x release soon.
