### ISSUE TITLE
Recognition works, but the raw value is wrong

### ISSUE THREAD

**Issue by SilRo991** [jomjol/AI-on-the-edge-device#1110]
**Describe the bug**
After updating to the latest version, I get the wrong raw value.
The recognition works perfectly. I didn't find anything on the wiki to solve the problem myself.
I played a lot with the focus of the camera and the alignment. I don't think that's the problem though, as the recognition works.

**Version**
11.3.1
*Updated to Version: Branch: 'HEAD', Tag: 'v12.0.1', Revision: dfe2c46 - same behavior*

**Expected behavior**
The value should be the correct one, as it is also output by the recognition.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/34778444/193086467-d7fdf243-aec3-474a-b322-997f1a78aed2.png)
![grafik](https://user-images.githubusercontent.com/34778444/193086519-11a3013c-6efc-4594-aa7a-1df9eea267e4.png)

**Comment by Plawasan** [comment]
Got a similar issue on 12.0.1 - good recognition, wrong value.. looks like the algo still needs some finetuning:

Correct value should be 170.05287 not 170.05387

![image](https://user-images.githubusercontent.com/73796046/193107129-4a2bcce3-61f4-40f8-85dd-83cfc43af4df.png)

![image](https://user-images.githubusercontent.com/73796046/193107245-b8141662-8d56-4e4e-8321-43f5b5f99fec.png)

**Comment by haverland** [comment]
Look at ROI configuration. If the ROIs in height not correctly configured, it recognize 2.0 but is 1.8. 

![](https://github.com/haverland/collectmeterdigits/blob/main/images/ROI-setup.png)

**Comment by haverland** [comment]
@Plawasan  your last digit should have the height like the digit before and all other digits should be the height like in picture described.

**Comment by Plawasan** [comment]
> @Plawasan your last digit should have the height like the digit before and all other digits should be the height like in picture described.
> 
> ![193107245-b8141662-8d56-4e4e-8321-43f5b5f99fec](https://user-images.githubusercontent.com/412645/193109893-a7dacb45-ec82-44d1-94d3-d11e2f93d16e.png)

I hear you, but recognition is not the issue here, the algorithm is...

**Comment by haverland** [comment]
@SilRo991 if you use a class100 or cont model for digits your issue is fixed. Depends on the post-processing of class11.

**Comment by haverland** [comment]
> > @Plawasan your last digit should have the height like the digit before and all other digits should be the height like in picture described.
> 
> I hear you, but recognition is not the issue here, the algorithm is... however I have updated the ROIs to match the recommended settings, no difference in output:
> 
Class100 and cont models have the same post-processing, but class11 it's own.

**Comment by Plawasan** [comment]
> > > @Plawasan your last digit should have the height like the digit before and all other digits should be the height like in picture described.
> > 
> > 
> > I hear you, but recognition is not the issue here, the algorithm is... however I have updated the ROIs to match the recommended settings, no difference in output:
> 
> Class100 and cont models have the same post-processing, but class11 it's own.

I've changed the config to use the class 11 model, still the same exact thing
```
[Digits]
Model = /config/dig-class11_1411_s2_q.tflite
```

**Comment by haverland** [comment]
> > > > @Plawasan your last digit should have the height like the digit before and all other digits should be the height like in picture described.
> > > 
> > > 
> > > I hear you, but recognition is not the issue here, the algorithm is... however I have updated the ROIs to match the recommended settings, no difference in output:
> > 
> > 
> > Class100 and cont models have the same post-processing, but class11 it's own.
> 
> I've changed the config to use the class 11 model, still the same exact thing
> 
> ```
> [Digits]
> Model = /config/dig-class11_1411_s2_q.tflite
> ```

A class11 will recognize "3". The problem here is, only > 9.x on the analog a special post-processing will be used and calculate here a 3(-1)=2. Here is the difference between the pointer and the first digit our biggest problem.

**Comment by SilRo991** [comment]
> @SilRo991 if you use a class100 or cont model for digits your issue is fixed. Depends on the post-processing of class11.

@haverland I forgot to say that I also checked [ROI Configuration](https://github.com/jomjol/AI-on-the-edge-device/wiki/ROI-Configuration) and [Choosing the Model](https://github.com/jomjol/AI-on-the-edge-device/wiki/Choosing-the-Model). I thried all but it is always the same raw value. I also did a fresh installation of v11.3.1 and restored my config. Checked the differences in default config settings and mine. My config is basically default except the positioning parameters.

But I am not really sure what it has to do with the ROI or tflite as the recognition page show us the right value.

**Comment by Duese123** [comment]
I have exactly the same...
The numbers are corrctly recognized but it shows one too less.
![Screenshot_20221003-162011_Chrome](https://user-images.githubusercontent.com/95966691/193601856-471381f6-52ff-43f3-84e0-8ac57bf5707e.jpg)

**Comment by jomjol** [comment]
Well, in principle you are right. But you see here one of the current challanges. Although you 0.1 counter is clearly higher than 2 already, the last digit is only at ~6.7.
The algo is teached in that way, that if the 0.1 is outside a tolerance band (here +/-0.2), than the read value is taking for real (here still a "6". If I increase the tolerance band to +/-0.3, it would work here, but not for other counters.

That is still challange for us to fine tune the settings and make them accesible in an understandable way to the user, so he can adjust to the specific model.

That will take some time, as the development here is very time consuming.

**Comment by pos-ei-don** [comment]
My Suggestion would be to let us users define a value which should gec calculated to the detected value.
I have on Meter with on numbrr which stays to High and another which stays too low. I'd love to add +0.4 to the first one and - 0.3 to the last one.

**Comment by Duese123** [comment]
@jomjol you are right... now it is 6.8 and the new counter is valid... thats for me ok...

Thanks for this Projekt It is very stable and works reliable

**Comment by haverland** [comment]
You Van reduce the height on Top of the digits. The ROIs are over the digit window. With newer models Dig-Class100 or dig-cont its essentially to set the ROIs close to the top and bottom of the digit window, to get correct results.

**Comment by brandstaetter** [comment]
Possibly stupid question (have not looked at the code yet) but would the following process make sense?

1. Recognition of all values
2. start at "lowest" digit, work backwards and do sanity check, not only using the tolerance band....

e.g.: working on a number made up of: `dig1 dig2 dig3 ana1 ana2 ana3`

dig1 -> recognized as 2.2
dig2 -> recognized as 4.5
dig3 -> recognized as 5.9
ana1 -> recognized as 9.4
ana2 -> recognized as 3.8
ana3 -> recognized as 8.6

in my experience this would yield a raw valui of 246.938 instead of the 275.938 it should be. This regularely leads to phases of error state, until the counter rolls over and it's not suddenly 1 m³ more than before.

I would have expected that the translation from recognition to raw value would be something like...

ana3: 8.6, tolerance 0.2, must be 8.
ana2: 3.8 tolerance 0.2, might be 3.6 to 4. but ana3 tells me, this should be 3.8 -> 3
ana1: 9.4 tolerance 0.2, with the knowledge of ana2 I can correct it as 9.3 -> 9
dig3: 5.9, tolerance 0.2, might be 5.7 to 6.1; with the knowledge ana1=9 I can pin it at 5.9 -> 5
etc...

might also be possible to go the other direction as well as yet another sanity check in the end

am I completely off or is that something that can be implemented to vastly improve accuracy?

**Comment by haverland** [comment]
> in my experience this would yield a raw valui of 246.938 instead of the 275.938 it should be. This regularely leads to 
dig3 = 5.9
ana1 =    9.4
In this case the dig3 is not 6, the ana1 is not over 0. So it is 245.938 the correct result, I think.

But I found the tolerance of 0.2 is not useful on the transition ana->dig. The difference between dig and ana is often very much (see @Duese123  dig=6.7, ana=2.2 => value=7.2)

**Comment by haverland** [comment]
> Got a similar issue on 12.0.1 - good recognition, wrong value.. looks like the algo still needs some finetuning:
> 
> Correct value should be 170.05287 not 170.05387
> 
> ![image](https://user-images.githubusercontent.com/73796046/193107129-4a2bcce3-61f4-40f8-85dd-83cfc43af4df.png)
> 
> ![image](https://user-images.githubusercontent.com/73796046/193107245-b8141662-8d56-4e4e-8321-43f5b5f99fec.png)

@Plawasan : I'm not really shure here. Could you give a screenshot when the analog pointer is between 7-8. And a screenshot when the pointer ist between 9-0?

**Comment by Plawasan** [comment]
> @Plawasan : I'm not really shure here. Could you give a screenshot when the analog pointer is between 7-8. And a screenshot when the pointer ist between 9-0?

Here's 7-8 on the analog counter, all looks good, will post 9-0 when I catch it

![image](https://user-images.githubusercontent.com/73796046/196277694-d1da9f4b-ebc9-471b-b8aa-a058c7dbe9ee.png)

**Comment by haverland** [comment]
> > Got a similar issue on 12.0.1 - good recognition, wrong value.. looks like the algo still needs some finetuning:
> > Correct value should be 170.05287 not 170.05387
> > ![image](https://user-images.githubusercontent.com/73796046/193107129-4a2bcce3-61f4-40f8-85dd-83cfc43af4df.png)
> > ![image](https://user-images.githubusercontent.com/73796046/193107245-b8141662-8d56-4e4e-8321-43f5b5f99fec.png)
> 
> @Plawasan : I'm not really shure here. Could you give a screenshot when the analog pointer is between 7-8. And a screenshot when the pointer ist between 9-0?

Thx. Looks like the last digit rolling with the analog pointer parallel. Not like the other digits

**Comment by haverland** [comment]
@Plawasan: In next release you can set AnalogDigitalTransitionStart. Your meters should set here to 7.6-7.7.

All others can use the defaults.
