### ISSUE TITLE
Update to 12.0.1 - Set Previous Value

### ISSUE THREAD

**Issue by friedpa** [jomjol/AI-on-the-edge-device#1116]
After switching to 12.0.1 I had to adjust the "Previous Value"
I inserted the value 20760.56 clicked "set value" and afterwards the "Overview" tab. The value in "Previous Value" was set to 20760.560547, which ended up in a "neg. Rate - Read""
![grafik](https://user-images.githubusercontent.com/42890695/193124871-054b099a-f06c-45fc-a0f3-abbd812e00c0.png)
Otherwise everything works good with the new release. Congratulation to the Developer! Well done!

**Comment by jomjol** [comment]
Please test current rolling: https://github.com/jomjol/AI-on-the-edge-device/actions/runs/3156575254

**Comment by friedpa** [comment]
Hi Josef,
when ich den Link folge bekomme ich folgende Webseite:

![grafik](https://user-images.githubusercontent.com/42890695/193221996-c4ef9226-1ef4-486f-98b4-fc586a2ad2e4.png)

Was muss ich nun installieren? :o)
Liebe Grüße Paul

**Comment by jomjol** [comment]
Du kannst die erste Datei (firmware__(extract...)) runterladen. Darin findest du eine firmware_XXXX.bin.
Diese kannst du zum Update nehmen.

ACHTUNG: hier musst du die Datei noch einmalig in `firmware.bin` umbennen, da es noch einen Bug mit anders benannten firmware_xxx.bin gab. Ist dann aber behoben.

**Comment by friedpa** [comment]
Ok. danke!

**Comment by friedpa** [comment]
Works. Thanks!

**Comment by friedpa** [comment]
@jomjol: Das gleiche Verhalten trat heute wieder auf:

![grafik](https://user-images.githubusercontent.com/42890695/195682654-9bf8e019-3475-4d54-9cdf-d8b365352c40.png)

Previous Value wieder eine Stelle mehr (5) und Verleich mit RAW Value ergibt wieder "Neg. RAte - Read:
