### ISSUE TITLE
N anstelle der gelesenen Zahl

### ISSUE THREAD

**Issue by domiarduino** [jomjol/AI-on-the-edge-device#112]
Hallo,

ich bekomme ständig für das erste und dritte Digit Fenster ein N an stelle der gelesenen Zahl. Z.b. der Zählerstand ist 345 und ich bekomme den Wert N4N angezeigt und auch an MQTT übergeben. Woran könnte das liegen?

Viele Grüße

**Comment by aendes** [comment]
Hallo,

schau mal da: https://github.com/jomjol/neural-network-digital-counter-readout

Das bedeutet, dass die Zahl nicht erkannt wurde. Falscher Focus, Falsches Alignment oder weil die Zahl gerade "am Drehen" ist sind die Hauptgründe dafür.

**Comment by jomjol** [comment]
@domiarduino ,
genau wie @aendes sagt. Zusätzlich könnte es sein, dass deine Ziffern komplett anders sind, dann müsste man die noch teachen. Post mal ein Bild, dann kann ich genaueres sagen.
Gruß,
  jomjol
