### ISSUE TITLE
Recognition does not match reference

### ISSUE THREAD

**Issue by rs200x** [jomjol/AI-on-the-edge-device#1135]
### The Problem

Hi,
since some days I'm trying to get a working configuration.
But I always get to the same point which ends up that the recognition image does not match the configured reference image.
I have the impression that the defined rotation angle is not applied correctly.
![watermeter_full](https://user-images.githubusercontent.com/39993567/194106127-17362465-da55-4d51-a77e-eb3d5689c662.png)

I started with version 10.6, but its the same for 11 & 12
Am I doing something wrong?

### Version

12.0.1

### Additional Context

[MakeImage]
LogImageLocation = /log/source
WaitBeforeTakingPicture = 5
LogfileRetentionInDays = 15
Brightness = -2
Contrast = 2
Saturation = -2
LEDIntensity = 2
ImageQuality = 12
ImageSize = VGA
FixedExposure = true

[Alignment]
InitialRotate = 343
InitialMirror = false
SearchFieldX = 20
SearchFieldY = 20
AlignmentAlgo = default
FlipImageSize = false
/config/ref0.jpg 318 3
/config/ref1.jpg 208 88

[Digits]
Model = /config/dig-cont_0570_s3.tflite
;CNNGoodThreshold = 
;LogImageLocation = /log/digit
;LogfileRetentionInDays = 3
main.dig1 216 27 24 42 false
main.dig2 241 28 25 42 false
main.dig3 268 30 22 37 false
main.dig4 291 28 26 43 false
main.dig5 316 27 27 44 false
sub.sub1 346 29 25 42 false
sub.sub2 369 26 28 47 false
sub.sub3 400 27 29 47 false

[Analog]
Model = /config/ana-cont_11.3.0_s2.tflite
;LogImageLocation = /log/analog
;LogfileRetentionInDays = 3
main.ana1 384 92 108 108 false

[PostProcessing]
;main.DecimalShift = 0
sub.DecimalShift = 0
PreValueUse = true
PreValueAgeStartup = 720
AllowNegativeRates = true
;main.MaxRateValue = 0.05
;sub.MaxRateValue = 
main.MaxRateType = AbsoluteChange
;sub.MaxRateType = 
main.ExtendedResolution = false
;sub.ExtendedResolution = 
main.IgnoreLeadingNaN = false
;sub.IgnoreLeadingNaN = 
ErrorMessage = true
CheckDigitIncreaseConsistency = false

[MQTT]
Uri = mqtt://192.168.0.155:1883
MainTopic = wassermeter
;ClientID = wasser
;user = USERNAME
;password = PASSWORD
SetRetainFlag = false

;[InfluxDB]
;Uri = 
;Database = 
;Measurement = 
;user = 
;password = 

;[GPIO]
;IO0 = input disabled 10 false false 
;IO1 = input disabled 10 false false 
;IO3 = input disabled 10 false false 
;IO4 = built-in-led disabled 10 false false 
;IO12 = input-pullup disabled 10 false false 
;IO13 = input-pullup disabled 10 false false 
LEDType = WS2812
LEDNumbers = 2
LEDColor = 150 150 150

[AutoTimer]
AutoStart = true
Intervall = 5

[Debug]
Logfile = true
LogfileRetentionInDays = 3

[System]
TimeZone = CET-1CEST,M3.5.0,M10.5.0/3
;TimeServer = undefined
;AutoAdjustSummertime = false
;Hostname = undefined
SetupMode = false

**Comment by jomjol** [comment]
Most propably the reference structure is not identified correctly. Please try to use one with a higher contrast or but a sticker with high constrast on the meter and use this for recognition.

**Comment by epestela** [comment]
Has the same issue, fixed the references, and it's solved now :D

**Comment by rs200x** [comment]
Sorry for the late response.
I also got it working after some tries.
Had to put some tape on to reduce the reflection and also some stickers for the references.
