### ISSUE TITLE
Erkennung bei Digitaler Anzeige

### ISSUE THREAD

**Issue by jonnycastaway** [jomjol/AI-on-the-edge-device#114]
Guten Abend,
ich habe einen digitalen Wasserzähler bei dem leider an dritter Stelle eine 3 immer als 9 gewertet wird.
Sind denn rein digitale Zahlen (LCD) trainiert? Schärfe, Beleuchtung und Kontrast find ich eigentlich gut.
Muss ich da noch an Einstellungen drehen?

![Wasserzaehler](https://user-images.githubusercontent.com/25009091/107863404-7ab62e00-6e54-11eb-9508-3ec6147208a2.png)

**Comment by jomjol** [comment]
Hallo,
digitale Ziffern sind zwar trainiert, aber die sehen etwas anders aus, wie deine:
![digit3_2020-04-17_18-51-09](https://user-images.githubusercontent.com/30766535/107873741-f1831380-6eb4-11eb-96af-df2f2bf56482.jpg) ![digit3_2020-03-22_11-01-07](https://user-images.githubusercontent.com/30766535/107873850-d664d380-6eb5-11eb-8fe9-0f5d01b88e6c.jpg)![digit1_2020-04-17_15-13-51](https://user-images.githubusercontent.com/30766535/107873842-cc42d500-6eb5-11eb-9c52-2f894cc9eae1.jpg)![digit3_2020-03-23_20-46-42](https://user-images.githubusercontent.com/30766535/107873743-f8118b00-6eb4-11eb-84b0-2704111c6df9.jpg)

Vor allem sind die Ziffern deutlich dünner. Zum Ersten würde ich empfehlen, etwas mehr Rand um die Ziffern zu lassen, insbesondere in der Breite. Wenn sich die ROIs überlappen, ist es nicht schlimm. Beipspiel:
![grafik](https://user-images.githubusercontent.com/30766535/107873929-4e32fe00-6eb6-11eb-8c34-fbfc29f28a2e.png)

Wenn das die Erkennung nicht verbessert, kann ich anbieten, deine Ziffern mit ins nächste Training mit aufzunehmen. Dazu einfach von jeder Ziffer 2-3 Beispielbilder sammeln und mir schicken.

Gruß,
  jomjol

**Comment by jonnycastaway** [comment]
Hallo nochmal,
nach Vergrößerung der Ränder, der Tipp das sich die ROIs ruhig überlappen können war die Lösung, funktioniert die Erkennung nun perfekt. Vielen Dank für die schnelle Hilfe und das prima Projekt.

**Comment by jonnycastaway** [comment]
Kurzer Nachtrag zu Info:
Auch nach mehreren Tagen läuft die Erkennung einwandfrei!
Vielen Dank noch einmal.

**Comment by jomjol** [comment]
@Wildshunter: vielleicht maximal 2 Umdrehungen. Richtung ist "reindrehen" - wenn ich mich richtig erinnere

**Comment by Kasper027** [comment]
@Wildshunter Echt Cool was du da hinbekommen hast.
Leider bekomme ich es schon gar nicht hin. Bei mir spiegelt es sich ganz extrem.  Auch die LED. Leider bringt es mir gerade garnichts, die LEDIntensity herunter zu setzten. Die LED bleibt immer gleich hell meiner Meinung. Kannst du auch mal messen, wie weit du von der Wasseruhr zur Kamera weg bist?

Viele Grüße
Kasper027

**Comment by JotWeDe01** [comment]
Ich schreibe hier einfach mal rein, auch wenn es schon länger her ist, und vermutlich alle Projekte schon umgesetzt sind.
Um den Fokus zu näheren Objekten zu bekommen muss die Linse **herausgedreht** werden ! Bei einem Abstand von ca. 7 cm zu meinem Gaszähler waren ca. 360° (1*rum) nötig. Es benötigt eine Menge Mut und auch Kraft nach dem Entfernen des Fixierklebers aus Shenzhen (das ist der gute) das Objektiv zu drehen. Sorry wollte hier nicht rumspammen, habe aber vor ca. einer Woche auch danach gesucht. Guten Rutsch in die Runde.

**Comment by Timon321** [comment]
Ich muss diesen Thread leider nochmal aufleben lassen.

Bei mir erkennt er jedes mal aus einer 1 eine 7. Ich habe auch schon mit den Größen der Erkennungsfelder gespielt. Lässt sich leider nichts machen. Gibts hier einen Tipp?

![image](https://github.com/jomjol/AI-on-the-edge-device/assets/7792233/ce6376c9-c9fd-4255-b836-be47d3c879f5)

**Comment by Reinhard-M** [comment]
Das "1 wird als 7" erkannt Problem habe ich hier schon häufiger gehört. Aus meiner persönlichen Sicht ist es immer wieder ein Beleuchtungs Thema, meistens auf die LED der Cam zurück zu führen (achte bitte auf die weiße horizontale Linie über der 1 in deinem Bild). Ich habe es bei mir über "indirekte Beleuchtung" in den Griff bekommen. Meine LED leuchtet auf eine schräge weiße Fläche nach oben. Dort ist wiederum eine weiße Fläche im 90° Winkel zur Kamera. Das Licht kommt somit sehr diffus von oben und erzeugt weniger harte Schatten.
