### ISSUE TITLE
Ist es möglich WLAN 802.11k und 802.11v zu implementieren?

### ISSUE THREAD

**Issue by sammykd** [jomjol/AI-on-the-edge-device#1141]
Super Projekt, habe es schon bei meinem Gaszähler und Wasseruhr umgesetzt.
Vielen dank dafür.
Aber es funktioniert nicht sauber mit meinem MESH System. Es fehlt die 802.11v und 802.11k WIFI implementierung. Sollte nach den Informationen, die hier beschrieben sind, möglich sein. Sofern Platz auf dem ESP System ist.  
`https://espressif-docs.readthedocs-hosted.com/projects/espressif-esp-faq/en/latest/software-framework/wifi.html` 
Unter Punkt 42 und 43 grob beschrieben.
Habe selber aber leider keine Ahnung zu der Programierung von ESP32. 
Ich habe ein Mesh System und die ESP's melden sich immer am schlechtesten AP an, meist die FB 10 Meter weg, obwohl der naheste AP direkt 3 Meter entfernt ist, Es handelt sich hier um AVM FRITZ MESH. AVM schreibt, ohne 802.11v und 802.11k kann man nur eine eigen SSID auf den AP bringen für diese Clients, somit funktioniert aber MESH für alle anderen Clients nicht mehr.
Hier der Hinweis von AVM 
`https://avm.de/service/wissensdatenbank/dok/FRITZ-Box-7590/3593_WLAN-Gerat-verbindet-sich-nicht-mit-optimalem-Mesh-Repeater/`
Vieleicht ist ja da was möglich?

Gruß Dietmar

**Comment by RasputinBerry** [comment]
... ich schließe mich dem Wunsch von sammykd an ... Bei mir ist es ähnlich ... der Repeater hat einen Abstand von Luftlinie 1m aber trotzdem ist der Zählersensor im Netz vom Gartenhaus, ca. 25m entfernt.
Ansonsten KLASSE Projekt !!!

**Comment by caco3** [comment]
Ich habe es mir mal angeschaut und versucht, das in der FAQ verlinkte Beispiel zum Laufen zu kriegen.
Das Beispiel will eine Date inkludieren, welche es offenbar mit Espressif SDK nicht gibt: [esp_wnm.h](https://github.com/espressif/ESP8266_RTOS_SDK/blob/master/examples/wifi/roaming/main/roaming_example.c#L7)

Und ich finde im Internet nichts dazu! Sollange sich nicht mal das offizielle Beispiel bauen lässt, werde ich da nicht weiter Zeit investieren!

**Comment by jomjol** [comment]
Ich habe das Feature gerade in der aktuellen Rolling implementiert: https://github.com/jomjol/AI-on-the-edge-device/pull/1671
