### ISSUE TITLE
Improve MQTT default values (eg. ClientID)

### ISSUE THREAD

**Issue by caco3** [jomjol/AI-on-the-edge-device#1146]
They are currently set to "wasserzaehler" resp. "wasser"
See https://github.com/jomjol/AI-on-the-edge-device/discussions/1145

**Comment by ozett** [comment]
show mqtt status (also influxdb) on info-page. 
when they are configured...

**Comment by caco3** [comment]
ClientID is fixed  in https://github.com/jomjol/AI-on-the-edge-device/pull/1232

@ozett i added https://github.com/jomjol/AI-on-the-edge-device/issues/1235 for your requests, but it is not easy to implement and has low prority for now.
