### ISSUE TITLE
Lats Valid Value

### ISSUE THREAD

**Issue by firesgc** [jomjol/AI-on-the-edge-device#1149]
Hello!

is it possible to return the last valid value in the REST Api when the detection fails? At the moment it's just an empty string.
If you don't want to break compatibility, maybe you could add a new field called "LastValidValue"?

Thanks a lot!

current return value:
{
"main":
  {
    "value": "",
    "raw": "20148.N0",
    "error": "Neg. Rate - Read:  - Raw: 20148.N0 - Pre: 20148.46 ",
    "rate": "",
    "timestamp": "2022-10-08T14:31:32"
  }
}

**Comment by caco3** [comment]
isn't "Pre" what you are looking for?
