### ISSUE TITLE
RAW Value ist korrekt, aber Checked value und Corrected value sind falsch

### ISSUE THREAD

**Issue by domiarduino** [jomjol/AI-on-the-edge-device#115]
Hallo,

ich bekomme relativ gute RAW Value Werte die zum Zählerstand passen. Leider sind die Checked und Corrected value werte immer abweichend und falsch. Z.B. Zählerstand ist 349.7087 RAW Value 349.7087, Corrected und Checked Value = 949.5305. woran kann das liegen?

Viele Grüße

Dominique

**Comment by jomjol** [comment]
Dein Prevalue stimmt nicht. Irgendwann wurde aufgrund eines fehlerhaften Wertes ein viel zu großer Wert gesetzt. Vermutlich hast du im ConsistencyCheck die negative Raten verboten. D.h. wenn du einmal einen zu großen Wert hast, gibt es keinen Weg zurück. Du musst:
1. per SetPrevalue den aktuell korrekten Ablesewert setzen
2. In der Konfiguration MaxRateValue aktivieren, damit werden so große Sprünge ignoriert oder AllowNegativeRates erlauben, dann springt er auch wieder zurück.

Gruß,
  jomjol
