### ISSUE TITLE
add LastValidValue to JSON

### ISSUE THREAD

**Issue by caco3** [jomjol/AI-on-the-edge-device#1154]
see https://github.com/jomjol/AI-on-the-edge-device/discussions/1150#discussioncomment-3829443

**Comment by jomjol** [comment]
done - see last rolling

**Comment by Turbo87** [comment]
for reference: https://github.com/jomjol/AI-on-the-edge-device/pull/1158 is the PR that implemented it :)

**Comment by firesgc** [comment]
I think it got removed with a merge by accident. At least I don't see it anymore.

**Comment by caco3** [comment]
I added it again, can you have a look on https://github.com/jomjol/AI-on-the-edge-device/actions/workflows/build.yaml?query=branch%3Aextend-mqtt-json ?

**Comment by firesgc** [comment]
The value "Pre" is no longer present in json (http://url/json)
Please check "ClassFlowPostProcessing::GetJSON()" at ~Ln58.
