### ISSUE TITLE
Feature Request: Zählereingang für Hall-Sensor für z.B. Gaszähler

### ISSUE THREAD

**Issue by gon0** [jomjol/AI-on-the-edge-device#116]
Hallo jomjol,

ich habe einen Verbesserungsvorschlag, der eher offtopic ist. Falls dies nicht vorgesehen oder nicht machbar ist, schließe dieses Ticket einfach.

Die Idee: Wahrscheinlich haben einige Personen den Wasserzähler im Keller und in der Nähe auch einen Gaszähler (wie z.B. hier: https://github.com/jomjol/AI-on-the-edge-device/issues/101). Ein einziger Eingang an der ESP32-CAM-Platine würde reichen, um einen Hallsensor anzuschließen, der am Gaszähler befestigt wird. Einige Gaszähler haben einen Magneten auf der "6" des schnellsten Zählerrades. Mir persönlich würde reichen, wenn jeder Impuls einfach einheitenlos über MQTT weitergeleitet wird.

Viele Grüße,
gon0

**Comment by jomjol** [comment]
Hi @gon0,
technisch würde das gehen, es sind noch 2 GPIOs verfügbar. Dazu müsste man aber einiges am Code ändern / ergänzen. Da ich der Programmierer daran bin, habe ich momentan keine Zeit dazu. Wenn du es versuchen willst, kann ich dir gerne einen Einblick in die Logik geben und du könntest das übernehmen.
Beste Grüße,
  jomjol

P.S.: ich schließe das Ticket erstmal.
