### ISSUE TITLE
Platformio vs Arduino IDE

### ISSUE THREAD

**Issue by middelbh** [jomjol/AI-on-the-edge-device#117]
Hi, I am very interested in your system, but do not have experience with Platformio, just with Arduino IDE. Please could you advise me how to use Arduino to setup the system? I would be very happy!!
Or is any explanation how to setup Platformio for this system available?

Excuse my stupid question!!

Hans

**Comment by aendes** [comment]
Hello Hans,

have a look at https://github.com/jomjol/AI-on-the-edge-device/wiki/Installation

This part is important for you:
esptool erase_flash
esptool write_flash 0x01000 bootloader.bin 0x08000 partitions.bin 0x10000 firmware.bin

Andreas

**Comment by middelbh** [comment]
Thanks for your superfast reaction! I am going to try!!!!

**Comment by jomjol** [comment]
@middelbh 
There is no version, that can be compiled with Arduino IDE. The project is just too complex in the current configuration.
With the explantion from @aendes you can flash it to the ESP32. If you want to compile it by yourself, there is a short explanation available, how to install the environment: https://github.com/jomjol/AI-on-the-edge-device/wiki/Build-Instructions

Best regards,
  jomjol
