### ISSUE TITLE
Quality difference between reference and image?

### ISSUE THREAD

**Issue by jdeath** [jomjol/AI-on-the-edge-device#1175]
### The Problem

The quality of the taken image (even with quality 0) is much worse than reference. This makes recognizing my digits harder as the contrast is worse.
Ref:
![ref_small](https://user-images.githubusercontent.com/17914369/195961694-4ce80e63-62b5-4abc-8a4b-a550ed4ad860.png)
Take Image:
![alg_small](https://user-images.githubusercontent.com/17914369/195961696-813233fc-3c22-4260-a095-ab1acd789a35.jpg)

I will keep playing with lighting to improve contrast

### Version

v12.0.1

**Comment by jdeath** [comment]
Still true, but got digits recognized with better lighting.

**Comment by haverland** [comment]
The camera focus could be better.
