### ISSUE TITLE
MQTT Zählerstand bei ReadError

### ISSUE THREAD

**Issue by challo2018** [jomjol/AI-on-the-edge-device#118]
Hi, vielen dank für die super Arbeit! Grundsätzlich funktioniert alles super und ich bin sehr begeistert.
Ich lese über MQTT den "wasserzaehler/zaehlerstand" ein und verarbeite diesen weiter.
Wenn jetzt ein Teil als NaN erkannt wird, wird das Topic "wasserzaehler/error" verwendet. Hier wird auch der "richtige" aktuelle Stand des Zählers mitgesendet.
Bei der weiterverabeitung ist es bei dieser Variante allerdings notwendig "normal" das Topic "zaelerstand" zu verwenden und sobald etwas im topic "error" stehet den Zählerstand aus dem Text (z.b. "Rate too high - Returned old value - read value: 290.6121" ) zu parsen.
Wäre es möglich, dass dieser Wert dann auch im Topic "zaelerstand" gesendet wird?

Vielen Dank!

**Comment by jomjol** [comment]
Ich habe das Problem noch nicht verstanden. Wenn du ein "N" hast, sollte eigentlich mit "UsePreValue" dieses durch den Wert vom letzten mal ersetzt werden und gar keine Fehlermeldung erscheinen. Hast du das aktiviert?

**Comment by challo2018** [comment]
![2021-02-22_19h17_19](https://user-images.githubusercontent.com/42739411/108751533-a3b87c00-7542-11eb-91c5-d08cb471b191.png)

Im Anhang habe ich die beiden MQTT Topics. Der Wert der im Error Topic steht stimmt. Hier wird N durch die richtige Ziffer aus dem PreValue ersetzt. Aber es wird nur im Error Topic übertragen nicht im "normalen"

**Comment by jomjol** [comment]
Dein Problem ist der Rate-Parameter. Die Fehlermeldung "Rate too high" zeigt, dass die Differenz zwischen deinem alten Wert - gespeichert als PreValue und dem jetzigen zu groß ist. Entweder du musst mal den PreValue updaten oder im Postprocessing den Parameter "MaxRateValue" deaktivieren.

**Comment by challo2018** [comment]
Okay, daran habe ich nicht gedacht. Hab den PreValue jetzt auf 290.6575 gesetzt. Jetzt stimmt erstmal der Wert. Mal schauen wie es ist wenn ich jetzt nochmal wasser verbrauche. Vielen Dank für deine Hilfe!
--



![2021-02-22_19h57_05](https://user-images.githubusercontent.com/42739411/108755946-314a9a80-7548-11eb-983b-5341ed3e7145.png)
