### ISSUE TITLE
What about a Webinstaller?

### ISSUE THREAD

**Issue by helllth** [jomjol/AI-on-the-edge-device#1180]
### Wouldn't it be cool to lower the hassle of the initial installation with a webinstaller?  

<img width="1044" alt="Screenshot 2022-10-16 at 12 10 35" src="https://user-images.githubusercontent.com/837211/196029675-b055c874-6a80-40a6-85a1-f6fdcf25f887.png">

I forked the repo to https://github.com/helllth/AI-on-the-edge-device and added a `gh_pages` branch to publish a slightly changed version of the `Readme.md `on https://helllth.github.io/AI-on-the-edge-device/.

Couldn't make a pull request though because there is no `gh_pages` branch in the current repo. (Therefore this issue).

Hope you'll like the idea :wink:

### Version

any

### Expected Behavior

You will find the Install Button on https://helllth.github.io/AI-on-the-edge-device/index.html#install below the **Download** section.

You'll just have to connect your device with an USB cable to your computer and click the button:

![Screen Recording 2022-10-16 at 11 51 49](https://user-images.githubusercontent.com/837211/196029819-19a91530-e434-469c-a6e0-6be890d140e8.gif)

Furthermore you can connect to an existing AI device and watch what is going on on the console (This example is from a hardware reset.):

![Screen Recording 2022-10-16 at 11 55 21](https://user-images.githubusercontent.com/837211/196029972-7de95c70-cc6d-4c78-a751-7353058b1471.gif)

### Additional Context

 **If you like the Idea of a Webinstaller, please add a `gh_pages` branch to your project and remove all content except the images directory. After that I can make a pull request to update that branch.** 

The pull request will contain an index.html that I manually converted from the current `Readme`.md with an added section **Webinstaller and Console** with the magic button.

(Before you merge the pull request you have to activate the `gh_pages` though - Deploy from a branch).

<img width="1243" alt="Screenshot 2022-10-16 at 12 07 18" src="https://user-images.githubusercontent.com/837211/196029559-8d8b10a2-b1f4-443b-8512-ef92bbfbddfb.png">

**Comment by jomjol** [comment]
In principle like the idea. Two points:
1. manual sd-card writing is still unavoidable
2. I develop everything with firefox, this is not supported to my knowledge
3. is there a change to choose between two configurations? e.g. rolling and master?

**Comment by caco3** [comment]
Some comments to above points:
1. No, this could be simplified. One would still need to format it on a PC first. The folders and files could be created by the firmware. For the initial OTA, we would need to implement a basic upload page directly in the firmware (like the reboot page). This also would give the advantage when we brick the HTML part as a basic OTA still would be possible!
2. Yes, i also would like to know the supported browsers/OS. To my undertsanding the browser needs access to the COM port resp. TTY on Linux. usually this is not allowed for security reasons.
3. It also would be sufficient to only support the releases and rolling. master anyway points to the last release usually.

**Comment by helllth** [comment]
Thanks for the detailed response. Find my answers inline.

> In principle like the idea. Two points:
> 
> 1. manual sd-card writing is still unavoidable

Yes. That was not the scope of my work.

> 2. I develop everything with firefox, this is not supported to my knowledge

Yes you are right. As @Disane87 stated: The API is experimental atm and not supported within firefox browsers.

> 3. is there a change to choose between two configurations? e.g. rolling and master?

Have a look at the Webinstaller of Tasmota (Also based on the button from[ ESP-Web Tools](https://esphome.github.io/esp-web-tools/)). There are a couple of options around their install button.

https://tasmota.github.io/install/

> 4. for this we need to move from readme.md to index.html?

Well. That is what I did. You could stay with the readme have an install only site without the additional info and link to that site from the readme. 



Anyway ...


If you don't want to integrate it in your site it's fine for me. Just decide. I will then setup an Installer repo that installs the current version under my org.

**Comment by caco3** [comment]
I love it (but haven't tested it yet myself)!

Even it does only work with Chrome, I think it would be of great help, especially if one could read out the USB log. Many people have issues to get logging working with putty, so with this we could make it easier for them!

I would keep the readme as markdown but add a link to the htm file as a way to flash/debug with Chrome

As for now, i still would suggest to keep the step of manual SD-Card preparation.

**Comment by caco3** [comment]
I created the branch as requested: https://github.com/jomjol/AI-on-the-edge-device/tree/gh_pages
How ever I am not sure if this will work the way you intended, because we can not merge that branch into `rolling` as it there also would remove all files!

As for enabling the pages, @jomjol would need to do that.

**Comment by caco3** [comment]
@helllth Please let us know how you want to proceed.
I think it would be great to have the webinstaller listed as an additional way to the existing solution. Also we could document its usage for showing the USB log

**Comment by helllth** [comment]
Hi. Great. Will do the pull request during the weekend. (At least that's the plan) 😉🤘

**Comment by helllth** [comment]
added https://github.com/jomjol/AI-on-the-edge-device/pull/1245

**Comment by caco3** [comment]
We should:
- [ ] Link form the main README to the Web Installer
- [ ] Add a reference to the main README on the landing page
- [ ] Add the [Logo](https://github.com/jomjol/AI-on-the-edge-device/blob/master/images/icon/watermeter.svg) to the main README and the Web Installer to add recognition

**Comment by caco3** [comment]
Enhanced, see https://github.com/jomjol/AI-on-the-edge-device/pull/1312

**Comment by helllth** [comment]
I like the new installer site 👍
