### ISSUE TITLE
Blurry pictures better than sharp pictures

### ISSUE THREAD

**Issue by Franzformator** [jomjol/AI-on-the-edge-device#119]
Hello,
first of all, I really like this project! It gives me the possibility to read my hidden Water-Counter without dissemble our furniture we have placed in front of the Counter to cover it. Also, I like to plot our water rate with MQTT and IoBroker.

After a longer setup period I got my sensor fixed to our water counter. First, I had only a very blurry picture of the readings, but the detection of die digit numbers was always perfect. 
Now I have “optimized” the mounting and I adjusted the focal point to get a sharp picture. 

The funny thing is, that the detection with the new sharp picture is much poorer than with a blurry picture (such as in the beginning). 
As you can see on my sample pictures. The detection has problems with “0” (becomes oftenNaN, 6 and 9) and “3” (becomes often an 8).

![image](https://user-images.githubusercontent.com/41994422/108681234-33343f80-74ef-11eb-9727-fe0e3e32fcce.png)

![image](https://user-images.githubusercontent.com/41994422/108681292-4810d300-74ef-11eb-8cc6-d1e168450101.png)

![image](https://user-images.githubusercontent.com/41994422/108681751-cd948300-74ef-11eb-822e-70f44296406b.png)

I also tried to change size of bounding boxes. But it has not changed anything.

**Is there any Solution for this Problem? Is it maybe possible to introduce synthetic blur for the detection?**

If not, I will try again to set my picture blurry by changing the focal point. 

THANK YOU!

**Comment by jomjol** [comment]
It seems, that something is wrong with your ROI size. The number on the ROI should not touch the border of the ROI. Here every digit is toughing the border:
![grafik](https://user-images.githubusercontent.com/30766535/108748317-bb8e0100-753e-11eb-9442-fd2edb6791f5.png)

You could make the ROI even a bit bigger:
![grafik](https://user-images.githubusercontent.com/30766535/108748546-ff810600-753e-11eb-828e-2f6ca2a4f6ff.png)

If all this is not helping, you can send me a sample of the digits (2-3 per image) and I put them into the next training.

**Comment by Franzformator** [comment]
Hi jomjol,

here you find some pictures, were zeros are not detected right. It seems that that the problmems cased throug the uper edges of the next number. Also you can find one picture with a wrong detection of a five:

![IMG_3656n](https://user-images.githubusercontent.com/41994422/112106132-8e6c5700-8bad-11eb-9c19-8fbb5075af8b.png)
![IMG_3657n](https://user-images.githubusercontent.com/41994422/112106136-8f04ed80-8bad-11eb-828a-78135bc49a7e.png)
![IMG_3654n](https://user-images.githubusercontent.com/41994422/112106137-8f9d8400-8bad-11eb-814a-3047045e2932.png)
![IMG_3655n](https://user-images.githubusercontent.com/41994422/112106139-8f9d8400-8bad-11eb-9181-1cf577773485.png)

**Comment by jomjol** [comment]
The NaN is okay, as the 0 is about to appearing. The "6" should noch happen. Two options I can offer:

1) you send me the image of the wrong detected "0" and I will put them in the next training session.
2) Remove the first ROI from you counter. This digit will most propably not change during the life time of you counter and therefore will stay in this half out stage forever.

Best regards,
  jomjol
