### ISSUE TITLE
[FR] IP address and MAC in MQTT 

### ISSUE THREAD

**Issue by Henry-Sir** [jomjol/AI-on-the-edge-device#1195]
### Feature Request

Please add the IP address and MAC in the MQTT message to be able to display this information in the Home Assitant.
(MAC also to be used as ID to identify the device -> see MQTT discovery)

**Comment by caco3** [comment]
We can addvthe MAC, but to identify, you can use the hostname as set in the wifi config!

**Comment by caco3** [comment]
Done in https://github.com/jomjol/AI-on-the-edge-device/issues/1134
