### ISSUE TITLE
Missing picture sections

### ISSUE THREAD

**Issue by Franzformator** [jomjol/AI-on-the-edge-device#120]
Hello,

during the setup I recognized that the detection window has a horizontal orientation.
If I am starting to change the angel corners are cuted from the original picture.

In my case this leads to the fact that not every counter is visible. But in the original picture the complete counter with all reading is on the picture. 

**Initial:**
![image](https://user-images.githubusercontent.com/41994422/108682717-f406ee00-74f0-11eb-94df-c2ecc3ac39f2.png)

**After Rotation:**
![image](https://user-images.githubusercontent.com/41994422/108682786-07b25480-74f1-11eb-9f4d-8020e93f67c7.png)

This also leads to missed readings if a bounding box is slightly out of the frame.
![image](https://user-images.githubusercontent.com/41994422/108682579-c621a980-74f0-11eb-94ca-2beb7f056685.png)

**Is it maybe possible to change orientation by config.ini?**

THANK YOU!

**Comment by jomjol** [comment]
I understand your problem, but this would imply some more changes in the code. Therefore I don't plan to make this configurable.

Another solution I could image is, to move the camera a bit further from the surface. There will be no problem with the resolution, as this is downscaled anyhow pretty strongly.

If you are using the rotary holder from thingiverse, you just could add another 2.5cm ring. This should be sufficient.
