### ISSUE TITLE
Helpful hint for Power-Supply

### ISSUE THREAD

**Issue by Franzformator** [jomjol/AI-on-the-edge-device#121]
Hello!

I had the same problems during the setup of my counter.

The ESP32 was working well and I could read out and configure it. But after a view runs (Read interval was set to 10 min) it crashed and was only got back to work after a power-off reset. 

I tried different USB power sources and also a big Lab power supply (set to 5.25V and 3 amp). But it was still crashing.

**The Solution I found was a 2200 uF capacitor (such as mentioned here: https://arduino-hannover.de/2018/07/25/die-tuecken-der-esp32-stromversorgung/) connected to the power pins directly on the board.** 

Now it is running stable since days.

Maybe this can help some guys in the future.

**Comment by jomjol** [comment]
Thanks for the hint! I will incorporate it into the documentation - untill then I leave this issue open.

**Comment by MichaelTimmermans** [comment]
Wich power pins did you use? The VCC, 5v or 3.3v?

**Comment by Franzformator** [comment]
I used the 5v Input. So, I can use a standard USB power source.

**Comment by jomjol** [comment]
Hint added to `installation.md` in the wiki
