### ISSUE TITLE
Enhancement: Show Image link and refresh-link on GUI

### ISSUE THREAD

**Issue by ozett** [jomjol/AI-on-the-edge-device#1210]
### The Problem

if i want to check the current status of the counter manually,
i would look onto an acutal image.

would be intuitive to have a button or link on the main GUI,
to refresh or capture that image (with/without flash).

i know that there is an uri, but one has to got through the wiki or readme to find it.

### Version

v12.0.1 (what field form the info-page do you need here: git-tag?)

### Expected Behavior

see a gui-button/link to capture an image.
usually the link on most webcams is http:/IP/snapshot.jpg

**Comment by jomjol** [comment]
The main page always shows the last taken image. This is not older than the cycle time of the runs.
It is not easily possible to take a new image at any time during the processing flow. The image data consumes so much memory, that you cannot hold a processing and an actual image in the memory at the same time.
So if the processing is using the memory and you would push that button, you risk to run out of memory, or we would need to change the flow logic, so that you can stop the processing at any time.

This just to have an image, that is maybe 2-3 minutes younger. I don't think, that this major effort is worth the benefit.

Please comment, there I have not closed the issue yet.

**Comment by ozett** [comment]
Great work so for for the engergy counter and AI, not to forget!  💐 

i came up to check the gasmeter from the image, because i had lots of time-out errors from the web-interface.
specially after activating on the influxdb part. so i lost a little bit of confidence in the stablity of the firmware.
As it sends only the numbers as the AI results over mqtt and i dont know if there is an error with them.

to my piece of mind i considered getting and saving an image for the long-run on node-red.
just to have later on reliable historical data for the next payment to the energy company in april next year.

i let the firmware now run (after time-out-errors with "file not found" messages instead of webgui) for a while, and it seems againt the foregoing errors that now the mqtt data is coming in constantly. 

maybe in my personal usecase i dont need to check with an image anymore.
(allthough a visible link would make reading the readme superflous)

i was used to do have tasmota on the device, and it was somehow stable on mqtt and i could reliably get snapshots.

maybe another enhancement could be instead to have a minimal webgui on the device, and load only extended html-code from the filesystem in a second run. 
it seems to me that it causes issues for the webgui to get all html-code from the filesystem. 
that experience caused my little loss of trust in the firmwares main functionality over the long run.

i would like forget that device now and see it running on its own for 6 months...

**Comment by jomjol** [comment]
Okay got it. The MQTT is running stable on my system, but others report same topic as you. 
But the MQTT contains also some error information:
![grafik](https://user-images.githubusercontent.com/30766535/197397149-066ccd6b-7baa-434b-bac3-703ead1b3b3a.png)


Secondly you can get the actual image very easily with the following html:
`http://IP-ADRESS/img_tmp/raw.jpg`

**Comment by ozett** [comment]
to workaround the unknown instability of the whole device sometimes (but always comes to normal state after some reboot, which is fine at the end) i used my already running node-red to automate grabbing an image and storing datapoints to a database.

![image](https://user-images.githubusercontent.com/5937811/197401406-1e8066cb-5978-494f-9a96-e1de14689445.png)


on my ESPs i used [espeasy ](https://github.com/letscontrolit/ESPEasy)for longtime, but as tasmota is easy to install with [webinstaller ](https://tasmota.github.io/install/) (like some others firmwares on esps, [wled](https://install.wled.me/), [ESPresence](https://espresense.com/firmware)) and has lots of controls over MQTT i migrated most devices to one platform and control all from node-reg gui.

![image](https://user-images.githubusercontent.com/5937811/197401587-e47d9945-0b35-4707-8564-e7a9f21b6645.png)



### URL for only grabbing an image?
another idea for more stability could be thinking of only grabbing an image an process the AI-Part on another host. Maybe node-red itself.  i have alread ["frigate"](https://github.com/blakeblackshear/frigate) running with a lots of cams and its making a fantastic job with tensorflow and hardware-accelleration.  could be another story to integrate number-detection or your model on another host/device. maybe [doods2 ](https://github.com/snowzach/doods2)could also run your model. That way one could use normal webcams and (already existing?) beefier hardware for tensorflow...

**Comment by jomjol** [comment]
### URL for only grabbing an image
That was, how everything startet. BUT: the neural network needs quite some sophisticated environment (tensorflow, image process, ...). This was done in a docker container, but for most users, the installation, running and combining a docker with the ESP in the local network was a barrier.

**Comment by ozett** [comment]
it is great, how it is now.
configuration and integration are great.
ws2813 LED also an great idea. 
thanks for all that!

👍 

another story would be maybe client/server version as a 2nd option,
stay with that edge-device on the gasmeter, and have a control channel running only with grabbing an image and processing on hosts/node-red...

**Comment by jomjol** [comment]
Yeah, possible, but honestly, this would need more ressources, which we don't have.
I'll close this issue. But we can still use it for discussion.
