### ISSUE TITLE
[FR] Possibility to set offset to value after meter exchange

### ISSUE THREAD

**Issue by unclej84** [jomjol/AI-on-the-edge-device#1211]
### The Problem

Feature Request:
It would be nice to define some kind of offset to the detected value in order to log into some kind of database even after the value is reset after a meter exchange. Mainly interesting this would be as output in the json output - maybe as additional key "offsetted".
Normally the new meter has a different value than the previous one so there would be a step in the values recorded

### Version

v12.0.1

### Expected Behavior

Additional setting to define offset to previous meter/sum of previous meters. This offset is then added to the detected value and written to the json output as new additional key e.g. "offsetted".

**Comment by jomjol** [comment]
I don't think, that this should be solved on the device. It's target is to read out the value.
I suggest to solve this on the receiver part (e.g. MQTT server, DB)
