### ISSUE TITLE
Refresh model information 

### ISSUE THREAD

**Issue by kaciker** [jomjol/AI-on-the-edge-device#1213]
### The Problem

Digits, model definition
In description for Models, information call to "_Path to CNN model file for image recognition. Check the [documentation](https://github.com/jomjol/AI-on-the-edge-device/wiki/Choosing-the-Model) for details."

For digit model we have this 3 options:
dig1330s1q.tflite
dig-sd1-md-v1.0-q.tflite
dig1400s2q.tflite.tflite 

But in the link github, we have 
dig-class11
dig-class100 / dig-cont

What is the connection between both ?? How to know the spects of the 3 proposals in the app ?

### Version

12.0.1

### Expected Behavior

update of the infor in github

**Comment by haverland** [comment]
Use the [update.zip](https://github.com/jomjol/AI-on-the-edge-device/releases/download/v12.0.1/update.zip) from 12.0.1 again. It uploads the models, firmware and html. 

Or download the [initial_esp32_setup.zip](https://github.com/jomjol/AI-on-the-edge-device/releases/download/v12.0.1/initial_esp32_setup.zip) and extract it from scard.zip (folder config) and upload it manually to /config folder on your device.

**Comment by kaciker** [comment]
> Use the [update.zip](https://github.com/jomjol/AI-on-the-edge-device/releases/download/v12.0.1/update.zip) from 12.0.1 again. It uploads the models, firmware and html.
> 
> Or download the [initial_esp32_setup.zip](https://github.com/jomjol/AI-on-the-edge-device/releases/download/v12.0.1/initial_esp32_setup.zip) and extract it from scard.zip (folder config) and upload it manually to /config folder on your device.

It works, thanks
