### ISSUE TITLE
Analog recognition ROIs are completely different from set regions in settings

### ISSUE THREAD

**Issue by rizz360** [jomjol/AI-on-the-edge-device#1214]
### The Problem

Hello,
I have an issue with the detection of analog ROIs.
On the overview and recognition page it displays the analog ROIs completely misaligned even though the analogs ROIs are correctly aligned in settings. The alignment marks and the digital ROIs are displayed perfectly fine.

Is this a mistake on my part? Please see the attached images for reference.

### Version

12.0.1

### Expected Behavior

Analog ROIs should respect their set size and position and detect the correct values.

### Screenshots

<img width="666" alt="Screenshot 2022-10-24 at 18 54 50" src="https://user-images.githubusercontent.com/1228549/197583164-6d7f3ee1-d0c5-47fc-a7f1-a43be074d41d.png">

<img width="678" alt="Screenshot 2022-10-24 at 18 53 33" src="https://user-images.githubusercontent.com/1228549/197583214-c76a99ac-daf6-4b94-a92d-aa92a57d0675.png">

### Additional Context

AI-on-the-edge was working okay a few month ago but analog values were never perfectly identified. I had some spare time on my hands now and checked for the issue.

I updated to the newest version and have tried redoing the reference image, alignment marks and resettings the analogs ROIs in the settings. Sadly it didn't help.

I strange detail I noticed is that each digit of the recognized analogs ROIs displays the same image, eventhough the areas are different.

**Comment by rizz360** [comment]
Here's my config for reference:

```
[MakeImage]
;LogImageLocation = /log/source
WaitBeforeTakingPicture = 5
;LogfileRetentionInDays = 15
Brightness = 0
Contrast = 0
Saturation = 0
LEDIntensity = 25
ImageQuality = 12
ImageSize = VGA
FixedExposure = false

[Alignment]
InitialRotate = 125.45
InitialMirror = false
SearchFieldX = 20
SearchFieldY = 20
AlignmentAlgo = default
FlipImageSize = false
/config/ref0.jpg 325 134
/config/ref1.jpg 220 278

[Digits]
Model = /config/dig-class100_s1d-md-v1.0_q.tflite
CNNGoodThreshold = 0.5
;LogImageLocation = /log/digit
;LogfileRetentionInDays = 3
main.dig1 223 55 39 70 false
main.dig2 268 55 39 70 false
main.dig3 316 55 39 70 false
main.dig4 360 55 39 70 false
main.dig5 403 55 39 70 false

[Analog]
Model = /config/ana-cont_1101_s2_q.tflite
;LogImageLocation = /log/analog
;LogfileRetentionInDays = 3
main.x0,1 421 214 119 119 false
main.x0,01 342 335 120 120 false
main.x0,001 195 351 124 124 false
main.x0,0001 87 243 128 128 false

[PostProcessing]
main.DecimalShift = 0
PreValueUse = true
PreValueAgeStartup = 720
AllowNegativeRates = false
main.MaxRateValue = 2
;main.MaxRateType = AbsoluteChange
;main.ExtendedResolution = false
;main.IgnoreLeadingNaN = true
ErrorMessage = true
CheckDigitIncreaseConsistency = false

[MQTT]
Uri = mqtt://**************
MainTopic = **************
ClientID = **************
user = **************
password = **************
SetRetainFlag = true

;[InfluxDB]
;Uri = undefined
;Database = 
;Measurement = undefined
;user = undefined
;password = undefined

;[GPIO]
;IO0 = input disabled 10 false false 
;IO1 = input disabled 10 false false 
;IO3 = input disabled 10 false false 
;IO4 = built-in-led disabled 10 false false 
;IO12 = input-pullup disabled 10 false false 
;IO13 = input-pullup disabled 10 false false 
LEDType = WS2812
LEDNumbers = 2
LEDColor = 150 150 150

[AutoTimer]
AutoStart = true
Intervall = 3

[Debug]
Logfile = false
LogfileRetentionInDays = 3

[System]
TimeZone = **************
;TimeServer = undefined
;AutoAdjustSummertime = false
;Hostname = undefined
SetupMode = false```

**Comment by jomjol** [comment]
I have never seen this before. Maybe, the `, ` in the naming is causing the problem. Can you try to remove this?

```
[Analog]
Model = /config/ana-cont_1101_s2_q.tflite
;LogImageLocation = /log/analog
;LogfileRetentionInDays = 3
main.x0,1 421 214 119 119 false
main.x0,01 342 335 120 120 false
main.x0,001 195 351 124 124 false
main.x0,0001 87 243 128 128 false
```

**Comment by rizz360** [comment]
Oh wow! I think I would have never figured that one out! I renamed the ROIs and rebooted. It is showing the ROIs correctly now. Thank you so much!

Sadly the values are not identified correctly. But I guess that's a seperate issue.

<img width="655" alt="Screenshot 2022-10-24 at 19 28 38" src="https://user-images.githubusercontent.com/1228549/197588892-f52a965b-185e-4b85-aa98-c9829da5ee5c.png">

**Comment by rizz360** [comment]
Using `ana-class100_0120_s1_q.tflite` the values are correctly identified now. Again thank you so much for your support and the awesome project!

<img width="659" alt="Screenshot 2022-10-24 at 19 42 39" src="https://user-images.githubusercontent.com/1228549/197591357-eaaf4019-8a27-4235-9745-a9a87f2012c3.png">
