### ISSUE TITLE
Feature Request: CSV Log-Datei

### ISSUE THREAD

**Issue by MightyMaxon** [jomjol/AI-on-the-edge-device#122]
Hallo,

erstmal ein großes Lob. Wirklich ein cooles Projekt.

Für jemanden, der keine Möglichkeiten hat, eine Weiterverarbeitung via MQTT zu machen, wäre es möglich, die Zählerstände regelmäßig mit Datum und Uhrzeit in eine Log-Datei schreiben zu lassen auf die SD-Karte, z.B. in eine .csv Datei? Man könnte das in  der config.in ein- und ausschalten.

VG

**Comment by jomjol** [comment]
Hi,
Logdatei gibt es ja iun du könntest manuell die Logdateien parsen und die Werte auslesen. CSV ist nicht geplant, da müsste ich auch noch eine Codierung erstellen und ich brauche aktuell 97.7% des Speichers für die Firmware und das OTA.
Du kannst aber auch die Werte mit einer URL und einem Script selbst abholen: ```/wasserzaehler.html``` liefert dir den ausgelesenen Zählerwert als einfachen Text für Weiterverarbeitung.
Gruß,
  jomjol
