### ISSUE TITLE
Feature Request: Allow grouping of digits to multiple reading values

### ISSUE THREAD

**Issue by papauorg** [jomjol/AI-on-the-edge-device#123]
This is a really awesome project. I use it for my water meter as described in the documentation. It's working really well and I'm quite happy with your project. Thanks a lot for your work.

Beeing so happy I wanted to go further and use another esp to read my power meter. It would work exactly the same (minus the analog digits) BUT I have a power meter that counts two different values depeding on the time the power is used. It looks similar to this one here: 
![Powermeter](https://www.energieberatung-frankenwald.de/wp-content/uploads/2014/05/drehstromzaehler.png)

It would be great if I could use one device for recognizing all the digits and then group them so I can read two values. I could read all digits of both values and merge it to one number, but then I loose the sanity checks that the device performs.

The Idea would be that in the configuration of the ROIs some form of grouping is allowed. E.g. ROI1-6 belong to VALUE1 and ROI7-12 belong to VALUE2 (or some other named group). And those values are then used to be checked and sent via MQTT the same way it's now done for one value. Would this be possible?

Please let me know what you think.

Thanks and best regards,
Philipp

**Comment by jomjol** [comment]
@papauorg,
I fully get you point. The implementation is fully focused on only one group of digits and analogs only. Therefore this would need a deeper change in the logic. At the moment I'm the only programmer of this and do not have the ressources to do so.

I could offer you maybe another solution: what if you just make the grouping later in a off side postprocessing. So you could specify all digits in one row, make the comma as the separator. So you would have a "virtual" counter number, giving you all digits:  ```abcdef,ghijkl``` abcdef would be e.g. the upper and ghijkl the lower counters. You would need to take care of the comma in each by yourself. 

There are some limits:
* replacement of the "N" would work
* but the error correction like MaxRateValue does not make sense

Maybe this helps you.

Best regards,

  jomjol

**Comment by jomjol** [comment]
Due to lack of capacity this is not followed currently. In order to not forget it, it is added to the feature request page: https://github.com/jomjol/AI-on-the-edge-device/blob/master/FeatureRequest.md

Meanwhile this issue will be closed, as it is not active currently.

**Comment by jomjol** [comment]
Implemented since v8.0.0
