### ISSUE TITLE
Cam version YYH V2.0 does not work

### ISSUE THREAD

**Issue by JoeAverge9** [jomjol/AI-on-the-edge-device#1230]
### The Problem

I have the following camers YYH V2.0 and the system locks with a refused connection. Seems to slow the system down. After a LONG wait a page may load but then freezes. I change the cam to 8225H V2.0 and it works

### Version

v12.0.1

### Expected Behavior

Normal operation with web page loading. Is there a way to certify this camera as the cam that works is very bad quality.

**Comment by jomjol** [comment]
We do not certify specific versions. What we us is the esp32cam camera driver from github (https://github.com/espressif/esp32-camera).
Whatever works with this driver in our firmware is okay, if not we do not provide specific versions.

**Comment by JoeAverge9** [comment]
Thanks for the update. I will look for compatable cameras
