### ISSUE TITLE
Current bootloader version seems bad.

### ISSUE THREAD

**Issue by MichaelTimmermans** [jomjol/AI-on-the-edge-device#124]
Hi, 

I tried to install the bins using the expressif tool and i used the bins in referenced in te installation guide. It burned sucessfully but the esp was stuck in a boot loop. 

After that i burned the previous release (the rolling camera version) and that worked fine. I updated the esp via OTA after that. 

The current bootloader is 101 KB, while the previous one is only 26 KB. Dont know if that matters.

**Comment by jomjol** [comment]
Hi,
  somethings seems to be wrong with your download. Just checked the current bootloader.bin in the master:

![grafik](https://user-images.githubusercontent.com/30766535/109213898-71f91c80-77b1-11eb-8244-2323f92a9bef.png)

It has about 25k, which is okay. Don't know, where your 101k is coming from. Please try a new download.

Best regards,
  jomjol
