### ISSUE TITLE
Update Home Assistant Wiki page for 2022.11 HA release

### ISSUE THREAD

**Issue by iridris** [jomjol/AI-on-the-edge-device#1242]
### The Problem

With the upcoming Home Assistant 2022.11 release, `water` is being added as a `device_class`, and will also be able to be added to the `Energy` dashboard. Please update the wiki accordingly, as it mentions in several places workarounds for not having proper `water` support.

https://rc.home-assistant.io/blog/2022/10/26/release-202211/#getting-insights-into-water-usage

### Version

12.0.1

**Comment by caco3** [comment]
yes, I am aware of this and will update it in the near future

**Comment by caco3** [comment]
Added support to the firmware in https://github.com/jomjol/AI-on-the-edge-device/pull/1246
and will update the wiki within https://github.com/jomjol/AI-on-the-edge-device/issues/1133
