### ISSUE TITLE
Recognition ist correct - Value is wrong

### ISSUE THREAD

**Issue by Kornelius777** [jomjol/AI-on-the-edge-device#1244]
### The Problem

Have a look at the screenshots.
The meter reading is recognized correctly (screenshot 1),
however, the calculated value is wrong (screenshot 2).

"CheckDigitIncreaseConsistency" is set to "true".

### Version

v12.0.1

### Screenshots

https://paste.pics/5f80733887be9fa9faf080cd70af0623
https://paste.pics/83d7a48d6198ff98e30ecd3c6d74ef1f

**Comment by RasputinBerry** [comment]
I have (the same) error: The setup worked for a week without any problems. The "Raw Value" is recognized correctly, the "Value" is no longer updated.
![Value](https://user-images.githubusercontent.com/56359831/201413600-90d97d83-eebb-4dc1-84f1-e36866b14984.jpg)

**Comment by jomjol** [comment]
![grafik](https://user-images.githubusercontent.com/30766535/201462011-002cea30-b845-4246-826b-cfc693adfa57.png)

Your MaxRate Setting is too tight.
