### ISSUE TITLE
Updated Wiki "ROI Configuration

### ISSUE THREAD

**Issue by haverland** [jomjol/AI-on-the-edge-device#1249]
### The Problem

I've updated the ROI-Configuration for dig-class100/dig-cont models (https://github.com/jomjol/AI-on-the-edge-device/wiki/ROI-Configuration )

and moved collecting images to https://github.com/jomjol/AI-on-the-edge-device/wiki/Learn-models-with-your-own-images

Please counter read and close if ok.

**Comment by caco3** [comment]
- The ROI page looks great! Thank you! I reformated it a bit and added some remarks/links. I home you don't mind.
- For the Training page: 
  - Would it be possible to generate an overview of all trained digits/pointers? Then people could check if their pointer is contained. If you point me to the folder containing them, I can see what I can do.
  - I am still a bit confused. Which part can they do by themself and which must be done by you?
  - There are 2 sections named "dig-class11 models"
  - On one point you say they have to create a Pull Request, on the Other you say to create an Issue! I would suggest that we create an Issue template so its clear for them

**Comment by haverland** [comment]
Looks like the ROI-Configuration Page is now deleted?

**Comment by DanielWe2** [comment]
Seems to be here now: https://github.com/jomjol/AI-on-the-edge-device/wiki/ROI-(Region-of-Interest)-Configuration  ?

**Comment by caco3** [comment]
> Seems to be here now: https://github.com/jomjol/AI-on-the-edge-device/wiki/ROI-(Region-of-Interest)-Configuration ?

Wrong Issue?

**Comment by caco3** [comment]
ah, sry, I renamed its title and forgot that the wiki does not update the links :(
I reverted the change now

**Comment by haverland** [comment]
Thanks for your hints:


>   * Would it be possible to generate an overview of all trained digits/pointers? Then people could check if their pointer is contained. If you point me to the folder containing them, I can see what I can do.

It would be hard to keep that up. It also doesn't really say anything about whether the network recognizes your images. I've added the Links to the images folders.
>   * I am still a bit confused. Which part can they do by themself and which must be done by you?
All can be do by itself. But if they want to share the images, please only the images in PR.
>   * There are 2 sections named "dig-class11 models"
Fixed. 
>   * On one point you say they have to create a Pull Request, on the Other you say to create an Issue! I would suggest that we create an Issue template so its clear for them
You can use both types, if you don't know what a PR is. Added to section sharing

**Comment by caco3** [comment]
PR = Pull request. I would not tell them to use that as they would have to fork, change files and create a PR, => far too complicated.

**Comment by caco3** [comment]
@haverland What do you think about https://caco3.github.io/neural-network-analog-needle-readout/ ?
It is fully autogenerated and automatically deployed through https://github.com/caco3/neural-network-analog-needle-readout/blob/main/.github/workflows/generate-overview.yaml

**Comment by haverland** [comment]
Real cool Idea. Could you make a pull-request? I will integrate it in https://github.com/haverland/Tenth-of-step-of-a-meter-digit and update the Wiki.

**Comment by caco3** [comment]
> Real cool Idea. Could you make a pull-request? I will integrate it in https://github.com/haverland/Tenth-of-step-of-a-meter-digit and update the Wiki.

Yes, I will create one. But give me time to optimize it a bit first.

**Comment by caco3** [comment]
I updated the script and HTML page a bit, see https://github.com/jomjol/neural-network-analog-needle-readout/pull/13 and https://github.com/jomjol/neural-network-digital-counter-readout/pull/18

- [ ] Once merged, we can update the wiki pages and refer to this overview pages

**Comment by cbho** [comment]
Ok - thanks :-)
However, I'm not really sure how to understand this sentence then: "Therefore, the height must be set differently and more accurately."
As I see the illustrations, the inner box should fit the size of the number exactly the same?
But placing the ROI differs in that it should be equidistant from top and bottom, no matter where the number when placing the ROI?

**Comment by caco3** [comment]
Thanks @jomjol for merging!

I updated the first section of https://github.com/jomjol/AI-on-the-edge-device/wiki/ROI-Configuration and added links to the generated overviews.

**Comment by caco3** [comment]
> Ok - thanks :-) However, I'm not really sure how to understand this sentence then: "Therefore, the height must be set differently and more accurately." As I see the illustrations, the inner box should fit the size of the number exactly the same? But placing the ROI differs in that it should be equidistant from top and bottom, no matter where the number when placing the ROI?

I am closing this issue since it is about updating the Wiki pages.

@cbho If your issue still is unsolved, please create a discussion to proceed there. This makes it easier to find it for others having the same issue.

**Comment by caco3** [comment]
@haverland  You might want to update your https://github.com/haverland/Tenth-of-step-of-a-meter-digit with my latest changes, although they are just cosmetic
