### ISSUE TITLE
Gelegentliche Falscherkennung der Analogwerte

### ISSUE THREAD

**Issue by LineF** [jomjol/AI-on-the-edge-device#125]
Hallo Jomjol,

alle 2-3 Wochen kommt es bei mir vor, daß der Analogwert hoch springt, spätere Werte dann wieder korrekt gelesen werden, aber wegen zu niedrigem Wert dann verworfen werden.
Ich habe deshalb mal das Debugging aktiviert und folgende falsch erkannte Bilder gefunden:
![7 1_analog1_20210225-191341](https://user-images.githubusercontent.com/11915423/109209898-6820ea80-77ac-11eb-82a9-cc1be02c13a5.jpg)
7.1_analog1_20210225-191341

![7 2_analog2_20210225-191341](https://user-images.githubusercontent.com/11915423/109209916-6bb47180-77ac-11eb-9ea6-48412cbcb178.jpg)
7.2_analog2_20210225-191341

![8 2_analog3_20210225-191341](https://user-images.githubusercontent.com/11915423/109209926-6f47f880-77ac-11eb-800d-f6f8d75f0416.jpg)
8.2_analog3_20210225-191341

![4 6_analog4_20210225-191341](https://user-images.githubusercontent.com/11915423/109209934-71aa5280-77ac-11eb-8171-e5691f33d011.jpg)
4.6_analog4_20210225-191341

Die Bilder werden in diesem einen Fall also ganz verquer ausgeschnitten und dann falsch analysiert.

Mein Bild der Wasseruhr sieht generell so aus:
![2021-02-25 20_54_56-jomjol - AI on the edge](https://user-images.githubusercontent.com/11915423/109210070-9e5e6a00-77ac-11eb-9815-d2a79f322916.png)

Im Normalfall werden die Bilder auch exakt ausgeschnitten und korrekt erkannt...

Viele Grüße,
Martin

**Comment by jomjol** [comment]
Hallo Martin,
  ein solcher Fehler ist mir bisher noch nicht aufgefallen. Die verzerrten, bzw. teilweise doppelt erscheinenen Bilder sehen sehr nach einem Kameraauslesefehler aus. Dann ist das Alignment natürlich total im Wald. Sprunghaft falsche Werte kannst du über die Paramter für die maximal Sprungrate (MaxRateValue) und das sperren von negativen Werten (AllowNegativeRate) verwerfen.

Wenn du das Logging anhanst, könntest du mal zu den Bilder in die Logdatei schauen, ob dann auch ein Restart vorkommt oder was dort so steht.
Gruß,
  jomjol

**Comment by gon0** [comment]
Hallo zusammen,

bei mir "springt" hauptsächlich die 0,1 m³-Stelle. Ob die Ursache bei mir in falsch aufgenommenen Bildern liegt, oder ob die Zeigerposition nicht korrekt ausgewertet wird, kann ich nicht sagen. Ich behalte die Bilddarstellung mal im Auge. 
Meine bisherigen Erkenntnisse: Hauptsächlich scheint es bei der 0,1 m³ -Stelle bei zu passieren. Es kann sein, dass dies bei den weiteren Nachkommastellen nicht auffällt, weil diese verworfen werden, bis die 0,1 m³ Stelle tatsächlich weiterspringt. 

So sieht es über die vergangene Woche aus: 
![grafik](https://user-images.githubusercontent.com/33236024/109413762-6e32e900-79af-11eb-9404-8653d9059afc.png)

Die Erkennung sah bei meiner Stichprobe so aus:
![grafik](https://user-images.githubusercontent.com/33236024/109413794-8efb3e80-79af-11eb-91e2-3c9c47afdcdc.png)

Es fällt auf, dass der Zahlenwert bei der Analoganzeige manchmal nicht richtig erkannt wird:
![grafik](https://user-images.githubusercontent.com/33236024/109413912-282a5500-79b0-11eb-8942-d97baa57419d.png)

Ich habe das Logging über die letzten Woche aktiviert, jedoch sind die Ordner "analog", "digital" und "source" leer. Nur im Ordner "message" fanden sich de angehängten log-Dateien, in denen die Wertesprünge zu erkennen sind:

[log_2021-02-27.txt](https://github.com/jomjol/AI-on-the-edge-device/files/6056504/log_2021-02-27.txt)
[log_2021-02-26.txt](https://github.com/jomjol/AI-on-the-edge-device/files/6056505/log_2021-02-26.txt)
[log_2021-02-25.txt](https://github.com/jomjol/AI-on-the-edge-device/files/6056506/log_2021-02-25.txt)

Ich unterstütze gerne, wenn bestimmte Daten bei der Fehlerbehebung helfen.

Viele Grüße,
gon0

**Comment by jomjol** [comment]
Hi gon0,
ist das Thema noch aktuell? Mir scheint beim betrachten der Bilder, dass du die Zeiger nicht ganz mittig hast. Erfahrung ist, sich nicht am Ziffernring zu orientieren, sondern an der Mitte des roten Zeigers, dann stimmen die Werte besser.
Bitte um kurze RM, ob ich den Issue schließen kann oder du noch Hilfe brauchst?
Beste Grüße, 
  jomjol

**Comment by gon0** [comment]
Hi Jomjol,

das ist ein guter Tipp. Ich habe mich am Ziffernring orientiert und werde nun die Konfiguration erneut durchführen und die Zeigermitte auswählen.

Dieses Ticket kannst Du von meiner Seite aus gerne schließen.

Viele Grüße,
gon0

**Comment by LineF** [comment]
Hallo Jomjol,

ich wollte eben das Debugging so hochschalten, daß auch das komplette Kamerabild geloggt wird. Es hat sich dann die Web-Oberfläche aufgehängt und nach etlichen Versuchen kam ich dann wieder drauf.
Ein Reboot hat nicht stattgefunden (Uptime 4 Tage), aber ich hatte dann folgendes Kamerabild:
![image](https://user-images.githubusercontent.com/11915423/110383166-36393f00-805c-11eb-8065-84643a60c246.png)

Und die Analyse des Bildes ging dann auch wieder schief.
Es stellt sich jetzt die Frage, ob das ein Auslesefehler ist oder ob da irgendwas im Speicher rumschreibt und dabei das Bild erwischt und die Bilddatenstruktur (zer-)stört.

Werde mal noch weiter beobachten.

Gruss,
Martin

**Comment by jomjol** [comment]
Ich kenne diese Art von Fehlerbild eigentlich nicht wirklich - sieht  nach einer instabilem Kamera aus. Ist die Auflösung VGA?

Noch ein Hinweis: ich würde die digitalen Ziffern mit etwas mehr Rand ausschneiden. Dann passt das besser zu den geteachten Bildern.

Gruß,
  jomjol

**Comment by LineF** [comment]
Ich hatte ja das Debugging eingeschaltet, um das Gesamtbild mitzuprotokollieren. Jetzt hatte ich wieder einen Fall, wollte mir das Bild raussuchen, aber die Protokollierung hat nicht richtig gearbeitet.
Die scheint irgendwie nach ein paar Tagen aufzuhören und die alten Bilder, die nach 3 Tagen gelöscht werden sollten, werden auch nicht gelöscht...
Ich verwende gerade eine Version vom 23.01.2021

Gibt's da Probleme beim Debugging?
Folgende Parameter habe ich dafür gesetzt:

[MakeImage]
LogImageLocation = /log/source
LogfileRetentionInDays = 3
WaitBeforeTakingPicture = 5
ImageQuality = 5
ImageSize = VGA
......

Gruss,
Martin

**Comment by jomjol** [comment]
Hi Martin,
am Loging wurde schon länger nicht mehr gearbeitet. Ehrlich gesagt, ist das Modul auch gar nicht von mir. Wenn ich dich richtig verstehe, dann funktioniert das Logging anfangs gut und nach ein paar Tagen schaltet es ab?

**Comment by LineF** [comment]
Ja, so hab ich das zuletzt beobachtet.
Ich habe jetzt mal auf der SD-Karte aufgeräumt - nicht, dass die voll war - was ich allerdings nicht glaube...
Werde mal die nächsten Tage noch beobachten.

Bei den Bildern, die in log/source mitprotokolliert werden, habe ich bislang zwei gefunden, die problematisch waren, allerdings keinen Einfluss auf die Ziffernerkennung hatten:

![raw_20210317-090806](https://user-images.githubusercontent.com/11915423/111693161-908e8880-8830-11eb-9712-4dfdf5efac42.jpg)
![raw_20210318-060029](https://user-images.githubusercontent.com/11915423/111693171-93897900-8830-11eb-96ef-596bb6f95435.jpg)

Die Bilder, die unter log/source abgespeichert werden, werden die gleich nach dem Laden von der Kamera dort abgespeichert - also noch vor weiteren Verarbeitungsschritten? Nicht, daß evtl. irgendein Bug im Memory rumschreibt und damit Informationen im im RAM gespeicherten Bild zerstört...

Vielleicht habe ich auch ein Problem mit der Versorgungsspannung - die wird über ein relativ langes Kabel (aber vglw. großem Querschnitt) zugeführt.
Am Anfang des Projekts hatte ich ein dünneres Kabel, da hat die Foto-LED ab und zu kräftig geflackert - ich glaube da hatte ich mehr Spannungsprobleme - aber da waren keine Erkennungsprobleme...

Martin

**Comment by jomjol** [comment]
Spannungsprobleme werden in der Tat immer wieder berichtet. Du brauchst eine stabile 5V Versorgung. Es wird immer wieder auch berichtet, dass ein Stützkondensator zwischen GND und VCC mit möglichst hoher Kapazität (2200uF) hilft.

**Comment by jomjol** [comment]
Werde das jetzt mal bei mir einschalten und mit nur einem Tag. Mal schauen was bleibt und warum.
Danke für den Hinweis.

**Comment by sirpete83** [comment]
Hallo,
ein Kondensator und ein gutes Kabel zwischen Netzteil und Modul sind sehr wichtig, damit das Bild störungsfrei aufgenommen wird. Ich würde aber verschlagen auch eine Kapazität von 470 µF zwischen 3V3 und GND anzuschließen.
Ich habe aber auch ein problem, hat jemand von euch so einen Zähler mit diesen analog zeiger in der zweiten stelle? Der liefert immer andere Werte und ich habe keine idee wie ich das verbessern kann?
![Screenshot_2021-03-22 jomjol - AI on the edge](https://user-images.githubusercontent.com/7904787/112054934-80d7b280-8b56-11eb-830c-bacc863a9174.png)

**Comment by jomjol** [comment]
Du braucht dazu ein neues File für die analogen CNNs. In der neuesten Version findest du `ana0700s1lq.tflite`. Dort ist ein ähnlicber Zeiger trainiert. Verwendest du das schon?

Falls es damit auch nicht besser wird, brauche ich neue Bilder zum Trainieren.

**Comment by sirpete83** [comment]
Hallo jomjol,
nein, dass wusste ich noch nicht. Werde mir das ganze mal anschauen. Und die Änderung kann ich dann auch für den einen Zeiger vornehmen?

**Comment by jomjol** [comment]
Ja, das stimmt, aber den Wechsel der tflite sollte man mit Bedacht selbst machen. Bis auf die Fälle, wo du wirklich neue Zeiger verwendest besteht eigentlich auch kein Grund, da dort keine Bugs enthalten sind.

Ich schließe den Issue mal. Wenn du noch Themen hast, bitte gerne wieder öffnen.
