### ISSUE TITLE
Missing Home Assistant MQTT Discovery settings?

### ISSUE THREAD

**Issue by AdmiralRaccoon** [jomjol/AI-on-the-edge-device#1256]
### The Problem

Hello,
I can´t find the switch "Enable HomeAssistant Discovery" for MQTT in the configuration asdescribed in this wiki:
https://github.com/jomjol/AI-on-the-edge-device/wiki/Integration-Home-Assistant

Everything MQTT relelated i see is in the screenshot.
(Sorry if I have overread something)

Thanks
Philipp

### Version

12.0.1

### Screenshots

![image](https://user-images.githubusercontent.com/41727850/199477836-4c00f39f-d0ec-4912-b262-2a2ce5cf4e9d.png)

**Comment by caco3** [comment]
Sorry, you are a bit to early for us :)
This feature will only come in the next release. but you can already try it out now, just use the `update_*.zip`from https://github.com/jomjol/AI-on-the-edge-device/actions/runs/3376294777 (at bottom of page).

If you find issues, please report them in https://github.com/jomjol/AI-on-the-edge-device/issues/1133
