### ISSUE TITLE
Wrong value error exits flow

### ISSUE THREAD

**Issue by khase** [jomjol/AI-on-the-edge-device#1259]
### The Problem

Since the last update i do have a problem that the flow always exits wit 'rate to high'
The Raw value seems correct but the Error Message states a wrong value as 'Read'
It always seems to be double the actual value.

![image](https://user-images.githubusercontent.com/26968077/199693986-049d4717-3236-4952-a818-ae94d21f202c.png)

### Version

It Says Git-Branch: master but i did use the Package from Release 12.0.1

### Expected Behavior

Fill not recognized digits with known onse of the Pre value.

### Screenshots

![image](https://user-images.githubusercontent.com/26968077/199694495-5425270a-8d60-430e-848f-59248d5119af.png)
![image](https://user-images.githubusercontent.com/26968077/199694577-b75e97a3-04e1-4dc6-9094-d96d24442925.png)
![image](https://user-images.githubusercontent.com/26968077/199694667-e61bef33-bab4-4b4d-8d9e-ad6f602af52b.png)

**Comment by haverland** [comment]
You use an older Version. 12.0.1 release and build on 29th of september.

Looks like you use the 11.x.x Version. This had a bug that was fixed in version 12.0.1.

**Comment by khase** [comment]
Tahanx for opening my eyes.
Had to dig a little deeper to find that its indeed running on 11.3...

Seems that i was obviously stuck at `If anything bricks you can try to ... Use the initial_esp32_setup.zip as alternative` in the upgrade description :(
