### ISSUE TITLE
Uncaught ReferenceError: doTake is not defined     at HTMLInputElement.onclick (edit_reference.html:42)

### ISSUE THREAD

**Issue by Coalado** [jomjol/AI-on-the-edge-device#126]
The js block is created AFTER the link that calls it.
Browser: Latest Chrome

**Comment by jomjol** [comment]
Just testet "edit_reference.html" with Chrome, Firefox and Edge. No problem on any system.

Please give some more input, until then I'll close the issue.

**Comment by Coalado** [comment]
It's not a JS issue. The JS block is correct.
Anyway, it sometimes works, sometimes not. I had the same issue with Chome and Edge.

Try to reload http://watermeter/edit_reference.html several times. Open the Web Debugger to bypass the browser Cache.

It seems that the webserver has a bug and does not finish connections.

The browser is loading "forever", and does not init the embedded JS.

![image](https://user-images.githubusercontent.com/21013026/109345027-d2e72a00-786f-11eb-8ca2-1d2ac8c95a06.png)

![image](https://user-images.githubusercontent.com/21013026/109345083-e4303680-786f-11eb-8b0d-1bf5b523cb30.png)

**Comment by Coalado** [comment]
I get the same issues on other pages es well. Here, edit_config_param.html does not finish. As you can see on the screenshot, the server starts the response with "0\r\n\r\n" -> The header parser in chrome fails. Is there are a reason why you send the data "chunked"?

![image](https://user-images.githubusercontent.com/21013026/109346376-e3989f80-7871-11eb-89d8-396f31486947.png)

**Comment by jomjol** [comment]
I send the data "chunked" because depending on the size of the html or js-file, it is loaded from the SD-card in peaces and therefore is send chunked.

**Comment by Coalado** [comment]
That makes sense.
