### ISSUE TITLE
HTML/JS Error!

### ISSUE THREAD

**Issue by Coalado** [jomjol/AI-on-the-edge-device#127]
Browser: Latest Chrome

edit_reference.html:42 Uncaught ReferenceError: doTake is not defined
    at HTMLInputElement.onclick (edit_reference.html:42)

**Comment by Coalado** [comment]
If I reload the page, it often works, so it seems to be some kind of loading/timing issue

**Comment by jomjol** [comment]
Just keep in mind, that you have running a:

* WebServer
* Image Processing
* Neural-Network Calculation

on an ESP32 with:

- 0.24 GHz, 
- 0.004GB RAM and 
- SD-Card ESP32

and not a on a 3 GHz, 16GB RAM, SSD-Drive i7-Prozessor :-)

It needs some patience :-)

Best regards,
  jomjol
