### ISSUE TITLE
ROI naming - must not contain a ","

### ISSUE THREAD

**Issue by jomjol** [jomjol/AI-on-the-edge-device#1280]
The naming of the ROIs must not contain a "," (comma), because this is internally used as column separator.

- [x] Check naming convention in ROI
- [x] Information in the documentation

**Comment by caco3** [comment]
Also check for whitespaces and double quotes

**Comment by caco3** [comment]
https://github.com/jomjol/AI-on-the-edge-device/issues/1214#issuecomment-1289353089

**Comment by jomjol** [comment]
Implemented in rolling with [f725adf5ba9ced8a76df142da72788f42b62800a](https://github.com/jomjol/AI-on-the-edge-device/tree/f725adf5ba9ced8a76df142da72788f42b62800a)
