### ISSUE TITLE
NTP fails for all 10 retries

### ISSUE THREAD

**Issue by caco3** [jomjol/AI-on-the-edge-device#1292]
I have seen it several times that it needed all 10 retries to get the time from the  NTP server.

Also at least once it failed the tenth. and kept the time on 1. January 1970.

- [x] Add log

**Comment by pos-ei-don** [comment]
Just a hint: I found on other esp32 projects that they had Problems when more than one ntp is set. But maybe the library solved this Problem already...
Reducing the ntp to one solved the Problem on those oder Devices without an Update.

**Comment by caco3** [comment]
see also https://github.com/jomjol/AI-on-the-edge-device/issues/1283

I think we should add a check before ever run and try NTP again when the year is still on 1970.

**Comment by caco3** [comment]
Hopefully this gets fixed with https://github.com/jomjol/AI-on-the-edge-device/pull/1364
