### ISSUE TITLE
GPIO Settings not working

### ISSUE THREAD

**Issue by klkl140** [jomjol/AI-on-the-edge-device#1299]
### The Problem

Hello, when I switch on the GPIO settings in the config.ini there is no working flash light any more. Even when GPIO4 is activated for using the build-in flash LED it does not work. (Using GPIO12 does not work either.) When I switch off the GPIO settings, the internal flash-LED is working like it should. Im using 12.0.1 and never tried this with older FW versions.  Any ideas? Thanks in advance Klaus

### Version

12.0.1

**Comment by caco3** [comment]
can you try with older firmware?
I don't think we changed anything in the last release.

**Comment by klkl140** [comment]
Am I able to downgrade without problems? Or are there special things to keep in mind.
I ask cause the update to 12.0.1 was a bit spezial

**Comment by caco3** [comment]
Please reopen once you can provide more information.
