### ISSUE TITLE
Where is the on-device ML code?

### ISSUE THREAD

**Issue by AndreaPi** [jomjol/AI-on-the-edge-device#130]
As per subject. Your project uses TFLite, but where is the TFLite code, which runs on the device, stored in this repository? For example, there's a weight file for the neural network, but there's no code for the NN architecture and training. Where can I find it?

**Comment by jomjol** [comment]
For running on the device you find two components in the code:

/code/component/tfmicro:
* code to run the CNN-files (extracted from TensorFlow Lite)

/code/component/jomjol_tfliteclass:
* c++ library for easy using of tflite files
