### ISSUE TITLE
Kein Kamerabild mehr

### ISSUE THREAD

**Issue by Kasper027** [jomjol/AI-on-the-edge-device#1308]
### The Problem

Hey. Ich habe ein Problem mit der Kamera.
Ich habe alles erstmal eingerichtet. Das hat auch soweit alles funktioniert. Nachdem ich nun die Konfig abgespeichert habe, sehe ich kein Kamerabild mehr.
![image](https://user-images.githubusercontent.com/35900030/200823051-5c94fb8c-666f-478c-8d7b-0ca16dfa52e7.png)

Nun geht auch unter neues Referenzbild erstellen die kamera nicht mehr. Lösche ich alles von der SD-Karte, flashe den ESP neu dann läuft alles erstmal wieder. Woran kann es liegen?
Version ist die 12.0.1 GIT-Revision dfe2c46

### Version

V12.0.1

**Comment by jomjol** [comment]
Ist kein typischer Firmware Fehler --> erstmal einen harten Reset testen (Strom weg!)
Wenn das auch nicht hilft, bitte das Logfile posten.

**Comment by caco3** [comment]
Allenfalls auch mal in den Developertools deines Webbrowser nachschauen, ob er das Bild nicht laden kann. Je nach Webbrowser lasen sich die Tools mit Shift-F12 öffnen.

**Comment by stefanbode** [comment]
Ich habe ein ähnliches Problem gehabt als ich das Format von VGA auf QVGA order was das war gestellt. habe. Mit VGA war alles wieder super.

**Comment by Kasper027** [comment]
ich habe es nun gelöst bekommen. Ich habe als erstes die 10.3 installiert. Damit lief es dann. Danach auf auf und dann auf 12 über ota geupdatet. Nun läuft es seit fast 2 Tagen aktuell ohne Fehler.
Wie sollten die Referenzen generell gesetzt werden? Eher größer oder genau so groß, wie das eig Symbol/Zeichen ist? Ich habe das gefühl, dass es mit größeren bildausschnitten besser und stabiler läuft als mit kleineren

**Comment by caco3** [comment]
> ich habe es nun gelöst bekommen. Ich habe als erstes die 10.3 installiert. Damit lief es dann. Danach auf auf und dann auf 12 über ota geupdatet. Nun läuft es seit fast 2 Tagen aktuell ohne Fehler.

Siehst Du Unterschiede in der Config?

> Wie sollten die Referenzen generell gesetzt werden? Eher größer oder genau so groß, wie das eig Symbol/Zeichen ist? Ich habe das gefühl, dass es mit größeren bildausschnitten besser und stabiler läuft als mit kleineren

Ich denke, sie müssen vor allem etwas mit gutem Kontrast enthalten, das eindeutig ist.
