### ISSUE TITLE
Recognition while digits are turning

### ISSUE THREAD

**Issue by georgbachmann** [jomjol/AI-on-the-edge-device#1309]
### The Problem

I am seeing this problem quite often. My digits turn, and then ai-on-the-edge cannot compute the correct values any more. Is there a way to fix this? Am I missing some settings? Do I need to choose an other model in settings? If so, which one would be better? Here's a screenshot of my problem

<img width="863" alt="Bildschirm­foto 2022-11-09 um 17 34 30" src="https://user-images.githubusercontent.com/893113/200887668-e3bd81cf-252a-4714-981b-e805423baded.png">

### Version

v12.0.1

**Comment by jomjol** [comment]
Please find advice in the wiki: https://github.com/jomjol/AI-on-the-edge-device/wiki/Choosing-the-Model

**Comment by georgbachmann** [comment]
Awesome! Thanks!
My models though have different name in the UI?
Those are the available values.
<img width="267" alt="Bildschirm­foto 2022-11-10 um 08 08 34" src="https://user-images.githubusercontent.com/893113/201023446-d4e15b3d-a3cc-4430-a0ab-5947bca73aa1.png">
Nothing with something like 100 or cont inside the name.
Thanks for your help!

**Comment by caco3** [comment]
are yoo really on 12.0.1?
And also updated the WebUI?

the "ana" should not be shown in the list on the digital section...

**Comment by georgbachmann** [comment]
@caco3 yes... should be... i did update yesterday and this is how the info page looks for me

<img width="510" alt="Bildschirm­foto 2022-11-10 um 13 53 06" src="https://user-images.githubusercontent.com/893113/201096763-9869b4a2-ebd3-423d-b7ef-640752d3a3dd.png">

**Comment by caco3** [comment]
the model filter does not work because it it expects a dash behind "ana", see https://github.com/jomjol/AI-on-the-edge-device/pull/939

but that is not the cause of your problems!

**Comment by georgbachmann** [comment]
ok... so but would one of the model i get suggested improve my result? 
and is my installed version ok like so?

**Comment by jomjol** [comment]
you still have the older names tflite-files.
You can download the newest one out of the rolling version: https://github.com/jomjol/AI-on-the-edge-device/tree/rolling/sd-card/config
Upload them via the FileManager to the /config directory on the device and you should see them in the configuration.

**Comment by georgbachmann** [comment]
Cool! I will give the other models a try and see it that helps! Thanks!
I'll reopen this issue if I still have problems if that's fine with you!
Thanks for all your work on this project! It's really cool!
