### ISSUE TITLE
USB Socket - Which Socket

### ISSUE THREAD

**Issue by Maddin2020** [jomjol/AI-on-the-edge-device#131]
Hello together, first this is a very great project. Everythink work fine but i have one question. Which type from the USB Socket is the right version for use it with the 3D Case. I have try 2 types but both are to big.

Can give me anybody a link.

Thank a lot.

**Comment by moeskerv** [comment]
Not a direct answer, but If you don't want to hassle with the USB connector, you might use a ESP32-CAM-MB board. I made a remix on thingiverse to fit the housing to such a board. The ESP32-CAM-MB board brings a USB connector which can be used to power and program the ESP32-CAM.

https://www.thingiverse.com/thing:4778435

**Comment by TheLion** [comment]
I guess you also don't need the 2200uF capacitor when using the MB board for power?

**Comment by jomjol** [comment]
@TheLion 
I'm not sure about this. The capacitor is just stabilizing the power supply. Maybe this is not needd in case of the MB board.

**Comment by TheLion** [comment]
> @TheLion
> I'm not sure about this. The capacitor is just stabilizing the power supply. Maybe this is not needd in case of the MB board.

When programming the ESP32CAM with the UART connector, the power seemed more stable than with the direct-connected 5v power supply. 
But that's just my opinion. :wink:

**Comment by TheLion** [comment]
Just an update.

When powering the ESP32CAM through the ESPCAM32-MB, the board is much more stable, without a 2200uF capacitor.
