### ISSUE TITLE
MQTT password can not contain =

### ISSUE THREAD

**Issue by prutseltje** [jomjol/AI-on-the-edge-device#1313]
### The Problem

Having a password with a = sign in it will cutoff the password after the = sign.

RanDomP=fd will become RanDomP

### Version

Branch: 'HEAD', Tag: 'v12.0.1', Revision: dfe2c46

### Expected Behavior

Password should be able to contain = signs

**Comment by caco3** [comment]
The problem is the way we store it in the config file as we use `key=value`, see https://github.com/jomjol/AI-on-the-edge-device/blob/master/sd-card/config/config.ini#L60

Will need to check if we can encode it somehow.

**Comment by prutseltje** [comment]
Perhaps it is possible to escape it with quotes?
Or split key/value only on the first = sign

**Comment by caco3** [comment]
can you test if it works with the most top build in https://github.com/jomjol/AI-on-the-edge-device/actions?query=branch%3Asupport-white-space-and-equal-in-passwords?

You will need to update the firmware as well as the Web UI!

**Comment by prutseltje** [comment]
I can confirm this works as expected now.

**Comment by caco3** [comment]
thanks!

Then i add it to the next release => https://github.com/jomjol/AI-on-the-edge-device/pull/1327
