### ISSUE TITLE
Issues with recognised value sanity check

### ISSUE THREAD

**Issue by Kimble8650** [jomjol/AI-on-the-edge-device#1315]
### The Problem
Yesterday as my meters m3 was about to roll from **640m3** to **641m3**, the recognised value jumped by about **1m3**. That is in a sense understandable as my meter maybe is not fully aligned with training data. Checking the recognition -tab I noticed that the **0** was recognised as **0.9** and then probably rounded to **1** -> **641m3.**
So I thought that this issue would resolve by itself after I actually roll over the **641m3** mark. 

To my surprise, the issue was gone before that. At **640,9028m3** the value was again resolved correctly. When checking again the recognition tab, the **0** was now resolved to **1.0**, but some decision process decided that it must be wrong, and reverted the value as **640m3**. 

### Version
v12.0.1

### Expected Behavior
The values should gracefully handle the obvious misinterpretation during the roll over.

### Additional Context
I have attached the saved logs right before the error, and right after the error was resolved
[waterMeterLogs.txt](https://github.com/jomjol/AI-on-the-edge-device/files/9978491/waterMeterLogs.txt)

I have the **CheckDigitIncreaseConsistency** set to true.

From this I would deduce, that there is an issue with some value sanity checks. Maybe this kind of issue could be avoided with checking if the value is close to rolling over (like **.750 -> .000**) and check for sudden jumps the size of **1m3**?

Being able to manually update the value from the UI would also help get through any persistent errors. Then when the error is resolved, one would not get a sudden jump of several hundred litres in home assistant.

**Comment by stefanbode** [comment]
CheckDigitIncreaseConsistency is a beast. You should better try with FALSE. Special with rolling digits this make things most times worse

**Comment by Kimble8650** [comment]
Haha :D
Ok, that is good to know! Thanks!
I think I will, for now, keep it set to true and try changing it to false the next time this happens to see if that helps.

**Comment by jomjol** [comment]
The problem with the postprocessing algo is, that you cannot find settings, that do fit for all meters at once. Therefore in the time of change, there is some time of wrong results, that will vanish by themselfs.
One option would be to make the parameters adaptable for different meters. Sounds easy, but is difficult in detail.

I'll close this issue for the time beeing, as there is currently nothing to do about.

**Comment by Kimble8650** [comment]
After a few months of tinkering, I'm returning here to reflect on my experiences =). I'm still consistently having an issue, with the rollover of the digits. At around x.8 the model rounds the value to x+1, which obviously leads to a "rate too high" -error. Would it be possible to add a parameter in the expert mode, to fine tune the rounding threshold to suite ones specific needs?
Something like "Rounding threshold = 0.05" Which would round x.95 to x+1? So if the last digit in 100 is interpreted as 0.95, the last digit would be rounded to 1 and the result would be 101m3.

I don't know at all is this even remotely feasible, but if it were, I think it would reduce the number of issues people are experiencing. @jomjol @haverland @caco3

**Comment by haverland** [comment]
Do you tried AnalogDigitalTransitionStart in version 13.0.8? It should fix it in almost all situations. See https://github.com/jomjol/AI-on-the-edge-device/wiki/Watermeter-specific-analog---digital-transition too.
