### ISSUE TITLE
New "semi" digital water meters with rotating analog numbers

### ISSUE THREAD

**Issue by stefanbode** [jomjol/AI-on-the-edge-device#1316]
I got a new meter where the 0.001 measurement behaves different. As you can see on the foto the SCALE itself rotates and the value is the one on the scale at the top. Beside the complex reading of all of the plastic ribs this is another issue.

Maybe I can read this digit a an "digital" value. But how do I "assemble" it back into ONE number. I assume in germany at least we will see this now comming more often because this is the new "standard" if your watermeter gets replaced. Any help or idea welcome.

The target value to recognize: 8.56515
The air bulb is moving and hopefully disappear in one or two weeks

![image](https://user-images.githubusercontent.com/16225290/201061404-b2ada309-d18f-4ce6-a0e7-4e48fcdf411a.png)

**Comment by jomjol** [comment]
This type of mixed reading of the analog values is not supported with this currently. You could readout every pointer and digit as a single number and put everything together on your local server.
As this is not planned to be implemented I close the issue.
