### ISSUE TITLE
Ethernet Connection possible?

### ISSUE THREAD

**Issue by Waschtli** [jomjol/AI-on-the-edge-device#132]
What a nice project. Great Idea. I've not tried it yet but i will do it soon. Sure. It woul be even greater if a wired LAN connection would be possible.
Here is the background for that.
My aim is to read out our water meter automatically and prefer the communication via mqtt. The mqtt-broker Mosquitto is the central instance of our smart home system. Zigbee2MQTT and an OpenMQTTGatway for 433 MHz is already connected. This backbone can be controlled by different home automation systems. Currently I use FHEM but switching to another system is relatively easy. I prefer wired connections because WLAN will preserved for mobile devices and is switched off during nighttime an if no one is at home.

**Comment by jomjol** [comment]
Hi @Waschtli,
in principle, the code is flexible enough to integrate another interface. You would need to code just another unit like the MQTT-adapter, just for ethernet interface and then modify the hardware corespondingly. Unfortunatly I do not have the capacity to do it myself, but if you are able to to so, I would be happy to support you.
Best regards,
  jomjol

**Comment by moeskerv** [comment]
I had the same idea, but at the end I used WiFi. The water consumption during WiFi off isn't that high and as the reading is always an entire reading and not incremental, nothing gets lost. Reconnect in the morning when Wifi is switched on again works stable.

**Comment by jomjol** [comment]
Currently no activities planned from my side

**Comment by Waschtli** [comment]
Hi Jomjol,

I made the device, as promised. Actually I didn't change anything on the code. It works as described. Many thanks for your work.
The hardware is made from a DN90 HT-Tube, which snuggly fit on the water meter, when th lid is detached. The electronic is mounted on a plywood disc inside the tube. No big deal at all. Attached are some images.
It would be good to add two points to the wiki. Firstly the focus of the camera needs to be adjusted. A distance of 10 cm allows for an image, which contains all necessary items. From the original focus of the ESP32-Cam I need around one turn of the lens counterclockwise to get a sharp image.
Our water meter have only one distinct alignment mark. The other one was made with an Edding pen as visible on the image.
Secondly the mapping of the Digital ROIs to the digit could be explained more clear. My working configuration is:
ROI 1, named "digit5" is the most significant digit standing for 10^5 m^3, following logically to lead significant digit ROI 5, named "digit1", standing for 1 m^3. This has been a little bit fiddly because our new water meter shows zeros except of the 1 m^3-digit.
I will try to ad a wired LAN port, but I will try it with an normal ESP32 first.
Another option would be the integration into a MySensors Network preferably with RS485 connectivity. But that is a different story.

With very kind regards

Waschtl

Am 2. März 2021 07:33:32 MEZ schrieb jomjol ***@***.***>:

**Comment by duffy6** [comment]
Hey Waschtli,

ESP32cam with LAN, that‘s what I wanna do too!
What Hardware did you use?
I can nit figure out how which hardware to use for the LAN-Part?
Did you manage to use PoE?

greetz

**Comment by raindancer2204** [comment]
Hi gibt es jetzt ein Board das mit Ethernet funktioniert?

**Comment by SybexX** [comment]
https://github.com/jomjol/AI-on-the-edge-device/discussions/2963#discussioncomment-13934075
