### ISSUE TITLE
Feature Request: Optional GPIO for external flash/lighting

### ISSUE THREAD

**Issue by DrCoolHands** [jomjol/AI-on-the-edge-device#133]
Would it be possible to add in the option to use a GPIO pin to trigger supplementary lighting?
The onboard ESP32-Cam flashlight causing significant glare for my usecase and I'd rather use a separate set of LEDs.

Thanks!!

**Comment by jomjol** [comment]
Technical possible, currently you can activate a external PIN with an http command: `/GPIO?GPIO=12&Status=high/low`

Currently I'm lacking of time to further implement it in the automated flow.

**Comment by jomjol** [comment]
Due to lack of capacity this is not followed currently. In order to not forget it, it is added to the feature request page: https://github.com/jomjol/AI-on-the-edge-device/blob/master/FeatureRequest.md

Meanwhile this issue will be closed, as it is not active currently.

**Comment by jomjol** [comment]
Implemented in v8.0.0
