### ISSUE TITLE
MQTT: Read value equals raw value

### ISSUE THREAD

**Issue by peterimnetz** [jomjol/AI-on-the-edge-device#134]
MQTT topic in case of negative value would be much more informative if "raw value" and "checked value" are given in string.

Here is one example from actual information:
"Negative Rate - Returned old value - read value: 422.3001 - raw value: 00422.3001"

Would be much more informative if information as follow is send:
"Negative Rate - Returned old value - read value: 422.3001 - **checked** value: **422.3009**"

**Comment by jomjol** [comment]
I have added this in the newest rolling from today.

**Comment by peterimnetz** [comment]
Thanks a lot!
