### ISSUE TITLE
Gas meter 

### ISSUE THREAD

**Issue by moeskerv** [jomjol/AI-on-the-edge-device#135]
I meanwhile built a gas meter adapter and its working quite well. If possible I would also like to add some data for training after some time of operation. I enabled logging for it.

Would it possible for me to do some training on my own? 

For those who are interested, a adapter for a Pipersberg G4 RF1 meter can be found here: https://www.thingiverse.com/thing:4785777

![Screenshot 2021-03-06 183341_](https://user-images.githubusercontent.com/15142022/110216057-4a8b0980-7ead-11eb-897e-a898ae192454.png)

![Screenshot 2021-03-06 180722](https://user-images.githubusercontent.com/15142022/110215990-e7997280-7eac-11eb-909f-99610f6a4e06.png)

Glare/reflections have been a challenge and required to relocate the ESP32-CAM LED. 

![Screenshot 2021-03-06 184455](https://user-images.githubusercontent.com/15142022/110216052-4232ce80-7ead-11eb-92f5-5598164e9209.png)

Thanks a lot!
BR, Volker

**Comment by nanosonde** [comment]
@moeskerv 
The link to the adapter does not work:
404.

**Comment by jomjol** [comment]
Great adapter, thanks for sharing!

Own training is possible, but needs some knowledge about TensorFlow/Python. Code is published here:
https://github.com/jomjol/neural-network-digital-counter-readout
https://github.com/jomjol/neural-network-analog-needle-readout

But if you send the images to me, too, I will incorporate them in future versions, that helps other users as well.

Thanks,
  jomjol
