### ISSUE TITLE
New Training Data (Iskra T3F-01S1) for dig-class100

### ISSUE THREAD

**Issue by awirtz** [jomjol/AI-on-the-edge-device#1350]
### Files

There seem to be similar fonts in your training data, but when I checked the images within the Tenth-of-a-step-meter-digit project, I wasn't able to find them. I've created my own model from these image captures and it massively has improved the recognition rate of my power meter (almost error free). Feel free to use them, works like a charm for me.

[Iskra T3F-01S1.zip](https://github.com/jomjol/AI-on-the-edge-device/files/10006970/Iskra.T3F-01S1.zip)

**Comment by jomjol** [comment]
Included in the newest version: https://github.com/jomjol/AI-on-the-edge-device/raw/rolling/sd-card/config/dig-cont_0600_s3.tflite

Thanks for your data!
