### ISSUE TITLE
Manual start the reading process through REST API

### ISSUE THREAD

**Issue by caco3** [jomjol/AI-on-the-edge-device#1351]
some would like to trigger the reading through REST API: https://github.com/jomjol/AI-on-the-edge-device/discussions/1051#discussioncomment-4142484
and MQTT: https://github.com/jomjol/AI-on-the-edge-device/discussions/1410

**Comment by Slider0007** [comment]
Please find more information in the WIKI: 
- [REST API](https://github.com/jomjol/AI-on-the-edge-device/wiki/REST-API)
- [MQTT API](https://github.com/jomjol/AI-on-the-edge-device/wiki/MQTT-API)

**Comment by caco3** [comment]
@Slider0007 Thank you for extending the documentation! I also added some explanations to it, but there is still much more to do.

**Comment by caco3** [comment]
The `save` REST API is not clear to me, what means delay and which image gets saved where?

**Comment by Slider0007** [comment]
@caco3 : I agree more details for the respective handler/topics would be helpful. Therefore I used highlights for every item, so additional info can be added easily.

I'm haven't used/tested every REST handler extensively, just did a quick sneak.
For my understanding "save" is like capture with the possibility to save the image to SD card relative to root of SD card. Delay seems to delay the capture.

**Comment by caco3** [comment]
> Therefore I used highlights for every item, so additional info can be added easily.

I was so free to replace your quotes with more inlined text (4 whitespaces). This way it gets inlined correctly automatically
