### ISSUE TITLE
Stop recognizing numbers

### ISSUE THREAD

**Issue by lakusz1github** [jomjol/AI-on-the-edge-device#1359]
### The Problem

Device stop recognize numbers.

### Version

12.0.1

### Screenshots

![obraz](https://user-images.githubusercontent.com/82530567/202185693-b80d3bd4-489f-43fa-a77b-c767361b9852.png)

### Logfile

no logs file

**Comment by jomjol** [comment]
More info needed! I don't see that something has stopped.

**Comment by caco3** [comment]
please make sure the alignment ares (red) do not overlap the numbers!

**Comment by caco3** [comment]
Please reopen once you can provide more information.
