### ISSUE TITLE
Question: Case Tube STL

### ISSUE THREAD

**Issue by tunip** [jomjol/AI-on-the-edge-device#136]
Hello,

great project. My first dry run with a photo of my watermeter printed on paper was fine. Next step is the case. On thingiverse you have the case for the ESP32-CAM. But where can I find the tube (STL) between the watermeter and the ESP32-CAM? Could you share this also? Size could be easily adjusted in the slicer.

Many thx

**Comment by tunip** [comment]
Found it :-)

**Comment by dilmash** [comment]
> Found it :-)

Good Job! But where did you find it?

**Comment by tunip** [comment]
@dilmash
https://www.thingiverse.com/thing:4573481
