### ISSUE TITLE
Hilfe bei Digitizer - AI on the edge - WasserUhr

### ISSUE THREAD

**Issue by Brutschi** [jomjol/AI-on-the-edge-device#1363]
### The Problem

Ich habe seit kurzem folgendes Problem die Kamera zeigt nur ein schwarzes Bild mit Blauen Vierecken.
wenn ich ein neues Referenzbild anlege wir die Wasseruhr korrekt angezeigt. bin leider absoluter Neuling auf dem gebiet und würde mich über eure Unterstützung sehr freuen-
HEAD
Grit Tag v12.0.1
Revision dfe2c46
Build Time 29-9-2022

### Version

Revision dfe2c46

### Screenshots

![waaseruhr](https://user-images.githubusercontent.com/118440863/202428475-b2d26ad8-d32f-401e-a60d-927adfaa95c1.JPG)

**Comment by caco3** [comment]
Bitte logfile mitliefern!

**Comment by Brisk007** [comment]
Hallo, ich habe das gleiche Problem.

**Comment by caco3** [comment]
Ohne Logfile und Config ist es unmöglich, das Problem verstehen zu können! => Bitte nachliefern!

**Comment by Brisk007** [comment]
Die Option "Protokolleintrag" wird nicht auf dem ersten Gerät gespeichert. Der com-Port zeigt an, dass wenig Speicher vorhanden ist...
[Log COM.txt](https://github.com/jomjol/AI-on-the-edge-device/files/10048090/Log.COM.txt)

Auf der zweiten ist dies in der Protokolldatei. Klingt nach einem Kameraproblem... Jedoch, die Referenzfoto-Kamera tut gut.
[Log1.txt](https://github.com/jomjol/AI-on-the-edge-device/files/10048081/Log1.txt)

**Comment by jomjol** [comment]
Logfile ist da eindeutig:

1) Zu wenig PSRAM (2MB, statt benötigter 4MB) --> nicht verwendbar
2) Problem mit der Kamera. Manchmal hilft ein aus- und wiedereinstecken des Kameramoduls

Etwas merkwürdig, wenn der Konfigurationsmodus noch funktioniert hat, gab es bisher noch nicht. Trotzdem kein Thema der Firmware.

**Comment by Brisk007** [comment]
Sagen Sie mir bitte.
Warum könnte es so sein:

1. In Zeile Nummer 17
     _[0;32mI (46) boot.esp32: SPI Flash Size : 4MB_
und dann in Zeile 170
     _Not enough OSRAM available. Expected 4.194.304 MByte - available: 2094966_

2. In Zeile Nummer 75
     _[0;32mI (3548) camera: Detected camera at address=0x30_
und dann die Nummer 417
      _[0;31mE (37388) CImageBasis: Image with size 0 loaded --> reboot to be done! Check that your camera module is working and connected properly._

     _[Log2.txt](https://github.com/jomjol/AI-on-the-edge-device/files/10050631/Log2.txt)_

Darüber hinaus wird ein Beispielfoto von der Kamera erstellt und die Standorteinstellungen der Ziffern sind daher verfügbar.

Ich denke, das sind Wunder!

Ich verstehe, dass die Firmware höchstwahrscheinlich in Ordnung ist, aber speziell auf diesen Modulen (ich habe drei davon) ist sie wahrscheinlich fehlerhaft.

**Comment by jomjol** [comment]
1. SPI Flash Size = RAM für den internen Speicher - wird für die Firmware verwendet
PSRAM = erweiterter Speicherchip, anderer Speicher wie RAM. 
Wichtig: es wird 4 MB RAM **UND** 4 MB PSRAM benötigt

2. Die Kamera läßt sich anscheinden initialiseren (_[0;32mI (3548) camera: Detected camera at address=0x30_)
In Zeile 414 wird dann zum erstenmal im Flow tatsächlich ein Bild von der Kamera abgefragt. Bei der Prüfung des Bildes stellt die Software fest, dass es eine Größe von "0" hat und daher defekt sein muss. 
Dies ist leider ein oftmals beobachteter Fehler dieser Module. Genau aus diesem Grund wurde die Prüfung auf die Größe eingebaut.

Leider läßt sich das Problem (2) nicht über die Firmware verbessern. Wir updaten regelmäßig die Kameratreiber. Diese sind nicht selbst geschrieben. Leider funktionieren sie aber immer noch nicht immer perfekt.

**Comment by caco3** [comment]
Ich schliesse das mal.

Bei Bedarf bitte wieder öffnen und mit der neusten Firmware ein Log hinzufügen
