### ISSUE TITLE
Installation klappt nicht

### ISSUE THREAD

**Issue by Snago636** [jomjol/AI-on-the-edge-device#137]
Hallo,

ich bekomme es irgendwie nicht zum laufen. 
Ich habe es mit python directly und Flash Tool from Espressif probiert.

Es wird alles erfolgreich geflasht. Wenn ich den ESP32 dann normal starte sehe ich im Monitor das er ständig eine schleife durchläuft. Ich weiß nicht was ich noch machen soll.

16:23:42.809 -> rst:0x8 (TG1WDT_SYS_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
16:23:42.809 -> configsip: 0, SPIWP:0xee
16:23:42.809 -> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
16:23:42.809 -> mode:DIO, clock div:2
16:23:42.809 -> load:0x3fff0030,len:4
16:23:42.809 -> load:0x3fff0034,len:7140
16:23:42.809 -> load:0x40078000,len:13856
16:23:42.809 -> load:0x40080400,len:4052
16:23:42.809 -> entry 0x40080688
16:23:42.809 -> [0;32mI (58) boot: ESP-IDF 3.40100.200827 2nd stage bootloader[0m
16:23:42.809 -> [0;32mI (58) boot: compile time 19:51:06[0m
16:23:42.809 -> [0;32mI (58) boot: chip revision: 1[0m
16:23:42.809 -> [0;32mI (62) boot_comm: chip revision: 1, min. bootloader chip revision: 0[0m
16:23:42.809 -> [0;32mI (69) boot.esp32: SPI Speed      : 40MHz[0m
16:23:42.809 -> [0;32mI (74) boot.esp32: SPI Mode       : DIO[0m
16:23:42.809 -> [0;32mI (78) boot.esp32: SPI Flash Size : 4MB[0m
16:23:42.809 -> [0;33mW (83) boot.esp32: PRO CPU has been reset by WDT.[0m
16:23:42.809 -> [0;33mW (88) boot.esp32: WDT reset info: PRO CPU PC=0x400803c0[0m
16:23:42.809 -> [0;33mW (94) boot.esp32: WDT reset info: APP CPU PC=0x4008e7db[0m
16:23:42.809 -> [0;32mI (100) boot: Enabling RNG early entropy source...[0m
16:23:42.809 -> [0;32mI (106) boot: Partition Table:[0m
16:23:42.809 -> [0;32mI (109) boot: ## Label            Usage          Type ST Offset   Length[0m
16:23:42.809 -> [0;32mI (117) boot:  0 nvs              WiFi data        01 02 00009000 00004000[0m
16:23:42.809 -> [0;32mI (124) boot:  1 otadata          OTA data         01 00 0000d000 00002000[0m
16:23:42.809 -> [0;32mI (132) boot:  2 phy_init         RF data          01 01 0000f000 00001000[0m
16:23:42.809 -> [0;32mI (139) boot:  3 ota_0            OTA app          00 10 00010000 001db000[0m
16:23:42.809 -> [0;32mI (147) boot:  4 ota_1            OTA app          00 11 001f0000 001db000[0m
16:23:42.809 -> [0;32mI (154) boot: End of partition table[0m
16:23:42.809 -> [0;32mI (159) boot_comm: chip revision: 1, min. application chip revision: 0[0m
16:23:42.809 -> [0;32mI (166) esp_image: segment 0: paddr=0x00010020 vaddr=0x3f400020 size=0x4c730 (313136) map[0m
16:23:42.951 -> [0;32mI (310) esp_image: segment 1: paddr=0x0005c758 vaddr=0x3ffb0000 size=0x038c0 ( 14528) load[0m
16:23:42.951 -> [0;32mI (318) esp_image: segment 2: paddr=0x00060020 vaddr=0x400d0020 size=0x15f514 (1438996) map[0m
16:23:43.560 -> [0;32mI (940) esp_image: segment 3: paddr=0x001bf53c vaddr=0x3ffb38c0 size=0x01860 (  6240) load[0m
16:23:43.560 -> [0;32mI (944) esp_image: segment 4: paddr=0x001c0da4 vaddr=0x40080000 size=0x00404 (  1028) load[0m
16:23:43.560 -> [0;32mI (948) esp_image: segment 5: paddr=0x001c11b0 vaddr=0x40080404 size=0x1ee54 (126548) load[0m
16:23:43.748 -> [0;32mI (1035) boot: Loaded app from partition at offset 0x10000[0m
16:23:43.748 -> [0;32mI (1036) boot: Disabling RNG early entropy source...[0m
16:23:43.748 -> [0;32mI (1036) psram: This chip is ESP32-D0WD[0m
16:23:43.748 -> [0;32mI (1042) spiram: Found 64MBit SPI RAM device[0m
16:23:43.748 -> [0;32mI (1045) spiram: SPI RAM mode: flash 40m sram 40m[0m
16:23:43.748 -> [0;32mI (1051) spiram: PSRAM initialized, cache is in low/high (2-core) mode.[0m
16:23:43.748 -> [0;32mI (1058) cpu_start: Pro cpu up.[0m
16:23:43.748 -> [0;32mI (1062) cpu_start: Application information:[0m
16:23:43.748 -> [0;32mI (1067) cpu_start: Project name:     esp32cam-server-only[0m
16:23:43.748 -> [0;32mI (1073) cpu_start: App version:      0.0.9.3[0m
16:23:43.748 -> [0;32mI (1078) cpu_start: Compile time:     Jan 20 2021 19:48:33[0m
16:23:43.748 -> [0;32mI (1084) cpu_start: ELF file SHA256:  b9ffc04c8ab59a15...[0m
16:23:43.748 -> [0;32mI (1090) cpu_start: ESP-IDF:          3.40100.200827[0m
16:23:43.748 -> [0;32mI (1096) cpu_start: Starting app cpu, entry point is 0x40081c30[0m
16:23:43.748 -> [0;32mI (0) cpu_start: App cpu up.[0m
16:23:44.686 -> [0;32mI (1988) spiram: SPI SRAM memory test OK[0m
16:23:44.686 -> [0;32mI (1988) heap_init: Initializing. RAM available for dynamic allocation:[0m
16:23:44.686 -> [0;32mI (1989) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM[0m
16:23:44.686 -> [0;32mI (1995) heap_init: At 3FFC2AC8 len 0001D538 (117 KiB): DRAM[0m
16:23:44.686 -> [0;32mI (2001) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM[0m
16:23:44.686 -> [0;32mI (2007) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM[0m
16:23:44.686 -> [0;32mI (2014) heap_init: At 4009F258 len 00000DA8 (3 KiB): IRAM[0m
16:23:44.686 -> [0;32mI (2020) cpu_start: Pro cpu start user code[0m
16:23:44.686 -> [0;32mI (2025) spiram: Adding pool of 4096K of external SPI memory to heap allocator[0m
16:23:44.686 -> [0;32mI (2050) spi_flash: detected chip: generic[0m
16:23:44.686 -> [0;32mI (2051) spi_flash: flash io: dio[0m
16:23:44.686 -> [0;32mI (2051) cpu_start: Starting scheduler on PRO CPU.[0m
16:23:44.686 -> [0;32mI (0) cpu_start: Starting scheduler on APP CPU.[0m
16:23:44.686 -> [0;32mI (2059) spiram: Reserving pool of 32K of internal memory for DMA/internal allocations[0m
16:23:44.686 -> Do Reset Camera
16:23:44.686 -> [0;32mI (2069) gpio: GPIO[32]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 [0m
16:23:46.798 -> Init Camera
16:23:46.798 -> [0;32mI (4079) gpio: GPIO[5]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
16:23:46.798 -> [0;32mI (4079) gpio: GPIO[18]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
16:23:46.798 -> [0;32mI (4079) gpio: GPIO[19]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
16:23:46.798 -> [0;32mI (4089) gpio: GPIO[21]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
16:23:46.798 -> [0;32mI (4099) gpio: GPIO[22]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
16:23:46.798 -> [0;32mI (4109) gpio: GPIO[23]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
16:23:46.798 -> [0;32mI (4119) gpio: GPIO[25]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
16:23:46.798 -> [0;32mI (4129) gpio: GPIO[34]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
16:23:46.798 -> [0;32mI (4139) gpio: GPIO[35]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
16:23:46.798 -> [0;32mI (4149) gpio: GPIO[36]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
16:23:46.798 -> [0;32mI (4159) gpio: GPIO[39]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
16:23:46.798 -> [0;32mI (4169) sccb: pin_sda 26 pin_scl 27
16:23:46.798 -> [0m
16:23:46.798 -> [0;32mI (4169) gpio: GPIO[32]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 [0m
16:23:46.986 -> [0;32mI (4319) camera: Detected OV2640 camera[0m
16:23:46.986 -> [0;32mI (4319) camera: Allocating 1 frame buffers (150 KB total)[0m
16:23:46.986 -> [0;32mI (4339) camera: Allocating 150 KB frame buffer in OnBoard RAM[0m
16:23:47.501 -> [0;32mI (4909) connect_wlan_main: Initializing SD card[0m
16:23:47.595 -> [0;31mE (4929) sdmmc_common: sdmmc_init_ocr: send_op_cond (1) returned 0x107[0m
16:23:47.595 -> [0;31mE (4929) connect_wlan_main: Failed to initialize the card (263). Make sure SD card lines have pull-up resistors in place.[0m
16:23:47.595 -> [0;32mI (4939) server_ota: Start CheckOTAUpdateCheck ...[0m
16:23:47.595 -> Start CheckOTAUpdateCheck ...
16:23:47.595 -> [0;32mI (4959) server_ota: SHA-256 for the partition table: : 9d4a2809ae90fb20709a8ca3dd3ac3462e1e73286bcd31b689060c91de06fa3a[0m
16:23:47.642 -> [0;32mI (5019) server_ota: SHA-256 for bootloader: : 15f52f58b38b015f8d77a7fd637080c32b397905d47e4ca1bf5bbf1c6abe34bf[0m
16:23:48.356 -> [0;32mI (5749) server_ota: SHA-256 for current firmware: : 9e85de4055be332de6ebd46bca00b10d3bbdb260efcb2c79c0f0bfc418eeb3da[0m
16:23:48.356 -> CheckOTAUpdate Partition: ESP_OK
16:23:48.404 -> File is locked: /sdcard/wlan.ini - wait for 1
16:23:48.404 -> Logfile opened: 

Ich erkenne in dem Log nicht wirklich was. Das einzige was ich mir vorstellen könnte, ist die info mit der SD card. Würde mich freuen wenn ihr mir vielleicht weiterhelfen könntet.

gruß Andy

**Comment by jomjol** [comment]
Hi Andy,

sieht nach einem Problem mit der SD-Karte aus (siehe 16:23:47.595 ). Es gehen nur SD-Karte mit maximal 16GB und sie müssen mit FAT32 formatiert sein. Wenn er die SD-Karte nicht initialisierne kann, geht er immer wieder irgenwann in einen Reboot.

Gruß,
  jomjol

**Comment by Snago636** [comment]
Vielen dank für die schnelle Antwort. Also ich habe eine 2 GB Sd card mit FAT32. Hatte sie jetzt nochmal formatiert oder neu aufgespielt. Klappt leider auch nicht. Habe jetzt mal das release 5.0.0 probiert. Dieses läuft einwandfrei. Jedoch sobald ich auf die 6.1.0 wechsle geht es nicht mehr. Hat sich da irgendwas bei der SD geändert?

**Comment by Snago636** [comment]
Noch zur Info:
Wenn ich ein OTA update auf 6.1.0 mach und einen restart über die Weboberfläche läuft es auch. Jedoch sobald ich den ESP vom Strom nehme und er richtig neustartet wirft er wieder den Fehler. 
Merkwürdig da es anscheinend nur bei mir nicht geht und nur bei der 6.1.0

**Comment by jomjol** [comment]
Ich habe es jetzt auch probiert und kann deinen Fehler bestätigen! Ist mir aber total neu und unverständlich - ich stehe vor einem Rätsel - zumal du der erste bist, der davon berichtet.

Kannst du vielleicht testhalber mal die "Rolling" installieren? 

Update sobald ich etwas gefunden habe.

**Comment by Snago636** [comment]
Sorry für die dumme Frage aber Rolling?

**Comment by jomjol** [comment]
Konnte das Problem jetzt eingrenzen:
Es scheint an der SD-Karte selbst zu liegen. Zum Testen hatte ich eine bisher nicht gebrauchte Karte verwendet und prompt ist der von dir beschriebene Fehler genauso aufgetreten. Hatte schon angefangen, am Code zu arbeiten. 
Aber zum Glück vorher noch zwei weitere Karten gestestet und mit denen geht es wiederum. Es scheint, dass nicht alle Karten mit dem ESP32 kompatibel sind.
Hast du noch eine andere Karte? Bin interessiert, ob es bei dir das Problem löst.

Beste Grüße,
  jomjol

**Comment by Snago636** [comment]
Wo kann ich die Rolling finden? Dann teste ich das gerne.

gruß Andy

**Comment by jomjol** [comment]
Jetzt haben wir uns überschnitten - siehe meinen Comment von gerade eben - vermutlich die SD-Karte selbst, die nicht kompatibel ist.

**Comment by Snago636** [comment]
Muß ich mal schauen ob ich noch eine kleine SD finde. Ist aber dann komisch das die 5.0.0 ganz normal funktioniert. Oder?

**Comment by jomjol** [comment]
Nicht unbedingt, da ich von Version 5.0 auf 6.0 die SD-Karte auf 1-Wire Anschluss umgestellt habe, damit 2 Pins für externe Beschaltung frei wurden. Müsste mal prüfen, ob das den Unterschied macht.

**Comment by Snago636** [comment]
So hab eine SD gefunden und hat jetzt auch damit problemlos funktioniert.

**Comment by jomjol** [comment]
:-)

**Comment by Github197** [comment]
Ich habe das gleiche Problem. Es betrifft bei mir gleich beide SD-Karten, die ich zur Verfügung habe. Mit Version 5.0.0 läuft alles ohne Probleme!

SD-Karten, die nicht funktionieren:
- SanDisk Ultra 16GB MicroSD HC I
- Transcend SuperMLC 220 8GB MicroSD HC I

**Comment by jomjol** [comment]
@Github197 
Kannst du bitte mal folgende Firmware Version mit deiner SD-Karte testen:
[firmware_zipped.zip](https://github.com/jomjol/AI-on-the-edge-device/files/6215287/firmware_zipped.zip)

Hintergrund: ab Version 6.x.y habe ich den Zugriff auf die SD-Karte modifiziert, damit die GPIOs 12 & 13 frei werden. In dieser speziellen Version habe ich das rückgängig gemacht.

Danke und Gruß,
  jomjol

**Comment by moeskerv** [comment]
So kurios das klingt, aber ich nutze auch die Sandisk Ultra 16GB HC I, die hat auch bei mir erst nicht funktioniert, aber es lag bei mir am Kartenleser: Offenbar sind die Kontakte nicht die Besten, oder waren verdreckt. Ich habe am Ende die Karte einige Male entnommen und wieder eingesteckt. Seitdem funktioniert es seit Wochen Problemlos. Ich habe zwei dieser Karten im Einsatz.

Ich nutze im Moment die Version 6.3.1.

**Comment by Github197** [comment]
> 
> 
> @Github197
> Kannst du bitte mal folgende Firmware Version mit deiner SD-Karte testen:
> [firmware_zipped.zip](https://github.com/jomjol/AI-on-the-edge-device/files/6215287/firmware_zipped.zip)
> 
> Hintergrund: ab Version 6.x.y habe ich den Zugriff auf die SD-Karte modifiziert, damit die GPIOs 12 & 13 frei werden. In dieser speziellen Version habe ich das rückgängig gemacht.
> 
> Danke und Gruß,
> jomjol

Hi jomjol.

Diese neue Version funktioniert bei mir ohne Probleme. Ich habe rebooted und auch die Stromzufuhr unterbrochen. Jedes Mal startet sie wieder. Diese Version ist auch viel performanter und die WLAN-Verbindung stabiler.
Danke! Rene

**Comment by jomjol** [comment]
Eigentlich unterscheided sie sich nur in der Zugriffart auf die SD-Karte (eine Zeile Code!). Der Preis dafür ist, dass ich zwei GPIOs nicht mehr nutzen kann (Feature für einen anderen User). Muss mal schauen, wie ich damit umgehe und ob ich das irgendwie unter einen Hut bekomme.

**Comment by jomjol** [comment]
Ich habe jetzt eine neue Version erstellt (unter Branch Rolling), die den Fehler behebt. Kannst du die vielleicht mal testen und rückmelden, ob diese genauso gut funktioniert, wie die oben gepostete. Die neu Firmware findest du hier:
https://github.com/jomjol/AI-on-the-edge-device/blob/rolling/firmware/firmware.bin

**Comment by Github197** [comment]
> 
> 
> Ich habe jetzt eine neue Version erstellt (unter Branch Rolling), die den Fehler behebt. Kannst du die vielleicht mal testen und rückmelden, ob diese genauso gut funktioniert, wie die oben gepostete. Die neu Firmware findest du hier:
> https://github.com/jomjol/AI-on-the-edge-device/blob/rolling/firmware/firmware.bin

Auch diese Version (6.5.0 Rolling) funktioniert nach Reboot und nach Stromunterbrechung bei mir. :-)

**Comment by jomjol** [comment]
Danke für die Rückmeldung. Dann werde ich sie jetzt in den Master verschieben.

Beste Grüße,
  jomjol
