### ISSUE TITLE
Retake image if error detected

### ISSUE THREAD

**Issue by GitMeTender** [jomjol/AI-on-the-edge-device#1378]
### The Feature

It would be nice if you could create a checkbox/Function in the Config to retake an image if an Error like a Neg-Rate, or an change of the value outside of the specified range was detected - since I only take an image every 30 minutes, a lot of data is lost by misinterpretation of the digits.

**Comment by jomjol** [comment]
This does not make sence, as the problem usually is not the picture itself, but the natural inaccuray within the neural network. Therefore a new picture only makes sense, when the suspicious counter has moved a little bit.
I would suggest to decrease the detection intervall.
