### ISSUE TITLE
Einstellungsmöglichkeit für den AutoTimer

### ISSUE THREAD

**Issue by AdmiralRaccoon** [jomjol/AI-on-the-edge-device#1385]
### The Feature

Hi,
verstehe ich das richtig, das der Autotimer intervall immer dann startet, wenn der ESP gebootet wurde?
Wäre es möglich, einen einfachen Autotimer-Task-Planer zu implementieren, so das ich z.b. immer um 0:00 nachts und/oder 12:00 mittags eine Lesung bekomme, unabhängig davon, ob der ESP rebootet hat oder nicht., 

Gruss und danke für dieses Super Projekt,
Philipp

**Comment by jomjol** [comment]
Ja - richtig verstanden. Aktuell ist es aber nicht geplant, dass zu ändern. In der Regel wird ein Intervall von 2 - 30 Minuten verwendet, da spielt es keine Rolle, wann genau es startet. Ein Cron-Job ähnliche Konfigurationsmöglichkeit ist aktuell nicht geplant.

**Comment by caco3** [comment]
Wenn Du so etwas machen möchstest, verwendest Du am besten Homeassistatn oder ein anderes Home Automation System.
Da kannst Du entweder mittels MQTT die Daten mit jedem Interval aufzeichnen, oder du rufst `http://<IP>/json` nach Bedarf ab.

**Comment by AdmiralRaccoon** [comment]
Ja, ich nutze schon Home Assistant.
Die Idee dahinter war eigentlich das ich 1x täglich die Werte von Gas und Wasser auslese, vorzugsweise um 0:00 und dann alle 1440 Minuten. Wenn der ESP jetzt um z.b. um 10:37 neustartet, wird dann der Timerintervall ja auch neugestartet.

Aber ist ja nicht so tragisch, ich kann ja den Intervall auch auf 60 Minuten oder so stellen und das dann per Utility_Meter in Home Assistant konfigurieren

**Comment by caco3** [comment]
Wieso verwendest Du nicht das Energy Dashboard? Neu kann aud Wasser dargestellt werden.
Siehe https://github.com/jomjol/AI-on-the-edge-device/wiki/Integration-Home-Assistant#using-mqtt-automatically-setup-entities-using-homeassistant-mqtt-discovery

**Comment by AdmiralRaccoon** [comment]
Da bin ich in der Tat grade dran, danke. 👍
