### ISSUE TITLE
Problems with PSRAM 

### ISSUE THREAD

**Issue by michi22a** [jomjol/AI-on-the-edge-device#1386]
### Issue

hello people, after flashing the esp 32 cam i always get the following error message (last two lines). can someone help me what could be the reason?

ELF file SHA256: 28356ed42df4c694

Rebooting...
ets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:7664
load:0x40078000,len:15360
load:0x40080400,len:3744
entry 0x4008067c
I (27) boot: ESP-IDF 4.3.2 2nd stage bootloader
I (27) boot: compile time 20:02:47
I (27) boot: chip revision: 3
I (30) boot_comm: chip revision: 3, min. bootloader chip revision: 0
I (37) boot.esp32: SPI Speed      : 40MHz
I (42) boot.esp32: SPI Mode       : DIO
I (46) boot.esp32: SPI Flash Size : 4MB
I (51) boot: Enabling RNG early entropy source...
I (56) boot: Partition Table:
I (60) boot: ## Label            Usage          Type ST Offset   Length
I (67) boot:  0 nvs              WiFi data        01 02 00009000 00004000
I (74) boot:  1 otadata          OTA data         01 00 0000d000 00002000
I (82) boot:  2 phy_init         RF data          01 01 0000f000 00001000
I (89) boot:  3 ota_0            OTA app          00 10 00010000 001db000
I (97) boot:  4 ota_1            OTA app          00 11 001f0000 001db000
I (104) boot: End of partition table
I (109) boot_comm: chip revision: 3, min. application chip revision: 0
I (116) esp_image: segment 0: paddr=00010020 vaddr=3f400020 size=4df30h (319280) map
I (247) esp_image: segment 1: paddr=0005df58 vaddr=3ffb0000 size=020c0h (  8384) load
I (250) esp_image: segment 2: paddr=00060020 vaddr=400d0020 size=15e00ch (1433612) map
I (801) esp_image: segment 3: paddr=001be034 vaddr=3ffb20c0 size=029f8h ( 10744) load
I (806) esp_image: segment 4: paddr=001c0a34 vaddr=40080000 size=1c1f4h (115188) load
I (856) esp_image: segment 5: paddr=001dcc30 vaddr=50000000 size=00010h (    16) load
I (871) boot: Loaded app from partition at offset 0x10000
I (871) boot: Disabling RNG early entropy source...
I (883) psram: This chip is ESP32-D0WD
E (883) psram: PSRAM ID read error: 0xffffffff
E (883) cpu_start: Failed to init external RAM!
Re-enable cpu cache.

abort() was called at PC 0x40082dcf on core 0

Backtrace:0x40082c65:0x3ffe3ba0 0x4008f70d:0x3ffe3bc0 0x40096991:0x3ffe3be0 0x40082dcf:0x3ffe3c50 0x4007956d:0x3ffe3c80 |<-CORRUPTED

**Comment by jomjol** [comment]
Either problem with firmeware flashing or hardware problem. The log shows, that even the firmware does not start at all.
