### ISSUE TITLE
New Training Data for Digital Counters

### ISSUE THREAD

**Issue by alexander-th** [jomjol/AI-on-the-edge-device#1387]
### Files

**Thanks for this great work!**

The current AI recognizes the "0" on my digital counter as "8".  I would very much appreciate if you could include these counters in your training set, so that it will then hopefully work. 
In case you need different or modified training data please let me know and I will do my best to provide it.

[TrainingData.zip](https://github.com/jomjol/AI-on-the-edge-device/files/10050556/TrainingData.zip)

By the way: I tried to train these new digits via your "neural-network-autotrain-digital-counter" repository (https://github.com/alexander-th/neural-network-autotrain-digital-counter). However the run failed with the following warning:
```
[A job to say hello]
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout@v2

```
Maybe you can let me know what I did wrong.

**Comment by jomjol** [comment]
Please test the following new tflite: https://github.com/jomjol/neural-network-digital-counter-readout/raw/master/dig-class11_1500_s2.tflite

It is trained, including your new images.
