### ISSUE TITLE
Blitzlicht ist dauerhaft an

### ISSUE THREAD

**Issue by domiarduino** [jomjol/AI-on-the-edge-device#139]
Hallo,

nachdem ich meinen ersten ESP32 erfolgreich im Einstaz habe, habe ich mir nun einen zweiten geflasht. Leider leuchte bei diesem die Blitzlicht LED dauerhaft, sobald er hochgefahren ist. Das Webinterface ist normal erreichbar.

Irgendeinen Idee, woran das liegen kann?

Viele Grüße

**Comment by jomjol** [comment]
Hallo,
da hängt irgendwo deine Firmware. Strom weg und wieder an hast du vermutlich schon getestet. Kannst du während des Bootvorgangs die serielle Schnittstelle auslesen und posten?
Gruß,
  jomjol

**Comment by jomjol** [comment]
So einen Fehler habe ich noch nicht gesehen. Hast du mal den Kameraanschluss überprüft: Flexkabel nochmal neu eingesteckt?

**Comment by domiarduino** [comment]
Ja, schon häufiger inzwischen. Ich flashe die ESP32 Kamera über ein Ansteckboard mit USB Anschluß das bei der Kamera dabei war, die erste funktionierende habe ich über einen FTDI adapter geflasht. Könnte das daran liegen?

**Comment by domiarduino** [comment]
Die Kamera scheint defekt zu sein, ich habe eine Standard Webcamanwendung aufgespielt, damit ging zwar die Weboberfläche aber es kame ebenfalls kein Bild.
