### ISSUE TITLE
PreValue should be prefilled with RAW value instead of PreValue

### ISSUE THREAD

**Issue by caco3** [jomjol/AI-on-the-edge-device#1398]

**Comment by jomjol** [comment]
`/wasserzaehler.html?all=true&type=raw`

liefert etwas wie:
![grafik](https://user-images.githubusercontent.com/30766535/203645651-8b50d842-8d9b-4166-80e1-b1a62e72e1f1.png)

Daraus kannst du es dann auslesen.

**Comment by caco3** [comment]
super, danke!

**Comment by caco3** [comment]
`value?all=true&type=raw` geht übrigens auch und ist generischer

**Comment by caco3** [comment]
merged
