### ISSUE TITLE
Support request for special analog pointers 

### ISSUE THREAD

**Issue by IPSAttain** [jomjol/AI-on-the-edge-device#140]
First of all, great work.

My water meter has a special pointer at one gauge.
![grafik](https://user-images.githubusercontent.com/35669489/110469769-5871a200-80da-11eb-95ef-9bd898b5b730.png)
90% of the time the KI detect it wrong. I attached some samples and hope you can add it to the training.
[Wasserzähler.zip](https://github.com/jomjol/AI-on-the-edge-device/files/6108401/Wasserzahler.zip)
The other analog and digital ROI are detected rigth.

Thanks in advance and if you need further samles feel free to contact me.
BR
Attain

**Comment by jomjol** [comment]
Hi Attain,
I can add that to the training. Could you do me a favour and rename them with the right extected reading? For a good training I would need roughly need one picture for each setting (0.0, 0.1, 0.2 .... 9.8, 9.9). This are a lot of pictures, I know!
I think it would make sense to have about 2-4 Image for eacht intervall.
Best regards,
  jomjol

**Comment by IPSAttain** [comment]
... it means, you need the picture at format "x.y.jpg" ? Where x is the value of this gauge and y is the value of next lower digit?

e.g. 0.2.jpg for this sample: 
![2 8_analog2_20210309-070221](https://user-images.githubusercontent.com/35669489/110523554-8ecb1380-8112-11eb-9771-26cc3f59a437.jpg) 
I will collect the pictures, but i guess this will take some time.

**Comment by jomjol** [comment]
Perfect! 

I'll close this issue, please just reopen it, if you have the image collected!

**Comment by IPSAttain** [comment]
[water meter.zip](https://github.com/jomjol/AI-on-the-edge-device/files/6158838/water.meter.zip)

Hi, find the collected pictures attached.

**Comment by jomjol** [comment]
@IPSAttain: I have created a new analog tflite file:

[ana0700s1lq.zip](https://github.com/jomjol/AI-on-the-edge-device/files/6173006/ana0700s1lq.zip)

Just unzip and test it and let me know, if it works better for you now. If so, I will take this for the next release.

Best  regards,
  jomjol

**Comment by IPSAttain** [comment]
Hi @jomjol can confirm that this file works perfect with my water meter. Approved for the next release from my side.
Thanks for the quick fix and for this amazing project in general.

BR and stay safe
