### ISSUE TITLE
Matter protocol implementation

### ISSUE THREAD

**Issue by nliaudat** [jomjol/AI-on-the-edge-device#1404]
### The Feature

It could be great to implement matter protocol for wifi (not Matter Thread)
It's supported for ESP32 and have good [doc ](https://docs.espressif.com/projects/esp-matter/en/main/esp32/index.html)and [sdk.](https://github.com/espressif/esp-matter)

**Comment by jomjol** [comment]
Feel free to support and make a commit. Currently the developers have no capacity to do so. I will put this on the feature request list (next version) and close the issue.

**Comment by caco3** [comment]
I was just waiting to see how long it takes until this request comes :smile_cat:
