### ISSUE TITLE
Data Logging can not be enabled

### ISSUE THREAD

**Issue by caco3** [jomjol/AI-on-the-edge-device#1411]
### Issue

![image](https://user-images.githubusercontent.com/1783586/204035536-0ae13c34-9d76-4410-99e1-73f4bd9724a8.png)

@Slider0007 I think you changed that code, can you have a look?

@jomjol We need to fix this before the release

**Comment by jomjol** [comment]
I know, what happens here: if it is not defined in the config, it is greyed out. We need code to transfer in the html version:
- if disabled, set to default value. I'll have a look for that.

**Comment by Slider0007** [comment]
Do you have the two new parameters included in your config.ini?

![image](https://user-images.githubusercontent.com/115730895/204039550-db142e02-1a15-4cd7-9aec-c8df47fa5bb1.png)

When the parameters are missing I have the same behaviour (greyed out).

**Comment by Slider0007** [comment]
Datalogging should be enabled by default when the two parameters are missing in config.ini

![image](https://user-images.githubusercontent.com/115730895/204040371-792a68dc-8614-49b8-85f4-8baa1055944f.png)

**Comment by jomjol** [comment]
Problem ist the parsing of the `config.ini` 
If you update the html files, the `config.ini` is not updated. Therefore the new paragraph and parameter are not found.

The newest rolling has a downwards compatility hack include.

**Comment by caco3** [comment]
hmm, I still have this issue!
And I have the latest readconfigparam.js

**Comment by Slider0007** [comment]
I just verified it as well. It's working in general. Thanks @jomjol

It seems necessary to press the "update config.ini" button to inject the parameters to the config.ini, even parameters are already present in the GUI.

**Comment by caco3** [comment]
I will have a look on my side

**Comment by caco3** [comment]
The problem is that I already had a partial config:
```
;[DataLogging]
;DataLogActive =
;DataLogRetentionInDays =
```

Question is if it is only an issue because I iterated through all the rolling or if normal users also could tun into this

**Comment by caco3** [comment]
@jomjol And should we also add the new parameter to the default config.ini?
Currently it only shows
```
[DataLogging]
DataLogActive = true
DataLogRetentionInDays = 3
```

**Comment by jomjol** [comment]
1) New parameter has already been added to the `config.ini`
2) The problem with the commented out values (result of saving other values) is now covered by the newest rolling as well
