### ISSUE TITLE
set up SD card in the device 

### ISSUE THREAD

**Issue by s0170071** [jomjol/AI-on-the-edge-device#1416]
### The Feature

A nice addition to the browser based setup would be if the SD would be formatted and written by the ESP itself

**Comment by jomjol** [comment]
Not possible!

The minimum size needed is ~2.5MB of files and data. The remaining free capacity within the firmware RAM is < 200kB.

**Comment by s0170071** [comment]
Well, i didn't expect the contents of the sd card to be part of the bin file.  It would have to be downloaded either by the ESP or through the browser as it gets written to the card.

**Comment by jomjol** [comment]
Okay - got it. But I already hear a lot of users, that you should not expose the AI-on-the-edge to the external WEB, because it has no safety measures. Which I fully agree -> not really an option for the free version.

**Comment by s0170071** [comment]
I also agree but for installing that seems acceptable.

**Comment by s0170071** [comment]
Besides, the esp is behind the router firewall

**Comment by caco3** [comment]
it would be nice but is quite some effort and lot of things that could go wrong. that would mean its handling by the firmware would be quute complex!

**Comment by s0170071** [comment]
Or make it a two step bootload. First a binary that sets up the sd card and when thats done bootload the FW

**Comment by caco3** [comment]
yes, that would be possible, but we do not have the manpower to do it!
