### ISSUE TITLE
MQTT Sonderzeichen im Kennwort

### ISSUE THREAD

**Issue by UlrichThiess** [jomjol/AI-on-the-edge-device#1421]
### The Problem

Ich setze die 11.2 ein, da ich mit der aktuellen 12er Version den Webserver nicht zuverlässig erreichen konnte.

Ich habe einen MQTT Server, welcher Benutzer und Kennwort verlangt. Das Kennwort beinhaltet Sonderzeichen wie =

Leider wird vor dem = das Kennwort abgeschnitten. Ich konnte das mit tcpdump überprüfen.

### Version

11.2.0

### Logfile

```shell
Nicht notwendig.
```

**Comment by jomjol** [comment]
An der Version 11.x wird nicht mehr gearbeitet. Demnächst gibt es eine neue Version (13.x). Bitte diese Testen.
