### ISSUE TITLE
Feature Request/Question: Another camera module

### ISSUE THREAD

**Issue by JanHBade** [jomjol/AI-on-the-edge-device#143]
Hello,

for the OV2640 you can find other camera module.

Is that possible to use this in this project?

I want to use a camera that can I mount closer to the water meter like a fisheye camera...

**Comment by jomjol** [comment]
If you mean, that you just use another objective, yes that is possible, as long it fits to your camera holder. There are OV2640 with fisheye objectives available and some users do use them.

If you want to change to another camera module itself, this is not implemented currently.

**Comment by fluppie** [comment]
@jomjol have you tested other lenses in the meantime?
For example this ones:
![afbeelding](https://user-images.githubusercontent.com/8402106/147792660-9c378ace-4348-4b2b-8513-83cd36e166d1.png)

**Comment by jomjol** [comment]
@fluppie 

I have not tested or used fish-eye / wide angle lenses.
But I do not recommend to use them, as they will have image distortions, that might be critical for the input for the neural networks.

**Comment by fluppie** [comment]
OK thanks for your reply. I was looking at these to make a less high cylinder for my water meter.
But maybe you could use them if you retrain the AI with the wide-angle / fisheye lens?

**Comment by jomjol** [comment]
Distortion also means, that images of numbers in the inner will differ from images in the outer area. Therefore that will make the training much more difficult. I'm not planning to use them.

**Comment by ATBERKDA** [comment]
I’ve tested those lenses. They are working but only if you are not to far away from the digits. See here my _OV2640 2 million pixel camera module ESP32 module 160 degree 24pin can use for ESP32-CAM_:
![DD129BA0-FA07-40E0-8E21-C5B232F5F998](https://user-images.githubusercontent.com/44357120/147871485-48759342-5509-4dd9-a0c2-9db200c6fa43.jpeg)

**Comment by jomjol** [comment]
@ATBERKDA That's good to know.
Hint: your ROIs are not optimally adjusted. They are too big. For details see: https://github.com/jomjol/AI-on-the-edge-device/wiki/ROI-Configuration

**Comment by fluppie** [comment]
OK, I'll take the risk and also order some 120 degree modules, maybe 120 degree is more acceptable in terms of distortion?
We'll see and I'll report back!

**Comment by jomjol** [comment]
Looking forward on your experiences!

**Comment by cbho** [comment]
Hi,
Faboulous project - have it on three different meters - but would like to improve stability on the readings :-)

Would it be possible in some way to make a pinned topic, in which people could post which camera modules they have tested?
(Of course, preferably including a test image, how close the camera could come to the meter and a link to the specific camera making it easy to find)?
Then over time, it could be added to the wiki :-)

And, @fluppie, what exact modules did you buy and did it work?

Regards,
Chr.
