### ISSUE TITLE
MQTT Sensor für den Status

### ISSUE THREAD

**Issue by AdmiralRaccoon** [jomjol/AI-on-the-edge-device#1430]
### The Feature

Hallooo...Ich hatte das schonmal in einem Diskussionsthread erwähnt:

Wenn das technisch umsetzbar ist, wäre es toll, wenn es einen MQTT Sensor für den aktuellen Status gibt, den man auch auf der Homepage unten rechts sieht.
Dann könnte man, für Leute die wie ich des lötens nicht so ganz mächtig sind, eine externe LED für die Belichtung über eine Home Assistant Automation ansteuern.

![image](https://user-images.githubusercontent.com/41727850/204493675-7a294ae9-ee1d-4488-9ee3-5ca0b104e9eb.png)

**Comment by caco3** [comment]
**Status MQTT Topic**
A status MQTT topic with the status (without the time) would be nice, indeed.
This should be possible, but we have to check the impact to the memory usage. Also MQTT still is not very stable and I do not understand why.

**Use Status MQTT Topic to control external LED**
To control the LED it will not be as easy. The status most of the time is on "Flow finished". Then, when the Auto Timer fires, it immediately starts to switch on the internal LED and takes the photo.
I fear that reacting to a MQTT topic to enable an external LED might be to slow and unreliable.

**Comment by AdmiralRaccoon** [comment]
> Then, when the Auto Timer fires, it immediately starts to switch on the internal LED and takes the photo.

In that case, what happens if the LEDIntensity value is set to 0, and the WaitBeforeTakingPicture value set to (for example) 30?
Wouldn´t that be enough delay to trigger some external light?

**Comment by caco3** [comment]
yes, that might work, but I never played with that.

**Comment by caco3** [comment]
Can you try https://github.com/jomjol/AI-on-the-edge-device/actions/runs/3582839151?

![grafik](https://user-images.githubusercontent.com/1783586/204784372-2597f1a3-a86e-46e8-89fd-a16c9598d781.png)

**Comment by AdmiralRaccoon** [comment]
Looks good to me so far, thanks

![image](https://user-images.githubusercontent.com/41727850/204795223-0751b5e0-634c-4af1-8b8d-4f7379f55794.png)
