### ISSUE TITLE
Calculation issue in v6.2.1

### ISSUE THREAD

**Issue by stromzaehler** [jomjol/AI-on-the-edge-device#144]
`Rate too high - Returned old value - read value: 287.8737 - checked value: 287.873688`

The module calculates with a higher resolution (6 decimal places in checked value) than ROIs are defined (4). I had never seen that before.

**Comment by jomjol** [comment]
Thanks for that info - this is a minor conversion issue. The values are stored in float values and the conversion to string is not proper here. I will correct it in the next version.

Best regards,
  jomjol
