### ISSUE TITLE
Time between Last Refresh and Status is way off

### ISSUE THREAD

**Issue by awirtz** [jomjol/AI-on-the-edge-device#1463]
### The Problem

Hi,

I have a large mismatch between the actual time (Last Refresh) and the time that the process has run (Status). I can see that the process is still running okay, the results are still correct, but the timing is now way off. This has also led to strange graphs, where the time is jumping back and forward. NTP is not enabled.

I'm experiencing this **on all three** ESP32 that I'm running at the moment (water, gas, power), most extreme difference is ~1:50, least one is just 0:05, and all processes are ahead of "Last Refresh".

Reboot isn't fixing the issue.

I've updated all ESP32 to 13.0.1 yesterday evening. The attached logfile on debug is from today and yesterday.

Also, I've had a "Reset reason: Exception/panic".

Thanks!

[log_2022-12-01.txt](https://github.com/jomjol/AI-on-the-edge-device/files/10141408/log_2022-12-01.txt)
[log_2022-12-02.txt](https://github.com/jomjol/AI-on-the-edge-device/files/10141409/log_2022-12-02.txt)

### Version

13.0.1

### Logfile

```shell
See attachements
```

### Expected Behavior

Time from Status within 5min of Last Refresh.

### Screenshots

![image](https://user-images.githubusercontent.com/3907935/205303568-e1cc9590-4658-4f18-905b-a232455c245b.png)
![image](https://user-images.githubusercontent.com/3907935/205307662-7ef7bfaa-85d3-4fb8-85e7-d64e30546dcd.png)

**Comment by Ingo-Knito** [comment]
I have the same issue. The refresh-Time is correct.

![Time difference](https://user-images.githubusercontent.com/39132657/205323557-2b0bf7d6-94f8-424c-9fa1-848d0e2dfb02.jpg)

Release: v13.0.1 (Commit: 575d59d)

**Comment by caco3** [comment]
What is the reason you are not using NTP?

> Web UI version does not match firmware version!

This is already fixed in latest rolling, a new release is coming soon. nevertheless it is not a problem.

**Comment by Ingo-Knito** [comment]
Ahh. Thanks. Solved on my side: It was an upgrade and "undefinded" Entry on NTP-Server.
I have not seen this setting until now.

**Comment by awirtz** [comment]
I agree, the update apparently eliminated the default value "pool.ntp.org", which should've been taken if you have not enabled NTP and entered your own value.

**Intermediate fix**: Go to configuration, enable "Expert mode", enable "Time Server" and replace the undefinded value with "pool.ntp.org".

**Comment by caco3** [comment]
> I agree, the update apparently eliminated the default value "pool.ntp.org"

The config page states this: "Time server to synchronize system time (default: "pool.ntp.org" - used if nothing is specified) "

so the default gets replaced with "pool.ntp.org" on firmware level instead of config level.

@jomjol That's something we should correct.

But it does not explain why setting it manually fixed your issue!
I also have no NTP server set but still it works fine.

**Comment by jomjol** [comment]
@caco3 : I agree we need to fix that. Any idea, why it is removed with the update?

**Comment by caco3** [comment]
We did not remove anything, but I modified the startup a bit, maybe that has such an impact?
It worked for me but I did not test with other settings!

See https://github.com/jomjol/AI-on-the-edge-device/pull/1364

**Comment by caco3** [comment]
@awirtz  Is this still an issue with the latest release?

**Comment by 2bbe** [comment]
@caco3: I got this behaiviour after updating from 13.0.5 to 13.0.7.
adding pool.ntp.org as ntp server solved it

**Comment by awirtz** [comment]
The original error was gone for me, I had 13.0.5 running for a few days with my local Fritzbox as NTP, then I noticed that two of my three meters was showing wrong dates. I've moved to pool.ntp.org and installed 13.0.7, for now it seems to be okay... apparently others have issues with the ntp functionality as well...

**Comment by caco3** [comment]
The reason you have a discrepancy between `Last Page Refresh` and the Status time is a s following:
 - The `Last Page Refresh` is the time of your PC
 - The Status time is the time of the device.
So this basically means that the time of your device was wrong!

There are some issues with the NTP client, but I am working on it.
