### ISSUE TITLE
Build system uses old ESPressif framework

### ISSUE THREAD

**Issue by caco3** [jomjol/AI-on-the-edge-device#1467]
See https://github.com/jomjol/AI-on-the-edge-device/issues/1455

**Comment by caco3** [comment]
@jomjol I guess it got reverted to 4.4. by accident, see https://github.com/jomjol/AI-on-the-edge-device/commit/2ed3f4aa40660096cec3931fcd35f31c5653ca25#diff-e344deb500e905d2523dd58e760f61ecec29387bcc643c84c29a91d74261b186

I would suggest to update to 5.2 now


@Slider0007 FYI, thanks for the finding!

**Comment by jomjol** [comment]
Local testrun is running. If this is okay I push and release.
