### ISSUE TITLE
json/CSS dispalying problem

### ISSUE THREAD

**Issue by jurasjo** [jomjol/AI-on-the-edge-device#1468]
### The Problem

Hi
Thanks for this great project. I use it wit HA and the newest version  works very well. I wanted to let you know there might be a small problem with displaying json value inside "Diagnostic" card in HA. It gets outside of the card (maybe json string should have spaces). 
So now is:
`{"value":58.616,"raw":"058.616","error":"no error","rate":0.000000,"timestamp":"2022-12-03T09:44:24+0200"}`
and probably should be:
`{"value":58.616, "raw":"058.616", "error":"no error", "rate":0.000000, "timestamp":"2022-12-03T09:44:24+0200"}`

Looks like now, space between words "no" and "problem" is the only thing which allows this string to go to the new line.

### Version

Release: v13.0.3 (Commit: e9e1358+)

### Logfile

```shell
na
```

### Expected Behavior

json string should be within the card edges

### Screenshots

![Zrzut ekranu z 2022-12-03 09-37-11](https://user-images.githubusercontent.com/19259405/205430887-93814631-ac96-4c41-856a-dbf36af2cc5d.png)

**Comment by caco3** [comment]
The JSON string is not intended to be used directly in the UI. And the JSON specification does not require or enforce whitespaces outside the keys/values!

Therefore I do not see this as a bug.

**Comment by jurasjo** [comment]
**So it is a HA/Mosquito broker bug??** 

I use this new feature: "Using MQTT (Automatically Setup Entities using Homeassistant MQTT Discovery)". 
Settings > Integrations > MQTT(Mosquitto broker) there is my watermeter and those two cards "Sensors" and "Diagnostic".

**Comment by caco3** [comment]
No, it is not a bug at all!

The discovery page simply shows all discovered entities of our device, so you know what is available. A JSON entity newer is intended to be show directly in the UI, instead it is used for automation's or template sensors.
All information is available separate in other entities which can be added to the UI directly.

**Comment by jurasjo** [comment]
But it is displayed by default. That is the point.

**Comment by jurasjo** [comment]
So here is your wiki page: https://github.com/jomjol/AI-on-the-edge-device/wiki/Integration-Home-Assistant

You are telling me that if we had the whole screenshot there, there would be the same problem as on my screenshot? And it would be normal?

**Comment by caco3** [comment]
you are aware that the screenshot there is cut off? It is only there for illustration!

**Comment by caco3** [comment]
> But it is displayed by default. That is the point. If it is, then it should be displayed correctly.

you misunderstand that page in HA!
beside of this I told you already that it follows JSON spec and therefore is correct!

**Comment by jurasjo** [comment]
> you are aware that the screenshot there is cut off? It is only there for illustration!

I have written "if we had the whole screenshot", so yes I'm aware. You are not getting my point here. I know what that page is intended for. Does it mean it can be not displayed correctly? Looks like it is a problem with displaying properly formatted JSON in this card. That is all what I'm trying to tell you.

**Comment by caco3** [comment]
yes it would be the same and it is **not** a problem!

JSON is a data exchange format and nothing that is used to be shown directly on a UI!

Please show me any other device or screenshot where they show JSON on a UI!

**Comment by jurasjo** [comment]
BTW. So this button "ADD TO DASHBOARD" is there for what?
![Zrzut ekranu z 2022-12-03 10-54-40](https://user-images.githubusercontent.com/19259405/205432897-4d630c68-ab0e-4af4-ba31-0d29492dc3c0.png)

**Comment by caco3** [comment]
HA provides this button for all sections to make it easier for those who want to use it.

but if you try it you will see that you then can easily remove the unwanted entities.

**Comment by jurasjo** [comment]
But in this case this JSON entity is equal to the rest of entities and it should be displayed correctly.

It is like having twin house with gardens and fence between them and simply not respecting the perimeter of your property.  
So property in my example is the whole card here. 

Even if JSON is not for using directly in the UI  in this case it is used, because this is a screenshot from a UI.  It is a section of UI which displays discovered and entities.

**Comment by caco3** [comment]
You are free to create a Pull Request to fix this!

And before you can not show me any other device or screenshot where they show JSON on a UI, I will not respond anymore!

**Comment by caco3** [comment]
https://github.com/jomjol/AI-on-the-edge-device/pull/1489
