### ISSUE TITLE
MQTT: tries to connect even if disabled and crashes during this

### ISSUE THREAD

**Issue by jomjol** [jomjol/AI-on-the-edge-device#1476]
### The Problem

MQTT is completly disabled in the `config.ini`:

```

;[MQTT]
;Uri = mqtt://IP-ADRESS:1883
;MainTopic = wasserzaehler
;ClientID = wasser
;user = USERNAME
;password = PASSWORD
;SetRetainFlag = true
```

Even so during the startup a MQTT Init is tried and fails:

```
␛[0;32mI (24392) LOGFILE: Log Level set to ERROR␛[0m
␛[0;32mI (24392) SNTP: Time zone set to CET-1CEST,M3.5.0,M10.5.0/3␛[0m
␛[0;32mI (24392) GPIO: read GPIO config and init GPIO␛[0m
␛[0;32mI (24412) GPIO: GPIO init completed, handler is disabled␛[0m
␛[0;32mI (24412) TFLITE: task_autodoFlow - next round - Round #1␛[0m
␛[0;32mI (24412) MQTT INTERFACE: Init␛[0m
␛[0;32mI (24422) MQTT INTERFACE: ClGuru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.

Core  1 register dump:
PC      : 0x4008c871  PS      : 0x00060b30  A0      : 0x8020914a  A1      : 0x3fffcdb0
A2      : 0x00000000  A3      : 0xfffffffc  A4      : 0x000000ff  A5      : 0x0000ff00
A6      : 0x00ff0000  A7      : 0xff000000  A8      : 0x00000000  A9      : 0x3fffcd50  
A10     : 0x00000001  A11     : 0x00000001  A12     : 0x3ffcbb00  A13     : 0x3fffcd90  
A14     : 0x00000000  A15     : 0x00000001  SAR     : 0x0000000b  EXCCAUSE: 0x0000001c
EXCVADDR: 0x00000000  LBEG    : 0x4008c871  LEND    : 0x4008c881  LCOUNT  : 0xffffffff  


Backtrace:0x4008c86e:0x3fffcdb00x40209147:0x3fffcdc0 0x40232b0f:0x3fffcde0 0x4019cc7f:0x3fffce00
```

### Version

13.0.3

### Logfile

```shell
see above
```

### Expected Behavior

MQTT is not started at all

**Comment by Slider0007** [comment]
I can confirm that this is not working anymore.
It seems the issue started with this commit: 7e997889aac47159c271686fe9e2f7a960bc47e8

MQTTPublish gets called to provide flow status without checking wheter MQTT function is acitve. An interlock is missing.

**Comment by jomjol** [comment]
Found the problem - Quick fix is on the way and will be released as v13.0.4 if working.

**Comment by caco3** [comment]
I'm sorry, that was caused by my changes!

Thanks @jomjol for fixing it!

**Comment by jomjol** [comment]
No problem - quick fix is released (just in building)
@caco3 : this is only "dirty" solution, by blocking the MQTT init, if there is no Client or Topic specified. Would be better, if we even would not try to init, if MQTT is disabled, but did not find the time to jump into this in detail.

**Comment by caco3** [comment]
> 

Yes, for sure, lets have a look on it after we sorted all other issues out
