### ISSUE TITLE
Erkennungsrate schlecht - wo optimieren (Schärfe, Helligkeit?)

### ISSUE THREAD

**Issue by NemoN** [jomjol/AI-on-the-edge-device#148]
Aktuell werden die Werte nicht gut erkannt:
![Bildschirmfoto 2021-03-11 um 09 30 45](https://user-images.githubusercontent.com/2212175/110758332-b2927480-824c-11eb-8c0d-3943ed3ae2bd.png)
Was kann ich tun um die Erkennungsrate zu verbessern?

**Comment by NemoN** [comment]
**Version** master - v6.2.2 - 2020-03-10

**Comment by domiarduino** [comment]
Hast du schon versucht, den Fokus der Kamera anzupassen?

**Comment by MMeinhardt1** [comment]
Du könntest auch versuchen mit dem ESP näher an den Zähler zu kommen.

**Comment by jomjol** [comment]
Problem könnte die Reflexion in den unteren Bereichen der Ziffern sein ("heller Streifen"). Du könntest die Ziffern auch etwas großzügiger Ausschneiden:
![grafik](https://user-images.githubusercontent.com/30766535/110833651-f6ad6580-829c-11eb-85ac-29d5848bf5df.png)

Das Aspektverhältnis in deinem Bild ist etwas zu "rechteckig"

**Comment by Waschtli** [comment]
Mit der Kamera näher an die Uhr halte ich für sinvoll, da dann mehr pixel pro Digit verfügbar sind. Mit ca. 10 cm Abstand habe ich ein Bildfeld von ca. 5 cm x 7 cm. Scharfstellen war wichtig. Im Vergleich zum Auslieferungsstand des ESP32-CAM waren es ca. 1 Umdrehung gegen den Uhrzeigersinn. Das war recht schwirig, aber mit einer gute Zange ging es. Für mein Verständnis liegen Ihr Aligmnent-Marken zu nah beieinander. Die sollten möglichst an den Rändern des Bildes liegen um eine hohe Genauigkeit zu bekommen. Außerdem scheint ist Ihr bild stark verdreht, was, soweit ich es nachvollziehen kann, trotz Korrektur nicht unbedingt optimal ist. In meiner Ausführung habe ich die Kamera manuell so justiert, dass keine Verdrehung per Software nötig ist. Hier ist das Ergbenis.
![grafik](https://user-images.githubusercontent.com/73083412/111443871-1c59c500-870a-11eb-8431-562e3cc23ab0.png)

**Comment by NemoN** [comment]
@Waschtli kannst du dein "Gehäuse" mal von außen zeigen?
Hast du ein besonderes Objektiv? Ich dachte man muss mindestens 25cm? Abstand haben?

**Comment by Waschtli** [comment]
Hallo Herr Oeding,

klar kann ich das. Hier ist ein Bild von außen mit Maßstab. Das Gehäuse ist ein DN90 HT-Rohr aus dem Sanitär-Fachhandel, dass ich nur Schwarz angesprüht habe. Hauptsächlich von innen, um Reflexionen zu reduzieren, aber dann ist es außen gleich mit schwarz geworden.
Dies passt super auf unsere Wasseruhr. Es steckt ca. 3 cm auf der Uhr, die Kamera befindet sich bei 10 cm von unten, als ziemlich genau 7 cm über dem Glas der Uhr. Oben ist noch Platz für zusätzliche Elektronik. Ich hätte es gern mit LAN statt WLAN. Mal sehen, ob ich das hinbekomme.
Es ist keine besondere Kamera, sondern die, die mit dem Modul mitgeliefert wurde. Das Objektiv habe ich gegenüber der gelieferten Stellung um ca. eine Umdrehung herausgedreht, also gegen den Uhrzeigersinn, um das Bild scharf zu stellen.

Viel Erfolg

Waschtl

Am 19. März 2021 11:42:07 MEZ schrieb Thomas Oeding ***@***.***>:

**Comment by jomjol** [comment]
Ich schließe den Issue mal, da es aktiv keine Aktivitäten gibt. Bitte gerne wieder öffnen, wenn es weitere Themen gibt.
Gruß,
  jomjol
P.S.: in der neueste Version gibt es auch Hilfslinien, die die Einrichtung der ROIs insbesondere auch für die digtitalen Ziffern vereinfacht
