### ISSUE TITLE
Make code more readable

### ISSUE THREAD

**Issue by nliaudat** [jomjol/AI-on-the-edge-device#1484]
### The Feature

Many comment and core function are in German. It's not easy to understand and get involved in project.

**Comment by jomjol** [comment]
Clear, the developer is German. Not going to change that ;-)

No time / change to change the whole code to English.

**Comment by nliaudat** [comment]
I never seen a good developper who comment in its natural language. You have bad habits, but do great job. Thanks to keep it in mind for further if you want to have more contributors.

**Comment by jomjol** [comment]
I do this for my hobby and decided not to keep it private. Nothing more to comment.

**Comment by caco3** [comment]
> I never seen a good developper who comment in its natural language. You have bad habits, but do great job. Thanks to keep it in mind for further if you want to have more contributors.

That's the general habit of the Germans (no offense to @jomjol , @haverland ).

At my work we have software which is used by Germans customers. And thy also expect the UI in German, unlike the rest of the world who is fine with english (maybe also Japan) :)

I as a swiss guy also do not understand it, but I accept the decision of @jomjol and @haverland. Also there are far more important issues to solve first.

**Comment by jomjol** [comment]
Thanks for understandig. Just to make it clear. I'm not a professional programmer and do something totally different to pay my bills.

Programming I totally learned as an autodidact within the last years.

**Comment by caco3** [comment]
> Programming I totally learned as an autodidact within the last years.

Well, then I am even more impressed with what you created with this project!

**Comment by nliaudat** [comment]
In any case, thank you for your efforts and contributions! 
Like @caco3, I am also Swiss and understand some German. But it is still an effort to understand, especially when calling functions() or variables in German. 
I would like to be more involved in this project, which is useful for many people, and this is the reason for my request. 
Thanks again and congratulations!

**Comment by caco3** [comment]
@nliaudat There are some comments related to the algorithms which are in German. And also some variables are in German.
But overall most relevant stuff is English, so it should not be a problem for you, else feel free to ask!
