### ISSUE TITLE
New Training Data

### ISSUE THREAD

**Issue by Japander** [jomjol/AI-on-the-edge-device#1485]
### Files

Heyho,

i want to send in some training data from my german ferraris energy counter.
I know some of the pictures are not perfect, but for the number 3 and 5, AI on the edge currently often thinks number 3 is number 5.

[labeled.zip](https://github.com/jomjol/AI-on-the-edge-device/files/10148952/labeled.zip)

**Comment by jomjol** [comment]
What does it mean " pictures are not perfect"?

Did you align according to: https://github.com/jomjol/AI-on-the-edge-device/wiki/ROI-Configuration?

You can use the too of haverland to check and label your data: https://github.com/haverland/collectmeterdigits

Here we are very picky. The training data is one of the core assets of this and I only take "perfect" data. Please check and let me know. Thanks!

**Comment by haverland** [comment]
I tried it out. But the images drag down the accuracy of the model. 3 and 5 are still not recognized well.
Could you readjust the ROIs according to the instructions (uncheck "lock aspect ratio") and then collect and label images again? You will see that labeling is easier with correctly aligned ROIs.

**Comment by Japander** [comment]
They weren't aligned as they were supposed to be.

I adjusted them and am waiting now a few days of collecting to repost here.

3 numbers are now out of the reflection of the led and should be enough to get good readings.
Any tips what to do about these?

**Comment by haverland** [comment]
If it not recognize it fine, collect data again. The ROIs are good aligned now.

**Comment by caco3** [comment]
Please reopen if needed
