### ISSUE TITLE
Kontrast verbessern?

### ISSUE THREAD

**Issue by timo-g** [jomjol/AI-on-the-edge-device#149]
Wird der Kontrast des Bildes im post processing verbessert oder gibt es die Möglichkeit diesen im Vorfeld einzustellen? Eure Bilder scheinen qualitativ deutlich besser zu sein.

Die ungenaue Erkennung könnte auch an der etwas schrägen Position der Kamera auf den Zähler liegen **(?)** (um vorerst Reflexionen zu vermeiden). Die Zeiger sind demnach nicht exakt mittig.

![image](https://user-images.githubusercontent.com/32018557/111060661-d0571800-849e-11eb-8e65-f39f75eee1d6.png)

**Comment by jomjol** [comment]
Der Kontrast wird nicht nachbearbeitet oder verbessert. Es scheint, dass deine Kamera dort nicht optimal ist. Hast du vielleicht beim Einstellen des Fokus etwas auf das Objektiv bekommen (einfach mal "abwischen").
In dem Bild ist die Erkennung mit "62N.8377" aber fast richtig (bis auf die letzte Nachkommastelle "7", sollte eigentlich eine "6" sein. Die "3" ist bewusst als "N" markiert, da sie zwischen den Ziffern ist.
Bezüglich Kontrast: mit welcher Farbe hast du die Halterung gedruckt? Erfahrungsgemäßt funktionieren schwarze Gehäuse am besten. Gegebenfalls vielleicht einfach mal mit schwarzer Pappe auskleiden.
Gruß,
  jomjol

**Comment by timo-g** [comment]
Wow, das ging schnell!
Das Objektiv werde ich mir gleich anschauen.
Aktuell gibt es noch keine gedruckte Halterung, ich bin mir mit den Maßen noch nicht ganz sicher bei meinem Zähler.
Der ESP schaut erstmal provisorisch von oben drauf. Demnach habe ich noch kein geschlossenes System. Ich werde versuchen, einen provisorischen Zylinder zu basteln und melde mich dann wieder.

**Comment by timo-g** [comment]
Das Objektiv scheint einen Kratzer zu haben, daher wahrscheinlich der fehlende Kontrast. Siehst du da Nachteile bei der Erkennung? Eine nachträgliche Anpassung des Kontrastes wäre ja gar nicht so schlecht.
Da bis jetzt schon viel erkannt wird, werde ich mich erstmal um eine ordentliche Halterung kümmern. Danach wahrscheinlich eine neue Kamera...

**Comment by jomjol** [comment]
Zwei Auswirkungen können passieren: 
1. die Referenzfindun geht schief und das Bild liegt dann irgendwie
2. Die Erkennung der Ziffern und Zeiger geht häufiger schief.
Beides eher qualitative Bewertung. Die Referenzfindung sehe ich als größeres Problem, da in der Bilderkennung gewisse Varianz ein Teil des Trainings der neuronalen Netze ist. 
Ein Algo zur Kontrasterhöhung ist momentan für das ganze Bild nicht vorgesehen, da es Rechenzeit kostet und ehrlich gesagt bei meinem Wasserzähler kein Thema ist. Wenn sich noch mehr Bedarf dafür ergibt, kann ich es auf die ToDo-Liste nehmen.
Ich werde den Issue mal schließen, aber du kannst ihn bei Bedarf wieder öffnen oder einfach einen neuen Starten.

P.S.: eine neue Kamera bekommst du wirklich sehr günstig bei AliEpress (0.85 EUR) oder bei Amazon (2.90 EUR).
