### ISSUE TITLE
add hostname to wlan.ini

### ISSUE THREAD

**Issue by phlupp** [jomjol/AI-on-the-edge-device#15]
ich würde gerne mehrer Zähler abfragen (einmal Wasser und einmal Gas). Dafür wäre es super praktisch wenn man den Cams Hostnamen geben kann. Im moment ist in der _connect_wlan.cpp_ fest "icircuit" einprogrammiert.

Es wäre toll wenn man in der wlan.ini einfach noch die option **hostname="watermeter"** hätte.

**Comment by jomjol** [comment]
In der neusten "Rolling" Version implementiert - bei mir spricht er aber auf den hostname nicht an.

**Comment by phlupp** [comment]
Auch nach dem Pull #17 funktioniert das noch nicht wie gewünscht, ich kann das board immer noch nur unter dem DNS "iciruit" erreichen. Ich schau mir das nochmal an.

**Comment by phlupp** [comment]
jetzt mit Pull #18 sollte das laufen

**Comment by phlupp** [comment]
mit Pull #19 und #20 fertig eingebaut. 

Bei mir mit einer FritzBox getestet und funktioniert
