### ISSUE TITLE
Transition of digital counter does not match analog meter

### ISSUE THREAD

**Issue by TheDuffman85** [jomjol/AI-on-the-edge-device#1503]
### Issue

The transition of digital counter does not match analog meter on my water meter. What can I do? This leads to the problem, that the decimal places will cause negative flow. I'm using Version 13.0.4. 

![Screenshot_20221206-154327](https://user-images.githubusercontent.com/9296618/205944535-2e4c6eda-e9da-4cc9-a597-41f325a7aa08.png)

This will be recognized as 715.0958, but the previous figure was for example 715.9883. 

Any ideas?

**Comment by TheDuffman85** [comment]
I'll try that and will report if it solves my problem. Thank you.

**Comment by haverland** [comment]
CheckDigitIncreaseConsistency is not for new models. It works only for dig-class10. 
Best is here to adjust the ROIs like described inhttps://github.com/jomjol/AI-on-the-edge-device/wiki/ROI-Configuration#dig-class100--dig-cont-configuration (dig-class100/dig-cont)

Alternativly but not recommended: Set "AnalogDigitalTransitionStart" (Expert Mode) to 8.5 or less.

**Comment by TheDuffman85** [comment]
Unfortunately both is not working. I corrected the ROI setup and tried different AnalogDigitalTransitionStart values without any luck. Do I need to wait for the next transition for AnalogDigitalTransitionStart to have an effect?

**Comment by haverland** [comment]
Look now at raw value. In this case (9.9 on analog) it should post-process the 6.6 to 6. If it is on 0.1 it should post-process an 7. All on raw value (main page)

**Comment by TheDuffman85** [comment]
Raw value is currently at 716.0199

![grafik](https://user-images.githubusercontent.com/9296618/206567038-731f3927-3667-406f-9d20-a212e8b2a449.png)

**Comment by haverland** [comment]
Could you set Log to debug and post it. It should be round up if analog <2 and digit >=x.6

**Comment by TheDuffman85** [comment]
Sure, please see file attached. 

[logfileact.log](https://github.com/jomjol/AI-on-the-edge-device/files/10189537/logfileact.log)

**Comment by TheDuffman85** [comment]
Thank you for your help and fix. When can I expect it to hit the rolling branch?

My current workaround is, that I shifted the RIO down until it recognizes 6.8. 
![grafik](https://user-images.githubusercontent.com/9296618/206666078-b94ce86f-2562-4c46-9ad2-c1f67d38e5ff.png)

**Comment by haverland** [comment]
Now it's in rolling branch

**Comment by TheDuffman85** [comment]
Thank very much. I'll close the issue.

**Comment by TheDuffman85** [comment]
I can confirm that the issue is solved with version 13.0.7.
