### ISSUE TITLE
Bogus error message after reboot ?

### ISSUE THREAD

**Issue by fakenius** [jomjol/AI-on-the-edge-device#1505]
### The Problem

After reboot I get such error messages:

Neg. Rate - Read:  - Raw: 01.2268 - Pre: 1.2268

Obviously there is a problem with the leading "0" of the raw value...

### Version

13.0.4

### Logfile

```shell
.
```

### Expected Behavior

no error message when values are numerically equal.

**Comment by caco3** [comment]
was the value set correctly before?
Or is it the first round?

Please provide logs.

**Comment by fakenius** [comment]
This occurs here (now Version 13.0.5) only after (each?) reboot without any other manual influence and then disappears first if some water had been consumed and therefore the new value is higher. The values are correct, so I have actually no disadvantages.
I have 2 digital and 4 analogue ROIs defined and a new watermeter.

**Comment by fakenius** [comment]
[log.txt](https://github.com/jomjol/AI-on-the-edge-device/files/10175395/log.txt)

**Comment by jomjol** [comment]
The leading "0" in raw might not be the problem. It can be, that this is an internal rounding problem. When loading the prevalue to internal double representation, it can be, that it is a little bit bigger than stored:
e.g. 1.2268 (file) --> 1.22680001 (internal double) --> in this case the negative rate error can occur. 

As it is only at the first round, I would ignore it. The effort to check for this discrepancy of written decimal in files and internal representation within the double or float types will would be very high and will currently not followed.
