### ISSUE TITLE
Camera not working

### ISSUE THREAD

**Issue by beimoe** [jomjol/AI-on-the-edge-device#151]
Hi, 

in the IDF Monitor all looks fine, but i get the messages below (which repeat endless). What is the problem here?

[Debug]
Start ReadParameter
Logfile = false
LogfileRetentionInDays = 3

[System]
Start ReadParameter
TimeZone = CET-1CEST,M3.5.0,M10.5.0/3
TimeZone set to CET-1CEST,M3.5.0,M10.5.0/3
;TimeServer = fritz.box
;hostname = watermeter
SetupMode = true

bh 0x00ffdaff
bh 0x00ffdaff
bh 0x00ffdaff
bh 0x00ffdaff
bh 0x00ffdaff
bh 0x00ffdaff
bh 0x00ffdaff
bh 0x00ffdaff
bh 0x00ffdaff
bh 0x00ffdaff
bh 0x00ffdaff
bh 0x00ffdaff
bh 0x00ffdaff
bh 0x00ffdaff
bh 0x00ffdaff
bh 0x00ffdaff
bh 0x00ffdaff
bh 0x00ffdaff
bh 0x00ffdaff
bh 0x00ffdaff
bh 0x00ffdaff
bh 0x00ffdaff
bh 0x00ffdaff
bh 0x00ffdaff
bh 0x00ffdaff
[Ende]E (28369) camera: Failed to get the frame on time!
E (28369) server_part_camera: Camera Capture Failed
bh 0x00ffdaff

**Comment by jomjol** [comment]
Another user has reported a similar behaviour: https://github.com/jomjol/AI-on-the-edge-device/issues/139
There it turned out, that the camera was broken. Maybe only the connection is lost and you can check the cable firstly.
Best regards,
  jomjol

**Comment by jomjol** [comment]
Currently not active, there I will close it. Please reopen in case of further support needed.
