### ISSUE TITLE
alarm funktion ?

### ISSUE THREAD

**Issue by dl6dbh** [jomjol/AI-on-the-edge-device#1510]
### The Feature

Hi , 
im updated on 13.0.4 .... its working great. iḿ using with combinatition with volkszaehler.

An idee from me is to implement an alarm funktion     max l/h  

Best
meinolf

**Comment by caco3** [comment]
This is something that must be done externally with a Home Automation system!

Reason is that we should keep the complexity in the device as low as possible (its already **very** high) and that we are very limited with flash memory on the device.
