### ISSUE TITLE
Invalid Config Values

### ISSUE THREAD

**Issue by CFenner** [jomjol/AI-on-the-edge-device#1511]
### The Problem

Ich habe gerade einen neuen ESP32 mit der neusten Software bestückt (12.0.1 via esp web tools, update to 13.x.x.)

Da mein Zähler keine analogen Zählscheiben hat, habe ich analog deaktiviert und damit auch keine entsprechenden ROIs definiert.

Beim abspeichern der COnfig kommt nun die Fehlermeldung, dass die Config Werte ungültig sind. Dies war auch der Fall für einige MQTT Werte. Diese könnte ich nach Aktivierung von MQTT allerdings richtig setzen. Bei Analog ist das nicht der Fall.

### Version

13.x.x

### Logfile

```shell
tja
```

### Screenshots

<img width="558" alt="Bildschirm­foto 2022-12-07 um 11 58 20" src="https://user-images.githubusercontent.com/9592452/206161681-2f4f475b-bcd2-493f-9302-368f2afb6b5a.png">
<img width="492" alt="Bildschirm­foto 2022-12-07 um 11 58 23" src="https://user-images.githubusercontent.com/9592452/206161688-d8d685f4-cf10-488f-8f37-29e7e65802c9.png">

<img width="522" alt="Bildschirm­foto 2022-12-07 um 12 01 06" src="https://user-images.githubusercontent.com/9592452/206162268-188a1990-d710-41bd-b39f-f133f4122661.png">

**Comment by jomjol** [comment]
Du musst nicht erst 12.0.x installieren und dann updaten. Du kannst direkt 13.0.5 installieren, mit dem aktuellen config Verzeichnis. Dann sollte das kein Problem sein.

**Comment by CFenner** [comment]
Ich hab über die Web Tools keine Möglichkeit gesehen eine bestimmte Version zu installieren. Mir wurde nur 12.0.1 angezeigt.

**Comment by delhaltp** [comment]
Hallo,

Ich habe das selebe Problem. 

Ich habe auch via « https://jomjol.github.io/AI-on-the-edge-device/index.html » einen neuen ESP32 neu geflasht. Mir ist zusätzlich aufgefallen dass man bei Digits/Model und Analog/Model auch nichts aus der Dropdownbox auswählen kann denn diese ist leer.

<img width="474" alt="Capture d’écran 2022-12-07 à 21 11 51" src="https://user-images.githubusercontent.com/97796741/206285591-ea060b74-ce72-4a36-b6f3-3bd329f8b8a2.png">

**Comment by delhaltp** [comment]
Hallo ... 
Ich Ok Habe das Problem jetz für mich gelösst 

Ich habe ein OTA Update mit  https://github.com/jomjol/AI-on-the-edge-device/releases/download/v13.0.5/update.zip gemacht und jetz funktioniert es

**Comment by caco3** [comment]
> Ich hab über die Web Tools keine Möglichkeit gesehen eine bestimmte Version zu installieren. Mir wurde nur 12.0.1 angezeigt.

Stimmt, das haben wir vergessen nachzuführen. Werden es so bald wie möglich hinzufügen. Bis dann kann man eine vorhergehende Version flashen und dann ein OTA update machen

**Comment by jomjol** [comment]
Danke für den Hinweis mit dem Webinstaller - ist jetzt auf 13.0.5 upgedated.

**Comment by caco3** [comment]
@jomjol Habe eine Feature request dafür geschrieben, falls es uns mal langweilig wird :)
https://github.com/jomjol/AI-on-the-edge-device/issues/1523

**Comment by CFenner** [comment]
Nach etlichen Updates und Neuinstallationen und einer neuen SD Karte scheint es jetzt zu laufen. 

Ich hatte aber immer mal wieder die Meldung dass ein Config Wert `''` ungültig ist. Z.B. waren nach dem hinzufügen einer zweiten Nummern ROI die entsprechenden Config Werte leer, fehlen hier die entsprechenden defaults?

**Comment by caco3** [comment]
Was für config Werte meinst Du?

Ich habe gerade versuchweise eine edritte digitale Nummer hinzugefügt, in den COnfigs wurde dennoch nichts reklamiert!

**Comment by jomjol** [comment]
no more input - please make new issue, if still a problem
