### ISSUE TITLE
Wrong JSON Formatting in MQTT output - v13.0.5

### ISSUE THREAD

**Issue by snorre-k** [jomjol/AI-on-the-edge-device#1514]
### The Problem

With v13.0.5 the out put of the MQTT in JSON is malformatted:

![image](https://user-images.githubusercontent.com/18208930/206263922-ba77af04-9df4-4ccf-a764-17cc9f09861f.png)

There is a quotation mark missing after the raw value.

### Version

13.0.5

### Logfile

```shell
{"value": 406.5539, "raw": "00406.5539, "pre": "406.5539", "error": "no error", "rate": 0.000000, "timestamp": "2022-12-07T18:33:29+0100"}
```

### Expected Behavior

add the quotation mark after or leave it before the raw value

**Comment by caco3** [comment]
I just was refactoring the JSON parts.
Can you try and see if https://github.com/jomjol/AI-on-the-edge-device/actions?query=branch%3Arefactor-json works for you?

**Comment by snorre-k** [comment]
THX - the formatting looks good now. All values are quoted.
![image](https://user-images.githubusercontent.com/18208930/206403310-d052c6f3-0c01-4666-a108-98fffac2925b.png)

**Comment by b-neufeld** [comment]
Note the raw value should be fully enclosed with quotes as sometimes a "N" appears in the string when numbers can't be read.

**Comment by caco3** [comment]
Thanks, I just checked, with https://github.com/jomjol/AI-on-the-edge-device/pull/1518, all values are now double quoted.  `rate` was the only one that missed the double quotes

**Comment by caco3** [comment]
The latest rolling contains this fix
