### ISSUE TITLE
Digit detected as 10

### ISSUE THREAD

**Issue by CFenner** [jomjol/AI-on-the-edge-device#1524]
### The Problem

Bei meinem Zähler werden einige Ziffern als `10` erkannt. Gibt es einen use-case wo eine 10 Sinn macht? Meiner Meinung nach sollte doch `9` die höchste Ziffer sein, oder?

<img width="380" alt="Bildschirm­foto 2022-12-08 um 19 53 40" src="https://user-images.githubusercontent.com/9592452/206542674-b7325d69-8985-41e5-9cdb-a6bb86148d33.png">
<img width="296" alt="Bildschirm­foto 2022-12-08 um 19 53 27" src="https://user-images.githubusercontent.com/9592452/206542670-31b0cbbd-d4a5-4ce6-a577-885f932f21f2.png">

### Version

13.0.5

### Logfile

```shell
tba
```

**Comment by haverland** [comment]
Welches Model hast du verwendet?

**Comment by haverland** [comment]
Ja, das Model class100 sollte das Problem nicht haben, da es selbst nicht >10 in der Ausgabe geht. dig-cont sollte dann im nächsten Release das Problem nicht mehr haben.
