### ISSUE TITLE
Home Assistant Discovery: use problem device class for problem binary sensor 

### ISSUE THREAD

**Issue by CFenner** [jomjol/AI-on-the-edge-device#1530]
### The Feature

Currently the `problem` binary sensor is a plain binary sensor which displays as `on/off`.
<img width="344" alt="Bildschirm­foto 2022-12-09 um 10 47 58" src="https://user-images.githubusercontent.com/9592452/206674875-3d9efc2e-449a-4487-8792-56fbb1d74307.png">

Changing the [device class](https://developers.home-assistant.io/docs/core/entity/binary-sensor/#available-device-classes) to `problem` would display it as `ok/?`.
<img width="334" alt="Bildschirm­foto 2022-12-09 um 10 53 10" src="https://user-images.githubusercontent.com/9592452/206674948-26568074-8cae-4feb-86f8-c7431932266b.png">

**Comment by caco3** [comment]
Thanks!
