### ISSUE TITLE
master - v6.3.1 - 2020-03-16

### ISSUE THREAD

**Issue by vsajer** [jomjol/AI-on-the-edge-device#155]
master - v6.3.1 - 2020-03-16  Image show rotated  :o(

**Comment by jomjol** [comment]
What do you mean?

**Comment by vsajer** [comment]
I taught the gas meter ... And after the restart, the photo turned and is
out of the reading field.

Dne st 17. 3. 2021 20:31 uživatel jomjol ***@***.***> napsal:

**Comment by jomjol** [comment]
Please have a look into your `config.ini` itself. In an intermediate version there was a spelling error for the parameter `InitialRotate` (i was missing). In 6.3.1. this should have been corrected, maybe the ini files needs this update manually.

**Comment by jomjol** [comment]
Currently not active anymore, therefore closing for the moment.
Please reopen in case there are further questions.

**Comment by Jalle19** [comment]
This happened to me too, but after enough reboots the problem went away.
