### ISSUE TITLE
New Training Data for LCD and experiments with a LCD only model

### ISSUE THREAD

**Issue by DanielWe2** [jomjol/AI-on-the-edge-device#1554]
### Files

I had some issues with my LCD meter and have collected images of the digits.  (I know the quality is not very good but I am already using a external LED it is somehow hard to get good pictures from this model)

It seems that there already is similar image data in the dig_class_11 model but that has trouble with four of my own training images so I trained a new model including my images that seems to help. My meter seems to have different borders around some digits.

I also have experimented with a LCD only model. (Sorted all LCD images in the ziffer_sorted_raw into new folder and trained with that).  That lcd only model is a little better with my meter than the general dig_class_11 even without my training images. So it seems there may be some (small) value in having a LCD only model. (I haven't tried the reverse meaning a model without the LCD images for non LCD meters).  If you are interested in my sorted folder I can make a fork and push it to Github. 

But:  The dig_class_11 model trained with my additional training images also works perfectly. 

My images:
[images_new.zip](https://github.com/jomjol/AI-on-the-edge-device/files/10203090/images_new.zip)

**Comment by jomjol** [comment]
I'm not sure, if I want to encorporate them into the standart training data. The contrast is really bad and you need to know, that they are even varied by another 30% contrast modulation. This might be really critical.
I'll give it a try with the class11.

**Comment by DanielWe2** [comment]
Oh and one question:

I was training with https://github.com/jomjol/neural-network-digital-counter-readout

But:  Somehow my dig_class11 model was always a little worse than the official 1500_s2 version of the model.  Is Train_CNN_Digital-Readout-Small-v2 the correct script to use?   I trained is with the the data in that repository and validated it against the same data.  There are is a second version of the model defintion in that file but commented out should I use that?

**Comment by jomjol** [comment]
You have choosen the right version. There is no other. I've integrated your data - please try the following: https://github.com/jomjol/neural-network-digital-counter-readout/raw/master/dig-class11_1510_s2.tflite

Curious about your feedback.

**Comment by jomjol** [comment]
Great!
