### ISSUE TITLE
since begin 2021 in the update stripes in the recogitin picture

### ISSUE THREAD

**Issue by mikewolf** [jomjol/AI-on-the-edge-device#156]
hallo, seit beginn 2021 welches update weiß ich nimmer,
habe ich bei recogintation streifen in den Bildern der fotografierten Zellen ,siehe Bild
seitdem ist die Erkennung leider schlechter geworden ?? keinen Ahnung ob dies im Zusammenhang steht ?!
habe dies auf 3 ESP32Cam

Mit freundlichen Grüßen
mikewolf
[jomjol - AI on the edge.pdf](https://github.com/jomjol/AI-on-the-edge-device/files/6159659/jomjol.-.AI.on.the.edge.pdf)

**Comment by mikewolf** [comment]
vorher sah es so aus
![Bildschirmfoto 2021-03-17 um 21 59 05](https://user-images.githubusercontent.com/1781510/111537804-2d3b2280-876c-11eb-8cf1-475d0206b8b8.png)

**Comment by mikewolf** [comment]
seit Updates2021

![Bildschirmfoto 2021-03-17 um 22 01 06](https://user-images.githubusercontent.com/1781510/111537918-5065d200-876c-11eb-9aaa-27f2038f4f35.png)

**Comment by jomjol** [comment]
Das habe ich noch nie gesehen. Bei mir läuft die neueste Version (6.3.1). Die Bilder sehen wie gewohnt aus:
![grafik](https://user-images.githubusercontent.com/30766535/111543147-f3214f00-8772-11eb-91d3-7290429f4630.png)

Ich tippe am ehesten auf ein Problem mit der Kamera - Hardware?

Hast du mal ein Hard-Reset (Strom weg und wieder dran) probiert?

**Comment by mikewolf** [comment]
hallo ja habe dies auf 3 ESP32Cam , habe neu Geflasht, Sd karte ne neue alles probiert !
das normale Bild sprich take picture oder overview ! nur bei recog ist das problem bei Refernz bild sind auch keine Streifen
so jetzt gerade ml neue version geflasht jetzt fehler weg ..?! egal Danke perfekt !!
![Bildschirmfoto 2021-03-17 um 22 57 41](https://user-images.githubusercontent.com/1781510/111544060-36c88880-8774-11eb-927c-7878eb0ff081.png)
