### ISSUE TITLE
With the next main release, remove some of the no longer needed artifacts

### ISSUE THREAD

**Issue by caco3** [jomjol/AI-on-the-edge-device#1561]
### Issue

Those artifacts no longer need to be built and contained in the release:
- [x] firmware.bin
- [x] html-from-11.3.1

and remove from the build pipeline:
- [x] pack-for-OTA-v1

@jomjol @haverland Do you agree? This would make it a bit less confusing for our users.

**Comment by haverland** [comment]
Yes, good idea.

**Comment by haverland** [comment]
Im on it.
