### ISSUE TITLE
uncaught exception in Windows Tool for Gasmeter_Value_History

### ISSUE THREAD

**Issue by hike6688** [jomjol/AI-on-the-edge-device#1567]
### The Problem

While reading a data file the Gasmeter_Value_History.exe throws an exception like 

value that causes a exception
'10014.N9' is not a valid floating point value for Extended type

and terminates reading .

Seems to bee an uncaught exception in   
   function TForm1.LoadValue(const pFileName: string): Extended;

line 130 Result := lclStringList[2].ToExtended;

### Version

current rolling version on github (2022_12_12 21:50 )

### Logfile

```shell
part of the datafile that causes the exception, 
if the line with the N is deleted, reading works. 
...
2022-12-03T17:33:38,main,10014.98,10014.98,10014.98,0.006186,0.03,no error,1.0,0.1,0.0,1.0,4.0,9.0,8.0
2022-12-03T17:38:29,main,10014.98,10014.98,10014.98,0.000000,0.00,no error,1.0,0.1,0.0,1.0,4.0,9.0,8.0

2022-12-03T17:43:20,main,10014.N9,10014.99,10014.99,0.002062,0.01,no error,1.0,0.2,0.0,1.0,4.0,-1.0,9.0
                               ^
2022-12-03T17:49:22,main,10015.01,10015.01,10015.01,0.003315,0.02,no error,0.9,0.1,0.0,1.0,4.8,0.7,1.1
2022-12-03T17:52:25,main,10015.01,10015.01,10015.01,0.000000,0.00,no error,1.0,0.0,0.0,1.0,4.9,10.0,1.0
2022-12-03T17:57:16,main,10015.03,10015.03,10015.03,0.004124,0.02,no error,1.0,0.0,0.0,1.0,4.9,10.0,3.0
...
```

**Comment by reserve85** [comment]
Thanks for reporting, I‘ll fix it soon! My Computer is unfortionally broken and i am currently waiting for the delivery of a new one.

**Comment by reserve85** [comment]
@hike6688: can you please test this version?
[logfile-tool-13.0.7_Test.zip](https://github.com/jomjol/AI-on-the-edge-device/files/10224732/logfile-tool-13.0.7_Test.zip)

**Comment by hike6688** [comment]
@reserve85 I have tested logfile-tool-13-07 .
Works as expected, no uncought exceptions now.

What is the delpi version you use? I Have tried to install an old delphi 7 on Win 10  but this does not work.

**Comment by reserve85** [comment]
I use Delphi 11, you can get the "community edition" for free on their homepage [(https://www.embarcadero.com/de/products/delphi/starter/free-download)](https://www.embarcadero.com/de/products/delphi/starter/free-download)

perhaps someone can translate it to C++ or similar to integrate it into this project.

**Comment by caco3** [comment]
@jomjol I would suggest to move this tool into a separate repo

**Comment by jomjol** [comment]
well, it is not my tool. is was developed by somebody else - unfortunatly I lost the user name currently. I try to find it. Then we can ask him to host it.

**Comment by reserve85** [comment]
Yes, it was me

**Comment by caco3** [comment]
@reserve85 you could create a repo in your own Github account.
Just go to https://github.com/reserve85?tab=repositories and on the top right is a green button "new".

We then can link to your repo from here.

**Comment by jomjol** [comment]
> Yes, it was me
> I never hosted something here - if someone can help me doing this would be great.

Thanks for your fast response. It would be great, to host this in your own repository, especially, as it is your work!

**Comment by jomjol** [comment]
@reserve85 : can you add the full information - including the exe and the ini?
After that I will replace the code in my repo with a link to yours.

**Comment by reserve85** [comment]
Hey, the exe is in the release V1.0.0.0 and the *.ini is not needed, it creates itself when you start the program.

**Comment by jomjol** [comment]
Perfect - didn't realise the release version. Thanks a lot!
