### ISSUE TITLE
/capture_with_flashlight not working for external LEDs

### ISSUE THREAD

**Issue by jomjol** [jomjol/AI-on-the-edge-device#1576]
### The Problem

The function `/capture_with_flashlight` is not supporting the external LED strips. It only works with the internal Flash-LED.

### Version

all

### Logfile

```shell
n.a.
```

**Comment by caco3** [comment]
Solves: https://github.com/jomjol/AI-on-the-edge-device/issues/1575#issuecomment-1349542740

**Comment by jomjol** [comment]
I need to revert:  `/capture_with_flashlight` is supporting also the external LED-light - varyfied in code and with testing
