### ISSUE TITLE
Unregelmäßige Probleme mit WebUI

### ISSUE THREAD

**Issue by Morg42** [jomjol/AI-on-the-edge-device#159]
Ich habe die Firmware auf einem ESP32-CAM installiert, im Prinzip funktioniert das auch. Versorgung mit 5V USB, 3300 µF Kondensator nah an den Pins.

Das Setup ist langsam und bleibt manchmal hängen, die Bilder werden teilweise nicht geladen. Insbesondere die abschließende config.ini-Seite lädt oft gar nicht. (Dabei läuft die Bildanalyse noch nicht). Beim Debuggen sind mir ein paar Punkte aufgefallen, die ich hier mal reinschreibe:

- [ ] teilweise scheinen das Übergeben oder Parsen von Werten nicht zu passen:
![Screenshot 2021-03-21 at 14 28 45](https://user-images.githubusercontent.com/43153739/111908367-44725c80-8a59-11eb-87d6-fc62936f4fdd.png)

![Screenshot 2021-03-21 at 14 29 29](https://user-images.githubusercontent.com/43153739/111908374-4d632e00-8a59-11eb-8694-4e13d34ab53d.png)

Ein Fehler, der dabei auftritt, ist wiederholt ein "500 Internal Server Error" beim Zugriff auf /sdcard/img_tmp/ref_zw.jpg und /sdcard/img/tmp/ref_zw_org.jpg. Im Log vom ESP steht dann, dass der Zugriff auf die Datei fehlgeschlagen sei, da sie gesperrt sei (locked). Die Datei existierte zu keinem Zeitpunkt, an dem ich nachgeschaut habe (während des Betriebs per fileserver, nach Ausschalten auf der SD-Karte).

- [ ] Das Lesen und Anzeigen der Konfiguration schlägt fehl.
![Screenshot 2021-03-21 at 14 33 27](https://user-images.githubusercontent.com/43153739/111908544-f4e06080-8a59-11eb-85ec-131cbad7a0ae.png)

Im Inspector findet sich:

![Screenshot 2021-03-21 at 14 33 16](https://user-images.githubusercontent.com/43153739/111908562-01fd4f80-8a5a-11eb-8303-03cb08fca3cf.png)

Der letzte fehlgeschlagene XHR-Request bleibt offen, auch nach einer Stunde. Im Log ist kein Reboot zu finden. Der Browser (Vivaldi) reagiert im Fenster nicht mehr (Schaltflächen), weil er wohl auf den XHR wartet. Tab schließen geht (meist).

Manchmal wird die Konfigurationsseite geladen (im Setup oder auch aus dem Hauptmenü); wenn ich nach dem Schließen aller Browserfenster (ohne Reboot vom ESP) direkt die Konfigurationsseite aufrufe (/index_configure.html), ist die Chance größer, dass sie geladen wird, als wenn ich erst ins Hauptmenü gehe.

- [ ] Wenn die Konfiguration (manchmal) geladen wird, gibt es einen Fehler mit dem Ein-/Ausschalten des autotimers - Setzen/Löschen des Häkchens aktiviert/deaktiviert nicht das Eingabefeld für die Zeit.

![Screenshot 2021-03-21 at 15 11 10](https://user-images.githubusercontent.com/43153739/111908722-89e35980-8a5a-11eb-9517-dcabaeac1cf7.png)

Ich bin nicht sicher, ob die Punkte (Nichtreagieren beim Laden von Seiten mit fehlenden Bildern, Nichtanzeigen der Konfiguration) zusammenhängen. Ich habe versucht, Stromversorgung als Grund auszuklammern. Der WLAN-Router steht im gleichen Raum (Übertragungsraten gem. Router 63 bzw. 9 MBit/s). Automatische Verarbeitung war wie gesagt aus, zwischen Seitenaufrufen habe ich meist mindestens 30 Sekunden gewartet.

Wenn ich noch weitere Infos beibringen soll - gern.

Gruß
Sebastian

**Comment by jomjol** [comment]
Hallo Sebastian,

erstmal vielen Dank für deine detailierte Fehleranalyse, vor allem für die Screenshots. Das hilft mir sehr weiter.
Zunächst folgende Frage: wenn ich es richtig gesehen habe, verwendest du den Browser "Vivaldi". Welche Engine verwendet der im Hintergrund? Ich teste mit und programmiere mit Firefox und/oder Chrome.
Kannst du mir noch posten, mit welcher Version genau du die Tests gemacht hast (Firmware & Html-Version).
Ich habe das Setup auf einem frischen System gerade mit Chrome getestet und konnte es ohne Probleme absolvieren. Fehlermeldungen im Brower habe ich aber noch nicht kontrolliert. Antwort in meinem System war eher prompt und er hat auch alle Seiten geladen.

**zu 1 (teilweise scheinen das Übergeben oder Parsen von Werten nicht zu passen):**
* Den Fehler mit "/img_tmp/ref_zw.jpg" bzw "/img_tmp/ref_zw_org.jpg" kann ich nachvollziehen und er liegt an einer Änderung im Handling der Konfiguration. Da der Link on-the-fly bei Bedarf angepasst wird, ist das unkritisch. Ich werde das aber bei Gelegenheit mal korrigieren, um die Fehlermeldung zu vermeiden.
* Den Fehler bei edit_reference - Zeile 154 - ist vermutlich auf einen Schreibfehler meinerseits zurückzuführen. Kannst du bitte mal prüfen, wie genau bei dir in der `config.ini` der Parameter "InitialRotate" geschrieben ist. Mit **i** oder ohne nach dem t? Dort war ein Schreibfehler. Wenn alles aktuell ist, muss dort das **i** ergänzt werden.

**zu 2 (Das Lesen und Anzeigen der Konfiguration schlägt fehl):**
* bei mir nicht reproduzierbar - hängt vielleicht mit dem Schreibfehler bei 1) ab?
* Kann aber auch etwas ganz anderes sein - gerne weiteren Input!

**zu 3 (Setzen/Löschen des Häkchens aktiviert/deaktiviert nicht das Eingabefeld für die Zeit):**
* da habe ich wohl beim letzten Update noch ein paar generelle Bugs - ich arbeite dran.

Nochmals super danke für deinen Input! Ich melde mich hier, wenn es ein Update gibt (zunächst im Rolling-Branch)

Gruß,
 jomjol

**Comment by Morg42** [comment]
Moin,

erstmal danke für deine enthusiastische Reaktion :)

> Zunächst folgende Frage: wenn ich es richtig gesehen habe, verwendest du den Browser "Vivaldi". Welche Engine verwendet der im Hintergrund? Ich teste mit und programmiere mit Firefox und/oder Chrome.

Vivaldi basiert auf Chromium.

> Kannst du mir noch posten, mit welcher Version genau du die Tests gemacht hast (Firmware & Html-Version).

Gestern von github runtergeladen, aus master.  master - v6.3.0 - 2020-03-14, HTML 6.0.0.

Ist rolling "besser" und stabil genug?

> * Den Fehler bei edit_reference - Zeile 154 - ist vermutlich auf einen Schreibfehler meinerseits zurückzuführen. Kannst du bitte mal prüfen, wie genau bei dir in der `config.ini` der Parameter "InitialRotate" geschrieben ist. Mit **i** oder ohne nach dem t? Dort war ein Schreibfehler. Wenn alles aktuell ist, muss dort das **i** ergänzt werden.

Es muss ergänzt werden ;) Leider geht das nur über den Fileserver...

> **zu 2 (Das Lesen und Anzeigen der Konfiguration schlägt fehl):**
> 
> * bei mir nicht reproduzierbar - hängt vielleicht mit dem Schreibfehler bei 1) ab?
> * Kann aber auch etwas ganz anderes sein - gerne weiteren Input!

Wenn du mir sagst, was du brauchst - gern. Die Änderung "initial" hat jedenfalls keine Besserung gebracht. Ich bin aber auch nicht der Crack im JS-Debugging...


Aber immerhin - abgesehen von den Problemen läuft und liest es einwandfrei. 👍 

Gruß
Sebastian

**Comment by jomjol** [comment]
Habe gerade die `html.zip` in Rolling hochgeladen und einige der Bugs beseitigt.
Die Rolling ist eigentlich zum Testen gedacht, aber zumindest bei mir ist die getestet. Du könntest mal die neue html.zip testen und mir sagen, ob es besser läuft.
Und da das Problem mit der edit_reference anzuschauen, könntest du mal deine `config.ini` posten. Dann kann ich sie hier bei mir mal testen.

**Comment by Morg42** [comment]
Kann ich die html.zip aus rolling in master verwenden?

[config.ini.txt](https://github.com/jomjol/AI-on-the-edge-device/files/6178105/config.ini.txt)

**Comment by jomjol** [comment]
ja - kannst du

**Comment by jomjol** [comment]
Erstes Problem schon gefunden: beim Setzten des Hostnamen über die `Config.ini` funktioniert das notwendige Reboot nicht zuverlässig. Ist korrigiert und in einer neuen Firmware im Rolling Branch.
Ansonsten läuft deine config.ini aber bei mir ohne Probleme (Browser: Firefix).

**Comment by Morg42** [comment]
Hostname habe ich erst "zwischendurch" mal gesetzt, Reboot hat das aber nicht beeinträchtigt. Eigentlich bekommt er den über DHCP, ich bin nicht mal sicher, ob das einen Unterschied gemacht hat :wink:

**Comment by jomjol** [comment]
Schließe den Issue mal, da gerade keine Aktivität. Bitte gerne wieder öffnen!
