### ISSUE TITLE
Web UI requests files with wrong paths

### ISSUE THREAD

**Issue by TopGoalVl** [jomjol/AI-on-the-edge-device#1597]
### The Problem

Diese Fehlermeldung (s. Message Log) hatte ich bisher noch nie. Ist auch nicht wieder im Log aufgetaucht. 

Muss ich mir Sorgen machen? 

### Version

Release: v13.0.7 (Commit: 304b9e0)

### Logfile

```shell
Extrakt aus Message Log:
========================
[   194760] 2022-12-15T14:50:55 <INF> [POSTPROC] main: Raw: 0405.3465, Value: 405.3465, Status: no error
[  194760] 2022-12-15T14:50:55 <INF> [TFLITE SERVER] Round #669 completed

[ ====> Muss ich mir Sorgen machen? <=====] 
[  194779] 2022-12-15T14:51:14 <ERR> [OTA FILE] Failed to stat file: /sdcard/log/html/gethost.js!
[  194784] 2022-12-15T14:51:19 <ERR> [OTA FILE] Failed to stat file: /sdcard/log/data/html/gethost.js!
[  194847] 2022-12-15T14:52:22 <ERR> [OTA FILE] Failed to stat file: /sdcard/log/html/gethost.js!
[  194857] 2022-12-15T14:52:32 <ERR> [OTA FILE] Failed to stat file: /sdcard/log/source/html/gethost.js!
[  194879] 2022-12-15T14:52:55 <ERR> [OTA FILE] Failed to stat file: /sdcard/log/source/20221214/html/gethost.js!
[  194886] 2022-12-15T14:53:01 <ERR> [OTA FILE] Failed to stat file: /sdcard/log/source/20221214/00/html/gethost.js!
[  194992] 2022-12-15T14:54:47 <ERR> [OTA FILE] Failed to stat file: /sdcard/log/source/20221214/html/gethost.js!
[ ====> Muss ich mir Sorgen machen? <=====] 

[  195008] 2022-12-15T14:55:03 <INF> [TFLITE SERVER] Round #670 started
[  195052] 2022-12-15T14:55:48 <INF> [POSTPROC] main: Raw: 0405.3465, Value: 405.3465, Status: no error
[  195053] 2022-12-15T14:55:48 <INF> [TFLITE SERVER] Round #670 completed
[  195299] 2022-12-15T14:59:54 <INF> [TFLITE SERVER] Round #671 started
```

### Additional Context

SD-CARD INFO:
Transcend/Samsung (ID: 27), EB1QT
32Gb, schnell, zuverlässig und langlebig
hatte ich gerade beim Einrichten über!

**Comment by jomjol** [comment]
Mach mal nen reboot. Wenn das Problem dann weg ist nein - andernsfalls könnte es ein Problem mit dem Filesystem sein.

**Comment by TopGoalVl** [comment]
Die Einträge im Log wirden erstellt, wenn ich über den File Server auf z. B. /log/sources/20221214/00/*.jpg zugreife, um mir das Foto anzeigen zu lassen. Was auch einwandfrei und ohne merkliche Verzögerung funktioniert hat. Ich habe das für mehrere Fotos, aus unterschiedlichen Tagen und Uhrzeiten, gemacht. Konnte alle Fotos sauber anzeigen lassen. Den reboot habe ich noch nicht gemacht. Werde ich jetzt durchführen und noch einmal testen.

**Comment by TopGoalVl** [comment]
Nach dem reboot das selbe Problem :

[  219496] 2022-12-15T21:43:11 <INF> [POSTPROC] main: Raw: 0405.4058, Value: 405.4058, Status: no error
[  219496] 2022-12-15T21:43:11 <INF> [TFLITE SERVER] Round #754 completed
[  219744] 2022-12-15T21:47:20 <INF> [TFLITE SERVER] Round #755 started
[  219787] 2022-12-15T21:48:02 <INF> [POSTPROC] main: Raw: 0405.4058, Value: 405.4058, Status: no error
[  219787] 2022-12-15T21:48:03 <INF> [TFLITE SERVER] Round #755 completed
[  219800] 2022-12-15T21:48:15 <ERR> [OTA FILE] Failed to stat file: /sdcard/log/html/gethost.js!
[  219807] 2022-12-15T21:48:22 <ERR> [OTA FILE] Failed to stat file: /sdcard/log/source/html/gethost.js!
[  220035] 2022-12-15T21:52:11 <INF> [TFLITE SERVER] Round #756 started
[  220060] 2022-12-15T21:52:35 <ERR> [OTA FILE] Failed to stat file: /sdcard/log/html/gethost.js!
[  220070] 2022-12-15T21:52:45 <ERR> [OTA FILE] Failed to stat file: /sdcard/log/source/html/gethost.js!
[  220077] 2022-12-15T21:52:52 <ERR> [OTA FILE] Failed to stat file: /sdcard/log/source/20221214/html/gethost.js!
[  220079] 2022-12-15T21:52:54 <INF> [POSTPROC] main: Raw: 0405.4058, Value: 405.4058, Status: no error
[  220079] 2022-12-15T21:52:54 <INF> [TFLITE SERVER] Round #756 completed
[  220089] 2022-12-15T21:53:04 <ERR> [OTA FILE] Failed to stat file: /sdcard/log/source/20221214/00/html/gethost.js!
[  220105] 2022-12-15T21:53:20 <ERR> [OTA FILE] Failed to stat file: /sdcard/log/source/20221214/html/gethost.js!
[  220110] 2022-12-15T21:53:25 <ERR> [OTA FILE] Failed to stat file: /sdcard/log/source/20221214/01/html/gethost.js!
[  220113] 2022-12-15T21:53:28 <ERR> [OTA FILE] Failed to stat file: /sdcard/log/source/20221214/html/gethost.js!
[  220115] 2022-12-15T21:53:30 <ERR> [OTA FILE] Failed to stat file: /sdcard/log/source/20221214/00/html/gethost.js!
[  220130] 2022-12-15T21:53:45 <ERR> [OTA FILE] Failed to stat file: /sdcard/log/source/20221214/00/html/gethost.js!
[  220137] 2022-12-15T21:53:52 <ERR> [OTA FILE] Failed to stat file: /sdcard/log/source/20221214/html/gethost.js!
[  220273] 2022-12-15T21:56:08 <ERR> [OTA FILE] Failed to stat file: /sdcard/log/source/20221214/00/html/gethost.js!
[  220281] 2022-12-15T21:56:17 <ERR> [OTA FILE] Failed to stat file: /sdcard/log/source/20221214/html/gethost.js!
[  220284] 2022-12-15T21:56:19 <ERR> [OTA FILE] Failed to stat file: /sdcard/log/source/20221214/00/html/gethost.js!
[  220290] 2022-12-15T21:56:25 <ERR> [OTA FILE] Failed to stat file: /sdcard/log/source/20221214/00/html/gethost.js!
[  220326] 2022-12-15T21:57:02 <INF> [TFLITE SERVER] Round #757 started
[  220369] 2022-12-15T21:57:44 <INF> [POSTPROC] main: Raw: 0405.4058, Value: 405.4058, Status: no error
[  220369] 2022-12-15T21:57:45 <INF> [TFLITE SERVER] Round #757 completed
[  220387] 2022-12-15T21:58:02 <ERR> [OTA FILE] Failed to stat file: /sdcard/log/source/20221214/html/gethost.js!
[  220549] 2022-12-15T22:00:44 <ERR> [OTA FILE] Failed to stat file: /sdcard/log/html/gethost.js!
[  220554] 2022-12-15T22:00:49 <ERR> [OTA FILE] Failed to stat file: /sdcard/log/source/html/gethost.js!
[  220559] 2022-12-15T22:00:54 <ERR> [OTA FILE] Failed to stat file: /sdcard/log/source/20221214/html/gethost.js!
[  220561] 2022-12-15T22:00:56 <ERR> [OTA FILE] Failed to stat file: /sdcard/log/source/20221214/00/html/gethost.js!
[  220578] 2022-12-15T22:01:13 <ERR> [OTA FILE] Failed to stat file: /sdcard/log/source/20221214/html/gethost.js!
[  220579] 2022-12-15T22:01:14 <ERR> [OTA FILE] Failed to stat file: /sdcard/log/source/html/gethost.js!
[  220592] 2022-12-15T22:01:28 <ERR> [OTA FILE] Failed to stat file: /sdcard/log/source/20221213/html/gethost.js!
[  220609] 2022-12-15T22:01:44 <ERR> [OTA FILE] Failed to stat file: /sdcard/log/source/20221213/00/html/gethost.js!
[  220617] 2022-12-15T22:01:53 <INF> [TFLITE SERVER] Round #758 started
[  220636] 2022-12-15T22:02:11 <ERR> [OTA FILE] Failed to stat file: /sdcard/log/source/20221213/00/html/gethost.js!
[  220661] 2022-12-15T22:02:36 <INF> [POSTPROC] main: Raw: 0405.4058, Value: 405.4058, Status: no error
[  220661] 2022-12-15T22:02:37 <INF> [TFLITE SERVER] Round #758 completed
[  220679] 2022-12-15T22:02:54 <ERR> [OTA FILE] Failed to stat file: /sdcard/log/source/20221213/html/gethost.js!
[  220908] 2022-12-15T22:06:44 <INF> [TFLITE SERVER] Round #759 started
[  220951] 2022-12-15T22:07:26 <INF> [POSTPROC] main: Raw: 0405.4058, Value: 405.4058, Status: no error
[  220951] 2022-12-15T22:07:26 <INF> [TFLITE SERVER] Round #759 completed
[  221199] 2022-12-15T22:11:35 <INF> [TFLITE SERVER] Round #760 started
[  221242] 2022-12-15T22:12:17 <INF> [POSTPROC] main: Raw: 0405.4058, Value: 405.4058, Status: no error
[  221242] 2022-12-15T22:12:17 <INF> [TFLITE SERVER] Round #760 completed
[  221490] 2022-12-15T22:16:26 <INF> [TFLITE SERVER] Round #761 started
[  221533] 2022-12-15T22:17:08 <INF> [POSTPROC] main: Raw: 0405.4058, Value: 405.4058, Status: no error
[  221533] 2022-12-15T22:17:08 <INF> [TFLITE SERVER] Round #761 completed
[  221782] 2022-12-15T22:21:17 <INF> [TFLITE SERVER] Round #762 started
[  221824] 2022-12-15T22:21:59 <INF> [POSTPROC] main: Raw: 0405.4058, Value: 405.4058, Status: no error
[  221824] 2022-12-15T22:21:59 <INF> [TFLITE SERVER] Round #762 completed
[  222073] 2022-12-15T22:26:08 <INF> [TFLITE SERVER] Round #763 started
[  222115] 2022-12-15T22:26:50 <INF> [POSTPROC] main: Raw: 0405.4058, Value: 405.4058, Status: no error
[  222115] 2022-12-15T22:26:50 <INF> [TFLITE SERVER] Round #763 completed
[  222204] 2022-12-15T22:28:19 <INF> [OTA] Reboot triggered by Software (5s).
[  222204] 2022-12-15T22:28:19 <WRN> [OTA] Reboot in 5sec
[       4] 2022-12-15T20:00:06 <INF> [MAIN] =================================================
[       4] 2022-12-15T20:00:07 <INF> [MAIN] ==================== Startup ====================
[       4] 2022-12-15T20:00:07 <INF> [MAIN] =================================================
[       4] 2022-12-15T20:00:07 <INF> [MAIN] Branch: 'HEAD', Revision: 304b9e0, Date/Time: 2022-12-11 22:36, Web UI: Release: v13.0.7 (Commit: 304b9e0)
[       4] 2022-12-15T20:00:07 <INF> [MAIN] Reset reason: Via esp_restart
[       8] 2022-12-15T20:00:10 <INF> [MAIN] =================================================
[       8] 2022-12-15T20:00:10 <INF> [MAIN] ================== Main Started =================
[       8] 2022-12-15T20:00:10 <INF> [MAIN] =================================================
[      10] 2022-12-15T20:00:12 <INF> [MAIN] Initialization completed successfully!
[      12] 2022-12-15T21:00:15 <INF> [SNTP] Time zone set to CET-1CEST,M3.5.0,M10.5.0/3
[      12] 2022-12-15T21:00:15 <INF> [SNTP] Set SNTP-Server to de.pool.ntp.org
[      12] 2022-12-15T21:00:15 <INF> [SNTP] Waiting until we get a time from the NTP server de.pool.ntp.org
[      12] 2022-12-15T21:00:15 <INF> [SNTP] Status: Reset
[      14] 2022-12-15T22:28:35 <INF> [SNTP] Status OK
[      14] 2022-12-15T22:28:35 <INF> [SNTP] Time is synced with NTP Server de.pool.ntp.org
[      14] 2022-12-15T22:28:35 <INF> [MQTT] Digitizer interval is 4.8 minutes => setting MQTT LWT timeout to 12.1 minutes.
[      14] 2022-12-15T22:28:35 <INF> [MQTT IF] URI: mqtt://192.168.188.19:1883, clientname: LeuVoShWz6, user: shwguser, password: XXXXXXXX, maintopic: LeupoldsPub/Wasserzähler, last-will-topic: LeupoldsPub/Wasserzähler/connection, keepAlive: 727
[      14] 2022-12-15T22:28:35 <INF> [MQTT IF] Init
[      14] 2022-12-15T22:28:35 <INF> [MQTT IF] Client started, waiting for established connection...
[      14] 2022-12-15T22:28:35 <INF> [MQTT IF] Connected to broker
[      14] 2022-12-15T22:28:36 <INF> [TFLITE SERVER] Round #1 started
[      57] 2022-12-15T22:29:18 <INF> [POSTPROC] main: Raw: 0405.4058, Value: 405.4058, Status: no error
[      57] 2022-12-15T22:29:19 <INF> [TFLITE SERVER] Round #1 completed
[     305] 2022-12-15T22:33:27 <INF> [TFLITE SERVER] Round #2 started
[     348] 2022-12-15T22:34:09 <INF> [POSTPROC] main: Raw: 0405.4128, Value: 405.4128, Status: no error
[     348] 2022-12-15T22:34:09 <INF> [TFLITE SERVER] Round #2 completed
[     596] 2022-12-15T22:38:18 <INF> [TFLITE SERVER] Round #3 started
[     639] 2022-12-15T22:39:00 <INF> [POSTPROC] main: Raw: 0405.4128, Value: 405.4128, Status: no error
[     639] 2022-12-15T22:39:00 <INF> [TFLITE SERVER] Round #3 completed
[     666] 2022-12-15T22:39:27 <ERR> [OTA FILE] Failed to stat file: /sdcard/log/html/gethost.js!
[     677] 2022-12-15T22:39:38 <ERR> [OTA FILE] Failed to stat file: /sdcard/log/source/html/gethost.js!
[     695] 2022-12-15T22:39:56 <ERR> [OTA FILE] Failed to stat file: /sdcard/log/source/20221212/html/gethost.js!
[     701] 2022-12-15T22:40:02 <ERR> [OTA FILE] Failed to stat file: /sdcard/log/source/20221212/00/html/gethost.js!
[     706] 2022-12-15T22:40:07 <ERR> [OTA FILE] Failed to stat file: /sdcard/log/source/20221212/00/html/gethost.js!
[     712] 2022-12-15T22:40:13 <ERR> [OTA FILE] Failed to stat file: /sdcard/log/source/20221212/html/gethost.js!

**Comment by TopGoalVl** [comment]
Auch wenn ich via File Server: "/sdcard/html/gethost.js" ansehe, tritt der Fehler auf. Das Javascript wird aber korrekt angezeigt. 

Würde ein nochmaliges update.zip V13.0.7 das Problem beheben, oder reicht ein Upload von gethost.js? 

Das System läuft m. E. sauber und stabil. Ich kann auch auf den nächsten Release warten! 

Message Log :
[    2952] 2022-12-15T23:17:33 <ERR> [OTA FILE] Failed to stat file: /sdcard/html/html/gethost.js!

**Comment by caco3** [comment]
Wir scheinen Da einen Bug im Web UI zu haben, es werden falsche Pfade generiert:
[0d00h21m33s] 2022-12-16T00:06:06 <INF> [TFLITE SERVER] Round #11 completed
[0d00h22m14s] 2022-12-16T00:06:46 <ERR> [OTA FILE] Failed to stat file: /sdcard/html/html/gethost.js!
[0d00h22m17s] 2022-12-16T00:06:49 <INF> [TFLITE SERVER] Round #12 started
[0d00h22m26s] 2022-12-16T00:06:59 <ERR> [OTA FILE] Failed to stat file: /sdcard/html/html/gethost.js!
[0d00h22m42s] 2022-12-16T00:07:14 <ERR> [OTA FILE] Failed to stat file: /sdcard/html/html/gethost.js!
[0d00h22m44s] 2022-12-16T00:07:16 <ERR> [OTA FILE] Failed to stat file: /sdcard/log/html/gethost.js!
[0d00h22m48s] 2022-12-16T00:07:20 <ERR> [OTA FILE] Failed to stat file: /sdcard/log/data/html/gethost.js!
[0d00h22m50s] 2022-12-16T00:07:22 <ERR> [OTA FILE] Failed to stat file: /sdcard/log/html/gethost.js!
[0d00h22m52s] 2022-12-16T00:07:24 <ERR> [OTA FILE] Failed to stat file: /sdcard/log/digit/html/gethost.js!
[0d00h22m54s] 2022-12-16T00:07:26 <ERR> [OTA FILE] Failed to stat file: /sdcard/log/html/gethost.js!
[0d00h22m58s] 2022-12-16T00:07:30 <ERR> [OTA FILE] Failed to stat file: /sdcard/log/analog/html/gethost.js!
[0d00h23m02s] 2022-12-16T00:07:34 <ERR> [OTA FILE] Failed to stat file: /sdcard/log/analog/20221118/html/gethost.js!
[0d00h23m10s] 2022-12-16T00:07:42 <ERR> [OTA FILE] Failed to stat file: /sdcard/log/analog/20221118/00/html/gethost.js!
[0d00h23m46s] 2022-12-16T00:08:18 <INF> [POSTPROC] main: Raw: 525.5971, Value: 525.5971, Status: no error
[0d00h23m47s] 2022-12-16T00:08:19 <INF> [TFLITE SERVER] Round #12 completed

![grafik](https://user-images.githubusercontent.com/1783586/207986114-3b922f43-a658-426b-9c71-32cb07d9381d.png)

Es ist aber nicht ein wirkliches Problem für die Funktionalität!

**Comment by caco3** [comment]
Fixed inhttps://github.com/jomjol/AI-on-the-edge-device/pull/1610
