### ISSUE TITLE
"Corrected Value" wird falsch berechnet bei DecimalShift

### ISSUE THREAD

**Issue by michaeljoos72** [jomjol/AI-on-the-edge-device#16]
Hi jomjol

Ich eröffne das hier noch damit wir es hier "tracken" können.

Sobald ich den Wert wie in meinem Fall auf DecimalShift=-1 setze, wird das "Corrected Value" irgendwie falsch berechnet. Habe noch keine Logik gefunden, aber am Schluss wird immer eine 0 hinzugefügt und der Wert stimmt auch nicht wirklich.

**Hier einmal als Vergleich mit "DecimalShift=0" und "Set Prevalue = 10012.539"**

Direkt nach den Restart:

![image](https://user-images.githubusercontent.com/20517474/93111682-3cef8680-f6b7-11ea-935d-e0e3fd9519d2.png)

--> Das passt

Nach dem 1. Durchlauf:

![image](https://user-images.githubusercontent.com/20517474/93111813-732d0600-f6b7-11ea-87c7-cfdb7240d724.png)

--> Das passt ebenfalls!

**Dann ein weiterer Test mit "DecimalShift=-1" und "Set Prevalue = 1001.2539"**

Direkt nach den Restart:

![image](https://user-images.githubusercontent.com/20517474/93111974-aff8fd00-f6b7-11ea-88a7-4580354c0006.png)

--> Das passt auch noch

Nach dem 1. Durchlauf:

![image](https://user-images.githubusercontent.com/20517474/93111997-b7b8a180-f6b7-11ea-9251-57dbfdf23073.png)

--> Hier stimmt etwas noch nicht. Wie schon oben erwähnt eine zusätzliche "0" am Ende und "1011" anstatt "1001".

Raw-Value stimmt ja, das heisst die Erkennung passt.

**Und nach einigen weiteren Durchläufen ist es plötzlich noch eine Ziffer mehr:**

![image](https://user-images.githubusercontent.com/20517474/93114583-0451ac00-f6bb-11ea-865a-e2991458a633.png)

Gruss
Michael

**Comment by jomjol** [comment]
Konnte den Fehler nachvollziehen, danke für die gute Doku. Ist etwas tricky, da ich mehrfach eine Umwandlung verwende. In der neusten Version habe ich es angepasst. Kann es aber leider nicht gut testen, da bei mir heute und morgen kein "N" kommen wird.

**Comment by michaeljoos72** [comment]
hi jomjol

Ich habe das Problem immer noch, dass im Corrected Value nach einiger Zeit das Raw Value ausgegeben wird. Ich bin aber der Meinung, dass es nichts mit dem Verschieben der Dezimalstelle zu tun --> Die Dezimalstelle funktioniert seit dem letzten Update tiptop. Und das mit dem RAW-Value war ja vorher schon da...

Gruss
Michael

**Comment by jomjol** [comment]
Kannst du mal im Logfile schauen, ob es um den Zeitpunkt, wo der Corrected Value die "N" zeigte einen Reboot gab?

**Comment by michaeljoos72** [comment]
Ich habe gestern Abend mal alles zurückgesetzt, das PreValue neu gesetzt und über Nacht laufen lassen. Heute Morgen war dann der Fehler wieder da.

- Um 21:57:42 wurde zum letzten Mal die PreValue.ini gesetzt:

![image](https://user-images.githubusercontent.com/20517474/93432254-8ad9d980-f8c5-11ea-9041-5f37637d36a8.png)

Da sehe ich im LOG-File aber nichts Verdächtiges:
```
2020-09-16_21-57-37: task_autodoFlow - next round
2020-09-16_21-57-37: FlowControll.doFlow - ClassFlowMakeImage
2020-09-16_21-57-42: FlowControll.doFlow - ClassFlowAlignment				--> Um diese Zeit wurde das letzte PreValue in der INI gesetzt
2020-09-16_21-58-24: FlowControll.doFlow - ClassFlowDigit
2020-09-16_21-58-49: FlowControll.doFlow - ClassFlowAnalog
2020-09-16_21-59-14: FlowControll.doFlow - ClassFlowPostProcessing
2020-09-16_21-59-14: task_autodoFlow - round done
2020-09-16_22-01-35: handler_wasserzaehler
2020-09-16_22-02-28: task_autodoFlow - next round
2020-09-16_22-02-28: FlowControll.doFlow - ClassFlowMakeImage
2020-09-16_22-02-33: FlowControll.doFlow - ClassFlowAlignment
2020-09-16_22-03-15: FlowControll.doFlow - ClassFlowDigit
2020-09-16_22-03-39: FlowControll.doFlow - ClassFlowAnalog
2020-09-16_22-04-05: FlowControll.doFlow - ClassFlowPostProcessing
2020-09-16_22-04-05: task_autodoFlow - round done
```

Was mir nachher auffällt, ist eine unterschiedliche Sequenz:

Zuerst so:
```
020-09-16_22-06-37: handler_wasserzaehler
2020-09-16_22-07-19: task_autodoFlow - next round
2020-09-16_22-07-19: FlowControll.doFlow - ClassFlowMakeImage
2020-09-16_22-07-24: FlowControll.doFlow - ClassFlowAlignment
2020-09-16_22-08-07: FlowControll.doFlow - ClassFlowDigit
2020-09-16_22-08-31: FlowControll.doFlow - ClassFlowAnalog
2020-09-16_22-08-56: FlowControll.doFlow - ClassFlowPostProcessing
2020-09-16_22-08-56: task_autodoFlow - round done
2020-09-16_22-11-38: handler_wasserzaehler
2020-09-16_22-12-10: task_autodoFlow - next round
2020-09-16_22-12-10: FlowControll.doFlow - ClassFlowMakeImage
2020-09-16_22-12-15: FlowControll.doFlow - ClassFlowAlignment
2020-09-16_22-12-57: FlowControll.doFlow - ClassFlowDigit
2020-09-16_22-13-21: FlowControll.doFlow - ClassFlowAnalog
2020-09-16_22-13-46: FlowControll.doFlow - ClassFlowPostProcessing
2020-09-16_22-13-46: task_autodoFlow - round done
```

Und dann ist plötzlich "handler_wasserzaehler" mittendrin und nach "ClassFlowAlignment":
```
2020-09-16_22-31-34: task_autodoFlow - next round
2020-09-16_22-31-34: FlowControll.doFlow - ClassFlowMakeImage
2020-09-16_22-31-39: FlowControll.doFlow - ClassFlowAlignment
2020-09-16_22-31-41: handler_wasserzaehler
2020-09-16_22-32-21: FlowControll.doFlow - ClassFlowDigit
2020-09-16_22-32-45: FlowControll.doFlow - ClassFlowAnalog
2020-09-16_22-33-10: FlowControll.doFlow - ClassFlowPostProcessing
2020-09-16_22-33-10: task_autodoFlow - round done
2020-09-16_22-36-25: task_autodoFlow - next round
2020-09-16_22-36-25: FlowControll.doFlow - ClassFlowMakeImage
2020-09-16_22-36-30: FlowControll.doFlow - ClassFlowAlignment
2020-09-16_22-36-42: handler_wasserzaehler
2020-09-16_22-37-12: FlowControll.doFlow - ClassFlowDigit
2020-09-16_22-37-37: FlowControll.doFlow - ClassFlowAnalog
2020-09-16_22-38-02: FlowControll.doFlow - ClassFlowPostProcessing
2020-09-16_22-38-02: task_autodoFlow - round done
```

Ich kann aber nicht beurteilen was dahinter steckt und ob das ein Problem sein könnte?

Hier noch das komplette LOG-File von gestern Abend bis heute Morgen:
[log_wasserzähler.txt](https://github.com/jomjol/AI-on-the-edge-device/files/5237014/log_wasserzahler.txt)

**Comment by phlupp** [comment]
Das tritt bei mit tatsächlich auch auf, nach einem Neustart ist das so.

![Bildschirmfoto 2020-09-17 um 18 09 36](https://user-images.githubusercontent.com/6304863/93497939-660b5380-f911-11ea-91b6-cbf5831b7107.png)

Bei mir hatte sich das mal wieder Aufgehängt, und nach dem Neustart war dann NN im Wert. Hier noch mein Logfile:

[log.txt](https://github.com/jomjol/AI-on-the-edge-device/files/5240532/log.txt)

**Comment by jomjol** [comment]
Das Logfile hat geholfen. Folgendes passiert:

PreValue wird um 21:57 Uhr letztmalig gesetzt. Dann startet der ESP32 spontan neu (z.B: 02:08 Uhr). Dabei stellt der Algo fest, dass der PreValue älter ist als 30 Minuten (Standartwert) und nimmt an, dass er ungültig ist. Daher --> "N"

Zwei Dinge für mich zu tun:
1) Warum wird er PreValue nach 21:57 Uhr nicht mehr geschrieben
2) Reduktion der Anzahl Neustarts

zu 1) schaue ich mir morgen mal an
zu 2) längerfristiges Thema

**Comment by jomjol** [comment]
Okay, das hat schon mal geholfen.

Der PreValue wird um 21:57 Uhr zum letzten Mal gesetzt. Dann ist der 
ESP32 spontan mitten in der Nacht neu gestartet (z.B.: 02:08 Uhr). Bei 
diesem Start stellt der Algo fest, dass dein PreValue älter als 30 
Minuten ist (Standartwert) und sagt, dass er keinen aktuellen PreValue 
mehr hat und verwendet ihn nicht --> daher die "N".

Zwei Dinge zu klären:
1. Warum schreibt er den PreValue zum letzten Mal um 21:57 Uhr
2. Vermeidung Neustarts

zu 1) schaue ich mir morgen mal an.
zu 2) vermutlich längerfristiges Thema.

Gruß,
  jomjol

------ Originalnachricht ------
Von: "phlupp" <notifications@github.com>
An: "jomjol/AI-on-the-edge-device" 
<AI-on-the-edge-device@noreply.github.com>
Cc: "jomjol" <mueller.josef@gmail.com>; "Comment" 
<comment@noreply.github.com>
Gesendet: 17.09.2020 18:15:59
Betreff: Re: [jomjol/AI-on-the-edge-device] "Corrected Value" wird 
falsch berechnet bei DecimalShift (#16)

**Comment by michaeljoos72** [comment]
Ich habe PreValueAgeStartup jetzt auf 480 Minuten (8h) eingestellt aber irgendwo ist trotzdem noch "ein Hund" begraben ;)

- Letzte Nacht wurde PreValue.ini um 23:45 Uhr zum letzten Mal neu geschrieben
- Heute Morgen um 6 Uhr hatte ich dann wieder die N's im Corrected Value

Das ist eigentlich innerhalb der 8h die ich im PreValueAgeStartup eingestellt habe.

_PreValue wird nur gespeichert, wenn bei der Konsistzenzprüfung kein Fehler auftaucht (Rate zu Hoch, Negative Rate)_
--> Ja, einverstanden und das ist auch so

_Wenn bei der Konsistzenzprüfung kein Fehler auftritt und der Wert längere Zeit sich nicht ändert, wird weder der PreValue überschrieben, noch das Datum aktualisiert._
--> Ist das wirklich so? Wird das PreValue nicht jedes Mal gesetzt wenn die Konsistzenzprüfung OK ist? 
--> Wie lange ist die Zeit für "der Wert längere Zeit sich nicht ändert"?

Wäre es nicht sinnvoll, bei jeden Durchlauf und erfolgreicher Konsistzenzprüfung das Datum in der PreValue.ini neu zu setzen?

**Comment by jomjol** [comment]
Hast du Lust, das wir uns da mal gemeinsam in einer Skype Session anschauen?

**Comment by michaeljoos72** [comment]
Komme gerne mal auf das Angebot zurück, müsste mich aber zuerst "einrichten". Habe momentan Skype nicht installiert und keinen Account. 
Ehrgeizig wie ich bin, möchte ich mich zuerst mal selber in den Code "reinbeissen" und habe mir am Wochenende mal VS_Code, Espressif 32 & PlatformIO auf meinem Win10-Rechner installiert. Kämpfe aber noch mit Error-Meldungen bei "Check" und "Build". 

Weisst du gerade, ob ich noch etwas Spezielles beachten muss? Du hast ja im Forum mal erwähnt, dass die Installation von Espressif 32 auf Win10 etwas "tricky" war. Anstonsten übe ich mal weiter . . . schliesslich lerne ich ja auch was dabei :)

**Comment by jomjol** [comment]
Nicht wirklich, hatte ein paar Problem. Ich habe sie nicht dokumentiert, aber mit Google lies sich alles in den Griff bekommen :-).

**Comment by phlupp** [comment]
Ich musste über Run Menuconfig erst noch 'rtc_gpio_desc' aktivieren. Das ist in **Component config > Driver configurations > RTCIO configuration** zu finden. Erst dann lies es sich kompilieren

**Comment by michaeljoos72** [comment]
So, unterdessen läuft der Setup auf meinem Rechner und ich kann die FW selber erstellen.

Ich glaube ich hab die Ursache gefunden für mein Problem (hab mal ein paar Log-Zeilen eingefügt:

![image](https://user-images.githubusercontent.com/20517474/93995152-f1149f80-fd90-11ea-81b1-053f45988590.png)

Hier im Code wird als "PreValueAgeStartup" immer der Defaultwert (30) verwendet und nicht was ich in der INI gesetzt habe (480):

```
    if (difference > PreValueAgeStartup)
        return false;
```

"ReadParameter" stimmt, nur wird der nicht verwendet.

Bei meinem Zähler gibt es tatsächlich Situationen wo eine Fehlermeldung im "Corrected Value" länger als 30 Minuten ansteht und beim nächsten Reboot ist es dann passiert und ich hab die Ns wieder drin.

Hab aber noch nicht rausgefunden, wieso nicht der Wert in der INI verwendet wird.

**Comment by jomjol** [comment]
Mit dem Hinweis komme ich vielleicht weiter!
Ich habe in der Ini den Fehler gemacht, dass ich den PreValue immer gleich lade, wenn der Parameter `PreValueUse = True` gelesen wird. Da ist dann der Parameter `PreValueAgeStartup` noch gar nicht gesetzt, da er in der Reihenfolge meiner config.ini erst nachher gelesen wird!
Ist einfach zu korrigieren - mache ich in der nächsten Version heute oder morgen.

**Comment by michaeljoos72** [comment]
Ich glaube die einfachste Lösung wäre sogar PreValueAgeStartup in der INI eine Zeile nach oben zu verschieben, da du ja Zeile um Zeile einliest. Habe es kurz getestet und würde funktionieren. Aber das ist eventuell dann nicht "sauber" gelöst und braucht doch noch  eine Anpassung im Code?

**Comment by jomjol** [comment]
Habe die Firmware angepasst. Jetzt wird der PreValue erst gelesen, wenn alle Parameter gelesen sind. Sollte das Problem jetzt hoffentlich final beseitigen. Bitte testen und kurzes Feedback, ob ich den Issue schließen kann.

**Comment by michaeljoos72** [comment]
Besten Dank! Firmware ist eingespielt und ich teste mal. Der Wert der Variable `PreValueAgeStartup `beim Aufstarten stimmt schon mal.

**Comment by michaeljoos72** [comment]
Das sieht soweit gut aus. Ich schliesse hier mal.
