### ISSUE TITLE
Crop image before processing to allow for higher camera resolution

### ISSUE THREAD

**Issue by Jalle19** [jomjol/AI-on-the-edge-device#160]
I tried switching the camera resolution to UXGA or SVGA in order to get a sharper image, but it seems it's not possible to use higher than VGA at the moment. A big part of my image is irrelevant, it would be nice to be able to select a region of interest that represents the whole meter face.

![Screenshot_2021-03-21 jomjol - AI on the edge(3)](https://user-images.githubusercontent.com/1106133/111912422-1e0ceb00-8a72-11eb-950d-16b42fae9072.png)

So the process would be:

1. Take image in high resolution
2. Crop away everything except the main region of interest
3. Process the cropped image as usual.

**Comment by jomjol** [comment]
Hi Jalle,
this is not easy possible, as the RAM in the ESP32CAM is limited to 4MB. Including the tflite files for the CNN networks, it is not possible to use pictures, that are bigger than VGA. This would imply a major change in the RAM management.

Instead I would recommend to go closer to the water meter and adjust the focus, so you can achieve the same effect as discribed above. I will add a hint to the focus adjustment in the wiki soon.

**Comment by Jalle19** [comment]
I tried but fail to adjust the focus. My lense looks slightly different than the ones I've seen on the internet, so I'm not entirely sure I'm doing it right.

**Comment by jomjol** [comment]
Can you send me a picture of the lense?

**Comment by garvitkhera** [comment]
Hi Sam @Jalle19 

I hope you're doing well.

I was browsing to find a potential solution to cropping an image over esp32. I discovered I have the same problem as you; I just need a smaller ROI with a good resolution and stripping away unnecessary information. I had no luck in solving this.

Were you able to solve this by any means? I've been stuck on this part for a long time now. If yes, would you mind sharing some insight or solution to this?

Thank you,
Garvit

**Comment by SybexX** [comment]
With the current rolling, what you plan to do is possible.
Just use the zoom function there.

**Comment by Jalle19** [comment]
Nope, I stopped using this since I couldn't hack the lense 🤷

**Comment by SybexX** [comment]
The camera takes a picture with a resolution of 1600x1200
You can set the desired range using the zoom factor, zoom offsetY and offsetY parameters.

**Comment by garvitkhera** [comment]
@SybexX 

Thanks for your prompt response.

However, I can only get a zoomed image from the given set of resolutions by setting this sensor setting `int  (*set_framesize)       (sensor_t *sensor, framesize_t framesize);` right? If I want a custom image sized, say 300x100, that won't be possible with this. Am I correct? I would only be able to get a picture out of the given options in the esp32 library:

`typedef enum {
    FRAMESIZE_96X96,    // 96x96
    FRAMESIZE_QQVGA,    // 160x120
    FRAMESIZE_QCIF,     // 176x144
    FRAMESIZE_HQVGA,    // 240x176
    FRAMESIZE_240X240,  // 240x240
    FRAMESIZE_QVGA,     // 320x240
    FRAMESIZE_CIF,      // 400x296
    FRAMESIZE_HVGA,     // 480x320
    FRAMESIZE_VGA,      // 640x480
    FRAMESIZE_SVGA,     // 800x600
    FRAMESIZE_XGA,      // 1024x768
    FRAMESIZE_HD,       // 1280x720
    FRAMESIZE_SXGA,     // 1280x1024
    FRAMESIZE_UXGA,     // 1600x1200
    // 3MP Sensors
    FRAMESIZE_FHD,      // 1920x1080
    FRAMESIZE_P_HD,     //  720x1280
    FRAMESIZE_P_3MP,    //  864x1536
    FRAMESIZE_QXGA,     // 2048x1536
    // 5MP Sensors
    FRAMESIZE_QHD,      // 2560x1440
    FRAMESIZE_WQXGA,    // 2560x1600
    FRAMESIZE_P_FHD,    // 1080x1920
    FRAMESIZE_QSXGA,    // 2560x1920
    FRAMESIZE_INVALID
} framesize_t;`

And I can't control the image's startX and startY even if I use the set_framesize setting.

**Comment by SybexX** [comment]
1) With the zoom function you can choose between a resolution of 1600x1200 and 800x600
2) the area you want (I say zoom factor), StartX, StartY, EndX and EndY
3) the Output size that you want to have, in the rollig is the size fix

**Comment by garvitkhera** [comment]
Okay, noted. Thanks @SybexX

**Comment by SybexX** [comment]
/*
 * resolution = 0 \\ OV2640_MODE_UXGA -> 1600 x 1200
 * resolution = 1 \\ OV2640_MODE_SVGA -> 800  x 600
 * resolution = 2 \\ OV2640_MODE_CIF  -> 400  x 296
 * resolution = 3 \\ OV2640_MODE_MAX
 */
void CCamera::SetCamWindow(sensor_t *s, int resolution, int xOffset, int yOffset, int xTotal, int yTotal, int xOutput, int yOutput)
{
    // - (xOffset,yOffset) is the origin of the window in pixels and (xLength,yLength) is the size of the window in pixels.
    // - (xOffset,yOffset) ist der Ursprung des Fensters in Pixel und (xLength,yLength) ist die Größe des Fensters in Pixel.

    // - Be aware that changing the resolution will effectively overwrite these settings.
    // - Beachten Sie, dass eine Änderung der Auflösung diese Einstellungen effektiv überschreibt.

    // - This works only if the aspect ratio of 4:3 is preserved in the window size.
    // - Dies funktioniert nur, wenn das Seitenverhältnis von 4:3 in der Fenstergröße beibehalten wird.

    // - total_x and total_y defines the size on the sensor
    // - total_x und total_y definieren die Größe des Sensors

    // - width and height defines the resulting image(may be smaller than the size on the sensor)
    // - width und height definieren das resultierende Bild (kann kleiner sein als die Größe des Sensor)

    // - keep the aspect total_x : total_y == width : height
    // - Behalten Sie den Aspekt total_x : total_y == width : height bei

    // - use values divisible by 8 without remainder
    // - Verwenden Sie Werte, die ohne Rest durch 8 teilbar sind

    // - start with total_x = width and total_y = height, reduce both values by eg.32 pixels
    // - Beginnen Sie mit total_x = width und total_y = height und reduzieren Sie beide Werte um z.B.32 Pixel

    // - next try moving with offset_x or offset_y by 8 pixels
    // - Versuchen Sie als Nächstes, mit offset_x oder offset_y um 8 Pixel zu verschieben

    // set_res_raw(sensor_t *sensor, int startX, int startY, int endX, int endY, int offsetX, int offsetY, int totalX, int totalY, int outputX, int outputY, bool scale, bool binning)
    // set_window(sensor, (ov2640_sensor_mode_t)startX, offsetX, offsetY, totalX, totalY, outputX, outputY);
    // set_window(sensor, mode, offset_x, offset_y, max_x, max_y, w, h);

    int unused = 0;
    s->set_res_raw(s, resolution, unused, unused, unused, xOffset, yOffset, xTotal, yTotal, xOutput, yOutput, unused, unused);
}
