### ISSUE TITLE
Nochmal Zahlenüberlauf

### ISSUE THREAD

**Issue by sirpete83** [jomjol/AI-on-the-edge-device#161]
Hallo Jomjol,
ich habe mir die geschlossenen issues angeschaut und muss das Thema nochmal aufgreifen. 
Ich habe manuell den Wert auf 951,9069 gesetzt.
![Screenshot_2021-03-23 jomjol - AI on the edge](https://user-images.githubusercontent.com/7904787/112147138-a7d8c780-8bdc-11eb-94c9-4b067439ed6d.png)

Das sollte dem angezeigten Wert entsprechen, oder meinst du es ist schon 952,0069 ?
Das ist jetzt schwierig zu beurteilen.
Hast du eine Idee, einfach mal so laufen lassen?
Gruß Peter

**Comment by jomjol** [comment]
Hallo Peter,
das müsste eigentlich 952,0069 sein. Du musst die Zahlen von hinten lesen:

0,0001:   9.6 --> 9
0,001: 6,8 --> 6 (mit vorheriger Ziffer noch vor der 7)
0,01: 0,7 --> 0, aber der Nulldurchgang damit schon vollzogen
0,1: 0,0 --> mit der Info der vorherigen Zahl, dass der Nulldurchgang schon rum ist --> 0

Rest: 0952 ist klar

--> 0952.0069 = genau was der Algo ausgewertet hat.

**Comment by sirpete83** [comment]
Hey,
Danke für die Erklärung. Wenn man es so liest, dann sollte es passen. Scheint klar zu sein.
