### ISSUE TITLE
Bildfehler nach X Betriebsstunden

### ISSUE THREAD

**Issue by timo-g** [jomjol/AI-on-the-edge-device#162]
Mein ESP erzeugt nach ca 6 Stunden (manchmal länger, manchmal kürzer) die unten angehangenen Fehlbilder. Immer etwas unterschiedlich. 
Ich habe die 5V Spannungsversorgung überprüft und stabilisiert, die Firmware neu geflasht. 
Zuerst dachte ich an einen Defekt der Kamera oder ein Fehler am Flachband-Steckverbinder, aber nach einem harten Reboot läuft das System wieder ohne Probleme. Für mich sieht es erstmal nach einem Fehler in der Datenübertragung aus(?)
Der Log gibt leider auch keinen Fehler aus. 

![Bildschirmfoto 2021-03-24 um 16 13 55](https://user-images.githubusercontent.com/32018557/112337075-e5615180-8cbd-11eb-9bfb-757773906b91.png)
![Bildschirmfoto 2021-03-24 um 16 30 00](https://user-images.githubusercontent.com/32018557/112337433-32ddbe80-8cbe-11eb-88cf-081bbd03dab8.png)

**Comment by jomjol** [comment]
Das sieht nach einem Problem mit der Kamera aus. Manchmal kann auch ein Timing Problem mit der SD-Karte die Ursache sein.

Startet der ESP32 von selbst neu oder musst du ihn manuel starten?

**Comment by timo-g** [comment]
Also am besten mal eine andere SD-Karte testen? (Aktuell 8GB)
Den ESP muss ich manuell vom Netzteil trennen, damit der Fehler behoben wird. Danach erstmal keine Probleme feststellbar, bis nach ein paar Stunden wieder die oben gezeigten Bilder erzeugt werden.

**Comment by timo-g** [comment]
**Update:** Bei 5,5V Eingangsspannung aktuell nach 9h noch keinen Fehler. Sicher noch keine 100% Garantie, aber ich schließe den Issue erstmal.
