### ISSUE TITLE
Renaming  numbers not possible

### ISSUE THREAD

**Issue by caco3** [jomjol/AI-on-the-edge-device#1631]
### The Problem

renaming a number is not possible because there is a bug in the name validation

### Version

rolling

### Screenshots

![grafik](https://user-images.githubusercontent.com/1783586/208320254-2421225d-3222-4dfe-9761-75bb42e9ab94.png)
![grafik](https://user-images.githubusercontent.com/1783586/208320269-0143eb9b-f42e-439d-a530-17799218d9d8.png)

**Comment by jomjol** [comment]
Corrected in newest Rolling
