### ISSUE TITLE
Wrong HA Autodiscovery if structured MainTopic

### ISSUE THREAD

**Issue by emics** [jomjol/AI-on-the-edge-device#1633]
### The Feature

if in configuration page the **MainTopic** field was edit with structured data (es. "home/watermeter") , the generated home assistant discovery topic is wrong; don't have the relative structure.

**Comment by caco3** [comment]
so you want support for `/` in the main topic?

Although this technically is possible, I don't think we will add this in the near future due to missing manpower

**Comment by emics** [comment]
tnx a lot caco3
this is a minor feature.

**Comment by caco3** [comment]
After thinking about this, I even think we should not support "/" for the main topic!
I think it would bring more confusion than help. Also the internal handling/testing is not trivial.

But we should add a check on the config page against unsupported characters

Sorry!
