### ISSUE TITLE
Home Assistant MQTT state_topic path incorrect when using default Number name

### ISSUE THREAD

**Issue by DrCoolHands** [jomjol/AI-on-the-edge-device#1643]
### The Problem

I have the meter reader configured to send data to MQTT and to provide HomeAssistant discovery details, however a number of the state_topic fields for HomeAssistant are invalid and include an additional `/default/` path.

From the MQTT Server:

for example:

homeassistant/sensor/aiwatermeter/value/config
```
{
"~": "aiwatermeter",
"unique_id": "aiwatermeter-value",
"object_id": "aiwatermeter_value",
"name": "Value",
"icon": "mdi:gauge",
"state_topic": "~/default/value",
"unit_of_meas": "m³",
"device_class": "water",
"state_class": "total_increasing",
"availability_topic": "~/connection",
"payload_available": "connected",
"payload_not_available": "connection lost",
"device": {
"identifiers": ["aiwatermeter"],
"name": "aiwatermeter",
"model": "Meter Digitizer",
"manufacturer": "AI on the Edge Device",
"sw_version": "v13.0.8",
"configuration_url": "http://192.168.0.100"
}
}
```

The state_topic value is published as '\~/default/value' however that topic does not exist. Instead it should be '~/value'

![image](https://user-images.githubusercontent.com/24321125/208535220-81d5fd9e-e4c2-42be-aa08-3404fb2cc063.png)

This effects the following sensor topics:

- homeassistant/sensor/aiwatermeter/value/config
- homeassistant/sensor/aiwatermeter/raw/config
- homeassistant/sensor/aiwatermeter/error/config
- homeassistant/sensor/aiwatermeter/rate_per_time_unit/config
- homeassistant/sensor/aiwatermeter/rate_per_digitalization_round/config
- homeassistant/sensor/aiwatermeter/timestamp/config
- homeassistant/sensor/aiwatermeter/json/config
- homeassistant/binary_sensor/aiwatermeter/problem/config

The other config topics show the correct state_topic path

Config:
```
[MQTT]
Uri = mqtt://mqtt.local:1883
MainTopic = aiwatermeter
ClientID = watermeter
HomeassistantDiscovery = true
MeterType = water_m3
```

### Version

13.0.8

### Logfile

```shell
[0d00h00m04s] 2022-12-20T03:43:55 <INF> [MAIN] ==================== Startup ====================
[0d00h00m04s] 2022-12-20T03:43:55 <INF> [MAIN] =================================================
[0d00h00m04s] 2022-12-20T03:43:55 <INF> [MAIN] Branch: 'HEAD', Revision: 04f2f23+, Date/Time: 2022-12-19 20:41, Web UI: Release: v13.0.8 (Commit: 04f2f23+)
[0d00h00m04s] 2022-12-20T03:43:55 <INF> [MAIN] Reset reason: Via esp_restart
[0d00h00m08s] 2022-12-20T03:43:59 <INF> [MAIN] =================================================
[0d00h00m08s] 2022-12-20T03:43:59 <INF> [MAIN] ================== Main Started =================
[0d00h00m08s] 2022-12-20T03:43:59 <INF> [MAIN] =================================================
[0d00h00m08s] 2022-12-20T03:43:59 <INF> [MAIN] The device has 8 MBytes of PSRAM
[0d00h00m10s] 2022-12-20T03:44:01 <INF> [MAIN] Initialization completed successfully!
```

**Comment by caco3** [comment]
hmm, for me it works ok.

MQTT discovery topic content (`homeassistant/sensor/wasserzaehler/value/config`):
```
{
"~": "wasserzaehler",
"unique_id": "wasserzaehler-value",
"object_id": "wasserzaehler_value",
"name": "Value",
"icon": "mdi:gauge",
"state_topic": "~/main/value",
"unit_of_meas": "m³",
"device_class": "water",
"state_class": "total_increasing",
"availability_topic": "~/connection",
"payload_available": "connected",
"payload_not_available": "connection lost",
"device": {
"identifiers": ["wasserzaehler"],
"name": "wasserzaehler",
"model": "Meter Digitizer",
"manufacturer": "AI on the Edge Device",
"sw_version": "v13.0.8",
"configuration_url": "http://192.168.1.151"
}
}

```

![image](https://user-images.githubusercontent.com/1783586/208539296-0463e1ee-47b8-4910-9515-b2095f8084ba.png)


And in HA:

![image](https://user-images.githubusercontent.com/1783586/208538959-aa66bc07-7916-444f-8912-f4cdaea88d68.png)

**Comment by DrCoolHands** [comment]
Can you post your MQTT config from the meter?

**Comment by caco3** [comment]
if you used MQTT before, you might need to delete the `aiwatermeter` tree in MQTT Explorer first as the topics are marked to be retained!

**Comment by DrCoolHands** [comment]
Thank you for the reference config. Seems that our MQTT configs are similar enough.

I've cleared out the related topics on my MQTT server and republished using the /mqtt_publish_discovery URL on the meter reader.

The topics were republished with the same flat structure and the incorrect "\~/default/value" paths for the state_topic kvps.

**Comment by caco3** [comment]
can you please provide some screenshots showing the problem?
please also enable debug logging and show us the startup and at least one successful round

**Comment by DrCoolHands** [comment]
Screenshots and logs attached:

Home Assistant showing 'Unknown' data for various fields:
![image](https://user-images.githubusercontent.com/24321125/208801355-20421a5a-83cb-458f-b7ab-d00de2da5be8.png)

MQTT Explorer showing related topics and their payloads:
![image](https://user-images.githubusercontent.com/24321125/208801713-ac09d302-1188-4bce-83a2-7ce48ec30896.png)
Note that the 'state_topic' path for some do not match what is published, include an additional topic 'default'

Logs from debug mode
[watermeter.log](https://github.com/jomjol/AI-on-the-edge-device/files/10273871/watermeter.log)

**Comment by caco3** [comment]
Can you please do 2 things in that order:
1. Post your complete `config.ini` file (remove the username/password)
2. rename your main number. Currently it is called `default`, maybe that's the issue.

**Comment by caco3** [comment]
Thanks for testing it!
I will create a fix for this.
