### ISSUE TITLE
"rate_per_time_unit" shows "inf" or "nan"

### ISSUE THREAD

**Issue by duffy6** [jomjol/AI-on-the-edge-device#1645]
### The Problem

Hi There

"rate_per_time_unit" shows "inf" or "nan"
It's a energy counter. Is this a bug?

![208636171-c8788e30-8dbd-44c0-8cd2-dfbb878c253f](https://user-images.githubusercontent.com/30000750/208643481-e67a910e-d145-494a-a750-d05a4d12d90d.PNG)

### Version

13.0.7

### Logfile

```shell
logfile is empty
```

**Comment by jomjol** [comment]
Can you please change to v13.0.8. There this bug should be removed.
