### ISSUE TITLE
Web UI shows plain HTTP header instead of data

### ISSUE THREAD

**Issue by caco3** [jomjol/AI-on-the-edge-device#1656]
### Issue

When loading the web interface, I sporadically see a HTTP header instead of the requested data, eg:
`HTTP/1.1 200 OK
Content-Type: text/html
Transfer-Encoding: chunked
Access-Control-Allow-Origin: *`
![image](https://user-images.githubusercontent.com/1783586/208922969-591d04fe-56cd-4587-8369-489a0af23ec6.png)

---

The header seems to be missing in the response.
**Good header:**
![image](https://user-images.githubusercontent.com/1783586/208923139-ff9cd123-0b2c-4c85-a2ec-da56a9a49ed7.png)
**Bad header:**
![image](https://user-images.githubusercontent.com/1783586/208923176-e800a44b-7646-4550-906f-8727f7d69ab1.png)

---

Wireshark shows that the device sends all data, but the FIN Flag gets set:
**Good Frame:**
![image](https://user-images.githubusercontent.com/1783586/208923989-ef3d40b1-c915-4159-a194-753be773403c.png)

**Bad Frame:**
![image](https://user-images.githubusercontent.com/1783586/208923820-876cb901-3cdf-41f0-9163-8b5515c99fe6.png)

---

It is not clear to me why this happens. Also I noticed that I only have the issue in Firefox(!). Chrome never shows this issue!

**Comment by Slider0007** [comment]
I also realized this from time to time. Switching to non chunked transfer could possibly improve this -> #1797 

I will still have an eye on it...

**Comment by jomjol** [comment]
Old problem. Many changes on interface. If still valid, please reopen.
