### ISSUE TITLE
PreValue too high

### ISSUE THREAD

**Issue by Github197** [jomjol/AI-on-the-edge-device#167]
My watermeter is showing 158m3 so I wanted to set the PreValue to 158.0000. After dooing so I get the following error message:

158.0000 Rate too high - Returned old value - read value: 158.4511 - checked value: 158.4511

In case you need more info, please tell me what info I shall provide.

Thank you, Rene

**Comment by jomjol** [comment]
Hi Rene,
it looks like your using the option for consistency check of the change rate. Just disable it in the `config.ini` - parameter: `MaxRateValue` -  and you will not get this error (or increase the allowed change rate).
Best regards,
  jomjol
