### ISSUE TITLE
Set previous value - which comma sign?

### ISSUE THREAD

**Issue by Joo01** [jomjol/AI-on-the-edge-device#1672]
### The Problem

For 'set previous value' the page mention "Input (Format = 123.456):"   ... means the dot character should be used. 
But on using the up-down arrows of value field the comma sign is used.
What is the correct character for the decimal separator?   

### Version

13.0.8

### Logfile

```shell
not needed
```

### Screenshots

![image](https://user-images.githubusercontent.com/47685962/209195851-676bf669-f5ba-4559-92ba-01021b4c42da.png)

**Comment by jomjol** [comment]
Both can be handled.
