### ISSUE TITLE
Allow Analog ROI zero point to be rotated

### ISSUE THREAD

**Issue by emics** [jomjol/AI-on-the-edge-device#1691]
### Turn zero point of an Analog Clock

The request is the possibility to set a different zero of Analog ROI clock. 
I have a water meter with Analog indicator not aligned but turned 90 degrees clockwise. The zero of the analog clock isn’t at top of dial (hour 12) but is in the right side (number 3 of the clock).

**Comment by caco3** [comment]
@emics I don't promise that we will add this, but could you please add a photo of your meter here?
Copy it from the UI aft the round is completed,

**Comment by caco3** [comment]
The easiest would be to add a generic offset for each number.
Eg. if your 0.01 analog pointer is rotated 45° clockwise (as described by you), this would mean that it is 1/4 of 0.01 to low. so you would have to add an offset of 0.0025.

**Comment by emics** [comment]
hi @caco3 thanks for your reply.
I've found a workaround configuring the value of **AnalogDigitalTransitionStart** to 4 and now the change of the analog pointer is correct.
i think this issue is not more necessary.
thanks for your fantastic work!
