### ISSUE TITLE
Alignment mark generation fails due to activating #define STBI_ONLY_JPEG

### ISSUE THREAD

**Issue by caco3** [jomjol/AI-on-the-edge-device#1721]
@caco3 also got this `E (95242) C IMG BASIS: Failed to load /sdcard/img_tmp/ref0_org_org.jpg! Is it corrupted?` in rolling 4b23e0c

_Originally posted by @stefan123t in https://github.com/jomjol/AI-on-the-edge-device/issues/1720#issuecomment-1367505354_

**Comment by caco3** [comment]
It seems to have got broken with https://github.com/jomjol/AI-on-the-edge-device/pull/1713
With https://github.com/jomjol/AI-on-the-edge-device/pull/1711 it is still ok

**Comment by Slider0007** [comment]
This commit seems to break it: 2ce25751a9f946933030e87bdcbd8d47f78b40c8 --> PR #1706

**Comment by caco3** [comment]
I could trace it down to only this line: `STBI_ONLY_JPEG`

It looks like as if the alignment mark generation uses something else than JPEG.

This most probably could be changed. Until then, I revert that line.
