### ISSUE TITLE
Hide wifi-credentials from physical access

### ISSUE THREAD

**Issue by Xxplore** [jomjol/AI-on-the-edge-device#1733]
### The Feature

Is it possible to hide the wifi credentials from easy physical access to the sd-card?
I have my device set up in an area that is openly accessible by all my (inhouse) neighbours. 
It would be possible to take out the sd-card and simply put it into an sd-card reader.

**Comment by caco3** [comment]
no, this is currently not supported, sry.

With having physical access, most security functionality can be worked around!

**Comment by nliaudat** [comment]
Storing the wifi credentials in nvs partition (not used actually) could be the solution.

**Comment by caco3** [comment]
> Storing the wifi credentials in nvs partition (not used actually) could be the solution.

yes, right, that would be an option which is a bit more secure.
We would need to read the wlan.ini file on startup and if there is a password, move it to the flash partition and remove it from the wlan.ini file. To update the password, you simply would need to add it to the wlan.ini file to retrigger this process.
At the same time we should do the same with the SSID to have it consistent.

Maybe we could use the PHY partition for this, see https://github.com/jomjol/AI-on-the-edge-device/issues/1681

**Comment by nliaudat** [comment]
I've reparsed the code and the NVS partition is also empty. 
There are many #include <nvs_flash.h>, but no code excepted in main.cpp which has a 
bool Init_NVS_SDCard() function which init the nvs partition for read.
I mean there is an error cause it's not related to initialization of sdcard.

**Comment by nliaudat** [comment]
With the new softap functions, I mean the wlan.ini could be deleted and only remaining in nvs partition

**Comment by caco3** [comment]
> With the new softap functions, I mean the wlan.ini could be deleted and only remaining in nvs partition

But we need to make sure that migration for existing users also works

**Comment by nliaudat** [comment]
I have some propositions : https://github.com/jomjol/AI-on-the-edge-device/discussions/1740
