### ISSUE TITLE
Wishlist new hardware / Wunschliste neue Hardware 

### ISSUE THREAD

**Issue by stener2009** [jomjol/AI-on-the-edge-device#174]
Hello,

there is always problem with the hardware ESP32-CAM. 
Therefore I plan to redesign the hardware and optimize it for the application.

Following point I have already made from my own experience and from reading in the forum

- optimized power supply ( input voltage 5-36V)
- more PRAM (8MB)
- 2 relay outputs (230V)
- fix  eMMC (4gb or 8gb) instead of SD-Card (longer lifetime)
- more LEDs for illumination and PWM-dimming (less reflections)
- JTAG debug interface

- Mechanical dimensions optimal for water, gas and electricity meters

- target price of the finished assembly 10-20€ 

I invite everyone to contribute their wishes

**Comment by jomjol** [comment]
I think, there is a limit of 4MB on the PSRAM. 

![grafik](https://user-images.githubusercontent.com/30766535/113509976-a2726a00-9558-11eb-8cfb-416192779df2.png)
(https://thingpulse.com/esp32-how-to-use-psram/)

**Comment by stener2009** [comment]
External SRAM can be mapped into CPU data memory space. SRAM up to 8 MB is supported and up to 4
MB can be mapped at a time

**Comment by kaskerol** [comment]
Ein oder mehrmaliges Auslesen je Tag per Parameter dazwischen Rückfall in den Schlaf Modus.

**Comment by stromzaehler** [comment]
- additional LAN interface.

**Comment by msome** [comment]
> * additional LAN interface.

+ supporting PoE supply

**Comment by gomito1** [comment]
I apologize if it is not a topic in this post ..
I see that the project allows configuration by fixed IP with three parameters (ip, gateway, netmask) to be able to do LAN communication.
The question comes is, does an ethernet module have to be added and what would be the pins already configured?
or by connecting a USB to ETHERNET converter to the TTL module.

It would be of great help thanks.

**Comment by jomjol** [comment]
The fixed IP is for the WLan as well. Also there you can specify a fixed IP. A ethernet module ist not supported. Background is the limited availablity of GPIOs for the connection and my lack of time :-)
I'll close this issue.

**Comment by maticslaszlo** [comment]
* Infrared flash

**Comment by caco3** [comment]
- screws to attach it properly :)
- USB socket + boot button for easy flashing
