### ISSUE TITLE
Digital/Analog Digits can not be enabled in edit_digits/edit_analog pages

### ISSUE THREAD

**Issue by caco3** [jomjol/AI-on-the-edge-device#1745]
### The Problem

the checkbox gets unchecked again immediately

### Version

rolling

**Comment by caco3** [comment]
@jomjol could you have a quick look? I did n0t understand why it does not work.

Steps to reproduce:
1. Disable digital or analogue in the settings.
2. go to digital/analogue ROI config page
3. the info message "Digital ROIs are disabled - please enable first (Check box top left)" gets shown
4. Enable the checkbox on the top left.

=> It gets disabled again immediately together with the info message "Digital ROIs are disabled - please enable first (Check box top left)"

**Comment by jomjol** [comment]
Bug confirmed - will work on this.

**Comment by jomjol** [comment]
solved in rolling
