### ISSUE TITLE
OTA Upload: Show progressbar

### ISSUE THREAD

**Issue by caco3** [jomjol/AI-on-the-edge-device#1748]
### Issue

See:
 - https://codepen.io/PerfectIsShit/pen/zogMXP

**Comment by caco3** [comment]
@jomjol @haverland @Slider0007 

I created a new OTA page which shows a progressbar during uploading.

Could you test it before we release it into the wild?

Keep in mind that you first have to install it and only then can test it with the next OTA!

https://github.com/jomjol/AI-on-the-edge-device/actions/workflows/build.yaml?query=branch%3Anew-ota-page

**Comment by caco3** [comment]
@jomjol When I test it with a `firmware.bin` it sporadically fails because it hangs after: 
```
I (53147) OTA FILE: File reception complete
I (53257) OTA FILE: Found file: firmware.bin (1703472 bytes)
I (53317) OTA: Starting OTA update
I (53327) OTA: Running partition type 0 subtype 16 (offset 0x00010000)
I (53327) OTA: Writing to partition subtype 17 at offset 0x1f0000
```

This only seems to happen in the legacy mode where we do not reboot before the flashing.
Would it make sense to also replace this with a flashing after a reboot?

**Comment by Slider0007** [comment]
> Could you test it before we release it into the wild?

@caco3 : The progress bar looks really good, is more informative and update executed without any issue.
Some remarks:
- What in my opinion is a bit unusual is the fact that the upgrade starts immediately just by selecting the file. I would prefer to acitivly trigger such a critical task by pressing a button. This also gives me the chance to revert my maybe wrong file selection. 
- When I select a file with e.g. spaces the overlay gets flashed and reminds me but the ota page gets stuck. I have to reload the page. Before I was able to select antoher file and continue without reloading the page.
- When I select an non suitable file (e.g..txt) the file gets processed and it's mentioned that upgrade is in progress which is not always true.
BTW: Is it possible to limit file selection dialog to only relevant files (.bin, .zip, .tflite, ...)? 

Let's see what's the feedback of the others.

> When I test it with a `firmware.bin` it sporadically fails because it hangs after:

Interesting, I use this flash method quite often but I've never had this issue before.

**Comment by jomjol** [comment]
> This only seems to happen in the legacy mode where we do not reboot before the flashing.
> Would it make sense to also replace this with a flashing after a reboot?

You are right and I have harmonized the update after reboot for `firmware.bin` in the newest rolling, as well
(flash firmware after reboot and then do a reboot by itself).

**Comment by jomjol** [comment]
Additionally I find this really cool, but I agree to @Slider0007: addtional button to start after selecting file

**Comment by caco3** [comment]
thanks for your feedbacks!
I am working on those findings.

**Comment by Slider0007** [comment]
@caco3 : Whow, that was quick :-)

I tested it again. Some comments:
- Handling with 2nd stage button is perfect!
- File validation doesn't accept
   - filenames with dash --> e.g. `AI-on-the-edge-device__update__new-ota-page_(399c398).zip`
   --> Maybe it's sufficient to check only `AI-on-the-edge-device__update`
   - firmware.bin
   --> Maybe, just accept all `*.bin` or add `firmware.bin`
- Maybe it's straight forward to limit file selector by showing only valid ones using the accept attrbute? 
--> `<input type="file" name="file_selector" id="file_selector" accept=".bin,.zip,.tfl,.tflite" onchange="validate_file()">`
- Uploading a tflite/tfl file --> Upload sucessful, but progress bar keeps running

Side note / keep in mind: Filename of actual release 13.0.8 (and earlier releases) also doesn't meet new file pattern. 

Personal side note: I like the new page. The MB counter is quite helpful, escpecially when WIFI reception is quite bad to check if it's even loading...

**Comment by caco3** [comment]
Thanks for the feedback!

 > File validation doesn't accept
      filenames with dash --> e.g. AI-on-the-edge-device__update__new-ota-page_(399c398).zip
      --> Maybe it's sufficient to check only AI-on-the-edge-device__update

I use regex and missed the `-`

      firmware.bin
      --> Maybe, just accept all *.bin or add firmware.bin

That's already possible (with the warning)

>  Maybe it's straight forward to limit file selector by showing only valid ones using the accept attrbute?
  --> <input type="file" name="file_selector" id="file_selector" accept=".bin,.zip,.tfl,.tflite" onchange="validate_file()">

Ah nice, I didn't know that.

> Side note / keep in mind: Filename of actual release 13.0.8 (and earlier releases) also doesn't meet new file pattern.

Yes, that's why I only show a warning.

> Personal side note: I like the new page. The MB counter is quite helpful, escpecially when WIFI reception is quite bad to check if it's even loading...

:heart: 

Also I added now a progressbar for the installation (simply counts up).
And it shows an error if it is not up after 300s



>  Uploading a tflite/tfl file --> Upload sucessful, but progress bar keeps running

@jomjol under which conditions do you reboot? Is it on zip and on bin?

**Comment by Slider0007** [comment]
@caco3 : Perfect, everything looks good!

**Comment by caco3** [comment]
thank!

**Comment by Slider0007** [comment]
@caco3: Filenames with capital letter included are not valid ones. Does this have a reason or just missing in pattern checker?

**Comment by caco3** [comment]
it was simply lazyness 😺
