### ISSUE TITLE
Update repo settings

### ISSUE THREAD

**Issue by caco3** [jomjol/AI-on-the-edge-device#1764]
### Issue

@jomjol, kannst Du bitte folgendes in den Einstellungen des repos ändern?

## Settings
- [x] Wiki nicht mehr editierbar machen (Restrict editing to collaborators only): 
  ![grafik](https://user-images.githubusercontent.com/1783586/210600948-f7e3196b-59b7-4d3f-9611-7a20eb4e31c9.png)
- [x] Das "Projects" tab braucne wir nicht:
  ![grafik](https://user-images.githubusercontent.com/1783586/210601373-1dd3cd16-c212-4663-83a9-99809fb5ead6.png)
---
## Repo hauptseite
 Oben rechts bei
![grafik](https://user-images.githubusercontent.com/1783586/210601905-3492c5ac-6375-43b0-ad8c-80459c193246.png)
Könntest Du eine Beschreibung sowie den Link auf die Doku anzeigen:
![grafik](https://user-images.githubusercontent.com/1783586/210602286-54723f0f-6a11-41fe-bdb4-a0c2a26f4e9a.png)
https://jomjol.github.io/AI-on-the-edge-device-docs/

**Comment by jomjol** [comment]
done - thanks for the details decription.
