### ISSUE TITLE
UnicodeDecodeError: 'gb2312' codec can't decode bytes in position 38-39: illegal multibyte sequence

### ISSUE THREAD

**Issue by rimbach64** [jomjol/AI-on-the-edge-device#177]
Hi,
don't know if this is an issue, but flashing does'nt work, because of this error. Used the ESP download tool, with no effect.

Can somebody help me?

Regards
Meikel

**Comment by jomjol** [comment]
I suggest to use the esptool within python.

**Comment by rimbach64** [comment]
Sorry,
I'm a beginner.

Installed Python 3.9 now, same Error, google confused me in total. Thanks for your help.

**Comment by jomjol** [comment]
I have tested it with Pyhton 3.8 and 3.7. But it should also work wit 3.9 with the following description:

Using esptool in python directly

For this you need a python environment (e.g. Anaconda in Win10). Here you need to install the esptool:

`pip install esptool`

Then connect the ESP32 with the USB-UART connector to the system, put it in bootmode and with the following command you can erase the flash and flash bootloader, partitions and firmware in two steps:

```
esptool erase_flash
esptool write_flash 0x01000 bootloader.bin 0x08000 partitions.bin 0x10000 firmware.bin
```

Maybe you need to specify the COM-port if it is not detected by default.

**Comment by rimbach64** [comment]
Okay, thanks.
It works now, but not without a big round in installing some Windows stuff like Visual Studio and so on.
Regards
Meikel

**Comment by theslash** [comment]
Had the same Problem, solved it by moving the Flashtool and the files directyl to c:
Reason was a too long filepath

**Comment by jomjol** [comment]
Solved
