### ISSUE TITLE
Provide JSON values as number and not as string

### ISSUE THREAD

**Issue by tig987** [jomjol/AI-on-the-edge-device#1770]
### The Feature

Currently all values in JSON are provided as strings:

wasserzaehler/main/json {
"value": "2381.5617",
"raw": "02381.5617",
"pre": "2381.5617",
"error": "no error",
"rate": "0.001073",
"timestamp": "2023-01-05T10:45:15+0100"
}

to work with the JSON values it would be better to provide the measurement values as numbers 
and only the real text like "raw", "error" and "timestamp" as strings
like this:

wasserzaehler/main/json {
"value": 2381.5617,
"raw": "02381.5617",
"pre": 2381.5617,
"error": "no error",
"rate": 0.001073,
"timestamp": "2023-01-05T10:45:15+0100"
}

This would make it possible to parse them with Telegraf JSON input (https://docs.influxdata.com/telegraf/v1.24/data_formats/input/json/)
to put them into a Influx or TimescaleDB database.

**Comment by jomjol** [comment]
In some cases the values are not numbers but string. E.g. if not all numbers can be read, than there will be a  "N" in the value. Therefore we send everything by string.
