### ISSUE TITLE
Todo : find why STBI_ONLY_JPEG breaks Alignment mark

### ISSUE THREAD

**Issue by nliaudat** [jomjol/AI-on-the-edge-device#1779]
### The Feature

As mentionned in https://github.com/jomjol/AI-on-the-edge-device/issues/1721 ,STBI_ONLY_JPEG  breaks alignment marks

STBI_ONLY_JPEG  can save 2% of Flash

Todo : 
debug the alignment marks to find why ClassFlowAlignment.h is linked to stb_image.h

I did not find why : 
ClassFlowAlignment.h includes CAlignAndCutImage.h 
CAlignAndCutImage.h includes CImageBasis.h _**(works if STBI_ONLY_JPEG  enabled)**_
CImageBasis.h includes stb_image.h _**( works if STBI_ONLY_JPEG  enabled)**_

**Comment by caco3** [comment]
The images as seen in the Recognition page are stored on the sd-card as BMP images, see `http://<IP>/fileserver/img_tmp/`.

I guess thats the reason.

We should check with  @jomjol what the reason to pick BMP is. Maybe it simply could be switched to JPG as well?

**Comment by jomjol** [comment]
Bitmaps are choosen, because I wanted to avoid lossed due to compression. If we would change the settings of the jpeg, that might work as well.

**Comment by caco3** [comment]
thanks!

I think if you set the jpeg compression to minimum it should be ok

**Comment by jomjol** [comment]
Would be needed to test.
BUT: if we remove the BMP option, we will loose the backward compatiblity, because up to now every image is stored as BMP.

**Comment by caco3** [comment]
I tested your PR https://github.com/jomjol/AI-on-the-edge-device/pull/1789 and it works for me.

If it breaks the backwards compatibility,what impact does this have?
The recognition page seems to be ok after the first round.
And I like that the image are shown larger now.

**Comment by jomjol** [comment]
I checked everything and it does not break the backward compatility. I made a mistake while checking. So we can implement this change.

**Comment by nliaudat** [comment]
fixed in https://github.com/jomjol/AI-on-the-edge-device/pull/1789
