### ISSUE TITLE
WIFI connect fails when WPA key contains "="

### ISSUE THREAD

**Issue by asdt1803** [jomjol/AI-on-the-edge-device#178]
Hi,

It took me some time to find out why the device failes to connect to my WIFI. It seems that WPA keys containing an "=" are not supported. Are you using "=" as a string delimiter?

Regards
Andre

**Comment by jomjol** [comment]
That bug should have been removed in the newer versions.'
Which version are you using?

**Comment by asdt1803** [comment]
Probably this line of code in wlan_coonect.cpp, right?:

	std::string delimiter = " =,";

So a comma or a space in the WPA key would make the WIFI connect fail too. Would that be something worth to be documented?

**Comment by jomjol** [comment]
Corrected in newest rolling

**Comment by jomjol** [comment]
Transferred to release version
