### ISSUE TITLE
Allow finer granularization with MQTT topic structure (Homeassistant auto-discovery)

### ISSUE THREAD

**Issue by maginator** [jomjol/AI-on-the-edge-device#1792]
### The Problem

Hi,

Momentan habe ich das Problem, das wenn ich meine Wasseruhr in die bereits Vorhandene MQTT Struktur einbinden möchte, diese ist nach dem Muster "Home/Raum/Gerät" nach einer Empfehlung von MQTT aufgebaut, das damit dann die Homeassistant Auto-Discovery kaputt geht. Da der Konfigparameter Main Topic in die Home Assistant Struktur gerendert wird.
Man könnte das z.B Aufteilen in DNS Name + MainTopic und nimmt für die Homeassistant Discovery nur den DNS Name oder so.
Da Momentan das ganze irgendwie so nicht mehr Funktioniert

### Version

v13.0.8 (Commit: 04f2f23+)

### Logfile

```shell
Not Needed
```

### Expected Behavior

Werte "Home/HwRaum/Wasseruhr" 

Homeassistant Auto Discovery:  "homeassistant/sensor/Wasseruhr"

und nicht 

Werte: Home/HwRaum/Wasseruhr
homeassistan Auto-Discovery: homeassistant/sensor/Home/HwRaum/Wasseruhr

### Screenshots

![image](https://user-images.githubusercontent.com/19614585/211363403-1507ae48-0fa4-4e5a-a63f-6d334118e884.png)

**Comment by caco3** [comment]
Das ist zur Zeit leider nicht unterstützt.

Beim Homeassistant MQTT Auto-Discovery haben wir uns an die Empfehlung von https://www.home-assistant.io/integrations/mqtt/#mqtt-discovery gehalten:
`<discovery_prefix>/<component>/[<node_id>/]<object_id>/config`

Wobei die `<node_id>` optional ist und von HA nicht verwendet wird!

Für das Maintopic wird der hostname verwendet, sofern es nicht gesetzt wird. 
Dein Problem ist wohl, dass das Maintopic nur ein Level hat.

**Comment by maginator** [comment]
Schade.
Weil ich finde es komisch das man in der jetzigen Konfigurationsmöglichkeit halt nur die Möglichkeit hat die Sachen die nach MQTT gepublisht werden auf Root ebene zu lassen da man sich sonst die homeassistant auto-discovery zerschießt aber wäre cool wenn wenn sich das bei gelegenheit jemand angucken könnte ;)

**Comment by caco3** [comment]
Es liegt leider einiges an Arbeit an und wir machen alles in der Freizeit, da ist leider nicht alles möglich.
Aber Du darfst dich gerne auch selber daran versuchen. Wir unterstützen dich gerne dabei und sind froh um Mitstreiter.

**Comment by maginator** [comment]
Ja gerne. Wenn ihr mir beim Setup helfen könnt Versuche ich mich dran hab ein bisschen Arduino programmier Erfahrung aber gute Ansprechpartner im Haushalt die das können ;)

**Comment by caco3** [comment]
Schau mal hier: https://github.com/jomjol/AI-on-the-edge-device/blob/master/code/README.md

Das ganze MQTT handling ist hier: https://github.com/jomjol/AI-on-the-edge-device/blob/master/code/components/jomjol_mqtt/server_mqtt.cpp

**Comment by JakobTewes** [comment]
Heyhey,

bin auch über die mit MQTT-Sub-Topics nicht funktionierende Discovery gestolpert. Wäre prima, wenn das gefixed würde ;-)
