### ISSUE TITLE
Alg_roi.jpg store into memory directly as JPG

### ISSUE THREAD

**Issue by Slider0007** [jomjol/AI-on-the-edge-device#1799]
### The Feature

Store alg_roi.jpg into memory directly as JPG
- Reduce memory usage 
- Faster refresh

**Comment by caco3** [comment]
Maybe this could be done together with https://github.com/jomjol/AI-on-the-edge-device/issues/1187

**Comment by caco3** [comment]
As far as i understand, the framebuffers are directly JPG.
At least for the demo mode, i simply replace the framebuffer with a read JPG and it just works

**Comment by Slider0007** [comment]
These are my ideas:
Right now, the ROI overlays are drawn over a CImageBasis object every time the alg_roi is requested (Processed in ClassFlowControll::GetJPGStream routine). My idea is to use the already existing ImageTMP CImageBasis object which is needed for alignment anyway and draw ROIs in this object after alignment is done. The result can be stored as JPG in RAM and recalled when it's needed without reprocessing it again.

Advantages:
- less memory due to the fact no additional CImage Object is needed for ROI (save 921kB RAM)
- faster refresh
- ROI only visible when alignment is done
- In early phase till alignment is done, raw image can be shown

I provide a draft the next days, then you can test and have a look to the proposal.

#1187: This means some text needs to be included in the image, right? Do you have an idea / library how to include this?

**Comment by caco3** [comment]
> 921**kB** RAM

You are a genius :smiley_cat: 

> This means some text needs to be included in the image, right? 

Hmm, I see your problem, maybe we simply could draw an icon, eg. for alignment we could show something like:
![grafik](https://user-images.githubusercontent.com/1783586/211670793-3cd1776a-7593-47bb-ad81-e0e5b4e4f7fe.png)

**Comment by Slider0007** [comment]
> Hmm, I see your problem, maybe we simply could draw an icon, eg. for alignment we could show something like:

The image manipulation is done by setting single pixels in an image array (CImageBasis::setPixelColor). Whatever element you'd like to include you have to program it pixel by pixel. As long there is no library, this could be a lot of work. As far as I can see right now there are only basic elements like line, rectangle, circle, elipse. A text library would be great...

**Comment by caco3** [comment]
but a text library again adds RAM usage, drawing a simple icon might be more efficient

**Comment by caco3** [comment]
so if i understand it right, before https://github.com/jomjol/AI-on-the-edge-device/blob/fca37ee69925c9ad3a091787a4af90340886ba41/code/components/jomjol_flowcontroll/ClassFlowControll.cpp#L649 we should check in which step we are and only draw the ROIs if we completed the alignment step.

Looking at https://github.com/jomjol/AI-on-the-edge-device/blob/fca37ee69925c9ad3a091787a4af90340886ba41/code/components/jomjol_flowcontroll/ClassFlowControll.cpp#L76 this should not be too hard.
And maybe we can dram a simple camera while in the `Take Picture` step (althrough I am not sure what currently gets drawn in that step).


Looking on my MQTT Log, `Take Image` takes around 8s, so there is a chance to catch this step:
![grafik](https://user-images.githubusercontent.com/1783586/211673283-f97dd37a-8b3f-4b59-8421-a7dba9f2b4a1.png)

**Comment by caco3** [comment]
If you want, I can create icons for those 2 cases

**Comment by Slider0007** [comment]
In my opinion we have the status text which tells what happens right now. Maybe it's helpful to have status text more prominent if flow is actually processing...
![image](https://user-images.githubusercontent.com/115730895/211677553-b82d30c2-e2df-4b06-b276-8f531b86f63a.png)

Showing the ROI overlay only after the alignment completed is for sure beneficial to avoid some confusion...

**Comment by Slider0007** [comment]
This would be the view before alignment is comleted: 
![image](https://user-images.githubusercontent.com/115730895/211678636-2a590e4c-5aac-4394-82fa-c95d8e9997de.png)

**Comment by caco3** [comment]
Yes, an overlay on the UI would be ok too, but is tricky to implement.

The Web UI only works with polling, which means that the status information might not get loaded at the same time as the image.
So those changes most likely are not fully in sync, causing confusion.

Also one could pull the image separately and eg. show it in Homeassistant. Then we would miss the icons

**Comment by Slider0007** [comment]
> Yes, an overlay on the UI would be ok too, but is tricky to implement.
> 
> The Web UI only works with polling, which means that the status information might not get loaded at the same time as the image. So those changes most likely are not fully in sync, causing confusion.

The image on the webinterface is also only updated with polling (e.g. page refresh). With the refresh of the page or automatic refresh after the specified time the status text is going to be updated, as well (like it's done already)
Or do you mean the sync while the loading / refesh is already initiated because of loading delay?

**Comment by jomjol** [comment]
Writing text to the image: I use `std_image.h` as a simple library. This does not provide writing text to an image, only pixel manipulation.

**Comment by caco3** [comment]
doing it directly on the image would save us the hassle with the UI only partially working//updating!

I would be happy to provide some drawing instructions

**Comment by Slider0007** [comment]
For sure you can provide some drawings if you want :-)

**Comment by caco3** [comment]
@Slider0007 During the step `Take Image` the image is just black, right?
If so, we could just serve an image from the SD Card instead. We would save to have to draw an icon in that case.
What do you think?

**Comment by Slider0007** [comment]
@caco3: Actually, in the step "Take Image" it starts with a black image and then you see the image building up line by line, but this takes only a few secs before it switches to alignment step. Therefore this "image capture process" could be skipped for sure. I was also thinking about this during my coding.

Providing an alternative image during "Take Image" step would be an option, also to avoid the black screen at the beginning of the process.

What is also missing is the visualization when flow is not started yet. Also for this we could show an indication image which is loaded from SD.

Possible steps:
1. Device / webserver started, but flow not started (yet) --> Image with indication "flow not started"
2. Flow started and step "Take image" --> Image with indication of taking image
3. Flow started and step "Alignemnt" --> serve alg / alg_roi (like already coded + ?alignment icon?)
4. and the follwoing steps --> serve alg / alg_roi (like already coded)

What do you think?

**Comment by caco3** [comment]
I like your proposal!

Just seeing a lack picture can really be confusing, there where already a few questions because of this.
And another special image in case the flow is not started yet would also be helpful.
