### ISSUE TITLE
3D Housing link is linked to the housing only project

### ISSUE THREAD

**Issue by queeek** [jomjol/AI-on-the-edge-device#180]
Hi,
in the readme, the thingiverse link points to only the esp32-cam housing.
This is the thingiverse project which includes also the other files and not only the case from the esp32-cam 
https://www.thingiverse.com/thing:4573481
this should be linked in the readme or is there any reason to use the other one?
pull request can be found here: https://github.com/jomjol/AI-on-the-edge-device/pull/179
Cheers
Ina

**Comment by jomjol** [comment]
Thanks for the hint - pull request is accepted
