### ISSUE TITLE
Add support for a pulse reading mode

### ISSUE THREAD

**Issue by teixeluis** [jomjol/AI-on-the-edge-device#1804]
### The Feature

Several meters today have physical features to facilitate the optical readout of pulses by an external device (normally a wm-bus adaptor), notably by the presence of encoder wheels and reflectors next to the dials.

For example:

![image](https://user-images.githubusercontent.com/51710382/211809490-addce8b2-f731-4bed-af54-bfe6991d8141.png)

It could be interesting to provide a new model  or mode of operation, where the device would focus on reading full revolutions of the mirror wheel for example. The measurements would be derived from the count of these pulses.

This could be eventually complemented by the occasional OCR readouts for corrections (using the current implementation).

The advantage of this approach would lie in the potentially higher temporal resolution, assuming recognizing revolutions of a mirror (or similar object) would be a computationally cheaper task.

Thanks

**Comment by Kimble8650** [comment]
My guess is that this is quite heavy computationally, as a constant video stream would be needed to analyse the rotation in real time. I've actually wondered a similar thing, that would it be possible to (in idle mode) check for movement on a very small area of the meter(like the little black star on the image you posted) that would then trigger a digitalisation round.

I would guess that it would be easier to have some external electronics to capture said pulse and then have the water meter reader receive said trigger via a GPIO pin.

**Comment by teixeluis** [comment]
@Kimble8650, yeah some IR diode / sensor combo shining on the rotary mirror would likely be a very simple and effective approach. More difficult to make it work at a distance compared to the camera though.

Thanks for the inputs.

**Comment by jomjol** [comment]
This would be a totally different detection algorithm and therefore cannot be implemented here.

**Comment by nliaudat** [comment]
I've done some test with IR diodes with TCRT5000, in my watermeters, the plexigas between block the IR diode. 
No working result. I've tested https://github.com/hugokernel/esphome-water-meter

I have also tested Hall Effect Sensors, but the magnetic field is too low.

**Comment by teixeluis** [comment]
@nliaudat interesting, ok. Apparently some of the commercial devices use an induction coil to detect the rotation of one of the wheels, while others use infrared. Apparently the wheel with the metallic half circle is for induction sensing.

[](https://api.apator.com/uploads/oferta/woda-i-cieplo/systemy/radiowy/apt-wmbus-na-1/apt-wmbus-na-1-manual.pdf
)

Could it be the angle of incidence of the IR light  affecting your results? Maybe playing with a different angle, and power level could provide better results?

The induction option on the other hand would of course be indifferent to the cover material.

**Comment by teixeluis** [comment]
The commercial wm-bus adaptor for the meter on the picture (Apator SV-RTK), appears to rely on 3 IR diodes in different positions, to illuminate the half circle:

![image](https://user-images.githubusercontent.com/51710382/211923272-c7a51cf5-1caf-4d26-bf31-91f274a966d4.png)

And a phototransistor picks up the reflections. So maybe the amount of IR diodes suggest that the illumination needs to be substantial and from multiple angles in order to provide reliable results.

**Comment by nliaudat** [comment]
@teixeluis I use IR opto ITR8307 for another project and it work very fine sensing from 1-5mm distance.

Here is it's reflective properties :
![Capture d’écran 2023-01-11 230756](https://user-images.githubusercontent.com/6782613/211928729-7553736a-7954-44b8-86d6-9f7a2fd52fef.png)

My plexiglass is ticker, about 2 mm and perhaps may act as prism or the overall distance is more than 5mm.
I do not know the exact properties of your IR sensor (Apator SV-RTK), but it's not ITR8307 nor TCRT5000.

For the hall effect, I've used the internal sensor of esp32 devkit. I may test with HMC5883L or QMC5883L for better results, but the sensor do not detected any changes. I have some skills in  [magnetometers calibration script](https://github.com/nliaudat/magnetometer_calibration) but I do not succeed with that way.

**Comment by teixeluis** [comment]
> Perhaps my watermeter as only an "aluminium foil" (no magnetic) on its surface.

@nliaudat yes, that seems to be the case for the inductive sensing..where an external coil would sense the inductance variations depending on the position of the aluminium half circe. 

From what I learned, in most meters there is a magnetic (mechanical) coupling between the mechanism in the metallic body (which is in contact with the water) and the meter part. This allows the first part to be completely sealed.  But this is buried deep in the meter, so it must be difficult to pickup that magnetic field from an external hall effect sensor. There is even some degree of shielding in order to prevent the device from being tampered with via strong magnetic fields intended to slow down the rotation.

> I do not know the exact properties of your IR sensor (Apator SV-RTK), but it's not ITR8307 nor TCRT5000.

From my last photo it appears that the wm-bus module has discrete diodes and a phototransistor, instead of a single module like yours (Apator SV-RTK is the meter model, and not any IR module).
