### ISSUE TITLE
Watermeter with different number types

### ISSUE THREAD

**Issue by tvunen** [jomjol/AI-on-the-edge-device#181]
I have made a second device for another branch watermeter, but this one have different number types. and some numbers on the digital dials are not recognized. I tried to figure out how to train these new number layouts, but it's looks that this is not going to be an easy job. Is there possible an alternative way to train these numbers.
![watermeter](https://user-images.githubusercontent.com/82120296/114085738-0b881380-98b2-11eb-95f8-e0189d4b2d0e.png)

**Comment by jomjol** [comment]
The training can only be done through the CNN-github. I frequently update this with new number. So if you collect them (2-3 picture for each digit and color), then I will incorporate them in my next training session.

But before two remarks:
1. There are a lot of refections in the images - especially the middle 3 and 1, you almost do not see the lower part of the number
2. Your ROIs are two small. Compare the follwing suggestion with the inner frame as the size of the number itself:
![grafik](https://user-images.githubusercontent.com/30766535/114164323-70338480-992b-11eb-90ab-afb9afaef6c4.png)

**Comment by tvunen** [comment]
Thanks for the quick reply!

I'm going to adjust the ROIs so that the middle square matches the numbers. this weekend I'm going to do some tests to reduce the reflections and increase the contrast. The reflections are indeed a problem and difficult to solve, but do indeed present a problem with the bottom of the numbers. I have enabled the logging with the images of the figures. And noticed that the red / white numbers 1,2,3,4,7,8,9,0 are well recognized 5 & 6 have not yet been displayed. The number 1 of the white / black numbers is read incorrectly anyway, the 0, 2 and 3 are recognized correctly, the rest of the numbers have not yet passed, so 8m3 liters of water must first be used.

When i have some good readings of all the numbers white/black and red/white

With regards,
Tony

**Comment by jomjol** [comment]
Sounds good -I'll close this issue for the time beeing. Just reopen this or a new one, if you have the images.
