### ISSUE TITLE
fix cache of build pipeline

### ISSUE THREAD

**Issue by caco3** [jomjol/AI-on-the-edge-device#1819]
For the Github Actions, we can use caches. One of them caches the Espressif build objects, making a build speed up from 10 to 2..3 minutes.
This no longer seems to work.

the `platformio.ini` changed a lot in the last weeks. I looked a bit into it but already the slightest changes break the caching :(

**Comment by caco3** [comment]
@nliaudat do you understand why caching no longer works?

As you can see [here](https://github.com/jomjol/AI-on-the-edge-device/actions/workflows/build.yaml?query=branch%3Arolling), it stopped working after this changes: https://github.com/jomjol/AI-on-the-edge-device/commit/e661e1d7f229a566a076a8abb24aad5f8d14070f

@Slider0007 I looked into it but could not trace it down to the reason :(

**Comment by nliaudat** [comment]
I mean sdkconfig.esp32cam-testing and in general all sdkconfig. XXX another than default should no be uploaded to repo. 
The github cache is limited in size and many pull request in a short time from different branches can lead to a bad cache. 
I propose deleting all cache entries and sdkconfig xxx

- sdkconfig - Kopie.defaults
- sdkconfig - Kopie.esp32cam
- sdkconfig.esp32cam-testing

https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#managing-caches

**Comment by caco3** [comment]
could you give it a try?
You can also do it in your own fork if you want.

**Comment by nliaudat** [comment]
Last run fast ...
![image](https://user-images.githubusercontent.com/6782613/212427500-3e63e00e-8fc9-4bff-84da-2ca9acda9fe8.png)

**Comment by nliaudat** [comment]
next build : Cache not found for input keys: Linux-pio-1829/merge

Cache is full and latest build are not stored.

**Comment by caco3** [comment]
> next build : Cache not found for input keys: Linux-pio-1829/merge

We have separate caching for each branch, and because its the first build for that branch, obviously there is no chache available yet, see https://github.com/jomjol/AI-on-the-edge-device/actions?query=branch%3Aesp_sys_info

> Cache is full and latest build are not stored.

The cache can not get full in this way. See https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#force-deleting-cache-entries, github automatically starts deleting other caches if space is exceeded!

> Last run fast ...

That is interesting!

Sadly I can not reproduce this :(
I merged your sdkconfig cleanup, let it build in rolling, then did a simple change of the readme, but still it runs a ful build, see https://github.com/jomjol/AI-on-the-edge-device/actions/runs/3915776245

**Comment by nliaudat** [comment]
Have to investigate futher ....

What about "Create clean-branch-cache-after-pull-request-got-closed.yml"

**Comment by nliaudat** [comment]
Latest small commit (add file to git ignore) : 
https://github.com/jomjol/AI-on-the-edge-device/pull/1830
Cache not found for input keys: Linux-pio-1830/merge

![image](https://user-images.githubusercontent.com/6782613/212439569-c42921ef-a3cd-4515-a01f-9974218340f3.png)

**Comment by nliaudat** [comment]
use build cache [v3.2.3](https://github.com/actions/cache/releases/tag/v3.2.3) ??

```
 - name: Use Build Cache
      uses: actions/cache@v3
      with:
        path: ./code/.pio/
        key: ${{ runner.os }}-pio-${{ github.ref_name }}
```

**Comment by nliaudat** [comment]
I've deleted all cache in my repo :=> compile time ~2 min

![image](https://user-images.githubusercontent.com/6782613/212466073-2078a7f8-0227-48ae-b794-284ce3ba3ad6.png)

Here with no deletion  => compile time ~7 min

![image](https://user-images.githubusercontent.com/6782613/212466100-52e44fa8-57a5-4ab2-81a0-28c79b0c28e0.png)

**Comment by nliaudat** [comment]
I'v add manually triggered workflow clear_cache.yml in https://github.com/jomjol/AI-on-the-edge-device/pull/1831

**Comment by caco3** [comment]
> What about "Create clean-branch-cache-after-pull-request-got-closed.yml"

I tried to use the example from https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#force-deleting-cache-entries, but it does not work due to missing credentials.

> I've add manually triggered workflow clear_cache.yml in https://github.com/jomjol/AI-on-the-edge-device/pull/1831

:heart: 

Does that fix the caching issue?

**Comment by caco3** [comment]
Looking at following screenshot shows that it works for your forked rolling but not ours:
![grafik](https://user-images.githubusercontent.com/1783586/212471315-60ee5eff-6eb6-4512-9284-a5ca4776f00e.png)

maybe https://stackoverflow.com/a/63590002 has an explanation:
>    Once you create a cache, you cannot change the contents of an existing 
>  cache but you can create a new cache with a new key.

Since we modified the `platformio.ini`, the cache gets invalid but can not be updated.

We need to delete that cache somehow or update the key used for it.

> GitHub will remove any cache entries that have not been accessed in over 7 days.

Or maybe it solves itself after a week?

**Comment by caco3** [comment]
I reworked the build pipeline according the example in https://github.com/actions/cache/blob/main/tips-and-workarounds.md#update-a-cache

Hopefully this fixes it now.
Even more, according to the docs, the branches are supposed to also use the caches from `rolling`.

=> https://github.com/jomjol/AI-on-the-edge-device/pull/1836

**Comment by caco3** [comment]
@nliaudat  sorry to have accused your changes to platformio.ini.
I now learned a lot about the caching and could improve it even further with that pull request.

**Comment by nliaudat** [comment]
@caco3  np, but please learn platformio.ini env asap :)
