### ISSUE TITLE
Fresh installation

### ISSUE THREAD

**Issue by rimbach64** [jomjol/AI-on-the-edge-device#182]
Hi Guys,
after hurdeling with flashing the ESP, I stuck now with installing the SD-Card. Sorry, I'm a beginner.

Is it possible that I have to copy every single file from Github to my SD-Card? I cannot find a Cardimage or ZIP-File.

Regards
Meikel

**Comment by jomjol** [comment]
You can download the complete repository and then copy the content of the subdirectory "sd-card" to the card.
Be aware, that not every card is working.

You can find a installation intruction in the Wiki: https://github.com/jomjol/AI-on-the-edge-device/wiki/Installation
