### ISSUE TITLE
New Training Data - Red on Black Analogue Gas Meter

### ISSUE THREAD

**Issue by jtricerolph** [jomjol/AI-on-the-edge-device#1823]
Hope this is right, have followed instructions as best I can, unfortunately cannot frame the digit in the inner box without including a little of the white of the window.
Have never done pull or submitted with github and docs said other option was to post zip of digits here.
### Files

[red-on-black.zip](https://github.com/jomjol/AI-on-the-edge-device/files/10410710/red-on-black.zip)

**Comment by jomjol** [comment]
Please check the newest version: https://github.com/jomjol/neural-network-digital-counter-readout/raw/master/dig-class11_1600_s2.tflite

**Comment by jtricerolph** [comment]
sweet, thanks, i just drop this on sd card and change in config right?

**Comment by jtricerolph** [comment]
Fantastic, first dozzen rounds or so are working a treat 👍
Thanks

**Comment by jtricerolph** [comment]
Overnight has seen a stream of consistent results many thanks 🙏👍
