### ISSUE TITLE
Please verify the links

### ISSUE THREAD

**Issue by TBobsin** [jomjol/AI-on-the-edge-device#1824]
### The Problem

all over the site are links that are not reachable or show "oh not here, look there" 
i just downloded the file initial_esp32_setup__13.0.8.zip
in the readme.md  is https://github.com/jomjol/AI-on-the-edge-device/wiki/Installation oh not there :(  (https://github.com/jomjol/AI-on-the-edge-device/wiki/Installation) 

In the latest Releases url: https://github.com/jomjol/AI-on-the-edge-device/releases - why not link to the documents? 

Initial Setup:
1. Use the initial_esp32_setup.zip ( https://github.com/jomjol/AI-on-the-edge-device/wiki/Installation ) as alternative to have a clean install.

404
https://github.com/jomjol/-AIon-the-edge-device/wiki/Installation

Link chaos is no pleasure

### Version

1

### Logfile

```shell
no
```

### Expected Behavior

links are working :)

### Screenshots

take as mana as you want :)

**Comment by TBobsin** [comment]
if i get my first run i got an error on my device, (ok that's an other problem) but the links is not to the documentation
We have one or more critical errors:
0x00000001
0x00000002

Please check [github.com/jomjol/AI-on-the-edge-device/wiki/Error-Codes](https://github.com/jomjol/AI-on-the-edge-device/wiki/Error-Codes) for more information!

**Comment by caco3** [comment]
please be patient!
The documentation is in a transition and is quite some work to do!
