### ISSUE TITLE
Readings not working

### ISSUE THREAD

**Issue by MarcelloPignata** [jomjol/AI-on-the-edge-device#184]
After quite some tries with the setup I managed to get the alignment right, just for the readings to be all wrong

![contatore](https://user-images.githubusercontent.com/72017683/114264576-04652080-99ec-11eb-915e-1d1ff2472ff8.png)

Anyone know what could be the issue here? I might be getting something wrong that I'm not aware of.
Thanks in advance!

**Comment by jomjol** [comment]
1. It looks likes, your image is not fully sharp or is this a effect of the rotation? Can you post a raw image?
2. The naming of your ROIs is not unique. There some analog and digital ROIs have the same name. Resulting in the mixing on the html page. The internal recognition is still working - so this will not improve the result.

**Comment by MarcelloPignata** [comment]
I'm gonna try again in the next few days and I'll let you know, thanks!

**Comment by MarcelloPignata** [comment]
After some tries and little tweaks I managed to get it to work fine, sorry for opening the issue and leaving you hanging, thank you very much for your work and help!
