### ISSUE TITLE
Counter switches to early to the next full m³ value

### ISSUE THREAD

**Issue by ollibaba** [jomjol/AI-on-the-edge-device#185]
The counter switches to early the the next full m³ value (here from 486,xxxx to 487,xxxx), because the rotation to the next full m³ of the last digit in the watermeter starts with all values greater than x0,7 m³. So you can see 2 half numbers in the last digit (in my example a half 6 and a half 7). Then after some error messages and correction tries the software recognizes the counter sum of 487,8145, But the correct value is 486,8145
There should be a check in connection with the x0,1 pointer that could prevent such an issue.
Greetings ollibaba

![watermetervalue486](https://user-images.githubusercontent.com/41732822/114271301-fa094d80-9a10-11eb-9282-89880e54ac5b.JPG)

![watermetervalue486-2](https://user-images.githubusercontent.com/41732822/114276910-0e594480-9a29-11eb-87e2-d0a5f1654323.JPG)

**Comment by jomjol** [comment]
This check is implemented:

![grafik](https://user-images.githubusercontent.com/30766535/114278912-2da89f80-9a32-11eb-8362-8437041bdb78.png)

By default it is disabled, because it causes trouble in pure digit counter types.

Remark: you should improve the sharpness of the image a bit.

**Comment by ollibaba** [comment]
Ok. Thanks. Changed to true now. Will see if it works. 
Can take a while until next change will happen.
