### ISSUE TITLE
Support saturation / contrast or at least check actual support to have proper documentation

### ISSUE THREAD

**Issue by Slider0007** [jomjol/AI-on-the-edge-device#1851]
### The Feature

Support saturation / contrast or at least check actual support to have proper documentation

![image](https://user-images.githubusercontent.com/115730895/212561781-94ef120a-d763-47c8-83f8-cfd460c9a2e5.png)

comapre discussion #1826

**Comment by jomjol** [comment]
This is a problem of the copied ESP32 driver, which we will not update within this project. We can update it to the most recent one.
But as there is a high risk (out of experience), that we run into stability problems. Therefore we should do that only after the next release.

**Comment by Slider0007** [comment]
Implemented with #2048.

Please be aware that this change could affect existing camera configuration.
