### ISSUE TITLE
Question: better recognition with custom images?

### ISSUE THREAD

**Issue by micky0867** [jomjol/AI-on-the-edge-device#186]
Hi,

thanks a lot for your project, it's amazing!

Sometimes the images are not recognized correctly on my gas-meter.
I'm wondering if I can download a bunch of images (likely from /img_tmp every 5 minutes) and use your neural-network project to create a custom tflite-file from that?
Maybe this will enhance the recognition a bit more, because of the same colors, illumination and angle/distance.

BR
Michael

**Comment by jomjol** [comment]
The training of the tflite file is published as well - so feel free to use this for your own personalized cnn.
https://github.com/jomjol/neural-network-digital-counter-readout

Anyway I can offer, that you send me 2-3 images per digit and I will incorporate them into my next training. By this, the new number type will also be beneficial for other users.

Best regards,
   jomjol
