### ISSUE TITLE
config errors with default config

### ISSUE THREAD

**Issue by caco3** [jomjol/AI-on-the-edge-device#1868]
> While stepping through the config wizard I have seen the following dialogs multiple times:
      Configuration got updated. Please reboot to activate changes!
      In the selected field the value '' in the section 'MQTT' in the field 'HomeassistantDiscovery' is invalid. PLEASE CHECK BEFORE SAVING!
      In the selected field the value '' in the section 'MQTT' in the field 'MeterType' is invalid. PLEASE CHECK BEFORE SAVING!

That is a separate topic and I have seen it before. I will create an issue for this.

_Originally posted by @caco3 in https://github.com/jomjol/AI-on-the-edge-device/issues/1827#issuecomment-1396174854_

**Comment by caco3** [comment]
I can not reproduce this!

The default config from https://github.com/jomjol/AI-on-the-edge-device/blob/rolling/sd-card/config/config.ini contains everything that is needed!

@stefan123t I guess you used a config file which did not yet have the addition config parameters which got recently added.

**Comment by stefan123t** [comment]
@caco3 i do see neither `HomeassistantDiscovery` nor `MeterType` in the config.ini / rolling linked by you above ?

**Comment by caco3** [comment]
You are right, I somehow missed this, sry.

This will be fixed inhttps://github.com/jomjol/AI-on-the-edge-device/pull/1880
