### ISSUE TITLE
[Code] letter order wrong in the code: ligth <> light

### ISSUE THREAD

**Issue by ozett** [jomjol/AI-on-the-edge-device#1875]
### The Problem

wanted to check for http-url examples to make API/REST calls to get some images,
and [the docu told me to look in the code](https://jomjol.github.io/AI-on-the-edge-device-docs/REST-API/) for API-Call definiton

i looked in the code and saw a reverted letter in the word "light".
may not serious, because it was used 2 times, but maybe better to spell it correct?

https://github.com/jomjol/AI-on-the-edge-device/blob/eefdc74e9ae64f9cc62f284440d4bf2c4b62139a/code/components/jomjol_controlcamera/server_camera.cpp#L126

| light vs ligth|
|:---:|
![image](https://user-images.githubusercontent.com/5937811/213492946-2a18cf3a-9d94-46db-9234-2c6847793ad7.png)

### Version

13.0.8

### Logfile

```shell
-not needed
```

### Expected Behavior

spelling correction

### Screenshots

above

### Additional Context

--

**Comment by caco3** [comment]
Thanks, I will correct it.

There are several other typos, like the classical German error "Make Picture" vs. "Take Picture".
I would how ever not change that one as it would break the API.

**Comment by caco3** [comment]
https://github.com/jomjol/AI-on-the-edge-device/pull/1881
