### ISSUE TITLE
Disable status "Sending MQTT" for MQTT publishing to topic "status"

### ISSUE THREAD

**Issue by Slider0007** [jomjol/AI-on-the-edge-device#1885]
### The Feature

As is now, one of the status we send over MQTT is "Sending MQTT":
![image](https://user-images.githubusercontent.com/115730895/213862630-4b8c37d7-cc45-4692-a652-df37023dfbf5.png)
![image](https://user-images.githubusercontent.com/115730895/213862632-0ec6750b-45a8-484b-bc08-0da676d7f266.png)
See https://github.com/jomjol/AI-on-the-edge-device/blob/rolling/code/components/jomjol_flowcontroll/ClassFlowControll.cpp#L88

I would suggest to disable sending this state over MQTT.
#####################
> > I would suggest to disable sending this state over MQTT.
> 
> Just for my understanding, what's your background thinking to remove this? If this would be disabled what about the state "Sending InfluxDB"? Maybe it could be combined using a more generic text e.g. "Publish results" for both states or get rid of both states?

Its kind of odd that there is a MQTT message which states "sending MQTT message".
We actually are sending at other times as well.

Sending InfluxDB is something else for me as it might be useful to see in MQTT when this happens.
So I just would disabling the MQTT status sending for that step.

_Originally posted by @caco3 in https://github.com/jomjol/AI-on-the-edge-device/issues/1858#issuecomment-1399045048_

**Comment by caco3** [comment]
Having another look on it, i think we can keep it as is now.

![grafik](https://user-images.githubusercontent.com/1783586/222987882-a14cc0e5-b051-41fd-8931-3082d9fbd494.png)

**Comment by friedpa** [comment]
Können wir diese Texte nicht ganz in Englisch ausgeben, Es sind bereits viele nicht Deutsch sprechende Benutzer dieses Projektes an Bord und der Text ist so wie so am Anfang und am Ende in Englisch.....

**Comment by caco3** [comment]
hehe
Der Test vom Device **ist** in englisch.
Der deutache Teil kommt von meinem HA.
