### ISSUE TITLE
REST-API: /sysinfo not in json ?

### ISSUE THREAD

**Issue by ozett** [jomjol/AI-on-the-edge-device#1887]
### The Problem

try too make some REST-api calls on some endpoints,
but got errors for the format.

is there something wrong with the syntax of the expected json-return?
https://github.com/jomjol/AI-on-the-edge-device/blob/defbd60ccf8ca8791df0a14c392e6f0ac65ee5a1/code/main/server_main.cpp#L340

### Version
Release: v13.0.8 (Commit: 04f2f23+)
### Logfile
```shell
-
```
### Expected Behavior
no errors on json-syntax

### Screenshots
| 1 |
| :---:|
|![image](https://user-images.githubusercontent.com/5937811/213864182-0abb004e-fa4a-4ece-b3b4-018f0316e593.png)|
| 2 |
![image](https://user-images.githubusercontent.com/5937811/213864262-3ced74d3-53a2-42b5-952a-1a7e55c8d226.png)
|3|
![image](https://user-images.githubusercontent.com/5937811/213866410-d5b5e4d7-4135-4414-88a5-9df1b3f399c5.png)

### Additional Context

[{"id":"78c1700e5af5bb63","type":"inject","z":"d838f7c4a438035b","name":"rest-api","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":1630,"y":420,"wires":[["1d4498daebf8ce3a"]]},{"id":"1d4498daebf8ce3a","type":"http request","z":"d838f7c4a438035b","name":"63-sysinfo","method":"GET","ret":"obj","paytoqs":"ignore","url":"http://192.168.14.63/sysinfo","tls":"","persist":false,"proxy":"","insecureHTTPParser":true,"authType":"","senderr":false,"headers":[],"x":1830,"y":420,"wires":[["ceecbd5a353a2499"]]},{"id":"ceecbd5a353a2499","type":"debug","z":"d838f7c4a438035b","name":"sysinfo","active":true,"tosidebar":true,"console":false,"tostatus":true,"complete":"true","targetType":"full","statusVal":"payload","statusType":"auto","x":2180,"y":420,"wires":[]}]

**Comment by ozett** [comment]
this is great return on missing endpoints.
sadyl seems not to work on /info

![image](https://user-images.githubusercontent.com/5937811/213864459-a7811400-3a16-414f-864e-8faab4ebe2be.png)

**Comment by ozett** [comment]
as i looked up the endpoints :
/cputemp.html
(the full url must be given? but unusual to send the ending ".html").

so one should better expect a redirect?

https://github.com/jomjol/AI-on-the-edge-device/blob/905b5a2ac5b4ac42e5793b0386d0dd9406195bfe/code/components/jomjol_tfliteclass/server_tflite.cpp#L960

and sadly is not a json, and some special chars are not escaped?

![image](https://user-images.githubusercontent.com/5937811/213864642-55af3115-32ee-4240-8abc-a34491113bec.png)

**Comment by ozett** [comment]
(https://github.com/jomjol/AI-on-the-edge-device/blob/905b5a2ac5b4ac42e5793b0386d0dd9406195bfe/code/components/jomjol_tfliteclass/server_tflite.cpp#L1013)

should work?

![image](https://user-images.githubusercontent.com/5937811/213864885-26d9f391-653c-4a31-936b-facc0e9285da.png)

**Comment by ozett** [comment]
while testing all nothing on my module on:

/value 
/value.html 
/wasserzaehler.html

https://github.com/jomjol/AI-on-the-edge-device/blob/905b5a2ac5b4ac42e5793b0386d0dd9406195bfe/code/components/jomjol_tfliteclass/server_tflite.cpp#L991

![image](https://user-images.githubusercontent.com/5937811/213864948-0de93967-1a89-460e-9286-f06411fa5e26.png)

**Comment by ozett** [comment]
look like there is a bad character `\n` in the json

![image](https://user-images.githubusercontent.com/5937811/213878764-6696124a-e976-4544-bd7e-9106859efb77.png)

**Comment by caco3** [comment]
Thanks for your input!

Sadly, the REST API has grown a lot and there are a lot of inconsistencies in it (like an URL with appended` .html` but then returning `JSON`.

I created https://github.com/jomjol/AI-on-the-edge-device/issues/1889 as an enhancement to work on this.

Sadly it is quite some work and it would break the current API which will not be loved by many users.

**Comment by caco3** [comment]
> (
> 
> https://github.com/jomjol/AI-on-the-edge-device/blob/905b5a2ac5b4ac42e5793b0386d0dd9406195bfe/code/components/jomjol_tfliteclass/server_tflite.cpp#L1013
> )
> 
> should work?
> 
> ![image](https://user-images.githubusercontent.com/5937811/213864885-26d9f391-653c-4a31-936b-facc0e9285da.png)

that one works for me, but I think your version is too old for that. You could try `rolling` or wait for the next release which is coming very soon.

**Comment by Eldarion85** [comment]
Why don't i check here first before i do the work of making the same screenshots again to open a issues :D

![JSON_OK](https://user-images.githubusercontent.com/90176159/213906996-49edf1da-dd65-437e-85d0-571a76b85004.png)

![JSON_Fehler](https://user-images.githubusercontent.com/90176159/213906998-5a75682a-db69-445d-b5fd-b00d513dfb32.png)

**Comment by ozett** [comment]
@Eldarion85 
![image](https://user-images.githubusercontent.com/5937811/213909293-6aff3615-3c94-4289-bd23-904abe3832d0.png)
