### ISSUE TITLE
Unable to build with PIO

### ISSUE THREAD

**Issue by v-c** [jomjol/AI-on-the-edge-device#189]
Here's the error I get:

xtensa-esp32-elf-ar: .pio\build\esp32cam\esp-idf\tfmicro\libtfmicro.a: No space left on device
*** [.pio\build\esp32cam\esp-idf\tfmicro\libtfmicro.a] Error 1

**Comment by v-c** [comment]
I guess the board I was using only had 4MB of PSRAM.
 
I have ordered one that has the required 8MB PSRAM and will build for that: https://www.amazon.com/Aideepen-ESP32-CAM-Bluetooth-ESP32-CAM-MB-Arduino/dp/B08P2578LV/

**Comment by v-c** [comment]
Even with the new board, I am not sure how to ensure the 8MB of PSRAM is accessible. As per this  https://docs.platformio.org/en/latest/boards/index.html and the platformio.ini file in this project, I will only be able to access 4 MB PSRAM. What am I missing?

**Comment by jomjol** [comment]
Your problem is not the PSRAM. I'm also only using 4 MB, I think the 8MB are not accessible (at least to some espressif documentation, which I cannot find right now).
Are you sure to use the newest version with some space optmiziations (see my sdkonfig)

**Comment by v-c** [comment]
I am using the latest version of PlatformIO, Espressif toolchain and this Git repo. That's when I see this error.

**Comment by jomjol** [comment]
Hard to help you. I would need more information, e.g. logfile or comparable. This error is not known to me.

**Comment by jomjol** [comment]
seems to be solved in another issue - please reopen on demand

**Comment by ThomasCr** [comment]
> xtensa-esp32-elf-ar: .pio\build\esp32cam\esp-idf\tfmicro\libtfmicro.a: **No space left on device**

says all, your local disk drive is full :)
