### ISSUE TITLE
Web page not loading (ERR_INCOMPLETE_CHUNKED_ENCODING)

### ISSUE THREAD

**Issue by frazer84** [jomjol/AI-on-the-edge-device#1894]
### The Problem

Accessing the website of my ESP32-CAM-module running AIOTED, the page will not load in full (images missing).
This applies to all pages, and pages without images like the System Info page loads very slowly.

In the Chrome Developer Console, errors like this one are showing, and no images are loaded:
`GET http://192.168.1.253/readconfigcommon.js net::ERR_INCOMPLETE_CHUNKED_ENCODING 200 (OK)`

The unit does send messages through MQTT but they are obviously not correct since I can't configure it without any images loading.

I have set up multiple devices using the same hardware (same ESP32-board and same SD card) and those work as intended.

### Version

Release: v13.0.8 (Commit: 04f2f23+)

### Logfile

```shell
[6d19h47m16s] 2023-01-20T06:50:57	<ERR>	[C FIND TEMPL] Failed to load /sdcard/config/ref0.jpg! Is it corrupted?
[8d12h47m09s] 2023-01-21T23:50:50	<ERR>	[OTA FILE] Failed to read existing file: ���?!
[8d13h01m51s] 2023-01-22T00:05:31	<ERR>	[OTA FILE] Failed to read existing file: ԛ�?!
```

### Expected Behavior

Images, like the recognition image and reference image, are shown in the web interface.

### Screenshots

![Screenshot 2023-01-21 at 23 19 10](https://user-images.githubusercontent.com/5439752/213889229-b0163fdb-5067-4d28-bcde-da7f3ccdbc7e.png)

**Comment by caco3** [comment]
Maybe you did not setup the SD Card properly?

I simply would redo the setup.

**Comment by caco3** [comment]
Also the next release is coming soon. You can either wait for it or use the latest rolling.

**Comment by frazer84** [comment]
> Also the next release is coming soon. You can either wait for it or use the latest rolling.

Thanks. I'll try that and see if it helps. I've already tried to reformat the SD card and redone the setup.
