### ISSUE TITLE
Additional Metertype with Unit °C and °F

### ISSUE THREAD

**Issue by HolliDolli** [jomjol/AI-on-the-edge-device#1899]
### The Feature

Configuration allows only Metertypes with Volumes.
I'm using the device to read the water temperature on a Vitocal 161 Waterheater.
Unit °C would't be nice to have.

**Comment by caco3** [comment]
The meter type selection is used for the Homeassistant  MQTT Discovery. Is it also supporting other units? If so ,please feel free to propose extending it.

Changes needed:
- https://github.com/jomjol/AI-on-the-edge-device/blob/master/code/components/jomjol_flowcontroll/ClassFlowMQTT.cpp#L134
- https://github.com/jomjol/AI-on-the-edge-device/blob/35fa2bd3531127072edf25dcd5354f757eb0e875/sd-card/html/edit_config_param.html#L677

**Comment by caco3** [comment]
It is ok to ask/suggest here. Thanks for taking your time to do so!

You always can use the "Other" for meter type to have it unit less!
The selection is only there to make the live of Homeassistant users easier.

**Comment by HolliDolli** [comment]
That's what I did, I currently use "other". and everything works fine.
It's just a "problem" in HomeAssistant. Data is mixed in grafics with other numerical data. And it should be mixed with other temperatures. No real problem, just a proposal for enhancement. So, if someone is working on that anyways, maybe that can be done "en passant".

**Comment by jomjol** [comment]
The topic is, that if we start with °C and so on, there are douzends of other things that you can measure and expected to be implemented. We will stay with the main purpuse and suggest to use the "other" for all other devices. 
But anyway, thanks for bringing up this idea.

**Comment by HolliDolli** [comment]
OK, valid point. but may i suggest to bring the unit for the option "other" to the config-file? so any unit can be set by editing the raw-file.

**Comment by jomjol** [comment]
@HolliDolli : as @caco3 mentioned it is a lot of work, which we cannot follow up currently.

But we are happy for any support and commits - support is warmly welcome.
