### ISSUE TITLE
Incorrect image recognition

### ISSUE THREAD

**Issue by v-c** [jomjol/AI-on-the-edge-device#191]
I'm seeing incorrect image recognition a lot. The numbers itself are not correct, despite setting the ROI. See image
![Image](https://user-images.githubusercontent.com/19736118/115265064-dd51d180-a104-11eb-9b98-616cde9863b4.png)

**Comment by jomjol** [comment]
Your image quality still needs some improvement. The contrast is tool low. Maybe you can make it a bit sharper or your camera has a problem.

**Comment by jomjol** [comment]
Okay got it. This is because 2 of your ROIs have the same name - check the config.ini and rename one of them.

**Comment by v-c** [comment]
That was exactly right about the ROI's having the same name.
