### ISSUE TITLE
Since version 14 RC1 I receive the error "Header fields are too long for server to interpret"

### ISSUE THREAD

**Issue by wokkeltje13** [jomjol/AI-on-the-edge-device#1940]
### The Problem

On lots of places in the webinterface I receive the message "Header fields are too long for server to interpret" since the update to version 14 RC1 (remains in RC2)
It looks like issue 502 [[https://github.com/jomjol/AI-on-the-edge-device/issues/502](url)](https://github.com/jomjol/AI-on-the-edge-device/issues/502)

### Version

Release: v14.0.0-RC2 (Commit: 4395135+)

### Logfile

```shell
nothing special in the logfile
```

**Comment by caco3** [comment]
Thanks for reporting it!

According to https://github.com/espressif/arduino-esp32/issues/2983 we might need to increase [CONFIG_HTTPD_MAX_REQ_HDR_LEN](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/kconfig.html#config-httpd-max-req-hdr-len).

Which webbrowser are you using?

**Comment by wokkeltje13** [comment]
Edge 109 and Edge Beta 110, both same result

**Comment by caco3** [comment]
can you show a screenshot of the webbrowser console where it shows the error?
And if possible the request header?

According to https://github.com/jomjol/AI-on-the-edge-device/blob/rolling/code/sdkconfig.defaults#L105 we already set it from 512 to 1024!

**Comment by caco3** [comment]
With Firefox, it shows a usage of 360 bytes:
![grafik](https://user-images.githubusercontent.com/1783586/215339618-3b0c1c6e-d642-4124-85ae-5a7247542888.png)

**Comment by wokkeltje13** [comment]
![image](https://user-images.githubusercontent.com/57153640/215340943-34956c3f-b9bd-40e9-bf31-dd18127e64e1.png)
No Idea how to retrieve the header size in Edge. I know I need to use F12, but can't find header size

**Comment by wokkeltje13** [comment]
![image](https://user-images.githubusercontent.com/57153640/215341352-5e1eb762-836a-454d-9110-db3e90af0014.png)

**Comment by wokkeltje13** [comment]
After clearing cookies and cache, It seems that everything is working now. maybe other users can have the same issue.

**Comment by caco3** [comment]
It looks like your header is quite large.

But this seems to be an issue of your webbrowser and we can not just increase the buffer further as we are short of memory. Also if this would be a common issue, more users  would have had the same issue.
