### ISSUE TITLE
Kein Aufruf mit http://ip/capture_with_flashlight mit v6.7.0

### ISSUE THREAD

**Issue by Knallochse** [jomjol/AI-on-the-edge-device#196]
Seit der Version v6.7.0 - 2020-04-23 geht der Befehl

http://IP/capture_with_flashlight
Bei mir nicht mehr.

Problem wurde von im IoBroker Forum von anderem User bestätigt 

https://forum.iobroker.net/topic/36622/wasserzähler-version-2-all-in-device/1258

Es kommt nur die Rückmeldung

`Failed to read existing file`

Ich benutze den Befehl um das Bild in meiner VIS anzuzeigen.

**Comment by jomjol** [comment]
Hi, ja das kann ich bestätigen. Inzwischen ist die Firmware so groß geworden (98,1% des verfügbaren Platzes), dass ich für die Vorbereitung auf ein Upgrade auf die nächste ESP-IDF-Version (v4.3) Features herausnehmen musste.
Dachte nicht, dass das noch genutzt wird - wenn dringend benötigt, kann ich es wieder rein programmieren.
Alternativ kann '/img_tmp/raw.jpg' verwendet werden. Dann kommt das letzte Bild halt aus dem Speicher und nicht direkt aufgenommen.
Würde das reichen?

**Comment by Knallochse** [comment]
Das geht vollkommen in Ordnung 👍
