### ISSUE TITLE
Image alignment: parameter "flip image size" produces weird ROI image

### ISSUE THREAD

**Issue by Slider0007** [jomjol/AI-on-the-edge-device#1961]
### Discussed in https://github.com/jomjol/AI-on-the-edge-device/discussions/1960

<div type='discussions-op-text'>

<sup>Originally posted by **ujagusch** February  1, 2023</sup>
Nach dem update auf Release: v14.0.0-RC8 zeigt das Display in Recognition und Overview folgende Anzeige:

![image](http://taxi-troisdorf.de/bilder/fehler2.jpg)]

Die Auswertung der Digital und Analoganzeigen ist aber korrekt, ebenso werden diese in Recognition korrekt angezeigt.
Weder erneutes Betätigen von Overview oder Recognition ändert etwas an der Anzeige.

Dieser Fehler tritt erst nach dem Update auf Version v14.0.0 auf.

UJagusch

</div>

### Version

14.0.0-RC8

### Logfile

```shell
n.a.
```

### Screenshots

![image](http://taxi-troisdorf.de/bilder/fehler3.jpg)

Größe ist immer 137k, erscheint mir etwas groß?

**Comment by caco3** [comment]
ich denke nicht, dass es etwas mit RC3 zu tun hat. ich musste die RCs so schnell hochzählen, da wir die build pipeline modifizieren mussten

**Comment by Slider0007** [comment]
@caco3: Ich denke auch nicht, dass dies speziell mit RC3 zusammenhängt, sondern mit der generellen Umstellung der Aufbereitung, die seit v14 offiziell mit enthalten ist. Es ist aber interessant, dass die Datei in diesem Fall so groß ist. Mehr als ca. 100kB habe ich in meinem Setup (auch mit sehr vielen ROIs und diversen verschiedenen Bildinhalten) nicht hinbekommen. Das Rohbild hat bei mir zwischen 25-60kB und es kommen ca. 20-40kB für ROIs dazu. Wie groß ist die Datei bei dir in deinem Setup?

**Comment by ujagusch** [comment]
@caco3 @jomjol 

Sorry, aber der update auf **AI-on-the-edge-device__update__Increase-max-JPG-size_(d40d5ba)** hat keinerlei Änderung ergeben, das Display sieht immer noch so aus wie oben angezeigt.

Ausserdem steht der Initalization Screen für "immer" auf dem Schirm. Erst wenn man aktiv Overview oder Recognition drückt kommt die Ansicht die aufgenommen wurde (allerdings so wie oben angegeben).
Dieser Effekt tritt auch erst seit V. 14.x auf, mit der 13 war noch alles ok, da startet sofort der Overview Screen.

UJagusch

**Comment by ujagusch** [comment]
@caco3 @Slider0007

Kleines Update:

Version **update_13.08** installiert - Alle Anzeigen, Displays und Berechnungen sind normal und werden auch ohne Fehler angezeigt

Version **AI-on-the-edge-device__update__Increase-max-JPG-size** installiert. Nach Installation und Reboot wird das aufgenommene Bild angezeigt. Das sagen wir mal RAW Bild.

![image](https://user-images.githubusercontent.com/61631767/216284140-ab19ebbe-4835-4d9e-8a37-5578d03cc7ca.png)

Aktualisiert man über Overview oder Recognition kommt wieder das "zerhackte" Bild, so wie es oben angezeigt ist.
 
Ujagusch

**Comment by Slider0007** [comment]
@ujagusch: danke fürs Update. Das es bei 13.0.8 funktioniert ist klar. Dort war das Handling noch anders, aber leider sehr speicherineffizient. Deshalb wurde bei v14 ein neues Procedere eingeführt.

Wie groß ist die Datei im Schritt "Aligning - aslo RAW BIld" und im Schritt "Digitalization ROIs"? Einfach in den jeweiligen Schritten bei offnen Entwicklertools die Seite refreshen.

Die Grenze habe ich testweise auf 160kB hochgestellt.

**Comment by Zw3rg85** [comment]
Bei mir ist das einstellungs Bild gerade. Die Felder auch aber bei der Erfassung verdreht es immer. Kann es nicht einstellen 
![Uploading BD9B9B73-0B52-404A-B7F9-21CB0F67CBE3.jpeg…]()

**Comment by Zw3rg85** [comment]
![346C92F2-2167-4827-B510-0E56F8010941](https://user-images.githubusercontent.com/95000632/216323407-6cd5941c-f1c1-4b93-8f87-5567f6c633fb.jpeg)
![77E729F5-B79D-417F-AE18-96E946851D21](https://user-images.githubusercontent.com/95000632/216323418-4b99f936-915b-4707-aa0b-77690447c06a.jpeg)
![7769A68D-45BA-417F-A0CB-7F650209A8BD](https://user-images.githubusercontent.com/95000632/216323425-ac15c564-a060-481c-a3ea-e7dafbe1eec1.jpeg)

**Comment by Zw3rg85** [comment]
![Uploading 0ADCA23F-0A23-44F0-9BAD-DB5467AEC9BD.jpeg…]()

**Comment by Zw3rg85** [comment]
Reference
![Uploading FA9660BE-BE25-4178-B4BA-A8BF64A10325.jpeg…]()

**Comment by ujagusch** [comment]
@Slider0007 

![image](https://user-images.githubusercontent.com/61631767/216325537-d3f2057e-e055-4659-836b-ac5ac7ac3979.png)


Die Bildgröße ist immer 43,8 kB bei Alignment - wenn man dann umschaltet auf Overview (bei offener F12 Konsole) kann man sehen daß das Bild anscheinen mehrer Male aufgerufen wird. Die Bildgröße zählt in Stufen bis 134 kB hoch, diese einzelnen Stufen sieht man auch am Bildschirm, sieht so aus als ob sich die Bilder überlagern.

**Comment by Slider0007** [comment]
@Zw3rg85: Bitte die Fragen und Screenshots in einer separater Diskussion einstellen. Dein Problem passt leider nicht zum Thema.
--> Ich denke, du musst deine Alignment Marker optimieren (besser angepasst an ein statisches Merkmal, keine Überlagerung mit den ROIs)

@ujagusch: Es sieht so aus, als ob das dann zwei Probleme zu sein scheinen. Einerseits die Größe des Bildes. Durch die Erhöhung des Puffers auf 160kB müssten zumindest die Artefakte am unteren Bildrand weg sein, da dein File < 160 kB groß ist. Kannst du das bestätigen?
![image](https://user-images.githubusercontent.com/115730895/216326886-c6111fe1-6b02-4b0c-b403-6f7b28a34254.png)

Warum dein Bild generell so groß ist, ist mir auch noch schleierhaft. Bei 46kB Rohbild sollten keine 90kB ROI Infos dazu kommen...

Das andere kann ich mir nicht erklären. Hast du schon mal probiert, mit einem anderen Gerät / Browser drauf zuzugreifen, die Browsercaches zu löschen bzw. das Caching testweise in den Entwicklereinstellungen zu deaktivieren: 
![image](https://user-images.githubusercontent.com/115730895/216327530-15ddf313-ca4b-4e83-9603-7108e785fecb.png)


> Die Bildgröße ist immer 43,8 kB bei Alignment - wenn man dann umschaltet auf Overview (bei offener F12 Konsole) kann man sehen daß das Bild anscheinen mehrer Male aufgerufen wird.

Gemäß diesem Bild wird das Bild nur einmal abgerufen. Sollten es mehrere Aufrufe sein, müsste jeder Aufruf eine Zeile generieren:
![image](https://user-images.githubusercontent.com/115730895/216328715-970d44ea-b0d6-45de-a30d-265820b5eee1.png)

**Comment by ujagusch** [comment]
@Slider0007 
Ok - die Artefakte am unteren Bildrand sind weg.
Egal welchen Browser, immer dasselbe Display.

Wo kommt eigentlich die /img_tmp/alg_roi.jpg her ? Im img_tmp verzeichnis finde ich die nicht.

**Comment by Slider0007** [comment]
> Ok - die Artefakte am unteren Bildrand sind weg.

Gut, immerhin das ergibt Sinn.


> Egal welchen Browser, immer dasselbe Display.

Das ist natürlich nicht gut. Warum lädt das bei dir eigentlich so langsam. 9s für das Laden des Bildes sind ungewöhnlich. Ist deine WLAN Verbindung so schlecht? Mit der neuen Version müsste es erheblich schneller laden als mit v13...
![image](https://user-images.githubusercontent.com/115730895/216333692-4f5fb3ed-5e31-4ebf-be9e-5bafd62f7afa.png)

Bei mir dauert das Laden des Bildes ca. 400-500ms bei halber Bildgröße im Vergleich zu deiner:
![image](https://user-images.githubusercontent.com/115730895/216333623-321cb198-a68d-43ec-a32c-660a0c40db91.png)




> Wo kommt eigentlich die /img_tmp/alg_roi.jpg her ? Im img_tmp verzeichnis finde ich die nicht.

Das Bild wird direkt aus dem RAM geladen, um nicht unnötig Schreibzugriffe auf die SD zu generieren.

**Comment by ujagusch** [comment]
@Slider0007 

im Augenblick schwanken meine Ladezeiten für das Bild zwischen 900mS und 1.2 Sek. Das WLAN hier im Haus ist bescheiden, bzw. das WLAN ist gut, nur die Decke zum Keller ist ziemlich Massiv.

Ich vermute das es an der in V14 "neuen" Bildbehandlung liegt. Ich kann zwar auch mit der V13 leben, aber dass kann ja nicht Sinn der Sache sein. Irgendwo ist da der Wurm drin. 
BTW - bin ich der einzige der damit Probleme hat?

**Comment by Slider0007** [comment]
> BTW - bin ich der einzige der damit Probleme hat?

Du bist tatsächlich aktuell der Einzige mit diesem Problem. Irgendwo schient das Problem zu liegen, aber aktuell denke ich eher, dass es was spezifisches bei dir sein müsste. Bei mir läuft die Konfig bereits seit ca. 2-3 Wochen stabil auf mehreren Systemen.

Hast du mal mit einem neuen  Setup versucht? Du kannst zur Kontrolle deine config.ini posten.

**Comment by ujagusch** [comment]
Hier mal meine Config.ini. Vlt. findest du ja was bevor ich mein System neu aufsetze:

[MakeImage]
;LogImageLocation = /log/source
WaitBeforeTakingPicture = 5
;LogfileRetentionInDays = 15
Brightness = 0
Contrast = 0
Saturation = 0
LEDIntensity = 15
ImageQuality = 12
ImageSize = VGA
FixedExposure = false

[Alignment]
InitialRotate = 265
InitialMirror = false
SearchFieldX = 20
SearchFieldY = 20
AlignmentAlgo = fast
FlipImageSize = true
/config/ref0.jpg 13 327
/config/ref1.jpg 295 186

[Digits]
Model = /config/dig-cont_0600_s3.tflite
CNNGoodThreshold = 0.5
;LogImageLocation = /log/digit
;LogfileRetentionInDays = 3
main.dig1 107 184 32 55 false
main.dig2 152 187 32 55 false
main.dig3 196 190 32 55 false
main.dig4 241 193 32 55 0

[Analog]
Model = /config/ana-cont_11.3.0_s2.tflite
;LogImageLocation = /log/analog
;LogfileRetentionInDays = 3
main.ana1 331 277 109 109 false
main.ana2 279 396 109 109 false
main.ana3 157 445 109 109 false

[PostProcessing]
main.DecimalShift = 0
main.AnalogDigitalTransitionStart = 0.2
PreValueUse = true
PreValueAgeStartup = 720
AllowNegativeRates = false
main.MaxRateValue = 0.05
main.MaxRateType = AbsoluteChange
;main.ExtendedResolution = false
;main.IgnoreLeadingNaN = true
ErrorMessage = true
CheckDigitIncreaseConsistency = true

[MQTT]
Uri = mqtt://192.168.2.190:1883
MainTopic = wasserzaehler
ClientID = wasser
;user = USERNAME
;password = PASSWORD
SetRetainFlag = true
HomeassistantDiscovery = false
MeterType = water_m3

;[InfluxDB]
;Uri = undefined
;Database = 
;Measurement = undefined
;user = undefined
;password = undefined

;[GPIO]
;IO0 = input disabled 10 false false 
;IO1 = input disabled 10 false false 
;IO3 = input disabled 10 false false 
;IO4 = built-in-led disabled 10 false false 
;IO12 = input-pullup disabled 10 false false 
;IO13 = input-pullup disabled 10 false false 
LEDType = WS2812
LEDNumbers = 2
LEDColor = 150 150 150

[AutoTimer]
AutoStart = true
Intervall = 3

[DataLogging]
DataLogActive = true
DataLogRetentionInDays = 3

[Debug]
Logfile = 1
LogfileRetentionInDays = 3

[System]
TimeZone = CET-1CEST,M3.5.0,M10.5.0/3
;TimeServer = pool.ntp.org
;AutoAdjustSummertime = false
;Hostname = undefined
SetupMode = false


UJagusch

**Comment by Slider0007** [comment]
@ujagusch: Wir sind einen Schritt weiter. Es liegt definitv an deiner Config. Nach dem Laden deiner Config in mein Testsystem habe ich das gleiche Problem. Es liegt vermutlich am Parameter "FlipImageSize", dieser steht bei dir auf "true". Stelle diesen bitte testweise auf "false". Dieser ist aber nur durch direktes Bearbeiten der config.ini geändert werden:

![image](https://user-images.githubusercontent.com/115730895/216357455-766f2176-ed08-4b93-bec7-90143fe14209.png)
![image](https://user-images.githubusercontent.com/115730895/216358479-2e4058bd-e6a3-4a0e-a5c3-771eef2d0dbe.png)

**Comment by caco3** [comment]
> @caco3: Wie groß ist die Datei bei dir in deinem Setup?

bei mir kommt es auf 75 kbytes

**Comment by caco3** [comment]
nimmt mich wunder, wieso 'FlipImageSize' bei dir au true steht und für was man das brauchen würde.

**Comment by ujagusch** [comment]
> nimmt mich wunder, wieso 'FlipImageSize' bei dir au true steht und für was man das brauchen würde.

Ich hab keine Ahnung, noch dazu wo es eine Zeitlang lief, und mit dem ersten Wechsel auf 14.x ging dann nix mehr.
Jetzt läuft z.Zt. die Development-Branch: Increase-max-JPG-size (Commit: d40d5ba+) mit FlipImageSize auf false (ohne das ich das geändert habe, das war beim setup schon so).

Die Größe vom alg_roi.jpg liegt jetzt bei 67.3 kB

Die Sache mal weiter im Auge behalten.

Da ist zwar noch ein Problem mit der Anzeige vom ANA3 Bild in Recognition, aber solange es korrekt ausgewertet wird ist mir das im Moment egal.

Jetzt warte ich erstmal auf den nächsten Rollover - mal sehn was da passiert.

UJagusch

**Comment by Slider0007** [comment]
@caco3, @jomjol: Ich habe den Fix für das FlipImageSize Problem nun vorbereitet. Das stellt den Stand v13 wieder her. Der Bug ist durch die Umstellung auf die JPG-Speicherung entstanden.
Längerfristig könnte aber überlegt werden, ob dieser Parameter nicht komplett entfernt werden könnte. Dieser reduziert nur das Bildfeld auf effektiv nutzbare 480x480, da die Kamera fest auf 640x480 eingestellt ist. Eine wirkliche Drehung des Bildes kann auch mit 90° Rotationswinkel erreicht werden.

@jomjol: Gab/Gibt es dafür einen speziellen Use Case für diese Funktion?

Flip Image Size = true
![image](https://user-images.githubusercontent.com/115730895/216440704-01e5d0cb-5d34-4337-9b38-7ac81147cad8.png)




Zweites Thema: Ich würde von der Erhöhung der MAX JPG SIZE von 128k auf 160kB erst mal absehen, da die zu große Datei mit ziemlicher Sicherheit durch die fehlerhafte Darstellung entstanden ist. Ansonsten "verschwenden" wir unnötigerweise RAM. Einen Buffer-Overflow-Schutz inkl. Fehlermeldung würde ich aber trotzdem implementieren, damit zumindest keine anderen Auswirkungen entstehen können, sofern doch mal größere Files auftauchen sollten. Was meint ihr?

**Comment by tomwellnitz** [comment]
Habe das gleich Problem wie @ujagusch nach dem Update von 13.0.8 auf 14.0.0

<img width="983" alt="image" src="https://user-images.githubusercontent.com/81973502/216439227-d4c9eee3-c053-4ff7-91d1-fd69908575f3.png">

[MakeImage]
;LogImageLocation = /log/source
WaitBeforeTakingPicture = 5
;LogfileRetentionInDays = 15
Brightness = -2
Contrast = 0
Saturation = -1
LEDIntensity = 2
ImageQuality = 12
ImageSize = VGA
FixedExposure = false

[Alignment]
InitialRotate = 0
InitialMirror = false
SearchFieldX = 20
SearchFieldY = 20
AlignmentAlgo = default
FlipImageSize = true
/config/ref0.jpg 366 245
/config/ref1.jpg 187 163

[Digits]
Model = /config/dig-cont_0600_s3.tflite
CNNGoodThreshold = 0.5
;LogImageLocation = /log/digit
;LogfileRetentionInDays = 3
main.dig1 132 236 25 45 false
main.dig2 164 236 25 45 false
main.dig3 196 238 25 45 false
main.dig4 228 238 25 45 0
main.dig5 260 238 25 45 0
main.dig6 288 239 25 45 0
main.dig7 315 239 25 45 0
main.dig8 338 240 25 45 0

[Analog]
Model = /config/ana-class100_0154_s1_q.tflite
;LogImageLocation = /log/analog
;LogfileRetentionInDays = 3
main.ana1 280 341 92 92 false

[PostProcessing]
main.DecimalShift = -3
main.AnalogDigitalTransitionStart = 9.2
PreValueUse = true
PreValueAgeStartup = 300
AllowNegativeRates = false
main.MaxRateValue = 0.5
;main.MaxRateType = AbsoluteChange
main.ExtendedResolution = true
;main.IgnoreLeadingNaN = true
ErrorMessage = true
CheckDigitIncreaseConsistency = true

[MQTT]
Uri = 
MainTopic = 
ClientID = 
user = 
password = 
SetRetainFlag = true
HomeassistantDiscovery = true
MeterType = water_m3

;[InfluxDB]
;Uri = undefined
;Database = 
;Measurement = undefined
;user = undefined
;password = undefined

;[GPIO]
;IO0 = input disabled 10 false false 
;IO1 = input disabled 10 false false 
;IO3 = input disabled 10 false false 
;IO4 = built-in-led disabled 10 false false 
;IO12 = input-pullup disabled 10 false false 
;IO13 = input-pullup disabled 10 false false 
LEDType = WS2812
LEDNumbers = 2
LEDColor = 150 150 150

[AutoTimer]
AutoStart = true
Intervall = 10

[DataLogging]
DataLogActive = true
DataLogRetentionInDays = 3

[Debug]
Logfile = 1
LogfileRetentionInDays = 3

[System]
TimeZone = CET-1CEST,M3.5.0,M10.5.0/3
;TimeServer = pool.ntp.org
;AutoAdjustSummertime = false
;Hostname = undefined
SetupMode = false

Ich habe dann mal FlipImageSize = false gesetzt und bekomme dann das folgende Bild

![Ohne Titel](https://user-images.githubusercontent.com/81973502/216441213-20c7ef8c-1922-49d4-b617-f78be0aff987.jpg)

Gruß
Tom

**Comment by Slider0007** [comment]
@tomwellnitz: Du musst die ROIs neu setzen, da sich durch die Deaktivierung des Parameters die Referenz zum Basisbild verändert hat. Alternativ müsstest du warten, bis der Fix im nächsten Release ist. Ich würde dir aber empfehlen, den Parameter nicht zu verwenden und lieber neu auszurichten. Damit wärst du für die Zukunft besser aufgestellt.

**Comment by jomjol** [comment]
Ich versuche den Parameter mal an folgendem Beispiel zu erklären:

![grafik](https://user-images.githubusercontent.com/30766535/216703735-18faa8d3-655c-4e6b-9ea7-be0aebba3a0a.png)

Zugegeben hier ein bisschen konstruiert. Aber Idee ist simple: bei manchen Aufnahmesituation ist die Bildinformation nicht im Kernbereich (480x480), sondern auch im äußeren Bildbereich (hier: "00021") **und** gleichzeitig das Bild um 90° gedreht.

Bei `FlipImageSize=true` wird das Bildformat mitgedreht und damit der Bereich nicht weggeschnitten. Kommt nicht oft vor, aber es gabe in ältereren Posts ein paar Anwendungen, die das brauchten (insbesondere wenn die Platzverhältnise beengt sind).

**Comment by Slider0007** [comment]
@jomjol: Vielen Dank für die ausführliche Erklärung. Damit macht das Ganze schon mehr Sinn und hat auch seine Daseinsberechtigung.
Umso wichtiger wäre es ja, diese Funktion in V14 auch wieder vollumfänglich herzustellen. Aktuell im V14 Release gibt es bei Verwendung dieses Parameters das nicht anschauliche Bild, wie oben zu sehen. Dies ist aber nur ein Darstellungsfehler, was ich bei der Implementierung der JPG Variante übersehen hatte. Dies wollte ich mit dem PR #1966 beheben. Der PR ist nicht dafür gedacht, den Parameter zu entfernen. Ergänzend ist im PR noch eine Pufferüberlaufsicherung mit drin, die verhindert, dass bei Überschreiten der MAX JPG SIZE des preallokierten Puffers andere Daten im Speicher ausversehen überschrieben werden.

**Comment by SvondenBerg** [comment]
Nur für's Protokoll: Ich habe genau aus den von Jomjol dargelegten Gründen flipimagesize aktiviert. Die Installation ist ganz frisch, die Übersicht ist bei mir ähnlich zerhackt, wobei die Daten selbst korrekt ausgelesen werden. :) Nur zur Dokumentation, dass es nicht nur 1-2 Personen betrifft. :D

**Comment by jomjol** [comment]
Bitte probiert mal die neueste Rolling. Damit sollte das Problem behoben sein: https://github.com/jomjol/AI-on-the-edge-device/actions/runs/4093354613

**Comment by SvondenBerg** [comment]
In der Tat, in der Übersicht wird mit dem update nun wieder ein sinnvolles Bild angezeigt. 👍

**Comment by jomjol** [comment]
Dann bringen wir das als Fix in eine neue subversion.

**Comment by Slider0007** [comment]
This issue was fixed with commit 34a3d6d6e3d62bb36aa57adc367447b04322194d (commit equal to PR #1966) and is included in release v14.0.1 and higher.
