### ISSUE TITLE
Wifi Connection not working (well) on TP-Link Omada AP

### ISSUE THREAD

**Issue by uwen70** [jomjol/AI-on-the-edge-device#1969]
### The Problem

Bei Nutzung von AI-on-the-edge-device Firmware an TP-Link APs (EAP 225 v3, EAP 225-Wall) ist die WLAN Verbindung so schlecht, dass ein Setup nach der Installation über das Webinterface nicht gelingt. 

Ping zeigt einen Paketverlust von bis zu 30% und Paketlaufzeiten von bis 3600 ms. Keine Probleme gibt es bei Nutzung einer FritzBox 6666 als AP im selben Funkkanal. 
Ein ESPHome (https://web.esphome.io/) hat keine Verbindungsprobleme an TP-Link APs.
Bei zeitgleichen Test mit zwei ESP32-CAMs am selben AP ergibt sich für Ping:  
AI-on-the-edge-device: Minimum = 91ms, Maximum = 2954ms, Mittelwert = 558ms, 23% Verlust
ESPHome:  Minimum = 8ms, Maximum = 540ms, Mittelwert = 77ms, 0% Verlust

Gibt es Einstellungen, die für einen fehlerfreieb Betrieb ggf. am AP ein- oder abgeschaltet werden müssen?
 

### Version

v14.0.0, v14.0.0-RC8, v13.0.8

### Logfile

```shell
I (6200) MAIN: =================================================
I (6210) MAIN: ==================== Startup ====================
I (6210) MAIN: =================================================
I (6220) MAIN: Release: v14.0.0 (Commit: fa69272+), Date/Time: 2023-02-02 18:31, Web UI: Release: v14.0.0 (Commit: fa69272+)
I (6230) MAIN: Reset reason: Via esp_restart
I (6250) OTA: Start CheckOTAUpdateCheck...
I (6260) OTA: SHA-256 for the partition table: : 9d4a2809ae90fb20709a8ca3dd3ac3462e1e73286bcd31b689060c91de06fa3a
I (6280) OTA: SHA-256 for bootloader: : 4a9573dafac5d5c79c43e5a356568332da3a99dd2e220da6ceeadc96d32708a2
I (6720) OTA: SHA-256 for current firmware: : 60b28956748fca167af62458147703c2db212720d6031959646a2b40598ea5be
I (6770) MAIN: WLAN-Settings - RSSI-Threashold: 0
I (6790) wifi:wifi driver task: 3ffd3e70, prio:23, stack:6144, core=0
I (6790) system_api: Base MAC address is not set
I (6790) system_api: read default base MAC address from EFUSE
I (6800) wifi:wifi firmware version: eeaa27d
I (6800) wifi:wifi certification version: v7.0
I (6800) wifi:config NVS flash: enabled
I (6800) wifi:config nano formating: enabled
I (6810) wifi:Init data frame dynamic rx buffer num: 16
I (6810) wifi:Init management frame dynamic rx buffer num: 16
I (6820) wifi:Init management short buffer num: 32
I (6820) wifi:Init static tx buffer num: 16
I (6830) wifi:Init tx cache buffer num: 16
I (6830) wifi:Init static rx buffer size: 1600
I (6840) wifi:Init static rx buffer num: 10
I (6840) wifi:Init dynamic rx buffer num: 16
I (6840) wifi_init: rx ba win: 6
I (6850) wifi_init: tcpip mbox: 32
I (6850) wifi_init: udp mbox: 6
I (6850) wifi_init: tcp mbox: 6
I (6850) wifi_init: tcp tx win: 5744
I (6860) wifi_init: tcp rx win: 5744
I (6860) wifi_init: tcp mss: 1440
I (6860) wifi_init: WiFi IRAM OP enabled
I (6870) wifi_init: WiFi RX IRAM OP enabled
I (6870) phy_init: phy_version 4670,719f9f6,Feb 18 2021,17:07:07
I (6970) wifi:mode : sta (c8:f0:9e:4d:55:8c)
I (6970) wifi:enable tsf
I (6980) BLINK: Flash - start
I (6980) WIFI: Set hostname to: watermeter
I (6980) WIFI: wifi_init_sta finished.
I (6990) wifi:new:<11,0>, old:<1,0>, ap:<255,255>, sta:<11,0>, prof:1
I (6990) wifi:state: init -> auth (b0)
I (7000) wifi:state: auth -> assoc (0)
I (7060) wifi:state: assoc -> run (10)
I (7180) BLINK: Flash - done
I (7250) wifi:connected with SSID, aid = 1, channel 11, BW20, bssid = aa:da:c4:1d:ae:6e
I (7250) wifi:security: WPA2-PSK, phy: bgn, rssi: -75
I (7260) wifi:pm start, type: 1

I (7280) wifi:AP's beacon interval = 102400 us, DTIM period = 1
W (7790) wifi:<ba-add>idx:0 (ifx:0, aa:da:c4:1d:ae:6e), tid:0, ssn:1, winSize:64
I (8780) esp_netif_handlers: sta ip: 192.168.8.76, mask: 255.255.255.0, gw: 192.168.8.251
I (8780) WIFI: got ip:192.168.8.76
I (8780) BLINK: Flash - start
I (8780) WIFI: Connected with AP: SSID, password: XXXXXXX

...
W (230430) httpd_txrx: httpd_sock_err: error in send : 11
E (230430) SERVER HELP: File sending failed!
W (231680) httpd_txrx: httpd_resp_send_err: 500 Internal Server Error - Failed to send file
W (242430) httpd_txrx: httpd_sock_err: error in send : 11
W (243870) httpd_uri: httpd_uri: uri handler execution failed
```

**Comment by caco3** [comment]
> selben Funkkanal
Welchen Kanal verwendest Du? Kanal 12 und höher scheint Probleme zu machen, siehe https://github.com/jomjol/AI-on-the-edge-device/discussions/1608#discussioncomment-4823059

Ansonsten verwenden wir halt die Beispielkonfiguration von Espressif. Wenn das nicht passt, wird es schwierig, den Fehler zu finden.

**Comment by uwen70** [comment]
Ich habe Kanal 1 und Kanal 11 ausprobiert. In beiden das gleiche Verhalten.

Das Problem ist aber größer: Wenn man ein Modul mit Webinstaller neu aufsetzt und keine vorbereitete SD Karte hat, startet der SoftAP zur Konfiguration. Ich habe vier verschiedene Laptops mit Win 10 versucht (MS Surface 4, MS Surface 7+, Lenovo W530, Lenovo P1Gen2) und alle können (nacheinander) verbinden, bekommen eine IP. Aber die Verbindung ist sehr schlecht mit 60% bis 97% Paketverlust bei Ping. Damit kann das Webinterface nicht ordentlich bedient werden. Der SoftAP ist auf Kanal 11.

Allen bisher getesteten Geräten ist gemeinsam, dass sie Wifi5 (ac) oder Wifi6 (ax) Hardware haben und unter Windows 10 22H2 laufen. Ich werde mal noch nach alter Hardware schauen.

Ich habe im Log gesehen, dass Wifi Firmware eeaa27d (wifi certification version: v7.0) von expressif läuft. Gibt es eine neure Version oder auch eine ältere Version der Firmware zum testen? 
Ein Hardwarefehler am ESP32-CAM ist auszuschließen, da es mit ESPHome (https://esphome.github.io/esp-web-tools/ Image: https://firmware.esphome.io/esphome-web-esp32/esphome-web-esp32.bin) beim Setup im SoftAP fehlerfrei läuft.

Gibt es Ideen, wie  weiter?

**Comment by caco3** [comment]
Wir verwenden fast die neuste Version, welche von PlatformIO bereitgestellt wird: https://github.com/platformio/platform-espressif32/releases/tag/v5.2.0
Wir hatten mal versucht, auf 5.3 oder 6 zu gehen, aber es ist leider einiges an Aufwand, siehe https://github.com/jomjol/AI-on-the-edge-device/issues/1728

Mit unserem Release 12.0.1 hatten wir noch 4.4.0 am laufen, siehe https://github.com/jomjol/AI-on-the-edge-device/blob/dfe2c466bcef6ae13fc1eda80eaa237c2f73248e/code/platformio.ini

Seit der Version 12.0.1 haben wir aber schon ganz vieles verbessert, daher muss die Version nicht zwingend stabiler sein!

**Comment by uwen70** [comment]
OK, ich habe die v14.0.0 im SoftAP gegen ein altes Intel Wifi n Modul mit Windows 10 probiert. Die schlechte Performance und Paketverluste bleiben.
Die v12.0.1 hat das Probem auch, aber nicht ganz so schlimm. Die Paketverlusste kommen runter auf ca. 3% bis 10% und die Pingzeiten beiben bei unter 1000ms.

**Comment by uwen70** [comment]
Ich habe auf meiner Suche gefunden, dass das Problem einen Zusammenhang mit der Camera hat (https://github.com/esphome/issues/issues/3030). Wenn ich das Modul ohne verbundene Kamera starte, habe ich keine Paketverluste mehr und die Ping Zeiten gehen auf unter 65 ms im Mittelwert. Webserver ist dann auch problemlos erreichbar. 

Ist die CPU bei 160MHz eventuell zu langsam, um alle Interupts rechtzeitig zu bedienen? Warum startet ihr die CPU nicht mit 240MHz? Kann die Frequenz in der config.ini eingestellt werden?

**Comment by caco3** [comment]
Ich habe bei mir das 5GHz Wifi deaktiviert, deshalb habe ich keinen Vergleich.

Grundsätzlich könnte man die Kammera schon abschalten, es scheint ja technisch möglich zu sein.
Ev. hat das @jomjol ja schon mal versucht gehabt.
Grundsätzlich steigert das halt wieder die Komplexität, und das System ist sonst schon recht fehleranfällig.

Infos:
- https://randomnerdtutorials.com/esp32-cam-ai-thinker-pinout/
- https://github.com/espressif/esp32-camera/issues/247

**Comment by jomjol** [comment]
Bisher keine Tests meinerseits. Dass die Kamera durch Interferenzen das WLAN Problem auslöst ist für mich auch neu (zumal ich mit meinen Modulen bisher keine Probleme diesbezüglich hatte).

**Comment by caco3** [comment]
https://github.com/jomjol/AI-on-the-edge-device/issues/2092

**Comment by caco3** [comment]
can you try the latest rolling, there are quite some improvements!
