### ISSUE TITLE
password protected administration

### ISSUE THREAD

**Issue by oeschlberger** [jomjol/AI-on-the-edge-device#1976]
### The Feature

hello,

I would like to suggest to add a passwort to enter the administration page. This would be stored in a file such as the wifi config. Also new rest endpoints to trigger actions on the device could be verified via api key in request header. 

thank you for this great project!

**Comment by jomjol** [comment]
This has been often discussed. we decided not to add any additional security features as it would be very easy to overcome them (which is also true for the wlan.ini)
