### ISSUE TITLE
Version 6.7.0 bei mir mit deutlich verschlechterter Erkennung

### ISSUE THREAD

**Issue by linwinDE** [jomjol/AI-on-the-edge-device#198]
Hallo Jomjol,
nochmals herzlichen Dank für dein tolles Projekt und die super Doku !

Ich habe 6.7.0 bei mir wieder runtergeworfen und bin zur 6.6.0 zurück.
Jetzt habe ich wieder eine Erkennung von "100%".
Die 6.7.0 ist bei mir deutlich schlechter.

**Comment by jomjol** [comment]
Hast du nur die Firmware ausgetauscht, nur das tflite-File oder beides?

Gruß,
  jomjol

**Comment by linwinDE** [comment]
Ich habe analog zum OTA-update firmware.bin hochgeladen und geflasht und dann html.zip hochgeladen und entpackt.
Dann neu gebootet.
Das bitte nicht als Gejammer auffassen, die 6.6.0 funktioniert perfekt für mich !

**Comment by jomjol** [comment]
Habe ich nicht als Gejammer verstanden, sondern bin auf Ursachensuche.
Aber konkret: die Config.ini hast du nicht angefasst?

Hintergrund: Probleme mit der Erkennung können vom Programmablauf (Firmware.bin) oder aber von der Ziffernerkennung (tflite) kommen. Und ich habe auch bemerkt, dass es gerade nicht ganz so stabil läuft und weiss nicht warum.

**Comment by linwinDE** [comment]
Ich habe nur firmware.bin und html.zip angefasst.
Ich kann gerne testweise wieder auf 6.7 updaten.
Gib mir ein paar Hausaufgaben und ich arbeite sie ab. Das Wetter übers Wochenende schreit nach PC-Arbeit ;-)

**Comment by jomjol** [comment]
Okay - das sind eher "schlechte" Neuigkeiten. Sie bedeuten nämlich, dass der Algo nicht stabil läuft. Hatte ich fast befürchtet. Ich schalte bei mir jetzt mal das erweiterte Debuging ein. Sobald ich eine neue Version zum Testen habe, komme ich gerne auf dein Angebot zurück!

**Comment by jomjol** [comment]
Habe mir gerade meine Log-Files angeschaut:
![grafik](https://user-images.githubusercontent.com/30766535/116652900-6a5b1d00-a986-11eb-9551-d4d4a298ab66.png)

Kommt bei so ca. bei 10-20% der Bilder vor. Das erklärt einiges - wenn dort noch Alignmentmarken liegen, dann geht schon das schief, ansonsten kommen natürlich sinnlose zahlen.
Da muss ich wohl am Wochenende den Code mit der vorherigen Version vergleichen. Ich habe schon so eine Ahnung bei der Kameraansteuerung. Melde mich!

**Comment by linwinDE** [comment]
lt. Version System->Info habe "master - v6.6.1 - 2020-04-05" und "HTML Version6.4.1" perfekt (!!) am laufen ;-)

**Comment by stromzaehler** [comment]
Hallo, ich habe (bzw. hatte) genau die gleichen Probleme bei gleicher Wasseruhr wie linwinDE. Bin auch zur 6.1.1 zurück, die perfekt läuft.

Danke und Grüße

**Comment by jomjol** [comment]
Kann die Fehler bei mir reproduzieren und bin schon dran :-)

**Comment by jomjol** [comment]
Ich habe eine "neue" Version in der Rolling (wird später 6.7.1) hochgeladen. Ist bei mir heute Nacht gut durchgelaufen.
Sie hat dieselben Verbesserungen wir 6.7.0, aber den Kern von 6.6.1, d.h. das Kamerahandling ist wieder das Alte.

@stromzaehler, @linwinDE: könnt ihr die bitte auch mal testen?

**Comment by linwinDE** [comment]
Danke für die Testversion, habe ich jetzt drauf und beobachte. Melde mich dann morgen.

**Comment by jomjol** [comment]
Läuft bei mir viel stabiler! Wenn ich nichts anderes von euch höre, werde ich das heute Abend zur Master machen.

**Comment by stromzaehler** [comment]
Läuft stabil, bringt aber immer einen um 1 oder 2 zu hohen Wert beim ersten analogen ROI. Das hatte ich bei der 6.7.0 auch schon. Habe außer der Firmware nichts geändert. Muss jetzt allerdings "in den 1. Mai". Mal sehen, ob ich das heute Abend dann noch im Griff habe ;-)

**Comment by linwinDE** [comment]
Sieht sehr gut asu.

**Comment by jomjol** [comment]
Änderungen in v6.7.1 eingepflegt
