### ISSUE TITLE
How to add library

### ISSUE THREAD

**Issue by Dollar0712** [jomjol/AI-on-the-edge-device#1980]
### Issue

Same as this issue, #311.

I want to add the ESP_FlexyStepper lib library to develop some functions related to the stepper motor, but it keeps showing can not find ESP_FlexyStepper.h.

Please give me some help.

Thanks

**Comment by jomjol** [comment]
Hi, 
I strongly recommend, not to extend this firmware by additional complex libraries. 
There are almost no free GPIOs (for a stepper you might need up to three: step, direction, limit. They are simply not available without soldering.
But your problems sound more principal. The ESP_FlexyStepper is an Arduino library. Here we are programm within espressif. Maybe it works somehow, but I cannot give you any advice.
