### ISSUE TITLE
SD card size displayed incorrectly in startup log

### ISSUE THREAD

**Issue by uwen70** [jomjol/AI-on-the-edge-device#1985]
### The Problem

The size of the SD card is displayed incorrectly in the startup log. The bug has crept in since version 12.0.1.

### Version

v14.0.0

### Logfile

```shell
I (5921) MAIN: Using SDMMC peripheral
Name: ASTC
Type: SDHC/SDXC
Speed: 20 MHz
Size: luMB
```

### Expected Behavior

Logfile from v12.0.1

```
I (6192) main: Using SDMMC peripheral
Name: ASTC
Type: SDHC/SDXC
Speed: 20 MHz
Size: 29818MB
```

**Comment by caco3** [comment]
Thanks for reporting this.

As far as I can see, this is a bug in `sdmmc_card_print_info()` in the Espressif Framework.
We can not fix this ourself.

Maybe the next framework has it fixed.
