### ISSUE TITLE
Image misaligned after config

### ISSUE THREAD

**Issue by marcelrv** [jomjol/AI-on-the-edge-device#199]
[using latest version 6.7.0] I'm stuggling to get the alignment right
During the config phase all is perfect aligned, but once running it is misaligned.
Any suggestion?

![image](https://user-images.githubusercontent.com/5871213/116621216-2135a980-a943-11eb-995d-85d2fdb1a8ad.png)

here the ref image and ROIs.. it seems aligned here
![image](https://user-images.githubusercontent.com/5871213/116621498-85586d80-a943-11eb-847c-5f8e24f6ad61.png)
![image](https://user-images.githubusercontent.com/5871213/116621620-c2bcfb00-a943-11eb-9b8e-3f6a583bce90.png)

**Comment by jomjol** [comment]
It looks like
1) Contrast is a bit weak
2) Reference structure might be a bit too fine structures.

With the 2) I have no experience, but the algo is rather simple, so if you have a fine structured reference and a rotation, it might fail. I would suggest to use more simple part like the "m³", but this currently has a low contrast. 
You could help yourself with sticking a black piece of something to the surface.

**Comment by marcelrv** [comment]
yes, that did the trick. Thanks
