### ISSUE TITLE
Option to set Previous Value via MQTT

### ISSUE THREAD

**Issue by olli0815** [jomjol/AI-on-the-edge-device#1994]
### The Feature

Hi,

I would love to get the option to change the previous value also via MQTT.
From time to time I need to just previous value - Via MQTT or API I would be able to automate that, applying some rules.

Thanks for the great stuff,
Ole

**Comment by Slider0007** [comment]
It's already possible via REST API 'http://IP/setPreValue?value=1234&numbers=main' where 1234 is the new value and main the name of the number to be adjusted.

Please have a look to the documentation.

**Comment by olli0815** [comment]
Thanks
