### ISSUE TITLE
Installation difficulty: Console saying Connection to the AP failed

### ISSUE THREAD

**Issue by matcies** [jomjol/AI-on-the-edge-device#1996]
### Issue

Hi. Might be due to a mistake in the installation process from my side. 

Ive flashed the ESP32 CAM unit with the web installer putting the board into Flash mode (Pushing Reset while GPIO0 was pushed).
Installation worked according to the page. 

Then opening the console, some commands are visible that appear to show that the device is booting properly. 

Then after a few seconds its trying to connect to Wifi. And then giving the error message. WIFI: Connection to the AP failed. 
This is repeating.
No wifi network "AI on the edge" visible. 
 
Any ideas what I could try or did wrong? Thank you in advance for any ideas.

**Comment by friedpa** [comment]
Did you put your Wifi SSID and the password in the file Wlan.ini?

**Comment by matcies** [comment]
Hi friedpa. Thanks for your fast help. 

Yes that was the problem. Didnt see that step in the installation wiki. Might be self explaining to advanced guys. But wasnt clear to me. 

Thank you.
