### ISSUE TITLE
Warnmeldungen nach JS-Controller Update

### ISSUE THREAD

**Issue by MMeinhardt1** [jomjol/AI-on-the-edge-device#200]
Hi,
bekomme im Log folgende Warnmeldungen,

Adaptername | Zeit | Status | Meldung
-- | -- | -- | --
mqtt.0 | 2021-05-01 13:09:53.017 | warn | State value to set for "mqtt.0.Gaszaehler_neu.Stand" has wrong type "number" but has to be "string"
mqtt.0 | 2021-05-01 13:08:38.498 | warn | State value to set for "mqtt.0.Wasserzaehler.Stand" has wrong type "number" but has to be "string"

**Comment by jomjol** [comment]
Verursacht das ein Problem? Wenn nein, würde ich erstmal am Code nichts ändern.

**Comment by MMeinhardt1** [comment]
Ein Problem nicht wirklich, nur eben eine Warnmeldung im Log. Wenn Du mal ne ruhige Minute hast wäre es schön wenn Du da mal nachschauen könntest, eilt aber nicht. 

Danke und nen schönen restlichen 1. Mai

**Comment by jomjol** [comment]
Habe mir das jetzt mal angeschaut. Der MQTT-Client versendet dort eigentlich einen String:
```
void MQTTPublish(std::string _key, std::string _content){
    if (client && mqtt_connected) {
        int msg_id;
        std::string zw;
        msg_id = esp_mqtt_client_publish(client, _key.c_str(), _content.c_str(), 0, 1, 0);
...
```
Weiss momentan nicht, was ich dort clientseitig ändern könnte. Schließe erstmal den Issue.

Bitte wieder öffnen, falls handlungsbedarf.
