### ISSUE TITLE
Image upside down

### ISSUE THREAD

**Issue by A380Coding** [jomjol/AI-on-the-edge-device#2011]
### The Problem

Using Prerotate angle of 180° after image is taken, it is shown upside down and and is also send upside down via REST API.
After alignment it is right.

Call:
img_tmp/alg_roi.jpg

### Version

14.0.3

### Logfile

```shell
-
```

### Expected Behavior

Image always in the right orientation

**Comment by caco3** [comment]
> After alignment it is right.

The rotation is AFAIK part of the alignment step, so thats bot a bug.

**Comment by A380Coding** [comment]
I've not seen it in 13.0.8 that's why I thought it is.

**Comment by caco3** [comment]
The timing got improved, that's why you might not seen it in older versions.
