### ISSUE TITLE
Aufnahmen der Digits und Analogzeiger rauschen

### ISSUE THREAD

**Issue by raebbaer** [jomjol/AI-on-the-edge-device#2019]
### The Problem

Ich habe gerade einen zweiten ESP32 mit CAM eingerichtet. Direkt mit der 14.0.3. Ich kann das Referenzbild aufnehmen, Marken setzen und die Digital- und Analogbereiche definieren. Er startet neu, sendet auch die MQTT Pakete, aber ohne erkannten Wert, weil die Rohdaten wie im Screenshot gezeigt aussehen. Woher kann das kommen?

### Version

14.0.3

### Logfile

```shell
Kein Eintrag.
```

### Screenshots

![Wasser](https://user-images.githubusercontent.com/123904506/218323691-4aaa2398-dd73-434f-9108-6153beaa0151.jpg)

**Comment by caco3** [comment]
Aktiviere mal den Debug level für das Log, siehe unten

**Comment by SvondenBerg** [comment]
Ich meine, diese Bilder ebenfalls gesehen zu haben, als die Drehung nicht korrekt war. Das schien das Ergebnis zu sein, wenn unter den ausgerichteten Feldern keine Zahlen / Zähler lagen und der Algorithmus daraus versucht hat, etwas heraus zu deuten. Mag auch daran liegen, dass das Bild ganz frisch aufgenommen war und noch post-prozessiert werden musste (alignment, tensor-flow, etc.).

**Comment by haverland** [comment]
Bisher habe ich das nur gesehen, wenn irgendein ROI oder Referenzmarke außerhalb des Bildes ist. Das wird nicht korrekt abgefangen und man landet irgendwo im Speicher.
Zeig mal deine ROI / Referenzmarken-Config

**Comment by raebbaer** [comment]
Das Logfile gibt im Debug-Modus leider nichts her. Und leider war beim Zurückstellen auf das Log-Level Error die Hardware defekt. Ich habe das Modul nicht mehr zum Laufen bekommen. Auch nicht nach einer vollständigen Neuinstallation. Eine neue SD-Karte hat leider auch keinen Erfolg gebracht. Jetzt weiß ich leider nicht, ob die Macke des Moduls für die seltsamen Digits verantwortlich war oder z.B. die nicht korrekte Drehung. Ich habe mir eine neue Hardware bestellt und versuche das zu reproduzieren. Ich melde mich, wenn der Fehler wieder auftritt. Bis dahin macht es wahrscheinlich Sinn, den Bug zu schließen.

**Comment by caco3** [comment]
@raebbaer Was sind den die Symptome deiner Hardware?

**Comment by raebbaer** [comment]
@caco3: Das ist eine ziemlich komische Sache. Ich beschreibe einfach mal...

Gestartet habe ich mit meinem Gaszähler. ESP32 aufgesetzt mit der 14.0.0, WLAN über Fritz Mesh hat nicht richtig funktioniert, WLAN umgebaut, gespielt und irgendwann lief der ESP32 mit der 14.0.3 stabil. Also habe ich einen zweiten ESP32 gekauft und ihn direkt mit der 14.0.3 geflashed. 

Die SD Karte habe ich von meinem ersten ESP32 kopiert und lediglich den Namen geändert. Dann habe ich das Referenzbild neu aufgenommen, die Referenzmarken neu aufgenommen und die Digits neu definiert. Leider war das Ergebnis immer dasselbe: Die verrauschten Aufnahmen. 

Von daher kann es gut sein, dass @haverland Recht hat und die Referenzmarken nicht gepasst haben. Und das obwohl ich alles neu definiert habe. Mehrmals. Auch im Log war nichts zu sehen. Auch das Umstellen auf DEBUG hat keine Erkenntnisse gebracht. Keine Meldung. Beim Zurückstellen auf ERROR ist dann die config.ini verschwunden.

Ich habe also den ESP32 neu aufgesetzt und bin diesmal nur noch bis zur Definition des Referenzbildes gekommen. Jedes Mal beim Drücken auf SAVE hat sich der ESP32 aufgehängt, die config.ini gelöscht und neugestartet. Nach mehrfachen Versuchen habe ich den Flash gelöscht, die 14.0.3 frisch aufgespielt, eine frische SD-Karte genommen und alles nochmal probiert. Aber leider bin ich nicht übers SAVE beim Referenzbild hinausgekommen. Immer verschwindet die config.ini.

Von daher habe ich geschlossen, dass die Hardware eine Macke hat. Erst die rauschenden Digits und dann die verschwindende config.ini. Daher habe ich einen neuen ESP32 bestellt. Neue SD-Karte dazu. Und dann alles nochmal von vorne. 14.0.3 drauf, SD-Karte rein und wieder bin ich beim Referenzbild rausgeflogen. Die config.ini war wieder gelöscht.

Also habe ich den Flash gelöscht, die 14.0.0 aufgespielt, das SD-Karten-Image von der 14.0.0 draufgespielt und nochmal probiert. Damit habe ich den ESP32 ohne Probleme zum Laufen bekommen. Bild war speicherbar. Allerdings stand im ERROR Log, dass das Frontend nicht zur Firmware passt. Nach dem Update auf die 14.0.3 über den OTA Updater war die Fehlermeldung weg und ich kann nach wie vor Bilder speichern.

Irgendwie habe ich das Gefühl, dass gar nicht die Hardware, sondern die 14.0.3 das Problem ist. Genauer kann ich es leider nicht eingrenzen. Und bei den rauschenden Digits liegt es ziemlich sicher daran, dass ich die SD-Karte kopiert habe und er trotz Neusetzen aller Parameter alte Parameter behalten hat.

**Comment by Slider0007** [comment]
> Ich habe also den ESP32 neu aufgesetzt und bin diesmal nur noch bis zur Definition des Referenzbildes gekommen. Jedes Mal beim Drücken auf SAVE hat sich der ESP32 aufgehängt, die config.ini gelöscht und neugestartet.

Welches zip Paket hast du verwendet, um die SD initial vorzubereiten? Im zip für die remote config `AI-on-the-edge-device__remote-setup__v14.0.3.zip` der v14.0.3 fehlen die Ordner img_tmp und firmware auf der SD, wodurch es Probleme beim Update und bei der Erstellung der Referenzmarken gibt. Nach Anlage der Ordner war das Problem gelöst. Den Fix dafür habe ich bereits vorbereitet im PR #2020.
Sofern du dieses verwendet hast, könnte es deine Probleme erklären.

Daher könntest du den ersten ESP nochmals testen und sicherstellen, dass die notwendigen Ordner auf der SD sind. Das hat zwar nichts mit den verrauschten Aufnahmen zu tun, aber könnte ggf. den ersten ESP retten.
