### ISSUE TITLE
Here is a video tutorial

### ISSUE THREAD

**Issue by MakerMeik** [jomjol/AI-on-the-edge-device#202]
Hello Jomjol,

I am a fan of your project. Since I haven't found anything about it on Youtube yet, I made a short video tutorial about it myself. I hope you like it:

https://youtu.be/iUgxwbfkIqU

**Comment by jomjol** [comment]
Cool video - thanks a lot for this and the sharing!

**Comment by sygys** [comment]
Cant seem to get MQTT to work. Also the hardware is so darn slow that 90% of the time the webpages arent even loaded like it should.

I have a value of 822 on the mainpage. but for some reason this value isnt submitted to the mqtt server. Im not sure what im doing wrong. Have watched the video and in Home assistant the mqtt broker tells me the watermeter is connected through mqtt but my sensor keeps getting the value unavailable. so i guess the cam isnt sending any data out.

**Comment by jomjol** [comment]
@sygys: the mqtt interface has been simplified and you only need to set the maintopic anymore. The subtopics will be set by default values. 
As the video is not fully perfect anymore, I will close this issue, not to give a false advice.

**Comment by sygys** [comment]
I found some closed posts here that helped.
