### ISSUE TITLE
REST API `img_tmp/roi.jpg` funktioniert nicht. 

### ISSUE THREAD

**Issue by Danit2** [jomjol/AI-on-the-edge-device#2024]
### The Problem

The API `img_tmp/roi.jpg` is not working. 
When i try to open that i only become this site: 
![A4223E2B-2D4D-40A6-9D88-6D13A96ECBFB](https://user-images.githubusercontent.com/71522810/218395513-b47e0efd-a69d-4ada-8783-9831d9e1aa76.jpeg)

### Version

14.0.1

### Logfile

```shell
No Log
```

**Comment by Danit2** [comment]
The link "luck" in the screenshot is also not working.

**Comment by Slider0007** [comment]
Thanks for reporting. This is an mistake in documentation. It's already corrected.

--> img_tmp/alg.jpg (Show last aligned image)
