### ISSUE TITLE
Generated wifi.ini contains url-encoded spaces (%20)

### ISSUE THREAD

**Issue by phiresky** [jomjol/AI-on-the-edge-device#2036]
### The Problem

the initial "special-mode" wifi setup via the built-in access point generated a wifi.ini file that looked like the following:

```
ssid = "FRITZ!Box%207530%20TN"
password = "..."
```

It also fails to connect to this SSID
The correct name has spaces instead of %20:

```
ssid = "FRITZ!Box 7530 TN"
```

### Version

14.0.3

### Logfile

```shell
in serial console it just looped at "failed to connect to AP". After manually changing wifi.ini it's fixed.
```

**Comment by jomjol** [comment]
Fixed with latest rolling: https://github.com/jomjol/AI-on-the-edge-device/actions/runs/4210815203
