### ISSUE TITLE
New Training Data GWF MTK3coder MP Water Meter

### ISSUE THREAD

**Issue by supaeasy** [jomjol/AI-on-the-edge-device#2047]
### Files

[supaeasy.zip](https://github.com/jomjol/AI-on-the-edge-device/files/10775292/supaeasy.zip)

Great Project, I hope I can contribute with this. These are rolling Digits for dig-class100 / dig-cont taken from a GWF MTK3coder MP Water Meter. 

I trained dig-class100 with it and it works perfectly. Error Rate went from at least 50% errors to near zero.
[supaeasy.zip](https://github.com/jomjol/AI-on-the-edge-device/files/10775302/supaeasy.zip)

**Comment by jomjol** [comment]
Have a look here: 
https://github.com/jomjol/AI-on-the-edge-device/raw/rolling/sd-card/config/dig-cont_0610_s3.tflite
https://github.com/jomjol/AI-on-the-edge-device/raw/rolling/sd-card/config/dig-cont_0610_s3_q.tflite
