### ISSUE TITLE
Missing folders on sd card after "Remote Setup"

### ISSUE THREAD

**Issue by empty88** [jomjol/AI-on-the-edge-device#2049]
### The Problem

after using remote setup the folders "firmware" and "img_tmp" are missing on sd card.

This ends up in rebooting everytime you try to align the reference image in the first setup steps.

### Version

14.0.3

### Logfile

```shell
E (323580) OTA FILE: File does not exist: /img_tmp/ref0.jpg
W (323580) httpd_txrx: httpd_resp_send_err: 400 Bad Request - File does not exist
W (323590) httpd_uri: httpd_uri: uri handler execution failed
Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.

Core  1 register dump:
PC      : 0x401fd67d  PS      : 0x00060430  A0      : 0x801fd700  A1      : 0x3ffebca0  
A2      : 0x3ffcdd3c  A3      : 0x00000001  A4      : 0x00000001  A5      : 0x00000001  
A6      : 0x00000000  A7      : 0x3ffc2b15  A8      : 0x801fd67d  A9      : 0x3ffebc80  
A10     : 0x00000000  A11     : 0x3ffebcb4  A12     : 0x00000001  A13     : 0x3ffebd00  
A14     : 0x000000ff  A15     : 0x00000000  SAR     : 0x0000000e  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x00000064  LBEG    : 0x4008a274  LEND    : 0x4008a290  LCOUNT  : 0xffffffff  


Backtrace:0x401fd67a:0x3ffebca00x401fd6fd:0x3ffebce0 0x400fcdda:0x3ffebd00 0x40109cbf:0x3ffebd50 0x400e51b1:0x3ffebf40 0x400e4300:0x3ffebf80 0x400e4822:0x3ffec030 0x400e362c:0x3ffec050 0x40206d02:0x3ffec070 0x400e3749:0x3ffec090
```

**Comment by Slider0007** [comment]
Thanks for reporting. I also realized this today during some tests. The fix us already prepared in the following PR #2020.

**Comment by Slider0007** [comment]
The fix is already included in latest rolling and will be part of next offical release.

**Comment by thost96** [comment]
Running into this exact issue here on version 15.0.1. Directories "firmware" and "img_tmp" are missing and aren't created at boot. Tried multiple restarts. Is there a remote way to create these manually? Since folder firmware is missing, upgrade to 15.0.3 also fails atm.

**Comment by caco3** [comment]
as for now you have to create the folders manually on your PC, sry.
