### ISSUE TITLE
download meter image

### ISSUE THREAD

**Issue by dr-arut** [jomjol/AI-on-the-edge-device#2050]
### The Feature

How can I download clean photos of the water meter (without rectangles and circles)? Thank you very much for your work.
![alg_roi](https://user-images.githubusercontent.com/123622112/219954731-4cf6dfa5-f833-473d-aec0-f79fa65ce5dd.jpg)

**Comment by Slider0007** [comment]
You can download the "clean image" using http://IP/img_tmp/alg.jpg

**Comment by dr-arut** [comment]
thank you very much, just what you need
