### ISSUE TITLE
Speedup OTA DFU

### ISSUE THREAD

**Issue by caco3** [jomjol/AI-on-the-edge-device#2053]
### The Feature

Provide a list of md5 sums for each file on the SD-Card and only update the files which changed.

**Comment by TopGoalVl** [comment]
For all directories and files, including historical files on the SD card?

**Comment by caco3** [comment]
what do you mean with historical files?

For each file (in each folder) of the sd-card zip, we could calculate the md5sum.
that list would also be part of the zip file.
on an update, it iterates through each file in the zip file and compares its md5sum ( from the list) with tits md5sum of the current file on the sd-card. only if they mismatch, the file on the sd-card gets replaced.

the md5 sum of the files in the zip file could also be calculated on the fly, but that might be a bit more tricky.

**Comment by TopGoalVl** [comment]
So this only affects the firmware / Web-UI update process. Now I understand it.
By historical files I meant the files that were written in the past, on the fly.

**Comment by caco3** [comment]
> So this only affects the firmware / Web-UI update process. Now I understand it. By historical files I meant the files that were written in the past, on the fly.

Actually only the files on the SD-Card but not the firmware.

What ever file gets created/modified on the fly must not be touched by an update at all!

**Comment by nliaudat** [comment]
Perhaps it could be better to implement that in the building process of "AI-on-the-edge-device__update__xxx", to include only the modified files. 

Then the update on ESP32 side would be simpler, without computing md5 sum

**Comment by caco3** [comment]
no, that will not work, because we do not enforce that a user has to run each update step by step.

**Comment by nliaudat** [comment]
Computing md5 checksum on embedded device especially with sdcard is slow as it need to read the whole file. 
I mean overwriting every files faster.

**Comment by caco3** [comment]
agreed, md5 might not be the best approach, its just an idea.

And reading (also from sd-card) usually is much faster than erasing and writing.

**Comment by nliaudat** [comment]
[CRC-32](http://en.wikipedia.org/wiki/Cyclic_redundancy_check) is 4 time faster than md5.

Checking only the file size should be enough to decide if replacement is needed.

**Comment by jomjol** [comment]
I don't think, we will follow this. Therefore I close it. Please reopen in case it get relevant again.
