### ISSUE TITLE
Overview - Picture damaged

### ISSUE THREAD

**Issue by leonundjulie** [jomjol/AI-on-the-edge-device#2067]
### The Problem

Ich nutze die Version v14.0.0-RC7.

Warum wird im Overview das zuletzt gemachte Foto angezeigt wie die Anlage es zeigt? 

I am using version v14.0.0-RC7.

Why is the last photo taken displayed in the overview as shown in the attachment? 

![FalschesFoto](https://user-images.githubusercontent.com/120014597/220873520-547848fb-f7c2-4357-ba36-12057dc6303d.jpg)

### Version

v14.0.0-RC7.

### Logfile

```shell
no logfile
```

**Comment by Slider0007** [comment]
Please use latest official release 14.0.3. This issue is already fixed since 14.0.1.
