### ISSUE TITLE
Image crop after rotation

### ISSUE THREAD

**Issue by mrandt** [jomjol/AI-on-the-edge-device#207]
I love this project and have built the device to monitor my water consumption via Home Assistant (MQTT integration).

My water meter has a lid which I did not want to remove - so I modified the 3D-printed holder to feature a cutout which fits the lid. Downside: I can no longer rotate the tube / camera on the water meter.

I printed the case so that the camera orientation is in portrait mode, as I assumed that would ensure that all dials are in the cam's field of view.

Unfortunately I now realized that the image gets cropped when rotating.

Raw picture:

![water_meter_raw](https://user-images.githubusercontent.com/10500490/116877031-af4cb100-ac1d-11eb-9b6a-6f0aa740ce19.jpg)

After rotation / alignment:
![water_meter_rotated_cropped](https://user-images.githubusercontent.com/10500490/116877089-c1c6ea80-ac1d-11eb-931e-9ec41281f1a9.jpg)

You'll immediately spot the problem - while the raw image contains all info, the 10E-3 dial is partially cut away.

Is there an option to define the cropped area during "Alignment" stage? I was thinking of X and Y offset, width and height.

I did not find any related option in the docs.

If this is not possible, I can reprint my holder for a different orientation of the camera. However I think that using the cam in portrait mode has benefits - so adding such "cropping configuration" might be a nice extension.

Thanks!

**Comment by jomjol** [comment]
At the moment there is no option, but I'm think, how to implement a very basic option (e.g. rotate the image size).
Let you know, when I have a option.

**Comment by mrandt** [comment]
Do I understand correctly, that "rotating the image size" would mean keeping the aspect ratio and changing from landscape to portrait? That would certainly help. Thank you!

**Comment by jomjol** [comment]
I have now implemented a option to flip the image size from landscape to portrait. This can be done during the definition of the reference image:
![grafik](https://user-images.githubusercontent.com/30766535/117348502-8b51cf80-aeaa-11eb-82f1-538d95b76f2f.png)

In order to activate this option you need to add the following line into the `config.ini` in the section `[Alignment]`:
`FlipImageSize = false`

Currently this is only implemented in the "Rolling" branch.

Let me know, if it works!

**Comment by mrandt** [comment]
I can confirm that it works for me now. Thank you very much!

![grafik](https://user-images.githubusercontent.com/10500490/117643783-11ab3180-b189-11eb-872e-b25cb5b701eb.png)
