### ISSUE TITLE
PR #2055 ist nicht mehr drin bei der letzten Version

### ISSUE THREAD

**Issue by Danit2** [jomjol/AI-on-the-edge-device#2086]
### The Problem

Der PR https://github.com/jomjol/AI-on-the-edge-device/pull/2055 ist wider rückgängig gemacht worden in der aktuellen Version 15.0.1.

Ich fand dies noch gut. Leider ist nun wider auf jeder Seite der Rebootbutton. 

### Version

15.0.1

### Logfile

```shell
Keine
```

**Comment by caco3** [comment]
du hattest vorher nicht 14.0.3, oder?
weil diese änderung ist erst in rolling.
das kommt dann alles mit v15.1

**Comment by Danit2** [comment]
Nein ich hatte eine rollong version zwischen 14.0.3 und 15.0.1
War aber der meinung, dass beim 15.0.1 scho alles drinn ist was im rolling war. Aber in dem Fall ist alles ok. Danke.

**Comment by caco3** [comment]
wir haben ausnahmsweise das release nicht auf rolling gesetzt, damit wir ein release haben, wo nur die parameter migriert werden und sonst nichts verändert wurde.
