### ISSUE TITLE
Timestamp im Bild anzeigen. 

### ISSUE THREAD

**Issue by Danit2** [jomjol/AI-on-the-edge-device#2087]
### The Feature

Ist es möglich unten im Bild einen Timestamp anzuzeigen?

Ich habe das Bild von der Wasseruhr im HomeAssistant. Leider wird dort das Bild nicht immer aktualisiert. 
Mit dem Timestamp im Bild würde man besser erkennen ob das Bild aktuell ist oder nicht. 

Vielen Dank.

**Comment by caco3** [comment]
Duplicate of https://github.com/jomjol/AI-on-the-edge-device/issues/1187
