### ISSUE TITLE
Please, mark as "question"

### ISSUE THREAD

**Issue by woodlist** [jomjol/AI-on-the-edge-device#209]
Can we hope that the project will be ported to Arduino environment too?

**Comment by jomjol** [comment]
No - sorry no way. 

The needed external libraries (tflite, esp32cam, ...) and my self made libraries (image processing, flow controll, ...) need a more sofisticated editor than Arduino to be maintained. The effort to port this is too big (and I'm not an expert in Arduino IDE).

**Comment by woodlist** [comment]
@jomjol I would like to order custom project, based on introduced original project. Can we discuss privately? My email: woodlist.arakelyan@gmail.com Telegram: +37491837674

**Comment by woodlist** [comment]
@jomjol I would like to order custom project, based on introduced original project. Can we discuss privately? My email: woodlist.arakelyan@gmail.com Telegram: +37491837674
