### ISSUE TITLE
config save generates old boolean parameters

### ISSUE THREAD

**Issue by caco3** [jomjol/AI-on-the-edge-device#2090]
### The Problem

1. create a new (analog) number
2. save it
3. go to the config
4. select the new number

warnings about invalid parameters get shon.
looking on the logs, the boolean parameters get written in the old style (disabled):
```
;test.AllowNegativeRates =
;test.ExtendedResolution =
;test.IgnoreLeadingNaN =
```

### Version

rolling

### Logfile

```shell
-
```

**Comment by caco3** [comment]
@jomjol can you look into this? I did not find where this goes wrong in the javascript.

**Comment by jomjol** [comment]
Problem solved with the newest Rolling
