### ISSUE TITLE
Home Assistant Warning for RAW Value

### ISSUE THREAD

**Issue by Gloomyeye** [jomjol/AI-on-the-edge-device#2097]
### The Problem

Hallo,

ich erhalte mit der aktuellen Betaversion von Home Assistant 2023.3.0b2 eine Fehlermeldung, dass der RAW-Wert nicht numeric ist. Das ist korrekt, weil manchmal ein "N" drin steht. Sollte man dann die State Class beim RAW-Value nicht anpassen? total_increasing ist ggf. hier falsch.
Ich benutze Homeassistant MQTT Discovery für die Sensoren und habe die MQTT Sensoren nicht manuell angelegt.

### Version

Release: v14.0.3 (Commit: 6c891ab+)

### Logfile

```shell
Logger: homeassistant.components.sensor
Source: components/sensor/__init__.py:569
Integration: Sensor (documentation, issues)
First occurred: 16:29:09 (1 occurrences)
Last logged: 16:29:09

Sensor sensor.hwr_sensor_watermeter_raw_value has device class None, state class total_increasing and unit m³ thus indicating it has a numeric value; however, it has the non-numeric value: 0018N.31102 (<class 'str'>); Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+mqtt%22
```

### Expected Behavior

Keine Warning bei Home Assistant.

**Comment by haverland** [comment]
kann es sein, dass du ein class10 model verwendest? Mit class100/cont sollte das nicht vorkommen.

**Comment by caco3** [comment]
stimmt, das RAW topic muss ein string sein.
Ich muss mal schauen, wie ich da ändern kann, da ich ja keine Datentypen angehe sondern nur die device class. Gemäss https://www.home-assistant.io/integrations/sensor/#device-class müsste es wohl `None` sein.

**Comment by Gloomyeye** [comment]
> kann es sein, dass du ein class10 model verwendest? Mit class100/cont sollte das nicht vorkommen.

Stimmt. Ich habe auf ein class100 Modell gewechselt. Danke für den Tipp!

> stimmt, das RAW topic muss ein string sein. Ich muss mal schauen, wie ich da ändern kann, da ich ja keine Datentypen angehe sondern nur die device class. Gemäss https://www.home-assistant.io/integrations/sensor/#device-class müsste es wohl `None` sein.

Ja, ich würde hier auch einen String sehen. Auch "total_increasing" als state class würde ich hier nicht sehen, da der Raw Wert auch mal kleiner als der bereits gesetzte Wert sein kann.

**Comment by caco3** [comment]
Fixed in https://github.com/jomjol/AI-on-the-edge-device/pull/2103
