### ISSUE TITLE
Ignoring digits

### ISSUE THREAD

**Issue by awesome-michael** [jomjol/AI-on-the-edge-device#2099]
### Issue

Is it possible to ignore specific digits or set them to a hardcoded value if you know they can't be read correctly?
I have a watermeter that has a notch in the acrylic as mountingpoint for a reed sensor. However that notch distorts the image so that one or two of the analog values cannot be read reliably from the image. Is there a solution existing? Or should there be a feature to be able to ignore digits?

<img width="487" alt="Bildschirm­foto 2023-02-28 um 09 47 05" src="https://user-images.githubusercontent.com/37796947/221801985-3d7b6d57-a8e3-43db-a270-4ddb84b94679.png">

**Comment by jomjol** [comment]
In this case you can only use the 0.1 value (with extended resoltion). It does not make sense to ignore numbers or send them default values.
The only thing you could do is a post processing on your system out of the raw value.
