### ISSUE TITLE
WebUi not showing correct settings

### ISSUE THREAD

**Issue by unclej84** [jomjol/AI-on-the-edge-device#2101]
### The Problem

The WebUi shows different values than set in the config.ini - maybe related to #2077

### Version

v15.0.2

### Logfile

```shell
probably not really needed for this
```

### Expected Behavior

Values shown in the WebUI like they are in the config

### Screenshots

![WebUi](https://user-images.githubusercontent.com/60842330/221934738-d9d7dd74-93a7-4362-9ca9-84ce87c0af21.jpg)
![Config](https://user-images.githubusercontent.com/60842330/221934755-c2ceb9f1-b074-4798-a8f4-13cf3d6e67db.jpg)

**Comment by Piti61** [comment]
The down-button on the right side of "Postprocessing individual Parameters:" is not responding.

**Comment by caco3** [comment]
Is it still shown wrong if you force-refresh the web page (usually Ctrl-F5) or view it in another webbrowser or private mode?

**Comment by unclej84** [comment]
yes, force refresh and private mode still show the same result

**Comment by caco3** [comment]
can you provide your config.ini so I can reproduce it?

**Comment by unclej84** [comment]
[config.zip](https://github.com/jomjol/AI-on-the-edge-device/files/10854403/config.zip)
Here you are

**Comment by caco3** [comment]
Please upgrade to https://github.com/jomjol/AI-on-the-edge-device/releases/tag/v15.0.3

When we created  v15.0.2, one change got lost, I added it now again and made v15.0.3
