### ISSUE TITLE
https://github.com/jomjol/AI-on-the-edge-device/releases ist etwas durcheinander

### ISSUE THREAD

**Issue by Piti61** [jomjol/AI-on-the-edge-device#2102]
### The Problem

Die Assets zu 15.0.2 findet man unter 12.0.1. 

### Version

15.0.2

### Logfile

```shell
.
```

### Expected Behavior

Die Assets sollten weit oben unter 15.0.2 liegen

### Screenshots

![image](https://user-images.githubusercontent.com/121578900/221945660-bc97879e-7961-4399-ae76-ad9b63a0e673.png)

### Additional Context

.

**Comment by caco3** [comment]
Thanks

It was just the release notes which had too much content.
