### ISSUE TITLE
Home Assistant "rate_per_time_unit" misses state_class

### ISSUE THREAD

**Issue by caco3** [jomjol/AI-on-the-edge-device#2115]
See https://github.com/jomjol/AI-on-the-edge-device/discussions/2105
The sensor "sensor.gasmeter_rate_per_time_unit" has no "state_class: measurement" attribute. This is the flow rate, if I understand correctly. Without this attribute the value is not saved in the long term statistics. Is this attribute missing or is there a reason?

I guess that is a bug. I will correct it.
https://github.com/jomjol/AI-on-the-edge-device/blob/rolling/code/components/jomjol_mqtt/server_mqtt.cpp#L171

**Comment by caco3** [comment]
@MrReSc can you please try and test if https://github.com/jomjol/AI-on-the-edge-device/actions/workflows/build.yaml?query=branch%3Aadd-state-cass--to-rate_per_time_unit works for you? Just scroll down and take the "update" file.

Also make sure to create a backup before hand.
You will be able to return back to `v15.0` afterwards, but not to `v14`!

**Comment by MrReSc** [comment]
The attribute is now available.
![grafik](https://user-images.githubusercontent.com/24952268/222876905-2447a3e7-55b4-4955-ac51-ff86fe7d1865.png)

After the update a negative flow (`sensor.gasmeter_rate_per_time_unit`) was reported. This should not be, that if the parameter `Allow Negative Rates` is false.
![grafik](https://user-images.githubusercontent.com/24952268/222877122-d1f3e0ca-1237-4416-b391-34cfb2ec1212.png)
![grafik](https://user-images.githubusercontent.com/24952268/222877041-8901633a-f67d-4042-b486-67dbca918632.png)

**Comment by caco3** [comment]
Thanks for testing.

The thing with the negative rate is a separate issue, I created https://github.com/jomjol/AI-on-the-edge-device/issues/2121 for this.
