### ISSUE TITLE
timestamp again ;)

### ISSUE THREAD

**Issue by michapr** [jomjol/AI-on-the-edge-device#212]
Hi,

I really think that the option to send an additional timestamp would be nice.
(like in #79 already requested)

In the case that a digit cannot be recognized it can take a long time while this will be corrected / changed, depending on the digit.
So would be nice to get the last time of the written right value.

What do you think? Maybe as option in config?

Thank you for your great project!

**Comment by jomjol** [comment]
Just released a new version with a time stamp (and a rate) topic
After the update of the firmware and the html.zip you need to add the following lines in the `[MQTT]` section:
```
TopicRate = wasserzaehler/rate
TopicTimeStamp = wasserzaehler/timestamp
```
Just test it and let me know, if it is working!
Until then I'll close the issue.

**Comment by michapr** [comment]
Its working fine, thanks.
Would be nice to use a "standard format" like 
"2021-05-07T15:06:50"  instead of "2021-05-07_15-06-50"

What I mean with correct values - if there is a "N" we do not know about the "correctness" , right?
As sample if there will be 12.845m³ instead of  12.345m³ it will take at least 100 liter until the value could be corrected.
For higher values could take longer.

I have not found a "problem" in this time (just begin to use it for garden water only) but not sure how to handle such possible misinterpretation ;)

Will ask then, if such a problem exist. Anyway - I think for such cases it is the best to set "AllowNegativeRates" to true - for such corrections after next reading?

Thanks!

**Comment by michapr** [comment]
Just had a look at rate... How to understand the rate?

Should it be the flow rate per hour?

I have used 10 liters once - and got a rate of 0.00001 - but only once - then it was again "0"

For my understanding (from Domoticz as sample) the flow rate should be 10 liters / hour until next hour begin. 
That's why asking how it is defined ;)

Thanks!

**Comment by jomjol** [comment]
It's defined as unit / minute. That means, if you water meter has m³ as unit the flow rate of 1 means: 1000l/minute. In your case: 0.00001 = 0.1l/minute. 
It is always calculated compared to the last reading: (CurrentValue - LastValue) / (Time[minute])

**Comment by michapr** [comment]
Hmm... I think realistic values are max 1800l / hour - so 30l/minute - this would be a max 0.03  as max value.

ok, understand how it is calculated. If somebody (like me) need other value he can calculate it in own application ;)

Thanks!
