### ISSUE TITLE
The default Meter Type (Homeassistant section) is empty

### ISSUE THREAD

**Issue by caco3** [jomjol/AI-on-the-edge-device#2122]
### The Problem

`[MQTT SERVER] MQTT - Sending Homeassistant Discovery Topics (Meter Type: , Value Unit:  , Rate Unit: Unit/Minute)...`

### Version

-

### Logfile

```shell
-
```

**Comment by Slider0007** [comment]
@caco3: It was working during my testing (but this was before you rebased the PR, maybe it's related to that)

![image](https://user-images.githubusercontent.com/115730895/222922435-5c6c5009-1742-49a6-a579-488b66e1328d.png)

**Comment by caco3** [comment]
no, it is not related.

And the issue only occurs if discovery is enabled but the meter type is disabled (no default in the firmware)

**Comment by caco3** [comment]
I decided to keep it as is (empty9, since there is no proper values to fill in.
