### ISSUE TITLE
Add rest api call with value.html to hassio integration doc

### ISSUE THREAD

**Issue by nliaudat** [jomjol/AI-on-the-edge-device#2124]
### The Feature

[Hassio integration doc ](https://jomjol.github.io/AI-on-the-edge-device-docs/Integration-Home-Assistant/)is only json related .

Please add sample for direct html call from value.html

```
- platform: rest
  resource: http://<IP>/value.html
  name: cold_water 
  unique_id: cold_water_from_rest
  unit_of_measurement: "L"
  device_class: water
  state_class: total_increasing
  icon: mdi:gauge
  scan_interval : 120
```
Regards

**Comment by caco3** [comment]
please add a pull request directly to https://jomjol.github.io/AI-on-the-edge-device-docs/Integration-Home-Assistant/

You can edit it with the top right link "Edit on GitHub".
