### ISSUE TITLE
Set the previous value over rest-api/mqtt

### ISSUE THREAD

**Issue by ipod86** [jomjol/AI-on-the-edge-device#2127]
### The Feature

Hallo, 
ist es möglich "Set the previous value" über die rast-api und/oder mqtt bereitzustellen? 
Also das selbe, wie wenn ich folgenden Button drücke.

Hello, 
is it possible to provide "Set the previous value" via the rast-api and/or mqtt?  
So the same as when I press the following button.

![Screenshot_20230305_090201_Chrome](https://user-images.githubusercontent.com/66136363/222949186-f433223e-af36-4160-bfb4-75f21051d181.jpg)

**Comment by jomjol** [comment]
Sure: https://jomjol.github.io/AI-on-the-edge-device-docs/REST-API/

:-) RTFM :-)

**Comment by ipod86** [comment]
Lan I use it without enter a prevalue like the Button in the Website?

Like
/setPreValue?value=&numbers=main

**Comment by jomjol** [comment]
No, this is intended to set the prevalue by hand. Otherwise it does not make sense. 
You can read the raw value by another API call and use it to set the value (that's the way, the suggestions is done on the html-page)
