### ISSUE TITLE
Mal wieder ein paar Bilder

### ISSUE THREAD

**Issue by Knallochse** [jomjol/AI-on-the-edge-device#213]
[Bilder Wasserzaehler.zip](https://github.com/jomjol/AI-on-the-edge-device/files/6432117/Bilder.Wasserzaehler.zip)

Vielen Dank im Voraus

**Comment by jomjol** [comment]
Kommen ins nächste Training - aber Achtung: die nicht ganz eindeutigen habe ich unter NaN einsortiert.
Veröffentliche vermutlich am WE.
