### ISSUE TITLE
[TFLITE SERVER] Error in 15.0.2 and 15.0.3

### ISSUE THREAD

**Issue by JensHoRi** [jomjol/AI-on-the-edge-device#2134]
### The Problem

Das Device hat den Lesevorgang komplett eingestellt, startet alle paar Minuten neu und verbindet sich neu mit dem WLAN.

Der einzige Fehler (in 15.0.2 und 15.0.3) ist der Fehler TFFile, der im Log beigefügt ist.

### Version

15.0.3

### Logfile

```shell
<WRN> [TFLITE SERVER] Restarted due to an Exception/panic! Postponing first round start by 5 minutes to allow for an OTA Update or to fetch the log!
```

**Comment by Slider0007** [comment]
Please provide more information like logs with debug level and /or logs of serial console.
Howto --> see following posts

Sometimes it's related to an SD card issue and an corrupted file on SD. Have you already tested with another SD card?

**Comment by JensHoRi** [comment]
I got it running again with flashing it again and to the full setup again.

After re flash it still didn't work with old sdcard, with blank SD card reconfigured became it up again.

Logs were difficult, because device was only online a few seconds and restarted wlan connection again

**Comment by Slider0007** [comment]
Good to hear that it's working again. I'm closing the issue...
