### ISSUE TITLE
Backup timeout improvement

### ISSUE THREAD

**Issue by FastFrank** [jomjol/AI-on-the-edge-device#2139]
### The Problem

Add this before     xhr.ontimeout = (e) => { // XMLHttpRequest timed out        in backup.html  around line 148:

    xhr.onprogress = (e) => { // XMLHttpRequest progress ... extend timeout
        xhr.timeout = xhr.timeout + 500;
    };
    xhr.onerror = (e) => { // XMLHttpRequest error loading
        console.log("Error on fetching " + url + "!");
        if (retry > 5) {
            setStatus("<span style=\"color: red\">Backup failed, please restart the device and try again!</span>");
        }
        else {
            fetchFiles(urls, filesData, index, retry+1, zipFilename);
        }
    };

### Version

15.0.3

### Logfile

```shell
Timeout occurs although progress is made with downloading...
```

**Comment by caco3** [comment]
Thanks, I added it in https://github.com/jomjol/AI-on-the-edge-device/pull/2170
