### ISSUE TITLE
Linien im bild ??

### ISSUE THREAD

**Issue by mikewolf** [jomjol/AI-on-the-edge-device#215]
Habe jetzt meinen Ältesten ESP upgedatet auf rolling von 0605 uns auch hier diese Linien 
und somit kein OCR , habe dies jetzt bei 3 verschiedenen ESP32CAM  mit verschiedenen 
SD Karten und Netzteilen ??? bis zum Update funktionierte die OCR normal ohne Linien
Neustart , stromlos , reboot .. keine Änderung ????
neu geflasht usw neue SD karte ...

was mir noch auffällt das fast ständig die LED Leuchtet (blitz-weiß)

Mit freundlichen Grüßen
Mikewolf

![Bildschirmfoto 2021-05-07 um 20 35 40](https://user-images.githubusercontent.com/1781510/117493951-f3b8b380-af73-11eb-9ee8-280f914062b7.png)

**Comment by jomjol** [comment]
Ich hatte so einen Fehler schonmal irgendwo gesehen, finde es aber gerade nicht mehr.
Ich denke nicht, dass es an der Firmware selbst liegt. Eventuell ist es ein erhöhter Stromverbrauch. Ich habe einige Bibliotheken upgedated. Wie stark ist dein Netzteil? Gegenenfalls könntest du einen Stützkondensator in die Spannungsversorgung einbauen. Es gibt mehrer Threads, die damit gute Erfahrung gemacht haben.

**Comment by jomjol** [comment]
Bitte wieder öffnen bei weiteren Fragen
