### ISSUE TITLE
PostProcessing Parameters would not saved in config.ini

### ISSUE THREAD

**Issue by gotsila** [jomjol/AI-on-the-edge-device#2158]
### The Problem

Wenn ich in der Webconsole die Parameter für PostProcessing ändere und auf SAVE klicke werden diese nicht gespeichert. Die anderen Werte wie z.B.: MQTT werden abgespeichert.
Wenn ich die config.ini von Hand ändere werden die neuen Werte nicht in der Webconsole angezeigt.

### Version

15.0.2

### Logfile

```shell
[0d00h00m04s] 2023-03-11T17:43:49 <INF> [MAIN] Release: v15.0.2 (Commit: 4c40749+), Date/Time: 2023-02-27 21:28, Web UI: Release: v15.0.2 (Commit: 4c40749+)
[0d00h00m04s] 2023-03-11T17:43:49 <INF> [MAIN] Reset reason: Via esp_restart
[0d00h00m05s] 2023-03-11T17:43:50 <INF> [MAIN] WLAN-Settings - RSSI-Threshold: 0
[0d00h00m07s] 2023-03-11T17:43:52 <INF> [MAIN] =================================================
[0d00h00m07s] 2023-03-11T17:43:52 <INF> [MAIN] ================== Main Started =================
[0d00h00m07s] 2023-03-11T17:43:52 <INF> [MAIN] =================================================
```

**Comment by gotsila** [comment]
Ok, ein Update auf 15.03 hat funktioniert. Die config.ini wird nun mit den PostProcessing Parameters geladen. 
Dabei habe ich den Wert MaxRateValue auf 3.95 verändert und gespeichert. In der config.ini ist dieser Wert nun drin.

ABER:  Nach einem Reboot werden allerdings wieder keine  PostProcessing Parameters geladen.

**Comment by caco3** [comment]
> Wenn ich in der Webconsole die Parameter für PostProcessing ändere und auf SAVE klicke werden diese nicht gespeichert. 

Ich nehme an, mit der `Webconsole` meinst di die Konfigurationsseite. Die Webconsole ist nämlich etwas anderes, siehe https://jomjol.github.io/AI-on-the-edge-device-docs/Installation/#web-installer

Und ja, der Bug mit den postprossessing-Daten aus 15.0.2 wurde in 15.0.3 behoben.

> ABER: Nach einem Reboot werden allerdings wieder keine PostProcessing Parameters geladen.

Knnst Du das genauer erleutern?
Wo wird was nicht geladen?
Hast Du mal ein Page Refresh (Ctrl-F5) versucht?

**Comment by gotsila** [comment]
Richtig, ich meine die Konfigurationsseite: Settings > Configuration
Also ich hab jetzt paarmal hin und her die Werte geändert und gespeichert. Es funkioniert, wenn man sich nicht sicher ist, dann mal F5 drücken und dann passt das.

Prima, danke übrigens für das geile Projekt. Case solved!
