### ISSUE TITLE
Set PreValue with MQTT

### ISSUE THREAD

**Issue by helmar74** [jomjol/AI-on-the-edge-device#2174]
### The Feature

Currently the PreValue can be set in WEbGUI or with a Rest API Call.

In my setup it would be great to have the possibility to set the PreValue also thru MQTT.
I guess the change would "only" be to change PreValue from a status topic to a command topic?

**Comment by caco3** [comment]
Yes, I agree it might be useful.
Maybe we will implement it, but keep in mind that it is not as easy as it thoughts.
There area already MQTT topics to trigger the Flash LED, but else MQTT is only used for publishing.

**Comment by Slider0007** [comment]
Implemented with #2252. Will be part of next official release.

**Comment by Slider0007** [comment]
Implemented with #2252. This feature will be part of next official release.

Be aware: This feature is NOT available for versions 15.1.1 and older.
