### ISSUE TITLE
Link zu "here" bei der Hilfe "?" zu Digits und Analog führt zu einer lokalen IP.

### ISSUE THREAD

**Issue by Piti61** [jomjol/AI-on-the-edge-device#2175]
### The Problem

![Bildschirmfoto 2023-03-13 um 10 27 34](https://user-images.githubusercontent.com/121578900/224666214-a5e7eb55-7679-43b2-8bd3-3f6dbdd85245.jpg)

Im Foto links unten sichtbar unter ProsProcessing: lokaleIP/Choosing-the-Model

### Version

V15.1.0

### Logfile

```shell
x
```

### Expected Behavior

statt einer lokalen IP erwarte ich eine Domäne

**Comment by caco3** [comment]
Thanks for reporting it!

It is fixed with https://github.com/jomjol/AI-on-the-edge-device/pull/2180

See bellow how to get the latest rolling containing the fix.
