### ISSUE TITLE
AI on the EDGE on a ethernet and POE device 

### ISSUE THREAD

**Issue by bend94** [jomjol/AI-on-the-edge-device#2176]
### The Feature

Hi,
Would it be possible to have the "AI on the Edge" on an ethernet device ? (like raspberryPI4)
My water counter is far away from my WIFI network , i would like to have this feature on a device with a LAN and POE 

Thanks

**Comment by bend94** [comment]
may be i can used that device ?
IS "AI over the edge" compatible on this device?
https://shop.m5stack.com/collections/m5-cameras/products/m5stack-poe-camera-w-o-wi-fi-ov2640

**Comment by caco3** [comment]
We currently only support the ESP32-CAM hardware. It might work on aM5, but you would have to test and modify the firmware yourself.

**Comment by bend94** [comment]
hi
what do you mean by "modify the firmware" ? i am not a developper 
regards

**Comment by bend94** [comment]
it is very powerfull and easy to use but what does it means "RATE TOO HIGH"
What parameter do i have to tune to avoid "RATE TOO HIGH"? 
Thx

**Comment by caco3** [comment]
> what do you mean by "modify the firmware" ? i am not a developper

It means that somebody who is willing to invest a lot of time is free to get the firmware working on other hardware, but we will not do it.

>  what does it means "RATE TOO HIGH"

Please study the documentation, starting here: https://jomjol.github.io/AI-on-the-edge-device-docs/FAQs/#rate-too-high-read
