### ISSUE TITLE
ESP32CAM hängt sich nach kurzer Betriebszeit auf

### ISSUE THREAD

**Issue by phlupp** [jomjol/AI-on-the-edge-device#22]
Ich habe hier 2 ESP32CAM module, beide hängen sich nach kurzer Zeit auf und können nur durch ein Spannungsreset wieder zum Leben erweckt werden.

Ich betreibe die mit einem 5V 2A Netzteil und dem letzten Stabilen Build

Läuft das bei euch stabiler? 
Hat jemand eine Idee woran das liegen könnte ?

**Comment by jomjol** [comment]
Bei mir läuft es auf dem Rolling sehr stabil. Schaue dir mal das Logfile an (/log.txt) und poste mal die letzten 20-30 Zeilen.

**Comment by phlupp** [comment]
Ich habe jetzt nochmal ein anderes Netzteil verwendet, jetzt läuft es stabiler. Ich mach das hier wieder zu
