### ISSUE TITLE
OV2640: Camera init failed with error 0x20002

### ISSUE THREAD

**Issue by andim76** [jomjol/AI-on-the-edge-device#221]
Hallo,

vielen Dank für das super Projekt! Genau sowas habe ich gesucht. :-)

Ich habe allerdings ein Problem mit meiner Kamera. Die kann nicht initialisiert werden (siehe log unten) - "Failed to set frame size". Der ESP ist pingbar, aber rebootet regelmäßig.
Kamera ist eine OV2640 (Wobei es da scheinbar 2 verschiedene Typen geben soll. Meine Kamera ist vom Typ: XRZ00001-V240 V2.0 1903).

Zwischendurch hat die Kamera auch schon funktioniert. D.h. ich konnte per Browser ein neues Referenzbild machen. Beim nächsten Reboot ist der http Request vom Browser fehlgeschlagen. Ich habe es auch schon mit einem anderen ESP32 und einer anderen Kamera (selber Typ wie oben) getestet (auch über kreuz getauscht).

Als Spannungsversorgung verwende ich ein Labornetzgerät mit 5V und Strombegrenzung voll auf gedreht (bis 3A).

Hat jemand mit diesem Kameratyp Erfahrung oder hat diesen Fehler vielleicht sogar schon gelöst?

Serial log:
...
I (4070) gpio: GPIO[32]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0
E (5160) sccb: SCCB_Write Failed addr:0x30, reg:0x2e, data:0xdf, ret:263
I (5160) camera: Detected OV2640 camera
I (5160) camera: Allocating 1 frame buffers (150 KB total)
I (5180) camera: Allocating 150 KB frame buffer in OnBoard RAM
E (6210) sccb: SCCB_Write Failed addr:0x30, reg:0x3d, data:0x38, ret:263
E (6210) camera: Failed to set frame size
E (6210) camera: Camera init failed with **error 0x20002**
E (6210) server_part_camera: Camera Init Failed
I (6260) server-main: Using SDMMC peripheral
...

Danke schon mal im Voraus!

Viele Grüße,
Andi

**Comment by jomjol** [comment]
Hallo Andi,
  
Fehler ist mir bisher unbekannt. Kannst du mal das gesamt Log vom Start hier hochladen (per zip). Vielleicht liegt die Ursache noch woanders.

Danke und Gruß,
  jomjol

**Comment by andim76** [comment]
Hi jomjol,

hier ist das Log:
[log.zip](https://github.com/jomjol/AI-on-the-edge-device/files/6472628/log.zip)

Danke für's anschauen!

Grüße,
Andi

**Comment by jomjol** [comment]
Hi Andi, habe es mir angeschaut. Das Problem scheint beim I2C-Bus zu liegen (siehe SCCB-Fehler). Dieser Fehler ist mir bisher unbekannt und daher auch nur schwer auf die Ferne zu beheben. Ist natürlich komisch, dass es auch bei einem Kreuztausch nicht geholfen hat.
Ich kann nur empfehlen, die Verbindung nochmal zu prüfen (Kabel, Kontakte, ...). Aber das hast du vermutlich schon gemacht. Leider habe ich eine etwas andere Version von der OV2640 und kann es daher nicht testen.

Gruß,
  jomjol

**Comment by jomjol** [comment]
Schließe das mal, da keine Aktivität. Bitte gerne wieder öffnen, wenn es weitere Punkte / Fragen gibt.
