### ISSUE TITLE
Wlan password swollows '=' char

### ISSUE THREAD

**Issue by plix1014** [jomjol/AI-on-the-edge-device#222]
If you have a wlan password with a '=' char, it gets lost.
e.g.:
![esp32cam_wlan_pw](https://user-images.githubusercontent.com/45921388/118015653-d0677d00-b354-11eb-84e0-bd07d0597782.png)

> [...]
> CheckOTAUpdate Partition: ESP_OK
> file loaded
> ssid = "AAAABBBBCCCC"
> password = "abcdefghijklmnopqrstuvwxyzABCDE=FGHIJKL"
> hostname = "watermeter"
> WLan: AAAABBBBCCCC, abcdefghijklmnopqrstuvwxyzABCDEFGHIJKL
> Hostename: watermeter
> Fixed IP: , Gateway , Netmask , DNS 
> Connect to WLAN with dyn. IP
> [...]

**Comment by plix1014** [comment]
addon: Workaround: convert the passphrase to psk hexstring.

**Comment by jomjol** [comment]
Found the topic - will be corrected soon

**Comment by jomjol** [comment]
Corrected in the new release v7.0.1
