### ISSUE TITLE
Feature Request: Mobile Device Webpage

### ISSUE THREAD

**Issue by caco3** [jomjol/AI-on-the-edge-device#2225]
### Discussed in https://github.com/jomjol/AI-on-the-edge-device/discussions/2219

<div type='discussions-op-text'>

<sup>Originally posted by **8chM** March 22, 2023</sup>
It is possible to optimize the webpages, for mobile devices?
Of course it is very hard, to configure the ROIs with an iphone, but for overview it will be more helpfull.
</div>

## New Webpage (rolling)
- [x] Stream should open in new page
- [x] Add link to documentation into menu

**Comment by caco3** [comment]
@Slider0007 wouldn't it make sense to move the livestream menu entries into the `Data` section, like the recognition?

**Comment by Slider0007** [comment]
> @Slider0007 wouldn't it make sense to move the livestream menu entries into the `Data` section, like the recognition?

I personally wouldn't see it related to data section, but if your intention is to place it there, no issue for me.
