### ISSUE TITLE
Disable night recordings 

### ISSUE THREAD

**Issue by nhet** [jomjol/AI-on-the-edge-device#2228]
### The Feature

I use the software to record the yield of my PV system. Since this can only happen when the sun is shining, recording at night, or between sunset and sunrise is unnecessary. I would therefore wish that the recording intervals in this period can be switched off via config. Possible values for this are:
* Latitude
* Longitude
*  Offset (optional)

**Comment by iridium2001** [comment]
this sounds like a very similar request as mine here: https://github.com/jomjol/AI-on-the-edge-device/discussions/2221

**Comment by jomjol** [comment]
We suggest to solve this problem on the server side.
