### ISSUE TITLE
How to tune OCR?

### ISSUE THREAD

**Issue by mrandt** [jomjol/AI-on-the-edge-device#225]
OCR is not working well for certain characters; e.g. the 9 is mistaken for 0. See screenshot:

![grafik](https://user-images.githubusercontent.com/10500490/118263075-16882200-b4b6-11eb-8c1c-81923ea823d7.png)

Is there any way to tune the recognition?

Thanks!

I am on: master - v7.0.0 - 2020-05-08 build time 2021-05-08 18:20

**Comment by jomjol** [comment]
Hi,
yes, it looks, like the ROIs for your digits are a bit too small. If you are using also the newest html, then I you should reteach the ROIs and use the inner square as the size of the digit. Have a look at my settings:

![grafik](https://user-images.githubusercontent.com/30766535/118317835-d8f8b880-b4f8-11eb-83e5-a9a489c84248.png)

Best regards,
 jomjol

**Comment by v-c** [comment]
Similar issues for me:

![image](https://user-images.githubusercontent.com/19736118/118321882-43dfca80-b4cc-11eb-96de-9270ea61e7c5.png)

**Comment by v-c** [comment]
This is using the config like so:

![image](https://user-images.githubusercontent.com/19736118/118321978-6a056a80-b4cc-11eb-9db8-759848940eb1.png)

**Comment by jomjol** [comment]
@v-c: this digits look differently to the trained one. I can update the training if you send me 2-3 image of each digit (white and black each).

**Comment by v-c** [comment]
@jomjol : Here are a number of images from my water meter

https://www.dropbox.com/t/BZJdY7hl1ARPOu6f

**Comment by jomjol** [comment]
Thanks a lot, but I cannot process this format, as I would need to cut out every single image by hand.
If you turn on your logging in the settings, the ROIs are stored in the /log/digits directory. From this you can select 2-3 represenatives per digit. This I could use easily.
Thanks,
  jomjol

**Comment by mrandt** [comment]
I have enabled the logging and will send you the digits once I have pictures of all of them.

Posting a screenshot here for reference; this is from Configuration screen:

![grafik](https://user-images.githubusercontent.com/10500490/118355689-932c0680-b571-11eb-9cd2-6c04f8b32293.png)

**Comment by jomjol** [comment]
top!

**Comment by v-c** [comment]
Here's [a few days worth of images](https://drive.google.com/file/d/1D72bfWwZ4qWChe2nKZq_W7S3mVAGx5Re/view?usp=sharing) from my camera.

**Comment by jomjol** [comment]
Hi, I only need 2-3 image per digit (0, 1, ... 9). Can you please sort them and send then the 20-30 image only. I cannot sort this amount of images, as there quite some requests like this and I don't have the time to do so.
Thanks,
  jomjol

**Comment by v-c** [comment]
Sure. I thought you'd need more data to train. I'll add another link.

**Comment by v-c** [comment]
New [digits here](https://drive.google.com/file/d/1Izl3WXzGtznd2H78oCl_vqbLIsGSyhUS/view?usp=sharing).

**Comment by jomjol** [comment]
Just created a new tflite file: https://github.com/jomjol/neural-network-digital-counter-readout/blob/master/dig0860s1q.tflite
Please test and let me know.

**Comment by jomjol** [comment]
No activities currently. Please reopen in case of questions / remarks

**Comment by v-c** [comment]
Can you publish instructions on how to tune the OCR? I have some trouble even with the latest tflite file. See:

![image](https://user-images.githubusercontent.com/19736118/119567904-e294e280-bd7a-11eb-88e6-4d8e65a6874a.png)

**Comment by jomjol** [comment]
You can find the link on the first page on the wiki:
![grafik](https://user-images.githubusercontent.com/30766535/119606358-be74e800-bdf2-11eb-8b7b-da3883a02a7c.png)

Here it is directly: https://github.com/jomjol/neural-network-digital-counter-readout
