### ISSUE TITLE
Reboot after completing setup is not working

### ISSUE THREAD

**Issue by Slider0007** [jomjol/AI-on-the-edge-device#2256]
### The Problem

The reboot after completing the inital setup is not working.

Workaround: After pushing the button to complete the setup, pull the power cable to do the neccessary reboot.

see also issue https://github.com/jomjol/AI-on-the-edge-device/discussions/2253#discussion-5008826

### Version

15.x.x, rolling

### Logfile

```shell
n.a.
```

**Comment by srLinux** [comment]
yip confirmed! it does not work. And the reboot option system -> reboot destroys my tflite on the sdcard every time!

**Comment by Slider0007** [comment]
Will be fixed with new flow structure.

**Comment by caco3** [comment]
> reboot destroys my tflite on the sdcard every time!

I don't think this is related to the broken restart after the setup!
