### ISSUE TITLE
Include Library

### ISSUE THREAD

**Issue by Valou1807** [jomjol/AI-on-the-edge-device#2259]
### The Problem

Hello,

I am trying to upload the library in Arduino IDE 2.0.4 but it doesn't work. I receive this message: 

"Error: 13 INTERNAL: Library install failed: moving extracted archive to destination dir: library not valid"

Can you help me?

Valou

### Version

2.0.4

### Logfile

```shell
"Error: 13 INTERNAL: Library install failed: moving extracted archive to destination dir: library not valid"
```

**Comment by Slider0007** [comment]
This is not an Arduino library, therefore it's not possible to use with Arduino IDE.

This is a native ESP-IDF project. You have to use ESP-IDF environment (https://github.com/jomjol/AI-on-the-edge-device/blob/rolling/code/README.md) or use the precompiled files.
