### ISSUE TITLE
Saving new analog number not possible

### ISSUE THREAD

**Issue by caco3** [jomjol/AI-on-the-edge-device#2263]
### The Problem

after adding a new analog number, the save button stays disabled (which is ok as there is no ROI in it).
how ever after adding a ROI the save button still stays disabled.

Note:
On the digits this works correctly

### Version

15.1.1

**Comment by Slider0007** [comment]
@caco3: I'm already started to update some HTML pages for other reasons. I'm taking care of this one, if it's OK.
