### ISSUE TITLE
Where is the "AutoTimer" code located?

### ISSUE THREAD

**Issue by MarcelloPignata** [jomjol/AI-on-the-edge-device#227]
I am trying to make my device communicate with a server automatically after a set time (the autotimer value in this case), and I thought that editing the code executed by "AutoTimer" could help me achieve this, so I was wondering, where is the file that gets automatically executed located? Or do you think there is any other way I could do this?

Thank you very much in advance!

**Comment by jomjol** [comment]
The function, that is repeating the main flow on a high level ist: `void task_autodoFlow(void *pvParameter)` and it is located in the following file:
https://github.com/jomjol/AI-on-the-edge-device/blob/master/code/components/jomjol_tfliteclass/server_tflite.cpp
