### ISSUE TITLE
weird timezone issues in influxdb

### ISSUE THREAD

**Issue by srLinux** [jomjol/AI-on-the-edge-device#2273]
### The Problem

hi,
influxdb client always should send the UTC time. It causes weird issues like "in the future" measurements. Take a look over here: https://community.grafana.com/t/weird-timezone-problems/72815

![ksnip_20230331-200845](https://user-images.githubusercontent.com/127901031/229197342-cf6be088-fdb3-43d6-a4c2-a82d12fc318e.png)

After i changed the timezone on the webpanel to UTC0 the problem went away. It is maybe a influx/grafana related problem but the recommendation is to set the timezone to UTC in on the measurement sending clients. 

### Version

rolling 15.1.1

### Logfile

```shell
-
```

**Comment by wetneb** [comment]
Seems to be a similar problem to #2150.

I would still be interested to hear from @jomjol why this curious arithmetic had to be introduced in the first place:
https://github.com/jomjol/AI-on-the-edge-device/blob/dc9f5e597fc4ce2b89a27cc28f05553f0029f5bc/code/components/jomjol_influxdb/interface_influxdb.cpp#L56-L63

I agree that sending the time in UTC seems much cleaner.

**Comment by jomjol** [comment]
I agree in general. Does anybody know, how I get the UTC time in the ESP with a local time zone set?

**Comment by wetneb** [comment]
I think you can just use the same code I had written in the first place: https://github.com/jomjol/AI-on-the-edge-device/pull/2278

**Comment by srLinux** [comment]
> Seems to be a similar problem to #2150.
> 
> I would still be interested to hear from @jomjol why this curious arithmetic had to be introduced in the first place:
> 
> https://github.com/jomjol/AI-on-the-edge-device/blob/dc9f5e597fc4ce2b89a27cc28f05553f0029f5bc/code/components/jomjol_influxdb/interface_influxdb.cpp#L56-L63
> 
> I agree that sending the time in UTC seems much cleaner.

sorry, i don't used the search function this time :-)

**Comment by jomjol** [comment]
I cannot read the time in this functioni due to the following reason:
I want to send the time, when the picture was taken. This is handover as a parameter:
`void InfluxDB_V2_Publish(std::string _key, std::string _content, std::string _timestamp) `

Unfortunatly the string `_timestamp` is in local time. Therefore I need to convert it back into UTC. I could not find a function for this.

**Comment by jomjol** [comment]
I have made a branch to work on this problem: https://github.com/jomjol/AI-on-the-edge-device/tree/debug-influxdb

Please submit updates and changes there.

**Comment by jomjol** [comment]
Can you test my latest commit here: https://github.com/jomjol/AI-on-the-edge-device/actions/runs/4585284979

Should solve the problem.

**Comment by garciaargos** [comment]
> Can you test my latest commit here: https://github.com/jomjol/AI-on-the-edge-device/actions/runs/4585284979
> 
> Should solve the problem.

I just installed it and this works for me so far, Berlin timezone. Thanks!
