### ISSUE TITLE
Erkennungsrate erhöhen

### ISSUE THREAD

**Issue by Twister23** [jomjol/AI-on-the-edge-device#228]
Hallo, 

ich habe regelmäßig Probleme, das das Bild nicht richtig gedreht wird, wodurch natürlich die Zahlenerkennung nicht funktioniert. 

![jomjo_drehen](https://user-images.githubusercontent.com/84351049/118551958-9b956480-b75e-11eb-920c-e37090bbeaa2.jpg)

Weiter habe ich auch ein paar Zahlen, welche gut erkannt werden, andere hingegen nicht. Muss ich hier an der Kameraposition was ändern oder an der Einstellung?

![jomjo_ocr](https://user-images.githubusercontent.com/84351049/118552410-37bf6b80-b75f-11eb-9f03-3f2eed0daeae.jpg)

**Comment by jomjol** [comment]
Hi,
zu 1) Bild nicht richtig gedreht:
In diesem Fall hat die Software die Position der Referenzmarken nicht gefunden. Diese liegen dann irgendwo innerhalb des Suchfensters und dementsprechend passt die Drehung nicht. Ich habe den Eindruck, dass der Kontrast in deinem Bild nicht besonders hoch ist. Vielleicht kannst du dort noch etwas optimieren (Bildschärfe, eindeutigere Referenzstruktur, ...)

zu 2) Falsch erkannte Ziffern
Deine Zifferns sind sehr nah am unteren Rand und haben dort noch einen weißen Strick aufgrund der Reflexion. Das sind sehr schwierige Bedingungen für die Bilderkennung.
Kannst du eventuell die Kamera etwas zentraler über den Ziffern anbringen?

Beste Grüße,
  jomjol

**Comment by jomjol** [comment]
Aktuell keine Aktivitäten. Bitte gerne wieder öffnen.

**Comment by Twister23** [comment]
Danke für den Tipp. Ich hab die Kamera etwas anders positioniert und dann klappt das auch schon viel besser.

Leider funktioniert die Erkennung nicht immer. Wie sollte denn die Erkennungsrate aus deiner Erfahrung sein.

![41972640-DBAB-4D8D-8D03-A436746349A5](https://user-images.githubusercontent.com/84351049/119544480-0879b180-bd92-11eb-92aa-1a6fe8117e9a.jpeg)

**Comment by jomjol** [comment]
In deinem Beispiel hat es gut funktioniert. Die letzte Ziffer ist schwierig und kaum zu verbessern. Generell könntest du Ziffern sammel (2-3 Beispiele pro Ziffer reichen) und ich nehme sie ins nächste Training auf.

**Comment by Twister23** [comment]
Kann ich die Bilder auch per sftp/ftp downloaden?

**Comment by jomjol** [comment]
Weiss ich nicht - irgendwo hat mal einer geschrieben, wie er remote per Skript die Karte ausliest, aber ich finde es gerade nicht.

**Comment by Twister23** [comment]
mit "wget --mirror http://IP-ADRESSE/fileserver/log/digit/" kann man sich die Ordner downloaden.

Im Anhang hab ich mir noch ein paar passende Bilder zusammengestellt. Die Datei fängt mit der passenden Ziffer an.

[esp32.zip](https://github.com/jomjol/AI-on-the-edge-device/files/6572017/esp32.zip)

Danke schon man im Voraus.

**Comment by jomjol** [comment]
Zahlen sind angekommen und kommen ins nächste Training.
