### ISSUE TITLE
Flowstate_initialization_delayed

### ISSUE THREAD

**Issue by githubwesseln** [jomjol/AI-on-the-edge-device#2281]
### The Problem

Vor dem Update auf 15.1.1 war "dig-cont_0611_s3_q.tflite" eingestellt. Diese Auswahl wird jetzt nicht mehr angeboten (jetzt leeres Feld). Dadurch wird nach dem Booten "Flowstate_initialization_delayed" angezeigt. nach Änderung auf "dig-class100_0160_s2_q.tflite" läuft es wieder. "dig-cont_0611_s3_q.tflite" ist auf SD-Card vorhanden und nicht korrupt (nach Download über den File-Server) ergibt der Byte-Vergleich mit dem Original keine Fehler.
Dieser Fehler wird ähnlich schon in 2 weiteren Issues beschrieben.

### Version

15.1.1

### Logfile

```shell
kein Log-File

[Digits]
Model = /config/dig-class100_0160_s2_q.tflite

[Digits]
Model = /config/dig-cont_0611_s3_q.tflite
```

### Screenshots

![Flowstate_initialization_delayed](https://user-images.githubusercontent.com/61275073/229285577-5014f79d-dca0-4854-a39a-509437e0ecef.jpg)

**Comment by Slider0007** [comment]
I can confirm this issue.
The last listing in the drop down is missing and it could be the mentioned dig-cont_0611_s3_q.tflite.

**Comment by Slider0007** [comment]
This issue should be fixed with latest rolling. Can you please test and verify that dig-cont_0611_s3_q.tflite is selectable.

**Comment by githubwesseln** [comment]
Ok, nach Austausch von "readconfigparam.js" ist "dig-cont_0611_s3_q.tflite" wieder auswählbar. 
Habe es über den Fileserver allerdings nicht geschafft  "readconfigparam.js" hochzuladen, ging nur über OTA-Update.
Leerzeile zu Beginn der Auswahlbox ist weiterhin noch vorhanden.
