### ISSUE TITLE
flow rate is calculated wrong

### ISSUE THREAD

**Issue by Stff0r** [jomjol/AI-on-the-edge-device#229]
I am running version 7.0.0 and recognition works but the flow rate over MQTT is not calculated correct.

Example:
Current value: 159,9276 m³
Previous value: 159,9080 m³ 
So difference would be 0,0196 m³
Interval is set to 10 minutes so I would expect flow rate to be 0,00196 m³/min. But instead it was transmitted as "0.000017".

I noted different examples and rate is always very low, independent from real flow rate, and also the calculated numbers do not make sense to me.

**Comment by jomjol** [comment]
THe time that is used is the real time, in which the data was processed, so maybe this can explain part of the problem. The code is the following:
```
        time_t currenttime;
        time(&currenttime);
        localtime(&currenttime);
        double difference = difftime(currenttime, lastvalue);      // in Sekunden
        difference /= 60;                                          // in Minuten
        FlowRateAct = (Value - PreValue) / difference;
```
Maybe this helps.

**Comment by Stff0r** [comment]
Ganz klar ist es mir noch nicht.
Obiges Beispiel nochmal:
Um 8:00 Uhr wurde 159,9080 m³ gemessen, die nächste Messung ist um 8:10 Uhr mit 159,9276 m³.
Ich würde erwarten dass rate (um 8:10 Uhr) die Differenz zwischen den beiden Messungen ausgibt, also 0,00196 [m³/min].

Den Wert 0.000017 kann ich gar nicht nachvollziehen.

Oder habe ich die Funktion falsch verstanden?

**Comment by jomjol** [comment]
Ja im Prinzip schon. Aber die Berechnung der Rate ist nur "quick & dirty" implementiert. Die Zeitstempel, die er für die Berechnung zugrunde liegt sind z.B. nicht die Bildaufnahme, sondern die zum Zeitpunkt der Berechnung. Durch das Alignment (FastAlignment) kann die Zeitspanne dadurch durchaus mal um 2 Minuten größer oder kleiner sein und dann ändert sich die Rate im Vergleich zu deiner Rechnung. Wenn ich Zeit habe, dann werde ich das gerade ziehen (Zeitpunkt der Bildaufnahme).

**Comment by Stff0r** [comment]
Ok verstanden. Trotzdem sollte es aber keine Abweichung um den Faktor 100 geben, auch bei Verschiebung um ein paar Minuten?
Ich lasse mir die Durchflussrate parallel in FHEM berechnen und da ist mir aufgefallen dass der rate Wert über MQTT eigentlich immer abweicht und nahezu "willkürlich" erscheint mit Abweichungen von Faktor 50 bis 100.

Für mich aber aktuell kein Hindernis, da ich den Wert nicht zwingend benötige, wollte auf die (große) Abweichung hinweisen.

**Comment by jomjol** [comment]
Da hast du natürlich recht. Ich werde in den nächsten Tagen das Zeitintervall besser definieren (=Aufnahmezeit des Kamerabilders) und mir die Rechnung genauer anschauen. Melde mich, wenn ich etwas gefunden habe.

**Comment by jomjol** [comment]
Habe einen Bug gefunden (Abspeichern der alten Werte). In der neuen Rolling korrigiert.
Bitte gerne testen und rückmelden. Ich werde das in das Feature dann ins nächste Release aufnehmen und später den Issue schießen.

**Comment by Stff0r** [comment]
Funktioniert. Danke. 👍

Mein Nachtrag oben ging vermutlich unter:
Nachtrag2: bei deaktiviertem "TopicRate" in der config, wird auch Timestamp nicht mehr gesendet obwohl aktiviert.

Soll ich dafür besser ein neues issue machen?

**Comment by jomjol** [comment]
Nein brauchst kein neues Issue, ist nur eine Kleinigkeit.
Ist korrigiert und hochgeladen.

**Comment by Stff0r** [comment]
Getestet und funktioniert.
Kann geschlossen werden.
