### ISSUE TITLE
"main" von "value" für influxDB v1.8 trennen

### ISSUE THREAD

**Issue by Reinhard-M** [jomjol/AI-on-the-edge-device#2297]
### The Feature

Ich verwende influxDB v1.8.10. Aktuell wird für die Übertragung an influxDB "main" (also der Inhalt von 'Number:') und "value" zu "main/value" zusammengesetzt. Damit wird es in der Datenbank zu einem einzigen "field-key". Vorteihaft für die Datenbankauswertung wäre "main" als tag-key und "value" als field-key zu senden. Zusätlich ein "house" oder "room" Tag den der Anwender ausfüllen kann wäre auch nicht schlecht. Ist aber schon Luxus.

**Comment by jomjol** [comment]
In der neusten Rollling kannst du jetzt Measurement und Field unabhängig voneineander und auch noch für jeden Number einzeln definieren. Müsste also passen.

**Comment by Reinhard-M** [comment]
Funktioniert perfekt, vielen Dank für die schnelle Umsetzung 👍 
Kleine Anmerkung am Rande: Wenn man bei "Measurement" einfach die ganze Zeile übernimmt wäre volle Flexibilität für die influx v1 gegeben. Also sowas wie "my_measurement,Zaehler=main,Raum=Keller". Entspricht der Influx Syntax. Ich brauche es zwar nicht da ich nur einen Zähler habe. Aber eventuell ist es ja für andere von Vorteil :-)
