### ISSUE TITLE
Esphome support?

### ISSUE THREAD

**Issue by jkaberg** [jomjol/AI-on-the-edge-device#2307]
### The Feature

I was curious as if you guys have considered supporting [Esphome](https://esphome.io/)?

Benefits of using the Esphome platform would be [ease of management](https://github.com/esphome/dashboard) and (updates), [Bluetooth Proxy](https://esphome.io/components/bluetooth_proxy.html), [Native API](https://esphome.io/components/api.html) and generally just a [boat load of additions](https://esphome.io/components/) out of the box would be nice addition. 

I figure Ai on the edge would need to "support" the [external component](https://esphome.io/components/external_components.html) in Esphome for this to work? Maybe other changes are needed?

**Comment by caco3** [comment]
Our firmware is not based on ESPHome! Changing it to ESPHome as a base would be a huge effort. Also we are very limited on RAM, thus having an additional framework underneath might not be helpful.
