### ISSUE TITLE
corrected value is higher than raw ?

### ISSUE THREAD

**Issue by lakusz1github** [jomjol/AI-on-the-edge-device#232]
How it is possible ?

Raw Value: 00951.732
Corrected Value: 951.742
Checked Value: 951.742

**Comment by jomjol** [comment]
If you have the "ConsistencyCheck" enabled, the values are compared to the previous value and dependending on the changes, corrections are applied.
Example: Prevalue: 951.733 --> RawValue = 951.732 --> Last Digit is lower than previous --> zero crossing has happend --> digit before ("3") should have changed to "4" = corrected value. 
This does not work very well for pure digital values, so I recommend to disable.
