### ISSUE TITLE
Led Flash lässt sich nicht deaktivieren

### ISSUE THREAD

**Issue by Xsev1** [jomjol/AI-on-the-edge-device#233]
Version 7.0.1
Mit der Funktion "WaitBeforeTakingPicture" auf 0 schaltet der Blitz dennoch ein und lässt sich nicht deaktivieren. 
Grüße

**Comment by jomjol** [comment]
Du hast recht - das hängt mit FixedExposure zusammen. Wenn du das abstellst, sollte es funktionieren. In der nächsten Version sollte es immer tun. Bin gerade dabei das zu testen.

**Comment by Xsev1** [comment]
FixedExposure was bei mir default false. Da hab ich eigentlich keine Änderung vorgenommen.

**Comment by jomjol** [comment]
Sollte jetzt funktionieren (erstmal in der Rolling). Bitte um kurze RM.

**Comment by Xsev1** [comment]
Funktioniert! Super! Vielen Dank!
