### ISSUE TITLE
Empty Model dropdown list

### ISSUE THREAD

**Issue by A380Coding** [jomjol/AI-on-the-edge-device#2334]
### The Problem

Removed all tflite files except one for digital and one for analog readings.
Doing so, the Model dropdown (in config ) list is empty. Uploading a second tflite file e.g. for digital readings, shows one file in the drop down list, not both.

Configuration->Digits->Model

### Version

15.1.1

### Logfile

```shell
-
```

### Expected Behavior

Show correct model files in drop down list in configuration menu.

**Comment by Slider0007** [comment]
Thanks for reporting. This is a known issue and already fixed in rolling (#2282). The fix will be part of next official release.
