### ISSUE TITLE
Power saving

### ISSUE THREAD

**Issue by dotchewango** [jomjol/AI-on-the-edge-device#234]
Hi Josef, first of all, congratulations to your project and work. Respect!
I think, what would be the best add-on feature to this project is the possibility to use it by solar and lipo power. For this it should be possible to configure wake up times (e.g. once at 7:00 am every day with 10 minutes active server time or every hour and deep sleep after full image processing). I use the following Arduino IDE code on an ESP32-Cam module for a nest box watch project in order to do that.

`
void hibernate( void ) {
  time_t now;
  unsigned long timeToSleep; // = TIME_TO_SLEEP * uS_TO_S_FACTOR;
  
  // Turns off the ESP32-CAM white on-board LED (flash) connected to GPIO 4
  rtc_gpio_hold_en(GPIO_NUM_4);  // keep white LED actively off during sleep mode
  pinMode(FLASH_LED, OUTPUT);
  digitalWrite(FLASH_LED, LOW);      // white LED off

  digitalWrite(RED_LED, HIGH);     //  red LED off

  //esp_sleep_enable_ext0_wakeup(GPIO_NUM_04,1 /* level to trigger */);  // in this case, if LUX-Sensor detects sun set (darkness), because RTC_GPIO10 == GPIO4
  //esp_sleep_enable_ext0_wakeup(GPIO_NUM_34,1); //1 = High, 0 = Low
  if (bSetSendFotoMode) esp_sleep_enable_ext0_wakeup(GPIO_NUM_13, 1);  // PIR port pin zu Wecken

  time(&now);
  localtime_r(&now, &timeinfo);
  timeToSleep = ((3600 - ((timeinfo.tm_min*60) + timeinfo.tm_sec)) % AUFWACHINTERVAL) - 9;
  esp_sleep_enable_timer_wakeup(uS_TO_S_FACTOR * timeToSleep);
  //Serial.println("ESP32 wurde neu eingestellt aufzuwachen nach " + String(timeToSleep / 60) + " Minuten und " + String(timeToSleep % 60) + " Sekunden");
 
  Serial.println("Going to sleep now");
  Serial.flush(); 
  delay(1000);
  esp_deep_sleep_start();
  //Serial.println("This will never be printed");
}
`

**Comment by jomjol** [comment]
Idea is great, but just going to deep sleep will still remain in about 8mA power consuption, most probably due to the the camera. Would need some testing. I'll might give it a try, as soon, as I have some time.

**Comment by dotchewango** [comment]
With 3 Lipo cells (18650) you would have 3x2500mAh, i.e. 31 days operation @ 10mA permanent consumption without any solar charging.
Additionally, we'll find some camera enabling pin in order to switch off the camera completely during deep sleep, e.g. using JFET J113. Even without this, we had a solution to retrieve counters outside nearby in gas or water houses around your home or summer house.

**Comment by jomjol** [comment]
I'll take this into account in my testing.

**Comment by TapuGithub** [comment]
Just thought about using it in my house with lipo cells. But with 31 days on 3 lipo cells, it looks unpractical - instead of looking at devices once a month as I do, I'll need to recharge batteries once a month, not including at least doubling the solution cost.  So for autonomous operation, it either needs to be solar or reduce power consumption at least 3 times from 10mA.

Anyway great project :)

**Comment by jomjol** [comment]
@TapuGithub Thanks for your comments. The BLE does not solve the problem. Because I did not found an option to turn of the camera compeletely and this is the power consuming part.

**Comment by Papadoma** [comment]
Something that might be of interest to this topic

https://time4ee.com/articles.php?article_id=126

GPIO 32 is connected to a PMOS that turns on and off the two small regulators that make the 1.2V and 2.8V lines. However, the camera itself is always connected and the author suggests that connecting the PMOS output to the camera VDD (and the SD card VDD) will drop the current. 

Indeed, someone did it by a simple modification https://issueexplorer.com/issue/espressif/esp32-camera/247

**Comment by Papadoma** [comment]
> 



> Or, maybe, using BLE instead of Wifi.

As for this, according to Andreas Spiess https://youtu.be/nyWMaAF4dRQ, BLE can drop consumption even further. Not sure if its worth it if the reading is taken once a day though. Still, it would be nice to have it as an option

**Comment by jomjol** [comment]
@Papadoma , @TapuGithub @dotchewango 

Regarding the power savings, I'm not going to follow this anymore.

Background is, that a significant reduction would need a hardware modification and this is not an option for the majority of the users. This would be rather something for a commercialized variant, which I'm not having a customer for currently.

Therefore I close this post for the time beeing.

Thanks for your ideas and links to get a deeper technical understanding.
