### ISSUE TITLE
Low Power Mode

### ISSUE THREAD

**Issue by sov1980** [jomjol/AI-on-the-edge-device#2349]
### The Feature

It would be good to have Low Power mode in case of battery powering. For example switch to Low power after some time after reboot. After that wake up for the scan flow, report to MQTT or databases and go back sleep. As an option  - add MQTT command for going Low Power until the next scan flow.

**Comment by jomjol** [comment]
This has been extensively discussed. Due to the limits in the hardware (especially some transitors) the ESP32CAM device has a very high current usage even if the ESP32 is in ultra low power --> technically not possible without new hardware.
