### ISSUE TITLE
Was ist ein günstiger Druckdienst und welches Material benötigt man?

### ISSUE THREAD

**Issue by Tscherno** [jomjol/AI-on-the-edge-device#235]
Ich habe noch nie etwas 3D drucken lassen.

**Comment by jomjol** [comment]
Als Material ist PLA völlig ausreichend. Zu einen Druckdienst kann ich dir leider nicht helfen, da ich selbst drucke.
Du kannst aber am Anfang auch einfach eine Dose (z.B. Chipsdose) oder einen Karton nehmen. Andere haben es auch schon mit einem Rohr und einen Pappdeckel gebaut.
Bevor du Geld ausgibst, würde ich es erstmal so versuchen.

**Comment by Tscherno** [comment]
Gute Idee, danke. Und ne Ausrede für Chips hab ich auch :-D
