### ISSUE TITLE
New Analog Training Data

### ISSUE THREAD

**Issue by mkranjcic** [jomjol/AI-on-the-edge-device#2375]
### Files

Hello,
I did read how to prepare images, and I did check if those images already exist, but I am not sure if I did all good.
First, I can not find all same pointers on all digits.
Next, I am not able to run collectmeteranalog.exe on my windows, I keep getting error :(
If by any chance you can point me if this images are any good?
As seen on Analog Needles link - there are just "full numbers" of pointers, so I am sending just them.
If there is need to add 1/10th - please let me know.
I have renamed files for numbers as they should be, since from device I got all sorts of numbers (same as regular readings - it is not good, this is why I am sending images).

Thank you very much!

[AnalogPointer1.zip](https://github.com/jomjol/AI-on-the-edge-device/files/11367807/AnalogPointer1.zip)

**Comment by haverland** [comment]
The images are quite good. Because of images from dig-class11, we have many pictures of the x.0 but not so much of 1/10th. So it would be fine to share 1/10th images too.

If you can install python on your Windows machine, you can use collectmeteranalog alternatively.

**Comment by mkranjcic** [comment]
Huh, ok, I will do my best :)

**Comment by haverland** [comment]
Windows download should working now. https://github.com/haverland/collectmeteranalog/releases/tag/v1.0.14

**Comment by mkranjcic** [comment]
Hi,
I do not have them all, but, would this be sufficient?
[labeled.zip](https://github.com/jomjol/AI-on-the-edge-device/files/11417969/labeled.zip)

**Comment by haverland** [comment]
thx. Yes, because others added similiar images. 

You images are a bit rotated. This may be due to the alignment or the reference image. Here you can do something for yourself. 

We use rotation of the images within a narrow range for all images of the dataset to make the AI more robust against rotations. It is not too much on your images. So I will add it to the dataset.

**Comment by mkranjcic** [comment]
Hi,
I have noticed that rotation is not good, and I have tried to correct it, and now I am unable to set reference points (capturing points fails with 0 sized files, and if I reboot, process of capturing starts, and lasts 1h or so, while it is not possible to align image).
I will try to fix this by stopping auto capturing, but, maybe to add code that would report error when not possible to align image with reason of not having ref point images...
Anyhow, I will do my best to collect better images, and in meantime, I will try to check tflite-s.
Thx
