### ISSUE TITLE
WiFi Passphrase including "=" fails

### ISSUE THREAD

**Issue by Mirko81** [jomjol/AI-on-the-edge-device#238]
Hi, very good project and it works very well.
Unfortunately, connecting to a WiFI with an "=" in the passphrase does not work.
Method "ZerlegeZeile" eliminates all "=" from ini-values.

**Comment by Mirko81** [comment]
Do you know a workaround without changing the passphrase?

**Comment by jomjol** [comment]
Due to a restructuring, this bug went in the code again (see 7.0.0 --> 7.0.1) . 
Just corrected it in version 7.1.1 (again :-)).

Sorry for the inconvenience.

**Comment by Mirko81** [comment]
Thank you for the quick response and bug fix.
I will try ist tomorrow.
