### ISSUE TITLE
Incorrect checking of values

### ISSUE THREAD

**Issue by v-c** [jomjol/AI-on-the-edge-device#239]
![image](https://user-images.githubusercontent.com/19736118/120260490-0321d880-c264-11eb-991a-46caf2ac078d.png)

It seems like the value checking has a bug. See image. Raw value is 197526. Checked value is 197527, yet, the returned value is 197536? I can't seem to explain why this is the case.

**Comment by jomjol** [comment]
The explanation is the following: in the previous value, there was read a 19752**7**. Obiously the maximum rate detection is turned on with a "1". Therefore this is triggered. 
For some reason you do not use the DecimalShift to put the decimal separator to the second last position. Therefore you will always entcounter this problem. 
Two options:
1. Set the decimal separator
2. Disable MaximumRate or put it to a higher value.

Best regards,
  jomjol
