### ISSUE TITLE
WLAN-Password does not accept the empty ("") password ANY MORE

### ISSUE THREAD

**Issue by ve4011** [jomjol/AI-on-the-edge-device#2393]
### The Problem

We are using MAC-Radius-Authentification on our WLAN; so we just entered the WLAN-SSID, leaving the passwort EMPTY. 
This worked without any problems using firmware 13.0.8 - BUT NOW, firmware 15.2.4, results in an error "empty password".
Please change this back, so we can use our MAC-Radius-Authentification again.
Many thanks in advance!
Volker

### Version

15.2.4

### Logfile

```shell
[0d00h00m05s] 2023-05-06T18:26:55	<INF>	[WLANINI] SSID: IoT
[0d00h00m05s] 2023-05-06T18:26:55	<INF>	[WLANINI] Password: XXXXXXXX
[0d00h00m05s] 2023-05-06T18:26:55	<INF>	[WLANINI] Hostname: GasmeterCAM
[0d00h00m05s] 2023-05-06T18:26:55	<ERR>	[WLANINI] Password empty. Device init aborted!
```

### Screenshots

ssid = "IoT"
password = ""
hostname = "GasmeterCAM"

**Comment by ornea** [comment]
I also encountered this so moded my local source files.

But it got me thinking that it may have been changed for good reason - how
bad is it to have a open wifi with trusted users in a remote location.

I think its ok but curious if the developers had a good reason or if its
just a settings validation check that seemed like a good idea.
