### ISSUE TITLE
New Digital Training Data

### ISSUE THREAD

**Issue by rockberte** [jomjol/AI-on-the-edge-device#2398]
### Files

I collected the images of my digital counter following the guid in the documentation. I zipped and uploaded only those I have problems in recognition. For all other numbers similar data already exists.

[labeled.zip](https://github.com/jomjol/AI-on-the-edge-device/files/11420207/labeled.zip)

Hopefully the data is fine for training. Please let me know of something is missing or needs better quality or whatever.

Thank you very much!

**Comment by rockberte** [comment]
Ah sorry - I forgot to mention that.
I use the dig-class100 model.

**Comment by haverland** [comment]
Is now Part of the next release. You can test it uploading the https://github.com/jomjol/AI-on-the-edge-device/raw/rolling/sd-card/config/dig-class100-0162_s2_q.tflite  file to /config and change the version in configuration.
