### ISSUE TITLE
Elster V200

### ISSUE THREAD

**Issue by Gert05** [jomjol/AI-on-the-edge-device#240]
Hi,

Thanks for a great project. 
I'm using this with an Elster V200 watermeter, a common type in The Netherlands.
Recognition of digits is not 100%, also analog seems to suffer a bit every now and then.
I wonder if it is necessary to "teach" these different digits.
Would it be possible to include the V200 "character set" in a certain way?
![image](https://user-images.githubusercontent.com/12745187/120304971-8c6ef480-c2d0-11eb-953b-f7e9a20d7dea.png)

**Comment by jomjol** [comment]
Hi,
this is not a problem.

For the **digits** the ROIs look good. Just automatically collect examples, select 2-3 typical images per type (white on black, white on red) and send them to me. Just to make it clear: together not more than 40-60 images all together (I alread good 10000 images to sort by myself) :-)

For the **analog** part, I need to try, if I can encorporate it into the existing CNN or you need a specific one. I would give the integrated version a try. There the effort is a bit bigger. I need an image for about every position with the following naming `x.y_text.jpg` where x.y is the reading of the pointer. If there are some positions missing, this is not a problem as long, as there is a nearby image. For the image above it would look like: `9.9_arbitrary-text.jpg`. You can collect it also with the log files, but need to correct it by hand most probably.

I'm looking forward to get the new images.

Best regards,
  jomjol

**Comment by derFricklerDE** [comment]
same "problem" here... got also an Elster watermeter. 
I start collecting some images and send it to you.

Thanks so far for this awesome project

**Comment by Gert05** [comment]
Thanks for a quick response. It took some time to collect all digits / all colors (trying to conserve water here...), but that's done now. I'll send the digits over to you via mail.

**Comment by jomjol** [comment]
Digits included in v10.0.0
