### ISSUE TITLE
dual meter option?

### ISSUE THREAD

**Issue by wizardnl** [jomjol/AI-on-the-edge-device#241]
Dear Jomjol,

thanks for all the work great project.  currently using it for my gas and water meter.  now i have a question my electric meter is a so called double meter for day and night would it be possible to integrate this so its possible to read both meters with one esp.

![20210601_122303](https://user-images.githubusercontent.com/9564314/120453003-efc15b00-c392-11eb-930e-e364274a54b7.jpg)

**Comment by jomjol** [comment]
Hi,
you are not the first one to ask for this new feature :-). 

Up to now I refused to implement it, as it has major changes in the backbone. But as this request seems to be the "most wanted", I decided to start the development. It will take some time, but I'm working on it. Just stay tuned with the "rolling" branch, there it will be published first for testing and you are welcome to be part of the beta users.

Best regars,
  jomjol

**Comment by wizardnl** [comment]
> Hi,
> you are not the first one to ask for this new feature :-).
> 
> Up to now I refused to implement it, as it has major changes in the backbone. But as this request seems to be the "most wanted", I decided to start the development. It will take some time, but I'm working on it. Just stay tuned with the "rolling" branch, there it will be published first for testing and you are welcome to be part of the beta users.
> 
> Best regars,
> jomjol

i can imagen it would take some time to develop would be happy to beta test it for you just let me know how/when i can help

greetings

wizardnl

**Comment by jomjol** [comment]
TEASER: the newest rolling has a lot of preparation for a dual meter counter. But still at the moment I'm still testing it on a single meter counter to ensure a backward compatiblity.

**Comment by Basti09** [comment]
is there a solution for the standard electricity meter? 3d print housing

**Comment by jomjol** [comment]
@Basti09 I'm not aware of one.

**Comment by Basti09** [comment]
Haben Sie vor eine Variante zum Stromablesen zu machen ?

**Comment by jomjol** [comment]
Die Software kann das ja bereits. Ich plane aber keine allgemeine Hardware, da dort die Unterschiede so groß sind, dass es keine allgemeine Lösung gibt.

**Comment by Basti09** [comment]
Okay alles klar vielen dank :) und super Arbeit & Projekt dafür möchte ich mich natürlich auch bedanken.

**Comment by jomjol** [comment]
@wizardnl  The newest rolling has now the dual meter option.

**Comment by BenouGui** [comment]
Where is the option for dual ?

**Comment by jomjol** [comment]
You need to install the firmware and html of the "rolling" branch. Then you can define in the ROI definition of the digital and analog region of interest several "Numbers", so in your case two numbers.

![grafik](https://user-images.githubusercontent.com/30766535/124364935-2108a180-dc45-11eb-9361-454990e93f15.png)
![grafik](https://user-images.githubusercontent.com/30766535/124364938-282faf80-dc45-11eb-82b5-d2a316e5f280.png)

**Comment by BenouGui** [comment]
I don’t found the "rolling" branch.

**Comment by BenouGui** [comment]
Thank you

**Comment by jomjol** [comment]
![grafik](https://user-images.githubusercontent.com/30766535/124365335-937a8100-dc47-11eb-8fc0-71a4ab343a33.png)

**Comment by BenouGui** [comment]
![2662C226-ED9B-469D-9A69-D718FE763287](https://user-images.githubusercontent.com/72623517/124365948-ff5ee880-dc4b-11eb-9e6b-d7fa84d5c1c4.png)

Great work at first sight, it works well

**Comment by jomjol** [comment]
I'm closing this for the moment as it seems working
