### ISSUE TITLE
Headerfields are to long when using cloudflare tunnel

### ISSUE THREAD

**Issue by parhedberg** [jomjol/AI-on-the-edge-device#2413]
### The Problem

I am using cloudflare tunnel to reach some of my local servers, such as watermeter. This is not a common thing, but if I have this problem, maybe somenone else also have it in a different scenario. 

When i try to access via cloudflare tunnel i get this error:

a 431 statuscode and the text 'Header fields are too long'.

This link gave me some clues to the problem:
https://stackoverflow.com/questions/67849381/esp32-httpd-header-fields-are-too-long-for-the-server-to-interpret

### Version

Not accessible at the moment. But latest version.

### Logfile

```shell
Not accessible.
```

### Expected Behavior

Being able to administrate the watermeter with this setup.

### Screenshots

![image](https://github.com/jomjol/AI-on-the-edge-device/assets/13777521/6a60ffb4-98e3-41e4-958c-0e56f4742832)

**Comment by caco3** [comment]
closing due to missing feedback
