### ISSUE TITLE
Maybe improve guessing counter

### ISSUE THREAD

**Issue by StrathCole** [jomjol/AI-on-the-edge-device#242]
As seen on the screen, the first number is recognized wrong. All other numbers are correct. Maybe the system could recognize this as it does e.g. when finding a N when between 1 and 2. 
![IMG_20210608_111901](https://user-images.githubusercontent.com/7449529/121159712-b59d0100-c84b-11eb-8514-f8c7af5de2ac.jpg)

**Comment by jomjol** [comment]
Unfortunetatly this is not possible. The "N" is a outputof the neural network and needs to be trained. I don't see a point, that this number is identified wrong. You image looks a bit crumbly. What is the reason for this?

**Comment by StrathCole** [comment]
> Unfortunetatly this is not possible. The "N" is a outputof the neural network and needs to be trained. I don't see a point, that this number is identified wrong. You image looks a bit crumbly. What is the reason for this?

Oh, okay. I thought you were doing some kind of after-neural logic as you are doing the "rate too high" thing. So I thought one could check if the rate is too high by `first number * 10000`.
I don't know why the image is not optimal. I am using a standard ESP32-S with OV2640 camera. I guess that the "crumblyness" might be caused by adjusting contrast? No idea if that is done.
