### ISSUE TITLE
Problem recognition of fractional digital number 1

### ISSUE THREAD

**Issue by developnoop** [jomjol/AI-on-the-edge-device#2422]
### Issue

Hi,
Using AI-on-the-edge since 2021 and now got a problem with a newly installed water meter:
The Number 1 after the dot is hardly recognized.

The water meter is a Sensus IPearl and the 3 fractional digits have some sort of “bar” above and under the number.
The last fractional digit also has a bar to the right of the number.

The digit 1 often gets recognized as a 7.

I tried to get the box as close to the digit as possible. The issue here is also that the fractions are slightly leaned to the right.

Do you have any idea how I could boost the recognition of the 1 more?

![canvas](https://github.com/jomjol/AI-on-the-edge-device/assets/21089212/36dfda95-025e-4040-abba-cd6bba2e2231)
![Screenshot 2023-05-21 110835](https://github.com/jomjol/AI-on-the-edge-device/assets/21089212/d8f97011-adfb-488b-8906-23e317c709c3)

**Comment by jomjol** [comment]
This is a topic for the training data. The problem is the bar above the digits. For the neural network, this is very close to a digital "7" (two bars right and one above). We can only try to include a full set of this numbers to the next training. Can you turn on the loging and send 2-3 image for each digit (ideally one from each position (0.x, 0.0x, 0.00x), so we have a variation in illumination already.

The setting for the ROI is okay.

**Comment by developnoop** [comment]
Okay, thanks for the detailed answer!
I turned on the logging and will wait to have a set of each of the 3 possible digits from 0-9 with 2-3 pictures.
Will come back here when the data is ready!

**Comment by developnoop** [comment]
Okay, I have a zip with only the fractional digits. As given in the documentation, I used the tool [collectmeterdigits](https://github.com/haverland/collectmeterdigits).
It has all everything, only fractional digits, and also more than 3 of each digit. 
But the zip itself is around 155kb. Should i send it to the address given in the tool description, or add it here to this ticket?

**Comment by haverland** [comment]
I've added the dataset and rerun the model:

https://github.com/haverland/Tenth-of-step-of-a-meter-digit/blob/master/output/dig-class100-0164_s2_q.tflite

You can try it if you upload it to the config folder of the device and set in configuration to dig-class100-0164_s2

**Comment by developnoop** [comment]
Thanks! 
I tried to create a model myself but i failed miserable.
So i uploaded your updated model  today. 
If it is okay for you i will let it run for several days and than report back with the results.

**Comment by developnoop** [comment]
So after 3 days of testing: No problems with the model and the numbers anymore.
So i will close this topic, am i right that the changed model will be part of the next release?

**Comment by haverland** [comment]
Yes ist part of the next release.
