### ISSUE TITLE
Cannot leave setup mode - restarts always with initial setup 

### ISSUE THREAD

**Issue by moritzgoebel15** [jomjol/AI-on-the-edge-device#2438]
### The Problem

The setup worked perfectly and I was able to complete all steps.
When I push "Leave setup modus and reboot to Normal Modus" it seems to restart but boots into "Initial Setup" again.
I do not get any errors.  

### Version

not able sind stuck in setup mode

### Logfile

```shell
not able sind stuck in setup mode
```

### Expected Behavior

Restart in Normal Mode

**Comment by moritzgoebel15** [comment]
I have reflashed the device to be sure it was not due to a reboot in the setup process. Same problem again with latest version. 

Is there a way to manually get it out of the setup Mode ?

**Comment by forrestfunk** [comment]
try clearing cache of your browser or a "forced reload" of the page (Firefox it's Ctrl+F5 for example) (or try another browser)

**Comment by caco3** [comment]
you can set the setup mode config ma,ually to false.

whichversion are you using?

please provide a debug USB log

**Comment by jiikoo** [comment]
I have the same problem although the last line of the config.ini is "SetupMode = false"

**Comment by jiikoo** [comment]
The workaround is to add "/index.html#" to URL. Like this: http://192.168.2.71/index.html#

**Comment by moritzgoebel15** [comment]
Thanks - it was already set to setup mode false but the cache itself did not help but with another device reboot it worked. Thank you ! Now I just have to optimize my reflections :)
