### ISSUE TITLE
problem with quality and rotating

### ISSUE THREAD

**Issue by lakusz1github** [jomjol/AI-on-the-edge-device#244]
Hi

I have 2 problems when i rotating image from ESP32-CAM, quality is poorer than during create referance image. And problem is the angle is different in reference and standard view, why ?

These is standard view : https://ibb.co/d0yHnsY
These is reference image view https://ibb.co/MCGRWD7

**Comment by jomjol** [comment]
Image quality:
During the reference creation, the rotation is calculated in the browser with standard javascript image processing. Later this is done in the ESP32 with very simple libraries (e.g. no antialising, ...). 

Rotation: 
This should not be the case. The image looks strange, as there should not be red square. Normaly they indicate the reference. This cannot be on a digit itself.Please check the configuration.

**Comment by lakusz1github** [comment]
Hi
Look on the images. standard view is more rotated than reference. 

What is main reason these "referense image" ?

**Comment by jomjol** [comment]
The different rotation means, that your references for the alignment are not identified properly. In this case they are found arbritary and this results in a bad rotation. Which structure did you take vor alignment?

**Comment by lakusz1github** [comment]
I mean not "referense image" , but "Alignment Marks" ? What for it is ?

In menu: Configuration > Edit Configuration > Alignment > Reference Image 

Show actual reference is ok, but actual image from Main page, is actually more rotated

**Comment by jomjol** [comment]
The "Alignment Marks" are needed to find a defined reference position on the image to be sure, that you always find the right position. You can find more information in the chapter `2b. Define Alignment References` in the wiki: https://github.com/jomjol/AI-on-the-edge-device/wiki/Graphical-configuration

Regarding the wrong rotation, this problem is coming from not well defined reference images. Did you do a correct initial setting?

**Comment by lakusz1github** [comment]
I hope so, I try many times "restarting" setting, but w/o success

**Comment by jomjol** [comment]
No, I do not mean restart. I mean the inital setup with a guidence through setting the reference image, the alignment marks, the ROIs and the general settings.
