### ISSUE TITLE
Provide a way to log digit image when the confidence of the detection is low

### ISSUE THREAD

**Issue by v-c** [jomjol/AI-on-the-edge-device#245]
I would like to improve the machine learning model of the digits. For this, I want to log images of digits where the confidence in the detected number is low. Is there a way to log all low confidence images of the digits?

**Comment by jomjol** [comment]
At the moment the confidence is not recorded. You can extract this during the tflite procedure `int CTfLiteClass::GetOutClassification()`  (https://github.com/jomjol/AI-on-the-edge-device/blob/master/code/components/jomjol_tfliteclass/CTfLiteClass.cpp).
From there you can start writing a logging information.

**Comment by v-c** [comment]
Thanks. Closing the issue.
