### ISSUE TITLE
Extract of POIs broken

### ISSUE THREAD

**Issue by A380Coding** [jomjol/AI-on-the-edge-device#2451]
### Issue

Image is taken perfectly, but the digits (extracted from the POI round) look very strange. Green pixels, shifted numbers and therefore the extracted value of completely wrong. Out of sudden this happened and I can't get it working again. Any ideas?
![Unbenannt](https://github.com/jomjol/AI-on-the-edge-device/assets/80172816/c235bfd6-fb19-458a-8b55-4f15848758c1)

**Comment by friedpa** [comment]
Most properly your CAM Module died, but you can try to release the camera connection, clean it and reconnect.

**Comment by A380Coding** [comment]
The camera seems to be fine as the complete image is fine as well. I guess it is maybe the sd card?

**Comment by A380Coding** [comment]
I changed the SD card but nothing changed :(

**Comment by A380Coding** [comment]
I just deleted all jpg on sd card, reference image etc. rebooted and set up everything again. Now it is working again. I did the same step several times but only now it worked. Maybe because I deactivated automatic round start an rebooted after each step and only activated automatic round start at the very end again.
If someone else faces this issue, maybe this helps.
