### ISSUE TITLE
Hostname

### ISSUE THREAD

**Issue by barthm1** [jomjol/AI-on-the-edge-device#246]
If I use more than one device with different hostnames - the second device always reboots - because of the error
"Can't change hostname" - The hostname seems to always "watermeter"

watermeter is always set and the change to another name doesn't work

I can solve the problem when using dedicated ip addresses -

**Comment by jomjol** [comment]
Did you try to set the hostname in the config.ini directly?

**Comment by barthm1** [comment]
Yes

jomjol ***@***.***> schrieb am Di., 15. Juni 2021, 20:27:

**Comment by jomjol** [comment]
Then I need to search for the error :-(
Currently take a while, I will leave the issue open meanwhile.

**Comment by barthm1** [comment]
I think the hostname watermeter is set before the Name of the ini File ist
used

Now when  I use IP Adresse every device hast the hostname watermeter

jomjol ***@***.***> schrieb am Di., 15. Juni 2021, 21:36:

**Comment by Johny-Debugger** [comment]
I have the same problem with hostname. There is no reaction to the assignment of host names in wlan.ini

**Comment by jomjol** [comment]
Error found and corrected in v7.1.2 (2021-06-17)
