### ISSUE TITLE
Sendezeitpunkt über CRON-Expressions einstellbar machen

### ISSUE THREAD

**Issue by thoath2** [jomjol/AI-on-the-edge-device#2470]
### The Feature

Hallo jomjol,
beim meinem ersten Versuch, Dein tolles Projekt auszuprobieren, stieß ich auf eine Tatsache, die evtl. verfeinert werden könnte.
Das Sendeintervall kann ich zwar miz z.B. 5 min einstellen, jedoch wird als Startzeit ein zufälliger - in der Regel "krummer" Zeitpunkt (z.B. 2023-06-13 08:29:55.123) - verwendet, der sich sicher vom Reboot-Vorgang herleitet. Als alter Zeitreihenspezi (ich bin in einem Hochwasserzentrum tätig), würde ich mir "glatte Zeitstempel" wünschen (z.B. 2023-06-13 08:30:00.000), damit man diese besser weiterverarbeiten kann. Das würde aber eine Konfiguration des Startzeitpunktes voraussetzen, z.B. über eine CRON-Expression oder eine einfachere Lösung. Man müsste ja nur dem Timer sagen, dass er erst zu einem glatten Zeitpunkt seinen Dienst beginnen soll.
Viele Grüße
Thomas

**Comment by jomjol** [comment]
Hi Thomas,
aktuell nicht geplant, da du das Problem auch Serverseitig lösen kannst (z.B. Extrapolation). Aber ich nehme es in die Feature Request mit auf (#40)
