### ISSUE TITLE
Enable RSSI Threshold by default?

### ISSUE THREAD

**Issue by caco3** [jomjol/AI-on-the-edge-device#2480]
We got now several reports that the RSSI Threshold works as expected and is a great improvement.

eg. https://github.com/jomjol/AI-on-the-edge-device/discussions/2443#discussioncomment-6209859

@Slider0007, @jomjol what do you think if we enable it by default and set it eg. to `-70dBm`?
This would only apply to new installations.

IMO we still should keep it as Expert Param as most users will not need to understand or change it.

**Comment by Slider0007** [comment]
From my point of view it can be enabled by default. I would set the threshold at least to -75.
