### ISSUE TITLE
IoT Data using GSM or LTE-M with battery power

### ISSUE THREAD

**Issue by njscop** [jomjol/AI-on-the-edge-device#2483]
### The Feature

My use case is remote locations where the device would read and send data once a month.

Ideally, it would turn on using a simple schedule, read data -> Some Form of mobile data ->  MQTT  -> Hibernate for next Cycle.

Any suggestions?

**Comment by jomjol** [comment]
Not planned within this device as the hardware is limited and would need additional modules.
