### ISSUE TITLE
Energy saving

### ISSUE THREAD

**Issue by s0170071** [jomjol/AI-on-the-edge-device#2486]
### The Feature

I noticed the web interface constantly displays a high cpu temperature of about 57°C. I would suggest these two energy saving measures: 

1. option to sleep after recognition has finished until the next cycle. Web interface is inaccessible then. Acceptable for many users once set up. 
2. do not recognize most significant digits all the time. If e.g. flow limitation would kick in if the first three digits would change, there is no point in converting them in the first place. Most of the time in my case only the last two digits (out of 6) have to be processed. 
If there is a potential rollover on the next significant digit, include it. Other than that it is probably a good idea to do a full conversion every x cycles. 

Pseudo code: 
```
for (int i = 0; i< numberOfDigits; i++) {
  Digits[i].includeThisDigitInNextRecognition=false; 
  double significance = 9*10^(i+commashift) ; // i is the index of the digit, 0 is least significant 
  if ( allowedDelta > significance) {
     Digits[i].includeThisDigitInNextRecognition=true; 
  } else {
    if (Digits[i].lastKnownState== 9 {
    Digits[i].includeThisDigitInNextRecognition=true;    
  }
}

```

}

**Comment by adellafave** [comment]
I'd like this power saving enhancement to save temperature. I'm running a device outside in direct sunlight in a small enclosure that regularly hits between 66C to 81C in the Summer. I'd enable this option to save power and lower the operating temperature. I had a previous device that had it's LED begin strobing after about a year, not sure if it was temperature induced.

**Comment by ulipo** [comment]
I'm planning to use this wonderful piece of software to read a gas meter, I would love to run it on a small battery and solar panel setup, it would be great to have an option to make it sleep for long amount of time.
For my purposes, for example, a couple of readings per day should be more than enough.

**Comment by jomjol** [comment]
Currently not planned, as the remote controll would get very tricky if the web interface is only accessible on a very limited version of time. 
Idea transfere to Feature request (#38)
