### ISSUE TITLE
Auto set-up  

### ISSUE THREAD

**Issue by s0170071** [jomjol/AI-on-the-edge-device#2487]
### The Feature

1. is it possible to train a NN to recognize the rotation of the image ? If so, then auto rotation could be implemented. Alternatively use a known good recognized number and rotate the image slightly and see if the recognition confidence improves. Use this for adaptive fine tuning of the rotation. 
2. During set up, scan the camera image, detect any digits. 
Start with the largest ones (size of ROI), make sure there are multiple of those next to each other.   
Then assemble them from left to right to form a number. This could be a one time only job to assist set-up.

**Comment by jomjol** [comment]
The effort for this is for this free version very high. No plan to be followed this.
