### ISSUE TITLE
Auto init SD card

### ISSUE THREAD

**Issue by s0170071** [jomjol/AI-on-the-edge-device#2488]
### The Feature

The SD setup has giving me some trouble in the past. It would be great to have that piece handled by the Device. 
There is a project that obviously can format SD cards, but I have no clue if that piece of code fits into the current design. 

https://github.com/greiman/SdFat-beta

After formatting, the user sets the wifi credentials. Any other files can be downloaded by the ESP afterwards. 

On a side note: In the repo, there is a zip that needs to get extracted onto the SD. There is also a folder that is called sd-card. 
That one is a bit of a pitfall since it suggest you can copy this one to the SD. Seems this is not the case.

**Comment by caco3** [comment]
That project looks quite tricky and large.
We would need to add it to the existing firmware and also contain all needed files for the SD card. Later is impossible as we are at the limit of the firmware size.

**Comment by jomjol** [comment]
Thanks! But will not be followed currently. Has been stored in Feature Request (#37)
