### ISSUE TITLE
overexposed pictures since update to 7.1.2

### ISSUE THREAD

**Issue by HJS72** [jomjol/AI-on-the-edge-device#249]
Since update to 7.1.2 all pictures are overexposed. Reboot and refresh via OTA without any improvement.
Any idea?

<img width="971" alt="Bildschirmfoto 2021-06-20 um 08 10 18" src="https://user-images.githubusercontent.com/41542201/122664073-62a64080-d19f-11eb-8d07-cf5ca50f0106.png">

**Comment by jomjol** [comment]
I cannot reproduce this error. I just reflashed my system to v7.1.2:
![grafik](https://user-images.githubusercontent.com/30766535/122666701-3d213300-d1af-11eb-9497-e981cf55968d.png)


Everything is working fine (w/ and w/o `FixedExposure`). Can you send me your `config.ini` file, so I could check it.
My one for the image taking section is looking like follows:

```
...
[MakeImage]
;LogImageLocation = /log/source
WaitBeforeTakingPicture = 5
;LogfileRetentionInDays = 3
Brightness = -2
ImageQuality = 5
ImageSize = VGA
FixedExposure = true
...
```

**Comment by HJS72** [comment]
I just changed
WaitBeforeTakingPicture from 2 to 5
and added Brightness = -2.
Now everything is OK.

Thank you very much!

**Comment by jomjol** [comment]
Okay, in this case it is clear what happened: during the first 2-4 seconds, the automatic light controll of the camera is working and the image is arbitrary over or under illuminated. Obviously you where lucky with the old version and have been in a working intermediate state with 2 seconds.
You must not choose less than 5 seconds or switch on the FixedExposure setting.

Have fun,
  jomjol
