### ISSUE TITLE
Livestream submenu HTML is missing </li>

### ISSUE THREAD

**Issue by wilfredktlr** [jomjol/AI-on-the-edge-device#2491]
### The Problem

The HTML for the livestream submenu is missing a `</li>` (closing list item tag).

https://github.com/jomjol/AI-on-the-edge-device/blob/d47ed060b0f420565bebd7edf2dee3edcff68266/sd-card/html/index.html#L110-L114

### Version

v15.2.4 (Commit: cbd14a2)

### Logfile

```shell
N/A
```

**Comment by haverland** [comment]
> ### The Problem
> The HTML for the livestream submenu is missing a `</li>` (closing list item tag).
thanks
