### ISSUE TITLE
Enhance digit checking

### ISSUE THREAD

**Issue by cribskip** [jomjol/AI-on-the-edge-device#250]
I'm beginning to set up a permanent setup and struggle with consistent recognition (mainly because of bad optical position, I guess).

This leads to this situation f.e.:
<img width="821" alt="image" src="https://user-images.githubusercontent.com/1429498/122666985-b9684600-d1b0-11eb-879a-a13dd394e848.png">
31.6721 Rate too high - Returned old value - read value: 32.5727 - checked value: 32.5727
Aligned Image:

Digital Counter:
 0 0 0 3 1

Analog Meter:
 5.9 6.7 2.9 7.1

The raw value is perfectly fine. However, there seems to be a prior run which decided the 1st analog dial to be a six.

I see following possible improvement:
Adding an option to be extra careful when a digit is around +- 0,3 f.e. so that it may take the lower number when >maxflow. Together with CheckDigitIncreaseConsistency on, this may fix (my) problem just fine.

Cheers

**Comment by jomjol** [comment]
Normally something like this is implemented. The analog numbers are checked diffenently around +- 0.3. CheckDigitIncreaseConsistency is only handling the digits.
To judge, what happend I would need the history of the values. Do you have loggin on and could send me the last two readings before this error occures?

**Comment by cribskip** [comment]
Thanks for your quick and through reply, jomjol!

Turned out I had to realign the camera and now everything is performing just fine.
I moved the camera closer to the dails and adjusted the lens accordingly.
