### ISSUE TITLE
Wrong digit with digital CNN v8.7.0

### ISSUE THREAD

**Issue by tunip** [jomjol/AI-on-the-edge-device#251]
Version:
master - v7.1.2 - 2020-06-17

With CNN v8.7.0 on my gasmeter the "3" is recognized as "0". The result is permanent if I compare the two CNN versions the last few days.

digital CNN v8.5.0:
<img width="232" alt="Bildschirmfoto 2021-06-21 um 14 35 32" src="https://user-images.githubusercontent.com/11404472/122762770-f3634600-d29d-11eb-8e35-d4c745c3afaf.png">

digital CNN v8.7.0:
<img width="233" alt="Bildschirmfoto 2021-06-21 um 12 21 01" src="https://user-images.githubusercontent.com/11404472/122762655-d6c70e00-d29d-11eb-8614-f0e53a958e6b.png">

Is there something where i can help/support?

**Comment by Cybolord** [comment]
same behaviour at my water meter...

Version:
master - v7.1.2 - 2020-06-17

Analog reading "9" will be recognized by digit "0" indeed.

**Comment by jomjol** [comment]
You can send me a set of digits (2 images per digit -  not more!) and I will include them in the training. 
If you have a running tflite, there is no reason to change to a new one. Even if you change the firmware, it will run will all old versions.
So first, I suggest to switch back.
Best regards,
  jomjol

**Comment by Stff0r** [comment]
It also seems that 8.5.0 is working better for my meter.
But I still have the problem that '8' is recognized almost everytime as '0'. And sometimes the same with '6' and '9'. Thanks to the good plausibilization the value is corrected nevertheless.

jomjol, if I send you my digits, do you need a complete set from 0 to 9 or are the non working ones sufficient?
(It would take some weeks from 0 to 9)

**Comment by jomjol** [comment]
You can also send me only single digits. 1-2 images per digit is fully sufficient.

**Comment by Cybolord** [comment]
![watermeter2](https://user-images.githubusercontent.com/23726446/122891852-24e31c80-d345-11eb-95cf-7d6fdcc76687.jpg)
![watermeter1](https://user-images.githubusercontent.com/23726446/122891876-290f3a00-d345-11eb-9353-ae694f6721ea.jpg)

Thank you for your effort in advance!

**Comment by jomjol** [comment]
I need a single image of the digit, done by the logging of the cut out ROIs. I cannot provide image manual cutting of screenshots :-).

**Comment by Stff0r** [comment]
Hi jomjol,

please find attached my "critical" digits.

Thank you!

[watermeter_6_8_9.zip](https://github.com/jomjol/AI-on-the-edge-device/files/6703682/watermeter_6_8_9.zip)

**Comment by tunip** [comment]
Hi,

here are my 3:

![3_digit3_20210624-085437](https://user-images.githubusercontent.com/11404472/123220139-f0e73300-d4cd-11eb-9c87-fc69ebf727d8.jpg)

![3_digit3_20210624-085928](https://user-images.githubusercontent.com/11404472/123220156-f47aba00-d4cd-11eb-8661-09ecce12fe37.jpg)

**Comment by jomjol** [comment]
The numbers (both @tunip and @Stff0r) are used in the newest training set. I recommend to use the following tflite file:
https://github.com/jomjol/neural-network-digital-counter-readout/blob/master/dig1020s2q.tflite
