### ISSUE TITLE
Cutout numbers have lines in them, ESP seems to crash afterwards

### ISSUE THREAD

**Issue by TheGreyDiamond** [jomjol/AI-on-the-edge-device#252]
Hi,
I've been trying to get it to work for a few weeks now. The whole thing worked at some point with some old version of the firmware. I'm now on 7.1.2. After the photo is taken and the alignment marks have been found the cutting out of the digital numbers fails. The numbers have blue lines in them. The ESP seems to crash after the small numbers are cut out. I have a powerful power supply and a capacitor in my power supply. The cutouts also seemingly random shift around. I also have sufficient memory on the ESP. Here are a few images of the problem:
![Picture of the problem 1](https://cdn.thegreydiamond.de/img/2021/06/21/2021-06-21_17-39-07-47ce413c-b040-4150-93bf-06697a1de7d5.png)
![Picture of the problem 2](https://cdn.thegreydiamond.de/img/2021/06/21/2021-06-21_17-44-01-ea535acc-7b9f-4af3-b408-e14d616fdbf4.png)
![Picture of the problem 3](https://cdn.thegreydiamond.de/img/2021/06/21/2021-06-21_17-45-25-8db3afe7-f74b-4a05-974a-dd30ae330eeb.png)
![Picture of the problem 4](https://cdn.thegreydiamond.de/img/2021/06/21/2021-06-21_17-46-59-5be1cd41-bd39-4c58-8de7-330a102d5994.png)

What is wrong here?

**Comment by jomjol** [comment]
This problem has been reported somewhere as well, but I did not find the root cause. Did you try to fully reset the firmware (erease before) and do formating the SD card - you can make a copy of the content and just copy it back again.

**Comment by TheGreyDiamond** [comment]
After boot I still had this issue:
![](https://cdn.thegreydiamond.de/img/2021/06/23/2021-06-23_14-19-34-4265eeb3-fc2e-494b-8dc1-714077068368.png)

However, after waiting a bit, it seems to work, well better...
![](https://cdn.thegreydiamond.de/img/2021/06/23/2021-06-23_14-20-15-1554bd0a-55bf-46df-850d-ac34cc8e5bc7.png)
![](https://cdn.thegreydiamond.de/img/2021/06/23/2021-06-23_14-21-02-14da6f3b-f479-42ca-9da8-305fc086adde.png)

I guess the rest is just fine-tuning on my side...

**Comment by friedpa** [comment]
I can tell you that you have way too much reflections and additionally the focus of the linse is not OK

**Comment by TheGreyDiamond** [comment]
Huh, okay. At least I don't have lines anymore. I will fix these issues. As my other issues are now fixed, I'll close this issue! Thanks for the support.
