### ISSUE TITLE
Help needed: Some digits are not being detected properly

### ISSUE THREAD

**Issue by TheGreyDiamond** [jomjol/AI-on-the-edge-device#253]
This might be a problem with my setup, but I hope someone can help me nonetheless. This is my current result: 
![Picture of the problem 1](https://cdn.thegreydiamond.de/img/2021/06/24/2021-06-24_09-42-30-b6c485d4-208a-4309-8dd1-e32d6e4dcee7.png)
As you see the `4` got identified as 0. What is wrong with my setup here? It was clearly able to read the first 4. The last `NAN` is fine because the number is turning away. 

Okay after 20ish Minutes it now looks like this:
![Picture of the problem 2](https://cdn.thegreydiamond.de/img/2021/06/24/2021-06-24_10-02-13-23d254c0-5f98-4bd7-9727-ea51f41f63bc.png)
Only the last number is wrong

**Comment by friedpa** [comment]
Nothing wrong I guess, but you have to send jomjol the white on red background digits so that he can train it.
I would recommend that you use the Forum for the postings: 
https://forum.iobroker.net/topic/36622/wasserz%C3%A4hler-version-2-all-in-device/1484?_=1624523498049

**Comment by jomjol** [comment]
White on red is included in the training, but a neural network never works perfect. Therefore I can offer to use your specific numbers in the next training session as friedpa mentioned

**Comment by TheGreyDiamond** [comment]
Great, I've turned on logging yesterday, so I should have all the numbers soon!

**Comment by jomjol** [comment]
Please reopen in case of new input
