### ISSUE TITLE
Fehlerhaftes Model file abfangen

### ISSUE THREAD

**Issue by Snago636** [jomjol/AI-on-the-edge-device#254]
Hallo,
da mein Wasserzähler nicht mehr so funktioniert hat wie er sollte hab ich ihn einfach mal neu geflasht. Dachte mir clever und faul wie ich bin spiel ich einfach die alte Config ein und schön ist. 
Leider hat das nicht so ganz funktioniert und er hat sich im Minutentakt neu gestartet. Nach langen probieren (anderer ESP, andere SD) musste ich feststellen das der Fehler einfach nur daran lag das die eingetragene tflite Datei nicht mehr vorhanden war da diese ja ein update erhalten hatte und einen neuen namen hat (was ja auch sinnvoll ist falls man eine ander Version nutzen möchte).

Kann man das nicht vielleicht irgendwie abfangen bevor er abstürzt. So Quasi als Fehlermeldung im Log oder im Frontend (falls mal jemand genauso clever ist wie ich oder einfach nur die Datei gelöscht hat oder so)?

gruß Snago

**Comment by jomjol** [comment]
Hi Snago,
kann man abfangen. Problem ist nur, wo fange an, Fehler abzufangen und wo höre ich auf. Ein falsch definiertes ROI, Parameter mit unsinnigen Zeichen, ... . All das führt zu einem Absturz. Sauberes Fehlerhandling würde 
a) einiges an zusätlichen Code benötigen (Platz auf dem ESP32
b) erheblichen Aufwand in der Implementierung mit sich bringen

Daher ist das in dieser Freeware nicht umgesetzt. Support ist aber gerne willkommen. Ich nehme übernehme Änderungen/Ergänzungen sehr gerne in meinen Code.

Ich schließe den Issue wieder, damit die Idee aber nicht verloren geht, steht sie in meinem Langzeitspeicher:
![grafik](https://user-images.githubusercontent.com/30766535/123415260-49ddc680-d5b5-11eb-8d9a-1e695434b675.png)

Update mit nächster Version
