### ISSUE TITLE
replace if-else statement with map

### ISSUE THREAD

**Issue by SikaiGGMU** [jomjol/AI-on-the-edge-device#2548]
### Issue

I have no experience in programming c++ in an MCU.

I just wonder if we can replace the long if-else statement in function info_get_handler (server_main.cpp)  with something like a std::map<std::string, std::function<...>>. 
Or transform std::string _task into a hash, and replace the long if-else statement with a switch-case statement.

**Comment by caco3** [comment]
We are always happy about contributions.
So fell free to fork and create Pull Request.

Most of us have limited C++ experience, so for sure there are many easy improvements possible.

**Comment by jomjol** [comment]
As @caco3, just make a pull request and support us :-).

Untill then I will close this issue.
