### ISSUE TITLE
[MQTT] Add json doc

### ISSUE THREAD

**Issue by JanHBade** [jomjol/AI-on-the-edge-device#255]
Hello,

is is possible to pub a json doc under the "root" mqtt path?
(or a specific mqtt json path)

maybe i can help when a found the line where the new values goes into the mqtt lib... :)

**Comment by jomjol** [comment]
Hi, in principle possible.
You can find the routinge, that runs when a MQTT is send here: https://github.com/jomjol/AI-on-the-edge-device/blob/master/code/components/jomjol_flowcontroll/ClassFlowMQTT.cpp

The function is called `bool ClassFlowMQTT::doFlow(string zwtime)` - starting in line 124

I'm not going to follow it for the moment. If you make a branch, I can try to incorporate it later.

**Comment by JanHBade** [comment]
I make a branch, that works...

https://github.com/JanHBade/AiOnTheEdge/commit/dbabdc35dd48c7f9c358ef43e137b4813f349682

**Comment by jomjol** [comment]
Thanks a lot - it is implemented in the newest rolling, with one change: there the topics are predefined.

ATTENTION: the newest rolling is not downwards compatible
