### ISSUE TITLE
Anmeldung am UI per Benutzername + Passwort

### ISSUE THREAD

**Issue by Ingo-Knito** [jomjol/AI-on-the-edge-device#2559]
### The Feature

Aktuell kommt man ohne Anmeldung an die gesamte Oberfläche, wie auch die Konfiguration - und kann diese ändern.

Falls jemand (der Nachwuchs bspw.) die IP-Adresse des Devices kennt, kann dieser viel Unsinn treiben.
Die Absicherung, dass jeder der im LAN/WLAN angemeldet und wohl vertrauenswürdig ist, reicht manchmal nicht.

Um den Aufwand möglichst klein zu halten, wäre eine Absicherung der gesamten Oberfläche mit Benutzername + Passwort sicher sinnvoll.

**Comment by jomjol** [comment]
Das ist für die kostenlose und frei verfügbare Version nicht geplant. Jegliche sicherheitsrelevanten Aspekte bedürfen recht aufwendiger Pflege und Prüfung, um wirkliche Sicherheit zu gewährleisten und dass ist in diesem Rahmen nicht stemmbar.

Daher die Entscheidung lieber gar keine Absicherung, um klare Verhältnisse zu haben.
