### ISSUE TITLE
Timestamp in MQTT message `watermeter/main/json` is wrong (or the documentation is wrong)

### ISSUE THREAD

**Issue by baxerus** [jomjol/AI-on-the-edge-device#2560]
### The Problem

The documentation states that timestamp is the "Timestamp of the actual message" and also that the message under the topic `watermeter/main/json` "... is a JSON formatted object containing the following values: value, raw, pre, error, rate, timestamp".

From this I would understand that the `timestamp` in the `watermeter/main/json` message is the timestamp of **this** message. In very case (there are no special conditions mentioned in the documentation).  
**But** the timestamp in the message is acutally the timestamp of the last detection round **without** error.

In general this also *could* be okay (even if IMHO the "Timestamp of the actual message" makes most sense here), but then the documentation should reflect and describe the special condition, that the timestamp is only updated for successful detection rounds.

So either this is a bug or the documentation should be extended 👍 

### Version

v15.2.4 (Commit: cbd14a2)

### Logfile

```shell
-
```

**Comment by baxerus** [comment]
In the meantime I'm unsure if my observations are right.
I improved my setup (yesterday night) and will do more testing. And maybe close the issue with a mea culpa. Or will have more info to add to this

**Comment by baxerus** [comment]
The issue is really existing and it is also happening with `Release: v15.3.0 (Commit: 3fbff0a)`.

Since I assume that maybe not all code path are the same, the error message that is outputted is `Neg. Rate - Read:  - Raw: ...` type.

**Comment by baxerus** [comment]
A screenshot from `Node-RED`.
<img width="443" alt="image" src="https://github.com/jomjol/AI-on-the-edge-device/assets/1628976/97c77622-c123-449c-a8af-0d47a22ad651">
The two times are the same timezone.

The time at the top is when the message arrived at in `Node-RED`. Since the packet is send after the detection round is done this of course is normally around 40-60sec after the `timestamp` from the message (as this is the timestamp the picture was taken, isn't it?), but in the image the time is off by now more than two hours.

Also the same `timestamp` is repeated in every message received from the `AI-on-the-edge-device` device (also since two hours now) and will only change the moment there is no error anymore (in my case most likely when I use some more water 😉)

**Comment by Slider0007** [comment]
Your investigation is correct, the actual logic only provides a new timestamp as long as 'no error' was detected. The provided timestamp is actually the timestamp of previous value (pre) and this only gets updated in case of 'no error'.

I've updated to documention. Thanks for reporting.

**Comment by baxerus** [comment]
Cool 👍 

@Slider0007
One clarification for me, if there is a valid reading (so in `error` of the JSON is nothing aka. an empty string), then the timestamp is from this actual `value` (of the JSON), isn't it?
That's how I use the JSON message, if error is empty than it is a valid value.
I'm pretty sure it is like this, but only as clarification.

**Comment by Slider0007** [comment]
Yes, that's correct.
In case of no error (error = 'no error') previous value gets updated to actual value, therefore timestamp is the same for both values --> timestamp is matching actual value.

**Comment by baxerus** [comment]
Super 👍 
And thank you for the clarification!
