### ISSUE TITLE
NTP option

### ISSUE THREAD

**Issue by trantoriana** [jomjol/AI-on-the-edge-device#257]
Would it be possible to set date and time over a NTP server?
This could be added as custom server in the options, per default some of the more normal NTP servers can be used.

Thanks, Tran

**Comment by friedpa** [comment]
Hi Tran,
you can set NTP Server in the config.ini:
![grafik](https://user-images.githubusercontent.com/42890695/123907228-dd2c4880-d975-11eb-8524-c4ba85bcf763.png)

**Comment by trantoriana** [comment]
ofcourse :-) dis not think of turning on expert mode.

Thanks
