### ISSUE TITLE
HTTPS Support to include it into https secured Homeassistant

### ISSUE THREAD

**Issue by rsch90** [jomjol/AI-on-the-edge-device#2577]
### The Feature

Hi Team,
I was checking if I can upload a certificate somewhere into the Webserver. I was not able to find any spot.
Would it be possible to add the feature of ssl encryption into the Software? 

I would like to include the view on the index.html into my Homeassistant Installation. With only http it will complain about iframes not able to include http source if the Homeassistant is using https.

**Comment by jomjol** [comment]
HTTPS will not be supported in this public free version - see various discussion.

**Comment by MaluNoPeleke** [comment]
Does this also count for sending data to a SSL encrypted InfluxDB server?
