### ISSUE TITLE
[Feature] Pulse input

### ISSUE THREAD

**Issue by cribskip** [jomjol/AI-on-the-edge-device#258]
Hey jomjol,

while getting my setup to perform just right, I thought about the following:
I got a water softener right next to the water meter. The softener has a direct measuring fan-like flow sensor for the unit to know approximately how much water has passed it.

Now it would be cool to set a free pin as a pulse input for the flow sensor so the ESP could gain additional data to further evaluate the OCR data. Maybe with a little error corridor.

What do you think about this?

Best,
cribskip

**Comment by jomjol** [comment]
Hi cribskip,
there are a lot of ideas, what you could do with the external PINs (e.g. controll of external light, switching of valve, impuls input/output, communication to LORA, communication to another ESP, ...). Unfortunately they all need a different configuration and handling and there is not a general or common way to handle them in an easy way.

Therefore I decided not to implement them in the main branch. You could do a subbranch and do it there. I'm open to support there.

Best regards,
  jomjol
