### ISSUE TITLE
[Feature] Dynamic sample rate

### ISSUE THREAD

**Issue by cribskip** [jomjol/AI-on-the-edge-device#259]
Just another thought :-)

It would be good for energy conservation to make the sampling interval dynamic e.g. over mqtt. This way, the meter could be read less often at nighttimes, other intervals on vacation or presence. I for myself, would max out (3 minutes) the sampling when present, less often (e.g. 15 minutes) on vacation/absence and every 60 minutes at nighttimes/sleeping.

The MaxRateValue should perhaps be entered in a per Minute value in order to ease scaling for dynamic readouts.

While a recognition is running, a change to the interval should be honored afterwards.
This should be volatile so it doesn't cause wear on the sd card.

Best,
cribskip

**Comment by jomjol** [comment]
Hi cribskip,
 thanks for the idea. At the moment the MQTT is only a sender and not receiving. This would need some reconfiguration. As the power consuption is very low any way, I'm not sure, if a configuration of the intervall is worth the benefit. At the moment my focus is on a stable dual meter option. Therefore I would not follow this for the time beeing. I will put a remark in the long term idea storage - you will see it soon in the next update here: https://github.com/jomjol/AI-on-the-edge-device/blob/master/FeatureRequest.md

If you would have capacity to support there at the moment, let me know. Than we can discuss the concrecte implemtation and I can incorporate it than later.

Best regards,
  jomjol
