### ISSUE TITLE
Version.txt is missing in 15.3.0 release

### ISSUE THREAD

**Issue by brembygit** [jomjol/AI-on-the-edge-device#2591]
### The Problem

Hi,

Version.txt file is missing on 15.3.0 release, this prevent the web server load.
after I manually created it, it works

### Version

15.3.0

### Logfile

```shell
error 0x00000010
```

**Comment by caco3** [comment]
I am pretty sure you did not set the SD card up as required!
You can not simply copy the content of the GIT repo!

Please follow the instructions! -> https://jomjol.github.io/AI-on-the-edge-device-docs/Installation/#3-sd-card
