### ISSUE TITLE
Support für Chrome & Edge

### ISSUE THREAD

**Issue by michaeljoos72** [jomjol/AI-on-the-edge-device#26]
Hi jomjol

Ich eröffne dieses Issue noch kurz weil ich die Lösung für ""Bad Request - Header Field Too Long" in Chrome gefunden habe (diese Error-Meldung kam noch beim Versuch im File-Explorer ein File zu löschen)

Eine Anpassung in der SDKCONFIG dieser beider Parameter von 512 auf 1024 hat bei mir geholfen:

```
HTTP Server

CONFIG_HTTPD_MAX_REQ_HDR_LEN=1024
CONFIG_HTTPD_MAX_URI_LEN=1024
```

Mit dieser Einstellung funktioniert alles in Chrome & Edge und mir ist bis jetzt auch funktionell nichts aufgefallen.

Firefox, Edge, Chrome funktionieren und wir könnten somit auch das hier entfernen:

_Known Issues
Parts of the web page only works correctly in Firefox and Chrome! With Edge not all parts (especially the configuration) are not full functional._

**Comment by jomjol** [comment]
Super, dass du das gefunden hast. In der heutigen Version schon korrigiert. Ich mache den Commit gleich wieder zu.
