### ISSUE TITLE
Build instructions wrong?

### ISSUE THREAD

**Issue by JanHBade** [jomjol/AI-on-the-edge-device#260]
in VS code, open the AI-on-the-edge-device/code

    from terminal: cd AI-on-the-edge-device/code && code .

open a pio terminal (click on the terminal sign in the bottom menu bar)
make sure you are in the code directory
To build, type pio build

    the build artifacts are stored in code/.pio/build/esp32cam/

the code command are not there (anymore)?
-> Rightclick on the PlatformIo.ini works

pio build is no more, pio run works...

**Comment by jomjol** [comment]
Thanks for the hint. It will be updated in the next version.
