### ISSUE TITLE
Wasseruhr ESP32-CAM Bootprobleme mit SD Karte

### ISSUE THREAD

**Issue by TimFins** [jomjol/AI-on-the-edge-device#261]
Hallo zusammen,  

ich wollte meine Wasseruhr digitalisieren, wie in der Zeitschrift beschrieben. Ich habe mich komplett an die Anleitung gehalten und komme leider ab dem Punkt SD-Karte einführen nicht weiter. Ich habe wie beschrieben die SD-Karte mit den benötigten Daten gefüttert und in das ESP32 Modul gesteckt. Leider lässt sich das Gerät mit der Karte nun nicht starten. Wenn ich die SD-Karte wieder rausnehme startet das Gerät ganz normal (LED blinkt).  Bei der SD-Karte haben wir zwei verschiedene mit 1GB und 16GB Speicher ausprobiert. Da das ESP32-Modul in doppelter Ausführung geliefert wurde, habe ich auch hier beide getestet mit dem selben Ergebnis.  Die vorherigen Schritte, wie "erase_flash" und "Write_flash" habe ich im "Bootloader-Modus" durchgeführt (Brücke von GPIO0 zu GND). Diesen habe ich dann zum einführen der SD-Karte verlassen und habe nur den Strom mit dem ESP32 verbunden.
Leider bin ich etwas ratlos und bitte dringend um Hilfe!

Liebe Grüße und danke im Voraus.

**Comment by jomjol** [comment]
Hallo,
kannst du mal mit den Start mit der seriellen Schnittstelle mitloggen und die Logdatei hier posten?

Ich vermute ein Problem mit der SD-Karte. Es gibt Karten, die einfach nicht funktionieren.

Beste Grüße,
  jomjol
