### ISSUE TITLE
Device MAC

### ISSUE THREAD

**Issue by gomito1** [jomjol/AI-on-the-edge-device#262]
Good afternoon Jomjol, congratulations on the project, it is incredible. I ask you does the device have a MAC or you could program a MAC to manage devices and know which device is sending the data regardless of the IP that is assigned to the device or the fixed IP that is generated.
I say it would be nice to know the MAC to make changes and manage if there is more than a single device in the same network and to consult the IP if it is not possible to generate a static one.
thanks for your time.

**Comment by jomjol** [comment]
Yes, the device has a MAC address, but currently I'm following a different aproach. You can identify the device by a hostname or by different topic names in the MQTT. Why is this not sufficient?

**Comment by gomito1** [comment]
Friend If I want to access the device's Mac what part of the code I can add it, I bother you with that if you know.

**Comment by gomito1** [comment]
Hostmane also sends it by MQTT, or as you do the management of the devices with that data

**Comment by jomjol** [comment]
You can give each device a unique name in the settings:
![grafik](https://user-images.githubusercontent.com/30766535/125394163-8a0cb980-e3a9-11eb-8cc6-fb60a545df89.png)

And you can give each number a unique name:
![grafik](https://user-images.githubusercontent.com/30766535/125394232-a7418800-e3a9-11eb-999f-393d67db9a7b.png)

With this I can identify my devices very easy in the MQTT server:
![grafik](https://user-images.githubusercontent.com/30766535/125394396-eb348d00-e3a9-11eb-9d9f-08d65c55cd36.png)


Hope, that helps!

**Comment by gomito1** [comment]
In the repository with parts the Main Topic is not found.  or how you can configure more topic for example to be able to send the Mac and also the IP address when it is dynamic to constantly give what the current address is.

**Comment by jomjol** [comment]
The communication of the MQTT adapter is done in https://github.com/jomjol/AI-on-the-edge-device/blob/master/code/components/jomjol_flowcontroll/ClassFlowMQTT.cpp

and there in the function `bool ClassFlowMQTT::doFlow(string zwtime)`

**Comment by gomito1** [comment]
Do you know where I can find a basic example or where they can explain an example of esp32cam with OCR for the detection of numbers from ESP as your project but without so many things.  I would like to understand a little more about your project, it is fantastic.

**Comment by jomjol** [comment]
I'm not aware of a comparable project. There are some tutorials on tflite on ESP32 in the TensorFlow Library from Google.
