### ISSUE TITLE
Probleme bei Erkennung Analog Meter

### ISSUE THREAD

**Issue by waterfall0815** [jomjol/AI-on-the-edge-device#264]
Hallo zusammen,

vielen Dank für die Entwicklung der Wasseruhr. Das Prinzip finde ich sehr gut.

Leider habe ich Probleme bei der Erkennung einer der Analog Meter (siehe Bild).

![AnalogMeter](https://user-images.githubusercontent.com/87330516/125327325-45e6ce00-e343-11eb-9f54-41ae8169c20f.PNG)

Die Zuordnung der Position ist korrekt aber der Bildausschnitt, welcher in die Auswertung geht scheint nicht richtig zu sein. Hat jemand eine Idee?

Vielen Dank.

**Comment by jomjol** [comment]
Ja, dein ROI ist größer wie das Bild (untere Kante nicht mehr im Bild - sieht man auch am ROI. Dann funktioniert das Ausschneiden nicht und es ist ein Random Bild geladen. ROI etwas kleiner machen, oder Bild so drehen, dass alles rein passt.
