### ISSUE TITLE
Regularly resend HA discovery Data

### ISSUE THREAD

**Issue by SciLor** [jomjol/AI-on-the-edge-device#2641]
### The Feature

If I am restarting my server, including HASS and my MQTT Server,  the discovery information is gone and HASS doesn't find the device anymore.

So the discovery information should be resend once a while to mitigate this problem.

**Comment by caco3** [comment]
Restarting a server is not something that happens during normal operation. Also, when you enable retention, this will not be a problem.
Additionally, the UI has a button to resend those topics.

We on purpose decided no to resend those topics periodically to reduce the load on the ESP.

**Comment by SciLor** [comment]
Home Assistant and the mqtt servers restart regularly for updates. Is there any mqtt command / API endpoint to automate this process?

**Comment by caco3** [comment]
Its missing in the docs (I will add it to https://jomjol.github.io/AI-on-the-edge-device-docs/REST-API/). But just call `http://<IP>/mqtt_publish_discovery`

**Comment by Anto79-ops** [comment]
hi,

Could you pelase post the action you use for this command?

I'd like to setup this up so it does this a few minutes after HA has restarted but im not sure how to setup the command? I tried this, but it do not work:

```
action: mqtt.publish
data:
  topic: http://192.168.1.100/mqtt_publish_discovery
```

thank you

**Comment by caco3** [comment]
You have to use a REST call, not a MQTT call!
Eg. in `configuration.yaml`:
```yaml
rest_command:
  restart_watermeter:
    url: http://192.168.1.100/mqtt_publish_discovery
```

**Comment by Anto79-ops** [comment]
oh! thank you!

would it be useful, as a feature request, if this can be made a button in the integration? I guess I could do that myself, but trying to assing it to the watermeter device might be tricky

**Comment by Anto79-ops** [comment]
oh thank you!
