### ISSUE TITLE
ESP not working properly after a few days - Not able to save configuration

### ISSUE THREAD

**Issue by tucka** [jomjol/AI-on-the-edge-device#265]
Hi,

I got a strange behavior of my ESP. After a few days the system stoped working. I can still access the website of the ESP but no image of the cam is displayed and no new values are recognized. 

I'm also not able to save any configuration. All fields are "greyed out" (see screenshot).

The only solution is to re-install the html content of the SD-Card and re-configure the system. There is 7GB of free space on the SD Card, so memory should not be an issue.

Any idea?
Thanks!!
Tucka

![image](https://user-images.githubusercontent.com/9028857/125354271-e816ae00-e363-11eb-9826-b6aee8d06bca.png)

**Comment by jomjol** [comment]
This behavious is reported first time. But the most probable error is a corrupted SD card. The `config.ini` is not manipulated on the ESP32 directly, but is always loaded in the web browser, updated and send back.

Empty inputs shows, that the html page reads an empty `config.ini`. Experience is, that this is kind of problem is coming from SD card problems. You can reduce the read/write load, if you turn of the logging of the images.

**Comment by tucka** [comment]
Yes, after some investigation it seems that the config.ini got somehow deleted (it doesn't exist anymore).

I checked 2 different SD Cards and it happened twice. So I'll try to limit the logging as you recommended.

Thanks!
