### ISSUE TITLE
MQTT Single line transmit

### ISSUE THREAD

**Issue by sebastianheyn** [jomjol/AI-on-the-edge-device#2652]
### The Feature

on my previous version (10.xx??) the mqtt output would send single line json strings. All other smart home devices also send their data like that. Processing of the mqtt on the server is done line by line. 

If ai on the edge sends data like this 
watermeter/main/json   {
    "value": "197915",
    "raw": "197915",
    "pre": "197915",
    "error": "no error",
    "rate": "0.000000",
    "timestamp": "2023-10-13T07:13:18+0200"
  }

the server only sees 

 ------------------- 
watermeter/main/json   {
 --------------------

it would be great if you could add an option to send the data like this 

watermeter/main/json   { "value": "197915", "raw": "197915", "pre": "197915", "error": "no error", "rate": "0.000000", "timestamp": "2023-10-13T07:13:18+0200" }

in a single line. 

Thanks anyhow for the great project

**Comment by caco3** [comment]
The correct way is to make sure the server is able to handle the JSON spe.
Newlines are allowed and help for debugging!
