### ISSUE TITLE
Infinite boot

### ISSUE THREAD

**Issue by aamiel1** [jomjol/AI-on-the-edge-device#266]
Hi,

After installing both the firmware and the sd-card (I tested several types and sizes of cd-card) the boot constantly crashes.
Thanks,

Here is the boot log:

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:4
load:0x3fff0034,len:7248
ho 0 tail 12 room 4
load:0x40078000,len:13856
load:0x40080400,len:4052
entry 0x40080688
[0;32mI (31) boot: ESP-IDF 3.40100.200827 2nd stage bootloader[0m
[0;32mI (31) boot: compile time 19:48:46[0m
[0;32mI (31) boot: chip revision: 1[0m
[0;32mI (34) boot_comm: chip revision: 1, min. bootloader chip revision: 0[0m
[0;32mI (41) boot.esp32: SPI Speed      : 40MHz[0m
[0;32mI (46) boot.esp32: SPI Mode       : DIO[0m
[0;32mI (51) boot.esp32: SPI Flash Size : 4MB[0m
[0;32mI (55) boot: Enabling RNG early entropy source...[0m
[0;32mI (61) boot: Partition Table:[0m
[0;32mI (64) boot: ## Label            Usage          Type ST Offset   Length[0m
[0;32mI (71) boot:  0 nvs              WiFi data        01 02 00009000 00004000[0m
[0;32mI (79) boot:  1 otadata          OTA data         01 00 0000d000 00002000[0m
[0;32mI (86) boot:  2 phy_init         RF data          01 01 0000f000 00001000[0m
[0;32mI (94) boot:  3 ota_0            OTA app          00 10 00010000 001db000[0m
[0;32mI (101) boot:  4 ota_1            OTA app          00 11 001f0000 001db000[0m
[0;32mI (109) boot: End of partition table[0m
[0;32mI (113) boot_comm: chip revision: 1, min. application chip revision: 0[0m
[0;32mI (120) esp_image: segment 0: paddr=0x00010020 vaddr=0x3f400020 size=0x488a4 (297124) map[0m
[0;32mI (258) esp_image: segment 1: paddr=0x000588cc vaddr=0x3ffb0000 size=0x05038 ( 20536) load[0m
[0;32mI (268) esp_image: segment 2: paddr=0x0005d90c vaddr=0x40080000 size=0x00404 (  1028) load[0m
[0;32mI (269) esp_image: segment 3: paddr=0x0005dd18 vaddr=0x40080404 size=0x02300 (  8960) load[0m
[0;32mI (280) esp_image: segment 4: paddr=0x00060020 vaddr=0x400d0020 size=0x145704 (1332996) map[0m
[0;32mI (862) esp_image: segment 5: paddr=0x001a572c vaddr=0x40082704 size=0x1a204 (107012) load[0m
[0;32mI (930) boot: Loaded app from partition at offset 0x10000[0m
[0;32mI (931) boot: Disabling RNG early entropy source...[0m
[0;32mI (931) psram: This chip is ESP32-D0WD[0m
[0;32mI (936) spiram: Found 64MBit SPI RAM device[0m
[0;32mI (940) spiram: SPI RAM mode: flash 40m sram 40m[0m
[0;32mI (945) spiram: PSRAM initialized, cache is in low/high (2-core) mode.[0m
[0;32mI (953) cpu_start: Pro cpu up.[0m
[0;32mI (956) cpu_start: Application information:[0m
[0;32mI (961) cpu_start: Project name:     esp32cam-server-only[0m
[0;32mI (967) cpu_start: App version:      0.0.9.3[0m
[0;32mI (972) cpu_start: Compile time:     Jun 17 2021 19:47:20[0m
[0;32mI (978) cpu_start: ELF file SHA256:  c092874117d250f6...[0m
[0;32mI (984) cpu_start: ESP-IDF:          3.40100.200827[0m
[0;32mI (990) cpu_start: Starting app cpu, entry point is 0x40081ab4[0m
[0;32mI (981) cpu_start: App cpu up.[0m
[0;32mI (1888) spiram: SPI SRAM memory test OK[0m
[0;32mI (1888) heap_init: Initializing. RAM available for dynamic allocation:[0m
[0;32mI (1888) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM[0m
[0;32mI (1894) heap_init: At 3FFC2988 len 0001D678 (117 KiB): DRAM[0m
[0;32mI (1901) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM[0m
[0;32mI (1907) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM[0m
[0;32mI (1914) heap_init: At 4009C908 len 000036F8 (13 KiB): IRAM[0m
[0;32mI (1920) cpu_start: Pro cpu start user code[0m
[0;32mI (1925) spiram: Adding pool of 4096K of external SPI memory to heap allocator[0m
[0;32mI (1950) spi_flash: detected chip: generic[0m
[0;32mI (1951) spi_flash: flash io: dio[0m
[0;32mI (1951) cpu_start: Starting scheduler on PRO CPU.[0m
[0;32mI (0) cpu_start: Starting scheduler on APP CPU.[0m
[0;32mI (1959) spiram: Reserving pool of 32K of internal memory for DMA/internal allocations[0m
Do Reset Camera
[0;32mI (1969) gpio: GPIO[32]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 [0m
Init Camera
[0;32mI (3979) gpio: GPIO[5]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
[0;32mI (3979) gpio: GPIO[18]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
[0;32mI (3979) gpio: GPIO[19]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
[0;32mI (3989) gpio: GPIO[21]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
[0;32mI (3999) gpio: GPIO[22]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
[0;32mI (4009) gpio: GPIO[23]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
[0;32mI (4019) gpio: GPIO[25]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
[0;32mI (4029) gpio: GPIO[34]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
[0;32mI (4039) gpio: GPIO[35]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
[0;32mI (4049) gpio: GPIO[36]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
[0;32mI (4059) gpio: GPIO[39]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
[0;32mI (4069) sccb: pin_sda 26 pin_scl 27
[0m
[0;32mI (4069) gpio: GPIO[32]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 [0m
[0;31mE (4149) camera: Detected camera not supported.[0m
[0;31mE (4149) camera: Camera probe failed with error 0x20004[0m
[0;31mE (4149) server_part_camera: Camera Init Failed[0m
[0;32mI (4199) server-main: Using SDMMC peripheral[0m
Name: SR64G
Type: SDHC/SDXC
Speed: 20 MHz
Size: 60906MB
[0;32mI (4259) server_ota: Start CheckOTAUpdateCheck ...[0m
Start CheckOTAUpdateCheck ...
[0;32mI (4269) server_ota: SHA-256 for the partition table: : 9d4a2809ae90fb20709a8ca3dd3ac3462e1e73286bcd31b689060c91de06fa3a[0m
[0;32mI (4329) server_ota: SHA-256 for bootloader: : 7f9c6b4ef8e66679c8782c8e72b1401f41e530fe5ada1d260fee66fe2ef28d8f[0m
[0;32mI (5009) server_ota: SHA-256 for current firmware: : 869a699ff035e37e81dc97dc1ef63ba8390f974cff54b35634f57a5c736d8fb4[0m
CheckOTAUpdate Partition: ESP_OK
file loaded

WLan: XXXXXX, XXXXXX
Hostename: mymeter
Fixed IP: 192.168.1.116, Gateway 192.168.1.254, Netmask 255.255.255.0
DNS IP: 8.8.8.8
[0;32mI (5049) wifi station: set IP 192.168.1.116, GW 192.168.1.254, Netmask 255.255.255.0 manual[0m
I (5069) wifi:wifi driver task: 3ffd35a8, prio:23, stack:6656, core=0
[0;32mI (5069) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE[0m
[0;32mI (5079) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE[0m
I (5109) wifi:wifi firmware version: 3ea4c76
I (5109) wifi:config NVS flash: enabled
I (5109) wifi:config nano formating: disabled
I (5109) wifi:Init dynamic tx buffer num: 32
I (5109) wifi:Init data frame dynamic rx buffer num: 32
I (5119) wifi:Init management frame dynamic rx buffer num: 32
I (5119) wifi:Init management short buffer num: 32
I (5129) wifi:Init static tx buffer num: 16
I (5129) wifi:Init static rx buffer size: 1600
I (5139) wifi:Init static rx buffer num: 10
I (5139) wifi:Init dynamic rx buffer num: 32
[0;32mI (5139) wifi station: set DNS manual[0m
[0;32mI (5249) phy: phy_version: 4180, cb3948e, Sep 12 2019, 16:39:13, 0, 0[0m
I (5249) wifi:mode : sta (24:0a:c4:2a:41:9c)
[0;32mI (5249) BLINK: Blinken - start[0m
[0;32mI (5259) wifi station: wifi_init_sta finished.[0m
I (5379) wifi:new:<6,2>, old:<1,0>, ap:<255,255>, sta:<6,2>, prof:1
I (5379) wifi:state: init -> auth (b0)
I (5399) wifi:state: auth -> assoc (0)
I (5419) wifi:state: assoc -> run (10)
I (5439) wifi:connected with XXXXXX, aid = 3, channel 6, 40D, bssid = XXXXXX
I (5439) wifi:security: WPA2-PSK, phy: bgn, rssi: -39
[0;32mI (5449) BLINK: Blinken - done[0m
I (5449) wifi:pm start, type: 1

[0;32mI (5449) esp_netif_handlers: sta ip: 192.168.1.116, mask: 255.255.255.0, gw: 192.168.1.254[0m
[0;32mI (5459) wifi station: got ip:192.168.1.116[0m
[0;32mI (5459) BLINK: Blinken - start[0m
[0;32mI (5459) wifi station: connected to ap SSID:XXXXXX password:XXXXXXX[0m
Autoflow: sleep for : 200ms
I (5469) wifi:AP's beacon interval = 102400 us, DTIM period = 3
[0;32mI (7479) sntp: Time is not set yet. Connecting to WiFi and getting time over NTP.[0m
[0;32mI (7479) sntp: Initializing SNTP[0m
[0;32mI (7479) sntp: Waiting for system time to be set... (1/10)[0m
TimeZone set to CET-1CEST,M3.5.0,M10.5.0/3
Logfile opened: /sdcard/log/message/log_2021-07-13.txt
[0;32mI (9489) sntp: The current date/time in Berlin is: Tue Jul 13 20:58:52 2021[0m
[0;32mI (9499) sntp: The current date/time in Berlin is: 2021-07-13_20:58[0m
timeist 20210713-205852
Logfile opened: /sdcard/log/message/log_2021-07-13.txt
Logfile opened: /sdcard/log/message/log_2021-07-13.txt
Logfile opened: /sdcard/log/message/log_2021-07-13.txt
time 20210713-205852
Autoflow: sleep for : 200ms
[0;32mI (11529) server-main: Starting server on port: '80'[0m
[0;32mI (11529) server-main: Registering URI handlers[0m
[0;32mI (11529) server_tflite: server_part_camera - Registering URI handlers[0m
[0;32mI (11529) server_ota: server_ota - Registering URI handlers[0m
[0;32mI (11539) server_GPIO: server_GPIO - Registering URI handlers[0m
[0;32mI (11549) gpio: GPIO[12]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 [0m
[0;32mI (11559) gpio: GPIO[13]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 [0m
vor reg server main
vor dotautostart
[MakeImage]
Start ReadParameter
;LogImageLocation = /log/source
;LogfileRetentionInDays = 15
WaitBeforeTakingPicture = 5
ImageQuality = 5
ImageSize = VGA
;Brightness = -2
FixedExposure = false

[Alignment]
Guru Meditation Error: Core  0 panic'ed (LoadProhibited). Exception was unhandled.
Core 0 register dump:
PC      : 0x400e63bd  PS      : 0x00060930  A0      : 0x80182098  A1      : 0x3fff7ac0  
A2      : 0x3ffb57bc  A3      : 0x00000005  A4      : 0x00000008  A5      : 0xffffff9c  
A6      : 0x3ffb57bc  A7      : 0x00000000  A8      : 0x800e63bd  A9      : 0x3fff7aa0  
A10     : 0x00000000  A11     : 0xffffff9d  A12     : 0x3ffc3b87  A13     : 0x00000000  
A14     : 0x00000000  A15     : 0xff000000  SAR     : 0x00000010  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x0000005c  LBEG    : 0x4008a13c  LEND    : 0x4008a158  LCOUNT  : 0xffffffff  

ELF file SHA256: c092874117d250f6

Backtrace: 0x400e63ba:0x3fff7ac0 0x40182095:0x3fff7ae0 0x4017ffdd:0x3fff7b80 0x400ecacc:0x3fff7fd0 0x400ecc67:0x3fff8020

Rebooting...

**Comment by friedpa** [comment]
The Problem is:

camera: Detected camera not supported

Looks like the camera is defect.

**Comment by aamiel1** [comment]
Thank you for your quick answer,
I replace the camera and now the boot appears to have continued but it failed at another point...


[System]
Start ReadParameter
TimeZone = CET-1CEST,M3.5.0,M10.5.0/3
TimeZone set to CET-1CEST,M3.5.0,M10.5.0/3
;TimeServer = fritz.box
;hostname = watermeter
SetupMode = true

[Ende]Flashdauer: 5000
Image loaded from memory: 0, 0, 0
Guru Meditation Error: Core  0 panic'ed (LoadProhibited). Exception was unhandled.
Core 0 register dump:
PC      : 0x400e67d5  PS      : 0x00060530  A0      : 0x801819ef  A1      : 0x3fff9e80  
A2      : 0x00000780  A3      : 0x3ffc3b38  A4      : 0x00000280  A5      : 0x00000000  
A6      : 0x00000780  A7      : 0x00000001  A8      : 0x3f82c168  A9      : 0x00000000  
A10     : 0x000001e0  A11     : 0x3f92fc14  A12     : 0x00025800  A13     : 0x00000001  
A14     : 0x3ffc347c  A15     : 0x3fff9da0  SAR     : 0x00000007  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x00000000  LBEG    : 0x4008bc45  LEND    : 0x4008bc55  LCOUNT  : 0xffffffff  

ELF file SHA256: c092874117d250f6

Backtrace: 0x400e67d2:0x3fff9e80 0x401819ec:0x3fff9ef0 0x40181a4d:0x3fff9f30 0x4017f29b:0x3fff9fc0 0x400eccab:0x3fffa040

Rebooting...

**Comment by jomjol** [comment]
Something still not okay with the camera:
`Image loaded from memory: 0, 0, 0`
This tells me, that the picture could not be taken. Normally it should look like:
`Image loaded from memory: 640, 480, 3`

**Comment by aamiel1** [comment]
There seems to be something wrong with the board, 
I also tried a sample code and even then there seems to be a problem. 
Thanks for the help.
