### ISSUE TITLE
Button to hide other red Digit Frames for easier setup

### ISSUE THREAD

**Issue by loewi1979** [jomjol/AI-on-the-edge-device#2680]
### The Feature

For easier Setup it would be great, if there is a button on the Screen "Settings => Regions of Interrest => Digital ROI" that you can hide all other digits than the one which is setuped at the moment.
The red frames of all the digits overlap, so it is hard to see the actual confgigured digit-frame. If you could hide the other ones for setting up each digit by itself, and to show all the others for checking them all would be a great option.

**Comment by jurasjo** [comment]
It is a great idea!

**Comment by caco3** [comment]
The selected digit has a brighter red frame, so I am not sure if this really is needed:
![grafik](https://github.com/jomjol/AI-on-the-edge-device/assets/1783586/625f8c4a-c922-4bb2-ae13-7813b3e22bde)

**Comment by jurasjo** [comment]
Unless, your meter is like this one...
![image](https://github.com/jomjol/AI-on-the-edge-device/assets/19259405/e5f26ec6-6f50-4fb1-bd97-c9ad732da11d)

**Comment by caco3** [comment]
I suggest to make the names of the ROIS smaller.

IMO it would be quite some effort to implement this feature without a real need to it.
But we are happy to receive contributions.

**Comment by SybexX** [comment]
If you feel like it, you can try it out.
I only tested it briefly^^

[test.zip](https://github.com/jomjol/AI-on-the-edge-device/files/13856551/test.zip)

**Comment by caco3** [comment]
Could you create a Pull request?
That would be easier to see the changes and to test it.

**Comment by SybexX** [comment]
https://github.com/SybexX/AI-on-the-edge-device/commit/a50378b307f6a30296027cb9d4382845fa4ab3b4
https://github.com/SybexX/AI-on-the-edge-device/commit/eff7fbfb75c65249c09179bdd9d812764ebd7a7a

**Comment by caco3** [comment]
Thanks!
I will modify the UI a bit and invert the text -> "hide other ROIs"

**Comment by SybexX** [comment]
ich würde die Werte von Aec2 = true und FixedExposure = true in der config.ini ändern, dann hat man annähernd die Bildqualität die vor den Änderungen war

**Comment by caco3** [comment]
kannst Du einen PR machen?, wäre cool

**Comment by caco3** [comment]
Bin auch am überlegen, beim ersten start der neuen version ein banner anzuzeigen, dass man die einstellungen überprüft
