### ISSUE TITLE
Bad Requests (HTML 400) in 8.0.0 

### ISSUE THREAD

**Issue by duebbers** [jomjol/AI-on-the-edge-device#269]
After an (OTA) Update to 8.0.0 I can't write the config, or save a new reference image:

![grafik](https://user-images.githubusercontent.com/18099824/125767877-269ecf48-102c-4724-9372-d65ce7cd4075.png)

I can take a new picture, but can' save it.
![grafik](https://user-images.githubusercontent.com/18099824/125768250-011709f1-ec3c-423e-9461-74fad7eda97d.png)

And the Overview-Picture is always black and I don't get any new values - maybe because it can't save new pictures for the image recognition either!?
![grafik](https://user-images.githubusercontent.com/18099824/125768548-e4c44613-bc68-47cb-9641-6257c6ff16c8.png)

**Comment by derandiunddasbo** [comment]
I got similar errors when trying to upload already existing files thru the file system tool. Apparently this error is only triggered sometimes, not always. Currently for example I can upload already existing files just fine without any errors.

A quick workaround:

I assume the config save is using the same function to upload an updated config.ini.

Thus, you may open the file server (preferably in a new tab), copy & paste the current contents of /config/config.ini to somewhere else (as a backup, just in case) and delete the file from the sd card. Now you should be able to save the configuration from the config tab.

**Comment by duebbers** [comment]
Yes, I thought of that, but you can't delete the config.ini with the file system tool.
And when I delete the reference.jpg - this you can do - it will be written anew when I click "update reference image", but I still get the 400-Error-message.

But my main problem is that the normal image recognition completely stopped working. The overview-image or the "aligned image" under the Recognition-tab are always just black and the meter cutouts just contains noise (I think because it cranks the gain/contrast up):
![grafik](https://user-images.githubusercontent.com/18099824/125808958-a5b298cd-3bf0-4eb9-9bb6-7f6df12b8f90.png)

Even the log/source/ folder doesn't contain any new images since the update

**Comment by duebbers** [comment]
Ok, it looks like it was a problem with the update or the config-conversion after the update.
I flashed the ESP again, which hasn't done anything. After that, I erased the SD card and reconfigured everything - and now it works again.
Since this seems to be a singular event, I close the issue

**Comment by jomjol** [comment]
Thanks for doing so. It might have been, that the config.ini file was somehow corrupted and the deletion did not work. I had this error once and a reboot helped. The SD card is very sensitive, sometimes it needs a fresh formatting :-(
But once it is up and running it is stable.

**Comment by domborovicova** [comment]
I'm having the same issue after OTA update of the latest version 8.0.0.

**Comment by jomjol** [comment]
@domborovicova  Sometimes the transfer from an old version has a problem. Please try to reset the SD card (copy old data, format, reload).

**Comment by derandiunddasbo** [comment]
Regarding deleting config.ini, or any other file in that regard, from the file system tool: This should be possible. I've done it several times, amongst other things to mitigate this very error. If  the file system tool doesn't let you delete any file, it's most likely because there's something wrong with the file system or the SD card itself. In this case it should be verified/repaired/rewritten from another computer.

**Comment by duebbers** [comment]
Thanks for the clarification - I misunderstood and thought it was just a suggestion. It didn't work in my case. Maybe there was something wrong with the file system or the file itself. I could delete other files with the file system tool but just not the config.ini, so I assumed it was kind of protected to avoid some unconfigured state. In the end I could delete it (and everything else) via a SD card reader on my PC. After rewriting the whole SD-folder and reconfiguring everything it works fine now.
