### ISSUE TITLE
purpose of file "html.zip" in the directory called "firmware"

### ISSUE THREAD

**Issue by uherting** [jomjol/AI-on-the-edge-device#270]
Does the file html.zip in the firmware directory have any purpose?  ( https://github.com/jomjol/AI-on-the-edge-device/tree/master/firmware )
I could not find any hint in the wiki so far.
TIA for your help!

**Comment by jomjol** [comment]
The html.zip contains the content of `/sdcard/html` and is used in the OTA:

![grafik](https://user-images.githubusercontent.com/30766535/125934821-3a127fdb-fde6-4e8f-a755-dc6e24c29618.png)

You should always update the firmware and the html content together, as they are depending on each other.
