### ISSUE TITLE
Nachkommastelle des letzten erkannten Digits als 2. Nachkommastelle

### ISSUE THREAD

**Issue by hackman6** [jomjol/AI-on-the-edge-device#2700]
### The Feature

Hallo,
es wäre doch sinnvoll, wenn die Nachkommastelle der erkannten letzten Position (klappt übrigens perfekt), z.B. eines Stromzählers wie der unten, als zweite Nachkommastelle ausgegeben würde.
Die Analyse des Zählerstandes ergibt:
2.0   5.0   5.0   0.9   0.0   3.5  und führt zu 25510,3. Ich fände es toll, wenn daraus 25510,35 würde.
Gerade im Zusammenhang mit Solaranlagen würde das einen echten Mehrwert (z.B. Nulleinspeisung) bringen.
Man könnte das ja gerne mit einem Häkchen in den Settings optional machen.

![alg_roi](https://github.com/jomjol/AI-on-the-edge-device/assets/31844748/87346db3-619a-494b-bb25-37d470cb10d8)

Vielen Dank für's darüber Nachdenken :-)

**Comment by jomjol** [comment]
Das geht bereits. Siehe Doku: https://jomjol.github.io/AI-on-the-edge-device-docs/Parameters/#parameter-numberextendedresolution

**Comment by hackman6** [comment]
Oh Gott, ist das peinlich...Danke.Am 16.11.2023 17:22 schrieb jomjol ***@***.***>:
Das geht bereits. Siehe Doku: https://jomjol.github.io/AI-on-the-edge-device-docs/Parameters/#parameter-numberextendedresolution
