### ISSUE TITLE
Add support for external pulse based meter over GPIO

### ISSUE THREAD

**Issue by jakobs** [jomjol/AI-on-the-edge-device#2706]
### The Feature

I have a gas meter next to my water meter, that has a magnet when the last digit rolls over. A simple reed contact is enough to provide a pulse for reading. The GPIO support would allow me to publish the information over an MQTT and I could to the counting at my home assistant instance. However, I would feel more comfortable if the pulse counting was actually done on the device - just to make sure not pulses are missed, e.g. when I restart my home assistant.
I guess this could be done similar to how the SmartLed driver can be used on the GPIO.

Features could be:
- hold a pulse count
- Use configured interrupt (rising, falling, high, low) to increase count
- (optional) Store count on sd after increase, and load count from sd on boot
- publish count over mqtt

**Comment by wg25** [comment]
Why not using an additional device with AI-on-the-edge to read the gasmeter?

**Comment by jakobs** [comment]
The reed contact switch on the gas meter is cheaper, smaller, easier to setup and more reliable.

**Comment by caco3** [comment]
Sorry, but this is not really in the scope of this project.
But it looks like an easy project to implemented with eg. arduino.
You might also be able to use https://github.com/letscontrolit/ESPEasy and do it without any programming!

**Comment by jakobs** [comment]
Thanks for the suggestions. I think I will still try to integrate it into the esp32 as it would already provide the MQTT bridge and Wifi and I just have to add a cable with the switch.

**Comment by jakobs** [comment]
I have this mostly running using the GPIO module and a modification for debouncing. Also found issue #1804, which seems to be aiming in the same direction.
