### ISSUE TITLE
Einsatz ohne SD-Karte möglich?

### ISSUE THREAD

**Issue by NeuerUser** [jomjol/AI-on-the-edge-device#271]
Ich habe eine M5Stack TimerCameraX. Scheint so ziemlich alles zu haben, was man für dieses spannende Projekt braucht, aber leider keine SD-Karte.

Kann man das auch anders lösen, oder braucht es die SD-Karte unbedingt?

**Comment by jomjol** [comment]
Die Option über die SD-Karte gibt viele Freiheitsgrade. Z.B. große CNN-Netze (tflite-Files) und gleichzeitig VGA-Bilder und http-Server. Ich habe einige kommerzielle Anwendungen , die rein auf dem ESP32, ohne SD-Karte laufen, aber da musst du einige Kompromisse eingehen, die du als DIY-Projekt für jedermann nicht zumuten kannst.
