### ISSUE TITLE
The version 15.3.0 does not work as a new installation 

### ISSUE THREAD

**Issue by martin8310** [jomjol/AI-on-the-edge-device#2719]
### The Problem

The version 15.3.0 does not work as a new installation. Error 0x10
14.0.3 works fine. 

Hardware: ESP32-CAM-CH340

### Version

14.0.3

### Logfile

```shell
0x00000010 SD folder or file presence check failed
```

**Comment by caco3** [comment]
What is the content of sour SD-card? Did you set it up beforehand?

**Comment by contentpirate** [comment]
Same problem here

Tried to use different SD cards, different ESP32. I used the web installer, copied all the files to the SD card including changing the wifi.ini file. It didn't work, so I copied the config.ini and the wlan.ini manually to the SD card again. No success.

`ets Jul 29 2019 12:21:46

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:7664
load:0x40078000,len:15360
load:0x40080400,len:3744
entry 0x4008067c
I (27) boot: ESP-IDF 4.3.2 2nd stage bootloader
I (27) boot: compile time 20:02:47
I (27) boot: chip revision: 3
I (30) boot_comm: chip revision: 3, min. bootloader chip revision: 0
I (37) boot.esp32: SPI Speed      : 40MHz
I (42) boot.esp32: SPI Mode       : DIO
I (46) boot.esp32: SPI Flash Size : 4MB
I (51) boot: Enabling RNG early entropy source...
I (56) boot: Partition Table:
I (60) boot: ## Label            Usage          Type ST Offset   Length
I (67) boot:  0 nvs              WiFi data        01 02 00009000 00004000
I (75) boot:  1 otadata          OTA data         01 00 0000d000 00002000
I (82) boot:  2 phy_init         RF data          01 01 0000f000 00001000
I (89) boot:  3 ota_0            OTA app          00 10 00010000 001db000
I (97) boot:  4 ota_1            OTA app          00 11 001f0000 001db000
I (104) boot: End of partition table
I (109) boot: No factory image, trying OTA 0
I (114) boot_comm: chip revision: 3, min. application chip revision: 0
I (121) esp_image: segment 0: paddr=00010020 vaddr=3f400020 size=46fbch (290748) map
I (241) esp_image: segment 1: paddr=00056fe4 vaddr=3ffb0000 size=03ce0h ( 15584) load
I (247) esp_image: segment 2: paddr=0005accc vaddr=40080000 size=0534ch ( 21324) load
I (257) esp_image: segment 3: paddr=00060020 vaddr=400d0020 size=1575fch (1406460) map
I (795) esp_image: segment 4: paddr=001b7624 vaddr=4008534c size=15208h ( 86536) load
I (846) boot: Loaded app from partition at offset 0x10000
I (891) boot: Set actual ota_seq=1 in otadata[0]
I (891) boot: Disabling RNG early entropy source...
I (902) quad_psram: This chip is ESP32-D0WD
I (902) esp_psram: Found 8MB PSRAM device
I (902) esp_psram: Speed: 40MHz
I (902) esp_psram: PSRAM initialized, cache is in low/high (2-core) mode.
W (910) esp_psram: Virtual address not enough for PSRAM, map as much as we can. 4MB is mapped
I (918) cpu_start: Pro cpu up.
I (921) cpu_start: Starting app cpu, entry point is 0x40082e48
I (0) cpu_start: App cpu up.
I (1814) esp_psram: SPI SRAM memory test OK
I (1823) cpu_start: Pro cpu start user code
I (1823) cpu_start: cpu freq: 160000000 Hz
I (1824) cpu_start: Application information:
I (1824) cpu_start: Project name:     AI-on-the-edge
I (1829) cpu_start: App version:      v15.3.0
I (1833) cpu_start: Compile time:     Jul 22 2023 09:43:02
I (1838) cpu_start: ELF file SHA256:  29d38f3fa1a9857c...
I (1843) cpu_start: ESP-IDF:          5.0.2
I (1847) cpu_start: Min chip rev:     v0.0
I (1851) cpu_start: Max chip rev:     v3.99 
I (1855) cpu_start: Chip rev:         v3.1
I (1859) heap_init: Initializing. RAM available for dynamic allocation:
I (1865) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM
I (1870) heap_init: At 3FFBD890 len 00022770 (137 KiB): DRAM
I (1875) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
I (1881) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (1887) heap_init: At 4009A554 len 00005AAC (22 KiB): IRAM
I (1892) esp_psram: Adding pool of 4083K of PSRAM memory to heap allocator
I (1900) spi_flash: detected chip: generic
I (1902) spi_flash: flash io: dio
I (1917) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
I (1918) esp_psram: Reserving pool of 40K of internal memory for DMA/internal allocations
I (1918) MAIN: 



================ Start app_main =================
I (8178) MAIN: =================================================
E (8438) LOGFILE: Can't open log file /sdcard/log/message/log_1970-01-01.txt
I (8438) MAIN: ==================== Start ======================
E (8698) LOGFILE: Can't open log file /sdcard/log/message/log_1970-01-01.txt
I (8698) MAIN: =================================================
E (8958) LOGFILE: Can't open log file /sdcard/log/message/log_1970-01-01.txt
I (8958) MAIN: PSRAM size: 8388608 byte (8MB / 64MBit)
E (9218) LOGFILE: Can't open log file /sdcard/log/message/log_1970-01-01.txt
I (9218) MAIN: Total heap: 4377471 byte
E (9478) LOGFILE: Can't open log file /sdcard/log/message/log_1970-01-01.txt
I (9488) gpio: GPIO[32]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 
I (11488) gpio: GPIO[25]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:2 
I (11488) cam_hal: cam init ok
I (11488) sccb: pin_sda 26 pin_scl 27
I (11488) sccb: sccb_i2c_port=1

I (11488) gpio: GPIO[32]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 
I (11528) camera: Detected camera at address=0x30
I (11528) camera: Detected OV2640 camera
I (11528) camera: Camera PID=0x26 VER=0x42 MIDL=0x7f MIDH=0xa2
I (11618) cam_hal: buffer_size: 32768, half_buffer_size: 4096, node_buffer_size: 2048, node_cnt: 16, total_cnt: 15
I (11618) cam_hal: Allocating 61440 Byte frame buffer in PSRAM
I (11618) cam_hal: cam config ok
I (11618) ov2640: Set PLL: clk_2x: 0, clk_div: 0, pclk_auto: 0, pclk_div: 8
I (13698) MAIN: Camera info: PID: 0x26, VER: 0x42, MIDL: 0x7f, MIDH: 0xa2
E (13958) LOGFILE: Can't open log file /sdcard/log/message/log_1970-01-01.txt
I (13958) SDCARD: Basic R/W check started...
E (14218) LOGFILE: Can't open log file /sdcard/log/message/log_1970-01-01.txt
E (14998) SDCARD: Basic R/W check: (E3) Not able to open file to read back
E (15258) LOGFILE: Can't open log file /sdcard/log/message/log_1970-01-01.txt
E (15518) HELPER: New System Status: 0x00000008
E (15778) LOGFILE: Can't open log file /sdcard/log/message/log_1970-01-01.txt
E (16038) MAIN: Config file seems to be missing!
E (16298) LOGFILE: Can't open log file /sdcard/log/message/log_1970-01-01.txt
W (16558) SNTP: No ConfigFile defined - exit setupTime()!
E (16818) LOGFILE: Can't open log file /sdcard/log/message/log_1970-01-01.txt
W (17078) MAIN: No ConfigFile defined - exit setCpuFrequency()!
E (17338) LOGFILE: Can't open log file /sdcard/log/message/log_1970-01-01.txt
I (19098) OTA: Start CheckOTAUpdateCheck...
I (19118) OTA: SHA-256 for the partition table: : 9d4a2809ae90fb20709a8ca3dd3ac3462e1e73286bcd31b689060c91de06fa3a
I (19138) OTA: SHA-256 for bootloader: : 4a9573dafac5d5c79c43e5a356568332da3a99dd2e220da6ceeadc96d32708a2
I (19618) OTA: SHA-256 for current firmware: : b64a22854eb1e33763bde88abf63d86bb137038b818f619734b7e59e5fc8e6b6
W (20428) WIFI AP: config.ini not found!
W (20428) WIFI AP: wlan.ini not found!
I (20428) WIFI AP: Starting access point for remote configuration
I (20448) wifi:wifi driver task: 3ffd12dc, prio:23, stack:6144, core=0
I (20448) system_api: Base MAC address is not set
I (20448) system_api: read default base MAC address from EFUSE
I (20448) wifi:wifi firmware version: 57982fe
I (20448) wifi:wifi certification version: v7.0
I (20458) wifi:config NVS flash: enabled
I (20458) wifi:config nano formating: enabled
I (20468) wifi:Init data frame dynamic rx buffer num: 16
I (20468) wifi:Init management frame dynamic rx buffer num: 16
I (20478) wifi:Init management short buffer num: 32
I (20478) wifi:Init static tx buffer num: 16
I (20488) wifi:Init tx cache buffer num: 16
I (20488) wifi:Init static rx buffer size: 1600
I (20488) wifi:Init static rx buffer num: 16
I (20498) wifi:Init dynamic rx buffer num: 16
I (20498) wifi_init: rx ba win: 16
I (20498) wifi_init: tcpip mbox: 32
I (20508) wifi_init: udp mbox: 6
I (20508) wifi_init: tcp mbox: 6
I (20508) wifi_init: tcp tx win: 5744
I (20518) wifi_init: tcp rx win: 5744
I (20518) wifi_init: tcp mss: 1440
I (20518) wifi_init: WiFi/LWIP prefer SPIRAM
I (20528) wifi_init: WiFi IRAM OP enabled
I (20528) wifi_init: WiFi RX IRAM OP enabled
I (20548) phy_init: phy_version 4670,719f9f6,Feb 18 2021,17:07:07
W (20548) phy_init: failed to load RF calibration data (0x1102), falling back to full calibration
I (20738) wifi:mode : softAP (08:d1:f9:cd:73:fd)
I (20738) wifi:Total power save buffer number: 8
I (20738) wifi:Init max length of beacon: 752/752
I (20738) wifi:Init max length of beacon: 752/752
I (20748) WIFI AP: started with SSID "AI-on-the-Edge", password: "", channel: 11. Connect to AP and open http://192.168.4.1
I (103608) wifi:new:<11,2>, old:<11,2>, ap:<11,2>, sta:<255,255>, prof:11
I (103608) wifi:station: 90:61:ae:87:3e:b2 join, AID=1, bgn, 40D
I (103618) WIFI AP: station 90:61:ae:87:3e:b2 join, AID=1
I (103678) esp_netif_lwip: DHCP server assigned IP to a client, IP is: 192.168.4.2
I (105878) esp_netif_lwip: DHCP server assigned IP to a client, IP is: 192.168.4.2
Start des Post Handlers
Nach Start des Post Handlers
filepath: /sdcard/firmware/AI-on-the-edge-device__remote-setup__v15.2.4.zip, filename: /firmware/AI-on-the-edge-device__remote-setup__v15.2.4.zip
E (178828) WIFI AP: Failed to create file: /sdcard/firmware/AI-on-the-edge-device__remote-setup__v15.2.4.zip
W (178828) httpd_txrx: httpd_resp_send_err: 500 Internal Server Error - Failed to create file
W (178838) httpd_uri: httpd_uri: uri handler execution failed
Start des Post Handlers
Nach Start des Post Handlers
filepath: /sdcard/firmware/AI-on-the-edge-device__remote-setup__v15.2.4.zip, filename: /firmware/AI-on-the-edge-device__remote-setup__v15.2.4.zip
E (182898) WIFI AP: Failed to create file: /sdcard/firmware/AI-on-the-edge-device__remote-setup__v15.2.4.zip
W (182898) httpd_txrx: httpd_resp_send_err: 500 Internal Server Error - Failed to create file
W (182918) httpd_uri: httpd_uri: uri handler execution failed
ets Jul 29 2019 12:21:46

rst:0x1 (POWERON_RESET),boot:0x12 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:7664
load:0x40078000,len:15360
load:0x40080400,len:3744
entry 0x4008067c
I (27) boot: ESP-IDF 4.3.2 2nd stage bootloader
I (27) boot: compile time 20:02:47
I (27) boot: chip revision: 3
I (30) boot_comm: chip revision: 3, min. bootloader chip revision: 0
I (37) boot.esp32: SPI Speed      : 40MHz
I (42) boot.esp32: SPI Mode       : DIO
I (46) boot.esp32: SPI Flash Size : 4MB
I (51) boot: Enabling RNG early entropy source...
I (56) boot: Partition Table:
I (60) boot: ## Label            Usage          Type ST Offset   Length
I (67) boot:  0 nvs              WiFi data        01 02 00009000 00004000
I (75) boot:  1 otadata          OTA data         01 00 0000d000 00002000
I (82) boot:  2 phy_init         RF data          01 01 0000f000 00001000
I (89) boot:  3 ota_0            OTA app          00 10 00010000 001db000
I (97) boot:  4 ota_1            OTA app          00 11 001f0000 001db000
I (104) boot: End of partition table
I (109) boot_comm: chip revision: 3, min. application chip revision: 0
I (116) esp_image: segment 0: paddr=00010020 vaddr=3f400020 size=46fbch (290748) map
I (236) esp_image: segment 1: paddr=00056fe4 vaddr=3ffb0000 size=03ce0h ( 15584) load
I (242) esp_image: segment 2: paddr=0005accc vaddr=40080000 size=0534ch ( 21324) load
I (252) esp_image: segment 3: paddr=00060020 vaddr=400d0020 size=1575fch (1406460) map
I (790) esp_image: segment 4: paddr=001b7624 vaddr=4008534c size=15208h ( 86536) load
I (841) boot: Loaded app from partition at offset 0x10000
I (841) boot: Disabling RNG early entropy source...
I (853) quad_psram: This chip is ESP32-D0WD
I (853) esp_psram: Found 8MB PSRAM device
I (853) esp_psram: Speed: 40MHz
I (853) esp_psram: PSRAM initialized, cache is in low/high (2-core) mode.
W (860) esp_psram: Virtual address not enough for PSRAM, map as much as we can. 4MB is mapped
I (869) cpu_start: Pro cpu up.
I (871) cpu_start: Starting app cpu, entry point is 0x40082e48
I (0) cpu_start: App cpu up.
I (1765) esp_psram: SPI SRAM memory test OK
I (1774) cpu_start: Pro cpu start user code
I (1774) cpu_start: cpu freq: 160000000 Hz
I (1774) cpu_start: Application information:
I (1775) cpu_start: Project name:     AI-on-the-edge
I (1779) cpu_start: App version:      v15.3.0
I (1784) cpu_start: Compile time:     Jul 22 2023 09:43:02
I (1789) cpu_start: ELF file SHA256:  29d38f3fa1a9857c...
I (1794) cpu_start: ESP-IDF:          5.0.2
I (1798) cpu_start: Min chip rev:     v0.0
I (1802) cpu_start: Max chip rev:     v3.99 
I (1806) cpu_start: Chip rev:         v3.1
I (1810) heap_init: Initializing. RAM available for dynamic allocation:
I (1816) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM
I (1821) heap_init: At 3FFBD890 len 00022770 (137 KiB): DRAM
I (1826) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
I (1832) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (1837) heap_init: At 4009A554 len 00005AAC (22 KiB): IRAM
I (1843) esp_psram: Adding pool of 4083K of PSRAM memory to heap allocator
I (1851) spi_flash: detected chip: generic
I (1853) spi_flash: flash io: dio
I (1868) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
I (1869) esp_psram: Reserving pool of 40K of internal memory for DMA/internal allocations
I (1869) MAIN: 



================ Start app_main =================
I (8109) MAIN: =================================================
E (8369) LOGFILE: Can't open log file /sdcard/log/message/log_1970-01-01.txt
I (8369) MAIN: ==================== Start ======================
E (8639) LOGFILE: Can't open log file /sdcard/log/message/log_1970-01-01.txt
I (8639) MAIN: =================================================
E (8899) LOGFILE: Can't open log file /sdcard/log/message/log_1970-01-01.txt
I (8899) MAIN: PSRAM size: 8388608 byte (8MB / 64MBit)
E (9159) LOGFILE: Can't open log file /sdcard/log/message/log_1970-01-01.txt
I (9159) MAIN: Total heap: 4377243 byte
E (9419) LOGFILE: Can't open log file /sdcard/log/message/log_1970-01-01.txt
I (9419) gpio: GPIO[32]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 
I (11419) gpio: GPIO[25]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:2 
I (11419) cam_hal: cam init ok
I (11419) sccb: pin_sda 26 pin_scl 27
I (11419) sccb: sccb_i2c_port=1

I (11419) gpio: GPIO[32]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 
I (11459) camera: Detected camera at address=0x30
I (11459) camera: Detected OV2640 camera
I (11459) camera: Camera PID=0x26 VER=0x42 MIDL=0x7f MIDH=0xa2
I (11549) cam_hal: buffer_size: 32768, half_buffer_size: 4096, node_buffer_size: 2048, node_cnt: 16, total_cnt: 15
I (11549) cam_hal: Allocating 61440 Byte frame buffer in PSRAM
I (11549) cam_hal: cam config ok
I (11549) ov2640: Set PLL: clk_2x: 0, clk_div: 0, pclk_auto: 0, pclk_div: 8
I (13629) MAIN: Camera info: PID: 0x26, VER: 0x42, MIDL: 0x7f, MIDH: 0xa2
E (13879) LOGFILE: Can't open log file /sdcard/log/message/log_1970-01-01.txt
I (13879) SDCARD: Basic R/W check started...
E (14139) LOGFILE: Can't open log file /sdcard/log/message/log_1970-01-01.txt
E (14899) SDCARD: Basic R/W check: (E3) Not able to open file to read back
E (15149) LOGFILE: Can't open log file /sdcard/log/message/log_1970-01-01.txt
E (15399) HELPER: New System Status: 0x00000008
E (15659) LOGFILE: Can't open log file /sdcard/log/message/log_1970-01-01.txt
E (15909) MAIN: Config file seems to be missing!
E (16159) LOGFILE: Can't open log file /sdcard/log/message/log_1970-01-01.txt
W (16419) SNTP: No ConfigFile defined - exit setupTime()!
E (16669) LOGFILE: Can't open log file /sdcard/log/message/log_1970-01-01.txt
W (16919) MAIN: No ConfigFile defined - exit setCpuFrequency()!
E (17179) LOGFILE: Can't open log file /sdcard/log/message/log_1970-01-01.txt
I (18909) OTA: Start CheckOTAUpdateCheck...
I (18929) OTA: SHA-256 for the partition table: : 9d4a2809ae90fb20709a8ca3dd3ac3462e1e73286bcd31b689060c91de06fa3a
I (18949) OTA: SHA-256 for bootloader: : 4a9573dafac5d5c79c43e5a356568332da3a99dd2e220da6ceeadc96d32708a2
I (19429) OTA: SHA-256 for current firmware: : b64a22854eb1e33763bde88abf63d86bb137038b818f619734b7e59e5fc8e6b6
W (20219) WIFI AP: config.ini not found!
W (20219) WIFI AP: wlan.ini not found!
I (20219) WIFI AP: Starting access point for remote configuration
I (20229) wifi:wifi driver task: 3ffd131c, prio:23, stack:6144, core=0
I (20229) system_api: Base MAC address is not set
I (20229) system_api: read default base MAC address from EFUSE
I (20239) wifi:wifi firmware version: 57982fe
I (20239) wifi:wifi certification version: v7.0
I (20249) wifi:config NVS flash: enabled
I (20249) wifi:config nano formating: enabled
I (20249) wifi:Init data frame dynamic rx buffer num: 16
I (20259) wifi:Init management frame dynamic rx buffer num: 16
I (20259) wifi:Init management short buffer num: 32
I (20269) wifi:Init static tx buffer num: 16
I (20269) wifi:Init tx cache buffer num: 16
I (20279) wifi:Init static rx buffer size: 1600
I (20279) wifi:Init static rx buffer num: 16
I (20279) wifi:Init dynamic rx buffer num: 16
I (20289) wifi_init: rx ba win: 16
I (20289) wifi_init: tcpip mbox: 32
I (20289) wifi_init: udp mbox: 6
I (20299) wifi_init: tcp mbox: 6
I (20299) wifi_init: tcp tx win: 5744
I (20299) wifi_init: tcp rx win: 5744
I (20309) wifi_init: tcp mss: 1440
I (20309) wifi_init: WiFi/LWIP prefer SPIRAM
I (20309) wifi_init: WiFi IRAM OP enabled
I (20319) wifi_init: WiFi RX IRAM OP enabled
I (20329) phy_init: phy_version 4670,719f9f6,Feb 18 2021,17:07:07
I (20429) wifi:mode : softAP (08:d1:f9:cd:73:fd)
I (20429) wifi:Total power save buffer number: 8
I (20429) wifi:Init max length of beacon: 752/752
I (20429) wifi:Init max length of beacon: 752/752
I (20439) WIFI AP: started with SSID "AI-on-the-Edge", password: "", channel: 11. Connect to AP and open http://192.168.4.1
I (87119) wifi:new:<11,2>, old:<11,2>, ap:<11,2>, sta:<255,255>, prof:11
I (87129) wifi:station: 90:61:ae:87:3e:b2 join, AID=1, bgn, 40D
I (87129) WIFI AP: station 90:61:ae:87:3e:b2 join, AID=1
I (87189) esp_netif_lwip: DHCP server assigned IP to a client, IP is: 192.168.4.2
I (89199) esp_netif_lwip: DHCP server assigned IP to a client, IP is: 192.168.4.2
Start des Post Handlers
Nach Start des Post Handlers
filepath: /sdcard/firmware/AI-on-the-edge-device__remote-setup__v15.2.4.zip, filename: /firmware/AI-on-the-edge-device__remote-setup__v15.2.4.zip
E (160199) WIFI AP: Failed to create file: /sdcard/firmware/AI-on-the-edge-device__remote-setup__v15.2.4.zip
W (160199) httpd_txrx: httpd_resp_send_err: 500 Internal Server Error - Failed to create file
W (160209) httpd_uri: httpd_uri: uri handler execution failed
Start des Post Handlers
I (161289) wifi:<ba-add>idx:2 (ifx:1, 90:61:ae:87:3e:b2), tid:0, ssn:191, winSize:64
Nach Start des Post Handlers
filepath: /sdcard/firmware/AI-on-the-edge-device__remote-setup__v15.2.4.zip, filename: /firmware/AI-on-the-edge-device__remote-setup__v15.2.4.zip
E (164839) WIFI AP: Failed to create file: /sdcard/firmware/AI-on-the-edge-device__remote-setup__v15.2.4.zip
W (164839) httpd_txrx: httpd_resp_send_err: 500 Internal Server Error - Failed to create file
W (164849) httpd_uri: httpd_uri: uri handler execution failed`

**Comment by caco3** [comment]
> copied all the files to the SD card

Can you describe this a bit better?
What did you copy?
Can you show a screenshot of `http://<IP>/fileserver/#` ?
The log sais you dont have a `logs` folder: `E (8438) LOGFILE: Can't open log file /sdcard/log/message/[..]`

**Comment by caco3** [comment]
```
I (15329) MAIN: Initialization completed successfully
I (15369) ov2640: Set PLL: clk_2x: 0, clk_div: 0, pclk_auto: 0, pclk_div: 8
E (17019) sdmmc_cmd: sdmmc_read_sectors_dma: sdmmc_send_cmd returned 0x109
E (17029) diskio_sdmmc: sdmmc_read_blocks failed (265)
Guru Meditation Error: Core  0 panic'ed (LoadProhibited). Exception was unhandled.
```

There is an issue with your SD card!
Can you try with a different one?
