### ISSUE TITLE
Adding support for Seeed ESP32S3 Sense

### ISSUE THREAD

**Issue by KaelanTesseract** [jomjol/AI-on-the-edge-device#2721]
### The Feature

It is possible to add the Seeed ESP32S3 Sense as supported Hardware?

https://wiki.seeedstudio.com/xiao_esp32s3_getting_started/

Thanks for your work.

**Comment by caco3** [comment]
there are no plans to support different hardware beside the ESP32-CAM board, sry.

**Comment by Slider0007** [comment]
Fork with support for various ESP32 and ESP32-S3 boards --> more infos: #3874
