### ISSUE TITLE
Alignment issue

### ISSUE THREAD

**Issue by DarioB92** [jomjol/AI-on-the-edge-device#273]
Hello, even if all marks and rois are aligned in cinfiguration, in overview and in recognition aren't.
I took new reference image to check the device din't moved, and it didn't.
Ideas why happens?  Thanks
![allineati](https://user-images.githubusercontent.com/39674389/126032876-a1134c82-eabe-4494-b798-6a2fcfad4cbd.JPG)
![non allineati](https://user-images.githubusercontent.com/39674389/126032879-2c00e65b-c616-45f3-8230-d43f0370f017.JPG)

**Comment by friedpa** [comment]
With this pictures it will never work. Please check: https://forum.iobroker.net/topic/36622/wasserzähler-version-2-all-in-device for all necessary information including how the picture should look like.

**Comment by jomjol** [comment]
Hello @DarioB92,
unfortunately friedpa is totally right. This image has much too less contrast. Therefore the alignment reference are not found on a stable way and the rotation is somehow arbitraty, resulting in your observerd behaviour.
Why is your image so yellow? Do you have a chance to change this?

**Comment by DarioB92** [comment]
I didn't thought the misalignment could be due to image quality, I used a yellowish tape to reduce reflexions, I will read the forum and will try to achieve a better image quality.
Thanks for reply, it's a really interesting project!

**Comment by JanChrisKlein** [comment]
Hi,

somehow similar problem here. After meticulous drawing of ROIs I can't seem to get results:
![störrisch](https://user-images.githubusercontent.com/2203295/126047128-87837f07-90ca-4faf-a492-e5c4a75a28db.jpg)
Alignement does not work. Lighting is not too bad...
Any help appreciated.
Oh. and: fascinating project :)

Christoph

**Comment by jomjol** [comment]
Hi Christoph,
this rotation tells me, that the alignment with the two alignment references is not working. The image quality is totally okay. I would use the m3 with the dot on the right hand as one alignment point. The second one is more complicatet. Maybe you can rotate it a bit, than the PIP would have a good contrast and simple structure
