### ISSUE TITLE
illumunation/ picture quality changes randomly 

### ISSUE THREAD

**Issue by mdax82** [jomjol/AI-on-the-edge-device#276]
Device was rebooting on his own and after reboot picture quality dropped while no physical device change:

Before reboot:
![raw_20210717-174639](https://user-images.githubusercontent.com/30009068/126047778-9b1f2b27-d8bf-4027-8f54-64de0ff5d9e1.jpg)

After reboot:
![raw_20210717-175130](https://user-images.githubusercontent.com/30009068/126047785-c7880242-d4c9-43b7-b892-410dc6f394d3.jpg)

In this situation reading fails as it seems it cant align the picture anmore anymore (the ROIs dont match).

After another reboot its though fine again - until another reboot which may work or not.

Obviously there is a big reflection point - will try to play around if this might be a root cause though I would expect it either works or fails overall...

**Comment by jomjol** [comment]
Please switch of "FixedExposure" (=set it to false). If the problem is still there increase `WaitBeforeTakingPicture`.

This colouring happens, if the camera is not in a stable version after switching on the light.

**Comment by mdax82** [comment]
Indeed this seem to fix it! Magic thanks! 

Though I see the default config.ini has 
"FixedExposure = false"

I was wondering why I had set it to true but never intend to change. 

In "Edit configuration" in WebUI it seems FixedExposure is always set "true" regardless if the real value of config.ini. It seems in my case when set further options it set the "FixedExposure = true" while it was never intend to be so. 

I can set it to "false" it writes the right value to the config.ini but open the dialog again it would set it to "true" at next save. 

I was able to reproduce this behavior here you may want to check if there is something broken?

**Comment by jomjol** [comment]
I can reproduce the error with the setting and bug fix version is published (v8.0.1 - only html.zip)

**Comment by mdax82** [comment]
works like a charme thanks! :)
