### ISSUE TITLE
Port to Raspberry Pi?

### ISSUE THREAD

**Issue by JanChrisKlein** [jomjol/AI-on-the-edge-device#278]
Hi,

I understand that part of this project‘s fascination comes from the processor it‘s running on. But would it be possible to port Your project to Raspberry Pi (let‘s say a ‚zero‘)?
Wouldn‘t that get rid of Your performance trouble? And still have the small form factor?

Chris

**Comment by jomjol** [comment]
Hi Chris,
the barrier is the tflite micro implemenation. A few month ago, this was not avaible for the raspberry zero.
I assume, that it will be possible somehow. But the effort is high, therefore I'm not going to follow this approach.
