### ISSUE TITLE
Missing Config.ini

### ISSUE THREAD

**Issue by mustermannalex** [jomjol/AI-on-the-edge-device#279]
After refining the ROI alignment, no images were taken anymore. I don't know how it happened, maybe due to missing wireless connection in the saving process or something else, but the config.ini was missing. Therefore, no change in the web configuration for the ROI settings could be made. The error message was ROI disabled and no ROI defined, please define the first ROI manual in the config.ini file.

The solution was to copy the standard config.ini file from the git repo to the config folder on the SD card and configuring the ROI's again.

Maybe there could be some checking if the file is present or not and if not, restoring the file automatically. Maybe even before saving and, if saving failed, restoring the previous file.

Nevertheless, amazing project!!

**Comment by jomjol** [comment]
I totally agree, that error handling is at some points rudimentary. 

Question is, where to start and stop with limited resources (firmware size > 95% available space AND programming ressource of developer :-)).

For the second problem, I' m happy to merge branches, that deal with this issue.
