### ISSUE TITLE
New Training Data

### ISSUE THREAD

**Issue by cnmontreal** [jomjol/AI-on-the-edge-device#2802]
### Files

![3](https://github.com/jomjol/AI-on-the-edge-device/assets/12156704/88261a3e-fc42-4063-b55b-6635190139a4)
It recognizes this as 5.

**Comment by jomjol** [comment]
Can you support a full set of training data, please?

I'm not planing to extend single images into the training, but rather full training sets.

Thanks in advance!

**Comment by gbcsysteme** [comment]
I am not the creator, but I also have problems with the recognition. The "1" in particular is rarely recognized. 
I have created a training set.

[Data.zip](https://github.com/jomjol/AI-on-the-edge-device/files/14001803/Data.zip)

Thanks in advance for your help.

**Comment by jomjol** [comment]
Images have been included in training. You find the newest tflite here:
https://github.com/jomjol/AI-on-the-edge-device/blob/rolling/sd-card/config/dig-cont_0640_s3_q.tflite

**Comment by gbcsysteme** [comment]
![Screenshot_20240217-141511](https://github.com/jomjol/AI-on-the-edge-device/assets/97114736/ff0eaa76-9a4e-4468-9a07-b1370a718df9)


That looks very good now, thank you very much!
