### ISSUE TITLE
New Training Data - digit 5 recognized as 1

### ISSUE THREAD

**Issue by waldmeisterx** [jomjol/AI-on-the-edge-device#2804]
### Files

![5 0_1](https://github.com/jomjol/AI-on-the-edge-device/assets/2168391/a6795176-c73f-47f4-9a56-77f365a35c10)
![5 0_2](https://github.com/jomjol/AI-on-the-edge-device/assets/2168391/3724af94-61e1-4aeb-b7ca-af1ae688dadb)
![5 0_3](https://github.com/jomjol/AI-on-the-edge-device/assets/2168391/2f8b25ed-c4bc-4951-b7d0-5b83547d6a87)
these courious "5" get recognized as "1"

**Comment by jomjol** [comment]
Can you support a full set of training data, please?

I'm not planing to extend single images into the training, but rather full training sets.

Thanks in advance!

**Comment by waldmeisterx** [comment]
Sure. As requested here a complete set of all digits
[Stromzaehler set of all digits.zip](https://github.com/jomjol/AI-on-the-edge-device/files/13931502/Stromzaehler.set.of.all.digits.zip)

**Comment by jomjol** [comment]
Thanks for the update. 

One question: I expected data for the tflite with intermediate value (0, 0.1, 0.2, 0.3, .... 9.7, 9.8, 9.9) naming: dig-cont_XXXX.tflite

With this I can only train the discrete one: 0, 1, 2, ... 9) - naming: dig-class11_XXXX.tflite

If you need an update for the dig_con model, I need values for every intermediate step, about 2 per status --> 200 images.

**Comment by waldmeisterx** [comment]
Ok, as I require the dig_con model, so I'll upload a new zip shortly.

**Comment by waldmeisterx** [comment]
Ok, here we are, the 0.1 digit pictures.
[Stromzaehler set of 0.1 digits.zip](https://github.com/jomjol/AI-on-the-edge-device/files/13932180/Stromzaehler.set.of.0.1.digits.zip)

Btw. very nice project. 
I'm running 3 ESP right now and they are attached to our Home Assistant. 
Only the power meter has sometimes problems with this "5".

**Comment by waldmeisterx** [comment]
Sind die neuen Daten in Zehntel-Dezimalen ok?
(ich denke auf Deutsch geht auch, oder?)

**Comment by jomjol** [comment]
Bilder sind okay, brauche schlicht die Zeit, die zu verarbeiten.

**Comment by jomjol** [comment]
Images have been included in training. You find the newest tflite here:
https://github.com/jomjol/AI-on-the-edge-device/blob/rolling/sd-card/config/dig-cont_0640_s3_q.tflite
