### ISSUE TITLE
New Training Data for false positive value 4 (recognised as 1)

### ISSUE THREAD

**Issue by sipossz** [jomjol/AI-on-the-edge-device#2806]
### Files

The 3rd digit recognised as 1 agains 4. There is also a 4 at the 2nd digit, what is correctly recognised. I don't see the difference, but I tried many times with different settings and I also got the same false positive meter value:

![image](https://github.com/jomjol/AI-on-the-edge-device/assets/78107707/87172c11-c197-40f0-8874-1183c6f40a1a)

I'm using the following model setting:
![image](https://github.com/jomjol/AI-on-the-edge-device/assets/78107707/29172cdc-68d7-4ce2-b3e2-7d7953c00e11)

**Comment by jomjol** [comment]
Can you support a full set of training data, please?

I'm not planing to extend single images into the training, but rather full training sets.

Thanks in advance!

**Comment by sipossz** [comment]
This is the failed digit recognised 1 by dig-cont_0611_s3 model
![image](https://github.com/jomjol/AI-on-the-edge-device/assets/78107707/deeda256-a2d6-42b7-a952-9969af6e2164)
All the other digits ara working well.

**Comment by jomjol** [comment]
It does not make sense to implement single images. I'll close this issue.
If you can provide a full trianing set, please open a new issue
