### ISSUE TITLE
new digit for number 7 and 2 and 1

### ISSUE THREAD

**Issue by kthemall** [jomjol/AI-on-the-edge-device#2808]
### Files

![image](https://github.com/jomjol/AI-on-the-edge-device/assets/78484370/744eb6cb-2df0-47fb-8777-4eb02ca14523)

**Comment by kthemall** [comment]
hi, the 7 is identified as 1

maybe my screen helps a bit. thx tom

**Comment by kthemall** [comment]
![image](https://github.com/jomjol/AI-on-the-edge-device/assets/78484370/5a8b29fd-d217-42af-93f9-8e6cc71bcf6a)

**Comment by kthemall** [comment]
![image](https://github.com/jomjol/AI-on-the-edge-device/assets/78484370/360eed80-f73c-4602-b7fe-542fe1e0c8b2)

**Comment by kthemall** [comment]
i hope this is ok if i just enter the jpgs with the numbers here???

**Comment by jomjol** [comment]
No update since 4 weeks. Please reopen in case training data is available
