### ISSUE TITLE
report wireless rssi

### ISSUE THREAD

**Issue by minoger** [jomjol/AI-on-the-edge-device#281]
hello

at first thank you for your work. it runs perfectly and was exactly what i was looking for.
question: is it possible to add the wireless rssi values to mqtt output.
thank you

regards
Michael

**Comment by jomjol** [comment]
Hi Michael,

thanks a lot for your positiv feedback!

Regarding the extention of the MQTT-adapter, there are so many indivual request (e.g. RSSI, MAC-Adress, IP-Adress, ...), that I decided not to implement them by my own, but to stay with the elementary important.
Though it is not too difficult to make a individual solution. So I'm happy to support with the entry to this.

Beste regards,
  jomjol
