### ISSUE TITLE
External LED on GPIO16

### ISSUE THREAD

**Issue by twam** [jomjol/AI-on-the-edge-device#2810]
### The Feature

GPIO16 (U2RXD) seems unused in the [ESP-CAM schematic](https://github.com/SeeedDocument/forum_doc/blob/master/reg/ESP32_CAM_V1.6.pdf). Would it be possible to add an optional to use this for a flash?

I have a LED ring light with a low-active EN, which would require an unused GPIO in open-drain configuration (preferred) or push-pull.

PS:
The current GPIO settings only support GPIO4 and GPIO12. However it looks like I cannot assign GPIO12 to an external flash as suggested in the paragraph before.
<img width="973" alt="image" src="https://github.com/jomjol/AI-on-the-edge-device/assets/112843/27cca732-fe02-4682-b55f-e209d39360a2">

**Comment by caco3** [comment]
not sure if pin 16 really is unused (UART). But it should be possible to extend the other pins as open drain or inverted output.

**Comment by twam** [comment]
From my understanding UART0 on GPIO1 and GPIO3 is used.

**Comment by twam** [comment]
Meh – double check the schematic. GPIO16 Is actually used as a chip-select for the PSRAM – It has two names in the schematic (IO16 and U2RXD).
