### ISSUE TITLE
Why 3 minute interval minimum?

### ISSUE THREAD

**Issue by vguna** [jomjol/AI-on-the-edge-device#282]
Hey.
First of all GREAT WORK you did with this project! I'm really amazed how much work you put into this to get it running on such a small and cheap device - including all the UI stuff. Awesome!

I just wanted to ask, what is the reason behind the at least 3 minutes interval restriction? Is it to not overload the ESP32 that might reboot then? And not make the UI slow down?

Although it does not kill me to have the 3 minutes interval, but I had something in my mind to combine the presence detector in my shower with the water drainage to avoid false alarms to detect whether someone is actually showering or just cleaning it :D. Of course there are still edge-cases when some is using water somewhere else than in the shower - but it's an improvement still. Hence I would try to set it to 1-2 minutes or so.

I also thought about for such situations, if it would be possible to trigger a recognition from externally via REST POST call to the ESP32 WebUI or so. So I could even go to 15 minutes or bigger for normal usecases, but if presence detection triggers, I would kick a on-demand recognition. Would that be a useful feature to implement?

**Comment by friedpa** [comment]
Hi, the reason for the 3+ minutes is that the ESP need for one "round" over two minutes to calculate. So values lower than 3 minutes would not work and in worst case end up in endless rebooting. For manual trigger you can use the "web-commands" descripted on the github webpage. So you could set in the config.ini a high value for the trigger and afterwards manually or with a programme trigger the reading e.g. in IOBroker

**Comment by vguna** [comment]
Amazing, I will take a look, thanks!

**Comment by vghero** [comment]
Hm I just could find: https://github.com/jomjol/water-meter-picture-provider.You mean the `capture` endpoints? From the description it sounds it just takes a picture but does it also start the recognition?

**Comment by jomjol** [comment]
If you turn on the logging, you can check, how long a round actually takes and reduce the time corresponding. Another option for decreasing the round time is, to use `FixedExposureSetting' (-5 seconds) and set the AlignmentAlgo to "Fast" (only working after first round).

**Comment by vguna** [comment]
Hm but that would only be to finetune the recognition times itself, right? The minimum 3 minute interval will still be in place, I guess. So this would be beneficial for on-demand triggered recognitions? If so, how can I trigger it exactly? As mentioned I could only find the capture endpoints which look like making images but not starting the actual recognition (?).

**Comment by jomjol** [comment]
The minimum of 3 minutes is only a recommendation. From the programming code you can go down as much as you like. Worst case, it should start one recognition after the other

**Comment by vguna** [comment]
Ah, I thought I've seen the restriction on the UI (got red when tried to go below 3?!) in the setup wizard. But maybe I do not remember correctly. So is it possible to directly trigger a recognition via HTTP call?

**Comment by jomjol** [comment]
You can trigger a recognition flow with the following http request:
``http://IP-ADDRESS/doflow``
