### ISSUE TITLE
MQTT sends old changeabsolut if found neg. raw value

### ISSUE THREAD

**Issue by DigiNecro** [jomjol/AI-on-the-edge-device#2826]
### The Problem

Some days ago I hat a problem with a correct recognition (in phase of switch from 1 to 2 it recognised 0)  of the digit ROI (optimizing the ROI fixed it), but whenever it recognised a negativ raw value it sends over MQTT the last changeabsolut, so I get a lot false values in my system.

### Version

v15.4.0 (Commit: 74d4f20)

### Logfile

```shell
-
```

### Expected Behavior

Would it be possible, if it findsnegative raw value, it send no changeabsolut or 0 as changeabsolut?

**Comment by caco3** [comment]
should be fixed with https://github.com/jomjol/AI-on-the-edge-device/pull/2956
