### ISSUE TITLE
Basic auth for the UI?

### ISSUE THREAD

**Issue by vguna** [jomjol/AI-on-the-edge-device#283]
I know, call me paranoid, but is there space left to add authentication to the UI :)?

**Comment by jomjol** [comment]
Technically possilbe, rather focusing towards a commercial usage. It would need quite some changes in the code and communication handling. I will put it on the feature request list (https://github.com/jomjol/AI-on-the-edge-device/blob/master/FeatureRequest.md), but not follow it actively.
