### ISSUE TITLE
Wrong MIME-type for .jpg files

### ISSUE THREAD

**Issue by stroebjo** [jomjol/AI-on-the-edge-device#284]
Inside the following function the MIME type for the webserver response is checked by file extension. For JPGs only `.jpeg` (with the extra `e`) ist checked but not `.jpg`. The images seem to be saved with `.jpg` so they all get transmitted with `text/plain` (noticed this during saving images from the digit log with right click save as and getting txt files). 

https://github.com/jomjol/AI-on-the-edge-device/blob/635b2c35a89ab745eb79f540c4b66df60dadf6b9/code/components/jomjol_fileserver_ota/server_help.cpp#L108

Adding an additional check with `IS_FILE_EXT(filename, ".jpg")` should fix this, like: 

```
/* Set HTTP response content type according to file extension */
esp_err_t set_content_type_from_file(httpd_req_t *req, const char *filename)
{
    if (IS_FILE_EXT(filename, ".pdf")) {
        return httpd_resp_set_type(req, "application/pdf");
    } else if (IS_FILE_EXT(filename, ".html")) {
        return httpd_resp_set_type(req, "text/html");
    } else if (IS_FILE_EXT(filename, ".jpg") || IS_FILE_EXT(filename, ".jpeg")) {
        return httpd_resp_set_type(req, "image/jpeg");
    } else if (IS_FILE_EXT(filename, ".ico")) {
        return httpd_resp_set_type(req, "image/x-icon");
    }
    /* This is a limited set only */
    /* For any other type always set as plain text */
    return httpd_resp_set_type(req, "text/plain");
}
```

--- 

I was not sure if I should provide an PR for this rather small fix? (not sure how to handle the build artefacts etc).

**Comment by jomjol** [comment]
Thanks for the hint - updated in the current rolling (2021-07-23) and will go to the next release
