### ISSUE TITLE
Reset ReturnChangeAbsolute on error

### ISSUE THREAD

**Issue by kub3let** [jomjol/AI-on-the-edge-device#2840]
### The Problem

I'm using "watermeter Change since last digitalization round" (ReturnChangeAbsolute) in Homeassistant to plot the historical changes in the same way a power meter would do.

While on successful read with no change the value is set to 0, on any error the value does not change which fills the graph with invalid data e.g. it stays the same.

IMHO on any error the value should be set to 0 since the change can't be calculated. On the next successful reading it would be corrected automatically.

For example: https://github.com/jomjol/AI-on-the-edge-device/commit/d6ce50df46fa4a9cb6f68cbf9544e1f614b107b4

### Version

15.4.0

### Logfile

```shell
n/a
```

**Comment by DigiNecro** [comment]
It seems this is the same problem as mine

https://github.com/jomjol/AI-on-the-edge-device/issues/2826

**Comment by kub3let** [comment]
> It seems to be the same problem as mine
> 
> #2826

You are right it's the same issue.

I made a beta build with the patch which can be downloaded here https://github.com/kub3let/AI-on-the-edge-device/releases/tag/15.4.1

Before updating make a Backup `System -> Backup/Restore -> Create Backup`

The build is based on the latest rolling branch which could contain other bugs, but so far I had no issues with it, detection / ha reporting works as usual.

**Comment by DigiNecro** [comment]
Thank you! i'll give it a try :)

**Comment by kub3let** [comment]
This has been running with no problems for 2 weeks now.

I rebased it to include the memory leak fix in 15.5 https://github.com/kub3let/AI-on-the-edge-device/releases/tag/15.6.1

I'm not going to add any other updates, @caco3 should decide to merge / implement it into upstream.

**Comment by caco3** [comment]
should be fixed with https://github.com/jomjol/AI-on-the-edge-device/pull/2956
