### ISSUE TITLE
File already exists 400 Error!

### ISSUE THREAD

**Issue by Basti09** [jomjol/AI-on-the-edge-device#285]
Hey,

nach dem update auf 8.0.1 kann ich die config nicht mehr verändern. Habe nur noch schwarzes Bild. 
Er hat automatisch die sec nach dem Blitz bis zum Foto auf 7 sec geändert.

Bekomme den Fehler nicht weg.
Gibt es dazu eine Lösung ?

**Comment by mikewolf** [comment]
hallo habe nach uprade selbifes Problem , evt schreibrechte  ???

**Comment by B-Kramer** [comment]
I have the same problem.

**Comment by Stff0r** [comment]
Problem kann ich bestätigen nach OTA Update auf 8.0.1, schwarzes Bild und keine Änderungen an der Config möglich (mit Fehlermeldung oben).
Einfache Lösung habe ich nicht gefunden. Habe SD Karte neu aufgesetzt + Ersteinrichtung.

**Comment by Basti09** [comment]
Gibt es auch eine andere Alternative als die SD Card neu aufzusetzen und alles neu zu machen. War gerade froh das es es so einigermaßen gut läuft

**Comment by jomjol** [comment]
Von welcher Version habt ihr den upgedated? Könnt ihr mir eure `config.ini` schicken. Ich vermute den Fehler dort.

**Comment by Basti09** [comment]
ich habe von der letzten auf 8.0 und hatte den Fehler da schon. Und dachte dann das er mit 8.0.1 dann weg wäre.
Wie kann ich dir die schicken ?
[config.zip](https://github.com/jomjol/AI-on-the-edge-device/files/6863876/config.zip)

**Comment by jomjol** [comment]
@Basti09  kann das ZIP-File nicht öffnen.

**Comment by Basti09** [comment]
[config.zip](https://github.com/jomjol/AI-on-the-edge-device/files/6863899/config.zip)

**Comment by jomjol** [comment]
Kann jetzt erstmal bestätigen, dass deine Config bei mir auf dem Testsystem auch nicht läuft. Habe eine Vermutung, kann das aber vermutlich erst am Wochenende prüfen, da es etwas Zeit braucht. melde mich dann.

**Comment by Basti09** [comment]
Alles klar vielen Dank :) komisch ist auch das man die config über den file Browser nicht löschen kann ! Ich hoffe das es mit dem nächsten OTA Update dann geht, mag das Dingen nicht wieder abbauen 😂

**Comment by jomjol** [comment]
Wollte gerade den Fehler in der neuesten Rolling nachvollziehen, aber deine Config.ini läuft dort ohne Probleme!
Kannst du das mal selbst probieren (neueste rolling)?

**Comment by Basti09** [comment]
Ja klar mache ich heute Abend. Ich melde mich dann noch mal. Danke für deine Mühe

**Comment by Stff0r** [comment]
Ich habe von 7.0.1 auf 8.0.1 Update gemacht (Firmware und HTML).
Danach das Problem mit dem schwarzen Bild und keine Änderungen an der config möglich.
Auch mit dem Problem dass man über File Server keine Dateien löschen konnte.
Also vielleicht irgendwas mit Dateiberechtigungen oder Filesystem?

**Comment by jomjol** [comment]
Ich habe jetzt gerade aus dem Release von v7.0.1 das komplette config Verzeichnis auf mein Testdevice geladen, den Initialen Config-Modus deaktiviert und er ist ganz normal gestartet. Keine Ahnung was da gerade bei euch schief läuft. Eventuell hat es beim Update irgendwie die SD-Karte zerschossen?

**Comment by Basti09** [comment]
Habe gerade ein Update auf die Master gemacht leider ohne Erfolg. Der Fehler ist immer noch da.
Am 23. Juli 2021, 20:22 +0200 schrieb jomjol ***@***.***>:

**Comment by jomjol** [comment]
Ich vermute, dass dann deine SD-Karte zerschossen ist. Habe selbst gerade nochmals das OTA bei meinen 4 Produktivdevices getestet, läuft alles ohne Fehler.
Ich würde dir empfehlen, dein System nochmals neu aufzusetzen (Firmware auf Master v8.0.2, SD-Karte formatieren und neu bespielen). Sorry für den Aufwand.

**Comment by developnoop** [comment]
Also ich habe den Fehler beim erneuten einrichten über die Konfigurationsseite bekommen, frisches 8.0.1 Installation.
Bei Änderungen z.b. am Referenzbild oder der Orientierungsmarken.
Zwischendurch meckerte der Browser das die Seite nicht reagieren würde und ob man warten möchte oder die Seite schließen möchte.
Wenn ich lange genug gewartet habe bekam ich die 400er Meldung. Dann war das Bild erst einmal schwarz, wie von den anderen beschrieben.
Nun das merkwürdige, die Konfig Seiten erneut aufgerufen und es ging wieder, dann konnte man die Änderungen auch speichern.
Dachte erst ich habe irgendwas komisches konfiguriert :-)

Logfiles habe ich noch keine, habe aber gerade das Loging aktiviert.
Auch finde ich seltsam das sich anscheinend der ESP32 öfters neustartet. Da ich die Uptime mitlogge fällt das auf.

**Comment by jomjol** [comment]
Welchen Browser verwendest du?

**Comment by developnoop** [comment]
Die Fehler hatte ich im Crome-Browser.

**Comment by jomjol** [comment]
Das müsste ich dann mal probieren. Ich verwende und teste mit Firefox

**Comment by Basti09** [comment]
Ja war hier auch so, Chrome und Edge nur Probleme gewesen. Firefox war am besten.

**Comment by developnoop** [comment]
Ich gestehe: Ich habe den Arbeitlaptop für die Konfiguration genutzt, das VPN erlaubt lokalen Netzwerkzugriff (*hust*), da ich keine Admin Rechte habe musste ich mit Chrome vorlieb nehmen, Edge wäre auch da gewesen.
Okay, wenn ich damit nicht alleine bin, dann muss ich einfach Firefox am eigenen Rechner nutzen. 
Mein Chromebook ist dann auch raus.

**Comment by papauorg** [comment]
Ich habe das gleiche Problem. Ich habe das OTA Update gemacht, erst auf 8.0.1 und nach dem dort die Erkennung der Ziffern nicht funktioniert hat, habe ich auf 8.0.2 aktualisiert. Inzwischen habe ich auch die SD-Karte frisch formatiert und dann die Dateien aus dem Release-Ordner frisch draufkopiert.

Ich kann aber die Einrichtung nicht abschließen, da der o.g. Fehler bei mir auch erscheint. 
Das Reference-Image hat er wohl hochgeladen, das ist auch nach einem Refresh noch da. Es scheint aber so zu sein, dass keine Änderungen an der config gemacht werden können. Der Fehler tritt beim POST auf die config.ini auf. Hier als Beispiel beim Versuch die alignment structure Einstellungen zu speichern.
![grafik](https://user-images.githubusercontent.com/2471424/126893362-1bc8a13a-882d-4c19-a8b3-f9b216f54cfe.png)

Habe auch versucht die Einrichtung einfach mal durchzuklicken aber ruft man hinterher die Seite erneut auf (nach dem man mehrfach den Fehler ignoriert hat), landet man einfach wieder auf der Einrichtungsseite.


Es sieht mir so aus, als sollte die Datei jeweils immer gelöscht werden um neu an den Server gesendet werden zu können. Die Aufrufe dafür scheinen auch da zu sein, aber es sieht für mich so aus als würde die Datei auf dem Server nicht gelöscht werden:
![grafik](https://user-images.githubusercontent.com/2471424/126894133-79de4922-15f5-454e-9176-31cd4401cbef.png)

Die dafür beteilligten codestellen aus dem Screenshot bzw, auf der Serverseite sind vermutlich die hier:
https://github.com/jomjol/AI-on-the-edge-device/blob/03b5e36114c0fc834d66105441cd7bb653e2a91f/sd-card/html/readconfigcommon.js#L5
und
https://github.com/jomjol/AI-on-the-edge-device/blob/03b5e36114c0fc834d66105441cd7bb653e2a91f/code/components/jomjol_fileserver_ota/server_file.cpp#L513

Ich habe aber nicht gesehen, warum das Löschen nicht funktioniert ... 

Vielleicht hilft das ja bei der Fehlersuche ...

**Comment by jomjol** [comment]
@papauorg 
Ja super - das hilft sehr. Ich teste es jetzt mal auf einem frisch aufgesetzten System. Wenn der "delete" Befehl fehlschlägt, dann erklärt das das Problem in der Tat!

Danke für die ausführliche Fehlersuche!

**Comment by jomjol** [comment]
@papauorg Welchen Browser verwendest du?

**Comment by papauorg** [comment]
@jomjol Firefox

**Comment by jomjol** [comment]
@papauorg 
Ich konnte eine Ursache für den Reboot während des Speicherns der Config.ini finden und beseitigen. Habe das in einer neuen Rolling korrigiert. Kannst du das mal testen?

**Comment by B-Kramer** [comment]
I have installed rollling, and after about 5 minutes I have not had the error again.  Nice work!

**Comment by Basti09** [comment]
@jomjol meinst du die 8.0.2 als neue Rolling ?

**Comment by papauorg** [comment]
@jomjol Ich kann bestätigen, dass der aktuelle Rolling branch bei mir funktioniert. Sowohl beim Setup als auch beim nachträglichen Ändern. Danke für den schnellen fix! :+1: 

@Basti09 Ich denke es ist der Rolling branch gemeint.

**Comment by jomjol** [comment]
Problem mit aktuellen Release beseitigt.

**Comment by tucka** [comment]
Leider bekomme ich auch beim 8.0.3 Release den Fehler immer noch :-(

Ich habe die SD-Karte gelöscht und das sd-card Verzeichnis neu auf die Karte kopiert....

**Comment by friedpa** [comment]
Auch schon eine andere SD-Karte probiert? Manche SD-Karten funktionieren mit dem ESP32 einfach nicht.

**Comment by tucka** [comment]
Ja,  mit Version 7.x funktionierte die Karte ja.

**Comment by vuffiraa72** [comment]
Ich habe das gleiche Problem, also Fehlermeldung 400 beim Speichern der Konfiguration und schwarzes Bild.
Aufgetreten ist es nach einem OTA Update von 7.0.1 auf 8.0.3.

**Comment by jomjol** [comment]
@vuffiraa72, @tucka Es gibt mehrere Benutzer, die bei einem Upgrade von dem Problem berichten. Trotz Testfiles und detailierten Hinweisen kann ich es aber bei auf dem System nicht reproduzieren und damit nicht die Ursache finden.
Wenn nichts mehr geht, dann hilft es am ehesten, alles nochmals direkt mit v8.0.3 aufzusetzen. Bei mir läuft die Version sehr stabil.
