### ISSUE TITLE
MQTT not working

### ISSUE THREAD

**Issue by hermann1514** [jomjol/AI-on-the-edge-device#286]
Hi, after i upgrade to the latest Version, MQTT is not working.
I can't add a Main Topic. Always there is a Message "Settings cannot be saved. Please check your entries." and the Main Topic Filed is orange. I insert in this field "Gaszaehler"

Any idea?

**Comment by hermann1514** [comment]
if add the topic in the config.ini it's working.

**Comment by jomjol** [comment]
Hard to judge. My config.ini is looking like follows:
```

[MQTT]
Uri = mqtt://xxx.yyy.zzz.aaa:1883
MainTopic = wasserzaehler
ClientID = wasser
;user = USERNAME
;password = PASSWORD
```
