### ISSUE TITLE
Minor: "Maximum Age of Previous Value after Startup" is seconds or minutes, but for sure not both 😉 

### ISSUE THREAD

**Issue by baxerus** [jomjol/AI-on-the-edge-device#2870]
### The Problem

"Maximum Age of Previous Value after Startup" is seconds or minutes, but for sure not both 😉 

See the screenshot, there are two units for the same value (directly behind the input field and in the help you get when pressing the ❓ Button.
Only one can be the right...

### Version

v15.5.0 (Commit: 019069c+)

### Logfile

```shell
-
```

### Screenshots

<img width="725" alt="image" src="https://github.com/jomjol/AI-on-the-edge-device/assets/1628976/e71ebe11-a186-4566-bf00-400458d1f452">

**Comment by caco3** [comment]
Thanks for pointing it out.
Minutes is the correct one. I will update it in the Web UI.
