### ISSUE TITLE
Raw read value is accurate reported read value is not

### ISSUE THREAD

**Issue by ZacFranken** [jomjol/AI-on-the-edge-device#289]
![image](https://user-images.githubusercontent.com/4374232/126880249-6b7e8837-267b-4ea7-92a8-32c648f039f6.png)

I'm unsure why it seems to be shuffling the digits in the value field.

Let me know if you need any debug data.

Thanks!

Zac

Config.ini:

[MakeImage]
LogImageLocation = /log/source
WaitBeforeTakingPicture = 5
LogfileRetentionInDays = 365
Brightness = -2
;Contrast = 0
;Saturation = 0
ImageQuality = 5
ImageSize = VGA
FixedExposure = false

[Alignment]
InitialRotate = 177
InitialMirror = false
SearchFieldX = 20
SearchFieldY = 20
AlignmentAlgo = default
FlipImageSize = false
/config/ref0.jpg 129 272
/config/ref1.jpg 410 390

[Digits]
Model = /config/dig1100s2q.tflite
LogImageLocation = /log/digit
LogfileRetentionInDays = 2000
ModelInputSize = 20 32
main.dig1 145 314 30 54
main.dig2 192 314 30 54
main.dig3 240 314 30 54
main.dig4 289 314 30 54
main.dig5 337 313 30 54

[Analog]
Model = /config/ana0700s1lq.tflite
;LogImageLocation = /log/analog
;LogfileRetentionInDays = 3
ModelInputSize = 32 32
ExtendedResolution = true
main.ana1 454 281 112 112

[PostProcessing]
main.DecimalShift = 0
;Dial.DecimalShift = 
PreValueUse = true
PreValueAgeStartup = 720
AllowNegativeRates = false
main.MaxRateValue = 0.1
;Dial.MaxRateValue = 
ErrorMessage = true
CheckDigitIncreaseConsistency = true

[MQTT]
Uri = mqtt://10.241.11.1:1883
MainTopic = Gasmeter
ClientID = Gasmeter
user = xxxxxx
password = xxxxxx

;[GPIO]
;MainTopicMQTT = wasserzaehler/GPIO
;IO0 = input disabled 10 false false 
;IO1 = input disabled 10 false false 
;IO3 = input disabled 10 false false 
;IO4 = built-in-led disabled 10 false false 
;IO12 = input-pullup disabled 10 false false 
;IO13 = input-pullup disabled 10 false false 

[AutoTimer]
AutoStart = true
Intervall = 4.85

[Debug]
Logfile = false
LogfileRetentionInDays = 3

[System]
TimeZone = GMT0BST,M3.5.0,M10.5.0/3
TimeServer = 10.241.7.254
;AutoAdjustSummertime = false
Hostname = gasmeter
;SetupMode = false

**Comment by jomjol** [comment]
I assume, that the value and prevalue was correct, when you initially did the setup.
Can you turn on the logging (`Logfile = true`), reset the prevalue (otherwise you will not get rid of the error problem) and send me the logfile, when the error occures again.
Thanks,
  jomjol

**Comment by ZacFranken** [comment]
Hi,
Ok the prevalue.ini file had an entry for a recognition area that had been deleted. I deleted the prevalue.ini file and let it recreate it. All appears well now.
Put it down to user error.

This is a fantastic project! Thanks for putting it together!!

Thanks!

Zac
