### ISSUE TITLE
Additional Datapoints for Influx

### ISSUE THREAD

**Issue by carpshark** [jomjol/AI-on-the-edge-device#2943]
### The Feature

Hi there, thanks for the influx functionality, I love it!

But, it seems the data is only pushed upon change, which leads to empty panels, the expectation is to have a data point on each round, even if the measurement has not changed, is this something considered to be implemented?

![Screenshot_2024-02-20-23-50-12-913_com android chrome-edit](https://github.com/jomjol/AI-on-the-edge-device/assets/109219020/b426ac5e-6f7e-4ab5-a146-160dc701972f)

Regards.

**Comment by caco3** [comment]
> it seems the data is only pushed upon change

This would surprise me. I am not aware of such a functionality in our firmware. Contradictory, I think this is the behaviour of influxDB to same storage space.

**Comment by carpshark** [comment]
And you are absolutely right, it was my bad WiFi reception, despite my tasmota working fine.. Ai on the edge did not respond, (Webinterface was unresponsive too) weird thing is it worked a while but then it died.. 

However, I just added a small range extender which seems to have it sorted..

![Screenshot_2024-02-21-23-22-45-383_com chrome beta-edit](https://github.com/jomjol/AI-on-the-edge-device/assets/109219020/bdfcea2e-5bff-4ade-b73c-d9f580d7a451)

Sorry for the request, feel free to close it.

Regards.

**Comment by caco3** [comment]
The UI shows the RSSI, for a good reception it should be below approx. -75 dBm. It might be worth to add an external antenna as the internal one is not very good.
