### ISSUE TITLE
Jump Back to older Release - Image not sharpen and Value not right

### ISSUE THREAD

**Issue by svalcken** [jomjol/AI-on-the-edge-device#2946]
### The Problem

I have used 15.5.0 and update to 15.7.0. Bug with raw value incorrect. With 15.7.0 the image are very unsharp so i jump back to 15.3.0. This image works for me current better.

Please verify why the image from camera are so bad. Thanks.

### Version

15.7.0

### Logfile

```shell
Nothing needed.
```

**Comment by A380Coding** [comment]
Check out issue #2901

**Comment by svalcken** [comment]
Thanks,

I have retry and now i can setting the expert settings for auto correction. Before this option are greyed out.
Now it works
