### ISSUE TITLE
SD-Karte locked

### ISSUE THREAD

**Issue by TimFins** [jomjol/AI-on-the-edge-device#295]
Hallo,

ich hatte bereits vor einigen Tagen einen Issue aufgemacht, bei dem die ESP32-Cam einfach nicht wie gewünscht gestartet ist. Die LEDs haben nicht wie zu erwarten geblinkt und es wurde keine WLAN-Vebrindung hergestellt. Daraufhin wurde mir empfohlen den Start mit zu loggen über die serielle Schnittstelle. Ich kam bisher noch nicht dazu und habe es jetzt aber mal gemacht. Anbei übersende ich mal die LOG-Datei. Ich konnte schon selber herausfinden, dass die ESP32-Cam den Hostname und das Passwort der wlan.ini nicht lesen konnte. Kurz darüber steht "File is locked: /sdcard/wlan.ini - wait for 1". Das lässt mich vermuten, dass es nicht geht, weil die Datei aus welchem Grund auch immer gelocked sein soll. SD-Karte ist im FAT32-Format und hat 16GB Speicher. Mit den entsprechnenden WLAN-Daten war sie beim erstellen der LOG-Dateien auch beschrieben.
Hat jemand eine Idee? 
[seriell.txt](https://github.com/jomjol/AI-on-the-edge-device/files/6884888/seriell.txt)

LG
Tim

**Comment by friedpa** [comment]
Aus meiner Erfahrung heraus kann ich nur raten andere SD-Karten zu probieren. Einige funktionieren und andere aus unbekannten Grund einfach nicht. Ich verwende sandisk ultra oder extreme (ohne hier Werbung posten zu wollen) die haben bei mir bis jetzt immer funktioniert. Wichtig ist immer die SD-Karte vorher mit einem geeigneten Tool vollständig zu löschen / formatieren.

**Comment by jomjol** [comment]
Hallo Tim,
die Ursache ist eindeutig auf der SD-Karte. Grundsätzlich kann die SD-Karte angesprochen werden (daran zu erkennen, dass Größe und Art angegeben werden). Das erste File das gelesen wird, ist wlan.ini und das scheint nicht zu gehen. Entweder ist das File nicht da (muss im Root-Verzeichnis liegen) oder es ist korrupt (File oder Filesystem).
Hier würde ich empfehlen, die SD-Karte vollständig zu formatieren und neu zu bespielen. Ich hatte jedoch auch schon eine Karte, die sich wiederholt mit einem ähnlichen Fehler gezeigt hat. Letztlich hat nur ein Austausch geholfen.
