### ISSUE TITLE
Feature Request: Disable Auto Timer

### ISSUE THREAD

**Issue by Kornelius777** [jomjol/AI-on-the-edge-device#2964]
### The Feature

My fhem server starts the watermeter flow once a day (via http://10.10.10.10/flow_start). 
I don't want the Auto Timer to be active. 
Feature Request: If Auto Timer is set to "0", disable the Auto timer, and only respond to external requests

**Comment by Slider0007** [comment]
You could do this already without modification.
Set the timer interval to a value greater than one day and trigger externally on a daily basis. Autotimer will never be reached as long as you trigger before.
