### ISSUE TITLE
Update problem with blank screen and file already exists 400 Error

### ISSUE THREAD

**Issue by vuffiraa72** [jomjol/AI-on-the-edge-device#297]
Nach einem OTA Update von 7.0.1 auf 8.0.3 hatte ich die gleichen Probleme, wie bereits mehrfach beschrieben:

- schwarzes Bild
- beim Speichern der config.ini kommt Fehlermeldung: file already exists - 400 error

Die SD-Card war soweit in Ordnung und ich konnte die config.ini am PC ändern und speichern. Dabei ist mir aufgefallen, dass meine config.ini mit einem leeren [Ende]-Block abgeschlossen war, aber die Vorlage aus dem git diesen Block nicht (mehr) enthält. Nach dem Löschen des [Ende]-Tags am Ende der config.ini läuft bei mir wieder alles.

**Comment by jomjol** [comment]
Danke für deine Analyse. Ich habe das mit dem [Ende] probiert, aber bei geht es mit und ohne. Hast du noch etwas anderes verändert?

**Comment by vuffiraa72** [comment]
Ich habe es bei mir noch mal nachgestellt. Das einfache Kopieren des alten Konfiguration unter "Edit Config.ini direct" hat das Verhalten nicht reproduziert. Dabei ist mir aber noch ein Unterschied aufgefallen. Meine kaputte Konfiguration hat nach dem [Ende] noch ein Newline. Wenn ich das ergänze bekomme ich wieder das Fehlerbild.

Außerdem war mir noch aufgefallen, dass ich meine Konfiguration nur direkt in der config.ini ändern konnte, aber nicht über die Konfigurationsformulare. Also irgendwie hat die Migration der config.ini bei mir nicht zu einer gültigen Version geführt. Meine Installation ist schon etwas älter, ich glaube, ich bin bei 5-irgendwas eingestiegen, dann ein OTA-Update auf 7.0.1 und dann weiter zu 8.0.3.

Anbei noch die komplette alte Konfiguration nach dem Update auf 8.0.3.
[config.ini.org.txt](https://github.com/jomjol/AI-on-the-edge-device/files/6899076/config.ini.org.txt)

**Comment by jomjol** [comment]
Das mit deinem Config.ini war der entscheidende Hinweis. Fehler war reproduzierbar und ich konnte eine Endlosschleife beim Auslesen der config.ini finden. Teste mal bitte die neuests Version (v8.0.4).
VIELEN DANK!

**Comment by developnoop** [comment]
@vuffiraa72 Du kannst einfach aus dem Ordner Firmware die 8.0.4 flashen. 
Also folgende: AI-on-the-edge-device/firmware/firmware.bin 
Jomjol wird sicherlich im laufe der Tage noch das Release hochladen. Aktuell steht es ja noch bei 8.0.3.

**Comment by vuffiraa72** [comment]
Mit der Firmware 8.0.4 funktioniert auch meine alte Konfiguration. Folgendes Szenario habe ich geprüft:

- Ausgangszustand
Firmware 8.0.3, alte Konfiguration mit [Ende] LF zum Abschluss. Also schwarzer Bildschirm und Fehler 400.
- OTA Update auf Firmware 8.0.4
Datei konnte hochgeladen werden, aber Flash-Vorgang wurde nicht gestartet.
- Also flashes per esptool auf Firmware 8.0.4
Das funktionierte ohne Probleme.

Nach einem Neustart wurde die Konfiguration wieder gelesen und konnte direkt geändert werden. Außerdem wurde auch wieder ein Bild aufgenommen. Für mich scheint dein Fix erfolgreich zu sein.
