### ISSUE TITLE
Wrong Recognized Analog ROIs

### ISSUE THREAD

**Issue by winacid** [jomjol/AI-on-the-edge-device#2973]
### The Problem

the recognized analog rios are completly off. what is wrong?

### Version

15.7.0

### Logfile

```shell
[0d00h01m19s] 2024-03-07T08:26:08 <ERR> [POSTPROC] main: Raw: 00065.1130, Value: , Status: Neg. Rate - Read: - Raw: 00065.1130 - Pre: 65.8830
```

### Screenshots

![image](https://github.com/jomjol/AI-on-the-edge-device/assets/59926842/5d8596f2-2fda-46c1-99fe-c005609e893e)

**Comment by jgmGit** [comment]
I have a similar issue with 15.7 version.

The analog values are completly off.

![image](https://github.com/jomjol/AI-on-the-edge-device/assets/12555816/942e296d-0b0e-4688-b326-13c78587d1d0)

**Comment by SybexX** [comment]
Your ROIs are relatively poorly aligned and quite blurry, try to correct this first.
In approximately like this picture:
![ROIs](https://github.com/jomjol/AI-on-the-edge-device/assets/587201/ac832c0d-45fc-45c9-958e-3b9266dac356)

**Comment by jgmGit** [comment]
![image](https://github.com/jomjol/AI-on-the-edge-device/assets/12555816/67d0bc1a-6388-46f1-adfa-7b68910aad78)

@SybexX sorry for the long delay. 
What do you they about the alignment now ? Still the values are very much off.

Attaching the my config also. [config.txt](https://github.com/jomjol/AI-on-the-edge-device/files/14897440/config.txt)

**Comment by SybexX** [comment]
set the ImageQuality to 8 (the higher the value, the worse the image quality)

**Comment by Cyrelion** [comment]
I've the same problem that the analog digits are totally off :-(

![Screenshot 2024-05-28 at 07 50 14](https://github.com/jomjol/AI-on-the-edge-device/assets/16318570/90b1d21b-85e5-4615-a9e0-249898172aed)

**Comment by winacid** [comment]
i did a complete reinstall and now it works again. can someone confirm the workaround?
