### ISSUE TITLE
Allow Fixed value as option

### ISSUE THREAD

**Issue by pos-ei-don** [jomjol/AI-on-the-edge-device#2986]
### The Feature

I got a new water meter. The new one has air bubbles under the glas, wich partly covers the second digit!
As this digit will stay 1 for the next 5 weecks, i'd love to have the possibillity to set this to constant to 1.
Because of the air bubble, which I cannot remove, the device always recognice it as 9.
This makes this very reliable device currently not usable for me :-(

**Comment by caco3** [comment]
I am very sure you will not want to have to go and correct a number manually every few weeks!
I would just keep the first 2 digits away and implement the overflow logic externally, eg using a homeautomation system (with Homeassistant could do this).

**Comment by pos-ei-don** [comment]
My problem got better as the air-bubbles almost went away after some weecks.
But I'd still love to have some simple correction-possibillities (per regexp or other ) within the esp32
