### ISSUE TITLE
New Training Data Sensus i Perl Watermeter

### ISSUE THREAD

**Issue by spielkind1611** [jomjol/AI-on-the-edge-device#2995]
### Files

[Sensus Iperl.zip](https://github.com/jomjol/AI-on-the-edge-device/files/14623322/Sensus.Iperl.zip)

**Comment by jomjol** [comment]
See:

https://github.com/jomjol/AI-on-the-edge-device/blob/rolling/sd-card/config/dig-class11_1701_s2.tflite

**Comment by spielkind1611** [comment]
Thanks i will Test it

**Comment by alexboss** [comment]
Thanks for integrating the training data for Sensus iPerl. In my case, I used the model for a week https://github.com/jomjol/AI-on-the-edge-device/blob/rolling/sd-card/config/dig-class11_1701_s2.tflite , as well as the latest models, but unfortunately still had many wrong readings.
Finally, I resorted to build my own DB following the instructions provided in the documentation, and only using Sensus iPerl pictures. I have to say the result is excellent, for 1 week, not a single wrong reading so far.
Hope it will stay like this.

**Comment by spielkind1611** [comment]
I have to say that I continued to have incorrect readings no matter which model I tried. Maybe you can share your model with us then.
I'm now trying the model from the post [https://github.com/jomjol/AI-on-the-edge-device/issues/2422](url)

**Comment by alexboss** [comment]
Here it is @spielkind1611 : [dig1410s3.tflite.zip](https://github.com/user-attachments/files/17284084/dig1410s3.tflite.zip)
You can give it a try, if it works well for you, all good, if you have a minimal amount of false readings I can try to add your dataset to the training, and if it's not working well at all, then I really encourage you to train your own model with own pictures, you'll be amazed by the result.

**Comment by spielkind1611** [comment]
I haven't had any incorrect values ​​for two days. Thank you.

**Comment by alexboss** [comment]
Thank you for your feedback, glad it works for you as well. I can't guarantee it is 100% bullet-proof since I had a limited pictures for the tens / hundreds / thousands numbers. But for numbers after the decimals we should be covered. Anyway, as soon as I'll have wrong readings, I'll enrich the model with pictures that couldn't be processed.
