### ISSUE TITLE
Crash on boot

### ISSUE THREAD

**Issue by ideaweb** [jomjol/AI-on-the-edge-device#3]
I am not an expert but it seems that my CAM is crashing. Any idea what the problem could be? Hardware or software issue? Thx for you help/work!

10:03:44.796 -> rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
10:03:44.796 -> configsip: 0, SPIWP:0xee
10:03:44.796 -> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
10:03:44.829 -> mode:DIO, clock div:2
10:03:44.829 -> load:0x3fff0018,len:4
10:03:44.829 -> load:0x3fff001c,len:7024
10:03:44.829 -> ho 0 tail 12 room 4
10:03:44.829 -> load:0x40078000,len:15428
10:03:44.829 -> load:0x40080400,len:4596
10:03:44.829 -> entry 0x400806e8
10:03:44.829 -> [0;32mI (77) boot: Chip Revision: 1[0m
10:03:44.829 -> [0;32mI (77) boot_comm: chip revision: 1, min. bootloader chip revision: 0[0m
10:03:44.829 -> [0;32mI (41) boot: ESP-IDF GIT-NOTFOUND 2nd stage bootloader[0m
10:03:44.829 -> [0;32mI (41) boot: compile time 10:16:55[0m
10:03:44.864 -> [0;32mI (41) boot: Enabling RNG early entropy source...[0m
10:03:44.864 -> [0;32mI (47) boot: SPI Speed      : 40MHz[0m
10:03:44.864 -> [0;32mI (51) boot: SPI Mode       : DIO[0m
10:03:44.864 -> [0;32mI (55) boot: SPI Flash Size : 4MB[0m
10:03:44.864 -> [0;32mI (59) boot: Partition Table:[0m
10:03:44.864 -> [0;32mI (62) boot: ## Label            Usage          Type ST Offset   Length[0m
10:03:44.864 -> [0;32mI (70) boot:  0 nvs              WiFi data        01 02 00009000 00004000[0m
10:03:44.897 -> [0;32mI (77) boot:  1 otadata          OTA data         01 00 0000d000 00002000[0m
10:03:44.897 -> [0;32mI (85) boot:  2 phy_init         RF data          01 01 0000f000 00001000[0m
10:03:44.897 -> [0;32mI (92) boot:  3 ota_0            OTA app          00 10 00010000 001db000[0m
10:03:44.897 -> [0;32mI (100) boot:  4 ota_1            OTA app          00 11 001f0000 001db000[0m
10:03:44.897 -> [0;32mI (107) boot: End of partition table[0m
10:03:44.934 -> [0;32mI (111) boot_comm: chip revision: 1, min. application chip revision: 0[0m
10:03:44.934 -> [0;32mI (119) esp_image: segment 0: paddr=0x00010020 vaddr=0x3f400020 size=0x43e98 (278168) map[0m
10:03:45.039 -> [0;32mI (227) esp_image: segment 1: paddr=0x00053ec0 vaddr=0x3ffb0000 size=0x047c8 ( 18376) load[0m
10:03:45.039 -> [0;32mI (235) esp_image: segment 2: paddr=0x00058690 vaddr=0x40080000 size=0x00400 (  1024) load[0m
10:03:45.039 -> [0;32mI (236) esp_image: segment 3: paddr=0x00058a98 vaddr=0x40080400 size=0x07578 ( 30072) load[0m
10:03:45.039 -> [0;32mI (256) esp_image: segment 4: paddr=0x00060018 vaddr=0x400d0018 size=0x131768 (1251176) map[0m
10:03:45.487 -> [0;32mI (704) esp_image: segment 5: paddr=0x00191788 vaddr=0x40087978 size=0x167f8 ( 92152) load[0m
10:03:45.555 -> [0;32mI (743) esp_image: segment 6: paddr=0x001a7f88 vaddr=0x50000000 size=0x00004 (     4) load[0m
10:03:45.555 -> [0;32mI (762) boot: Loaded app from partition at offset 0x10000[0m
10:03:45.555 -> [0;32mI (762) boot: Disabling RNG early entropy source...[0m
10:03:45.555 -> [0;32mI (763) psram: This chip is ESP32-D0WD[0m
10:03:45.588 -> [0;32mI (768) spiram: Found 64MBit SPI RAM device[0m
10:03:45.588 -> [0;32mI (772) spiram: SPI RAM mode: flash 40m sram 40m[0m
10:03:45.588 -> [0;32mI (777) spiram: PSRAM initialized, cache is in low/high (2-core) mode.[0m
10:03:45.588 -> [0;32mI (784) cpu_start: Pro cpu up.[0m
10:03:45.588 -> [0;32mI (788) cpu_start: Application information:[0m
10:03:45.588 -> [0;32mI (793) cpu_start: Project name:     esp32cam-server-only[0m
10:03:45.626 -> [0;32mI (799) cpu_start: App version:      0.0.9.3[0m
10:03:45.626 -> [0;32mI (804) cpu_start: Compile time:     Sep  2 2020 10:15:59[0m
10:03:45.626 -> [0;32mI (810) cpu_start: ELF file SHA256:  e880dd3123be5bcb...[0m
10:03:45.626 -> [0;32mI (816) cpu_start: ESP-IDF:          GIT-NOTFOUND[0m
10:03:45.626 -> [0;32mI (821) cpu_start: Starting app cpu, entry point is 0x40081b28[0m
10:03:45.626 -> [0;32mI (807) cpu_start: App cpu up.[0m
10:03:46.524 -> [0;32mI (1714) spiram: SPI SRAM memory test OK[0m
10:03:46.524 -> [0;32mI (1714) heap_init: Initializing. RAM available for dynamic allocation:[0m
10:03:46.524 -> [0;32mI (1714) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM[0m
10:03:46.524 -> [0;32mI (1720) heap_init: At 3FFC22A8 len 0001DD58 (119 KiB): DRAM[0m
10:03:46.524 -> [0;32mI (1727) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM[0m
10:03:46.524 -> [0;32mI (1733) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM[0m
10:03:46.557 -> [0;32mI (1740) heap_init: At 4009E170 len 00001E90 (7 KiB): IRAM[0m
10:03:46.557 -> [0;32mI (1746) cpu_start: Pro cpu start user code[0m
10:03:46.557 -> [0;32mI (1751) spiram: Adding pool of 4096K of external SPI memory to heap allocator[0m
10:03:46.557 -> CreateClassCamera
10:03:46.557 -> [0;32mI (1777) spi_flash: detected chip: generic[0m
10:03:46.594 -> [0;32mI (1777) spi_flash: flash io: dio[0m
10:03:46.594 -> [0;32mI (1778) cpu_start: Starting scheduler on PRO CPU.[0m
10:03:46.594 -> [0;32mI (0) cpu_start: Starting scheduler on APP CPU.[0m
10:03:46.594 -> [0;32mI (1786) spiram: Reserving pool of 32K of internal memory for DMA/internal allocations[0m
10:03:46.594 -> Do Reset Camera
10:03:46.594 -> [0;32mI (1796) gpio: GPIO[32]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 [0m
10:03:48.638 -> [0;32mI (3846) connect_wlan_main: Initializing SD card[0m
10:03:48.638 -> [0;32mI (3846) gpio: GPIO[13]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 [0m
10:03:48.711 -> Name: SL08G
10:03:48.711 -> Type: SDHC/SDXC
10:03:48.711 -> Speed: 20 MHz
10:03:48.711 -> Size: 7580MB
10:03:48.711 -> [0;32mI (3926) server_ota: Start CheckOTAUpdateCheck ...[0m
10:03:48.744 -> Start CheckOTAUpdateCheck ...
10:03:48.744 -> [0;32mI (3936) server_ota: SHA-256 for the partition table: : 9d4a2809ae90fb20709a8ca3dd3ac3462e1e73286bcd31b689060c91de06fa3a[0m
10:03:48.744 -> [0;32mI (3936) boot_comm: chip revision: 1, min. application chip revision: 0[0m
10:03:48.814 -> [0;32mI (4006) server_ota: SHA-256 for bootloader: : 5002f4530fba074ae4d298f22c51da1332fb59cdde1358655ce33a1be08594bc[0m
10:03:48.814 -> [0;32mI (4006) boot_comm: chip revision: 1, min. application chip revision: 0[0m
10:03:49.463 -> [0;32mI (4646) server_ota: SHA-256 for current firmware: : f3fb5c2695a2e00e742cd8a05d41539df43eb7ca1f258a2b558d5170c3078d95[0m
10:03:49.463 -> CheckOTAUpdate Partition: ESP_OK
10:03:49.497 -> WLan: ***, ***
10:03:49.497 -> [0;32mI (4716) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE[0m
10:03:49.530 -> [0;32mI (4716) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE[0m
10:03:49.640 -> [0;32mI (4846) phy: phy_version: 4180, cb3948e, Sep 12 2019, 16:39:13, 0, 0[0m
10:03:49.640 -> [0;32mI (4846) gpio: GPIO[33]| InputEn: 0| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
10:03:51.995 -> [0;32mI (7206) tcpip_adapter: sta ip: 192.168.10.135, mask: 255.255.255.0, gw: 192.168.10.1[0m
10:03:51.995 -> [0;32mI (7206) gpio: GPIO[33]| InputEn: 0| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
10:03:52.032 -> IP :  192.168.10.135
10:03:52.032 -> Autoflow: sleep for : 200ms
10:03:54.040 -> [0;32mI (9226) sntp: Boot count: 1[0m
10:03:54.040 -> [0;32mI (9226) sntp: Waiting for system time to be set... (1/10)[0m
10:03:56.030 -> [0;32mI (11226) sntp: Waiting for system time to be set... (2/10)[0m
10:03:58.008 -> [0;32mI (13226) sntp: Waiting for system time to be set... (3/10)[0m
10:04:00.006 -> [0;32mI (15226) sntp: Waiting for system time to be set... (4/10)[0m
10:04:02.008 -> [0;32mI (17226) sntp: Waiting for system time to be set... (5/10)[0m
10:04:04.027 -> [0;32mI (19226) sntp: Waiting for system time to be set... (6/10)[0m
10:04:06.025 -> [0;32mI (21226) sntp: Waiting for system time to be set... (7/10)[0m
10:04:08.032 -> [0;32mI (23226) sntp: Waiting for system time to be set... (8/10)[0m
10:04:10.008 -> [0;32mI (25226) sntp: Waiting for system time to be set... (9/10)[0m
10:04:12.021 -> [0;32mI (27226) sntp: The current date/time in Berlin is: Sat Sep  5 23:03:53 2020[0m
10:04:12.021 -> [0;32mI (27226) sntp: The current date/time in Berlin is: 2020-09-05_23:03[0m
10:04:12.021 -> time 20200906-100411
10:04:12.021 -> time 20200906-100411
10:04:12.057 -> Init Flash
10:04:12.057 -> Init Camera
10:04:12.057 -> [0;32mI (27236) sccb: pin_sda 26 pin_scl 27
10:04:12.057 -> [0m
10:04:12.057 -> [0;32mI (27236) gpio: GPIO[32]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 [0m
10:04:12.057 -> [0;32mI (27276) sccb: SCCB_Probe start[0m
10:04:12.578 -> [0;32mI (27766) sccb: SCCB_Probe start[0m
10:04:13.105 -> [0;32mI (28296) camera: Detected OV2640 camera[0m
10:04:13.105 -> [0;32mI (28296) gpio: GPIO[35]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
10:04:13.105 -> [0;32mI (28306) gpio: GPIO[34]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
10:04:13.105 -> [0;32mI (28306) gpio: GPIO[39]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
10:04:13.140 -> [0;32mI (28316) gpio: GPIO[36]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
10:04:13.140 -> [0;32mI (28326) gpio: GPIO[21]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
10:04:13.140 -> [0;32mI (28336) gpio: GPIO[19]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
10:04:13.140 -> [0;32mI (28346) gpio: GPIO[18]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
10:04:13.175 -> [0;32mI (28356) gpio: GPIO[5]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
10:04:13.175 -> [0;32mI (28366) gpio: GPIO[25]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
10:04:13.175 -> [0;32mI (28376) gpio: GPIO[23]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
10:04:13.208 -> [0;32mI (28386) gpio: GPIO[22]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
10:04:13.208 -> [0;32mI (28396) camera: Allocating 1 frame buffers (937 KB total)[0m
10:04:13.314 -> [0;32mI (28536) camera: Allocating 937 KB frame buffer in OnBoard RAM[0m
10:04:13.664 -> Autoflow: sleep for : 200ms
10:04:15.641 -> [0;32mI (30846) example: Starting server on port: '80'[0m
10:04:15.641 -> [0;32mI (30846) example: Registering URI handlers[0m
10:04:15.641 -> [0;32mI (30846) server_camera: server_part_camera - Registering URI handlers[0m
10:04:15.641 -> [0;32mI (30846) server_tflite: server_part_camera - Registering URI handlers[0m
10:04:15.676 -> [0;32mI (30856) server_ota: server_ota - Registering URI handlers[0m
10:04:15.676 -> Start tfliteflow.InitFlow(config);
10:04:15.676 -> [MakeImage]
10:04:15.676 -> ;LogImageLocation = /log/source
10:04:15.676 -> WaitBeforeTakingPicture=5
10:04:15.676 -> ImageQuality = 5
10:04:15.676 -> ImageSize = VGA
10:04:15.676 -> 
10:04:15.676 -> [Alignment]
10:04:15.676 -> InitalRotate=180
10:04:15.676 -> /config/ref0.jpg 119, 273
10:04:15.676 -> /config/ref1.jpg 456, 138
10:04:15.676 -> SearchFieldX = 20
10:04:15.676 -> SearchFieldY = 20
10:04:15.709 -> 
10:04:15.709 -> [Digits]
10:04:15.709 -> ;Model=/config/dig0622.tfl
10:04:15.709 -> Model=/config/dig0630s3.tflite
10:04:15.709 -> LogImageLocation = /log/digit
10:04:15.709 -> ModelInputSize 20, 32
10:04:15.709 -> digit1, 306, 120, 37, 67
10:04:15.709 -> digit2, 355, 120, 37, 67
10:04:15.709 -> digit3, 404, 120, 37, 67
10:04:15.709 -> 
10:04:15.709 -> [Analog]
10:04:15.709 -> ;Model=/config/ana0622.tfl
10:04:15.709 -> Model=/config/ana0630s2.tflite
10:04:15.709 -> LogImageLocation = /log/analog
10:04:15.709 -> ModelInputSize 32, 32
10:04:15.709 -> analog1, 444, 225, 92, 92
10:04:15.709 -> analog2, 391, 329, 92, 92
10:04:15.743 -> analog3, 294, 369, 92, 92
10:04:15.743 -> analog4, 168, 326, 92, 92
10:04:15.743 -> 
10:04:15.743 -> [PostProcessing]
10:04:15.743 -> PreValueUse = True
10:04:15.743 -> [PreValue]
10:04:15.743 -> time = 2000-01-01_00-00-00
10:04:15.743 -> abort() was called at PC 0x40105866 on core 0
10:04:15.743 -> 
10:04:15.743 -> ELF file SHA256: e880dd3123be5bcb
10:04:15.743 -> 
10:04:15.743 -> Backtrace: 0x4008a5f5:0x3fffa740 0x4008a98d:0x3fffa760 0x40105866:0x3fffa780 0x40184ce5:0x3fffa7a0 0x400d84d1:0x3fffa7c0 0x400dd98b:0x3fffa7f0 0x400ddd8b:0x3fffad40 0x400d99b5:0x3fffaf90 0x400d40af:0x3fffb440 0x400d41eb:0x3fffb490 0x40093bdd:0x3fffb4e0
10:04:15.777 -> 
10:04:15.777 -> Rebooting...

**Comment by jomjol** [comment]
This problem is known since yesterday and patch is already out. I assume you downloaded yesterday?
The problem is a wrong format for a file on the SD-card: `/config/prevalue.ini`

Three options for a quick fix: 
1. download and replace this file from the new version (v1.0.1)
2. Change in the `/config/config.ini` the value for `PreValueUse = True` to `PreValueUse = False`
3. Delete the file `prevalue.ini` on the sd card

Sorry for the bug and it hopes, this helps! Please give a short confirmation.
Thx,
  jomjol

**Comment by ideaweb** [comment]
Thx for you fast reply/fix, its working now...

**Comment by jomjol** [comment]
Thx for the feedback
