### ISSUE TITLE
Sensus Analog Gas Meter - White Background, Black Dials

### ISSUE THREAD

**Issue by dadcoachengineer** [jomjol/AI-on-the-edge-device#3010]
### Files

[data.zip](https://github.com/jomjol/AI-on-the-edge-device/files/14729039/data.zip)

**Comment by caco3** [comment]
See https://github.com/jomjol/AI-on-the-edge-device/discussions/2998

**Comment by dadcoachengineer** [comment]
Thank you @caco3 

I removed the lower gauges from my ROI but there still does not seem to be training data for white background with black gauges so I am providing labeled images.

https://jomjol.github.io/neural-network-analog-needle-readout/

**Comment by caco3** [comment]
@dadcoachengineer The data needs to be added to the training data first by @jomjol. It usually takes a while until he can do it.
My comment above was only to add a link to the screenshot corresponding to your training data.

**Comment by jomjol** [comment]
see: https://github.com/jomjol/AI-on-the-edge-device/blob/rolling/sd-card/config/ana-cont_1300_s2.tflite

**Comment by dadcoachengineer** [comment]
Possibly need to provide some additional training data?

<img width="1041" alt="image" src="https://github.com/jomjol/AI-on-the-edge-device/assets/6666082/c8546488-ab33-4b99-9dc1-9d6637d7b987">

**Comment by jomjol** [comment]
No, you need to improve the illumination conditions (too dark!) and sharpness.
