### ISSUE TITLE
Actaris P50 Wasserzähler

### ISSUE THREAD

**Issue by hackman6** [jomjol/AI-on-the-edge-device#3013]
### The Feature

Hallo,
bevor ich mir die Mühe mache, Fotos vom analog-Teil meines Actaris P50 damit sie trainiert werden können, wollte ich mal hören, ob das vielleicht schon jemand gemacht hat. Hier jedenfalls habe ich sie nicht gefunden :-(
So sieht der Zeiger aus (Schärfer geht's nicht. Der Zeiger liegt in einer anderen Ebene, als die digitalen Stellen) und wird fälschlicher Weise als 8.3 erkannt. Witziger Weise erkett AI on the edge nicht die Nadel sondern eine Kante des hinteren Teils.

![10000](https://github.com/jomjol/AI-on-the-edge-device/assets/31844748/e647f864-7097-44b9-8770-7c1812464bff)

**Comment by caco3** [comment]
Ich sehe keine Skalierung von deinem Zeiger, fehlt das ganz oder ist es einfach ausserhalb des Bildes?
SO wie ich da sehe, kommst Du nicht darum herum, Bilder aufzunehmen für Trainingsdaten.

**Comment by SybexX** [comment]
![Unbenannt](https://github.com/jomjol/AI-on-the-edge-device/assets/587201/2c420117-0858-466d-8fc8-ff84082fb58d)

**Comment by hackman6** [comment]
Genau so sieht der Zähler aus, wenn alles scharf ist ;-)
So ein Ärger. Mal sehen, wie ich das mit den Bildern mache. Endweder ich drehe dafür noch mal am Fokus oder ich bemühe eine externe Kamera.

**Comment by caco3** [comment]
Ich mache den Issue mal zu, da länger nichts mehr gelaufen ist.
@hackman6, falls Du Trainingsdaten beisteuern kannst, kannst Du ihn gerne wieder aufmachen.

**Comment by mircebirke1399** [comment]
@hackman6  Welches Gehäuse hast ud gedruckt für deinen Zähler?
