### ISSUE TITLE
MQTT Trouble

### ISSUE THREAD

**Issue by papudeal** [jomjol/AI-on-the-edge-device#303]
I have installed mosquitto broker in to a vm running ubuntu, actually i have conection with mosquitto broker and de ESP 32, i also have installed node red in the VM to try to catch the mqtt but i cant recive the mqtt
![image](https://user-images.githubusercontent.com/88558810/128565256-af904004-6ac2-48a1-bca7-8783cb656b23.png)
in the image you can see that the client md1 that is the esp32 its connected 
![image](https://user-images.githubusercontent.com/88558810/128565331-02c18041-043e-4376-8899-edb567cdebe1.png)
here are my configurations,
in node red i have configure the nodes
![image](https://user-images.githubusercontent.com/88558810/128565443-612091c5-e786-4de2-b427-070b998161ea.png)
but i cant recive the data 

here are the other configuration of the node red
![image](https://user-images.githubusercontent.com/88558810/128565707-ecf1c30f-51db-479f-90ed-a7aff5245c7a.png)

**Comment by jomjol** [comment]
maybe you can test the main topic withouth a ``/``?

**Comment by papudeal** [comment]
i tried like this 
![image](https://user-images.githubusercontent.com/88558810/128566078-5bfbdff2-9671-402d-8e0a-ec478ef81c34.png)
![image](https://user-images.githubusercontent.com/88558810/128566142-159c03f7-d734-4fd6-9d64-8cabda1ddf63.png)

and doesnt work either

**Comment by jomjol** [comment]
for me everything look alright and I assume, that the problem is rather on the mqtt side. But I'm not an mqtt expert

**Comment by papudeal** [comment]
i solved the problem!!!
![image](https://user-images.githubusercontent.com/88558810/128579107-c7ff60ab-810f-4c92-81ed-e026457f887d.png)
it was neccesary to add into the topic /main/value
![image](https://user-images.githubusercontent.com/88558810/128579190-d23e0915-2260-42e4-8f0c-79abe5b948d2.png)

**Comment by sygys** [comment]
@papudeal could you please share a screenshot of the settings in the camera software so i can see what you put there as MainTopic.

I still cant seem to get it to work
