### ISSUE TITLE
Start only with the ESP32-CAM-MB board

### ISSUE THREAD

**Issue by Sectorchan** [jomjol/AI-on-the-edge-device#3032]
### The Feature

I had on another ESP32-CAM project the issue that the board wont start due brownout detection.
My current  AI on the edge only runs with the ESP32-CAM-MB board, with 5V only it wont start.

I've found out that you have to disable the brownout detection when you are sure that the used power supply is from a good quality and stable over 500mA.

Since I've not forked or did anything here, I cant open a pull request and want to add this as a Feature Request here:
In order to deactivate the brownout detection you have to:

```
#include "soc/soc.h"
#include "soc/rtc_cntl_reg.h"
```

and:

```
void setup() {
  WRITE_PERI_REG(RTC_CNTL_BROWN_OUT_REG, 0);
}
```

**Comment by caco3** [comment]
But the Brown-out-detection is an important feature which helps to detect insufficient power! Disabling it has no real benefit.

If you board only works without it, I would expect you have bad hardware.

**Comment by Sectorchan** [comment]
And the same esp32-cam board works with the same power supply but in addition with the esp32-cam-mb board without the brownout detection issue

**Comment by SybexX** [comment]
https://randomnerdtutorials.com/esp32-cam-troubleshooting-guide/

**Comment by Sectorchan** [comment]
This does not solve my question. 
How can you identify that the board is bad when you don't get the brownout message when using the same usb power supply for with the esp32-cam-mb board compared without the -mb board but with the same usb cable and supply?

**Comment by SybexX** [comment]
![Unbenannt](https://github.com/jomjol/AI-on-the-edge-device/assets/587201/7f487f81-bc23-499a-9e41-ecc094fe9cda)

**Comment by Slider0007** [comment]
@Sectorchan 
Disabling brownout is already prepared in software, but it's not comiled in. You can compile your own version and disable brownout by only setting this definition.

https://github.com/jomjol/AI-on-the-edge-device/blob/7e5f6bf4a55c30a437ba8645e9e683d491c9e19b/code/main/main.cpp#L181

It's not recommended to disable brownout, because unrecognised voltage drops could lead to undefined device behaviour.

**Comment by Sectorchan** [comment]
Maybe still better instead to complain and discuss with the vendor of the board. Could be an advanced feature or similiar
