### ISSUE TITLE
Fehlendes version.txt

### ISSUE THREAD

**Issue by wurschtbrot01** [jomjol/AI-on-the-edge-device#3036]
### Issue

hab ein kleines Problem bei der Installation.
und zwar.
den Esp kann ich über den Online Flasher ganz normal aufspielen inkl der Meldung zum Schluss
"Erfolgreich".
Quelle https://jomjol.github.io/AI-on-the-edge-device/index.html

danach habe ich die Sd karte gemacht und hier ist das erst Problem.
dann lade ich die Sd-Karten Dateien, entpacke sie und kopiere sie auf meiner Sdkarte mit dem Forma FAT32
Quelle
https://github.com/jomjol/AI-on-the-edge-device/releases/tag/v15.7.0

dies setze ich dann in meinen ESP ein und lass ihn neu booten...
jetzt bekomme ich die Fehlermeldung wenn ich mich auf dem Webserver anmelde
"0x00000010" bzw. 4 mal blinkende LED.
Nach einen Abgleich mit dem Quelltext, SD-Karte und heruntergeladene Zip-Dateien,
fehlt mir diese Datei immer wieder ... version.txt

/* check if file exists: version.txt */
if (stat("/sdcard/html/version.txt", &sb) != 0) {
LogFile.WriteToFile(ESP_LOG_ERROR, TAG, "Folder/file check: File /html/version.txt not found");
bRetval = false;

jetzt habe ich aus einer Früheren Version 13.x.x
diese Datein genommen und in meiner 15.7.0 eingefügt.

jetzt "bootet" er ohne Fehlermeldung oder Blinkcode und ich komme auf dem eigentlichen Webserver.
ABER er ist extrem langsam und hängst sich immer auf so das ich ihn nicht einrichten kann, obwohl das Warnsignal sehr gut ist weil er direkt neben dem AP steht und dies auch meldet.

Und eine Fehlermeldung habe ich auch bekommen das die Versionen nicht zueinander
passen.
was Wohl mit meiner kopierten Version.txt Datei zu tun hat.
20240412_170232.jpg

kann mir da einer Weiter Helfen?
Gruß Michael
![Unbenannt](https://github.com/jomjol/AI-on-the-edge-device/assets/166860571/f980b57f-c874-4907-adf9-439e5baa8c56)
![20240412_170232](https://github.com/jomjol/AI-on-the-edge-device/assets/166860571/55ff051a-bad7-4403-88f8-fe695bc9e9b9)

**Comment by SybexX** [comment]
da ist wohl was beim kopieren schief gegangen
[version.txt](https://github.com/jomjol/AI-on-the-edge-device/files/14962253/version.txt)

**Comment by wurschtbrot01** [comment]
> da ist wohl was beim kopieren schief gegangen [version.txt](https://github.com/jomjol/AI-on-the-edge-device/files/14962253/version.txt)

wie meinst du das beim Kopieren 
selbst in der Roh ZIp datei ist nirgend die Version.txt drin und ich habe die glaube ich 20mal runtergeladen ;)

**Comment by SybexX** [comment]
ich habe gerade das manual, remout und das update runtergeladen und bei allen war sie drine

**Comment by wurschtbrot01** [comment]
> ich habe gerade das manual, remout und das update runtergeladen und bei allen war sie drine

ich gerade auch nochmal über diesen link und wieder nix drin....
![version txt](https://github.com/jomjol/AI-on-the-edge-device/assets/166860571/39874e68-ae00-42fa-b4ad-f8e83ed1e48a)


https://github.com/jomjol/AI-on-the-edge-device/releases/tag/v15.7.0
über diesen Link und dann ganz unten auf Source code
Source code(zip)

**Comment by SybexX** [comment]
da ist sie nicht drin, sie wird erst beim Kompilieren erzeugt

**Comment by wurschtbrot01** [comment]
ok jetzt ist er zumindest auf anhieb damit gestartet,
aber an was kann das liegen das er extrem schlecht reagiert und teilweiße die seit mehrmals aktualisiert werden muss bis über haupt was kommt.
bzw. ich komm ja nichmal durch die anfängliche Config durch... ggf. ESP defekt

**Comment by wurschtbrot01** [comment]
![1](https://github.com/jomjol/AI-on-the-edge-device/assets/166860571/09c79e43-a510-43ea-9b44-e201d0e31c8f)
![2](https://github.com/jomjol/AI-on-the-edge-device/assets/166860571/7c3626a3-d80b-49ff-be1b-e4cc930ab98a)

**Comment by SybexX** [comment]
oder beim flashen was schief gegagnen, verwende am besten gleich das aktuelle rolling, da sind einige Probleme gefixt worden.
https://github.com/jomjol/AI-on-the-edge-device/actions/runs/8652202431

**Comment by wurschtbrot01** [comment]
gibts da ne Anleitung für anfänger zum Flashen ;)

**Comment by SybexX** [comment]
wenn du in der config.ini den Wert "SetupMode = false" setzt, kannst du die Einrichtungsgeschichte überspringen und dann per OTA die firmware aktualisieren

**Comment by wurschtbrot01** [comment]
Also, jetzt hat es geklappt.
konnte den esp mit dem flashtool löschen und habe ihn dann erneut aufgespielt.
jetzt läuft er. konnte zwar nicht den Einrichtungsassistenten nutzen aber durch den Tip von oben konnte ich das überspringen und manuell einrichten...
danke nochmal für den Support
