### ISSUE TITLE
Overlook the image

### ISSUE THREAD

**Issue by userosos** [jomjol/AI-on-the-edge-device#3037]
### Issue

Hi! I have some Overlook the inage and it can't digitalization the image. I set in the led on the ESP32 from LED LAMP but it can't help. How i can remove the Overlook  from the image?
![canvas](https://github.com/jomjol/AI-on-the-edge-device/assets/22872748/0ca10d8f-bb76-40af-94cc-44ddfa00882b)

**Comment by SybexX** [comment]
which version are you using and what are your camera settings?

**Comment by userosos** [comment]
> which version are you using and what are your camera settings?

<html><body>
<h3>Build Info</h3>


Firmware version: | Release: v15.7.0 (Commit: 0d0b018+)
Firmware build time: | 17.02.2024 00:15
Web interface version: | Release: v15.7.0 (Commit: 0d0b018+)


</body>
</html>
[config.zip](https://github.com/jomjol/AI-on-the-edge-device/files/14968517/config.zip)

**Comment by SybexX** [comment]
disable negatives

**Comment by userosos** [comment]
> disable negatives
> 
> ![cam_settings2](https://private-user-images.githubusercontent.com/587201/322230450-7196bb54-cb17-42e2-b52f-4c3697bd8318.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwNzk5MzIsIm5iZiI6MTcxMzA3OTYzMiwicGF0aCI6Ii81ODcyMDEvMzIyMjMwNDUwLTcxOTZiYjU0LWNiMTctNDJlMi1iNTJmLTRjMzY5N2JkODMxOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNFQwNzI3MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZWIxZGRlNGMwMTdhYzQwOTEzNDNjOGY1YzIyYmVjYjc2ZmQ0MmQ0Y2YzMGE2NjVjMDhmNDBhZTAyYmJlM2RmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2c--AOEJkSc86BgFR9qAfDJtxJdLoiwHtT7EkXI3vq0)
> 
> save and reboot

![alg_roi](https://github.com/jomjol/AI-on-the-edge-device/assets/22872748/203d1ea0-6f60-4248-b0ba-26890a8da93e)
Ok.I do it. It not wok ok
 - <html><body>

Raw Value
--
00205.9


</body>
</html>

**Comment by SybexX** [comment]
This is probably due to the reflection of the light in the area, try reducing the lighting.
or use the current rolling and zoom in https://github.com/jomjol/AI-on-the-edge-device/actions/runs/8652202431

**Comment by userosos** [comment]
> This is probably due to the reflection of the light in the area, try reducing the lighting. ![Belichtung](https://private-user-images.githubusercontent.com/587201/322273891-4b49ac87-01dc-4ca3-8c6d-5397ef08d852.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNzkxMTMsIm5iZiI6MTcxMzE3ODgxMywicGF0aCI6Ii81ODcyMDEvMzIyMjczODkxLTRiNDlhYzg3LTAxZGMtNGNhMy04YzZkLTUzOTdlZjA4ZDg1Mi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNVQxMTAwMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZDM0ZDBlNTFkYzZkMTk3NjYyZGRiNjk5YzhlMTZjNzJkYzlhZTJlMDhjNDEzOWQ3NDcxZDljYzdlNjE2ODFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.n3jjwpPwZKZRrTkdAz9sjM5ml43WcpEsxYpnV_vTaS4)
> 
> or try the current rolling and zoom in https://github.com/jomjol/AI-on-the-edge-device/actions/runs/8652202431

I was reducing the lighting but it cant help. I think that i need use someone like diflector of lighting for fix the blink (but what?).

**Comment by SybexX** [comment]
https://jomjol.github.io/AI-on-the-edge-device-docs/External-LED/

**Comment by userosos** [comment]
![изображение](https://github.com/jomjol/AI-on-the-edge-device/assets/22872748/809ccba7-b004-4e69-99ba-2074ce79b1e0)
Mount an external LED - work ok. Thx fjr help!
