### ISSUE TITLE
Question: What does the double border stand for?

### ISSUE THREAD

**Issue by TheLion** [jomjol/AI-on-the-edge-device#304]
Hi,

I was wondering what the double border in the ROI selection stands for?

What border should I fit the digits in when drawing the rectangle?

**Comment by jomjol** [comment]
The outer border is the ROI, that is cut out for the image recognition. As the number itself should not touch the border of the image, the inner frame is the one, which should fit the size of the digit:
![grafik](https://user-images.githubusercontent.com/30766535/128642645-34a23959-6200-4956-bc00-a972cc907f0b.png)
