### ISSUE TITLE
Webpage refresh not working anymore (Firefox)

### ISSUE THREAD

**Issue by friedpa** [jomjol/AI-on-the-edge-device#3041]
### The Problem

I noticed today that the Webpage in Firefox is not working any longer. Unfortunately I cannot say since which version this behaviour occured. I remember that tis refresh was set to 5 Minutes.

### Version

latest rolling: Commit: 32282ec+

### Logfile

```shell
N/A
```

**Comment by SybexX** [comment]
I think it's because of Firefox, because in my opinion the page is updated using a cookie.

the errors it gives:

Synchronous XMLHttpRequests on the main thread should no longer be used because it has detrimental effects on the end user experience. For further help see https://xhr.spec.whatwg.org/#sync-warning readconfigcommon.js

The page cookie does not have a valid value for the SameSite attribute. Soon, cookies without the "SameSite" attribute or with an invalid value for it will be treated as "Lax". This means the cookie is no longer sent to contexts belonging to a third party. If your application requires the cookie in these contexts, please add the "SameSite=None" attribute to it. For more information about the SameSite attribute, see https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite.

**Comment by caco3** [comment]
Ich denke, das hat nichts mit den cookies zu tun. Das cookie haben wir ja nur, damit wir bei einem Page refresh wieder auf dem gleichen Tab landen.

Das Problem mit den `Synchronous XMLHttpRequests` ist, dass sie synchron sind. D.h., wenn man einen Request sendet, bleibt das ganze WebUI blockiert, bis die Antwort oder Timeout kommt. Das ist leider nicht sehr responsive, und ist nicht mehr zeitgemäss.

Eigentlich sollten wir das UI umbauen, dass das alles asynchron passiert. Aber das ist leider einiges an Arbeit, weshalb ich das von meiner Seite auf die lange Bank geschoben habe ala, geht ja auch ohne.

Aber zu deinem Problem:
Ich meine auch, dass das mal funktioniert hat. Ich würde erwarten, dass das Web UI einen Timer hat (Javascript `setInterval()`), der die relevanten Daten periodisch auffrischt. Aber ich finde nichts dazu und sehe auch nicht, dass da mal etwas entfernt wurde :(
Weist Du noch, was alles aktualisiert wurde? War es einfach alles auf der Overview-Seite?

**Comment by Slider0007** [comment]
Hier wird das Refresh der overview page realisiert.
 https://github.com/jomjol/AI-on-the-edge-device/blob/rolling/sd-card%2Fhtml%2Foverview.html#L172

**Comment by SybexX** [comment]
Diese Funktion ist ja immer noch vorhanden, nur scheint dies nicht zu funktionieren. Ich habe mal im Internet nach Refresh gesucht und auch was funktionierendes gefunden, nur kamm jedes mal beim Refresh eine Meldung seitens Firefox und deshalb habe ich alles verworfen. Denn ob ich jetzt jedes mal beim Firefox auf "zulassen" klicke oder auf den Reiter Overview um die Seite zu aktuallisieren, macht für mich kein Unterschied/Sinn.

**Comment by friedpa** [comment]
Es war nur die Overview Seite die Refreshed wurde. Ich habe meine zwei Systeme auf einem Übersichtsmonitor im Büro angezeigt und das war halt praktisch mit dem AutoRefresh. Man kann das Problem in Firefox aber auch so lösen, dass man ein Addon wie TabReloader verwendet.

**Comment by caco3** [comment]
> Hier wird das Refresh der overview page realisiert. https://github.com/jomjol/AI-on-the-edge-device/blob/rolling/sd-card%2Fhtml%2Foverview.html#L172

Danke!
Und soweit ich sehen kann, funktioniert es auch noch, zumindest unter Linux mit Firefox 124:
![grafik](https://github.com/jomjol/AI-on-the-edge-device/assets/1783586/812d88a3-8079-4e45-ab12-5fbb8aab362d)

Der richtige Weg wäre, wo etwas mittels Websocket zu lösen. Ich hatte das mal in https://github.com/jomjol/AI-on-the-edge-device/pull/2370 versucht, allerdings lief es nicht stabil. Vermutlich passen einige Thread sizes noch nicht (obwohl ich da recht rumgespielt habe).

Langfristig müssen wir aber auch auf asynchronous wechseln :(

**Comment by SybexX** [comment]
jetz weiß ich weshalb Autorefresh nicht geht^^
in der overview, index und einigen anderen Dateien wurde aus  "xhttp.open("GET", url, false);" auf "xhttp.open("GET", url, true);" gestellt, das wurde bestimmt gemacht um den Fehler zu beseitigen, nur verursacht dies halt Probleme.

**Comment by caco3** [comment]
Habe das gerade mal bei mir getestet. Firefox refresht immer noch automatisch wie gehabt!

Getestet mit dem neusten rolling.

@friedpa Kannst Du das bei dir nochmals nachstellen?

**Comment by SybexX** [comment]
Benutzt du Linux oder Windows?
Unter Windows 10 funktioniert es bei mir leider auch nicht^^

**Comment by caco3** [comment]
ich verwende Linux.
und ja, es sieht sehr nach einem client problem aus.

**Comment by friedpa** [comment]
Gleich wie @SybexX: seit einem Update von Firefox funktioniert der autom. Refresh wieder. Ich habe leider vergessen das Ticket zu schließen... sorry!
by the way: Früher gabe es ein nettes ICON beim Reiter in Firefox...

![grafik](https://github.com/user-attachments/assets/83e3705d-97f4-4f32-b2b9-28bf318532f1)

**Comment by friedpa** [comment]
Closed (fixed by Firefox Developers).

**Comment by caco3** [comment]
> by the way: Früher gabe es ein nettes ICON beim Reiter in Firefox...

Stimmt.
Habe es mir gerade angeschaut. Auch da scheint Firefox ein Problem zu haben. Mit Chrome/Chromium geht es nämlich.
Ich habe jetzt die svg-Variante entfernt, damit geht es auch im Firefox wieder: https://github.com/jomjol/AI-on-the-edge-device/commit/2c69e90fac60d54e7766532f2dfef86c90dcca51

**Comment by friedpa** [comment]
ICON in Firefox wieder vorhanden. 
Issue anyway closed, so thanks for your effort.
