### ISSUE TITLE
We are in Setup Mode -> Not starting Auto Flow!

### ISSUE THREAD

**Issue by AhmedThabit** [jomjol/AI-on-the-edge-device#3042]
After installation and adding WiFi username and password, it starts and obtains an IP address, but nothing appears in the browser.

I (9786) WIFI: Connected to: Thabit, RSSI: -56
I (9836) wifi:AP's beacon interval = 102400 us, DTIM period = 2
I (12706) wifi:<ba-add>idx:0 (ifx:0, 0a:c5:e1:06:72:54), tid:0, ssn:2, winSize:64
I (13286) esp_netif_handlers: sta ip: 192.168.43.7, mask: 255.255.255.0, gw: 192.168.43.1
I (13286) WIFI: Assigned IP: 192.168.43.7
I (27146) MAIN: Device info: CPU cores: 2, Chip revision: 100
I (27146) MAIN: SD card info: Name: SU16G, Capacity: 15193MB, Free: 15181MB
I (29156) MAIN SERVER: Starting server on port: '80'
I (29156) MAIN SERVER: Registering URI handlers
I (29156) MAINCTRL: server_main_flow_task - Registering URI handlers
I (29156) OTA: Registering URI handlers
I (29156) GPIO: start GpioHandler
I (29166) GPIO: register GPIO Uri
I (29166) GPIO: server_GPIO - Registering URI handlers
I (29166) MAIN: Initialization completed successfully
I (29186) main_task: Returned from app_main()
I (29216) ov2640: Set PLL: clk_2x: 0, clk_div: 0, pclk_auto: 0, pclk_div: 8
I (31286) LOGFILE: Set log level to ERROR
I (31296) GPIO: read GPIO config and init GPIO
I (31306) GPIO: GPIO init completed, handler is disabled
I (31306) MAINCTRL: We are in Setup Mode -> Not starting Auto Flow!
I (37606) MAINCTRL: Autostart is not enabled -> Not starting Flow

**Comment by AhmedThabit** [comment]
yes
![image](https://github.com/jomjol/AI-on-the-edge-device/assets/7771838/7641adf1-5195-40c4-a966-d616b9f426d8)

**Comment by AhmedThabit** [comment]
Log:

![image](https://github.com/jomjol/AI-on-the-edge-device/assets/7771838/f9e71c99-0eb2-45ad-8c17-81496fbd3d35)

**Comment by AhmedThabit** [comment]
update 2 :

![image](https://github.com/jomjol/AI-on-the-edge-device/assets/7771838/1e245915-1617-4620-bfdf-6e98da1e39fd)

**Comment by Slider0007** [comment]
Du kannst noch folgende Dinge prüfen / beachten, um die WLAN Performance zu verbessern. 
 https://github.com/jomjol/AI-on-the-edge-device/discussions/2406#discussioncomment-8348127

**Comment by Slider0007** [comment]
@AhmedThabit 

Congrats that is working now.

For me it's quite interesting to hear the second time that is related to end device antivirus scanner. I cannot explain right now, though.

@jomjol, @caco3, @SybexX, @haverland: I added all the recent findings related to bad WebUI responsiveness to documentation [FAQs -> 1.2](https://jomjol.github.io/AI-on-the-edge-device-docs/FAQs/). Could be extended in future...

**Comment by caco3** [comment]
> I added all the recent findings related to bad WebUI responsiveness to documentation
Thanks!
