### ISSUE TITLE
No reconnect after WLAN was unavailable

### ISSUE THREAD

**Issue by Wuehli** [jomjol/AI-on-the-edge-device#305]
Hi,

i've just installed my first Wasserzähler :-)
It's a great project! Many thanks for this!

But i got on issue, our WLAN is not available druing the night (11pm - 7am)
unfortunately the ESP doesn't reconect after wlan is available again, i always have to reboot it.

Is there any solution for this?

Thanks
Regards

**Comment by jomjol** [comment]
The reconnect is limited to 1000 retries. I have removed this limit to infinity in the "rolling" branche. Please test it. it will be released in the next version into the master branch.

**Comment by jomjol** [comment]
corrected in release v8.1.0
