### ISSUE TITLE
Question about tflite files

### ISSUE THREAD

**Issue by papudeal** [jomjol/AI-on-the-edge-device#306]
Excuse me for the question, i want to ask what are for the .tflite files on the github of the neural network, i saw that are a lot of versions like dig1110sq3.tflite or dig1110sq2.tflite and the other files, this can be load on the orginial firmware? or what are these for?, thank you for your answer

**Comment by jomjol** [comment]
These are different version of the neural networks. Increasing numbers (1110 --> version 11.1.0) typically are based on additional trainings files. s1 ... s4 are different versions (bigger to smaller) and "q" means quantized version.
