### ISSUE TITLE
LogfileRetention does not cleanup properly for Digits

### ISSUE THREAD

**Issue by mdax82** [jomjol/AI-on-the-edge-device#307]
It seems the cleanup of old stored images is not working properly. I recognized it for "Digit" so far:

setting:

 [Digits]  
LogImageLocation = /log/digit  
LogfileRetentionInDays = 2

Though it does not keep only 2 days - the data is stored infinite.

At some point based on the amount of data in /log/digit/ every night at 1st run after midnight watermeter crashed. Though it should not have hit the FAT32 limitations at that point.

Analog which has similar setting

[Analog]
LogImageLocation = /log/analog
LogfileRetentionInDays = 2

does not seem to have the issue.

RemoveOldLogs would be called at every execution not just once per day right? 

Running master - v8.0.5 - 2021-08-01 but based on the data in /log/digit  it was an issue since I setup v8 from scratch.

thx

**Comment by jomjol** [comment]
Thanks for your feedback. It's possible, that there are some leaks in the code in this part. An extended test and maybe new revision could be done. Currently I'm not following this directly, as I don't have capacity to do so.
I'll put it on the list of long term topics.
Best regards,
  jomjol

**Comment by mdax82** [comment]
Thanks, no immediate issue at all I had it enabled for debug but forgot to disable ;) Besides this it works like a charme 👍
