### ISSUE TITLE
Zoomfaktor ändert sich zufällig

### ISSUE THREAD

**Issue by Zugschlus** [jomjol/AI-on-the-edge-device#3073]
### The Problem

Hallo,
ich wollte das neue experimentelle Zoom-Feature ausprobieren, habe Expertmodus eingeschaltet, Zoom aktiviert und den Zoomfaktor auf 1 gestellt (andere Werte als 0 und 1 scheinen nicht zu gehen). Wenn ich auf "Update Reference Image" klicke, scheint sich die Bildgröße zu verändern. Mal ist es so wie ohne Zoom, mal ist es wie mit Zoom, mal ist es auch so groß dass man nur noch die letzten zwei Ziffern des Zählwerks im Ausschnitt hat.
Das Log scheint nur die im Hintergrund weiter laufende Bilderkennung zu enthalten, nicht die Arbeit im Webinterface.
Grüße
Marc

### Version

v15.7.0 (Commit: 0d0b018+)

### Logfile

```shell
There was an error creating your Issue: body is too long (maximum is 65536 characters).
```

### Expected Behavior

Bild bleibt stets so groß wie eingestellt, man kann mehr als nur zwei Bildgrößen auswählen.

### Screenshots

There was an error creating your Issue: body is too long (maximum is 65536 characters).

**Comment by SybexX** [comment]
verwende bitte das aktuelle rolling für zoom https://github.com/jomjol/AI-on-the-edge-device/actions/runs/8992820658
