### ISSUE TITLE
Unexpected "rouding" of recognized digit

### ISSUE THREAD

**Issue by koying** [jomjol/AI-on-the-edge-device#3074]
### Issue

My apologies if I didn't found the proper documentation, but I don't quite understand the link between what is recognized, and what is reported, sometimes.

Here is an example:

![image](https://github.com/jomjol/AI-on-the-edge-device/assets/164740/7cc9980c-2c27-410c-8001-3832b406e9e1)

I don't understand why the rightmost digit is reported as a "2" instead of a "3", while I understand the "2.9" as "It's between 2 and 3, with a 90% chance it's a 3"

Even more confused as the leftmost digit is correctly reported as a "4"

**Comment by SybexX** [comment]
If another number follows the processing number, an algorithm is applied; for the last number, the .9 is simply ignored.
activate Extendedresolution for 4697.2 >> 4697.29
https://jomjol.github.io/AI-on-the-edge-device-docs/Correction%20Algorithm/#extendedresolution
