### ISSUE TITLE
[Feature Request] Compatible with other device

### ISSUE THREAD

**Issue by slimjet4u** [jomjol/AI-on-the-edge-device#3077]
### The Feature

There is a very tight hardware requirement, there are duplicate and fake hardware all around in the market. Why do we have to flash the device. Many device don't have that capability. Why it isn't as simple as other projects where we simply upload the code using arduino ?

I have never seen such a hardware that has so much complexity.

**Comment by jomjol** [comment]
Your totally right, this is a very complex softwre and that is the reason, why you cannot use the Arduino Environment.
You need to use various other libraries, such as Tensorflow, zip-libraries, ... .
This requires a solid programming environment such as VSCode with the Espressif plugin
