### ISSUE TITLE
Sending multiple results to influxdb v2

### ISSUE THREAD

**Issue by Viko1690** [jomjol/AI-on-the-edge-device#3085]
### The Feature

Hello,

is it possible to send multiple results to an InfluxDB? Actually it only transmit the latest count of the watermeter…
It would be nice to send also the flow rate. Unfortunately the docs does not describe very much about the influxdb connectivity.

Thank in advance and keep up the great work.
Viktor

**Comment by caco3** [comment]
This is currently not possible.
And I think it should be easy enough to calculate the rate directly in influxDb. Overall, it is just the difference since the last value divided by the time delta.

**Comment by Viko1690** [comment]
Ok, thanks for your feedback! In the mean time I also changed to mqtt to get more information like wifiRSSI.
