### ISSUE TITLE
Cyclic Restart configurable

### ISSUE THREAD

**Issue by Brueller1982** [jomjol/AI-on-the-edge-device#3102]
### The Feature

Is it possible to add an option for a cyclic restart of the device maybe after a certain time or after a specified number of Recognition cycles?
To avoid that the system hangs after a certain time.

**Comment by caco3** [comment]
if you have issues with a device hanging after a while, you first should solve those issues. Normally, this is no issue, my devices run for months without issues.

Can you provide a debug log when it starts hanging?
Usually such issues are due to bad hardware or a bad SD card.

**Comment by nliaudat** [comment]
Can be done with the rest api 

https://jomjol.github.io/AI-on-the-edge-device-docs/REST-API/
