### ISSUE TITLE
how to add the dht library

### ISSUE THREAD

**Issue by ornea** [jomjol/AI-on-the-edge-device#311]
Not an issue - Very new to platformio but have successfully compiled AI-on-the-edge-device and imported an arduino DHT project.

However, I am unable add DHT support to this project.  

Platformio repeatedly reports that it can not find DHT.h regardless of how I reference the file or where I put it, (unless it is in the same directory as one of the components libraries)

I have also used platformio to install the library which seems to install ok but again I can not work out how to #include "DHT.h" without error.

Any hints on how I add a arduino library to this project?

Thanks jomjol for making available an awesome project with some awesome code making AI available to me and the masses so I can do what I do best which is take some fine code and tailor it to do my thing while morphing it into something horrible and unrecognisable

**Comment by jomjol** [comment]
Hi, this is a major change in the code and I would not recommend to do so. If you send me your private email, I can give some advice.

**Comment by ornea** [comment]
Hi, thank you for the generous offer, but I figure your time is better spent on the steady stream of more important issues.

I have your code, so we spend some time figuring out how it goes together.
