### ISSUE TITLE
Need help with HA auto discovey

### ISSUE THREAD

**Issue by Dillton** [jomjol/AI-on-the-edge-device#3120]
### Issue

Hello.

I have set up my meters finally after many hours of fine tuning the cameras 😄  and now I am at stage of adding my watermeters to HA.
So I have set the mqtt parameters everything like this:
![image](https://github.com/jomjol/AI-on-the-edge-device/assets/68992112/a37d47ae-26da-4e0c-ab1b-29e09dc8ac76)

I can see all the data in MQTT explorer were received by MQTT broker (confings and actual reading values) but no device was populated in HA.
![image](https://github.com/jomjol/AI-on-the-edge-device/assets/68992112/eae2f088-b341-443d-91fc-96a3b8c60f2b)

Also logs confirms that eveything was published:
![image](https://github.com/jomjol/AI-on-the-edge-device/assets/68992112/0a243a49-4619-4d0f-ab7c-3f89692c3024)

Can anyone help me with this?

**Comment by henrythasler** [comment]
The current release version does not correctly derive the HA service discovery topic from a nested topic as Main Topic. This was fixed with https://github.com/jomjol/AI-on-the-edge-device/pull/3088. Either reduce the Main Topic to one level (e.g. "cold") or build+flash the latest "rolling" branch.

**Comment by SybexX** [comment]
@henrythasler build the rolling branch it yourself is not absolutely necessary, he can simply download the finished OTA files.
https://github.com/jomjol/AI-on-the-edge-device/actions/runs/9439572638

**Comment by Dillton** [comment]
Ah ok thank you for info.
I was thinking that something like this might be the problem but wasn't sure.
So far I have created the sensors as needed from mqtt but I will definitely try to update to this once I have some spare time.
So I will share the result later.

**Comment by Dillton** [comment]
> @henrythasler build the rolling branch it yourself is not absolutely necessary, he can simply download the finished OTA files. https://github.com/jomjol/AI-on-the-edge-device/actions/runs/9439572638

Thank you very much I just updated both meters and both were detected as expected by HA.
