### ISSUE TITLE
Initial Setup - Final screen - Uncaught ReferenceError: reboot is not defined

### ISSUE THREAD

**Issue by wejder669** [jomjol/AI-on-the-edge-device#313]
Hello All,
Amazing project trying to get it running. Ger below error on the final screen during Setup.
"Uncaught ReferenceError: reboot is not defined
onclick http://192.168.1.182/edit_explain_6.html:1"

**Comment by jomjol** [comment]
Is this problem still there? I just checked the code and the defintion of reboot should be there. You find the definition of the function in line 55: `function reboot() {...`

Please reopen, if error is still a problem.
