### ISSUE TITLE
Bright Display 

### ISSUE THREAD

**Issue by varadujagan** [jomjol/AI-on-the-edge-device#314]
Great work .... first of all, thanks for the project. 
I'm new to these. I came across 2 problems. Here I'm explaining those below. 

1. My EB meter is having a Backlight,  here is the photo of that  
![EB](https://user-images.githubusercontent.com/78145278/129444182-878b478d-125c-496b-91db-19b4ae8d2919.jpeg)
I cont able to see anything in that display. The back light will be ON  every time. 
What to Do ??

2.  In the meter the values are continuously changing between 50 values in that 50 value I want only one (KWH). how to get that single value from those 50 values.  for reference, I attaching the video link. 
https://youtu.be/tW_Sphts9BE

**Comment by jomjol** [comment]
Hi,
first thanks for your feedback. Regarding your questions:

to 1: you can switch of the flash light led by setting `WaitBeforeTakingPicture` to zero. Other options are currently not implemented

to 2: I don't see the video link. But anyway, I assume, that you need to take the picture exactly, when the right information is displayed. At the moment, there is no synchronisation or exact timing for taking the pictures. Sorry for this!

Best regards,
  jomjol

**Comment by varadujagan** [comment]
> Hi,
> first thanks for your feedback. Regarding your questions:
> 
> to 1: you can switch of the flash light led by setting `WaitBeforeTakingPicture` to zero. Other options are currently not implemented
> 
> to 2: I don't see the video link. But anyway, I assume, that you need to take the picture exactly, when the right information is displayed. At the moment, there is no synchronisation or exact timing for taking the pictures. Sorry for this!
> 
> Best regards,
> jomjol

Thanks for replying ...
 for 1: ok let me try `WaitBeforeTakingPicture` set zero. I will update u after checking 

for 2: Sorry I forgot to add a link, now I Added  https://youtu.be/tW_Sphts9BE  

Make this as Feature Requests: Water meter, EB meter, Solar Inverter, etc., all are Digital only. In everything it won't display the same value, it will continuously display multiple parameters.  

My small Request :
You have implemented an alignment references image option to realign every taken image to the reference coordinates. like that 
If you create an option to get references for the units (KWH, KVrh, A, V, etc..). when the unit came then only it suppose to get values, this will be a good solution for my Problems  

 For Example 
![Screenshot (395)](https://user-images.githubusercontent.com/78145278/129453047-7f380cfb-1f0f-450b-9fe4-663171dbb446.png)
From the above Image If we put a reference point as a unit `KWH`  when the display matches the reference point then it will get the values. this is my small Idea. you are more genius than me you Know the Best. thanks for Hearing

**Comment by jomjol** [comment]
Hi,
got you idea, but I think, this would have some points to be considered:
- not a small change - as the background flow would need a significant extension and especially the configuration needs to be extended for multi outputs, that are configurable with respect to reference images
- even then I'm not sure, if the result would be accetable, as you have no controll, when the value of interest is showing up. And as the digitalization might take up to 30 seconds, you most problalby cannot sync it properly.

This is a VISIONTEK 37M. It already has a digital output. Why don't you use that?
![grafik](https://user-images.githubusercontent.com/30766535/129473066-59a643d9-d042-45f9-9d26-0f11b6af269c.png)

I'm not going to work on that right now. I could put it on the long term request list. But to be honest, for an already digital meter, that would be a high effort for an available solution :-).

What do you thing?

**Comment by varadujagan** [comment]
> Hi,
> got you idea, but I think, this would have some points to be considered:
> 
> * not a small change - as the background flow would need a significant extension and especially the configuration needs to be extended for multi outputs, that are configurable with respect to reference images
> * even then I'm not sure, if the result would be accetable, as you have no controll, when the value of interest is showing up. And as the digitalization might take up to 30 seconds, you most problalby cannot sync it properly.
> 
> This is a VISIONTEK 37M. It already has a digital output. Why don't you use that?
> ![grafik](https://user-images.githubusercontent.com/30766535/129473066-59a643d9-d042-45f9-9d26-0f11b6af269c.png)
> 
> I'm not going to work on that right now. I could put it on the long term request list. But to be honest, for an already digital meter, that would be a high effort for an available solution :-).
> 
> What do you thing?

So I told you. You are the expert. 
let me look into digital output.  Is there any project lead to reading digital output signal. Please Link them 

Thanks for the beautiful work you have done. (AI-on-the-edge-device)
