### ISSUE TITLE
Datum und Uhrzeit auf der Overview Page

### ISSUE THREAD

**Issue by friedpa** [jomjol/AI-on-the-edge-device#3140]
### The Feature

Nachdem bei meinem Systemen es gelegentlich vorkommt, dass der Connect zum Router NTP wegfällt, wäre es aus monitoring Sicht für mich gut, wenn auf der Overview Page z.B. unter System Info auch das Datum (und die Uhrzeit) angezeigt wird. Das richtige Datum alleine zeigt aber eh davon, dass ein NTP Server gefunden wurde.

**Comment by Gerd2809** [comment]
Moin friedpa,

ich kann in meinem Netz nicht auf pool.ntp.org direkt zugreifen, wollte aber keine Firewallregel dafür machen, da der Router selber seine Zeit bei pool.ntp.org holt und er auch die Zeit im Netz verteilen kann, trägt man einfach die IP des Routers ein. 

Gruß Gerd

**Comment by SybexX** [comment]
![Unbenannt](https://github.com/user-attachments/assets/2475c884-eaf0-42fc-bafe-1269026cc196)

**Comment by SybexX** [comment]
@friedpa meinst du das so? https://github.com/SybexX/AI-on-the-edge-device/actions/runs/11959157548

![Unbenannt](https://github.com/user-attachments/assets/e131cea9-1803-4f80-bf1b-7e4b52f925e1)

**Comment by friedpa** [comment]
Datum + Uhrzeit wäre super.
Wann wird denn eigentlich die Umstellung von 16.0.0 RC4 auf 16.0.0 Released geben?

**Comment by caco3** [comment]
> ich kann in meinem Netz nicht auf pool.ntp.org direkt zugreifen

Falls Du eine Fritzbox hast, kannst Du als NTP-Server auch die IP der Fritzbox angeben, Intern agiert sie als NTP-Server. Ich denke, andere Router machen das auch so.

**Comment by caco3** [comment]
> Wann wird denn eigentlich die Umstellung von 16.0.0 RC4 auf 16.0.0 Released geben?

Es gibt keinen Nachteil/Unterschied, wenn Du anstatt einem getagte Release auf den lauest `main` (früher `rolling`) aufsetzt!
