### ISSUE TITLE
New Training Data for Kamstrup FlowIQ2200 water meter

### ISSUE THREAD

**Issue by lauer** [jomjol/AI-on-the-edge-device#3144]
Using the dig-class11_1500_s2.tflite model.
It had some problems between 1 and 7 for the last digits, where there is a small line around it. 

![1_c03c9b51b0568d376d88177528af4ad8](https://github.com/user-attachments/assets/8d0d35da-486f-4ca8-9690-9c5ed5007a18)
![1_ce87fd7941d3444afabcecacfa388a8d](https://github.com/user-attachments/assets/1967314f-01c7-4849-a658-fa35583c852e)
![7_acc16d59968bef8c2cce946facb9a2cb](https://github.com/user-attachments/assets/973b08c0-c0b3-4cc3-9971-320f247aff24)
![7_e3a8d1f77c38bc576c09a482310568d5](https://github.com/user-attachments/assets/fef5df1d-6226-4944-82bb-307af86f67b2)

see #3121 

### Files

[labeled.zip](https://github.com/user-attachments/files/16316894/labeled.zip)

![flowiq2200-1024x1024](https://github.com/user-attachments/assets/f1003c22-96de-47e4-ab5c-514d57b755e6)

**Comment by lauer** [comment]
I just downloaded and activated dig-class11_1701_s2 to see if that one is doing it better.

**Comment by lauer** [comment]
Did not work, again it confused a 1, and said it was a 7.

**Comment by SybexX** [comment]
Have you already tried the model dig-class11_1800_s2.tflite?
you can find it there https://github.com/jomjol/neural-network-digital-counter-readout

**Comment by lauer** [comment]
Ohh. Thanks for the quick reply. I didn't see the 1800 for some reasons. 

Would you like me to check with that one first before checking the 1801 model?

**Comment by haverland** [comment]
Images are added to model  https://github.com/haverland/neural-network-digital-counter-readout/blob/master/dig-class11_1801_s2_q.tflite in [#25](https://github.com/jomjol/neural-network-digital-counter-readout/pull/25)

Alternative the model  https://github.com/haverland/Tenth-of-step-of-a-meter-digit/blob/master/output/dig-class100-0172-s2-q.tflite also includes the images

**Comment by lauer** [comment]
what are the difference between the models? Also, what does the _q mean?

**Comment by haverland** [comment]
class11 can only digits and "not a digit". Normally all that you need. 

class100 and cont- can for normal digits on meters between the digit (in transition) the tenth of steps (0.0-9.9). Is for lcds not that really needed, but the models have massive more images to learn (>23.000). So it could be a better recognition. It's to try out.

-q.tflite vs. .tflite: -q means quantized. The models are smaller and faster with a minimal less on accuracy.

**Comment by lauer** [comment]
I can confirm, that the class11_1801_s2_q solves all the issues with 7 and 1. So I guess this ticket can be closed? Or at least when it's merged in jomjol/neural-network-digital-counter-readout#25

**Comment by Commifreak** [comment]
Also had some occasional issues with my flowiq 2200 and the class11_1700 model. Sometimes it detects 5 as 6 (next run is was ok again). I'll try the 1901 again (1801 got deleted at the repo?)

**Comment by maisun** [comment]
Hi I tried 1900 and 1901 for the same water meter but it detect 4 as 0. Has anybody similar issue? I’m now on class100 which occasionally miss some readings. Where can download 1801? Would like to give a try (it’s not in the list)

**Comment by maisun** [comment]
[

![Image](https://github.com/user-attachments/assets/15f676db-83b7-45bb-bcf7-33f4881cda9c)

](url)

Just to add my problem with 4, notice there is a dot (decimal point) maybe that’s the issue

**Comment by maisun** [comment]
With class100 it works most of the time, occasionally it misses on the last digit. For example last night for 6 hours I have 120 rounds, only 1 round mixed 5 with 9:

![Image](https://github.com/user-attachments/assets/d621f660-5c41-4d9f-8b4a-da839951274f)

**Comment by erikxson** [comment]
I've made a wMbus-reader for FlowIQ2200.
This is tested on my home setup with an ESP32 and CC1101, please test it if you like.
(If your meter is encrypted it require an encryption key.)

https://github.com/erikxson/watermeter-flowiq2200
