### ISSUE TITLE
version.txt is missing in Sourcecode.zip in the html Folder

### ISSUE THREAD

**Issue by robo-kob** [jomjol/AI-on-the-edge-device#3145]
### The Problem

**I get this:** 

AI on the Edge Device

We have one or more critical errors:
0x00000010

Please check logs with log viewer and/or [jomjol.github.io/AI-on-the-edge-device-docs/Error-Codes](https://jomjol.github.io/AI-on-the-edge-device-docs/Error-Codes) for more information!

**Workaround: put an an empty version.txt File in the html Folder** because it is necessary --> https://github.com/jomjol/AI-on-the-edge-device/blob/rolling/code/components/jomjol_helper/sdcard_check.cpp#L14 Line 151 

### Version

15.7.0

### Logfile

```shell
See Problem description
```

**Comment by SybexX** [comment]
You just have to expand/change rolling/code/main/CMakeLists.txt a bit, then it will be created automatically when compiling.

from:
-----
```C
..........

if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/version.cpp)
    file(READ ${CMAKE_CURRENT_SOURCE_DIR}/version.cpp VERSION_)
else()
    set(VERSION_ "")
endif()

if (NOT "${VERSION}" STREQUAL "${VERSION_}")
    file(WRITE ${CMAKE_CURRENT_SOURCE_DIR}/version.cpp "${VERSION}")
    file(WRITE ${CMAKE_CURRENT_SOURCE_DIR}/../sd-card/html/version.txt "${VERSION_HTML}")
endif()

...........
```

to:
---
```C
...........

if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/version.cpp)
    file(READ ${CMAKE_CURRENT_SOURCE_DIR}/version.cpp VERSION_)
else()
    set(VERSION_ "")
endif()

if (NOT "${VERSION}" STREQUAL "${VERSION_}")
    file(WRITE ${CMAKE_CURRENT_SOURCE_DIR}/version.cpp "${VERSION}")
    file(WRITE ${CMAKE_CURRENT_SOURCE_DIR}/../sd-card/html/version.txt "${VERSION_HTML}")
    file(WRITE ${CMAKE_CURRENT_SOURCE_DIR}/../../sd-card/html/version.txt "${VERSION_HTML}")
endif()

............
```

**Comment by caco3** [comment]
> **Workaround: put an an empty version.txt File in the html Folder** because it is necessary

No, that is wrong!
Just follow exactly the build instructions!
