### ISSUE TITLE
LED flicker/bad image quality

### ISSUE THREAD

**Issue by Kev0123** [jomjol/AI-on-the-edge-device#315]
I get some random LED flickering
I tried several different power supplies.
I even tried a different SD Card.
As this issues was not present at first, it might be a hardware problem.
![Screenshot_20210817-180715~2](https://user-images.githubusercontent.com/19821853/129762184-0d5ae206-84cb-4a00-8877-c594f211d367.png)

Anyone else discovering this issue?

https://user-images.githubusercontent.com/19821853/129762817-6db956ac-21ad-4cfa-a29d-7be72b50d918.mp4

Sometimes its present, sometimes not. Changing at every picture taken

**Comment by RiRomain** [comment]
You could try to add 220 µF or bigger capacitor between the ground and 5V (assuming you are powering with 5V).
Also one issue is that the board seems to sometimes require more than 5V. Some board only work well when powered with more than 5.4V, you could try looking for a power supply that provide more than 5V.
You can go as high as 7V, as the regulator is able to handle 15V (but might overheat above 7V without additional cooling).

More information here: https://nachbelichtet.com/esp32-cam-probleme-beheben/ it's in German, but you should be able to use google translate to understand it.

**Comment by jomjol** [comment]
Did the condensator and another power supply help or do you have further topics to this or can I close this issue?

**Comment by Kev0123** [comment]
It was hardware related, i changed the whole unit but will give the "old" one a try with a higher voltage. The new doesn't flicker.

Thanks @RiRomain for the hint! 
PS: Deutsch ist kein Problem 😁

**Comment by jomjol** [comment]
Alles klar - dann schließe ich das mal.
