### ISSUE TITLE
Presentation of the project to ML community

### ISSUE THREAD

**Issue by borelg** [jomjol/AI-on-the-edge-device#316]
Dear @jomjol ,
I am part of a ML community, and we try to bring to our members and friends interesting projects and researches on the topic.
I believe that your project would be a very interesting one because you devised it to be reproduced. 
Would you like to be our guest during one of the next sessions? :)
Have a nice day,
borelg

**Comment by jomjol** [comment]
Dear @borelg ,
which community are you part of? I'm happy to share my project and experiences.
Best regards,
  jomjol

**Comment by borelg** [comment]
Dear jomjol,
Thanks for your message :)
I am getting back to you so late because of summer vacations.

I am part of one of the Italian Machine Learning community:
https://mlmodena.it/

Why don’t you drop an email to our address?
***@***.***

I will share with you more details and I believe that your project and your
experience will be very interesting!

Thanks again!!!
borelg

Il giorno gio 19 ago 2021 alle 19:54 jomjol ***@***.***> ha
scritto:

**Comment by jomjol** [comment]
Hi borelg,

the email in your message is not readable. Which email should i use to get in personal contact?

Best regards,
  jomjol

**Comment by borelg** [comment]
Hi jomjol,

Sure.
mlmodena.info[at]gmail[dot]com

Please let me know if you read it.
Thanks!

Il giorno sab 4 set 2021 alle 19:45 jomjol ***@***.***> ha
scritto:

**Comment by jomjol** [comment]
Send you a direct email - closing this issue.
