### ISSUE TITLE
Uptime Kuma monitoring of Digitizer Water Meter

### ISSUE THREAD

**Issue by tomasenskede** [jomjol/AI-on-the-edge-device#3167]
I’m running a Digitizer Water Meter and want to monitor the solution using Uptime Kuma. However, an HTTP request isn't reliable, as I often encounter a 'Parse Error: Expected HTTP.' Is there another way to monitor this service?

![image](https://github.com/user-attachments/assets/7c547019-e6c0-4f19-ba46-906337c0d4ce)

Perhaps the ESP32 isn't powerful enough to be monitored directly? Should I instead monitor the delivery of data into the MQTT broker?

**Comment by caco3** [comment]
Do you see an error in the devices DEBUG log?
In general, REST calls should be ok. Which URL are you calling?
But the device is more focuses on MQTT, so you could give that one a tray as it reduces the load to the device (no polling)

**Comment by tomasenskede** [comment]
> Do you see an error in the devices DEBUG log?
> 
> In general, REST calls should be ok. Which URL are you calling?
> 
> But the device is more focuses on MQTT, so you could give that one a tray as it reduces the load to the device (no polling)

I switched to ping control, and it seems to be more stable.

**Comment by caco3** [comment]
> I switched to ping control, and it seems to be more stable.

Just be aware that a ping response does not guarantee that the device works properly, eg. if the MQTT connection still is ok.
On Homeassistant, I have an automation which checks the uptime MQTT topic. If that does not change for a while, an alert is raised.
