### ISSUE TITLE
Feature request: Device reset request over mqtt and/or better web server availability detection

### ISSUE THREAD

**Issue by derandiunddasbo** [jomjol/AI-on-the-edge-device#318]
I'm quite often running into the issue, that the device is still online somehow, as it is still computing current values and sending them over mqtt, but the web server isn't available anymore. 

As far as I read in some other issues, the device already does some error condition detection, but it still doesn't seem to reliably detect, if the web server has crashed. Unfortunately a manual reset of the device can only be triggered through the web server.

I don't know if this detection can be improved, but as a last resort it would be nice, to also have a mqtt topic that the device listens to which triggers a restart, as the network and mqtt connection seems to be quite stable.

**Comment by ornea** [comment]
I had similar a experience but if i waited it would eventually serve up a web page and if left on its own it would auto update the photo and values after a period of time.

I just figured ( probably  wrongly) that it had some serious work to do while it was running the AI and therefore becomes unresponsive during that time.

**Comment by derandiunddasbo** [comment]
Yes, sometimes it's best to leave the device alone for some time, but it doesn't always recover from that state and the web server doesn't become available again even after some hours. But as it's still updating values via mqtt, the device is apparently up and running. 

As the web server seems to be the most unstable component of this firmware, it would be good to have a trigger for restarting the device, which doesn't rely on the web server being accessible.

**Comment by jomjol** [comment]
You can trigger a reboot directly with ``http://IP-ADRESS/reboot``

**Comment by derandiunddasbo** [comment]
I'll try it next time the web server becomes unresponsive, but how should calling this URL work, if the web server is... well... unresponsive? 🤔

**Comment by jomjol** [comment]
If the server is only not responding, but receiving it should work and after the reboot, it should respond again. Please test. currently I have no plan to use the mqtt for this in receiving mode.

**Comment by derandiunddasbo** [comment]
Just as a quick follow up: `http://IP-ADRESS/reboot` actually worked several times, even if the web server otherwise appeared unresponsive.

**Comment by jomjol** [comment]
Thanks!
