### ISSUE TITLE
Improve documentation of expert camera parameters

### ISSUE THREAD

**Issue by caco3** [jomjol/AI-on-the-edge-device#3185]
### The Feature

Eg. the parameter [camrawgma](https://jomjol.github.io/AI-on-the-edge-device-docs/Parameters/#parameter-camrawgma) only sais "RawGma".

We should add at least a sentence to explain what it is used for.

**Comment by caco3** [comment]
@SybexX Do you remember, did you add those parameters?
Could you extend their documentation?
Bee aware that the parameters are now documented in this repo (and no longer in the documentation repo as was before)

**Comment by SybexX** [comment]
Unfortunately I didn't really find anything useful about it.
The data sheet for the OV5640 says this:
5.4 raw gamma
The main purpose of the Gamma (GMA) function is to compensate for the non-linear characteristics of the sensor. GMA
converts the pixel values according to the Gamma curve to compensate the sensor output under different light strengths.
The non-linear gamma curve is approximately constructed with different linear functions. Raw gamma compensates the
image in the RAW domain.

**Comment by caco3** [comment]
I see :(

It is even hard to find a proper datasheet for it with a link which should stay long term.
A reliable one might be https://cdn.sparkfun.com/datasheets/Sensors/LightImaging/OV5640_datasheet.pdf

I would suggest to:
- add a link to the data sheet for all those parameters.
- copy the text out of the datasheet to the parameter page (where possible).

**Comment by SybexX** [comment]
this is also a good site https://heyrick.eu/blog/index.php?diary=20210418&keitai=0

**Comment by SybexX** [comment]
I started to revise all the parameter descriptions.
I took most of the descriptions from this page: https://docs.circuitpython.org/en/latest/shared-bindings/espcamera/index.html
[TakeImage.zip](https://github.com/user-attachments/files/16651434/TakeImage.zip)

**Comment by SybexX** [comment]
Can we copy the data sheets into the [documentation](https://github.com/jomjol/AI-on-the-edge-device-docs/tree/main/docs) or something so that the link is always available?

**Comment by caco3** [comment]
yes, I rhink that should be ok

**Comment by SybexX** [comment]
I revised it again and think this structure is better. 
[TakeImage_24_08_2024.zip](https://github.com/user-attachments/files/16741248/TakeImage_24_08_2024.zip)

I wanted to upload the PDFs, but I get the error that the upload is deactivated^^

**Comment by caco3** [comment]
> I wanted to upload the PDFs, but I get the error that the upload is deactivated^^

You mean you could not add it using the web IDE?
Then try to add it on your PC, that for sure will work.

**Comment by SybexX** [comment]
![Unbenannt](https://github.com/user-attachments/assets/e6d48219-4be0-4fcf-b37f-0dfc519fdd1e)

**Comment by caco3** [comment]
ah, I guess @jomjol first needs to add you as a contributor.
For now you could fork it and add a PR.

**Comment by SybexX** [comment]
![Unbenannt](https://github.com/user-attachments/assets/1bf90576-26b5-416a-abea-620ca0c6bb45)
Which structure do you think is better, the old or the new?

**Comment by caco3** [comment]
I prefer a mix: the title and the options formatted as a list.
But I would move it to above the warning as it is the main information a user wants to read.

**Comment by SybexX** [comment]
@caco3 do you mean it like that?
![361251826-1bf90576-26b5-416a-abea-620ca0c6bb45](https://github.com/user-attachments/assets/43e85117-06f3-45f4-a2d4-a15f448658bb)

**Comment by caco3** [comment]
yes.
maybe even move it above the default value line.

**Comment by caco3** [comment]
No, I would not put it to the SD card. that would increase the image by several MB and only devs/power users will need it. And those user I expect to be able to access the internet :)

**Comment by SybexX** [comment]
what do you think, can I upload the last version or should I change something else?

**Comment by SybexX** [comment]
adapted for ov2640 + ov5640

[TakeImage_26_08_2024_3.zip](https://github.com/user-attachments/files/16752080/TakeImage_26_08_2024_3.zip)

**Comment by caco3** [comment]
@SybexX Thanks for your work! Did you add this already to a PR?
