### ISSUE TITLE
Reconfigure

### ISSUE THREAD

**Issue by axb0306** [jomjol/AI-on-the-edge-device#320]
Hi and thanks for you work!

I have tried to configure and did the last step but I stuble on som problems and want to reconfigure without flash the firmware again. How do I do that?

**Comment by jomjol** [comment]
Every configuration item is avialable due the normal top menue - see: https://github.com/jomjol/AI-on-the-edge-device/wiki/Graphical-configuration

Or you can go back to the initial configuration mode by changing manually in the config.ini: `SetupMode = true`
