### ISSUE TITLE
RAW value differs from Read?

### ISSUE THREAD

**Issue by RedGreenChilli** [jomjol/AI-on-the-edge-device#3200]
### The Problem

Hallo zusammen, ich hoffe, dass mir jemand helfen kann. Ich verwende die Version 15.6.0. Die aktuellere Version sorgt bei mir leider für einen Fehler mit der Kamera, weswegen ich wieder ein downgrade durchgeführt habe. Ich erhalte regelmäßig die negative Rate Fehlermeldung. 
Ich verstehe allerdings nicht, wieso der Wert falsch angezeigt wird. Wenn ich auf den Tab Recognition gehe und mir dort die Erkennung anschaue, dann scheint alles zu stimmen. Er erkennt die Zahl absolut korrekt. Allerdings wird der RAW Wert um genau 1 zu wenig angezeigt, weswegen er ein Negativrate Error gibt. 
verstehe ich hier die Anzeige falsch beziehungsweise kann mir jemand das Verhalten erklären oder habe ich hier einen Fehler entdeckt? 

Vielen Dank schon mal für die tolle community und viele Grüße 

![IMG_0489](https://github.com/user-attachments/assets/7390fccd-dd4b-45bd-bc5b-0db9c990d3c5)
![IMG_0491](https://github.com/user-attachments/assets/0deab0fc-4646-483f-aa06-c0341a339786)

### Version

15.6.0

### Logfile

```shell
0d00h01m06s] 2024-08-27T22:21:30 <ERR> [POSTPROC] main: Raw: 216.64930, Value: , Status: Neg. Rate - Read: - Raw: 216.64930 - Pre: 217.49530
[0d00h06m05s] 2024-08-27T22:26:29 <ERR> [POSTPROC] main: Raw: 216.64929, Value: , Status: Neg. Rate - Read: - Raw: 216.64929 - Pre: 217.49530
```

### Expected Behavior

Der im Recognition Tab erkannte wert sollte mit dem Pre Value verglichen werden und dann als Wert übernommen werden.

**Comment by RedGreenChilli** [comment]
I tried the update to 15.7.. it worked this time. I will check if the error comes back…

**Comment by SybexX** [comment]
Weil jeder Werte anders behandelt/berechnet wird.
Der Recognition-Wert wird einfach gerundet, während der Value mithilfe einer komplexen Berechnung berechnet wird.
Gucke mal hier nach: https://jomjol.github.io/AI-on-the-edge-device-docs/Watermeter-specific-analog---digital-transition/

versuche auch bitte das aktuelle rolling  https://github.com/jomjol/AI-on-the-edge-device/actions/runs/10584237574
