### ISSUE TITLE
digitization rather than digitilization

### ISSUE THREAD

**Issue by Apfelstruhdl** [jomjol/AI-on-the-edge-device#3212]
### The Problem

Converting analog values to digitial ones is called digitization.

google "digitization vs digitalization"

### Version

-

### Logfile

```shell
-
```

**Comment by caco3** [comment]
You are right.
Sadly, in German both words are used interchangeable, so there are a lot of wrong occurrences in all over the project.
I started to rename them but it needs further testing: https://github.com/jomjol/AI-on-the-edge-device/pull/3219
