### ISSUE TITLE
Reference image changing

### ISSUE THREAD

**Issue by axb0306** [jomjol/AI-on-the-edge-device#322]
Hi, I have a problem with the reference image changing. Sometimes it works, but most of the time it is offset on the detection. Why is that? 

<img src="https://imgshare.io/images/2021/08/23/ia.jpg" alt="ia.jpg" border="0" />

**Comment by jomjol** [comment]
Your references are not found. It looks like your contrast is a bit weak. Can you increase this or make some "artifical" reference marks with a black dot or by glueing something on top?

**Comment by jomjol** [comment]
Please reopen in case of updates
