### ISSUE TITLE
data/recognition does show wrong images during round

### ISSUE THREAD

**Issue by Apfelstruhdl** [jomjol/AI-on-the-edge-device#3221]
### The Problem

data/recognition page:
Not 100% sure about the exact moments when the ROI images are being updated, but it seems that already the new images appear (after image taking) but the old values are displayed as the digitization is not yet complete.
I think: The aligned image (current round) is updated, then the images of the ROIs are updated at the same time, but the values are still from previous round. Then after digitization also the values are from current round.

So overall the labeling of current and previous round for the large image the ROI images and the values is somehow misleading.

That leads to inconsistent information during some periods of time on the recognition page.

### Version

29.08.2024 22:19 Development-Branch: rolling (Commit: 822753b)

### Logfile

```shell
-
```

### Expected Behavior

the displayed image data and values depicted under "previous round" should at all times be consistent.

**Comment by caco3** [comment]
Yes, the small (ROI) images and the big overview picture are not from the same round (see titles on each image column).
This is because we only have limited RAM and can not keep the full image from the previous round, thus prefered to show the current one instead of none.
