### ISSUE TITLE
Import project in VS code

### ISSUE THREAD

**Issue by gomito1** [jomjol/AI-on-the-edge-device#323]
Hello friend I hope you are well, I bother you if you can help me with the execution of the project on the VScode platform,
I already opened the project from the Platformio plugin as it says in the guide you left https://github.com/jomjol/AI-on-the-edge-device/wiki/Build-Instructions , when I open the terminal and copy PIO RUN in the AI-on-the-edge-device / code folder it compiles the libraries but they are missing those of the folder (esp32-camera-master) that get error.
You have another guide that can help me execute the project in VScode a little more clearly, I would like to get my hands on the code.
it would be of great help thanks.

**Comment by jomjol** [comment]
No, there is no other instruction. What exactly is your problem?

**Comment by jomjol** [comment]
Just tested the instructions in a freshly installed Ubuntu (20.04) and indeed, it is only working if you use:
`platformio run --environment esp32cam` instead of `pio run`
But with this it did build without problems. I update the build instructions shortly in the future.

**Comment by jomjol** [comment]
Update Instructions done

**Comment by gomito1** [comment]
thanks friend, for your help.
