### ISSUE TITLE
New Training Data - Flow Systems SV-RTK water meter

### ISSUE THREAD

**Issue by teixeluis** [jomjol/AI-on-the-edge-device#3237]
### Files

[digits_flow_systems_sv_rtk.zip](https://github.com/user-attachments/files/17002693/digits_flow_systems_sv_rtk.zip)

![361779430-706a1875-9c83-4297-a2bf-78f92ea9d786](https://github.com/user-attachments/assets/ae3ee6db-3fa0-4a70-b76c-b8b0fcffbdee)

**Comment by jomjol** [comment]
Can you test the following tflite: https://github.com/jomjol/AI-on-the-edge-device/raw/refs/heads/rolling/sd-card/config/dig-cont_0710_s3_q.tflite

**Comment by teixeluis** [comment]
Thanks @jomjol, will give it a try.

**Comment by teixeluis** [comment]
As is, a bit worse, but maybe I need to reajust the ROIs (?)

![image](https://github.com/user-attachments/assets/1fcef2f0-3b1b-4faa-8d2a-55eed134f117)

My current ROI settings:

![image](https://github.com/user-attachments/assets/159e0d66-f2ba-4749-99b5-6d669379ef14)

[Digits]
;Model = /config/dig-class100-0168_s2_q.tflite
;Model = /config/dig-cont_0700_s3_q.tflite
Model = /config/dig-cont_0710_s3_q.tflite
CNNGoodThreshold = 0.5
ROIImagesLocation = /log/digit
;ROIImagesRetention = 3
main.dig1 171 21 66 78 false
main.dig2 244 22 66 78 false
main.dig3 323 23 65 76 false
main.dig4 403 23 58 77 0
main.dig5 480 22 54 78 0
main.dig6 555 22 61 80 0

**Comment by teixeluis** [comment]
(I followed the recommendation as in 1.2.2.2.2 Setup using dig-class100 or dig-cont Models https://jomjol.github.io/AI-on-the-edge-device-docs/ROI-Configuration/, considering a dig-cont model)

**Comment by teixeluis** [comment]
Regarding the recognition:

![image](https://github.com/user-attachments/assets/1e8268aa-86b7-498f-b056-72efcff0fc27)

**Comment by jomjol** [comment]
Your ROI is too small, especially in the height. The inner square should be as large as the number.
![image](https://github.com/user-attachments/assets/9caf9767-28d3-4d20-8f6b-7fade9457bcb)

P.S.: it doesn't matter, if there is a overlapp between the ROIs in the setup window.

**Comment by caco3** [comment]
new training data got added
