### ISSUE TITLE
[ unsure ] Failed transmission corrupts Home Assistant statistics

### ISSUE THREAD

**Issue by schoppfe** [jomjol/AI-on-the-edge-device#3247]
### The Problem

I use AI-on-the-edge with Home Assistant and Mosquitto MQTT. Occasionally (once or twice a week) the Home Assistant reports a sudden, large spike in value that skews my stats. This seems to be related to a loss of connection from the AI-on-the-edge device. While the water meter value corrects itself, the calculated costs in Home Assistant remain unrealistically high. I traced the problem back to a specific point in time and noticed that the diagnostic JSON was missing for that time period. The 'uptime' value fall to a very low value (from 180k to 1.5k sec) but NOT zero during the disconnect and then restored afterwards, suggesting that the device was never actually switched off but send corrupted data. 

Is this a bug that I can fix from the "AI-on-the-edge" side, or do I need to do a workaround within the Home Assistant?

### Version

Release: v15.7.0 (Commit: 0d0b018+)

### Logfile

```shell
There is no log entry for the time the error occurred.
```

### Expected Behavior

The device should not lose its connection. The transmission of values should be acknowledged as correct. If something is wrong, no incorrect values should be sent, but the device should be detected as unavailable so that the statistics are not falsified. 

### Screenshots

<img width="551" alt="image" src="https://github.com/user-attachments/assets/f1d84c99-5e71-4eb8-860c-0c8cced92241">
<img width="556" alt="image" src="https://github.com/user-attachments/assets/0b6e7c05-6b77-4522-b625-3d96c35a7cba">
<img width="551" alt="image" src="https://github.com/user-attachments/assets/8b2083c7-110a-4ed9-aefd-fd9e49431669">

### Additional Context

The connection should be very good (-66dBm) since I already specifically moved an access point for it.

**Comment by caco3** [comment]
Please check if you can see something n the log.

Enabling the DEBUG log might help.

>  The 'uptime' value fall to a very low value (from 180k to 1.5k sec)

I guess this is because the device restarted (eg. due to a crash).
