### ISSUE TITLE
Support for non rotary gauges?

### ISSUE THREAD

**Issue by legomind** [jomjol/AI-on-the-edge-device#3250]
### The Feature

Add support for reading a non-rotary gauge like this:

![image](https://github.com/user-attachments/assets/6d2eba6e-e895-4671-962b-83a85068e155)

**Comment by caco3** [comment]
If I interpret your image right, that gauge does not have a digit or a a rotating pointer. instead, the red part moves in and out.
This would need to be handled completely different. Thus it is out of scope for this project.
