### ISSUE TITLE
Dot/comma setting should be the same everywhere but isn't at Set Previous Value

### ISSUE THREAD

**Issue by TheChatty** [jomjol/AI-on-the-edge-device#3259]
### The Problem

Set Previous Value expects a comma as decimal point if this is according to regional setting. But in all other places (even on the same page) it display always in English format with point - regardless of regional setting.

### Version

15.7.0

### Logfile

```shell
unnecessary in this case
```

### Expected Behavior

Stick to one setting - either always English or always like regional setting.

### Screenshots

![image](https://github.com/user-attachments/assets/6e9e3270-f13f-4ff1-8e7a-97b944421c58)

**Comment by SybexX** [comment]
try the current rolling, it should be fixed there: https://github.com/jomjol/AI-on-the-edge-device/actions/runs/11084386670

**Comment by TheChatty** [comment]
I installed your linked release and I the situation is the same as in my above picture.

But now the camera picture is much darker. So the alignment markers are not correctly found --> image not rotated correctly and so on.

**Comment by SybexX** [comment]
I don't know why it's like that for you, for me it always shows a dot.
Activate Auto-Exposure Control 2 and possibly increase CamGainceiling, then the image should become brighter again.

**Comment by caco3** [comment]
> I don't know why it's like that for you, for me it always shows a dot.

I think the way a number is shown in an input box is dependent on the region settings of your webbrowser resp. operating system.
This is quite tricky to handle.

> But now the camera picture is much darker. So the alignment markers are not correctly found --> image not rotated correctly and so on. Edit: Going back to 15.7.0 resulted in previous (lighter) image.

If you migrate from an older version, you might need to update the camera settings and create a new reference image. We extended the camera settings and some devices need reconfiguration due to this.
