### ISSUE TITLE
Readout Fehler bei Ziffernanzahl Änderung

### ISSUE THREAD

**Issue by Xsev1** [jomjol/AI-on-the-edge-device#326]
Hallo Josef,
ich verwende die aktuelle Master (2021-08-24) Version. Mir ist aufgefallen, beim Wechsel von 3 auf 2 Ziffern  bzw. 4 auf 3 (100 auf 99  bzw. 1000 auf 999) kommt es zu einem Read Fehler, von 99 auf 100 (sprich andere Richtung) geht es. 
Kurzes Beispiel:
Ich hab 2 Ziffern hinterlegt und kann 0-99 darstellen.  Im einstelligen Bereich macht er mir einen "Nan" und die eine Zahl, was soweit passt, wenn über >= 10 werden beide Zahlen korrekt erkannt. Wenn er aber von 10 auf 9 geht, macht er eine 19 daraus. Sprich der "Nan" wird dann als 1 (vermutlich letzter Wert) weiterverwendet. Wenn man dann das Preset wieder auf 9 ändert geht es wieder.

Kann man das in der Config beinflussen das er "Nan" immer als 0 wertet?

**Comment by jomjol** [comment]
Hallo Xsev1,
d.h. dein Zähler läuft auch rückwerts, korrekt? In diesem Fall funktioniert die Option `CheckDigitIncreaseConsistency` nicht und du musst natürlich `AllowNegativeRates` auf `true` setzen. Aber dann sollte es damit eigentlich keine Problem geben. Eine NaN als "0" zu interpretieren wäre nicht gut, da dann alle Zwischenwerte (Zähler steht zwischen zwei Zahlen) falsch interpretiert werden. Hast du nochmal ein Beispiel?

**Comment by Xsev1** [comment]
Genau der läuft auch rückwärts, das funktioniert auch bestens. Das Problem ist, mein Messgerät hat keine führenden Nullen, sprich wenn der Wert unter z.B. 1000 fällt habe ich nur noch 3 Ziffern. Sobald das passiert, ersetzt der Zähler die Fehlende erste Roi mit der 1, dadurch hab ich dann 1999 und nicht  die richtigen 999. Die Fehlerkorrektur wird dann aktiv da der Wert außerhalb des erlauben ist. Solange alles im 3 stelligen Bereich ist, ignoriert er die erste roi mit NaN  nur wenn er einmal einen Wert bekommt 1000+ und die erste Roi einen Wert bekommt geht es nicht wieder rückwärts unter 1000, da er die NaN nicht wieder ignoriert sondern mit 1 ersetzt.
Is bisschen schwierig zu erklären hoffe du weißt was ich meine.

**Comment by jomjol** [comment]
Kannst du mir mal ein Bild von der Situation posten?

**Comment by Xsev1** [comment]
Problem gelöst, vielen Dank an Josef.
