### ISSUE TITLE
AI on the edge interface is not showing up?

### ISSUE THREAD

**Issue by Hamzademon** [jomjol/AI-on-the-edge-device#327]
I have uploaded the firmware successfully but when I typed in the IP address of the camera on webbrowser than instead of having the UI,  nothing shows up

**Comment by jomjol** [comment]
Did you also setup the sd-card and use an ESP32 with PSRAM?

**Comment by Hamzademon** [comment]
yes, I did, I am using esp32 cam which has 4 MB PSRAM. I also pasted all the files in the sd card folder with the wifi credentials,all the steps go along from uploading of firmware to led blinking of esp32 cam but no UI comes up

**Comment by jomjol** [comment]
Can you send the serial log file of the ESP32 directly after booting?

This error is unusal and I assume a problem with the configuration.

**Comment by Hamzademon** [comment]
![esp32 firmware uploading](https://user-images.githubusercontent.com/89914652/131817721-c643ce48-626d-497e-812c-071002782789.png)
here it is :)

**Comment by jomjol** [comment]
Missunderstanding. I need the serial log of the ESP32 while starting / running the firmware.
