### ISSUE TITLE
When value is blank, also rate_per_time_unit and rate_per_digitalization_round should be blank

### ISSUE THREAD

**Issue by docolli** [jomjol/AI-on-the-edge-device#3271]
### The Problem

When an error occurs, the `value` and `rate` is blank, however, the related MQTT topics `rate_per_time_unit` and `rate_per_digitalization_round` still have their last values. From my perspective they should also be blank.

### Version

15.7.0

### Logfile

```shell
<can be added, if needed>
```

### Expected Behavior

MQTT topics `rate_per_time_unit` and `rate_per_digitalization_round` go also blank, when there is a detection error.

### Screenshots

![grafik](https://github.com/user-attachments/assets/acf0263f-0d8b-468e-b79f-ba42d3f486d9)

**Comment by caco3** [comment]
@jomjol @SybexX @Slider0007 what do you think?
Would such change have a negative impact on existing users?

**Comment by jomjol** [comment]
I would not do that, because this would impact a lot of data handling on the client side.

**Comment by caco3** [comment]
Thanks @jomjol 

@docolli I agree with you that it is not proper. But like @jomjol also mentioned, a change of this behavior might have impact of other users.

**Comment by docolli** [comment]
Thank you for dicussing this. I agree that this might affect other users and will be a breaking change, however, keeping `rate_per_time_unit` and `rate_per_digitalization_round` to their latest values while `rate` is blank does not make real sense, or?

I will see if I can add some logic into my system, that these two values must be ignored, when rate is blank.
