### ISSUE TITLE
16.0.0-RC1:  Zoom enabled is discarded after upgrade

### ISSUE THREAD

**Issue by nliaudat** [jomjol/AI-on-the-edge-device#3277]
### The Problem

The old parameters as zoom = true are not preserved upon update

### Version

Release: v16-0-0-RC1 (Commit: ca01f5a+)

### Logfile

```shell
Old :
____________________

[TakeImage]
;RawImagesLocation = /log/source
WaitBeforeTakingPicture = 4
;RawImagesRetention = 15
Demo = false
Brightness = 0
Contrast = 0
Saturation = 0
Sharpness = 0 
LEDIntensity = 3
ImageQuality = 12
ImageSize = VGA
Zoom = true
ZoomMode = 0
ZoomOffsetX = 700
ZoomOffsetY = 285
Grayscale = false
Negative = false
Aec2 = true
AutoExposureLevel = -1
FixedExposure = false

NEW : 
_______________

[TakeImage]
;RawImagesLocation = /log/source
						   
;RawImagesRetention = 15
WaitBeforeTakingPicture = 4
CamGainceiling = x8
CamQuality = 10
CamBrightness = 0
CamContrast = 0
CamSaturation = 0
CamSharpness = 0
CamAutoSharpness = false
CamSpecialEffect = no_effect
CamWbMode = auto
CamAwb = true
CamAwbGain = true
CamAec = true
CamAec2 = true
CamAeLevel = 2
CamAecValue = 600
CamAgc = true
CamAgcGain = 8
CamBpc = true
CamWpc = true
CamRawGma = true
CamLenc = true
CamHmirror = false
CamVflip = false
CamDcw = true
CamDenoise = 0
CamZoom = true
CamZoomOffsetX = 0
CamZoomOffsetY = 0
CamZoomSize = 0
LEDIntensity = 3
Demo = false
```

### Screenshots

-

### Additional Context

-

**Comment by nliaudat** [comment]
For zoom, the fix is to set the "zoom size" (29 or more) if CamZoom = true

**Comment by caco3** [comment]
Yes, it is known that the reference image/camera settings might need an update.
I just added a note to the release for this:
![image](https://github.com/user-attachments/assets/5a974ada-8e35-4578-a608-396756a810c8)

**Comment by nliaudat** [comment]
Ok, but update the notice to 

"The reference image NEEDS to be updated". 

Mine was not to dark at all. It was not zoomed anymore

**Comment by caco3** [comment]
I chnage dit now to 
> **If the image is too dark after the update or otherwise different than before, you might need to update the camera settings and create a new reference image. We extended the camera settings and some devices need reconfiguration due to this.**

**Comment by nliaudat** [comment]
But the old parameters can be upgraded to new. 
That is the problem

**Comment by caco3** [comment]
> But the old parameters can be upgraded to new.
That is the problem

What do you suggest?

> the reference image and camera settings do no match the config

And here?

**Comment by SybexX** [comment]
@caco3 To solve the problem you would have to adjust the "void migrateConfiguration(void){}" in the main.cpp

**Comment by nliaudat** [comment]
In fact, I do not understand why @caco3  is closing bugs on alpha release without investigating. 

Actually, the zoom factor on my first cam was very blury and I broke it while turing it left side. 
The result is I cannot help you further to debug the problem, but there is one. 

Regards and please keep cool with helpers who spend time to find new bugs.

**Comment by SybexX** [comment]
@nliaudat The zoom function has been completely revised and now works similarly to a cell phone.
It is zoomed to the center and the offset is now +- , CamZoomSize = 0  >> no zoom and CamZoomSize = 29 >> fully zoomed in

**Comment by caco3** [comment]
@SybexX I was not aware that we renamed the parameters. Then a parameter migration of course makes sense.
Is your proposed code complete or do we have to go through a list and check?

@nliaudat We get a lot of issues and most of them actually should be discussions. Every week I convert a few of them :(
I closed this issue because we know that an update of the parameters is required and we already documented it on the release page. Of course a message directly on the UI would be much nice. But it also would be quite some work for us. We are a small team and also have other hobbies. I already spend far more time for this project than I actually should priority wise.

**Comment by SybexX** [comment]
@caco3 That should be all of the camera parameters, but I can't say what the others look like.

**Comment by caco3** [comment]
According to the diff those are the changes:
![image](https://github.com/user-attachments/assets/3ea02b14-aeb2-4721-9c72-6021036c7fc0)

**Comment by caco3** [comment]
> However, there will still be problems with zoom because there are more zoom levels and the offset is now +-
> ZoomMode = 0/1 vs. CamZoomSize = 0 to 29
> ZoomOffsetX = 0 to 800 vs. CamZoomOffsetX = +/- 480
> ZoomOffsetY = 0 to 600 vs. CamZoomOffsetY = +/- 360

That is ok. We can't handle everything automatically.

**Comment by p0macs** [comment]
The Configuration page refers to the old parameters name, at least for me:
![image](https://github.com/user-attachments/assets/9c80f1cb-d935-466d-89eb-ddc393922f69)

**Comment by SybexX** [comment]
@p0macs try Strg + F5
