### ISSUE TITLE
Fileserver "Delete All" does only work on file level, but not on directories...

### ISSUE THREAD

**Issue by krikk** [jomjol/AI-on-the-edge-device#328]
wanted to delete all my all logged source images ....it only works on file level: 
![image](https://user-images.githubusercontent.com/5165445/131668471-7b1516a0-d2c9-4fc4-911b-127d72321d9b.png)

but not when i do the same on directory level...
![image](https://user-images.githubusercontent.com/5165445/131668580-f2ea08c7-e37d-48c3-a41c-c8b6cfe8e6d5.png)

could you plz have a look into this, thx

**Comment by krikk** [comment]
and i also think the setting "LogfileRetentionInDays" on both the source image and digits does not have an effect? ... i have lots of images which should not happen with a LogfileRetentionInDays = 1 .

**Comment by friedpa** [comment]
Ir works perfectly in my environment.

**Comment by jomjol** [comment]
@krikk: Thanks for your oberervation. The fileserver is a very rudimentary implementation and only intended for small operations. Deleting full subdirectories is none of them. If you need to do this, I suggest to make this on an external SD-drive.

Could be a good idea to make this more clear in the environment. Currently I'm not planning to extend this feature for directories and therefore I close this issue.
