### ISSUE TITLE
16.0.0-RC1: new "enable/disable" not reflected in the tool tips

### ISSUE THREAD

**Issue by Piti61** [jomjol/AI-on-the-edge-device#3282]
### The Problem

Former "true/false" was changed to  "enable/disable" with this version. But this change was not reflected in several tool tips.

### Version

16.0.0-RC1

### Logfile

```shell
.
```

### Screenshots

![image](https://github.com/user-attachments/assets/3fb9a50b-76bf-4055-8e73-a1a580cf4814)

**Comment by caco3** [comment]
Thanks for your report!
This is true for all boolean parameters.
I changed it now to show true/false explicitly in the drop down box.
