### ISSUE TITLE
16.0.0-RC1: Denoise is numeric, Tooltip shows "true" as default

### ISSUE THREAD

**Issue by Piti61** [jomjol/AI-on-the-edge-device#3283]
### The Problem

A numeric value cannot have "true" as default.

### Version

16.0.0-RC1

### Logfile

```shell
.
```

### Expected Behavior

Default should be numeric as well

### Screenshots

![image](https://github.com/user-attachments/assets/6b59b1cc-3c4e-4e8e-a5ae-09200e34f89b)

**Comment by caco3** [comment]
Thanks!

Fixed in https://github.com/jomjol/AI-on-the-edge-device/commit/4c3dcd8c290d9493f8d2fad0c126de1cc8a0de83
