### ISSUE TITLE
New Training Data for Watermeter Digits with frame - iPearl

### ISSUE THREAD

**Issue by fliegema** [jomjol/AI-on-the-edge-device#3286]
### Files

Hi, we have a Watermeter from iPearl. Unfortunatley it has on the LCD display frames around the numbers, hence sometimes the digitalisation interprets the numbers diffrently. The frame is still within the space between the frame around the number itself and the thicker line. I was not able to find those kind of numbers upfront.

The zip file: 
[esp.zip](https://github.com/user-attachments/files/17230345/esp.zip)

Details to the watermeter itself:
[Wasserzähler](https://www.xylem.com/de-de/products--services/metrology-equipment-for-utilities/meters/iperl-international-water-meter/)

Below a picture of the display itself
![all numbers](https://github.com/user-attachments/assets/0885e8f5-8ad6-4ca3-9542-4b2fdbfcc4bb)

let me know if you need further information on the numbers.

**Comment by jomjol** [comment]
I need an image of every digit (0, 1, 2, ... 9) and I need them in a better quality.

Then I'm glad to update the training.

**Comment by developnoop** [comment]
Hmm, @jomjol for this type of reader there was already data training provided #2422.
Maybe @fliegema uses a different number model?

**Comment by fliegema** [comment]
> Hmm, @jomjol for this type of reader there was already data training provided #2422. Maybe @fliegema uses a different number model?
> 
> I have the same watermeter and it works nearly flawless.

Thank you so much for the input, Ineed I had never changed the model (was dig-cont 0611 s3). With the latest model dig-class100-0173-s2-q.tflite it works since 5 hours without any problem. Hence i will close the request and thank you for your work and feedback!
