### ISSUE TITLE
16.0.0 RC2: MQTT topics inconsistent

### ISSUE THREAD

**Issue by dandjo** [jomjol/AI-on-the-edge-device#3301]
### The Problem

I noticed that the case of some MQTT topics has changed. I suspect some are a search-replace issue of a refactoring. It affects:

* rate_per_Digitization_round (is) > rate_per_digitization_round (should)

Nit, but also an inconsistency (camel-case vs snake-case):

* freeMem > free_mem
* wifiRSSI > wifi_rssi
* CPUtemp > cpu_temp
* changeabsolut > change_absolute

I would suggest to use one naming convention for all topics.

### Version

16.0.0-RC2 (Commit: 3708698+)

### Logfile

```shell
water_meter/status Take Image
water_meter/status Aligning
water_meter/status Digitization of ROIs
water_meter/status Digitization of ROIs
water_meter/status Post-Processing
water_meter/status Sending MQTT
water_meter/connection connected
water_meter/uptime 894
water_meter/freeMem 785799
water_meter/wifiRSSI -58
water_meter/CPUtemp 50
water_meter/main/value 341.1701
water_meter/main/error no error
water_meter/main/rate 0.000000
water_meter/main/rate_per_time_unit 0.000000
water_meter/main/changeabsolut 0.0000
water_meter/main/rate_per_Digitization_round 0.0000
water_meter/main/raw 00341.1701
water_meter/main/timestamp 2024-10-05T22:09:34+0200
water_meter/main/json   {
    "value": "341.1701",
    "raw": "00341.1701",
    "pre": "341.1701",
    "error": "no error",
    "rate": "0.000000",
    "timestamp": "2024-10-05T22:09:34+0200"
  }

water_meter/status Flow finished
```

**Comment by caco3** [comment]
> * rate_per_Digitization_round (is) > rate_per_digitization_round (should)

You are right, thats an error that happened during the renaming.
Its now fixed in a0333d906fe433892c20dc534d3ad6c0b6f0910c

Also it reminded me that we should mention this topic renaming in the changelog.

> Nit, but also an inconsistency (camel-case vs snake-case):
> [..]
> I would suggest to use one naming convention for all topics.

I agree it is odd. We kept it on purpose this way to keep it consistent with the (already longer existing) REST API output.

**Comment by dandjo** [comment]
What about making those topics configurable with fallback defaults?

**Comment by caco3** [comment]
We already have far too many config options. Keep in mind that we ideally would test them all. But that is just too much to cope with. And every option also can be messed up by users who do not understand the impact.

**Comment by dandjo** [comment]
Okay, I see that.
