### ISSUE TITLE
No flashlight when creating a reference

### ISSUE THREAD

**Issue by lewicki-pk** [jomjol/AI-on-the-edge-device#3304]
Hi,
I'm trying to use your AI on the edge. I've installed 15.7 via Webinstall and then copied over the files taken from 1.16.0 remote_setup.zip.
It seems to be working fine but I cannot get through the setup:
On step 1 I have no problem to work with adjusting focus - there the flashlight works.
As soon as I move on to step 2- flashlight (I mean the built in LED) stops working.

Restarting setup doesn't make it work - even going back to step 1 doesn't bring the flashlight.
The only thing is to restart the device.

I thought that changine LEDIntensity value would help but it doesn't.

Are you aware of such problem? Is that a bug?

**Comment by lewicki-pk** [comment]
Ok. Nevermind.
This works fine after updating and having corresponding versions of app and configs...

**Comment by caco3** [comment]
Yes, don't copy over some files manually. Always use the OTA-Functionality with the `update`-file.
