### ISSUE TITLE
Problem when trying to compile and upload from Platform IO

### ISSUE THREAD

**Issue by wianoski** [jomjol/AI-on-the-edge-device#331]
i already followed the instruction, but the result from compiled and uploaded the codes are like this
![image](https://user-images.githubusercontent.com/20513613/131956558-20823fca-7e89-473b-8ab7-4eed3ff89641.png)

Apparently the function stuck at  TFliteDoAutoStart() , is it normal or is there anything i should change ? because i didnt change anything except trying to find out what exactly happening 

Thank you

**Comment by jomjol** [comment]
Up to this it looks pretty normal. Afterwards the config.ini should be loaded. Did you setup the sd-card correctly?

**Comment by wianoski** [comment]
already setup the SD-Card correctly, unfortunely everytime i compile and upload it from your git, it didnt work properly just like from firmware folder you gave it, everytime i access the index it'll be crased, and i guess when the first time use it'll be directly to the starting webpage, but when i compile and run it, it didn't happen

**Comment by wianoski** [comment]
The initiation like [MakeImage] and other config didnt happen, it stuck just like the screenshot i gave

**Comment by jomjol** [comment]
hard to diagnose from far. The flashed firmware is running correctly?

**Comment by wianoski** [comment]
im using esp-idf, cant use the platform io

**Comment by jomjol** [comment]
Getting closer. I assume your using esp 4.3? This is not working yet. Try 4.1 or 4.2 instead.

**Comment by wianoski** [comment]
on it, gonna try 4.2 version, will update as soon i try

**Comment by wianoski** [comment]
![image](https://user-images.githubusercontent.com/20513613/132004764-2d5fd00a-1622-47ba-b83d-13926f3250cd.png)
well i tried to back to use platform io and this what i get, i didnt know what i must to do, please help

**Comment by jomjol** [comment]
Hi, I'm not an expert in the Platform IO, but also just using it as a tool. Maybe you can find some information in the support forum to Platform IO. Unfortunatly I'm not able to help you with this error message. 

What I can tell for sure: if you use a freshly setup Ubuntu 20.04 and follow the build instructions out of the wiki (https://github.com/jomjol/AI-on-the-edge-device/wiki/Build-Instructions), the code will compile. I just tried this two days ago in a newly setup virtual maschine.

**Comment by jomjol** [comment]
I assume, you have been successfull, otherwise please feel free to contact me again.
I will close this issue for the time beeing.
