### ISSUE TITLE
add contributors name in readme 

### ISSUE THREAD

**Issue by Ayushjhawar8** [jomjol/AI-on-the-edge-device#3310]
### The Feature

**Title:** Request to Add Contributor Profiles to README

### Overview
I would like to propose the addition of contributor profiles to the README file of this repository. Highlighting contributors can encourage collaboration and recognize the hard work of individuals who have contributed to the project.

### Proposed Changes
- Create a section in the README file dedicated to contributors.
- Include the following information for each contributor:
  - GitHub profile link
  
### Benefits
- Acknowledges the efforts of contributors, fostering a sense of community.
- Provides visibility to contributors and encourages new developers to participate.
  
Thank you for considering this proposal!

**Comment by Ayushjhawar8** [comment]
assign me if you like the idea

**Comment by caco3** [comment]
Can this section be generated automatically?
Because i would not want to have to update it manually!

Feel free to provide a Pull request.

**Comment by caco3** [comment]
new approach, only trigger it manually, see https://github.com/jomjol/AI-on-the-edge-device/pull/3325

**Comment by Ayushjhawar8** [comment]
oh cool now i think its perfect to use
