### ISSUE TITLE
Better Footer with social links can be implemented 

### ISSUE THREAD

**Issue by NishantRana07** [jomjol/AI-on-the-edge-device#3311]
### The Feature

I can implement Better Footer with social links, Please assign it to me for faster execution and implementation

**Comment by caco3** [comment]
Feel free to create a Pull Request.
How ever I am not sure how useful it is since the website is onyl intended for the devices owner and not for the public.

**Comment by SURYANSH-RAI** [comment]
I have done that please review and accept my PR :)
