### ISSUE TITLE
AutoSharpness in "Reference Image and Camera Settings" Wrong behaviour?

### ISSUE THREAD

**Issue by friedpa** [jomjol/AI-on-the-edge-device#3327]
### The Problem

Mir ist aufgefallen, wenn man AutoSharpness "disable" hat, kann man den Slider Sharpness verstellen, wenn AutoSharpness auf enable steht ist der Slider ausgegraut. Sollte doch genau umgekehrt sein, oder?

![grafik](https://github.com/user-attachments/assets/d804af67-597f-42d2-a0b1-436b249e1274)

![grafik](https://github.com/user-attachments/assets/d5a80d48-5715-4034-8438-c105ba42ca7f)

### Version

16.0.0

### Logfile

```shell
No Logfile
```

**Comment by SybexX** [comment]
AutoSharpness = enable ->> Sharpness wird von der Kamera geregelt, also keine Einstellung möglich/nötig ->> Slider ausgegraut
AutoSharpness = disable ->> Sharpness wird auf den manuell eingestellte Wert gesetzt (Slider-Wert) ->> Slider verfügbar

**Comment by caco3** [comment]
`Sharpness` kannst Du dir vorstellen als `Manual Sharpness`. Und das macht bei aktiviertem `AutoSharpness` natürlich keinen Sinn.
