### ISSUE TITLE
Cannot select unit conversion in HomeAssistant

### ISSUE THREAD

**Issue by caco3** [jomjol/AI-on-the-edge-device#3333]
### Discussed in https://github.com/jomjol/AI-on-the-edge-device/discussions/3218

<div type='discussions-op-text'>

<sup>Originally posted by **Lackmake** September  1, 2024</sup>
I have a few smartplugs where i can manually select how HA should display the power values, like this:
![image](https://github.com/user-attachments/assets/417af5fe-caa1-464c-b32c-1d148c0884fc)

For the AI-on-the-edge entities however i cannot. The option is completely missing:
![image](https://github.com/user-attachments/assets/b4d3ed5b-4cd1-4376-bd8f-cadc34d6b830)

What i found is that the rate-sensor is missing the "device_class" attribute. That would have to be added here for both "rates", i think "power" would be correct as thats what my smartplugs report:
https://github.com/jomjol/AI-on-the-edge-device/blob/67c3020d7df7771d6aeae06f435677a4604af48b/code/components/jomjol_mqtt/server_mqtt.cpp#L187-L198

But i am not 100% sure if that is the only reason why home assistant doesnt let me choose the unit....i also found this old thread about the "native_unit_of_measurement": https://community.home-assistant.io/t/unit-of-measurement-2022-4/409860/16
</div>

**Comment by caco3** [comment]
@Lackmake I updated the `Device Class` according your suggestions in https://github.com/jomjol/AI-on-the-edge-device/pull/3332

Can you please test and see if it is ok now?
Please test the latest (most top) build from https://github.com/jomjol/AI-on-the-edge-device/actions?query=branch%3Asupport-homeassistant-2024.10

**Comment by Lackmake** [comment]
I now have a device_class of "volume_flow_rate" for my rate-sensors, thats not correct. Should be "power"

![image](https://github.com/user-attachments/assets/325f559c-c17d-4a99-925e-33534149d993)

**Comment by Lackmake** [comment]
Ok, so i played around a bit more and changed the mqtt-discovery values with a mqtt client and noticed that AIOTE does report a "unit_of_meas" and not "unit_of_measurement". See here:
https://github.com/jomjol/AI-on-the-edge-device/blob/67c3020d7df7771d6aeae06f435677a4604af48b/code/components/jomjol_mqtt/server_mqtt.cpp#L122-L124

When i set the device_class to "power" and fix the "unit_of_meas**urement**" then it works as i hoped and i can select the unit in home assistant. Both fixes are needed, either one alone does not enough

**Comment by Lackmake** [comment]
The wrong device_class probably comes from here:

https://github.com/jomjol/AI-on-the-edge-device/blob/f6fd351d38cbcd2123f4232859fe73f945e6f68d/code/components/jomjol_mqtt/server_mqtt.cpp#L193-L197

I think in the if condition you wanted to set "rate_device_class" not value_state_class. Maybe a copypaste error from a few lines above :D

**Comment by caco3** [comment]
> AIOTE does report a "unit_of_meas" and not "unit_of_measurement"

This is also correct according to the specification, see Supported abbreviations in https://www.home-assistant.io/integrations/mqtt/#discovery-messages
![grafik](https://github.com/user-attachments/assets/d730de0b-0f7d-4ea5-82ee-a4dd30f7c987)

**Comment by caco3** [comment]
> I think in the if condition you wanted to set "rate_device_class" not value_state_class. Maybe a copypaste error from a few lines above :D

You are right.
it is now fixed in the latest version.

**Comment by Lackmake** [comment]
I can select the unit now, perfect, thank you very much :)
![image](https://github.com/user-attachments/assets/d471973e-6425-47e4-8b16-aa332c3c91d0)

**Comment by caco3** [comment]
Fixed in https://github.com/jomjol/AI-on-the-edge-device/pull/3332
