### ISSUE TITLE
No error but value not updated to raw

### ISSUE THREAD

**Issue by ykri** [jomjol/AI-on-the-edge-device#3334]
### Issue

I have good reading of the meter with no errors but the value stays equals to pre-value and does not update to the raw. 

![IMG_0034](https://github.com/user-attachments/assets/8ac89260-d8a4-4fbf-a713-d6b1347a30b1)

**Comment by SybexX** [comment]
@ykri look at the following setting: https://jomjol.github.io/AI-on-the-edge-device-docs/Parameters/#parameter-numberchangeratethreshold

**Comment by ykri** [comment]
Thanks

**Comment by ykri** [comment]
Y
