### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by bilalmirza74** [jomjol/AI-on-the-edge-device#3335]
### The Problem

Links are broken in the [README](https://github.com/jomjol/AI-on-the-edge-device?tab=readme-ov-file) 
i.e (404 page not found)

### Version

16.0.0

### Logfile

```shell
N/A
```

### Expected Behavior

should show the directed page

### Screenshots

![{4954F86B-ADB3-4010-A1BC-8A35C10D01C3}](https://github.com/user-attachments/assets/96d54130-b99a-4ae5-b2c7-1c57ab8eb2eb)

![image](https://github.com/user-attachments/assets/39a54e63-fd0a-43ad-a7b9-0e00150f0751)

**Comment by friedpa** [comment]
Latest Version is 16.0.0, please upgrade.

**Comment by friedpa** [comment]
And? Same problems as before?

**Comment by friedpa** [comment]
I cannot find any broken link...

![grafik](https://github.com/user-attachments/assets/e53f5fff-2759-4015-82ac-b7f5d68bc8e7)
