### ISSUE TITLE
"Manual Control" menu entry no longer shown if HA Discovery is enabled

### ISSUE THREAD

**Issue by caco3** [jomjol/AI-on-the-edge-device#3339]

**Comment by Slider0007** [comment]
@caco3: Without testing, I assume you only have to revert this line back.
![image](https://github.com/user-attachments/assets/8b8363b1-b003-4741-882c-2a27e690f18d)

It was changed without any reason, any relation and any comment in #3029.

**Comment by caco3** [comment]
Thanks for the hint
