### ISSUE TITLE
Enable Flow Control UI menu entry

### ISSUE THREAD

**Issue by caco3** [jomjol/AI-on-the-edge-device#3343]
@Slider0007  can we enable this now?
https://github.com/jomjol/AI-on-the-edge-device/blob/dadf18f5c959443c665b064b51ea2c7805f160c2/sd-card/html/index.html#L138

It seems the REST entrypoint exists now.

(although I would prefer we return JSON instead of plain text, but that would require a general API refactoring)

**Comment by caco3** [comment]
what is missing?
Currently it already reports if it can be scheduled or not

**Comment by Slider0007** [comment]
If I remember right (This was long time agao, beginning of last year when I proposed the main flow refactoring) it is only working with autostart active, disabling autostart, main flow is not active anymore.

I could be that the functionality can be provided partly, but the main benefit to trigger a start if no autostart is active is not possible. If actual reaction and functionality is sufficient for you, feel free to activate it. :-)

**Comment by caco3** [comment]
Yes, the code seems still to be that way that it only works if the autostart is enabled.
I would keep it that way for now and just enable the UI entry, since the REST API anyway is available.

As a workaround to work around disabling the autostart, one can just set a very large interval.

Refactoring the whole loop thing is out of scope from my side.

**Comment by Slider0007** [comment]
Once it's on the WebUI, hopes will be raised and questions will come, so I didn't actively do that at the time. As soon as I use the REST API call, I'm already deeper into the topic and usually also more experienced with software.

Just my cents...

**Comment by caco3** [comment]
we also just could disable the disabling option and instead let it set to max. 24h.
disabling it always was marked as a debug option: https://jomjol.github.io/AI-on-the-edge-device-docs/Parameters/#parameter-autostart

**Comment by Slider0007** [comment]
This could be a solution

**Comment by caco3** [comment]
Relates to https://github.com/jomjol/AI-on-the-edge-device/issues/3302#issuecomment-2424223581

**Comment by caco3** [comment]
https://github.com/jomjol/AI-on-the-edge-device/pull/3423
