### ISSUE TITLE
Rate too high - Rate Change ignored?

### ISSUE THREAD

**Issue by friedpa** [jomjol/AI-on-the-edge-device#3347]
### The Problem

I have currently a RateChange Maximum of 0,07m3 = 70 Liter eingestellt:

![grafik](https://github.com/user-attachments/assets/a68e6482-95eb-488e-8cf5-b93f278ca628)

Heute aber ist diese RateChnage anscheinend ignoriert worden:

![grafik](https://github.com/user-attachments/assets/d2d12a5d-d12d-4ef2-b535-fea6088ea449)

Im Log File unten auf den PerValue Wert achten

### Version

Development-Branch: main (Commit: c448ece+)

### Logfile

```shell
[2d00h19m12s] 2024-10-19T15:10:26	<ERR>	[POSTPROC] main: Raw: 00563.9901, Value: , Status: Neg. Rate - Read:  - Raw: 00563.9901 - Pre: 563.9999 
[2d00h31m12s] 2024-10-19T15:22:26	<ERR>	[POSTPROC] main: Raw: 00563.9901, Value: , Status: Neg. Rate - Read:  - Raw: 00563.9901 - Pre: 564.9901 
[2d00h34m12s] 2024-10-19T15:25:26	<ERR>	[POSTPROC] main: Raw: 00563.9901, Value: , Status: Neg. Rate - Read:  - Raw: 00563.9901 - Pre: 564.9901 
[2d00h40m12s] 2024-10-19T15:31:26	<ERR>	[POSTPROC] main: Raw: 00564.0098, Value: , Status: Neg. Rate - Read:  - Raw: 00564.0098 - Pre: 564.9901 
[2d00h43m12s] 2024-10-19T15:34:26	<ERR>	[POSTPROC] main: Raw: 00564.0098, Value: , Status: Neg. Rate - Read:  - Raw: 00564.0098 - Pre: 564.9901 
[2d00h46m12s] 2024-10-19T15:37:26	<ERR>	[POSTPROC] main: Raw: 00564.0098, Value: , Status: Neg. Rate - Read:  - Raw: 00564.0098 - Pre: 564.9901 
[2d00h49m12s] 2024-10-19T15:40:26	<ERR>	[POSTPROC] main: Raw: 00564.0098, Value: , Status: Neg. Rate - Read:  - Raw: 00564.0098 - Pre: 564.9901 
[2d00h52m12s] 2024-10-19T15:43:26	<ERR>	[POSTPROC] main: Raw: 00564.0195, Value: , Status: Neg. Rate - Read:  - Raw: 00564.0195 - Pre: 564.9901
```

**Comment by SybexX** [comment]
Ich würde sagen, dass es so schon richtig sein wird, den du hast ja die Wertänderung auf "pro Minute" eingestellt.
Dadurch ist eine Wertänderung von 1050 Liter Wasser nach 15 Minuten noch ok.
Um jedoch korrekte Schlussfolgerungen ziehen zu können, benötigt man die genaue/richtige Zeitdifferenz.
![Unbenannt](https://github.com/user-attachments/assets/04db18a7-9fdc-4664-91e5-eb744edb5d9f)

**Comment by friedpa** [comment]
Aus dem oberen LOG erkenne ich 12 Minuten differenz zwischen den beiden PreValve Werten, oder? 12 *70 Liter also, oder sitze ich hier einem Irrtum auf (der Differenzwert ist aber 990,2 Liter). Und warum ändert sich nur der PreValue Wert?

**Comment by SybexX** [comment]
Du mußt die Zeit vom Setzen des vorheriegen PreValue Wertes dazu rechnen, dieser Zeitpunkt ist ja leider im Log nicht aufgeführt, weil da kein Fehler vorlag/vorliegen konnte. Zwischen der Ersten und der Zweiten Zeile muß eine erfolgreiche Auswertung stattgefunden haben, wo der PreValue Wert neu gesetzt wurde und natürlich vor der ersten Zeile. Deshalb kann mann leider die genaue Zeitdifferenz nicht bestimmen^^

**Comment by SybexX** [comment]
@friedpa Ich habe mal die dafür zuständigen Code-Zeilen rausgesucht und konnte in der Berechnung kein Fehler finden:
ClassFlowPostProcessing.cpp | Zeile 744 bis 985
````c
bool ClassFlowPostProcessing::doFlow(string zwtime) {
.
.
    // aktuelle Zeit auslesen
    imagetime = flowTakeImage->getTimeImageTaken();
.
.
    // Zeitdifferenz zwischen der letzten erfolgreichen Runde und der aktuellen Runde berechnen
    double LastPreValueTimeDifference = difftime(imagetime, NUMBERS[j]->timeStampLastPreValue);   // in seconds
.
.
.
    // Zeitdifferenz von Sekunden zu Minuten umrechnen
    LastPreValueTimeDifference = LastPreValueTimeDifference / 60; // in minutes
.
    // Wertänderung pro Minute berechnen -> (Aktueller Wert minus Vorwert) geteilt durch vergangene Minuten
    NUMBERS[j]->FlowRateAct = (NUMBERS[j]->Value - NUMBERS[j]->PreValue) / LastPreValueTimeDifference;
.
.
.
    if (NUMBERS[j]->MaxRateType == RateChange) {
        _ratedifference = NUMBERS[j]->FlowRateAct;
    }
.
    // Vergleichen, ob die Wertänderung pro Minute, grösser der erlaubten Wertänderung ist
    if (abs(_ratedifference) > abs(NUMBERS[j]->MaxRateValue)) {
        // Wenn ja, Fehler ausgeben und die Auswertung abbrechen
        NUMBERS[j]->ErrorMessageText = NUMBERS[j]->ErrorMessageText + "Rate too high - Read: "............
        continue;
    }
.
.
.
    // aktuellen Wert als Vorwert setzen
    NUMBERS[j]->PreValue = NUMBERS[j]->Value;
    NUMBERS[j]->PreValueOkay = true;
.
    // aktuelle Zeit als letzte Auswertzeit setzen
    NUMBERS[j]->timeStampLastValue = imagetime; 
    // aktuelle Zeit als letzte Vorwertzeit setzen
    NUMBERS[j]->timeStampLastPreValue = imagetime;
.
.
.
}
````

**Comment by friedpa** [comment]
Hmm, dann schließe ich einmal den case.
