### ISSUE TITLE
Feature request: rising values filter

### ISSUE THREAD

**Issue by s0170071** [jomjol/AI-on-the-edge-device#336]
I acknowledge that there is already some filtering going on, I still do have issues with sporadically too large readings. 
As I understand it, the value is only communicated if it did a) rise and b) no more than the max flow (which uses a comma instead of a decimal dot ?)

I would go one step beyond. Assume there were 3 readings, a, b and c. 
I propose to send out reading b if it is larger than a and smaller than c. 
This way there had to be two false large readings in a row until the a false reading is communicated.  Of course the max flow criteria should still be obeyed. I am aware that the meter would read a 3 minute old reading, but I could live with that :-)

**Comment by jomjol** [comment]
No, the algorithm is a little bit different: it always will send out a value. But if you have limited to positive increase and a max flow rate, than in case, the limits are violated, then there will be send out the old value.

There are douzend ideas, how you can check the consistency. If you want to update this, you can find the handling in the file ClassFlowPostProcessing. There new way could be implemented.
