### ISSUE TITLE
ESP32 Cam unresponsive after about 20h

### ISSUE THREAD

**Issue by zimbo86** [jomjol/AI-on-the-edge-device#3366]
### The Problem

I´m using an ESP32Cam as hardware.
It works fine for about 20 hours. After that the red led on the board blinks 3 times pause 2 times.
When rebooting it takes a while and it will work again. The logfile does not show anything before the cold boot.
What can i do for further troubleshooting?

### Version

latest

### Logfile

```shell
xx
```

**Comment by SybexX** [comment]
https://jomjol.github.io/AI-on-the-edge-device-docs/StatusLED-BlinkCodes/

**Comment by zimbo86** [comment]
> https://jomjol.github.io/AI-on-the-edge-device-docs/StatusLED-BlinkCodes/

thanks, missed that.
Replaced the microsd card, seems better now.
