### ISSUE TITLE
Add Previous Value Input for Plausibility Check

### ISSUE THREAD

**Issue by Ashcora** [jomjol/AI-on-the-edge-device#3379]
**Description:**

Currently, the AI-on-the-edge-device misinterprets the digit "8" as "4" due to the specific font used on my powermeter. This misrecognition leads to implausible readings, such as my powermeter showing a reduction of 4000 kW within 1.5 hours. To address this issue, it would be beneficial to have a feature allowing users to input the previous value, and enabling the AI to perform a plausibility check and correct obvious errors.

**Feature Proposal:

**Previous Value Input:**
- Allow users to input the previous meter reading value as "real update point" for the next round.
- Use this input as a reference to check the plausibility of the newly recognized value.

**Plausibility Check:**
- Implement a logic to compare the new value with the previous value.
- If the difference is beyond a reasonable threshold (e.g., a sudden decrease of 4000 kW within 1.5 hours), prompt a warning or automatically correct the value.

**Use Case:**

- User inputs the previous meter reading of 98000 kW.
- The AI misreads the next value as 94000 kW due to the font misinterpretation.
- The system recognizes the implausibility of such a large decrease within a short time frame.
- The system either prompts a warning to the user or corrects the value to a more reasonable figure.

**Benefits:**
- Increases the accuracy of meter readings.
- Reduces the need for manual corrections.
- Enhances user trust and reliability of the AI system.

**Comment by SybexX** [comment]
have you tried this parameter: https://jomjol.github.io/AI-on-the-edge-device-docs/Correction%20Algorithm/#checkdigitincreaseconsistency

**Comment by SybexX** [comment]
Did you set PreValue correctly before the reboot? Normally the algorithm should turn the 4 into an 8.

**Comment by Ashcora** [comment]
@SybexX : Yes it is set to the respective value (which is +1 in the meantime 😆 ). 
<img width="169" alt="image" src="https://github.com/user-attachments/assets/bbf787c1-f40c-471c-ab94-b129287237a4">

I have reset all the settings and reference images to check if they are now recognized correctly.
Thanks for your help and instant support.

**Comment by Ashcora** [comment]
It seems to be working so far (after making the reset) - with this expert parameter it is to be seen as kind of plausibility check 🙂
