### ISSUE TITLE
Small images & recognition values missing in latest version 

### ISSUE THREAD

**Issue by michaeljoos72** [jomjol/AI-on-the-edge-device#338]
Hi Jomjol

In latest version 8.3.0 it doesn't show the small pictures & values anymore in recognition tab:

![image](https://user-images.githubusercontent.com/20517474/132974594-927ae7e6-aac2-4a37-b2d7-b7eef5c6c879.png)

I'm testing new default CNN (dig1200s1q.tflite, ana0700s1lq.tflite) on my watermeter and it really looks good! I have trained my own tflite-files one year ago because of my very special model here in Switzerland :) Could be that it still does not recognize number 3:

![20201010-081900_digit5](https://user-images.githubusercontent.com/20517474/132976139-9d28def1-5135-4297-af5f-0795cc0504d7.jpg)
![20201009-160326_digit6](https://user-images.githubusercontent.com/20517474/132976458-54bd8ebf-b9fe-461e-8db6-09d85ade8ded.jpg)

But need to wait & test a few days now.

Thanks a lot for your effort all the time!

BR
Michael

**Comment by jomjol** [comment]
Thanks for thint. I'll have a look onto it. There were some refractoring, maybe something got lost.
Regard the "3" in the last version so many numbertype were added, maybe it works again with the general (current version 12.1).

**Comment by jomjol** [comment]
Corrected in the current rolling and wil be transfered to the next release soon.
