### ISSUE TITLE
OV2640: Brightness, contrast + saturation not working anymore

### ISSUE THREAD

**Issue by Slider0007** [jomjol/AI-on-the-edge-device#3381]
### The Problem

OV2640: Brightness, contrast and saturation parameter are not functional anymore.

This workaround to enable functionality is somewhere lost between 15.7 and 16.0:
https://github.com/jomjol/AI-on-the-edge-device/blob/0d0b0187f45d84cb0d404d7f23da72bcff0b9075/code/components/jomjol_controlcamera/ClassControllCamera.cpp#L218

Workaround is still required for OV2640 camera even with newest camera driver.
For OV5640 it's not required, it's functional without this workaround.

### Version

16.0.0RC4

### Logfile

```shell
n.a.
```

**Comment by Slider0007** [comment]
@SybexX: FYI

**Comment by caco3** [comment]
@SybexX or @Slider0007 Does one of you have such HW and can add and test a fix?

**Comment by SybexX** [comment]
Please test whether this fixes the problem (nothing has changed for the OV5640): https://github.com/SybexX/AI-on-the-edge-device/tree/fix_ov2640_brightness_contrast_saturation

**Comment by Slider0007** [comment]
Using the provided test firmware, brightness, contrast and saturation adaption is working again with OV2640.

Be ware: I've only tested the part which is related to this issue and not the multiple additional changes which are also included in this branch. (I'm not sure if this branch is intended to be merged directly or split up again to only address this issue here. IMHO it usually doesn't make sense to test a branch which contains multpile topics.)
