### ISSUE TITLE
External Light source (LED stripes)

### ISSUE THREAD

**Issue by jomjol** [jomjol/AI-on-the-edge-device#339]
I started to implement a WS281x controll into your GPIO-handling extension. With this one can controll external LEDs with arbritrary RGB-value (color, intensity) and number (up to the limit of the power supply :-)).

@Zwer2k:  Just have a look into to current rolling. Not that nice code, but working in my test device.

**Comment by Zwer2k** [comment]
Hello Jomjol,

You've been very busy again :-)
I will try it out in the near future.

**Comment by jomjol** [comment]
To be followed in the next major release
