### ISSUE TITLE
Spontaneous Reboots

### ISSUE THREAD

**Issue by michaeljoos72** [jomjol/AI-on-the-edge-device#34]
Hi Jomjol

Ich habe mir jetzt eine Test-Umgebung eingerichtet die bei einem Absturz/Reboot das System stoppt und die Core-Dump-Informationen in der Console ausgibt. Diese Information kann dann mit einem Python-Script "lesbar" gemacht werden. Aber ganz ehrlich...ob es was hilft weiss ich auch nicht.

Diese Dump-Files sind im "normalen" Betrieb . . . sprich ohne Zugriff auf den Webserver:
(Ich habe momentan vielleicht noch alle 4h ein Reboot)
[result_2.txt](https://github.com/jomjol/AI-on-the-edge-device/files/5316109/result_2.txt)
[result_3.txt](https://github.com/jomjol/AI-on-the-edge-device/files/5316110/result_3.txt)
[result_4.txt](https://github.com/jomjol/AI-on-the-edge-device/files/5316111/result_4.txt)
[result_1.txt](https://github.com/jomjol/AI-on-the-edge-device/files/5316112/result_1.txt)

Und hier war der Reboot bei intensiver Benutzung des Webservers:
[result_http.txt](https://github.com/jomjol/AI-on-the-edge-device/files/5316120/result_http.txt)

Bei allen ist es der Task "'task_autodoFlow'".

Einfach mal als Input. Vielleicht hilft es ja.

Gruss
Michael

**Comment by jomjol** [comment]
Bei mir läuft eine Version mit intensiven Log-Einträgen an verschiedenen Stellen. Ich hatte heute Nacht 3 Reboots, jedesmal an einer anderen Stelle im Programm. Allen gemeinsam ist, dass es immer im Umfeld des Berechnen des neuronalen Netzes für die analogen Zeiger passiert. (1x beim Laden des Bildes, 1x nach Berechnen des CNN, 1x ?).
Das es immer im Taskk "task_autodoFlow" stattfindet ist normal, da das der übergreifende Task für die Steuerung der Erkennung ist.

**Comment by michaeljoos72** [comment]
Ich hatte damals einen ESP32 mit einem Mini USB UART Programmer direkt am Laptop und dann in der SDKCONFIG:

CONFIG_ESP32_PANIC_PRINT_HALT=1
# CONFIG_ESP32_PANIC_PRINT_REBOOT is not set

und

CONFIG_ESP32_ENABLE_COREDUMP_TO_UART=y
# CONFIG_ESP32_ENABLE_COREDUMP_TO_NONE is not set

Und dann in VSSCript direkt im Terminal geloggt bis zum Crash.

Danach wird es etwas kompliziert. Den output musst du in ein File kopieren und dann mit einem python script decodieren. Der Befehl dazu sieht etwas so aus:

python c:\Users\micha\esp\components\espcoredump\espcoredump.py info_corefile -t b64 -c c:\Users\micha\esp\hello_world\dump_1.txt c:\Users\micha\esp\hello_world\build\firmware.elf

Wobei bei mir die Pfadangaben willkürlich sind. Wichtig ist "dump_1.txt" mit den Informationen von oben und "firmware.elf" aus dem Wasserzähler-Projekt. "firmware.elf" kriegst du soviel ich mich erinnern kann beim kompilieren (build)

Gruss
Michael

**Comment by jomjol** [comment]
Ich habe gerade den tflite-Kernel upgedated. Dort scheint sich einiges getan zu haben. Daher habe ich es erstmal einen eigenen Branch erzeugt:  `update_tflite`.
Auch wenn sich unter der Haube wohl viel verändert hat (175 Dateinen), so ist das Interface fast unverändert geblieben. Ich musste nur 3 Zeilen Code anpassen und es lief dann auf Anhieb.

Mal sehen, ob es jetzt weniger Reboots gibt. Sollte es zumindest nicht schlechter sein, werde ich es zügig in die Rolling und dann auch eine neue Master mergen.

**Comment by jomjol** [comment]
In der Version 4.0.0 wurden einige Speicherlecks beseitigt. Die Anzahl der Reboots ist deutlich geringer.
Schließe den Issue jetzt erstmal.
