### ISSUE TITLE
partition 0 invalid magic number Error

### ISSUE THREAD

**Issue by narf0815** [jomjol/AI-on-the-edge-device#340]
Hi,
i've uploaded the 3 files with the Flash Tool from Espressif but the program won't start.
i have tried with to different sd cards, but all i get is this loop:
```
20:40:16.142 -> rst:0x3 (SW_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
20:40:16.142 -> configsip: 0, SPIWP:0xee
20:40:16.142 -> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
20:40:16.142 -> mode:DIO, clock div:2
20:40:16.142 -> load:0x3fff0030,len:4
20:40:16.142 -> load:0x3fff0034,len:7248
20:40:16.142 -> ho 0 tail 12 room 4
20:40:16.142 -> load:0x40078000,len:13856
20:40:16.142 -> load:0x40080400,len:4052
20:40:16.142 -> entry 0x40080688
20:40:16.142 -> [0;32mI (60) boot: ESP-IDF 3.40100.200827 2nd stage bootloader[0m
20:40:16.142 -> [0;32mI (60) boot: compile time 07:32:06[0m
20:40:16.142 -> [0;32mI (60) boot: chip revision: 1[0m
20:40:16.142 -> [0;32mI (64) boot_comm: chip revision: 1, min. bootloader chip revision: 0[0m
20:40:16.142 -> [0;32mI (71) boot.esp32: SPI Speed      : 40MHz[0m
20:40:16.142 -> [0;32mI (76) boot.esp32: SPI Mode       : DIO[0m
20:40:16.142 -> [0;32mI (80) boot.esp32: SPI Flash Size : 4MB[0m
20:40:16.142 -> [0;32mI (85) boot: Enabling RNG early entropy source...[0m
20:40:16.142 -> [0;31mE (90) flash_parts: partition 0 invalid magic number 0xa0a[0m
20:40:16.142 -> [0;31mE (97) boot: Failed to verify partition table[0m
20:40:16.142 -> [0;31mE (102) boot: load partition table error![0m
20:40:16.142 -> ets Jun  8 2016 00:22:57
```
i have tried to flash the example CameraWebServer from the esp32 arduino examples and that worked fine.
so i don't think this is a hardware error.

**Comment by jomjol** [comment]
I'm not using the espressif tool, but I use the esptool to flash it (https://github.com/jomjol/AI-on-the-edge-device/wiki/Installation). Did you try this as well?

**Comment by narf0815** [comment]
no, as i can't install esptool with anaconda:
```
error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
  ERROR: Failed building wheel for reedsolo
```
i have downloaded (5,6gb) and installed Microsoft Visual C++ 2019 but the error persists.

**Comment by jomjol** [comment]
Seems something is wrong with your bin-files. How did you download them and how big are they? Here is a screenshot of mine (in a windows drive):
![grafik](https://user-images.githubusercontent.com/30766535/133198133-e5f6d901-d43b-4e60-aa32-7a24863f6177.png)

**Comment by narf0815** [comment]
right click on file, save link as ...
![Downloads](https://user-images.githubusercontent.com/9511238/133198681-17590506-aecc-4767-8bbb-1b9e695618f8.png)
now i downloaded the code as zip and extracted the 3 files and the flash went through!
sorry for the trouble!

**Comment by jomjol** [comment]
solved!
