### ISSUE TITLE
Hostname, Mac-Address, IP missing in MQTT

### ISSUE THREAD

**Issue by bjoernmayer** [jomjol/AI-on-the-edge-device#3408]
### The Problem

Hostname, Mac-Address, IP are missing from MQTT messages.

The Mac-Address could also be used as `identifier` in Home Assistant. See https://developers.home-assistant.io/docs/device_registry_index/#device-properties

### Version

15.7.0

### Logfile

```shell
No need to attach a log file, I guess?
```

**Comment by caco3** [comment]
The MAC address is provided as Home Assistant Discovery topic:
![grafik](https://github.com/user-attachments/assets/0b743244-5a43-48a5-92d2-9cad21d9e9de)

Also the IP/Hostname is accessible if you click on "Besuchen":
![grafik](https://github.com/user-attachments/assets/ca8fedd3-0b2a-483c-a025-446d0cabdfbf)

**Comment by Commifreak** [comment]
The MAC should also be displayed at System -> Info. The gateway and dns could also be there.
