### ISSUE TITLE
MQTT: change Connection Status Values to offline / online

### ISSUE THREAD

**Issue by pixeldoc2000** [jomjol/AI-on-the-edge-device#341]
I would like to propose to change the MQTT Connection Status this project send to a more standard (Home Assistant) Value:

Topic: `watermeter/connection`
"connection" -> "online"
"connection lost" -> "offline"

AFAIK most other MQTT Devices use these values and this is what Home Assistant expects. This would make it more inline with given "defaults" ;-)

**Comment by jomjol** [comment]
Technically easy, but this setting has been used since almost the beginning, therefore all other scipts etc. are based on "offline / online" and would not work anymore.
Therefore I tend, not to change this currently. Any other recommendations?

**Comment by jomjol** [comment]
Currently not followed
