### ISSUE TITLE
recognized two digits out of one box

### ISSUE THREAD

**Issue by ganslmeier** [jomjol/AI-on-the-edge-device#343]
Sometime i watch that two digits are recognized out of one box. Then i get a way to high values. 
Is it intended that a number greater than 9 will be recognized with a digit?

<img width="1139" alt="Bildschirmfoto 2021-09-17 um 7 26 03 AM" src="https://user-images.githubusercontent.com/1924710/133733851-ff080b40-27ab-48c2-a9a5-599c43f30093.png">
.

**Comment by jomjol** [comment]
No, that could be a bug. what version are you using and can you send me a logfile containing such an event?

**Comment by ganslmeier** [comment]
Sure. Happy to help.
Version: master - v8.3.0 - 2021-09-12
Log-file attached. e.g., line 1398

[log_2021-09-17.txt](https://github.com/jomjol/AI-on-the-edge-device/files/7184719/log_2021-09-17.txt)

**Comment by ganslmeier** [comment]
Hi jomjol, same issue with my second device.
Version: master - v8.3.0 - 2021-09-12

![Bildschirmfoto 2021-09-17 um 12 41 56 PM](https://user-images.githubusercontent.com/1924710/133770113-0059d2d3-757e-4120-95e7-101670cd1ebc.png)

**Comment by jomjol** [comment]
Is it always an "11" that is wrong?

**Comment by ganslmeier** [comment]
it seems so. until now it was always "11"

**Comment by s0170071** [comment]
maybe this is related: 

I have configured a reading called "analog", which only covers the pointer. 
![grafik](https://user-images.githubusercontent.com/33855380/133921145-05d66d1c-f205-442b-8697-756ccbf624f4.png)
How is it possible that the reading ever exceeds 9.9?
Post processing is deactivated for analog. In fact, it is 702000. Also, the web interface is almost inaccessible when analog processing is activated.

**Comment by jomjol** [comment]
There is something wrong with the internal decimal shift. Reason is internal refactoring of that part.

Correction will take some days due to lack of time.

Thanks for the hint.

**Comment by ganslmeier** [comment]
@jomjol thanks for your feedback and great to help make your project even more great. Very cool project - Tanks a lot! Will spend you some coffee.

@s0170071: what camera / housing do you use? The image looks very sharp and precise compared to my setup.

**Comment by s0170071** [comment]
Its an ESP32CAM module. What you could try is adjusting the focus. Remove the glue from the thread and twist the lens. Also, I did de-solder the LED and placed it a bit away from the lens.

**Comment by jomjol** [comment]
@ganslmeier thanks for the support. regarding the LED I'm working on a solution to controll some external LED (WS2812) to have more flexibility with the illumination.

**Comment by jomjol** [comment]
Found some missing modulus to 10, that could explain the double numbers. Has been fixed in the current rolling - please test it

**Comment by ganslmeier** [comment]
Thx. Will Test at the weekend When I am Back Home

**Comment by melvinisken** [comment]
I don't know if my issue is related, I face the problem that there is an additional digit attached to the end of the number. I have four analog meters and I also configured only those for, but I get "readings" for five analog values. And the last one seems to flicker so most values are not accepted.. Where does the last digit come from?
![2021-09-24 13_55_03-Posteingang - isken@cellumation com - Outlook](https://user-images.githubusercontent.com/10966010/134670862-cf00d9a2-4bf7-4983-929f-6706b5e26c34.png)

**Comment by jomjol** [comment]
> 
> 
> I don't know if my issue is related, I face the problem that there is an additional digit attached to the end of the number. I have four analog meters and I also configured only those for, but I get "readings" for five analog values. And the last one seems to flicker so most values are not accepted.. Where does the last digit come from?
> ![2021-09-24 13_55_03-Posteingang - isken@cellumation com - Outlook](https://user-images.githubusercontent.com/10966010/134670862-cf00d9a2-4bf7-4983-929f-6706b5e26c34.png)

Most propably you have the extended resolution enabled. The analog pointer is digitized with a subcomma e.g. 9.5 for the first number. This is used as an additional number for the last number.

**Comment by jomjol** [comment]
See newest release

**Comment by melvinisken** [comment]
Just for information: in my case it was indeed the extended resolution setting. Everything is working fine now.
