### ISSUE TITLE
Plausibility check for the date?

### ISSUE THREAD

**Issue by gitpower2017** [jomjol/AI-on-the-edge-device#3440]
### The Feature

Plausibility check for the date?

I now had the problem that a single entry was from 1970. This makes the diagram look very strange.
Is there a feature that checks whether the data set matches the previous one? (Timestamp)
There is a flag for the maximum delta water length.

![Datums_Error](https://github.com/user-attachments/assets/fe0bcd24-2c37-40a7-909e-0da9ed5fd303)

**Comment by gitpower2017** [comment]
I was already aware that this date is set after a cold start of Linux systems and that the NTP has not yet set a current date. It makes sense to mark this entry as ERROR if the previous date is more recent.
Perhaps a plausibility check will be added after all.

**Comment by caco3** [comment]
This has nothing to with Linux. It is n issue of any system without a RTC (Real time Clock) which would keep the clock running even if the device is switched off.
