### ISSUE TITLE
Problem with last digit

### ISSUE THREAD

**Issue by Proll86** [jomjol/AI-on-the-edge-device#3441]
### Issue

Hallo,
ich habe ein Problem mit der letzten Zahl. Diese steht kurz vor der 2 und wird leider als 2 erkannt. damit kommen fehlerhafte Ergebnisse.
Wie kann ich das verhindern?
Check Digit Increase Consistency habe ich bereits auf true
![Screenshot 2024-12-18 172620](https://github.com/user-attachments/assets/94f92cb2-069e-4b15-bbea-aae1efd39095)
![Screenshot 2024-12-18 175458](https://github.com/user-attachments/assets/0136ffb8-47c2-4832-b99f-1f5d7ce5c3b5)

**Comment by SybexX** [comment]
https://jomjol.github.io/AI-on-the-edge-device-docs/Watermeter-specific-analog---digital-transition/

**Comment by Proll86** [comment]
> https://jomjol.github.io/AI-on-the-edge-device-docs/Watermeter-specific-analog---digital-transition/

I will try. Thank you so far.
