### ISSUE TITLE
Werte werden nicht Aktualiesiert 

### ISSUE THREAD

**Issue by Sefina-DS** [jomjol/AI-on-the-edge-device#345]
Hi zusammen

Ich nutze 2 ESP´s
einen für den Gaszähler und einen für den Wasserzähler

Der Gaszähler Aktualiesiert keine Werte obwohl er sie sauber erkennt :
Value : 14529.71
Previous Value : 14529.71
Raw Value : 14530.71
Error : no error

Die "MaxRateValue" ist bei 10 eingestellt, bei 0,X bekomme ich einen Error das der wert zu hoch ist.

Bei der Wasseruhr ist es anders ....
Irgendwann wurde eine Stelle Falsch gelessen und seit dem ist der Wert um genau 1 zu hoch 
die Werte werden trotzdem sauber erkannt : 
Value : 156.0814
Previous Value : 156.0814
Raw Value : 155.08140
Error : no error

Die "AllowNegativeRates" ist auf true gestellt

wenn ich den PreValue ändere wird dieser nie übernommen.

Version nutze ich "master - v8.2.0 - 2021-08-24"

Vieleicht kann wer helfen ....

**Comment by jomjol** [comment]
Welche Version verwendest du: Rolling oder Master?
Momentan arbeite ich an einer Umstrukturierung des Zahlenhandlings in der Rolling.

1) der Sprung um die "1" zuviel bei der Wasseruhr kommt von "CheckDigitalConsistency", warum er sich aber per PreValue nicht zurücksetzen kann ist merkwürdig
2) Gaszähler: siehe meine erste Bemerkung - wenn du Rolling verwendest. Ansonsten ist es merkwürdig.

Vielleicht kannst du mal ein Logfile schicken, das könnte evt. etwas helfen.

**Comment by Sefina-DS** [comment]
Also ich nutze wie Oben geschrieben : master - v8.2.0 - 2021-08-24

Ich habe jetzt alle Überprüfungen deaktiviert und auch erlaubt das er zurückspringen kann, seit dem geht es ....
Auch wenn er Rückwärtssprünge mit drin hat.

Würde ich es Aktivieren ist das Probelm bestehen.

Wenn du mir sagst welche Logs du benötigst und wie ich diese Aktiviere  ....

MfG

**Comment by jomjol** [comment]
Versuche vielleicht zunächst mal die Rolling Version. Dort habe ich einige Bugs beseitigt, aber Achtung, die Settings sind auch leicht verschoben.
Die Logfiles kannst du über die config.ini - ganz unten - aktivieren. Du findest sie dann im Verzeichnis log/messages nach Tagen sortiert.

**Comment by jomjol** [comment]
Mehrere Maßnahmen in Firmware und html im aktuellen Release implementiert
