### ISSUE TITLE
Change Wifi Settings, no wifi.ini

### ISSUE THREAD

**Issue by jonnycastaway** [jomjol/AI-on-the-edge-device#346]
Hello @all,

i need to change my wifi settings.
On the FileServer i didn't found a wifi.ini.
So, is it possible to change wifi settings from the Webinterface and how?
I think it's not a real problem. I think i have tomatoes on my eyes.

**Comment by jwillich** [comment]
That's intended i think. Have a look at the Wiki > Installation > WLan. To protect the wifi password witch is stored as cleartext the wifi.ini file is hidden from the file server.
So i think you have to retrieve the SD card from the ESP and change the settings with your pc.

**Comment by jomjol** [comment]
Hi,
that's absolutely right. Due to the fact, that the wlan password is in cleartext, the wlan settings are not reachable through the web page or any other external wlan access.
