### ISSUE TITLE
Desktop browser never fully loads

### ISSUE THREAD

**Issue by TravisRoy** [jomjol/AI-on-the-edge-device#348]
On my phone, the interface seems to work fine. On my computer (x86 mac, happens with crome, firefox, and safari), the big box that usually shows the image and other information is just blank and it keeps loading but never finishes.

<img width="1034" alt="Screen Shot 2021-09-21 at 6 35 00 PM" src="https://user-images.githubusercontent.com/30446459/134256609-17ef722e-7de5-4a4a-93c3-757c68d87dd8.png">

**Comment by TravisRoy** [comment]
Just installed the latest rolling release of firmware.bin and index.zip. No change. Works on phone, not on laptop. It's so weird.

**Comment by TravisRoy** [comment]
Tried to re-install the master branch version on another ESP32-cam and a different SD card. Same results.

**Comment by jomjol** [comment]
I have sometimes the same problem. In my case I need to wait about 3-4 minutes after the start and than it works. Currently I have no glue, what is behind :-(.

**Comment by TravisRoy** [comment]
No matter how long I wait, it never loads, just sits there and spins.

**Comment by jomjol** [comment]
Then there is something wrong with your settings. Can you make a serial log after the startup for about 1-2 minutes and post it here?

**Comment by Jamoth** [comment]
> I have sometimes the same problem. In my case I need to wait about 3-4 minutes after the start and than it works. Currently I have no glue, what is behind :-(

I played a bit around with RTOS functionality to split the web-server and the AI part on two cores. In fact, the web was blazing fast, but it became very unstable and esp restarted pretty often when i used the UI. I havent had too much time lately to digg into that, but one problem to be solved for that is to make the resources shared between web and AI thread save with some token logic. I think I observed, that when the picture processing takes place and at the same time the image is beeing loaded there are null pointers. One other potential problem I came across was that there might have been a bug within the tf-libs itself with a certain library version that triggered resets, but thats not a performance issue.
Aside from that, your project is amazing.

**Comment by jomjol** [comment]
@Jamoth : thanks for the info. I observe the same topics. The tf-libs can be brougth to fail in even very simple code, if you do some other stuff parallel. In fact in some cases if you access the web server, the internal memory structure of the tf-lib gets corrupted. That's one of the reasons, why I have implemented a rather stable reboot sequence with the "prevalue".
Sometimes it seems also HW related. I have some devices, running for 200-300 runs without any disturbance and other rebooting every 10-15 runs.
I'm open to any suggestions, but I have currently no other ideas.

**Comment by melvinisken** [comment]
I have a similar effect, I'm still within the setup routine, I could finish step 1 (reference image) in Firefox (Win 10, latest). If I go to the next step (alignment references), no image is shown, only the input forms for setting new values. Sometimes two small images are shown below "original image" and "reference image" (small image with 'CRI' letters). Mostly nothing. The same happens in chrome. On my iPhone, it seems to work, though.

**Comment by melvinisken** [comment]
I just checked my browser and there are some errors. I marked the log messages from the initial click on next (showing the reference image page, no error, just warnings) (1) and after clicking on next again (alignment references page).
![2021-09-24 11_29_47_ff1](https://user-images.githubusercontent.com/10966010/134657183-d72d7463-e220-4992-8bae-44224ffba9ab.png)
If I directly try to load such an image, I get:
![2021-09-24 11_30_40_ff2](https://user-images.githubusercontent.com/10966010/134657235-3e5ca79a-ead1-4831-86b3-b0ce2625f52c.png)

But it seems to change between runs, sometimes I get less errors, so it might be a performance issue as you already discussed.

**Comment by Jamoth** [comment]
@melvinisken: Maybe focus on the last line, where you have an error within your config file. Maybe a typo? What's the content?
@jomjol I think, the warnings can be solved within the declaration of the .js sources in the code with <script type="text/javascript"> instead of text/plain

**Comment by melvinisken** [comment]
I will post my config file once I have physical access to my ESP. But it's a clean install, I never touched the files manually, I only started this setup-procedure. I did some furhter testing and this error never occured again. And the number of internal server errors also changes, so I don't think one can derive some clues out of it. I think it looks like load / performance issues that sometimes the webserver does not react fast enough and sometimes it does.
Update: finally, I was able to get through the setup using Chrome on Win10. Since this didn't work an hour ago, I think this is also just a matter of coincidence. :-)

**Comment by jomjol** [comment]
@melvinisken I'm almost sure, it is not a problem of your config.ini. For some reasons the timing and the resources in the ESP are not working as expected. For example loading the alignment page triggers several processes on the ESP.
1) load config.ini
2) copy the reference images (original and enhanced) to the tmp folder
3) send the image, config.ini, ... to the client

if e.g. 3) is faster than 2), that might cause one of the problems. I think about a solution.

**Comment by jomjol** [comment]
Several measure implemented in the recent release. Closing it for the moment.

**Comment by to-scho** [comment]
This issue is still present in 9.1.1. Apple Desktops did not schow a complete setup page at all, windows based ones fails on the last setup step when trying to reboot into normal boot. After that the confit.ini was deleted from sad card and must be restored before any new setup attempt. Thanks to the tip here I tried using my iPad which was no fun but succeeded until end. Let’s see whether normal mode of operation is stable now.

**Comment by jomjol** [comment]
@to-scho I cannot test on apple safari (no such device). Never the less, html would need some support.

Supportes are welcome :-)
