### ISSUE TITLE
feature request: show hostname in title + each site (webinterface)

### ISSUE THREAD

**Issue by Sandworm-of-Dune** [jomjol/AI-on-the-edge-device#349]
Hello jomjol,
I have three ESPs (Water / gas / power)
It is sometimes difficult to know on which interface I am, if I all of them are open at the same time.
It would be nice if on each site (e.g. header) and also the website-title the hostname or an individual choseable name is shown.

Attached a picture of my situation:
Also a suggestion where the hostname could be located.

![grafik](https://user-images.githubusercontent.com/91150538/134310226-47f7184d-e131-4c4d-883c-d1c680039461.png)
Thanks a lot 
Regards Tobias

**Comment by jomjol** [comment]
Good idea, will keep it open for one of the next updates of the html-files. Currently I'm working on a different topic.

**Comment by Sandworm-of-Dune** [comment]
ok. Thanks a lot.
Regards Tobias

**Comment by jomjol** [comment]
Just have a lool at the current rolling:

![grafik](https://user-images.githubusercontent.com/30766535/134415268-b70b79bb-036f-49fd-be3e-80c32cbd80a5.png)

**Comment by Backfire-FF** [comment]
Hi Tobias,

as a quick fix, add this to the index.html (HTML folder on the SD-Card)

`<script type="text/javascript">
    var hostname = location.host;
    document.title = "jomjol - " + hostname;
</script>`

Cheers
Danny
