### ISSUE TITLE
Module Not starting after flash... 

### ISSUE THREAD

**Issue by AbDhops** [jomjol/AI-on-the-edge-device#350]
Hello,
I am installing for the first time. Here are my detailed steps : 

**Hardware:**

1. ESP32-CAM-MB for powering the baord
2. ESP32-CAM module

**Software**
1. Downloaded 8.4.0 release
2. Download latest release of flash_download_tool i.e. 3.9.0

**Steps:**

1. Make a copy of the [SD-Card subdirectory](https://github.com/jomjol/AI-on-the-edge-device/tree/master/sd-card) to the root of the sd-card.
2. Insert SD Card into EST CAM32 module
3. Connect ESP32 CAM module using to PC.
2. Ensure it is connected on one of the COM port  (in my case it is COM5)
3. First erase and then Flash the software

![image](https://user-images.githubusercontent.com/46280644/134811766-111da6f2-6ef7-4bd9-8322-299539754946.png)

Flash is successfull (see below log): 
```
*************************** START ****************************

START TIME: 202109261601

CONNECT BAUD: 115200
com port closed

set state: ESP_DL_SYNC
serial port opened
-----------
baud:115200
root baud:115200
-------------
===============BAUD : 115200===============CALL DEVICE SYNC
connecting...
chip sync ok
mac l: 0xbd66b308
mac h: 0x1d7c9e
crc_cal: 29
crc_read: 29
crc_test: 0
ESP32 MAC CRC OK
get mac res: 1
get flash id : 0x001640d8

manufacturer_id: 0xd8

device_id: 0x4016


Wrote 25264 bytes (15169 compressed) at 0x00001000 in 0.2 seconds (effective 1031.5 kbit/s)...

Hash of data verified.
Wrote 3072 bytes (128 compressed) at 0x00008000 in 0.0 seconds (effective 6142.2 kbit/s)...

Hash of data verified.
Wrote 1661824 bytes (991064 compressed) at 0x00010000 in 13.1 seconds (effective 1013.8 kbit/s)...

Hash of data verified.
Leaving...

com closed
Use time: 17 s

Download result: PASS

*************************** END ****************************
```

At this stage, I performed the reset, but the CAM32 module is not coming up. ESP LED is always off.  Neither it broadcast the hotspot nor it connects to configured WiFi. Also reset button or reconnecting to power does not have any influence.

**Comment by mikewolf** [comment]
here i have the same problem , without sdcard red led flashes without pause, but when a sd card is inserted the red led flash not .... , with 3 sd cards

**Comment by jomjol** [comment]
That is strange. I just formated my sd card and erased the esp32. The I did the installation freshly exactly according to the normal procedure, but not with the espressif tool, but with python directly (https://github.com/jomjol/AI-on-the-edge-device/wiki/Installation). Everything is working as expected.

So two possible problems:
1) espressif tool is not working with this firmware - unlikely, but several users have reported problems with that.
2) the "new" firmware 8.4.0 is not working with the configuration of the 8.3.0. There are some changes (e.g. extended resolution), but this should theoretically  not be a problem. But I cannot test it, as I don't have a original 8.3.0 configuration anymore.

To exclude 2), can you monitor the serial interface during startup and post the output. Then I can see, where the software crashes.

**Comment by AbDhops** [comment]
So, after lot of trial and erros, I realized that somehow, Wifi.inf file was set to read only. Due to which it was holding any settings whatever I was doing.
Fixing it, I could store my Wifi credientrails, and BAAAM.. It started working. 
However, since you mentioned "Extended Resolution", I am still seeing problem in OCR. Currently ESP is not recognizing values from below image... 

![image](https://user-images.githubusercontent.com/46280644/134822211-6fed01b6-c89f-43a0-9be4-c2df2d77a9ba.png)

**Comment by jomjol** [comment]
You need to adjust the camera. It is obviously not shart and therefore you have a low contrast. Also you need to remove the reflections on the analog meters.
