### ISSUE TITLE
Falsche Erkennung bei Zahlwechsel an der 1-Stelle

### ISSUE THREAD

**Issue by RichardSauer** [jomjol/AI-on-the-edge-device#351]
Immer wenn der Zählerstand von xx0 auf xx1 auf xx2 usw. springt. Läuft die Erkennung falsch und die Nachkommastellen springen auf .9999 und der Zählerstand muss jedesmal korrigiert werden. Der RAW Value wird allerdings zu 99% richtig angezeigt. Wo liegt das Problem?
![image](https://user-images.githubusercontent.com/42067245/134821139-ff652d6f-0c2e-4a5f-b1df-fc0411293d32.png)

![image](https://user-images.githubusercontent.com/42067245/134821176-00bb9af5-8c66-4765-92db-0e7506723322.png)

**Comment by jomjol** [comment]
Welche Version verwendet du und hast du CheckDigitalConsisency mal abgeschaltet?

**Comment by RichardSauer** [comment]
Verwende die Version v8.3.0 hatte aber auch gleiche Problem unter v7. Und ich habe an den Einstellungen nichts geändert.
![F08390CA-86F8-498B-BCAA-B9E656B6A16A](https://user-images.githubusercontent.com/42067245/134821818-232f6085-1975-4947-9ac7-2fc512e35a50.jpeg)

**Comment by jomjol** [comment]
Kannst du die Logfiles einschalten und mir mal einen Auszug schicken, wo genau der Fehler und 1-2 Runs vorher und nachher zu lesen sind.

**Comment by RichardSauer** [comment]
Hier bitte die Logs https://pastebin.com/KZKH69jF

**Comment by jomjol** [comment]
Du solltest `CheckDigitIncreaseConsistency` einschalten.

Vermutlich passiert folgendes: deine digitale Anzeige wechselt auf die nächste Ziffer, weil diese durch die Bilderkennung schon erkannt wird, bevor die Nachkommastelle über die 0.9999 hinweg ist. Dieser Effekt wird durch den Schalten `CheckDigitIncreaseConsistency` vermieden. Er aktzeptiert die neue digitale Stelle erst, wenn die Nachkommastelle auch den Nulldurchgang hatte.
