### ISSUE TITLE
Two meters in VGA windows

### ISSUE THREAD

**Issue by vlad-bravo** [jomjol/AI-on-the-edge-device#352]
Add initialization step:
1. Choose stay with VGA frame
2. or switch to UXGA frame and define 1 or more VGA windows

Process VGA frame or VGA window as earlier

**Comment by jomjol** [comment]
I don't get background of you idea. The image size is limited to VGA to keep the memory size under controll. 
1) If I change to UXGA I need to process 1600x1200, even if I use later on only VGA.
2) The input of the CNN is anyway downscaled to 32x32 or 32x20, so image resolution is not a topic.

**Comment by vlad-bravo** [comment]
Ok, in other words
2. Define on VGA frame future windows
3. Init OV2640 to UXGA frame and simultaneously VGA window - sensor will provide VGA picture to ESP

In my bath there are two meters close to each other
I can place ESP32-CAM to see both meters
UXGA frame and VGA window will be digital zoom for each meter

**Comment by jomjol** [comment]
Okay, got your idea. Seems like VGA resolution is not good enough for both meters. 
This implementation seems to be rather specific and I don't have resources to follow it. But I offer to merge a solution that you provide. Other option would be to use two ESP32, as they are really cheap.
