### ISSUE TITLE
Extend Support : Possibility to connect ReedContact to same ESP

### ISSUE THREAD

**Issue by AbDhops** [jomjol/AI-on-the-edge-device#353]
Hi,
I assume many are having possibility to connect Reed contacts to the meters. Is it possible (currently or can be expanded) to connect those Reed Sensors to same ESP ?
I guess we just need to setup the initial value, resolution of each pulse, and then software can keep counting. By this way it is possible to connect 2 meters, one with CAM and another one with Reed contact... 

Do you think it makes sense ?

**Comment by jomjol** [comment]
Hi,
technically possible, but this device is focused on the image processing. I would recommend to implement this idea in a separate software. Otherwise this would get too crouded. Anyway, I'm the only developer in this software and don't have ressources for this.

**Comment by AbDhops** [comment]
thanks @jomjol,
I can totally understand. Currently I am going through the code, but could not identify the correct location to add software. e.g. which Pins are currently free, where to poll the PIN and add counter, and then to publish this on MQTT and on <IP>/wasserzahler page. Can you guide on that...

**Comment by jomjol** [comment]
I don't recommend to do so. The neural network part is time controlled code, that runs one after the other procedure. There are no interrupts etc. implemented and the MQTT event is sent, when the picture is analysed.
What you need is a event driven controll, whenever a reed contact closes. This is a totally different process flow, that would need major adaptions. Additionally during the image processing the ESP32 is pretty loaded, so maybe he even would not react in time.
