### ISSUE TITLE
esptool 3.9.0 not recognizing chip

### ISSUE THREAD

**Issue by aaamoeder** [jomjol/AI-on-the-edge-device#354]
Tried to follow the tutorial today but for the life of me I cannot get the espdownloadtool (3.9.0) to recognize the esp32s chip
I have everything connected as suggested (I think) but when I plug in the uart stick and the power to the esp nothing gets detected.
all that happens when I press start is it tried to connect over baud rate 115200 no matter which baud rate I select and it keeps running without any result.
![image](https://user-images.githubusercontent.com/20947118/135073110-2f86b5db-8db5-4ef0-b614-42319383a652.png)
![IMG_20210928_124836](https://user-images.githubusercontent.com/20947118/135073620-f286295c-6d1d-44ab-b01b-067aad3976a3.jpg)
![IMG_20210928_124825](https://user-images.githubusercontent.com/20947118/135073624-e6155b77-2e78-46d8-85f1-831df8f77311.jpg)
![IMG_20210928_124819](https://user-images.githubusercontent.com/20947118/135073635-33483c65-e410-4274-9599-33817e598bf8.jpg)
![IMG_20210928_124800](https://user-images.githubusercontent.com/20947118/135073646-cd636db0-21ab-4701-b657-1d88791cd6bc.jpg)

because I lack a button I just shorted the third pin on the bottom right with the gnd to get it to bootloader mode (white cable)

I've searched all over the web for hours now but found multiple tutorials that all seem to describe different hardware or methods.
I'm affraid I might mess something up so asking here if anyone could help me out.
Thanks !

**Comment by friedpa** [comment]
How are you providing power? Normally for the programming you should only use your programming device and not an external power supply, just to make sure that both devices are having the same ground and the same positiv Voltage! Use 5V as 3,3V is sometimes unreliable! Hope that helps.
Secondly look at the baud rate and the COM Board, I am almost sure that COM1 is wrong. Plug in the Programming device with the Windows Device Manager open and look what COM board get added.

**Comment by AbDhops** [comment]
Apart from what @friedpa mentioned, also try to put the board in flash mode, and then apply power. For me, it did the trick.

**Comment by aaamoeder** [comment]
> How are you providing power? Normally for the programming you should only use your programming device and not an external power supply, just to make sure that both devices are having the same ground and the same positiv Voltage! Use 5V as 3,3V is sometimes unreliable! Hope that helps. Secondly look at the baud rate and the COM Board, I am almost sure that COM1 is wrong. Plug in the Programming device with the Windows Device Manager open and look what COM board get added.

I've wired it up according to the info on this page
https://github.com/jomjol/AI-on-the-edge-device/wiki/Installation
picture seems to imply connecting it to a usb power supply

Could you suggest a correct way to wire it ?

**Comment by aaamoeder** [comment]
nevermind...
I'm an idiot ... :p

**Comment by friedpa** [comment]
Can you let us know what was wrong so that others can also benefit?

**Comment by aaamoeder** [comment]
> Can you let us know what was wrong so that others can also benefit?

I bought this
![image](https://user-images.githubusercontent.com/20947118/135265073-6c7508d9-1afb-475a-96bb-7e59311e97b0.png)
So I didnt need the uart stick at all
Appears that when I first tried the usb way, I just used 2 cables that have no data capability.
Tried another one that I had laying around and it got detected straight away

**Comment by atze09** [comment]
> > Can you let us know what was wrong so that others can also benefit?
> 
> I bought this ![image](https://user-images.githubusercontent.com/20947118/135265073-6c7508d9-1afb-475a-96bb-7e59311e97b0.png) So I didnt need the uart stick at all Appears that when I first tried the usb way, I just used 2 cables that have no data capability. Tried another one that I had laying around and it got detected straight away

I have bought the same but can not flash it, how did you get it working? Can you please explain?

**Comment by aaamoeder** [comment]
I simply installed the correct drivers and plugged in the esp via usb to micro usb and it worked !
