### ISSUE TITLE
Komma Fehler

### ISSUE THREAD

**Issue by Toki99** [jomjol/AI-on-the-edge-device#358]
![image](https://user-images.githubusercontent.com/49706480/135443936-e3ab12f2-7c75-4db6-a7ca-48aa8a020438.png)
Hallo, irgendwie bekomme ich das nicht mit dem Komma an der richtigen Stelle hin.

**Comment by friedpa** [comment]
Das Komma lässt sich in der Config.ini einstellen. In dem gezeigten Bild sollte also der Wert von DecimalShift 0 sein. Hier ein Beispiel anhand meines Wasserzählers:
![grafik](https://user-images.githubusercontent.com/42890695/135447312-ddc342fa-de86-4f6d-b003-e0fb8892a048.png)
und der Auszug aus der Config.ini:
![grafik](https://user-images.githubusercontent.com/42890695/135447401-38038791-0a43-4fba-87bd-74fdad6e5b40.png)

**Comment by friedpa** [comment]
Noch ein Punkt: Die RAW Value stimmt ja bei Dir!
@jomjol: ist das nicht dass gleiche Problem wie unlängst von jemanden gepostet, der auch diese Null dazu bekommen hat?

**Comment by Toki99** [comment]
Danken für deine Rückmeldung. Bei dezimal Shift habe ich auch mal getestet ob das Besserung bringt.
Gab es eine Lösung bei dem Problem das jemand gepostet hatte?

**Comment by friedpa** [comment]
Warten wir auf die Worte des Meisters :o)

**Comment by jomjol** [comment]
Eigentlich sollte dieser Fehler mit einem zusätzlichen Ziffer beseitigt sein - lag daran, dass ich an einigen Stellen vergessen hatte das Modul 10 zu machen. Vielleicht gibt es noch eine Zeile dazu. Um den Fehler etwas einzugrenzen:

1) Welche Version genau verwendest du?
2) Kannst du mal deine Config.ini posten und einen Auszug von ein paar Runden aus dem Logfile.

**Comment by Toki99** [comment]
Habe nun die aktuelle Version - gleicher Fehler

**Comment by jomjol** [comment]
Dann schick mir mal die oben genannten infos (config.ini & logfile)

**Comment by Toki99** [comment]
[log.zip](https://github.com/jomjol/AI-on-the-edge-device/files/7264397/log.zip)

**Comment by Toki99** [comment]
Irgendwie habe ich die zusätzliche Null weg bekommen. Jetzt habe ich nur das Problem beim Wechsel der Zahl. Kann man das Einstellen? Sollte das über den Last Value verhindert werden
![zähler](https://user-images.githubusercontent.com/49706480/135723004-7e93001e-5c3d-49a8-affc-95dea8d72f4b.PNG)
?

**Comment by jomjol** [comment]
Ja genau. Wenn er ein "N" erkennt, dann ersetzt er es durch die letzte erkannte Ziffer. Du kannst 
1) warten, bis deine Ziffern mal richtig erkannt wurden
2) den PreValue manuell setzen
![grafik](https://user-images.githubusercontent.com/30766535/135726525-ac12927a-a0a3-4780-849a-99ea15d9e300.png)

**Comment by Toki99** [comment]
Leider komme ich immer noch nicht richtig klar trotz euren Tipps. Anbei meine Einstellungen. Warum wird den 357 statt 356 interpretiert obwohl es im RAW richtig erkannt wird?
![z1](https://user-images.githubusercontent.com/49706480/137253516-f1d48998-52e0-4bca-b636-fb1f952bfdae.PNG)
![z2](https://user-images.githubusercontent.com/49706480/137253520-61ceda1b-7858-4550-83ef-b05f20c42092.PNG)
@jomjol  @friedpa

**Comment by Krusty1977** [comment]
Hallo zusammen, 

was muss ich machen, dass der ermittelte wert von 123.456 in Home Assistant als 123,456 Kubikmeter und nicht als 123456 Kubikmeter erkannt wird?
