### ISSUE TITLE
Analog needles that increase counter clockwise

### ISSUE THREAD

**Issue by bakerkj** [jomjol/AI-on-the-edge-device#361]
What a great project!!

I have a gas meter with two needles that increase as expected clockwise while it has two analog needles that increase counter clockwise. Is there a way to configure the model to detect these analog needles correctly?

![gas_meter](https://user-images.githubusercontent.com/5491232/135958130-23e93d3f-5785-4c9e-b5d4-9126354a00ff.jpg)

Note the 1,000,000 and 10,000 cu ft indicators increase counter clockwise.

Thanks in advance for your help!

-- Ken

(I suspect that I will also need to reduce the intensity of the reflection over the top of the 100,000 and 10,000 indicators)

**Comment by jomjol** [comment]
Well, currently there is  no option to configure this. The reading is purely comming from the neural network and this is teached to clockwise running counters. If all your counters would run counterclockwise, I could train a special version for you. But the algo cannot use two neural networks for analog counters within one number.
Sorry for this!

**Comment by bakerkj** [comment]
@jomjol for now could I create this as 4 different numbers and assemble them myself?

@jomjol would it be reasonable if I filed this as a future feature request?

**Comment by jomjol** [comment]
1) 4 numbers do work in principle
2) but you anyhow would need a specially trained tflite-file

**Comment by friedpa** [comment]
I checked your approach, which is in my opinion correct, so it would be only a "tick field" per ROI to define if that ROI works clockwise or counter-clockwise. No change in the tflite necessary, only a piece of code ... :o)

**Comment by bakerkj** [comment]
@jomjol I'll start gathering images.

@jomjol given the complexity of having two analog models in the current code base. Would it be possible to have one model able to recognize both clockwise and counter-clockwise images?

**Comment by jomjol** [comment]
No further activities or images received.
