### ISSUE TITLE
Is it possible to recoginze other meter?

### ISSUE THREAD

**Issue by ThinkontrolSY** [jomjol/AI-on-the-edge-device#364]
Hi, Thanks for create such a wanderful project 👍🏽

I just wonder whether it is possible to recognize other meters like voltage meter

![zhizhenshijiaoliudianyabiaoBE-80-AC450V](https://user-images.githubusercontent.com/11331554/136487536-4a31a048-d169-4a89-bf63-c70888022d9e.jpeg)

Thanks😀

**Comment by jomjol** [comment]
Hi,
the technique and background is in principle capable of this. It needs for sure a dedicated set of training images and some adaptions in the firmware, as it needs to handle different output.

**Comment by jomjol** [comment]
not activities - closing for the time beeing.
