### ISSUE TITLE
Erfahrungen mit Wasseruhr „Metrona Funk-Wasserzähler Q34“

### ISSUE THREAD

**Issue by Mikei386** [jomjol/AI-on-the-edge-device#365]
Die ist kein Problem der Software sondern ein Bericht über meine Erfahrungen mit der bei mir verbauten Wasseruhr. Vielleicht hilft es ja jemandem.
Es kann gerne direkt geschlossen, gelöscht oder an einen anderen Ort verschoben werden….

Zunächst nochmals vielen Dank an den Programmierer, der mir zuvor extrem schnell helfen konnte.

Dieses PDF zeigt die bei mir verbaute Uhr:
[https://www.brunata-metrona.de/site_data/user_upload/downloads/allgemein/m/BRUNATA_Wasserzaehler_Aufputzwasserzaehler-Typ7_Technisches_Datenblatt.pdf](url)

Bei uns im Haus ist eine recht neue Wasseruhr von Metrona verbaut. Diese ist in der Lage die Zählerständer per Funk (868 Mhz) oder per Infrarot auszugeben. Beides leider nur durch die Firma möglich.

An der oberen Seite des Zählers befindet sich ein Infrarot-Sensor sowie eine Infrarot-LED.

Irgendetwas an dieser Art von Zähler sorgt dafür, dass der ESP32 innerhalb von wenigen Minuten neustartet. Manchmal liegen sogar nur Sekunden zwischen den Neustarts.

Lege ich den ESP ca. 30 cm neben den Zähler läuft er Problemlos durch.
Das zweite Problem besteht darin, dass die Kamera „gestört“ wird. Bilder werden nur zur Hälfte aufgenommen. Die andere Hälfte bleibt immer Grau.
Sobald ich die Kamera in eine andere Richtung zeigen lasse, sind die Bilder in Ordnung.
Auch das abkleben der Infrarot-LED hat daran nichts geändert.

Ich habe das Ganze mit 3 verschiedenen ESP32 Cams sowie verschiedenen Netzteilen getestet. Alle verhalten sich gleich.
In den 5 Minuten in denen es zufälligerweise mal lief, wurden auch nur die Zahlen mit rotem Hintergrund perfekt erkannt. Die Zahlen auf weißem leider nicht. 

Mehr konnte ich nicht testeten da der ESP vor dieser Uhr nur Probleme macht.

Vielleicht hilft dies jemandem der auch solch eine Uhr hat und sich wunder das die ESPs nicht so wirklich möchten.

**Comment by schrej-zz** [comment]
Hallo @Mikei386 
bist du dir sicher, dass das Material, mit dem du abklebst auch keine IR durchlässt?
Sichtbares Licht <-> IR

**Comment by beejayf** [comment]
Hast Du versucht die Wasseruhr abzuschirmen - ist möglicherweise einfacher, als den ESP abzuschirmen und einen externe Antenne anzubauen. Einfach zum Testen mit Alufolie unhüllen und nur das Sichtfenster frei lassen.

**Comment by kongo09** [comment]
Danke für den Erfahrungsbericht! Ich versuche diese Uhr per Funk auszulesen. Leider klappt das ebenfalls nicht.

**Comment by jomjol** [comment]
Ich werde Issue jetzt trotzdem mal schließen, um den Überblick zu behalten.
