### ISSUE TITLE
How clear must the image be before it works ???

### ISSUE THREAD

**Issue by tjay78** [jomjol/AI-on-the-edge-device#372]
Is this not good enough ???
![image](https://user-images.githubusercontent.com/64300864/138661874-449e2a01-4543-4f88-ac52-f42d021235bf.png)

Thomas

**Comment by jomjol** [comment]
I'm using Anaconda python 38 TF 2.4
Do not use tf 2.6, that will not work at the moment

**Comment by jomjol** [comment]
closing until further notice (please reopen in case new information available)
