### ISSUE TITLE
not loading after initial setup

### ISSUE THREAD

**Issue by narf0815** [jomjol/AI-on-the-edge-device#376]
Hello!
i was finally able to remove the glue from the third camera (first and second got destroyed in the attempt...) and i was able to run the initial setup (setting up reference image, defining digital and analog roi) and after the first reboot i saw the webserver but without any content and i wasn't able to navigate on the page. cut the power and bootet again but the webserver is kind of dead... after some minutes i can't even load the page... 

the esp32 worked fine during the initial setup (which was running for quite a while until i got a picture that was "ok").

what can i do?

**Comment by narf0815** [comment]
is there anything i can do?

**Comment by jomjol** [comment]
You can collect example images and send them to me for the next training. Turn on the logging, and select 2-3 images for each number type (black and white), all together 30-60 images (format: jpeg, original ROI size). Put them in a zip file and post them here.
Until then I close this issue
