### ISSUE TITLE
No Reconnect to wifi after some time

### ISSUE THREAD

**Issue by mad2xlc** [jomjol/AI-on-the-edge-device#379]
After some good readings and mqtt messages the log file announces a reboot and no wifi connection is established anymore.
If i do i a power cycle everything is fine for next 3-6 readings.

**Comment by mad2xlc** [comment]
What i already did, and what i did today.
Mounted an external antenna to the ESP. Also tried an yagi antenna but i'm not sure if this made the problem even worse.
Tried different optimizations on the wifi connection. location, direction power etc.
Installed an additional AP and wifi bridge aka extender.
Two different esp cam boards.
Started from scratch with new firmware and new content on the sd card.

With a mobile phone i got around 50Mbps at the same spot.
With the wifi bridge i have a uplink quality of 80% and 80% to the esp.

Wifi connection drops after 15 to 30 seconds.

`Antwort von 10.107.0.115: Bytes=32 Zeit=75ms TTL=254
Antwort von 10.107.0.115: Bytes=32 Zeit=70ms TTL=254
Zeitüberschreitung der Anforderung.
Antwort von 10.1.0.1: Zielhost nicht erreichbar.
Antwort von 10.107.0.115: Bytes=32 Zeit=10ms TTL=254
Antwort von 10.107.0.115: Bytes=32 Zeit=60ms TTL=254
Antwort von 10.107.0.115: Bytes=32 Zeit=74ms TTL=254
Antwort von 10.107.0.115: Bytes=32 Zeit=9ms TTL=254
Antwort von 10.107.0.115: Bytes=32 Zeit=98ms TTL=254
Antwort von 10.107.0.115: Bytes=32 Zeit=108ms TTL=254
Zeitüberschreitung der Anforderung.
Antwort von 10.107.0.115: Bytes=32 Zeit=2472ms TTL=254
Antwort von 10.107.0.115: Bytes=32 Zeit=4ms TTL=254
Antwort von 10.107.0.115: Bytes=32 Zeit=18ms TTL=254
Antwort von 10.107.0.115: Bytes=32 Zeit=24ms TTL=254
Antwort von 10.107.0.115: Bytes=32 Zeit=33ms TTL=254
Antwort von 10.107.0.115: Bytes=32 Zeit=42ms TTL=254
Antwort von 10.107.0.115: Bytes=32 Zeit=48ms TTL=254
Zeitüberschreitung der Anforderung.
Antwort von 10.107.0.115: Bytes=32 Zeit=2288ms TTL=254
Antwort von 10.107.0.115: Bytes=32 Zeit=6ms TTL=254
Antwort von 10.107.0.115: Bytes=32 Zeit=6ms TTL=254
Antwort von 10.107.0.115: Bytes=32 Zeit=118ms TTL=254
Antwort von 10.107.0.115: Bytes=32 Zeit=4ms TTL=254
Antwort von 10.107.0.115: Bytes=32 Zeit=36ms TTL=254
Antwort von 10.107.0.115: Bytes=32 Zeit=31ms TTL=254
Antwort von 10.107.0.115: Bytes=32 Zeit=35ms TTL=254
Antwort von 10.107.0.115: Bytes=32 Zeit=31ms TTL=254
Antwort von 10.1.0.1: Zielhost nicht erreichbar.
Antwort von 10.1.0.1: Zielhost nicht erreichbar.
Antwort von 10.107.0.115: Bytes=32 Zeit=1135ms TTL=254
Antwort von 10.107.0.115: Bytes=32 Zeit=3ms TTL=254
Antwort von 10.107.0.115: Bytes=32 Zeit=30ms TTL=254
Antwort von 10.107.0.115: Bytes=32 Zeit=37ms TTL=254
Antwort von 10.107.0.115: Bytes=32 Zeit=45ms TTL=254
Antwort von 10.107.0.115: Bytes=32 Zeit=4ms TTL=254
Antwort von 10.107.0.115: Bytes=32 Zeit=50ms TTL=254
Antwort von 10.107.0.115: Bytes=32 Zeit=52ms TTL=254
Antwort von 10.107.0.115: Bytes=32 Zeit=36ms TTL=254
Antwort von 10.1.0.1: Zielhost nicht erreichbar.
Antwort von 10.1.0.1: Zielhost nicht erreichbar.
Antwort von 10.107.0.115: Bytes=32 Zeit=1012ms TTL=254
Antwort von 10.107.0.115: Bytes=32 Zeit=3ms TTL=254
Antwort von 10.107.0.115: Bytes=32 Zeit=67ms TTL=254
Antwort von 10.107.0.115: Bytes=32 Zeit=66ms TTL=254
Antwort von 10.107.0.115: Bytes=32 Zeit=68ms TTL=254
Antwort von 10.107.0.115: Bytes=32 Zeit=65ms TTL=254
Antwort von 10.107.0.115: Bytes=32 Zeit=70ms TTL=254
Antwort von 10.107.0.115: Bytes=32 Zeit=73ms TTL=254
Antwort von 10.107.0.115: Bytes=32 Zeit=78ms TTL=254
Antwort von 10.107.0.115: Bytes=32 Zeit=93ms TTL=254
Antwort von 10.107.0.115: Bytes=32 Zeit=81ms TTL=254
Antwort von 10.107.0.115: Bytes=32 Zeit=84ms TTL=254
Antwort von 10.107.0.115: Bytes=32 Zeit=89ms TTL=254
Antwort von 10.107.0.115: Bytes=32 Zeit=93ms TTL=254
Antwort von 10.107.0.115: Bytes=32 Zeit=98ms TTL=254
Antwort von 10.107.0.115: Bytes=32 Zeit=139ms TTL=254
Antwort von 10.107.0.115: Bytes=32 Zeit=146ms TTL=254
Antwort von 10.107.0.115: Bytes=32 Zeit=16ms TTL=254
Antwort von 10.107.0.115: Bytes=32 Zeit=24ms TTL=254
Antwort von 10.107.0.115: Bytes=32 Zeit=38ms TTL=254
Antwort von 10.107.0.115: Bytes=32 Zeit=43ms TTL=254
Antwort von 10.107.0.115: Bytes=32 Zeit=45ms TTL=254
Antwort von 10.107.0.115: Bytes=32 Zeit=58ms TTL=254
Zeitüberschreitung der Anforderung.
Zeitüberschreitung der Anforderung.
Antwort von 10.107.0.115: Bytes=32 Zeit=92ms TTL=254
Antwort von 10.107.0.115: Bytes=32 Zeit=97ms TTL=254
Antwort von 10.107.0.115: Bytes=32 Zeit=109ms TTL=254
Antwort von 10.107.0.115: Bytes=32 Zeit=17ms TTL=254
Antwort von 10.107.0.115: Bytes=32 Zeit=24ms TTL=254
Antwort von 10.107.0.115: Bytes=32 Zeit=35ms TTL=254
Antwort von 10.107.0.115: Bytes=32 Zeit=46ms TTL=254
Antwort von 10.107.0.115: Bytes=32 Zeit=43ms TTL=254
Zeitüberschreitung der Anforderung.`

**Comment by jomjol** [comment]
That is really a lot. How did you mount the external antenna? Did you also resolder the switch, so that is is connected?

There is no reason in the firmware, that could explain, why you lose the connection after some time. I have no further idea what to do.

**Comment by mad2xlc** [comment]
Yes i resolder that switch.
For testing i installed an esphome instance on the same device with no performance issues. 
What I noticed is when I copy the initial content to the SD card and don't do the setup, the device remains available.
Which internet connections does the device need? Is there anything beside the NTP server pool? Maybe my DNS server is blocking something. I will bypass this and configure an other DNS server for this device.

**Comment by jomjol** [comment]
This is really strange. The wifi-connection part is independend from the way you access the ESP32. Because first of all, the wifi connection is done.
There is only one topic, that was brought recently to my attention: how do you access the MQTT? I always use the direct IP-address and do not use a hostname there. Maybe this could be a topic?

**Comment by mad2xlc** [comment]
I hooked up to the serial port. And there i found something. Can you explain what should happen right after [Alignment]?

vor reg server main
vor dotautostart
task_autodoFlow: start

open config file /sdcard/config/config.ini in mode r
[MakeImage]
Start ReadParameter ([MakeImage]
)
;LogImageLocation = /log/source
WaitBeforeTakingPicture = 5
;LogfileRetentionInDays = 15
Brightness = -2
;Contrast = 0
;Saturation = 0
ImageQuality = 5
ImageSize = VGA
FixedExposure = false

[Alignment]
Guru Meditation Error: Core  0 panic'ed (LoadProhibited). Exception was unhandled.
Core 0 register dump:
PC      : 0x400eef3a  PS      : 0x00060030  A0      : 0x8018c839  A1      : 0x3fff7c00  
A2      : 0x00000000  A3      : 0xfffffffe  A4      : 0xffffff9c  A5      : 0xffffff9c  
A6      : 0x3ffb7c4c  A7      : 0x00000001  A8      : 0xffffff9d  A9      : 0x3fff7be0  
A10     : 0x00000000  A11     : 0x00000000  A12     : 0x3ffd385b  A13     : 0x00000000  
A14     : 0x00000000  A15     : 0xff000000  SAR     : 0x00000018  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x00000048  LBEG    : 0x4008a3cc  LEND    : 0x4008a3e8  LCOUNT  : 0xffffffff  

ELF file SHA256: 95c885e95605412e

Backtrace: 0x400eef37:0x3fff7c00 0x4018c836:0x3fff7c20 0x4018b32d:0x3fff7ce0 0x400f106e:0x3fff8160 0x400f1273:0x3fff81a0

Rebooting...


In a run before it was fine

[Alignment]
Start ReadParameter ([Alignment])
InitialRotate = 8
InitialMirror = false
SearchFieldX = 20
SearchFieldY = 20
AlignmentAlgo = default
FlipImageSize = false
/config/ref0.jpg 220 272
/config/ref1.jpg 499 164

**Comment by jomjol** [comment]
[Alignment] should be visible two times, the second one is for the GPIO setup. Can you post a full logfile?

**Comment by mad2xlc** [comment]
[exception_1.txt](https://github.com/jomjol/AI-on-the-edge-device/files/7454154/exception_1.txt)

**Comment by jomjol** [comment]
Okay - I can read the following:
1) the first rund is running normally and ends in line 420 ``Autoflow: sleep for : 25317ms`` 
That means, that your configuration is running normally
2) Second rung is also okay (line 484), ...
3) The problem starts in line 741: 
```
[0;31mE (1185088) camera: Timeout waiting for VSYNC[0m
[0;31mE (1185088) server_part_camera: CaptureToBasisImage: Camera Capture Failed[0m
[0;32mI (1185088) server_ota: Reboot in 5sec[0m
```
There the camera cannot be read any more (VSYNC problem). Therefore this is one of the unstabilities, that cannot be explained. It might be related to the HW, but there is nothing, that I can do from the firmware currently.

**Comment by mad2xlc** [comment]
YES, problem found. It was a faulty camera module. I replaced it (had one spare left). And now the esp32 is up for 14hours.
Many thanks
und grüße aus Salzburg
