### ISSUE TITLE
Implementing LORA for AI on the Edge Device

### ISSUE THREAD

**Issue by istratezaur** [jomjol/AI-on-the-edge-device#383]
Hi Jomjol and guys,

First, I wish to say thank you for the amazing and useful thing u made here with the ESP32! Really great
Also, I am a big fan of LoRa usefulness and applications, trying to make as many things as possible and I think it would be awesome some implementation of the water or gas meter with LoRa. 
Therefore, if you want to give some advice or to help with future development. I mention that I am not really good at coding(mechanical engineer, just a passion for IoT). Is there any file where readings are saved on ESP or some easy way to do this in order to transmit it via LoRa? 
Thank you very much!
Mihnea Istrate

**Comment by jomjol** [comment]
Hi Mihenea,
LoRA is a big wish from several users, never the less it might be very tricky to implent, due to the limited remaining resources on the ESP32CAM. And most important, I don't have time to deal with this in the next future.

The actual reading is always stored in the following file: /config/prevalue.ini

Best regards,
  jomjol

**Comment by goranskular** [comment]
Lora would be great, but also power consumption and sleep mode needs to be solved first. Right now it uses around 10mA. 

I would like to use it for a water meter which is outside of my house, underground. I would use a micro hydro generator 5V on the water pipe and one 3.7V LiPo 2000mAh battery with small charge controller like TP4056 and DC boost to 5V.

If not with this esp32 board, maybe with low power version of esp32 Firebeetle with cam module and Lora module.

Thanks for the project!

**Comment by istratezaur** [comment]
> Hi Mihenea, LoRA is a big wish from several users, never the less it might be very tricky to implent, due to the limited remaining resources on the ESP32CAM. And most important, I don't have time to deal with this in the next future.
> 
> The actual reading is always stored in the following file: /config/prevalue.ini
> 
> Best regards, jomjol

**Comment by istratezaur** [comment]
> Hi Mihenea, LoRA is a big wish from several users, never the less it might be very tricky to implent, due to the limited remaining resources on the ESP32CAM. And most important, I don't have time to deal with this in the next future.
> 
> The actual reading is always stored in the following file: /config/prevalue.ini
> 
> Best regards, jomjol

Hi jomjol,
Thank you for your promptly answering and help :) 
Right now, I think to use another ESP32 just for LoRa, therefore I am looking forward how can I transfer via serial the info  stored in  /config/prevalue.ini 
I will check the code, but if you have any hints, I would be very gladful. 
Thank you again !
Mihnea

**Comment by jomjol** [comment]
The serial is extensivly used for debugging, as the JTAG-debugger cannot be connected (no free GPIOs). But you can inject at any point (e.g. in the doFlow function of the Postprocessing) an unique identifier, on which you trigger the second ESP32.

**Comment by jomjol** [comment]
I'll close this issue for the time beeing, as I cannot follow it currently
