### ISSUE TITLE
Probleme mit den Kommastellen

### ISSUE THREAD

**Issue by michi2274** [jomjol/AI-on-the-edge-device#385]
Hi, habe Probleme mit den Kommastellen.
die Werte werden richtig erkannt aber es wird auf die erste Nachkommastelle gerundet. Und erhalte ab der zweiten Runde die Meldung Wert zu klein.
![wasser1](https://user-images.githubusercontent.com/93586739/139885858-d7b281a2-e73e-4ee4-8f31-ddf89864166d.PNG)

mit den folgenden Einstellungen

![config](https://user-images.githubusercontent.com/93586739/139887873-282882f3-871e-4e45-996a-4f86171166c2.PNG)

Wenn ich die Konsistenzprüfung deaktivieren erhalte ich den Wert mit allen Nachkommastellen, aber dann mit dem Risiko das evtl. Zahlen nicht erkannt werden.
![wasser2](https://user-images.githubusercontent.com/93586739/139906567-4a884ea7-9057-42b1-8976-0fdab66e7782.PNG)

Den Set PreValue hab ich auch schon mal  auf 46.9771 gesetzt. Wenn ich die Konsistenzprüfung nach erfolgreicher Erkennung aller Stellen wieder einschalte und Neustarte sieht es leider wieder so aus wie im ersten Bild.

Wo liegt mein Fehler? Vielen Dank

![version](https://user-images.githubusercontent.com/93586739/139907672-44dc5709-a42b-406d-bddc-260ccc769766.PNG)

**Comment by friedpa** [comment]
Verstehe jetzt nicht ganz warum Deine ROI Fenster so unterschiedlich sind (einmal oben, einmal unten). Bitte an jomjols Empfehlungen im Wiki achten. Woher kommen die deutschen Übersetzungen im Configuration Fenster, z.B. "Negative Preise zulassen" versus "AllowNegativeRates"?

**Comment by michi2274** [comment]
Ich hatte zur besseren Wortwahl die Seite kurz ins deutsche übersetzen lassen, und da meinen Screenshot gemacht, die Fehler tauchten aber schon vorher auf. Zu den ROI Fenstern, die hatte ich schon mehrmals geändert, aber das dürfte ja nichts mit der Anzahl der Kommastellen zu tun haben. Beim Wasserzähler interessieren mich halt auch die 2 und 3 Stelle.

**Comment by hsmwfgie** [comment]
Hallo, ich habe das gleiche Problem. Gibt es mittlerweile eine Lösung für das Problem?

**Comment by jomjol** [comment]
Nein - ich habe diese Woche keine Zeit, mich darum zu kümmern. Muss tiefer in den Code schauen, zumal bei mir das Problem nicht auftritt. Könnt einer von (@hsmwfgie, @michi2274) seine `config.ini` posten, damit ich nach den Unterschieden zu meinem Setting suche.

**Comment by jomjol** [comment]
Update: Fehler im Code ist gefunden und wird die Tage korrigiert. Dauert noch einen Moment, da ich es Testen muss.

**Comment by michi2274** [comment]
Danke schon mal für die Hilfe

**Comment by hsmwfgie** [comment]
Von mir ebenfalls schon mal ein großes Dankeschön. Hab dir für deine tolle Arbeit gerade paar Euro per Paypal gespendet!

**Comment by jomjol** [comment]
Ich habe jetzt im Rolling branch ein bug-fix hochgeladen. Da ich es doch nicht ohne Aufwand (müsste mein Produktivsystem benutzen) testen konnte, bitte bei euch mal prüfen, ob der Fehler jetzt weg ist.
Wenn nicht, bitte natürlich sofort melden.

**Comment by hsmwfgie** [comment]
Hi jomjol, sieht gut aus. Die Nachkommastellen sind jetzt alle da. 
Vielen Dank!

**Comment by jomjol** [comment]
Danke für die Rückmeldung. Dann mache ich den Issue hier zu und beim nächsten Release landet das dann automatisch die Tage im Main

**Comment by michi2274** [comment]
Konnte leider erst jetzt testen, läuft bei mir jetzt auch.
