### ISSUE TITLE
Ziffer wird nicht korrekt erkannt

### ISSUE THREAD

**Issue by hsmwfgie** [jomjol/AI-on-the-edge-device#386]
Hallo, ich habe das Problem, dass die Ziffer 6 auf meinem Zähler meistens als "0" oder manchmal auch als "4" erkannt wird.
Alle anderen Ziffern scheinen gut erkannt zu werden.
Hat jemand eine Idee, woran das liegen könnte? Oder besteht die Möglichkeit ein Modell für meine eigenen Ziffern zu trainieren
<img width="666" alt="2021-11-04_10-09-21" src="https://user-images.githubusercontent.com/58842478/140289962-dae83519-3565-4de9-8515-c3d81fec81b7.png">
?

**Comment by jomjol** [comment]
Deine ROIs für die digitalen Ziffern sind nicht optimal. Sie sollten eigentlich alle gleich groß sein. Im Einstellfenster gibt es beim aktiven ROI bewußt das innere Viereck, das sollte genau mit den Ziffern abschließen (wenn sie mittig stehen):
![grafik](https://user-images.githubusercontent.com/30766535/140306894-2ef0fe2a-67ed-4eb4-a960-529fc89ea04c.png)

**Comment by hsmwfgie** [comment]
Danke für die Info, habe das jetzt mal so umgesetzt und da funktioniert es jetzt auch!

**Comment by jomjol** [comment]
Dann mach ich den Issue erstmal zu.
