### ISSUE TITLE
An other esp32-cam with psram problem

### ISSUE THREAD

**Issue by LacerDomotique** [jomjol/AI-on-the-edge-device#389]
Hello,
I got another esp32-cam and I still have the psram problem.
The psram reference on both esp is : IPUS IPS6404L
What PSRAM do you have ?
It is to know if the problem can come from there. I have seen esp32-cam with ips6404L at ap memory. Are there any differences ?

![Psram IPUS 6404L](https://user-images.githubusercontent.com/87008912/140618902-81c0acb5-b599-45da-8182-c8e0c7b02f5d.jpg)

**Comment by jomjol** [comment]
This is mine:
![grafik](https://user-images.githubusercontent.com/30766535/140624900-7e2ccea5-75dc-4f80-934b-21e2cc97e835.png)
Working well.

**Comment by LacerDomotique** [comment]
These are two 6404L, what can be the difference ?
Do you think that’s where the problem lies ?
Can you give me the purchase link to make sure we have the same psram ?

**Comment by jomjol** [comment]
I can't tell you. I have ordered 5-6 devices differently from Amazon or Alibaba by change. All of them where working. I guess the problem is somewhere else.
Do you use my compiled version or do you compile by your own?

**Comment by friedpa** [comment]
Good Norning, I am using this type purchased via Amazon. They are working fine in two installations.

![grafik](https://user-images.githubusercontent.com/42890695/140636738-0aea80a0-d24a-4e2d-9a30-3998812e398b.png)

https://www.amazon.de/gp/product/B07WS3W52J/ref=ppx_yo_dt_b_asin_title_o01_s00?ie=UTF8&psc=1

**Comment by LacerDomotique** [comment]
> I can't tell you. I have ordered 5-6 devices differently from Amazon or Alibaba by change. All of them where working. I guess the problem is somewhere else. Do you use my compiled version or do you compile by your own?

I use your compiled version. What is the advantage of compiling your own version ?
It's strange, two differents esp but with the same psram

**Comment by LacerDomotique** [comment]
> Good Norning, I am using this type purchased via Amazon. They are working fine in two installations.
> 
> ![grafik](https://user-images.githubusercontent.com/42890695/140636738-0aea80a0-d24a-4e2d-9a30-3998812e398b.png)
> 
> https://www.amazon.de/gp/product/B07WS3W52J/ref=ppx_yo_dt_b_asin_title_o01_s00?ie=UTF8&psc=1

What is the reference of the psram on your board ?

**Comment by friedpa** [comment]
It says:
IPUS
IPS6404LSO
1823Y7GW

**Comment by LacerDomotique** [comment]
> It says: IPUS IPS6404LSO 1823Y7GW

Same as mine and it's work for you
How did you flash it ?

**Comment by LacerDomotique** [comment]
> > I can't tell you. I have ordered 5-6 devices differently from Amazon or Alibaba by change. All of them where working. I guess the problem is somewhere else. Do you use my compiled version or do you compile by your own?
> 
> I use your compiled version. What is the advantage of compiling your own version ? It's strange, two differents esp but with the same psram

And how did you flash it ? I use windows power shell and it seems to work

**Comment by friedpa** [comment]
I am using Flash_Download_Tool_3.8.5

**Comment by LacerDomotique** [comment]
> I am using Flash_Download_Tool_3.8.5

What do you think of that ?

During the boot
[0;31mE (885) cpu_start: Failed to init external RAM!
Backtrace: 0x4008cfb0:0x3ffe3c00 0x4008d3e1:0x3ffe3c20 0x40081dcf:0x3ffe3c40 0x4007931a:0x3ffe3c80 |<-CORRUPTED


![image](https://user-images.githubusercontent.com/87008912/140641807-2af5069f-1f83-4cfd-b37e-ed6d70c2fb6f.png)

![image](https://user-images.githubusercontent.com/87008912/140641819-b1a589da-3a54-44c7-b736-cef638b9b9f2.png)

![image](https://user-images.githubusercontent.com/87008912/140641824-3f239f04-ecf2-4715-895d-8c502df9dd13.png)

**Comment by JanHBade** [comment]
maybe runnig simple tests may help: https://thingpulse.com/esp32-how-to-use-psram/

**Comment by jomjol** [comment]
Bei mir funktioniert das Flashing Tool nicht. Ich flashe daher aus einer Python Umgebung heraus mit dem esptool.

**Comment by friedpa** [comment]
I had once the problem wit an "faulty" USB-Cable. Maybe you try another one?!

**Comment by LacerDomotique** [comment]
> Bei mir funktioniert das Flashing Tool nicht. Ich flashe daher aus einer Python Umgebung heraus mit dem esptool.

I have also tried with esptool under windows powershell, same problem

**Comment by LacerDomotique** [comment]
> maybe runnig simple tests may help: https://thingpulse.com/esp32-how-to-use-psram/

This code

#include <Arduino.h>

void logMemory() {
  log_d("Used PSRAM: %d", ESP.getPsramSize() - ESP.getFreePsram());
}

void setup() {
  logMemory();
  byte* psdRamBuffer = (byte*)ps_malloc(500000);
  logMemory();
  free(psdRamBuffer);
  logMemory();
}

void loop() {}

Gives this result

ets un  8 2016 00:22:57

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:928
ho 0 tail 12 room 4
load:0x40078000,len:8740
load:0x40080400,len:5800
entry 0x4008069c
[W][esp32-hal-psram.c:30] psramInit(): PSRAM init failed!
[D][CameraWebServer.ino:4] logMemory(): Used PSRAM: 0
[D][CameraWebServer.ino:4] logMemory(): Used PSRAM: 0
[D][CameraWebServer.ino:4] logMemory(): Used PSRAM: 0

It confirms that there is a psram problem

**Comment by LacerDomotique** [comment]
I did the following test
CameraWebServer works, but there is something very strange, I explain :
Under arduino I configure the esp32-cam as "ESP32 Wrover Module " (In tools/Type of board) and I load CameraWebServer (with #define CAMERA_MODEL_AI_THINKER), I Compile and load it.
Then I restart the esp with tools/serial monitor
There is the error : [esp32-hal-psram.c:30] psramInit(): PSRAM init failed! But CameraWebServer starts on 192.168.2.148 with resolution QVGA (320 x 240)

![image](https://user-images.githubusercontent.com/87008912/140653990-ac25490e-ebc1-442a-ae3c-2d9d0e9384ad.png)
 
Now same thing with :
Under arduino I configure the esp32-cam as "AI Thinker ESP32-CAM" (In tools/Type of board) and I load CameraWebServer (with #define CAMERA_MODEL_AI_THINKER), I Compile again and load it.
Then I restart the esp with tools/serial monitor
There is no PSRAM error

![image](https://user-images.githubusercontent.com/87008912/140654007-3c6429c1-bbe6-411c-a2c0-5b53362db0e4.png)

I do not know arduino and I will perhaps say a stupidity but it seems that in environment "AI Thinker" the psram is enable and not in "Wrover" environment
So, if I could load the 3 binaries at the correct address under Arduino in the "AI Thinker" environment it will work ?
But I don't know how to do, is it possible ?

**Comment by jomjol** [comment]
This is really strange. I never heared of such a strang behaviour. 
Your idea of uploading the firmware in some kind of "Arduino AI-Thinker" environment will not work. The 3 binaries are the firmware compiled for the ESP32CAM module. There is no way of uploading them to some kind of special environment.

**Comment by JanHBade** [comment]
maybe the two baords have a different pinout/configuration for the psram...

So we have to check the schematics a see a diff maybe...

**Comment by jomjol** [comment]
Please reopen in case of further discussion
