### ISSUE TITLE
Camera or lens to take pictures at very close range

### ISSUE THREAD

**Issue by 111lisu** [jomjol/AI-on-the-edge-device#390]
I am looking for a camera or lens to take pictures at very close range, has anyone had such a case?
I only have a few centimeters in the counters.

**Comment by jomjol** [comment]
Have a look into this design: https://www.thingiverse.com/thing:5028229
It only need 3cm due to a mirror and 90° arrangement.

**Comment by 111lisu** [comment]
Thanks, I like it very much.

**Comment by jomjol** [comment]
Your welcome - I close this issue
