### ISSUE TITLE
Analog digits not recognized anymore

### ISSUE THREAD

**Issue by StrathCole** [jomjol/AI-on-the-edge-device#391]
Since last update I have a really strange behaviour.
The recognition of the analog values stopped working suddenly.

![Bildschirmfoto von 2021-11-08 13-10-06](https://user-images.githubusercontent.com/7449529/140740103-1b2f8796-0d55-4fa5-88e4-7555371010d4.png)

![Bildschirmfoto von 2021-11-08 13-10-28](https://user-images.githubusercontent.com/7449529/140740105-a8d8589f-780d-4a9d-9a22-748dc2c2dc2b.png)

At "recognition" during page load there is 4 times a -1.0 shown and after page load it shows the image attached.
The alignments seem to be correct (the last digit of the digital numbers is moved up a bit by purpose).

**Comment by jomjol** [comment]
Can you update your tflite-file for the analog (in the /config) to the newest version?

1. Download (https://github.com/jomjol/AI-on-the-edge-device/blob/master/sd-card/config/ana0700s1lq.tflite) and upload to /config
2. Change the filename in the corresponding line in config.ini

**Comment by StrathCole** [comment]
Thank you that solved it. The file name in the config.ini was already there and correct, but in config there was no ana*.tflite file at all.
Should I also upload https://github.com/jomjol/AI-on-the-edge-device/blob/master/sd-card/config/dig1310s3q.tflite to the config folder? I still have a file dig0870s3q.tflite in there and referenced in config.ini.

**Comment by jomjol** [comment]
If your current tflite is working well, there is no need to update.

"Never change a running system"

**Comment by StrathCole** [comment]
Thank you a lot.
