### ISSUE TITLE
Falsche Erkennung

### ISSUE THREAD

**Issue by s0170071** [jomjol/AI-on-the-edge-device#392]
![grafik](https://user-images.githubusercontent.com/33855380/140891847-b0cb413e-18d3-4a00-8658-c27f39579c58.png)
 .. mit den tflite files aus dem "new pointer design" issue.

**Comment by jomjol** [comment]
Komisch, ich verwende die auch und habe kein Probleme damit. Die 000.00 sieht aus wie ein fehlendes tflite. Vielleicht ein Schreibfehler in der config.ini?

**Comment by jomjol** [comment]
Keine weiteren Aktivitäten - bitte wieder öffnen bei Diskussionsbedarf
