### ISSUE TITLE
tflite zusenden

### ISSUE THREAD

**Issue by gomble** [jomjol/AI-on-the-edge-device#394]
Hallo,

wie kann ich meine tflite Datei zukommen lassen, damit diese ebenfalls angelernt werden?

**Comment by jomjol** [comment]
Eine tflite ist das Ergebnis des Trainings. Ich kann diese nicht in eine andere hinein lernen. Ich benötige die Rohbilder, z.B. per ZIP-File hier im Issue.
Bitte nicht zu viele Bilder senden, maximal 2-3 pro Ziffer.

**Comment by jomjol** [comment]
Bitte wieder öffnen bei weiterem Diskussionsbedarf
