### ISSUE TITLE
Meter photovoltaic Gama 350

### ISSUE THREAD

**Issue by 111lisu** [jomjol/AI-on-the-edge-device#395]
I have a question if there is a chance to read several values at the same time of the photovoltaic meter:
1.8.1 or 1.8.1.0 Read meter of imported energy.
2.8.1 or 2.8.1.0 Value of exported energy.

https://www.youtube.com/watch?v=9-ipV8ld6h8

**Comment by MMeinhardt1** [comment]
This electric meter have an optical output to read the values. For ioBroker you need the smartmeter adapter. Have a look on google to readout a smartmeter.

**Comment by jomjol** [comment]
You can digitize every number, that you find on an image. There is nothing implemented to push the button.

**Comment by 111lisu** [comment]
This meter has a weak soft (cheap version). I was about to buy a onemeter.com, but it turned out that it does not support it.
In total, you could add something to press the button, because I use Hassio, but this counter displays the values in the loop, it is enough to read it once a day, but how to prepare such a configuration?

**Comment by jomjol** [comment]
Technical it is possible to use GPIO12 or GPIO13 to controll a push button device. Or you can make some effort to synchronize the readout with the loop. Both would be quite some effort for the firmware.

**Comment by 111lisu** [comment]
If he only read the values to me - the rest could be done quickly in Node Red

**Comment by jomjol** [comment]
The major task is to synchronize and implement a reading of a rolling display itself. The postprocessing is the easy part anyway.
