### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by tcpipchip** [jomjol/AI-on-the-edge-device#396]
![image_2021_11_10T18_01_01_531Z](https://user-images.githubusercontent.com/11488460/141318774-ded36f73-b0e6-42a1-9b7c-35521f995a70.png)
This was my first test! It´s really works nice!

**Comment by friedpa** [comment]
What do you want to show/ask?

**Comment by jomjol** [comment]
As you realize, you can digit everything on an image. The ROI can be improved.

**Comment by tcpipchip** [comment]
yes, i know! I will do more tests!
