### ISSUE TITLE
LED WS2812

### ISSUE THREAD

**Issue by rieders** [jomjol/AI-on-the-edge-device#397]
Hallo

Ich habe wie in der Anleitung [https://github.com/jomjol/AI-on-the-edge-device/wiki/External-LED](url) die LED´s angeschlossen.
Die Firmwareversion 9 habe ich installiert.
Leider bekomme ich bei GPIO12 keine Auswahl "Anzahl der LED" und LED Color.
Bei GPIO 12 State "external flash light pwm controlled ( not implemented )
Wie kann ich das aktivieren ?

Grüße André

**Comment by jomjol** [comment]
Welche html Version hast du installiert?
![grafik](https://user-images.githubusercontent.com/30766535/141655943-e6fc8284-60e8-4fae-a153-8558d0737df4.png)

Sollte 11.0.1 sein, ansonsten bitte updaten. Es müsste eigentlich so aussehen:
![grafik](https://user-images.githubusercontent.com/30766535/141655934-f851ba59-5baa-4b2b-aaf3-8b2c2c3f7629.png)

**Comment by jomjol** [comment]
keine Aktivität --> schließe den Issue vorerst

**Comment by rieders** [comment]
Hallo
Ich habe die HTML version nochmal überspielt.
Dann ging es.

Grüße
André
