### ISSUE TITLE
Keine Ansteuerung von mehr als 2 LEDS über GPIO12 möglich.

### ISSUE THREAD

**Issue by ankulf** [jomjol/AI-on-the-edge-device#399]
Hallo,

zuallererst möchte ich ein großes Dankeschön an dieses Projekt aussprechen. 
Mein Wasserversorger hat mir vor einem Jahr einen neuen digitalen Zähler eingebaut, der über M-Bus auslesbar ist. 
Leider ist mir der Zugang durch eine Verschlüsselung nicht möglich. Den Key dafür wird mir leider auch nicht zur Verfügung gestellt, so dass ich für dieses Projekt sehr dankbar bin.

Aufgrund von Spiegelungen im LCD durch die interne LED, habe ich mich heute an einer Umsetzung des neuen Updates versucht.

Leider musste ich feststellen, dass auch mit der Version 9.1.0 keine Ansteuerung von mehr als 2 LEDs des WS2812 Stripes möglich ist.

Nachfolgend das Fehlerbild bei der Ansteuerung von mehr als 2 LEDs.

Über eine Lösung wäre ich dankbar! 

Viele Grüße
Andreas

![IMG_1470](https://user-images.githubusercontent.com/94314763/141694493-b09c7188-8ca6-4446-bb55-ef9af3e6e5d2.JPG)

**Comment by jomjol** [comment]
Hi Andreas,
es gibt hier wohl ein Problem mit einem Speicherleck. Das ist extrem schwer zu finden. Ich habe sowohl eine lokal implementierte Lösung probiert (die Schnittstelle wird bei jedem Aufruf initialiert), wie auch eine globale (Schnittstelle wird am Anfang initialisiert und dann verwendet). Bei mir funktioniert nur die lokale, aber anscheinend nicht bei allen.
Ich werde das mal weiter testen, aber eine schnelle Lösung kann ich nicht versprechen. Empfehlung: erstmal nur maximal 2 LEDs benutzen, ist immerhin schon 1 mehr, als nur die interne :-).

**Comment by ankulf** [comment]
Hallo,

vielen Dank für die schnelle Antwort. Ich werde mich hüten auf eine schnelle Lösung zu drängen :) ... gut muss eine Lösung sein.

Ich kann mich zwar nur am Rande mit Programmierung aus, aber ich habe in der Komponente "jomjol_controlGPIO/server_GPIO.cpp" eine Stelle in einer IF-Bedingung gefunden, die genau das Anzeigebild der LED 1 und LED 2 - wie auf meiner Aufnahme - definiert:


![image](https://user-images.githubusercontent.com/94314763/141848913-cfe18f2b-2980-4c90-bfc7-f5f1f6cd3582.png)

**Comment by jomjol** [comment]
Danke für den detailierten Hinweis. In der Tat ist dieser Code nicht korrekt. Da habe ich wohl einen Fehler beim Merge von Rolling in Master gemacht. 
Teste bitte mal die Version 9.1.1, dort ist dieser Fehler korrigiert.

**Comment by ankulf** [comment]
Hallo,

danke für die schnelle Umsetzung.
Ein erster kurzer Test zeigt, dass der Fehler behoben ist. 
Nur leider scheint jetzt das ganze System sich in einer Schleife zu befinden. 

Der Webserver ist kaum noch erreichbar. 
Auch die Ansteuerung der LEDs und die Kamera funktioniert nur noch sporatisch, so dass vorübergehend wieder ein Wechsel auf die 9.1.0 sinnvoll wäre.

Lass dir Zeit bei der Fehlersuche. 

Danke schon einmal vorab.

VG

**Comment by jomjol** [comment]
Hallo,
das sollte nichts mit dem LED Update zu tun haben. Habe es bei mir auch bei zwei ESPs heute morgen installiert und es läuft ohne Probleme.

**Comment by ankulf** [comment]
Hallo,

danke für Rückmeldung.
Ich werde meinen ESP32 noch einmal neu aufsetzen und erneut testen.

Danke und VG

**Comment by ankulf** [comment]
Hallo,

ich habe heute Abend meinen ESP32 noch einmal neu aufgesetzt. 

Testergebnisse und gewonnene Erkenntnisse:

Die Aktivierung und Nutzung des GPIO12 Pins für die externe Steuerung des WS2812 Stripes funktioniert tadellos unter folgender Voraussetzung:
> In jedes RGB Feld muss der gleiche Wert eingetragen werden. (Screenshot 1)
> Wird davon abgewichen, weil beispielsweise nur die Farbe ROT angezeigt werden soll, so friert der ESP32 nach dem Neustart ein und ist nicht mehr nutzbar. Dies ist, bei mir jedenfalls, reproduzierbar.

Da ich aber nur "Weiß" benötige und insgesamt 10 - in der Helligkeit steuerbare - LEDs anbinden möchte, ist für mich die eigentliche Funktionalität erfüllt.
Danke noch einmal für das Projekt und die investierte Arbeit!

VG

Screenshot 1 - Funktionsfähig:
![image](https://user-images.githubusercontent.com/94314763/142277165-4d5d7b5c-2498-441e-93d6-9435b4725cd3.png)

Screenshot 2 - ESP32 friert ein:
![image](https://user-images.githubusercontent.com/94314763/142277537-20188e09-f5a6-4d6c-98eb-b2c30619ff4d.png)

**Comment by jomjol** [comment]
Im Feld für Grün und Blau muss auch eine Ziffer drin stehen, in diesem Fall eine "0". Dann sollte auch eine Farbe funktionieren. Könntest du das bei dir evt. testen?

**Comment by ankulf** [comment]
Hallo,

ja du hast recht :). Kleiner Fehler große Wirkung.

Wenn durch die Felder ein Wert mitgegeben wird, dann funktioniert alles wie gewünscht. Eventuell kann man die Feldeingaben noch abprüfen, um solche Fehler, wie von meiner Person zu vermeiden :).

Von mir aus, kann das Ticket dann geschlossen werden.
Danke für die schnelle Hilfe!

VG
