### ISSUE TITLE
File Server: Option to delete multiple/all files in a directory

### ISSUE THREAD

**Issue by michaeljoos72** [jomjol/AI-on-the-edge-device#4]
Hi jomjol

It would be great to have an option to select and delete multiple/all files at once in file server.
This would especlially help to clean up the Log-Folders without to remove the SD-Card.

BR
Michael

**Comment by jomjol** [comment]
Feature is implemented in version 1.1.0:

Beside the firmware, you also need to update the content of /html

![grafik](https://user-images.githubusercontent.com/30766535/92333587-fbdbee80-f086-11ea-84db-e685986c4303.png)
