### ISSUE TITLE
Feature Request: add support for ds18b20 temp sensor

### ISSUE THREAD

**Issue by jezikk82** [jomjol/AI-on-the-edge-device#400]
Hi, great software, still learning how to use all the features.
Now I have 2 esp's, one for 3 ds18b20 (temp of cold water intake, hot water in boiler, warn water from heating pump) and other with reading water usage.

In future I'd love to combine both devices in to one.
Would it be possible to add support for multiple 1-wire temp sensors in you software?
Just simple scan 1-wire line to detect sensors and add name to then, later populate this info the same way as meters reading to mqtt.

Thanks in advance

**Comment by jomjol** [comment]
Technically this is feasable, but would make this even more complex and error sensitive. As an esp32 is a really cheap device, the effort is not worth the benefit.
But fell free to make a fork out of this. I can incorporate it later then back in the main path.

**Comment by jezikk82** [comment]
Unfortunately, I'm not a software dev and I cant do it myself. 
I'm using this espeasy firmware (https://github.com/letscontrolit/ESPEasy), perhaps you can just copy/paste the relevant code responsible for 1-wire.  Please consider that.  It'd open new possibilities in all-in-one form for many other people, as mostly this device is located in the room with meters, often heating, boilder, etc.

**Comment by jomjol** [comment]
Sorry for not supporting your request.
But merging two softwares together can really be very painfull. Even incorporating only parts of the code would take several working days:
underst

- anding the other code
- make a modified version
- modify my own code
- incorporate in the configuration
- test and debugging
- ...

If I would need to pay somebody for this I would not be surprise for much more then 40 hours of full working time. Just compare this to the costs of a second ESP32 for about 10€. I don't have time and ressources to do so.

Sorry for not considereing this.
