### ISSUE TITLE
Water leak guard

### ISSUE THREAD

**Issue by jjude1966** [jomjol/AI-on-the-edge-device#401]
The idea would be to read the water meter at night, for example at 3:00 and 4:00, and save the difference in memory, which can then be displayed in an html form.
If the reading is something (and the resident has not used water) water leakage may be suspected.

**Comment by friedpa** [comment]
Why do you not use e.g. IOBroker for this? You are getting the data via MQTT into the IOBroker very easily and after that you can do everything you want. The esp32 is very low cost and low on performance / memory so using an front-end would be solving your problem quickly.

**Comment by jomjol** [comment]
I agree with friedpa and suggest to solve this with an external unit like iobroker or comparable.
