### ISSUE TITLE
Not responding after 20 hours.... 

### ISSUE THREAD

**Issue by nibors76** [jomjol/AI-on-the-edge-device#402]
Just flashed a Esp32-cam yesterday, set it up properly, got readings etc.
But today, when trying to log in via browser, I get "connection refused", and Mqtt stream is stopped...
Any tips and tricks, or is it just to re-flash it again....?

**Comment by friedpa** [comment]
That sounds, as I had it also several times that the WiFi connection is not working. Can you see the ESP on your Router?

**Comment by nibors76** [comment]
Yes it is connected, and also have a tiny bit of traffic to and from it...

**Comment by nibors76** [comment]
After formatting the SD card, and copying the files (not the old ones) it is up and running again... Had to do a full setup again, but....

**Comment by jomjol** [comment]
This sound like some instable system. You can make a copy of the config directory as backup. Then you do not need to make the setup again, if your system crashes again.

**Comment by nibors76** [comment]
This has happened on 2 different esp32-cam, with 2 different SD cards.
There is no obvious reason for this, as I see it, other than that 2 esp32cam, and 2 SD cards is faulty. Which is very unlikely....
