### ISSUE TITLE
Device is rebooting after fiew seconds after boot up

### ISSUE THREAD

**Issue by vitalyu** [jomjol/AI-on-the-edge-device#403]
Hi. I was bought ESP32-CAM from [this seller](https://www.aliexpress.com/item/4000093185394.html). All specifications like in requirements.
After flashing and booting up, the device was connected to my wlan and opens the web page. But, after a 2-5 seconds it reboots. Within this fiew seconds, I can browse the pages and they opens correctly, but device always reboots. I tried 3 latest firmware, with a different power supplies and flash cards - same result. Maybe, somebody know what happens. All other firmwares (arduino examples for ai thinker esp32-cam) works stable. Thanks

Output from serial before rebooting:
```
02:05:36.984 -> [0;32mI (16756) server_GPIO: GPIO init comleted, handler is disabled[0m
02:05:36.984 -> Flashdauer: 30000
02:06:07.535 -> Image loaded from memory: 0, 0, 0
02:06:07.535 -> Guru Meditation Error: Core  0 panic'ed (LoadProhibited). Exception was unhandled.
02:06:07.569 -> Core 0 register dump:
02:06:07.569 -> PC      : 0x400ef224  PS      : 0x00060030  A0      : 0x8018c502  A1      : 0x3fff9fd0  
02:06:07.569 -> A2      : 0x00000780  A3      : 0x3ffc3cb4  A4      : 0x00000280  A5      : 0x00000780  
02:06:07.569 -> A6      : 0x00000001  A7      : 0x000001e0  A8      : 0x00000000  A9      : 0x3f82c168  
02:06:07.569 -> A10     : 0x00000000  A11     : 0x3fffa388  A12     : 0x00003200  A13     : 0x00000001  
02:06:07.602 -> A14     : 0x3ffc35b4  A15     : 0x3fff9ef0  SAR     : 0x0000001e  EXCCAUSE: 0x0000001c  
02:06:07.602 -> EXCVADDR: 0x00000000  LBEG    : 0x4008bed5  LEND    : 0x4008bee5  LCOUNT  : 0xffffffff  
02:06:07.602 -> 
02:06:07.602 -> ELF file SHA256: 0dbda5e7af80986c
02:06:07.602 -> 
02:06:07.602 -> Backtrace: 0x400ef221:0x3fff9fd0 0x4018c4ff:0x3fffa040 0x4018c586:0x3fffa080 0x40189cc1:0x3fffa110 0x400f12be:0x3fffa1c0
02:06:07.602 -> 
02:06:07.602 -> Rebooting...
```
[Full log](https://github.com/jomjol/AI-on-the-edge-device/files/7558612/log.txt)

**Comment by jomjol** [comment]
This line:
```
02:06:07.535 -> Image loaded from memory: 0, 0, 0
```
tells, that there is a problem with loading the image from the camera. There should be: "Image loaded from memory: 640, 480, 3"
Afterwards it crashes, because there is no error handling for an image with zero size.
You can check the connection of camera and module (flex cable) or test with a second camera module.

**Comment by jomjol** [comment]
closing until further notice (please reopen in case new information available)

**Comment by amishv** [comment]
Autoflow: start
doflow - start 20211128-005947
Flashdauer: 0
Image loaded from memory: 640, 480, 3
Vor ft->FindTemplate(_temp1);  /sdcard/config/ref0.jpg
FindTemplate 01 size 
FindTemplate 02
Guru Meditation Error: Core  0 panic'ed (LoadProhibited). Exception was unhandled.
Core 0 register dump:
PC      : 0x40179de7  PS      : 0x00060830  A0      : 0x8017a050  A1      : 0x3fff9e70  
A2      : 0x3ffe3d34  A3      : 0x00000000  A4      : 0x00000000  A5      : 0x00000003  
A6      : 0x00000000  A7      : 0x00000001  A8      : 0x80661135  A9      : 0x3f82c168  
A10     : 0x0000000a  A11     : 0x3ffae948  A12     : 0x00000000  A13     : 0x3ffb0ec4  
A14     : 0x000000fe  A15     : 0x7275736f  SAR     : 0x0000001e  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x80661135  LBEG    : 0x4008bed5  LEND    : 0x4008bee5  LCOUNT  : 0xfffffffc  

ELF file SHA256: eff338e7a5506d99

Backtrace: 0x40179de4:0x3fff9e70 0x4017a04d:0x3fff9f00 0x40179a29:0x3fff9fb0 0x4019323a:0x3fffa030 0x40189f17:0x3fffa0c0 0x400f115d:0x3fffa170 0x400f13ef:0x3fffa1c0
