### ISSUE TITLE
Is the color relevant for recognision?

### ISSUE THREAD

**Issue by marcelrv** [jomjol/AI-on-the-edge-device#404]
![image](https://user-images.githubusercontent.com/5871213/142374117-998181cc-9796-48f5-a1d4-045e8b512f8f.png)

I struggle to get the right recognision. The red numbers seem never to be recognised. 
I tried making the squares smaller/bigger etc, but I could never get it to recognise a number 

The last digit has a line though it, which I can imagine prevents recognision, but also always the other red numbers fail.
(also the 5th digit seems to have an isue here... that one is more random, sometimes right, sometimes wrong)

Any hint how I can improve. Is color relevant, meaning is the red/white number an issue that requires training the model more?

note using the latest release 9.11

**Comment by jomjol** [comment]
The sharpness and the contrast in the red images is not very good. This in combination with the reflections (lines in the number) cause most propably the problem.

**Comment by marcelrv** [comment]
thanks... I'll try to improve image quality once more.
Side question... I saw that in https://github.com/jomjol/neural-network-digital-counter-readout you already at 13.20 - dig1320s3q.tflite, but in your release you included the earlier 13.10  - dig1310s3q.tflite
Is 13.20 not yet ready for usage (as I was trying to train the AI with my digits to see if that would make a difference)

**Comment by jomjol** [comment]
Well, the difference should not be really big. I update it in AI-on-the-edge device only from time to time.
But can test the new one without problems and easy change back, if you see problems.
