### ISSUE TITLE
Booting is not successful

### ISSUE THREAD

**Issue by jjude1966** [jomjol/AI-on-the-edge-device#405]
Coming error : phy_init: failed to load RF calibration data...

LOG:
[0;32mI (273) esp_image: segment 1: paddr=0x00060fb8 vaddr=0x3ffb0000 size=0x05050 ( 20560) load[0m
[0;32mI (282) esp_image: segment 2: paddr=0x00066010 vaddr=0x40080000 size=0x00404 (  1028) load[0m
[0;32mI (283) esp_image: segment 3: paddr=0x0006641c vaddr=0x40080404 size=0x09bfc ( 39932) load[0m
[0;32mI (310) esp_image: segment 4: paddr=0x00070020 vaddr=0x400d0020 size=0x122edc (1191644) map[0m
[0;32mI (826) esp_image: segment 5: paddr=0x00192f04 vaddr=0x4008a000 size=0x12bb4 ( 76724) load[0m
[0;32mI (880) boot: Loaded app from partition at offset 0x10000[0m
[0;32mI (880) boot: Disabling RNG early entropy source...[0m
[0;32mI (881) psram: This chip is ESP32-D0WD[0m
[0;32mI (885) spiram: Found 64MBit SPI RAM device[0m
[0;32mI (890) spiram: SPI RAM mode: flash 40m sram 40m[0m
[0;32mI (895) spiram: PSRAM initialized, cache is in low/high (2-core) mode.[0m
[0;32mI (902) cpu_start: Pro cpu up.[0m
[0;32mI (906) cpu_start: Application information:[0m
[0;32mI (911) cpu_start: Project name:     esp32cam-server-only[0m
[0;32mI (917) cpu_start: App version:      0.0.9.3[0m
[0;32mI (922) cpu_start: Compile time:     Nov 16 2021 07:06:13[0m
[0;32mI (928) cpu_start: ELF file SHA256:  0dbda5e7af80986c...[0m
[0;32mI (934) cpu_start: ESP-IDF:          3.40100.200827[0m
[0;32mI (939) cpu_start: Starting app cpu, entry point is 0x40081b00[0m
[0;32mI (0) cpu_start: App cpu up.[0m
[0;32mI (1837) spiram: SPI SRAM memory test OK[0m
[0;32mI (1837) heap_init: Initializing. RAM available for dynamic allocation:[0m
[0;32mI (1838) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM[0m
[0;32mI (1844) heap_init: At 3FFC2A10 len 0001D5F0 (117 KiB): DRAM[0m
[0;32mI (1850) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM[0m
[0;32mI (1856) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM[0m
[0;32mI (1863) heap_init: At 4009CBB4 len 0000344C (13 KiB): IRAM[0m
[0;32mI (1869) cpu_start: Pro cpu start user code[0m
[0;32mI (1874) spiram: Adding pool of 4096K of external SPI memory to heap allocator[0m
[0;32mI (1899) spi_flash: detected chip: generic[0m
[0;32mI (1900) spi_flash: flash io: dio[0m
[0;32mI (1900) cpu_start: Starting scheduler on PRO CPU.[0m
[0;32mI (0) cpu_start: Starting scheduler on APP CPU.[0m
[0;32mI (1908) spiram: Reserving pool of 32K of internal memory for DMA/internal allocations[0m
Do Reset Camera
[0;32mI (1918) gpio: GPIO[32]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 [0m
Init Camera
[0;32mI (3928) gpio: GPIO[5]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
[0;32mI (3928) gpio: GPIO[18]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
[0;32mI (3928) gpio: GPIO[19]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
[0;32mI (3938) gpio: GPIO[21]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
[0;32mI (3948) gpio: GPIO[22]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
[0;32mI (3958) gpio: GPIO[23]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
[0;32mI (3968) gpio: GPIO[25]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
[0;32mI (3978) gpio: GPIO[34]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
[0;32mI (3988) gpio: GPIO[35]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
[0;32mI (3998) gpio: GPIO[36]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
[0;32mI (4008) gpio: GPIO[39]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
[0;32mI (4018) sccb: pin_sda 26 pin_scl 27
[0m
[0;32mI (4018) gpio: GPIO[32]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 [0m
[0;32mI (4168) camera: Detected OV2640 camera[0m
[0;32mI (4178) camera: Allocating 1 frame buffers (150 KB total)[0m
[0;32mI (4188) camera: Allocating 150 KB frame buffer in OnBoard RAM[0m
[0;32mI (4778) main: Using SDMMC peripheral[0m
Name: SD32G
Type: SDHC/SDXC
Speed: 20 MHz
Size: 29844MB
[0;32mI (4828) server_ota: Start CheckOTAUpdateCheck ...[0m
Start CheckOTAUpdateCheck ...
[0;32mI (4838) server_ota: SHA-256 for the partition table: : 9d4a2809ae90fb20709a8ca3dd3ac3462e1e73286bcd31b689060c91de06fa3a[0m
[0;32mI (4898) server_ota: SHA-256 for bootloader: : 2f4c792de3ca36713d14c6b1e98c2601ad2b22206ee169706b4dcf9e39c7c421[0m
[0;32mI (5538) server_ota: SHA-256 for current firmware: : fd924f0025e85034e06f0e4e65c62dd323f6af611ccfc42f24d89530b300852d[0m
CheckOTAUpdate Partition: ESP_OK
open file /sdcard/wlan.ini in mode r
file loaded

WLan: 5G-Gateway-FB99, my_password
Hostename: WaterMeter
I (5588) wifi:wifi driver task: 3ffd9cb4, prio:23, stack:6656, core=0
[0;32mI (5588) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE[0m
[0;32mI (5588) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE[0m
I (5618) wifi:wifi firmware version: 3ea4c76
I (5618) wifi:config NVS flash: enabled
I (5618) wifi:config nano formating: disabled
I (5628) wifi:Init dynamic tx buffer num: 32
I (5628) wifi:Init data frame dynamic rx buffer num: 32
I (5628) wifi:Init management frame dynamic rx buffer num: 32
I (5638) wifi:Init management short buffer num: 32
I (5638) wifi:Init static tx buffer num: 16
I (5648) wifi:Init static rx buffer size: 1600
I (5648) wifi:Init static rx buffer num: 10
I (5658) wifi:Init dynamic rx buffer num: 32
[0;33mW (5658) phy_init: failed to load RF calibration data (0x1102), falling back to full calibration[0m

Brownout detector was triggered

ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:4
load:0x3fff0034,len:7248
ho 0 tail 12 room 4
load:0x40078000,len:13856
load:0x40080400,len:4052
entry 0x40080688
[0;32mI (31) boot: ESP-IDF 3.40100.200827 2nd stage bootloader[0m
[0;32mI (31) boot: compile time 07:07:29[0m
[0;32mI (31) boot: chip revision: 1[0m
[0;32mI (34) boot_comm: chip revision: 1, min. bootloader chip revision: 0[0m
[0;32mI (41) boot.esp32: SPI Speed      : 40MHz[0m
[0;32mI (46) boot.esp32: SPI Mode       : DIO[0m
[0;32mI (51) boot.esp32: SPI Flash Size : 4MB[0m
[0;32mI (55) boot: Enabling RNG early entropy source...[0m
[0;32mI (61) boot: Partition Table:[0m
[0;32mI (64) boot: ## Label            Usage          Type ST Offset   Length[0m
[0;32mI (71) boot:  0 nvs              WiFi data        01 02 00009000 00004000[0m
[0;32mI (79) boot:  1 otadata          OTA data         01 00 0000d000 00002000[0m
[0;32mI (86) boot:  2 phy_init         RF data          01 01 0000f000 00001000[0m
[0;32mI (94) boot:  3 ota_0            OTA app          00 10 00010000 001db000[0m
[0;32mI (101) boot:  4 ota_1            OTA app          00 11 001f0000 001db000[0m
[0;32mI (109) boot: End of partition table[0m
[0;32mI (113) boot_comm: chip revision: 1, min. application chip revision: 0[0m
[0;32mI (120) esp_image: segment 0: paddr=0x00010020 vaddr=0x3f400020 size=0x50f90 (331664) map[0m
[0;32mI (273) esp_image: segment 1: paddr=0x00060fb8 vaddr=0x3ffb0000 size=0x05050 ( 20560) load[0m
[0;32mI (283) esp_image: segment 2: paddr=0x00066010 vaddr=0x40080000 size=0x00404 (  1028) load[0m
[0;32mI (284) esp_image: segment 3: paddr=0x0006641c vaddr=0x40080404 size=0x09bfc ( 39932) load[0m
[0;32mI (310) esp_image: segment 4: paddr=0x00070020 vaddr=0x400d0020 size=0x122edc (1191644) map[0m
[0;32mI (826) esp_image: segment 5: paddr=0x00192f04 vaddr=0x4008a000 size=0x12bb4 ( 76724) load[0m
[0;32mI (880) boot: Loaded app from partition at offset 0x10000[0m
[0;32mI (880) boot: Disabling RNG early entropy source...[0m
[0;32mI (881) psram: This chip is ESP32-D0WD[0m
[0;32mI (885) spiram: Found 64MBit SPI RAM device[0m
[0;32mI (890) spiram: SPI RAM mode: flash 40m sram 40m[0m
[0;32mI (895) spiram: PSRAM initialized, cache is in low/high (2-core) mode.[0m
[0;32mI (902) cpu_start: Pro cpu up.[0m
[0;32mI (906) cpu_start: Application information:[0m
[0;32mI (911) cpu_start: Project name:     esp32cam-server-only[0m
[0;32mI (917) cpu_start: App version:      0.0.9.3[0m
[0;32mI (922) cpu_start: Compile time:     Nov 16 2021 07:06:13[0m
[0;32mI (928) cpu_start: ELF file SHA256:  0dbda5e7af80986c...[0m
[0;32mI (934) cpu_start: ESP-IDF:          3.40100.200827[0m
[0;32mI (940) cpu_start: Starting app cpu, entry point is 0x40081b00[0m
[0;32mI (931) cpu_start: App cpu up.[0m
[0;32mI (1837) spiram: SPI SRAM memory test OK[0m
[0;32mI (1838) heap_init: Initializing. RAM available for dynamic allocation:[0m
[0;32mI (1838) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM[0m
[0;32mI (1844) heap_init: At 3FFC2A10 len 0001D5F0 (117 KiB): DRAM[0m
[0;32mI (1851) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM[0m
[0;32mI (1857) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM[0m
[0;32mI (1864) heap_init: At 4009CBB4 len 0000344C (13 KiB): IRAM[0m
[0;32mI (1870) cpu_start: Pro cpu start user code[0m
[0;32mI (1875) spiram: Adding pool of 4096K of external SPI memory to heap allocator[0m
[0;32mI (1900) spi_flash: detected chip: generic[0m
[0;32mI (1901) spi_flash: flash io: dio[0m
[0;32mI (1901) cpu_start: Starting scheduler on PRO CPU.[0m
[0;32mI (0) cpu_start: Starting scheduler on APP CPU.[0m
[0;32mI (1909) spiram: Reserving pool of 32K of internal memory for DMA/internal allocations[0m
Do Reset Camera
[0;32mI (1919) gpio: GPIO[32]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 [0m
Init Camera
[0;32mI (3929) gpio: GPIO[5]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
[0;32mI (3929) gpio: GPIO[18]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
[0;32mI (3929) gpio: GPIO[19]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
[0;32mI (3939) gpio: GPIO[21]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
[0;32mI (3949) gpio: GPIO[22]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
[0;32mI (3959) gpio: GPIO[23]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
[0;32mI (3969) gpio: GPIO[25]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
[0;32mI (3979) gpio: GPIO[34]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
[0;32mI (3989) gpio: GPIO[35]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
[0;32mI (3999) gpio: GPIO[36]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
[0;32mI (4009) gpio: GPIO[39]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
[0;32mI (4019) sccb: pin_sda 26 pin_scl 27
[0m
[0;32mI (4019) gpio: GPIO[32]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 [0m
[0;32mI (4169) camera: Detected OV2640 camera[0m
[0;32mI (4179) camera: Allocating 1 frame buffers (150 KB total)[0m
[0;32mI (4189) camera: Allocating 150 KB frame buffer in OnBoard RAM[0m
[0;32mI (4779) main: Using SDMMC peripheral[0m
Name: SD32G
Type: SDHC/SDXC
Speed: 20 MHz
Size: 29844MB
[0;32mI (4829) server_ota: Start CheckOTAUpdateCheck ...[0m
Start CheckOTAUpdateCheck ...
[0;32mI (4839) server_ota: SHA-256 for the partition table: : 9d4a2809ae90fb20709a8ca3dd3ac3462e1e73286bcd31b689060c91de06fa3a[0m
[0;32mI (4899) server_ota: SHA-256 for bootloader: : 2f4c792de3ca36713d14c6b1e98c2601ad2b22206ee169706b4dcf9e39c7c421[0m
[0;32mI (5539) server_ota: SHA-256 for current firmware: : fd924f0025e85034e06f0e4e65c62dd323f6af611ccfc42f24d89530b300852d[0m
CheckOTAUpdate Partition: ESP_OK
open file /sdcard/wlan.ini in mode r
file loaded

WLan: 5G-Gateway-FB99, my_password
Hostename: WaterMeter
I (5589) wifi:wifi driver task: 3ffd9cb4, prio:23, stack:6656, core=0
[0;32mI (5589) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE[0m
[0;32mI (5589) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE[0m
I (5619) wifi:wifi firmware version: 3ea4c76
I (5619) wifi:config NVS flash: enabled
I (5619) wifi:config nano formating: disabled
I (5619) wifi:Init dynamic tx buffer num: 32
I (5629) wifi:Init data frame dynamic rx buffer num: 32
I (5629) wifi:Init management frame dynamic rx buffer num: 32
I (5639) wifi:Init management short buffer num: 32
I (5639) wifi:Init static tx buffer num: 16
I (5649) wifi:Init static rx buffer size: 1600
I (5649) wifi:Init static rx buffer num: 10
I (5659) wifi:Init dynamic rx buffer num: 32
[0;33mW (5659) phy_init: failed to load RF calibration data (0x1102), falling back to full calibration[0m

Brownout detector was triggered

....

**Comment by jjude1966** [comment]
I read another forum and this seems to be to blame!

Restarts during full RF calibration are almost always due to power stability (or power supply capacitance) problems.

ESP-WROOM32 modules are not made to be used standalone. They are designed to be integrated on a PCB with an adequate 3.3V supply on the board and at least 10uF + 0.1uF (or more) capacitors on the power input.

If you're using the ESP-WROOM32 module standalone, you'll need to work out how to achieve this (shorter/thicker power leads, soldering low ESR high value capacitors to the power pins on the module).

If this module is on a PCB design, revise the PCB design based on the schematic shown in the ESP-WROOM32 datasheet "Peripheral Schematics" section (and/or by reviewing Espressif's development board designs).

**Comment by aiditz** [comment]
I just ran into the same issue powering a ESP32-CAM from a usb-ttl adapter.

After switching power to a power bank, the problem is gone. Thanks @jjude1966 for the advice.

**Comment by jomjol** [comment]
Okay - thanks for the update
