### ISSUE TITLE
Read from LCD?

### ISSUE THREAD

**Issue by sirtet** [jomjol/AI-on-the-edge-device#407]
I wonder if this would work to read something different:
To read numbers off an lcd screen like so:
![20211119_042358](https://user-images.githubusercontent.com/3509308/142560709-420e2d98-1b3c-461d-94d6-9b52705a6ee8.jpg)
It is a medical device, would need the two big numbers only...
Disregarding the Bad quality Sample image, i think it should work. Or am I overseeing some show stopper?

**Comment by jomjol** [comment]
Hi,
FIRST: you must never use this device for a live safing device. Neither the ESP32 is a stable and 100% reliable fail save device, nor the software is written in a fail safe way. CNN-networks can produce unreliable numbers at any time.

Second: this sounds like a commercial application. The code is not license free for this. Please contact me directly to discuss a commercial licence.

Saying this in advance, you are right, the algorithm and the device is in principle capable to digitize any number on a device. For a new set of numbers a dedicated new neural network is necessyry

Best regards,
  jomjol

**Comment by sirtet** [comment]
Sure, i get all your points and agree.
No, it's not a commercial thing at all.
How can i contact you directly? (easy to find me...)

**Comment by jomjol** [comment]
You can send me an email to: 
![grafik](https://user-images.githubusercontent.com/30766535/142671990-b05cfa18-9d2c-4ed3-a745-2c5185eec94a.png)
