### ISSUE TITLE
Javascript errors on setup pages

### ISSUE THREAD

**Issue by jensb** [jomjol/AI-on-the-edge-device#410]
This is a really cool evaluation of the original water-meter system. I was looking forward to trying it out, and flashing and Wifi connection worked without a flaw.
However, when I get to page two of the setup process, no image is shown. The browser console tells me this:

```
readconfigparam.js:14 Uncaught TypeError: Cannot read property 'split' of undefined
    at ParseConfig (readconfigparam.js:14)
    at init (edit_reference.html:275)
    at edit_reference.html:450
ParseConfig @ readconfigparam.js:14
init @ edit_reference.html:275
(anonymous) @ edit_reference.html:450
edit_reference.html:130 Uncaught TypeError: Cannot read property 'Alignment' of undefined
    at loadRawImage (edit_reference.html:130)
    at HTMLInputElement.onclick (edit_reference.html:42)
loadRawImage @ edit_reference.html:130
onclick @ edit_reference.html:42 
```

This happens both on Chromium and Brave (Firefox based) browsers. 

No image is shown and I cannot take one.

Any ideas what causes this?

**Comment by jackyyc** [comment]
I also encountered the same mistake as you.

**Comment by jensb** [comment]
I managed to avoid these errors by patching html/readconfigcommon.js, but the base problem is that I can only reach my ESP32 via a SSH tunnel (different Wifi network) and the setup constructs absolute URLs with the "real" IP of the ESP.

Can we have relative URLs please?

**Comment by jomjol** [comment]
Can send me the patch, than I will merge it into the code. 

Regarding the absolute URLs. I agree, that the html code is not very good. But honestly, 
1) html is not my core competence and I'm happy, that it is working as it is.
2) I don't have ressources and time to work onthis. Currently I'm the only one who is actively developing this.

So I'm absolutly happy for any support and will merge any improvements as soon as possible :-) .
Looking forward to your patch.

Best regards,
   jomjol

**Comment by jensb** [comment]
This gets the setup procedure running without JS errors even when using a SSH tunnel to access the ESP32:
(My smart devices use their own Wifi provided by a Raspberry Pi to separate them from the home Wifi and also provide better signal coverage also in the basement. Thus I need a SSH tunnel.)

It assumes your local test system at 192.168.178.79 is accessed using port 80.  If the port is different to 80, the code now assumes that a tunnel is being used and creates basepaths with correct hostname and port.

Since your project currently has no licence: this patch is hereby placed in the public domain. 

```
diff --git a/sd-card/html/gethost.js b/sd-card/html/gethost.js
index e9f056e..5824555 100644
--- a/sd-card/html/gethost.js
+++ b/sd-card/html/gethost.js
@@ -5,7 +5,8 @@ function gethost_Version(){
 
 function getbasepath(){
     var host = window.location.hostname;
-    if ((host == "127.0.0.1") || (host == "localhost") || (host == ""))
+    if( ((host == "127.0.0.1") || (host == "localhost") || (host == "")) 
+     && ((window.location.port == "80") || (window.location.port == "")))
     {
 //        host = "http://192.168.2.219";          // jomjol interner test
 //        host = "http://192.168.178.46";          // jomjol interner test
@@ -18,6 +19,9 @@ function getbasepath(){
     {
         host = "http://" + host;
     }
+    if(window.location.port != "") {
+       host = host + ":" + window.location.port;
+    }
     return host;
 }
 
diff --git a/sd-card/html/readconfigparam.js b/sd-card/html/readconfigparam.js
index 68f7c5c..1c2f5c6 100644
--- a/sd-card/html/readconfigparam.js
+++ b/sd-card/html/readconfigparam.js
@@ -2,9 +2,9 @@ function readconfig_Version(){
      return "1.0.0 - 20200910";
  }
 
-var config_gesamt;
-var config_split;
-var param;
+var config_gesamt = "";
+var config_split = [];
+var param = [];
 var category;
 var ref = new Array(2);
 var NUMBERS = new Array(0);
```

**Comment by jomjol** [comment]
Thanks a lot I will update the rolling in the next run.

**Comment by jomjol** [comment]
Implemented
