### ISSUE TITLE
ROI Not Updating correctly

### ISSUE THREAD

**Issue by toben1997** [jomjol/AI-on-the-edge-device#411]
I changed the position of the camera and updated the alignment marks ant the ROI, it's showing the updated regions but doesn't take the correct  photos what can i do to fix this? 

![firefox_tnUSRKDF6G](https://user-images.githubusercontent.com/23506168/142727470-05cdfbcb-7688-4d27-9dc9-08a94e43ee2b.png)
![firefox_f04dcdjv86](https://user-images.githubusercontent.com/23506168/142727474-dbc8c854-acca-482b-8c26-2896fbe76231.png)

**Comment by jomjol** [comment]
I only see one red box. Where is your second alignment mark?

**Comment by toben1997** [comment]
it was outside the screenshot frame but i fix it my  alignment marks I chose weren't good
