### ISSUE TITLE
Infinite reboot

### ISSUE THREAD

**Issue by jackyyc** [jomjol/AI-on-the-edge-device#414]
After I flash the firmware, I also encountered the problem of unlimited reboot 
Error log：Image loaded from memory: 0, 0, 0

But I don't think it's a hardware problem，Because other firmware can display the Image normally。
I guess it's a pin definition problem
my board is ESP32CAM_AITHINKER,   I don't know your  firmware use which pin definition?
can you build a firmware use  ESP32CAM_AITHINKER pin definition?

**Comment by LacerDomotique** [comment]
Hello,
I received a third esp32-cam which is an ESP32-D0WD-V3 (PSRAM) and the PSRAM is ESP PSRAM16H and I have the same problem as vitalyu: (device is rebooting after fiew seconds after boot up #403) when the led lights up I can go on the first page only and the esp restarts
I tried with three cameras and two sd-cards and versions 9.1.1 and 8.0.0 and there is the same error message.
With version 5.0.0 the esp starts well and I can take a picture.

File requested: /sdcard/html/cnn_images.jpg
open config file /sdcard/html/cnn_images.jpg in mode r
[0;32mI (23656) serverhelp: Sending file : /sdcard/html/cnn_images.jpg ...[0m
[0;32mI (23746) serverhelp: File sending complete[0m
Image loaded from memory: 0, 0, 0
Guru Meditation Error: Core  0 panic'ed (LoadProhibited). Exception was unhandled.
Core 0 register dump:
PC      : 0x400eede0  PS      : 0x00060630  A0      : 0x8018e33e  A1      : 0x3fffa000  
A2      : 0x00000780  A3      : 0x3ffc3c30  A4      : 0x00000280  A5      : 0x00000780  
A6      : 0x00000001  A7      : 0x000001e0  A8      : 0x00000000  A9      : 0x3f82c168  
A10     : 0x00000000  A11     : 0x3fffa388  A12     : 0x00003c24  A13     : 0x00000001  
A14     : 0x3ffc3574  A15     : 0x3fff9f20  SAR     : 0x0000001e  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x00000000  LBEG    : 0x4008bc9d  LEND    : 0x4008bcad  LCOUNT  : 0xffffffff  

ELF file SHA256: 5975f7b813691986

Backtrace: 0x400eeddd:0x3fffa000 0x4018e33b:0x3fffa070 0x4018e3c2:0x3fffa0b0 0x40189e99:0x3fffa140 0x400f1006:0x3fffa1c0

Rebooting...

**Comment by jomjol** [comment]
Which camera module are you using? At some version I focused on the OV2640 and removed all other modules, because the firmware was getting too big for the firmware at that time

**Comment by LacerDomotique** [comment]
I use OV2640
No problem with version 5.0.0, I can do all the initialisation procedure and take images

**Comment by jomjol** [comment]
And which board? ESP32CAM?

If so, I'm running out of ideas.

**Comment by jackyyc** [comment]
> Which camera module are you using? At some version I focused on the OV2640 and removed all other modules, because the firmware was getting too big for the firmware at that time

esp32-cam with OV2640

**Comment by LacerDomotique** [comment]
> And which board? ESP32CAM?
> 
> If so, I'm running out of ideas.

Yes, it's an esp32-cam (ESP32-D0WD-V3)

If it's work with version 5.0.0, something has changed after that

I have read that the error LoadProhibited means that the cpu tried to load a variable from an illegal address

But I am not a programmer and I don't know what to do with that

**Comment by LacerDomotique** [comment]
> > Which camera module are you using? At some version I focused on the OV2640 and removed all other modules, because the firmware was getting too big for the firmware at that time
> 
> esp32-cam with OV2640

Have you tried version 5.0.0 ?

**Comment by jackyyc** [comment]
> > > Which camera module are you using? At some version I focused on the OV2640 and removed all other modules, because the firmware was getting too big for the firmware at that time
> > 
> > 
> > esp32-cam with OV2640
> 
> Jackyyc, Have you tried version 5.0.0 ?

I try it . It's wokr.

**Comment by LacerDomotique** [comment]
> > > > Which camera module are you using? At some version I focused on the OV2640 and removed all other modules, because the firmware was getting too big for the firmware at that time
> > > 
> > > 
> > > esp32-cam with OV2640
> > 
> > 
> > Jackyyc, Have you tried version 5.0.0 ?
> 
> I try it . It's wokr.

And are you able to solve the problem ? I am not

**Comment by jackyyc** [comment]
> 

It can boot normally, take photos and set configuration。But it doesn't work。。no images show in overview.

**Comment by friedpa** [comment]
How long did you wait? The first picture and the value can take up to 3 minutes to appear.

**Comment by LacerDomotique** [comment]
If I check "LogimageLocation" they are stored in /log/source immediately but never in overview

**Comment by jomjol** [comment]
Can you send a log file of the serial from booting until the failure happens? 
I have no idea, what is going wrong. In general: if you load a image with zero size, the rest of the code will fail, because at some point it will try to read a not defined pointer, as images with size zero are not checked for.

**Comment by LacerDomotique** [comment]
here it is, I don't know how to load the file
It's with version 9.1.1
With version 5.0.0 there is no file called "reference.jpg" in the log

ets Jul 29 2019 12:21:46

rst:0x1 (POWERON_RESET),boot:0x12 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:4
load:0x3fff0034,len:7248
ho 0 tail 12 room 4
load:0x40078000,len:13856
load:0x40080400,len:4052
entry 0x40080688
[0;32mI (31) boot: ESP-IDF 3.40100.200827 2nd stage bootloader[0m
[0;32mI (31) boot: compile time 07:07:29[0m
[0;32mI (31) boot: chip revision: 3[0m
[0;32mI (35) boot_comm: chip revision: 3, min. bootloader chip revision: 0[0m
[0;32mI (42) boot.esp32: SPI Speed      : 40MHz[0m
[0;32mI (46) boot.esp32: SPI Mode       : DIO[0m
[0;32mI (51) boot.esp32: SPI Flash Size : 4MB[0m
[0;32mI (55) boot: Enabling RNG early entropy source...[0m
[0;32mI (61) boot: Partition Table:[0m
[0;32mI (64) boot: ## Label            Usage          Type ST Offset   Length[0m
[0;32mI (72) boot:  0 nvs              WiFi data        01 02 00009000 00004000[0m
[0;32mI (79) boot:  1 otadata          OTA data         01 00 0000d000 00002000[0m
[0;32mI (87) boot:  2 phy_init         RF data          01 01 0000f000 00001000[0m
[0;32mI (94) boot:  3 ota_0            OTA app          00 10 00010000 001db000[0m
[0;32mI (102) boot:  4 ota_1            OTA app          00 11 001f0000 001db000[0m
[0;32mI (109) boot: End of partition table[0m
[0;32mI (113) boot_comm: chip revision: 3, min. application chip revision: 0[0m
[0;32mI (121) esp_image: segment 0: paddr=0x00010020 vaddr=0x3f400020 size=0x50f90 (331664) map[0m
[0;32mI (273) esp_image: segment 1: paddr=0x00060fb8 vaddr=0x3ffb0000 size=0x05050 ( 20560) load[0m
[0;32mI (283) esp_image: segment 2: paddr=0x00066010 vaddr=0x40080000 size=0x00404 (  1028) load[0m
[0;32mI (284) esp_image: segment 3: paddr=0x0006641c vaddr=0x40080404 size=0x09bfc ( 39932) load[0m
[0;32mI (310) esp_image: segment 4: paddr=0x00070020 vaddr=0x400d0020 size=0x122edc (1191644) map[0m
[0;32mI (826) esp_image: segment 5: paddr=0x00192f04 vaddr=0x4008a000 size=0x12bb4 ( 76724) load[0m
[0;32mI (881) boot: Loaded app from partition at offset 0x10000[0m
[0;32mI (881) boot: Disabling RNG early entropy source...[0m
[0;32mI (881) psram: This chip is ESP32-D0WD[0m
[0;32mI (886) spiram: Found 16MBit SPI RAM device[0m
[0;32mI (890) spiram: SPI RAM mode: flash 40m sram 40m[0m
[0;32mI (895) spiram: PSRAM initialized, cache is in low/high (2-core) mode.[0m
[0;32mI (903) cpu_start: Pro cpu up.[0m
[0;32mI (906) cpu_start: Application information:[0m
[0;32mI (911) cpu_start: Project name:     esp32cam-server-only[0m
[0;32mI (917) cpu_start: App version:      0.0.9.3[0m
[0;32mI (922) cpu_start: Compile time:     Nov 16 2021 07:06:13[0m
[0;32mI (928) cpu_start: ELF file SHA256:  0dbda5e7af80986c...[0m
[0;32mI (934) cpu_start: ESP-IDF:          3.40100.200827[0m
[0;32mI (940) cpu_start: Starting app cpu, entry point is 0x40081b00[0m
[0;32mI (0) cpu_start: App cpu up.[0m
[0;32mI (1397) spiram: SPI SRAM memory test OK[0m
[0;32mI (1397) heap_init: Initializing. RAM available for dynamic allocation:[0m
[0;32mI (1398) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM[0m
[0;32mI (1404) heap_init: At 3FFC2A10 len 0001D5F0 (117 KiB): DRAM[0m
[0;32mI (1410) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM[0m
[0;32mI (1416) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM[0m
[0;32mI (1423) heap_init: At 4009CBB4 len 0000344C (13 KiB): IRAM[0m
[0;32mI (1429) cpu_start: Pro cpu start user code[0m
[0;32mI (1434) spiram: Adding pool of 2048K of external SPI memory to heap allocator[0m
[0;32mI (1459) spi_flash: detected chip: generic[0m
[0;32mI (1460) spi_flash: flash io: dio[0m
[0;32mI (1460) cpu_start: Starting scheduler on PRO CPU.[0m
[0;32mI (0) cpu_start: Starting scheduler on APP CPU.[0m
[0;32mI (1468) spiram: Reserving pool of 32K of internal memory for DMA/internal allocations[0m
Do Reset Camera
[0;32mI (1478) gpio: GPIO[32]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 [0m
Init Camera
[0;32mI (3488) gpio: GPIO[5]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
[0;32mI (3488) gpio: GPIO[18]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
[0;32mI (3488) gpio: GPIO[19]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
[0;32mI (3498) gpio: GPIO[21]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
[0;32mI (3508) gpio: GPIO[22]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
[0;32mI (3518) gpio: GPIO[23]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
[0;32mI (3528) gpio: GPIO[25]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
[0;32mI (3538) gpio: GPIO[34]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
[0;32mI (3548) gpio: GPIO[35]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
[0;32mI (3558) gpio: GPIO[36]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
[0;32mI (3568) gpio: GPIO[39]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
[0;32mI (3578) sccb: pin_sda 26 pin_scl 27
[0m
[0;32mI (3578) gpio: GPIO[32]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 [0m
[0;32mI (3728) camera: Detected OV2640 camera[0m
[0;32mI (3738) camera: Allocating 1 frame buffers (150 KB total)[0m
[0;32mI (3748) camera: Allocating 150 KB frame buffer in OnBoard RAM[0m
[0;32mI (4348) main: Using SDMMC peripheral[0m
Name: SD16G
Type: SDHC/SDXC
Speed: 20 MHz
Size: 14992MB
[0;32mI (4388) server_ota: Start CheckOTAUpdateCheck ...[0m
Start CheckOTAUpdateCheck ...
[0;32mI (4398) server_ota: SHA-256 for the partition table: : 9d4a2809ae90fb20709a8ca3dd3ac3462e1e73286bcd31b689060c91de06fa3a[0m
[0;32mI (4458) server_ota: SHA-256 for bootloader: : 2f4c792de3ca36713d14c6b1e98c2601ad2b22206ee169706b4dcf9e39c7c421[0m
[0;32mI (5098) server_ota: SHA-256 for current firmware: : fd924f0025e85034e06f0e4e65c62dd323f6af611ccfc42f24d89530b300852d[0m
CheckOTAUpdate Partition: ESP_OK
open file /sdcard/wlan.ini in mode r
file loaded

WLan: TP-LINK_CB6F04, 9876543210
Hostename: watermeter
I (5148) wifi:wifi driver task: 3ffd9ccc, prio:23, stack:6656, core=0
[0;32mI (5148) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE[0m
[0;32mI (5148) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE[0m
I (5178) wifi:wifi firmware version: 3ea4c76
I (5178) wifi:config NVS flash: enabled
I (5178) wifi:config nano formating: disabled
I (5178) wifi:Init dynamic tx buffer num: 32
I (5188) wifi:Init data frame dynamic rx buffer num: 32
I (5188) wifi:Init management frame dynamic rx buffer num: 32
I (5198) wifi:Init management short buffer num: 32
I (5198) wifi:Init static tx buffer num: 16
I (5208) wifi:Init static rx buffer size: 1600
I (5208) wifi:Init static rx buffer num: 10
I (5208) wifi:Init dynamic rx buffer num: 32
[0;32mI (5308) phy: phy_version: 4180, cb3948e, Sep 12 2019, 16:39:13, 0, 0[0m
I (5308) wifi:mode : sta (e0:e2:e6:aa:a3:58)
[0;32mI (5318) BLINK: Blinken - start[0m
[0;32mI (5318) wifi station: wifi_init_sta finished.[0m
I (5438) wifi:new:<10,2>, old:<1,0>, ap:<255,255>, sta:<10,2>, prof:1
I (5438) wifi:state: init -> auth (b0)
I (5458) wifi:state: auth -> assoc (0)
I (5478) wifi:state: assoc -> run (10)
[0;32mI (5518) BLINK: Blinken - done[0m
I (5588) wifi:connected with TP-LINK_CB6F04, aid = 8, channel 10, 40D, bssid = 50:c7:bf:b1:44:c1
I (5588) wifi:security: WPA2-PSK, phy: bgn, rssi: -47
I (5598) wifi:pm start, type: 1

I (5608) wifi:AP's beacon interval = 102400 us, DTIM period = 1
[0;32mI (8638) esp_netif_handlers: sta ip: 192.168.2.143, mask: 255.255.255.0, gw: 192.168.2.254[0m
[0;32mI (8638) wifi station: got ip:192.168.2.143[0m
[0;32mI (8638) BLINK: Blinken - start[0m
[0;32mI (8638) wifi station: connected to ap SSID:TP-LINK_CB6F04 password:xxxxx[0m
main: sleep for : 200ms
[0;32mI (10658) sntp: Time is not set yet. Connecting to WiFi and getting time over NTP.[0m
[0;32mI (10658) sntp: Initializing SNTP[0m
[0;32mI (10658) sntp: Waiting for system time to be set... (1/10)[0m
[0;32mI (12658) sntp: Waiting for system time to be set... (2/10)[0m
TimeZone set to CET-1CEST,M3.5.0,M10.5.0/3
Logfile opened: /sdcard/log/message/log_2021-11-21.txt
[0;32mI (14678) sntp: The current date/time in Berlin is: Sun Nov 21 17:35:42 2021[0m
[0;32mI (14678) sntp: The current date/time in Berlin is: 2021-11-21_17:35[0m
timeist 20211121-173542
Logfile opened: /sdcard/log/message/log_2021-11-21.txt
Logfile opened: /sdcard/log/message/log_2021-11-21.txt
Logfile opened: /sdcard/log/message/log_2021-11-21.txt
time 20211121-173542
main: sleep for : 200ms
[0;32mI (16718) server-main: Starting server on port: '80'[0m
[0;32mI (16718) server-main: Registering URI handlers[0m
[0;32mI (16718) server_tflite: server_part_camera - Registering URI handlers[0m
[0;32mI (16718) server_ota: server_ota - Registering URI handlers[0m
[0;32mI (16728) server_GPIO: start GpioHandler[0m
[0;32mI (16728) server_GPIO: register GPIO Uri[0m
[0;32mI (16738) server_GPIO: server_GPIO - Registering URI handlers[0m
vor reg server main
vor dotautostart
task_autodoFlow: start

open file /sdcard/config/config.ini in mode r
[MakeImage]
Start ReadParameter ([MakeImage]
)
;LogImageLocation = /log/source
WaitBeforeTakingPicture = 5
;LogfileRetentionInDays = 15
Brightness = -2
;Contrast = 0
;Saturation = 0
ImageQuality = 5
ImageSize = VGA
FixedExposure = false

[Alignment]
Start ReadParameter ([Alignment])
InitialRotate = 179
InitialMirror = false
SearchFieldX = 20
SearchFieldY = 20
AlignmentAlgo = Default
FlipImageSize = false
/config/ref0.jpg 103 271
/config/ref1.jpg 442 142

[Digits]
Start ReadParameter ([Digits])
Model = /config/dig1310s3q.tflite
;LogImageLocation = /log/digit
;LogfileRetentionInDays = 3
ModelInputSize = 20 32
main.dig1 294 126 30 54
GetGENERAL - GENERAL main - roi dig1
main.dig2 343 126 30 54
GetGENERAL - GENERAL main - roi dig2
main.dig3 391 126 30 54
GetGENERAL - GENERAL main - roi dig3

[Analog]
Start ReadParameter ([Analog])
Model = /config/ana0700s1lq.tflite
;LogImageLocation = /log/analog
;LogfileRetentionInDays = 3
ModelInputSize = 32 32
ExtendedResolution = true
main.ana1 432 230 92 92
GetGENERAL - GENERAL main - roi ana1
main.ana2 379 332 92 92
GetGENERAL - GENERAL main - roi ana2
main.ana3 283 374 92 92
GetGENERAL - GENERAL main - roi ana3
main.ana4 155 328 92 92
GetGENERAL - GENERAL main - roi ana4

[PostProcessing]
Start ReadParameter ([PostProcessing])
Anzahl NUMBERS: 1 - DIGITS: 1, ANALOG: 1
Number main, Anz DIG: 3, Anz ANA 4
main.DecimalShift = 0
PreValueUse = true
PreValueAgeStartup = 720
AllowNegativeRates = false
main.MaxRateValue = 0.1
ErrorMessage = true
CheckDigitIncreaseConsistency = true

;[MQTT]
Read Zeile Prevalue.ini: 2020-11-30_12-02-22
42.013401
TIME: 120, 10, 0, 1, 1, 5
Read: ;Uri = mqtt://IP-ADRESS:1883
Read: ;MainTopic = wasserzaehler
Read: ;ClientID = wasser
Read: ;user = USERNAME
Read: ;password = PASSWORD
Read: 
Read: ;[GPIO]
Read: ;MainTopicMQTT = wasserzaehler/GPIO
Read: ;IO0 = input disabled 10 false false 
Read: ;IO1 = input disabled 10 false false 
Read: ;IO3 = input disabled 10 false false 
Read: ;IO4 = built-in-led disabled 10 false false 
Read: ;IO12 = input-pullup disabled 10 false false 
Read: ;IO13 = input-pullup disabled 10 false false
Read: LEDType = WS2812
Read: LEDNumbers = 2
Read: LEDColor = 50 50 50 
Read: 
Read: [AutoTimer]
Start ReadParameter ([AutoTimer]
)
AutoStart = true
Intervall = 4.85

[Debug]
Start ReadParameter ([Debug])
Logfile = false
LogfileRetentionInDays = 3

[System]
Start ReadParameter ([System])
TimeZone = CET-1CEST,M3.5.0,M10.5.0/3
TimeZone set to CET-1CEST,M3.5.0,M10.5.0/3
;TimeServer = undefined
;AutoAdjustSummertime = false
;Hostname = undefined
SetupMode = true
END OF FILE
*************** Start GPIOHandler_Init *****************
[0;32mI (18588) server_GPIO: read GPIO config and init GPIO[0m
open file /sdcard/config/config.ini in mode r
[MakeImage]
;LogImageLocation = /log/source
WaitBeforeTakingPicture = 5
;LogfileRetentionInDays = 15
Brightness = -2
;Contrast = 0
;Saturation = 0
ImageQuality = 5
ImageSize = VGA
FixedExposure = false

[Alignment]
InitialRotate = 179
InitialMirror = false
SearchFieldX = 20
SearchFieldY = 20
AlignmentAlgo = Default
FlipImageSize = false
/config/ref0.jpg 103 271
/config/ref1.jpg 442 142

[Digits]
Model = /config/dig1310s3q.tflite
;LogImageLocation = /log/digit
;LogfileRetentionInDays = 3
[0;32mI (18648) BLINK: Blinken - done[0m
ModelInputSize = 20 32
main.dig1 294 126 30 54
main.dig2 343 126 30 54
main.dig3 391 126 30 54

[Analog]
Model = /config/ana0700s1lq.tflite
;LogImageLocation = /log/analog
;LogfileRetentionInDays = 3
ModelInputSize = 32 32
ExtendedResolution = true
main.ana1 432 230 92 92
main.ana2 379 332 92 92
main.ana3 283 374 92 92
main.ana4 155 328 92 92

[PostProcessing]
main.DecimalShift = 0
PreValueUse = true
PreValueAgeStartup = 720
AllowNegativeRates = false
main.MaxRateValue = 0.1
ErrorMessage = true
CheckDigitIncreaseConsistency = true

;[MQTT]
;Uri = mqtt://IP-ADRESS:1883
;MainTopic = wasserzaehler
;ClientID = wasser
;user = USERNAME
;password = PASSWORD

;[GPIO]
;MainTopicMQTT = wasserzaehler/GPIO
;IO0 = input disabled 10 false false 
;IO1 = input disabled 10 false false 
;IO3 = input disabled 10 false false 
;IO4 = built-in-led disabled 10 false false 
;IO12 = input-pullup disabled 10 false false 
;IO13 = input-pullup disabled 10 false false
LEDType = WS2812
LEDNumbers = 2
LEDColor = 50 50 50 

[AutoTimer]
AutoStart = true
Intervall = 4.85

[Debug]
Logfile = false
LogfileRetentionInDays = 3

[System]
TimeZone = CET-1CEST,M3.5.0,M10.5.0/3
;TimeServer = undefined
;AutoAdjustSummertime = false
;Hostname = undefined
SetupMode = true
[0;32mI (18758) server_GPIO: GPIO init comleted, handler is disabled[0m
Flashdauer: 5000
uri: /
1 uri: /, filename: , filepath: /sdcard
System ist im Setupmodus --> index.html --> setup.htmlFilename: 
File requested: /sdcard/html/setup.html
open file /sdcard/html/setup.html in mode r
[0;32mI (19768) serverhelp: Sending file : /sdcard/html/setup.html ...[0m
[0;32mI (19788) serverhelp: File sending complete[0m
uri: /edit_explain_0.html
1 uri: /edit_explain_0.html, filename: , filepath: /sdcard
Filename: 
File requested: /sdcard/html/edit_explain_0.html
open file /sdcard/html/edit_explain_0.html in mode r
[0;32mI (20068) serverhelp: Sending file : /sdcard/html/edit_explain_0.html ...[0m
[0;32mI (20078) serverhelp: File sending complete[0m
uri: /flow_overview.jpg
1 uri: /flow_overview.jpg, filename: , filepath: /sdcard
Filename: 
File requested: /sdcard/html/flow_overview.jpg
open file /sdcard/html/flow_overview.jpg in mode r
[0;32mI (20118) serverhelp: Sending file : /sdcard/html/flow_overview.jpg ...[0m
[0;33mW (20138) httpd_txrx: httpd_sock_err: error in send : 104[0m
[0;31mE (20138) serverhelp: File sending failed![0m
[0;33mW (20148) httpd_txrx: httpd_sock_err: error in send : 128[0m
[0;33mW (20148) httpd_txrx: httpd_resp_send_err: 500 Internal Server Error - Failed to send file[0m
[0;33mW (20158) httpd_txrx: httpd_resp_send_err: error calling setsockopt : 22[0m
[0;33mW (20168) httpd_txrx: httpd_sock_err: error in send : 128[0m
[0;33mW (20168) httpd_txrx: httpd_sock_err: error in send : 128[0m
[0;33mW (20178) httpd_uri: httpd_uri: uri handler execution failed[0m
uri: /cnn_images.jpg
1 uri: /cnn_images.jpg, filename: , filepath: /sdcard
Filename: 
File requested: /sdcard/html/cnn_images.jpg
open file /sdcard/html/cnn_images.jpg in mode r
[0;32mI (20198) serverhelp: Sending file : /sdcard/html/cnn_images.jpg ...[0m
[0;32mI (20298) serverhelp: File sending complete[0m
uri: /edit_reference.html
1 uri: /edit_reference.html, filename: , filepath: /sdcard
Filename: 
File requested: /sdcard/html/edit_reference.html
open file /sdcard/html/edit_reference.html in mode r
[0;32mI (23148) serverhelp: Sending file : /sdcard/html/edit_reference.html ...[0m
[0;32mI (23208) serverhelp: File sending complete[0m
uri: /explain_1.html
1 uri: /explain_1.html, filename: , filepath: /sdcard
Filename: 
File requested: /sdcard/html/explain_1.html
open file /sdcard/html/explain_1.html in mode r
[0;32mI (23218) serverhelp: Sending file : /sdcard/html/explain_1.html ...[0m
[0;32mI (23228) serverhelp: File sending complete[0m
uri: /gethost.js
1 uri: /gethost.js, filename: , filepath: /sdcard
Filename: 
File requested: /sdcard/html/gethost.js
open file /sdcard/html/gethost.js in mode r
[0;32mI (23288) serverhelp: Sending file : /sdcard/html/gethost.js ...[0m
[0;32mI (23298) serverhelp: File sending complete[0m
uri: /readconfigparam.js
1 uri: /readconfigparam.js, filename: , filepath: /sdcard
Filename: 
File requested: /sdcard/html/readconfigparam.js
open file /sdcard/html/readconfigparam.js in mode r
[0;32mI (23318) serverhelp: Sending file : /sdcard/html/readconfigparam.js ...[0m
[0;32mI (23398) serverhelp: File sending complete[0m
uri: /readconfigcommon.js
1 uri: /readconfigcommon.js, filename: , filepath: /sdcard
Filename: 
File requested: /sdcard/html/readconfigcommon.js
open file /sdcard/html/readconfigcommon.js in mode r
[0;32mI (23418) serverhelp: Sending file : /sdcard/html/readconfigcommon.js ...[0m
[0;32mI (23448) serverhelp: File sending complete[0m
uri: /fileserver/config/config.ini
uri: /fileserver/config/config.ini, filename: /config/config.ini, filepath: /sdcard/config/config.ini
open file /sdcard/config/config.ini in mode r
[0;32mI (23638) file_server: Sending file : /config/config.ini (1739 bytes)...[0m
[0;32mI (23648) file_server: File sending complete[0m
uri: /fileserver/config/reference.jpg?session=471754
uri: /fileserver/config/reference.jpg?session=471754, filename: /config/reference.jpg, filepath: /sdcard/config/reference.jpg
open file /sdcard/config/reference.jpg in mode r
[0;32mI (23868) file_server: Sending file : /config/reference.jpg (111087 bytes)...[0m
Image loaded from memory: 0, 0, 0
Guru Meditation Error: Core  0 panic'ed (LoadProhibited). Exception was unhandled.
Core 0 register dump:
PC      : 0x400ef224  PS      : 0x00060a30  A0      : 0x8018c502  A1      : 0x3fff9fd0  
A2      : 0x00000780  A3      : 0x3ffc3c70  A4      : 0x00000280  A5      : 0x00000780  
A6      : 0x00000001  A7      : 0x000001e0  A8      : 0x00000000  A9      : 0x3f82c168  
A10     : 0x00000000  A11     : 0x3f92ddd8  A12     : 0x0000a6d6  A13     : 0x00000001  
A14     : 0x3ffc35b4  A15     : 0x3fff9ef0  SAR     : 0x0000001e  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x00000000  LBEG    : 0x4008bed5  LEND    : 0x4008bee5  LCOUNT  : 0xffffffff  

ELF file SHA256: 0dbda5e7af80986c

Backtrace: 0x400ef221:0x3fff9fd0 0x4018c4ff:0x3fffa040 0x4018c586:0x3fffa080 0x40189cc1:0x3fffa110 0x400f12be:0x3fffa1c0

Rebooting...
ets Jul 29 2019 12:21:46

**Comment by LacerDomotique** [comment]
hello,
I just made an other test with again version 9.1.1 and here is the log file of a loop start

[Four boots.txt](https://github.com/jomjol/AI-on-the-edge-device/files/7588424/Four.boots.txt)

**Comment by friedpa** [comment]
Two lines are critical:
**Image loaded from memory: 0, 0, 0**     means no data could be loaded (no picture) -> ESP reboots
**Brownout detector was triggered**        The underlying reason could be one of many things: The USB cable is of poor quality, or too long. Your computer's USB port cannot supply enough power to the board (ESP. Camera, Flashlight,...). The ESP32Cam is defective, or the Camera is defect/ not mechanically right installed. 
My first guess is the Power Supply, the second one the Camera.

**Comment by LacerDomotique** [comment]
I have tested with three differents cameras, short usb cable , 2,1A power supply, two sd-cards, same problem with version 9.1.1 and 8.0.0

BUT it boots with version 5.0.0 then I can take images that are stored in /log/source but nothing in overview

**Comment by friedpa** [comment]
@jomjol In the log-file I found the below entries after a reset. I did not saw that ever before...can this point out a defect / not compatible SD-Card? Most of the reboots in the log-file are: Image loaded from memory: 0, 0, 0 (so no image was stored on the SD-Card)

File to upload: alg_roi.jpg
ClassFlowControll::GetJPGStream alg_roi.jpg
 Heap: 895512 Min Free: 885184 larg. Block:  860700 SPI Heap: 860700 NOT_SPI Heap: 34812 Internal Heap: 34812 Internal Min Heap free: 24484
Kein freier Speicher mehr!!!! Benötigt: 640 480 3 921600
Guru Meditation Error: Core  0 panic'ed (StoreProhibited). Exception was unhandled.

**Comment by jomjol** [comment]
@friedpa: when did that happen? After a fresh restart or quite some while?
The reason for something like this is a memory leakage due to some not freed memory. If this happens once a while, it is uncritical, because after a reboot the memory is clean again (freshly setup).
And yes you are right after version 5 I removed the image handling on the SD card and do most of it in the memory. This means using more RAM and be more sensitive to this problem.

@LacerDomotique: how big are your reference images and how many ROIs do you define. Maybe you are running out of memory for this reason?

**Comment by friedpa** [comment]
@jomjol I looked true the provided Log-File and found it right after a Reset (starting with: ets Jul 29 2019 12:21:46). Normal activities until the ESP wants to upload the File: _File to upload: alg_roi.jpg_
I still think of the SD-Card :o)

**Comment by jomjol** [comment]
@friedpa had a look in the wrong log file. Therefore I did not find it.

Anyway: in general the files like alg_roi.jpg, raw.jpg, ... which used to be stored in "/img_tmp" directory are now created directly out of the memory. That was the major change from version 5 to version 6.

For solving this problem, one would need to debug this dedicated setting directly. The behaviour is really strange and hard to debug remotely, unfortunately.

**Comment by LacerDomotique** [comment]
> @friedpa: when did that happen? After a fresh restart or quite some while? The reason for something like this is a memory leakage due to some not freed memory. If this happens once a while, it is uncritical, because after a reboot the memory is clean again (freshly setup). And yes you are right after version 5 I removed the image handling on the SD card and do most of it in the memory. This means using more RAM and be more sensitive to this problem.
> 
> @LacerDomotique: how big are your reference images and how many ROIs do you define. Maybe you are running out of memory for this reason?

After flashing (I erase before) with version 9.1.1 I power off the esp32-cam then power on and the log "four boots" is the loop start (just after the flashing, rebooting again and again). When the led goes on I can connect about 2 seconds so no time to do something.
I have tried two sd cards.

If It can boot with version 5.0.0 means there is no hardware problem , no ?

**Comment by jomjol** [comment]
Regarding hardware problem: yes or no? 
1. **no**: if version 5 is working, than the camera, wlan, sd-card etc. is obviously working
2. **yes**: you are the first and only, reporting that a change from version 5 to a higher version is not working anymore --> everywhere else this seems to be okay --> must be related to your system hardware or setting

One topic came into my mind: with change to verison 9: did you also made a clean update of the sd-card? There are some parameters in the config, that changed or have been added meanwhile. At that time it was downward compatible. But if you jump over several versions, that might get lost.

I would give it a last try: make a clean new installation: 
1) erase flash and reflash new
2) format sd-card and start from github v9.1.1

**Comment by LacerDomotique** [comment]
I did a complete format of the sd-card, erase and flash with version 9.1.1. Same problem
here is the log

[Boots after format.txt](https://github.com/jomjol/AI-on-the-edge-device/files/7589921/Boots.after.format.txt)

**Comment by jomjol** [comment]
Okay - bad news - than I'm out ?!? no more ideas currently

@all: any other user experiencing this effect?

**Comment by LacerDomotique** [comment]
Jackyyc who opened this issue has the same problem : ok with V5.0.0, but loop at boot with others versions
And Vitalyu issue#403

**Comment by friedpa** [comment]
If it is not the SD-Card, by the way I tried four different ones, I am also out (my SD-Card is a SanDisk Extreme 32GByte and the other one a SanDisk Ultra 32GByte)

**Comment by jomjol** [comment]
Looks likes 3 devices, that more than bad luck. 

But I would need one of these devices, otherwise I don't see a chance to solve this. I'm located in Germany, if there is interest I can offer to invest it by myself.

**Comment by jackyyc** [comment]
> hardware problem

I have good news for you。I solve the problemm。haha
This is the hardware problem。I buy other board from AI-thinker official store.
ererything is OK!  no more reboot!

**Comment by jomjol** [comment]
Good to hear after that "hard" discussion :-)

I close this issue then.
