### ISSUE TITLE
Frage zu Mqtt

### ISSUE THREAD

**Issue by toben1997** [jomjol/AI-on-the-edge-device#416]
Ich wollte mal fragen, wann der digitizer  sich sicher ist und Ergebnis über MQTT rausgibt? Und wie oft

**Comment by toben1997** [comment]
Das Problem ist das er seit gestern läuft und auch die richtigen werte anzeigen tut aber es nicht über MQTT ausgibt

**Comment by jomjol** [comment]
Er schickt bei jedem Durchgang einen Wert per MQTT, also ca. alle 5 Minuten. 
Wenn du noch immer keine Werte siehst, dann stimmt etwas mit den MQTT Einstellungen oder dem Server nicht.

**Comment by friedpa** [comment]
Wohin liefert der ESP32 die MQTT Werte? IOBroker?
Wenn ja: 
Config.ini:

![grafik](https://user-images.githubusercontent.com/42890695/142908378-3d8f127f-a173-408d-bff6-7b1768e63705.png)

Im Beispiel oben ist 192.168.10.16 meinIOBroker Server mit dem installierten Adapter MQTT Server&Client

**Comment by toben1997** [comment]
Danke alles gut ich war zum zweiten Mal doof hatte ein kommer anstatt eines Punktes in der ip adresse :D
