### ISSUE TITLE
Probleme mit Ziffer "9"

### ISSUE THREAD

**Issue by chindocaine** [jomjol/AI-on-the-edge-device#417]
Hallo jomjol,
erst mal ein großes Lob, das ist ein echt tolles Projekt. Mein Problem ist nur, ich versuche schon seit Tagen, die Erkennung der Ziffern richtig zum laufen zu bringen. Im großen und ganzen geht es auch nicht schlecht, nur die Ziffer "9" wird grundsätzlich als "0" erkannt!
![2021-11-22_18-50](https://user-images.githubusercontent.com/3941625/142911933-b3814d98-8f03-4cfa-acc5-baec5d70b4f9.png)
![2021-11-22_18-54](https://user-images.githubusercontent.com/3941625/142911976-0dcb179e-60c9-408d-bfce-3ae777c163f2.png)
Ich habe schon einige alte Issues gewälzt und alles Mögliche probiert (ROIs sind glaube ich so gut es geht definiert, andere Beleuchtung usw.) - aber die 9 ist und bleibt eine 0.
Mache ich noch irgendwas falsch? Muss hier die AI etwas "nachtrainiert" werden? Wenn ja, hast du eine Anleitung, wie man das machen kann, oder musst du das selbst machen?

Edit: Habe mal einige Ziffern gesammelt: [ziffern.zip](https://github.com/jomjol/AI-on-the-edge-device/files/7584765/ziffern.zip)

**Comment by toben1997** [comment]
+1
habe das auch.
und mit der 8 auch da meine 8 eine kerbe hat 
![chrome_SzhgxzHE98](https://user-images.githubusercontent.com/23506168/142918536-34440825-b762-4e23-bc68-12e5bed73f41.png)
![chrome_yD7le7oxEM](https://user-images.githubusercontent.com/23506168/142918597-b0482fa4-c288-42ff-9ac3-160117e30613.png)

**Comment by friedpa** [comment]
Meiner Meinung nach muss die 9 nachtrainiert werden, du solltest also 2-3 "9" an jomjol senden.

**Comment by jomjol** [comment]
Habe die Bilder aus dem Post 2 weiter oben in das Training aufgenommen.

**Comment by chindocaine** [comment]
Die aus dem ersten (meinem) Post auch? Hier noch mal ein Update, habe jetzt alle Ziffern aus meinem Zähler zusammen:
[ziffern.zip](https://github.com/jomjol/AI-on-the-edge-device/files/7586387/ziffern.zip)

**Comment by jomjol** [comment]
Habe die Ziffern aus deinem zip-File aufgenommen.

**Comment by toben1997** [comment]
danke

**Comment by toben1997** [comment]
gibt es eigentlich einen discord server von dir/diesem projekt?

**Comment by jomjol** [comment]
Was meinst du mit discord server?

**Comment by toben1997** [comment]
naja halt ne discord server so man channel hat für z.b. hilfe/support bei der einrichtung, chats oder channel für bilder zum lernen der Ai und sowas halt

**Comment by jomjol** [comment]
nein - gibt es nicht. Läuft alles hier über github und das wiki dort.

Das hier ist aber aktuell so ziemlich eine "one-man-show", was die Programmierung und Doku angeht.

**Comment by toben1997** [comment]
ahh oke schade

**Comment by jomjol** [comment]
Habe gerade ein neues tflite erzeugt: https://github.com/jomjol/AI-on-the-edge-device/blob/rolling/sd-card/config/dig1330s1q.tflite
