### ISSUE TITLE
"Previous Value" always shows actual "Value"

### ISSUE THREAD

**Issue by rupert-sch** [jomjol/AI-on-the-edge-device#418]
Even if "Value" changes due to consumption, "Previous Value" shows the actual, same as "Value". I would expect to see here the value from the previous detection cycle.
May depend on configuration, so here is mine:
![Bildschirmfoto_2021-11-22_19-21-03](https://user-images.githubusercontent.com/40740682/142914926-436c9fa6-2635-4417-9800-95b383853566.png)
Best regards, Rupert

**Comment by jomjol** [comment]
"Previous Value" has the meaning of the last "correct" read value. If the detection of the current value is okay, than this becomes also automatically the previous one. So they are identical.

The intention of "Previous Value" is to find misreadings and unlogig readings. 

But you are right, the naming might be a bit misleading. Could be a point for an update.
