### ISSUE TITLE
Idee ggf. zur optimirung des berechnungs ablauf? 

### ISSUE THREAD

**Issue by toben1997** [jomjol/AI-on-the-edge-device#419]
Ich nutze Digitizer noch nicht lange, ich nutze es mit Home Assistent und dem Energy Dashboard, da aber die Aktualisierungsrate von mindestens 3 Minuten recht langsam ist, hatte ich eine Idee wie man vielleicht die Aktualisierung rate flexibler machen könnte bzw. ggf. Rechenleistung sparen kann. 

Wen ich das richtig verstehe macht er ja jedes Mal wen er ein Foto macht eine Berechnung von jeder zahl die angegeben ist welches wahrscheinlich am meistens Rechenleistung braucht.

Die Idee: am Anfang der Einrichtung macht man ein gesamtes Foto liest das so wie jetzt aus und gibt eine zahl an z.b. 09085,8 darauf hin fragt man den User ist diese zahl richtig ausgelesen wurden und wen nicht ggf. anpassen lassen vom Nutzer, daraufhin man macht nur ein Foto und liest die letzten zahl aus in meinem fall die erste nachkommer stelle und das in einem recht kurzem Abstand und wen die zum Beispiel von 8 auf 9 wechselt das man dann nur die letzte zahl aktualisiert und bei jede volle Umdrehung von 9 auf 0 dann nur die letzten beiden zahlen in meinem fall z.b. 09086.0, das könnte allgemein Leistung sparen und es könnte meines Verständnisses nach auch Fehler einsparen  da er nicht ausversehen aus der ersten 9 eine 0 machen kann so lange nicht die vorherige zahl eine volle Umdrehung gemacht hat (so war das bei mir öfter dan hat er einen raw value von 00085,8 gehabt ) und wen das System feststellt das irgend etwas nicht stimmt mit den zahlen dann erst wider ein/mehrere Bild/er von der gesamten zahl machen und ggf. aufgetretenen Fehler zu korrigieren

**Comment by jomjol** [comment]
Sorry, dass ich so lange nicht geantwortet hatte.
Also deine Idee ist ein Hybrid aus inkrementellem und absolutem Zähler. Ich habe diese Version genau deswegen gemacht, da mein inkrementeller Zähler nicht genau genug funktioniert hat.
Dein Algorithmus könnte in der Tat etwas Zeit beim Digitalisieren der Ziffern sparen. Jedoch ist der größte Aufwand das Ausrichten des Bildes anhand der Alignmentmarken und das müsstest du weiterhin jedesmal machen (oder FastAlign verwenden).
Für eine auf Zeit, bzw. minimale Durchlaufzeit optimierte Variante wäre deine Idee sehr hilfreich. Ich beabsichte jedoch nicht in diese Richtung zu entwicklen, da selbst bei Doppelzählern eine Messung alle 2-3 Minuten möglich ist. Das reicht meines Erachtens aus.
Vielen Dank für deine Idee.
