### ISSUE TITLE
Falscher Value wird angezeigt

### ISSUE THREAD

**Issue by lexiz52** [jomjol/AI-on-the-edge-device#420]
Hi jomjol !

Ich nutze den AI zum Auslesen meines Gaszählers. Grundsätzlich funktioniert es auch gut, ich habe den Issue, das der Value sich ändert obwohl sich der Raw value sich nicht ändert. Der andere Issue ist das zwar der richtige Raw value gelesen wird, aber der value wird falsch angezeigt. Set Pre value wurde schon mehrfach gemacht. Es ist die aktuelle Version installiert.

Danke

![Watermeter](https://user-images.githubusercontent.com/61904155/143018622-45b83bb6-dca3-48ab-b65a-718e4015e93f.JPG)

**Comment by jomjol** [comment]
Vermutlich hast du ```CheckDigitIncreaseConsistency``` aktiviert. Bitte abschalten - das macht nur bei analogen Zählern oder sehr sehr langsam laufenden digitalen Zählern (letzte Stelle ändert sich maximal um 1) Sinn

**Comment by lexiz52** [comment]
Danke! CheckDigitIncreaseConsistency war aktiviert.
