### ISSUE TITLE
Web Url to read JSON readout 

### ISSUE THREAD

**Issue by jengstro2** [jomjol/AI-on-the-edge-device#421]
First of all SuperUber piece of software and idea!

I was looking for url that I can get JSON out of it, like this:
GET http://192.168.1.2/json
{
  "value": 1234.567,
  "previousvalue": 1234.566,
  "rawvalue": "123N.567",
  "error": "no error"
}

HTML scraping is not ideal solution.

**Comment by jengstro2** [comment]
Actually I snooped around... and found this inner url path how to get e.g. the "plain" value
http://192.168.1.86/wasserzaehler.html?all=true&type=value

Still JSON would be nice.

**Comment by jomjol** [comment]
direct json not implemented yet - should be done :-)

**Comment by jomjol** [comment]
Just have a look at the newest rolling version:
![grafik](https://user-images.githubusercontent.com/30766535/143186960-82186c43-b216-43fa-84cf-87622976a5e5.png)

**Comment by jengstro2** [comment]
That was quick 👍 , I would love to contribute, but don't really have (experience) all the compilers etc.  Anyway, I commented to commit/push. Anyway, JSON looks good. I missed timestamp, that is good to be in there.

**Comment by jomjol** [comment]
Implemented in v9.2.0
