### ISSUE TITLE
False recognition of 6 and 9 (sometimes 5)

### ISSUE THREAD

**Issue by beejayf** [jomjol/AI-on-the-edge-device#423]
Hello,

1st off: Thanks a lot for your work on this project - it is amazing how far you habe come!

I'm using this to setup to read my gas meter but I have constant problems with the digits 9 and 6 (sometimes 5 and even 8) being recognized as zero. (I'll try to attache a screenshot)

I optimized the lightting, focus and tried larger and smaller recangles around the digits - with not a lot of success.

Can you please advise me how to procede? If I can provide anything to get the project ahead, please let me know! 

Thanks in advance

![GasZaehler](https://user-images.githubusercontent.com/10280921/143251144-d17a7dae-57f4-4d97-84f3-faa117f81637.png)
!

**Comment by jomjol** [comment]
1) It looks like your ROIs are a bit large. The inner rectangle should fit tight around the number itself like this (number 3):
![grafik](https://user-images.githubusercontent.com/30766535/143253429-cc301fc5-b127-47f7-a586-f86f95478a3f.png)

2) I just have released a new tflite with better and more images. You can switch to it by copying it into the config folder and update the name in the config.ini.
You find the new version here: https://github.com/jomjol/AI-on-the-edge-device/blob/rolling/sd-card/config/dig1330s1q.tflite

3) if all this does not help, I can incorporate your digits into the next training. Therefore I would need 2-3 images of each number 0, 1, ... 9 (not more!!!!)

**Comment by beejayf** [comment]
I updated the file and adjusted the area accordingly - but if I place the inside rectangle over the number as you mentioned the area gets larger not smaller:
![GasZaehlerROI](https://user-images.githubusercontent.com/10280921/143268273-92773521-c58e-47f0-98ca-609d46461e52.png)
Now there are no more 9es on the counter - I'll keep checking and start collecting images

**Comment by jomjol** [comment]
The setting i looking good. You could make the ROI 1-2 pixel narrower in x-direction, but that is fine tuning. If you still have problems, than collect immages in this setting and send 2-3 images per digit to me for training.

Meanwhile I close the issue to keep the overview. Please reopen, when you have further topics.

**Comment by beejayf** [comment]
Now I even have the digit 3 recognized as 0 - crazy!
I attached 3 images for each digit - selected from different positions - hope that works. Since I don't know too much about training image recognitions I need to ask: Would it be better to train on this set of numbers ONLY - or is it better to merge "my" numbers with existing ones? What would I need to produce training date for your project?
[digits_bj.zip](https://github.com/jomjol/AI-on-the-edge-device/files/7611913/digits_bj.zip)

**Comment by jomjol** [comment]
@beejyaf: the ROI is still not okay. Most of your images have no border around the image. It does not make sense to train them without this border, as my image augmentation does not work properly without.

**Comment by beejayf** [comment]
Okay - undestood! I got those manually from the rag images saved in the log - somehow the folder for automatic digit saving stays empty on my device. Hope I got this better, if not just lewt me know!
[Digits_BJ_another_try.zip](https://github.com/jomjol/AI-on-the-edge-device/files/7613526/Digits_BJ_another_try.zip)

**Comment by jomjol** [comment]
Okay, this is looking good - they will be in the next version (current: 13.3)

**Comment by beejayf** [comment]
Thanks a lot!!

**Comment by beejayf** [comment]
I am assuming I will find the update here

https://github.com/jomjol/AI-on-the-edge-device/tree/master/sd-card/config

right? Or was it part of the last firmware update? (in which case my nines are still recognized as "0" about 80% of the time) I improved the lighting, focus / distance and the ROIs with no improvement.

**Comment by jomjol** [comment]
You will find it there or in the original training post: https://github.com/jomjol/neural-network-digital-counter-readout

But I did not have an update yet.

**Comment by beejayf** [comment]
Just wanted to convey a very big THANK YOU!!! from my side - since I updated to dig-s2-q-20220104.tflite (Rolling 20220104) - the device is recognizing flawlessly - tracking gas consumption from a raspberry pi on a 5 minute basis along with temperatures inside/extermal! I'm looking forward on how this data will help to optimize my house and safe a couple % CO2 emissions! 

Great project, great support, 100% useful!

**Comment by jomjol** [comment]
@beejayf  Thanks a lot!
