### ISSUE TITLE
Continuation of issue #414

### ISSUE THREAD

**Issue by LacerDomotique** [jomjol/AI-on-the-edge-device#425]
Hello,
Sorry to open this issue further #414 but I don't agree with jackyyc who said it's an hardware problem. I rather  think it's something different between the differents PSRAM (Ipus, ap memory or esp)
Jackyyc what psram you had and what you have on the new esp32-cam ? And can you give the link where you bought the esp32-cam. My psram is ESP PSRAM16H
Jomjol, Vitalyu and Friedpa wich psram do you have ?

Jomjol, a big thank you for the time you spend to develop this program. I would like to help more but I don’t know how to program
I really want to do this project

**Comment by jackyyc** [comment]
Obviously, it's the problem of PSRAM. My three esp32-cam boards have three different PSRAM IC. The first one is a reading error, the second one can't drive PSRAM, and the third one finally work normally. When I come home from work, I will tell you the specific model of PSRAM which can be use. I live in China, and buying links should not help you.
here is https://h5.m.taobao.com/awp/core/detail.htm?id=573698917181&spm=a2141.7631671.content.1

**Comment by jomjol** [comment]
This is mine:
![grafik](https://user-images.githubusercontent.com/30766535/143388198-d1ef885e-8209-49c9-89c6-a06b4a199803.png)

**Comment by friedpa** [comment]
IPUS
IPS6404LSO
1823Y7GW

![grafik](https://user-images.githubusercontent.com/42890695/143393719-4d97920f-df1d-404f-a95a-30ba39f47b5b.png)

**Comment by LacerDomotique** [comment]
Hello,
My first two esp32-cam have IPUS IPS6404LSO and at boot up the message is : [esp32-hal-psram.c:30] psramInit(): PSRAM init failed! That's an hardware problem, but they work with tasmota which don't use psram.
The third one is from ESP
I would like to buy one with psram from AP MEMORY, but it seems very difficult to have one
It's the lottery. Jomjom where  did you find your esp ?
I founf the official store of ai-thinker but it's all in chinese

**Comment by jackyyc** [comment]
![90B652AC-6492-45E7-9FBD-F7243925A352](https://user-images.githubusercontent.com/93693056/143465598-fd07890e-812f-4c83-a8e1-81839f6be3fa.jpeg)
this is mine

**Comment by LacerDomotique** [comment]
And mine ESP PSRAM16H. The datasheet says Product density 16Mbit, this means 2MB ?
At startup in log file I have "[0;32mI (51) boot.esp32: SPI Flash Size : 4MB"
And "[0;32mI (886) spiram: Found 16MBit SPI RAM device"
And "[0;32mI (1434) spiram: Adding pool of 2048K of external SPI memory to heap allocator"
The description of the seller is "Built-in 520 KB SRAM, external 4M PSRAM"

The problem seems to be there, the psram is in fact only 2MB should be 4MB
Jomjol, I think that your program needs more than 2MB ?

So, I have to open dispute on aliexpress

![ESP PSRAM16H](https://user-images.githubusercontent.com/87008912/143479434-832f76af-754c-49b9-be11-4f9f13c94280.jpg)

**Comment by jomjol** [comment]
That makes sense. If the PSRAM is only 2MByte instead of 4MByte it will not work and have an out of memory at some time, therefore rebooting.

I'll close this issue therefore.
