### ISSUE TITLE
Bright RGB leds v9.1.1

### ISSUE THREAD

**Issue by kaciker** [jomjol/AI-on-the-edge-device#426]
Hello, I instaled 2 the external WS281B RGB leds and updated to V9.1.1.
I setuped in config 2 leds , and the code 255,255,255 to have the maximun brigh in withe color, but after restart and take pictures to setup the ALigment, the bright is too low. I used those WS281B to other projects with Wemos and ESP32 and the bright is high. There are any way to increase the light bright ? In courent situation the system don't reconize the digital numbers. Thanks for your help

**Comment by jomjol** [comment]
I never observed this problem. 3 problems I can think of:
1) Configuration problem - Can you post your config.ini?
2) Limited power supply, I know this problem from rather large number of LED (10+) in which the current is limited.
3) Problem in the firmware

**Comment by kaciker** [comment]
Dear jomjol, thanks for your quick reply, I really appreciate it.
I tested several power sources 5v, and the same result in all. I use this power suply for another ESP32 and WS281B in a 3Dprinted illuminated moon and leds light up strong.
Maybe solution is add another 2 or 4 leds?

This is the config.ini content.

[MakeImage]
;LogImageLocation = /log/source
WaitBeforeTakingPicture = 5
;LogfileRetentionInDays = 15
Brightness = -1
;Contrast = 0
;Saturation = 0
ImageQuality = 5
ImageSize = VGA
FixedExposure = true

[Alignment]
InitialRotate = 180
InitialMirror = true
SearchFieldX = 20
SearchFieldY = 20
AlignmentAlgo = highAccurity
FlipImageSize = false
/config/ref0.jpg 193 232
/config/ref1.jpg 291 209

[Digits]
Model = /config/dig1310s3q.tflite
;LogImageLocation = /log/digit
;LogfileRetentionInDays = 3
ModelInputSize = 20 32
gasmeter.Digi1 33 125 49 83
gasmeter.Digi2 92 125 48 81
gasmeter.Digi3 142 123 49 82
gasmeter.Digi4 192 122 50 85

;[Analog]
Model = /config/ana0700s1lq.tflite
;LogImageLocation = /log/analog
;LogfileRetentionInDays = 3
ModelInputSize = 32 32
gasmeter.ana1 147 325 101 101
gasmeter.ana2 379 332 92 92
gasmeter.ana3 283 374 92 92
gasmeter.ana4 155 328 92 92

[PostProcessing]
gasmeter.DecimalShift = 1
PreValueUse = true
PreValueAgeStartup = 720
AllowNegativeRates = false
gasmeter.MaxRateValue = 1
;gasmeter.ExtendedResolution = false
;gasmeter.IgnoreLeadingNaN = false
ErrorMessage = true
CheckDigitIncreaseConsistency = true

[MQTT]
Uri = mqtt://192.168.31.1:1883
MainTopic = Gas-meter
ClientID = kacwater
user = xxxxxxx
password =xxxxxxxxxxx

[GPIO]
;IO0 = input disabled 10 false false 
;IO1 = input disabled 10 false false 
;IO3 = input disabled 10 false false 
IO4 = built-in-led disabled 10 false false 
;IO12 = external-flash-ws281x disabled 10 false false 
;IO13 = input-pullup disabled 10 false false 
LEDType = WS2812B
LEDNumbers = 2
LEDColor = 255 255 255

[AutoTimer]
AutoStart = true
Intervall = 3

[Debug]
Logfile = false
LogfileRetentionInDays = 3

[System]
TimeZone = CET-1CEST,M3.5.0,M10.5.0/3
;TimeServer = undefined
;AutoAdjustSummertime = false
;Hostname = undefined
SetupMode = false

Attach two pictures, one with the inegrated led (gpio4 on, gpio12 off) and second with this unactive (gpio4 off gpio12 on
![2021-11-25_08h56_11](https://user-images.githubusercontent.com/7668181/
![2021-11-25_08h46_44](https://user-images.githubusercontent.com/7668181/143403102-86afb13b-f1f1-45dd-adff-93f45cb4c6ca.png)
143403084-00284d27-1d05-4738-bb53-d6a64f4de312.png)
)

**Comment by jomjol** [comment]
The config looks good for me. So no reason why it should not work. You could try to disable ```FixedExposure```, but I don't assume, that this changes the situation. 
Currntly no idea, why it is not working.

**Comment by kaciker** [comment]
FInally I installed 2 rgb more, and now is much better
![image](https://user-images.githubusercontent.com/7668181/143499150-f12d4089-2358-4209-9ccd-e379d6320407.png)

**Comment by friedpa** [comment]
Still wondering why your picture is so dull?
My Gasmeter:
![grafik](https://user-images.githubusercontent.com/42890695/143531741-38be882d-cb56-4c60-a902-92e225758ecb.png)

**Comment by jomjol** [comment]
For me it looks a little bit, like there is a film on the camera lens or some window.

**Comment by kaciker** [comment]
Hello, I'll change the lens shortly, I'm still doing tests for the moment. Maybe the distance between the lens and the meter is high. I'm using this version attacehd in the pic 

I constated that after few minutes whit the 4 leds RGB config, the system becomes inestable, and I need to comeback to 2 RGB to be able to take the control again, or restore de info in the card to start from scratch.
![IMG_4913](https://user-images.githubusercontent.com/7668181/143541653-bb570434-0640-4c3b-b09d-d330a60db917.jpg)

**Comment by jomjol** [comment]
You need to adjust the focus of the lens. The original focus length is too far.

**Comment by kaciker** [comment]
Hello, strange behavior, now with new ESP32 and new camera, the 4 leds are very brillant... and with only 2 and 100/100/100 is enaugh. The problem is that is not reconizing the numbers

![2021-11-29_10h45_16](https://user-images.githubusercontent.com/7668181/143846220-778b6606-10a9-4488-b672-2b9d159a0490.png)

There are some info to setup correctly the light to be able that the system reconize the numbers right ?

**Comment by jomjol** [comment]
Yes and you should make the ROIs as suggested (inner frame exantly around the number).

I will close this issue meanwhile. Please reopen in case of question ....
