### ISSUE TITLE
Wassermeter erkennt 0 statt 8

### ISSUE THREAD

**Issue by Skarhand** [jomjol/AI-on-the-edge-device#427]
Moin,
ich habe den Wassermeter jetzt seit zwei Wochen im Dauereinsatz und bin recht zufrieden. Bis jetzt hat er alles immer richtig erkannt. Allerdings ist meine Wasseruhr jetzt von 57m³ auf 58m³ umgesprungen und er gibt mir als Wert nur noch 50m³ raus. Habe den Wassermeter schon auf die neueste Version upgedatet und mehrfach neu gestartet. Immer das selbe Phänomen. Ich bin ratlos. Im analogen Bereich (bei den Drehrädchen) werden alle Zahlen problemlos erkannt.

MFG
Sebastian

**Comment by ideaweb** [comment]
Habe das gleiche Problem mit der "8". Auch bspw. "1.9xx" wird meist schon zu "2.9xx", wahrscheinlich weil die "1" schon zu weit "weggedreht" ist. Beide Probleme zusammen macht es manchmal fast unbrauchbar.

**Comment by jomjol** [comment]
Folgende Hinweise:
1. Prüft bitte die Einstellungen von ```CheckDigitIncreaseConsistency```. Das solltest ihr nur aktivieren, wenn ihr auch analoge Ziffern habt, ansonsten kann das zu solchen Fehlern führen
2. Wenn es an der Erkennung der Ziffern liegt, dann muss ich eure Ziffern mit ins Training aufnehmen --> Dazu bitte dann 2-3 Bilder von jeder Ziffer (nicht mehr!) raussuchen und mir dann schicken.

**Comment by Skarhand** [comment]
Moin, bei mir schein das Deaktivieren des Parameters was gebracht zu haben. Ich werde es weiter beobachten, und mich dann evl noch mal melden.
Dankeschön :-)

**Comment by ideaweb** [comment]
Bei mir auch. Seit mehren Tagen keine Probleme mehr. Ich werde das auch weiter beobachten. Danke für den Tipp!!
