### ISSUE TITLE
Send read value to Thinger.io dashboard

### ISSUE THREAD

**Issue by flaviopuhl** [jomjol/AI-on-the-edge-device#428]
Hi jomjol, amazing job!

I would like to branch you project and modify it to send the meter value to my dashboard on thinger.io.
I could not find where in the code I can find the value. Can you give a hint?

Thanks

**Comment by jomjol** [comment]
The postprocessing is done here:
https://github.com/jomjol/AI-on-the-edge-device/blob/master/code/components/jomjol_flowcontroll/ClassFlowPostProcessing.cpp

in the following functin - starting in line 559:

```bool ClassFlowPostProcessing::doFlow(string zwtime)```
