### ISSUE TITLE
einbinden NTP Server

### ISSUE THREAD

**Issue by MMeinhardt1** [jomjol/AI-on-the-edge-device#43]
Hi @jomjol,

bezugnehmend auf [diesen](https://forum.iobroker.net/topic/36622/wasserz%C3%A4hler-version-2-all-in-device/336) Thread eröffne ich diesen Issue.
Wie schon erwähnt erscheint es aus meiner Sicht durchaus sinnvoll einen NTP Server konfigurieren zu können, da der ESP innerhalb von 2 Wochen ohne Reboot seiner Zeit ca. 30 Minuten voraus ist (also die interne Uhr bzw. der interne Takt scheint schneller zu sein).
Ich denke das könnte die Fehlersuche im Fall des Falles auch einfacher gestalten.

Danke

**Comment by hike6688** [comment]
Hi @jomjol 
Die vorhandene sntp-Implementierung time_sntp.cpp macht bei mir Probleme:
Ich habe beobachtet, dass bei meinen Gaszaehler  bei einem reboot die Zeit **nicht** aktualisiert wird und somit immer weiter nach vorne driftet. 

Um das mitzukriegen, logge ich bein Start von main  den Status bei obtain_time()

> ====== Main started ======= 
Version Nov 16 2020 16:41:35
app_main after initSD-card  Free Heap Size: 4399816 Min Free Heap : 4398724 larg. Block :  4167332 SPI Heap: 4167332 Internal Min Heap free: 231392 larg. Block:  113804 Heap: 232484
app_main after checkOtaUpdate  Free Heap Size: 4399724 Min Free Heap : 4398132 larg. Block :  4167332 SPI Heap: 4167332 Internal Min Heap free: 230800 larg. Block:  113804 Heap: 232392
app_main after LoadWlanFromFile  Free Heap Size: 4399680 Min Free Heap : 4398032 larg. Block :  4167332 SPI Heap: 4167332 Internal Min Heap free: 230700 larg. Block:  113804 Heap: 232348
app_main after initialize wifi  Free Heap Size: 4332844 Min Free Heap : 4330304 larg. Block :  4167332 SPI Heap: 4167332 Internal Min Heap free: 162972 larg. Block:  113804 Heap: 165512
app_main before setup_time  Free Heap Size: 4332852 Min Free Heap : 4330304 larg. Block :  4167332 SPI Heap: 4167332 Internal Min Heap free: 162972 larg. Block:  113804 Heap: 165520
time_sntp::setup_time
Boot count: 1
time_sntp::obtain_time start: 
time_sntp::obtain_time: Waiting for system time to be set... (1/20)
time_sntp::obtain_time: Waiting for system time to be set... (2/20)
time_sntp::obtain_time: Waiting for system time to be set... (3/20)
time_sntp::obtain_time: Waiting for system time to be set... (4/20)
time_sntp::obtain_time: Waiting for system time to be set... (5/20)
time_sntp::obtain_time: Waiting for system time to be set... (6/20)
time_sntp::obtain_time: Waiting for system time to be set... (7/20)
time_sntp::obtain_time: Waiting for system time to be set... (8/20)
time_sntp::obtain_time: Waiting for system time to be set... (9/20)
time_sntp::obtain_time: Waiting for system time to be set... (10/20)
time_sntp::obtain_time: Waiting for system time to be set... (11/20)
time_sntp::obtain_time: Waiting for system time to be set... (12/20)
time_sntp::obtain_time: Waiting for system time to be set... (13/20)
time_sntp::obtain_time: Waiting for system time to be set... (14/20)
time_sntp::obtain_time: Waiting for system time to be set... (15/20)
time_sntp::obtain_time: Waiting for system time to be set... (16/20)
time_sntp::obtain_time: Waiting for system time to be set... (17/20)
time_sntp::obtain_time: Waiting for system time to be set... (18/20)
time_sntp::obtain_time: Waiting for system time to be set... (19/20)
2020-11-16_17-39-07: time_sntp::obtain_time status :SNTP_SYNC_STATUS_RESET count retries: 20
time_sntp::obtain_time end: 
2020-11-16_18:38
time_sntp::setup_time finished: time 20201116-183907
app_main after setup_time  Free Heap Size: 4332836 Min Free Heap : 4330304 larg. Block :  4167332 SPI Heap: 4167332 Internal Min Heap free: 162972 larg. Block:  113804 Heap: 165504
2020-11-16_18-39-07: Time is set
2020-11-16_18-39-07: app_main do InitCam   Free Heap Size: 4332692 Min Free Heap : 4330304 larg. Block :  4167332 SPI Heap: 4167332 Internal Min Heap free: 162972 larg. Block:  113804 Heap: 165360
2020-11-16_18-39-15: app_main InitCam done  Free Heap Size: 3315660 Min Free Heap : 3314040 larg. Block :  3207328 SPI Heap: 3207328 Internal Min Heap free: 106712 larg. Block:  75356 Heap: 108332
2020-11-16_18-39-17: app_main do start webserver   Free Heap Size: 3315636 Min Free Heap : 3313524 larg. Block :  3207328 SPI Heap: 3207328 Internal Min Heap free: 106196 larg. Block:  75356 Heap: 108308
2020-11-16_18-39-17: app_main  start webserver  done  Free Heap Size: 3284712 Min Free Heap : 3284680 larg. Block :  3207328 SPI Heap: 3207328 Internal Min Heap free: 77352 larg. Block:  64896 Heap: 77384
2020-11-16_18-39-17: app_main  TFliteDoAutoStart  done  Free Heap Size: 3235156 Min Free Heap : 3234452 larg. Block :  3207328 SPI Heap: 3207328 Internal Min Heap free: 27124 larg. Block:  15740 Heap: 27828

Ein parallel dazu laufender ESP8266, der die  Pulse vom Gaszaehler zählt, hat immer die richtige Zeit. Erst durch den Vergleich ist mit das Problem aufgefallen.

Das Problem tritt nur bei dem Production device auf, nicht beim Testdevice. 
Gruß Hike

**Comment by jomjol** [comment]
NTP-Server kann jetzt eingestellt werden
```
[System]
TimeZone = CET-1CEST,M3.5.0,M10.5.0/3
```
Automatischer Sync fehlt noch

**Comment by MMeinhardt1** [comment]
Das klingt doch gut, magst Du die Parameter noch erklären?

**Comment by jomjol** [comment]
Der Parameter ist der POSIX Timespamp Format: https://www.postgresql.org/docs/13/datetime-posix-timezone-specs.html
Automatischer Sync bedeutet, dass regelmäßig die Zeit mit dem dem Timeserver synchronisiert wird (z.B. alle 6 Stunden oder so).

**Comment by jomjol** [comment]
Habe mich gestern dem Problem angenommen. Der Timesync jede Stunde eine automatische Synchronisation, habe das heute Nacht mal testweise protokolliert und es passt.
Also schließe ich den Issue

**Comment by MMeinhardt1** [comment]
Hi @jomjol,
ich habe meinen ganzen IoT Geräten nun den direkten Zugriff aufs Internet untersagt, und was soll ich sagen jetzt funktioniert die Zeitsynchronisierung leider nicht mehr. Kannst Du die Konfig irgendwann mal dahingehend ändern das z.B. die FritzBox als Zeitserver eingetragen werden kann.

Vielen Dank

**Comment by jomjol** [comment]
Keine schlechte Idee, ich öffnene den Issue daher nochmal - damit es nicht vergessen wird

**Comment by MMeinhardt1** [comment]
Super, vielen Dank und jetzt aber erstmal schöne, ruhige und besinnliche Feiertage 🎄

**Comment by jomjol** [comment]
Ich habe eine erste Version implementiert, jedoch nicht in der normalen Rolling, sondern in https://github.com/jomjol/AI-on-the-edge-device/tree/rolling-reduce-sd-use
Da arbeite ich gerade an reduzierten Schreib-/Lesezugriffen auf die SD-Karte. Leider gibt es dort wieder vemehrt Restarts, aber grundsätzlich tut es schon - läuft bei mir jetzt seit einigen Tagen. Du kannst den Time Server im Config-File im Parameter `TimeServer` wie folgt einstellen:
```
[System]
TimeZone = CET-1CEST,M3.5.0,M10.5.0/3
TimeServer = fritz.box
```

P.S.: bei der Version musst du auch unbedingt die html Dateien austauschen.

**Comment by jomjol** [comment]
In der neuen Rolling implementiert.
