### ISSUE TITLE
 Continuation of issue #414 & #425 

### ISSUE THREAD

**Issue by amishv** [jomjol/AI-on-the-edge-device#430]
Continuation to the previous two issues, my chip is 64mbit IPS1704L.
It is detected as 64MBit; from the logs
[0;32mI (878) psram: This chip is ESP32-D0WD␛[0m
␛[0;32mI (883) spiram: Found 64MBit SPI RAM device␛[0m
␛[0;32mI (887) spiram: SPI RAM mode: flash 40m sram 40m␛[0m

I have uncommented the print messages in FindTemplate class.
Please find the logs below.  It  does not seems to be a low SRAM issue. The issues seems to be in the function
CalculateSimularities(rgb_template, _ref->fastalg_x, _ref->fastalg_y, ow, oh, min, avg, max, SAD, _ref->fastalg_SAD, _ref->fastalg_SAD_criteria);

Flashdauer: 0
Image loaded from memory: 640, 480, 3
Vor ft->FindTemplate(_temp1);  /sdcard/config/ref0.jpg
FindTemplate 01 size 
FindTemplate 02
Guru Meditation Error: Core  0 panic'ed (LoadProhibited). Exception was unhandled.
Core 0 register dump:
PC      : 0x40179de7  PS      : 0x00060830  A0      : 0x8017a050  A1      : 0x3fff9e70  
A2      : 0x3ffe3d34  A3      : 0x00000000  A4      : 0x00000000  A5      : 0x00000003  
A6      : 0x00000000  A7      : 0x00000001  A8      : 0x80661135  A9      : 0x3f82c168  
A10     : 0x0000000a  A11     : 0x3ffae948  A12     : 0x00000000  A13     : 0x3ffb0ec4  
A14     : 0x000000fe  A15     : 0x7275736f  SAR     : 0x0000001e  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x80661135  LBEG    : 0x4008bed5  LEND    : 0x4008bee5  LCOUNT  : 0xfffffffc  

ELF file SHA256: eff338e7a5506d99

Backtrace: 0x40179de4:0x3fff9e70 0x4017a04d:0x3fff9f00 0x40179a29:0x3fff9fb0 0x4019323a:0x3fffa030 0x40189f17:0x3fffa0c0 0x400f115d:0x3fffa170 0x400f13ef:0x3fffa1c0

Rebooting...

**Comment by jomjol** [comment]
As there is some memory leakage, which has not been found yet, from time to time a reboot can happen. It is getting more likely if you use a lot of memory by:
- using large reference images
- big images (big ROIs) or a large number of ROIs

Currently I'm not planning to work on this, because a direct debugging is not possible and the majority of the systems seems to be stable. I will put this issue in the long term topics and close the issue again.

Sorry for beeing so strickt, but I want to keep the overview over and therefore only keep issues open, that I will work on.

**Comment by amishv** [comment]
> As there is some memory leakage, which has not been found yet, from time to time a reboot can happen. It is getting more likely if you use a lot of memory by:
> 
>     * using large reference images
> 
>     * big images (big ROIs) or a large number of ROIs
> 
> 
> Currently I'm not planning to work on this, because a direct debugging is not possible and the majority of the systems seems to be stable. I will put this issue in the long term topics and close the issue again.
> 
> Sorry for beeing so strickt, but I want to keep the overview over and therefore only keep issues open, that I will work on.

I found that issue is only when we change the "AlignmentAlgo"  from  "default" to "fast" and probably  also in HighAccuracy. Not many running devices would have chaged that setting in the "expert mode"
