### ISSUE TITLE
Abweichung zwischen Raw Value und Value

### ISSUE THREAD

**Issue by SebastianGranzow** [jomjol/AI-on-the-edge-device#431]
Hallo,
ich habe ein Problem bei dem der Raw Value beim Auslesen korrekt erkannt wird, der veröffentlichte Value aber ein offset dazu aufweist. Dieser offset verändert sich auch. 
Der Offset bezieht sich lediglich auf die digitale Anzeige die analogen Anzeigen passen immer.
Ich würde mich über Hinweise oder Ratschläge sehr freuen

Vielen Dank

<img width="1009" alt="Bildschirmfoto 2021-11-28 um 10 08 26" src="https://user-images.githubusercontent.com/83725853/143745311-74348e69-5f22-44ef-8875-c67eb293d028.png">

**Comment by rupert-sch** [comment]
Hallo Sebastian, 

ob ein raw value zu value wird oder nicht, hängt von Deinen Einstellungen im PostProcessing ab. Ohne diese Info ist die Fehlersuche Stochern im Nebel.
Auch mir ist aufgefallen, dass sich value kontinuierlich "vorrobbt", obwohl kein Wasser verbraucht wurde (z.B. nachts). Das liegt daran, dass eigentlich identische Bilder zufällig zu unterschiedlichen raw values führen -- siehe mein Issue #429 . Seit ich AllowNegativeRates = true gesetzt habe, gibt es zwar gelegentlich negativen Verbrauch, aber über den Tag mittelt sich das aus. Und vor allem: Der Zählerstand läuft mir nicht davon.

Vielleicht helfen auch bei Dir "bessere" alignment regions, wie Paul im selben issue empfiehlt.

Gruß, Rupert

**Comment by SebastianGranzow** [comment]
Hallo Rupert,
habe die Hinweise mal angewendet. 
Mal schauen.

Danke

**Comment by jomjol** [comment]
Noch ein weiterer Hinweis: Ihr könnt auch noch ``CheckDigitIncreaseConsistency`` deaktivieren. Das kann auch zu einer Verschiebung führen.

Ansonsten würde ich den Issue erstmal schließen
