### ISSUE TITLE
Header fields are too long for server to interpret

### ISSUE THREAD

**Issue by jensb** [jomjol/AI-on-the-edge-device#432]
I am getting this error - I think this is because the hostname is shared (I forward the ESP32's IP to another network), and my browser sends a "Cookie" header which is quite long. Opening the ESP32 page in a private browsing session works.

Since the ESP32 doesn't use cookies (right?), can we just ignore such headers instead of failing the request?

![image](https://user-images.githubusercontent.com/44540/143763521-bf9de111-2221-4606-98ad-bb661a60027d.png)

**Comment by jomjol** [comment]
Hi, this is not a problem of cookies, but the header is longer, than the buffer in the ESP32 server, which is 1kbyte. 
If I increase this buffer, I remove the free memory for other variables and this is already at the limit (see reboot problems).
Therefore I'm not tending to change this. You could make a folk with a changes buffer (changed via menuconfig for the esp-idf).

**Comment by jensb** [comment]
OK, I understand.
Maybe it is possible instead to just crop headers which are too large, or ignore Cookie headers altogether. I'll try to find out.
