### ISSUE TITLE
Probleme mit Alignment Marks -> 0kb ref Dateien

### ISSUE THREAD

**Issue by Otti12345** [jomjol/AI-on-the-edge-device#433]
Hallo,
ich bekomme alles bis auf die Alignment Marks eingestellt.
Reference Image - Done & gespeichert
Ana & Dig ROI - Done & gespeichert
Aber wenn ich die Alignment Bilder machen will passiert einfach nix. Die Koordinaten werden im config file gespeichert ... das Bild wird auch erstellt aber ist immer 0kb groß.

Hier das Reference Bild, die Qualität sollte ja gut genug sein:
![Inkedreference_LI](https://user-images.githubusercontent.com/44932547/144125033-ebfd9a8f-28b6-4ddb-8572-69decc42d347.jpg)

![Unbenannt](https://user-images.githubusercontent.com/44932547/144129417-cd368381-6b6e-4229-9478-cd5743060054.jpg)

Ich habe Alignment Algo schon auf Fast geändert aber ohne erfolg.
Ich habe erst mit Flash Download Tool gearbeitet und danach die Python esptools probiert.
Ich habe verschiedenste SD-Karten (SanDisk, Transcend von 4GB bis 16GB probiert)
Habe auch schon einen zweiten ESP32 ausprobiert aber ich bekomme es einfach nicht zum laufen ....
Gefühlt läuft die 8.5.0 flüssiger wie die 9.1.1, aber das Alignment geht bei beiden nicht.
Router ist eine Fritzbox, hatte schon gelesen das es bei anderen zu Problemen kommen kann, habe es auch schon mit dem ESP in der nähe des Routers probiert (Top Signal).

Was kann ich noch tun ?

**Comment by friedpa** [comment]
Wie sieht denn den der zweite Alignment Punkt aus? Im Bild sieht man die Alignmentmarke "Reference 0", bitte poste die zweite auch. Bei der "Reference 0" sollte man auch nach update unter _Original Image_ das Alignmentmarkenbild sehen.

**Comment by Otti12345** [comment]
Mit der zweiten verhält es sich wie mit der ersten. 
Die Files Ref1 & Ref1_org werden mit dem klick auf "Update Reference" erzeugt aber haben 0kb.

**Comment by Otti12345** [comment]
Problem gefunden, liegt an zu kleinem RAM.
Mit QVGA Auflösung funktioniert es einwandfrei.

**Comment by jomjol** [comment]
Dann hast du aber vermutlich auch nur 2 MB PSRAM. Denn mit 4 MB sollte es funktionieren.

Da scheinen einige low cost ESP32CAM unterwegs zu sein, die nur einen 16 MBit = 2 MByte Chip verbaut haben.
