### ISSUE TITLE
Analog values reading off

### ISSUE THREAD

**Issue by Lea9ue** [jomjol/AI-on-the-edge-device#434]
Analog readings are way off.  Tryed adjusting multiple things with no success. Any suggestions?

![Untitled](https://user-images.githubusercontent.com/49419111/144179263-2d846a44-5d67-49b4-a11e-c68d4b04dc6a.png)

Edit: I know there are CCW dials. Thats not my concern.

**Comment by friedpa** [comment]
The hands would have to be trained first and please note that the display shows 2 and 4 against the clock hand.
The algorithm does NOT read the digits, but evaluates the position of the hands, i.e. the leftmost image should actually show 7.5.

**Comment by Lea9ue** [comment]
I edited my original post to acknowledge the CCW dials. There is an active work around for this.  When you say the hands would have to be trained first, can you elaborate on this.

**Comment by friedpa** [comment]
There is a procedure which pictures you have to send to jomjol to train the analog hands.

**Comment by jomjol** [comment]
Hi, @friedpa  is totally right. This kind of pointer (black on white, narrow small) is not trained and therefore the neural network is not accurate enough.

For a training I need picture of almost all counter positions in clock wise notation with the following boundary conditions:
- taken with the original settings (e.g. out of the log file)
- Encoding the reading between 0.0 and 9.0 and write the expected value in the file name: like 8.3_WHAT_EVER_YOU_WANT.jpg for reading 8.3
- about 1-2 images for each reading - all together about 100-200 images (not more!!!)
- if single readings are missing, this should not be a problem

You can collect the numbers in a ZIP-file and post them here.

Example of images see here: https://github.com/jomjol/neural-network-analog-needle-readout/tree/main/data_raw_all

**Comment by Lea9ue** [comment]
@jomjol I've started logging images last night. To clarify, what do you mean "original" setting.  Does this include the 32 x 32 size and default "5" quality?  Currently they are being saved at 109 x 109.

**Comment by jomjol** [comment]
Please send the bigger ones. My script will rescale them automatically.

**Comment by Lea9ue** [comment]
@jomjol Heres the zip, Thank
[AnalogImages.zip](https://github.com/jomjol/AI-on-the-edge-device/files/7654852/AnalogImages.zip)
s

**Comment by jomjol** [comment]
The images are looking okay. Are they slightly out of the middle and "tilted"?

I will put them in the next training session.

**Comment by Lea9ue** [comment]
@jomjol  From original post image the analog of the saves was on the far right. So it is a little off center which might be giving the illusion of it being tilted. If this is a issue, let me know.

**Comment by jomjol** [comment]
I will give it a try. Let's see. To illustrate the "problem":
![0 0_0003_zeiger1_2019-06-04T044009](https://user-images.githubusercontent.com/30766535/144798866-0eb8bdb9-609a-4e4e-b669-2b677fb5338f.jpg)![0 0_2_ANALOG_THIN_BLACK](https://user-images.githubusercontent.com/30766535/144798876-0767a969-90b9-42ba-8a7f-c99b43ee6b3d.jpg)

Here you see what I mean. I looks like in your "0.0" the pointer is not fully upright. Could also be a topic of the illumination.

**Comment by Lea9ue** [comment]
I see the concern.  I'll adjust camara tomorrow and start saving images just incase. I feel if there is going to be a problem it'll be more noticeable between 9-1 and 4-6. I could most likely adjust this post process as long as reading are consistent.

**Comment by Lea9ue** [comment]
@jomjol Is it possible to train off of created analog images or is that not recommended? I included zip of produced images.
[Generated.zip](https://github.com/jomjol/AI-on-the-edge-device/files/7664032/Generated.zip)

**Comment by jomjol** [comment]
That is a very intersting question. If every image is created, I assume, the cnn will not learn how to handle noise in the image. As long as only a part is generated, it should work. I will give it a try with your images.

How did you create the images. Can you share your code?

**Comment by Lea9ue** [comment]
@jomjol I did add some noise to half the images.  Like here:
![8 1_PRODUCED_ANALOG_2](https://user-images.githubusercontent.com/49419111/144975600-c6cfd8d6-a379-464f-b1c8-762bf2a4233a.jpg)
Its not super aggressive. I was also thinking about the coloring but I didn't do that route because I didnt know how much the color change would effect training.  I could randomly add color varients into the images if needed.  As far as the creation process I just took a nice quality image of the analog on the meter and using Gimp 2 I merged 2 images together to create background.  From there I added the pointer and through various scripts that are already available, I rotated the pointer creating a new layer for each possible outcome.  I then used another script to export each layer with the background.  If its of more interest I can do a write up here on the actual process and scripts used.

**Comment by Lea9ue** [comment]
@jomjol With color variations.
[generatedColorVariation.zip](https://github.com/jomjol/AI-on-the-edge-device/files/7666491/generatedColorVariation.zip)

**Comment by juergen852** [comment]
Same as #361

**Comment by ThiloAm** [comment]
@Lea9ue 
Your approach is interesting, if you can please explain in more detail. Maybe you can provide instructions and can you share your code?  That would help me (and other) a lot.

**Comment by jomjol** [comment]
Included meanwhile
