### ISSUE TITLE
Update documentation for digital counters graphical alignment

### ISSUE THREAD

**Issue by wernight** [jomjol/AI-on-the-edge-device#435]
The UI now shows some extra boundaries but I didn't see any doc on how they should be placed:

- Put the digit inside the outer rectangle
- Put the digit inside the inner rectangle
- Put the digit line to be middle with the inner rectangle

All these seem legit.

![image](https://user-images.githubusercontent.com/145667/144232744-a6134531-752b-42ef-94f3-e2ec1c8f267e.png)

**Comment by friedpa** [comment]
The boundaries are overlapping, which is OK. The inner frame should be close around the digit. By the way you must improve the contrast, otherwise it will not work. Make sure all frames have the same scale.

**Comment by wernight** [comment]
Thank you. You're right the contrast isn't good enough. I'm looking at ways to fix the lighting like the new external LED.

**Comment by jomjol** [comment]
Done: https://github.com/jomjol/AI-on-the-edge-device/wiki/Graphical-configuration - see section 3a/b

**Comment by wernight** [comment]
Very neat thank you.
