### ISSUE TITLE
Blinking meter display

### ISSUE THREAD

**Issue by h4sk33r** [jomjol/AI-on-the-edge-device#436]
Hi, 
I am planning on using this on my heat meter. In theory it is a smart meter, however the modbus is blocked by my landlord. I can therefore only use the digital LCD screen for readings. Unfortunately the meter display is not static but only showing the current kWh-total every 5 seconds for about 1 second.

Is it possible to basically decrease the external LED brightness to a minimum to then be able to take 5 second captures, to hopefully include the reading with a high enough contrast.

As an alternative would you just let the cam module work with the shortest intervall possible to hopefully capture the correct reading every hour or so by chance?

Thank you very much and best regards.

**Comment by jomjol** [comment]
Decreasing the illumination down to a 5 second capture is not possible. Although the contrast would be way to low.

Depending on the detailed setting you can run the system down to 1-2 minutes per run. So by change that might be a possiblity. But you would need some post processing. 

To be honest, I don't think, that this will be succesfull
