### ISSUE TITLE
Feature Request: Get last raw picture

### ISSUE THREAD

**Issue by nos86** [jomjol/AI-on-the-edge-device#442]
Hello,
I have implemented your project with my Home Assistant to read the level of the gas tank: just unique analog gauge that reports the level from 0 to 100.

In order to allow the CNN to recognize the right value, in alignment phase, I made a rotation in order to have the 0 on the center top. 

It would be very helpful, if in the future, it will be possible to retrieve the last raw image from the same url.

**Comment by jomjol** [comment]
I don't get the point. What image exactly do you want to access?

**Comment by nos86** [comment]
Your project saves a photo everytime it concludes the flow (under fileserver/log/analog/DATE/HOUR/VALUE_Level_DATE_TIME.jpg). My request was to have the possibility to retrieve the last picture with a standard shortcut like fileserver/log/analog/last.jpg or at least retrieve this information from `http://IP-ESP32/json`

However, looking at the Wiki, I found a solution for my question. I can use the url: `http://IP-ESP32/capture_with_flashlight` to get the raw image to save in Home assistant as raw image. This will be used to send the image via Telegram to alert me when the level is lower than a level. (Remember that I'm using this project to monitor the gas tank level).

The only concern I have is that if I invoke the method above during flow execution will lead a reset of the ESP32.

**Comment by jomjol** [comment]
There is a easear solution:

* ``http://IP-ESP32/img_tmp/raw.jpg``  --> raw image
* ``http://IP-ESP32/img_tmp/alg.jpg`` --> aligned image
* ``http://IP-ESP32/img_tmp/alg_roi.jpg`` --> aligned image with alignment ROIs

It is not intend for frequent use, so maybe it will result in crashes
