### ISSUE TITLE
Feature Request: Manage non linear gauge without CNN re-training

### ISSUE THREAD

**Issue by nos86** [jomjol/AI-on-the-edge-device#443]
Hello, 
my gauge for Gas Tank Level is not linear (see picture attached)
<img width="587" alt="Schermata 2021-12-05 alle 22 29 16" src="https://user-images.githubusercontent.com/6265510/144764638-cd87f271-af0d-4a74-8795-028cc7137dcb.png">

In order to avoid to create a dedicated CNN for this case, I would propose you to add a part of firmware where the raw value calculated is processed through a defined look-up table.

What do you think?

**Comment by jomjol** [comment]
The idea is good and could be implemented in an extended version. I will put it on the feature request list, but currently I have no capacity to follow this actively. But if you could implement this, I could merge the feature and the user interface update.
