### ISSUE TITLE
New analog images

### ISSUE THREAD

**Issue by michaeljoos72** [jomjol/AI-on-the-edge-device#444]
Hi Jomjol

Can you train attached analog pictures in one of the next releases? I know... , quite a lot of files ;) Is the more the better or should I reduce?

Thanks & BR
Michael

[analog.zip](https://github.com/jomjol/AI-on-the-edge-device/files/7662253/analog.zip)

**Comment by jomjol** [comment]
Sure, I can do so. But please reduce them to about 200 - max two pictures for each reading.

Thanks in advance.

**Comment by michaeljoos72** [comment]
Oki . . . reduced to 196

[anhalog_reduced.zip](https://github.com/jomjol/AI-on-the-edge-device/files/7667527/anhalog_reduced.zip)

**Comment by jomjol** [comment]
Trainined within the newest rolling: https://github.com/jomjol/AI-on-the-edge-device/raw/rolling/sd-card/config/ana1000s2.tflite
