### ISSUE TITLE
Bug: Missing Digits are replaced with old digit - even if digit left beside increased

### ISSUE THREAD

**Issue by Mann00007** [jomjol/AI-on-the-edge-device#445]
If numbers are not recognized, they should not always replace 1: 1 with the old number at this position.
It's neccecary to look at the position to the left. If the digit to the left has increased compared to the old value, the 'undetected' digit should be set to 0.

Example:
currently:
Raw 1234.16 -> 1234.16
Raw 1234.1N -> 1234.16 -> OK
Raw 1234.19 -> 1234.19
Raw 1234.2N -> 1234.29 -> is displayed as 1234.29, although in reality it is e.g. 1234.21
Raw 1234.25 -> 1234.29 -> brings up an errors because it is smaller than the old value -> but this is a correct recogniced value and shouldt bring up an error

wish:
Raw 1234.16 -> 1234.16
Raw 1234.1N -> 1234.16 -> OK
Raw 1234.19 -> 1234.19
Raw 1234.2N -> 1234.20 -> is displayed as 1234.20 because the digit to the left of N is larger than in the last measurement (in reality, e.g. 1234.21)
Raw 1234.25 -> 1234.25 -> again correct measurement / measured values

**Comment by jomjol** [comment]
This is a difficult topic. I have tried several versions, but all of them have some drawback.

For example: what happens, if your rate is so high, that the next number already went more than 1 digit, or even a full round (can happen for lowest digits), ...

This problem will be solved, as soon, as subdigt information will be available also for digit rolling numbers. Then the "N" will not be needed anymore and you have more information for consistency checks.

This is a major change on several parts (CNN, labeled training data, code) and there will need some time. It will be implemented in the next or overnext major release version.

Therefore I'm not going to change the logic currently and close this issue for the time beeing.

**Comment by Mann00007** [comment]
I dont' see it tht complicated and also independet from ther further development - becaus reading issues will always be there - and the target should be, that they dont lead to 'to high' values to make sure that the following correct measurements are accept and not refused because of negative values.

The technical solution should be quite simple - because you just have to check the number 'left' beside the missing digit. And to avoid issues with 'multiple' turns it's also no problem to check the whole number.

Solution idea:
1234,17 -> 1234,17 
1234,2N  -> 1234,20    0 because 1234,2>1234,1
1234,25  -> 1234,25    
1234,2N  -> 1234,25    old digit because 1234,2<=1234,2
1238,35  ->  1238,35
125N,21  -> 1250,21    0 because 125>123
1256,21  -> 1256,21   
125N,21  -> 1256,21      old digit because 125<=125
1256,33  ->  1256,33
125N,N4  ->  1256,34  1N; old digit because 125<=125  -> 6   
                                     2N old digit because 1256<=1256  -> 3 
1256,53  ->  1256,53
125N,N2  ->  1256,32  1N; old digit because 125<=125  -> 6   
                                     2N old digit because 1256<=1256  -> 5       -> Value will be dropped because of smaler than before
                                                                                                              - but this will happen in both solutions (old and new)
                                                                                                              - real value here was i.e.1256,42
Rule:
- Start with N's from left to right
- If left part beside N is bigger then the old left part from N than 0 else old digit
- for the 2. (and more) missing Digit (N) use the new number with the replaced digit by the rule from the first N

**Comment by jomjol** [comment]
With the future version, there will be no "N" anymore. That's my way to go :-)

**Comment by Mann00007** [comment]
If that works, that would also be an option for me ;-)
