### ISSUE TITLE
Change: API-call name should be more generic

### ISSUE THREAD

**Issue by Mann00007** [jomjol/AI-on-the-edge-device#446]
The URL for the value should be more generic, because it's also used for much more than water-meters already

Current situation:
http://[IP]/wasserzaehler.html

additional url more generic i.e.
http://[IP]/measurement.html or
http://[IP]/value.html or
http://[IP]/messwert.html
and use this in the documentation.

**Comment by caco3** [comment]
is this ticket is still valid?
For me the system only uses an `index.html` file resp. `index_configure.html`!

See also the list of html files in use: https://github.com/jomjol/AI-on-the-edge-device/tree/master/sd-card/html

**Comment by jomjol** [comment]
Next version should support `/value.html` additional to `/wasserzaehler.html`
