### ISSUE TITLE
Change: Save measurements also locally in a separate logfil

### ISSUE THREAD

**Issue by Mann00007** [jomjol/AI-on-the-edge-device#447]
It would be great if you could simply log the measured values locally on the memory card in parallel without having to activate the complete debugging.
This means that the whole project can also be used autonomously without external connections to analyze data in more detail.
And the access to the log files is already very nicely implemented in the web interface.
Because when it comes to 'real analyzes' you are quickly in Excel or Access (or other DBs)

ChangeRequest: extra checkbox in the config for value logging with 3 columns:
Timestamp, measured value and 'raw measured value'

**Comment by jomjol** [comment]
The final values are available in the function: ``bool ClassFlowPostProcessing::doFlow(string zwtime)`` (currently line #559)

in the file: https://github.com/jomjol/AI-on-the-edge-device/blob/master/code/components/jomjol_flowcontroll/ClassFlowPostProcessing.cpp

At the end of this function one could implement such a log file.

**Comment by Mann00007** [comment]
I will have a look,
Which compiler do you use/recommend to compile the files after changes?
Visual Studio?

**Comment by jomjol** [comment]
You need a toolchain with the esp-idf. I use VSCode with the PlattformIO with espressif32@2.1.0
You can also use the esp-idf toolchain directly, but there you also need to be carefull to use the right version: (4.1).

An older simple installation guide you find here: https://github.com/jomjol/AI-on-the-edge-device/wiki/Build-Instructions

**Comment by jomjol** [comment]
Closing as currently no action.
