### ISSUE TITLE
Change: For 'analog' rolling counters also teach some 'intermediate numbers'

### ISSUE THREAD

**Issue by Mann00007** [jomjol/AI-on-the-edge-device#448]
Since the 'last' position in analog roller counters in particular always has some 'intermediate values' in the photo, there are often recognition problems there.

Idea: Not only learn 1,2,3,4,5,6,7,8,9,0, but also one or two 'intermediate numbers' to improve the recognition rate.
As e.g.
8.33 as 8
8.66 as 9
9 as 9
9.33 as 9
9.66 as 0
0 as 0
0.33 as 0
0.66 as 1
I do not know whether it has already been tried, if the quality increases or whether this will lead to more 'wrong interpretations'.

Possibly you can only compare the 'last' digit with these additional 'intermediate numbers' to avoid miss-interpretations on the other digits.
And usually all positions in front of the last one are positioned 'exactly' and interpreted correct.

**Comment by Lea9ue** [comment]
Analogs are taught fractionally .0 to .9 (eg. 1.9)  but you would never want to round this number up. You can in your config show the final decimal value

**Comment by Mann00007** [comment]
Hello Lea9ue,
I think that works only 'analogs' of  a water meter.
Analoges of a analog roller counter are defined als 'Digital' but they are not binary switching - they are also 'rolling' - and in that case often between two numbers what causes reading issues.

I use it on a gas-meter

**Comment by jomjol** [comment]
On this topic I'm already working. The challange is the neural network, that needs to be adapted
* new structure to get the subdivision after the decimal
* new and much more labeled training data
* adapted code

But that will be working in the next or overnext major release.

**Comment by Mann00007** [comment]
That sounds perfect. Thanks a lot.

**Comment by wurmthomas80** [comment]
Hi,
are you guys talking about this problem?
![grafik](https://user-images.githubusercontent.com/46227631/148183535-a4eeab57-4619-427e-b252-4cd82f080f22.png)

Struggling with same issue. Sure I can reduce one decimal and only read 10liter intervals, but 1 liter intervals would be nice too ;-)

**Comment by jomjol** [comment]
One of the next versions (2-3 month) will be able to read also intermediate numbers. But this will take some time to develop.

**Comment by wurmthomas80** [comment]
Sure :-) lots of thanks for you efforts!
just wasn't sure if we are really talking about same issue

**Comment by cbho** [comment]
> Hi, are you guys talking about this problem? ![grafik](https://user-images.githubusercontent.com/46227631/148183535-a4eeab57-4619-427e-b252-4cd82f080f22.png)
> 
> Struggling with same issue. Sure I can reduce one decimal and only read 10liter intervals, but 1 liter intervals would be nice too ;-)

HI,
have the same type of meter with a larger frame for the last digit.
Noticed in the pictere above, that the ROI-box has been made larger that the others.
I've made mine the same size as the others and aligned it with these.
Which strategy would be the best the get the best readings?

Regards,
Chr.
