### ISSUE TITLE
Gasmeter wrong digit: 6 is 0

### ISSUE THREAD

**Issue by tunip** [jomjol/AI-on-the-edge-device#449]
Hello jomjol,

since dig1310 my 6 is a 0.

Attached the 6 from my gasmeter from different places for learning:
![6_digit3_20211208-170406](https://user-images.githubusercontent.com/11404472/145273087-922aa178-75ab-4e46-b560-214c5b0cfd22.jpg)
![6_digit6_20211208-170406](https://user-images.githubusercontent.com/11404472/145273094-6653c1a5-2406-4219-8231-b3008b7da4eb.jpg)
![6_digit7_20211208-170406](https://user-images.githubusercontent.com/11404472/145273096-56d13bab-ddf5-4e7e-86f7-54754e80d49d.jpg)

**Comment by jomjol** [comment]
If the old one is working better, I suggest to stay with that.
