### ISSUE TITLE
(Garten)Wasseruhr ohne CRI

### ISSUE THREAD

**Issue by Reinschki** [jomjol/AI-on-the-edge-device#45]
Hallo jomjol,

großes Kino, vielen Dank!

Ich konnte soweit alles installieren, scheitere jedoch am Einrichten meiner Gartenwasseruhr.
![Gartenwasseruhr](https://user-images.githubusercontent.com/74489990/99183247-a1bc7100-273a-11eb-9f74-9f2106929eee.jpg)
Bei diesem Modell gibt es kein CRI Referenz Image.
Lässt sich diese Wasseruhr Konfigurieren? Mir würden die digitalen Werte ausreichen. Bei dieser Uhr gibt es ohnehin nur einen analogen Zähler.

Über Tipps währe ich sehr dankbar!

Viele Grüße
Reinschki

**Comment by jomjol** [comment]
Hallo Reinschki,

die Referenz ist frei wählbar und kann einfach über die Web-Oberfläche konfiguriert werden (https://github.com/jomjol/AI-on-the-edge-device/wiki/Graphical-configuration).
Mir schein dein Bild noch etwas unscharf und du solltest noch etwas mit der Position der Kamera spielen. Die Reflexionen führen zu weissen Strichen in den unteren Bereichen der Ziffern, das könnte noch Probleme machen. Vielleicht einfach mal um 90 Grad drehen - läßt sich ja einfach wieder beim Erstellen des Referenzbildes anpassen.
Gruß,
  jomjol

P.S.: ich mache den Issue wieder zu. Wenn du weitere Themen hast, bitte natürlich gerne melden.
