### ISSUE TITLE
[Request] show sd information

### ISSUE THREAD

**Issue by spcqike** [jomjol/AI-on-the-edge-device#451]
Hi,

is it possible, to show some SD card information? like used, free and total space? 
if so, is it possible to publish (at least free/available) space to MQTT? 

Or maybe have the possibility to choose, what messages to publish (like disable Uptime and freemem, enable rate, value, sd_free, ...) ? :)

I'm just curious, because i have no idea how much storage is needed, and how long it takes until the SD card is full. :)

best regards

**Comment by jomjol** [comment]
In principle yes, but I think, it is not necessary. You can switch on the retetion days (``LogfileRetentionInDays``), that cleans the old log files. The size of the images is also not really big. If you turn on the pure text logfile (messages), than you increase by about 1-2 MByte / day. 
I'm currently not planning to implement this. If you make a folk, I can check later and integrate it.
