### ISSUE TITLE
Webinterface only reachable via Smartphone

### ISSUE THREAD

**Issue by Duese123** [jomjol/AI-on-the-edge-device#453]
The Webinterface is only reachable via Smartphone (i used Chrome). On the PC it will open mabye once after an restart and thats it. I tried with Chrome and also Edge. Via smarthpone there are no problems. In forum i got feedback that it occurs at least by one other user.

![image](https://user-images.githubusercontent.com/95966691/145676927-71ef7a17-ef76-4853-9561-feef9ebf5256.png)

**Comment by jomjol** [comment]
I'm not using Chrome for testing, but Firefox. Can you test it with Firefox or Edge?

**Comment by Duese123** [comment]
i tried with Edge as i mentioned before. It is the same. The webinterface will not open and shows a blank screen. Maybe it is an Port forwarding issue i do not know. With the smarthphone it is working.

**Comment by pbertra** [comment]
Same issue:
- not working on windows 10 with latest Chrome
- not working on windows 10 with latest edge
But
- working on android mobile with chrome
- working on windows 10 with firefox

**Comment by jomjol** [comment]
@pbertra Known issue - only Firefox tested. No capacities and html skills to adapt for other browsers.

Support welcome !
