### ISSUE TITLE
Make the result persistent over MQTT

### ISSUE THREAD

**Issue by nos86** [jomjol/AI-on-the-edge-device#455]
Hello Jomjol,
using your project with Home Assistant, I experience an issue when reboot Home Assistant, that the value of the gauge is not available until next image processing. 

In order to fix it and improve your project, I suggest you to set the Retain flag in MQTT publish.

What do you think?

I think it's needed to add the `true` as additional argument to set the retained for:

https://github.com/jomjol/AI-on-the-edge-device/blob/18f6e83a2c03a2da4d7f1bff13efe92d5cdc156c/code/components/jomjol_flowcontroll/ClassFlowMQTT.cpp#L173

https://github.com/jomjol/AI-on-the-edge-device/blob/18f6e83a2c03a2da4d7f1bff13efe92d5cdc156c/code/components/jomjol_flowcontroll/ClassFlowMQTT.cpp#L176

https://github.com/jomjol/AI-on-the-edge-device/blob/18f6e83a2c03a2da4d7f1bff13efe92d5cdc156c/code/components/jomjol_flowcontroll/ClassFlowMQTT.cpp#L179

https://github.com/jomjol/AI-on-the-edge-device/blob/18f6e83a2c03a2da4d7f1bff13efe92d5cdc156c/code/components/jomjol_flowcontroll/ClassFlowMQTT.cpp#L182

https://github.com/jomjol/AI-on-the-edge-device/blob/18f6e83a2c03a2da4d7f1bff13efe92d5cdc156c/code/components/jomjol_flowcontroll/ClassFlowMQTT.cpp#L191

https://github.com/jomjol/AI-on-the-edge-device/blob/18f6e83a2c03a2da4d7f1bff13efe92d5cdc156c/code/components/jomjol_flowcontroll/ClassFlowMQTT.cpp#L207

**Comment by jomjol** [comment]
I don't do that by purpose, because if the ESP32 is down for some reasons, I still would get the value. 
My MQTT is reading every 3-4 minutes, after this the value is available or I know, that there is a problem. But feel free to make a copy and adapt your code to yours needs.
