### ISSUE TITLE
wrong value updating on analog changes

### ISSUE THREAD

**Issue by TungstenE2** [jomjol/AI-on-the-edge-device#457]
previous  value: 83.6028

new raw value:  080.6072 (after water usage)

new value is not updated.

please check, changes are recognized, but not correct processed.

thx

![grafik](https://user-images.githubusercontent.com/39955685/145984423-7c240f1c-b3a3-4576-809a-2509d8e0bc37.png)

![grafik](https://user-images.githubusercontent.com/39955685/145984504-ca80cd5f-ae8b-4b75-8cc3-a15bbbcd709e.png)

**Comment by friedpa** [comment]
The picture is not sharp enough, additionally the frames around the digits are not equaly in the size. Please see Wiki for instruction to improve the recognition. You disabled in the config.ini AllowNegativeRates, so no lower reading as the previous reading will be submitted.

**Comment by TungstenE2** [comment]
30min later readings are correct

![grafik](https://user-images.githubusercontent.com/39955685/145990685-765c84ff-0541-4046-a201-6b2c3ba4a1b0.png)

**Comment by TungstenE2** [comment]
> The picture is not sharp enough, additionally the frames around the digits are not equaly in the size. Please see Wiki for instruction to improve the recognition. You disabled in the config.ini AllowNegativeRates, so no lower reading as the previous reading will be submitted.

is 83.6072 lower than 83.6028? I dont think so.

**Comment by friedpa** [comment]
It was 80.6072 (RAW Value) which is lower than 83.6028 (Previous Value) ....

**Comment by TungstenE2** [comment]
you are fully right, I only focused on the last 4 digits

**Comment by jomjol** [comment]
Then I close this issue for the time beeing. Please reopen on demand.
