### ISSUE TITLE
add configuration backup/restore  

### ISSUE THREAD

**Issue by thost96** [jomjol/AI-on-the-edge-device#459]
Hi,

it would be nice to have a backup and restore button or menu entry (e.g. under system tab) on the web GUI to back up all configuration data. At the moment, all needed files must be downloaded separately which is quite complex and user error missing a file can happen. 

Thanks!

**Comment by jomjol** [comment]
Idea is understood and technically possible. Never the less I don't have capacity to do so currently. Therefore I will put it to the feature list and close this issue to the time beeing.
