### ISSUE TITLE
Extreme Probleme Wert wird nicht mehr richtig angezeigt

### ISSUE THREAD

**Issue by Basti09** [jomjol/AI-on-the-edge-device#460]
Hallo zusammen,

ich habe aktuell das Problem das mit der wert nicht mehr angezeigt wird. Die Erkennung scheint zu funktionieren. Woran kann das liegen, ich finde den Fehler einfach nicht.

master - v9.1.1 - 2021-11-16

![Screenshot 2021-12-17 215817](https://user-images.githubusercontent.com/19894220/146607333-9458dfe2-b80e-4994-ba0c-5599c401224d.png)
![Screenshot 2021-12-17 220050](https://user-images.githubusercontent.com/19894220/146607428-f866dd28-34b2-4d4a-b734-1fa89f896e25.png)

**Comment by jomjol** [comment]
Da scheint etwas in der Configuration nicht zu stimmen. Hast du das tflite-File geändert oder ist es vielleicht auf der SD-Karte defekt?

**Comment by Basti09** [comment]
Ne eigentlich nicht. Wie soll ich vorgehen ? Da Karte rausnehmen und neu beschreiben ? Dann probiere ich es morgen Mittag mal aus und melde mich noch einmal.

**Comment by jomjol** [comment]
Ja - am besten die Daten runter kopieren - schauen, dass dort keine kaputten dabei sind (z.B. Größe = 0). Die SD-Karte formatieren und dann neu bespielen.

**Comment by Basti09** [comment]
Alles klar, werde es bis morgen Abend ausprobieren und mich dann noch mal melden. Vielen Dank schon mal

**Comment by jomjol** [comment]
Schließe den Issue mal, bis es neue Informationen gibt.

**Comment by Basti09** [comment]
Hallo, habe das Problem gefunden.

Der Firmwareordner war angeblich 40GB groß bei einer 8GB microSD, der Ordner lässt sich auch nicht mehr mit Kopieren.

Muss ich jetzt wieder komplett neu flashen der habe ich noch eine andere möglichkeit ?

**Comment by friedpa** [comment]
Ich würde die SD-Karte komplett neu formatieren, das erspart Dir einigen Aufwand. Verwende dazu ein Tool wie Rescue Pro von SanDisk (gibt es auch in einer Freeware Version).

**Comment by jomjol** [comment]
Du kannst vorher noch das config Verzeichnis sichern und die Einträge dann übernehmen.

**Comment by Basti09** [comment]
Das habe ich soweit alles gesichert. Also wieder neu Flashen okay.

**Comment by Basti09** [comment]
so hab alles neu gemacht , bin jetzt beim Einrichten. Jetzt meine Frage kann ich einfach mein Backup einspielen ? Habe alles gesichert außer den Firmware Ordner

**Comment by jomjol** [comment]
Poste mal deine ´config.ini´. Ich schau mir das mal an.

**Comment by Basti09** [comment]
[config.zip](https://github.com/jomjol/AI-on-the-edge-device/files/7786371/config.zip)

Vielen dank

**Comment by jomjol** [comment]
Sieht erstmal okay aus. Hast du auch die beiden tflite-Files im Config-Verzeichnis?
```
[Digits]
Model = /config/dig0850s1q.tflite
...
[Analog]
Model = /config/ana0700s1lq.tflite
```

**Comment by Basti09** [comment]
![1](https://user-images.githubusercontent.com/19894220/147649149-af5d0c5c-7b99-4a6a-a64b-4ba06b7f6646.JPG)

**Comment by jomjol** [comment]
da ist etwas nicht okay mit der Datei: `dig0850s1q.tflite` - die gibt es im Verzeichnis nicht und daher kann er auch die Ziffern nicht digitalisieren.
Das ist aber eh noch eine sehr alte Version. Inzwischen bin ich bei `dig1330s1q.tflite`  - siehe GitHub: https://github.com/jomjol/AI-on-the-edge-device/tree/master/sd-card/config

**Comment by Basti09** [comment]
okay, vielen dank, kann ich die Dateien einfach so jetzt auf die SD Kopieren und die vorhandenen überschreiben ?

**Comment by jomjol** [comment]
das könntest du probieren und natürlich auch in der config.ini anpassen.

**Comment by Basti09** [comment]
Ok, ich schaue mal ansonsten muss ich nochmal alles neu machen. Dann ist das eben so. Ich bin davon ausgegangen das immer wenn man ein Update macht die darein sich auch Updaten. Deswegen habe ich meine gesicherten einfach drüber kopiert
