### ISSUE TITLE
Alignment Fehler

### ISSUE THREAD

**Issue by FISO291** [jomjol/AI-on-the-edge-device#461]
Ich habe auch das Problem, dass das Alignment nicht stimmt. Die Kamera ist scharf eingestellt (siehe Bilder)
Ich hatte die Marker eine Zeitlang bei CRI und bei m³, aber nach paar Tagen dann war es verschoben und er konnte nichts mehr richtig auslesen.

Setze ich die Marker bei CRI und MOM, dann gehts erst garnicht.

Braucht er denn immer ein Alignment? Ich mein, wenn die Kamera verschoben wird, dann macht es ja irgendwie Sinn. Aber wenn ich die nicht Bewege weil die Fest in ein Gehäuse drinsteckt, dann verändert sich die Position ja nicht und dann wären die Analogen und digitalen Marker ja immer an der selben Position.

Das Selbe Problem hat übrigens mein Nachbar. Er hat mich vor paar Tagen damit angefixt. Ich war Feuer und Flamme weil die Idee ja total super ist :) Übrigens ein Lob für die Tolle Arbeit. Also hab ich mir dann auch eine ESP32 Cam geholt und mein Nachbar hat mir Netterweise das passende Gehäuse für die Uhr gedruckt.

Aber leider funktioniert es nicht so wie wir uns das wünschen. Woran kann es liegen, was kann ich dagegen tun? Ich danke schonmal im Voraus für die Hilfe und wünsche euch noch einen schönen Abend und ein schönes Wochenende.

VG 

Steve

Übersicht
![image](https://user-images.githubusercontent.com/71070045/146608029-0ec71704-3cab-4ab4-8ade-e7282d8f83ef.png)

Alignment
![image](https://user-images.githubusercontent.com/71070045/146608138-f842bba2-8b5b-4815-8025-36df14a5512d.png)
Alignment
![image](https://user-images.githubusercontent.com/71070045/146608201-258e2687-93bd-42c3-a902-e5027ad4db08.png)

Auf dem Bild (Übersicht) wird es kriminell :D

![image](https://user-images.githubusercontent.com/71070045/146608927-bbffcbfa-aa9d-4990-8329-31434d76308d.png)

Klick ich auf Recognition dann kommt folgendes:

![image](https://user-images.githubusercontent.com/71070045/146609030-97760020-1ca6-4e6a-b867-2201c6dccf11.png)

Die Marker sind garnicht sichtbar, es sind nur 2 Rote Punkte da!

**Comment by jomjol** [comment]
1. Die Alignmentstrukturen sind zu dicht beieinander. Idealerweise liegen sie diagonal auseinander und haben einen hohen Kontrast
2. Wenn du dort nur einen Punkt siehst, dann stimmt etwas mit der Config.ini nicht. Du kannst sie ja mal posten, dann schaue ich mir das Alignment an.

**Comment by FISO291** [comment]
Hier die Config.ini

[MakeImage]
;LogImageLocation = /log/source
WaitBeforeTakingPicture = 5
;LogfileRetentionInDays = 15
Brightness = -2
;Contrast = 0
;Saturation = 0
ImageQuality = 5
ImageSize = VGA
FixedExposure = false

[Alignment]
InitialRotate = -1
InitialMirror = false
SearchFieldX = 20
SearchFieldY = 20
AlignmentAlgo = default
FlipImageSize = false
/config/ref0.jpg 196 113
/config/ref1.jpg 198 74

[Digits]
Model = /config/dig1330s1q.tflite
;LogImageLocation = /log/digit
;LogfileRetentionInDays = 3
ModelInputSize = 20 32
main.dig1 294 57 32 57
main.dig2 324 57 32 57
main.dig3 354 57 32 57
main.dig4 384 57 32 57

[Analog]
Model = /config/ana0910s3_longq.tflite
;LogImageLocation = /log/analog
;LogfileRetentionInDays = 3
ModelInputSize = 32 32
main.ana1 395 167 83 83
main.ana2 341 246 83 83

[PostProcessing]
main.DecimalShift = 0
PreValueUse = true
PreValueAgeStartup = 720
AllowNegativeRates = false
main.MaxRateValue = 0.1
;main.ExtendedResolution = false
;main.IgnoreLeadingNaN = false
ErrorMessage = true
CheckDigitIncreaseConsistency = false

[MQTT]
Uri = mqtt://
MainTopic = wasserzaehler
ClientID = Wasseruhr
;user = 
;password =

;[GPIO]
;IO0 = input disabled 10 false false 
;IO1 = input disabled 10 false false 
;IO3 = input disabled 10 false false 
;IO4 = built-in-led disabled 10 false false 
;IO12 = input-pullup disabled 10 false false 
;IO13 = input-pullup disabled 10 false false 
LEDType = WS2812
LEDNumbers = 2
LEDColor = 50 50 50

[AutoTimer]
AutoStart = true
Intervall = 5

[Debug]
Logfile = false
LogfileRetentionInDays = 3

[System]
TimeZone = CET-1CEST,M3.5.0,M10.5.0/3
;TimeServer = undefined
;AutoAdjustSummertime = false
;Hostname = undefined
SetupMode = false

**Comment by jomjol** [comment]
Sorry habe gerade festgestellt, dass die Größe der Alignmentmarke von den Bildern auf der SD-Karte bestimmt wird.
Hast du dir mal /config/ref0.jpg oder /config/ref1.jpg angeschaut?

**Comment by FISO291** [comment]
![image](https://user-images.githubusercontent.com/71070045/146611409-704f75ad-5fe9-4684-891b-8aa82942c0db.png)

Ref 0
![image](https://user-images.githubusercontent.com/71070045/146611485-655fc40a-4941-4793-b99c-ed0146f4222d.png)

Ref1
![image](https://user-images.githubusercontent.com/71070045/146611534-83909354-3515-4371-b8a3-81953a0d40a1.png)

**Comment by jomjol** [comment]
Sieht eigentlich alles gut aus. Kann den Fehler momentan nicht nachvollziehen. Hast du mal 5 Minuten gewartet, bis der zweiter Run durch ist?

**Comment by FISO291** [comment]
Noch nicht. Ich hab mal den Marker wie du vorgeschlagen hast diagonal angeordnet. Einen auf MOM (links oben) und einen diagonal rechts unten auf MCI. Hab grad neu gebootet und melde mich gleich wieder :)

**Comment by FISO291** [comment]
Also das ging schonmal schief. Ich warten noch 10 min und schau was er dann macht.

![image](https://user-images.githubusercontent.com/71070045/146612263-e35d4625-b8e3-4956-83ae-8aa993d7a9fa.png)

**Comment by jomjol** [comment]
Wenn der Fehler so aussieht, dann sind deine Marker nicht ausreichend. Du könntest mal etwas weißes auf die Oberfläche kleben und dann einen schwarzen Punkt o.ä. drauf malen. Einen besseren Kontrast kann du nicht bekommen.
Vermutlich ist die Marke "MCI" das Problem.

**Comment by FISO291** [comment]
komisch ist ja jetzt, dass er einen Teil vom oberen Bild abscheidet.... 

![image](https://user-images.githubusercontent.com/71070045/146620976-9496a760-f696-4e5e-803e-d337aaa4db58.png)

Hab die Alignment Marks geändert.

![image](https://user-images.githubusercontent.com/71070045/146621009-192a44c0-036f-4a62-8185-0842adde71be.png)
![image](https://user-images.githubusercontent.com/71070045/146621037-d680f62f-bb79-4bcf-9469-170492b4660a.png)

Erzeugt nun auf der Startseite folgendes:

![image](https://user-images.githubusercontent.com/71070045/146621075-36d5a845-90f8-458c-b70a-8fe5ca5fae8d.png)

![image](https://user-images.githubusercontent.com/71070045/146621132-b6fef0ed-8b71-47d9-bb52-99927627be5c.png)

![image](https://user-images.githubusercontent.com/71070045/146621155-00104f51-4344-4d50-af2d-f64689c0b3c9.png)


Also es geht jetzt erstmal wieder. Hoffe dauerhaft :)

**Comment by jomjol** [comment]
Dann drück ich die Daumen  und schließe den Issue erstmal.
