### ISSUE TITLE
Herausforderung EnerCal

### ISSUE THREAD

**Issue by awor** [jomjol/AI-on-the-edge-device#463]
Als erstes, vielen herzlichen Dank für dieses überaus cooles Projekt! 🥇 
Ich versuche einen EnerCal F2 auszulesen. Die Herausforderung dabei ist, dass die drei Ziffern hinter dem Dezimalpunkt blinken. Meist schaffen sie es auf das Bild, jedoch ist der Kontrast nicht so gut weil sie eben nicht konstant an sind.
![EnerCal](https://user-images.githubusercontent.com/3464535/146673597-1ac84846-3d4e-4c08-b663-37faac74450a.png)
Die vorderen Ziffern (400 auf dem Bild) werden meist zuverlässig gelesen.
Hast Du mir einen Tip betreffend den Einstellungen, um diese Situation besser zu meistern, oder ist das ein hoffnungsloser Fall?
Auch wollte ich noch fragen: Gibt einen Weg, dass ich als Anwender die SW selbst trainieren kann, um meine Ziffern besser zu erkennen?
Besten Dank und viele Grüsse

**Comment by jomjol** [comment]
Hi,
du könntest die ROIs etwas größer definieren, dann passt es besser zu den trainierten Bildern - Details siehe hier (Abschnitt 3a/b): https://github.com/jomjol/AI-on-the-edge-device/wiki/Graphical-configuration

Du kannst das CNN auch selbst trainieren - ist aber nicht ganz so detailiert dokumentiert: https://github.com/jomjol/neural-network-digital-counter-readout

**Comment by awor** [comment]
Hi, besten Dank für Deine Antwort. Wenn ich die ROI so dimensioniere, dass der innere Rahmen eng um die Zahlen liegt, wären die äusseren Rahmen überlappend (ggf. sogar über die benachbarten Zahlen). Ist das kein Problem?

**Comment by jomjol** [comment]
Überlapp ist kein Problem, die ROIs werden ja der Reihe nach ausgeschnitten. Benachbarte Zahlen können in der Tat ein Thema werden. Das müsstes du mal probieren.

**Comment by awor** [comment]
Ich habe zig verschiedene ROI Einstellungen versucht, leider mit bescheidenem Erfolg. Kann es sein, dass die Software mit digitalen Ziffern und tieferen Kontrasten nicht gut klar kommt? Bei meinem analogen Gas-Zählerwerk (BK-G6A) funktioniert es deutlich besser.
![EnerCal](https://user-images.githubusercontent.com/3464535/147880375-ac179aa5-9368-484a-a1e8-8c4cc26aefbe.png)
Grössere ROI bringen in meinem Fall schlechtere Ergebnisse. Überlappungen mit benachbarten Ziffern auch, womit ich die ROI nicht breiter machen kann.
Oder gibt es nebst den ROI noch andere Einstellungen, welche ich in meinem Fall anpassen müsste?
Ein tolles 2022 wünsche ich noch :)

**Comment by jomjol** [comment]
Ich bin gerade dabei einen Set von LCD-Ziffern ins teachin aufzunehmen, die haben aber einen anderen Kontrast und sind auch nicht so eng beeinander. Wenn du willlst, kannst du das als Beta-Tester mal mit folgendem neuen tflite-File testen (musst du noch auspacken):

[dig-s1-q-20220102.zip](https://github.com/jomjol/AI-on-the-edge-device/files/7799306/dig-s1-q-20220102.zip)

Bin gespannst auf deine RM.

**Comment by awor** [comment]
Sehr gerne. Muss ich nur ins config Verzeichnis uploaden + reboot, richtig?

**Comment by awor** [comment]
Habs mal so gemacht (nach auspacken des zips), scheint in meinem Fall keine Verbesserung zu bringen:
![2022-01-02 16_58_13-jomjol - AI on the edge - EnerCal](https://user-images.githubusercontent.com/3464535/147881484-8d4d6b65-b40a-4834-9061-1d579b838e2d.png)

**Comment by jomjol** [comment]
Dann würde nur ein dediziertes Training von deinen LCD Ziffern helfen.
Ich würde es erstmal mit den ROIs mit dem 20% Rand versuchen (https://github.com/jomjol/AI-on-the-edge-device/wiki/ROI-Configuration). Wenn du mit den Einstellungen einen Satz an Bildern erzeugst hast - idealerweise mit den unterschiedlichen Kontrastarten (siehe z.B. die "4"), dann nehme ich den ins nächste Training mit auf.

**Comment by ThomasCr** [comment]
Nebenbei kann der Zähler wohl auch das MBus Protokoll am optischen Interface. Daß Interface sieht aus wie daß von meinem Stromzähler inkl. Befestigung. Daß bekommt von für um die 20 € fertig in eBay oder nur die Platine oder Bausatz.

Tasmota kann daß Protokoll auch, sollte also machbar sein.

Hab in #509 schon was dazu geschrieben.

**Comment by Scotty-89** [comment]
Hallo zusmmen,

ich sehe das du hier ein änliches Problem hast wie ich ;) 
https://github.com/jomjol/AI-on-the-edge-device/issues/509

kann ich euch hier irgendwie helfen ? was für Bilder braucht ihr ? dann würde ich auch welche bereitstellen

**Comment by Scotty-89** [comment]
> ade dabei einen Set von LCD-Ziffern ins

soweit ich das sehe muss man das noch in der Config Ini dann auch "auswählen"
-> 
[Digits]
Model = /config/dig1330s1q.tflite
;LogImageLocation = /log/digit
;LogfileRetentionInDays = 3
ModelInputSize = 20 32
main.dig1 294 126 30 54
main.dig2 343 126 30 54
main.dig3 391 126 30 54

**Comment by Scotty-89** [comment]
Ich habe das dig-s1-q-20220102.tflite jetzt auch mal Probiert und muss sagen so recht scheint das nicht besser zu sein..
siehe bild:
![image](https://user-images.githubusercontent.com/54929714/148183526-97c053c0-20a3-489e-9533-8f254317af85.png)

zuvor hatte er die erste 8 immer korrekt erkannt nun ist es eine 2

**Comment by jomjol** [comment]
Ja verstanden, wenn ich aber selbst 2x hinschauen muss, um zu sehen, ob es eine 2 oder eine 8 ist, bei der ein Strich schlecht leuchtet, dann wird es auch für das neuronale Netz schwierig:
![grafik](https://user-images.githubusercontent.com/30766535/148184615-80f1fba0-b93b-4fcd-8eb6-27465cf66ace.png)

Beleuchtung ist der Key!

**Comment by jomjol** [comment]
P.S.: seit heute morgen gibt es im Rolling nochmals ein Update: https://github.com/jomjol/AI-on-the-edge-device/blob/rolling/sd-card/config/dig-s2-q-20220104.tflite

**Comment by Scotty-89** [comment]
Ich werd es gleich mal drauf machen und testen.

udn wie gesagt mit der Beleuchtung spiele ich nachher hauch nochmal..
VIELEN DANK!

**Comment by Scotty-89** [comment]
hab das akutelle Roling drauf und was soll ich sagen auf Anhieb hat er es korrekt erkannt .. mal sehen wie sich das den Tag über verhält.
![image](https://user-images.githubusercontent.com/54929714/148186942-838b9976-8731-4fde-a704-7e7d09f7ec79.png)

**Comment by awor** [comment]
Ein grundlegender Unterschied zwischen mechanischen Zählern und digitalen Displays ist der Platz zwischen den Ziffern. Wenn die 20% Rand-Vorgabe vollständig eingehalten wird, ist es zumindest bei mir so, dass benachbarte Zahlen teilweise im Ausschnitt sind. Dies ist bei den Screenshots von @Scotty-89 teilw. auch so. Ich frage mich, ist das überhaupt ein Problem? Wenn Ja bräuchte es wahrscheinlich einen weiteren Schritt im Flow, welcher z.B. mit ImageMagick o.ä. den Fokusbereich der Zahl ausschneidet und einen entsprechenden 20% Rand hinzufügt, bzw. das Format "passend" macht. Das andere Problem ist der Kontrast. Mein Gaszähler mit den mechanischen Zahlen ist ziemlich scharf und klar. Hier ein Vergleich:

![image](https://user-images.githubusercontent.com/3464535/148205627-7be1f9fc-b067-48e5-ae5a-c2c2ec2650dc.png)
![image](https://user-images.githubusercontent.com/3464535/148207897-5d63f37d-7303-4c92-be02-5d4f4b68112b.png)

![image](https://user-images.githubusercontent.com/3464535/148205679-ddad1b5a-ccb2-49ee-8c6b-21270d654507.png)

An der Beleuchtung und Fokus-Einstellung habe ich schon zig Stunden verbracht, bringe es nicht besser hin. Das Auslesen der Digitalanzeige ist bei mir aktuell sehr unzuverlässig (s. Beispiel oben)

**Comment by Scotty-89** [comment]
guten abend,

also so wirklich besser ist es dann wohl doch nicht ...
![image](https://user-images.githubusercontent.com/54929714/148274825-f41af73e-a833-4938-8102-6f278434109e.png)

dann müsste man die Zahlen wohl doch mal Trainieren oder ?

**Comment by jomjol** [comment]
Die Kontrastvariationen sind echt groß, da brauche ich schlicht mehr trainingsmaterial für helle und dunke Ziffern.
Eventuell muss ich einen speziellen Datensatz für LCD-Displays machen.

**Comment by Scotty-89** [comment]
das ist leider das Problem mit Displays ;)...  ich werd die tage nochmal mit einer externen LED Spielen ggf geht es noch besser..

was genau brauchst du den so für Bilder und wie ..
Dann helfe ich dir zumindest da etwas.

**Comment by jomjol** [comment]
1. ROI optimal einstellen (dürfte passen) - siehe hier: https://github.com/jomjol/AI-on-the-edge-device/wiki/ROI-Configuration
2. Einfach das logging der Bilder einschalten und passende Bilder raussuchen, entsprechend bennen und mir hier per ZIP schicken (siehe auch: https://github.com/jomjol/AI-on-the-edge-device/wiki/ROI-Configuration#1-get-images-into-the-next-training-round)

Das wird wohl einen Moment dauern, solange mache ich den Issue zu. Du kannst ihn dann ja einfach wieder eröffnen.

**Comment by Scotty-89** [comment]
@jomjol 

danke fürs Angebot...

ich habe jetzt mit der Beleuchtung nochmal gespeilt und es deutlich verbessern können.
Es hat sich auch schon merklich verbessert aber mit den "kleinen" zahlen hat er hier und da noch ein paar Probleme.

Anbei ein paar Bilder zum Trainieren, wäre cool wenn du mir daraus was geben könntest.
 
[wasserzähler.zip](https://github.com/jomjol/AI-on-the-edge-device/files/7835046/wasserzahler.zip)

**Comment by mley** [comment]
Entschuldigt wenn ich mich einfach so einmische, aber ist "AI" für ein 7-Segment-Display nicht etwas mit Kanonen auf Spatzen schießen? Eigentlich sollte es reichen für jedes Segment jeder Ziffer einen Punkt zu definieren, der innerhalb des Segments liegt, ändert sich die Helligkeit ist das Segment an oder aus. Wie einfach sich das mit dem Framework hier umsetzen lässt, kann ich nicht sagen, da ich noch nicht in den Code selbst reingeschaut habe... nur als kleine Anmerkung.

**Comment by jomjol** [comment]
@Scotty-89 die Zip-Datei ist defekt.

**Comment by Scotty-89** [comment]
[Wasserzaehler.zip](https://github.com/jomjol/AI-on-the-edge-device/files/7835711/Wasserzaehler.zip)

zweiter versuch..

**Comment by jomjol** [comment]
@Scotty-89 Jetzt hat es geklappt. Kommt ins nächste Training

**Comment by Scotty-89** [comment]
@jomjol 

Cool danke am besten wäre wenn du nochmal kurz bescheid gibst wenn der "Build" durch ist ..
läuft das Täglich oder wie ?

**Comment by awor** [comment]
@jomjol anbei noch ein Satz von meiner Seit
[digits.zip](https://github.com/jomjol/AI-on-the-edge-device/files/7841857/digits.zip)
e
