### ISSUE TITLE
Problem with MQTT authetification

### ISSUE THREAD

**Issue by speerwerfer** [jomjol/AI-on-the-edge-device#464]
Hello,

I recently started using your project to read an electricity meter.
Today I wanted to activate MQTT. As a broker I use mosquitto (version 1.6.9). Only connections with username and password are allowed. I have entered the data in the config.ini of the ESP32. 
With the tools mosquitto_pub & mosquitto_sub the MQTT Broker works with username & password - with Node-Red it works too. But the ESP can't seem to establish a connection. Only when I allow a connection without authentication at Mosquittto, data is transferred from the ESP32 via MQTT.

What can be the problem?

Greetings
speerwerfer

**Comment by FotoFieber** [comment]
Is there TLS support in the code? Username/Password without encryption seems to be quite useless.

**Comment by jomjol** [comment]
No, there is no TLS support in this version.

**Comment by jomjol** [comment]
@speerwerfer to be honest: I don't use MQTT authification. It was working, but testet about a year ago. As there is no TLS support, @FotoFieber is right, it does not really make sense. I would recommend, not to use this device in an open internet environment anyway. It is not designed with any security features and I assume, there are dozends ways, to attack it.

A more sophisticated approach would be required for a commercial device, but this is not the target group of this published version.

**Comment by speerwerfer** [comment]
@jomjol this is in the Log of Mosquitto:

`1640334963: New connection from 192.168.0.30 on port 1883.
1640334963: Sending CONNACK to 192.168.0.30 (0, 5)
1640334963: Socket error on client <unknown>, disconnecting.`

**Comment by speerwerfer** [comment]
> Is there TLS support in the code? Username/Password without encryption seems to be quite useless.

I see it differently. I now have to allow an anonymous publish at Mosquitto. I would like to avoid that, or limit it to the one client only.

**Comment by jomjol** [comment]
Currently no acitivies --> closing for the time beeing

**Comment by andilee7** [comment]
+1 for TLS support

**Comment by mauriceKA** [comment]
I also would like to see MQTT TLS support
