### ISSUE TITLE
Problem beim Wechsel der Zahlen

### ISSUE THREAD

**Issue by FISO291** [jomjol/AI-on-the-edge-device#465]
So, nachdem das Alignment Problem wohl gelöst ist (Vielen Dank nochmals für deine Hilfe!) ist mir aufgefallen, dass wenn er zb die Zahl wechselt (von 6 auf 7) er ja keine Chance hat, den korrekten Wert zu erkennen (Siehe Bild). Eigentlich macht er ja ein N wenn er was nicht lesen kann. Wenn der neue Wert kleiner ist als der vorherige, dann übernimmt er es nicht.

Mir ist heute aufgefallen dass der Alte Wert irgendwie verschwunden ist? Aus der zuvor gelesenen 6 (366) und nun werdenden 7 (367) liest er eine 0. Ok, das ist ja noch ok, aber wieso ist der Alte Wert denn verschwunden?

Kann man es auch so machen, dass wenn die Digitale Zahl nicht richtig gelesen werden kann, die Analogen aber schon, (von 366 auf 367 die Analogen Zahlen mit eingerechnet werden? Wenn er was nicht lesen kann dann bleibt er ja standardmäßig beim alten Wert. Aber man könnte doch eine Option einbauen dass zumindest die Analogen weiter zählen und wenn eine Digitale Zahl nicht lesbar ist dann bleibt die auf dem alten Stand?

Die Frage die sich mir aber Stellt ist, wieso ist der alte Wert nicht mehr drin?

Ansonsten Wie immer tolle Arbeit :)

![image](https://user-images.githubusercontent.com/71070045/146760024-59efa0b0-2216-4991-b364-dae132162142.png)

**Comment by jomjol** [comment]
Also, das sieht sieht nach einer falschen Erkennung aus: aus der "6" hat er eine "0" erkannt und damit als neuen Wert aktzeptiert.
Das ist offensichtlich eine Fehlerkennung des neuronalen Netzes, das kommt vor. Zwei Dinge kannst du dagegen unternehmen:
1. Negative Raten ausschließen (Zähler läuft nicht rückwärts)
2. Maximal Rate limitieren --> wenn der Sprung zu weit ist, war es offensichtlich ein Fehler.

Beides findest du in der Config.ini

**Comment by FISO291** [comment]
Also mittlerweile ist er bei der 7. Jetzt funktioniert es wieder. Aber bei 366,8.... hat er die letzte Zahl als 7 erkannt, was ja nicht weiter schlimm ist, aber eigentlich müsste es noch 6 sein, weil die analogen Zeiger noch nicht wieder auf Null sind.

**Comment by jomjol** [comment]
Du kannst gerne deine Ziffern mitloggen und mir für die Trainingsdaten überlassen. Je Zifffer (0, 1, ..., 9) bitte 2-3 Bilder in einem Zip-File.

**Comment by DaHype** [comment]
Jemand eine Idee warum ich ständig nur Problem erhalte? Es hat eine Zeit lang wunderbar funktioniert.
Jetzt steht immer Rate to high. Was könnte ich noch optimieren?
Die Luftblasen bekomm ich leider nicht raus, schon alles versucht.

Danke

![WhatsApp Image 2023-02-22 at 09 11 38 (1)](https://user-images.githubusercontent.com/102579433/220560957-cd539b9c-e421-4916-95e0-b9065b053e5b.jpeg)
![WhatsApp Image 2023-02-22 at 09 11 38](https://user-images.githubusercontent.com/102579433/220560961-44951504-b87b-4c06-b630-0d9111638d47.jpeg)
