### ISSUE TITLE
Unable to read digits on digital meter

### ISSUE THREAD

**Issue by ausycb** [jomjol/AI-on-the-edge-device#468]
Hi,
I know that the image quality I have needs to be improved, but I am still disappointed with the results. Can anyone provide some help on what i can do here to improve the results or even if it is possible to read this meter with the current solution?

Thanks,
C
![Screenshot 2021-12-21 064530](https://user-images.githubusercontent.com/52815224/146830793-f16f391d-d16d-4445-b262-4d4bb63c7061.png)
B

**Comment by jomjol** [comment]
Sorry, but the image quality is really bad. The image is unsharp and almost no contrast:
![grafik](https://user-images.githubusercontent.com/30766535/146831059-2642eb4b-8f99-482b-8784-fa1c1eaea54a.png)
Even for a human eye it is hard see, that there is a "1".

1. You need to increase the sharpness (see wiki).
2. You need to get a more homogeneous illumination (maybe WS2812 LEDS - see wiki) 
3. Adjust the ROIs according to the settings (see wiki 3a/b)

With this 3 steps you should be able to improve the results.
