### ISSUE TITLE
Permanent falsche Werte vom Stromzähler 

### ISSUE THREAD

**Issue by mastermischke** [jomjol/AI-on-the-edge-device#469]
Hallo zusammen

leider erhalte ich permanent falsche Werte. 
Meiner Einschätzung nach sind alle Zahlen deutliche zu erkennen. Auch habe ich mehrfach versucht Fehler durch Reflexionen zu vermeiden bzw. die Kamera neu zu positionieren. 

Anbei mal ein paar Screenshots 

![3ACB7D77-6F95-431D-93EC-EBE32E6923D4](https://user-images.githubusercontent.com/5719053/146833810-fa044fd5-4fc8-4b26-91b5-cc2e7dd08b08.jpeg)
![3F296866-803D-4F32-A84E-8AE976A55E45](https://user-images.githubusercontent.com/5719053/146833813-fe1d7532-98c5-49e5-99d5-1923cd2fad9c.jpeg)
![0B5C71A1-9CAB-4CC5-BC2C-82CDC97D44FE](https://user-images.githubusercontent.com/5719053/146833814-22978ee6-cb5f-4033-aa0e-4c342884c7ef.jpeg)

Bin über jede Hilfe dankbar :-)

**Comment by jomjol** [comment]
Bitte zunächst mal die ROIs entsprechend dem Wiki einstellen. Sie sollten eigentlich alle gleich groß sein und sich an den Ziffern orientieren - Abschnitt 3a/b 
https://github.com/jomjol/AI-on-the-edge-device/wiki/Graphical-configuration

**Comment by ThomasCr** [comment]
mal ne frage: wie ist das wenn die Zahl gerade verdreht ist? Da gibt es sicher dann probleme? Wird das irgendwie abgefangen? Evtl. dadurch dass er Trackt wieviel % die Zahl schon verschoben ist um besser zu erkennen, wenn die Zahl bald schlecht zu erkennen ist - damit er dazu kein Ergebnis liefert was dann evtl. sowieso falsch ist.....?!

**Comment by mastermischke** [comment]
> Bitte zunächst mal die ROIs entsprechend dem Wiki einstellen. Sie sollten eigentlich alle gleich groß sein und sich an den Ziffern orientieren - Abschnitt 3a/b
> https://github.com/jomjol/AI-on-the-edge-device/wiki/Graphical-configuration

Erstmal danke für die Hilfe. 
Nach der Arbeit werd ich versuchen dir ROIs anzupassen. Allerdings sind sie aktuell bereits so, dass der innere Kreis die Zahl eng umschließt. Steht ja so im Wiki … ;)

über Nacht habe ich den Zähler weiterlaufen lassen. 
es sieht für mich als vollidiot so aus, als würde er Probleme mit einigen Ziffern haben und diese nicht „kennen“ ?
Anbei zwei neue Screenshots. 

![B09B184E-26FC-42A0-A148-FA2046E2B4C3](https://user-images.githubusercontent.com/5719053/146879251-103ef111-bfbe-4773-9f08-f5da94bdb587.png)
![98E9A514-1FD8-4972-9396-A35C1329F8DD](https://user-images.githubusercontent.com/5719053/146879255-c17885a0-29f5-4907-9318-60046424a597.png)

**Comment by jomjol** [comment]
Passt irgendwie noch nicht:
1) deine zifffern sind schief --> schlecht für die Erkennung
2) deine ROIs sollten alle gleich groß sein, da die Ziffern ja auch gleich groß sind

**Comment by mastermischke** [comment]
Ich werde versuchen das über die Ausrichtung in der confit anzupassen. 
Allerdings könnte das schwierig werden da ich ein fisheye objektiv nutzen muss. Der Abstand zwischen Linse und Zähler ist leider nur wenige cm …
:-/

**Comment by friedpa** [comment]
Fischauge ist nicht gut, verwende die Möglichkeit über einen Umlenkspiegel (siehe dbzgl Forumsdiskussionbeiträge) den nötigen Abstand Linse - Anzeigewerte zu generieren. Die Spiegelung der werte kann man in der config.ini kompensieren.

**Comment by jomjol** [comment]
Ich kann bestätigen, dass Fisheye wegen der Verzehrung ein dauerhaftes Problem darstellen wird.
Wenn du ein Platzproblem hast dann würde ich folgendes Design empfehlen: https://www.thingiverse.com/thing:5028229

Ich werde das hier mal schließen, da das Problem identifiziert ist. Wenn du etwas postest, sehe ich es aber trotzdem und reagiere dann.

**Comment by mastermischke** [comment]
Soooo, frohes neues Jahr :-)
Das Christkind hat einen 3D Drucker gebracht, sodass ich die Halterung drucken konnte ... Vielen Dank dafür.
Allerdings besteht noch immer das Problem ... zumindest in Teilen.
Ich nutze KEIN Fisheye mehr etc.

Ich tippe aktuell aber eher darauf, dass es sich um ein Problem in Zusammehang mit der Nachkommastelle handelt ?
![jomjom1](https://user-images.githubusercontent.com/5719053/147980661-84ebbd0f-48f6-40bd-bdaa-9a596968bd4f.JPG)
![jomjom2](https://user-images.githubusercontent.com/5719053/147980663-d8e30433-d38e-4ba6-a7f6-ba78db815a02.JPG)
![jomjom3](https://user-images.githubusercontent.com/5719053/147980665-61949cca-8dd6-44ce-8886-44fa72076d39.JPG)

**Comment by jomjol** [comment]
Hi, es gibt keine Nachkommastelle, wenn ein Rad zwischen zwei Ziffern steht, dann kommt die Ausgabe "N", da nicht klar ist, welche Zahl genau gemeint ist. Das korrigiert dann der Rest des Algos, sobald er mal weiß, wo er steht.

Dein ROIs sind noch nicht ganz sauber. Eigentlich müssen die alle gleich groß sein und auf einer Linie liegen. Details siehe hier: https://github.com/jomjol/AI-on-the-edge-device/wiki/ROI-Configuration

**Comment by Timezone840** [comment]
Guten Tag
![alg_roi (1)](https://github.com/user-attachments/assets/7227e75b-e52c-4d9f-8df6-d2ef98b212f1)
Bei mir wird in der Nachkommerstelle oft eine Falsche Zahl erkannt.
