### ISSUE TITLE
Analog digit with metal semicircle blocking half of the display

### ISSUE THREAD

**Issue by mwuerr** [jomjol/AI-on-the-edge-device#470]
my lowest analog digit has a special shape.
As it is not reliably detected I assume this so far is not part of your training data.

Are you interested in including it? if so I would gather images.

**Comment by mwuerr** [comment]
![1 3_ana4_20211221-221800](https://user-images.githubusercontent.com/10683415/147000142-89dd2661-961c-4338-8ca7-493688b41569.jpg)
![6 8_ana4_20211221-210940](https://user-images.githubusercontent.com/10683415/147000273-7b657ec0-acab-48ca-93e1-13e184469394.jpg)
2 sample images to ilustrate the type of meter.

**Comment by jomjol** [comment]
Sure, I can incorporate this type. Therefore I need a series of image (out of the log directory) with the following naming:
x.y_ANYTHING.jpg
I need about 1-2 images per reading (0.0, 0.1, ... 9.8, 9.9). For the images above it would be: 6.4 and 0.1

**Comment by zitterfritz** [comment]
Hi, is there any progress with this issue?

**Comment by jomjol** [comment]
Did you send me the images?
Sorry - but I get up to 40 mails regarding this project a day. Maybe I missed it.

**Comment by zitterfritz** [comment]
No, I'am new to your project and just installing the camera und get everything working.
 I have just the same meter and maybe I can help you with the images, when everything is installed.

**Comment by mwuerr** [comment]
Hi, no I did not yet send the images. I do have issues with power stability and the material for that just arrived last friday, installed yesterday. Then spend an hour optimizing the flash. Then everything worked. Installed it and now it is no longer reachable. Probably just a very simple problem, but obvoiusly to complicated to 2oh clock in the night. to be solved in the next days.
So I should be able to take those images soon.
But if you have the same and are faster, go.

**Comment by jomjol** [comment]
Closing the issue until further notice - please reopen in case of image etc.
