### ISSUE TITLE
ESP abgestürzt

### ISSUE THREAD

**Issue by FISO291** [jomjol/AI-on-the-edge-device#472]
gestern Abend ist mir aufgefalllen, dass wenn ich auf die Weboberflächte gehe, alles leer war. Dachte mir, ok, er macht jetzt irgendwas. Heut morgen war es schon wieder so. Also musste ich den ESP manuell booten.

Ist es irgendwie möglich, eine Funktion einzubauen (zb nachts, 3 Uhr?), die den ESP automatisch rebootet? Bzw kann man von Außen den ESP rebooten?

Ich könnte im ioBroker den State abfragen..... und dann kurz ein und ausschalten wenn der ESP nicht mehr erreichbar ist (connected -> MQTT). Aber einfacher wäre es, wenn es eine Funktion gäbe. Wäre das möglich?

**Comment by jomjol** [comment]
ja, das ist über folgende URL möglich - sofern der Webserver noch irgendwie reagiert.
`http://IP-ADRESSE/reboot`
