### ISSUE TITLE
9 is always read as a 0

### ISSUE THREAD

**Issue by ihrigb** [jomjol/AI-on-the-edge-device#473]
Hi,

I got the issue that a nine is always being read as a 0. Also the four is sometimes a 0, but not very often. I tried to improve the configuration multiple times, but no improvement here.
![alg_roi](https://user-images.githubusercontent.com/3423161/147109691-e74d8342-4735-414d-bc3c-c23b07784a74.jpg)
![main_dig5](https://user-images.githubusercontent.com/3423161/147109694-c1c15693-6a66-41fe-99f6-4b2a29fa44d3.jpg)
.

**Comment by jomjol** [comment]
I've put your 9 to the next training round.

**Comment by ihrigb** [comment]
@jomjol when can I expect this to be in an update?

**Comment by jomjol** [comment]
Somewhere during my christmas holidays until the first week of January
