### ISSUE TITLE
MQTT Topic erlaubt keine / am anfang

### ISSUE THREAD

**Issue by DerDoubleD** [jomjol/AI-on-the-edge-device#474]
Leider wird ein Fehler ausgegeben wenn ich /SmartHome/bal/blub als MQTT Topic angebe.
Meine ganze Struktur ist aber so aufgebaut.
Kann man das bitte zukünftig erlauben?!

Danke für das tolle Projekt!!!

**Comment by jomjol** [comment]
Corrected in the newest "Rolling" version and working:
![grafik](https://user-images.githubusercontent.com/30766535/147201700-466baafb-24a6-4a93-b496-68ae5949f583.png)
 Only the html.zip needs to be updated.
