### ISSUE TITLE
Eine Stelle wird immer falsch ausgewertet

### ISSUE THREAD

**Issue by DerDoubleD** [jomjol/AI-on-the-edge-device#475]
Immer die Vorletzte Stelle wird falsch ausgewertet.
Egal welche Zahl dort steht. Es ist immer falsch.
Was könnte ich machen um zu debugen was da falsch läuft?

![WZ_fehler](https://user-images.githubusercontent.com/47006370/147154463-7491beac-ff03-4b68-ac79-453d7f0d549c.jpg)
![WZ_fehler1](https://user-images.githubusercontent.com/47006370/147156728-f7ee5aab-a4bd-41d1-a7b6-5c3ef3e5ce70.jpg)

Danke!

**Comment by jomjol** [comment]
Dein ROIs sind zu groß. Hast du sie gemäß Abschnitt 3a/b aus https://github.com/jomjol/AI-on-the-edge-device/wiki/Graphical-configuration eingerichtet?
Du muss Höhe und Breite anpassen, so dass das innere Rechteck genau um deine Ziffern passt.

**Comment by DerDoubleD** [comment]
Danke für deine Antwort.
Es ist so konfiguriert.
Ist das nicht richtig?

![dig6](https://user-images.githubusercontent.com/47006370/147273454-9735dc8e-b520-4453-a8c6-822b39cf3000.jpg)
![dig7](https://user-images.githubusercontent.com/47006370/147273464-ddff81be-ce48-4141-afce-05d48ee3189a.jpg)

**Comment by jomjol** [comment]
Doch im Prinzip schon, aber irgendwie ist deine Orientierung immer noch schief.

Ich habe jetzt mal hier eine Beschreibung gemacht. Wenn du weiterhin Probleme hast, kannst anhand dieser Beschreibung auch deine Ziffern fürs Training sammeln: https://github.com/jomjol/AI-on-the-edge-device/wiki/ROI-Configuration
