### ISSUE TITLE
5 analog values?

### ISSUE THREAD

**Issue by kleinmantara** [jomjol/AI-on-the-edge-device#476]
Hi,

tanks for the nice work. I have 5 analog values und i don't know why. In the config are only ana1...ana4. And is it correct that the last digital digit cannot be evaluated?

```
[Digits]
Model = /config/dig1330s1q.tflite
;LogImageLocation = /log/digit
;LogfileRetentionInDays = 3
ModelInputSize = 20 32
main.dig1 228 24 45 100
main.dig2 272 22 45 100
main.dig3 317 22 45 100
main.dig4 359 24 45 100
main.dig5 402 21 45 100

[Analog]
Model = /config/ana0910s3_longq.tflite
;LogImageLocation = /log/analog
;LogfileRetentionInDays = 3
ModelInputSize = 32 32
main.ana1 422 190 118 118
main.ana2 346 310 116 116
main.ana3 205 324 118 118
main.ana4 99 223 120 120
```

<img width="977" alt="Bildschirmfoto 2021-12-23 um 10 47 08" src="https://user-images.githubusercontent.com/22788087/147222175-ab20e4d4-b42d-4678-a8f1-f081989d2bd7.png">

**Comment by jomjol** [comment]
That's because you have extended resolution activated:

![grafik](https://user-images.githubusercontent.com/30766535/147228145-56d1a1eb-5153-43df-874a-e291bcda5479.png)


This is usingn a subidigt information for the last value: Reading of x0,0001 --> 7.8
