### ISSUE TITLE
new MQTT Topic

### ISSUE THREAD

**Issue by speerwerfer** [jomjol/AI-on-the-edge-device#479]
Hello ,
can you imagine to extend the MQTT Topics with the value RAW Value? 
I would like to react in Node-Red to the situation when the letter N appears in the RAW Value.

**Comment by speerwerfer** [comment]
In the HTTP GET response from http://IP-ADDRESS/json I see the RAW Value already.

**Comment by jomjol** [comment]
raw value is now implemented in the newest rolling branch as well (mqtt topic as well as json)
