### ISSUE TITLE
Anpassung neues Log

### ISSUE THREAD

**Issue by MMeinhardt1** [jomjol/AI-on-the-edge-device#48]
Hallo @jomjol,

habe gerade die neue Version installiert, das tageweise speichern des Logs finde ich sehr gut (ich hoffe das klappt so).
Und da hätte ich dann auch direkt ne Frage / Bitte / Feature Request, ich fände es ganz praktisch das aktuelle Log als "current.log" oder ähnlich zu speichern und wenn der Tag dann rum ist der Datei den entsprechenden "Datumsnamen" des Vortags zu übergeben. Das ganze hat den Hintergrund das man sich das Log in irgendeiner VIS anschauen kann und der Name des Logfiles für den aktuellen Tag eben immer der gleiche wäre.

Daher auch hier jetzt die Bitte und Frage nach der Umsetzung?

Danke

**Comment by jomjol** [comment]
Hallo @MMeinhardt1,

ich habe deine Bitte umgesetzt. Es gibt jetzt folgende URL, die dann immer auf das gerade aktuelle Logfile umgerouted wird:

`http://IP-ADRESS/logfileact`

Ist in der aktuellen Rolling (Datum von heute) implementiert.

Gruß,
  jomjol
