### ISSUE TITLE
Problem mit Analog Zeiger

### ISSUE THREAD

**Issue by brightcolor** [jomjol/AI-on-the-edge-device#481]
Hallo,

zu erst - geiles Projekt!

Die oberen Rollen werden sehr gut erkannt. Nur die 4 analogen Zeiger nicht - das ist recht random was da erkannt wird.

Erschwerend kommt da sicher noch hinzu, dass die Zeiger nicht identisch sind. Gibt es eine Möglichkeit die Erkennung zu verbessern? Ich habe das Logging bereits eingeschaltet, sodass da demnächst sicher ein paar Samples verfügbar sind.

Hattest du schonmal solche Zeiger?

![image](https://user-images.githubusercontent.com/9386956/147390072-5ad8ceeb-caa7-44cb-bea1-1da350d44f48.png)

Frohe Weihnachten!

MfG

**Comment by jomjol** [comment]
Hi, solche Zeiger hatte ich nocht nicht und das könnte tatsächlich schwierig werden. Eventuell benötigst du da ein ganz speziell nur für dich geteachtes Netz.

**Comment by brightcolor** [comment]
Hi,

danke für die schnelle Rückmeldung. 

Kann ich das selbst machen, oder muss ich dir das schicken? Ich hatte hier irgendwo in deinem Repo (?) eine Verlinkung zu einem Setup Tutorial gefunden - kann es aber nicht wieder finden. 

Wer mir den Zähler noch mal genauer ansehen - wie es scheint sind die Zeiger ja auch nicht zentriert - je weiter rechts umso dezentraler. Sieht nach einer verschobenen Scheibe oder so aus. Vielleicht auch B-Ware ^^

mfg

**Comment by jomjol** [comment]
Ja die sind dezentriert und sehr blass. Da habe ich aktuell wenig Hoffnung. Du kannst es selbst probieren, ist aber nicht ganz trivial. Aktuell sind die Skripte mit nur wenigen Kommentaren hier veröffentlicht: https://github.com/jomjol/neural-network-analog-needle-readout

**Comment by brightcolor** [comment]
Ah danke. 

Werds mal versuchen.

Könnte man den Kontrast der Zeiger ggf. erhöhen? Gibt es dazu schon ein Setting?

**Comment by jomjol** [comment]
Nein - da musst du mit der Beleuchtung optimieren. Für mich sieht das Glas milchig aus, dann kannst du da nicht viel machen :-(

**Comment by jomjol** [comment]
Länger keine Aktivitäten, schließe daher erstmal vorerst.
