### ISSUE TITLE
Specified Private Time Server but device still call pool.ntp.org

### ISSUE THREAD

**Issue by grimmaldus** [jomjol/AI-on-the-edge-device#482]
Firmware:
v9.2.0

Description:
I've specified my own time server in configuration however the AI-on-the-edge-device still calls pool.ntp.org. 
`[System]
TimeZone = CET-1CEST,M3.5.0,M10.5.0/3
TimeServer = <PRIVATE TIME SERVER>
;AutoAdjustSummertime = 
Hostname = watermeter
;SetupMode = false`

FW Logs:
`IN=<REDACTED> OUT=<REDACTED> MAC=<REDACTED> SRC=<AI-on-the-edge-device IP> DST=<pool.ntp.org IP>`

**Comment by jomjol** [comment]
This is not a bug, but by purpuse. Right at the beginning, even before any ini-file is read the software tries once to contact a general time server. This is to make it possible to get a time as early as possible.
The access to the internal time server is only used later during the booting, when the ini-files are processed. If you block the external access, that is not a problem, only the log files etc. will use a wrong time until the internal is set.

**Comment by grimmaldus** [comment]
What time do you use in your flow and value calculations. I can confirm that this has impact at least on log files where are wrong MQTT values such as uptime.

**Comment by jomjol** [comment]
Rate value is based on the difference between the last and the current value. The difference should not depend on the absolute time. Never the less I use the time from a standart time server, unless specified differently in the config.ini

**Comment by grimmaldus** [comment]
Thanks, in this case there shouldn't be any significant impact at all I can live with that negative uptime information. I was just curious since at first glace it looked like there is a correlation between negative uptime and wrong value (it has always showed up when previous reading had negative uptime - issue #530 ). I will look at it more thoroughly this weekend maybe it's a HW issue.
