### ISSUE TITLE
Config-Prozess stürzt ab während der Ersteinrichtung

### ISSUE THREAD

**Issue by Ragna2000** [jomjol/AI-on-the-edge-device#484]
Hallo,

trotz meines Problems auf das ich gleich eingehen werde, finde ich das Projekt an sich sehr sehr GUT!
Ich bin mir sicher das bei mir eine entscheidende "Kleinigkeit" für die Problem sorgt, das sich hoffentlich lösen lässt.

Wie im Titel beschrieben, komme ich leider nicht dazu die Erst-Konfiguration durchzuführen da sich bereits beim zweiten 
oder spätestens 3. Menüschritt die Ersteinrichtung aufhängt so das man nichts mehr anklicken kann. 
Da hiilft dann nur Stecker ziehen. Leider kommt man dann auch nicht viel weiter.

Ab diesem Menüpunkt friert alles ein, sogar auch wenn man im Schritt zuvor (nur als Test) das Bild nicht aufnimmt, 
sondern nur auf "Next" weiter klickt:
![image](https://user-images.githubusercontent.com/85805060/147465811-c13963e0-c526-4acc-aaea-82969df3ef48.png)

wlan.ini
![image](https://user-images.githubusercontent.com/85805060/147467291-06e192d8-4e6b-4aca-9c0b-8b6831147050.png)

config.ini
![image](https://user-images.githubusercontent.com/85805060/147467446-9f7cd32b-336f-4e5d-8f86-72042e96a6e1.png)

########################################

Hier ein paar Details zum Vorgehen:
- Einrichtung mit Windows 10 64bit PC

- zum Flashen benutze ich "Flash Download Tools" (Windows PC | V3.9.2) 
von hier: https://www.espressif.com/en/support/download/other-tools?keys=

- Flashvorgang ordnungsgemäß abgeschlossen mit "STOP" am Ende und dann erst getrennt (keinerlei Fehler):
![image](https://user-images.githubusercontent.com/85805060/147466446-5770220e-e643-45cb-938f-de9414dcbcab.png)

- Einsatz getestet mit noName SD Karte mit 8Gb, sowie mit SanDisk 16GB (beide FAT32 Format) => immer das gleiche Ergebnis

- Netzteil: 24W Dual-USB, 5V

- getestet mit 20cm kurzem MikroUSB Kabel sowie mit 2m Kabel (beide geschirmt)

Ich habe das Gefühl das sobald ein mal die Kamera angesteuert wurde, sich danach das folge Menü aufhängt.
Bin für jegliche Tipps dankbar. Würde es gerne ans Laufen bekommen um mit dem JSON Aufruf 
http://192.168.178.167/json
...die Werte abzuholen für mein HomeMatic System.

**Comment by speerwerfer** [comment]
Was sagt denn die Debugausgabe des Seriellen Ports? Die hat mir bei meinem ersten Problem den Hinweis gegeben, das mein Modul nicht kompatibel ist. Vielleicht kommen da ja noch Infos raus ...

**Comment by Ragna2000** [comment]
da ich noch Laie bin, darf ich fragen wie/wo ich das einsehen kann?
Gerät wieder an PC anschließen via Kabel und dann auf die SD-Karte in ein Verz. nachschauen?
(Sorry für die Basic Frage).

**Comment by Ragna2000** [comment]
...habe übrigens das Modul hier gekauft und hoffe das es kompatibel ist?!?
https://www.amazon.de/gp/product/B08P1NMPLL/ref=ppx_yo_dt_b_asin_title_o05_s01?ie=UTF8&psc=1

**Comment by Ragna2000** [comment]
der Flashvorgang lief denke ich sauber...

![image](https://user-images.githubusercontent.com/85805060/147471092-2e941ca0-03bb-4eee-b4a5-b072ffab4664.png)

**Comment by jomjol** [comment]
Das Logfile bekommst du, indem du den Ausgang der seriellen Schnittstelle mit demselben Tool mitschreibst, mit dem du auch das Flashen gemacht hast. Du solltest einen COMx Port haben und dort einfach mittels Terminalprogramm den Ausgang vom Booten bis zum Absturz mitschreiben.

**Comment by Ragna2000** [comment]
ich entschuldige mich in voraus für die Frage, aber ich weiß leider nicht wie ich das "mitschreiben" sollte bzw. was konkret wo einzustellen ist damit das Booten mitgeloggt wird?

Verwenden tue ich das ESP32 Tool V3.92 wie im Screen oben zu sehen. 
Ich kann leider keine Settings im Tool finden dafür was Du beschreibst, sorry.

Ich lese mich gerne ein (bevor ich dazu viele Basics-Fragen hier stelle) wenn Du dazu einen Link hättest für die Einsteiger. 
Danke Dir.

**Comment by jomjol** [comment]
Hallo,
hier findest du eine Anleitung für Linux und Windows: https://docs.espressif.com/projects/esp-idf/en/latest/esp32/get-started/establish-serial-connection.html

**Comment by Otti12345** [comment]
Probiere mal das andere Modul, hatte schon öfters gelesen das bei vielen die dieses Doppelset gekauft hatten nur einer der beiden einwandfrei funktionierte ...
https://www.youtube.com/watch?v=mDIJEyElkAU schau mal bei 20:30 Min

**Comment by ThomasCr** [comment]
Ich habe auch ein ähnliches verhalten und vermute auch ein Hardware Problem dahinter.

Bei mir hatte anfangs auch noch alles Funktioniert. Da ich aber nicht fertig damit war und neues Gehäuse wegen zu viel Spiegelung gedruckt hatte, Weihnachten dazwischen kam, usw. hatte ich es erstmal auf Eis gelegt. 

Jetzt nachdem ich wieder dran weiter gebaut hatte ging auf einmal die SD Karte nicht mehr (Rode LED blinkte immer). Also hab ich sie am PC wieder in das Lesegerät gesteckt und dort wurde sie auch nicht mehr erkannt. Also die zweite genommen, auf 4 GB mit Fat16 formatiert und alles wieder drauf kopiert. 

Dann viel mir auf, dass die LED nach dem Boot gar nicht mehr aus geht. Das Webinterface kam auch nicht. Da ich auch zwei Module hatte, habe ich die CAM von dem einen auf den anderen Umgebaut und siehe da - die LED ging wieder aus. 

Trotzdem gibt es jetzt im Webinterface des öfteren Hänger wenn ich auf die Camera zugreife. Es scheint als wenn das Modul irgend einen Schaden hat.

Heute Abend werde ich halt noch das zweite Modul "flashen" und damit nochmal probieren.

Irgendwie scheint die Hardware nicht ganz zuverlässig zu sein. Ich habe gesehen da gibt es noch ein paar andere ESP32-Modelle mit CAM. Keine Ahnung ob die auch Kompatibel wären.

z.B. die mit USB-C Schnittstelle:
https://www.ebay.de/itm/402654414081

Oder mit Display und Antenne:
https://www.ebay.de/itm/255283295128

Oder mit ESP32-WROOM-32E
https://www.ebay.de/itm/27491152317

So wie ich das verstanden habe, sollten die gleich sein....
https://www.espressif.com/en/products/modules

Mal schauen, wie sich das entwickelt... ich teste erst mal mit dem 2. brauche aber trotzdem dann noch einen neuen, da ich noch einen zweiten Wasserzähler habe...

**Comment by Ragna2000** [comment]
Hi all,

danke für Euren Input. 
Mit dem zweiten Modul was in der Lieferung dazu kam, läuft es zumindest etwas besser, wenn auch nicht perfekt.
Nach 3-4 Versuchen, habe ich die Konfiguration dann doch noch abschließen können.
Es scheint wirklich an dem Modul selbst zu liegen, da das selbe Setup an einem Gerät läuft und das selbe am anderen gar nicht.

Anderer Test mit dem zweten mitgelieferten ESP32 Modul (das noch nicht läuft):
verbunden als COM3 (bei mir unter Win10) 
mit dem Putty Tool wie folgt:
![image](https://user-images.githubusercontent.com/85805060/147666761-2e238916-ad7e-4bd1-a345-8e89850183c1.png)

Fakt ist, während das Flashtool via denselben COM3 verbunden ist, kriegt Putty nichts mit und das Fenster bleibt leer:
![image](https://user-images.githubusercontent.com/85805060/147667049-c72fc5d3-e064-4509-9717-b62a9616e4df.png)

Was mache ich noch falsch, das kein Logging angezeigt wird in Putty?


1)  ESP32 via USB Kabel verbinden

2) Putty starten & via COM3 verbinden

3) Flashtool  / Flashvorgang  starten

**Comment by speerwerfer** [comment]
PuTTY und FlashTool parallel wird nicht gehen. Da greift vermutlich das FlashTool auf den COM Port zu und Putty bekommt nichts mit. Aber darum ging es mir auch nicht. Interessant ist, was bei Putty ankommt, wenn du den ESP32 startest, und die Konfig durchführen willst.

**Comment by juergen852** [comment]
*SOLVED*
Had the same problem.
Cause: Camera is defect
Solution: Change camera module.
(Had 2 units, one working, one not, swapped camera --> both worked.)

From the log
14:55:33.911 -> [0;32mI (16839) server_GPIO: GPIO init comleted, handler is disabled[0m
14:55:33.911 -> Flashdauer: 5000
14:55:42.912 -> [0;31mE (25859) camera: **Failed to get the frame on time**![0m
14:55:42.912 -> [0;31mE (25859) server_part_camera: CaptureToBasisIma**ge: Camera Capture Failed[0**m
14:55:42.946 -> [0;32mI (25859) server**_ota: Reboot in 5sec**[0m
14:55:47.928 -> I (30859) wifi:state: run -> init (0)
14:55:47.928 -> I (30859) wifi:pm stop, total sleep time: 21207780 us / 27561388 us

**Comment by juergen852** [comment]
ToDo: Instead of reboot, web interface could show error message.

**Comment by Ragna2000** [comment]
kleine Alternative (die aber zu prüfen ist):
bei dem einem erstmal nicht funktionierende Modul, habe ich das Kamera-Band aus dem 
Schnapp-Adapter gelöst (in dem die Klemme nach oben geklickt wird).
Dann ist die Kamera lose.

Wenn man das Band wieder vernünftig reinklemmt, geht das gesamte Modul wieder.
Das ist sicherlich nicht die Lösung für alle kaputten Kamera-Module, aber bei mir hat es von 4 Modulen bei einem geholfen.

Ob der Amazon-Anbieter die Retoure annimmt da wg der Kamera reklamiert wird, wird sich die Tage noch zeigen ;-)

Da ich zwei Sets gekauft habe (dachte es ist immer ein Modul in der Verpackung drinnen da tolle Amazon-Beschreibung....)
hatte ich somit 4 Module zum testen.
Es zeigte sich (bei mir zumindest) das immer das hintere Modul in der Schachtel funktioniert und das vordere was
zuerst im Karton liegt nicht.

Kann ein Zufall sein, daher sollte nur als Info am Rande dienen.

**Comment by ThomasCr** [comment]
>Es zeigte sich (bei mir zumindest) das immer das hintere Modul in der Schachtel funktioniert und das vordere was
zuerst im Karton liegt nicht.

Ich vermute dass die empfindlich auf Druck reagieren..... die Kamera die bei mir ja zuerst ging, habe ich "möglicherweise" durch etwas zu viel druck geschrottet... ist halt nur eine Vermutung, aber ich könnte es mir vorstellen...

Mal sehen, ich versuche gerade schon das zweite Modul zu flashen und da hapert es auch irgendwie.... das flashen (mit flash_download_tool_3.9.2.exe) dauert Ultra lange und da laufen ca 100 Zeilen mit ........ (Pünktchen) durch.

Hab es irgendwann abgebrochen und schau mal ob ich es mit VS Code gebaut und geflasht bekomme. Hab ich sowieso schon drauf gehabt....

**Comment by jomjol** [comment]
@ThomasCr @Ragna2000 @juergen852 @ThomasCr 

Also ich habe die Tage intensiv an dem Thema gearbeitet und zwei Effekte auseinander dividieren können:
1. Speicherleck in der Software
2. Instabile und tlw. nicht funktionierende Hardware.

zu 1)
seit gerade gibt es eine neue "Rolling" Version, die deutlich stabililer laufen sollte. Ich habe die Toolchain upgedated auf ESP-IDF 4.3 und in dem Zug ein größeres Speicherleck beseiten können

zu 2)
Ich jetzt mal meine gesamte Hardware durchgetestet und festgestellt, das ein bestimmter Kameratyp bei mir sehr instabil bis gar nicht funktioniert. Die Ergebnisse sammle ich auf folgender WIKI-Seite: https://github.com/jomjol/AI-on-the-edge-device/wiki/Hardware-Compatibility
Damit könnt ihr eure Devices gerne mal abgleichen und ergänzen.

Ich würde euch empfehlen testweise auf die neue Rolling zu flashen. Wenn sich das bei meinen 4 Devices als stabile herausstellt, werde ich damit die Version 10.0 in kürze releasen.

Gruß,
  jomjol

**Comment by juergen852** [comment]
I have two OV2640 - Camera with DC-26 40-V3

One of them is working with V9, the other does not work. V10 did not change anything.
See enclosed boot log [V10-bootlog.txt](https://github.com/jomjol/AI-on-the-edge-device/files/7795860/V10-bootlog.txt)
.

**Comment by juergen852** [comment]
BTW: V10 still says "cpu_start: App version:      0.0.9.3"

**Comment by juergen852** [comment]
V10 App-Version:
10:41:03.473 -> 1672) cpu_start: Project name:     esp32cam-server-only
10:41:03.473 -> (1678) cpu_start: **App version:      0.0.9.3**
10:41:03.473 ->  (1683) cpu_start: Compile time:     Dec 31 2021 08:56:50
10:41:03.507 ->  (1690) cpu_start: ELF file SHA256:  51fb6215cb2f3968...
10:41:03.507 ->  (1696) cpu_start: **ESP-IDF:          4.3.1**

Observations on my device with the non-working camera:
V9: White LED was light for 5 seconds before crash.
V10: White LED does not light up.

Error "Failed to get frame on time:"
  Can you double the waiting-time ?


SD-Card LOG:
2021-12-31T11:14:08: ================ Main Started ==============
2021-12-31T11:14:08: =========================================
2021-12-31T11:14:17: Camera cannot be initialzed. System will reboot.
2021-12-31T11:14:17: Reboot in 5sec
2021-12-31T11:16:20: Time zone set to CET-1CEST,M3.5.0,M10.5.0/3
2021-12-31T11:16:20: ===============================
2021-12-31T11:16:20: ================ Main Started =================
2021-12-31T11:16:20: ===========================
2021-12-31T11:16:29: Camera cannot be initialzed. System will reboot.
2021-12-31T11:16:29: Reboot in 5sec

SERIAL-LOG:
11:16:24.612 ->  (11497) camera: Detected OV2640 camera
11:16:24.612 ->  (11497) camera: Allocating 1 frame buffers (150 KB total)
11:16:24.645 ->  (11507) camera: Allocating 150 KB frame buffer in OnBoard RAM
11:16:26.306 ->  (13167) BLINK: Blinken - done
11:16:29.329 ->  (16197) camera: **Failed to get the frame on time!**
11:16:29.329 ->  (16197) main: esp_camera_fb_get: Camera Capture Failed
11:16:29.329 -> Logfile opened: /sdcard/log/message/log_2021-12-31.txt
11:16:29.329 ->  (16197) server_ota: Reboot in 5sec
11:16:29.329 -> Logfile opened: /sdcard/log/message/log_2021-12-31.txt
11:16:34.344 -> I (21207) wifi:state: run -> init (0)
11:16:34.344 -> I (21207) wifi:pm stop, total sleep time: 14245102 us / 18696643 us
11:16:34.344 -> 
11:16:34.344 -> W (21207) wifi:<ba-del>idx
11:16:34.344 -> I (21207) wifi:new:<6,0>, old:<6,0>, ap:<255,255>, sta:<6,0>, prof:1
11:16:34.344 -> ets Jun  8 2016 00:22:57
11:16:34.344 -> 
11:16:34.344 -> rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
11:16:34.344 -> configsip: 0, SPIWP:0xee

**Comment by jomjol** [comment]
This is a problem of the camera.
The APP version shown during booting is not correct - I should update it time by time.

**Comment by Ragna2000** [comment]
Hat jemand einen Shop-Link zu einem ESP32 Modul mit der Kamera das gar keine Probleme mit der o.g. Software macht?
