### ISSUE TITLE
Temperature sensor

### ISSUE THREAD

**Issue by SKOJau** [jomjol/AI-on-the-edge-device#485]
Would it be possible to connect an temperature sensor to the ESP32-Cam?
If yes could you implement this in your codebase?

I would need an temperature sensor like an DS18B20 in the room, so why not use the ESP32 for the watermeter that is allready there ;)

**Comment by jomjol** [comment]
Technically yes, but the firmware is already rather crowed and only 2 free GPIOs are available. Therefore I'm not going to implement this. Rather buy a second device for 5 EUR and implment it independendly.
