### ISSUE TITLE
Does this support gas meters with half foot and two foot dials?

### ISSUE THREAD

**Issue by poldim** [jomjol/AI-on-the-edge-device#486]
Below is my PG&E gas meter.  I have figured out a way to scrape daily usage from the utility's website, but wondering if I can use your project to get more granular usage data.   The issue is determining and tracking the digits that would exist below the smallest 1,000 dial based on the two half-foot and two-foot dials.

My guess is that you would have to create a variable to track 0-999 cubic feet based on the two cubic feet dial.  Maybe take an image every 30 seconds to keep track of the counter since it needs to have multiple captures before a full rotation.

Let me know if you need some training images for this.

![image](https://user-images.githubusercontent.com/16869713/147492335-261c1594-e59e-4fda-ba0c-359c504acb1d.png)

**Comment by jomjol** [comment]
How does your foot, respecitvly two feet work? I can read out the meters, e.g. as subdigits. But the system cannot accumulate the rotations until 1000 are reached.
The reading frequency is about every 2-3 minutes. As your counters are running clock and counterclock wise, this is not supported yet. That would need more changes in the firmware.

**Comment by poldim** [comment]
The general purpose of the half and two foot indicators are for diagnostics. For example, you can check how much gas one of your applicances is using by turning all of them off except the one you want to test and then timing the rotation of the half or two foot dials. Here is an example: https://hvactechhangout.com/home/system-measurements/how-to-clock-a-gas-meter/

The two foot dial has to make 500 rotations for every rotation of the 1000 foot dial. But you can infer which tenth of the 1000 foot dial you are in, so you really need to be able to track the 50 rotations of the two foot dial within that tenth. 

Is it possible to increase the frequency from 3 min to 10 sec or is this limited by cpu?

**Comment by friedpa** [comment]
The fastest cycle I was ever able to measure was 2:56min on my ESP hardware

**Comment by jomjol** [comment]
10 sec is not possible. I have commerical variants of this code, that can detected specific features within 1.5seconds, but only one feature, no alignment, ... totally different firmware structure and flow.
For this application I don't see a chance to support half and two foot indicators.

**Comment by johnboiles** [comment]
@poldim I have a very similar meter did you ever find a good solution? I've set up measuring for the other dials, but as you identify it's not super useful for seeing in-the-moment usage rates.

Perhaps it's a different project but maybe there's a fast way to just watch for the zero crossing on the half foot to determine flow rate.

![IMG_0172 2 Medium](https://user-images.githubusercontent.com/218876/221391863-7a64edd5-054a-45c8-8235-ba51189e6005.jpeg)

**Comment by poldim** [comment]
> @poldim I have a very similar meter did you ever find a good solution?

No, I ended up installing a flow gauge with a pulse output to get my own readings.
