### ISSUE TITLE
Analog wird oft falsch erkannt...

### ISSUE THREAD

**Issue by Expello** [jomjol/AI-on-the-edge-device#487]
Hi,

manche Analogwerte werden für mich nicht nachvollziehbar falsch erkannt, wie in diesem Beispiel der zweite Analogwert wird als 1,9 erkannt, er ist aber recht deutlich bei der 3 zu sehen.

Kann ich selbst noch etwas optimieren?

![image](https://user-images.githubusercontent.com/18443885/147509712-da35963a-66ed-44a5-a4d4-239b21496101.png)

Vielen Dank und viele Grüße
Expello

**Comment by jomjol** [comment]
Hi,
mir erscheint die Schärfe und der Kontrast in deinem Bild sind eher noch nicht sehr gut sehr schwach. Insbesondere das Rot ist sehr blass - zum Vergleich:
Dein Bild:
![grafik](https://user-images.githubusercontent.com/30766535/147563461-32a38b25-e858-4924-83db-a7a306af4795.png)
Trainingsbild: 
![grafik](https://user-images.githubusercontent.com/30766535/147563527-36799b85-f6a3-44e0-b2ad-8ea9e313b906.png)

Es sieht so aus, als ob du einen weißen Innentubus verwendest. Bild könnte besser werden, wenn er innen schwarz ist (einfach Tonpapier verwenden).
