### ISSUE TITLE
Image rotiert

### ISSUE THREAD

**Issue by gitiegit** [jomjol/AI-on-the-edge-device#488]
Teilweise rotiert das Bild, dann ist es wieder korrekt.

![image](https://user-images.githubusercontent.com/24435657/147546599-1d7135c5-8829-420e-bf67-d0ce651ed96a.png)

master - v9.2.0 - 2021-12-02

**Comment by friedpa** [comment]
Wie schon von jomjol mehrmals geschrieben, kommt es darauf an, wann man den Webpage refresh macht, oder automatisch von der Webpage getriggert (alle 5 Minuten) wurde, ob das Bild schon "fertig" gedreht wurde oder nicht. Daher kommen diese, für die Auswertung aber nicht verwendete, "Zwischenbilder".

**Comment by jomjol** [comment]
@gitiegit : Ursache hier ist einen andere. Der Kontrast in deinem zweiten Referenzmarke ist zu schlecht. Ich vermute, es ist dieser helle Korb auf hellenm Grund :-). Wenn er das nicht ordentlich findet, dann gibt es irgendwelche Koordinaten und die Ausrichtung des Bildes geht schief. Da musst du dir etwas anderes suchen oder einfach einen weißen Sticker mit schwarzer Markierung auf das Glas kleben und den dan verwenden.

**Comment by gitiegit** [comment]
Ok habe eine andere Referenzmarke genommen und werde mal testen.
![image](https://user-images.githubusercontent.com/24435657/147660480-8eb62cb9-d163-4e24-91b1-9476b32c898d.png)

**Comment by gitiegit** [comment]
Ja das scheint es gewesen zu sein.
Dankeschön
