### ISSUE TITLE
Digitale Kommastellen

### ISSUE THREAD

**Issue by Screambear** [jomjol/AI-on-the-edge-device#489]
Hallo,

ich habe 5 digitale Hauptstellen und 3 digitale Nachkommastellen sowie eine vierte Analoge.

Wie bekomme ich das richtig konfiguriert?

Danke

**Comment by Screambear** [comment]
Nach lange suchen in der Doku durch Zufall drauf gestoßen.

**Comment by thost96** [comment]
Falls jemand in der Zukunft diesen Beitrag findet, hier ein Link zur Doku: https://github.com/jomjol/AI-on-the-edge-device/wiki/Configuration-Parameter-Details#postprocessing
