### ISSUE TITLE
Value eine Ziffer zu viel / Kein Raw - Wert

### ISSUE THREAD

**Issue by allgrinder** [jomjol/AI-on-the-edge-device#490]
Hallo zusammen,

erstmal Danke für das super Tool!
Gleichwohl habe ich ein paar Probleme. Ich habe 4 analoge Zeiger - Es werden manchmal aber 5 Nachkommerziffern angezeigt
![Unbenannt](https://user-images.githubusercontent.com/75566736/147656883-8b112224-e2fc-4f0a-9d38-f97bf9e7232e.JPG)

Des Weiteren habe ich immer wieder Sprünge drin... und dann kein RAW-Wert.
![Unbenannt1](https://user-images.githubusercontent.com/75566736/147657300-b5db055d-3c36-445f-be06-656d6c83b4a0.JPG)

Danke und viele Grüße
Johannes

**Comment by allgrinder** [comment]
Ps.: Gibt es zufällig eine Anleitung wie die analogen Zeiger trainiert werden können? Der x0,0001 ist leider etwas schlechter in der Erkennungsrate. Eine 8 ist eine 3 etc. Die restlichen drei Zeiger werden zu 99Prozent erkannt

**Comment by jomjol** [comment]
Die weitere Stelle kommt von der Einstellung.
![grafik](https://user-images.githubusercontent.com/30766535/147742769-50898d24-9157-4ce5-8fd9-bcb6ded5db62.png)
Dann wird die Nachkommastelle beim Digitalisieren der Zeiger für die letzte Stelle mit verwendet.

Teaching der Zeiger siehe hier: https://github.com/jomjol/neural-network-analog-needle-readout

Deine Zeiger sollten aber eigentlich gut funktionieren, da diese Art schon mit enthalten ist. Deine ROIs sind aber nicht ganz optimal eingestellt:
Digital siehe hier: https://github.com/jomjol/AI-on-the-edge-device/wiki/ROI-Configuration
Analog: du solltest darauf achten, dass dein Zeiger gut in der Mitte ist - siehe z.B. x0,0001 ist zu hoch.

**Comment by allgrinder** [comment]
Hey,
Danke für deine Rückmeldung!
Die FUnktion ExtendedResolution ist deaktiviert. Ich habe dies aber auch nicht verändert. Die zusätzliche Zahl ist aktuell verschwunden.
![Unbenannt](https://user-images.githubusercontent.com/75566736/147751352-f16fbe30-1b9e-4f4e-8f86-51fda014d2ff.JPG)
Können die Probleme auch durch die PostProcessing-Einstellungen erzeugt werden? Diese habe ich angepasst,

Danke nochmals für den Hinweis mit den ROI. Diese habe ich nochmals überarbeitet. Wie gehe ich aber mit der letzten Ziffer um? Diese ist ja ständig in Bewegung?

**Comment by jomjol** [comment]
Welche Ziffer meinst du? Die digitale oder den Zeiger?

**Comment by allgrinder** [comment]
Ich meine die letzte digitale Ziffer. In meinem Fall die 2 die zu einer 3 wird.

**Comment by jomjol** [comment]
Wenn die zwischen zwei Werten steht, dann kommt da aktuell im Rohwert ein "N" und er ersetzt es durch den letzten bekannten Wert.

**Comment by allgrinder** [comment]
Danke für d8ie Info! Also kann ich die PostProcessing-Einstellungen deaktivieren?

**Comment by jomjol** [comment]
ja
