### ISSUE TITLE
Messwert Syntax und seine Dezimalstellen

### ISSUE THREAD

**Issue by Ragna2000** [jomjol/AI-on-the-edge-device#491]
Der Wasserzähler steht bei "0298" für die vier "Dig1bis4" Stellen die in der Konfig. eingestellt sind.
Als darausgelesene Value zeigt es aber den Wert "29800"

![image](https://user-images.githubusercontent.com/85805060/147667893-d5e7b04a-dfb2-4ab4-97e1-1ee240209d0a.png)

Die JSON Abfrage im Browser "http://192.168.178.167/json" liefert logischerweise auch das Ergebnis "29800":

{
"main":
  {
    "value": 29800,
    "raw": "029800",
    "error": "no error",
    "rate": 0.000000,
    "timestamp": "2021-12-29T14:11:09"
  }
}

Natürlich kann ich dann via Script im Smarthome die Stellen manuell zurecht schieben,
aber es wäre optimal wenn die HTML Ausgabe sowie JSON einfach nur das anzeigen was man vorkonfiguriert hat
und das wäre entweder der Wert "0298" oder "298".

Oder habe ich da einen Konfig-Dreher drinnen?
Danke.

**Comment by speerwerfer** [comment]
Hast du in der Konfig die Dezimalstellen verschoben? Und nach der Änderung musste ich mindestens einen Durchlauf warten.

**Comment by Ragna2000** [comment]
hmmm...guter Tipp.
So stehts bei mir in der config.ini....

[PostProcessing]
main.DecimalShift = 2
PreValueUse = true
PreValueAgeStartup = 720
AllowNegativeRates = false
main.MaxRateValue = 0.1
ErrorMessage = true
CheckDigitIncreaseConsistency = false

Auf was müsste ich demnach den "DecimalShift" Wert ändern das ich nur "298" angezeigt bekomme?

**Comment by speerwerfer** [comment]
Ich würde sagen 0. Du hast die roten Ziffern ja nicht in der Erkennung

**Comment by jomjol** [comment]
Ja genau - das ist die Ursache!

**Comment by Ragna2000** [comment]
obwohl ich Dez. Stellen seit gestern von "0" auf "2" umgestellt habe, ändert sich der Wert nicht bzgl. Dez. Stellen.
Ich vermute das es nicht geht weil ich komplett "Analoge Digits" abgeschaltet habe und 
arbeite nur mit den 6 Digits wie auf dem Foto zu sehen.

Wenn das der Fall ist, kann ich wohl nichts selber ändern da das im Code so fixiert ist
das die Kommawerte nur durch analoge Uhren kommen. 
Ist das der Fall?

Falls nicht, bitte um Rat was ich noch anpassen könnte damit die roten Zahlen als ",xx" angezeigt werden. Danke!

Das Ziel ist den Wert "299,39" zu bekommen als Raw-Wert.


![image](https://user-images.githubusercontent.com/85805060/147747371-063f9628-f9e4-4d15-bcb9-fda4436c7dca.png)


![image](https://user-images.githubusercontent.com/85805060/147747169-c020b37c-1e32-4451-a84c-8025fbd64355.png)

**Comment by speerwerfer** [comment]
stelle mal den DecimalShift auf -2 ... und warte dann mal mindestens einen kompletten Durchlauf der Bilderkennung ab.

**Comment by Ragna2000** [comment]
BESTEN DANK!!!

![image](https://user-images.githubusercontent.com/85805060/147752143-a3ee99da-f402-4bc0-abfd-34f125ca40ce.png)

**Comment by jomjol** [comment]
Dann den Shift halt um zwei Stellen in die andere Richtung: +2 ... einfach ein bisschen probieren :-)

**Comment by Ragna2000** [comment]
Danke, aber passt doch inzwischen wie oben im Screen zu sehen.
;-)
Ich habe "-2" eingetragen und jetzt wird der "Raw Value" für mich passend angezeigt
und lässt sich via JSON schön sauber abgreifen für Smarthome Zwecke.
