### ISSUE TITLE
Failed to init camera

### ISSUE THREAD

**Issue by Sandiegoo** [jomjol/AI-on-the-edge-device#492]
Hello helpers,

i have trouble to get this code to run on my hardware. It allways reboots. After a wail of reading the logs and fixing the trouble with brown out reset. I was able to reacht the website. But it reboots after a while.

So looked into the uart log and it tell me that it can detect the camera but fails to take a picture.
I already disconnected and reconnected the camera module. But nothing changed :(

What else can i do?

Uart log:
[AI_on_the_edge_device_uart_log.txt](https://github.com/jomjol/AI-on-the-edge-device/files/7789595/AI_on_the_edge_device_uart_log.txt)

**Comment by Sandiegoo** [comment]
i couldn´t get it to run with any code (Not even with arduino examples). I ordered some new ones. I hope that will help.

**Comment by jomjol** [comment]
Something is wrong with your camera module - see your logfile
```
<27>[0;31mE (14367) camera: Camera init failed with error 0x20002<27>[0m<\r><\n>
<27>[0;31mE (14367) server_part_camera: Camera Init Failed<27>[0m<\r><\n>
```

Not all modules are working well. I have testet all my modules and summarized the result here: https://github.com/jomjol/AI-on-the-edge-device/wiki/Hardware-Compatibility

**Comment by Sandiegoo** [comment]
Thank you for answering. I just had a look on the flex Connector. Can´t really compare it to your loggings.

This is what is written on my camera module flex connector:

XRZ00D1
-V240
V2.0 1903

I bought this module 2 years ago. Maybe it is just to old to work with newer firmware. Can´t remeber if it was ever running or not.
