### ISSUE TITLE
Always on LED setting?

### ISSUE THREAD

**Issue by jdeath** [jomjol/AI-on-the-edge-device#493]
My meter needs light to "wake-up" and charge via a solar panel. Is there a setting to keep the LED light on all the time? Or start 30 seconds before taking a picture? It also displays the serial number first, then switches to water usage, then switches to water rate. If I could configure the time the light is on before take a picture, it would be perfect.

**Comment by jdeath** [comment]
Looks like setting is there. closing

**Comment by jomjol** [comment]
I would strongly not recommend to turn on the LED a very long time. It will get **VERY** hot and this might cause trouble!
