### ISSUE TITLE
Digital Number 3 recognized as 0

### ISSUE THREAD

**Issue by short997** [jomjol/AI-on-the-edge-device#496]
Hi,
this is a great piece of software! I have attached examples of my number 3 reading (more are available, but I read 2-3 are enough), which is recognized to 90% as Zero. May I ask for your help to train the neuronal network please? I have played with the ROI Settings for two evenings, without success for better readings / recognitions.

MQTT:
{"value":134.7038,"error":"Neg. Rate - **Read: 104.7078** - Raw: 00104.7078 - **Pre: 134.7038** ","rate":0.000000,"timestamp":""}

[3_arbitrary.zip](https://github.com/jomjol/AI-on-the-edge-device/files/7794390/3_arbitrary.zip)

Many thanks!

**Comment by MaddogMccree** [comment]
Hi
the same problem.

MQTT:
{"value":,"raw":"00210.2917","error":"Neg. Rate - Read: 210.2917 - Raw: 00210.2917 - Pre: 213.0991 ","rate":"","timestamp":""}


![main_dig5](https://user-images.githubusercontent.com/76697599/147813993-5ffd8fbe-85b2-49d5-8728-0f6b7830cecc.jpg)

Thanks

**Comment by jomjol** [comment]
Can you please make a complete set of your data? If I start to train single images, I will all day put new numbers in there :-).

Please check, that the settings are according to: https://github.com/jomjol/AI-on-the-edge-device/wiki/ROI-Configuration

Thanks,
  jomjol

**Comment by MaddogMccree** [comment]
So here all the digit and analog and ref pictures.
Is this what you want ?
[main_ana1.zip](https://github.com/jomjol/AI-on-the-edge-device/files/7795781/main_ana1.zip)

**Comment by jomjol** [comment]
No - please read the wiki page for the detailed description, what I need: 
* https://github.com/jomjol/AI-on-the-edge-device/wiki/ROI-Configuration#1-get-images-into-the-next-training-round

**Comment by short997** [comment]
Just to be clear, do you need 3 examples of each number -> 3x0, 3x1 ... for the training? A full turn of the m³ to have pictures of all numbers will take some time. 1 and 4 is working, only the 3 makes trouble.

**Comment by MaddogMccree** [comment]
So here the the complete set

[set of numbers.zip](https://github.com/jomjol/AI-on-the-edge-device/files/7795841/set.of.numbers.zip)
 thanks for your help

**Comment by jomjol** [comment]
@short997:
- yes I would ask for a full set of training data - otherwise I will add image after image and do nothing else anymore :-)

@ MaddogMccree:
- If you want to train analog pointers, I even need 200 images of about every 0.1 steps (0.0, 0.1, 0.2, .0.3, ... 9.7, 9.8, 9.9)
- And they need to be labeled in the correct way **by hand** (expected output)
- This is really a lot of work
- Both is not given the images you send me. 
E.g wrongly labeled as 3.9 
![grafik](https://user-images.githubusercontent.com/30766535/147828903-ab6b715c-9434-4f05-bfcb-64968eacdc98.png)

**Comment by MaddogMccree** [comment]
No i only want the digital numbers  to train 
the analog Pointers are exactly enough for me

**Comment by jomjol** [comment]
Newest digital model is now here:

[Uploading dig-s1-q-20220102.zip…]()


You can use it as a "beta" tester. I will upload it with the next version.

**Comment by MaddogMccree** [comment]
@jomjol 
Hallo

ich habe gesehen das du auch Deutsch kannst.
Ich kann die datei nicht herunterladen. Wenn ich draufklicke komm ich wieder auf die Seite.
Und wie muss ich das dann auf dem esp32 ändern?
Einfach Datei austauschen und neu booten?

MFG
Michael

**Comment by MMeinhardt1** [comment]
@MaddogMccree Eventuell meint @jomjol die Datei "dig-s1-q.tflite" von [dieser](https://github.com/jomjol/neural-network-autotrain-digital-counter/tree/main/a_output_actual) Seite!?

**Comment by MaddogMccree** [comment]
OK DAnke für den Hinweiß 
aber wie bekomme ich das auf den esp32 ?

**Comment by MMeinhardt1** [comment]
Na, von der verlinkten Seite herunterladen und über den im ESP implementierten Dateibrowser hochladen.

**Comment by MaddogMccree** [comment]
In den config ordner wo die anderen .tflite dateien sind?
Und dann einfach reboot?

**Comment by MMeinhardt1** [comment]
Genau, in den config Ordner und dann den Dateinamen auch in die config.ini eintragen, speichern und rebooten.

**Comment by MaddogMccree** [comment]
super vielen Dank für die Hilfe

**Comment by MMeinhardt1** [comment]
Gerne und viel Erfolg.

**Comment by MMeinhardt1** [comment]
@MaddogMccree hat es funktioniert? Wenn nicht, die neue Datei ist jetzt auch im Rolling branch und /sdcard/config verfügbar.
