### ISSUE TITLE
OTA Update is not overwrite firmware.bin

### ISSUE THREAD

**Issue by ThomasCr** [jomjol/AI-on-the-edge-device#497]
First many thanks for your update :)

I was really happy, because I fiddle right now around with it.

But when I uploaded it with OTA from the Webpage - I got told uploaded .... so I flashed it.... but at the end (after the reboot) I have still the old version.

So I deleted the file with the filemanager and did it again. Now I got on info "master - v10.0.0 - 2021-12-30"

It should be overwritten or print a warning that the file already exists :)

**Comment by jomjol** [comment]
Normally it deletes the old firmware.bin in the directory. No warning necessary. Seems there went something unusally wrong.
