### ISSUE TITLE
Programmierung / Konfiguration schlägt fehl

### ISSUE THREAD

**Issue by Simes62** [jomjol/AI-on-the-edge-device#498]
Gestern hatte ich mein ESP32 erfolgreich mit der Firmware 9.2.0 geflasht. Im Webinterface war allerdings die Definition eines Referenz-Bildes nicht möglich. Über den Aufruf <ip-adresse>/capture_with_flashlight konnte ich aber das von der Kamera aufgenommene Bild  sehen. 

Heute morgen habeich mit dem Espressif Flash-Tool die V10.0.0 geflasht. Leider hat sich dadurch das Problem mit dem Referenzbild nicht vereändert. Nach Das Webinterfaces sieht wie folgt aus:
![Webinterface](https://user-images.githubusercontent.com/80912715/147813696-60cbadc8-a499-43f6-9b88-e5118f7cd8d0.JPG)

Ein Downgrade auf die V9.2.0  hat nicht funktioniert. Das Flash-Tool bringt eine Fehermeldung "5-chip efuse check fail". Nun läuft das Board auch nicht mehr hoch.

Was kann ich tun?

**Comment by jomjol** [comment]
Vielleicht ist etwas mit dem Flashen schief gelaufen. Dann den Flash-Speicher vor dem Firmware flashen komplett löschen (siehe Wiki). Anschließend befindet er sichim Auslieferzustand und du müssstest wieder flashen können. Ansonsten hast du einen Hardwarefehler.

**Comment by Simes62** [comment]
Der Flashvorgang  mit dem esptool läuft deutlich stabiler. Ich bekomme keine Fehlermeldungen mehr und der Speicher lässt sich vor dem Flashen komplett löschen. Der Update auf die V10 hat mich nun auf die Spur meines Problems gebracht. Im Logfile gab es die Fehlermeldung, dass zu wenig PSRAM verfügbar sind:
![PSram](https://user-images.githubusercontent.com/80912715/147849279-cb010fc7-79c8-4bc9-a339-b5e015e95dd1.JPG)
Und tatsächlich ist auf dem Board nur ein 2MB PSRAM verbaut (ESP-PSRAM16H), obwohl in der Artikelbeschreibung bei Aliexpress 4MB angegeben waren. 
Interessant ist noch, dass diese Fehlermeldung bei der alten Firmware V9.2.0 nicht kam und das Board sogar teilweise funktionierte (wie oben beschrieben).

**Comment by jomjol** [comment]
@Simes62 
Ich habe die Prüfung erst mit der neuen Version eingeführt, da jetzt schon mehrere User Probleme hatten und ich erst nach vielen anderen Versuchen auf die Ursache "zu wenig PSRAM" gekommen bin, zumal sie auch laut Papier ein 8MByte Modul gekauft haben.
