### ISSUE TITLE
Image overexposed - too much light from LED? 

### ISSUE THREAD

**Issue by reibuehl** [jomjol/AI-on-the-edge-device#499]
Hi,

I am trying to setup recognition of my water meter. The reference image and also the normal images later are all very bright - to a degree where hardly any recognition is possible. It seems that the flash LED is way too bright and a lot of light is reflected by the shiny clear plastic cover of the meter. Is there a way to dim the flash LED? I am using 10.0.1.

**Comment by juergen852** [comment]
Have the same problem, LED is also getting really hot (can't touch with finger while lit...).
Dim to about 50% would certainly extend life of LED.
Tasmota provides a slider for LED brightness, see tasmota32-webcam.bin at http://ota.tasmota.com/tasmota32/release/

**Comment by wlayher** [comment]
I have the same problem. I printed a white half-dome as a diffuser to go over the LED, but that still does not seem enough, even at the brightness setting of -2. I'll try next to put a sheet of paper over the LED to dim it further.

**Comment by wlayher** [comment]
I just tried to dim the LED by editing the config.ini. Search for the line
LEDColor = 50 50 50
and change it to
LEDColor = 30 30 30
Save the file and reboot. This reduces the brightness. If that is not correct for you, you can change the values again. If all 3 values are the same, the colour should be still white.

**Comment by jomjol** [comment]
Dimming the LED is only partaly helpfull as the camera is working in auto illumination mode. So if you dim the LED, the illumination time will increase.
Using LEDColor is the right way to go, **but only** if you are using external WS2812 LEDs, because only this can be dimmed really and placed also out of the axis of the camera in order to reduce reflections.
Another way to handle this would be a "mask" on the meter itself. It has been reported to be very useful in this forum:
https://forum.iobroker.net/post/730652

**Comment by wlayher** [comment]
Thanks for the tip with the mask. That could make things a bit easier, but I still have reflections directly over the numbers that make the algorithm recognize them incorrectly, e.g. a "0" with a reflection across the middle gets recognized as an "8". And the numbers in my meter are not wholly visible to the camera, but are partially covered by the housing on the meter. I could try to change the camera mount to get a more vertical viewpoint on the numbers for the camera and use external LEDs to get rid of the glare. But I think I'll first try another method with an inductive probe, as I have all the components for that on hand.
