### ISSUE TITLE
Chrome Browser not fully supported

### ISSUE THREAD

**Issue by michaeljoos72** [jomjol/AI-on-the-edge-device#5]
Hi jomjol

Chrome Browser does only partially work and does not show "Raw Value" and "Corrected Value":

![image](https://user-images.githubusercontent.com/20517474/92331081-253f4f00-f074-11ea-9c06-55152c520bc3.png)

"Edit Configuration" and "File Server" shows:

![image](https://user-images.githubusercontent.com/20517474/92331112-6fc0cb80-f074-11ea-8eb1-cbcafe8b31c7.png)

BR
Michael

**Comment by jomjol** [comment]
Update to v1.1.2 improves the compatbility - please check and give further feedback.

**Comment by jomjol** [comment]
Close for the moment - see v1.1.2
