### ISSUE TITLE
Zusätzliche Korrektur beim Nulldurchgang Digitaler Teil

### ISSUE THREAD

**Issue by eki1503** [jomjol/AI-on-the-edge-device#50]
Bei mir ist es aktuell so, dass immer beim Nulldurchgang der digitalen Ziffern eine Meldung erscheint, dass der Wert negativ ist (beim Nulldurchgang wird temporär das Digit nicht erkannt) und es wird erst wieder etwas geschickt, wen die letzte digitale Stelle wieder erkannt wird. Das dauert leider immer eine ganze Weile und ist daher unschön. Könnte man nicht bei der Korrektur auf große negative Sprünge zwischen den Werten prüfen und daraus ableiten, dass ein Nulldurchgang stattgefunden hat und somit die letzte Stelle hochzählen (sprich den preValue anpassen) wenn sie nicht erkannt wird.

**Comment by jomjol** [comment]
Hi Eki, 
ich verstehe dein Problem nicht. Wenn die PreValue richtig gesetzt ist und auch aktiv, dann werden die von dir genannten Prüfungen gemacht und es kommt nicht zu einem negativen Sprung. Es ist auch eine Prüfung, ob die Ziffer einen Nulldurchgang hatte implementiert - dazu musst du die entsprechenden Parameter wie folgt setzten:
```
[PostProcessing]
...
PreValueUse = True
...
ErrorMessage = True
CheckDigitIncreaseConsistency = True
```
Wenn dein Problem trotzdem besteht, bitte den Issue mit einem Beispiel wieder eröffnen.
Gruß,
  jomjol

**Comment by eki1503** [comment]
Hallo jomjol,

Die Parameter sind wie von Dir angegeben gesetzt. Ich fürchte, das Problem kommt aus einer Kombination von Dingen. Bei mir ist der digitale Wert vor dem. Nulldurchgang 352.xxx, allerdings wird die 5 manchmal als 6 erkannt und entsprechend korrigiert. Wenn das jetzt beim Nulldurchgang passiert, ist der Rohwert u.U. 36N, mit der Korrektur wird 352 korrigiert und dann wird wohl nicht mehr auch noch die zweite Korrektur des Nulldurchgang geprüft. Ich gebe zu, das sind sehr viele Wenns und es ist auch nicht super dringend.

**Comment by jomjol** [comment]
Das kann natürlich sein. Da hilft dann final nur eine Verbesserung der Erkennungsrate. Dazu brauche ich von jedem deiner Digits jeweils 2-3 Bilder und ich kann sie ins Training integriere.
