### ISSUE TITLE
Training Request - LCD Digital Display

### ISSUE THREAD

**Issue by jdeath** [jomjol/AI-on-the-edge-device#500]
[Digit Set.zip](https://github.com/jomjol/AI-on-the-edge-device/files/7796878/Digit.Set.zip)

Digit set for my LCD water meter. Hopefully I did everything correct. A couple numbers I could only find in one of the positions.

**Comment by jomjol** [comment]
Training has been done and will be part of the next release. Can you test it in advance?
[dig-s1-q-20220102.zip](https://github.com/jomjol/AI-on-the-edge-device/files/7799516/dig-s1-q-20220102.zip)

**Comment by jdeath** [comment]
Yes, I will report back tomorrow. I uploaded into /config/ and changed the filename in config.ini under digits, save and reboot. Hopefully that is right.

**Comment by jdeath** [comment]
Still have a few misidentified digits with the new training. Attached are the bad digits I found so far.
[bad digits.zip](https://github.com/jomjol/AI-on-the-edge-device/files/7799980/bad.digits.zip)

**Comment by jomjol** [comment]
I will include most of them in the next training round. The following are not okay (criteria border):
![8-0_7_20220102-184752](https://user-images.githubusercontent.com/30766535/147909853-e0338daf-5905-4c4c-ae7f-ce213720d3dd.jpg) ![7-1_7_20220102-162752](https://user-images.githubusercontent.com/30766535/147909859-be1e85c2-b126-44b3-96ca-d523e6d17947.jpg) ![5-1_5_20220102-150242](https://user-images.githubusercontent.com/30766535/147909860-a1da5cac-7b1a-4f7c-91b5-9cc62d0ab404.jpg)

8, 7: border to small
5: border too big

Two remarks / questions:
* Do you have the chance to enhance the contrast?
* Do you have the images with a larger size? That would the judgment much easier.

**Comment by jomjol** [comment]
You can test the next run with this file:
https://github.com/jomjol/neural-network-autotrain-digital-counter/blob/main/a_output_actual/dig-s2-q.tflite

**Comment by jdeath** [comment]
This file works well. I adjusted the ROI and I've had pretty solid results today. My digits are so close, so the boxes overlap in the GUI. I'll keep watching it. Thanks so much, this is a really great project.
