### ISSUE TITLE
Falsche Werte gelesen

### ISSUE THREAD

**Issue by lexiz52** [jomjol/AI-on-the-edge-device#501]
Hallo 

Ein gutes neues Jahr!

Ich habe seit neuesten ein Problem das die Werte von meinem Gaszähler nicht mehr richtig gelesen werden obwohl das Bild klar und scharf ist. 
Kann ich noch etwas an den settings ändern? Ich habe auch schon die V10.0.2 getestet, mit dem selben Ergebnis.

VG 
Thomas
![Gaszähler](https://user-images.githubusercontent.com/61904155/147848047-b2417cae-3e31-4df3-b21f-7cfceb45f04d.JPG)

**Comment by jomjol** [comment]
Deine ROIs sind nicht optimal eingestellt. Der Rand ist deutlich zu groß: 
![grafik](https://user-images.githubusercontent.com/30766535/147852850-7d3d0e98-d81d-4238-a912-ac924d644a2a.png)

Ich habe hier eine detailierte Anleitung und Erklärung für die ROIs geschrieben: https://github.com/jomjol/AI-on-the-edge-device/wiki/ROI-Configuration
