### ISSUE TITLE
Header fields are too long for server to interpret

### ISSUE THREAD

**Issue by Soe-Koh** [jomjol/AI-on-the-edge-device#502]
Seit dem Update auf 10.0.1 funktioniert das Auslesen nicht mehr. Update auf 10.0.2 bringt auch keine Besserung. Wenn ich die Konfiguration einsehen möchte, erhalte ich die Fehlermeldung: "Header fields are too long for server to interpret".

![image](https://user-images.githubusercontent.com/44121375/147850234-a214a6ad-de98-439d-8731-d95d391d0878.png)

**Comment by jomjol** [comment]
Wie genau greifst du darauf zu? Mit dem Update auf den ESP-IDF 4.3 wird auch der HTML-Server auf die neueste espressif Version upgedatet, eventuell hat sich dort etwas geändert.
Hast du mehr Details? Fehlermeldung habe ich von anderen noch nicht gehört.

**Comment by Soe-Koh** [comment]
Den Fehler erhalte ich mit Chrome 95 unter Windows. Aber auf Grund Deiner Nachfrage jetzt mal mit Firefox und Edge getestet und damit funktioniert der Aufruf der Konfiguration wieder. Mit Downgrade auf 10.0 funktioniert die Erkennung auch wieder.

**Comment by jomjol** [comment]
Okay - eigentlich sind zwischen 10.0.0, 10.0.1 & 10.0.2 nur ein paar Zeilen Code im MQTT-Modul angepasst, um Fehler im JSON-String zu korrigieren. Daher ist es komisch, dass ein Downgrade etwas bei der Stabilität ausmacht. 
Aber okay - ich schließe das jetzt erstmal. Bitte gerne wieder öffnen, falls weitere Themen kommen.

**Comment by xerion3800** [comment]
Ich kann den Fehler bestätigen muss aber dabei sagen daß ich erst seit gestern das erste Mal das Projekt installiert habe und eigentlich von einem Fehler meinerseits ausgegangen bin.

**Comment by barthm1** [comment]
Ich bin wider auf 9.2 zurück -  Habe den Fehler unter edge und chrome 96

**Comment by xerion3800** [comment]
Kann ich auch bestätigen das Downgrade auf 9.2 löst das Problem.

**Comment by Soe-Koh** [comment]
> Kann ich auch bestätigen das Downgrade auf 9.2 löst das Problem.

Bin auch wieder auf 9.2 zurück und funktioniert alles wieder

**Comment by jomjol** [comment]
@Soe-Koh @xerion3800 
Könnt ihr mir mal die genauen Umstände schicken, unter denen das Problem bei euch auftritt?
Ich habe gerade meinen ESP32 (v10.0.2) mit einem akutuellen Chrome angesurft und es klappt bisher ohne Probleme

**Comment by xerion3800** [comment]
Also ich hatte gestern das Modul in Betrieb genommen und bin dann auf die 10.0.0 gegangen. Danach hatte ich das Modul konfiguriert und nachdem das Setup abgeschlossen war wollte ich wie im Wiki beschrieben über Edit Configuration MQTT freischalten. Beim Aufruf der Seite kam dann der besagte Fehler. Ich hatte mir dann damit geholfen das ich die config.ini direkt editiert habe. Ich nutze folgende Module (https://www.amazon.de/gp/product/B08P1NMPLL/ref=ppx_yo_dt_b_asin_title_o01_s01?ie=UTF8&psc=1) und auf dem Smart Phone wie auch in Windows 10 den Browser Edge.

**Comment by jomjol** [comment]
Okay danke - weder Smartphone, noch Edje jemals getested, daher kann ich das nicht ausschließen. Ich würde aktuell einen Desktop mit Firefox oder am ehesten vermutlich Chrome empfehlen.

**Comment by xerion3800** [comment]
Chrome und Edge sollte sich m.E. nicht unterscheiden und die vorherigen Kommentare hatten auch Chrome erwähnt. Ich denke dort ist noch was anderes die Ursache,

**Comment by Soe-Koh** [comment]
Eigentlich nichts Besonderes gemacht. Hatte die Updates gesehen und installiert, aber nichts weiter geprüft. Heute wollte ich den Wasserstand ablesen und hatte dann bemerkt, das seit gestern keine neuen Daten hinzukamen. Dann direkt auf den ESP zugegriffen und die Fehlermeldung gesehen. Neustart hatte auch nichts gebracht. Dann das Downgrade gemacht und Erkennung funktioniert wieder. Aber die fehlenden Daten und die Config Fehlermeldung sind dann wahrscheinlich doch zwei voneinander Unabhängige Problem, die ich nur zeitgleich festgestellt habe. Chrome96 funktioniert bei mir auf keinem Windows Rechner.

**Comment by xerion3800** [comment]
Mit Firefox geht es ohne Probleme.

**Comment by watcherkb** [comment]
Mit der Version 10.0.2 habe ich diese Probleme auch (Chrome/Edge), Firefox funktioniert aber.

**Comment by barthm1** [comment]
Ich habe ein Device komplett neu aufgesetzt - Der Setup funktioniert bis auf den letzten Schritt mit dem Reboot.
Dieser bringt erst den Fehler - Bei diesen Posts muss also etwas anders sein.

**Comment by jomjol** [comment]
@barthm1 welche Version hast du genau genommen: master oder rolling?
In der Rolling habe ich die Buffer und den maximalen Headerlength für den Webserver erhöht.

**Comment by barthm1** [comment]
Master

jomjol ***@***.***> schrieb am Fr., 7. Jan. 2022, 12:09:

**Comment by jomjol** [comment]
Okay - dann ist da noch nicht die Optimierung mit den vergrößterten Buffern drin.

**Comment by barthm1** [comment]
Noch nicht alles getestet - aber 10.1 sieht gut aus - was die Benutzung von Edge/Chrome angeht

**Comment by Soe-Koh** [comment]
Bei mir scheint es auch wieder alles zu klappen
