### ISSUE TITLE
Feature Request: Auto Update Check 

### ISSUE THREAD

**Issue by toben1997** [jomjol/AI-on-the-edge-device#503]
Es wäre echt schön wen das System einen über Updates informieren würde, als Beispiel ein neue Button der im Menü auftaucht wo steht update available, und wen man drauf klickt, dass es auf das Tutorial verlinken tut im GitHub wie man updatet.
ggf. auch ein MQTT topic so ungefähr wie das Error topic nur halt mit update, welches man dann z.b. in Home Assistant als binären Sensor nutzen könnte.

Als beispiel:

![pHXtIaf51f](https://user-images.githubusercontent.com/23506168/147858206-4574f82a-cbea-402b-9173-d57ab72b6e84.png)

**Comment by jomjol** [comment]
Hi, ich kann deine Idee nachvollziehen.
Aktuell programmiere ich das Projekt im Wesentlichen komplett alleine in meiner Freizeit (C-Code & HTML). Ich habe leider keine Zeit, dass selbst zu übernehmen. Wenn du das aber übernehmen würdest, freue ich mich, dein Update als Commit zu integrieren.

**Comment by speerwerfer** [comment]
Dann sollte so was aber bitte konfigurierbar/abschaltbar sein. Ich möchte nicht, das meine ESP ins Netz gehen ....

**Comment by jomjol** [comment]
Ich werde das aktuell nicht angehen.
