### ISSUE TITLE
Probleme mit digitaler Anzeige?

### ISSUE THREAD

**Issue by JensHoeppner** [jomjol/AI-on-the-edge-device#504]
Hallo,
zuerst mal Danke für dieses großartige Projekt.

Ich fummel nun seit Weihnachten dran rum. Nun will ich mal nachfragen.
zuerst die Verständnissfrage:
* Wofür wird das Referenzbild genutzt? Nur um die ROIs und Alignment Marks festzulegen? Oder auch später bei der Erkennung der Bilder?

Nun zum Handling:
Ich versuche unseren Stromzähler auszulesen. Die Erkennungsrate ist allerdings stark unterschiedlich. Mal gut, mal eher mies.
Gemäß dem Wiki habe ich die Ziffern in die inneren Markierungen eingefasst. Dadurch komme ich aber mit den äußeren Markierungen schon über die Nachbarziffern. ist das ein Problem?
Speziell die Ziffer "1" wird extrem selten erkannt. Ich vermute, weil sie ja nicht mittig, sondern versetzt nach rechts angezeigt wird.

Ist die Bildqualität so OK, oder kann das so nix geben?
![image](https://user-images.githubusercontent.com/96954468/147858672-8cfb0815-348c-440a-b117-fc41474b777a.png)

Ach ja, SK6812 über GPIO12 gesteuert funktioniert hier.

Schönen Gruß
Jens

**Comment by jomjol** [comment]
Referenzbild:
* dient zur Definition der Referenzen und ROIs. Das läuft folgendermaßen:
1. Nach jeder Bildaufnahme wird das Kamerabild über die Referenzen so gedreht, dass die ROIs immer an derselben Stelle liegen, wie im Referenzbild definiert
2. Ausschneiden der ROIs immer genau an der derselben Stelle
--> das ganze wird unabhängig von kleineres Bewegungen des Gehäuses

Das Referenzbild als solches wird während des Ablaufs gar nicht benutzt. Nur wenn du die ROIs anpasst, machst du es natürlich auf der Referenz und nicht der evt. leicht verschobenen aktuellen Aufnahme

LCD-Display:
* An sich kann der Algo das grundsätzlich auch.
* Wenn aber die LCD-Ziffern so eng stehen, dass du immer auch einen Teil der Nachbarziffern drin hast, wird das ein Problem sein.
* Um das zu beseitigen, brauchst du einen speziell angepasstes Neuronales Netz, bei dem die LCD-Ziffern größer ausgeschnitten sind und dann auch so trainiert wurden (Rand << 20%)
* Im Allgemeinen funktioniert die Erkennung bessern, wenn ich den Rand bei diesen 20% halte, daher kann ich das nicht für alle Ziffern anpassen

Ich kann dir bei Gelegenheit beim Training helfen. Du könntest aber im ersten Ansatz mal die ROIs etwas kleiner machen, so dass die Nachbarziffern gerade so nicht mehr drauf sind und es ausprobieren. Der Bilderkennungsalgo ist dort bezüglich einer gewisssen Größenschwankung tolerant.
