### ISSUE TITLE
Delete and Delete All does not work for Folders which are not empty

### ISSUE THREAD

**Issue by CSchoch** [jomjol/AI-on-the-edge-device#505]
If i try to delete a folder which contains files or folders nothing happens.

Git-Base-Branch:
master - v10.0.2 - 2022-01-01
HTML Version: 
11.4.0

**Comment by jomjol** [comment]
That is not a bug, but a feature.

This is a very primitive file manager and it should only be used for very simple manipulations. Deleting a complete directory, including all subfiles is dangerous, even on full systems like win / linux, therefore this is n ot supported.
Secondly I have not written it by myself, so update would be rather time consuming.
