### ISSUE TITLE
Feature requeset: Calibration for FishEye image

### ISSUE THREAD

**Issue by CSchoch** [jomjol/AI-on-the-edge-device#507]
I have the system runnung for a few days now and are impressed how good it works on such a cheap device (considering industrial devices 5k or more). Great Job!

I have a 160 degree wide angle lens which produces a rather fish eyed image.
Is it possible to add a calibration [camera calibration](https://de.wikipedia.org/wiki/Kamerakalibrierung) it's in german to the system?

**Comment by jomjol** [comment]
Most propably technically possible. It would need:
1.  The development of such a correction algorithm with the libraries, that are available for the ESP32 environment.
2. New module for integration of the flow into the image processing flow.
3. Extension of the configuration (config.ini) and html-pages
4. Parameter adjustment and testing for every different fish-eye module
5. Maintenance for further updates / modules, ...

As I developed the alignment and partially the image processing algo by myself, I estimate this for 40-80h of working time (first "stomach" estimation). I don't have time and ressources to do so in the mid term timescale. Therefore I cannot start this unfortunatly. 

I have put this onto the feature demand list, but will close this issue.
