### ISSUE TITLE
Probleme mit MQTT seit Update auf 10.0.2

### ISSUE THREAD

**Issue by awor** [jomjol/AI-on-the-edge-device#508]
Folgendes Verhalten habe ich bisher noch nicht gesehen:

Wenn kein Fehler ist alles korrekt:
![image](https://user-images.githubusercontent.com/3464535/147884399-deb52c55-cf50-4ba5-925f-eed679d791d6.png)
Value entspricht json value

Bei einem Fehler ist die value im json leer:
![image](https://user-images.githubusercontent.com/3464535/147884448-bce32bfe-5a61-4367-b6a6-775ef29cb4d1.png)

Das Ergebnis in Home Assistant ist nun dass Wert 0 angezeigt wird (basiert wohl auf dem json). Dieses Verhalten ist mir vorher nie aufgefallen und scheint neu seit dem Update zu sein.

**Comment by jomjol** [comment]
Eigentlich ist das beabsichtigt, denn ein anderer User hat darum gebeten, keinen Wert zu übermitteln, falls ein Fehler vorliegt.
Ich finde das auch aus folgender Logik bei mir selbst besser und habe es daher mit v10 geändert:

ALT:
* Bei vorliegen eines Fehlers wurde bisher immer der alte Wert gesendet, obwohl sich der Zähler vielleicht weiter dreht. Wenn das jetzt über einen etwas längeren Zeitraum stattfindet, dann gibt es irgendwann mit dem richtigen Wert einen sehr großen Sprung in der Rate, da ja bis zum Wert vorher noch der alte Wert gesendet wurde.

NEU: 
* Ich sende keinen Wert, bis es wieder einen richtigen Wert gibt. Die Rate wird dann aus der Zeitdifferenz zum letzten korrekten Wert berechnet und entspricht der mittleren Rate seit dem letzten korrekten Wert. Das ist zumindest besser wie ein fiktiver hoher Verbrauch, der durch das Senden der alten "falschen" Wertes entspricht.

**Comment by awor** [comment]
Okay, es wird jedoch m.E. dann zum Problem, wenn ein Fehler ausgegeben wird, obwohl es aus meiner Sicht keinen gibt, z.B.
 
![image](https://user-images.githubusercontent.com/3464535/148118664-e9e84f12-8d88-48ff-a22b-4a0ec7ee68d3.png)

Warum wird, wenn es gerade keinen Verbrauch gibt und der Zähler "still" steht, einen "Neg. Rate" Fehler ausgegeben? In diesem Fall müsste einfach wieder der erfolgreich gelesener Wert ausgegeben werden, auch wenn sich dieser nicht verändert hat. Oder habe ich etwas falsch verstanden?

**Comment by jomjol** [comment]
Da hast du natürlich recht. Vermutlich liegt der Fehler an weiteren Kommastellen, die hier nicht sichtbar sind. Da müsste ich dann nochmal eine Rundung zum löschen dieser Ziffern einbauen. Lasse des Issue mal offen.

**Comment by awor** [comment]
Hier noch ein anderes Beispiel, scheint nicht nur ein Rundungsproblem zu sein:
![image](https://user-images.githubusercontent.com/3464535/148294118-e0bc8623-6567-4667-b142-861894bd41dc.png)

**Comment by jomjol** [comment]
Wie ist denn bei dir folgender Paramter in der Config.ini eingestellt?
`CheckDigitIncreaseConsistency`

**Comment by awor** [comment]
Er ist auf `true`, ich deaktiviere

**Comment by jomjol** [comment]
Das erklärt das beobachtete Verhalten. Der Parameter ist für drehende Räder gedacht: Wenn die nächste Ziffer schon sichtbar ist, aber die vorherige die 0 noch nicht ganz erreicht hat, wird die nächster Ziffer zunächst noch nicht erhöht, bis der Nulldurchgang stattgefunden hat. Das macht bei LCD-Displays
1. keinen Sinn
2. nur Probleme mit Fehlerkennungen, denn wenn z.B. statt einer 8 eine 3 erkannt wird, denkt der Algo: Nulldurchgang --> Erhöhe die nächste Ziffer
