### ISSUE TITLE
Probleme mit Digitalen Wasserzähler

### ISSUE THREAD

**Issue by Scotty-89** [jomjol/AI-on-the-edge-device#509]
Guten abend zusammen,

erstmal vielen Dank für das gut Projekt ;)

ich verwende gerade den ersten ESP32 CAM mit der SW hier für meinen Wasserzähler und muss aber leider feststellen das er wohl mit den Digital Zahlen ein paar Probleme hat.

![Unbenannt](https://user-images.githubusercontent.com/54929714/147886506-cbe4873f-f460-458e-aed8-a35f166a7f8a.PNG)

mit der 8 und jetzt auch mit der 3 tut er sich schwer.
habe aber auch schon gesehen das er Probleme hat 7 und 1 zu unterscheiden das geht auch oft schief ... 

ist das bekannt oder könnte man hier was gegen machen ? 

danke.

**Comment by ThomasCr** [comment]
Der Zähler kann doch auch digital ausgewertet werden.

Sieht aus wie das Interface meines Stromzählers. Das hat aber SML und der Wasserzähler kann wohl "Wirered" MBUS.

https://www.kamstrup.com/de-de/wasserzaehlerloesungen/intelligente-wasserzaehler/meters/multical-21/documents
Siehe  Datenblatt (2)  Seite 12, da ist der Lesekopf auch gezeigt. Ich vermute der funktioniert aber exat wie der für meinen Stromzähler, nur das die Befestigung anders funktioniert. Ist halt ein wenig zu balsteln, aber sicherlich machbar.

Bzw das ist wohl das Teil... kann man ja mal erfragen was das Kostet:
https://www.kamstrup.com/de-de/wasserzaehlerloesungen/intelligente-wasserzaehler/meters/flowiq-2101

Das hier ist der Lesekopf den ich für meinen Stromzähler habe. Das wird so nicht ganz funktionieren (Abstände der Dioden anders), aber die Dioden kann man ja auslöten und über Kabel verlängern und an die richtige Position bringen.
https://www.ebay.de/itm/313525835802

Benutz habe ich Tasmota, das hat ein Smartmeter Modul, das auch den M(od)Bus kann.
https://tasmota.github.io/docs/Smart-Meter-Interface/

Ich habe den Tasmota allerdings nur im TCP Bridge Mode laufen und greife über Node-RED darauf zu... da muss man sich wohl ein wenig einlesen....

Alternativ kann man wohl auch den magnetischen Impus auswerten....

Infos zu dem Thema:

https://forum.fhem.de/index.php?topic=115474.0
https://forum.fhem.de/index.php?topic=87943.0

**Comment by ThomasCr** [comment]
Falls du es aber wirklich über AI on the Edge durchziehen willst:
1. ist es ganz wichtig das Bild gerade auszurichten, es fehlen wohl noch ein paar mm in der Rotation (Pre-rotate Angle und Fine Alignment)
2. wenn richtig gedreht, sind die Zahlen ja alle auf der gleichen Y Axe - also da überall den gleichen wert eintragen. Dann die Größe der Boxen ist auch überall gleich. Der Abstand normal auch (immer +X) so sollte es besser funktionieren.
3. Wenn das immer noch nicht zum erfolg verholfen hat, kann man die Zahlen evtl. Trainieren @jomjol

**Comment by Scotty-89** [comment]
Hey,

danke fürs Feedback aber genau diese Lösungen wollte ich nicht bzw. kann ich nicht umsetzten da ich den key auch nicht bekommen. zumal es auch extrem auf die Batterie gehen soll.

Ich würde es ja gern auf mein System Trainieren aber ich glaube das übersteigt meine Fähigkeiten den ich verstehe allein au der Doku nur die Hälfte ..
aber kann ich dabei ggf supporten ? irgendwas dafür bereitstellen etc ? 

ich kann mir schon vorstellen das es dem Projekt allg helfen würde wenn man ggf zwischen gedruckten Zahlen und Digitalen Zahlen unterscheiden könnte oder ?

**Comment by ThomasCr** [comment]
Glaube nicht dass du den Key dazu benötigt, wenn du das per Optischer Schnittstelle abgreifst. So wie ich das verstanden habe, ist das nur nötig per Funk..... Ist aber auf jeden Fall etwas schwieriger das zusammen zu Puzzlen (viel lesen und probieren).

**Comment by ThomasCr** [comment]
Ansonsten schau auch Mal hier rein

https://github.com/jomjol/AI-on-the-edge-device/issues/463

**Comment by jomjol** [comment]
Ich mache das mal zu, da es aktuell keine Aktivität gibt.

**Comment by svenblum** [comment]
Hi, ich habe dasselbe Kamstrup Modell und ich konnte mit einer angepassten Halterung das Problem lösen. Der Trick ist die Bilder etwas schräg aufzunehmen und so den Display möglichst gut zu beleuchten. Alle Infos & Bilder sind hier: https://www.thingiverse.com/thing:5198099

**Comment by Scotty-89** [comment]
Hey,

vielen dank für die Info ich habe es so ähnlich gelöst ich habe eine externe LED (WSB2812B) genommen und außermittig positioniert damit geht es bis jetzt sehr gut.

**Comment by jomjol** [comment]
@Scotty-89 an den reboots bin ich dran. Du kannst mal die Rolling Version probieren, die hat ein Update für den Kameratreiber, der die Ursache dafür ist. Scheint aber noch  nicht überall stabil zu laufen - daher noch in Testphase.
