### ISSUE TITLE
Digit 1 identified as 0

### ISSUE THREAD

**Issue by merbanan** [jomjol/AI-on-the-edge-device#51]
A dial looking like this:

![meter](https://user-images.githubusercontent.com/124883/99261014-714d0380-281c-11eb-81c2-5dab02fcf459.jpg)

gets decoded like this:
1960.7883

The 3 decoded as a 6 is fine but the 1 as 0 was unexpected. I read through the documentation with regards to the digital dials. Is there some some way to get better identification of the digital digits? Do I need to remove all the reflections for better identification? Or can the tf-model be retrained ?

**Comment by jomjol** [comment]
The reflections in the 9, 3 and 1 are part of the problem. Try to rotate the camera (can be easily adjusted later on).
Best regards,
  jomjol
