### ISSUE TITLE
Zahlenwechsel

### ISSUE THREAD

**Issue by Ma-Pa** [jomjol/AI-on-the-edge-device#510]
erst einmal super Projekt, danke für deine Arbeit...

Allerdings gibt es ein kleines Problem, sobald eine Ziffer auf die nächst höhere Zahl umspringt.

Bsp.: Zählerstand auf der Uhr
666.0000 (wird ohne Probleme erkannt digital und analog)
66**6**.5000 (wird nicht mehr erkannt, da das Zählrad den unteren Teil der 6 und den oberen Teil der 7 anzeigt und diese Zahl nicht mehr erkannt wird.
66**6**.**9900** hier wird schon 667.9999 erkannt, weil die 7 sichtbar ist und die 6 schon weg gedreht ist.

Gibt es eine Möglichkeit die erste Zahl vor dem Komma festzuhalten, bis der analoge Zeiger (erste Zahl nach dem Komma) wieder bei 0 steht?

Grund: Ich logge kontinuierlich den Zählerstand in eine Datenbank und berechne daraus meinen Stunden, Tages, Wochen und Monatsverbrauch. Problem ist, dass ich aktuell Sprünge habe, da wenn die Zahl nicht erkannt wird, wird an dieser Stelle eine 0 per MQTT unter 'value'  oder NaN unter 'raw' gesendet wird

**Comment by jomjol** [comment]
Diesen Schalter gibt es schon: 
![grafik](https://user-images.githubusercontent.com/30766535/147908515-5f9bbe76-aa40-474d-9bad-f146258bfb30.png)

Allerdings nur im Expertenmodus.
Achtung: der funktioniert nur zuverlässig, wenn deine Nachkommastellen von analogen Zeigern kommen.
