### ISSUE TITLE
Raw unterscheidet sich von der Recognition  

### ISSUE THREAD

**Issue by allgrinder** [jomjol/AI-on-the-edge-device#511]
Hey,

ich habe ein kleineren Fehler bei mir.
Bei dem Tab Recognition ist die Erkennung fehlerfrei:  253.7**4**52
![Screenshot_20220103-194537_Chrome](https://user-images.githubusercontent.com/75566736/147970988-73b1bb11-267f-452b-bb85-b7e0b4a5938b.jpg)
 
Gleichwohl wird aber 253.7**3**52 übertragen:
![Screenshot_20220103-194549_Chrome](https://user-images.githubusercontent.com/75566736/147971120-c9b9d6fb-e037-4db3-a50d-dd2e108ad2d0.jpg)

Viele Grüße

**Comment by jomjol** [comment]
Ist der Fehler einmalig oder dauerhaft? Zur Analyse bräuchte ich die Logfiles mit den Daten rund um den Fehler.

**Comment by allgrinder** [comment]
Hey, das ist öfters passiert. Kann ich den log Rückwirkend ziehen? Oder geht das immer nur für jede Analyse und wird danach gelöscht?

**Comment by jomjol** [comment]
Nein - einfach im Config.ini einschalten und dann von der SD-Karte runterziehen, zippen und hier posten.

**Comment by ThomasCr** [comment]
Da Stand doch aber prev value was er erkannte.
Aktuell ist die Zahl so verdreht, dass er sie nicht lesen kann. Deswegen NaN.

Hatte ich auch demletzt. Besser wäre natürlich er würde den Stand so nicht raus melden, was er aber leider tut.

**Comment by jomjol** [comment]
Schließe das mal, bis weitere Infos vorliegen.
