### ISSUE TITLE
Can the program detect symbols from a LCD screen?

### ISSUE THREAD

**Issue by JohnnyPicnic** [jomjol/AI-on-the-edge-device#513]
Hi have an HVAC panel that uses symbols to show its current mode. Can the program be used the send the status?
![Screen Shot 2022-01-03 at 10 40 12 PM](https://user-images.githubusercontent.com/5553884/148014646-41921ca2-4ab4-4974-a90b-0494e2cda7ab.png)

**Comment by jomjol** [comment]
Hi,
technically this is possible, but it would need a dedicated trained neural network and maybe some slight adjustment in the number and interpretation of the output classes.
If you are interesseted, I can offer an adaption on a professional (commercial) project. But be aware, that this will take quite some hours of effort. 
Best regards,
  jomjol

**Comment by jomjol** [comment]
No acitivities --> closing for the time beeing.
