### ISSUE TITLE
Training tflite model using another version of digital meter

### ISSUE THREAD

**Issue by wianoski** [jomjol/AI-on-the-edge-device#514]
can i request or is there any other way to training a digital recognize from 7s display ?  like this picture below 

thanks !

[https://ae01.alicdn.com/kf/HTB1R3CaSXXXXXaqXVXXq6xXFXXXP.jpg?size=297171&height=1000&width=1000&hash=ae4a5de4d1bbdecde0af68a05d1dc1dc](url)
[](https://ae01.alicdn.com/kf/HTB1R3CaSXXXXXaqXVXXq6xXFXXXP.jpg?size=297171&height=1000&width=1000&hash=ae4a5de4d1bbdecde0af68a05d1dc1dc)

**Comment by jomjol** [comment]
The link is not working.

**Comment by MMeinhardt1** [comment]
The right link [here](https://ae01.alicdn.com/kf/HTB1R3CaSXXXXXaqXVXXq6xXFXXXP.jpg?size=297171&height=1000&width=1000&hash=ae4a5de4d1bbdecde0af68a05d1dc1dc

**Comment by jomjol** [comment]
Technically possible, needs additional / dedicated trained neural network.
For this I need images (see here: https://github.com/jomjol/AI-on-the-edge-device/wiki/ROI-Configuration)

**Comment by wianoski** [comment]
okey ill send the images to you, but what format that you'll use the image for training ?

**Comment by jomjol** [comment]
This is discripted in the link above!

In a nutshell:
1. Correct setting of ROI !!!
2. 2-3 images per digit with the correct naming
3. collect them in a zip-file and post them here
