### ISSUE TITLE
Rollierende "digitale" Zahlen 

### ISSUE THREAD

**Issue by allgrinder** [jomjol/AI-on-the-edge-device#515]
Hey,

letzter vermeintlicher Fehler:
Das System erkennt im RAW-Wert 254.8747 aber eigentlich ist es 253.8747. Die digitalen Ziffern rollieren. Daher ist es auch sehr schwer die Erkennungenszonen ordentlich zu platzieren.  

Zuererst erkennt er die 253 perfekt. Dann eine ganze Zeit 25NaN. Durch den preValue behebe ich die Fehlerkennung. Irgendwann ist die nachfolgende Ziffer für den Algorithmus erkennbar. Dies führt dann automatisch zum Status "State too high" - Da der Wert dann als 254 erkannt wird.

![Screenshot_20220104-134135_Chrome](https://user-images.githubusercontent.com/75566736/148066202-977f328d-a8af-4ab2-8166-73e517276612.jpg)

Viele Grüße
:)

**Comment by jomjol** [comment]
Das liegt daran, dass er in der ersten Nachkommastelle ein 8 erkannt hat und vorher war es eine 9 --> da die Zahl kleiner ist, nimmt er an, dass ein Nulldurchgang stattgefunden hat und zählt daher hoch.
Dagegen hilft nur MaxRate Error und es tut genau was es soll :-)

**Comment by allgrinder** [comment]
![Screenshot_20220104-153544_Chrome](https://user-images.githubusercontent.com/75566736/148075328-21c98775-2589-476d-8814-1a58c0f1b17b.jpg)

Hm irgendwie passt es leider nicht. Habe den Wert entsprechend angepasst und es kommt eine 254

**Comment by jomjol** [comment]
wie ist bei dir der Parameter "CheckDigitIncreaseConsistency" eingestellt?

**Comment by allgrinder** [comment]
Der ist auf false... Soll ich diesen aktivieren?

**Comment by jomjol** [comment]
Ja!!! Der verhindert genau diesen Fehler.
