### ISSUE TITLE
mqtt funktioniert nicht

### ISSUE THREAD

**Issue by Shortypower** [jomjol/AI-on-the-edge-device#516]
Erst mal danke für dieses tolle Projekt!
Ich betreibe 3 watermeter für Wasser, Gas und Strom und bin sehr zufrieden.
Ich habe den Strommesser jetzt das neuste update verpasst. Nun funktioniert mqtt nicht mehr.
Im homeassitant kommt nichts mehr an. Ich habe natürlich das alte Topic gegen TopicMain ausgetauscht.
Folgende Konfiguration

Git-Base-Branch: master - v10.0.2 - 2022-01-01
html: 11.4.0

config.ini:
[MQTT]
Uri = mqtt://192.168.1.177:1883
MainTopic = stromzaehler/zaehlerstand
ClientID = strom

configuration.yaml:
  - platform: mqtt
    name: Stromzähler
    state_topic: "stromzaehler/zaehlerstand/main/value"
    unique_id: stromcount1
    unit_of_measurement: "kWh"
    icon: "mdi:transmission-tower"

es funktioniert einfach nicht! auch nicht wenn ich value_template: {{ value }} hinzufüge.
Die beiden noch nicht aktualisierten ESP32cams liefern zuverlässig über Topic den Wert.

**Comment by jomjol** [comment]
Mit homeassitant kenne ich mich nicht aus. 
Ab Version 10 hat sich aber folgendes geändert: es werden nur noch Werte übertragen, wenn kein Fehler gelesen wird. Ansonsten wird nichts mehr übertragen, auch nicht der vorherige Wert, da das ja eigentlich auch falsch ist.
Es kann daher, je nach Konstallation relativ lange dauern, bis wieder ein Wert übertragen wird. Du kannst im Logfile (falls eingeschaltet) sehen, was per MQTT übertragen wurde.

**Comment by Shortypower** [comment]
Danke für den Hinweis mit dem Logfile.
Dort konnte ich sehen, dass das /main/ nicht dabei sein darf. Da frag ich mich warum das in allen Beispielen steht?
Egal. Es funktioniert! Und das Update von 6. irgendwas auf 10 hat sich gelohnt: wegen wenig Abstand im Zählerschrank habe ich ein Weitwinkel objektiv im Einsatz, welches ein wenig verzerrt. Die neue Version liefert aber regelmäßig richtige Werte und findet vor allem das alignment zuverlässig! 

Jetzt kann ich sie anderen auch Updaten!

**Comment by Max242** [comment]
Könnte mir wer helfen, bring es auch nicht zusammen. Hab folgendes in der Config.ini:



mqtt:
  sensor:
    - name: "gasmeter"
      state_topic: "gasmeter/value"
      value_template: "{{ value }}"


      unit_of_measurement: "kWh"
      icon: "mdi:flash"
    - name: "Main rate meter AIOE"
      state_topic: "gasmeter/rate"
      value_template: "{{ value }}"
      icon: "mdi:swap-vertical"
    - name: "Main timestamp meter AIOE"
      state_topic: "gasmeter/timestamp"
      value_template: "{{ value }}"
      icon: "mdi:clock-outline"

  binary_sensor:
    - name: "Main error meter AIOE"
      state_topic: "gasmeter/error"
      value_template: "{%if value != 'no error' -%}ON{%-else-%}OFF{%-endif%}"
      json_attributes_topic: "gasmeter/json"
      icon: "mdi:alert-circle"

**Comment by jomjol** [comment]
Sorry, kein Experte in MQTT. Vermutlich eher ein Problem auf der Empfängerseite --> hier nicht das richtige Forum.

**Comment by Bens0n68** [comment]
Hallo Jomjol,
erstmal vielen Dank für das tolle Projekt!!
Habe 2 Zähler laufen und die zählen inzwischen ziemlich genau.

Aber seid dem letzten Update (v12.0.1) funktioniert MQTT nicht mehr richtig.
Nach einem Neustart überträgt es ein paar Mal, dann kommt nichts mehr an.
Started man den Digitizer neu klappt es wieder...Spiel beginnt von vorne.

Hast Du keine Idee was das sein könnte?
Als ugly Workarround wäre eine automatische Restart Funktionen (alle x Stunden) prima. Oder Restart über Web-Befehl - dann könne man automatisiert - wenn länger nichts mehr kommt - neu starten.

**Comment by caco3** [comment]
The next version will be far more stable (I hope).
You can wait some more days..weeks or try rolling. But be aware that a lot changed!

**Comment by Bens0n68** [comment]
> The next version will be far more stable (I hope).
> You can wait some more days..weeks or try rolling. But be aware that a lot changed!

That sounds great!
Only installed final releases so far - better will wait then - or is there a guide how to install a pre-version? Or do I only need to replace the firmware.bin with the new one?

**Comment by caco3** [comment]
You can fetch the latest rolling from here (select most top build, then scoll down): https://github.com/jomjol/AI-on-the-edge-device/actions?query=branch%3Arolling
But be aware that those automatic builds might be unstable
