### ISSUE TITLE
Falsche Erkennung von Ziffern

### ISSUE THREAD

**Issue by Reinschki** [jomjol/AI-on-the-edge-device#52]
Hallo jomjol,

ich muss mich noch mal melden:
![image](https://user-images.githubusercontent.com/74489990/99272641-4f597e00-2828-11eb-9fa9-4b6974844c3a.png)
Was kann ich in diesem Fall noch zur Verbesserung der Erkennung tun?
Das Ausrichten der Erkennungsfelder bringt jedenfalls nichts! Das habe ich in allen möglichen Varianten durch...
Die Bildschärfe ist meines Erachtens doch auch ganz ordentlich.

Gruß
Reinschki

**Comment by jomjol** [comment]
Ich würde die Ziffern etwas größer Ausschneiden:

![grafik](https://user-images.githubusercontent.com/30766535/99286213-d3b3fd00-2838-11eb-9d0d-c2b4db28e56b.png)

Und wenn das auch nicht reicht, dann müsstest du Beispielbilder sammeln (2-3 pro Ziffer, jeweils rot & schwarz) und  mir zum teachen schicken.
Gruß,
  jomjol

**Comment by Reinschki** [comment]
Hi,

größer Ausschneiden hat leider auch nichts gebracht.
![image](https://user-images.githubusercontent.com/74489990/99388864-7f5f5a80-28d6-11eb-8365-aab07714162a.png)

Die Beispielbilder für die rot hinterlegten Bilder bekomme ich ja noch hin. Bei den schwarzen dauert das Monate.
Würde das auch nur für die roten funktionieren?

Falls ja 
-Bild jeweils der kompletten Wasseruhr?
-oder nur die Ziffer?
-hier ins Forum, als Zip-Archiv?

Falls nein
-Wäre das Schade, aber nicht zu ändern.

Ein tolles Projekt! Bin begeistert!

Viele Grüße
Reinschki

**Comment by jomjol** [comment]
Hallo Reinschki,
es geht auch nur mit den roten Ziffern - kein Problem!

Ich brauche die fertig ausgeschnittenen Ziffern, idealerweise schon vom ESP32.
- 2-3 Bilder je Ziffer. Nicht mehr! hatte mal 10000 Bilder bekommen :-)
- gerne als Zip-Archiv - hier oder im ioBroker Forum

Hier mal ein Link zu den bisherigen Ziffern, die ich verwende, damit du siehst, womit schon trainiert wurde: https://github.com/jomjol/neural-network-digital-counter-readout/tree/master/ziffer_sortiert_raw

Beste Grüße,
  jomjol

**Comment by Reinschki** [comment]
Sodele,

hier meine Ziffern: [digits.zip](https://github.com/jomjol/AI-on-the-edge-device/files/5555318/digits.zip)

Da bin ich schon mal sehr gespannt!

Besten Dank & viele Grüße
Reinschki

**Comment by jomjol** [comment]
Here you are:
https://github.com/jomjol/neural-network-digital-counter-readout/blob/master/Train_CNN_Digital-Readout_Version_7.1.0-Small-v3.tflite

Lass mich wissen, ob es jetzt besser geht.

**Comment by Reinschki** [comment]
Hi jomjol,

habe es eine Weile getestet und es funktioniert jetzt prima!

Vielen Dank noch mal
Reinschki
