### ISSUE TITLE
ESP32-CAM-MB

### ISSUE THREAD

**Issue by atze09** [jomjol/AI-on-the-edge-device#520]
Hello guys,
i am struggling in flashing my ESP32-CAM with motherboard so without the "external" ftdi adapter.
The new version "flash_download_tool_3.9.2.exe" does not find the board.
I use the following settings in the device manager :
![image](https://user-images.githubusercontent.com/6229866/148171378-e8f0aa30-3a2c-4b5c-bcac-a770d94e988b.png)

But the flash download tool does not detect the board:
![image](https://user-images.githubusercontent.com/6229866/148171443-d16f676f-7ce2-4dc5-988d-565ee0b8a4c3.png)
![image](https://user-images.githubusercontent.com/6229866/148171482-22caf3fc-9605-49de-a966-9157e840338d.png)

I tried different usb cables but without success.
The NodeMCU flasher detects the board and i can flash files but i cannot flash it the way it is neccesarry.
Can someone please help me out?

**Comment by MG-CPC05** [comment]
I tried it yesterday successfully with a esp32-cam-mb.
What i did, was selecting the bin-files and entering the offsets like descripted here:

https://github.com/jomjol/AI-on-the-edge-device/wiki/Installation

First it didn't worked, but when I changed the Offsets to the following:
 
<html>
<body>


Filename | Offset
-- | --
bootloader.bin | 0x01000
partitions.bin | 0x08000
firmware.bin | 0x10000


</body>
</html>

So I expect the "0" after 0x for bootloader.bin and partitions.bin is, more or less, important.

Hope this helps

**Comment by atze09** [comment]
> I tried it yesterday successfully with a esp32-cam-mb. What i did, was selecting the bin-files and entering the offsets like descripted here:
> 
> https://github.com/jomjol/AI-on-the-edge-device/wiki/Installation
> 
> First it didn't worked, but when I changed the Offsets to the following:
> 
> Filename	Offset
> bootloader.bin	0x01000
> partitions.bin	0x08000
> firmware.bin	0x10000
> So I expect the "0" after 0x for bootloader.bin and partitions.bin is, more or less, important.
> 
> Hope this helps

Ok did also not work.
Which settings do you use?
Here
![image](https://user-images.githubusercontent.com/6229866/148190341-320f87a6-6db5-4c85-8150-aeca68fe0ac6.png)
And here:
![image](https://user-images.githubusercontent.com/6229866/148190384-33f2182d-0849-4119-baee-6f112241a68e.png)

Baud Rate?

**Comment by atze09** [comment]
It works with the command line es32tool with the following commands:

.\esp32tool.exe --chip esp32 --port COM5 --baud 115200 --before default_reset --after hard_reset write_flash -z --flash_mode dio --flash_freq 40m --flash_size detect 0x01000 .\bootloader.bin
.\esp32tool.exe --chip esp32 --port COM5 --baud 115200 --before default_reset --after hard_reset write_flash -z --flash_mode dio --flash_freq 40m --flash_size detect 0x08000 .\partitions.bin
.\esp32tool.exe --chip esp32 --port COM5 --baud 115200 --before default_reset --after hard_reset write_flash -z --flash_mode dio --flash_freq 40m --flash_size detect 0x10000 .\firmware.bin
