### ISSUE TITLE
Pipersberg gas meter digits

### ISSUE THREAD

**Issue by fabianonline** [jomjol/AI-on-the-edge-device#522]
Hi.

I'm using this project to read the digits of my Pipersberg G4 RF1 gas meter. It's working quite good, but the digits 3 and 9 have a lot of errors. While all other digits are recognized just fine, those two have a error rate of >50%.

I've attached a zip file of a few images of those two images. Would that be enough to be included in the next training round? I can also collect samples from all the digits, if necessary.

Thanks a lot.
[digits.zip](https://github.com/jomjol/AI-on-the-edge-device/files/7814432/digits.zip)

**Comment by jomjol** [comment]
I have put this images to the queue for the next training.
