### ISSUE TITLE
Dimmen der onboard LED

### ISSUE THREAD

**Issue by Tobi266** [jomjol/AI-on-the-edge-device#524]
Ist es möglich die Onboard-LED zu dimmen?
Ich habe Spiegelungen im Glas und auch das Bild ist ziemlich überbelichtet (trotz brightness -2).
Mein Quickfix ist es die LED mit einer Folie etwas abzudunkeln, aber irgendwie wäre es doch cooler das Thema (Problem will ich es nicht unbeding nennen) direkt über Software/Hardware zu lösen.

Danke und Grüße

**Comment by jomjol** [comment]
Nein ist nicht möglich und auch nicht sinnvoll, da die Kamera im automatischen Belichtungsmodus läuft. Sobald du die LED dimmst, erhöht die Kamera die Belichtungszeit.
Du kannst das Problem aber abschalten, wenn du WS2812 LEDs zur Beleuchtung nimmst. Die kannst du an einem Kabel überall hinhängen und damit die Reflexion los werden. Ansteuerung ist in der Firmware integriert.
