### ISSUE TITLE
ESP32 CAM continuously reboot

### ISSUE THREAD

**Issue by Geraldf** [jomjol/AI-on-the-edge-device#525]
I got myself an ESP32 CAM, and flashed the .bin files using the esptool.py as mentioned in the WIKI Installation. 
I was expecting the LED start flashing, but 
### nothing happens!

**My chip is the following (reading with esptool.py chip_id):**

>Detecting chip type... ESP32
Chip is ESP32-D0WDQ6 (revision 1)
Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, Coding Scheme None
Crystal is 40MHz
MAC: fc:f5:c4:0c:1c:94
Uploading stub...
Running stub...
Stub running...
Warning: ESP32 has no Chip ID. Reading MAC instead.
MAC: fc:f5:c4:0c:1c:94

**Next I looked what the board is reporting using the Arduino Serial Monitor**
>09:51:56.647 -> rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
09:51:56.647 -> configsip: 0, SPIWP:0xee
09:51:56.647 -> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
09:51:56.647 -> mode:DIO, clock div:2
09:51:56.647 -> load:0x3fff0030,len:7188
09:51:56.647 -> load:0x40078000,len:14764
09:51:56.682 -> load:0x40080400,len:3764
09:51:56.682 -> entry 0x40080680
09:51:56.682 -> boot: ESP-IDF 4.3.1 2nd stage bootloader
09:51:56.682 -> boot: compile time 08:56:34
09:51:56.682 -> boot: chip revision: 1
09:51:56.682 -> boot_comm: chip revision: 1, min. bootloader chip revision: 0
09:51:56.682 -> boot.esp32: SPI Speed      : 40MHz
09:51:56.682 -> boot.esp32: SPI Mode       : DIO
09:51:56.715 -> boot.esp32: SPI Flash Size : 4MB
09:51:56.715 -> boot: Enabling RNG early entropy source...
09:51:56.715 -> boot: Partition Table:
09:51:56.715 -> boot: ## Label            Usage          Type ST Offset   Length
09:51:56.715 -> boot:  0 nvs              WiFi data        01 02 00009000 00004000
09:51:56.715 -> boot:  1 otadata          OTA data         01 00 0000d000 00002000
09:51:56.750 -> boot:  2 phy_init         RF data          01 01 0000f000 00001000
09:51:56.750 -> boot:  3 ota_0            OTA app          00 10 00010000 001db000
09:51:56.750 -> boot:  4 ota_1            OTA app          00 11 001f0000 001db000
09:51:56.750 -> boot: End of partition table
09:51:56.750 -> boot_comm: chip revision: 1, min. application chip revision: 0
09:51:56.782 -> esp_image: segment 0: paddr=00010020 vaddr=3f400020 size=46088h (286856) map
09:51:56.885 -> esp_image: segment 1: paddr=000560b0 vaddr=3ffb0000 size=04980h ( 18816) load
09:51:56.885 -> esp_image: segment 2: paddr=0005aa38 vaddr=40080000 size=055e0h ( 21984) load
09:51:56.885 -> esp_image: segment 3: paddr=00060020 vaddr=400d0020 size=114288h (1131144) map
09:51:57.327 -> esp_image: segment 4: paddr=001742b0 vaddr=400855e0 size=1698ch ( 92556) load
09:51:57.363 -> esp_image: segment 5: paddr=0018ac44 vaddr=50000000 size=00010h (    16) load
09:51:57.396 -> boot: Loaded app from partition at offset 0x10000
09:51:57.396 -> boot: Disabling RNG early entropy source...
09:51:57.396 -> psram: This chip is ESP32-D0WD
09:51:57.396 -> psram: PSRAM ID read error: 0xffffffff
09:51:57.396 -> cpu_start: Failed to init external RAM!
09:51:57.396 -> Re-enable cpu cache.
09:51:57.431 -> 
09:51:57.431 -> abort() was called at PC 0x40082f33 on core 0
09:51:57.431 -> 
09:51:57.431 -> Backtrace:0x4008f2fd:0x3ffe3ba0 0x4008fa55:0x3ffe3bc0 0x40096851:0x3ffe3be0 0x40082f33:0x3ffe3c50 0x40079231:0x3ffe3c80 |<-CORRUPTED
09:51:57.431 -> 
09:51:57.431 -> 
09:51:57.431 -> ELF file SHA256: 05b1a13b34332619
09:51:57.431 -> 
09:51:57.431 -> Rebooting...
09:51:57.431 -> ets Jun  8 2016 00:22:57
09:51:57.431 -> 
09:51:57.431 -> rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
09:51:57.431 -> configsip: 0, SPIWP:0xee
09:51:57.431 -> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
09:51:57.464 -> mode:DIO, clock div:2
09:51:57.464 -> load:0x3fff0030,len:7188
09:51:57.464 -> load:0x40078000,len:14764
09:51:57.464 -> load:0x40080400,len:3764
09:51:57.464 -> entry 0x40080680
09:51:57.464 -> boot: ESP-IDF 4.3.1 2nd stage bootloader
09:51:57.464 -> boot: compile time 08:56:34
09:51:57.464 -> boot: chip revision: 1
09:51:57.464 -> boot_comm: chip revision: 1, min. bootloader chip revision: 0
09:51:57.498 -> boot.esp32: SPI Speed      : 40MHz
09:51:57.498 -> boot.esp32: SPI Mode       : DIO
09:51:57.498 -> boot.esp32: SPI Flash Size : 4MB
09:51:57.498 -> boot: Enabling RNG early entropy source...
09:51:57.498 -> boot: Partition Table:
09:51:57.498 -> boot: ## Label            Usage          Type ST Offset   Length
09:51:57.498 -> boot:  0 nvs              WiFi data        01 02 00009000 00004000
09:51:57.532 -> boot:  1 otadata          OTA data         01 00 0000d000 00002000
09:51:57.532 -> boot:  2 phy_init         RF data          01 01 0000f000 00001000
09:51:57.532 -> boot:  3 ota_0            OTA app          00 10 00010000 001db000
09:51:57.532 -> boot:  4 ota_1            OTA app          00 11 001f0000 001db000
09:51:57.569 -> boot: End of partition table
09:51:57.569 -> boot_comm: chip revision: 1, min. application chip revision: 0
09:51:57.569 -> esp_image: segment 0: paddr=00010020 vaddr=3f400020 size=46088h (286856) map
09:51:57.670 -> esp_image: segment 1: paddr=000560b0 vaddr=3ffb0000 size=04980h ( 18816) load
09:51:57.670 -> esp_image: segment 2: paddr=0005aa38 vaddr=40080000 size=055e0h ( 21984) load
09:51:57.704 -> esp_image: segment 3: paddr=00060020 vaddr=400d0020 size=114288h (1131144) map
09:51:58.116 -> esp_image: segment 4: paddr=001742b0 vaddr=400855e0 size=1698ch ( 92556) load
09:51:58.149 -> esp_image: segment 5: paddr=0018ac44 vaddr=50000000 size=00010h (    16) load
09:51:58.182 -> boot: Loaded app from partition at offset 0x10000
09:51:58.182 -> boot: Disabling RNG early entropy source...
09:51:58.182 -> psram: This chip is ESP32-D0WD
09:51:58.182 -> psram: PSRAM ID read error: 0xffffffff
09:51:58.182 -> cpu_start: Failed to init external RAM!
09:51:58.216 -> Re-enable cpu cache.
09:51:58.216 -> 
09:51:58.216 -> abort() was called at PC 0x40082f33 on core 0
09:51:58.216 -> 
09:51:58.216 -> Backtrace:0x4008f2fd:0x3ffe3ba0 0x4008fa55:0x3ffe3bc0 0x40096851:0x3ffe3be0 0x40082f33:0x3ffe3c50 0x40079231:0x3ffe3c80 |<-CORRUPTED
09:51:58.216 -> 
09:51:58.216 -> 
09:51:58.216 -> ELF file SHA256: 05b1a13b34332619
09:51:58.216 -> 
09:51:58.216 -> Rebooting...
09:51:58.216 -> ets Jun  8 2016 00:22:57

then I tried to compile it on my own, using the ESPRESSIF IDF plugin in VSCODE. 
Building and flashing worked fine (no error message) 
** Compile result **
>Total sizes:
Used static DRAM:   69152 bytes ( 111584 remain, 38.3% used)
      .data size:   21192 bytes
      .bss  size:   47960 bytes
Used static IRAM:  100719 bytes (  30353 remain, 76.8% used)
      .text size:   99692 bytes
   .vectors size:    1027 bytes
Used stat D/IRAM:  169871 bytes ( 141937 remain, 54.5% used)
      .data size:   21192 bytes
      .bss  size:   47960 bytes
      .text size:   99692 bytes
   .vectors size:    1027 bytes
Used Flash size : 1736627 bytes
      .text     : 1432659 bytes
      .rodata   :  303712 bytes
Total image size: 1980449 bytes (.bin may be padded larger)
** flash result **
>esptool.py v3.2-dev
Serial port /dev/cu.usbserial-14530
Connecting.....
Chip is ESP32-D0WDQ6 (revision 1)
Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, Coding Scheme None
Crystal is 40MHz
MAC: fc:f5:c4:0c:1c:94
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 460800
Changed.
Configuring flash size...
Auto-detected Flash size: 4MB
Flash will be erased from 0x00010000 to 0x001d4fff...
Flash will be erased from 0x00001000 to 0x00007fff...
Flash will be erased from 0x00008000 to 0x00008fff...
Compressed 1851616 bytes to 1049926...
Wrote 1851616 bytes (1049926 compressed) at 0x00010000 in 26.6 seconds (effective 556.7 kbit/s)...
Hash of data verified.
Compressed 26112 bytes to 16018...
Wrote 26112 bytes (16018 compressed) at 0x00001000 in 0.8 seconds (effective 261.0 kbit/s)...
Hash of data verified.
Compressed 3072 bytes to 103...
Wrote 3072 bytes (103 compressed) at 0x00008000 in 0.1 seconds (effective 385.7 kbit/s)...
Hash of data verified.
Leaving...
Hard resetting via RTS pin...

but
### Still not working

>rst:0x3 (SW_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:7416
load:0x40078000,len:14912
load:0x40080400,len:3688
0x40080400: _init at ??:?
entry 0x4008067c
I (52) boot: ESP-IDF v4.3.2-dirty 2nd stage bootloader
I (52) boot: compile time 10:01:28
I (52) boot: chip revision: 1
I (56) boot.esp32: SPI Speed      : 40MHz
I (61) boot.esp32: SPI Mode       : DIO
I (66) boot.esp32: SPI Flash Size : 4MB
I (70) boot: Enabling RNG early entropy source...
I (76) boot: Partition Table:
I (79) boot: ## Label            Usage          Type ST Offset   Length
I (86) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (94) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (101) boot:  2 factory          factory app      00 00 00010000 00100000
I (109) boot: End of partition table
I (113) esp_image: segment 0: paddr=00010020 vaddr=3f400020 size=487cch (296908) map
I (229) esp_image: segment 1: paddr=000587f4 vaddr=3ffb0000 size=052c8h ( 21192) load
I (238) esp_image: segment 2: paddr=0005dac4 vaddr=40080000 size=02554h (  9556) load
I (242) esp_image: segment 3: paddr=00060020 vaddr=400d0020 size=15dc54h (1432660) map
I (764) esp_image: segment 4: paddr=001bdc7c vaddr=40082554 size=1641ch ( 91164) load
I (802) esp_image: segment 5: paddr=001d40a0 vaddr=50000000 size=00010h (    16) load
E (802) esp_image: Image length 1851616 doesn't fit in partition length 1048576
E (807) boot: Factory app partition is not bootable
E (813) boot: No bootable app partitions in the partition table
ets Jun  8 2016 00:22:57

### Hmmm, what is going on? maybe the ESP32 CAM Board has an issue?

I tried to compile and flash the "blink" example coming with the ESPRESSIF IDF plugin. 
this example worked fine without an issue. So the board looks like it is working.

**Comment by friedpa** [comment]
My guess:
In the first case the ESP PSRAM could not be initialized:
`09:51:57.396 -> cpu_start: Failed to init external RAM!`

In the second case the compiliation went somehow wrong:
`E (802) esp_image: Image length 1851616 doesn't fit in partition length 1048576`
I am never getting a log entry that the files are compressed sent to the ESP?!

Maybe try to use "flash_download_tool_3.8.5" for Windows (never failed so far in my case)

**Comment by jomjol** [comment]
Hi, I agree to Paul for the first try: PSRAM is not working. As the blink example does not use PSRAM, you cannot deduct from the working example, that your hardware has no failure.

Regarding your own complication, the compression ist okay für this way of flashing. But the problem with the not fitting partition is an indication, that the custom partition is not activated in the sdkconfig. Did you change something or used another version than esp-idf 4.3?

**Comment by Geraldf** [comment]
@jomjol your hint with the **custom partition** did bring me a step further. 
the reboot is gone. the ESP32 CAM now connected to the WLAN, but it looks like there are some issues with the WEBSERVER now. 
>Not enought PSRAM available. Expected 4.194.304 MByte - available: 118272
Either not initialzed or too small (2MByte only) or not present at all. Firmware cannot start!!Logfile opened: /sdcard/log/message/log_2022-01-06.txt
I (14694) log: Can't open log file /sdcard/log/message/log_2022-01-06.txt
uri: /
1 uri: /, filename: , filepath: /sdcard
Filename: 
File requested: /sdcard/html/index.html
open file /sdcard/html/index.html in mode r
E (91534) serverhelp: Failed to read existing file : /sdcard/html/index.html
W (91534) httpd_txrx: httpd_resp_send_err: 500 Internal Server Error - Failed to read existing file
W (91554) httpd_uri: httpd_uri: uri handler execution failed
uri: /favicon.ico
1 uri: /favicon.ico, filename: , filepath: /sdcard
Filename: 
File requested: /sdcard/html/favicon.ico
open file /sdcard/html/favicon.ico in mode r
I (92554) serverhelp: Sending file : /sdcard/html/favicon.ico ...
I (92574) serverhelp: File sending complete
W (92614) httpd_txrx: httpd_sock_err: error in recv : 104
uri: /
1 uri: /, filename: , filepath: /sdcard
Filename: 
File requested: /sdcard/html/index.html
open file /sdcard/html/index.html in mode r
E (96854) serverhelp: Failed to read existing file : /sdcard/html/index.html
W (96854) httpd_txrx: httpd_resp_send_err: 500 Internal Server Error - Failed to read existing file
W (96874) httpd_uri: httpd_uri: uri handler execution failed
uri: /favicon.ico
1 uri: /favicon.ico, filename: , filepath: /sdcard
Filename: 
File requested: /sdcard/html/favicon.ico
open file /sdcard/html/favicon.ico in mode r
I (97364) serverhelp: Sending file : /sdcard/html/favicon.ico ...
I (97394) serverhelp: File sending complete
uri: /
1 uri: /, filename: , filepath: /sdcard
Filename: 
File requested: /sdcard/html/index.html
open file /sdcard/html/index.html in mode r
E (136564) serverhelp: Failed to read existing file : /sdcard/html/index.html
W (136564) httpd_txrx: httpd_resp_send_err: 500 Internal Server Error - Failed to read existing file
W (136584) httpd_uri: httpd_uri: uri handler execution failed
uri: /favicon.ico
1 uri: /favicon.ico, filename: , filepath: /sdcard
Filename: 
File requested: /sdcard/html/favicon.ico
open file /sdcard/html/favicon.ico in mode r
I (137174) serverhelp: Sending file : /sdcard/html/favicon.ico ...
I (137364) serverhelp: File sending complete
ets Jun  8 2016 00:22:57

**Comment by jomjol** [comment]
Did you prepare the SD card correctly?

E (91534) serverhelp: Failed to read existing file : /sdcard/html/index.html

Never the less it will not work. There is still the error message with the PSRAM
