### ISSUE TITLE
Not enought PSRAM available

### ISSUE THREAD

**Issue by MubiTec** [jomjol/AI-on-the-edge-device#526]
Hi,
I guess this log seems to be clear, what the problem is.
Now the question: Is there anything I could change to get this ESP32CAM to work? Or is it just the case that this CAM is "not good enough" for this application?

BR,

Marcel

______________________
2022-01-06T14:00:51: Time zone set to CET-1CEST,M3.5.0,M10.5.0/3
2022-01-06T14:00:51: =============================================================================================
2022-01-06T14:00:51: =================================== Main Started ============================================
2022-01-06T14:00:51: =============================================================================================
2022-01-06T14:00:55: Not enought PSRAM available. Expected 4.194.304 MByte - available: 2176418
Either not initialzed or too small (2MByte only) or not present at all. Firmware cannot start!!

**Comment by spcqike** [comment]
you should (or must?) use another modul with more PSRAM. see also [here](https://github.com/jomjol/AI-on-the-edge-device/wiki/Hardware-Compatibility) and [here](https://github.com/jomjol/AI-on-the-edge-device/issues/454) and a lot of other issues with camera or rebooting problems :)

**Comment by jomjol** [comment]
You need 4MB! Just be aware, that you need to do image processing, neutral network calculation, web server all in parallel.

**Comment by Wine1410** [comment]
Guten Abend,
ich habe das selbe Problem. Gibt es eine Möglichkeit den PSRAM zu initialisieren? Verbaut ist der ESP-PSRAM16H.
Grüße A.Schmid

**Comment by Geraldf** [comment]
> 

@Wine1410 Bis jetzt habe ich noch keine Lösung gefunden. Ich habe schon ein neues Board geordert, da ich nicht weiss, ob es am board ** Chip is ESP32-D0WDQ6 (revision 1) **, oder an meiner Config liegt. 
Wie hast Du den ESP PSRAM Chip herausbekommen?

**Comment by Wine1410** [comment]
Du kannst die Bezeichnung an folgendem Bauteil (PSRAM) ablesen.
https://www.fambach.net/esp32-cam-modul/

**Comment by jomjol** [comment]
@Wine1410: PSRAM16 ist schlicht zu wenig PSRAM. Der Speicherbaustein enthält nur 2MByte, du brauchst aber mindestens 8MByte, also 32MBit. Meistens sind dann PSRAM-Chips mit 64MBit eingebaut.

**Comment by Wine1410** [comment]
Vielen Dank für deine Antwort. Alles klar, dann schaue ich nach einem anderen ESP.
Übrigens klasse Projekt was du da aufgestellt hast :)

**Comment by MubiTec** [comment]
Oh, man braucht mindestens 8mb? Hab aus meiner Fehlermeldung gelesen, mindestens 4mb und jetzt einen mit 4mb bestellt. Naja, mal gucken, ich probiere es mal aus

**Comment by jomjol** [comment]
@MubiTec : nein, du brauchst nur 4MByte, aber sehr häufig ist ein 8MByte Modul verbaut. Ich habe noch keine Hardware mit 4MByte gesehen. die oberen 4MByte bleiben dann halt ungenutzt.
