### ISSUE TITLE
5 wird nicht erkannt

### ISSUE THREAD

**Issue by Shortypower** [jomjol/AI-on-the-edge-device#527]
Hallo
Bei meiner Wasseruhr ESPCamerkennt die Software die 5 nicht.
Ich habe versucht, alle alignemts und ROIs so genau wie möglich und exakt einzustellen.

gibts einen Tip für mich? 
Ansonsten läuft dieses Ding eigentlich sehr zuverlässig!

Neuste firmware ist drauf!

<img width="572" alt="wasserfuenf" src="https://user-images.githubusercontent.com/60262118/148406738-4d622509-c5af-4d75-b623-3bc732e08d52.png">

**Comment by jomjol** [comment]
Alignment sieht gut aus. Die 5 fängt langsam an aus dem ROI rauszulaufen. Eigentlich sollte das durch den Algorithmus mit dem PreValue kein Problem sein, da er das NaN aus den Vorwerten ersetzt. 
Aus meiner Sicht keine Aktivität notwendig. Eine der Folgeversionen wird auch mit Zwischenwerten zurecht kommen und damit keine Ns mehr haben.
