### ISSUE TITLE
Digital number in transition

### ISSUE THREAD

**Issue by vigne** [jomjol/AI-on-the-edge-device#528]
Hi,

first a great thank you for doing this amazing project.
My water meter is currently transitioning between two numbers in the digitl part, and ti seems that the software is having issues.
It was working before, but it isn't any more.

![Screenshot from 2022-01-06 20-37-52](https://user-images.githubusercontent.com/3774908/148441810-9cf63142-31d3-4a3b-a17a-2400df09cf73.png)

I understood that the project is capable to deduce numbers from previous readings, but it seems it fails in this case :-(
Maybe this info helps to improve the project.

Thanks again!

**Comment by vigne** [comment]
Started working again pretty much after filing this report. Sorry for the noise.

Cheers!

**Comment by jomjol** [comment]
Hi, no everything is as expected. 

It has tried to deduced the number from the previous and came to the conclusion: 151.9301 and this seems to be okay.
But unfortunatly in the previous run it read: 151.9599 and this is bigger (obviously missreading in the run before).
Therefore it detected a negative rate and blocked the sending of the value.
