### ISSUE TITLE
ESP32 blinkt nur einmal kurz

### ISSUE THREAD

**Issue by apprecht** [jomjol/AI-on-the-edge-device#529]
Also als erstes mal: Ein superschönes Projekt, leider hat mir das Gerät nun mit der 10.0.2er Version bei der Einrichtung irgendwie im Nachgang die config.ini gelöscht, die Bilder waren noch auf der SD-Karte. Nun habe ich versucht die SD-Karte einfach noch mal mit dem alten Inhalt zu ersetzen, dann komme ich jedoch nicht mehr auf das Webinterface.

Nun habe ich das mit einem zweiten ESP32-CAM noch mal genau so gemacht um an der gleichen Stelle hängen zu bleiben.

Danach Blinkt der ESP auch nur noch einmal kurz, eine Logfile wird nicht geschrieben, auch wenn in der config.ini gesetzt.

Hier der Output von der Seriellen Schnittstelle:

`ets Jul 29 2019 12:21:46

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:7188
load:0x40078000,len:14764
load:0x40080400,len:3764
entry 0x40080680
[0;32mI (27) boot: ESP-IDF 4.3.1 2nd stage bootloader[0m
[0;32mI (27) boot: compile time 08:56:34[0m
[0;32mI (27) boot: chip revision: 3[0m
[0;32mI (30) boot_comm: chip revision: 3, min. bootloader chip revision: 0[0m
[0;32mI (37) boot.esp32: SPI Speed      : 40MHz[0m
[0;32mI (42) boot.esp32: SPI Mode       : DIO[0m
[0;32mI (46) boot.esp32: SPI Flash Size : 4MB[0m
[0;32mI (51) boot: Enabling RNG early entropy source...[0m
[0;32mI (56) boot: Partition Table:[0m
[0;32mI (60) boot: ## Label            Usage          Type ST Offset   Length[0m
[0;32mI (67) boot:  0 nvs              WiFi data        01 02 00009000 00004000[0m
[0;32mI (75) boot:  1 otadata          OTA data         01 00 0000d000 00002000[0m
[0;32mI (82) boot:  2 phy_init         RF data          01 01 0000f000 00001000[0m
[0;32mI (89) boot:  3 ota_0            OTA app          00 10 00010000 001db000[0m
[0;32mI (97) boot:  4 ota_1            OTA app          00 11 001f0000 001db000[0m
[0;32mI (104) boot: End of partition table[0m
[0;32mI (109) boot_comm: chip revision: 3, min. application chip revision: 0[0m
[0;32mI (116) esp_image: segment 0: paddr=00010020 vaddr=3f400020 size=46088h (286856) map[0m
[0;32mI (234) esp_image: segment 1: paddr=000560b0 vaddr=3ffb0000 size=04980h ( 18816) load[0m
[0;32mI (242) esp_image: segment 2: paddr=0005aa38 vaddr=40080000 size=055e0h ( 21984) load[0m
[0;32mI (252) esp_image: segment 3: paddr=00060020 vaddr=400d0020 size=114288h (1131144) map[0m
[0;32mI (685) esp_image: segment 4: paddr=001742b0 vaddr=400855e0 size=1698ch ( 92556) load[0m
[0;32mI (725) esp_image: segment 5: paddr=0018ac44 vaddr=50000000 size=00010h (    16) load[0m
[0;32mI (739) boot: Loaded app from partition at offset 0x10000[0m
[0;32mI (740) boot: Disabling RNG early entropy source...[0m
[0;32mI (751) psram: This chip is ESP32-D0WD[0m
[0;32mI (752) spiram: Found 64MBit SPI RAM device[0m
[0;32mI (752) spiram: SPI RAM mode: flash 40m sram 40m[0m
[0;32mI (757) spiram: PSRAM initialized, cache is in low/high (2-core) mode.[0m
[0;32mI (764) cpu_start: Pro cpu up.[0m
[0;32mI (768) cpu_start: Starting app cpu, entry point is 0x40082e24[0m
[0;32mI (0) cpu_start: App cpu up.[0m
[0;32mI (1664) spiram: SPI SRAM memory test OK[0m
[0;32mI (1672) cpu_start: Pro cpu start user code[0m
[0;32mI (1672) cpu_start: cpu freq: 240000000[0m
[0;32mI (1672) cpu_start: Application information:[0m
[0;32mI (1675) cpu_start: Project name:     esp32cam-server-only[0m
[0;32mI (1681) cpu_start: App version:      0.0.9.3[0m
[0;32mI (1686) cpu_start: Compile time:     Jan  1 2022 08:54:54[0m
[0;32mI (1693) cpu_start: ELF file SHA256:  05b1a13b34332619...[0m
[0;32mI (1699) cpu_start: ESP-IDF:          4.3.1[0m
[0;32mI (1704) heap_init: Initializing. RAM available for dynamic allocation:[0m
[0;32mI (1711) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM[0m
[0;32mI (1717) heap_init: At 3FFC0500 len 0001FB00 (126 KiB): DRAM[0m
[0;32mI (1723) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM[0m
[0;32mI (1730) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM[0m
[0;32mI (1736) heap_init: At 4009BF6C len 00004094 (16 KiB): IRAM[0m
[0;32mI (1743) spiram: Adding pool of 4096K of external SPI memory to heap allocator[0m
[0;32mI (1752) spi_flash: detected chip: generic[0m
[0;32mI (1755) spi_flash: flash io: dio[0m
[0;32mI (1764) cpu_start: Starting scheduler on PRO CPU.[0m
[0;32mI (0) cpu_start: Starting scheduler on APP CPU.[0m
[0;32mI (1770) spiram: Reserving pool of 32K of internal memory for DMA/internal allocations[0m
[0;32mI (1800) main: Using SDMMC peripheral[0m
Name:      
Type: SDHC/SDXC
Speed: 20 MHz
Size: 15271MB
[0;32mI (2250) server_ota: Start CheckOTAUpdateCheck ...[0m
Start CheckOTAUpdateCheck ...
[0;32mI (2260) server_ota: SHA-256 for the partition table: : 9d4a2809ae90fb20709a8ca3dd3ac3462e1e73286bcd31b689060c91de06fa3a[0m
[0;32mI (2260) server_ota: SHA-256 for bootloader: : 292d80a5e41642d6d0447a35227444f035325e6b4656fe1a73942e79ef32d8ca[0m
[0;32mI (2270) server_ota: SHA-256 for current firmware: : c7ec6c139723e7649c673ee8740e549319b07da0998952fe47d015fe0c7c08ea[0m
CheckOTAUpdate Partition: ESP_OK
open file /sdcard/wlan.ini in mode r
file loaded

WLan: SSID, Passwort
Hostename: watermeter
I (2330) wifi:wifi driver task: 3ffd266c, prio:23, stack:6656, core=0
[0;32mI (2330) system_api: Base MAC address is not set[0m
[0;32mI (2330) system_api: read default base MAC address from EFUSE[0m
I (2340) wifi:wifi firmware version: 88c8747
I (2340) wifi:wifi certification version: v7.0
I (2340) wifi:config NVS flash: enabled
I (2350) wifi:config nano formating: disabled
I (2350) wifi:Init data frame dynamic rx buffer num: 16
I (2350) wifi:Init management frame dynamic rx buffer num: 16
I (2360) wifi:Init management short buffer num: 32
I (2360) wifi:Init static tx buffer num: 8
I (2370) wifi:Init tx cache buffer num: 16
I (2370) wifi:Init static rx buffer size: 1600
I (2380) wifi:Init static rx buffer num: 5
I (2380) wifi:Init dynamic rx buffer num: 16
[0;32mI (2380) wifi_init: rx ba win: 6[0m
[0;32mI (2390) wifi_init: tcpip mbox: 32[0m
[0;32mI (2390) wifi_init: udp mbox: 6[0m
[0;32mI (2400) wifi_init: tcp mbox: 6[0m
[0;32mI (2400) wifi_init: tcp tx win: 5744[0m
[0;32mI (2400) wifi_init: tcp rx win: 5744[0m
[0;32mI (2410) wifi_init: tcp mss: 1440[0m
[0;32mI (2410) wifi_init: WiFi IRAM OP enabled[0m
[0;32mI (2420) wifi_init: WiFi RX IRAM OP enabled[0m
[0;32mI (2440) phy_init: phy_version 4670,719f9f6,Feb 18 2021,17:07:07[0m
I (2530) wifi:mode : sta (94:b9:7e:fa:f1:f0)
I (2530) wifi:enable tsf
[0;32mI (2530) BLINK: Blinken - start[0m
[0;32mI (2540) wifi station: wifi_init_sta finished.[0m
I (2540) wifi:new:<1,0>, old:<1,0>, ap:<255,255>, sta:<1,0>, prof:1
[0;32mI (2730) BLINK: Blinken - done[0m
I (3300) wifi:state: init -> auth (b0)
I (4300) wifi:state: auth -> init (200)
I (4300) wifi:new:<1,0>, old:<1,0>, ap:<255,255>, sta:<1,0>, prof:1
[0;32mI (4300) wifi station: retry to connect to the AP[0m
[0;32mI (4310) wifi station: connect to the AP fail[0m
[0;32mI (6350) wifi station: retry to connect to the AP[0m
[0;32mI (6350) wifi station: connect to the AP fail[0m
I (6360) wifi:new:<1,0>, old:<1,0>, ap:<255,255>, sta:<1,0>, prof:1
I (6360) wifi:state: init -> auth (b0)
I (6360) wifi:state: auth -> assoc (0)
I (6420) wifi:state: assoc -> run (10)
W (6430) wifi:<ba-add>idx:0 (ifx:0, 24:5a:4c:73:1e:72), tid:5, ssn:2, winSize:64
I (6430) wifi:connected with SSID, aid = 5, channel 1, BW20, bssid = 24:5a:4c:73:1e:72
I (6430) wifi:security: WPA2-PSK, phy: bgn, rssi: -61
I (6500) wifi:pm start, type: 1

I (6500) wifi:AP's beacon interval = 102400 us, DTIM period = 1
`

In der letzten zwei Zeile gibt es alle paar Restarts ein paar Änderungen:
`W (4300) wifi:<ba-add>idx:0 (ifx:0, 24:5a:4c:73:1e:72), tid:5, ssn:2, winSize:64
I (4340) wifi:AP's beacon interval = 102400 us, DTIM period = 1`

Mich wird das Gefühl nicht ganz los, dass es ein WLAN-Problem ist, und das gerät daher nicht weitermacht. Ein Reflashen oder SD-Karte formatieren bringt leider auch nichts, es scheint dann ein wenig in einer Einbahnstraße zu klemmen. Vllt. hat jemand eine Idee?

Ähnliches (leider ohne Lösung) habe ich hier gefunden:
https://github.com/espressif/esp-idf/issues/4809
https://github.com/espressif/esp-idf/issues/2647

Nachtrag: Wenn ich in der wlan.ini noch die IP, Gateway und Netzmaske setze geht's.

Viele Grüße
Sebastian

**Comment by jomjol** [comment]
Hallo Sebastian,
ja das ist ein WLAN-Problem und die Firmware stoppt, wenn sie keine WLAN-Verbindung bekommt. Eigentlich ist WLAN auf Standart ohne spezielle Einstellung / Voraussetzung. Und wenn SSID und PASSWORT in der `wlan.ini` gesetzt sind, funktioniert es auch bei allen anderen.
