### ISSUE TITLE
Aktuelles Bild abrufen per Http

### ISSUE THREAD

**Issue by mikewolf** [jomjol/AI-on-the-edge-device#53]
HAllo ein direktaufruf wäre via http hilfreich ,
sowie früher 3000/roi.html 
oder  capture with flashlight
um den aktuellen stand direkt ohne recognition zu bekommen 

,Mit freundlichen Grüßen
mikewolf

**Comment by simonscheib** [comment]
Geht ohne Probleme über `/capture` oder `/capture_with_flashlight`. Ruf ich bei mir nach jedem MQTT publish ab, um die Bilder historisch abzulegen um manchmal falsche Werte zu korrigieren 

Gruß
Simon

**Comment by mikewolf** [comment]
Danke stand leider nicht in Doc,,,..... und ich probierte capture.html mein Fehler!

erledigt !

**Comment by simonscheib** [comment]
Falls noch jemand über den Issue stolpert, da hatte ich die Info gefunden: https://github.com/jomjol/AI-on-the-edge-device/wiki/Integrated-Functions
