### ISSUE TITLE
ESP32 CAM worked for 1-2 min than some burned smell and reset itself

### ISSUE THREAD

**Issue by fluppie** [jomjol/AI-on-the-edge-device#531]
I've received my modules Today, I got it working for a few minutes, was in the calibration image screen when the PCB became really hot and some burned smell/odour.

Could it be that my module is not a true ESP32-S ? This is the log from flashing with ESP Tool in Windows Powershell

```
esptool.py erase_flash

esptool.py v2.6
Found 2 serial ports
Serial port COM7
Connecting....
Detecting chip type... ESP32
Chip is ESP32D0WDQ6 (revision 1)
Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, Coding Scheme None
MAC: 58:bf:25:83:bf:34
Uploading stub...
Running stub...
Stub running...
Erasing flash (this may take a while)...



esptool.py write_flash 0x01000 bootloader.bin 0x08000 partitions.bin 0x10000 firmware.bin

esptool.py v2.6
Found 2 serial ports
Serial port COM7
Connecting......
Detecting chip type... ESP32
Chip is ESP32D0WDQ6 (revision 1)
Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, Coding Scheme None
MAC: 58:bf:25:83:bf:34
Uploading stub...
Running stub...
Stub running...
Configuring flash size...
Auto-detected Flash size: 4MB
Compressed 25808 bytes to 15635...
Wrote 25808 bytes (15635 compressed) at 0x00001000 in 1.4 seconds (effective 150.0 kbit/s)...
Hash of data verified.
Compressed 3072 bytes to 128...
Wrote 3072 bytes (128 compressed) at 0x00008000 in 0.0 seconds (effective 1265.3 kbit/s)...
Hash of data verified.
Compressed 1551760 bytes to 940928...
Wrote 1551760 bytes (940928 compressed) at 0x00010000 in 93.6 seconds (effective 132.6 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...
```

I have more of them, but don't want to burn them :). I have to say, I took around 12 ref images in that 1-2min timeframe. Could the current be the issue here?
Or do all of you have **ESP32D0WDQ6 (revision 1)** this chip?

![IMG_5566](https://user-images.githubusercontent.com/8402106/148537093-9e8559f9-3bac-4d16-8559-cd890b3b6292.jpg)
![IMG_5567](https://user-images.githubusercontent.com/8402106/148537099-9d58c96b-e79f-42f6-abcf-3f8284a22c4b.jpg)

**Comment by jomjol** [comment]
This is looking normal. It will get hot, if you keep the LED on, this is using ~500mA, which is really a lot!
