### ISSUE TITLE
Images misaligned

### ISSUE THREAD

**Issue by MArimont3** [jomjol/AI-on-the-edge-device#533]
First of all, thanks for this great development!

I have an issue I do not understand:
- I configured everything (I think correctly)
- When regularly refreshing the "Overview" page, I see an image and a Status "Aligning", showing the image correctly aligned, and the alignment marks and digital regions correctly covering the regions I configured.
- Somewhat later (30 sec) , after a next screen refresh, the Status is "Flow Finished", the image shown is completely misaligned, and the  digital regions do not cover (at all) anymore the regions I defined. Resulting in a Raw Value result of NNNNN.NNN

What happens ? The system first seems to be able to align correctly, but when recognizing the figures the alignment is lost...

I reconfigured several times, rebooted, restarted the ESP, ... Nothing helps. In Status=Aligning the alignment shows correct, in Status=Finished the alignment is wrong.

Any idea ?

**Comment by MArimont3** [comment]
![Capture2](https://user-images.githubusercontent.com/55663660/148581563-76b3710c-9448-49e7-baa1-088d3ae4a18c.PNG)
![Capture1](https://user-images.githubusercontent.com/55663660/148581568-3445cf8c-60be-4961-aaea-73b400d24b47.PNG)

**Comment by friedpa** [comment]
This pictures are not good enough at all, I give you an example how the picture should look like:

![grafik](https://user-images.githubusercontent.com/42890695/148586860-e8b06cc1-3723-4181-92e0-f6f8ea07b7fa.png)

Play around with the lens and the contrast as explained in the Wiki, otherwise you will not have any success.

**Comment by jomjol** [comment]
I agree to friedpa. The image quality is too low. The constrast for the alignment marks is not high enough, so it will fail to find the right position from time to time. But even if it will find it, the neural network number recognition will most propably have problems with low contrast.
