### ISSUE TITLE
Directly write to InfluxDB

### ISSUE THREAD

**Issue by bolausson** [jomjol/AI-on-the-edge-device#534]
Hej,

I am about to switch from my own water meter readout setup ["watermeter project"](https://github.com/bolausson/watermeter) to this amazing project.

I am wondering if there are any plans to e.g. write directly to a InfluxDB server using e.g. [influxdb-cpp](https://github.com/orca-zhang/influxdb-cpp) and make the connection configurable via the Web-Interface.

My C/C++ skills are "read only" - so as much as I would love to contribute this, I can't :(

_By the way, I have generated a annotated library [picture of a digit <-> value it shows] to train my neural network. It contains chopped of numbers, distorted numbers etc which have manually been assigned a value and has a size of 924 MB - let me know if this might be useful for you. My best model can be found [here](https://github.com/bolausson/watermeter/tree/main/training/model)_

Cheers,
Bjoern

**Comment by jomjol** [comment]
Your signal processing tool is a great project.

I would be interested in your training data, it might be good aditional data for my neural network: https://github.com/jomjol/neural-network-digital-counter-readout

Currently I don't have time and capacity to extend the firmware with another interface like InfluxDB. At the end I'm also using InfluxDB, bug going the way through an MQTT broker.

I will put the idea to the Feature Request list, but that also means, I'm not working on it for the moment.

**Comment by bolausson** [comment]
Is there a way I can send you a direct message with the Link to training data?

**Comment by jomjol** [comment]
You can send me an email: 
![grafik](https://user-images.githubusercontent.com/30766535/148676487-f1b70bc7-7c6e-41e1-b550-8c13b3b9adf8.png)

**Comment by bolausson** [comment]
Done!

**Comment by wetneb** [comment]
I am starting to work on this issue.

**Comment by bolausson** [comment]
This is great news! Thanks a lot!
Can you consider to write as well the "certainty" with which each digit has been recognized to InfluxDB? If you plot this via e.g. Grafana it is easy to see with which numbers the network has issues.

**Comment by jomjol** [comment]
Reopten the issue due to new activities

**Comment by wetneb** [comment]
@jomjol have you got any thoughts about which library would be acceptable to add as a dependency to implement this feature? If the project already depends on some HTTP client library then I could just use that, otherwise it could make sense to use an InfluxDB-specific library such as https://github.com/tobiasschuerg/InfluxDB-Client-for-Arduino?

**Comment by jomjol** [comment]
Nothing prefered. It needs to be in a dedicated class and should not need too many space in the firmware as there are only 10% left.

**Comment by jomjol** [comment]
Meanwhile integraded

**Comment by Surfrobbe** [comment]
Storing directly into InfluxDB 2.0 is not working for me with version 15.3. Don't I need to specify the bucket where it should store the data? 

I can only send the data via MQTT to the ioBroker and write it to InfluxDB from there. However, it also stores incorrect values (error) for me. The "Previous Value" is set to true, and "allow negative rates" is set to false.
