### ISSUE TITLE
Image with size 0 loaded

### ISSUE THREAD

**Issue by uwedamm** [jomjol/AI-on-the-edge-device#535]
Hello,
my log-file shows that error-message approx once per hour (random time-scale):

> 2022-01-08T17:23:37: Image with size 0 loaded --> reboot to be done! Check that your camera module is working and connected properly.
2022-01-08T17:23:37: Reboot in 5sec
2022-01-08T17:23:48: Time zone set to CET-1CEST,M3.5.0,M10.5.0/3
2022-01-08T17:23:48: =============================================================================================
2022-01-08T17:23:49: =================================== Main Started ============================================
2022-01-08T17:23:49: =============================================================================================

Do you have experience with this message?
Is this due to weak power supply? (Till now, I do have RAW ESP32-CAM without additional capacitor value, which is connected to 5V of a USB power supply).
Or do you have any other idea, what I can check?

Thank you for that great project!!!
I was really amazed about the simpleness of installation and it works already fine for the 1st day.

**Comment by jomjol** [comment]
No - this is some instability of the camera or the camera driver. This is getting more severy since version 10. Reason unknown and under investigation. But will take a longer time.

**Comment by uwedamm** [comment]
@grimmaldus:
Did you solve it by reconnecting camera, etc.?
My setup works fine for the past few days (beside issues with the analog-digit detection for the m^3, I have to clarify in another issue) only these reboots approx each hour.
When I find the time, I will check
a) reconnect the camera
b) if a) does not change anything THEN solder a smal Tantal-CAP to the 5V line, just to check if it makes a difference

**Comment by grimmaldus** [comment]
@uwedamm 
I don't have physical access to the device at the moment. I've rolled back to 9.2.0, the only thing that I could do now. 
Anyway I will try your suggestions after the weekend. 

P.S. I'm using power supply which has filtered output I believe :D But I can put there 47-µF on 5V line just to be sure.

**Comment by uwedamm** [comment]
I replaced the power supply ...
Now I cannot readout the logfiles any more🤔
`Header fields are too long for server to interpret`
Have to check the SDCARD. ..

**Comment by grimmaldus** [comment]
This indicates that the header sent by the application is too large to be interpreted by the Server installed in the ESP32.
Try to load it in Firefox.

**Comment by NitramH** [comment]
Do you have any news about that issue?

It seems to be a systematical failure, nearly every 3h and 50min I get this message (see below)




2022-07-21T**01:51**:13: Image with size 0 loaded --> reboot to be done! Check that your camera module is working and connected properly.
2022-07-21T01:51:14: Reboot in 5sec
.....
2022-07-21T**05:40**:00: Image with size 0 loaded --> reboot to be done! Check that your camera module is working and connected properly.
2022-07-21T05:40:01: Reboot in 5sec
....
2022-07-21T**09:28**:49: Image with size 0 loaded --> reboot to be done! Check that your camera module is working and connected properly.
2022-07-21T09:28:49: Reboot in 5sec

**Comment by jomjol** [comment]
Hi, this looks like an instable hardware. Either the power supply or the ESP32 itself.

**Comment by NitramH** [comment]
Sorry, i do not believe that, because it is systematic repeating error.
Instable HW would not have a identical repetition time pattern.

I think it is a SW issue, maybe a driver problem?

**Comment by jomjol** [comment]
Well, can also be a driver problem or an overflow in a variable. But following observations in my systems (4x) and of others:

There are 1:1 identical settings. One of them is running for weeks without any reboot, another is rebooting every 2-3 hours. Changing the hardware of the second (identical config), the reboot was gone.

In any case nothing, I will follow up. The work around is a rather stable system with respect to reboot.

**Comment by grimmaldus** [comment]
You can try to debug current issues by yourself by adding this into source code:

```#include "soc/soc.h"
#include "soc/rtc_cntl_reg.h"```

and into setup() function:

```void setup() {
  WRITE_PERI_REG(RTC_CNTL_BROWN_OUT_REG, 0); //disable   detector
  //Your code
}```

then you can watch serial monitor if you see something like:
`'Brownout detector was triggered'`

More about Brownout Detector [here ](https://iotespresso.com/how-to-disable-brownout-detector-in-esp32-in-arduino/)

**Comment by SlavMAK** [comment]
I'm facing the same problem, maybe my log will be useful.

`Image loaded from memory: 0, 0, 0
E (19796) CImageBasis: Image with size 0 loaded --> reboot to be done! Check that your camera module is working and connected properly.
Image with size 0 loaded --> reboot to be done! Check that your camera module is working and connected properly.
Reboot triggered by Software (5s).
I (19826) server_ota: Reboot in 5sec
Reboot in 5sec
Guru Meditation Error: Core  0 panic'ed (LoadProhibited). Exception was unhandled.

Core  0 register dump:
PC      : 0x400efe0f  PS      : 0x00060e30  A0      : 0x800f06e1  A1      : 0x3ffea490  
A2      : 0x3fff4f8c  A3      : 0x3ffc3a3c  A4      : 0x00060023  A5      : 0x3ffcd2f8  
A6      : 0x00000000  A7      : 0x00000000  A8      : 0x3ffc2cb4  A9      : 0x02000841  
A10     : 0x3ffb72b8  A11     : 0x3ffb72c0  A12     : 0x3ffb72b8  A13     : 0x00060e20  
A14     : 0x000000fe  A15     : 0x00000001  SAR     : 0x00000000  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x02000855  LBEG    : 0x00000000  LEND    : 0x00000000  LCOUNT  : 0x00000000  

Backtrace:0x400efe0c:0x3ffea490 0x400f06de:0x3ffea4c0


ELF file SHA256: 28356ed42df4c694

Rebooting...
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:7664
load:0x40078000,len:15360
load:0x40080400,len:3744
entry 0x4008067c`

**Comment by jomjol** [comment]
Looks like you have a problem with the camera. Try to check the cabling and connection.
