### ISSUE TITLE
Erkennung

### ISSUE THREAD

**Issue by route662** [jomjol/AI-on-the-edge-device#536]
Hallo,
Leider bekomme ich es nicht hin, das hier die richtige Zahl 715, xxxx erkannt wird. Erkannt wird immer 716,xxxx.
Gibt es noch Ideen, was ich ändern könnte?

[Screenshot_20220109_081131_com android chrome](https://user-images.githubusercontent.com/97343669/148672970-193859db-2298-4e85-aef9-ea8d0dd5e83a.jpg)

**Comment by jomjol** [comment]
Hallo,
vorweg: du könntest deine ROIs noch besser einstellen: https://github.com/jomjol/AI-on-the-edge-device/wiki/ROI-Configuration

Ansonsten: zunächst wird ja die richtige Zahl erkannt: 716,79... Damit der Algo erkennt, dass es noch nicht ganz bei 716, sondern noch bei 715 liegt, musst du
1. UsePreValue aktivieren (`PreValueUse = true`)
2. PreValue setzen (Configuratin --> SetPreValue)
3. Idealerweise noch im Expertenmodus folgenden Paramter aktivieren: `CheckDigitIncreaseConsistency = true`

**Comment by route662** [comment]
Danke für deine Hilfe & Rückmeldung, preValue war/ist gesetzt, die anderen beiden Einstellungen noch nachgezogen und die Areas nochmal genauer gesetzt.
Trotzdem stellt er es immer auf 719,** statt 718,***
![Screenshot_20220117_222205_com android chrome](https://user-images.githubusercontent.com/97343669/149892486-90770eaf-0ce4-4c4a-a8e7-3578c8975de2.jpg)

**Comment by route662** [comment]
![Screenshot_20220118_084640_com android chrome](https://user-images.githubusercontent.com/97343669/149893035-82f2bc87-570a-418c-8c2a-32c63989b9fc.jpg)

**Comment by route662** [comment]
![Screenshot_20220118_084640_com android chrome](https://user-images.githubusercontent.com/97343669/149893154-019dac0f-7c38-4c36-a3a3-c1a5ebb22e7f.jpg)

**Comment by route662** [comment]
Ich habe leider weiterhin das Problem, das die Erkennung der ersten 3 Ziffern nicht richtig funktioniert. Irgendwann in den letzten 24h wurde es wieder um 1qm zu hoch erkannt.
PreValue war richtig gesetzt. Digital-ROI sind soweit "oben" gesetzt, da sonst immer deutlich zu früh auf die nächste Zahl "umgestellt" wird / diese zu früh erkannt wird?

![image](https://user-images.githubusercontent.com/97343669/153263483-d42ba4ba-936b-47c7-a262-567f4fd5c6bb.png)

**Comment by jomjol** [comment]
Du musst dein Alignment besser einstellen. Die Zifferns sind ja in einer Ecke des ROIs. Details siehe hier: https://github.com/jomjol/AI-on-the-edge-device/wiki/ROI-Configuration

Die Ziffern sollten zentral in der Mitte sein, mit 20% Rand.

**Comment by route662** [comment]
Hallo, die hatte ich perfekt eingestellt, auch genau mit 20% wie beschrieben.
Da hatte ich dann das Problem, dass viel zu "früh" die neue Zahl erkannt wurde, und dann bereits "umgeschaltet". Deshalb hatte ich da ja so weit hoch geschoben, um spätest-möglich eine Erkennung zu erreichen.
Soll ich sonst mal mit Klebeband den Bereich so abkleben, dass der untere Rand nicht mehr im Sichtbereich ist?

**Comment by jomjol** [comment]
Nein, du kannst im Expertenmodus "CheckDigitIncreaseConsitency" aktivieren, dass sollte bei korrekter Erkennung genau diesen Effekt verhindern.

**Comment by route662** [comment]
Das CheckDigitIncreaseConsitency ist bereits die ganze Zeit gesetzt, verhindert es leider nicht.

**Comment by jomjol** [comment]
Ich bin gerade dabei, auch wieder die Möglichkeit, eine absolute Veränderung (statt normiert auf Zeit) zu implementieren. Das sollte das ganze wieder stabiler machen. Muss noch ein paar Dinge anpassen und testen.
