### ISSUE TITLE
Konfiguration nach update 7.12 auf 10.10 nicht mehr möglich

### ISSUE THREAD

**Issue by Sonnenfan** [jomjol/AI-on-the-edge-device#537]
Hallo und guten Tag!
Der Wasserzähler hat für Monate sehr gut funktioniert. Nach dem Update (firmware und html) erscheint unter "edit configuration" eine leere Seite. Die Erkennung läuft, es findet kein Übermittlung per MQTT mehr statt. Die config.ini ist vorhanden und sieht ok aus. Habe probeweise den setupmode=true gesetzt ohne Effekt.
Was ist denn da los? Was kann man tun?
Viele Grüße

![Screenshot 2022-01-09 123721](https://user-images.githubusercontent.com/97387713/148680695-0cee0bef-d9f7-4add-8500-a414938ee026.jpg)

**Comment by jomjol** [comment]
Wenn du von Version 7.x direkt auf 10.x gehst, dann ist die `config.ini` nicht mehr kompatibel. Irgendwo bei 8.x musste ich dort eine Ergänzung vornehmen. In der Version gab es auch einige Zeit lang einen Kompatibitätsmodus, aber es kann sein, dass die Änderungen inzwischen zu groß sind.

Es gibt eventuell eine Möglichkeit: die `config.ini` einmalig im Konfigurationsmodus öffnen und wieder schreiben. Dann sollten alle Werte im neuen Format sein.
Aber vermutlich wirst du entweder bei 7.x bleiben müssen oder einmal alles neu aufsetzen. Dazu dann die SD-Karte mit den Default-Werten aus dem GitHub überschreiben.
