### ISSUE TITLE
MQTT - Auflistung der Topics

### ISSUE THREAD

**Issue by wlan4you** [jomjol/AI-on-the-edge-device#538]
Hallo,
leider muss ich mein 2er Set mit der ESP32-CAM zurück schicken (neues ist Unterwegs), da eine CAM defekt ist.
Jedoch habe ich es gestern schon geschafft die Cam an sich ans laufen zu bringen auch mit "unschrfwn" Bild, da ich, wegen des defektes, den Fokus noch nicht verdrehen kann.
Jedoch hab ich so meine Probleme mit dem MQTT.

Gibt es eine Auflistung der gesamten MQTT Struktur?
Gestern hatte ich noch einen Wert gesehen, der VALUE hiess.
Heute ist er weg und kommt nicht mehr.

Grüße und fettes Danke für das geile Projekt.
Als nächstes will ich versuchen mit der 2. Cam meinen Stromzähler auszulesen.

![Wasser](https://user-images.githubusercontent.com/60288714/148681043-7e9bbdde-06ff-4cdb-a901-9b4d4ba9304b.JPG)

**Comment by jomjol** [comment]
Du hast mehrere Quellen für den json:
http://IP-ADRESSE/json
![grafik](https://user-images.githubusercontent.com/30766535/148681447-45fe0d4b-7b49-42c8-ae28-75fee9d421f2.png)

oder über den MQTT-Broker, dann jeweils als Topic für die jeweilige Zahl
{
  "value": 19962.88,
  "raw": "NNNNN.NN",
  "error": "no error",
  "rate": 0,
  "timestamp": "2022-01-09T13:02:27"
}

**Comment by wlan4you** [comment]
Ja, danke
Aber an sich sind das ja nicht alle.
Aktuell sehe ich ja noch
connection
freeMem

Was gäbe es denn da noch?
Aktuelle Firmware?
Wlan Empfangsqualität RSSI?

**Comment by jomjol** [comment]
Hier ein Screenshot aller übermittelten Werte für ein System mit zwei Zahlen:
![grafik](https://user-images.githubusercontent.com/30766535/148694066-b3ff9bd5-4dbf-44d7-968d-20f4cc31681d.png)
