### ISSUE TITLE
Digital ROI falsch erkannt

### ISSUE THREAD

**Issue by bommel947** [jomjol/AI-on-the-edge-device#539]
Hallo und danke erstmals für das tolle Projekt.

Ich hab Schwierigkeiten mit der 1er Stelle - diese wird partout nicht zuverlässig erkannt.
Der 3er wird immer als 0 interpretiert

![image](https://user-images.githubusercontent.com/45903971/148682116-a43b7c31-d62d-4562-a431-7dbe5d6f80b0.png)

Schon versucht die ROI neu zu erstellen -> hat leider auch nix gebracht :-(

Versionen:
Git: master - v10.1.0 - 2022-01-09
HTML Version: 11.4.0

Vielen Dank für eventuelle Tips & Hilfestellungen

**Comment by jomjol** [comment]
Bitte zunächst die ROIs gemäß folgender Geometrie nochmal optimieren: https://github.com/jomjol/AI-on-the-edge-device/wiki/ROI-Configuration

Wenn es dann immer noch nicht passt, müsste ich ggf. deine Ziffern mit in Training aufnehmen.
