### ISSUE TITLE
mqtt output

### ISSUE THREAD

**Issue by merbanan** [jomjol/AI-on-the-edge-device#54]
I have MaxRateValue = 1.0 and AllowNegativeRates = False in my config but a digital 0 got identified as a 6 so I got a delta of 6000m³ over mqtt. After some hours it returned to a 0 and the mqtt reported value was the reported correctly.

So I think mqtt output is triggered even though the Checked Value: is the old.

**Comment by jomjol** [comment]
Thanks for the hint. I have found an error in the implementation of the "UsePreValue". Because of this under certain circumstances the MaxRateValue and AllowNegativeRates check was not functional.
In the rolling version of today, this error should be corrected.
