### ISSUE TITLE
Rote Ziffern werden nicht erkannt.

### ISSUE THREAD

**Issue by HousseB** [jomjol/AI-on-the-edge-device#541]
Hoi!

Erstmal cooles Projekt! Danke fürs sharen!

Ich hab bei meinem Zähler das Problem dass die roten Ziffern nicht erkannt werden...
Die werden immer als NaN zurückgemeldet.

Gibt es dazu irgend eine Lösung??
![image](https://user-images.githubusercontent.com/97395053/148686330-38198fb6-4516-460d-8c9a-1c1c5b5e523f.png)

**Comment by jomjol** [comment]
Im ersten Schritt bitte erstmal das ROI gemäß folgender Anleitung optimieren: https://github.com/jomjol/AI-on-the-edge-device/wiki/ROI-Configuration

Wenn das auch noch nicht hilft, muss ich deine Ziffern mit ins Training aufnehmen (dazu siehe auch Details im o.g. Link).
