### ISSUE TITLE
Header fields are too long for server to interpret

### ISSUE THREAD

**Issue by viper-666** [jomjol/AI-on-the-edge-device#542]
Seitdem ich meine beiden ESPs auf die Version 10 über OTA upgedatet habe bekomme ich bei unterschiedlichen Browsern (Opera, Chrome) beim Webinterface sehr oft die Fehlermeldung "Header fields are too long for server to interpret".
Wenn ich das Webinterface mit einem Browser öffne mit dem ich noch nie auf diesen war funktioniert es erst mal wieder für eine Zeit.

**Comment by friedpa** [comment]
Duplicate of #502 (please see #502)
