### ISSUE TITLE
ESP32 does not send MQTT messages at v10.1.0

### ISSUE THREAD

**Issue by sgoudsme** [jomjol/AI-on-the-edge-device#543]
[log_2022-01-09.txt](https://github.com/jomjol/AI-on-the-edge-device/files/7835636/log_2022-01-09.txt)

Hi, 
After updating to version 10.1.0, the numbers are recognised a lot better for me, but it does not send any mqtt messages anymore.
I added the logfile and the config. ini in the attachements. 

You can see that at the beginning, there are messages like 'sent publish successful in MQTTPublish', but after reboot and update, these messages are not in the log file anymore.

I did the update via OTA on the device itself.

Do I have to edit the config file?
Is it possible that MQTT is broken after the update?

Regards,
Sibrecht

**Comment by mcbo007** [comment]
Thanks for your beautiful project! 

I have the same problems with version 10.1.0. 
The values from web interface and json-file are ok. 
Over mqtt will not send teh correctly values.

Thanks

Marcel

**Comment by zuzu59** [comment]
Hello,
Super thank you for this wonderful project!

That worked well until today when I switched to version 10.1.0 where I no longer receive anything on the mqtt :-(

Coming back to the December version, it works again!

**Comment by haeuslesbauer** [comment]
Also a big thank you for this great project from my side!
Updated to 10.1.0 today and now the recognition works much better.
I also use (and used before) MQTT. But it still works fine with 10.1.0. Updated firmware and help file via OTA on the device.

**Comment by zuzu59** [comment]
Version 10.0.2 does not work either!
![Capture d’écran 2022-01-09 à 20 03 31](https://user-images.githubusercontent.com/15345233/148696855-506ccc25-d335-4d82-9c12-07b386da0e20.png)

Yet she decodes the numbers correctly on the gas meter

**Comment by zuzu59** [comment]
There you have it, the last version that works with my mqtt broker is 10.0.1!

https://github.com/jomjol/AI-on-the-edge-device/tree/98f9274085f32fac2975d7782689235533cf254d

**Comment by Nachgefragt** [comment]
Wenn MQTT nicht sendet bitte mal in der Config MQTT und alle darunter liegenden Optionen der MQTT-Einstellungen deaktivieren (Haken weg) und abspeichern, danach wieder anhaken und rebooten. Schein bei mir aktuell geholfen zu haben.

**Comment by bommel947** [comment]
> Wenn MQTT nicht sendet bitte mal in der Config MQTT und alle darunter liegenden Optionen der MQTT-Einstellungen deaktivieren (Haken weg) und abspeichern, danach wieder anhaken und rebooten. Schein bei mir aktuell geholfen zu haben.

Nope. Kann ich nicht bestätigen.
Daten werden trotzdem nicht mehr via MQTT gesendet.

**Comment by Nachgefragt** [comment]
> 

Muss dir leider zustimmen hatte kurz den Eindruck, muss aber wohl durch mich manuell ausgelöst worden sein. Bug ist also noch vorhanden.

**Comment by jomjol** [comment]
Könnt ihr mir mal den Abschnitt zum MQTT posten?

Eigentlich hat sich an dem Teil nichts geändert. Wenn er jetzt aber nichts mehr sendet, scheint er keine Verbindung zum MQTT-Broker aufbauen zu können. Denn dann sendet er einfach nicht. 
Ursache unklar - aber bei mir funktioniert es auf 4 Geräten. Mal schauen, ob ich einen Unterschied finde.

**Comment by sgoudsme** [comment]
![image](https://user-images.githubusercontent.com/16043322/148832693-c548874b-91c5-4ad1-a3d9-0ec25427c5a9.png)
(Im not German speaking)
This is my MQTT section.
Should there be an error message when there is no connection to the mqtt broker in the log file?

**Comment by jomjol** [comment]
In principle, this is looking really okay. Regarding the log message, I need to check. Most propably, there is currently no message, but I should put one for sure.

**Comment by sgoudsme** [comment]
As extra info: I now flashed my mcu with v10.0.2 and it is working just fine...
There should be something different in the 10.1.0?
![image](https://user-images.githubusercontent.com/16043322/148895453-1f529341-1660-4125-a0de-6f5fb289cbf8.png)

**Comment by homecineplexx** [comment]
Mich trifft das selbe Problem

**Comment by tunip** [comment]
I have nearly the same issue. MQTT messages are sent out, but the intervall is extreme high. Issue starts with the upgrade to 10.1.0 yesterday (red line):

![9BD5C6CB-BEDA-4465-8BE6-4404690C8FFC](https://user-images.githubusercontent.com/11404472/148990485-a6c3b093-9aff-460f-8b20-ae545ef2fa49.jpeg)

**Comment by zuzu59** [comment]
My two cents
![Capture d’écran 2022-01-12 à 08 25 02](https://user-images.githubusercontent.com/15345233/149082667-eeb3731d-a072-4d2b-8dc7-03b379cf8501.png)

**Comment by Schmakus** [comment]
Hi, gleiches MQTT Problem mit der v10.1.0

**Comment by tigerduck** [comment]
Same problem for me in Version master - v10.1.0 - 2022-01-09.
Some debugging pointed me to `interface_mqtt.cpp` where the command `esp_mqtt_client_start(client)` returns -1(ESP_FAIL).
But no clue why this happens...

**Comment by jomjol** [comment]
Hi guys,
I found the problem with the MQTT - it was a bug in the graphical user interface of v10. As long as you did not change a parameter everything was fine. But after saving the config againg, there was a problem with the MQTT-Parmater for the topic (renamed from "Topic" to "MainTopic".

The problem should be solved with the change to v10.1.1 (especially the html.zip) and a little bit of manual work:

**10.1.1 - Stability Increase (2022-01-12)**

- Bug Fix MQTT problem
 - Issue:
        Changing from v9.x to 10.x the MQTT-paramter "Topic" was renamed into "MainTopic" to address multiple number meters This renaming should have been done automatically in the background within the graphical configuration, but was not working. Instead the parameter "Topic" was deleted and "MainTopic" was set to disabled and "undefined".
    
- ToDo
  - Update the html.zip
  - If old config.ini available: copy it to /config, open the graphical configuration and save it again.
  - If old config.ini not available: reset the parameter "MainTopic" within the config.ini manually
   - Reboot
   
   
### I appoligize for the inconvinience.

**Comment by tigerduck** [comment]
Hi,
leider hat die neue Version das Problem bei mir nicht behoben.
Es wird immer noch ESP_FAIL beim Aufruf von esp_mqtt_client_start zurück gegeben. Somit läuft der Mqtt-Task nicht...

**Comment by zuzu59** [comment]
Hello,
I tried this morning and at home also 10.1.1 does not work, I had to go back to 10.0.1, which works fine with my mqtt broker.
But in order not to spam, I was waiting for others to have the problem too ;-)

**Comment by tigerduck** [comment]
The issue came in with commit 8dd3a9267131af602b37479e42e74ab132e17090 (Rolling 20220103).
The xTaskCreate() call inside of esp_mqtt_client_start() fails.

**Comment by Schmakus** [comment]
> If old config.ini not available: reset the parameter "MainTopic" within the config.ini manually
Was ist damit gemeint?
Das Problem ist mit der neuen v10.1.1 HTML nicht behoben

**Comment by jomjol** [comment]
@Schmakus @tigerduck  Ihr müsst in der Config.ini manuel den Parameter "MainTopic"
1. wieder aktivieren (";" entfernen)
2. auf den Topic in MQTT-Broker setzen, den du brauchst.

Dieser Wert ist leider durch den Fehler gelöscht worden. Wenn es damit nicht gelöst ist, bitte eure config.ini hier mal posten.

**Comment by Dobi62** [comment]
Hallo zusammen

Ich hab 2 Kameras in betrieb. Einmal für Gas und einmal für Wasser.
Eine Kamera funktioniert nach einspielen der alten config.ini, die andere nicht.
Die MQTT-Daten sind bei beiden gleich.

Just zur Info.

Bin mit der nicht funktionierenden wieder auf eine alte Version gewechselt.
Damit geht wieder alles

**Comment by jomjol** [comment]
@Dobi62 : hast du ein paar Infos zum nicht funktionierenden System? Das ist merkwürdig und würde ich versuchen etwas besser zu verstehen, da einige Nutzer das Problem wohl haben.

**Comment by zuzu59** [comment]
Hello,
Here is my config.ini, hoping it can help with the resolution?

```
[MakeImage]
;LogImageLocation = /log/source
WaitBeforeTakingPicture = 5
;LogfileRetentionInDays = 15
Brightness = -2
;Contrast = 0
;Saturation = 0
ImageQuality = 5
ImageSize = VGA
FixedExposure = false

[Alignment]
InitialRotate = 3
InitialMirror = false
SearchFieldX = 20
SearchFieldY = 20
AlignmentAlgo = default
FlipImageSize = false
/config/ref0.jpg 155 139
/config/ref1.jpg 459 398

[Digits]
Model = /config/dig1330s1q.tflite
;LogImageLocation = /log/digit
;LogfileRetentionInDays = 3
ModelInputSize = 20 32
main.digit1 244 264 23 38
main.digit2 277 264 23 38
main.digit3 308 264 23 38
main.digit4 340 264 23 38
main.digit5 369 264 23 38
main.digit6 399 264 23 38

;[Analog]
Model = /config/ana0910s3_longq.tflite
;LogImageLocation = /log/analog
;LogfileRetentionInDays = 3
ModelInputSize = 32 32
main.ana1 432 230 92 92
main.ana2 379 332 92 92
main.ana3 283 374 92 92
main.ana4 155 328 92 92

[PostProcessing]
main.DecimalShift = -3
PreValueUse = true
PreValueAgeStartup = 720
AllowNegativeRates = false
main.MaxRateValue = 0.05
;main.ExtendedResolution = false
;main.IgnoreLeadingNaN = false
ErrorMessage = true
CheckDigitIncreaseConsistency = false

[MQTT]
Uri = mqtt://x.x.x.x:1883
MainTopic = gazmeter1
ClientID = toto
user = toto
password = toto

;[GPIO]
;IO0 = input disabled 10 false false 
;IO1 = input disabled 10 false false 
;IO3 = input disabled 10 false false 
;IO4 = built-in-led disabled 10 false false 
;IO12 = input-pullup disabled 10 false false 
;IO13 = input-pullup disabled 10 false false 
LEDType = WS2812
LEDNumbers = 2
LEDColor = 50 50 50

[AutoTimer]
AutoStart = true
Intervall = 5

[Debug]
Logfile = true
LogfileRetentionInDays = 3

[System]
TimeZone = CET-1CEST,M3.5.0,M10.5.0/3
;TimeServer = undefined
;AutoAdjustSummertime = false
;Hostname = undefined
SetupMode = false
```

**Comment by Dobi62** [comment]
@jomjol : Was willst du denn wissen? 
Meine config. ini sieht aus wie die von Zuzu59 nur das ich die alten Werte von Topic anstatt MainTopic und einem anderen, 
der mir gerade nicht einfällt (bin auf der Arbeit), noch in der config stehen habe. 
Wie gesagt habe ich beide cam mit der selben config bestückt.
Eine funktioniert und eine nicht.
Wenn ich dir was anderes zukommen lassen soll, lasse es mich wissen.
Dann kann ich mich heute Abend darum kümmern.

**Comment by muevol** [comment]
Hi @jomjol,

ich möchte mich mal mit in die Diskussion einmischen, da ich selber von dem MQTT-Fehler mit 10.1.0 betroffen war und ihn mit 10.1.1 nicht beheben konnte.
Ich glaube das der Fehler ursächlich nichts mit der config.ini zu tun hat, wie es friedpa in
https://github.com/jomjol/AI-on-the-edge-device/issues/558#issue-1100233100
beschrieben hat.

Die Umstellung des MQTT-Parameters von "Topic" zu "MainTopic" hat doch schon mit Version 8.0.0 statt gefunden, denn dort hast du ihn erstmalig in der config.ini eingeführt.
8.0.0 config.ini (Multi Meter Support)
;[MQTT]
;Uri = mqtt://IP-ADRESS:1883
;MainTopic = wasserzaehler
;ClientID = wasser
;user = USERNAME
;password = PASSWORD

Vorherige Version:
7.1.2 config.ini
[MQTT]
;Uri = mqtt://IP-ADRESS:1883
;Topic = wasserzaehler/zaehlerstand
;TopicError = wasserzaehler/error
;TopicRate = wasserzaehler/rate
;TopicTimeStamp = wasserzaehler/timestamp
;ClientID = wasser
;user = USERNAME
;password = PASSWORD

Mit der Umstellung haben sich auch die Topics zum Empfang auf MQTT-Client geändert
8.0.0 Topic
wasserzaehler/connection
wasserzaehler/main/error
wasserzaehler/freeMem
wasserzaehler/main/json
wasserzaehler/main/rate
wasserzaehler/main/timestamp
wasserzaehler/uptime
wasserzaehler/main/value

7.1.2 Topic
wasserzaehler/error
wasserzaehler/rate
wasserzaehler/timestamp
wasserzaehler/zaehlerstand

Wie man sieht wurden die Topics zum Teil mit "main" erweitert.
Meine Schlussfolgerung daraus, wenn man eine ältere config.ini (7.x) nicht angepasst hat, diese mit 10.x ändert, werden die Topics um "main" erweitert, was man erst im Logfile sieht, und dadurch kann der MQTT-Client keine Daten mehr empfangen.
Deine Änderung von "Topic" zu "MainTopic" und der Beseitigung von "undefined" in der congig.ini hat in jeden Fall seine Berechtigung, aber ich glaube, das sie nicht ursächlich für den MQTT-Fehler verantwortlich ist.
Viele hatten ihre config.ini schon mit MainTopic angepasst, so wie ich, bis einschließlich 10.0.2 lief auch alles ohne MQTT-Problene.
Ich kann mich auch mit meiner These irren, zumal ich es nicht mit einer Testumgebung bweisen kann und Versionen 10.1.x bei dir und einigen anderen tadellos laufen, aber vielleicht können sie als Denkanstoss dienen.

Gruß

Volker

**Comment by jomjol** [comment]
Hallo zusammen,

eventuell handelt es sich um mehrere Fehler. Ich beschreibe mal das Problem, was ich mit v10.1.1 beseitigt habe:

Wie @muevol schreibt ist es richtig, dass die Umbenennung von "Topic" zu "MainTopic" schon in v8 stattgefunden hat. Ich habe die Doppeldeutigkeit auch in der `firmware.bin` berücksichtigt (reagiert kompatibel auf beide). Damit war das bis dato downward kompabitel.

Folgendes ist nun passiert: die Erstellung der `config.ini` findet in einer Javascript Bibliothek auf dem Browser statt. Dabei werden seit einiger Zeit nicht nur einzelne Werte geändert, sondern die komplette Datei immer neu erzeugt. Also sie wird beim Start der Bearbeitung gelesen und dann komplett neu geschrieben. Solange ihr die Konfiguration nicht bearbeitet passiert nichts. Wenn ihr aber in der v10 die graphische Konfiguration öffnet (z.B. um MaxRate einzustellen) und sie enthält noch das "alte Format" mit "Topic", dann wurde das nicht korrekt dem Wert von "MainTopic" zugeordnet. Wenn dann die `config.ini` gespeichert wird, findet er keinen Wert für "MainTopic" und deaktiviert ihn dann und schreibt `;MainTopic = undefined`.
Wenn jetzt die Firmware startet, dann wird aufgrund der Auskommentierung (`;`) der MainTopic nicht zugewiesen. Wenn dann der MQTT-Broker startet, findet er den Wert nicht und startet deswegen nicht.

In der Version 10.1.1 wird Topic --> MainTopic korrekt umbenannt. Wenn dort natürlich schon `;MainTopic = undefined` steht, ist es 1. deaktiviert und 2. die Information verloren. Dann aktivieren und den Wert nochmal reinschreiben.

Falls der MQTT-Broker trotzdem nicht funktioniert, dann gibt es vielleicht noch einen zweiten Fehler. Da bin ich auf eure Detailinfos angwiesen.

Ansonsten hoffe ich, das hilft ein bisschen, das Problem zu verstehen und zu beseitigen.

Beste Grüße,
  jomjol

**Comment by jomjol** [comment]
@zuzu59 : with this config it should work. Can you send me the serial logfile with the startup until the first measurement was done. I hope to find there the reason.

**Comment by zuzu59** [comment]
@jomjol 
Hello Jomjol,

Unfortunately, I cannot give you the log file via the serial port, because I am not at home at the moment. I can only give you the one I got on January 13 from the web interface (in extended logs mode).

[log_2022-01-13.txt](https://github.com/jomjol/AI-on-the-edge-device/files/7874661/log_2022-01-13.txt)

The passage where I did tests between 10.0.1 and 10.1.1 is since 11:19 !

You will also see in passing that the CPU temperature is not at all the same between the old and the new version.

That's why I'm really happy to be able to upgrade to the new version ;-)

Thanks again for all the work

**Comment by zuzu59** [comment]
And... I can't test the new version 10.2.0 not being at home :-(

I will do it on Monday!

**Comment by jomjol** [comment]
@zuzu59 : okay - don't forget to update the config.ini correspondingly:

![grafik](https://user-images.githubusercontent.com/30766535/149617073-b70741e4-e684-4f43-a8eb-9c059488ac2d.png)

**Comment by Der-Hoschi** [comment]
> Hallo zusammen,
> 
> eventuell handelt es sich um mehrere Fehler. Ich beschreibe mal das Problem, was ich mit v10.1.1 beseitigt habe:
> 
> Wie @muevol schreibt ist es richtig, dass die Umbenennung von "Topic" zu "MainTopic" schon in v8 stattgefunden hat. Ich habe die Doppeldeutigkeit auch in der `firmware.bin` berücksichtigt (reagiert kompatibel auf beide). Damit war das bis dato downward kompabitel.
> 
> Folgendes ist nun passiert: die Erstellung der `config.ini` findet in einer Javascript Bibliothek auf dem Browser statt. Dabei werden seit einiger Zeit nicht nur einzelne Werte geändert, sondern die komplette Datei immer neu erzeugt. Also sie wird beim Start der Bearbeitung gelesen und dann komplett neu geschrieben. Solange ihr die Konfiguration nicht bearbeitet passiert nichts. Wenn ihr aber in der v10 die graphische Konfiguration öffnet (z.B. um MaxRate einzustellen) und sie enthält noch das "alte Format" mit "Topic", dann wurde das nicht korrekt dem Wert von "MainTopic" zugeordnet. Wenn dann die `config.ini` gespeichert wird, findet er keinen Wert für "MainTopic" und deaktiviert ihn dann und schreibt `;MainTopic = undefined`. Wenn jetzt die Firmware startet, dann wird aufgrund der Auskommentierung (`;`) der MainTopic nicht zugewiesen. Wenn dann der MQTT-Broker startet, findet er den Wert nicht und startet deswegen nicht.
> 
> In der Version 10.1.1 wird Topic --> MainTopic korrekt umbenannt. Wenn dort natürlich schon `;MainTopic = undefined` steht, ist es 1. deaktiviert und 2. die Information verloren. Dann aktivieren und den Wert nochmal reinschreiben.
> 
> Falls der MQTT-Broker trotzdem nicht funktioniert, dann gibt es vielleicht noch einen zweiten Fehler. Da bin ich auf eure Detailinfos angwiesen.
> 
> Ansonsten hoffe ich, das hilft ein bisschen, das Problem zu verstehen und zu beseitigen.
> 
> Beste Grüße, jomjol

Ich habe gerade auf die 10.2.0 geupdatet und die MQTT-Einstellungen zurückgesetzt, leider selbes Verhalten. Die oberen Topics im ioBroker werden angelegt, die Werte an sich fehlen weiterhin.

Hier meine MQTT-Config:

[MQTT]
Uri = mqtt://192.168.0.46:1884
MainTopic = gaszaehler
ClientID = gas
;user = 
;password = 

Vielleicht kann mal jemand seine Config posten.

Gruß
DerHoschi

**Comment by Der-Hoschi** [comment]
So,
ich habe jetzt diverse Firmwareversionen getestet, 7.0.1, 7.1.2, 9.2, 10.0.1 und 10.2.0.
Überall mit demselben Ergebnis, per MQTT in ioBroker werden nur das Topic alive angelegt und mit TRUE gefüllt.
Ich habe jedesmal die SD-Card gelöscht und neu beschrieben und die Firmware per Flashtool geflasht. Irgendetwas scheint ioBroker anders zu machen als andere MQTT-Server. :-(

Beim Flashen bin ich noch auf folgenden Fehler gestoßen: Ich hatte mir mit einem Downgrade auf 7.1.2 einen Leser zerschossen , abgebaut und neu geflasht. Danach bootete er nicht mehr. Mit der Version 9.2.0 ging noch die weiße LED an, ansonsten tat sich nichts mehr. Die anderen FW-Versionen machten gar nichts. Nach ca. 2 Stunden rumprobieren dachte ich mir: es wird ja wohl kaum an der fehlenden externen WLAN-Antenne liegen. Aus lauter Verzweifelung habe ich dann mal eine angeschloßen und das Dr...ding bootet wieder. :-)Also an alle die die interne Antenne abgeklemmt und eine externe angeschlossen haben, ohne die externe bootet die Firmware nicht mehr.

Ein weiteres Phänomen ist mir dann auch noch aufgefallen, nachdem mein ESP nicht mehr wollte habe ich einen anderen geflasht, kein kompletter Boot. Er kommt ins WLAN aber startet die Firmware nicht. Im Log steht dann dass er das PSRAM nicht initialisieren kann, es wären keine 4MB verbaut, vermutlich nur 2. Laut Aliex... sollen die beiden Module allerdings 8MB haben. Meine 2 anderen haben laut Verkäufer 4MB und funktionieren beide.

Auch muss ich ein riesiges Lob an jomjol und die Community loswerden, selten ein so geiles Projekt gesehen. :-)
Ich freue mich schon auf noch weitere Features.

viele Grüße
DerHoschi

**Comment by zuzu59** [comment]
Hello @jomjol ,

Sorry for the late reply, but I was only able to test version 10.2.0 on Tuesday!
So, that's all good, this version works with my mqtt.
This version is much more stable than last year's version. I easily last a day without it restarting.
Thanks again for everything.

PS1: on the other hand the old neural network works better with my gas meter
PS2: I NEVER had the empty MainTopic problem because I always modified the config.ini file in expert/text mode !
