### ISSUE TITLE
previous read value not updated error Rate too high 

### ISSUE THREAD

**Issue by benziman88** [jomjol/AI-on-the-edge-device#546]
Hi, I have the issue that my esp32 cam has correct raw data for my gasmeter but the previous value is still not beeing updated so I get the error: Rate too high - Read: 4951947 - Pre: 4951.

Am I doing sth wrong, I have another esp32 for watermeter which works just fine!
Do I need to start the config from scratch to fix the pre value?

**Comment by benziman88** [comment]
![esp32_gas](https://user-images.githubusercontent.com/52277532/148747967-04ec7078-12e9-41fc-bd9a-cf7d933483a4.png)

**Comment by DcFamas** [comment]
You should configure the Previous Value 4951.914 and set this setting in the config:

![grafik](https://user-images.githubusercontent.com/35306967/148748770-c807970e-671c-40ee-afc5-f98640719be0.png)

**Comment by benziman88** [comment]
that didn't work as expected. 
![esp32_gas_2](https://user-images.githubusercontent.com/52277532/148751021-948754a0-22a7-4be6-8080-d584cf35fd8b.png)

**Comment by DcFamas** [comment]
Do you configured -3 or 3?
I think you need to configure "minus"3.

Best regards

**Comment by benziman88** [comment]
thanks that fixed it for me! Didn't have to do it on my watermeter due to analog roi`s therefore didn't know.
thanks a bunch!

**Comment by benziman88** [comment]
One issue remains, I still get the error "Rate too high - Read: 4953.782 - Pre: 4952.381" but don't udnerstand what the issue is.

**Comment by benziman88** [comment]
Changed MaxRateValue to 1,5 (no error after restart), will close if no error within next hour.

**Comment by jomjol** [comment]
You need to set the PreVlaue manually if it is wrong. You do this with the following setting:
![grafik](https://user-images.githubusercontent.com/30766535/148824926-12531d38-39a4-4445-b9d8-add22f76bfa5.png)
After that you can put the right value into the follwoing field:
![grafik](https://user-images.githubusercontent.com/30766535/148825055-b463c44c-af86-40b0-9fdd-288723f5bf1e.png)
