### ISSUE TITLE
V10.1 MQTT und Value<>RAW fehlerhaft

### ISSUE THREAD

**Issue by Hasont** [jomjol/AI-on-the-edge-device#547]
Hallo, wie hier bereits gepostet ist auch bei mir in 10.1 MQTT bei Gas und Wasser fehlerhaft. 
Des weiteren hatte ich wie auch schon in der 10.01 und 10.02 wieder einen Sprung von einem oder mehreren m3 (siehe Bild). 
Max RateValue steht derzeit bei ,05 statt 0,3

![grafik](https://user-images.githubusercontent.com/22281094/148762088-12cc2b3b-69c8-46ff-ba98-67d7bde04e34.png)

Im Log ist um 2:24:28 zu sehen, dass plötzlich MQTT wieder ging,
Ab 3:00 steht dann gar nichts mehr im Log und die letzte Datenübertragung war um 3:08 lt IoBroker.  

Auch eine Korrektur des Value heute um 12:35 ging erst nach einem Reset,
Es ist jetzt 13:10 und im Log wird auch weiter kein Eintrag mehr erzeugt.
[log_2022-01-10.txt](https://github.com/jomjol/AI-on-the-edge-device/files/7838685/log_2022-01-10.txt)

Ich gehe erstmal wieder zurück auf 8.5 bist du was zum Thema Value<>RAW gefunden hast.

Gruß Horst

**Comment by AlexanderSch90** [comment]
Gleiches Problem auch hier bei V10...

**Comment by jomjol** [comment]
Mit Version 10.x wurde die Backbone verändert (esp-idf auf v4.3). Damit ggf. auch die verwendeten MQTT-Bibliotheken, da ich hier natürlich die von esp-idf verwende. 
Vielleicht keine schlechte Idee, erstmal beim der funktonierenden Version zu bleiben - never change a running system.

Vielleicht einfach noch die ein oder andere Version abwarten, bis die "Kinderkrankheiten" wieder raus sind. Ich schließe den Post erstmal, sonst verliere ich den Überblick.

Gruß,
  jomjol
