### ISSUE TITLE
stupid mounting point on analog 2

### ISSUE THREAD

**Issue by wawibu** [jomjol/AI-on-the-edge-device#548]
Hi all,
first I would like to thanks for that great project !

I implemented it but struggle with the 2nd analog ROIs. There is a mounting point which issues a clear view on the needle (see picture).

![optical issue on analog](https://user-images.githubusercontent.com/32385342/148782877-3e9e5288-bac2-497a-a4b1-5172db2e7cd1.PNG)

That means that I current get only the value for 100l and not further down. 

Does anyone have an idea what could be done here to get a more detailed view?

Could analog 2 just be a calculated value based on analog 3 ?

**Comment by simplest-circuits** [comment]
No idea in general on your problem, but this could be a feature request to prevent such cases with a random/fixed or placeholder number.
I think it´s not really important to be accurate in such a case and prevent a NAN with an individual placeholder number @jomjol?

**Comment by jomjol** [comment]
I don't see a way, because the image of the pointer is totally distorted.

**Comment by Kalli01** [comment]
In the settings there is the item "ExtendedResolution".
This would allow you to calculate the 10L from the 100L value.

**Comment by wawibu** [comment]
Thanks @Kalli01 , that is a great hint. Have that now activated.
@jomjol  would it maybe possible in a further release to enable that for a selectable analog? If that would be possible I could activate that for analog 1 so that analog 2 is based on extended resolution of analog 1 and I could add a further reverence for analog 3. 
Just a thought.

**Comment by jomjol** [comment]
@wawibu Technically yes. But this a really special case with a rare usage.
Implementation, algo update, html update, ... it will take rought 1-2 day of work. Additionally the features will get really complicated and most people will not understand the background of this.

Currently I don't plan to follow this.
