### ISSUE TITLE
Ethernet Shield module

### ISSUE THREAD

**Issue by beetronic** [jomjol/AI-on-the-edge-device#549]
First of all what a great project and THANK YOU! I have implemented the project successfully and designed and printed my own version of the PLA tube. Nevertheless my watermeter has issues with the wifi connection!
As my watermeter is in the basement, in a small, well shielded concrete room I would like to connect via an Arduino Ethernet shield because a LAN cable is available down there.
Any suggestions on what specific Ethernet shield I should pick for the ESP32-Cam?
What needs to be changed in the code or wifi. ini?
Thank you!

**Comment by jomjol** [comment]
You don't have a chance with an Ethernet shield. There are only GPIO12/13 available, which will not be enough to my knowledge.
All other ports are used by: PSRAM, SD-Card, Camera, Flash.

**Comment by beetronic** [comment]
Danke für die rasche Antwort. Das Ethernet Shield nutzt Port 10,11,12 und 13. D.h. es wird so nicht klappen.... Muss mir einmal anschauen was über 10,11 kommuniziert. Vielen Dank Herr Müller

**Comment by SkylightXD** [comment]
Hast du eine Lösung für dein  Ethernet gefunden? Ich habe das gleiche Problem...

**Comment by beetronic** [comment]
Nein, funktioniert leider nicht.
Siehe auch https://github.com/jomjol/AI-on-the-edge-device/discussions/607
Das wäre eine Option, aber da ist einiges an coding notwenig.
Hab zusätzlich eine ext. Antenna angeschlossen und mit Version 10.5.2 läuft es so halbwegs.
