### ISSUE TITLE
DigitalReadout neue Trainingsbilder Stromzähler

### ISSUE THREAD

**Issue by simonscheib** [jomjol/AI-on-the-edge-device#55]
Hi jomjol,

hab für meinen Stromzähler nochmal einen Satz neuer Bilder angefertigt (4 pro digit). Diesmal direkt von der ESP Cam (die vom letzten Mal waren separat aufgenommen). Könntest du die ins nächste Training mit einfließen lassen? Hab auch noch einen Satz an validen NaN Bildern hinzugefügt.

[strom.zip](https://github.com/jomjol/AI-on-the-edge-device/files/5572792/strom.zip)

Gruß
Simon

**Comment by jomjol** [comment]
Hi Simon,

da hast du aber wirklich teilweise sehr wenig Kontrast - bin mal gespannt, ob dass noch gut geht.

Gruß,
  jomjol

**Comment by simonscheib** [comment]
Ist mal so mal so. Evtl muss ich noch etwas mehr Licht in meine Box bauen. Beleuchtung ist immer an und den 5 Sekunden timeout vor dem Bild zur belichtungseinstellung hab ich auch noch drin. 
Improvement ongoing :)

**Comment by jomjol** [comment]
Hallo Simon,
hier ein Update mit deinen Ziffern: 
[dig0720s1.zip](https://github.com/jomjol/AI-on-the-edge-device/files/5576094/dig0720s1.zip)

Folgende Bilder habe ich nicht mit ins Training aufgenommen, da sie die Kriterien für eindeutige Ziffern nicht erfüllen (Ziffer vollständig und mit freiem Rand):
[strom_nicht_geteached.zip](https://github.com/jomjol/AI-on-the-edge-device/files/5576101/strom_nicht_geteached.zip)

Gruß,
  jomjol

**Comment by simonscheib** [comment]
Super, danke dir. Hab mittlerweile auch noch für etwas mehr Licht gesorgt und noch zwei LED Stripes eingelötet. Mal sehen wie's damit klappt. Gaszähler funktioniert schon seit dem letzten teachen perfekt. 

Und nochmal generell vielen Dank für die Arbeit. Klasse Projekt.

Gruß
Simon
