### ISSUE TITLE
DC-26 40-V3

### ISSUE THREAD

**Issue by MubiTec** [jomjol/AI-on-the-edge-device#551]
Hi,

Du schreibst zwar hier

https://github.com/jomjol/AI-on-the-edge-device/wiki/Hardware-Compatibility

dass die DC-2640-V3 nicht kompatibel ist.

Hab die jetzt trotzdem mal angeschlossen und bekomme ein Bild. Das ist jedoch noch unscharf. Ich würde jetzt den Siegellack abmachen, um das scharf zu stellen.
Will aber nicht umsonst die Kamera kaputt machen, also warum ist die Kamera nicht kompatibel und sollte ich mir das lieber sparen?

Danke dir!

**Comment by jomjol** [comment]
Danke für die RM, ich habe dein Ergebnis mit aufgenommen - und einen Hinweis, dass es sich nur um einzelne Erfahrungen handelt.
