### ISSUE TITLE
Ziffer "1" wird nur als "0" erkannt

### ISSUE THREAD

**Issue by Schmakus** [jomjol/AI-on-the-edge-device#552]
Ich kann machen was ich will, aber die "1" an dig3 wird immer nur al "0" erkannt. Wie kann ich das verbessern/ändern?
v10.1.0

![Xnip2022-01-11_14-56-28](https://user-images.githubusercontent.com/8231359/148955844-c69a56c4-b460-4f37-b57d-6655a8e9bead.jpg)

**Comment by Schmakus** [comment]
Hat sich erledigt. ;-)

**Comment by bommel947** [comment]
Was war die Lösung?
Bei mir wird immer die 1er Stelle nicht erkannt
Vorher die 3 und nun die 4 wird immer als 0 oder NaN ausgewertet

:-(

![image](https://user-images.githubusercontent.com/45903971/148976453-2fbae829-4f10-460b-aff2-3e3d259aa0ac.png)
