### ISSUE TITLE
PreValue too old

### ISSUE THREAD

**Issue by aberlechristian** [jomjol/AI-on-the-edge-device#554]
Ich nutze Version 10.1.0 und habe leider das Problem, dass immer wieder PreValue too old angezeigt wird.
Selbst nachdem ich auf Configuration --> set preValue gehe und dort den Wert setze, bleibt trotzdem in der Übersicht die Anzeige "PreValue too old". Auch ein Reboot löst das Problem nicht.

In der Config habe ich schon PreValueAgeStartup auf 3000 gesetzt und durch einen Reboot aktiviert, trotzdem tritt das Problem wieder auf, auch vor dem Ablauf der 3000 Minuten.

Grundsätzlich kann es ja vorkommen, dass die KI beim digitalen Zähler etwas nicht erkennt, wenn die Zahlen gerade auch wirklich nicht gut zu erkennen sind. Dann wird das ja als N angezeigt. Wenn nun kein Wasserverbrauch da ist, dann kann das so ja auch mal etwas länger stehen bleiben. Dadurch, dass aber irgendwann PreValue too old erscheint, übermittelt er dann auch nicht mehr den richtigen Zählerstand per MQTT an meinen IOBroker.

Hier noch ein Screenshot:
![image](https://user-images.githubusercontent.com/59068920/149001611-e67d3fa0-bca0-4158-8a50-d04a9972679e.png)

Kann ich noch irgendwelche Infos liefern, um bei der Lösung des Problems helfen zu können?

**Comment by jomjol** [comment]
Kannst du mal das Logging aktivieren und 
1. PreValue nochmals updaten
2. Reboot
3. Logfile nach einigen Runs (z.B. 10) hier als zip posten.

Danke!

**Comment by jomjol** [comment]
Schließe das mal, bis weitere Daten vorliegen.
