### ISSUE TITLE
NaN in between numbers

### ISSUE THREAD

**Issue by JHA-2021** [jomjol/AI-on-the-edge-device#555]
![grafik](https://user-images.githubusercontent.com/80697380/149118016-0e32b144-e4a3-437a-b114-978c90b01778.png)

![grafik](https://user-images.githubusercontent.com/80697380/149118157-39e7abe6-85c2-4fa6-b4b2-e291a50e657f.png)

As you can see there is a NaN where no digital number identification field is defined.
The identification of the analog number is wrong as well but that is actually of minor importance to me.

I set the decimal shift to -2

Version master - v9.2.0, 11.1.0

**Comment by MMeinhardt1** [comment]
The NaN is the not recognized "digital" 1. Read the wiki please.

**Comment by JHA-2021** [comment]
I know the wiki. I just looked wrong when I posted the picture, sorry. 

This behaviour is correct except that it is not recognizing the number fully in sight.
