### ISSUE TITLE
MQTT - After update of config.ini not working

### ISSUE THREAD

**Issue by friedpa** [jomjol/AI-on-the-edge-device#558]
Hi @jomjol,
ich habe folgende Beobachtung gemacht.
Steps:
1. System von V9.0 auf V10 upgegradet (letzte Version 10.0.2)
2. LOG File zeigte ständige Reboots
3. System downgrade von V10.0.2 auf V9.0 -> MQTT funktioniert
4. Änderung in der config.ini gemacht (MaxRateValue verändert)
5. Reboot um neue config.ini zu übernehmen
6. Nach Reboot keine MQTT Übertragung mehr 

Ich denke also, dass es einen Fehler(?) in der config.ini geben muss, da sich wie von Zauberhand der MQTT Eintrag verändert hat:
Vor der Änderung (MaxRateValue):
Uri = mqtt://192.168.10.16:1883
Topic = gaszaehler/zaehlerstand
TopicError = gaszaehler/error
TopicRate = gaszaehler/rate
TopicTimeStamp = gaszaehler/timestamp
ClientID = gaszaehler
user = xxxxx
password = xxxxx

Nachher:
Uri = mqtt://192.168.10.16:1883
;MainTopic = undefined
ClientID = gaszaehler
user = xxxx
password = xxxxx

7. Alte Werte in die config.ini wieder übernommen
8. Reboot
9. MQTT funktioniert wieder

Ich habe aber garantiert NICHTS beim MQTT geändert, sondern nur die MaxRateValue verstellt ....
Liebe Grüße
Paul

**Comment by jomjol** [comment]
Hi Paul,
danke dir! **Top-Hinweis** und jetzt weiß ich zumindest wo ich suchen muss. Mein Problem ist nur, dass ich diese Woche beruflich extrem unterwegs bin und daher vermutlich erst am WE dazu komme, mich damit intesiver zu beschäftigen.

Ich vermute, es ist ein Fehler bei der Umwandlung von Eingabezahlten (String to Float, Komma vs. Punkt als Dezimalzeichen, Fehler nicht abgefangen) - vermutlich im HTML/java-Code.

Gruß,
  Josef

P.S.: ich letztes WE bei der Kamera weitergekommen. Hier ein Auszug aus meinem Log:
![grafik](https://user-images.githubusercontent.com/30766535/149134088-826b230a-7082-4eaf-b612-f1ac22ce0227.png)

**Comment by friedpa** [comment]
Hallo Josef
Cool, 1233 Rounds! Mein Rekord an Rounds ist immer noch 926 :o)
Liebe Grüße
Paul

**Comment by jomjol** [comment]
Hallo Paul,
konnte die Finger doch nicht davon lassen und habe gerade ein Update gepostet. Das Problem lag im Umbenennen des MQTT-Paramters "Topic" in "MainTopic", um den Multi-Number-Zähler gerecht zu werden. Beim Öffnen und Schreiben eines beliebigen Wertes in der Config.ini wollte ich das eigentlich "silent" machen, hat es aber irgendwie nicht in den Code geschaft und daher jetzt die MQTT-Einstellungen verhagelt.

Du musst die html.zip updaten und dann deine v9 config öffnen und wieder schließen und dann klappt es. Oder einfach nur den Parameter "MainTopic" aktivieren und nochmal manuel setzen.

Gruß,
  jomjol

P.S.:
![grafik](https://user-images.githubusercontent.com/30766535/149213923-76c45602-5317-4813-8c07-4fba2b2fb726.png)
Aber das Update habe ich noch nicht hochgeladen, da muss ich noch ein bisschen was testen :-).
