### ISSUE TITLE
Recognition of numbers in 10.1.0 much worse than in 9.2.0

### ISSUE THREAD

**Issue by JHA-2021** [jomjol/AI-on-the-edge-device#559]
I updated via OTA to 10.1.0 and now it hardly recognizes numbers correctly.

![grafik](https://user-images.githubusercontent.com/80697380/149138597-c029a64b-eaa1-4795-bf43-d40786717d60.png)

**Comment by JHA-2021** [comment]
Actually I take that back. I downgraded and it is as wrong as in 10.1.0

![grafik](https://user-images.githubusercontent.com/80697380/149196317-655fafce-14c4-4d26-8488-608fa92dabe3.png)

**Comment by jomjol** [comment]
The quality of the recognition should not change with a pure firmware upgrade. The recognistion itself is done with the parameter of the tflite file in the /config directory. You need to update them manually.

**Comment by bommel947** [comment]
I can recommend using "dig-s2-q-20220104.tflite".
The recognition is way better
