### ISSUE TITLE
Last Will und RSSI

### ISSUE THREAD

**Issue by rejoe2** [jomjol/AI-on-the-edge-device#56]
Hi,

vorab mal: sehr cooles Projekt, Danke für die Lösung eines meiner hartnächigsten Problemchen im IoT!

Einen kleinen feature-request hätte ich (bzw. zwei, je nach Zählweise):
Es wäre zum einen nett, wenn der Zähler eine LWT-Message absetzen könnte (separater Topic), um den Verbindungsstatus mit dem MQTT-Server zu signalisieren.
Chris Mullins hat z.B. sowas (und etwas mehr) in den MiLight-Hub hier eingebaut:
https://github.com/sidoh/esp8266_milight_hub/pull/435

Weiter wären ein paar Basisinfos hilfreich, mich würde z.B. hin und wieder die Signalqualität interessieren, das Teil hängt vermutlich nicht nur bei mir an einer nicht ganz optimalen Stelle, was WLAN-verfügbarkeit angeht.

Grüße und vorab schon mal Danke für's Ansehen!

**Comment by jomjol** [comment]
Last Will Testament ist in der neuesten Rolling implementiert. Es wird der String "connection lost" in den Error Topic (`TopicError`) spezifiziert.

RSSI werde ich erstmal nicht implementieren - so langsam wird der Code zu groß und ich habe noch einige andere Ideen, die ich zuerst verfolgen werde.

Ich schließe den Topic damit.
Gruß,
  jomjol

**Comment by rejoe2** [comment]
Danke. Muss mir das mal ansehen, bin aber nicht sicher, ob das dann nicht überschrieben wird, wenn man "normale" Messages über denselben Topic sendet.

RSSI ist bei mir zwischenzeitlich dahingehend gelöst, dass ich eine externe Antenne drangebastelt habe und das auch über den Router abfragen kann. Die Verbindung war hakelig gewesen... Mit der "vga"-Version fühlt sich jetzt alles deutlich "fluffiger" an *grins*. Jetzt muss ich dem  nur noch beibiegen, dass die als "7" erkannte "1" eine "1" ist (presetValue hilft leider nicht dauerhaft ab).
