### ISSUE TITLE
Improvement to logic to "guess" numbers that can not be read 

### ISSUE THREAD

**Issue by MArimont3** [jomjol/AI-on-the-edge-device#560]
Improvement to logic to "guess" numbers that can not be read 

First some context: in my case, the meter has "difficulties" to roll the digits when the digit to the right passes the "0". The digit (N) is only rolled over for 80% or 90%, making it unreadable for the tool. Often, the digit to the right (N+1) has to roll to 2, 3, sometimes even 5, 6 or  7 in order to read the digit (N) correctly. So in many many of my readings, one or more digits are read as "N" (not a number).

In the current implementation, I have the impression that when a digit is read as "N", it is assumed it has still the same value as last time (it was read correctly). I think in some cases this is not the right strategy, and a small change could resolve > 90% of my bad readings!

Lets show it with a simple(simplified) case with only 2 digits:

- assume the digits are read correctly as 17
- next the value passes to 20, but as the "2" is not (yet) rolled completely, the whole is read as "N0"
- then the logic replaces the "N" by "1" (last good value), and raises an error as "10" is lower than the last value ("17"). It is clear that does not make much sense. 

I think a better rule instead of just replacing a "N" by the last good value would be:  if a digit is read as "N", and the digit to the right 
 decreased, it should be replaced with "the last good value PLUS ONE", and by "the last good value" otherwise.

What do you think ?
It would even be better to make a setting of this behavior ?

**Comment by derandi80** [comment]
Hi, in my experience, the last value will be used if there is a "N" within the current readout. So for your example, it should be 17.  
If this is not the case, then perhaps a solution would be to increase the last correct value with the MaxRateValue. 
PreValue + MaxRateValue = CurrentValue

For your Example, the solution could be: 
PreValue: 17
Raw Value: N0
Value: 17 + 2 (MaxRateValue) = 19

So get average value instead of a wrong value.

**Comment by MArimont3** [comment]
Hi derandi80,
No, I am pretty sure: if the read out contains one (or more!) "N", the "N" is re^placed by the last good value for that particular digit. And if the whole gives a correct value, it is accepted (and send over MQTT in my case).

Do not understand neither what you mean with "increase the last correct value with the MaxRateValue". How and when would you do this ? Manually ???
