### ISSUE TITLE
Beim umspringen der Zahl werden falsche Werte berechnet/gepeichert.

### ISSUE THREAD

**Issue by akoerth** [jomjol/AI-on-the-edge-device#561]
Hallo zusammen, 
bei mir werden beim umspringen auf die nächste Zahl falsche Werte angezeigt. 
![grafik](https://user-images.githubusercontent.com/97634891/149219997-b126c2bb-e1e7-4f6b-b8bb-c6ebde2110e7.png)
![grafik](https://user-images.githubusercontent.com/97634891/149220284-974b4184-9312-4216-b02d-bd382a7f2fae.png)
Danach werden die Werte übernommen und stehen so auch im Iobroker (MQTT)
![grafik](https://user-images.githubusercontent.com/97634891/149220424-4138533d-e1ca-4854-b55e-013db2034a92.png)
Hatte bisher keinen Tag wo die WErte korrekt dargestellt wurden. Ich nutze die Version 10.0.2

**Comment by jomjol** [comment]
Kannst du das entsprechenede Logfile bitte posten? Ich brauche noch mehr Infos.

**Comment by akoerth** [comment]
Hallo Jomjol, 
hier die Logs vom 11.01 und 12.01. 
Ich kann dir auch weitere zur Verfügung stellen falls benötigt.
[log_2022-01-11.txt](https://github.com/jomjol/AI-on-the-edge-device/files/7875163/log_2022-01-11.txt)
[log_2022-01-12.txt](https://github.com/jomjol/AI-on-the-edge-device/files/7875164/log_2022-01-12.txt)

**Comment by jomjol** [comment]
Ich vermute, du hast den Parameter `CheckDigitIncreaseConsistency` aktiviert?
Das ist zwar für mixed (analoge + digitaler Zeiger) gedacht, funktioniert aber nur zuverlässig, wenn das Komma auch genau zwischen den digitalen und analogen Zeigern ist. In deinem Fall hast du es aber auch Literstelle gesetzt. Dann führt das genau zu dieser Art Problemen.

Ich würde empfehlen, das Komma auf die m³ zu setzen und die Umrechnung in Liter dann erst in deiner Weiterverarbeitung zu machen. Nur dann funktionieren die Korrekturalgorithmen zuverlässig.

**Comment by akoerth** [comment]
Hallo Jomjol,  

vielen Dank für deinen Support. Ich habe das jetzt umgestellt und werde es beobachten. 

Gruß, Andreas
