### ISSUE TITLE
How to select the right version of the model file dig-s2-q-20220104.tflite

### ISSUE THREAD

**Issue by beejayf** [jomjol/AI-on-the-edge-device#562]
Hi,

I was searching for a rule on how to select the right model file - I found dig-s1 to dig-s3 with / wthout q.

Thanks for the hint!

**Comment by jomjol** [comment]
This are model files with different internal structure. The recommended one you can find in the master branch within the config.ini (https://github.com/jomjol/AI-on-the-edge-device/blob/master/sd-card/config/config.ini) 

If your system is running smoothly there is no reason to change the model file.

I always test serveral of them (s1, ... s3) and choose the best one.
