### ISSUE TITLE
Wlan Signalstärke anziegen

### ISSUE THREAD

**Issue by Kalli01** [jomjol/AI-on-the-edge-device#563]
Hallo zusammen,

wäre es möglich die WLAN Signalstärke noch mit auf der Info Seite darzustellen?
Hintergrund ist folgender.

Ein Modul habe ich an einen Stromzähler montiert. Dieser sitzt in einem Zählerschrank aus Metal. 
Mit einer kleinen externen Antenne funktionierte das auch gut und die Weboberfläche konnte über Monate normal aufgerufen werden.
Von einem auf den anderen Tag hat das Modul jetzt einen so schlechten Empfang, das ich die Oberfläche nicht mehr aufrufen kann. Auch über MQTT werden dann keine Daten mehr übertragen. Ein Neustart hilft für kurze Zeit.
Komisch finde ich, dass ich die Weboberfläche über ein Handy ganz normal aufrufen kann. Über einen PC der über LAN angeschlossen ist, geht es dann nicht. Auf beiden nutze ich Google Chrome.
Naja jedenfalls habe ich schon verschiedene Antennen versucht aber komme nicht weiter. Auch das verlegen der Antennen über ein Kabel außerhalb des Zählerschranks hat nicht geholfen.
Meine Vermutung ist jetzt eigentlich, dass das Modul einen Fehler hat.

**Comment by watcherkb** [comment]
welche Version hast du denn?
Versuchs mal mit Firefox

**Comment by Kalli01** [comment]
Firefox hatte ich vorhin versucht, aber damit funktioniert es dann auch nicht.  
Nach einem Neustart über das Handy kann ich die Seite über den PC mit Chrome und Firefox aufrufen.
Aktuell läuft bei mir die Version master - v10.1.0 - 2022-01-09. 
Der Fehler trat aber ohne einen Versionswechsel von alleine auf.

Auf dem PC
Google Chrome Version 96.0.4664.110 (Offizieller Build) (64-Bit)
Firefox 95.0.1 (64-Bit)

Auf dem Handy
Chrome 81.0.40.44.138

Ich bin mir nicht sicher ob es ein Software Problem ist.  Weitere Browser kann ich erst morgen testen, wenn es wieder hängt.

**Comment by jomjol** [comment]
Ich habe es in die Feature Request Liste aufgenommen. Aktuell arbeite ich aber nicht daran.
