### ISSUE TITLE
Raw Value versus Value

### ISSUE THREAD

**Issue by Gukerl** [jomjol/AI-on-the-edge-device#564]
Grüß Euch,
bei mir wird der Value Wert quasi gleichbleibend, immer der selbe Wert, angezeigt, die Raw Value stimmt aber immer. ENtweder ist das ein Fehler, oder ich hab ein Verständnisproblem.  Auch haperts bei mir mit der Previous Value, ich kann dazu leider keine Beschreibung finden. Vielleicht kann mir jemand etwas auf die Sprünge helfen.
Danke Euch :
![PreValuevsValue](https://user-images.githubusercontent.com/72930135/149502736-4f40cf9c-fe1e-4bb9-a260-503bea0ebe23.JPG)
)

**Comment by Feinfinger380** [comment]
Wahrscheinlich hat er den Sprung um 2 Stellen nicht erkennen können und liest den Stand jetzt erst wieder korrekt aus.
Da dein MaxRateValue aller Vorraussicht nach auf 0,1 steht, wirft er jetzt den Zähler mit Rate too high aus.
Entweder den PreValue setzen, oder MaxRateValue anpassen.

**Comment by jomjol** [comment]
Wahrscheinlich wird es genaus sein.
