### ISSUE TITLE
Update 10.1.1 not correct shown in Webserver

### ISSUE THREAD

**Issue by Duese123** [jomjol/AI-on-the-edge-device#567]
Update not correct shown in Webpage newest update installed (10.1.1) and it was shown as master - v10.1.0 - 2022-01-09
in the picture
![image](https://user-images.githubusercontent.com/95966691/149578157-7f96cf39-3aa8-4758-a5fc-5abf0f8a9006.png)
also newer files in config folder were not there and have to copy/upload manually (ana-s3-q-20220105.tflite for example)

**Comment by jomjol** [comment]
Corrected in the newest update: 10.2.0:
![grafik](https://user-images.githubusercontent.com/30766535/149578647-230c91ed-ee30-4789-9e66-7109cc3abe11.png)

**Comment by Duese123** [comment]
4 minutes ago.. cheesh
