### ISSUE TITLE
mqtt still not working

### ISSUE THREAD

**Issue by dinkel1975** [jomjol/AI-on-the-edge-device#568]
hi,

mqtt not working for me in V10.1.1. 
V9.2.0 is OK. 

best regards

**Comment by jomjol** [comment]
Did you do the recommended steps:

![grafik](https://user-images.githubusercontent.com/30766535/149613398-966b961c-72c7-4bb3-bc1e-c086460b0462.png)

Please post your `config.ini` - so I will check for the problem.

**Comment by dinkel1975** [comment]
Thank you!
Works! I have overseen this!

**Comment by jomjol** [comment]
Great!

**Comment by DiKaY1969** [comment]
Hi there,

MQTT ran stable for me up to version 10.0.0.2. From 10.0.1.0 or 10.0.1.1 unfortunately no longer reliable! Sometimes data comes and then suddenly no more!

But the MainTopic parameter in the config.ini is correct!

A quick test with 9.2.0.0 and 10.0.2.0 showed me that MQTT works perfectly again immediately!

I think something is wrong from version > 10.0.2.0!

Can you please check that again?

Thank you for this super project.

**Comment by jomjol** [comment]
@DiKaY1969: Please update to v10.2.0

**Comment by DiKaY1969** [comment]
Hi there,
yes, V10.0.2. currently working stable!

**Comment by DiKaY1969** [comment]
Sorry V10.0.2 not V10.2!

**Comment by jomjol** [comment]
anyway I recommend the update to v10.2.0. This is even more stable (solution for the high reboot tendency)

**Comment by DiKaY1969** [comment]
Hi there,

yes, V10.2.0. is currently working stably again!

**Comment by dinkel1975** [comment]
yes. 10.2.0 works.

**Comment by Schmakus** [comment]
10.2.0 works, thx!!
