### ISSUE TITLE
MQTT funktioniert immer noch nicht

### ISSUE THREAD

**Issue by RoberWi** [jomjol/AI-on-the-edge-device#569]
Auch in Version 10.0.2 funktioniert bei mir MQTT immer noch nicht wieder.

Ich habe alle Schritte in Bezug auf die Config vorgenommen, die mir eingefallen sind: Alte Config, neue Config, MQTT in jeder einzelnen Optionen deaktivieren (reboot, aktivieren, reboot, also 8 mal), den Wert der Variablen umbenennen, den Titel einmal in "Topic" zurückbenannt (wird nach dem Speichern dann korrekt wieder in MainTopic umbenannt).

Egal, was ich machen, es werden keine Werte übertragen.

Noch eine Idee?

[config.ini.txt](https://github.com/jomjol/AI-on-the-edge-device/files/7874727/config.ini.txt)
[log.txt](https://github.com/jomjol/AI-on-the-edge-device/files/7874728/log.txt)

**Comment by dinkel1975** [comment]
Probier nochmal flashen. bei mir hats erst beim zweiten flashen funktioniert.

**Comment by RoberWi** [comment]
Habe ich auch schon durch. Einen von den vier nicht mehr funktionierenden habe sogar schon getauscht (ESP + SD-Card), weil ich an einen Hardwarefehler dachte.

**Comment by dinkel1975** [comment]
und die version 9.2.0? die hat bei mir immer funktioniert.

**Comment by RoberWi** [comment]
Die alten funktionieren, das ist nicht das Thema. In 10.x hat sich ja einiges andere verbessert, das würde ich schon nutzen wollen.

**Comment by dinkel1975** [comment]
wenn die alte läuft, kannst zumindest mal die hardware ausschließen.

**Comment by friedpa** [comment]
Hi Gents,
ich habe das gleiche "Problem". Version 9.0.0 läuft ohne Probleme, sobald ich eine "10er" Version, inkl. der 10.2.0 probiere kommt es zu Problemen mit reboots und/oder MQTT.

**Comment by RoberWi** [comment]
Während ich gerade im iobroker einen Poll für die API baue, um die Werte dann wenigsten zyklisch zu lesen und darüber zu verteilen, stelle ich fest, dass alle Geräte im MQTT "connected" sind.... Ohne dass ich irgendwas erkennbares gemacht habe.

**Comment by jomjol** [comment]
@RoberWi: Das einzige was mir auffiel ist das xx.yy in der URI:
```
[MQTT]
Uri = mqtt://192.168.xx.yy:1883
...
```
Wenn das so in der Config.ini steht, geht es nicht, da dort nur eine konkrete Adresse funktioniert. Der Rest sieht erstmal gut aus.

**Comment by Dreamoffice** [comment]
ich habe das selbe Problem mit MQTT.

**Comment by RoberWi** [comment]
> @RoberWi: Das einzige was mir auffiel ist das xx.yy in der URI:
> 
> ```
> [MQTT]
> Uri = mqtt://192.168.xx.yy:1883
> ...
> ```
> 
> Wenn das so in der Config.ini steht, geht es nicht, da dort nur eine konkrete Adresse funktioniert. Der Rest sieht erstmal gut aus.

Die IP-Adresse ist natürlich korrekt.

Im Augenblick funktioniert MQTT wieder. Aber gefühlt hat die WLAN-Stabilität und Erkennungsqualität mit der 10.x nachgelassen. So viele fehlerhafte Werte hatte ich vorher nicht und so oft in den Keller rennen, ume ESP neu zustarten, weil er nicht mehr erreichbar ist, hatte ich mit 9.x auch nicht.

**Comment by jomjol** [comment]
Erkennungsqualität sollte unabhängig von der Verison sein - zumindest aus Sicht der neuronalen Netze. Wenn es jetzt instabilier läuft, dann erstmal bei v9 bleiben. Bei mir ist aktuell genau das Gegenteil der Fall, aber ich sollte es erstmal 1-2 Wochen laufen lassen, um zu sehen, ob das auch nachhaltig ist.

**Comment by Dreamoffice** [comment]
ich bin jetzt auch wieder auf die v9 zurück. die läuft jetzt wieder bisher ohne Zicken

**Comment by dinkel1975** [comment]
bei mir läuft die 10.2.0 nach anfänglichen mqtt problemen auch sehr stabil

**Comment by RoberWi** [comment]
Einen Tag später kann ich sagen, das MQTT sich irgendwie eingependelt hat. Selten fehlt mal eine Übertragung. Das hatte ich vorher nicht, kann ich aber mit leben.

An der Erkennungsrate feile ich noch. Bei meinem Stromzähler funktioniet dig1300s1q.tflite am besten. Allerdings musste ich die Rahmen noch einen Pixel enger ziehen. Beim Wechsel gibt es manchmal Sprünge.

Mir ist noch nicht klar, warum es einen Sprung +6 gibt, wenn ich die Rate auf 0,1 bei Intervall von 30 Minuten eingestellt habe. Dürfte der höchste Sprung dann nicht nur +3 sein?

**Comment by juergen852** [comment]
Die Wert-Änderung könnte für den Zeit-Intervall zu groß sein. (463 auf 464).
2022-01-15T08:58:18: PostProcessing - Raw: 463.70 Value: 464.70 Error: no error

In der Config hast Du "zahlen.MaxRateValue = **0.1" was Faktor 10 kleiner ist, als 1.**
Dann sagt die Software: Änderung zu groß, ich schicke keine Werte, sondern warte auf die nächste Messung.
Ergo: Es kommt nichts per MQTT.

Ändere "zahlen.MaxRateValue = 0.1" mal auf 2 statt 0.1.
Dann müssten die Werte kommen.

**Comment by jomjol** [comment]
Ihr könnt die Diskussion gerne weiter führen, ich mache das jetzt trotzdem zu, da das Topic (MQTT) ja jetzt zu funktionieren scheint. Ansonsten verliere ich hier den Überblick.

**Comment by Dreamoffice** [comment]
Bei mir läuft die 10er Version nicht. Ich bleibe jetzt erstmal auf der 9.2.
