### ISSUE TITLE
Number recognation

### ISSUE THREAD

**Issue by patrick131184** [jomjol/AI-on-the-edge-device#570]
Hi there,
first of all thank you for this great project!

Having two ESPs running, one for a watermeter and one for a gasmeter.
The gasmeter seems to make some problems with the number recognation.
The numbers "3","9"and "8" are sometimes recognized as "0".

![image](https://user-images.githubusercontent.com/31507327/149619565-ea12b57c-989b-4b6c-8a01-50330d52bd28.png)
![image](https://user-images.githubusercontent.com/31507327/149619782-69735bdb-fcea-4fea-ae54-bea7ce19bee7.png)

Any advice?
Maybe i can help with my numbers for training?
Please let me know what i have to do then.

Thank you

[MakeImage]
;LogImageLocation = /log/source
WaitBeforeTakingPicture = 5
;LogfileRetentionInDays = 15
Brightness = 0
;Contrast = 0
;Saturation = 0
ImageQuality = 5
ImageSize = VGA
FixedExposure = false

[Alignment]
InitialRotate = 180
InitialMirror = false
SearchFieldX = 20
SearchFieldY = 20
AlignmentAlgo = default
FlipImageSize = false
/config/ref0.jpg 114 337
/config/ref1.jpg 504 77

[Digits]
Model = /config/dig1330s1q.tflite
;LogImageLocation = /log/digit
;LogfileRetentionInDays = 3
ModelInputSize = 20 32
main.digital1 177 264 34 66
main.digital2 233 260 34 64
main.digital3 289 261 34 62
main.digital4 347 258 35 69
main.digital5 406 260 33 64
main.digital6 463 267 30 60
main.digital7 518 262 33 67

[Analog]
Model = /config/ana0910s3_longq.tflite
;LogImageLocation = /log/analog
;LogfileRetentionInDays = 3
ModelInputSize = 32 32

[PostProcessing]
main.DecimalShift = -2
PreValueUse = true
PreValueAgeStartup = 720
AllowNegativeRates = false
main.MaxRateValue = 0.1
;main.ExtendedResolution = false
;main.IgnoreLeadingNaN = false
ErrorMessage = true
CheckDigitIncreaseConsistency = false

[MQTT]
Uri = mqtt://192.168.0.12:1883
MainTopic = gaszaehler
;ClientID = wasser
;user = USERNAME
;password = PASSWORD

[GPIO]
;IO0 = input disabled 10 false false 
;IO1 = input disabled 10 false false 
;IO3 = input disabled 10 false false 
;IO4 = built-in-led disabled 1 false false 
IO12 = external-flash-ws281x disabled 10 false false
;IO13 = input-pullup disabled 10 false false 
LEDType = WS2812B
LEDNumbers = 1
LEDColor = 255 255 255

[AutoTimer]
AutoStart = true
Intervall = 4.85

[Debug]
Logfile = true
LogfileRetentionInDays = 3

[System]
TimeZone = CET-1CEST,M3.5.0,M10.5.0/3
;TimeServer = undefined
;AutoAdjustSummertime = false
;Hostname = undefined
SetupMode = false

**Comment by jomjol** [comment]
Well, it's not looking too bad. Maybe you should improve the ROI setting a little bit according to the wiki: https://github.com/jomjol/AI-on-the-edge-device/wiki/ROI-Configuration

But if this does not help, I would add your images to the training. What I need for this you also find in the wiki
