### ISSUE TITLE
Help with exposure and alignment.

### ISSUE THREAD

**Issue by amaridev** [jomjol/AI-on-the-edge-device#572]
Hello,
to begin with, I wanted to say a big thank you for this fantastic project. I am using the flat power meter housing from thingiverse to read out my power meter with 2 external WS2812B LEDs, I positioned one left and one right relatively low, close to the mirror.

My problem is that the picture is always misaligned. First, I thought my reference marks are too close to each other. But after playing for two hours, I think it's more due to the exposure of the image. My reference picture was perfectly sharp, good contrast and lightning. But every image after that is either underexposure or too bright. Setting different values for the LEDs between 20 and 255 didn't make a big difference. 

Do you think, too, that the alignment issue is due to bad exposure? What could I do to fix it? I am getting out of ideas, as the lightning with these 2 external LEDs is already as good as it gets. 

![Screenshot 2022-01-15 at 15 54 39](https://user-images.githubusercontent.com/13658668/149627657-d36c2afb-462d-4b31-9dfd-d014efdb5039.png)
![Screenshot 2022-01-15 at 15 55 05](https://user-images.githubusercontent.com/13658668/149627659-94bca965-ca15-4a32-a5c2-bb9db5267145.png)
![Screenshot 2022-01-15 at 16 07 05](https://user-images.githubusercontent.com/13658668/149627662-8bebbe0f-27ba-4662-ae31-a79c18172064.png)

**Comment by Kalli01** [comment]
I would try to create the marks on opposite corners.
The marks are used to align the image and if they are further apart, it works better.

Maybe you can put a small white strip of tape in the top left corner. With the kWh on the bottom right you might have a better alignment

[Wiki](https://github.com/jomjol/AI-on-the-edge-device/wiki/Graphical-configuration#2b-define-alignment-references)

After changing settings you have to restart once to apply them.

**Comment by jomjol** [comment]
The alignment marks are clearly to close to each other. They should be more or less on the oposite to each other and they should have a structure, that is not given in the surrounding area.

**Comment by amaridev** [comment]
Thank you, I followed that advice and added a sticker with a dot on it. Picture quality is still not like I wish it was, but at least the alignment is now very consistent. 

My only problem is now, that it sometimes returns wrong values  for one of the numbers. For example, here, the 6 was read as 8. Which is an increase in 20 kwh. In the config, I had set the `MaxRateValue` to 0.5. But it seems it ignored that? Or did I use this parameter wrong?

![Screenshot 2022-01-17 at 07 58 20](https://user-images.githubusercontent.com/13658668/149726496-490b3c75-3adb-428c-9254-d82721e3d38d.png)

Also, how would you set the frames for the single digits if they are not always centered? Sometimes the number sits to high or to low in the frame, because the position of the number wheels is not consistent. It's a very old powermeter unfortunately.

**Comment by friedpa** [comment]
Much to less contrast, looks like the flash is too strong

**Comment by amaridev** [comment]
@friedpa Thanks, I will try that :). It gets really noisy when I dim the led. But maybe it will help.

**Comment by friedpa** [comment]
Example:

![grafik](https://user-images.githubusercontent.com/42890695/149781360-d722f01c-a72d-4440-b748-13cc23b11655.png)
