### ISSUE TITLE
Web-GUI Auffälligkeiten

### ISSUE THREAD

**Issue by RoberWi** [jomjol/AI-on-the-edge-device#573]
Für ein zukünftiges Update, in den HTML-Masken habe ich im Firefox (neueste Version) ein paar Merkwüdigkeiten:

ROIs editieren, in einem der Felder x,y, dy, dy eine manuelle Eingabe machen. Ergebnis: Das Pulldown für die Auswahl eines ROIs kann nicht mehr benutzt werden. Es öffnen uns schließt sich sofort wieder ohne Änderungsmöglichkeit:

Ursache: Der Focus wird direkt wieder in das Feld gezogen, in dem man die Eingabe gemacht hat.

Work-Around: Tastensteuerung nutzen

Config-Editor: Gleiches Problem, bei bestimmten Eingaben wird der Focus direkt wieder ins letzte Eingabefeld gezogen, daher ist das Anklicken von "Update Config.ini" nicht möglich.

Work-Around: Tastensteuerung nutzen

**Comment by jomjol** [comment]
Fehler nicht nachvollziebar (gestestet und Firefox). Bitte ggf. nochmals aufmachen.
