### ISSUE TITLE
Timesync in 10.2.0 not working anymore

### ISSUE THREAD

**Issue by michaeljoos72** [jomjol/AI-on-the-edge-device#574]
Does someone else see this? On info page (latest restart) & MQTT I get this: 19700101-010022 or 01.01.1970 17:03
Timezone settings enabled: CET-1CEST,M3.5.0,M10.5.0/3

**Comment by jomjol** [comment]
This means, that the time server could not be reached and there the time starts with 01.01.1977.

Check the time server settings and the excess of your device to the internet or internal time server.

**Comment by RoberWi** [comment]
I can confirm that there seem to be problems with time synchronization in version 10.2. Downgrade to version 9.2 and without changing the settings the synchronization works again.

**Comment by michaeljoos72** [comment]
I have downgraded and then flashed 10.2 again. After that step it worked (only re-flash 10.2 did not solve).
