### ISSUE TITLE
mosquitto_sub doesn't work

### ISSUE THREAD

**Issue by rainerme** [jomjol/AI-on-the-edge-device#575]
when I use mosquitto_sub -h 192.168.178.113 -t /# -d I always get Error: Connection refused. This subscribe request should work for any topic since I am using /#. Also using the right topic does show the same issue too. I am using the latest version master - v10.2.0 - 2022-01-14. 192.168.178.113 is my IP address which I also use in my web browser to connect.

This is the mqtt section of of my configuration:
[MQTT]
Uri = mqtt://192.168.178.113:1883
MainTopic = elektrozaehler/zaehlerstand
;ClientID = elektro
;user = xxxx
;password = xxx

Also mosquitto_sub -h 192.168.178.113 -t elektrozaehler/zaehlerstand -d  or mosquitto_sub -h 192.168.178.113 -t elektrozaehler/zaehlerstand/# don't work.

Also in the logfile verbose I am not able to nail down why I can subscribe. If I am using a local mosquito_pub all is working fine, no issue.

**Comment by jomjol** [comment]
The MQTT running on the ESP32 is not able to get subscriptions. It works the other way round and sends the data to an broker after a reading.
