### ISSUE TITLE
Spezieller Zahlenüberlauf 

### ISSUE THREAD

**Issue by Phirror** [jomjol/AI-on-the-edge-device#576]
Hallo,
zunächst einmal vielen Dank für dieses großartige Projekt! 

Ich habe ein spezielles Problem mit meinem Wasserzähler. Der Überlauf in die digitale 1er Stelle findet seltsamerweise nicht beim Nulldurchgang der analogen 0,1er Stelle statt, sondern zwischen x,4 und x,5. Dies führt natürlich zu Problemen bei der Kostistenzprüfung und zu negative erkannten Raten beim Nulldurchgang der 0,1er Stelle.
![Wasseruhr_1](https://user-images.githubusercontent.com/97850553/149674823-1ce68be3-59b2-4b2c-996f-12b0ec361471.jpg)
Ich kann mir vorstellen, dass der Zeiger der 0,1er Stelle um 180° verdreht im Zählwerk montiert ist.
Gibt es hier eine Möglichkeit, dies zu korrigieren?

**Comment by jomjol** [comment]
Leider nein - du könntest dir die Rohwerte abholen und dann den Algorithmus selbst implementieren.

Beste Grüße,
  jomjol
