### ISSUE TITLE
Letze Ziffer wird zeitweise al "0" ausgeweret

### ISSUE THREAD

**Issue by xerion3800** [jomjol/AI-on-the-edge-device#577]
Hallo erstmal und vielen Dank für das Tolle Projekt.
Ich habe immer weder mal das Problem, dass die letzte Stelle als  identifiziert wird obwohl ich keine Problem visuell entdecken kann.
Nutze die Version "master - v10.2.0 - 2022-01-14"
Irgendwelche Tipps wo ich nach schauen könnte?

![image](https://user-images.githubusercontent.com/46169403/149675239-9a78e59b-98c8-4f7e-80e3-5ec53723318c.png)

**Comment by jomjol** [comment]
Falls noch nicht geschehen, könntest du auf das neueste tflite umstellen: https://github.com/jomjol/AI-on-the-edge-device/raw/master/sd-card/config/dig-s2-q-20220104.tflite

Falls das auch nicht hilft, dann könntest du mir einen Trainingsset erzeugen und ich nehme es mit auf. Anleitung findest du hier: https://github.com/jomjol/AI-on-the-edge-device/wiki/ROI-Configuration#1-get-images-into-the-next-training-round

**Comment by xerion3800** [comment]
Danke für die schnelle Rückmeldung. Ich habe jetzt mal auf die neueste tfilte umgestellt und teste das erstmal.

**Comment by msmthng** [comment]
![image](https://user-images.githubusercontent.com/40269445/150118977-042c3b71-95d5-44cc-935d-91aa654f04a6.png)
Ich habe ein ähnliches Problem,  die 8 wird manchmal als 3 erkannt.

**Comment by msmthng** [comment]
![image](https://user-images.githubusercontent.com/40269445/150119146-e41b51bf-6c4d-4203-aee5-94a14d10edce.png)
