### ISSUE TITLE
Ziffer "1" wird nur als "0" erkannt

### ISSUE THREAD

**Issue by Schmakus** [jomjol/AI-on-the-edge-device#578]
Ich kann machen was ich will, aber die "1" an dig3 wird immer nur al "0" erkannt. Wie kann ich das verbessern/ändern?
v10.2
![148955844-c69a56c4-b460-4f37-b57d-6655a8e9bead](https://user-images.githubusercontent.com/8231359/149717299-5461f321-ba39-496d-87c3-feaf1e5c02ac.jpg)
.0

**Comment by juergen852** [comment]
Versuch mal 
- Kamera ein paar Grad gegen den Uhrzeigersinn zu drehen, am besten von Hand und nicht per Software. Die Ziffer 1 und 5 sind etwas versetzt, das muss nicht sein.
- Der Orientierungspunkt m³ hat eine starke Spiegelung. Ich würde mal den R40H rechts als Alternative versuchen.

**Comment by CS-OL** [comment]
Hallo, ich habe ein ähnliches Problem, wollte dafür nicht ein weiteres Thema aufmachen. Bei mir wird eine 2 alle paar Durchläufe als 5 erkannt. Das merkt die Software, dass das ein Fehler sein muss und es wird ein leeres Value übermittelt. Dann geht es zwischendurch wieder. Ich werte das in FHEM aus mit Statistic-Modul, das erkennt dann mitmal, 120m³, wenn das denn dann wieder übermittelt wird und damit habe ich für heute einen Verbauch von 120m³. Kann man vielleicht etwas am Kontrast stellen ? Und ist es konfigurierbar, dass bei einem Error eben nicht ein leeres Value sondern der Pre-Wert übermittelt wird ?

Sonst super Projekt !!! 

Grüße Christian
![Zählerstand Fehler](https://user-images.githubusercontent.com/97830140/150581015-f44b320f-f957-4536-8d80-9c469a84ff5b.JPG)
?

**Comment by jomjol** [comment]
Ich trainiere gerade wieder einen neuen Satz Daten. Eventuell wird es damit besser. 
@CS-OL : Konfiguration des Verhalten bei Fehler ist momentan nicht drin - eventuell für eine spätere Version. Gerade aber keine Kapa.

Ich lassen den Issue mal offen, bis ich ein neues Netz trainiert habe und poste es dann hier.

**Comment by CS-OL** [comment]
Super, danke dir !!!

**Comment by jomjol** [comment]
Gerade habe ich ein neues neuronales Netz geteached: https://github.com/jomjol/AI-on-the-edge-device/raw/rolling/firmware/dig-s1-q-20220206.tflite

Bitte mal probieren!
