### ISSUE TITLE
Fix Ipadress aviable

### ISSUE THREAD

**Issue by mikewolf** [jomjol/AI-on-the-edge-device#58]
Hallo wäre es machbar in der Config,ini oder Wlan.ini  ne fixe ip adresse zu geben ,
normal macht das die Fritz ,nur die gibt diesen ebtweder 55 oder239 argg
obwohl fix zugegeben passiert bei manchen esps

**Comment by jomjol** [comment]
Hast du mal probiert über den Hostnamen darauf zuzugreifen? Momentan würde ich nicht noch mehr features in die config.ini einbauen. Ich bekomme jede Menge Fragen zu den schon vorhandenen. 
Eins der nächsten Projekte ist erstmal, eine html-Seite für die schon vorhandenen Parameter zu implementieren. Suche da noch Support.
Gruß,
   jomjol
