### ISSUE TITLE
Mehr Infos Protokollieren....

### ISSUE THREAD

**Issue by ThomasCr** [jomjol/AI-on-the-edge-device#580]
Ich denke es wäre hilfreich, wenn im Header des Logfiles auch die Firmware / HTML Version mit weggeschrieben werden würde.

Evtl. auch Technische Daten wie bei Tasmota.... oder zumindest auf der Info Seite....

<html><body>

Daten | Wert
-- | --
ESP Chip ID | 2097479 (ESP8266EX)
Flash Chip ID | 0x16405E
Größe Flash-Chip | 4096 kB
Flash nutzbar | 4096 kB
Größe Programm | 622 kB
Flash frei | 1424 kB
Freier Arbeitsspeicher | 26.4 kB

</body>
</html>

Solche Infos sind evtl. auch von Bedeutung, um bestimmte Fehler raus deuten zu können.....

**Comment by ThomasCr** [comment]
Oh, ich würde auch Protokollieren, wenn man OTA benutzt (Fileupload (bytes), und das Flashen selbst/auspacken).

**Comment by jomjol** [comment]
Hallo Thomas,
ich kann deine Idee nachvollziehen und wenn du da unterstützen kannst, bin ich sehr dankbar und intergriere gerne den Pull-Request. 

Ich selbst habe aber in den nächste Wochen keine Zeit daran zu arbeiten. Daher nehme ich die Idee in den Feature Request List mit auf, schließe aber den Issue.


Daher nehme ich sie in den Langzeitspeicher auf
