### ISSUE TITLE
erkannter Wert wird nicht übernommen

### ISSUE THREAD

**Issue by RoberWi** [jomjol/AI-on-the-edge-device#581]
Das im Bild kommt öfter mal vor, gibt es irgendeine konfigurationstechnische Erklärung dafür?

Raw korrekt erkannt, trotzdem Value nicht neugesetzt, "no error". 

![tempsnip](https://user-images.githubusercontent.com/97785524/149816076-09e25c4d-e019-430a-805b-443d7e20d4df.png)

**Comment by juergen852** [comment]
Setz mal in der Konfiguration den Wert "MaxRateValue / Maximum change of reading per minute" auf 5 oder so.
Soweit ich das verstanden hatte, versucht die Software unlogische Werte zu verhindern indem:
1. Das neue Ergebis kann nie kleiner sein, als das frühere.
2. Das neue Ergebnis kann sich innerhalb eines Messzyklus maximal um "Maximum Change" ändern. Wenn die Änderung größer ist, als der vom Anwender definierte Zuwachs, ist es vermutlich eine Falschmessung.

**Comment by RoberWi** [comment]
Falschmessungen werden aber mit "rate too high" quittiert. Hier wird "no error" ausgegeben.

Mal davon abgesehen, steht der Wert "Maximum change of reading per minute" bei 1, was bei einem Intervall von 30 Minuten ja eine Änderung von 30 erlauben würde. Im Bild kann sehen, dass die Änderung nur 0,5 ist.

**Comment by RoberWi** [comment]
Wird lustiger:
Raw 10710,49 -> korrekt
Prev: 10708,40
Error: Neg. Rate.

Keine Ahnung, wo der Wert von "Read" herkommt. Und warum ist "Value" oben leer?

![tempsnip](https://user-images.githubusercontent.com/97785524/149989476-3c541c97-78af-4d75-a377-0476ef9bc213.png)

**Comment by friedpa** [comment]
Weil es einen nicht gültigen Wert hat. Setze nun einmal PreValue auf 10710.49

**Comment by RoberWi** [comment]
Ehrlich gesagt ist mir diese Fehlersuche im Nebel mittlerweile zu blöd. Version 9.2 installiert und beim ersten Reboot sieht plötzlich alles wieder gut aus.

**Comment by friedpa** [comment]
Verstehe ich gut, bin auf 9.0 ....

**Comment by jomjol** [comment]
Das Problem dürfte mit dem Paramter `CheckDigitIncreaseConsistency`. Ich vermute, dass der aktiviert ist (true). Bitte deaktivieren, ist nur im Zusammenhang mit analogen Zählern sinnvoll.

**Comment by RoberWi** [comment]
> Das Problem dürfte mit dem Paramter `CheckDigitIncreaseConsistency`. Ich vermute, dass der aktiviert ist (true). Bitte deaktivieren, ist nur im Zusammenhang mit analogen Zählern sinnvoll.

Der Wert war tatsächlich gesetzt. Habe ich rausgenommen und beobachte. Danke dafür!
