### ISSUE TITLE
Via MQTT to TheThingsNetwork TTN

### ISSUE THREAD

**Issue by juergen852** [jomjol/AI-on-the-edge-device#582]
Hi,
does somebody use https://eu1.cloud.thethings.network to store readings?
I am not shure about the username when creating the API-Key.
TTN proposed "privat@ttn" as username to me and created a Key.

Using this config the ESP logs, that he could not connect to the MQTT-Broker.
![mqtt2ttn vom 2022-01-17 22-15-36](https://user-images.githubusercontent.com/33433306/149837744-1d32aaaf-305a-487c-a01b-9c300de25ce1.png)

**Comment by stromzaehler** [comment]
Try mqtt://eu1... (with 2 slashes)

**Comment by juergen852** [comment]
You cannot imagine how I feel now....
Anyway: I managed to connect the ESP and mosquitto_sub, but somehow I was unable to recieve the data at mosquitto_sub side....
Set up my own mosquitto and works fine now.
