### ISSUE TITLE
Letzte "digitale" Ziffer wird zu früh upgedated.

### ISSUE THREAD

**Issue by Cumulus7** [jomjol/AI-on-the-edge-device#584]
Hi,

die letzte Ziffer zählt zu "früh" hoch.
Sie läuft bei meinem Wasserzähler die ganze Zeit "rund". 
Resultat: bei 695.9 wird schon 696,9 erkannt.
Erkennbar an der Previous-Value.
Jetzt wird der Zählerstand wieder korrekt ausgelesen - aber nicht mehr verarbeitet.....

![image](https://user-images.githubusercontent.com/45620107/149894200-02fb1af8-06c6-4d83-80a3-8482bed8c43b.png)

Kann ich das verhindern?
Ich hatte gedacht, das Post-Processing würde so etwas verhindern.
Edit: Im Laufe des gestrigen Tages stand die ganze Zeit 69N.xxx im erkannten RAW-Wert. Ist auch logisch, da eine halb rotierte Zahl zwischen 5 und 6 nicht erkannt werden kann. Dank der Previous Value wurde aber immer der korrekte Wert 695.xxx übermittelt. Das lief also zunächst super.

![image](https://user-images.githubusercontent.com/45620107/149894649-7aa23398-42bc-4ed7-84f6-1c4c438cae99.png)

Meine Version:
master - v10.1.0 - 2022-01-09

Ansonsten: Wahnsinns-Projekt. Mega-Respekt vor der Leistung, das auf dem ESP32 zum Laufen zu bekommen.

Gruß,
Markus

**Comment by Kalli01** [comment]
Hi
in den Einstellungen gibt es im Experten Modus die Option "CheckDigitIncreaseConsistency" 
Bei meine Wasserzähler habe ich sie aktiviert. Vielleicht hilft sie dir.

**Comment by Cumulus7** [comment]
Danke. Habe ich jetzt mal aktiviert.
Jetzt muss ich den nächsten Kubikmeter mal abwarten.

Melde mich dann noch mal!

Gruß
Markus

**Comment by jomjol** [comment]
Ja - sollte helfen. Ist genau dafür gedacht, aber nur im Zusammenspiel mit analogen Zeigern.

**Comment by Cumulus7** [comment]
Rückmeldung: hat geholfen - der nächste Round-Trip der letzten Ziffer hat jetzt funktioniert :-)
Danke!
