### ISSUE TITLE
Training

### ISSUE THREAD

**Issue by redflag237** [jomjol/AI-on-the-edge-device#585]
Hi,
Kannst du bitte die Zahlen für das Modell trainieren? Die anhängenden Zahlen (immer die letzte digitale Ziffer) verursacht bei mir noch größere Probleme. Entweder wird Sie als 10 oder 2 erkannt. Ändern der Box-Größe bringt keinen Unterschied.
Dankeschön :-)
![2_dig5_20220118-101521](https://user-images.githubusercontent.com/27703750/149912551-f5240c79-82a5-43fe-bd2d-29af789f4484.jpg)
![2_dig5_20220118-101755](https://user-images.githubusercontent.com/27703750/149912557-4fb3013e-4829-4fd1-8d2d-a5375bbedd71.jpg)
![2_dig5_20220118-103755](https://user-images.githubusercontent.com/27703750/149912560-75e7da65-1222-40e7-9fa8-5805ba23324e.jpg)
![10_dig5_20220118-100903](https://user-images.githubusercontent.com/27703750/149912562-64855aaf-1f32-432a-94ae-e102c3a42f8d.jpg)
![10_dig5_20220118-101228](https://user-images.githubusercontent.com/27703750/149912563-4669de47-cd10-4e65-bb91-ce23ad4f790b.jpg)
![2_dig5_20220118-113446](https://user-images.githubusercontent.com/27703750/149921440-2db9baab-4335-4e96-8d62-17439c0e2cf0.jpg)
![10_dig5_20220118-111752](https://user-images.githubusercontent.com/27703750/149921442-c665a98b-71de-4384-a178-b55b051a840c.jpg)
![2_dig5_20220118-112834](https://user-images.githubusercontent.com/27703750/149921446-17cdcc48-61ed-4b11-b89d-095add8bad8d.jpg)
(raw)
![raw_20220118-101521](https://user-images.githubusercontent.com/27703750/149913902-264636b8-f929-40d0-ba46-f3ca29120c81.jpg)

**Comment by jomjol** [comment]
Werde ich machen.

Du könntest deine ROIs noch ein bisschen optimieren: https://github.com/jomjol/AI-on-the-edge-device/wiki/ROI-Configuration
