### ISSUE TITLE
Web-GUI häufig nicht erreichbar

### ISSUE THREAD

**Issue by Gukerl** [jomjol/AI-on-the-edge-device#588]
Oft mehrmals am Tag ist das "Gerät" weder per Web-GUI erreichbar und liefert klarerweise dann auch keine Daten per MQTT.
Workaround: eine WLAN-Steckdose, die vom iOBroker bei MQTT "not connected" kurz aus- und wieder eingeschalten wird.

Weiteres Problem beim Neustart, dass das Gerät nicht wirklich durchbooted. Ich sehe es im "Seriellen Monitor" der Arduino Entwicklungsumgebung. Immer mal wieder bleibt es beim Booten hängen. WLAN wird verbunden und bevor das erste Mal die LED aufleuchten sollte bleibt es hängen.
Workaround Erweiterung des iOBroker Skriptes, aus/ein schalten -> warten -> nach 60sec kein connect -> das ganze wieder von vorne, nach mehreren Versuchen klappt es dann meistens. So halte ich das Teil am Leben.

SoftwareVersion : 10.2.0

Hat jemand ähnliche Probleme?

**Comment by CS-OL** [comment]
Ich hatte ähnliche Probleme. Bei mir war es anscheind das Netzteil, ich habe da eins vom IPhone dran gehängt, seit dem ist das ganze sehr stabil.

Grüße Christian

**Comment by jomjol** [comment]
In der Version 10.2 habe ich eine neuere Bibliothek des ESP32-CAM Treibers von espressif verwendet. 
WENN er läuft, dann läuft er in der Regel sehr viel stabile (teilweise mehr als 2000 Runs ohne Reboot). 
ABER WENN ER NICHT LÄUFT, dann leider auch gar nicht.

Ich habe inzwischen eines meiner zahlreichen Testmodule mit genau demselben Thema. Ich konnte auch schon feststellen, dass das Modul sehr viel empfindlicher auf die Stromversorgung reagiert (@Gukerl), aber das alleine löst es noch nicht.

Ich bin dran, aber bis dahin bleibt nur auf v9.x zu wechseln, falls es nicht läuft.

**Comment by Gukerl** [comment]
Danke für die Feedbacks. Mit meinem iOBroker Blockly Skript klappts ganz gut, in wurde 24h 12x neu gestartet. Ich Grunde will ich nur den gesamten Tagesverbrauch wissen, somit kommts darauf jetzt nicht so wirklich an.
Ich hänge das Blocly mal an, vielleicht kanns jemand als Inspiration brauchen.
LG, Andi
![Fernwaerme](https://user-images.githubusercontent.com/72930135/150485562-75de55f3-5d77-481f-bed8-a6a537b5bcf9.JPG)

**Comment by jomjol** [comment]
Ich konnte das Problem weiter einkreisen: die neuen ESP32-CAM Treiber reagieren sehr viel empfindlicher auf Spannungsschwankungen. Diese tretten insbesondere bei Verwendung der integrierten Flash-LED auf. System mit WS2812-LEDs scheinen das Problem nicht zu haben. Bei diesen Schwankungen kann die Kamera anscheinend in einem Zustand hängen bleiben, bei der nur noch einer Reset mit PowerOff zu helfen scheint.

Leider läßt sich bei dem ESP32CAM Modul die Kamera per Software nicht vollständig vom Strom trennen (die 3.3V sind nicht schaltbar). Ich experementiere mit ein paar Tricks während des Startups. 

Bitte mal die neueste Rolling testen.

**Comment by Kalli01** [comment]
Ein Zähler bei mir hat ein ähnliches Problem. Liegt bei mir aber vermutlich nicht an einer Version, da er von heute auf morgen plötzlich schlechter erreichbar war.
@Gukerl könntest du bitte einmal probieren, ob du über ein Handy auf die Oberfläche kommst, wenn er nicht mehr erreichbar ist?
Bei mir ist das nämlich so. Iobroker zeigt connection lost und über Chrome am PC lädt die Oberlfäche gar nicht oder schlecht. 
Über Chrome auf dem Handy lädt die Seite aber.
So ein ähnliches Script werde ich mir auch erstellen. Über die Seite IP/reboot kann man einen Neustart auslösen. Vielleicht ist diese Seite noch erreichbar, um mir so die Funksteckdose zu sparen.

**Comment by Gukerl** [comment]
> könntest du bitte einmal probieren, ob du über ein Handy auf die Oberfläche kommst

Leider auch nicht, die GUI ist mit keinem Device/Browser erreichbar. Ich werds beim nächsten Mal checken. Was ich aber noch nicht versucht habe, per Ping. 
Feddback fühestens am Montag 24.01.22, jetzt mal Wochenende. :)

**Comment by jomjol** [comment]
Problem sollte ab Version 10.3 behoben sein (Achtung: Anpassung Parameter ImageQuality notwendig).
