### ISSUE TITLE
Tips für analogen Wert gesucht

### ISSUE THREAD

**Issue by Cumulus7** [jomjol/AI-on-the-edge-device#589]
Hi,

mein erster analoger Zähler wird ein wenig ungenau ausgewertet.
Leider der erste - der damit um 100l falsch zählt.

Statt ca. 0,5 wird 1,1 erkannt.
-> xxx,1504 m³ statt xxx,0504 m³

Ich habe versucht:
- neue Halterung gedruckt, um alle Zeiger vollständig anzuzeigen und die Ausleuchtung zu verbessern (vorher war einer minimal abgeschnitten und eine Spiegelung der Blitz-LED auf einem Zeiger)
- Bild versucht maximal scharf einzustellen
- 64x64 in der Expert-Config bei der analogen Model-Input-Size eingetragen (da kam nur noch Müll bei raus - passt wohl das Training dann nicht zu?)
- den ersten Analog-Zeiger etwas Off-Center gesetzt nach rechts - der Zeiger erschien mit nicht genau Mittig im Kreis zu sitzen
- nach den Änderungen jeweils ein Reboot

Gibt es noch irgend etwas, was ich hier versuchen könnte?
Evtl. die Kreise größer oder kleiner machen?
(habe hier leider keine Tips im Wiki zu gefunden)

Screenshots:

![image](https://user-images.githubusercontent.com/45620107/150405466-279e1b7e-a4b1-44eb-a990-41102613e9c4.png)

Ausschnitt aus der Recognition:
![image](https://user-images.githubusercontent.com/45620107/150405575-be8c9ee2-5371-448d-8d26-47d9ec94e94c.png)

Danke für alle Tips und Gruß,
Markus

**Comment by jomjol** [comment]
Leider nein, du hast schon eine ziemlich optimale Einstellung und ehrlich gesagt liegt er nur "0.5" daneben. Ich weiß, es sind 500 Liter, aber ich fürchte da bist du jetzt an der Grenze des aktuell machbaren.

Alternativ könntest du ein eigenes Netz trainieren mit größeren Bilder etc. aber das ist ziemlich aufwendig.
