### ISSUE TITLE
Guru Meditation Error: Core 0 panic'ed (LoadProhibited).

### ISSUE THREAD

**Issue by SerDacik** [jomjol/AI-on-the-edge-device#592]
Guru Meditation Error: Core  0 panic'ed (LoadProhibited). Exception was unhandled.

Core  0 register dump:
PC      : 0x4008b565  PS      : 0x00060f30  A0      : 0x800dc822  A1      : 0x3ffc3440  
A2      : 0x3ffc3520  A3      : 0x00000000  A4      : 0x000000ff  A5      : 0x0000ff00  
A6      : 0x00ff0000  A7      : 0xff000000  A8      : 0x00000000  A9      : 0x3ffc3400  
A10     : 0x3ffc3520  A11     : 0x3f40c711  A12     : 0x00000000  A13     : 0x400dc458  
A14     : 0x00000000  A15     : 0x3ffc35bc  SAR     : 0x00000016  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x00000000  LBEG    : 0x4008b565  LEND    : 0x4008b57d  LCOUNT  : 0xffffffff  

Backtrace:0x4008b562:0x3ffc3440 0x400dc81f:0x3ffc3450 0x400d3962:0x3ffc3600 0x40209f3b:0x3ffc36a0

Please Help

**Comment by jomjol** [comment]
Not enough information. Please post a full log of the serial output.
