### ISSUE TITLE
Firmware not starting

### ISSUE THREAD

**Issue by Ashracx** [jomjol/AI-on-the-edge-device#593]
Hi,
I have some trouble by starting my ESP.
In the Log it says:
Not enought PSRAM available. Expected 4.194.304 MByte - available: 2149914
Either not initialzed or too small (2MByte only) or not present at all. Firmware cannot start!!

**Comment by jomjol** [comment]
You have 
1) bought a module with only 2MByte
2) have been cheated by you trader.

Only solution: buy a version with 4MByte.
