### ISSUE TITLE
Guru Meditation Error: Core  0 panic'ed (LoadProhibited). Exception was unhandled.

### ISSUE THREAD

**Issue by SerDacik** [jomjol/AI-on-the-edge-device#594]
Rebooting...
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:7188
load:0x40078000,len:14764
load:0x40080400,len:3764
entry 0x40080680
[0;32mI (27) boot: ESP-IDF 4.3.1 2nd stage bootloader[0m
[0;32mI (27) boot: compile time 20:31:42[0m
[0;32mI (27) boot: chip revision: 1[0m
[0;32mI (30) boot_comm: chip revision: 1, min. bootloader chip revision: 0[0m
[0;32mI (37) boot.esp32: SPI Speed      : 40MHz[0m
[0;32mI (41) boot.esp32: SPI Mode       : DIO[0m
[0;32mI (46) boot.esp32: SPI Flash Size : 4MB[0m
[0;32mI (51) boot: Enabling RNG early entropy source...[0m
[0;32mI (56) boot: Partition Table:[0m
[0;32mI (60) boot: ## Label            Usage          Type ST Offset   Length[0m
[0;32mI (67) boot:  0 nvs              WiFi data        01 02 00009000 00004000[0m
[0;32mI (74) boot:  1 otadata          OTA data         01 00 0000d000 00002000[0m
[0;32mI (82) boot:  2 phy_init         RF data          01 01 0000f000 00001000[0m
[0;32mI (89) boot:  3 ota_0            OTA app          00 10 00010000 001db000[0m
[0;32mI (97) boot:  4 ota_1            OTA app          00 11 001f0000 001db000[0m
[0;32mI (104) boot: End of partition table[0m
[0;32mI (109) boot_comm: chip revision: 1, min. application chip revision: 0[0m
[0;32mI (116) esp_image: segment 0: paddr=00010020 vaddr=3f400020 size=49038h (299064) map[0m
[0;32mI (239) esp_image: segment 1: paddr=00059060 vaddr=3ffb0000 size=04984h ( 18820) load[0m
[0;32mI (247) esp_image: segment 2: paddr=0005d9ec vaddr=40080000 size=0262ch (  9772) load[0m
[0;32mI (251) esp_image: segment 3: paddr=00060020 vaddr=400d0020 size=13a1b4h (1286580) map[0m
[0;32mI (745) esp_image: segment 4: paddr=0019a1dc vaddr=4008262c size=19200h (102912) load[0m
[0;32mI (790) esp_image: segment 5: paddr=001b33e4 vaddr=50000000 size=00010h (    16) load[0m
[0;32mI (804) boot: Loaded app from partition at offset 0x10000[0m
[0;32mI (804) boot: Disabling RNG early entropy source...[0m
[0;32mI (816) psram: This chip is ESP32-D0WD[0m
[0;32mI (816) spiram: Found 64MBit SPI RAM device[0m
[0;32mI (816) spiram: SPI RAM mode: flash 40m sram 40m[0m
[0;32mI (821) spiram: PSRAM initialized, cache is in low/high (2-core) mode.[0m
[0;32mI (828) cpu_start: Pro cpu up.[0m
[0;32mI (832) cpu_start: Starting app cpu, entry point is 0x40082910[0m
[0;32mI (825) cpu_start: App cpu up.[0m
[0;32mI (1727) spiram: SPI SRAM memory test OK[0m
[0;32mI (1735) cpu_start: Pro cpu start user code[0m
[0;32mI (1735) cpu_start: cpu freq: 160000000[0m
[0;32mI (1735) cpu_start: Application information:[0m
[0;32mI (1738) cpu_start: Project name:     esp32cam-server-only[0m
[0;32mI (1744) cpu_start: App version:      0.0.9.3[0m
[0;32mI (1749) cpu_start: Compile time:     Jan 14 2022 20:30:04[0m
[0;32mI (1755) cpu_start: ELF file SHA256:  b04120accc0780f7...[0m
[0;32mI (1761) cpu_start: ESP-IDF:          4.3.1[0m
[0;32mI (1766) heap_init: Initializing. RAM available for dynamic allocation:[0m
[0;32mI (1773) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM[0m
[0;32mI (1780) heap_init: At 3FFC0510 len 0001FAF0 (126 KiB): DRAM[0m
[0;32mI (1786) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM[0m
[0;32mI (1792) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM[0m
[0;32mI (1799) heap_init: At 4009B82C len 000047D4 (17 KiB): IRAM[0m
[0;32mI (1805) spiram: Adding pool of 4096K of external SPI memory to heap allocator[0m
[0;32mI (1814) spi_flash: detected chip: generic[0m
[0;32mI (1818) spi_flash: flash io: dio[0m
[0;32mI (1827) cpu_start: Starting scheduler on PRO CPU.[0m
[0;32mI (0) cpu_start: Starting scheduler on APP CPU.[0m
[0;32mI (1832) spiram: Reserving pool of 32K of internal memory for DMA/internal allocations[0m
[0;32mI (1882) main: Using SDMMC peripheral[0m
Name: SU04G
Type: SDHC/SDXC
Speed: 20 MHz
Size: 3781MB
[0;32mI (1932) server_ota: Start CheckOTAUpdateCheck ...[0m
Start CheckOTAUpdateCheck ...
[0;32mI (1942) server_ota: SHA-256 for the partition table: : 9d4a2809ae90fb20709a8ca3dd3ac3462e1e73286bcd31b689060c91de06fa3a[0m
[0;32mI (1942) server_ota: SHA-256 for bootloader: : 58654fd0ec886a7a55a6166ade6a1fae24b07d13f6e1d1e9b6c8aa603f0662e9[0m
[0;32mI (1962) server_ota: SHA-256 for current firmware: : 53471952973179c9007c1579a8c95d3d72f00ae63b2e63a292afe56037f09ad3[0m
CheckOTAUpdate Partition: ESP_OK
open file /sdcard/wlan.ini in mode r
file loaded
No SSID and PASSWORD set!!!Hostname not set.
I (2012) wifi:wifi driver task: 3ffd2634, prio:23, stack:6656, core=0
[0;32mI (2012) system_api: Base MAC address is not set[0m
[0;32mI (2012) system_api: read default base MAC address from EFUSE[0m
I (2032) wifi:wifi firmware version: 88c8747
I (2032) wifi:wifi certification version: v7.0
I (2032) wifi:config NVS flash: enabled
I (2032) wifi:config nano formating: disabled
I (2032) wifi:Init data frame dynamic rx buffer num: 16
I (2042) wifi:Init management frame dynamic rx buffer num: 16
I (2042) wifi:Init management short buffer num: 32
I (2052) wifi:Init static tx buffer num: 16
I (2052) wifi:Init tx cache buffer num: 16
I (2062) wifi:Init static rx buffer size: 1600
I (2062) wifi:Init static rx buffer num: 10
I (2062) wifi:Init dynamic rx buffer num: 16
[0;32mI (2072) wifi_init: rx ba win: 6[0m
[0;32mI (2072) wifi_init: tcpip mbox: 32[0m
[0;32mI (2072) wifi_init: udp mbox: 6[0m
[0;32mI (2082) wifi_init: tcp mbox: 6[0m
[0;32mI (2082) wifi_init: tcp tx win: 5744[0m
[0;32mI (2092) wifi_init: tcp rx win: 5744[0m
[0;32mI (2092) wifi_init: tcp mss: 1440[0m
[0;32mI (2102) wifi_init: WiFi IRAM OP enabled[0m
[0;32mI (2102) wifi_init: WiFi RX IRAM OP enabled[0m
Guru Meditation Error: Core  0 panic'ed (LoadProhibited). Exception was unhandled.

Core  0 register dump:
PC      : 0x4008b565  PS      : 0x00060f30  A0      : 0x800dc822  A1      : 0x3ffc3440  
A2      : 0x3ffc3520  A3      : 0x00000000  A4      : 0x000000ff  A5      : 0x0000ff00  
A6      : 0x00ff0000  A7      : 0xff000000  A8      : 0x00000000  A9      : 0x3ffc3400  
A10     : 0x3ffc3520  A11     : 0x3f40c711  A12     : 0x00000000  A13     : 0x400dc458  
A14     : 0x00000000  A15     : 0x3ffc35bc  SAR     : 0x00000016  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x00000000  LBEG    : 0x4008b565  LEND    : 0x4008b57d  LCOUNT  : 0xffffffff  

Backtrace:0x4008b562:0x3ffc3440 0x400dc81f:0x3ffc3450 0x400d3962:0x3ffc3600 0x40209f3b:0x3ffc36a0

ELF file SHA256: b04120accc0780f7

**Comment by jomjol** [comment]
Something is wrong with your wif settings:
```
No SSID and PASSWORD set!!!Hostname not set.
```
This also could mean, that the sd-card cannot be read and therefore there is no wifi settings

**Comment by SerDacik** [comment]
Thanks for your reply.
What cards should be used?
I have the usual 4 GB.
need SDHС or SDXC

**Comment by jomjol** [comment]
I don't have a general recommendation. You need to a try and error approach.

**Comment by SerDacik** [comment]
Thank you.
installed a new SDHC card - and lo and behold, it worked !!!!
Thank you for your work.

**Comment by Dougstar** [comment]
I just got a similar issue:

Rebooting...
ets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:4
load:0x3fff0034,len:7248
ho 0 tail 12 room 4
load:0x40078000,len:13856
load:0x40080400,len:4052
entry 0x40080688
[0;32mI (31) boot: ESP-IDF 3.40100.200827 2nd stage bootloader[0m
[0;32mI (31) boot: compile time 21:55:31[0m
[0;32mI (31) boot: chip revision: 3[0m
[0;32mI (34) boot_comm: chip revision: 3, min. bootloader chip revision: 0[0m
[0;32mI (42) boot.esp32: SPI Speed      : 40MHz[0m
[0;32mI (46) boot.esp32: SPI Mode       : DIO[0m
[0;32mI (51) boot.esp32: SPI Flash Size : 4MB[0m
[0;32mI (55) boot: Enabling RNG early entropy source...[0m
[0;32mI (61) boot: Partition Table:[0m
[0;32mI (64) boot: ## Label            Usage          Type ST Offset   Length[0m
[0;32mI (72) boot:  0 nvs              WiFi data        01 02 00009000 00004000[0m
[0;32mI (79) boot:  1 otadata          OTA data         01 00 0000d000 00002000[0m
[0;32mI (86) boot:  2 phy_init         RF data          01 01 0000f000 00001000[0m
[0;32mI (94) boot:  3 ota_0            OTA app          00 10 00010000 001db000[0m
[0;32mI (101) boot:  4 ota_1            OTA app          00 11 001f0000 001db000[0m
[0;32mI (109) boot: End of partition table[0m
[0;32mI (113) boot_comm: chip revision: 3, min. application chip revision: 0[0m
[0;32mI (120) esp_image: segment 0: paddr=0x00010020 vaddr=0x3f400020 size=0x511d4 (332244) map[0m
[0;32mI (273) esp_image: segment 1: paddr=0x000611fc vaddr=0x3ffb0000 size=0x05050 ( 20560) load[0m
[0;32mI (283) esp_image: segment 2: paddr=0x00066254 vaddr=0x40080000 size=0x00404 (  1028) load[0m
[0;32mI (284) esp_image: segment 3: paddr=0x00066660 vaddr=0x40080404 size=0x099b8 ( 39352) load[0m
[0;32mI (310) esp_image: segment 4: paddr=0x00070020 vaddr=0x400d0020 size=0x123240 (1192512) map[0m
[0;32mI (827) esp_image: segment 5: paddr=0x00193268 vaddr=0x40089dbc size=0x12df8 ( 77304) load[0m
[0;32mI (881) boot: Loaded app from partition at offset 0x10000[0m
[0;32mI (881) boot: Disabling RNG early entropy source...[0m
[0;32mI (882) psram: This chip is ESP32-D0WD[0m
[0;32mI (886) spiram: Found 16MBit SPI RAM device[0m
[0;32mI (891) spiram: SPI RAM mode: flash 40m sram 40m[0m
[0;32mI (896) spiram: PSRAM initialized, cache is in low/high (2-core) mode.[0m
[0;32mI (903) cpu_start: Pro cpu up.[0m
[0;32mI (907) cpu_start: Application information:[0m
[0;32mI (912) cpu_start: Project name:     esp32cam-server-only[0m
[0;32mI (918) cpu_start: App version:      0.0.9.3[0m
[0;32mI (923) cpu_start: Compile time:     Dec  2 2021 21:53:54[0m
[0;32mI (929) cpu_start: ELF file SHA256:  d31ca3157c9027f1...[0m
[0;32mI (935) cpu_start: ESP-IDF:          3.40100.200827[0m
[0;32mI (940) cpu_start: Starting app cpu, entry point is 0x40081b00[0m
[0;32mI (932) cpu_start: App cpu up.[0m
[0;32mI (1397) spiram: SPI SRAM memory test OK[0m
[0;32mI (1398) heap_init: Initializing. RAM available for dynamic allocation:[0m
[0;32mI (1398) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM[0m
[0;32mI (1404) heap_init: At 3FFC2A10 len 0001D5F0 (117 KiB): DRAM[0m
[0;32mI (1411) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM[0m
[0;32mI (1417) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM[0m
[0;32mI (1424) heap_init: At 4009CBB4 len 0000344C (13 KiB): IRAM[0m
[0;32mI (1430) cpu_start: Pro cpu start user code[0m
[0;32mI (1435) spiram: Adding pool of 2048K of external SPI memory to heap allocator[0m
[0;32mI (1460) spi_flash: detected chip: generic[0m
[0;32mI (1461) spi_flash: flash io: dio[0m
[0;32mI (1461) cpu_start: Starting scheduler on PRO CPU.[0m
[0;32mI (0) cpu_start: Starting scheduler on APP CPU.[0m
[0;32mI (1469) spiram: Reserving pool of 32K of internal memory for DMA/internal allocations[0m
[0;32mI (1529) main: Using SDMMC peripheral[0m
Name: SD16G
Type: SDHC/SDXC
Speed: 20 MHz
Size: 30264MB
[0;32mI (1569) server_ota: Start CheckOTAUpdateCheck ...[0m
Start CheckOTAUpdateCheck ...
[0;32mI (1579) server_ota: SHA-256 for the partition table: : 9d4a2809ae90fb20709a8ca3dd3ac3462e1e73286bcd31b689060c91de06fa3a[0m
[0;32mI (1639) server_ota: SHA-256 for bootloader: : fcdaa822cbfd3931bcf8b49d91f2b86a98b93513bdbadb110eecd54f32d13c55[0m
[0;32mI (2279) server_ota: SHA-256 for current firmware: : c3447097e655d087ac6d2a666307dad4d95e8dd648f4870ac0521f6b4fe209aa[0m
CheckOTAUpdate Partition: ESP_OK
open file /sdcard/wlan.ini in mode r
file loaded

WLan: Flugschule, ***
Hostename: watermeter
I (2329) wifi:wifi driver task: 3ffd35cc, prio:23, stack:6656, core=0
[0;32mI (2329) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE[0m
[0;32mI (2329) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE[0m
I (2359) wifi:wifi firmware version: 3ea4c76
I (2359) wifi:config NVS flash: enabled
I (2359) wifi:config nano formating: disabled
I (2359) wifi:Init dynamic tx buffer num: 32
I (2369) wifi:Init data frame dynamic rx buffer num: 32
I (2369) wifi:Init management frame dynamic rx buffer num: 32
I (2379) wifi:Init management short buffer num: 32
I (2379) wifi:Init static tx buffer num: 16
I (2389) wifi:Init static rx buffer size: 1600
I (2389) wifi:Init static rx buffer num: 10
I (2389) wifi:Init dynamic rx buffer num: 32
[0;32mI (2489) phy: phy_version: 4180, cb3948e, Sep 12 2019, 16:39:13, 0, 0[0m
I (2489) wifi:mode : sta (44:17:93:7c:8d:b8)
[0;32mI (2499) BLINK: Blinken - start[0m
[0;32mI (2499) wifi station: wifi_init_sta finished.[0m
I (2619) wifi:new:<11,0>, old:<1,0>, ap:<255,255>, sta:<11,0>, prof:1
I (2619) wifi:state: init -> auth (b0)
I (2629) wifi:state: auth -> assoc (0)
I (2629) wifi:state: assoc -> run (10)
I (2669) wifi:connected with Flugschule, aid = 5, channel 11, BW20, bssid = dc:39:6f:c2:8c:58
I (2669) wifi:security: WPA2-PSK, phy: bgn, rssi: -68
I (2669) wifi:pm start, type: 1

I (2679) wifi:AP's beacon interval = 102400 us, DTIM period = 1
[0;32mI (2699) BLINK: Blinken - done[0m
[0;32mI (3319) esp_netif_handlers: sta ip: 192.168.178.77, mask: 255.255.255.0, gw: 192.168.178.1[0m
[0;32mI (3319) wifi station: got ip:192.168.178.77[0m
[0;32mI (3319) BLINK: Blinken - start[0m
[0;32mI (3319) wifi station: connected to ap SSID:Flugschule password:***[0m
main: sleep for : 200ms
[0;32mI (5339) sntp: Time is not set yet. Connecting to WiFi and getting time over NTP.[0m
[0;32mI (5339) sntp: Initializing SNTP[0m
[0;32mI (5339) sntp: Waiting for system time to be set... (1/10)[0m
TimeZone set to CET-1CEST,M3.5.0,M10.5.0/3
Logfile opened: /sdcard/log/message/log_2022-01-23.txt
[0;32mI (7349) sntp: The current date/time in Berlin is: Sun Jan 23 19:11:40 2022[0m
[0;32mI (7349) sntp: The current date/time in Berlin is: 2022-01-23_19:11[0m
timeist 20220123-191140
Logfile opened: /sdcard/log/message/log_2022-01-23.txt
Logfile opened: /sdcard/log/message/log_2022-01-23.txt
Logfile opened: /sdcard/log/message/log_2022-01-23.txt
time 20220123-191140
main: sleep for : 200ms
[0;32mI (9409) server-main: Starting server on port: '80'[0m
[0;32mI (9409) server-main: Registering URI handlers[0m
[0;32mI (9409) server_tflite: server_part_camera - Registering URI handlers[0m
[0;32mI (9409) server_ota: server_ota - Registering URI handlers[0m
[0;32mI (9419) server_GPIO: start GpioHandler[0m
[0;32mI (9419) server_GPIO: register GPIO Uri[0m
[0;32mI (9429) server_GPIO: server_GPIO - Registering URI handlers[0m
vor reg server main
vor dotautostart
Do Reset Camera
[0;32mI (9439) gpio: GPIO[32]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 [0m
Init Camera
[0;32mI (11449) gpio: GPIO[5]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
[0;32mI (11449) gpio: GPIO[18]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
[0;32mI (11449) gpio: GPIO[19]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
[0;32mI (11459) gpio: GPIO[21]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
[0;32mI (11469) gpio: GPIO[22]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
[0;32mI (11479) gpio: GPIO[23]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
[0;32mI (11489) gpio: GPIO[25]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
[0;32mI (11499) gpio: GPIO[34]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
[0;32mI (11509) gpio: GPIO[35]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
[0;32mI (11519) gpio: GPIO[36]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
[0;32mI (11529) gpio: GPIO[39]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
[0;32mI (11539) sccb: pin_sda 26 pin_scl 27
[0m
[0;32mI (11539) gpio: GPIO[32]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 [0m
[0;32mI (11699) camera: Detected OV2640 camera[0m
[0;32mI (11699) camera: Allocating 1 frame buffers (150 KB total)[0m
[0;32mI (11719) camera: Allocating 150 KB frame buffer in OnBoard RAM[0m
task_autodoFlow: start

open file /sdcard/config/config.ini in mode r
[MakeImage]
Start ReadParameter ([MakeImage]
)
;LogImageLocation = /log/source
WaitBeforeTakingPicture = 5
;LogfileRetentionInDays = 15
Brightness = 0
;Contrast = 0
;Saturation = 0
ImageQuality = 5
ImageSize = VGA
FixedExposure = false

[Alignment]
[0;32mI (13329) BLINK: Blinken - done[0m
Start ReadParameter ([Alignment])
InitialRotate = 179
InitialMirror = false
SearchFieldX = 20
SearchFieldY = 20
AlignmentAlgo = Default
FlipImageSize = false
/config/ref0.jpg 103 271
/config/ref1.jpg 442 142

[Digits]
Start ReadParameter ([Digits])
Model = /config/dig-s2-q-20220104.tflite
;LogImageLocation = /log/digit
;LogfileRetentionInDays = 3
ModelInputSize = 20 32
main.dig1 294 126 30 54
GetGENERAL - GENERAL main - roi dig1
main.dig2 343 126 30 54
GetGENERAL - GENERAL main - roi dig2
main.dig3 391 126 30 54
GetGENERAL - GENERAL main - roi dig3

[Analog]
Start ReadParameter ([Analog])
Model = /config/ana-s3-q-20220105.tflite
;LogImageLocation = /log/analog
;LogfileRetentionInDays = 3
ModelInputSize = 32 32
ExtendedResolution = true
main.ana1 432 230 92 92
GetGENERAL - GENERAL main - roi ana1
main.ana2 379 332 92 92
GetGENERAL - GENERAL main - roi ana2
main.ana3 283 374 92 92
GetGENERAL - GENERAL main - roi ana3
main.ana4 155 328 92 92
GetGENERAL - GENERAL main - roi ana4

[PostProcessing]
Start ReadParameter ([PostProcessing])
Anzahl NUMBERS: 1 - DIGITS: 1, ANALOG: 1
Number main, Anz DIG: 3, Anz ANA 4
main.DecimalShift = 0
PreValueUse = true
PreValueAgeStartup = 720
AllowNegativeRates = false
main.MaxRateValue = 0.05
ErrorMessage = true
CheckDigitIncreaseConsistency = false

;[MQTT]
Read Zeile Prevalue.ini: 2020-11-30_12-02-22
42.013401
TIME: 120, 10, 0, 1, 5, 5
Read: ;Uri = mqtt://IP-ADRESS:1883
Read: ;MainTopic = wasserzaehler
Read: ;ClientID = wasser
Read: ;user = USERNAME
Read: ;password = PASSWORD
Read: 
Read: ;[GPIO]
Read: ;MainTopicMQTT = wasserzaehler/GPIO
Read: ;IO0 = input disabled 10 false false 
Read: ;IO1 = input disabled 10 false false 
Read: ;IO3 = input disabled 10 false false 
Read: ;IO4 = built-in-led disabled 10 false false 
Read: ;IO12 = input-pullup disabled 10 false false 
Read: ;IO13 = input-pullup disabled 10 false false
Read: LEDType = WS2812
Read: LEDNumbers = 2
Read: LEDColor = 150 150 150 
Read: 
Read: [AutoTimer]
Start ReadParameter ([AutoTimer]
)
AutoStart = true
Intervall = 4.85

[Debug]
Start ReadParameter ([Debug])
Logfile = false
LogfileRetentionInDays = 3

[System]
Start ReadParameter ([System])
TimeZone = CET-1CEST,M3.5.0,M10.5.0/3
TimeZone set to CET-1CEST,M3.5.0,M10.5.0/3
;TimeServer = undefined
;AutoAdjustSummertime = false
;Hostname = undefined
SetupMode = true
END OF FILE
*************** Start GPIOHandler_Init *****************
[0;32mI (14099) server_GPIO: read GPIO config and init GPIO[0m
open file /sdcard/config/config.ini in mode r
[MakeImage]
;LogImageLocation = /log/source
WaitBeforeTakingPicture = 5
;LogfileRetentionInDays = 15
Brightness = 0
;Contrast = 0
;Saturation = 0
ImageQuality = 5
ImageSize = VGA
FixedExposure = false

[Alignment]
InitialRotate = 179
InitialMirror = false
SearchFieldX = 20
SearchFieldY = 20
AlignmentAlgo = Default
FlipImageSize = false
/config/ref0.jpg 103 271
/config/ref1.jpg 442 142

[Digits]
Model = /config/dig-s2-q-20220104.tflite
;LogImageLocation = /log/digit
;LogfileRetentionInDays = 3
ModelInputSize = 20 32
main.dig1 294 126 30 54
main.dig2 343 126 30 54
main.dig3 391 126 30 54

[Analog]
Model = /config/ana-s3-q-20220105.tflite
;LogImageLocation = /log/analog
;LogfileRetentionInDays = 3
ModelInputSize = 32 32
ExtendedResolution = true
main.ana1 432 230 92 92
main.ana2 379 332 92 92
main.ana3 283 374 92 92
main.ana4 155 328 92 92

[PostProcessing]
main.DecimalShift = 0
PreValueUse = true
PreValueAgeStartup = 720
AllowNegativeRates = false
main.MaxRateValue = 0.05
ErrorMessage = true
CheckDigitIncreaseConsistency = false

;[MQTT]
;Uri = mqtt://IP-ADRESS:1883
;MainTopic = wasserzaehler
;ClientID = wasser
;user = USERNAME
;password = PASSWORD

;[GPIO]
;MainTopicMQTT = wasserzaehler/GPIO
;IO0 = input disabled 10 false false 
;IO1 = input disabled 10 false false 
;IO3 = input disabled 10 false false 
;IO4 = built-in-led disabled 10 false false 
;IO12 = input-pullup disabled 10 false false 
;IO13 = input-pullup disabled 10 false false
LEDType = WS2812
LEDNumbers = 2
LEDColor = 150 150 150 

[AutoTimer]
AutoStart = true
Intervall = 4.85

[Debug]
Logfile = false
LogfileRetentionInDays = 3

[System]
TimeZone = CET-1CEST,M3.5.0,M10.5.0/3
;TimeServer = undefined
;AutoAdjustSummertime = false
;Hostname = undefined
SetupMode = true
[0;32mI (14269) server_GPIO: GPIO init comleted, handler is disabled[0m
Flashdauer: 5000
Image loaded from memory: 0, 0, 0
Guru Meditation Error: Core  0 panic'ed (LoadProhibited). Exception was unhandled.
Core 0 register dump:
PC      : 0x400ef1a8  PS      : 0x00060830  A0      : 0x8018c866  A1      : 0x3fffcfd0  
A2      : 0x00000780  A3      : 0x3ffc3bf4  A4      : 0x00000280  A5      : 0x00000780  
A6      : 0x00000001  A7      : 0x000001e0  A8      : 0x00000000  A9      : 0x3f82c168  
A10     : 0x00000000  A11     : 0x3f92ddd8  A12     : 0x00004527  A13     : 0x00000001  
A14     : 0x3ffe3428  A15     : 0x3fffcef0  SAR     : 0x0000001e  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x00000000  LBEG    : 0x4008bed5  LEND    : 0x4008bee5  LCOUNT  : 0xffffffff  

ELF file SHA256: d31ca3157c9027f1

Backtrace: 0x400ef1a5:0x3fffcfd0 0x4018c863:0x3fffd040 0x4018c8ea:0x3fffd080 0x40189d79:0x3fffd110 0x400f130a:0x3fffd1c0
