### ISSUE TITLE
Falsche werte.

### ISSUE THREAD

**Issue by Winny1904** [jomjol/AI-on-the-edge-device#595]
Hallo,
Zwischendurch werden falsche Werte abgelesen. Dann muss ich immer den richtigen Wert von Hand eintragen. 

Woran kann das liegen? 

Denn so macht eine Auswertung keinen Sinn 

Die Zahlenfelder sind alle in der richtigen Reihenfolge. Es wird unter RAW auch der richtige Wert abgelesen.

**Comment by Winny1904** [comment]
![Screenshot_20220122-084620_Edge](https://user-images.githubusercontent.com/93474265/150633435-21d02cfa-20d0-4574-b0c3-1cdbd1b4c83a.jpg)

**Comment by jomjol** [comment]
Dann deaktivere bitte die Option "CheckDigitIncreaseConsistency", diese scheint in Kombination mit falsch erkannten Werten zu dem Problem zu führen. Allerdings werden dann die Wechsel der m³ zu früh angezeigt, da die neue Ziffer sofort mit dem erkennen aktualisiert wird, auch wenn der Zeiger noch nicht über die 0 ist. 

Ansonsten würde ich empfehlen, nur den Rohwert zu nehmen und selbst die Logik zu implementieren.

**Comment by Winny1904** [comment]
Die Funktion ist bei mir deaktiviert! 

Das Problem besteht trotzdem.

Wird der Rohwert per Mittwoch übertragen?

**Comment by jomjol** [comment]
Rohwert wird per MQTT übertragen (im JSON)

**Comment by Winny1904** [comment]
![16430103839947760570896082046187](https://user-images.githubusercontent.com/93474265/150741923-eeec0326-48f2-4bc0-a020-c5d0a4aa5338.jpg)


Leider ist der Rohwert nicht im Json

**Comment by jomjol** [comment]
Welche Version verwendest du? Das sollte mit einem update besser sein:
![grafik](https://user-images.githubusercontent.com/30766535/150858473-55ff9b51-4b12-4fb4-ac5b-8614e140416f.png)

**Comment by Winny1904** [comment]
Habe ein Update gemacht. Raw wird übertragen. Werde mir das Ergebnis die Tage ansehen
