### ISSUE TITLE
Zeitsyncronisation

### ISSUE THREAD

**Issue by marthorn** [jomjol/AI-on-the-edge-device#596]
Hallo,

ist es möglich dass immer zu einer bestimmten Zeit abgelesen wird?
Als Beispiel alle 5 Min also 0 5 10 15 20 ...

also wie ein CRONJOB?

**Comment by Gukerl** [comment]
Idee: Du könntest den Timer auf 15min stellen und genau zur Minute 15 "starten".

**Comment by jomjol** [comment]
Nein, dass ist aktuell nicht möglich und auch nicht vorgesehen.
