### ISSUE TITLE
Ständige reboots

### ISSUE THREAD

**Issue by labmaster** [jomjol/AI-on-the-edge-device#597]
Bin neu mit dem ESP32Cam Board und AI-on-the-edge.
Habe jedoch folgedes Problem.

Am Schreibtisch im EG Büro mit 3A USB Steckernetzteil ( zum debuggen teils dann zusätzlich ein FTDI232 an Rx,Tx, GND dran) funktioniert das Ding.  Kann über die Weboberfläche die Konfig starten, Bilder machen (Referenz), und, und und. Über Stunden keinen Absturz.

Sobald ich den ESP32Cam dann auf den Wasserzähler im Keller montiere (selbes Netzteil, selbe Verkabelung, nur andere 230V Steckdose sowie schlechteres WLAN (Keller halt) geht das Ding in einen zyklischen Absturz,
Fährt hoch, die Weboberfläche ist kurz ansprechbar, dann wieder weg, Reboot, dann wieder von vorne)

Einziger Unterschied ist eben die WLAN Stärke.

Habe mittlerweile auf dem ESP32Cam board an die 3.3V noch einen 47uF Kerko sowie an die 5V (Eingang) einen 220uF Elko dran gemacht, nur um sicher zu sein, daß es nicht an sehr kurzen Spannungseinbrüchen liegen kann.

Ist echt doof zum debuggen, da ich im Keller keine Rechner hab um per Serial den Debug anzuschauen und im Büro läuft alles.

Hab bezüglich Software auch gerade die Rolling probiert, hat leider nichts gebracht.

Ideen ?

**Comment by Gukerl** [comment]
Servus,

https://github.com/jomjol/AI-on-the-edge-device/issues/588

LG, Andi

**Comment by Feinfinger380** [comment]
Ich glaube das es was mit dem Wifi Empfang zu tun hat, hatte in etwa das gleiche Problem.

Und zwar hattte ich einen ESP set mit Antenne bestellt, weil der Empfang im Keller auch eher mäßig ist. Danach wollte der ESP nicht mehr starten. Hab dann 4 Module probiert, alle gleich, am Schreibtisch liefen die, im Keller nicht.
Die Lösung war dann die Antenne abzuklemmen.
Seitdem laufen alle 4 wieder einwandfrei.

**Comment by labmaster** [comment]
...
> #588
> 
> LG, Andi

Servus,
das hatte ich gesehen, 
ist aber bei mir eben anders und vor allem reproduzierbar ( WLAN Stärke )

VG, Walter

**Comment by jomjol** [comment]
Das ist zwar das selbe Problem, aber der Hinweis von @labmaster hilft in der Fehlersuche.

Die Beobachtung, dass es am Schreibtisch über Stunden funktioniert und im Keller unter gleiche Bedingungen (insb. Stromversorgung) plötzlich nicht mehr, passt zu meiner Beobachtung und Hypothese:

Mit den neuen Kameratreiber in v10.2 scheint der ESP32-CAM deutlich emfpfindlicher auf Spannungsschwankungen zu reagieren. Mit einer bestimmten Wahrscheinlichkeit, ist die Kamera nach einem solchen spontanen Reboot in einem Fehlermodus, der einen Kaltstart erfordert.'
Wenn das mit Spannungsschwankungen zusammenhängt, kann ein schwächeres WLAN da durchaus einen entscheidenden Einfluss haben, da dann dort mehr Strom gezogen wird.

Mein Beobachtung bisher:
3 System laufen super stabil (viel stabiler als mit v9.x)
1 System sehr instabil mit Reboots und komplettem Hängenbleiben

Unterschiede:
* okay: 
  * externe Antenne
  * WS2812-LED Beleuchtung
  * direkte 5V Versorgung
  * externer Kondensator (47 mikroFarad)
* nicht okay: 
  * interne Antenne
  * Flash-LED
  * Spannungsversorung über ESP32CAM-MB Board
  * kein Kondensator

**Comment by Feinfinger380** [comment]
Auch interessant, wusste ich nicht.

[https://randomnerdtutorials.com/esp32-cam-connect-external-antenna/](url)

**Comment by jomjol** [comment]
@labmaster: hatte jetzt genau dasselbe Phänomen und die Ursache hatte nichts mit der WLAN-Stärke zu tun, sondern mit dem neuen Kameratreiber. Ich vermute du hast am Schreibtisch auch kein scharfes Bild, sondern halt irgendeins (zumindest bei mir war es so).  Wenn ich jetzt den Labtop mit der Kamera in den Keller trage und auf meinen Wasserzähler aufsetze, ist es reproduzierbar abgestürtzt.

Ich konnte das jetzt mit der Qualitätseinstellung für die JPEG-Komprimierung verbinden. Die ist mit "5" eher hoch eingestellt. Mit dem Wechsel des neuen Treibers, scheint der Platzbedarf in Stufe "5" gestiegen zu sein und sobald dort ein scharfes / kontrastreiches Bild des Wasserzähler aufgenommen wurde, hat es wohl zu einem Speicherüberlauf geführt.

Sobald ich die Q-Einstellung auf "12" geändert habe, war alle gut.

Ich veröffentliche gerade die v10.3, da sollte das alles berücksichtigt sein (Q-Einstellung auf 12 musst du manuell machen). Ich schließe daher jetzt mal den Issue.

**Comment by labmaster** [comment]
@jomjol 
Zum testen habe ich bei mir am Schreibtisch den Ausdruck eines Fotos vom Zähler im passenden Abstand unter den 3D gedruckten Tunnel gelegt.
Das Bild war scharf und bis auf Bewegung (Zeiger) auch dem Original sehr ähnlich.
Also in meinen Fall sollte es eigentlich nicht am Bild liegen, ich werds testen sobald ich wieder dazu komme.
Vielen Dank schon mal für deine Arbeit.
