### ISSUE TITLE
Corrected Value (PreValue) does show Raw Value

### ISSUE THREAD

**Issue by michaeljoos72** [jomjol/AI-on-the-edge-device#6]
Hi jomjol

Sometimes it happens that "Corrected Value" (=PreValue?) does still show the "Raw Value" instead the corrected one:

![image](https://user-images.githubusercontent.com/20517474/92625836-71370180-f2c9-11ea-867f-1400f225f4b7.png)

![image](https://user-images.githubusercontent.com/20517474/92625762-5ebcc800-f2c9-11ea-997c-b757655e73c0.png)

If this is the case only "Set PreValue" does help.

BR
Michael

**Comment by jomjol** [comment]
Hallo Michael,
ehrlich gesagt, hat der Parameter bei der URL /wasserzaehler.html gar keine Bedeutung mehr. Er wird über den Paramter 
`[PostProcessing]
PreValueUse = True`
gesteuert. Trotzdem sollte natürlich der richtige Wert zurück gegeben werden. Kannst du sagen, wann der Fehler auftritt? Direkt nach einem Neustart (auch implizit - siehe log.txt) oder auch so zwischendurch?

**Comment by michaeljoos72** [comment]
Ich muss mich mal achten wann das genau passiert...hatte es bisher ca. 3x

Wegen der URL: Ich müsste dann aber weiterhin eine Möglichkeit haben, um nur den aktuellen Pre-Value-Wert weiter zu verarbeiten (z.B. in openHAB). Wenn ich es richtig verstehe, gibt es momentan keine URL, die einfach den aktuell gültigen Wert ausgibt?

Wenn ich z.B. sowas habe:

![image](https://user-images.githubusercontent.com/20517474/92681808-f0aaec00-f32e-11ea-866c-9dee680e8657.png)

Dann liefert mir http://ip/wasserzaehler.html auch das im output:

![image](https://user-images.githubusercontent.com/20517474/92682079-b4c45680-f32f-11ea-9063-d2938cb632b0.png)

Und das ist schwierig zum weiterverarbeiten.

**Comment by michaeljoos72** [comment]
Etwas in dieser Form:

Raw: 0NN1N.157
Result: 0NN5.156 Rate too high.... (dass es diesen output gibt ist gut und hilfreich!)
Actual: 00010.157

Und "Actual" gibt dann einfach den aktuell gültigen Wert aus.

**Comment by jomjol** [comment]
Ich habe noch nicht genau verstanden, was du genau brauchst. Ich fasse mal zusammen, was es gibt:

Raw-Value = 0NN1N.157
- Wert der Bilderkenning mit führenden "0" und "N"
- URL: `/wasserzaehler.html?rawvalue=true`

Corrected Value = 10.157
- "N" ersetzt 
- Konistenzcheck durchgeführt (falls an)
- ggf. auch eine Fehlermeldung
- URL: `/wasserzaehler.html`

Das was du oben als "Result" hast kann es nicht geben, da keine Konsistenzprüfung möglichist, solange noch "N" vorhanden sind.
Was brauchst du noch dazwischen? Eine Art Zwischenwert, bei dem zwar die "N" ersetzt und die führenden "0" gelöscht, aber noch kein Konsistenzcheck vorhanden?

**Comment by michaeljoos72** [comment]
War vielleicht etwas kompliziert beschrieben...ich gebe es zu.

Raw-Value = 0NN1N.157

- Wert der Bilderkenning mit führenden "0" und "N"
- URL: /wasserzaehler.html?rawvalue=true

**--> Das passt**

Corrected Value = 10.157

- "N" ersetzt
- Konistenzcheck durchgeführt (falls an)
- ggf. auch eine Fehlermeldung
- URL: /wasserzaehler.html

**--> Das habe ich oben mit "Result" gemeint (Corrected Value = Result). weil es eben auch die Fehlermeldungen ausliefert
--> Wenn ich nun in openHAB eine HTML-Abfrage mit "/wasserzaehler.html" mache steht da wenn ich Pech habe eben auch "Rate too high - Returned old value ..." und das ist zumm Auswerten nicht so schön ;)**

Das könnte man natürlich schon irgendwie per Java-Script "parsen" und den richtigen Wert auslesen, wenn möglich möchte ich das aber vermeiden.

Was mir fehlt ist eine URL, die **nur den Wert ausgibt** ohne eine Fehlermeldung.

**Comment by michaeljoos72** [comment]
Noch als Ergänzung mit dem Screenshot von ganz oben:

**Raw-Value** (URL: /wasserzaehler.html?rawvalue=true): 0NNN07.948
**Corrected Value** (URL: /wasserzaehler.html): 10006.944 Rate too high - Returned old value - read value: 10007.948

Und jetzt müsste ich eine zusätzliche URL haben die in diesem Fall den Pre-Value-Wert ausgibt.

Die neue URL hat folgende Logik:
Wenn "Corrected Value" ohne Fehlermeldung dann Output = Corrected Value
Wenn "Corrected Value" mit Fehlermeldung dann Output = PreValue

**Comment by michaeljoos72** [comment]
Achsooooo :)

```
[PostProcessing]
...
ErrorMessage = False
```

Das habe ich nicht geschnallt. 

Aber vielen Dank für das Implementieren des neuen URL-Parameters. Das gibt ein wenig mehr Fexibilität. 
Ich teste und beobachte das mal.

**Comment by michaeljoos72** [comment]
Jetzt habe ich das Problem wieder, dass "Corrected Value" nicht richtig angezeigt wird:

![image](https://user-images.githubusercontent.com/20517474/92949694-cc006280-f45b-11ea-9151-32324b408302.png)

- Ein Reboot hilft in diesem Fall definitiv nicht
- Die "prevalue.ini" sieht eigentlich gut aus

"/wasserzaehler.html" liefert:

0NNN0N.295 (mit ErrorMessage = True in der config.ini)

"/wasserzaehler.html?noerror=true" liefert:

Kein Output (leere Page)

Hier noch das Log-File und die prevalue.ini (aber ich sehe nichts Verdächtiges):

[Files.zip](https://github.com/jomjol/AI-on-the-edge-device/files/5210425/Files.zip)

Das letzte PreValue wurde heute um 12:28 Uhr gesetzt, seither wird das RAW-Value angezeit.

--> Nach "Set Pre-Value" & Reboot wird wieder der richtige Wert angezeigt und "/wasserzaehler.html?noerror=true" liefert auch wieder den richtigen Wert.

**Comment by jomjol** [comment]
Habe jetzt nochmal das Handling von PreValue, insbesondere bei Neustart und Laden vom File optimiert. Schau mal, ob der Fehler noch da ist.

**Comment by michaeljoos72** [comment]
Ich habe das Problem in der aktuellsten Version leider immer noch:

![image](https://user-images.githubusercontent.com/20517474/93108738-745c3400-f6b3-11ea-9536-2fa482033869.png)

Komisch ist ja auch, dass nciht mal ein Reboot hilft, da bleibt alles unverändert. Was wird eigentlich alles verändert/gesetzt bei "Set PreValue"? Nur die prevalue.ini? Denn nur "Set PreValue" + Reboot hilft.

**Comment by jomjol** [comment]
Raw-Value wird zurück gegeben, Problem mit DecimalShift wird in anderem Issue verfolgt
