### ISSUE TITLE
Weboberfläche nicht aufrufbar

### ISSUE THREAD

**Issue by MarioSander** [jomjol/AI-on-the-edge-device#600]
Hallo zusammen.
Ich habe das Projekt mit dem Wasserzähler jetz auch in Angriff genommen.
Mit dem Flashen hat auch alles soweit geklappt, die IP zeigt es mir auch im Netzwerk an nur komm ich nicht auf die Weboberfläche, da öffnet sich nix.
was mach ich falsch?
Danke schonmal.

**Comment by jomjol** [comment]
Welche Version verwendest du? In der Version 10.x ist aktuell ein Problem, dass es sich auf einigen Systemen komplett aufhängt. Ursache unbekannt und in Untersuchung. Du kannst auf v9.x ausweichen.
Die läuft nicht ganz so stabil, aber zumindest hängt sie sich nicht komplett auf.

**Comment by MarioSander** [comment]
Danke für deine schnelle Antwort.hab die 10 er  bin jetzt schon soweit das
es übers Handy geht. Und über Firefox.aber chrome nicht.

jomjol ***@***.***> schrieb am So., 23. Jan. 2022, 20:39:

**Comment by jomjol** [comment]
Aktuell keine Aktivitäten --> schließe das mal ab - im Bedarfsfall bitte wieder melden.
