### ISSUE TITLE
Low-contrast digits recongition

### ISSUE THREAD

**Issue by pcmihnea** [jomjol/AI-on-the-edge-device#603]
Hi,

Due to physical contraints and water meter design, I am unable to obtain a higher contrast image of a watermeter with digits only display.

![image](https://user-images.githubusercontent.com/16557188/150820680-cf090e7f-7810-468c-a236-b7fca672fe7d.png)
The meter in question has red-ish digits on a white background ( [https://metra-su.cz/en/product/dry-dial-vane-wheel-single-jet-water-meter-js-02-smart](url) ). There's no easy way to mount the camera directly due to it's position inside a well and the attached  wireless module ( [https://metra-su.cz/en/product/electronic-radio-module-e-rm-30-for-residential-water-meters-apator-powogaz](url) ).

The highest readability I could obtain was with a 8x WS2812 LEDs ring ( [https://uk.pi-supply.com/products/8-led-neopixels-ring](url) ) running full green only.
The ESP32-CAM has the default OV2640 camera module. I've used yellow labels (with '-30%' markings) for maximum contrast with the dark background.

How may I improve recongition of the meter's readings?
![image](https://user-images.githubusercontent.com/16557188/150820871-42f73667-95ae-4e48-beec-ce3294df136a.png)
![image](https://user-images.githubusercontent.com/16557188/150820847-135885b9-7509-4270-ac7b-143a01989084.png)
![image](https://user-images.githubusercontent.com/16557188/150820893-a6ebb213-50df-4492-bde0-9108326ea25a.png)
![image](https://user-images.githubusercontent.com/16557188/150820913-922a2347-1e24-4506-83cb-5cb21c428cc8.png)
![image](https://user-images.githubusercontent.com/16557188/150822373-70181401-619c-447f-acd0-d520f4c487a6.png)

**Comment by jomjol** [comment]
In this case it is really difficult. You most propably would need a dedicated trained network. If you are familiar with Python and Tensorflow you can find details here: https://github.com/jomjol/neural-network-digital-counter-readout

But to be hones, I strongly recommend to get closer to the meter. I also have a system inside a metal box and used an external WLAN antenna. That works very well.

**Comment by pcmihnea** [comment]
Tried different placement and lighting - moved the camera as close as possible, replaced the LED ring with the onboard one, and trimed the lens focus. Still no luck...
![image](https://user-images.githubusercontent.com/16557188/151226117-c3a699e1-9fd6-4ad8-9e7c-741cf6545b21.png)

**Comment by jomjol** [comment]
Well it might be, that it is needed to implement your numbers in one of the next trainings rounds - for details see here: https://github.com/jomjol/AI-on-the-edge-device/wiki/ROI-Configuration
