### ISSUE TITLE
Cannot load model: FlowControll.doFlow - ClassFlowPostProcessing

### ISSUE THREAD

**Issue by buttash** [jomjol/AI-on-the-edge-device#608]
Hi
I've just installed the software and configured for the first time to read a digital meter.  I'm not getting any values detected and I'm getting the following in my logs:

```
2022-01-25T10:07:47: task_autodoFlow - next round - Round #1
2022-01-25T10:07:47: 	FlowControll.doFlow - ClassFlowMakeImage
2022-01-25T10:07:55: 	FlowControll.doFlow - ClassFlowAlignment
2022-01-25T10:08:07: 	FlowControll.doFlow - ClassFlowCNNGeneral
2022-01-25T10:08:07: Cannot load model
2022-01-25T10:08:07: 	FlowControll.doFlow - ClassFlowPostProcessing
```

I'm running master - v10.2.0 - 2022-01-14.  Looks like I've not got things configured correctly.  Can anybody lend some assistance?

Best
Martin

**Comment by jomjol** [comment]
`Canno load model` means, that the tflite file for the neural model description cannot be loaded. There can be 2 reasons:
1) the model is defined in `config.ini`: `Model = /config/dig-s2-q-20220104.tflite`
the file needs to match a file in the config folder and the file must be present
2) problem with reading from sd-card --> test another sd-card

**Comment by jomjol** [comment]
Currently no action --> closing for the moment beeing

**Comment by buttash** [comment]
Hi.  Sorry for not replying. Got everything working after downloading that file. Thanks!
