### ISSUE TITLE
digital digit not readable

### ISSUE THREAD

**Issue by blaumsass** [jomjol/AI-on-the-edge-device#609]
Hallo,

Ich verstehe es nicht...

Seit dem ich auf den die all in one Lösung umgebaut habe funktioniert es selten bei mir.

die letzte digital Stelle wird oft falsch gelesen, warum weiß ich leider nicht.
![Neue Bitmap](https://user-images.githubusercontent.com/78652311/151021247-13eb84af-3e97-493c-8261-d354b979190f.jpg)

**Comment by blaumsass** [comment]
Jetzt geht gar nix mehr keine digitale Zahl wird erkannt.
Raw Wert jetzt .564

**Comment by blaumsass** [comment]
![Screenshot_20220125-183813_Chrome](https://user-images.githubusercontent.com/78652311/151029718-b3ffb15e-87b3-4b00-90c0-dc5cfaf35992.jpg)

**Comment by jomjol** [comment]
Dann hast du ein Problem mit der SD-Karte. Das Ergebnis -1 bedeutet i.d.R., dass das neuronale Netz kein Ergebnis liefert.
Wahrscheinlichste Ursache ist, dass es das tflite-File nicht mehr lesen kann. Denn diese Ziffern sollten definit funktionieren.
SD-Karte mal formatieren und neu bespielen - vorher natürliche die Konfiguration sichern.

**Comment by blaumsass** [comment]
Probiere ich morgen aus und berichte. Welche Daten sollte ich denn sichern?
Config.ini? Welche noch? Welche Bilder?

**Comment by jomjol** [comment]
Das config Verzeichnis und die wlan.ini.

1. SD-Karte formatieren (FAT32)
2. Default-Verzeichnis vom GitHub nochmal kopieren (damit die Dateistruktur erhalten bleibt)
3. Deine Konfigurationsdaten (config-Verzeichnis und wlan.ini) kopieren.

**Comment by blaumsass** [comment]
Hallo,

danke für deine Hilfe mega!!! Ich habe erst versucht so wie du beschrieben hattest. Funktionierte aber auch nicht die -1.0 blieb. Dann habe ich nix außer der Wlan Confi übernommen und siehe da alles läuft wieder!!! Das Anfangsproblem ist auch erstmal weg. #

**Comment by jomjol** [comment]
okay - danke für die RM
