### ISSUE TITLE
Auslesefehler via MQTT

### ISSUE THREAD

**Issue by rejoe2** [jomjol/AI-on-the-edge-device#61]
Wenn die Flow-Rate zu hoch ist (hier: vermutlich wegen eines Erkennungsfehlers, evtl. ist auch das default limit recht niedrig (?)), wird anscheinend dann nichts mehr via MQTT versendet. 
(Vorläufiger) Vorschlag wäre, die im Web-Interface unter "Corrected Value" ausgegebene Fehlermeldung unter einem gesonderten Topic zu versenden (und dann ggf. zu löschen, wenn wieder alles ok ist), so dass man ohne Blick auf das Web-IF erkennen kann, ob bzw. woran es hakt.

**Comment by jomjol** [comment]
In der neuesten Version kann die Fehlermeldung in einem eigenen Topic gemeldet werden (`TopicError`)

**Comment by rejoe2** [comment]
Danke!
Noch ein Grund mehr, die rolling auszutesten...

**Comment by rejoe2** [comment]
Danke schon mal.
Hab's erst grade vollends eingerichtet, aber bei der Gelegenheit eine Frage: ist das Absicht, dass sich das nicht in der neuen WEB-Config aktivieren oder Festlegen läßt, sondern nur via Config.ini? 
Oder habe ich einen Fehler beim update der html.zip gemacht?
Bin aktuell auf "master", das scheint ja seit gestern abend identisch mit "rolling" zu sein, oder?
