### ISSUE TITLE
Image loaded from memory: 0, 0, 0 Guru Meditation Error: Core  0 panic'ed (LoadProhibited). Exception was unhandled.

### ISSUE THREAD

**Issue by Dougstar** [jomjol/AI-on-the-edge-device#612]
Hi, I got the following problem:

Rebooting...
ets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:4
load:0x3fff0034,len:7248
ho 0 tail 12 room 4
load:0x40078000,len:13856
load:0x40080400,len:4052
entry 0x40080688
[0;32mI (31) boot: ESP-IDF 3.40100.200827 2nd stage bootloader[0m
[0;32mI (31) boot: compile time 19:48:46[0m
[0;32mI (31) boot: chip revision: 3[0m
[0;32mI (34) boot_comm: chip revision: 3, min. bootloader chip revision: 0[0m
[0;32mI (42) boot.esp32: SPI Speed      : 40MHz[0m
[0;32mI (46) boot.esp32: SPI Mode       : DIO[0m
[0;32mI (51) boot.esp32: SPI Flash Size : 4MB[0m
[0;32mI (55) boot: Enabling RNG early entropy source...[0m
[0;32mI (61) boot: Partition Table:[0m
[0;32mI (64) boot: ## Label            Usage          Type ST Offset   Length[0m
[0;32mI (72) boot:  0 nvs              WiFi data        01 02 00009000 00004000[0m
[0;32mI (79) boot:  1 otadata          OTA data         01 00 0000d000 00002000[0m
[0;32mI (86) boot:  2 phy_init         RF data          01 01 0000f000 00001000[0m
[0;32mI (94) boot:  3 ota_0            OTA app          00 10 00010000 001db000[0m
[0;32mI (101) boot:  4 ota_1            OTA app          00 11 001f0000 001db000[0m
[0;32mI (109) boot: End of partition table[0m
[0;32mI (113) boot_comm: chip revision: 3, min. application chip revision: 0[0m
[0;32mI (120) esp_image: segment 0: paddr=0x00010020 vaddr=0x3f400020 size=0x488a4 (297124) map[0m
[0;32mI (258) esp_image: segment 1: paddr=0x000588cc vaddr=0x3ffb0000 size=0x05038 ( 20536) load[0m
[0;32mI (268) esp_image: segment 2: paddr=0x0005d90c vaddr=0x40080000 size=0x00404 (  1028) load[0m
[0;32mI (269) esp_image: segment 3: paddr=0x0005dd18 vaddr=0x40080404 size=0x02300 (  8960) load[0m
[0;32mI (280) esp_image: segment 4: paddr=0x00060020 vaddr=0x400d0020 size=0x145704 (1332996) map[0m
[0;32mI (862) esp_image: segment 5: paddr=0x001a572c vaddr=0x40082704 size=0x1a204 (107012) load[0m
[0;32mI (931) boot: Loaded app from partition at offset 0x10000[0m
[0;32mI (931) boot: Disabling RNG early entropy source...[0m
[0;32mI (931) psram: This chip is ESP32-D0WD[0m
[0;32mI (936) spiram: Found 16MBit SPI RAM device[0m
[0;32mI (940) spiram: SPI RAM mode: flash 40m sram 40m[0m
[0;32mI (946) spiram: PSRAM initialized, cache is in low/high (2-core) mode.[0m
[0;32mI (953) cpu_start: Pro cpu up.[0m
[0;32mI (956) cpu_start: Application information:[0m
[0;32mI (961) cpu_start: Project name:     esp32cam-server-only[0m
[0;32mI (967) cpu_start: App version:      0.0.9.3[0m
[0;32mI (972) cpu_start: Compile time:     Jun 17 2021 19:47:20[0m
[0;32mI (978) cpu_start: ELF file SHA256:  c092874117d250f6...[0m
[0;32mI (984) cpu_start: ESP-IDF:          3.40100.200827[0m
[0;32mI (990) cpu_start: Starting app cpu, entry point is 0x40081ab4[0m
[0;32mI (981) cpu_start: App cpu up.[0m
[0;32mI (1447) spiram: SPI SRAM memory test OK[0m
[0;32mI (1448) heap_init: Initializing. RAM available for dynamic allocation:[0m
[0;32mI (1448) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM[0m
[0;32mI (1454) heap_init: At 3FFC2988 len 0001D678 (117 KiB): DRAM[0m
[0;32mI (1460) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM[0m
[0;32mI (1467) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM[0m
[0;32mI (1473) heap_init: At 4009C908 len 000036F8 (13 KiB): IRAM[0m
[0;32mI (1479) cpu_start: Pro cpu start user code[0m
[0;32mI (1484) spiram: Adding pool of 2048K of external SPI memory to heap allocator[0m
[0;32mI (1509) spi_flash: detected chip: generic[0m
[0;32mI (1510) spi_flash: flash io: dio[0m
[0;32mI (1510) cpu_start: Starting scheduler on PRO CPU.[0m
[0;32mI (0) cpu_start: Starting scheduler on APP CPU.[0m
[0;32mI (1518) spiram: Reserving pool of 32K of internal memory for DMA/internal allocations[0m
Do Reset Camera
[0;32mI (1528) gpio: GPIO[32]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 [0m
Init Camera
[0;32mI (3538) gpio: GPIO[5]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
[0;32mI (3538) gpio: GPIO[18]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
[0;32mI (3538) gpio: GPIO[19]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
[0;32mI (3548) gpio: GPIO[21]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
[0;32mI (3558) gpio: GPIO[22]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
[0;32mI (3568) gpio: GPIO[23]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
[0;32mI (3578) gpio: GPIO[25]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
[0;32mI (3588) gpio: GPIO[34]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
[0;32mI (3598) gpio: GPIO[35]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
[0;32mI (3608) gpio: GPIO[36]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
[0;32mI (3618) gpio: GPIO[39]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
[0;32mI (3628) sccb: pin_sda 26 pin_scl 27
[0m
[0;32mI (3628) gpio: GPIO[32]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 [0m
[0;32mI (3778) camera: Detected OV2640 camera[0m
[0;32mI (3788) camera: Allocating 1 frame buffers (150 KB total)[0m
[0;32mI (3798) camera: Allocating 150 KB frame buffer in OnBoard RAM[0m
[0;32mI (4398) server-main: Using SDMMC peripheral[0m
Name: SA02G
Type: SDSC
Speed: 20 MHz
Size: 1898MB
[0;32mI (4438) server_ota: Start CheckOTAUpdateCheck ...[0m
Start CheckOTAUpdateCheck ...
[0;32mI (4448) server_ota: SHA-256 for the partition table: : 9d4a2809ae90fb20709a8ca3dd3ac3462e1e73286bcd31b689060c91de06fa3a[0m
[0;32mI (4508) server_ota: SHA-256 for bootloader: : 7f9c6b4ef8e66679c8782c8e72b1401f41e530fe5ada1d260fee66fe2ef28d8f[0m
[0;32mI (5188) server_ota: SHA-256 for current firmware: : 869a699ff035e37e81dc97dc1ef63ba8390f974cff54b35634f57a5c736d8fb4[0m
CheckOTAUpdate Partition: ESP_OK
file loaded

WLan: Fxxx, ****
Hostename: watermeter
I (5248) wifi:wifi driver task: 3ffd9c40, prio:23, stack:6656, core=0
[0;32mI (5248) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE[0m
[0;32mI (5248) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE[0m
I (5278) wifi:wifi firmware version: 3ea4c76
I (5278) wifi:config NVS flash: enabled
I (5278) wifi:config nano formating: disabled
I (5278) wifi:Init dynamic tx buffer num: 32
I (5288) wifi:Init data frame dynamic rx buffer num: 32
I (5288) wifi:Init management frame dynamic rx buffer num: 32
I (5298) wifi:Init management short buffer num: 32
I (5298) wifi:Init static tx buffer num: 16
I (5308) wifi:Init static rx buffer size: 1600
I (5308) wifi:Init static rx buffer num: 10
I (5308) wifi:Init dynamic rx buffer num: 32
[0;32mI (5408) phy: phy_version: 4180, cb3948e, Sep 12 2019, 16:39:13, 0, 0[0m
I (5408) wifi:mode : sta (44:17:93:7c:8d:b8)
[0;32mI (5418) BLINK: Blinken - start[0m
[0;32mI (5418) wifi station: wifi_init_sta finished.[0m
I (5538) wifi:new:<11,0>, old:<1,0>, ap:<255,255>, sta:<11,0>, prof:1
I (5538) wifi:state: init -> auth (b0)
I (5548) wifi:state: auth -> assoc (0)
I (5548) wifi:state: assoc -> run (10)
I (5588) wifi:connected with Flugschule, aid = 17, channel 11, BW20, bssid = dc:39:6f:c2:8c:58
I (5588) wifi:security: WPA2-PSK, phy: bgn, rssi: -73
I (5588) wifi:pm start, type: 1

[0;32mI (5618) BLINK: Blinken - done[0m
I (5628) wifi:AP's beacon interval = 102400 us, DTIM period = 1
[0;32mI (6228) esp_netif_handlers: sta ip: 192.168.178.77, mask: 255.255.255.0, gw: 192.168.178.1[0m
[0;32mI (6228) wifi station: got ip:192.168.178.77[0m
[0;32mI (6228) BLINK: Blinken - start[0m
[0;32mI (6228) wifi station: connected to ap SSID:Fxxx password:***r[0m
Autoflow: sleep for : 200ms
[0;32mI (8248) sntp: Time is not set yet. Connecting to WiFi and getting time over NTP.[0m
[0;32mI (8248) sntp: Initializing SNTP[0m
[0;32mI (8248) sntp: Waiting for system time to be set... (1/10)[0m
TimeZone set to CET-1CEST,M3.5.0,M10.5.0/3
Logfile opened: /sdcard/log/message/log_2022-01-26.txt
[0;32mI (10258) sntp: The current date/time in Berlin is: Wed Jan 26 23:29:24 2022[0m
[0;32mI (10258) sntp: The current date/time in Berlin is: 2022-01-26_23:29[0m
timeist 20220126-232924
Logfile opened: /sdcard/log/message/log_2022-01-26.txt
Logfile opened: /sdcard/log/message/log_2022-01-26.txt
Logfile opened: /sdcard/log/message/log_2022-01-26.txt
time 20220126-232924
Autoflow: sleep for : 200ms
[0;32mI (12378) server-main: Starting server on port: '80'[0m
[0;32mI (12378) server-main: Registering URI handlers[0m
[0;32mI (12378) server_tflite: server_part_camera - Registering URI handlers[0m
[0;32mI (12378) server_ota: server_ota - Registering URI handlers[0m
[0;32mI (12388) server_GPIO: server_GPIO - Registering URI handlers[0m
[0;32mI (12398) gpio: GPIO[12]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 [0m
[0;32mI (12408) gpio: GPIO[13]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 [0m
vor reg server main
vor dotautostart
[MakeImage]
Start ReadParameter
;LogImageLocation = /log/source
;LogfileRetentionInDays = 15
WaitBeforeTakingPicture = 5
ImageQuality = 5
ImageSize = VGA
;Brightness = -2
FixedExposure = false

[Alignment]
Start ReadParameter
InitialRotate=180
FlipImageSize = false
/config/ref0.jpg 119 273
/config/ref1.jpg 456 138
SearchFieldX = 20
SearchFieldY = 20
InitialMirror= false
AlignmentAlgo = Default

[Digits]
Start ReadParameter
aktparamgraph: [Digits]
Name Digit: 
Model = /config/dig0870s3q.tflite
;LogImageLocation = /log/digit
;LogfileRetentionInDays = 3
ModelInputSize = 20 32
digit1 306 120 37 67
digit2 355 120 37 67
digit3 404 120 37 67

[Analog]
Start ReadParameter
Model = /config/ana0700s1lq.tflite
;LogImageLocation = /log/analog
;LogfileRetentionInDays = 3
ModelInputSize = 32 32
analog1 444 225 92 92
analog2 391 329 92 92
analog3 294 369 92 92
analog4 168 326 92 92
ExtendedResolution = false

[PostProcessing]
Start ReadParameter
DecimalShift = 0
PreValueUse = true
PreValueAgeStartup = 720
AllowNegativeRates = false
MaxRateValue = 0.1
ErrorMessage = true
CheckDigitIncreaseConsistency = false

[MQTT]
2020-11-30_12-02-22
42.013401
Start ReadParameter
;Uri = mqtt://IP-ADRESS:1883
;Topic = wasserzaehler/zaehlerstand
;TopicError = wasserzaehler/error
;TopicRate = wasserzaehler/rate
;TopicTimeStamp = wasserzaehler/timestamp
;ClientID = wasser
;user = USERNAME
;password = PASSWORD

[AutoTimer]
Start ReadParameter
AutoStart = true
Intervall = 4.85

[Debug]
Start ReadParameter
Logfile = false
LogfileRetentionInDays = 3

[System]
Start ReadParameter
TimeZone = CET-1CEST,M3.5.0,M10.5.0/3
TimeZone set to CET-1CEST,M3.5.0,M10.5.0/3
;TimeServer = fritz.box
;hostname = watermeter
SetupMode = true

[Ende]Flashdauer: 5000
[0;32mI (16238) BLINK: Blinken - done[0m
Image loaded from memory: 0, 0, 0
Guru Meditation Error: Core  0 panic'ed (LoadProhibited). Exception was unhandled.
Core 0 register dump:
PC      : 0x400e67d5  PS      : 0x00060e30  A0      : 0x801819ef  A1      : 0x3fff9e80  
A2      : 0x00000780  A3      : 0x3ffc3b7c  A4      : 0x00000280  A5      : 0x00000000  
A6      : 0x00000780  A7      : 0x00000001  A8      : 0x3f82c168  A9      : 0x00000000  
A10     : 0x000001e0  A11     : 0x3fffa208  A12     : 0x000035ae  A13     : 0x00000001  
A14     : 0x3ffc347c  A15     : 0x3fff9da0  SAR     : 0x0000001e  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x00000000  LBEG    : 0x4008bc45  LEND    : 0x4008bc55  LCOUNT  : 0xffffffff  

ELF file SHA256: c092874117d250f6

Backtrace: 0x400e67d2:0x3fff9e80 0x401819ec:0x3fff9ef0 0x40181a4d:0x3fff9f30 0x4017f29b:0x3fff9fc0 0x400eccab:0x3fffa040

**Comment by friedpa** [comment]
The Problem is the line:
`Image loaded from memory: 0, 0, 0`
That would point out that the SD-Card is defect, cannot be read. Just try another SD-Card, and/or follow the several Tipps here if you try to format it again.

**Comment by jomjol** [comment]
The problem is the PSRAM. You have a device with only 2 MB (mostly delivered from cheap resellers):

![grafik](https://user-images.githubusercontent.com/30766535/151441089-b3dc5fbc-5dce-4306-a40a-72f7d0f08cd0.png)

You need minimum 32 MBit (= 4 MByte), most of them have 64 MBit, but still only 4 MByte are accesible.

Only change: buy a new device :-(
