### ISSUE TITLE
Add ESP32-CAM-mb to documentation

### ISSUE THREAD

**Issue by s0170071** [jomjol/AI-on-the-edge-device#613]
I am not sure if you are aware of this but this greatly simplifies flashing the module !
Its a ESP32-CAM-mb module that serves as base for the cam module and adds a usb programming port to it.
May be worth adding to the documentation. On ali they come as cheap as 1-2€ per piece.

![grafik](https://user-images.githubusercontent.com/33855380/151345471-8614283a-e409-4b4e-87d6-02b1639961d1.png)
![grafik](https://user-images.githubusercontent.com/33855380/151345836-b6e0fc6f-0665-4cf9-90fb-782e328d4acf.png)

https://www.ebay.de/itm/274991376108?chn=ps&mkevt=1&mkcid=28

**Comment by jomjol** [comment]
I'm using it as well. Would you be so nice to support me with the update? You write it into the docu or send me an updated version.

Thanks in advance,
  jomjol
