### ISSUE TITLE
No show value

### ISSUE THREAD

**Issue by mhorpheox** [jomjol/AI-on-the-edge-device#614]
Hi it’s very good job, but not show the value in my work 
![674F9023-B449-444D-9E1F-DBE3863474B5](https://user-images.githubusercontent.com/77242862/151392311-60fe966d-2952-4963-bf50-55fe71b86690.png)

**Comment by mhorpheox** [comment]
Update: i have downgrade the firmware at V. 10.0.2 and it’ s work! 
![Uploading C9A7DEC6-08BA-414C-A661-907CCDC3C1A0.png…]()

**Comment by jomjol** [comment]
The reason is, that due to the negative rate, there is no "valid" value.

![grafik](https://user-images.githubusercontent.com/30766535/151440766-56ffa9ae-b925-48ac-82d1-969ed5d2bbcb.png)


It will change as soon, as there is no more error.

**Comment by v12345vtm** [comment]
same here ...
worked 1 time that i saw a value...
later on : nothing
