### ISSUE TITLE
Version 10.2: Absturz komplett + Hardreset nötig

### ISSUE THREAD

**Issue by Altblechkutscher** [jomjol/AI-on-the-edge-device#616]
Hallo zusammen,

erstmal danke für die Entwicklung dieses Projekts, bin sehr angetan von der Idee und auch deren Umsetzung. 
Demletzt habe ich auf 10.2 geupdated, mit dem Effekt, dass sich mein Watermeter (was bei mir eigentlich ein Currentmeter ist ;) ) immer wieder komplett aufhängt. Typischerweise nach einem Tag ist ein harter Reboot (Stromversorgung trennen) nötig. 

Ich habe mal in die Logs gesehen, u.a. sehe ich darin soetwas:
`Image with size 0 loaded --> reboot to be done! Check that your camera module is working and connected properly.
2022-01-26T19:25:31: Reboot in 5sec`
Typischerweise gibt es etwa alle 5-6 Stunden einen Reboot.

Ich habe mal die Config.ini angehängt, evtl. liegt hier auch meinerseits ein Problem vor:

> [MakeImage]
> ;LogImageLocation = /log/source
> WaitBeforeTakingPicture = 3
> ;LogfileRetentionInDays = 15
> Brightness = 2
> ;Contrast = 0
> ;Saturation = 0
> ImageQuality = 5
> ImageSize = VGA
> FixedExposure = false
> 
> [Alignment]
> InitialRotate = 90
> InitialMirror = true
> SearchFieldX = 20
> SearchFieldY = 20
> AlignmentAlgo = fast
> FlipImageSize = false
> /config/ref0.jpg 94 106
> /config/ref1.jpg 498 253
> 
> [Digits]
> Model = /config/dig-s2-q-20220104.tflite
> ;LogImageLocation = /log/digit
> ;LogfileRetentionInDays = 3
> ModelInputSize = 20 32
> main.dig1 135 56 30 70
> main.dig2 193 56 30 70
> main.dig3 251 55 29 70
> main.dig4 307 54 30 70
> main.dig5 365 53 30 70
> main.dig6 424 54 30 70
> main.dig7_tenth 484 54 30 70
> 
> [Analog]
> Model = /config/ana-s3-q-20220105.tflite
> ;LogImageLocation = /log/analog
> ;LogfileRetentionInDays = 3
> ModelInputSize = 32 32
> 
> [PostProcessing]
> main.DecimalShift = -1
> PreValueUse = true
> PreValueAgeStartup = 720
> AllowNegativeRates = false
> main.MaxRateValue = 0.1
> main.ExtendedResolution = true
> ;main.IgnoreLeadingNaN = false
> ErrorMessage = true
> CheckDigitIncreaseConsistency = false
> 
> [MQTT]
> Uri = mqtt://192.168.2.92:1883
> MainTopic = stromzaehler
> ;ClientID = wasser
> ;user = USERNAME
> ;password = PASSWORD
> 
> ;[GPIO]
> ;IO0 = input disabled 10 false false 
> ;IO1 = input disabled 10 false false 
> ;IO3 = input disabled 10 false false 
> ;IO4 = built-in-led disabled 10 false false 
> ;IO12 = input-pullup disabled 10 false false 
> ;IO13 = input-pullup disabled 10 false false 
> LEDType = WS2812
> LEDNumbers = 2
> LEDColor = 50 50 50
> 
> [AutoTimer]
> AutoStart = true
> Intervall = 2
> 
> [Debug]
> Logfile = false
> LogfileRetentionInDays = 3
> 
> [System]
> TimeZone = CET-1CEST,M3.5.0,M10.5.0/3
> ;TimeServer = undefined
> ;AutoAdjustSummertime = false
> ;Hostname = undefined
> SetupMode = false

**Comment by friedpa** [comment]
Probiere einmal auf 9.2 zurück zu gehen. wenn das funktioniert, bist Du im Club derjenigen bei dem die neue Camera Biblothek reboots auslöst. Da hilft dann nur warten, bis @jomjol auf die alte Bibothek im Master zurück gegangen ist. Glaube aber in der Rolling ist das schon umgesetzt. Also vielleicht auch mal die letzte Rolling ausprobieren.

**Comment by Altblechkutscher** [comment]
Alles klar, bin mal auf das Rolling gegangen, mal sehen wie das so läuft. Danke für den Tipp! 
Wir haben 2 ESP Boards im Einsatz, es gibt bei der Kamera wohl unterschiede mit V2 und V3.
![grafik](https://user-images.githubusercontent.com/91900310/151546727-9f67c8a6-e6d8-44aa-baf0-e25b02fc3761.png)

**Comment by jomjol** [comment]
@Altblechkutscher: du solltest sicherheitshalber nochmal ein Update machen, ggf. ist das Bild nicht hell genug. Ich bekomme ein Kamera mit der V2 auch nicht zum laufen, ist aber jetzt auch schon seit 3 Jahren im Einsatz - vielleicht war es das dann auch. 
Heute kam eine V3, mal schauen, ob die jetzt stabiler läuft - das weiß ich morgen früh.

**Comment by jomjol** [comment]
@friedpa : bin jetzt doch erstmal bei der neuen Version geblieben. Konnte den Fehler beseitigen, indem ich den Parameter ImageQuality von 5 auf 12 geändert habe. Bei 5 ist das jpeg so detailreich, dass es anscheinend zu groß für den freien speicher wird.

**Comment by Altblechkutscher** [comment]
Hallo zusammen,
ein guter Zeitpunkt, hier mal ein Update zu geben. Wie sich rausstellen musste, handelte es sich nicht um ein Softwareproblem, sondern um ein Spannungsversorgungsproblem.

Ein Blick hierher hat Abhilfe geschaffen:
https://arduino-hannover.de/2018/07/25/die-tuecken-der-esp32-stromversorgung/
