### ISSUE TITLE
MQTT pereodic don't transfer value each 5 minutes

### ISSUE THREAD

**Issue by PETJ-DK** [jomjol/AI-on-the-edge-device#617]
Hi
First of all thanks for this super fine project.... Much appreciated.
I'm using it to measure our water consumption and transfering via MQTT to Home Assistant, for that it's working perfectly.
Now I want to use it for detecting water leakage, I have had our water tap running (only low flow) for some hours, and now i see that normally HA is receiving data approximately each 5 minutes (thats fine), but now and then it dosen't and I have seen up to 15 minutes between data received. I'm running ver 10.2.0 is there somthing I can do to make it more reliable?

**Comment by jomjol** [comment]
It does not send data, if the value cannot be detected properly, e.g. negative rate. There is not much to do about this, becauses the neural networks have a certain failure rate.
