### ISSUE TITLE
Kamera v10.2.0 wird nicht erkannt

### ISSUE THREAD

**Issue by DerDoubleD** [jomjol/AI-on-the-edge-device#618]
Hallo

mit der v10.2.0 wird die Kamera nicht erkannt und es wird ständig neu gebootet.

`
2022-01-28T10:10:55: Time zone set to CET-1CEST,M3.5.0,M10.5.0/3
2022-01-28T10:10:55: ==========================
2022-01-28T10:10:55: ======= Main Started ==========
2022-01-28T10:10:55: =========================
2022-01-28T10:11:01: Time zone set to CET-1CEST,M3.5.0,M10.5.0/3
2022-01-28T10:11:01: task_autodoFlow - next round - Round #1
2022-01-28T10:11:01: FlowControll.doFlow - ClassFlowMakeImage
2022-01-28T10:11:14: Camera is not working anymore - most propably hardware problem (instablility, ...). System will reboot.
2022-01-28T10:11:14: Reboot in 5sec
`

Ich habe dann auf die v10.1.0 zurückgeflasht und alles funktioniert wieder.

Welche Logs kann ich bereitstellen um nützliche Infos zu liefern?

**Comment by MMeinhardt1** [comment]
Am besten schaust du mal in den vorhandenen issues (auch closed) nach bezüglich v10.2.0, dort findest du fast tausendfach Infos zu dem Thema.

**Comment by jomjol** [comment]
Habe gerade eine Rolling hochgeladen, die das Problem angeht. 

JEDOCH: der neue Kameratreiber reagiert deutlich empfindlicher auf Spannungsschwankungen, insbesondere mit der internen Flash-LED. Bei meinen WS2812-LED läuft es teilweise jetzt schon tagelang ohne Reboot.

ACHTUNG beim Update muss vorher der Parameter ImageQuality von 5 auf 12 erhöht werden!

**Comment by Duese123** [comment]
Das mit der Erhöhung hatte ich auch gemerkt... Manchmal lief es mit 6 manchmal nicht. Lief manchmal stundenlang durch und manchmal Abbruch auf 12 wäre eine Möglichkeit.

**Comment by ckoeber83** [comment]
Rolling (2022-01-28)

    Bug fix: led intensity setting

Rolling (2022-01-27)

    Implemented LED flash dimming (in "Take Reference Image")

    Additional camera parameters: saturation, contrast (although not too much impact)

    Updated esp32 camera hardware driver

    ATTENTION: if the esp32 is stalled or permanently reboot try this:
        Update the parameter ImageQuality to 12 instead of the default value 5 (manually in the config.ini)


https://github.com/jomjol/AI-on-the-edge-device/tree/rolling

**Comment by DerDoubleD** [comment]
> Habe gerade eine Rolling hochgeladen, die das Problem angeht.
> 
> JEDOCH: der neue Kameratreiber reagiert deutlich empfindlicher auf Spannungsschwankungen, insbesondere mit der internen Flash-LED. Bei meinen WS2812-LED läuft es teilweise jetzt schon tagelang ohne Reboot.
> 
> ACHTUNG beim Update muss vorher der Parameter ImageQuality von 5 auf 12 erhöht werden!

Feedback zum Rolling.
Läuft bisher ohne Probleme!
Hab extra mehrmals neu gestartet, aber die Kamera wurde jedesmal zuverlässig erkannt!
Dankeschön!!!

**Comment by jomjol** [comment]
Dann schließe ich mal then Issue.
