### ISSUE TITLE
Feedback zur 10.3.0

### ISSUE THREAD

**Issue by CS-OL** [jomjol/AI-on-the-edge-device#619]
Hallo,

ich habe auf die 10.3.0 upgedatet, vorher die Camera auf 12 gestellt. Meine Erfahrungen: Einstellungen wie Contrast, Helligkeit, LED-Intensität haben auf das Erscheinungsbild eines neuen Referenzbildes keine Auswirkungen. In der Config sind Kontrast, Saturation und LEDintensität ausgegraut. Sehr häufige Reboots, Erkennung ist nicht besser geworden, heute erkennt das mit 10.2.0 und 10..3.0  statt 123 meist 128m³, also statt 3 eine 8 in der letzten Digitalstelle. Ich hatte die Firmware.bin und die html.zip geflasht. Habe ich da was falsch gemacht ? 

Grüße Christian

**Comment by jomjol** [comment]
* Contrast und Helligkeit haben in der Tat keine große Auswirkung, liegt wohl am Kamera-Treiber - vielleicht wird es mit einem zukünftige Update besser.
* LEDIntensity wird im Wesentlichen von der Autoilluminiation kompensiert. Erst sehr geringe Werte (<5) haben einen signifikanten Einfluss, da dann die automatische Belichtungseinstellung nicht mehr gegenkompensieren kann.
* Damit die Wert auch in der Configuration nicht mehr ausgeraut sind, musst du einmal das Refernzbild neu erstellen. Erst dann werden die Parameter aktiviert.

Zum Reboot:
* Ich musste jetzt nach längeren Testen auch feststellen, dass ein 4 Jahre alter ESP32CAM mit dem neuen Treiber nicht mehr funktioniert. Neue Hardware (mit OV2640 V3) in Betrieb genommen und fast alle Probleme waren weg.
* Die Version 9.2 scheint tolerante gegenüber älterer HW zu sein. Im Zweifelsfall dabei bleiben.

**Comment by CS-OL** [comment]
Hallo, 
woran erkenne ich denn, welche Version ich habe ? Ich hatte schon vor 1 1/2 Jahren einen ESP32-CAM für ein anderes Projekt, bei dem es nicht um die CAM ging, sondern mehr um die kleine Bauform, gekauft und nun die im Doppelpack von Amazon. Äußerlich sehen die identisch aus...

Grüße
Christian

**Comment by CS-OL** [comment]
Habe gerade in einigen Rezensionen bei Amazon gesehen, dass es wohl offenbar verschiedene Versionen mit verschiedenen Speichern (beworben wird wohl 4 bzw. 8MB, einige schreiben, die hätten nur 2MB) gibt. Vielleicht ist das ein Ansatz ?

**Comment by friedpa** [comment]
Das Thema verfolgt das Projekt schon seit monaten. Es werden oft ESPs mit 32MBit angeboten, welche aber dann nur weniger Speicher haben. Für dieses Projekt braucht man minimum 32 MBit = 4 MByte.

**Comment by lBulgur** [comment]
Wo gibt es denn die neue Hardware (OV2640 V3) zu kaufen?
Ich finde nur Module mit der TY-OV2640-V2.0

**Comment by CS-OL** [comment]
Wie erkenne ich denn, wieviel Speicher das Modul hat ?

**Comment by friedpa** [comment]
Wenn Du das LOG via config.ini eingeschalten hast, taucht im Fehlerfall diese Meldung im LOG auf:
![grafik](https://user-images.githubusercontent.com/42890695/151699018-163de05f-ef17-4063-9b28-b152b1923786.png)
In diesem Fall hat der ESP nur 16 MBit = 2 MByte, also zu wenig.

**Comment by CS-OL** [comment]
...ich finde im Log nur freeMem, 3085395, würde ja eher auf mehr als 2MB hinweisen oder ?

**Comment by ckoeber83** [comment]
> Wo gibt es denn die neue Hardware (OV2640 V3) zu kaufen? Ich finde nur Module mit der TY-OV2640-V2.0

Ich habe meinen ESP32-CAM-MB bei ebay gekauft https://www.ebay.de/itm/274841850465?var=575090963555

Dieser hat wohl laut Beschreibung:
- SPIFlash | Default 32Mbit
- RAM | Internal 520KB+ 8MB PSRAM

Und läuft mit der master 10.3.0

**Comment by lBulgur** [comment]
Hmmm Angaben zur Kameraversion stehen da nicht was steht denn auf der Kamera? 
Gibt es überhaupt ne OV2640 V3? bzw. wie kann ich die erkennen?

**Comment by lBulgur** [comment]
Hmmm okay hier scheint es bei mehreren modulen etwas günstiger zu sein, hoffe es klappt :)
https://de.aliexpress.com/item/1005002007073813.html?gatewayAdapt=glo2deu&spm=a2g0o.placeorder.0.0.5f3f7bd67J1bGL&mp=1

**Comment by friedpa** [comment]
@CS-OL Unter PSRAM im LOG File suchen ....

**Comment by jomjol** [comment]
@lBulgur : das Problem ist meistens nicht der ESP32 (wenn er denn die korrekten 4/8 MByte PSRAM enthält). Die kompatibilität hängt eher am Kameramodul. Die unterscheiden sich an der Beschriftung auf dem Flexband.

* Aktuell okay bei mir: "DC-26 / 40-V3"
* Probleme habe ich mit: "TY-OV2 / 604-V2.0" - kann natürlich sein, dass es einfach nur wirklich defekt ist.

**Comment by jomjol** [comment]
@CS-OL: Wenn nicht genug PSRAM verfügbar ist, steht es als Kommentar direkt auch im Log-File auf der SD-Karte mit etwa folgendem Text:
```
Not enought PSRAM available. Expected 4.194.304 MByte - available: xxxx
Either not initialzed or too small (2MByte only) or not present at all. Firmware cannot start!!
```

**Comment by CS-OL** [comment]
Hallo jomjol,
einen solchen Eintrag habe ich nicht finden können, allerdings habe ich heute auch schon 150 runs im Log, ausser, dass immer wieder die 3 als 8 erkannt wird, läuft es, wenn ich nichts am WebIF aufrufe. Gestern, wo ich viel im WebIF probiert hab, kamen ständige Freezes/Reboots. Damit liess sich nicht wirklich was an der Konfiguration oder dem Referenzbildes ändern/testen. Ich habe auch immer noch das Problem, dass Datum und Uhrzeit nicht gezogen werden, muss ich da noch was einstellen ?
Grüße Christian

**Comment by jomjol** [comment]
Wenn die Zeit nicht stimmt, dann erreicht er den Timeserver nicht. Entweder blockt ihn irgendwo dein Netzwerk oder falls du einen internen verwendet (z.B. FritzBox), dann vielleicht mal direkt die IP eintragen. Bei mir geht die Namensauflösung im internen Netzwerk auch nicht
* Funktioniert nicht: `TimeServer = fritz.box`
* Funktioniert: `TimeServer = 192.168.178.1`

**Comment by CS-OL** [comment]
super, das mit der Zeit hat sich damit erledigt, die IP der Fritzbox scheint zu klappen :-)

**Comment by jomjol** [comment]
Top - dann schließe ich den Issue mal.
