### ISSUE TITLE
Change Wlan conf

### ISSUE THREAD

**Issue by kaciker** [jomjol/AI-on-the-edge-device#620]
From the file server screen is posible to acces to all folders, but the file wlan.ini does not appears. If I force the path like / sytems i have a error because the file already exsit.
I can not acces phisically to the card to change manually. Is not posible to replace SSID and password info remotelly?

**Comment by friedpa** [comment]
No, this is not possible. For security reason you have to physically access the card and change the SSID and the Password.

**Comment by jomjol** [comment]
@friedpa : thx for explanation, that's right. Otherwise everybody could easily find SSID and Password in clear text form
