### ISSUE TITLE
Zwischen 2 Werten

### ISSUE THREAD

**Issue by githubwesseln** [jomjol/AI-on-the-edge-device#621]
Hallo,

teste gerade dieses Superprojekt, läuft auch im Prinzip.
Allerdings habe ich Probleme bei "digitalen Zwischenwerten" und "vollen Analogwerten".
Beim Wechsel von "53" auf "54" mit Stand auf der Hälfte von "3" und "4" (dauerte relativ lange) wurde immer die "58" erkannt.

![Screenshot_2022-01-28_234551](https://user-images.githubusercontent.com/61275073/151710160-51561226-a2ab-41a3-8536-66c56ec3079d.png)

![2022-01-30_175732](https://user-images.githubusercontent.com/61275073/151709590-23a7ab18-b81f-47ef-b654-e34c4ee48e5a.png)

Aktuell wird der erste Analogwert "2" nicht erkannt.
Liegt es an zu schlechter Bildqualität, oder hat der Erkennungsalgorithmus dort ein Problem ?

Kann ich den "Previous Value" per MQTT ändern ?

VG
Jochen Wiechern

**Comment by friedpa** [comment]
Die Aufnahme ist eh gut, die Ziffern sind aber geneigt, im 4er sind Reflexionen. Die Digits-Frames sollten kleiner sein und alle Frames gleich groß. Es gibt im Wiki eine genaue Dokumentation wie die Frames festgelegt werden sollen.

**Comment by jomjol** [comment]
Es gibt ein neues Trainingsfile für die digitalen Ziffern: https://github.com/jomjol/AI-on-the-edge-device/raw/rolling/firmware/dig-s1-q-20220206.tflite

Ich schließe dann auch mal den Issue. Bitte bei Bedarf weiter benutzen oder neuen Eröffnen
