### ISSUE TITLE
Power of led

### ISSUE THREAD

**Issue by LacerDomotique** [jomjol/AI-on-the-edge-device#622]
good evening,

is it possible to adjust the power of the led ? May be in expert mode, but I didn’t quite understand, is there documentation for this expert mode ?

Another thing,  German guys, can you write the title in English ? it would be easier for searches.
I learned Germain only two years a long time ago, so ....

thank you

**Comment by jomjol** [comment]
You can adjust the power of the led with the parameter LEDIntensity (from 0 to 100). You will notify a change only below 10, for lager value the automated illumination controll of the camera counteracts the decreased intensity
