### ISSUE TITLE
Value wird zu früh hochgezählt

### ISSUE THREAD

**Issue by sonneimtal** [jomjol/AI-on-the-edge-device#623]
Bei einem Wert von 510.9986 wird schon 511.9986 gewertet (da der einzer bereits gut sichtbar), somit werden alle folgenden Werte nicht übernommen da niedriger als "Previous Value"

**Comment by jomjol** [comment]
Dann musst du den Paramter "CheckDigitIncreasConsistency" im Expertenmodus aktivieren.
