### ISSUE TITLE
VGA-Bild lädt nicht, nur QVGA

### ISSUE THREAD

**Issue by Rosenwasser** [jomjol/AI-on-the-edge-device#625]
Bin von 10.3 zurück auf die Version 9.2 gewandelt aber auch hier wird ImageSize = VGA nicht geladen, nur QVGA welche für meine Zwecke etwas zu klein ist.
Beim VGA kann er die reference image und allinements wie auch die ROI setzen, einmal konfiguriert ladet er kein Bild mehr.
Gibt es hier noch Leute mit gleiches Problem? 
PS: Image Qualität steht auf 12, habe auch gesehen das er ständig rebootet.

**Comment by jomjol** [comment]
Poste mal bitte das Serial-Logfile von deinem Bootvorgang. Ich vermute, dass du keine 4MByte PSRAM hast. Denn VGA sollte bei beiden Versionen ohne Probleme funktionieren.

**Comment by Rosenwasser** [comment]
Hallo, im Anhang die logs, hoffentlich können Sie damit etwas falsch erkennen
[log_2022-01-31.txt](https://github.com/jomjol/AI-on-the-edge-device/files/7976481/log_2022-01-31.txt)
[log_2022-02-01.txt](https://github.com/jomjol/AI-on-the-edge-device/files/7976482/log_2022-02-01.txt)

**Comment by Rosenwasser** [comment]
Oh Entschuldigung, ich hoffe das beigefügte Datei die richtige ist
[serial log file.txt](https://github.com/jomjol/AI-on-the-edge-device/files/7980257/serial.log.file.txt)
.

**Comment by MMeinhardt1** [comment]
Hi @Rosenwasser,
laut deinem serial log hast du 16Mbit = 2MByte PSRAM, das ist leider zu wenig. Benötigt werden minimum 4MByte.

**Comment by jomjol** [comment]
Ja - das ist die Ursache  und erklärt auch das Verhalten. Beim v9.2 wird der PSRAM nicht geprüft und mit etwas Glück läuft QVGA dann gerade so. Ab Version v10.x verweigert die Firmware den Start, falls PSRAM nicht passt (und schreibt es auch ins log).

Ich mache den Issue dann zu.

**Comment by Rosenwasser** [comment]
Danke für diese Info !
... dann hat Mr. Ali mir leider den falschen geschickt.. ;-(

ESP32-CAM-MB

Parameter：
Use low-power dual-core 32-bit CPU, which can be used as an application processor.
The main frequency is up to 240MHz, and the computing power is up to 600 DMIPS
Built-in 520 KB SRAM, external 8MB PSRAM
Support UART/SPI/I2C/PWM/ADC/DAC and other interfaces
Support OV2640 and OV7670 cameras, built-in flash
Support picture WiFI upload
Support TF card
Support multiple sleep modes.
Embedded Lwip and FreeRTOS
Support STA/AP/STA+AP working mode
Support Smart Config/AirKiss one-click network configuration
Support secondary development

Ticket kann zu gemacht werden.

Nochmals Dank
