### ISSUE TITLE
Junping values

### ISSUE THREAD

**Issue by kaciker** [jomjol/AI-on-the-edge-device#630]
Hello.
I need a little help.
After several weeks finetuning I think that my system works, but from time to time, jump to a much higher value.
In my conf, the parameter -MaxRateValue is set to 0,4 being like this I can not understand how is posible jum from 46, to 56, 10 units
I correct the config, set prevalue, but time after, jump again, you will see in the last grafic. After start to read well, but the good data is in "raw value" not in "value"
Can you help me to understand ?

![image](https://user-images.githubusercontent.com/7668181/152209827-c9f1dd0f-d526-4da2-9be6-6872b0fabbf2.png)
![image](https://user-images.githubusercontent.com/7668181/152209903-18098cb7-385f-4c6c-94b7-66881d39ef47.png)
![image](https://user-images.githubusercontent.com/7668181/152209958-d6476147-99c8-4626-8e18-4a45165b817d.png)
![image](https://user-images.githubusercontent.com/7668181/152210520-c6b517b4-4903-4d37-9bcf-28bd4ad04656.png)

**Comment by tunip** [comment]
You can try to tune the MaxRateValue. For my Gasmeter I set it to (v10.3.0!):
MaxRateValue = 0.02

It depends your gas usage of course. I started with 0.01 and it was to low for my usage (rate to high), so I set it to 0.02 and it is fine now.

**Comment by jomjol** [comment]
If you have a setting of 0.4, that means, that the maximum usage is 0.4 m³ / minute --> after 30 minutes the maximum allowed jumg is already 12m³!

That fits to your observation.

**Comment by kaciker** [comment]
Ok, thansk to all, I will apply that
