### ISSUE TITLE
suspect IP adress in Javascript definition (config Web UI)

### ISSUE THREAD

**Issue by labmaster** [jomjol/AI-on-the-edge-device#631]
When i check the website html source of the initial (setup) WebUi ,there is a fixed IP adresse visible in the sourcecode.

`<script type="[text/javascript]()">
	var canvas = document.getElementById('canvas'),
		basepath = "http://192.168.178.22"; 
		aktstatu = 0;
`

I mean "192.168.178.22". This is not within my local network.

I guess this is somewhat hardcoded and maybe not used anymore but i guess its wrong anyway.

**Comment by jomjol** [comment]
This is not a bug, but a feature, that I need for debugging locally. It has no influence on the online version.
