### ISSUE TITLE
7 wird als 2 gelesen

### ISSUE THREAD

**Issue by msmthng** [jomjol/AI-on-the-edge-device#634]
![Screenshot_20220203_092236_com android chrome](https://user-images.githubusercontent.com/40269445/152306623-ff0d1521-86e2-496a-9103-d1f9c8b608f3.jpg)

**Comment by msmthng** [comment]
Ich habe das logging aktiviert und hoffe so alle digits hochladen zu können

**Comment by spcqike** [comment]
Es kann auf dem Bild vielleicht täuschen, aber hast du den Fokus richtig eingestellt? Die Zahlen und auch die analogen Anzeigen wirken recht....schwammig.

**Comment by msmthng** [comment]
![Screenshot_20220203_100247_com android chrome](https://user-images.githubusercontent.com/40269445/152312148-04b01e75-ff19-4e4d-b10b-5797993aca20.jpg)
Schärfer habe ich es nicht hinbekommen

**Comment by msmthng** [comment]
[Debug]
Logfile = true
LogfileRetentionInDays = 5


Die Logfolder sind trotzdem leer, reboot, wurde durchgeführt

**Comment by msmthng** [comment]
Mein Fehler, LogImageLocation gibts ja auch noch

**Comment by spcqike** [comment]
Welche Kamera und welche Auflösung (QVGA, VGA) nutzt du denn? Hast du den Fokusring, wie beschrieben, gedreht?
Es sollte schon schärfer gehen.

Meine Schärfe ist auch nicht perfekt (und das grüne Licht und die Reflektion, das werd ich noch einmal korrigieren)
![grafik](https://user-images.githubusercontent.com/50098985/152362983-f0e953fa-e082-4efe-88c6-f176f7da4e53.png)

https://github.com/jomjol/neural-network-digital-counter-readout/tree/master/ziffer_sortiert_raw
Dort siehst du alle hinterlegten Ziffern. Ich meine, deine "7" ist dabei.

**Comment by jomjol** [comment]
@msmthng  Die Qualität von deinem Bild ist echt nicht optimal. Bevor du Bilder für ein Training oder so aufnimmst, solltest du nochmal nach der Schärfe und den Settings schauen. Bitte VGA und nicht QVGA verwenden.

**Comment by msmthng** [comment]
Egal in welche Richtung ich gehe am Fokusring, schärfer bekomme ich es nicht hin.
Welche Auswirkungen hat die Imagequality, wenn ich da was anderes als 5 einstelle, dann startet das ding nicht wirklich:
2022-02-03T21:14:30: Time zone set to CET-1CEST,M3.5.0,M10.5.0/3
2022-02-03T21:14:30: =============================================================================================
2022-02-03T21:14:30: =================================== Main Started ============================================
2022-02-03T21:14:30: =============================================================================================
2022-02-03T21:15:54: Time zone set to CET-1CEST,M3.5.0,M10.5.0/3
2022-02-03T21:15:54: =============================================================================================
2022-02-03T21:15:54: =================================== Main Started ============================================
2022-02-03T21:15:54: =============================================================================================
2022-02-03T21:17:51: Time zone set to CET-1CEST,M3.5.0,M10.5.0/3
2022-02-03T21:17:51: =============================================================================================
2022-02-03T21:17:51: =================================== Main Started ============================================
2022-02-03T21:17:51: =============================================================================================
2022-02-03T21:21:13: Time zone set to CET-1CEST,M3.5.0,M10.5.0/3
2022-02-03T21:21:13: =============================================================================================
2022-02-03T21:21:13: =================================== Main Started ============================================
2022-02-03T21:21:13: =============================================================================================
2022-02-03T21:21:19: Time zone set to CET-1CEST,M3.5.0,M10.5.0/3
2022-02-03T21:21:

**Comment by jomjol** [comment]
Welchen VGA-Modus hast du eingestellt? VGA oder QVGA?

Das findest du in der config.ini

**Comment by msmthng** [comment]
Vga

**Comment by jomjol** [comment]
Dann kann es noch am PSRAM liegen (nur 2 MB statt der notwendigen 4 MB).

Um das rauszufinden kannst du einen Log von der seriellen Schnittstelle während des Bootvorgangs posten. Dann kann ich dir das sagen.

**Comment by msmthng** [comment]
![reference_image](https://user-images.githubusercontent.com/40269445/152490300-d4273851-3c5e-4792-8f87-b66196e5b7a6.jpg)
das ist ein reference image, die Kamera sollte also gut eingestellt sein.

**Comment by msmthng** [comment]
![Screenshot 2022-02-04 084517](https://user-images.githubusercontent.com/40269445/152491099-2013eb0c-4889-4778-bb12-f88567d5abb4.jpg)

**Comment by msmthng** [comment]
das ist dann das Resultat

**Comment by msmthng** [comment]
![image](https://user-images.githubusercontent.com/40269445/152491259-35059f65-74d4-476b-8d0d-6be7ef9f4325.png)
das ist das rawimage aus dem source log folder - an welchen einstellungen kann ich da drehen?

**Comment by ckoeber83** [comment]
Rechts hast du noch eine Reflektion am 0.1er Analogen Zeiger.
Scheinbar ist das Glas deines Wasserzählers auch etwas milchig?

Versuch Mal die Kamera noch weiter Ran zu bekommen, so das gerade die Zahlen welche gelesen werden sollen an den Rändern noch sichtbar sind. (Viel gefummelt)

Umso größer das Zahlenbild, umso besser die Erkennung!

War bei mir auch so am Anfang.

**Comment by barthm1** [comment]
Hatte das gleiche Problem - Wechsel auf dig1210s2q.tflite oder dig1310s3q.tflite hat geholfen

**Comment by jomjol** [comment]
Seit heute gibt es eine neue Version mit weiteren Trainingsbilder: https://github.com/jomjol/AI-on-the-edge-device/raw/rolling/firmware/dig-s1-q-20220206.tflite

Ich schließe dann auch mal diese Issue. Bitte gerne bei Bedarf einen neuen öffnen oder hier weiterschreiben. I.d.R. antworte ich auch auf geschlossene Issues.

**Comment by spcqike** [comment]
@jomjol wie kann man die Trainingsbilder aktualisieren? Einfach die Datei auf die SD packen? 

und ist es egal, welche Firmware dazu läuft? (die Firmware und der html-zip sollten ja immer passend sein. gilt das auch für die tflite?)

**Comment by jomjol** [comment]
@spcqike nein, Training findet nur offline bei mir auf meinem Rechner statt. Du kannst mir Beispielbilder gemäß der Anleitung im WIKI schicken und ich nehme die dann auf.

Für die tflite-Files ist es egal, welche Firmware läuft. An dieser Schnittstelle hat sich seit langem nichts mehr geändert.

**Comment by msmthng** [comment]
ich bin jetzt auch auf dig1310s3q.tflite umgestiegen, mit diesem file funktioniert das jetzt viel besser, nach dem update auf das neueste file hatte ich noch mehr lesefehler. seit ich auf dem alten file bin, habe ich noch kein einziges N und die ziffern wurden alle bis dato erkannt.

**Comment by spcqike** [comment]
@jomjol das war vielleicht schlecht formuliert von mir :) ich meinte, wo / wie man die neue .tflite einpflegt.

Hab gesehen, dass du da in den neuen Versionen eine Uploadmöglichkeit geschaffen hast :) Werde ich bei Gelegenheit mal aufspielen. (traue mich nur nicht, nachdem ich gelesen hab dass die Kameras bei Version 10 Probleme machen können :( ) meine 3Monate alte Cam hat V2 :D
