### ISSUE TITLE
Post Processing Digital ROIs

### ISSUE THREAD

**Issue by Mad-007** [jomjol/AI-on-the-edge-device#635]
Vielen Dank für das super Projekt - läuft bei meinem Wasserzähler schon seit einigen Monaten ohne Probleme!
Analoge und digitale ROIs werden bei meinem Wasserzähler größtenteils richtig erkannt (v9.0.0).

Nun wollte ich meinen Gaszähler (nur digitale ROIs) aufsetzen und dabei ist mir aufgefallen, dass das Post-Processing
der Werte des Öfteren Probleme bereitet. Der Raw-Value stimmt meist, der finale Wert hingegen nicht:

![image](https://user-images.githubusercontent.com/98906176/152215373-65bb05d2-4ad4-4079-b85b-ddd5593de9ce.png)

![image](https://user-images.githubusercontent.com/98906176/152337025-3e6a993a-f539-46cc-88d2-f98d8ed5a850.png)

![image](https://user-images.githubusercontent.com/98906176/152339226-3d65b78a-0040-4ef0-8049-8ea4319080f0.png)

Das Projekt läuft auf v10.3.0 mit diesen Post-Processing Einstellungen:

![image](https://user-images.githubusercontent.com/98906176/152208414-e03a09e6-83bf-4f0c-94bd-f7e94d414839.png)

Ich poll alle 5 Minuten. 
Aktuell werden bei mir ca. 40% der Werte falsch interpretiert, so dass ich schon überlege das Post-Processing nicht zu verwenden.
Sieht jemand ein ähnliches Verhalten?

**Comment by jomjol** [comment]
Erstmal danke für die super Dokumentation deines Problems. Die Lösung ist recht einfach. Bei einem rein digitalen Zähler funktioniert "ChekcDigitIncreaseConsistency" nicht gut. Am besten Abschalten, dann sollte es besser werden.

**Comment by Mad-007** [comment]
Vielen Dank für den Tipp und die schnelle Antwort!
Seit dem Abschalten von "CheckDigitIncreaseConsistency" hab ich keine fehlerhaften Werte mehr.
Meine Werte werden nun alle richtig erkannt!

Vielen Dank nochmal - Kaffee ist unterwegs...     ;-)
