### ISSUE TITLE
Change Request: Crypted WLAN Password

### ISSUE THREAD

**Issue by Gukerl** [jomjol/AI-on-the-edge-device#636]
Gibt es keine Möglichkeit, das WLAN Passwort von der SD Karte in irgendeiner Form verschlüsselt in den Speicher zu bringen, bzw., von der SD-Karte einmalig auszulesen und dann wieder verschlüsselt auf die Karte zu schreiben?
Das Passwort wird liegt im Klartext auf der Karte und wird auch im "Arduino-Serieller Monitor" in Klartext angezeigt.
Es muss ja keine Wunderwuzi-Verschlüsselung sein, nur grade soviel, dass nicht jeder, auf Ösi, "Depp", mit der Karte schwupps in's Netz kann.

LG, Andi
P.S: Ich bin kein Guru und hab "nur" rudimentäre Kenntnisse, ich hab ein wenig gegoogelt, sowas meine ich. -> https://techtutorialsx.com/2018/04/18/esp32-arduino-encryption-using-aes-128-in-ecb-mode/

**Comment by jomjol** [comment]
Die wlan.ini ist per Web-Interface nicht zugänglich. D.h. wer an dein Passwort will, muss die SD-Karte rausnehmen. Mehr Schutz ist aktuell nicht vorgesehen.

Wenn sich jemand aber dem Problem annimmt, binde ich den Code gerne ein.
