### ISSUE TITLE
Leere MQTT Werte bei fehlerhaftem einlesen

### ISSUE THREAD

**Issue by Gunter1710** [jomjol/AI-on-the-edge-device#641]
Als erstes möchte ich mich herzlich für dein gelungenes Projekt bedanken.

Zu meinem Problem. Wie alle habe ich das Problem, dass manchmal die Anzeige nicht richtig erkannt wird. Was aber für mich überhaupt kein Problem darstellt, denn 5 Minuten später hat er meisten wieder ein richtiges Ergebnis. Mein Problem ist aber, dass er trotz Einstellung **ErrorMessage=true** er mir ab und zu per MQTT einen leeren Wert sendet. Damit sind die berechneten Stunden/Tages/Monats-Werte falsch.
Besispiel:
`2022-02-04_21:06:54 MQTT2_ESP32_158 value: 105.350`
`2022-02-04_21:06:54 MQTT2_ESP32_158 statValueDay: 0.0389`
`2022-02-04_21:11:45 MQTT2_ESP32_158 value:`
`2022-02-04_21:11:45 MQTT2_ESP32_158 statValueDay: -105.3111`
`2022-02-04_21:21:27 MQTT2_ESP32_158 value: 105.350`
`2022-02-04_21:21:27 MQTT2_ESP32_158 statValueDay: 0.0389`
`2022-02-04_21:59:55 MQTT2_ESP32_158 statValueHourLast: 0.0010`
`2022-02-04_22:00:15 MQTT2_ESP32_158 value: 105.351`
`2022-02-04_22:00:15 MQTT2_ESP32_158 statValueDay: 0.0399`
`2022-02-04_22:48:45 MQTT2_ESP32_158 value: 105.358`
`2022-02-04_22:48:45 MQTT2_ESP32_158 statValueDay: 0.0469`
`2022-02-04_22:53:36 MQTT2_ESP32_158 value: 105.371`
`2022-02-04_22:53:36 MQTT2_ESP32_158 statValueDay: 0.0599`
`2022-02-04_22:58:27 MQTT2_ESP32_158 value:`
`2022-02-04_22:58:27 MQTT2_ESP32_158 statValueDay: -105.3111`
`2022-02-04_22:59:55 MQTT2_ESP32_158 statValueHourLast: -105.3500`

Das wiederum führt dazu, dass in FHEM meine Darstellung zerschossen wird
Falsch:
![image](https://user-images.githubusercontent.com/49900099/152632577-3b7d1076-79c9-463b-a94e-994f28ac1e2c.png)
 

Richtig:
![image](https://user-images.githubusercontent.com/49900099/152632589-b8b1e820-e6ed-4ea4-a194-62f8ee0065ae.png)

Hier noch ein Bild eines falschen Readings
![image](https://user-images.githubusercontent.com/49900099/152634590-892ac4bb-522d-4d84-a9de-770ffb87e6bd.png)

Ist es möglich keine leeren Werte mehr zu schicken? Das würde sehr helfen.

Gruß & Danke
Gunter1710

**Comment by jomjol** [comment]
Hallo Gunter,
welche Version verwendet du genau? Eigentlich sollte das bei MQTT genau so sein:

```
            zw = namenumber + "value"; 
            if (result.length() > 0)   
                MQTTPublish(zw, result);

```

oder machst du die Abfrage über den JSON String - da ist es anders. Dort kenne ich mich nicht aus und weiß nicht, ob ich auch partielle JSONs (ohne "value") schicken kann.

**Comment by Gunter1710** [comment]
Also ich verwende die neueste Version
![image](https://user-images.githubusercontent.com/49900099/152647814-891ce9d4-1d6b-49b1-b907-1a3ffd8e9015.png)

Ich lasse mir die Werte per MQTT schicken

**Comment by friedpa** [comment]
Es gibt auch schon 10.3.0 :o)

**Comment by Gunter1710** [comment]
> Es gibt auch schon 10.3.0 :o)

die 10.3.0 werde ich gleich mal ausprobieren.

Aber hier noch eine kleine Anmerkung zum Problem. 
Scheinbar wird bei einem Fehler nicht "" also nix sondern " " übertragen. Damit wäre `if (result.length() > 0)` also wahr 

`2022-02-05_17:32:27 MQTT2_ESP32_158 value: 105.520`
`2022-02-05_17:32:27 MQTT2_ESP32_158 raw: 00105.520`
`2022-02-05_17:42:08 MQTT2_ESP32_158 error: Neg. Rate - Read: 105.511 - Raw: 00105.511 - Pre: 105.520 `
`2022-02-05_17:42:08 MQTT2_ESP32_158 raw: 00105.511`
`2022-02-05_17:42:08 MQTT2_ESP32_158 value: `

**Comment by Gunter1710** [comment]
Habe den "Fehler" nun gefunden.
Es lag an dem JSON reading. 

Lösung unter FHEM:
In dem Gerät muss unter Attributes folgender Eintrag für readingList gelöscht werden:
<MQTT Geräte name>/main/json:.* { json2nameValue($EVENT) }
Zusätzlich muss aber auch noch Attribute autocreate hinzugefügt werden
autocreate = 0
Das verhindert, dass beim nächsten update der JSON Eintrag wieder hinzugefügt wird.

Thema kann somit geschlossen werden.
@jomjol Ich habe große Probleme Analoge Werte zwischen 0 und 4 richtig zu lesen. 

![image](https://user-images.githubusercontent.com/49900099/152670873-5774f91f-1dc6-448d-abda-3665ba85312e.png) 3.4 
![image](https://user-images.githubusercontent.com/49900099/152670926-e7fbb4a4-cde8-416b-82eb-ad11b73c51b6.png) 1.5

**Comment by jomjol** [comment]
@Gunter1710 Fehler von +/- 0.5 bei den analogen Zeigern werte ich momentan aktzeptabel. Das neuronale Netz erkennt unterschiedliche Zeigertypen, das ist der Preis dafür.
Du kannst deine Zeiger in einem eigenen speziell nur für dich trainierten Netz anlernen und damit nochmal besser werden. Aus Erfahrung heraus wird es aber nicht viel besser als +/- 0.2-0.3 sein. Da bist du auch schon eigentlich an der Auflösungsgrenze der Bildgrößen und auch der Genauigkeit der händisch gelabelten Trainingsbilder.

**Comment by Gunter1710** [comment]
Ich habe heute noch mal mit den Einstellungen rungespielt. 
Habe das Gefühl, dass mit der Reduzierung der LEDIntensity nun auch die Erkennung besser ist

![image](https://user-images.githubusercontent.com/49900099/152674651-22d826ed-1497-4ae2-adab-129720c1b6fd.png)

Noch mal Danke für alles.
Spende kommt ....
