### ISSUE TITLE
Training of my digital ROIs

### ISSUE THREAD

**Issue by Tobsen1599** [jomjol/AI-on-the-edge-device#642]
I would also like to thank you very much for your work. For the most part, it also works nearly perfect for me. From time to time, however, I still have error detections. Maybe you can help me with that. The most problems I have with the number 6, which is recognized as 8 and now and then the number 5, which is recognized as 6. Enclosed are the pictures of the collection of all digits in the zip file.

I have taped off the lower area because otherwise no image is created. I suspect that is due to overexposure, is that possible ? 

If you can help me here, I would be very grateful. 

Cheers
Toby

[Collection.zip](https://github.com/jomjol/AI-on-the-edge-device/files/8007993/Collection.zip)

Here the 6 was recognized as 8:
![raw_20220205-090451](https://user-images.githubusercontent.com/99076901/152641591-f8a285f6-405e-4690-bfb5-8f7c8f64e0d2.jpg)
![8_dig7_20220205-090451](https://user-images.githubusercontent.com/99076901/152641359-1fd3133d-a2fd-4d70-a995-824562001c51.jpg)8_dig7_20220205-090451

Different location, same problem: 
![raw_20220204-152245](https://user-images.githubusercontent.com/99076901/152641671-e7e7de7b-123e-4eca-b57e-e349533177a5.jpg)
![8_dig6_20220204-152245](https://user-images.githubusercontent.com/99076901/152641676-80dea2f1-455f-476f-b363-cde4c5a4959f.jpg)8_dig6_20220204-152245

Here the 5 was recognized as 6:
![raw_20220204-212138](https://user-images.githubusercontent.com/99076901/152641731-9b92e53c-ed46-4b13-9d90-18fbe6db9eea.jpg)
![6_dig7_20220204-212138](https://user-images.githubusercontent.com/99076901/152641740-b165074f-bdb9-4bd5-b808-187a10332759.jpg)6_dig7_20220204-212138

**Comment by jomjol** [comment]
I will put your images to the next training. But some of them do not obey the rule in https://github.com/jomjol/AI-on-the-edge-device/wiki/ROI-Configuration

for example (right border is signifinantly bigger than 20%:
![grafik](https://user-images.githubusercontent.com/30766535/152647478-bc6bf2b9-78fb-4266-b6c2-2fd485d001c5.png)

My tolerance can be seen by the rectangle (20% +/- 5%)

This I will not include into the training as I focus on well defined and clean training data

**Comment by Tobsen1599** [comment]
Grat, thanks for your quick feedback. I will optimize the ROI's again. 
Is the updated training then included in one of the next firmware's or how do I get this update ?

**Comment by friedpa** [comment]
If the Training from @jomjol is done, he will inform the community and close your post if your Samples are included. You have to copy the files on your SD Card (use the File Transfer Manager in the WebUI) and change the filenames in the config.ini. That´s it.

**Comment by jomjol** [comment]
I have uploaded a new trained version, including your fitting images from above. It is include in the newest rolling version for early adopters: https://github.com/jomjol/AI-on-the-edge-device/raw/rolling/firmware/dig-s1-q-20220206.tflite
