### ISSUE TITLE
Verbesserung der analogen Erkennung mit anderem tflite File.

### ISSUE THREAD

**Issue by littlebilly** [jomjol/AI-on-the-edge-device#644]
Hallo. ich bin vor ein paar Tagen zufällig auf dieses Projekt gestoßen und bin begeistert.
Nicht nur die Idee auch die Dokumentation ist außergewöhnlich. Nachdem ich noch eine esp32 cam herumliegen hatte 
gings an die Umsetzung. Alles kein Problem, 3D Drucker angeschmissen, esp32 cam geflasht, SD Karte bespielt und los gings.
Nach WIKI und Anleitung kalibriert und ausprobiert. Soweit so gut alles lief fast wie erwartet nur bei der analogen Erkennung
gab's häufiger Ausreißer.  Wäre für meine Anwendung kein Problem gewesen aber war unschön.
Nachdem ja im config file 2  tflite vorhanden sind habe ich von dem AI-on-the-edge-device-10.3.0 **ana-s3-q-20220105.tflite**
auf **ana0910s3_longq.tflite** umgestellt. Die Fehlerhäufigkeit war deutlich verringert. Mein Ehrgeiz war angestachelt.
Ich bin auf den Link
https://github.com/jomjol/neural-network-analog-needle-readout
gestoßen. Dort findet man weitere ana.... tflites. Nach dem Motto, probieren geht über studieren habe ich die nächste von unten nach der ana0910s3_longq.tflite --> die **ana0910s3_long.tflite** eingespielt. 
**Ergebnis:** Reduzierung der Aussetzer um ca. 100% (1 Aussetzer in 2 Tagen).
Das sieht in meinem Auswerte Log von gestern so aus.
![image](https://user-images.githubusercontent.com/23422753/152693812-6f3f9bea-280f-47eb-9695-414725a99950.png)
Ein grüner Raw Punkt der nicht auf der roten Linie sitzt würde  einen Aussetzer anzeigen.. 

Die Frage ist nun, macht es Sinn auf den o.a. Link bezüglich analog-needle-readout zu verweisen oder habe ich einfach Glück gehabt.

By the way a cup of coffee is on the way

Thanks a lot Billy

**Comment by jomjol** [comment]
Danke für die Rückmeldung und die detailierten Tests. Eigentlich kann man die tflite-files beliebig austauschen. Try and error ist hier tatsächlich kein schlechter Ansatz.
In der Rolling, die ich gerade hochgeladen habe, habe ich auch einen einfacheren Upload für die Files implementiert und eine Auswahl per Drop-Down Menue. Ich würde mal noch einen Moment warten mit genauerem Hinweis, da sich genau an der Schnittstelle viel tut.

Ich nehme deine Idee in einen Feature Request auf und schließe den Issue, damit ich den Überblick behalte.
