### ISSUE TITLE
so often  errors in the recognition of the numbers

### ISSUE THREAD

**Issue by radebold** [jomjol/AI-on-the-edge-device#645]
Hello,

I so often have errors in the recognition of the numbers.

Can someone tell me what I need to change to make it more reliable ?

Thanks a lot

![grafik](https://user-images.githubusercontent.com/25064101/152857834-1b3b947c-b846-4ff8-8b23-41ac5f7bb476.png)

**Comment by jomjol** [comment]
Why is your background so blue? There is no training set for black numbers on blue background.

I assume in reallity it is white. You need to change something on the illumination to get it white again.

**Comment by radebold** [comment]
![grafik](https://user-images.githubusercontent.com/25064101/153065476-ee2e1b91-1c0d-4225-9449-fbe30ba8ecf3.png)
I have change the contrast, but I think it will not be a problem of light blue

**Comment by jomjol** [comment]
this should work much better for the neural network recognition. I'm curious, what your output will be.

**Comment by Pat3rN0st3r** [comment]
I also have the issue that numbers will be reognized wrong, especially 0 will be recognized as 9 and 7 as 2 (In the digital values).
In the Image below, the 7 is recognized as 2. 0 is recognized right in this case.

![image](https://user-images.githubusercontent.com/21265240/153280653-d5f9bcf1-b599-4bef-b6b9-95e53bb22a1c.png)

**Comment by jomjol** [comment]
It looks like you have setup everything okay. If you have the change go closer to the surface, that will result in large images and more details.
Never the less, maybe you need an update of the tflite file. If you follow the readme you can find updates from there.
