### ISSUE TITLE
ESP32 does not update time - pool.ntp.org is reachable

### ISSUE THREAD

**Issue by FHEMbeta** [jomjol/AI-on-the-edge-device#654]
Hello,

I have some issues with my ESP32-CAM board running AI on the edge device. The ESP does not obtain the curent time. It always runs on default time in the year 1970.

The configuration of section system is the following:

`[System]
TimeZone = CET-1CEST,M3.5.0,M10.5.0/3
TimeServer = pool.ntp.org
AutoAdjustSummertime = true
;Hostname = undefined
SetupMode = false`

The server pool.ntp.org is reachable from the network of the ESP32. Multiple other D1 mini board get the correct time from pool.ntp.org and they are all in the same network.

Logging of the ESP32 device does not tell anything to get any idea what is running wrong:

`1970-01-01T01:01:25: Time zone set to CET-1CEST,M3.5.0,M10.5.0/3
1970-01-01T01:01:25: =============================================================================================
1970-01-01T01:01:25: =================================== Main Started ============================================
1970-01-01T01:01:25: =============================================================================================
1970-01-01T01:00:27: Time zone set to CET-1CEST,M3.5.0,M10.5.0/3
1970-01-01T01:00:27: =============================================================================================
1970-01-01T01:00:28: =================================== Main Started ============================================`

**Comment by friedpa** [comment]
Try to put the IP Address directly in, in some cases the DNS is not working properly.

**Comment by Gunter1710** [comment]
Use your Fritz!Box IP as TimeServer. Works fine for me

**Comment by friedpa** [comment]
Hopefully he has one :o) By the way in my case it also works in that way....

**Comment by FHEMbeta** [comment]
Thank you for the quick replies. Setting up my local router or IP 64.99.80.121 instead of the hostname of ntp.pool.org results in a correct date.

If this failure is well known, could it be corrected? I think adress resolution is some basic topic in networking and working with - local or remote IPs - is something ugly as they may change in future. I.e. you could change your local subnet. I have five networks at home for different things: trusted devices, IOT, kids, guests and so on. That means work in the future and some cause of error.

PS: Ich lebe in DE, werde aber niemals eine Fritzbox kaufen. Die kann ja nicht mal VLAN. ;-)

**Comment by jomjol** [comment]
@FHEMbeta Fehler ist zwar bekannt, aber warum die DNS-Auflösung nicht funktioniert ist nicht bekannt. Wenn du da Supporten kannst, herzliche Einladung einen Workaround zu implementieren.  :-)

**Comment by FHEMbeta** [comment]
> @FHEMbeta Fehler ist zwar bekannt, aber warum die DNS-Auflösung nicht funktioniert ist nicht bekannt. Wenn du da Supporten kannst, herzliche Einladung einen Workaround zu implementieren. :-)

Wenn ich die Zeit dazu finde, kann ich mal danach schauen. C++ ist mein täglich Brot. Nur habe ich bisher ESPs immer mit vorhandener Software bespielt und damit kaum Erfahrung.

**Comment by FHEMbeta** [comment]
Ich muss übrigens feststellen, dass das Problem wieder auftritt. Trotz Angabe der ntp IP ist mein ESP32 nun wieder im Jahr 1970.

Kann es sein, dass das kleine Board mit der Aufgabe am Rand seiner Belastungsgrenze läuft? Ich habe in der Zwischenzeit von QVGA auf VGA umgeschaltet, was eine höhere Last erzeugen dürfte.

**Comment by jomjol** [comment]
Belastungsgrenze ESP ist kein Problem, da die Zeit nur am Anfang, noch ohne weitere Aufgaben abgeglichen wird. Das wird allerdings nur für 10 Versuche gemacht. Wenn gerade da die Verbindung schlecht ist, dann wird es nicht weiter versucht.
