### ISSUE TITLE
Value anders als raw

### ISSUE THREAD

**Issue by CS-OL** [jomjol/AI-on-the-edge-device#655]
Hallo,
ich meine, das 2. schon mal hier gelesen zu haben, ich habe mit der 10.3. (direkt installiert, nicht über Update) zwei Probleme: 
1) bei den 4 digitalen sind das erste und zweite vertauscht, heisst bei dem Zählerstand 0125 wäre die Ausgabe 1025
2) das Value ist nicht gleich dem Raw, obwohl kein Fehler angezeigt wird

Grüße
Christian
![image](https://user-images.githubusercontent.com/97830140/153273387-d080e227-60af-4fb2-9276-4b58ec7132a6.png)

**Comment by jomjol** [comment]
Woran ereknne ich hier das vertausche? Im Raw Value passt es doch anscheinend?

Generel ist die Reihenfolge im ROI Setup definiert, in der Reihenfolge, wie sie im Drop-Down Menue gelistet sind. Dort kann die Reihenfolge auch verändert werden.

Um den anderen Fehler zu verstehen, benötige ich den enstprechenden Ausschnitt des Logfiles (zuerst aktivieren).

**Comment by CS-OL** [comment]
Hallo,
hier kannst du sehen, dass das vertauscht ist (ich habe die dann natürlich umgedreht, damit es in der Ausgabe stimmt
![image](https://user-images.githubusercontent.com/97830140/153280049-a66032a7-9f67-4a46-9294-3add9cc0d57e.png)
![image](https://user-images.githubusercontent.com/97830140/153280187-fec94a38-c097-4b59-8727-958bf255d05a.png)

Hier alles, was heute geloggt wurde:
[log_2022-02-09.txt](https://github.com/jomjol/AI-on-the-edge-device/files/8035806/log_2022-02-09.txt)

**Comment by jomjol** [comment]
Die Bezeichnung hat  nichts mit dem Namen zu tun, d.h. dig2 kann auch vor dig1 kommen. Die Reihenfolge im Drop-Down Menue entscheidet. Das änderst du über die folgenden Schalter verändert werden:
![grafik](https://user-images.githubusercontent.com/30766535/153281141-40ebbbc1-b1c2-4d6b-874a-c708192fcec2.png)

**Comment by jomjol** [comment]
Aus dem Logfile kann ich leider nicht erkennen, da der Fehler schon beim ersten Eintrag vorhanden war:
```
2022-02-09T00:00:10: sent publish successful in MQTTPublish, msg_id=16809, wasserzaehler/zaehlerstand/main/value, 136.1003
2022-02-09T00:00:10: sent publish successful in MQTTPublish, msg_id=28977, wasserzaehler/zaehlerstand/main/error, no error
2022-02-09T00:00:10: sent publish successful in MQTTPublish, msg_id=42492, wasserzaehler/zaehlerstand/main/rate, 0.000000
2022-02-09T00:00:10: sent publish successful in MQTTPublish, msg_id=55673, wasserzaehler/zaehlerstand/main/raw, 0126.1003
```

**Comment by CS-OL** [comment]
...dann ist Punkt 1 geklärt, wahrscheinlich habe ich dann irgendwo falsch drauf gedrückt, kein Drama.
Hier nochmal das Log von gestern
[log_2022-02-08.txt](https://github.com/jomjol/AI-on-the-edge-device/files/8035956/log_2022-02-08.txt)
Am Ende des 7.2. ist raw noch gleich value

**Comment by jomjol** [comment]
Also habe mal dein Logfile angeschaut und einen solchen Fehlablauf zusammengestellt:
```
2022-02-08T12:57:55: PostProcessing - Raw: 012N.0880 Value: 126.0880 Error: no error
2022-02-08T13:00:56: PostProcessing - Raw: 012N.9880 Value:  Error: Rate too high - Read: 126.9880 - Pre: 126.0880
2022-02-08T13:03:56: PostProcessing - Raw: 012N.9880 Value:  Error: Rate too high - Read: 126.9880 - Pre: 126.0880
2022-02-08T13:06:57: PostProcessing - Raw: 012N.9880 Value:  Error: Rate too high - Read: 126.9880 - Pre: 126.0880
2022-02-08T13:09:58: PostProcessing - Raw: 012N.9880 Value:  Error: Rate too high - Read: 126.9880 - Pre: 126.0880
2022-02-08T13:12:58: PostProcessing - Raw: 012N.9880 Value:  Error: Rate too high - Read: 126.9880 - Pre: 126.0880
2022-02-08T13:15:59: PostProcessing - Raw: 012N.9880 Value: 126.9880 Error: no error
```

Bis 12:58 alles okay, dann passiert bei 13:15 der Fehler --> nach 17 Minuten. wird eine Änderung von ca. 0.9 m³ zugelassen. Ich denke, du hast eine MaxRate von ca. 0.05 --> 50l/Minuten, dann bist du nach 17-18 Minuten bei 900 Litern und die MaxRate limitiert nicht mehr.
Hier wäre eine absolute Veränderung sinnvoll, wie es bei v9.x noch galt. Ich bin gerade dabei diese Option per Parameter wieder einzubauen. Dauert noch ein bisschen, da ich noch programmieren und testen muss.

**Comment by Mallegan** [comment]
> Hallo, ich meine, das 2. schon mal hier gelesen zu haben, ich habe mit der 10.3. (direkt installiert, nicht über Update) zwei Probleme:
> 
> 1. bei den 4 digitalen sind das erste und zweite vertauscht, heisst bei dem Zählerstand 0125 wäre die Ausgabe 1025
> 2. das Value ist nicht gleich dem Raw, obwohl kein Fehler angezeigt wird
> 
> Grüße Christian ![image](https://user-images.githubusercontent.com/97830140/153273387-d080e227-60af-4fb2-9276-4b58ec7132a6.png)

Hallo Christian,

darf ich dich bitte uns deinen Abstand von ESP32 zur Wasseruhr mitzuteilen? Dein Bild erscheint mir gestochen scharf. Was ist dein Trick und wie verhinderst du Reflexionen?

Danke

**Comment by CS-OL** [comment]
Hallo,

erstmal habe ich im zweiten Versuch (die vorherige Kamera hat das nicht so sauber ausgeleuchtet) den ESP hier bestellt:
https://www.amazon.de/gp/product/B08P1NMPLL/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1

Das sind zwei und auf der Kamera steht V3 drauf. Die Reflektionen sind dort, wo das Panzerband aufgeklebt ist, damit geht das ganze recht gut. Ich habe diese Halterung für den ESP:
https://www.thingiverse.com/thing:5167976

Damit ist der Abstand ca. 11cm, wenn ich das im CAD richtig ausgemessen habe (ich wollte den ESP jetzt nicht von der Halterung nehmen). Scharf stellen war echt tricky, erst den Klebepunkt mit dem Cuttermesser anritzen, dann mit der Zange sachte drehen bis der Klebstoff losbricht, dann immer wieder kleine Drehungen, wieder Referenzbild aufnehmen, nachstellen, bis das Optimum erreicht ist. Erschwerend kam dazu, dass der Zähler "schwitzte", damit auch das Glas etwas dunstig wurde,

Grüße Christian
