### ISSUE TITLE
Fehlerhafte Umwandlung vom Originalfoto zu Zahlen bei digitaler Wasseruhr mit teilweise massiven Zählersprüngen

### ISSUE THREAD

**Issue by FHEMbeta** [jomjol/AI-on-the-edge-device#658]
Hallo zusammen,

ich betreibe seit mehreren Tagen AI on the edge device mit einem digitalen Wasserzähler. Leider kommt es bei der Umwandlung vom Foto in die dazugehörigen Zahlen immer wieder zu Problemen. Teilweise habe ich Sprünge von mehreren m³ von einer Ablesung zur nächsten, obwohl die Erfassung alle **4,85 Minuten** läuft und die **MaxRateValue** auf **0,05** steht (ca. 250l von einer Ablesung zur nächsten möglich).

Anbei ein aktuelles Beispiel des aufgenommenen Fotos:
![raw](https://user-images.githubusercontent.com/99350853/153383563-9f322a42-2a42-422c-a35a-51be9d9dad6a.jpg)

Statt 33.828 werden 33.928 interpretiert:
![recognition](https://user-images.githubusercontent.com/99350853/153383611-6d37a347-54a4-462c-840a-19a86fd241bc.jpg)

Für mich sieht die erste Nachkommastelle sehr ähnlich zu der dritten aus. Warum hier einmal 9 und einmal 8 ermittelt wird, erschließt sich mir nicht. Diese Art der Fehlinterpretation ist noch nicht das Problem. denn die Abweichung sind nur 100l.
Problematisch ist, wenn zum Beispiel für eine Ziffer vor dem Komma eine 7 oder 9 erkannt wird, obwohl es eine 3 ist, die genauso deutlich ist wie auf dem Foto oben. Wie kann ich hier ansetzen das Problem zu identifizieren und zu beheben?

Ist das aufgenommene Foto nicht klar genug? Warum werden die recht deutlich gezeichneten Ziffern aus dem Originalfoto durch die Bearbeitung so verzerrt?

**Comment by ornea** [comment]
I have zero German language so its a big guess as to the issue and its a
long shot but I think the black shadows above the digits maybe confusing
the AI as they look like line segments.

**Comment by FHEMbeta** [comment]
> I have zero German language so its a big guess as to the issue and its a long shot but I think the black shadows above the digits maybe confusing the AI as they look like line segments.

The problem in short: The fist two digits **3** are sometimes misread as 4, 7. 9. The small numbers (828 on the pictures) are missread as 928. I can not figure out why the first **8** is read as **9** as it looks nearly identical to the second one.

Also the new values do sometimes not fit to my configuration of around 250l per minute maximum.

**Comment by jomjol** [comment]
Mache das hier mal zu. Falls du neue Ziffern hast, bitte einfach wieder posten.
