### ISSUE TITLE
Error in Post Processing

### ISSUE THREAD

**Issue by snorre-k** [jomjol/AI-on-the-edge-device#659]
Today I had a big issue in the post processing.

I am using v10.3.0 with the following settings in post processing:
```
[PostProcessing]
Aqua.DecimalShift = 0
PreValueUse = true
PreValueAgeStartup = 720
AllowNegativeRates = false
Aqua.MaxRateValue = 0.05
;Aqua.ExtendedResolution = false
;Aqua.IgnoreLeadingNaN = false
ErrorMessage = true
CheckDigitIncreaseConsistency = true
```

My digital values are just turning from 299 to 300:

![image](https://user-images.githubusercontent.com/18208930/153403069-5050841b-8bf9-4581-a2f8-1c52588aa68b.png)
Therefor the last 3 digits are recognized as N

The post processing calculated a big jump by ~1m3, calculated the wrong first analog number, as though the analog number(s) were read correct:

2022-02-10T10:10:16: PostProcessing - Raw: 00NNN.3590 Value: 299.3590 Error: no error
2022-02-10T10:15:06: PostProcessing - Raw: 00NNN.3590 Value: 299.3590 Error: no error
**2022-02-10T10:19:58: PostProcessing - Raw: 00NNN.2620 Value:  Error: Rate too high - Read: 300.2620 - Pre: 299.3590**
2022-02-10T10:24:50: PostProcessing - Raw: 00NNN.2620 Value:  Error: Rate too high - Read: 300.2620 - Pre: 299.3590
2022-02-10T10:29:41: PostProcessing - Raw: 00NNN.2620 Value:  Error: Rate too high - Read: 300.2620 - Pre: 299.3590
2022-02-10T10:34:31: PostProcessing - Raw: 00NNN.2620 Value: 300.2620 Error: no error
2022-02-10T10:39:22: PostProcessing - Raw: 00NNN.2620 Value: 300.2620 Error: no error

The log files of the analog numbers at 10:19 (properly) show: 3.1 - 6.0 - 2.0 - 0.4
![image](https://user-images.githubusercontent.com/18208930/153405232-5515870c-0103-4717-8124-b22e32034fee.png)

![image](https://user-images.githubusercontent.com/18208930/153405319-740ac339-bcf8-4082-b73d-f43a08ee5b4b.png) ![image](https://user-images.githubusercontent.com/18208930/153405350-a878329c-449b-4a8f-a757-52bde84bbcf6.png) ![image](https://user-images.githubusercontent.com/18208930/153405379-d538053f-5bca-45f3-9089-b425cbebd1b9.png) ![image](https://user-images.githubusercontent.com/18208930/153405417-cfcf8331-fbdd-49e7-baf2-55ab06a41e9d.png)

Do you have a clue, what goes wrong or if I have an error in my config?

THX
Snorre

**Comment by snorre-k** [comment]
THX for the answer.
But why does it calculate x.2620, when the reading is x.3620 - ans therefore added x+1 ?

**Comment by jomjol** [comment]
Out of the last good read value 299.3620 (=prevalue) it can replace the "N".
So
1) x.2620 --> 299.2620
2) detection of zero crossing  (x.2620 < .3620)
3) 299.2620 --> 300.2620 = new value = new prevalue
