### ISSUE TITLE
Einrichtung nicht möglich

### ISSUE THREAD

**Issue by Alex-joomla** [jomjol/AI-on-the-edge-device#660]
Dank verschiedener Hinweise bin ich nun mal bei der Einrichtung. Es lag tatsäcjhlich an einem nicht kompatiblen ESP32 Cam. Die aktuelle Rolling stürzte immer beim Abspeichern des aktuellen Referenzbildes ab, also habe ich die aktuelle Master installiert und so startet das Programm immerhin.
Leider währte die Freude nur kurz denn bei der Configuration ist schon wieder Ende Gelände. Bereits beim zweiten Bildschirm also den Alignment References stimmt wohl etwas nicht. Ich kann mit der Maus ein Rechteck ziehen, aber sobald ich im Dropdown Reference 1 auswähle, bleibt das alte Rechteck besetehen und ich kann kein neues hinzufügen. Auch beim Klick auf update Reference passiert im Prinzip nix. Unten scheint er auch Grafiken nicht zu laden. Ich habe das gleiche Verhalten auf Chrome, Firefox und Safari.

Hier ein Bild:
![Bildschirmfoto 2022-02-10 um 14 48 47](https://user-images.githubusercontent.com/32268233/153422613-75932159-d759-4b4b-88d3-a2e781306df8.png)

Im Pfad Feld hatte ich auch schon einen einfachen Namen eingegeben, kein Unterschied. Im nächsten Fenster funktioniert dann auch nichts so wie es soll, aber könnte auch ein Folgefehler sein. Hier kann ich keine Zahlen definieren sondern bekomme immer den Fehler:
![Bildschirmfoto 2022-02-10 um 14 49 17](https://user-images.githubusercontent.com/32268233/153422868-a37f9e54-309b-4186-b048-dac2f3acb275.png)

Hat einer ne Idee :-)

Grüße und schönen Mittag

**Comment by jomjol** [comment]
Welchen Browser verwendest du? Es funktioniert gut mit Firefox und eigentlich auch mit Chrome.

P.S.: deine Referenzstruktur (großer roter Balken) ist sehr ungünstig, da sich der untere Teil sich ja dauernd ändert, wenn die Ziffern weiterdrehen.

**Comment by jomjol** [comment]
Das Problem kenne ich so noch nicht. Daher vermute ich, dass es an deinem Settup liegt. Eventuell eine defekte Dateistruktur auf der SD-Karte?

**Comment by Alex-joomla** [comment]
Ou man, es ist echt zum heulen. Also mittlerweile habe ich den 5. ESP32 :-) Ich habe nun den, den @ckoeber83 empfohlen hatte. Ich habe gefühlt 200x alles neu geflasht und die Ordner auf die SD Karte gezogen. 
Der Start funktioniert, das Referenzbild wird normal aufgenommen. Dann bei der nächsten Seite das Gleiche Verhalten wie oben beschrieben (das war ein anderer ESP32), also an der Hardware sollte es nun wirklich nicht liegen.
Hier ein Bild von der Folgeseite. Nun baut sich nichtmal mehr das Referenzfoto auf. Was bei anderen Anläufen der Fall war. Was aber immer gefehlt hat waren die kleinen Beispielbilder unten. 
![Bildschirmfoto 2022-02-11 um 09 10 54](https://user-images.githubusercontent.com/32268233/153557616-7059db84-6753-4a73-a667-baa7fa191aed.png)

Hier der Log:
[https://pastebin.com/LRehc283](url)

Die SD Karte ist in Ordnung würde ich mal sagen...

**Comment by Gunter1710** [comment]
Ich würde als erstes die SD Karte tauschen. Möglichst 4GB oder 8GB. 
Zum anderen; hast du die Kamera mal in der Nähe deines WLAN Routers ausprobiert. Meine Wasseruhr ist in der Garage im Keller hinter dem Auto. Auch ich habe manchmal "Hänger" und das Bild wird nicht richtig aufgebaut. Das liegt aber definitiv an der instabilen WLAN Verbindung und wenn @jomjol denn RSSI wert noch in die nächste Version einbindet, kann man diese auch messen ;-)

**Comment by Alex-joomla** [comment]
Danke für eure Hinweise, es läuft jetzt nach unzähligen Versuchen obwohl ich nix anders gemacht hab. Kann also geschlossen werden. Aber die Erkennung funktioniert leider trotzdem nicht. Sollte ich näher ran?
![Bildschirmfoto 2022-02-11 um 13 21 18](https://user-images.githubusercontent.com/32268233/153590809-1d8fec5a-7422-4343-a7c5-4cbf4df11007.png)

**Comment by Gunter1710** [comment]
Um die Reflektionen in den Griff zu bekommen, habe ich bei mir einen schwarzen Karton mit Tesa auf das Glas geklebt. Damit sind die starken Reflektionen schon mal weg. Den Analogen Zeiger würde ich völlig weg lassen.

**Comment by Alex-joomla** [comment]
Danke für die Tipps, habe jetzt eigentlich wirklich ein super Bild, aber immernoch eine grottige Erkennung. Wird das besser mit der Zeit oder soll ich die Ziffern zum Training einreichen?
<img width="772" alt="Bildschirmfoto 2022-02-11 um 21 01 31" src="https://user-images.githubusercontent.com/32268233/153662196-02e42644-a883-4412-9b4a-e9b3bfd547f8.png">
<img width="1060" alt="Bildschirmfoto 2022-02-11 um 21 01 12" src="https://user-images.githubusercontent.com/32268233/153662208-d7936587-9bc2-442f-907b-78a0e22f46b1.png">

**Comment by jomjol** [comment]
Das wird von selbst nicht besser --> du solltest die Ziffern zu Training sammeln.
Bitte aber voher unbedingt nach dieser Anleitung einrichten: https://github.com/jomjol/AI-on-the-edge-device/wiki/ROI-Configuration

Das scheint mir noch nicht der Fall, da dann eigentlich alle ROIs gleich groß sein sollten. Die letzte halb verdeckte Ziffer mit dem Zeiger im unternen Bild wird nicht funktionieren. Die solltest du gleich weg lassen.

**Comment by ckoeber83** [comment]
Nimm als Digits Model mal: "`/config/dig1330s1q.tflite`"
Und deaktiviere "`CheckDigitIncreaseConsistency`" im Config Expert Mode:

![grafik](https://user-images.githubusercontent.com/52466072/153666454-38d6442d-b95f-4d1a-97f0-a47839de9ada.png)

Dann PreValue auf aktuellen Wert setzen und beobachten...

Zudem kannst du ab der [v10.3.0](https://github.com/jomjol/AI-on-the-edge-device/archive/refs/heads/master.zip) jetzt die LED Intensität, Helligkeit, Kontrast und Sättigung einstellen.
Ich würde auf alle Fälle den Blitz veringern (LEDIntensity = 3), die Helligkeit veringern (Brightness = -2), den Kontrast und die Sättigung erhöhen (Contrast + Saturation =2):

![grafik](https://user-images.githubusercontent.com/52466072/153667033-2e49d6c5-19c6-4499-920d-71cb534590c0.png)

So läuft das bei mir aktuell recht zuverlässig:

![grafik](https://user-images.githubusercontent.com/52466072/153667561-80376330-e414-4d56-9afd-81c4021513f0.png)

**Comment by Alex-joomla** [comment]
Danke @jomjol und @ckoeber83 für eure Tipps! Hab ich alle mal umgesetzt. Aber beim Alignment ist es so dass im Zählwerk die zweite und dritte Ziffer etwas tiefer stehen, also muss ich die unterschiedlich Hoch ansetzen sonst schneide ich ja eine der Ziffern ab wenn ich den Rahmen eng setze.
Bei der letzten Ziffer meinst du, keine Chance? Das könnte das Programm ja theoretisch erkennen können wenn sie weiter oben durchläuft, weil sie passt ja komplett rein in ein Erfassungsfenster?  
Jetzt macht das Ding aber gerade wieder was stranges:
Im Referenzfotobereich passt alles, Rotation bei 0°, im Edit Digit Bereich passt alles, im Übersichtsfoto stimmt allerdings garnix, da ist das Bild komplett schräg und die Rahmen passen garnicht:
<img width="1015" alt="Bildschirmfoto 2022-02-12 um 08 17 39" src="https://user-images.githubusercontent.com/32268233/153701590-a96d681b-026e-4bb7-a17f-8ec4d6079107.png">
<img width="833" alt="Bildschirmfoto 2022-02-12 um 08 16 21" src="https://user-images.githubusercontent.com/32268233/153701592-e07251d5-c8ea-412b-bfa8-ec3e4a160e26.png">
<img width="737" alt="Bildschirmfoto 2022-02-12 um 08 12 20" src="https://user-images.githubusercontent.com/32268233/153701595-18c78e50-90e1-4b09-979a-cc71651222c2.png">

**Comment by jomjol** [comment]
Dein Bild ist schräg weil die Alignmentmarke nicht erkannt wird. Der Kontrast von ALTAIR ist einfach zu schwach und es ist auch besser, etwas kleineres markanteres zu nehmen. Eventuell kannst du dort einfach etwas auf die Oberfläche kleben.
Die letzte Ziffer kannst du gerne probieren. Ins Teachen werde ich sie aber nicht aufnehmen.

Viel Erfolg!

**Comment by Alex-joomla** [comment]
Danke, war ein Super Tipp, auch der von @Gunter1710. Hab alles abgeklebt und jetzt ein einigermaßen vernünftiges Bild. Den analogen Zeiger kann ich denke ich vergessen. Jetzt habe ich ausnahmsweise mal eine korrekte Erkennung im RAW Feld, aber nicht bei Value. Irgendwie kann sich das Programm nicht dazu durchringen mal einen Wert auszugeben. An was liegt das?

Grüße

**Comment by jomjol** [comment]
Er hat noch einen "schlechten" alten Wert im PreValue --> den musst du nochmal resetten.

**Comment by jomjol** [comment]
Aktuell keine Aktivitäten --> schließe den Issue daher.

**Comment by Alex-joomla** [comment]
Ich habe hier noch die Trainingsdaten @jomjol . Dann bin ich mal gespannt :-
[numbers.zip](https://github.com/jomjol/AI-on-the-edge-device/files/8102477/numbers.zip)
)

**Comment by Alex-joomla** [comment]
Hi @jomjol darf ich dich mal fragen ob du die Bilder schon eingelernt hast?

Schöne Grüße

**Comment by jomjol** [comment]
@Alex-joomla,

entschuldige, dass ich mich länger nicht gemeldet habe. Sie sind traininert, aber ich habe keine Zeit zum Testen, aber das kannst du ja übernehmen:
[dig-20220224.zip](https://github.com/jomjol/AI-on-the-edge-device/files/8238070/dig-20220224.zip)

Da sind zwei verschiedene Files drin - ein größeres und ein kleineres, einfach mal testen.

Beste Grüße,
  jomjol

**Comment by DeLe177** [comment]
Hi,
ich möchte dieses Thema noch mal aufwärmen, da ich das gleiche Problem habe, wie es @Alex-joomla hatte: ich kann die Referenzpunkte nicht setzen. Sie werden zwar vermeindlich gespeichert aber beim nächsten Laden werden sie erneut nicht angezeigt. Im Ordner /config/ gibt es keine ref0 oder 1.jpg.
![image](https://user-images.githubusercontent.com/123316233/213926313-3c6e7891-43e4-405a-adea-9d333d020530.png)
Alex hatte keine richtige Lösung dafür gefunden, aber lt. seiner Beschreibung funktionierte es irgendwann. Das hilft mir nicht recht weiter...
Ich habe schon verschiedene SD Karten probiert; Ich habe die 13.0.8 und 13.0.6 getestet; zwei unterschiedliche ESPs: immer das gleiche Problem.
(Mir ist aufgefallen, dass die Info Seite keine Daten zu Build Info/Host Info usw anzeigt. 
Unter der Seite "Configuration"  kann ich keine Model für Digits oder Analog auswählen, das drop down ist leer...was ebenfalls seltsam ist.)
Ich habe das Logging auf "Debug" Level angehoben, aber scheinbar kommen keine Ausgaben von diesem Level durch.

Hat jemand einen Hinweis woran das liegen kann?
VG

**Comment by DeLe177** [comment]
update: 
ich bin auf diese Diskussion gestoßen: https://github.com/jomjol/AI-on-the-edge-device/discussions/1496
nachdem ich den ESP über den WEBInstaller programmiert habe, sind die beschriebenen Probleme gelöst.
Seltsam ist es, dass die bin Dateien aus dem Release bei mir nicht funktionieren: initial_esp32_setup__13.0.8.zip.
Ich habe vorher das esp tool verwendet: 
$ ./esptool-v4.4-win64/esptool.exe --port COM8 write_flash 0x01000 ./initial_esp32_setup__13.0.8/bootloader.bin 0x08000 ./initial_esp32_setup__13.0.8/partitions.bin 0x10000 ./initial_esp32_setup__13.0.8/firmware.bin

Kann jemand sagen wo der Unterschied zum Webinstaller liegt?
