### ISSUE TITLE
Hostname wrong response

### ISSUE THREAD

**Issue by skaa** [jomjol/AI-on-the-edge-device#661]
I'm using version "master - v10.2.0 - 2022-01-14", browser Firefox 96.0.2.
Sometimes (very rarely) device sends wrong response on `/version?type=Hostname` request.
On image: Заголовки - HTTP headers
![esp32cam1](https://user-images.githubusercontent.com/494532/153534360-f09ef8da-a421-42d6-8be1-e5483678da5c.png)
Ответ - Response
![esp32cam2](https://user-images.githubusercontent.com/494532/153534361-7196a91c-188a-4607-b28e-ca38a52adb86.png)

`"watermeter";hostname is optional` is my bad config for hostname, maybe this is the reason for wrong answer.
So my browser perceives the entire response (including headers) as response content.

**Comment by skaa** [comment]
Oh. I see there is new version 10.3.0. I will check this case on the new version.

**Comment by jomjol** [comment]
No furhter actions --> closing for the time beeing
