### ISSUE TITLE
Ziffern bitte mit in das Traning aufnehmen!

### ISSUE THREAD

**Issue by ThiloAm** [jomjol/AI-on-the-edge-device#663]
@jomjol kannst du die beigefügten Ziffern bitte mit Aufnehmen.
1 und 2 werden überhaupt nicht erkannt. Bei allen anderen kommt es immer wieder zu Fehlern.

Danke für das tolle Projekt!
[digit.zip](https://github.com/jomjol/AI-on-the-edge-device/files/8049786/digit.zip)

**Comment by jomjol** [comment]
Hi, hier findest du die neuesten tflite-files: das digitale enthält auch deine Bilder: https://github.com/jomjol/AI-on-the-edge-device/tree/master/firmware
