### ISSUE TITLE
v10.4.0 Auswahl von *.tflite für Digits falsch vorbelegt 

### ISSUE THREAD

**Issue by Nobbynews** [jomjol/AI-on-the-edge-device#664]
Guten Morgen,

nach OTA-Update auf die Version 10.4.0 war bei mir als Vorbelegung beim tflite-File der Digitalanzeige die Datei für die Analog-Anzeige ana-s3-q-20220105.tflite ausgewählt. Daher funktionierte die Digitalisierung der digits nicht.
Nach Ändern auf das File dig-s2-q-20220211.tflite klappte alles wieder.

Nobbynews

**Comment by Gunter1710** [comment]
Kann ich nicht bestätigen, bei beiden ESP-CAM's waren das tflite-File auf dig-s2-q-20220211.tflite gestellt.
Bei mir war aber ein andere Wert in der Config.ini verstellt. Kann mich aber nicht mehr erinnern welcher das war.

**Comment by jomjol** [comment]
@Nobbynews : habe schnell einen leeren ESP32CAM komplett neu aufgesetzt (Firmware, SD-Karte) und bei mir ist alles, wie es sein sollte:
![grafik](https://user-images.githubusercontent.com/30766535/153746619-0ee01547-4c28-4119-a87a-c2848195b67e.png)

Bitte um Infos, wie du vorgegangen bist, um den Fehler zu haben.

**Comment by Nobbynews** [comment]
Ich habe über OTA Firmware und HTML.ZIP hochgeladen und entsprechend geflahsed bzw.  das Update ausgeführt.
Anschließend habe ich noch die neue Datei dig-s2-q-20220211.tflite hochgeladen. Die vorhandene Datei dig_s2-q-20220104.tflite habe ich nicht gelöscht.
Nach dem Neustart hat es ewig gedauert, bis eine vernünftige Reaktion des ESP32 zurückkam, habe ich zu Versuchszwecken die Datei dig-s2-q-20220104.tflite gelöscht. Es kann natürlich sein, dass erst danach die falsche Datei ausgewählt wurde.
Nach dem Abschluß des Alignment warden die Digists mit grünen Ellipsen markiert, analog zu den runden Analoganteigen.
Dazu habe ich mir erst einmal nichts gedacht. Da aber die Ergebnisse jenseits von gut und böse waren, habe ich angefangen die config durchzuschauen. Dabei ist mir dass die faslche Zuordnung der *.tflite aufgefallen. Nach Auswahl der dig-s2*.* war wieder alles gut.

**Comment by jomjol** [comment]
Okay danke -verstehe. Das Löschen der Datei ist das Problem. Dadurch wird natürlich nicht die Config.ini geändert. 
Wenn er jetzt auf der Konfigurationsseite im Text etwas findet, was es als Datei gar nicht mehr gibt, dann nimmt er vermutlich das erste aus der Liste. 
Eigenlich sollte man:
1) erste neue tflite hochladen
2) ändern in der Konfiguration
3) und dann erst die alte Datei löschen (wenn überhaupt!)

Ich werde bei Gelegenheit einen Abfang (Fehlermeldung) in der Konfiguration einbauen.
