### ISSUE TITLE
Probleme mit GPIO12

### ISSUE THREAD

**Issue by Gunter1710** [jomjol/AI-on-the-edge-device#665]
Hallo,

meine zweite ESP32-CAM habe ich vor den Gaszähler gehängt. Bis dato habe ich den Gaszähler mit einem Wemos D1 und Reedkontakt abgelesen. Da die ESP32-CAM auch freie GPIO's hat habe ich den Wemos abgeklemmt und nun den GPIO12 an den Reedkontakt angeschlossen.

Folgende GPIO12 Einstellungen habe ich vorgenommen:

![image](https://user-images.githubusercontent.com/49900099/153743890-5ef400dd-1eaf-4d72-932b-ec487cdf1de0.png)

Das funktioniert soweit auch ganz gut, bis darauf, daß ich bis zu 10 Messages pro Sekunde per MQTT bekomme, obwohl sich der Zustand des Reedkontaktes nicht verändert hat

`2022-02-13T08:10:04: sent publish successful in MQTTPublish, msg_id=39245, gaszaehler/GPIO/Sensor, false`
`2022-02-13T08:10:04: sent publish successful in MQTTPublish, msg_id=59815, gaszaehler/GPIO/Sensor, false`
`2022-02-13T08:10:04: sent publish successful in MQTTPublish, msg_id=29099, gaszaehler/GPIO/Sensor, false`
`2022-02-13T08:10:04: sent publish successful in MQTTPublish, msg_id=59536, gaszaehler/GPIO/Sensor, false`
`2022-02-13T08:10:04: sent publish successful in MQTTPublish, msg_id=62051, gaszaehler/GPIO/Sensor, false`
`2022-02-13T08:10:04: sent publish successful in MQTTPublish, msg_id=12730, gaszaehler/GPIO/Sensor, false`
`2022-02-13T08:10:04: sent publish successful in MQTTPublish, msg_id=2253, gaszaehler/GPIO/Sensor, false`
`2022-02-13T08:10:04: sent publish successful in MQTTPublish, msg_id=43809, gaszaehler/GPIO/Sensor, false`
`2022-02-13T08:10:04: sent publish successful in MQTTPublish, msg_id=35400, gaszaehler/GPIO/Sensor, false`
`2022-02-13T08:10:04: sent publish successful in MQTTPublish, msg_id=48644, gaszaehler/GPIO/Sensor, false`

**Comment by 040medien** [comment]
Das Signal vom Reedkontakt ist nicht 100% sauber. Der ESP32 muss das Signal entprellen (debounce), was dieses Projekt anscheinend aktuell nicht unterstützt.

**Comment by 040medien** [comment]
Oh, und du zählst beide Flanken des Signals (rising+falling), was den Wert auch verdoppelt.

**Comment by jomjol** [comment]
Entprellen etc. ist dort nicht eingebaut. Da ich nicht empfehle, den ESP32 auch noch mit anderen Aufgaben zu betrauen, werde ich das auch nicht mit Prio weiterentwicklen. Wenn du dort aber einen einfachen Entprellalgo o.ä. implementierst, nehme ich es gerne mit in eine der nächsten Versionen auf.

**Comment by Gunter1710** [comment]
Sorry, meine Programmierkenntnisse beschränken sich auf copy/paste :-)
Ich werde das klassisch mit Widersand und Kondensator lösen...

**Comment by jomjol** [comment]
:-) - ich mache den Issue dann erstmal zu.
