### ISSUE TITLE
dig-s2-q-20220211.tflite erkennt meine 0 nicht

### ISSUE THREAD

**Issue by awor** [jomjol/AI-on-the-edge-device#666]
Mal erkennt er eine 8, meist eine 7
Bin auf [10.4.0]

![image](https://user-images.githubusercontent.com/3464535/153759200-a74a3443-c3f1-44b0-9196-f52a6a1e0a17.png)

Ich habe einen Satz für die Erkennung beigesteuert. 
https://github.com/jomjol/AI-on-the-edge-device/issues/463#issuecomment-1009338531
Meinst Du, ist dieser bereits eingeflossen?

**Comment by jomjol** [comment]
Die Bilder sind eingeflossen. Mit LCDs müsste man eigentlich einen eigenen Datensatz erzeugen, dann wäre die Erkennung vermutlich ziemlich gut. Momentan machen sie ca. 2-5% der Bilddaten aus und damit ist das Netz dort nicht optimal.
Momentan fehlt mir die Zeit, einen dritten Satz Daten zu erzeugen. Eventuell kannst du dir das ja anschauen?
https://github.com/jomjol/neural-network-digital-counter-readout

**Comment by jomjol** [comment]
Fast - am besten machst du dir einen Fork davon. Dann nur die Ziffern in /ziffern_raw laden, die du trainieren willst. Wenn du es dann hochlädst, sollte eigentlich eine automatische Action starten, die dir nach ablauf die trainierten Ergebnisse in /a_output_actual liefert.

**Comment by awor** [comment]
Ich möchte eine kurze Erfolgsmeldung mitteilen: Ich habe nun einen eigenen Satz erstellt. Die Erkennung funktioniert auf den ersten Blick viel besser. Es hat mir folgende tflites erstellt:
![image](https://user-images.githubusercontent.com/3464535/158070223-8b2362cc-32a5-41fc-91d5-7498b6dca744.png)
Ich habe den grau markierten genommen, was gut zu funktionieren scheint. Passt das so, bzw. für was sind die Anderen?

**Comment by jomjol** [comment]
Das sind alles verschiedene große neuronale Netze. Je größer desto besser geeignet für allgemeine Bilder, aber desto langsame. Das "q" bedeutet, dass es quantisierte Darstellung ist, die nochmals schneller sind.
