### ISSUE TITLE
Idee: SSH oder FTP Server

### ISSUE THREAD

**Issue by awor** [jomjol/AI-on-the-edge-device#667]
Ich bin gerade das Log Verzeichnis am bereinigen von Training Einträgen. Da DELETE ALL! nicht rekursiv funktioniert, muss jedes Unterverzeichnis separat bearbeitet werden. Als alternative Idee: Ein SSH oder FTP Server würde die Verwaltung vom Dateisystem deutlich vereinfachen...

**Comment by jomjol** [comment]
Dazu gibt es die Option `LogfileRetentionInDays` die alte Logfile / Dateien automatisch nach einer frei wählbaren Anzahl an Tagen löscht.
SSH / FTP ist für die public Variante nicht geplant meinerseits. Ich kann aber gerne eine andere Implementierung mit aufnehmen, wenn jeman die Integration übernimmt.
