### ISSUE TITLE
Bootloop nach Update

### ISSUE THREAD

**Issue by spcqike** [jomjol/AI-on-the-edge-device#669]
Hallo,

ich wollt nur Bescheidsagen, dass die 10.4.0 zumindest bei meinem Board (Update von 10.0.2) nicht läuft. Ich komme in dauerhafte Reboots. Auf der Kamera steht DCX-OV2 640-V2. Ich meine, in einem Issue eine Auflistung mit kompatiblen Kameras gesehen zu haben, finde es aber nicht.
Evtl. kann man das im Wiki mit aufnehmen? :) (die V3 soll wohl laufen, oder?)

Eine Frage für kommende Firmwares hab ich.
Kann man eine Art "Minimalmodus" einbauen? bspw. nach 3 Reboots binnen 5 Minuten, dass nicht alles gestartet wird, sodass man über die Weboberfläche ein Rollback durchführen kann. Das Problem scheint ja die Kamera zu sein, oder?
ich komme aktuell nur bis zum Upload der alten Firmware, beim Flashen kommt die Meldung, dass die Verbindung abrupt abgebrochen wurde.

Und eine Frage zum Logging:
Ich hab zwar den Debug-Log in der Config gesetzt, sehe aber trotzdem keine brauchbaren Infos, wenn ich denn mal auf den Log zugreifen kann :) 

So, ich bin dann mal im Keller :D

**Comment by Gunter1710** [comment]
Schließ doch mal einen UART an die ESP32-CAM (siehe Bild unter Wiring)
https://github.com/jomjol/AI-on-the-edge-device/wiki/Installation

Den UART kannst du dann an einen PC anschließen und mit einem Seriellen Monitor dir anschauen wo das Problem ist. Und wenn du den UART schon angeschlossen hast, kannst du auch wieder die alte Firmware einspielen ;-)

**Comment by spcqike** [comment]
Update,

mit einer Änderung auf ImageQaulity 12 startet das Modul wieder. (Das ließ sich ja auf der SD Karte direkt ändern)

Vielleicht genügt bei einem Update von Firmware < 10.2 (oder wo die Änderung und die Probleme kamen) auf die aktuelle ja, wenn beim Update die Config zwangsweise auch angepasst wird :)

**Comment by jomjol** [comment]
Okay - dann schließe ich den Issue.

**Comment by spcqike** [comment]
weiteres Feedback: Mit der Version 10.4.0 und ImageQuality läuft das Modul nun auch seit bald 24h durch.

ein Problem hab ich dennoch, was wohl am Zähler liegt ..... er erkennt aktuell kaum Zahlen. Ich vermute, das liegt einfach am Zähler. Die Zahlen kommen nicht ganz mittig hoch .... Aber evtl. hast du einen Tipp, was ich korrigieren könnte? :)

Das Nichterkennen ist aktuell öfter als mit der alten Version. Allerdings habe ich zeitgleich auf das neuste dig.tflite umgestellt, die LEDs von grün auf weiß gewechselt und ich musste die ImageQuality drastisch reduzieren.

![grafik](https://user-images.githubusercontent.com/50098985/154023109-936b79b2-62f9-4d84-943f-b13a42175236.png)

achso: und irgendwie zeigt er in der Info das WLAN/IP nicht mehr an :) 
![grafik](https://user-images.githubusercontent.com/50098985/154023973-b993a12c-6215-4f81-9a10-f72195c92025.png)

**Comment by friedpa** [comment]
Du solltest erstens die Frames alle gleich groß machen. Zweitens könntest Du versuchen, von schräg oben auf die Ziffern zu schauen. Was mir auffällt ist auch noch, dass das Bild sehr grobkörnig und unscharf ist. Welche Auflösung verwendest Du, sollte aber mindestens VGA sein. 
Hier ein Beispiel:

![grafik](https://user-images.githubusercontent.com/42890695/154039817-1a53fa5a-3ea3-43c1-8ec8-acbcad3bcad2.png)

**Comment by spcqike** [comment]
Die Auflösung ist VGA, das Bild war vor dem Update, ohne der hohen Kompression, schärfer. die ROIs sind alle gleich groß. (ok, die in den roten Zahlen sind kleiner, aber das sind die Zahlen auch :) ) Sie sind so groß, dass die Zahl in das innere Rechteck passt.
Schräg drauf gucken ist leider nicht möglich. Zumal die "100" und auch die "30" gerader herausgeschaut haben. 

Ich hab die ROIs etwas tiefer gesetzt, damit erkennt er es seit 2h :)

![grafik](https://user-images.githubusercontent.com/50098985/154053620-8d27125f-825b-4765-8ccd-8dfa12fdcfd6.png)


ich werds einfach mal laufen lassen und abwarten.

**Comment by jomjol** [comment]
@spcqike Ich fürchte, dass du damit nicht richtig erfolgreich sein wirst, denn eigentlich dürfe er die Ziffern nur sehr schlecht erkennen. Einzige Chance wäre ein nur für deinen Fall geteaches tflite-File, das diese versetzten Ziffern lernt.
