### ISSUE TITLE
Analog readouts wrong

### ISSUE THREAD

**Issue by De-k** [jomjol/AI-on-the-edge-device#671]
Hi,

My analog roeadouts are unplausible:
From the following image I get a Raw: 00N05.1420
![image](https://user-images.githubusercontent.com/47114986/153866074-f36c23e0-f5e6-45a8-8912-9ce946a73d57.png)

 Raw: 00N05.1420
I think the picture quality and sharpness is the best i can get. (Reflections, distance,...). I also assume that the analog pointers are quite standard, from what i can see in other posts. What else can i do to improve the detection?

best regards Dek

**Comment by jomjol** [comment]
Which tflite file are you using? But it can also be, that the contrast of your pointers is rather low. Just for comparison my images: 
![grafik](https://user-images.githubusercontent.com/30766535/153940934-c5cc6a97-0f33-4ccf-9817-7824104a7edb.png)

You can see, that the contrast is much better. The shape of the pointers should not be a problem. I have this kind also in the training set.

**Comment by De-k** [comment]
![pic](https://user-images.githubusercontent.com/47114986/153948578-f2489187-5dcf-4522-9cb8-a9aeaf270416.jpeg)

Now contrast is better. But digit 3 is still wrong. Whats best, high contrast, or whiter background?

**Comment by jomjol** [comment]
This is by poupuse: as son as it starts to roll out of the image it is rated as "N" and will be replaced by the PreValue Algorithm (if activated and set).

**Comment by De-k** [comment]
Thanks for your reply: Sorry, I was unclear.
Yes, I  understood an know that for the digital readings.  I was thinking about the 3rd analogue digit. 

My 'human-readout' is ~0.2 vs 'algo-readout' 4,9'.:


human | algo |Rating
-- | --   | -- 
4.7 | 5.0 |~OK
6.9 | 6.6 |OK
0.2 | 4.9|NOK
4.9 | 4.9|OK

**Comment by jomjol** [comment]
Okay - did not even see this problem. There is not much to do, but improve the image quality and if possible, make the pointers a bit lighter, they look very dark.

**Comment by De-k** [comment]
Thanks for the info. I will try cam settings and setup/flash etc. Maybe some tape to reduce the reflection glare. Maybe that helps in the cam selfadjustment of exposure and gain.

Dek
