### ISSUE TITLE
Initial setup HTML page blank

### ISSUE THREAD

**Issue by VinceW31** [jomjol/AI-on-the-edge-device#675]
The initial setup HTML page only show the words DIGITIZER _ INITIAL SETUP, then two buttons PREVIOUS and NEXT, nothing else is displayed.  Ive tried reformatting the SD card and re-copy the files to the card again then re flashing the firmware to the ESP32, but its the same and I cant continue.  Pressing the NEXT or PREVIOUS buttons does nothing either.

**Comment by VinceW31** [comment]
The following sketch:

#include <Arduino.h>

int PSRAMSize;
int PSRAMFree;

void setup() {
  Serial.begin(115200);
}

void loop() {
  
  PSRAMSize = ESP.getPsramSize();
  PSRAMFree = ESP.getFreePsram();
  Serial.print("Total PSRAM: ");
  Serial.println(PSRAMSize);
  Serial.print("Free PSRAM: ");
  Serial.println(PSRAMFree);
  Serial.println(" ");
  delay(5000);
}

Results in:
Total PSRAM: 4194252
Free PSRAM: 4194252

**Comment by jomjol** [comment]
Can you post a serial log during startup?

**Comment by VinceW31** [comment]
OK here is the serial monitor output during startup:


rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:7188
load:0x40078000,len:14764
load:0x40080400,len:3764
entry 0x40080680
␛[0;32mI (27) boot: ESP-IDF 4.3.1 2nd stage bootloader␛[0m
␛[0;32mI (27) boot: compile time 15:54:50␛[0m
␛[0;32mI (27) boot: chip revision: 1␛[0m
␛[0;32mI (30) boot_comm: chip revision: 1, min. bootloader chip revision: 0␛[0m
␛[0;32mI (37) boot.esp32: SPI Speed      : 40MHz␛[0m
␛[0;32mI (41) boot.esp32: SPI Mode       : DIO␛[0m
␛[0;32mI (46) boot.esp32: SPI Flash Size : 4MB␛[0m
␛[0;32mI (50) boot: Enabling RNG early entropy source...␛[0m
␛[0;32mI (56) boot: Partition Table:␛[0m
␛[0;32mI (59) boot: ## Label            Usage          Type ST Offset   Length␛[0m
␛[0;32mI (67) boot:  0 nvs              WiFi data        01 02 00009000 00004000␛[0m
␛[0;32mI (74) boot:  1 otadata          OTA data         01 00 0000d000 00002000␛[0m
␛[0;32mI (82) boot:  2 phy_init         RF data          01 01 0000f000 00001000␛[0m
␛[0;32mI (89) boot:  3 ota_0            OTA app          00 10 00010000 001db000␛[0m
␛[0;32mI (97) boot:  4 ota_1            OTA app          00 11 001f0000 001db000␛[0m
␛[0;32mI (104) boot: End of partition table␛[0m
␛[0;32mI (108) boot: No factory image, trying OTA 0␛[0m
␛[0;32mI (113) boot_comm: chip revision: 1, min. application chip revision: 0␛[0m
␛[0;32mI (120) esp_image: segment 0: paddr=00010020 vaddr=3f400020 size=49438h (300088) map␛[0m
␛[0;32mI (244) esp_image: segment 1: paddr=00059460 vaddr=3ffb0000 size=04984h ( 18820) load␛[0m
␛[0;32mI (252) esp_image: segment 2: paddr=0005ddec vaddr=40080000 size=0222ch (  8748) load␛[0m
␛[0;32mI (256) esp_image: segment 3: paddr=00060020 vaddr=400d0020 size=13abf4h (1289204) map␛[0m
␛[0;32mI (752) esp_image: segment 4: paddr=0019ac1c vaddr=4008222c size=19600h (103936) load␛[0m
␛[0;32mI (797) esp_image: segment 5: paddr=001b4224 vaddr=50000000 size=00010h (    16) load␛[0m
␛[0;32mI (811) boot: Loaded app from partition at offset 0x10000␛[0m
␛[0;32mI (811) boot: Set actual ota_seq=1 in otadata[0]␛[0m
␛[0;32mI (811) boot: Disabling RNG early entropy source...␛[0m
␛[0;32mI (828) psram: This chip is ESP32-D0WD␛[0m
␛[0;32mI (828) spiram: Found 64MBit SPI RAM device␛[0m
␛[0;32mI (828) spiram: SPI RAM mode: flash 40m sram 40m␛[0m
␛[0;32mI (833) spiram: PSRAM initialized, cache is in low/high (2-core) mode.␛[0m
␛[0;32mI (840) cpu_start: Pro cpu up.␛[0m
␛[0;32mI (844) cpu_start: Starting app cpu, entry point is 0x40082910␛[0m
␛[0;32mI (0) cpu_start: App cpu up.␛[0m
␛[0;32mI (1738) spiram: SPI SRAM memory test OK␛[0m
␛[0;32mI (1746) cpu_start: Pro cpu start user code␛[0m
␛[0;32mI (1746) cpu_start: cpu freq: 160000000␛[0m
␛[0;32mI (1746) cpu_start: Application information:␛[0m
␛[0;32mI (1749) cpu_start: Project name:     esp32cam-server-only␛[0m
␛[0;32mI (1755) cpu_start: App version:      0.0.9.3␛[0m
␛[0;32mI (1760) cpu_start: Compile time:     Jan 29 2022 15:53:16␛[0m
␛[0;32mI (1767) cpu_start: ELF file SHA256:  54bff4f229966b1f...␛[0m
␛[0;32mI (1773) cpu_start: ESP-IDF:          4.3.1␛[0m
␛[0;32mI (1778) heap_init: Initializing. RAM available for dynamic allocation:␛[0m
␛[0;32mI (1785) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM␛[0m
␛[0;32mI (1791) heap_init: At 3FFC0510 len 0001FAF0 (126 KiB): DRAM␛[0m
␛[0;32mI (1797) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM␛[0m
␛[0;32mI (1804) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM␛[0m
␛[0;32mI (1810) heap_init: At 4009B82C len 000047D4 (17 KiB): IRAM␛[0m
␛[0;32mI (1817) spiram: Adding pool of 4096K of external SPI memory to heap allocator␛[0m
␛[0;32mI (1826) spi_flash: detected chip: generic␛[0m
␛[0;32mI (1829) spi_flash: flash io: dio␛[0m
␛[0;32mI (1839) cpu_start: Starting scheduler on PRO CPU.␛[0m
␛[0;32mI (0) cpu_start: Starting scheduler on APP CPU.␛[0m
␛[0;32mI (1844) spiram: Reserving pool of 32K of internal memory for DMA/internal allocations␛[0m
␛[0;32mI (1854) gpio: GPIO[32]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 ␛[0m
Init Camera
␛[0;32mI (3864) gpio: GPIO[25]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:2 ␛[0m
␛[0;32mI (3864) cam_hal: cam init ok␛[0m
␛[0;32mI (3864) sccb: pin_sda 26 pin_scl 27␛[0m
␛[0;32mI (3864) gpio: GPIO[32]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 ␛[0m
␛[0;32mI (3904) camera: Detected camera at address=0x30␛[0m
␛[0;32mI (3904) camera: Detected OV2640 camera␛[0m
␛[0;32mI (3904) camera: Camera PID=0x26 VER=0x42 MIDL=0x7f MIDH=0xa2␛[0m
␛[0;32mI (3984) cam_hal: buffer_size: 32768, half_buffer_size: 4096, node_buffer_size: 2048, node_cnt: 16, total_cnt: 15␛[0m
␛[0;32mI (3984) cam_hal: Allocating 61440 Byte frame buffer in PSRAM␛[0m
␛[0;32mI (3994) cam_hal: cam config ok␛[0m
␛[0;32mI (3994) ov2640: Set PLL: clk_2x: 0, clk_div: 0, pclk_auto: 0, pclk_div: 8␛[0m
Internal Flash-LED turn off PWM
nach init camera: sleep for : 200ms
␛[0;32mI (6084) main: Using SDMMC peripheral␛[0m
Name: SD   
Type: SDHC/SDXC
Speed: 20 MHz
Size: 15075MB
␛[0;32mI (6284) server_ota: Start CheckOTAUpdateCheck ...␛[0m
Start CheckOTAUpdateCheck ...
␛[0;32mI (6294) server_ota: SHA-256 for the partition table: : 9d4a2809ae90fb20709a8ca3dd3ac3462e1e73286bcd31b689060c91de06fa3a␛[0m    
␛[0;32mI (6294) server_ota: SHA-256 for bootloader: : 7d6d1d6c68a1edfd738efb99e18a1294d0d9d017426bd05464b399294996b58e␛[0m
␛[0;32mI (6304) server_ota: SHA-256 for current firmware: : 8a1fe24eb98db1ce3cdbae026a771961162cb520f78e0736ba4f6bdfd7f2cbba␛[0m       
CheckOTAUpdate Partition: ESP_OK
open file /sdcard/wlan.ini in mode r
file loaded

WLan: BT-JKA22M, 9rM7hAVLEfeh4b
Hostename: PV_meter_reader
I (6374) wifi:wifi driver task: 3ffdb370, prio:23, stack:6656, core=0
␛[0;32mI (6374) system_api: Base MAC address is not set␛[0m
␛[0;32mI (6374) system_api: read default base MAC address from EFUSE␛[0m
I (6384) wifi:wifi firmware version: 88c8747
I (6384) wifi:wifi certification version: v7.0
I (6384) wifi:config NVS flash: enabled
I (6384) wifi:config nano formating: disabled
I (6394) wifi:Init data frame dynamic rx buffer num: 16
I (6394) wifi:Init management frame dynamic rx buffer num: 16
I (6404) wifi:Init management short buffer num: 32
I (6404) wifi:Init static tx buffer num: 16
I (6414) wifi:Init tx cache buffer num: 16
I (6414) wifi:Init static rx buffer size: 1600
I (6424) wifi:Init static rx buffer num: 10
I (6424) wifi:Init dynamic rx buffer num: 16
␛[0;32mI (6424) wifi_init: rx ba win: 6␛[0m
␛[0;32mI (6434) wifi_init: tcpip mbox: 32␛[0m
␛[0;32mI (6434) wifi_init: udp mbox: 6␛[0m
␛[0;32mI (6434) wifi_init: tcp mbox: 6␛[0m
␛[0;32mI (6444) wifi_init: tcp tx win: 5744␛[0m
␛[0;32mI (6444) wifi_init: tcp rx win: 5744␛[0m
␛[0;32mI (6454) wifi_init: tcp mss: 1440␛[0m
␛[0;32mI (6454) wifi_init: WiFi IRAM OP enabled␛[0m
␛[0;32mI (6464) wifi_init: WiFi RX IRAM OP enabled␛[0m
␛[0;32mI (6484) phy_init: phy_version 4670,719f9f6,Feb 18 2021,17:07:07␛[0m
␛[0;33mW (6484) phy_init: failed to load RF calibration data (0x1102), falling back to full calibration␛[0m
I (6644) wifi:mode : sta (24:0a:c4:60:5d:34)
I (6644) wifi:enable tsf
␛[0;32mI (6644) BLINK: Blinken - start␛[0m
␛[0;31mE (6644) wifi station: Set Hostname to:PV_meter_reader␛[0m
␛[0;32mI (6644) wifi station: wifi_init_sta finished.␛[0m
I (6654) wifi:new:<1,0>, old:<1,0>, ap:<255,255>, sta:<1,0>, prof:1
␛[0;32mI (6844) BLINK: Blinken - done␛[0m
I (7494) wifi:state: init -> auth (b0)
I (7514) wifi:state: auth -> assoc (0)
I (7544) wifi:state: assoc -> run (10)
I (7644) wifi:connected with BT-JKA22M, aid = 5, channel 1, BW20, bssid = 44:fe:3b:9e:03:49
I (7644) wifi:security: WPA2-PSK, phy: bgn, rssi: -69
I (7664) wifi:pm start, type: 1

I (7694) wifi:AP's beacon interval = 102400 us, DTIM period = 3
W (7804) wifi:<ba-add>idx:0 (ifx:0, 44:fe:3b:9e:03:49), tid:6, ssn:1, winSize:64
␛[0;32mI (8854) esp_netif_handlers: sta ip: 192.168.1.177, mask: 255.255.255.0, gw: 192.168.1.254␛[0m
␛[0;32mI (8854) wifi station: got ip:192.168.1.177␛[0m
␛[0;32mI (8854) wifi station: connected to ap SSID:BT-JKA22M password:9rM7hAVLEfeh4b␛[0m
␛[0;32mI (8854) BLINK: Blinken - start␛[0m
main: sleep for : 200ms
␛[0;32mI (10864) sntp: Time is not set yet. Connecting to WiFi and getting time over NTP.␛[0m
␛[0;32mI (10864) sntp: Initializing SNTP␛[0m
␛[0;32mI (10864) sntp: Waiting for system time to be set... (1/10)␛[0m
␛[0;32mI (12864) sntp: Waiting for system time to be set... (2/10)␛[0m
␛[0;32mI (14864) sntp: Waiting for system time to be set... (3/10)␛[0m
W (15714) wifi:<ba-add>idx:1 (ifx:0, 44:fe:3b:9e:03:49), tid:0, ssn:0, winSize:64
TimeZone set to CET-1CEST,M3.5.0,M10.5.0/3
Logfile opened: /sdcard/log/message/log_2022-02-17.txt
␛[0;32mI (16904) sntp: The current date/time in Berlin is: Thu Feb 17 14:31:01 2022␛[0m
␛[0;32mI (16904) sntp: The current date/time in Berlin is: 2022-02-17_14:31␛[0m
timeist 20220217-143101
Logfile opened: /sdcard/log/message/log_2022-02-17.txt
Logfile opened: /sdcard/log/message/log_2022-02-17.txt
Logfile opened: /sdcard/log/message/log_2022-02-17.txt
time 20220217-143101
Internal Flash-LED turn off PWM
main: sleep for : 2000ms
␛[0;32mI (18864) BLINK: Blinken - done␛[0m
starting server
␛[0;32mI (18964) server-main: Starting server on port: '80'␛[0m
␛[0;32mI (18964) server-main: Registering URI handlers␛[0m
␛[0;32mI (18964) server_tflite: server_part_camera - Registering URI handlers␛[0m
␛[0;32mI (18964) server_ota: server_ota - Registering URI handlers␛[0m
␛[0;32mI (18974) server_GPIO: start GpioHandler␛[0m
␛[0;32mI (18974) server_GPIO: register GPIO Uri␛[0m
␛[0;32mI (18984) server_GPIO: server_GPIO - Registering URI handlers␛[0m
vor reg server main
vor dotautostart
task_autodoFlow configMINIMAL_STACK_SIZE: 768
getESPHeapInfo:  Heap: 4155362 Min Free: 4154334 larg. Block:  2097152 SPI Heap: 4103731 NOT_SPI Heap: 51631 Internal Heap: 51631 Internal Min Heap free: 51115
task_autodoFlow: start
getESPHeapInfo:  Heap: 4128138 Min Free: 4127454 larg. Block:  2097152 SPI Heap: 4103731 NOT_SPI Heap: 24407 Internal Heap: 24407 Internal Min Heap free: 24235
open file /sdcard/config/config.ini in mode r
[MakeImage]
Start ReadParameter ([MakeImage]
)
;LogImageLocation = /log/source
WaitBeforeTakingPicture = 5
;LogfileRetentionInDays = 15
Brightness = 0
Contrast = 0
Saturation = 0
LEDIntensity = 50
Set led_intensity to 4095 of 8191
ImageQuality = 12
ImageSize = VGA
FixedExposure = false

[Alignment]
␛[0;32mI (19064) ov2640: Set PLL: clk_2x: 0, clk_div: 0, pclk_auto: 0, pclk_div: 8␛[0m
Start ReadParameter ([Alignment])
InitialRotate = 179
InitialMirror = false
SearchFieldX = 20
SearchFieldY = 20
AlignmentAlgo = Default
FlipImageSize = false
/config/ref0.jpg 103 271
/config/ref1.jpg 442 142

[Digits]
2022-02-16T15:18:22
Start ReadParameter ([Digits])
Model = /config/dig-s2-q-20220104.tflite
;LogImageLocation = /log/digit
;LogfileRetentionInDays = 3
ModelInputSize = 20 32
main.dig1 294 126 30 54
GetGENERAL - GENERAL main - roi dig1
main.dig2 343 126 30 54
GetGENERAL - GENERAL main - roi dig2
main.dig3 391 126 30 54
GetGENERAL - GENERAL main - roi dig3

[Analog]
Start ReadParameter ([Analog])
Model = /config/ana-s3-q-20220105.tflite
;LogImageLocation = /log/analog
;LogfileRetentionInDays = 3
ModelInputSize = 32 32
ExtendedResolution = true
main.ana1 432 230 92 92
GetGENERAL - GENERAL main - roi ana1
main.ana2 379 332 92 92
GetGENERAL - GENERAL main - roi ana2
main.ana3 283 374 92 92
GetGENERAL - GENERAL main - roi ana3
main.ana4 155 328 92 92
GetGENERAL - GENERAL main - roi ana4

[PostProcessing]
Start ReadParameter ([PostProcessing])
Anzahl NUMBERS: 1 - DIGITS: 1, ANALOG: 1
Number main, Anz DIG: 3, Anz ANA 4
main.DecimalShift = 0
PreValueUse = true
PreValueAgeStartup = 720
AllowNegativeRates = false
main.MaxRateValue = 0.05
ErrorMessage = true
CheckDigitIncreaseConsistency = false

;[MQTT]
Read Zeile Prevalue.ini: 2020-11-30_12-02-22
42.013401
TIME: 120, 10, 1073720960, 0, 1073721240, 1073720996
Write PreValue Zeile: main      1918-10-19T17:17:40     42.0134

Read: ;Uri = mqtt://IP-ADRESS:1883
Read: ;MainTopic = wasserzaehler
Read: ;ClientID = wasser
Read: ;user = USERNAME
Read: ;password = PASSWORD
Read:
Read: ;[GPIO]
Read: ;MainTopicMQTT = wasserzaehler/GPIO
Read: ;IO0 = input disabled 10 false false
Read: ;IO1 = input disabled 10 false false
Read: ;IO3 = input disabled 10 false false
Read: ;IO4 = built-in-led disabled 10 false false
Read: ;IO12 = input-pullup disabled 10 false false
Read: ;IO13 = input-pullup disabled 10 false false
Read: LEDType = WS2812
Read: LEDNumbers = 2
Read: LEDColor = 150 150 150
Read:
Read: [AutoTimer]
Start ReadParameter ([AutoTimer]
)
AutoStart = true
Intervall = 4.85

[Debug]
Start ReadParameter ([Debug])
Logfile = false
LogfileRetentionInDays = 3

[System]
Start ReadParameter ([System])
TimeZone = CET-1CEST,M3.5.0,M10.5.0/3
TimeZone set to CET-1CEST,M3.5.0,M10.5.0/3
;TimeServer = undefined
;AutoAdjustSummertime = false
;Hostname = undefined
SetupMode = true
END OF FILE
*************** Start GPIOHandler_Init *****************
␛[0;32mI (20894) server_GPIO: read GPIO config and init GPIO␛[0m
open file /sdcard/config/config.ini in mode r
[MakeImage]
;LogImageLocation = /log/source
WaitBeforeTakingPicture = 5
;LogfileRetentionInDays = 15
Brightness = 0
Contrast = 0
Saturation = 0
LEDIntensity = 50
ImageQuality = 12
ImageSize = VGA
FixedExposure = false

[Alignment]
InitialRotate = 179
InitialMirror = false
SearchFieldX = 20
SearchFieldY = 20
AlignmentAlgo = Default
FlipImageSize = false
/config/ref0.jpg 103 271
/config/ref1.jpg 442 142

[Digits]
Model = /config/dig-s2-q-20220104.tflite
;LogImageLocation = /log/digit
;LogfileRetentionInDays = 3
ModelInputSize = 20 32
main.dig1 294 126 30 54
main.dig2 343 126 30 54
main.dig3 391 126 30 54

[Analog]
Model = /config/ana-s3-q-20220105.tflite
;LogImageLocation = /log/analog
;LogfileRetentionInDays = 3
ModelInputSize = 32 32
ExtendedResolution = true
main.ana1 432 230 92 92
main.ana2 379 332 92 92
main.ana3 283 374 92 92
main.ana4 155 328 92 92

[PostProcessing]
main.DecimalShift = 0
PreValueUse = true
PreValueAgeStartup = 720
AllowNegativeRates = false
main.MaxRateValue = 0.05
ErrorMessage = true
CheckDigitIncreaseConsistency = false

;[MQTT]
;Uri = mqtt://IP-ADRESS:1883
;MainTopic = wasserzaehler
;ClientID = wasser
;user = USERNAME
;password = PASSWORD

;[GPIO]
;MainTopicMQTT = wasserzaehler/GPIO
;IO0 = input disabled 10 false false
;IO1 = input disabled 10 false false
;IO3 = input disabled 10 false false
;IO4 = built-in-led disabled 10 false false
;IO12 = input-pullup disabled 10 false false
;IO13 = input-pullup disabled 10 false false
LEDType = WS2812
LEDNumbers = 2
LEDColor = 150 150 150

[AutoTimer]
AutoStart = true
Intervall = 4.85

[Debug]
Logfile = false
LogfileRetentionInDays = 3

[System]
TimeZone = CET-1CEST,M3.5.0,M10.5.0/3
;TimeServer = undefined
;AutoAdjustSummertime = false
;Hostname = undefined
SetupMode = true
␛[0;32mI (21064) server_GPIO: GPIO init comleted, handler is disabled␛[0m
Flashdauer: 5000
Internal Flash-LED turn on with PWM 4095
Internal Flash-LED turn off PWM
Image loaded from memory: 640, 480, 3

**Comment by VinceW31** [comment]
After boot up (as above) then the setup screen loaded correctly this time with 192.168.1.177, however, when I press NEXT it goes to the next page but with some random blanks on the web page and then back to PREVIOUS an empty page or more random blanks.  At this point the serial monitor shows the following (or similar) error (httpd_txrx: httpd_sock_err: error in recv ):

1 uri: /readconfigcommon.js, filename: , filepath: /sdcard
Filename:
File requested: /sdcard/html/readconfigcommon.js
open file /sdcard/html/readconfigcommon.js in mode r
␛[0;32mI (1229504) serverhelp: Sending file : /sdcard/html/readconfigcommon.js ...␛[0m
␛[0;32mI (1229534) serverhelp: File sending complete␛[0m
␛[0;33mW (1229534) httpd_txrx: httpd_sock_err: error in recv : 104␛[0m
␛[0;33mW (1229544) httpd_txrx: httpd_sock_err: error in recv : 104␛[0m
␛[0;33mW (1229594) httpd_txrx: httpd_sock_err: error in recv : 104␛[0m

**Comment by jomjol** [comment]
Everythings looks okay from my point of view. I cannot find the root cause for your problem and this is the first time, such a behaviour is reported.

The only thing, that I can think of, is a problem with the sd-card. Can you check a smaller sd-card (e.g. 4 GB)? 16 GB is sometimes reported to be a problem.

**Comment by VinceW31** [comment]
Found the problem, your HTML in setup.html (and other pages I guess) isn't allowed by my virus checker Kaspersky Total Security.  Seems to work ok when I pause the protection.

**Comment by jomjol** [comment]
Close issue
