### ISSUE TITLE
AllowNegativeRates still active?

### ISSUE THREAD

**Issue by friedpa** [jomjol/AI-on-the-edge-device#678]
@jomjol
Guten Morgen Josef,
ich habe ein interessantes Phänomen. Folgendes Bild:
![grafik](https://user-images.githubusercontent.com/42890695/154212706-708c0adf-57eb-4ffb-95d1-d55d8db371a4.png)
Wie Du sehen kannst ist die Raw Value richtig: 00267.7202. Die Previous Value ist aber 268.7202. Es sollte somit ein Error vorliegen, da es ja ein negativer Wert zum PreValue ist. Trotzdem zählt der Algorhythmus weiter hinauf?!
Noch eine Frage: in der Config.ini müssen da die Dezimaltrenner ein Punkt, oder Beistrich sein (also 3.5 oder 3,5)?
Übrigends: ich bin bereits bei Round # 7746! Sensationell!
Liebe Grüße
Paul

EDIT:
![grafik](https://user-images.githubusercontent.com/42890695/154214141-7eab5ece-6df0-4a46-96fb-032f0551a43f.png)

**Comment by jomjol** [comment]
Hi Paul,
die Ursache für dieses Verhalten muss schon irgendwo vorher liegen. Wenn der PreValue erstmal um eins erhöht ist (268.7) dann kann ich das erklären:
Der CheckDigitConistencyAlgo erkannt anhander unveränderten ersten Nachkommastelle "7", dass kein Nulldurchgang stattgefunden hat und daher die Stelle sich nicht hätte ändern dürfen. 
Dann wird einfach der "neue" Wert (26**7**.7) durch den "korrekten" (=PreValue) ersetzt: 26**8**.7

Kannst du nachvollziehen, warum der Wert vorher nicht passt?

**Comment by jomjol** [comment]
Schließe das mal, da aktuell keine Aktivitäten - bitte gerne melden, wenn noch ein Thema
