### ISSUE TITLE
external illumination with WS2812B LEDs

### ISSUE THREAD

**Issue by Sandworm-of-Dune** [jomjol/AI-on-the-edge-device#682]
I wanted to switch to external illumination.
So I bought those single WS2812B LEDs because LED stripes are only available in meter 
![grafik](https://user-images.githubusercontent.com/91150538/154319117-cb5df285-bcf6-49a0-a2dc-ccee40659b3e.png) ![grafik](https://user-images.githubusercontent.com/91150538/154319139-bb70ccb3-c2d8-4a72-a432-d67c2793ca63.png)

https://www.ebay.de/itm/164271029394

I used the wiring (including 470 Ohm /470µF ) as described here:
https://github.com/jomjol/AI-on-the-edge-device/wiki/External-LED
![grafik](https://user-images.githubusercontent.com/91150538/154320508-64add7f4-5028-4bdd-a3e9-9e86e2c8d92b.png)

But after enabling GPIO 12, no external LED is shining.
![grafik](https://user-images.githubusercontent.com/91150538/154319191-d2ea78d1-68f3-4078-adac-93530f39742f.png)

Is anyone using these LEDs too?
What do I have to change to get this one working? Do I have to remove the 470 Ohm resistor because one resistor is alredy on the LEDboard?

Thanks 
Tobias

**Comment by WeVolutionNet** [comment]
Saw this (exterrnal LEDs) in a video a few minutes ago... Maybe it helps you...
https://youtu.be/iUgxwbfkIqU?t=405

**Comment by Kalli01** [comment]
Guten Morgen, da die Ebay Anzeige aus Deutschland kommt, schreibe ich dir mal auf deutsch. Falls Englisch besser wäre, dann kann ich es noch übersetzen lassen.

Bestellt habe ich diese https://www.ebay.de/itm/164339370970 LEDs. Wie ich sehe ist es der gleiche Händler wie bei dir.
Insgesamt habe ich zwei Module auf externe LEDs umgebaut. Das erste hat auf gleich funktioniert das zweite aber nicht.

Der Fehler war, dass dass Modul verdreht vor mir lag und ich so die LED an die falschen Pins gelötet hatte. Nach dem ich es korrigiert habe, leuchtet jetzt auch die LED.

Einen Widerstand und den Elko habe ich auch angelötet.
Vielleicht kannst du noch einmal die Pins prüfen. Du könntest auch die Spannungsversorgung einmal direkt an der LED messen.
Falls du noch eine LED hast könntest du sie auch einmal austauschen.

Meine Einstellungen scheinen die gleichen wie deine zu sein.
![LED Einstellungen](https://user-images.githubusercontent.com/97545405/154792382-4442a333-04f1-4a95-8497-87bad460aff1.png)

Hiernoch einmal als Text. Vielleicht hat sich etwas verstellt
[GPIO]
;IO0 = input disabled 10 false false 
;IO1 = input disabled 10 false false 
;IO3 = input disabled 10 false false 
;IO4 = built-in-led disabled 10 false false 
IO12 = external-flash-ws281x disabled 10 false false 
;IO13 = input-pullup disabled 10 false false 
LEDType = WS2812B
LEDNumbers = 2
LEDColor = 220 220 220


Nach dem Ändern der Einstellungen musst du einmal Neustarten. Das wirst du aber bestimmt schon mehrfach gemacht haben.

Mehr fällt mir jetzt erst einmal nicht ein.

**Comment by T0RST3N** [comment]
![image](https://user-images.githubusercontent.com/25604832/154802949-93bb8b69-4cb1-45ae-b321-1e3b3124004f.png)
At first it didn't work for me either, but then I played around a bit and entered something in the "PWM duty resolution" option. Even with "0" or more, the LED works, but if the field is empty without a value, the LED does not work. (for me). I don't quite know what the option is for :-)

**Comment by Sandworm-of-Dune** [comment]
Thanks @T0RST3N and @Kalli01
I will check later or tomorrow and let you know.
Regards Tobias

**Comment by Sandworm-of-Dune** [comment]
Good news. External LEDs are working.
It seems its only working if ALL entrys in section GPIO12 are filled with values (even if not used)
Thanks @T0RST3N again for this hint.

Here are my settings
![grafik](https://user-images.githubusercontent.com/91150538/154841792-e4a6aae6-2504-4c7d-b24a-91f333f910b1.png)
