### ISSUE TITLE
MQTT: rate not sent in release 10.5.0 and 10.5.1

### ISSUE THREAD

**Issue by mkranjcic** [jomjol/AI-on-the-edge-device#684]
It seams like rate is not sent in latest release 10.5.0 (it was working before update)
vodomjer/connection connected
vodomjer/uptime 1744
vodomjer/freeMem 3008051
vodomjer/wifiRSSI -56
vodomjer/main/value 824.5569
vodomjer/main/error no error
vodomjer/main/raw 00824.5569
vodomjer/main/timestamp 2022-02-18T22:42:35
vodomjer/main/json {"value":824.5569,"raw":"00824.5569","error":"no error","rate":"","timestamp":"2022-02-18T22:42:35"}
vodomjer/connection connected
vodomjer/uptime 69
vodomjer/freeMem 3010467
vodomjer/wifiRSSI -55
vodomjer/main/value 824.57183
vodomjer/main/error no error
vodomjer/main/raw 00824.57183
vodomjer/main/timestamp 2022-02-18T22:45:38
vodomjer/main/json {"value":824.57183,"raw":"00824.57183","error":"no error","rate":"","timestamp":"2022-02-18T22:45:38"}

**Comment by skynet74** [comment]
Same in JSON: {
"main":
  {
    "value": 81.6946,
    "raw": "00081.6946",
    "error": "no error",
    "rate": "",
    "timestamp": "2022-02-19T09:43:15"
  }
}

**Comment by friedpa** [comment]
I can confirm this behaviour with my two systems

**Comment by De-k** [comment]
Confirm,

Read value also missing in error message:
{"value":"","raw":"00N06.7367","error":"Neg. Rate - Read: - Raw: 00N06.7367 - Pre: 506.7384 ","rate":"","timestamp":"1970-01-03T18:45:20"}

**Comment by mkranjcic** [comment]
Issue persist with 10.5.1 release:
vodomjer/connection connected
vodomjer/uptime 3490
vodomjer/freeMem 3008495
vodomjer/wifiRSSI -56
vodomjer/main/value 825.53625
vodomjer/main/error no error
vodomjer/main/raw 00825.53624
vodomjer/main/timestamp 2022-02-20T19:26:46
vodomjer/main/json {"value":825.53625,"raw":"00825.53624","error":"no error","rate":"","timestamp":"2022-02-20T19:26:46"}

![image](https://user-images.githubusercontent.com/9868887/154858121-3a497845-d92e-4590-be2a-026759517044.png)

**Comment by skynet74** [comment]
I updated to 10.5.1 the rate value are back ;) 

{
  "main": {
    "value": 81.9499,
    "raw": "0008N.9499",
    "error": "no error",
    "rate": 0.000000,
    "timestamp": "2022-02-20T19:31:09"
  }
}

Thank you

**Comment by mkranjcic** [comment]
> I updated to 10.5.1 the rate value is back ;)
> 
> { "main": { "value": 81.9499, "raw": "0008N.9499", "error": "no error", "rate": 0.000000, "timestamp": "2022-02-20T19:31:09" } }
> 
> Thank you

Do you have same version info shown? Thx

**Comment by skynet74** [comment]
<img width="455" alt="Bildschirmfoto 2022-02-20 um 19 40 48" src="https://user-images.githubusercontent.com/13029404/154858596-fed1fbca-f148-4651-8ffc-0b3c095218b6.png">

**Comment by jomjol** [comment]
There was a very little error in the 10.5.1 withbuild time 16:02, which has been resolved in the version build at 16:21.
Didn't thought, that on Sunday afternoon somebody used it immediatly :-).

I will close the issue.

**Comment by mkranjcic** [comment]
I can also confirm that it is working.
Thank you.

And yes - not only you are working :)

**Comment by friedpa** [comment]
Hmmm, my rate is not updated, or always 0 is sent. Could you please check again?

**Comment by jomjol** [comment]
Hi Paul,
brauche noch mehr Inputs. Habe gerade mein System angeschaut:
/json
![grafik](https://user-images.githubusercontent.com/30766535/155004974-97b75a27-3215-4f99-84cb-b31f5c210af2.png)
logfile (Auszug):
```
2022-02-21T18:44:51: sent publish successful in MQTTPublish, msg_id=18494, strom_haus/connection, connected
2022-02-21T18:44:51: sent publish successful in MQTTPublish, msg_id=14121, strom_haus/uptime, 94642
2022-02-21T18:44:51: sent publish successful in MQTTPublish, msg_id=55974, strom_haus/freeMem, 3163263
2022-02-21T18:44:51: sent publish successful in MQTTPublish, msg_id=6332, strom_haus/wifiRSSI, -64
2022-02-21T18:44:51: sent publish successful in MQTTPublish, msg_id=56993, strom_haus/main/value, 36132.47
2022-02-21T18:44:51: sent publish successful in MQTTPublish, msg_id=44770, strom_haus/main/error, no error
2022-02-21T18:44:51: sent publish successful in MQTTPublish, msg_id=22372, strom_haus/main/rate, 0.019531
2022-02-21T18:44:51: sent publish successful in MQTTPublish, msg_id=41267, strom_haus/main/raw, 36132.47
2022-02-21T18:44:51: sent publish successful in MQTTPublish, msg_id=14304, strom_haus/main/timestamp, 2022-02-21T18:43:39
2022-02-21T18:44:51: sent publish successful in MQTTPublish, msg_id=50132, strom_haus/main/json, {"value":36132.47,"raw":"36132.47","error":"no error","rate":0.019531,"timestamp":"2022-02-21T18:43:39"}
```

Bei mir wird eine Rate angezeigt. Version ist folgende:
![grafik](https://user-images.githubusercontent.com/30766535/155005184-e025f939-3906-47ae-9396-86c5b722eaa1.png)

**Comment by friedpa** [comment]
Hi Josef,
selber SW Stand, beim Master, aber beim HTML bin ich auf 13.1.1
![grafik](https://user-images.githubusercontent.com/42890695/155009220-38e3720b-fa79-4f64-b2b3-93a4e60d33d0.png)

MQTT:
![grafik](https://user-images.githubusercontent.com/42890695/155009062-67426221-bad0-4ab2-b0ef-fc5b71a16be5.png)
Der Wert bei Rate bleibt immer 0.

**Comment by jomjol** [comment]
Okay - sehr strange. Habe gerade meinen MQTT geprüft:
![grafik](https://user-images.githubusercontent.com/30766535/155009649-fbf92b42-e1cc-47cd-aeb4-cb2901a6f583.png)
Zeigt auch eine Rate! Einziger Unterschied: das ist ein reiner Stromzähler (ohne analoge Zeiger).

**Comment by friedpa** [comment]
Der von mir oben angeführte Zähler ist auch ein reiner Digitalzähler.... Ich übertrage die Werte zu einem IOBroker. Ich sehe das alle Werte in der eingestellten Zeit (4 Minuten) grün werden, also durch den IOBroker MQTT Adapter empfangen werden, nur die "Rate" wird nicht upgedated. Ich werde Morgen einmal neu Flashen und auch die HTML Seite neu laden.

**Comment by jomjol** [comment]
bin gespannt, was rauskommt. HTML und MQTT sollten unsabhängig sein, da MQTT nur von der Firmware gesendet wird.

**Comment by andilee7** [comment]
Bei mir geht die rate bei MQTT auch nicht mit der 10.5.1
Denke aber stark es liegt an der Buildtime. Im .zip und .tar.gz unter dem letzten Release ist der timestamp der firmware.bin 16:05 und du meintest du hast um 16:21 noch mal einen Bug bezüglich der rate behoben.

**Comment by friedpa** [comment]
Guten Morgen Josef,
ich habe die SW neu geflashed und im IOBroker das "Rate" Objekt gelöscht. Es wird bei mir das Rate Objekt nicht übertragen, auch im jason ist der Wert "Rate" immer 0, das Objekt "Rate" wird nicht neu angelegt so wie bei anderen Feldern. Kann das an einer Einstellung der Config.Ini liegen?

**Comment by jomjol** [comment]
@andilee7 : danke für den Hinweis mit der Buildtime - irgendwie hat es die falsche firmware.bin in den Release geschafft. Sollte jetzt mit 10.5.2 korrigiert sein.

Sorry für die Verwirrung!

**Comment by friedpa** [comment]
@andilee7 Wie kommt man auf die Idee Buildtimes zu kontrollieren? Bin impressed! :o)

**Comment by andilee7** [comment]
@friedpa hehe :D eigentlich nur weil @jomjol erwähnte, dass es einen Rate-Bug gab der 20 Minuten später gefixt war aber ich trotzdem noch von dem Fehler betroffen war nach dem Update.
Mit der 10.5.2 hab ich die Rate via MQTT wieder :)

**Comment by friedpa** [comment]
@andilee7 Super! Bei mir ist der Fehler nun auch weg.
