### ISSUE TITLE
Strange conversion from raw to read

### ISSUE THREAD

**Issue by De-k** [jomjol/AI-on-the-edge-device#688]
Hallo, 

ich habe eine umwandlung von raw zu read, die falsch ist, und ich nicht verstehe, wenn ich Deine Algo Doku anschaue.

1970-01-03T17:46:11: PostProcessing - Raw: 00N06.7079 Value:  Error: Neg. Rate - Read: 505.7079 - Raw: 00N06.7079 - Pre: 506.4956 

Das N im Raw ist ok, die anderen Werte sind perfekt, warum der Wert dann auf 505 (statt 506) korrigiert wird, verstehe ich icht. Der Error ist folgerichtig auch verkehrt.

Ich habe 
prevalue und 
CheckDigitIncreaseConsistency 
Aktiviert.

Dek
PS using master - v10.4.0 - 2022-02-12

**Comment by crsarndt** [comment]
Hallo, 

Der fehler wurde in der Version 10.5.0 behoben.

**Comment by De-k** [comment]
Habs gelesen, nachdem ich gepostet habe. Update ist installiert.



Jörg
