### ISSUE TITLE
IP and Wlan SSID empty in version 10.4.0

### ISSUE THREAD

**Issue by Kalli01** [jomjol/AI-on-the-edge-device#690]
After updating from version 10.1.0 to version 10.4.0, the IP and the Wlan SSID are no longer displayed on the info page.
I have not yet tried whether this is also the case with version 10.5.0.
Just wanted to let you know

And thank you for adding the Wlan RSSI via MQTT.
![10 4 0  Info](https://user-images.githubusercontent.com/97545405/154805067-4e89a6d4-6457-4e23-b7b9-c54d7ce9ea5d.png)

**Comment by friedpa** [comment]
I can confirm this behaviour on my two systems

![grafik](https://user-images.githubusercontent.com/42890695/154813768-222d26a8-6c54-4fa7-91fb-b30b121e01a8.png)

**Comment by jomjol** [comment]
Fehler wird korrigiert in v10.5.1 - ist gerade im Test!

**Comment by friedpa** [comment]
Danke, wo war der Fehler? Habe versucht diesen mit meinen Basic Kenntnissen zu finden, ohne Erfolg :o)
