### ISSUE TITLE
Digit three incorrectly recognized

### ISSUE THREAD

**Issue by erd82** [jomjol/AI-on-the-edge-device#692]
Hello @jomjol,

first of all thanks for this amazing project ! I really like to productively use this project for different meters. And as in Germany the digitalization does not get momentum, we will have to rely on those projects still for long !!

The recognition generally works fine. But there is ONE digit which is often wrongly recognized: number 3.
The system assumes number 5.

Here you find two examples which constantly confuses the measurements.
![image](https://user-images.githubusercontent.com/63564291/154847547-44db849f-c3eb-42fb-9b0f-2a1166288250.png)
![image](https://user-images.githubusercontent.com/63564291/154847553-8a7ed502-753d-4782-861d-9747d6d65804.png)

Do you recommend uploading the relevant images in order to get then into the next training round (as explained [here](https://github.com/jomjol/AI-on-the-edge-device/wiki/ROI-Configuration#1-get-images-into-the-next-training-round))?

Cheers, red

**Comment by jomjol** [comment]
Yes, that's the only solution. I will put them into the training as soon, as I have the numbers.

Regarding producive use: if you thing about a commercial use, please let me know to agree on the license.

**Comment by erd82** [comment]
Hi @jomjol,

great I will send you the numbers asap.
No worries. It's just private and no commercial use :).

Cheers, red

**Comment by erd82** [comment]
@jomjol: Two more questions regarding the image upload for this issue: 

1. After enabling the image logging (in config.ini) the complete power meter image is stored on the SD card. Should I crop the image to the single digit? Or do you want to have the complete image of them meter? 
2. Do you only need the single digit 3 (which is incorrect) or do you need all digits of this character type (0 .. 9)?

BTW: Thanks for your quick feedback! I really appreciate it!

Cheers, red

**Comment by erd82** [comment]
Hello @jomjol,

I have attached three files for number 3 which is wrongly recognized.
[number 3.zip](https://github.com/jomjol/AI-on-the-edge-device/files/8112173/number.3.zip)

Additionally I have uploaded the raw material (588 cropped JPGs). Let me know if I can provide you some more information or prepare the material on a different way.
[raw_material.zip](https://github.com/jomjol/AI-on-the-edge-device/files/8112165/raw_material.zip)

Many thanks in advance! Cheers, red

**Comment by jomjol** [comment]
@erd82 : Your ROI settings are not according the suggestions in here: https://github.com/jomjol/AI-on-the-edge-device/wiki/ROI-Configuration

Especially the border around the images are much too small (target 20%):
![grafik](https://user-images.githubusercontent.com/30766535/155217547-60a145c3-631d-46bb-9433-e79a07637b49.png)![grafik](https://user-images.githubusercontent.com/30766535/155217597-109453f1-a324-453e-9492-c0ddd872c06e.png)![grafik](https://user-images.githubusercontent.com/30766535/155217639-b83acb59-5527-4072-80e8-cf7f13067c27.png)

Therefore I cannot use them for the training. Please update the ROIs and use the internal log mechanism to extract the already cut out images. Thanks!

**Comment by erd82** [comment]
Sorry @jomjol! My mistake! Now that you tell me, I just noticed that there is also an option to enable image recording for the digits. I accidentally enabled the LogImageLocation and LogfileRetentionInDays flags.

![image](https://user-images.githubusercontent.com/63564291/155225197-2dc0c171-cc76-42c4-ab11-72b84125210b.png)

Just as proposal: Can you maybe post this screenshot in the documentation https://github.com/jomjol/AI-on-the-edge-device/wiki/ROI-Configuration? This helps maybe prevents mistakes like I did.

I will send you the images once I have some.

**Comment by makuser** [comment]
@erd82 check out my comment in this issue https://github.com/jomjol/AI-on-the-edge-device/issues/689#issuecomment-1048950082, we seem to be using the same counter and I already took a few images and proposed them for inclusion in the next training, but also trained the model myself.
You may test it directly using the file I uploaded in the comment.

**Comment by jomjol** [comment]
Hint with the logging is taken over into the docu. Thx.
I close this issue. Please reopen, when data is available for training

**Comment by erd82** [comment]
Hi @jomjol,

the new digit images you can find here: [Number3.zip](https://github.com/jomjol/AI-on-the-edge-device/files/8127011/Number3.zip)

Cheers, red

**Comment by erd82** [comment]
@makuser, thanks for the hint !! I will try your tflite file (in parallel) and let you know.

**Comment by erd82** [comment]
> @makuser, thanks for the hint !! I will try your tflite file (in parallel) and let you know.

@makuser: I tried your trained model (https://github.com/jomjol/AI-on-the-edge-device/issues/689#issuecomment-1048950082). At the beginning it seemed to work well. But then the recognition also broke several times.

@jomjol: I will try your latest version from issue https://github.com/jomjol/AI-on-the-edge-device/issues/700 now.
