### ISSUE TITLE
Documentation - clarify purpose of "Create New Reference" and "Take Image" during setup

### ISSUE THREAD

**Issue by b-neufeld** [jomjol/AI-on-the-edge-device#694]
Great project! I got this set up over the weekend, mostly seamlessly. 

One thing that was not obvious to be during setup was the functionality of these two buttons below. "Create New Reference" is mentioned in the setup, but "Take Image" is not discussed in the setup, on the Wiki, or in any Issues so far. 

My experience was "Creating a New Reference" would take a new picture, but ignore any changes to LEDIntensity, Brightness, etc. "Take Image" seemed to respect changes to LEDIntensity, Brightness, etc.

![image](https://user-images.githubusercontent.com/18536548/154871033-e256bc04-dd53-466c-ae08-e392704db36d.png)

Super minor issue but I am sure it could be explained in a single sentence!

**Comment by stefanbode** [comment]
After setup my reference was 100% aligned and horizontal. Anyhow the images taken are at least 20° off and therefore useless. My assumption was that the "Pre-rotate Angle" also apply to the taken photos. Did I miss something?

**Comment by lethuer** [comment]
I also run into this setup issue.
My experience was that I had to try settings with "Create New Reference" which take effect after reboot and not directly after clicking the button.
"Take image" seems to have an effect directly without reboot but this settings are gone after rebooting the system.
