### ISSUE TITLE
With version 10.5.1 "setup mode" cannot be left any more

### ISSUE THREAD

**Issue by maxgrosse1** [jomjol/AI-on-the-edge-device#697]
After "setup mode" completion and rebooting, program always jumps to "setup mode" again. Previous versions did work properly.

**Comment by friedpa** [comment]
Try to set 
`SetupMode = false`
in the config.ini

**Comment by jomjol** [comment]
There was no change in that part of the html page. I just testet it on my system and the System leaves the configuration mode after pushing the last button: "Leave Setup Modus and Reboot to Normal"
