### ISSUE TITLE
Improve Releases

### ISSUE THREAD

**Issue by thost96** [jomjol/AI-on-the-edge-device#698]
Hi and thanks for your great work! 

It would be very nice if you could provide the firmware.bin and html.zip directly on each (new) release, so just for updates it's not necessary to download the whole project. Also, this would make automated updates using external tools much easier. 

Thanks a lot!

**Comment by spcqike** [comment]
whats wrong with the firmware folder?
https://github.com/jomjol/AI-on-the-edge-device/tree/master/firmware

you can change tags and switch between versions, too.
![grafik](https://user-images.githubusercontent.com/50098985/155302866-6fff9a7a-c58c-4d0a-a04b-826623403cc2.png)

**Comment by jomjol** [comment]
@thost96 : that is given. You can download the files directly from the repository: https://github.com/jomjol/AI-on-the-edge-device/tree/master/firmware

But be carefull, first to click the file once and only then use the download button. Don't right click on the file and download it by this!

@spcqike : my firmware directory is looking quite normal:
![grafik](https://user-images.githubusercontent.com/30766535/155314575-1a5758eb-4da9-492a-b195-b6cd45b0257a.png)

**Comment by spcqike** [comment]
@jomjol mine too. i just opened the dropdown to show, that one can switch between version.
![grafik](https://user-images.githubusercontent.com/50098985/155326143-376c26d8-ea69-4d17-bd51-131a3735a851.png)

**Comment by jomjol** [comment]
okay - understood. Than I close this issue now.
