### ISSUE TITLE
KNN Training #2

### ISSUE THREAD

**Issue by redflag237** [jomjol/AI-on-the-edge-device#699]
Hi, can you please train the following images with the next release? Thanks in advance.
![9_dig2_20220223-040151](https://user-images.githubusercontent.com/27703750/155315416-dfc8c64f-e259-4a1f-bdcc-f4c60c8b4bea.jpg)
![9_dig2_20220223-044151](https://user-images.githubusercontent.com/27703750/155315418-7ca8ba43-f818-4c75-8e7d-c45f2e3511c7.jpg)
![10_dig5_20220223-050651](https://user-images.githubusercontent.com/27703750/155315420-5cbd4c97-1463-487b-accf-646a42f3ce61.jpg)

**Comment by friedpa** [comment]
This is not the way it will work. You have to send jomjol the pictures in a zip-file. See Wiki.and several postings about this issue.

**Comment by jomjol** [comment]
https://github.com/jomjol/AI-on-the-edge-device/wiki/ROI-Configuration

Please open a new issue, once the data is available. Thx.
