### ISSUE TITLE
Update "Analog ROI" does overwrite "Digital ROI" in config

### ISSUE THREAD

**Issue by michaeljoos72** [jomjol/AI-on-the-edge-device#7]
Hi jomjol

This is still an open issue for me --> When I update the analog ROIs it overwrites the values to digital section in config:

![image](https://user-images.githubusercontent.com/20517474/92627196-4ea5e800-f2cb-11ea-9832-6eb8c469b2eb.png)

**Comment by jomjol** [comment]
Hi Michael,
Bug corrected "again" :-). I found an error in my previous correction. Now I testet it a bit more, should hopefully work. Please give me a short feedback, so that I can close the issue.
Best regard,
  jomjol.

**Comment by michaeljoos72** [comment]
Jetzt funktioniert es . . . musste aber etwas suchen:

--> Mir ist aufgefallen, dass beim HTML-Upload (html.zip) via OTA-Update die *.js-Dateien nicht hochgeladen bzw. überschrieben werden. Soll ich für das ein neues Issue erstellen oder lösen wir das hier drin?

**Comment by jomjol** [comment]
Gut, dass ich jetzt den ersten Fehler beseitigt habe.

Das fehlende Überschreiben der *.js Dateien kann ich nicht bestätigen, ich habe es gerade getestet.

**Comment by michaeljoos72** [comment]
_Das fehlende Überschreiben der *.js Dateien kann ich nicht bestätigen, ich habe es gerade getestet._
Ich auch nicht :)))) Man sollte nach dem Zip-Upload dann eben auch noch den 2. Button drücken und die Files entpacken!

--> Closed
