### ISSUE TITLE
Followup: Digit three incorrectly recognized

### ISSUE THREAD

**Issue by erd82** [jomjol/AI-on-the-edge-device#700]
Hi @jomjol,

Since the issue https://github.com/jomjol/AI-on-the-edge-device/issues/692 is already closed, I opened another issue for follow up.
The new digit images you can find here: [Number3.zip](https://github.com/jomjol/AI-on-the-edge-device/files/8127011/Number3.zip)

Cheers, red

**Comment by jomjol** [comment]
I have uploaded them for the next training. It might take some time until I have collected some more new images.

**Comment by erd82** [comment]
Many thanks, @jomjol !!
How will I notice that the new images are part of the training model?
When shall I check for an update?

**Comment by jomjol** [comment]
Please test the following file: https://github.com/jomjol/AI-on-the-edge-device/raw/rolling/firmware/dig-s0-q-20220224.tflite
