### ISSUE TITLE
Überbelichtung

### ISSUE THREAD

**Issue by msmthng** [jomjol/AI-on-the-edge-device#705]
Hallo, ich habe seit heute - ohne etwas an der Konfiguration geändert zu habe - total überbelichtete Bilder:

<img width="587" alt="image" src="https://user-images.githubusercontent.com/40269445/155596958-ffba3783-bc74-4f47-b651-8bd3035e299d.png">

Woran könnte das liegen?

Danke für die Hilfe

**Comment by jomjol** [comment]
Fehler unbekannt - Kamera oder LED defekt?
Ferndiagnose ist schwierig - nur wenn du nichts an der Konfiguration gemacht hast, dann muss es ein Hardwaredefekt sein.

**Comment by msmthng** [comment]
Ganz komisch, ich habe gesehen, dass der Ordner /log/source volgelaufen war. 
LogfileRetentionInDays war auf 2 gesetzt, aber die alten  Daten wurden nicht gelöscht.

Seit ich die Files manuell gelöscht habe und die SD Karte nicht mehr so voll ist, a) regiert das UI wieder viel schneller b) habe ich diese Belichtungsprobleme nicht mehr.
