### ISSUE TITLE
Analog Readings

### ISSUE THREAD

**Issue by RichardSauer** [jomjol/AI-on-the-edge-device#713]
Do you have such reference images for the analog meters?
![34C7CAA5-38D1-4C1F-A329-890C4865E56C](https://user-images.githubusercontent.com/42067245/156254065-1ddbb83d-5e1b-4ad3-b4f4-2c4efbc1ec42.jpeg)
![image](https://user-images.githubusercontent.com/42067245/156317466-fbf7f529-b697-4058-8da8-24161cd12f56.png)

**Comment by jomjol** [comment]
This kind of counter is included in the training.
