### ISSUE TITLE
Webinferface very slow, configuration cannot be finished

### ISSUE THREAD

**Issue by Maddinthebrain** [jomjol/AI-on-the-edge-device#721]
Hi, 
I tried to configure my watermeter ai. Well, the web interface is veeeerryy sloooow and runs very often into timeouts. When I try to configure everything, it doesn't work at all. First I cannot change the reference image due to several issues:
- Most of the time the captured image is black, although the Flash LED lights up regularly. When I use a flashlight for illumination I get an image. So its not a camera issue. 
- When I get a good image, I can align it perfectly, but the storage of this won't work. When I come continue the config process, the default pic is shown.

During all this process, the web interface is nearly unusable. It isn't responsive at all. It happens very often, that there is no reaction and the pages are not loaded completely as images are missing over sometimes even text.

What's the problem here? Is it maybe an SD-Card issue? I tried two different with the same result. The firmware is the latest as well the SD-card files. 

Thx

**Comment by jomjol** [comment]
I agree with friedpa. Another option is a blocking by a virus software.
You can check the first one, by placing the ESP32CAM next to your router and check, if the interface is more responsive.

**Comment by Maddinthebrain** [comment]
> For me it looks like more that the WLAN connection is not stable/ useable.

Well, the access point is about 40cm away. 

> I agree with friedpa. Another option is a blocking by a virus software. You can check the first one, by placing the ESP32CAM next to your router and check, if the interface is more responsive.

I tried different devices, 2 PCs and one smart phone.

What about the reference Pic and the not illuminated LED? BTW the Led Dimmer is set to 50% on the config page...

**Comment by jomjol** [comment]
Well, if it is not the WLan and not the software (different PCs) and it is a freshly setup system, this is totally unique and therefore currently only a defect hardware is in my mind.

**Comment by Maddinthebrain** [comment]
Hmm, that's annoying, as this is now the second esp32 board I bought. At 
the first one, the cam wasn't working. Now this... Is there a chance, to 
get a functional one?
Am 10. März 2022 22:06:29 schrieb jomjol ***@***.***>:

**Comment by jomjol** [comment]
I understand, that this is annoying and the propability to have two broken ones is realy low. I have bought more than 5 and all of them were okay. I buy them at Amazon

**Comment by Maddinthebrain** [comment]
I checked the log file on the SD-Card and found this:

`2022-03-12T16:08:13: Time zone set to CET-1CEST,M3.5.0,M10.5.0/3
2022-03-12T16:08:13: =============================================================================================
2022-03-12T16:08:13: =================================== Main Started ============================================
2022-03-12T16:08:13: =============================================================================================
2022-03-12T16:08:13: Not enought PSRAM available. Expected 4.194.304 MByte - available: 2098034
Either not initialzed or too small (2MByte only) or not present at all. Firmware cannot start!!
2022-03-12T16:08:23: Image with size 0 loaded --> reboot to be done! Check that your camera module is working and connected properly.`

I don't what that means.

**Comment by jomjol** [comment]
That means, you have a PSRAM module with only 2MB (=16MBit). This will not work.
There are some faulty modules on the market. No change to run the system with this you need new hardware.
