### ISSUE TITLE
Rf433 or rf868 integration

### ISSUE THREAD

**Issue by Frogowitsch** [jomjol/AI-on-the-edge-device#723]
Hello,
The project so far is very good working, my only problem is, that my power meter is rather far away from my network and Wifi is no go there. Is there any possibility to send the value via a rf433 module ? There are many very cheap modules around that could be used. 
Mqtt integration would happen on the rf433 receiver (either an esp32 module too or s raspberry pi for example).
Perhaps there is more interest in this and we could start an integration.

**Comment by jomjol** [comment]
Two topics to solve for this:
1) Technical: Depending on your configuration (internal / external illumination) you only have one free GPIO (13), therefore a connection to another board is difficult, without major restrictions.
2) Time and capacity: I simply currently don't have time and capacity to handle this.

Any good and working implementation is welcome and will be tested and implemented in the main firmware.

Therefore I close this issue (but you can post anyway for conversion).
