### ISSUE TITLE
Time plan for measuring and external trigger 

### ISSUE THREAD

**Issue by OstertagM** [jomjol/AI-on-the-edge-device#727]
I would like to measure not f.e. each 4 minutes. I would like to measure on exact an timings. So f.e. If I want to measure each 4 minutes that's means not from boot it means xx:04, xxx:08 and so on..

So also it would be nice if we can trigger the measure by MQTT or with calling a special url.
And measuring directly after boot. (this works)

**Comment by jomjol** [comment]
This is not planned currently from my side. I will put in on the feature request list, but this is just for storage. Maybe somebody else has time to implement it.

**Comment by jomjol** [comment]
Part of the long term list. Upload with the next update

**Comment by watcherkb** [comment]
+1 I'M also interested in this feature

**Comment by jomjol** [comment]
No prognosse, as long as I need to work on that. Feel free to make a commit.
