### ISSUE TITLE
Download complete config folder using "File Server"

### ISSUE THREAD

**Issue by erd82** [jomjol/AI-on-the-edge-device#731]
In order to update my device I would like to download / backup the complete config folder (incl. all files) using the "File Server". Is such a function available in the UI that I have overseen?

![image](https://user-images.githubusercontent.com/63564291/158829350-a656065c-04ec-4566-8171-e4252a451cb6.png)

**Comment by jomjol** [comment]
No, this option is not available and implemented.

**Comment by erd82** [comment]
It's a pity since it could help a lot to control the files better remotely. Anyway, thanks a lot !!

**Comment by jomjol** [comment]
There I only use an available example from espressif github code. It simply does not provide this feature and I don't have capa and real need to extend. But I would incorporate, if somebody is willing to invest time.
