### ISSUE TITLE
Rate too high - value not recognized 

### ISSUE THREAD

**Issue by erd82** [jomjol/AI-on-the-edge-device#732]
I have just updated my device to the latest firmware / html version (v10.2.0 - 2022-01-14 to v10.5.2 - 2022-02-22) as explained in the [wiki page for update](https://github.com/jomjol/AI-on-the-edge-device/wiki/Update). As recommended I also saved the configuration again and rebooted the device.

The device does not define the next value, although the "Raw Value" was correctly recognized. The UI shows the error "Rate too high" although exactly the closest and value is displayed.
![image](https://user-images.githubusercontent.com/63564291/158850492-7948b2c0-9e79-4a96-be02-5a283d65a2e9.png)

**Did I miss anything during the update procedure?** 

This is my device configuration:
```
[MakeImage]
;LogImageLocation = /log/source
WaitBeforeTakingPicture = 5
;LogfileRetentionInDays = 15
Brightness = 0
;Contrast = 0
;Saturation = 0
;LEDIntensity = 
ImageQuality = 5
ImageSize = VGA
FixedExposure = false

[Alignment]
InitialRotate = 270.6
InitialMirror = true
SearchFieldX = 20
SearchFieldY = 20
AlignmentAlgo = default
FlipImageSize = false
/config/ref0.jpg 214 182
/config/ref1.jpg 446 230

[Digits]
Model = /config/dig-s0-q-20220224.tflite
LogImageLocation = /log/digit
;LogfileRetentionInDays = 3
ModelInputSize = 20 32
main.dig1 201 223 26 47
main.dig2 233 223 26 47
main.dig3 266 223 26 47
main.dig4 297 223 26 47
main.dig5 330 223 26 47
main.dig6 362 223 26 47
main.dig7 394 223 26 47

;[Analog]
Model = /config/ana-s3-q-20220105.tflite
;LogImageLocation = /log/analog
;LogfileRetentionInDays = 3
ModelInputSize = 32 32
main.ana1 432 230 92 92
main.ana2 379 332 92 92
main.ana3 283 374 92 92
main.ana4 155 328 92 92

[PostProcessing]
main.DecimalShift = -1
PreValueUse = true
PreValueAgeStartup = 720
AllowNegativeRates = false
main.MaxRateValue = 0.05
;main.MaxRateType = RateChange
;main.ExtendedResolution = false
;main.IgnoreLeadingNaN = false
ErrorMessage = true
CheckDigitIncreaseConsistency = true

[MQTT]
Uri = mqtt://192.168.XXX.XXX:1XXXX
MainTopic = powermeter
ClientID = strom
user = XXXXXXXXX
password = XXXXXXXXX

[GPIO]
;IO0 = input disabled 10 false false 
;IO1 = input disabled 10 false false 
;IO3 = input disabled 10 false false 
;IO4 = built-in-led disabled 10 false false 
IO12 = external-flash-ws281x disabled 10 false false 
;IO13 = input-pullup disabled 10 false false 
LEDType = WS2812B
LEDNumbers = 2
LEDColor = 255 255 255

[AutoTimer]
AutoStart = true
Intervall = 3

[Debug]
Logfile = false
LogfileRetentionInDays = 3

[System]
TimeZone = CET-1CEST,M3.5.0,M10.5.0/3
;TimeServer = undefined
;AutoAdjustSummertime = false
;Hostname = undefined
SetupMode = false
```

**Comment by friedpa** [comment]
Remove the Semicolon in front of the row: ;main.MaxRateType = RateChange

**Comment by erd82** [comment]
Many many thanks for the tip! I have just performed the change as you recommended. It already looks better and now I need to monitor ist. Thanks & kind regards

**Comment by friedpa** [comment]
Pleasure! Advantage from a good community, and we are all part of it.

**Comment by erd82** [comment]
@friedpa: Again many thanks for your help! MaxRateType = RateChange helped to solve the issue.

PS: But I have another challenge now :) ... https://github.com/jomjol/AI-on-the-edge-device/issues/733
