### ISSUE TITLE
Detection stops when meter starts spinning rapidly

### ISSUE THREAD

**Issue by erd82** [jomjol/AI-on-the-edge-device#733]
The recognition works very well (using digital ROIs) over longer periods. This is an example of my power meter (= three-phase meter).
![image](https://user-images.githubusercontent.com/63564291/159067592-4b37c274-fde6-4f73-9bb4-8f0b038e589c.png)

But it only works reliably when the power consumption is low and the three-phase meter turns slowly.
![turn_slowly](https://user-images.githubusercontent.com/63564291/159065514-0d31dbdd-5051-4742-b879-5b6e0dd99b10.gif)

As soon as you switch on an energy consuming device with more than 1000W (such as dishwasher, washing machine, etc.) the three-phase meter turns too fast ...
![turn_fast](https://user-images.githubusercontent.com/63564291/159067728-098006a7-899a-4488-9a0b-b4d419d3b023.gif)

... and the recognition breaks.
![image](https://user-images.githubusercontent.com/63564291/159067632-19a084e2-de39-40b8-8ef8-9784a6c79f4f.png)

This is the result on AI on the edge.
![image](https://user-images.githubusercontent.com/63564291/159065061-5fda6f4a-60e4-40c1-835c-9089f98a7292.png)

**Is there still anything in configuration which I can improve?**

This is my configuration:

```
[MakeImage]
;LogImageLocation = /log/source
WaitBeforeTakingPicture = 5
;LogfileRetentionInDays = 15
Brightness = 0
;Contrast = 0
;Saturation = 0
;LEDIntensity = 
ImageQuality = 5
ImageSize = VGA
FixedExposure = false

[Alignment]
InitialRotate = 270.6
InitialMirror = true
SearchFieldX = 20
SearchFieldY = 20
AlignmentAlgo = default
FlipImageSize = false
/config/ref0.jpg 214 182
/config/ref1.jpg 446 230

[Digits]
Model = /config/dig-s0-q-20220224.tflite
LogImageLocation = /log/digit
;LogfileRetentionInDays = 3
ModelInputSize = 20 32
main.dig1 201 223 26 47
main.dig2 233 223 26 47
main.dig3 266 223 26 47
main.dig4 297 223 26 47
main.dig5 330 223 26 47
main.dig6 362 223 26 47
main.dig7 394 223 26 47

;[Analog]
Model = /config/ana-s3-q-20220105.tflite
;LogImageLocation = /log/analog
;LogfileRetentionInDays = 3
ModelInputSize = 32 32
main.ana1 432 230 92 92
main.ana2 379 332 92 92
main.ana3 283 374 92 92
main.ana4 155 328 92 92

[PostProcessing]
main.DecimalShift = -1
PreValueUse = true
PreValueAgeStartup = 720
AllowNegativeRates = false
main.MaxRateValue = 0.05
main.MaxRateType = RateChange
;main.ExtendedResolution = false
;main.IgnoreLeadingNaN = false
ErrorMessage = true
CheckDigitIncreaseConsistency = true

[MQTT]
Uri = mqtt://192.168.XXX.XXX:1XXX
MainTopic = powermeter
ClientID = strom
user = XXXXXXXXX
password = XXXXXXXXXX

[GPIO]
;IO0 = input disabled 10 false false 
;IO1 = input disabled 10 false false 
;IO3 = input disabled 10 false false 
;IO4 = built-in-led disabled 10 false false 
IO12 = external-flash-ws281x disabled 10 false false 
;IO13 = input-pullup disabled 10 false false 
LEDType = WS2812B
LEDNumbers = 2
LEDColor = 255 255 255

[AutoTimer]
AutoStart = true
Intervall = 3

[Debug]
Logfile = false
LogfileRetentionInDays = 3

[System]
TimeZone = CET-1CEST,M3.5.0,M10.5.0/3
;TimeServer = undefined
;AutoAdjustSummertime = false
;Hostname = undefined
SetupMode = false
```

**Comment by friedpa** [comment]
Your reading intervall is 3 minutes (which is already the minimum), so I don´t understand currently what you want to achieve? As you said already the whole setup is for "long period" recognizion.

**Comment by jomjol** [comment]
I also don't see improvements in your setting. How else can I help?

**Comment by erd82** [comment]
Do you have an additional logic which could help?
Or would it be possible to implement an additional logic which considers the last X consecutive RAW values?
I prepared two examples in a mockup.

Example 1: one consecutive RAW value
![Simulation-1](https://user-images.githubusercontent.com/63564291/159127161-fe0d7f1f-1db2-4cbb-8337-4805186a358d.gif)

Example 2: two consecutive RAW values
![Simulation-2](https://user-images.githubusercontent.com/63564291/159126982-f305c5ba-b917-4d6a-93f9-0b6ec7a3c71e.gif)

Maybe this could help continuing a broken detection. What do you think?

**Comment by jomjol** [comment]
That could help. But I'm going into another direction. I plan to use neural networks, that can digitize also numbers inbetween, e.g. 0.2, 0.3, ... . Then there is no "N" anymore and the problem should be solved.

But in order to make the expectations not too high: I'm doing this for free in my spare time for free. I'm the only developer working on this and currently I just don't have time for my hobby to develop further. So this could take a longer time. Meanwhile I will close this issue, because I'm not going to follow this approach.

Anyway thanks a lot for your ideas and the detailed mockup!

**Comment by erd82** [comment]
Hi @jomjol, 

I fully agree and I fully understand your position :-). I do NOT wanna put any pressure on this topic and especially not on you. I know that this is only hobby ... the same for me.

Unfortunately I don't have the detailed development experise. Therefore I am trying to contribute with my conceptual knowledge and "productization expertise". 

Anyway, please see my proposal just with low priority. But maybe it could help to improve the overall solution.

Finally let me say amazing idea and implementation! If this issue (breaking recognition) can be fixed, I would be able to use it daily at home.

Many thanks, red

**Comment by erd82** [comment]
Hi @jomjol, if you find a solution using neural networks in the future to resolve this kind of detection abort, I would be super happy! I guess the way to get there doesn't matter :-). 

Currently it breaks too often (more than 7 times a week, I have to manually set the preValue again). I am not sure if other people have the same issue?

![image](https://user-images.githubusercontent.com/63564291/159752599-9bb070aa-7c1e-4f5e-bd22-5ccf1335e013.png)

Many thanks for your great work!

**Comment by jomjol** [comment]
ok - just keep following the versions, you will see, if something has changed there.

**Comment by erd82** [comment]
Perfect and many thanks!! I will do.

**Comment by erd82** [comment]
@jomjol, are there any plans to follow this issue up?

**Comment by erd82** [comment]
Hello @jomjol, I can just say "GREAT WORK". 

After several months (on 30.10.2022) I installed version 12.0.1 on two of my ESP32-CAM modules. And finally also this issue could be completely fixed (I guess after you implemented the use of neural networks?). It's properly working since 1.5 months now.

**Comment by jomjol** [comment]
Thanks!
