### ISSUE TITLE
Is this project portable to something different than an ESP32 board?

### ISSUE THREAD

**Issue by metaminimalist** [jomjol/AI-on-the-edge-device#734]
Is this project portable to something different than an ESP32 board?

I think of a board which is possibly booted over network, powered via POE and has a camera (->Pi4, or M5Stack PoE Camera).
That would mean that this project would have to run as a process besides other processes on some linux and not as a superloop on an MCU.

I understood that it takes the ESP32 up to 4 min to read the meter, and that the 8MB RAM is even tight.

goals: 
- my well shaft with heavy metal plate lid will never have WLAN, hence the cable
- I hate batteries, hence the cable
- measure peak loads more exactly and more often, I want to be able to recognize broken irrigation pipes and burst hoses in the garden quickly
- additional sensors possible (like a cistern level meter, or a optical/hall sensor on those turining indicating wheels to get the flow rate more exactly)

**Comment by jomjol** [comment]
The algorithm for sure and I have devided the code into subsection, that make it easier to handle and separate the hardware related topics a bit easier. But it would take quite some additional effort.

**Comment by metaminimalist** [comment]
thank you! danke!
