### ISSUE TITLE
Strange DNS Querys from ESP-Device to Pi-Hole

### ISSUE THREAD

**Issue by in-famous-raccoon** [jomjol/AI-on-the-edge-device#735]
Hello,

i use pi-hole as my DNS server and today i noticed strange query's from my ESP Device.
In the WebUI i see something like this:
`Time			        Type   Domain  Client	Status		        Reply`
`2022-03-19 17:00:51 	A	   yõú?      <empty>	Unknown (NaN)	? (NaN)`
When i take a look in the pihole.log i see that the Client is my ESP Device with AI-on-the-edge-device:
`17:00:51: query[A] <name unprintable> from 192.168.30.5`

Any Idea what could be the issue here or how to track down the issue?

Reboot doesn't fix it and my version is the latest (10.5.2)

Thanks for your great Software!!
Greetings

**Comment by jomjol** [comment]
The are two outgoing connections:
1) Time sync during startup (only startup!)
2) MQTT client
There are no other connections. Can you identify it to one of these?

**Comment by in-famous-raccoon** [comment]
Thanks for your answer.
I have restarted pi-hole today and after that i thought the issue was gone, no errors after one hour...But as soon as i access the website for the ESP Device i get errors in the log at pi-hole...very strange.

My MQTT config looks like this:
```
[MQTT]
Uri = mqtt://192.168.1.10:1883
MainTopic = water
ClientID = ESP-WATER
user = mqtt-user
password = PASSWORD
```
I will try to access the ESP Device with the IP maybe this will solve the error...

**Comment by jomjol** [comment]
Currently no acitivies --> I'll close the issue
