### ISSUE TITLE
Flashed multiple times and no lights on ESP32-Cam

### ISSUE THREAD

**Issue by Dutchy-79** [jomjol/AI-on-the-edge-device#737]
I flashed the firmware with python and flash download tool 3.9.2 and copied all ityems from sd card folder to blank card, Boot with 2000ma 5v powersupply and no lights turn on and even after few minutes no new device on router.

What am I doing wrong here?

**Comment by jomjol** [comment]
How should I help with this information? I flash the camera with python copy the items to the sd card and everything works fine :-).
No seriously: I need the log file from the serial port during startup. Than I might help.

**Comment by Dutchy-79** [comment]
Sorry, I'm quite new to this so I don't know how to get the log during startup.

**Comment by jomjol** [comment]
Connect the same device, that you use for flashing and read the serial monitor. You will find plenty of instructions in the internet.

**Comment by Dutchy-79** [comment]
> Connect the same device, that you use for flashing and read the serial monitor. You will find plenty of instructions in the internet.

Got it,

`rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:7580
ho 0 tail 12 room 4
load:0x40078000,len:15360
load:0x40080400,len:3744
entry 0x4008067c
I (28) boot: ESP-IDF 4.3.2 2nd stage bootloader
I (29) boot: compile time 19:07:45
I (29) boot: chip revision: 1
I (32) boot_comm: chip revision: 1, min. bootloader chip revision: 0
I (39) boot.esp32: SPI Speed      : 40MHz
I (43) boot.esp32: SPI Mode       : DIO
I (48) boot.esp32: SPI Flash Size : 4MB
I (52) boot: Enabling RNG early entropy source...
I (58) boot: Partition Table:
I (61) boot: ## Label            Usage          Type ST Offset   Length
I (69) boot:  0 nvs              WiFi data        01 02 00009000 00004000
I (76) boot:  1 otadata          OTA data         01 00 0000d000 00002000
I (84) boot:  2 phy_init         RF data          01 01 0000f000 00001000
I (91) boot:  3 ota_0            OTA app          00 10 00010000 001db000
I (99) boot:  4 ota_1            OTA app          00 11 001f0000 001db000
I (106) boot: End of partition table
I (110) boot_comm: chip revision: 1, min. application chip revision: 0
I (117) esp_image: segment 0: paddr=00010020 vaddr=3f400020 size=484fch (296188) map
I (239) esp_image: segment 1: paddr=00058524 vaddr=3ffb0000 size=049d4h ( 18900) load
I (247) esp_image: segment 2: paddr=0005cf00 vaddr=40080000 size=03118h ( 12568) load
I (253) esp_image: segment 3: paddr=00060020 vaddr=400d0020 size=139f0ch (1285900) map
I (746) esp_image: segment 4: paddr=00199f34 vaddr=40083118 size=18b48h (101192) load
I (790) esp_image: segment 5: paddr=001b2a84 vaddr=50000000 size=00010h (    16) load
I (804) boot: Loaded app from partition at offset 0x10000
I (804) boot: Disabling RNG early entropy source...
I (816) psram: This chip is ESP32-D0WD
E (816) psram: PSRAM ID read error: 0xffffffff
E (816) cpu_start: Failed to init external RAM!
Re-enable cpu cache.

abort() was called at PC 0x40082d67 on core 0

Backtrace:0x40082bfd:0x3ffe3ba0 0x4008f619:0x3ffe3bc0 0x400963fd:0x3ffe3be0 0x40082d67:0x3ffe3c50 0x4007956d:0x3ffe3c80 |<-CORRUPTED


ELF file SHA256: c8d9d7442731a071

Rebooting...
ets Jun  8 2016 00:22:57
`

This keeps returning. SD Card is a new 32 GB. Also tried a older 16GB

**Comment by jomjol** [comment]
The problem is not the SD-card, you don't even get to this check. The problem is the PSRAM:
```
E (816) psram: PSRAM ID read error: 0xffffffff
E (816) cpu_start: Failed to init external RAM!
```
Either your board has no PSRAM (minimum 4 MByte needed) or it is broken.

**Comment by Dutchy-79** [comment]
It has PSRAM and when using a arduino sketch it works when using "ESP32 Dev Module" 
When I use AI Thinker cam it gives the same 0xffffffff error. Guess mine has a different pin set for the PSRAM

**Comment by jomjol** [comment]
There is no parameter for the PSRAM pins within the firmware.
