### ISSUE TITLE
In error state the software does not return last value

### ISSUE THREAD

**Issue by PetrMa** [jomjol/AI-on-the-edge-device#738]
Hello,
I´am using the version master - v10.5.2 - 2022-02-22 of the software with the settings:
![image](https://user-images.githubusercontent.com/24729480/159568524-04eed944-98cd-4311-9991-417f7c302425.png)

but when I got RAW value lower then previous value, the error message is displayed but no value is returned. Why? How i can ensure that the last know value is returned if the system got some error message?
![image](https://user-images.githubusercontent.com/24729480/159568867-a1a915f7-296c-470c-ae88-0c6c1b28dd63.png)

Thanks for your help, Regards,
Petr

**Comment by jomjol** [comment]
That is alsways the case and the switch is not used anymore. I will remove it in the next version.

**Comment by jomjol** [comment]
Because it only returns a value if it is rated as error free - that was a user request and changed from version 9 to version 10. It helps to
1. find errors faster
2. give a better average behavious, because it reduces large jump artefacts, if there was an error for a longer time.
