### ISSUE TITLE
Feature Request: Configuration w/o analog counters

### ISSUE THREAD

**Issue by jomjol** [jomjol/AI-on-the-edge-device#74]
Option to disable the analog counters, e.g. for gas meters

**Comment by Steffeng5** [comment]
+1 as my water meters have no analog POIs
<img width="549" alt="Bildschirmfoto 2020-12-30 um 23 12 12" src="https://user-images.githubusercontent.com/822659/103383842-880d9800-4af4-11eb-8220-b35b5ddf71c7.png">

**Comment by SilBlkPanther** [comment]
+1 for usage with a gas meter. 
can work around it in Node-Red / MySQL but would make things simpler

**Comment by plin2** [comment]
+1 for usage with a gas meter.
![gas](https://user-images.githubusercontent.com/3195189/103476369-3cd5dc80-4db5-11eb-9f59-2bf07da53309.png)

**Comment by jomjol** [comment]
Implemented in recent rolling (2021-01-05)

**Comment by Steffeng5** [comment]
Wow thanks! Can you estimate when there will be a commit/ or a release for this?

**Comment by plin2** [comment]
Great ... keep your fingers crossed that China post is delivering fast enough

**Comment by Steffeng5** [comment]
@jomjol I just installed current firmware.bin (and the other 2) from rolling branch. 
Where can I find this feature? Removing the last analog ROI is not possible and i cannot find any other config to disable analog counter

**Comment by jomjol** [comment]
@Steffeng5 
Did you also update the html files as written on top of the history?
Then you should have 2 options to disable the analog counters:

1. Edit settings:
![grafik](https://user-images.githubusercontent.com/30766535/103675489-4bbcba80-4f80-11eb-9fe9-b6a0c01a4d14.png)

2. Analog counter settings itself:
![grafik](https://user-images.githubusercontent.com/30766535/103675632-79096880-4f80-11eb-9fa6-ac81c1dbad3c.png)

If it's still not working, let me know!

Best regards,
  jomjol
