### ISSUE TITLE
implementation of esp_wifi_set_max_tx_power

### ISSUE THREAD

**Issue by mdax82** [jomjol/AI-on-the-edge-device#740]
Version 10.5.2 works like a charme right now many thanks! 👍 

One feature request I have is to cover following situation: 
From time to time the esp32 connects to the wireless accesspoint with a subobtimal RSSI about -80 while there is another one available with about -50 (mesh). 

I had similar situations with esp8266 at "esp easy" and there is a "Max WiFi TX Power:" setting. Reducing the max TX to 10dbm helped to make connectivity stable to the better connected AP.

Further references:
https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/network/esp_wifi.html#_CPPv425esp_wifi_set_max_tx_power6int8_t

https://github.com/letscontrolit/ESPEasy/blob/85828aa8abe8377002ecbb27c5df624742f182a7/src/src/ESPEasyCore/ESPEasyWifi.cpp#L395

If there is some work in that area may worth to have a look 😃

**Comment by jomjol** [comment]
This is a very special request. I'm not going to implement it by myself. But if you make a fork I will try to merge it later on.

**Comment by jomjol** [comment]
Close the issue
