### ISSUE TITLE
Negativ Werte 

### ISSUE THREAD

**Issue by Winny1904** [jomjol/AI-on-the-edge-device#742]
Hallo besteht die Möglichkeit, das er negativ Werte gar nicht erst speichert ? 

Beispiel. Er erkennt einmal falsch. Danach aber immer wieder richtig. Es ist so nicht praktikabel immer wieder den richtigen Wert einzustellen.

In der Confiserie müsste man eine Einstellung haben die heißt: Akzeptiere keine Negativen Wert.

Ich hab nun 3 mal alles in verschiedenen Versionen installiert. Alle ablese Punkte neu angelegt, die Kamera anders montiert, den Fokus eingestellt.

**Comment by friedpa** [comment]
Könntest Du das nochmals in andere Worte fassen, ich kann Dir nicht folgen. Z.B. wo werden negative Werte gespeichert?

**Comment by Winny1904** [comment]
Es sollen am besten kein Wert akzeptiert werden, der kleiner ist als der vorherige.

**Comment by friedpa** [comment]
![grafik](https://user-images.githubusercontent.com/42890695/160257884-34c20e8a-bb7b-4312-915b-766b70b3e04e.png)

**Comment by Winny1904** [comment]
![Screenshot_20220326-224558_Edge](https://user-images.githubusercontent.com/93474265/160258157-c89ac37e-89c3-457d-8400-16e5782ca72a.jpg)
![Screenshot_20220326-224623_Edge](https://user-images.githubusercontent.com/93474265/160258158-cf85c67c-f653-4feb-8bb0-34d074f4f610.jpg)

**Comment by friedpa** [comment]
Please help me, what is wrong? PreValue 275.9909 RawValue: 275.2653, which is less than PreValue -> this would be a negative value therefore Error and nothing is submitted. Did I miss something?

**Comment by Winny1904** [comment]
Bei Mqtt wird doch der PreValue Wert übertragen.

Der wird doch hier falsch angezeigt! Richtig ist 275.2653.....

Kann das nicht so eingestellt werden der der Pre Wert nie kleiner sein kann als der Wert zu vor ? 

Ich habe so oft das Problem das Negativ Error angezeigt wird

**Comment by jomjol** [comment]
Aber den PreValue solltest du nicht verwenden, sondern nur "Value" und der wir bei einer negativen Rate nicht übermittelt.

**Comment by Winny1904** [comment]
Dann liegt es daran. 
Warum wird mir Value nicht angezeigt?

**Comment by Winny1904** [comment]
![Screenshot_20220327-205507_Edge](https://user-images.githubusercontent.com/93474265/160296357-0ebb2c3d-297f-4ae8-af26-8be215c07763.jpg)

**Comment by Winny1904** [comment]
Ich denke ich gab es raus gefunden.

Ich habe in der config den Hacken bei PreValue entfernt
