### ISSUE TITLE
Reference image not display properly in overview page

### ISSUE THREAD

**Issue by alaska3586** [jomjol/AI-on-the-edge-device#743]
Cool project! After reading the article, a new ESP32 camera was  setup and is working fine.
However, there is an issue that repearedly the reference image is not displayed well in the overview page, see the 2 iamges attached:
- reference image is shown moved and rotated
- the 2 reference markers are shifted
- all digital and analog ROIs are shifted

As a result,  value recognition does not work , always returning NaN value.
I reconfigured several times, then finally installed a rand new config.ini file from Github and started again.
I saved all settings made in the web UI after change to config.ini, went through all steps and finally rebooted.
Again, as described above, the reference image is shifted ... 

The camera is about 15cm distanced from the water meter device, camera is located fix and did not move.
Proof is that a new refernce picture taken does not show any difference to the stored reference picture.
![ESP32_overview_page](https://user-images.githubusercontent.com/100996418/160280936-02fa5e0e-a55a-4168-ba1a-ef4589868058.JPG)
![ESP32_reference_digit](https://user-images.githubusercontent.com/100996418/160280937-a5176537-ffa1-4998-aa82-388868d16a83.JPG)

Any idea how to go ahead from here is highly appcreciated ...

**Comment by friedpa** [comment]
The picture is by far not good. Should look like trhis:

![grafik](https://user-images.githubusercontent.com/42890695/160285615-e7a01c95-dc89-4d6f-80aa-488e1db10731.png)

**Comment by alaska3586** [comment]
Thanks for posting  - this is much sharper than all I got when trying different settings / distances betwee ncamera sensor and meter.

From which distance was your photo taken? 
Are there any means available to sharpen the image?

**Comment by jomjol** [comment]
A typical distance is about 10 - 15cm. You need to adjust the sharpness by rotating the lense (see Wiki).
The rotated image is a fact of the bad image quality. Because of this the reference cannot be identified correctly and the image is rotated with wrong positions of the reference images.
