### ISSUE TITLE
low detection quality with recent version

### ISSUE THREAD

**Issue by kapet** [jomjol/AI-on-the-edge-device#744]
I've had the detection running with a slightly older version (9.x) for a while and although detection quality wasn't always great, it worked very well overall. Thank you!

But a few days ago I've updated to version 10.5.2 and the current tflite files and detection quality fell off a cliff... Almost every single attempt failed, analog meters kinda random, and most notably it even messed up digits that had not been an issue before (e.g. "2" detected as "7"). I've reverted to some older tflite files (dig1330s1q and ana0700s1lq) and detection immediately improved again.

Am I doing something wrong? Like using wrong files?

Anything I can provide to help debug? Is there a way to test the models on a PC?

I'm attaching an image to give an idea how my watermeter looks like.

Thanks!
![alg_roi](https://user-images.githubusercontent.com/6137365/160288361-c146f52f-a5ab-49d3-99a8-6cf2642775b8.jpg)

**Comment by jomjol** [comment]
You can simply go back and use the old tflite files also with the new version. They should work without a problem. You find the old tflite files in the releases.
