### ISSUE TITLE
Stupid Neptune water meter

### ISSUE THREAD

**Issue by avwuff** [jomjol/AI-on-the-edge-device#745]
Hi Jomjol!  Thanks so much for making this thing, it's really neat.  I'm hoping I can get it to work with my water meter.  It's a Neptune T-10 and as you can see, it is pretty useless for realtime readings:
![image](https://user-images.githubusercontent.com/2856227/160526347-d43e5aa8-4fba-4c7c-8af5-05953763c0d7.png)

- The main digits (black on white) and the 10th place digit (white on black) are obscured by the large red dial that sweeps across the entire face of the meter (the dial represents the 100th place digit)
- The ESP32CAM image looks awful, even with Contrast at -2 and the LED instensity at very settings, I can't get it to look any better than this.  I mean, it's pretty good for a $6 aliexpress board, but it's really not great.

I'm wondering if you can help me solve some issues?

Your app works some of the time, but I can never get it to read the final digit, so I just gave up on that.  Reading the big red dial is probably also out of the question, I tried but it wasn't working right.  I was hoping I could get it to just read the main four numbers, which represent m3. 

Trouble is, as you can see in the picture, the '3' just changed from '2' and isn't perfectly centered, so it can't be read.  I'm going to try to make the recognition boxes a bit bigger, but I feel like it may be a fools errand.

Also: The 'max rate of change' doesn't seem to work right -- I had it set to '2', and when it went from 1299 to 1300, it said 'too big of a change'.  Any suggestions?

Thanks so much!

**Comment by jomjol** [comment]
Hi,

>     * The main digits (black on white) and the 10th place digit (white on black) are obscured by the large red dial that sweeps across the entire face of the meter (the dial represents the 100th place digit)

First of all you should align the ROIs according to this suggestion: https://github.com/jomjol/AI-on-the-edge-device/wiki/ROI-Configuration
They should all have the same size.

>     * The ESP32CAM image looks awful, even with Contrast at -2 and the LED instensity at very settings, I can't get it to look any better than this.  I mean, it's pretty good for a $6 aliexpress board, but it's really not great.

The image quality is even for an ESP32CAM not very good. It looks like you're suffering from reflections. You could try to use a black inside of the tubus, that might help - just use a black piece of paper for testing.


> Your app works some of the time, but I can never get it to read the final digit, so I just gave up on that. Reading the big red dial is probably also out of the question, I tried but it wasn't working right. I was hoping I could get it to just read the main four numbers, which represent m3.

The big red pointer is a problem, espcially if it move across the digits. For this there is no solution in the software.


> Trouble is, as you can see in the picture, the '3' just changed from '2' and isn't perfectly centered, so it can't be read. I'm going to try to make the recognition boxes a bit bigger, but I feel like it may be a fools errand.

Don't make it bigger, see first point. The system detects the "inbetween" numbers as a "N" (=Not-a-Number) and replaces them with the previous red number until the new digit can be recognised.

> Also: The 'max rate of change' doesn't seem to work right -- I had it set to '2', and when it went from 1299 to 1300, it said 'too big of a change'. Any suggestions?

There are two setting: 
* relative max rate = maximum rate per minute allowed
* absolute change = change from one correct reading to the next correct reading.

Maybe you need to play around with this a little bit.

**Comment by jomjol** [comment]
No activities -> closing
