### ISSUE TITLE
Putting the Reading into MYSQL Database

### ISSUE THREAD

**Issue by MGPhil** [jomjol/AI-on-the-edge-device#746]
Hi,

finished to install everything on the esp32-cam and because of installation space had to use a fisheye lens
=> Works perfectly!

Now I am unsure how to get the data into my home database (MYSQL) were all other sensor values are stored.
Never used MQTT, right now all sensor data are simple https post with a php page that is putting the post data into mysql.

Any idea how to implement the water meter into that setup?

Thanks a lot for the great work!

Philipp

**Comment by jomjol** [comment]
A direct connection to MySQL is not implemented. But the way through a php page is working here as well. You can load a JSON with the data: http://IP-ADDRESS/json` and parse out of that the value and use php to insert into MySQL.

**Comment by MGPhil** [comment]
But I do not get some interrupt or information that a new reading is available just would be able to poll via an external server every 3min 30sec when 3min timing is set for example to read the information.

Any chance you implement a http post option in the future?
Should be only some additional lines of code and would enable a push from the client to the mysql server instead of polling.

**Comment by jomjol** [comment]
Currently not planned from my side to be implemented. But feel free to add this feature and I will upload it correspondingly.

**Comment by MGPhil** [comment]
I will give it a look but to add that feature I first need to understand your code
to know were and how to add best + to make it also configurable like the mqtt setting.

**Comment by barthm1** [comment]
You can take the MQTT output to save to DB https://github.com/curzon01/mqtt2sql

**Comment by MGPhil** [comment]
Thanks for the link would for sure be an temporary fix but having to run an additional Hardware which runs an MQTT Broker + that python script to push that into the mysql db is not a nice solution ;-)
