### ISSUE TITLE
Question to Alignment / Rotation

### ISSUE THREAD

**Issue by MGPhil** [jomjol/AI-on-the-edge-device#747]
Hi,
if I rotate the setup by some degrees the whole detection is broken
I need to update then the reference picture (change the degree value) until it is aligned again.
=> Should that not be done automatically by the CRI and m3 alighnment marks?

Also when I go to configuration alighnment marks or ROIs nothing is shown anymore
but in the overview (detection) everything is working like it should again since the update then the reference picture...

BR
Philipp

**Comment by jomjol** [comment]
Then your reference images are not unique enough. To a certain extend (~5°) a rotation will be compensated. This ensures, that you can take off and on the device.
In order to help you I need more information (e.g. example of correct and rotated image).

**Comment by MGPhil** [comment]
Can upoad some pictures here but if you say only 5° max gets corrected then thats my issue
I tried rotation it by for sure more then 10° to test if that would work.
Any reason why there is a limit how much you can be rotated?
Should be possible even with 180° or basically any rotation since you have the two reference marks to correct?

**Comment by friedpa** [comment]
you can rotate from 0 to 359 degrees, so there must be a misunderstanding.

**Comment by MGPhil** [comment]
Attached my ref picture and the output on the home screen (just manually blacked my serial on the screenshot)
If I rotate the device now by some degree the ROIs stay exactly were they are and everything is screwed up.

![70C2EC70-5799-4A32-B632-79E517114EB9](https://user-images.githubusercontent.com/30913060/160823938-d2774073-d9e6-43e0-beae-4df5a7b62201.jpeg)
![238889BF-E530-46A5-8F98-C8B2A236E5B4](https://user-images.githubusercontent.com/30913060/160823954-c711bda1-441d-48cb-824a-fcc1180c457c.jpeg)

**Comment by friedpa** [comment]
I have the same water meter. Improve the sharpness of the picture (howto in Wiki)
Use the tflite for analogue and digital from a previous version (I think it was Version2) ana0630s2.tflite and dig0630s3.tflite -> can be found on Github

**Comment by MGPhil** [comment]
Sharpness is a thing clear but not easy in my case as I had to use a fisheye lens and this lens is glued much more then the standard lens…do sou think that that is really the problem here as detection is working fine?
Is there a description in which tflite to use on which water meter? Thanks for the hint I will try!

**Comment by friedpa** [comment]
The files I used were long time ago one of the first sets jomjol trained. And I left it since then. Never change a running system :o) With a setup like below I have almost no misreadings.

![grafik](https://user-images.githubusercontent.com/42890695/160848551-3c3cbec1-e8de-4d49-a916-d6f619ed16d3.png)

**Comment by jomjol** [comment]
Regarding the rotation: the reference images are only searched in an area of +/-20 pixel. The reason is the limited calculation power and the simple search algo, that cannot handel rotated images. If not found within in this range, the result is arbritrary wrong.

**Comment by MGPhil** [comment]
Ok then this means again that rotating the camera is only able to be corrected by a very limited amount of degrees.
For me that tells me every time I have to put the device down and up on the water meter I have to redo the config.
Good to know thanks.

**Comment by jomjol** [comment]
Yes - the rotation is only corrected within a limited degree.
No - you don't need to redo the config everytime. The manual alignment that can be done "by eye" is usally much smaller than the deviation, after a device down and down again.

I have done this a lot of times and never a redo of the config due to a slight rotation was necessary.

**Comment by MGPhil** [comment]
Cloud I not just change the Alignment SearchFieldX and SearchFieldY in the config from 20 to full cam resolution i think 640x480 and accept the longer calculation time but for sure find the ref marks regardless of the alignment?

**Comment by jomjol** [comment]
yes you can, but it will not very user friendly as the calculation time scales with the amount of pixels:
(640*480)/(20*20) = 768 times 15 seconds = 3,2 hours.
If you also want to ensure an arbitray rotiation to be scanned in lets say 10° values --> additional an factor of 36.

Hope this makes clear, why the alignment algo is limited to only a rather smaller window and no rotation :-)

**Comment by jomjol** [comment]
No further acitivities --> closing
