### ISSUE TITLE
Usage of GPIO as an output

### ISSUE THREAD

**Issue by SchmDan** [jomjol/AI-on-the-edge-device#748]
Hi,

thank you very much for that great project. I really enjoy using it.
Is there a description how to use the GPIO state as an output? I'm searching especially for the usage of an API via HTTP or MQTT if enabled.
<img width="955" alt="image" src="https://user-images.githubusercontent.com/48385869/161058739-5596f61c-ad35-4ebe-838b-807df2abc2ec.png">

Thanks in advance!
Daniel

**Comment by jomjol** [comment]
This part has never been testet and is not recommended for usage. As I did the implementation not by myself, I even don't know how to use. Maybe I should disable the option at all :-)

**Comment by jomjol** [comment]
Closing this issue.
