### ISSUE TITLE
pool.ntp.org frequently called 

### ISSUE THREAD

**Issue by TungstenE2** [jomjol/AI-on-the-edge-device#750]
Hi all,

I am on master - v9.2.0 - 2021-12-02 and I can see in my Pi Hole log that 
the ESP32 is calling pool.ntp.org quite frequently.

Why is this the case and is this fixed in new release?

![grafik](https://user-images.githubusercontent.com/39955685/161394502-a3c79e2c-a39e-47eb-9fc3-3944935390d7.png)

thx

**Comment by jomjol** [comment]
It tries to reach the time server for maximum 10x during startup. Version 9.x tends to do frequent reboots.
This is better in version 10.x
