### ISSUE TITLE
OTA update v10.5.2 failed

### ISSUE THREAD

**Issue by TungstenE2** [jomjol/AI-on-the-edge-device#751]
Hi all,

I just did OTA update from  v9.2.0 to 10.5.2.

Steps:

- OTA uploaded firmware.bin and flashed it.

- OTA uplaoed html.zip and flashed it.

- Rebooted

After Reboot device is not reachable anymore.

Also did a power reset.

Any ideas? What did I do wrong?

As the ESP32 is in the basement at the hard reachable place, I do not want to take it to my desk.

v9.2.0 was working fine and stable for 3 months.

**Comment by jomjol** [comment]
Please follow the advice in the change log: https://github.com/jomjol/AI-on-the-edge-device#1011---stability-increase-2022-01-12

**Comment by TungstenE2** [comment]
Thx for the hint, as there were no installation notes with 10.5.2 I did not notice the info about config.ini from previous release.

Currently I can not access the ESP32. How to fix this?

**Comment by jomjol** [comment]
If it it not reachable at all via IP-Adress, then unfortunately there is no change beside taking out the sd-card an manually fix the config.ini (maintopic) or make a fresh setup.
