### ISSUE TITLE
Good practice

### ISSUE THREAD

**Issue by s0170071** [jomjol/AI-on-the-edge-device#765]
Hi all, 
I did quite some playing with this ESPCam and I would like to share some good practice points. 

1. Use the current version. It says somewhere in the readme that it is a bit more stable with new cameras. I can confirm that all my crashes are gone. Even with my "old" hardware. Its pretty stable now  (master - v10.5.2 - 2022-02-22)
2. Use qvga. If you can move the camera closer to the meter, do it. Mine is 4cm from the surface. Adjust the focus as you go.  It also helps to get rid of reflections from the glas.

![grafik](https://user-images.githubusercontent.com/33855380/162561838-309980d3-c510-4d56-9e0d-08a4a1a64413.png)

3. split the reading into two numbers. The last digit goes into a separate number. It is rolling and showing intermediate values all the time. If you split it, you get at least a good recognition for the left digits. Maybe, once in a while, also for the last digit. You need to adapt the shifting of the comma though for both numbers.  Example: in the image above, the left number is comprised of digits 13412, comma shift 2 (yields 134.12). The last digit is the second number with a comma shift of 3 (yields 0.008). I do the adding in my home automation system. 
4. Also filter out the number "9" for the last digit, very very often it misreads a 3 for a 9. If that happens, all other digits on the way to the real 9 are void because they appear as negative flow.
5. With qvga and only digital recognition, the processing of six digits is done in 14 seconds.  Check the log file to confirm this and  then you can set the reading interval to 1 minute (textual edit the config file :-)

Thanks for the good work, @jomjol and all others !

**Comment by caco3** [comment]
Thanks for your input!
We should collect such things and write them to the wiki

**Comment by Z18Aplha** [comment]
Thanks for your advice!

But in which way the number splitting does effect the recognition?
For example - The one is rotating and is recognized as a 7:
Without allowing NegativeRates (standard for meters) this 7 would not be recognized as a 2 later on? Or am I wrong?

I have a techem meter which has also three digital ROIs for decimal places and therefore the same problem with the "fast" rotating last ROI - see #991

**Comment by caco3** [comment]
@Z18Aplha please create a new issue for your question so we can handle it separately.

**Comment by s0170071** [comment]
> Thanks for your advice!
> 
> But in which way the number splitting does effect the recognition? 

That was an issue before the 100 classes DNN. An intermediate digit e.g. 5.5 prevented a valid reading.  Splitting it gave a correct reading for the first digits much more often.

**Comment by jomjol** [comment]
Thanks again for your input - most of the topics are in the wiki meanwhile or improved with the newer version. I close this issue to keep track on the active once.
