### ISSUE TITLE
Strange behaviour with checkDigitIncreaseConsistency == true

### ISSUE THREAD

**Issue by OliverWieland** [jomjol/AI-on-the-edge-device#766]
The attached image shows that the image recognition works perfectly. But if I set checkDigitIncreaseConsistency to true, the following happens:
If the last digital value is not readable (as it is in the picture), and the first analog value (x0.1) is between 2 and 4, then this first analog value 'seems to be decremented by 1' (not really decremented, I guess that was a non-perfect detection the in the previous measurement) in relative to the last detected value. As you can see in the error message, this value were detected as a '4' before.

`Rate too high - Read: 262.3101 - Pre: 261.4098`

This behavior leads to the incrementation of the last digital value, so that the overall evaluated value is way too high (262.3xxx instead of 261.4xxx)

What I would expect  in my case is a negative error (Read: 261.3101 - Pre: 261.4098)

My MaxRateValue is 0.2 (Absolute Change), maybe this parameter could be used to decide if the last digital value would be incremented or not.

Maybe a consistency check for the analog values would be nice, to decide if the new value is slightly lower than the last value. Ideally selectable for each analog counter (for the x0.0001 value this wouldn't make sense), or a selection how many analog counters  should be checked.

![Screenshot_20220410_103959](https://user-images.githubusercontent.com/837634/162610101-4277b174-01eb-4645-ba06-0b0b731f19bc.png)

**Comment by jomjol** [comment]
The topic is a "false" detected zero crossing due to the first subdigit beeing lower than the previous. Details of the algo can be found here: https://github.com/jomjol/AI-on-the-edge-device/wiki/Correction-Algorithm

Only option is a rate limit to subpress false detected numbers.
