### ISSUE TITLE
Image is drifting/rotating

### ISSUE THREAD

**Issue by Albretti** [jomjol/AI-on-the-edge-device#767]
Hi,

I observe the following problem. I have mounted my ESP32 Cam in a quite fixed position to a gasmeter. 
The picture is sharp and well lit from my point of view and the numbers are usually evaluated correctly. 
But from time to time, however, the image seems to be drifting / rotating and is therefore out of reading focus even though the camera is not moved.
so the picture should be like shown by the reference:
![Gasmeter Reference Image](https://user-images.githubusercontent.com/36680021/162922293-2d32015e-4317-44f8-981f-cb84c17ccb3f.jpg)

Instead the drifted picture which occurs looks like that

![Gasmeter drifting](https://user-images.githubusercontent.com/36680021/162921556-091215fb-d1ad-4c14-96c7-b2c7537eafa6.jpg)

I would be grateful to get any hint for solving this?

**Comment by Cino2424** [comment]
I have the same problem with latest release.

**Comment by jomjol** [comment]
This problem is clearly a not correct found reference image in the upper image most probably the "RF". You need to use an area with high contrast and simple feature. You can also create an artifical one with a peace of paper on top of the glass.

**Comment by jomjol** [comment]
No further discussion --> close issue

**Comment by benderrodrigo** [comment]
Sorry for old thread - but I had exactly this issue, and Jomjols comment fixed it.

For future people- Need to redefine reference images to be far apart from each other and clearly defined features.

-amazing build too Jomjol thank you so much
