### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by wetneb** [jomjol/AI-on-the-edge-device#773]
This repository does not declare any license, it would be nice to have one.

**Comment by jomjol** [comment]
I removed the licencense, after people startet to sell a 1:1 copy of the software for commercial purpose. As I did not find a fitting license, I decided to remove it.
You can use and copy it for private purpouse.

**Comment by atsju** [comment]
you might want to have a look at https://creativecommons.org/licenses/
but from what you describe nolicence is understandable (people who ask : look here for your rights  https://choosealicense.com/no-permission/)

**Comment by andy778** [comment]
If I understand you right you are after more permissive licence like MIT/BSD ?

**Comment by atsju** [comment]
@andy778 what I ask for is an explicit licence. I can be permissive or not. 
What you need to understand is that without licence, it's not open bar but rather absolute zero permission to do anything.
