### ISSUE TITLE
Make NTP server address configurable

### ISSUE THREAD

**Issue by wetneb** [jomjol/AI-on-the-edge-device#775]
For security reasons I run this device on a network with no internet access. At boot time the device tries to configure the time with NTP using `pool.ntp.org` as a server. If this server could be configurable, I could point it to a local NTP server instead (or point it to a specific IP that I could whitelist in my network configuration).

**Comment by jomjol** [comment]
This is already implemented in the expert mode:
![grafik](https://user-images.githubusercontent.com/30766535/163569706-7bbbe05b-805d-4769-9c87-4eca56a5b9ac.png)
It can happen, that it stills tries to access the default server (pool.ntp.org) but after 10 unsuccesfull tries it goes on and connect the manual defined server.

**Comment by wetneb** [comment]
amazing, thanks!
