### ISSUE TITLE
Troubleshooting Help: web server does not respond

### ISSUE THREAD

**Issue by jpconstantineau** [jomjol/AI-on-the-edge-device#776]
I have been trying to set things up and haven't been able to get through the initial setup without any files failing to be fetched.

I have tried a new sd card, a different esp32 cam and even a new, more powerful power supply and I never got to the point where I could save a new reference image.  When monitoring the network in developer tools (in chrome), I regularly get items with pending requests that never get completed.  This happens on all file types (js, html, etc).

The closest attempt got me to the point where the config.ini get deleted but a new one didnt get saved.

Any pointers to help troubleshoot this issue would be appreciated.

Is this a esp32 performance issue, a wifi issue or anything else?

I will be loading generic camera code to see if it's hardware or software related.  anything else I could try?

**Comment by jomjol** [comment]
This could be WLAN limited or a blocker in your internet (e.g. virus scanner, ...).
Or a broken or wrong device: are you sure, that you have 4MB PSRAM (>32 MBit). There are some very cheap modules around, who just have 2 MB, also claime to have 4 MB

**Comment by jpconstantineau** [comment]
I'll give a try by bringing an access point near the ESP32.  
It's a 4MB device.  A few weeks ago I did try with a 2Mb device and it clearly indicated the issue with insufficient PSRAM.

**Comment by jpconstantineau** [comment]
I have quite a few pieces surrounding the meter and I suspect that it wouldn't help wifi.  I already have a raspberry pi cam in place (wired) and I will be using that instead, along with node-red code to get something going.
Thanks for the pointers
