### ISSUE TITLE
Training for digit numbers

### ISSUE THREAD

**Issue by saemmy** [jomjol/AI-on-the-edge-device#781]
hi JomJol, here are my digits for next training. thanks.
[digits.zip](https://github.com/jomjol/AI-on-the-edge-device/files/8512816/digits.zip)

**Comment by jomjol** [comment]
You can try this one (unzip!):  [dig-s3-q-20220424.zip](https://github.com/jomjol/AI-on-the-edge-device/files/8550368/dig-s3-q-20220424.zip)

Please give feedback, it might go to the next main version.

**Comment by jomjol** [comment]
No feedback - seems to work --> closing
