### ISSUE TITLE
Strange issue with flash

### ISSUE THREAD

**Issue by TheLion** [jomjol/AI-on-the-edge-device#782]
I have a strange issue with the flash on my ESP32CAM,

When it is on my watermeter, it works fine for the first couple of pictaures/flashes, but after  a couple, it doesn't flash anymore. The picture is taken successfully, but it is way too dark to recognize anything.

When I take the thing apart, and plug the ESP32CAM with WEMOS attached into the USB port of my PC, to check what is wrong, it keeps working forever. I left it on there for a couple of days, and the flash works until I unplug it.

Not sure what can cause. It has been working for a couple of months without issues and these starting appearing suddenly.

Any thoughts on this?

**Comment by jomjol** [comment]
A difference between connecting to your PC and the usage on the meter sounds like an issue with the power supply. Never the less, if this is a new behaviour after a very long and stable phase, it must be coupled to some kind of hardware failure. E.g. a drop in voltage combinened with a not detected near brown out, resulting in an unsteady state of the switching of the flash.

I have no other idea, than exchaning the HW.

**Comment by TheLion** [comment]
Ok, I will order and try some new hardware.
I will update this issue when I have more info.

**Comment by jomjol** [comment]
No further activities --> close
