### ISSUE TITLE
Training digits

### ISSUE THREAD

**Issue by markus-hi** [jomjol/AI-on-the-edge-device#783]
Hello,

i have very often problems with the digit "6", it will be detected as "8". Hope you can integrate it in a new file for a better recognize.

Thank you
[digit.zip](https://github.com/jomjol/AI-on-the-edge-device/files/8549435/digit.zip)
!

**Comment by jomjol** [comment]
You can try this one (unzip!):  [dig-s3-q-20220424.zip](https://github.com/jomjol/AI-on-the-edge-device/files/8550368/dig-s3-q-20220424.zip)

Please give feedback, it might go to the next main version.

**Comment by markus-hi** [comment]
Thank you! With this version i have no problems actually 👍👌

**Comment by stalakerob** [comment]
FYI: Had the same issue and was fixed with this zip.
Thx
