### ISSUE TITLE
Read debug data from USB port

### ISSUE THREAD

**Issue by friebi** [jomjol/AI-on-the-edge-device#784]
Hi, thanks for all the replies in Issue #544

I'm opening a new issue since I do not get an answer in the old one for like a month and I still couldn't solve my current problem.

I got a little further with this project 😄 I have the ESP32 and the SW is running fine so far. I'm running latest release 10.5.2. I configured the SW and numbers are correctly read from the water meter. Nice!

However, as soon as I try to read from the serialport using any app (serialport inside NodeRed, minicom, screen, ...), the device seems to freeze. I am not getting any data from the serialport and the webinterface is not accessible any more until I power-cycle the device.
I'm using the following serial configuration: baud-rate 115200, 8 databits, 0 parity bits, 1 stopbit.

I couldn't find much info about reading this data in the docs. Any hint what I am doing wrong?

Thanks in advance!

**Comment by s0170071** [comment]
I guess its hardware relate. Two scenarios: 
1) your RPI cannot provide enough power. The ESP requires at least [310mA ](https://elektro.turanis.de/html/prj279/index.html)with the flash lamp on . I would not be surprised if it is even more. 
2) you are using the ESP32CAM-MB adapter and the rpi is resetting the system. 

This is the ciruit diagram of the ESP32CAM-MB, taken from [here](https://www.cat-one.net/2021/05/20/schematic-of-esp32-cam-mb/).

![grafik](https://user-images.githubusercontent.com/33855380/165495366-e8aaa6d2-22f2-4b18-9c7f-8162bb717d38.png)

Please note that they also operate the reset line from the RTS line of the serial / usb port. While this is handy for programming, it may cause issues in your case. See [here](https://www.reddit.com/r/esp32/comments/mscliq/anyone_have_the_schematic_for_the_esp32cammb/).

**Comment by friebi** [comment]
Thanks @s0170071 for the answer!
Power supply is not the problem since I also tested the behavior on my PC on a 1A powered USB port with the same result. Also the ESP works just fine connected to the RPi as long as I dont try to connect to the serial.
Your 2nd point is the cause of the error 😄 I do use this ESP32-CAM-MB module with a CH340C chip on it. Guess I need to try another solution. Thanks for the good hint!

**Comment by jomjol** [comment]
Then I close this issue - please reopen in case of support needed
