### ISSUE TITLE
Errors at the end of initial setup.

### ISSUE THREAD

**Issue by AseKarlsson** [jomjol/AI-on-the-edge-device#785]
Hi Jomjol,

At the end of the initial configuration, I get 3 errors.

If I ignore these errors and proceed, the GUI becomes unresponsive and even pings fail at intervals after restart.

The 3 errors are:

1.	In the selected field the value “in the parameter “PostProcessing” in the files “MaxRateType” is invalid. PLEASE CHECK BEFORE SAVING!
2.	In the selected field the value “in the parameter “PostProcessing” in the files “ExtendedResolution” is invalid. PLEASE CHECK BEFORE SAVING!
3.	In the selected field the value “in the parameter “PostProcessing” in the files “IgnoreLeadingNaN” is invalid. PLEASE CHECK BEFORE SAVING!

Please advise forward.

Thanks Ase

**Comment by jomjol** [comment]
This is a know bug in the current configuration and will be correted in one of the next versions

Work around: set some values to the named paramters (sometimes you need to enable them temporarily)

**Comment by AseKarlsson** [comment]
Hi Jomjol,

Thanks for the fast reply, where can I set these parameters, without access to the GUI?

Thanks,
Ase

**Comment by jomjol** [comment]
You can write them directly into the /config/config.ini

**Comment by AseKarlsson** [comment]
Great,

Should I add these under [PostPocessing]
MaxRateType = 0
ExtendedResolution = 0
IgnoreLeadingNaN = 0

Thanks,
Ase

**Comment by jomjol** [comment]
These values needs to go to the section [PostProcessing] like follwowing:
```
[PostProcessing]
main.DecimalShift = 0
PreValueUse = true
PreValueAgeStartup = 720
AllowNegativeRates = false
main.MaxRateValue = 0.05
;main.MaxRateType = AbsoluteChange
;main.ExtendedResolution = false
;main.IgnoreLeadingNaN = true
ErrorMessage = true
CheckDigitIncreaseConsistency = false
```

**Comment by AseKarlsson** [comment]
FollowUp question:

Should these 3 lines start with character ";"? 
I tried both with and without but with the same result, The GUI is badly responsing and pings fail about every 20 times.

**Comment by jomjol** [comment]
The ";" tells only, that the parameter is not used (graphical user interface still expects it to be configured).

If the interface is still unresponsive, than the problem is not the configuration, but rather instable WLAN or comparable. To get more inforamation I would need a serial log during the problem occuring.

**Comment by AseKarlsson** [comment]
Thanks,
WLAN is not the issue, the same behvaviour is also close to the AP. Everything is fine before finishing the initial configuration.
I use an older SD card that has not the latest speed, can that be an issue?
//Ase

**Comment by jomjol** [comment]
Could be

**Comment by AseKarlsson** [comment]
Any cheap card proven working? Example, Kingston microSDHC Canvas Select Plus - 32GB ?

**Comment by AseKarlsson** [comment]
16:38:24.396 -> [0;32mI (8764) sntp: Time is not set yet. Connecting to WiFi and getting time over NTP.[0m
16:38:24.396 -> [0;32mI (8764) sntp: Initializing SNTP[0m
16:38:24.396 -> [0;32mI (8764) sntp: Waiting for system time to be set... (1/10)[0m
16:38:26.397 -> [0;32mI (10764) sntp: Waiting for system time to be set... (2/10)[0m
16:38:28.356 -> [0;32mI (12764) sntp: Waiting for system time to be set... (3/10)[0m
16:38:30.363 -> [0;32mI (14764) sntp: Waiting for system time to be set... (4/10)[0m
16:38:32.410 -> [0;32mI (16754) BLINK: Blinken - done[0m
16:38:32.410 -> [0;32mI (16764) sntp: Waiting for system time to be set... (5/10)[0m
16:38:34.414 -> [0;32mI (18764) sntp: Waiting for system time to be set... (6/10)[0m
16:38:36.362 -> [0;32mI (20764) sntp: Waiting for system time to be set... (7/10)[0m
16:38:38.364 -> [0;32mI (22764) sntp: Waiting for system time to be set... (8/10)[0m
16:38:40.366 -> [0;32mI (24764) sntp: Waiting for system time to be set... (9/10)[0m
16:38:42.458 -> TimeZone set to CET-1CEST,M3.5.0,M10.5.0/3

Getting theese quite often, suggestion for time server in config.ini?
Can also see Rebooting... in intervalls.
What should I look for?

**Comment by AseKarlsson** [comment]
And you have to add it into the config.ini file to be used?

**Comment by jomjol** [comment]
you can, but if you disable the setting, it will be used by default

**Comment by AseKarlsson** [comment]
Did not work for me, unit thinks it 1970.

**Comment by AseKarlsson** [comment]
Added "Digital" images several times now for the main numbers. But next time i log on they are not there,..

**Comment by jomjol** [comment]
Then your device does not have access to the internet.

**Comment by jomjol** [comment]
> 

don't understand, what you mean?

**Comment by AseKarlsson** [comment]
![image](https://user-images.githubusercontent.com/80900477/165825084-685da7b9-c090-425d-b526-09a50aade287.png)
Took time from internal source and that worked fine.
After cleaning the "Prevalue.ini" file everything came responsive.

What I tried to ask is, that you did not understand is:
1. Should all numbers that should be detected be added from the biggest to she smallest (even analog)?
2. What is the differences of the fields shown by the arrows and what should I put in those?
3. I tried to use Number: "main" for all and just added Didigit 10000, Digit 1000, Digit 100 and so on for the fields, how is this supose to work?, any Youtube films or other guides to help with setup?

//Ase

**Comment by jomjol** [comment]
Have a look to the wiki!

https://github.com/jomjol/AI-on-the-edge-device/wiki/Graphical-configuration#3a3b-define-rois-for-image-recognition

**Comment by jomjol** [comment]
No further acitivies --> close (reopen new one in case of demand)

**Comment by AseKarlsson** [comment]
Thanks Jomjol,
Everything working great now!
//Ase
