### ISSUE TITLE
Digitizer - AI on the edge - watermeter || Fehlablesung

### ISSUE THREAD

**Issue by Takahara2022** [jomjol/AI-on-the-edge-device#786]
Hallo zusammen,

ich habe den Digitizer - AI on the edge - watermeter im Einsatz und immer wieder Fehlablesungen. Die Ausrichtung der digitalen- sowie analogen ROI's habe ich nun mehrfach überprüft.
Die Fehlablesung taucht nicht immer auf und ich vermute, dass es beim Aufnehmen des Zählerstandes wegen des Blitzlichtes zu keiner Überbelichtung kommt. Seltsam ist, dass die digitalen ROI's manchmal vertikal in der Mitte getrennt und verrückt sind. Auf dem beiliegenden Bild kann man dies bei der zweiten Ziffer 5 gut erkennen.

![2022-04-25 21_44_08-Window](https://user-images.githubusercontent.com/104391155/165163793-c93c4ba4-6db9-4cb3-9b2c-2925188f0cd7.png)
![2022-04-25 21_44_53-Window](https://user-images.githubusercontent.com/104391155/165163803-940bfd1b-bf54-451a-a208-1dbfcbffebbf.png)
 
Hat jemand eine Idee, wie ich eine stabile und zuverlässige Auswertung des Wasserstandes erreichen kann?

Vielen Dank im Voraus.

Takahara

**Comment by Mkay505** [comment]
Hi, habe ähnliche Probleme.
Die letzte Null wir entweder als 9 oder N (icht) erkannt. Selten als 0

![Screenshot_20220425-222954_Chrome](https://user-images.githubusercontent.com/75015019/165169944-53ad6fa9-3a23-41bd-9811-0f358458d307.jpg)

Man kann die Zahlen wohl speichern und dem Entwickler schicken.

Trotz unterschiedlicher Herausforderung:
Mega geniales Projekt, danke an jomjol!!!

**Comment by jomjol** [comment]
@Takahara2022 : du kannst deine ROIs noch deutlich optimieren. Sie sind deutlich zu groß. Im Wiki gibt es dazu eine ausführliche Erklärung: https://github.com/jomjol/AI-on-the-edge-device/wiki/ROI-Configuration

@Mkay505 : dort findest du auch, wie du Trainingsbilder erzeugst. Btw: die NaN im obigen Bild ist total okay, da die "0" schon deutlich verdreht ist.

**Comment by Takahara2022** [comment]
@jomjol : Vielen Dank für deine Rückmeldung. Ich habe die digitalen ROIs neu Positioniert und die Rechtecke verkleinert. Immer noch wird der Zählerstand nicht korrekt ermittelt. 
![2022-04-26 18_56_10-Window](https://user-images.githubusercontent.com/104391155/165353521-fe25c2f1-b589-4c63-a06e-84fd5b2fde53.png)
![2022-04-26 18_56_52-Window](https://user-images.githubusercontent.com/104391155/165353530-f168ce4e-6124-4755-8ed5-1c95833649be.png)

Hab ich immer noch was falsch gemacht?

VG Takahara

**Comment by Takahara2022** [comment]
@jomjol : Sorry, aber ich stehe bei deiner Frage auf dem Schlauch :( Wo kann ich die Informationen die du benötigst einsehen?

**Comment by jomjol** [comment]
Version: System --> Info
tflite: in der config.ini

**Comment by Takahara2022** [comment]
Die Firmwareversion habe ich finden können (siehe Screenshot).
![2022-04-26 20_56_47-Window](https://user-images.githubusercontent.com/104391155/165372682-9aa7d515-2189-459b-a811-73a59b1638c8.png)

Nur wie komme ich an die "config.ini" Datei?

**Comment by jomjol** [comment]
Bitte erstmal auf die neueste Version (10.5.2) updaten.

**Comment by flexstarr** [comment]
Bin auch sehr begeistert von diesem Projekt!

Ich erhalte auch NaN wenn der Zähler zwischen 2 Zahlen steht, ähnlich wie bei [Mkay505](https://github.com/Mkay505)
Lässt sich das optimieren oder mit der Software noch verbessern?

**Comment by Takahara2022** [comment]
@jomjol : Ich habe das Firmware Update (v10.5.2) sowie das Update "/html" directory (13.1.1) durchgeführt. Und auch noch mal zwei Screenshots vom Zählerstand vor und nach dem Update aufgenommen. Leider erfolgt immer noch keine genaue Ablesung des Zählerstandes 

Vor dem Update (05:13:52):
![2022-04-27 05_14_14-jomjol - AI on the edge - watermeter](https://user-images.githubusercontent.com/104391155/165433708-8238db12-bc28-47c7-be72-11107130f9a1.png)

Nachdem Update (05:20:16):
![2022-04-27 05_20_21-jomjol - AI on the edge - watermeter](https://user-images.githubusercontent.com/104391155/165433796-eb19bf6b-2c5b-40f0-af2d-71285796337d.png)
![2022-04-27 05_20_45-jomjol - AI on the edge - watermeter](https://user-images.githubusercontent.com/104391155/165433800-9b4e418a-1eb5-48fc-affc-5a6b4a616597.png)

VG Takahara

**Comment by jomjol** [comment]
Deine ROIs sind nicht mittig. Ich vermute, dass das mit der Alignmentmarke "DE" zusammenhängt, da sie verhältnismäßig wenig Kontrast hat und daher nicht ganz so gut zu erkennen ist. Vielleicht kannst du dort einfach eine schwarzen Punkt z.B. auf einen weissen Aufklebern anbringen.

**Comment by jomjol** [comment]
> 

Nein, dass läßt ich nicht verbessern, denn es ist sogar so gewollt, da bei einem Status zwischen zwei Ziffern nicht klar ist, welche der beiden Zahlen verwendet werden soll.

**Comment by flexstarr** [comment]
Okay, schade.
Da ich den Wert als Counter in Home Assistant nutzen möchte, ist es schlecht wenn dann ein N in der Zahl steht.
Hast Du ggf. eine Idee, wie man damit am besten umgeht?

**Comment by Mkay505** [comment]
Bin auch auf der Suche, dass der letzte Wert einfach weiter verwendet wird. Denn sonst sieht es in Home Assistent so aus.

Geht, aber nicht perfekt für meinen stündlichen Werte Export in CSV Datei. Denn öfter steht dann 0,00 drin.

Die Lösung muss jedoch denke ich aus Home Assistent kommen. 

![Screenshot_20220427-103655_Home Assistant](https://user-images.githubusercontent.com/75015019/165477786-070ad809-131b-41fb-b85b-d228366f6a3d.jpg)

**Comment by Takahara2022** [comment]
> Deine ROIs sind nicht mittig. Ich vermute, dass das mit der Alignmentmarke "DE" zusammenhängt, da sie verhältnismäßig wenig Kontrast hat und daher nicht ganz so gut zu erkennen ist. Vielleicht kannst du dort einfach eine schwarzen Punkt z.B. auf einen weissen Aufklebern anbringen.

Hallo jomjol: Ich hab jetzt einen schwarzen Punkt als stärkeren Kontrast aufgeklebt und die ROIs neu ausgerichtet. Immer noch wird der Zählerstand nicht korrekt ermittelt. 

Zudem erhalte ich eine Fehlermeldung:
![2022-04-27 10_50_16-Window](https://user-images.githubusercontent.com/104391155/165481508-5a70a8c4-fb0f-42ac-b82f-8a42cf428e83.png)

![2022-04-27 10_53_42-Window](https://user-images.githubusercontent.com/104391155/165481575-361d5efd-5239-40de-ba22-db9d471a960c.png)

**Comment by Mkay505** [comment]
Deine blauen Rechtecke um die Zahlen sind meines Erachtens noch immer zu weit rechts.
Schaue, dass du den gleichen Abstand links und rechts je Ziffer hast. Die Höhe passt, denke ich.

**Comment by s0170071** [comment]
> 

@Mkay505 Guck mal [hier](https://github.com/jomjol/AI-on-the-edge-device/issues/765). Wenn Du das letzte Digit als separate Zahl behandelst, bekommst Du öfter einen validen Auslesewert. Zusammenbauen musst Du die einzelnen Werte im Home Assistant.

@Takahara2022: versuch mal QVGA. Ich meine ich hatte auch mal so ein komischen offset in den ROIs, der ist aber mittlerweise weg. Wenn Du bei QVGA immernoch auf ne ROI Größe von 20x32 kommst, hast Du noch keine Bildinformationen verloren, aber ne Menge Speicher gespart. 
Ansonsten kontrollier mal die Reihenfolge deiner ROIs. Im Foto erkenne ich 0,0,5,5,8. Der RAW Wert hat alle Ziffern, nur in einer anderen Reihenfolge !

**Comment by Takahara2022** [comment]
@s0170071 : Ich habe die Reihenfolge der digitalen ROIs nochmals überprüft und die Anordnung ist richtig. Von links nach rechts ROI 1, 2,3,4 und 5.
Was genau ist "QVGA"?

**Comment by jomjol** [comment]
@Takahara2022 : poste bitte mal dein config.ini und einen Screenshot nach dem Drücken des Menüpunktes "Recognition"

**Comment by s0170071** [comment]
Einfach den Haken setzen bei Expert mode ;-) Dann erscheint ein Button. Drauf klicken. 


![grafik](https://user-images.githubusercontent.com/33855380/165583897-00656d14-3a99-4f52-8c9b-de482206d817.png)

**Comment by Takahara2022** [comment]
@jomjol : Anbei der Inhalt der config.ini

[MakeImage]
;LogImageLocation = /log/source
WaitBeforeTakingPicture = 5
;LogfileRetentionInDays = 15
Brightness = -2
Contrast = 2
Saturation = 0
LEDIntensity = 5
ImageQuality = 5
ImageSize = VGA
FixedExposure = false

[Alignment]
InitialRotate = 180
InitialMirror = false
SearchFieldX = 20
SearchFieldY = 20
AlignmentAlgo = default
FlipImageSize = false
/config/ref0.jpg 351 140
/config/ref1.jpg 89 303

[Digits]
Model = /config/dig-s2-q-20220104.tflite
;LogImageLocation = /log/digit
;LogfileRetentionInDays = 3
ModelInputSize = 20 32
main.dig2 223 148 22 39
main.dig3 254 150 22 39
main.dig1 192 148 22 39
main.dig4 284 148 22 39
main.dig5 315 147 22 39

[Analog]
Model = /config/ana-s3-q-20220105.tflite
;LogImageLocation = /log/analog
;LogfileRetentionInDays = 3
ModelInputSize = 32 32
main.ana1 384 207 78 78
main.ana2 348 293 78 78
main.ana3 261 327 78 78
main.ana4 170 289 78 78

[PostProcessing]
main.DecimalShift = 0
PreValueUse = true
PreValueAgeStartup = 720
AllowNegativeRates = false
main.MaxRateValue = 0.05
main.MaxRateType = RateChange
;main.ExtendedResolution = false
;main.IgnoreLeadingNaN = false
ErrorMessage = true
CheckDigitIncreaseConsistency = false

[MQTT]
Uri = mqtt://83.23.13.70:1883
MainTopic = wasserzaehler
ClientID = wasser
user = tasmota10
password = A4KHCQZ9hJuzchx4

;[GPIO]
;IO0 = input disabled 10 false false 
;IO1 = input disabled 10 false false 
;IO3 = input disabled 10 false false 
;IO4 = built-in-led disabled 10 false false 
;IO12 = input-pullup disabled 10 false false 
;IO13 = input-pullup disabled 10 false false 
LEDType = WS2812
LEDNumbers = 2
LEDColor = 150 150 150

[AutoTimer]
AutoStart = true
Intervall = 15

[Debug]
Logfile = false
LogfileRetentionInDays = 3

[System]
TimeZone = CET-1CEST,M3.5.0,M10.5.0/3
;TimeServer = undefined
;AutoAdjustSummertime = false
;Hostname = undefined
SetupMode = false

**Comment by s0170071** [comment]
Anstatt
```
main.dig2 223 148 22 39
main.dig3 254 150 22 39
main.dig1 192 148 22 39
main.dig4 284 148 22 39
main.dig5 315 147 22 39
```

probier mal: 

```
main.dig1 192 148 22 39
main.dig2 223 148 22 39
main.dig3 254 150 22 39
main.dig4 284 148 22 39
main.dig5 315 147 22 39
```

**Comment by jomjol** [comment]
Genau - das löst dein Problem. Es kommt nicht auf den Namen an, da kannst du reinschreiben, was du willst, sondern auf die Reihenfolge. RTFM ;-)

![grafik](https://user-images.githubusercontent.com/30766535/165618406-94e75578-575d-4b2e-b61c-1f07fb86c488.png)

**Comment by Takahara2022** [comment]
@jomjol @s0170071 : Bislang kann ich sagen, dass aktuell die Ablesung des Zählerstandes einwandfrei funktioniert und ich werde es in den kommenden Tagen noch weiter beobachten. Anschließend melde ich mich nochmals zurück.
Schon mal jetzt vielen lieben Dank für eure tatkräftige Unterstützung bei der Fehlersuche.
![2022-04-28 05_35_28-Window](https://user-images.githubusercontent.com/104391155/165671598-e989018f-04e3-4e09-8f13-3721d24a9668.png)

**Comment by jomjol** [comment]
@Takahara2022 Super - freut mich!

**Comment by Takahara2022** [comment]
Fazit: Heute morgen habe ich eine "neg. rate - Read:" gehabt was allerdings am Übergang der letzten Ziffer von 8 auf 9 liegen wird. Alles in allem scheint die Ablesung nun korrekt zu funktionieren, da die Änderung der Reihenfolge der digitalen ROIs das gewünschte Ergebnis und ein stabiles Ablesen ermöglicht.

Danke nochmals an alle für ihre Hilfe!!!!
![2022-04-29 06_46_35-jomjol - AI on the edge - watermeter](https://user-images.githubusercontent.com/104391155/165887138-5aa961e5-f469-4d36-8dfe-82357a930c03.png)

**Comment by Takahara2022** [comment]
Guten Abend,

ich komme gerade aus dem Urlaub zurück und wollte kurz den Wasserverbrauch überprüfen. Ich kann zwar noch die Weboberfläche des watermeter öffnen, eine Ablesung des aktuellen Verbrauchwertes erhalte ich allerdings nicht mehr. Auch kann ich das Menü nicht mehr öffnen. Habe ich bereits in unterschiedlichen Browsern versucht. Allerdings ohne Erfolg.

![2022-06-17 22_26_38-Window](https://user-images.githubusercontent.com/104391155/174396974-e99b0d37-cc03-4b3e-a84d-dfec4b15f806.png)

Hatte schon jemand das Problem?

VG
Takahara
