### ISSUE TITLE
Rebooting during recognition

### ISSUE THREAD

**Issue by De-k** [jomjol/AI-on-the-edge-device#787]
Hallo,

ich hab seit ein paar Tagen ( nach stabilem Betrieb) keine Werte mehr.

Lofile sagt immer:
AllocateTensors() failed

Das Bild wird gemacht, ausgerichtet, aber dann nicht ausgelesen, sondern reboot. Und das in einer Dauerschleife.

Ich habe die rolling vom 2022-03-22 20:46.
Was kann ich zur Analyse beitragen?

Dek

**Comment by jomjol** [comment]
Schreib bitte mal ein Logfile der seriellen Schnittstelle mit - dazu musst du es analog zum ersten Flashen an einen Rechner anschließen. Im besten Fall hast du ein Problem mit der SD-Karte (Kopieren und neu formatieren könnte helfen) oder im schlechteren einen Hardwaredefekt.

**Comment by De-k** [comment]
OK, geht wieder.

selbst der Rechner wollte die SD-Karte nicht mehr lesen. Hab' sie neu formatiert, jetzt schnurrt er wieder. Mein Vertrauen in diese SD-Card ist jetzt aber dahin, ich glaube ich besorg' schon mal Ersatz....
Dek

**Comment by jomjol** [comment]
Dann mach ich hier mal zu.
