### ISSUE TITLE
Feature Request: datetime of current value via mqtt

### ISSUE THREAD

**Issue by HJS72** [jomjol/AI-on-the-edge-device#79]
Please add a new object transmitted via mqtt with the timestamp of the last checked value. Can be used to check if the esp32cam is still alive.

**Comment by jomjol** [comment]
@HJS72 I readout the transmission time from my MQTT-Server. If you want to know, if the connection is still alived, there has been recently (currently only Branch rolling) another feature been added:
If you activate the MQTT ErrorTopic, a Last Will Testament is defined, that will produce a "connection lost" if the ESP32CAM is not responsive anymore. Just readout this topic.
Is that sufficient for you? Please give a short notive, so I could close this topic again.

**Comment by HJS72** [comment]
Reading the transmission time was my fallback solution ;-)
This will need some lines of code in my iobroker but will work for me. Thanks for great code and support. Enjoy your cup of coffee.

**Comment by jomjol** [comment]
You're welcome and thank you very much for the coffee!
