### ISSUE TITLE
GUI nicht erreichbar

### ISSUE THREAD

**Issue by srwilli1** [jomjol/AI-on-the-edge-device#790]
Hallo,
eben neu aufgesetzt. Watermeter taucht im Netzwerk auf, jedoch ist die Oberfläche über die ip nicht erreichbar.

Viele Grüße

**Comment by jomjol** [comment]
Wie soll ich mit so wenig Infos helfen?

Logfile, serielles Logfile, ... irgendetwas was ich analysieren kann. Bei allen anderen funktioniert die Installation ohne Probleme.

**Comment by srwilli1** [comment]
Laut Log wurde die Kamera nicht gefunden. Problem gelöst. Danke

**Comment by jomjol** [comment]
Toll, dass du es so schnell selbst lösen konntest. Ich schließe den Issue dann.
