### ISSUE TITLE
 AI-on-the-edge-device || Änderung WLAN-SSID und Password

### ISSUE THREAD

**Issue by Takahara2022** [jomjol/AI-on-the-edge-device#791]
Hallo,

ich möchte meinen  AI-on-the-edge-device Wassermengenzähler in ein neues Netzwerk integrieren. Wo kann ich ich die WLAN-SSID und das dazugehörige Passwort ändern?

VG
Takahara

**Comment by jomjol** [comment]
Genauso wie bei der ersten Einrichtung: wlan.ini auf der SD-Karte - geht aber nur mit Ausbau der Karte, da diese Datei vor Zugriffen geschützt ist.

RTFM ;-) https://github.com/jomjol/AI-on-the-edge-device/wiki/Installation#wlan

**Comment by Takahara2022** [comment]
> Genauso wie bei der ersten Einrichtung: wlan.ini auf der SD-Karte - geht aber nur mit Ausbau der Karte, da diese Datei vor Zugriffen geschützt ist.
> 
> RTFM ;-) https://github.com/jomjol/AI-on-the-edge-device/wiki/Installation#wlan

Super ;-) Hab vielen Dank. Super schneller support!!!!
