### ISSUE TITLE
Won't get IP

### ISSUE THREAD

**Issue by Dutchy-79** [jomjol/AI-on-the-edge-device#794]
Hi,

I finally received a new esp32cam because the previous one had PSRAM issues

Now erased and flashed, Uploaded details including wifi to SD and inserted

`15:22:47.954 -> ets Jun  8 2016 00:22:57
15:22:47.954 -> 
15:22:47.954 -> rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
15:22:47.954 -> configsip: 0, SPIWP:0xee
15:22:47.954 -> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
15:22:47.954 -> mode:DIO, clock div:2
15:22:47.954 -> load:0x3fff0018,len:4
15:22:47.954 -> load:0x3fff001c,len:5656
15:22:47.954 -> load:0x40078000,len:0
15:22:47.954 -> ho 12 tail 0 room 4
15:22:47.954 -> load:0x40078000,len:13920
15:22:47.954 -> entry 0x40078fd8
15:22:47.954 -> [0;32mI (30) boot: ESP-IDF v3.1-dev-463-g77eae33a-dirty 2nd stage bootloader[0m
15:22:47.954 -> [0;32mI (30) boot: compile time 10:52:13[0m
15:22:47.954 -> [0;32mI (31) boot: Enabling RNG early entropy source...[0m
15:22:47.954 -> [0;32mI (37) boot: SPI Speed      : 40MHz[0m
15:22:47.954 -> [0;32mI (41) boot: SPI Mode       : DIO[0m
15:22:47.954 -> [0;32mI (45) boot: SPI Flash Size : 4MB[0m
15:22:47.954 -> [0;32mI (49) boot: Partition Table:[0m
15:22:47.954 -> [0;32mI (52) boot: ## Label            Usage          Type ST Offset   Length[0m
15:22:47.954 -> [0;32mI (60) boot:  0 nvs              WiFi data        01 02 00009000 00004000[0m
15:22:47.954 -> [0;32mI (67) boot:  1 otadata          OTA data         01 00 0000d000 00002000[0m
15:22:47.954 -> [0;32mI (75) boot:  2 phy_init         RF data          01 01 0000f000 00001000[0m
15:22:47.954 -> [0;32mI (82) boot:  3 factory          factory app      00 00 00010000 00100000[0m
15:22:47.954 -> [0;32mI (90) boot:  4 ota_0            OTA app          00 10 00110000 00100000[0m
15:22:47.954 -> [0;32mI (97) boot:  5 ota_1            OTA app          00 11 00210000 00100000[0m
15:22:47.954 -> [0;32mI (105) boot: End of partition table[0m
15:22:47.954 -> [0;32mI (109) boot: Defaulting to factory image[0m
15:22:47.954 -> [0;32mI (113) esp_image: segment 0: paddr=0x00010020 vaddr=0x3f400020 size=0x17178 ( 94584) map[0m
15:22:48.003 -> [0;32mI (155) esp_image: segment 1: paddr=0x000271a0 vaddr=0x3ffb0000 size=0x031d8 ( 12760) load[0m
15:22:48.003 -> [0;32mI (161) esp_image: segment 2: paddr=0x0002a380 vaddr=0x40080000 size=0x00400 (  1024) load[0m
15:22:48.003 -> [0;32mI (163) esp_image: segment 3: paddr=0x0002a788 vaddr=0x40080400 size=0x05888 ( 22664) load[0m
15:22:48.003 -> [0;32mI (180) esp_image: segment 4: paddr=0x00030018 vaddr=0x400d0018 size=0x6fcf0 (457968) map[0m
15:22:48.238 -> [0;32mI (340) esp_image: segment 5: paddr=0x0009fd10 vaddr=0x40085c88 size=0x053e0 ( 21472) load[0m
15:22:48.238 -> [0;32mI (349) esp_image: segment 6: paddr=0x000a50f8 vaddr=0x400c0000 size=0x00000 (     0) load[0m
15:22:48.238 -> [0;32mI (356) boot: Loaded app from partition at offset 0x10000[0m
15:22:48.238 -> [0;32mI (356) boot: Disabling RNG early entropy source...[0m
15:22:48.238 -> [0;32mI (360) cpu_start: Pro cpu up.[0m
15:22:48.238 -> [0;32mI (364) cpu_start: Starting app cpu, entry point is 0x4008122c[0m
15:22:48.238 -> [0;32mI (0) cpu_start: App cpu up.[0m
15:22:48.238 -> [0;32mI (374) heap_init: Initializing. RAM available for dynamic allocation:[0m
15:22:48.238 -> [0;32mI (381) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM[0m
15:22:48.238 -> [0;32mI (387) heap_init: At 3FFB9980 len 00026680 (153 KiB): DRAM[0m
15:22:48.238 -> [0;32mI (393) heap_init: At 3FFE0440 len 00003BC0 (14 KiB): D/IRAM[0m
15:22:48.238 -> [0;32mI (400) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM[0m
15:22:48.238 -> [0;32mI (406) heap_init: At 4008B068 len 00014F98 (83 KiB): IRAM[0m
15:22:48.238 -> [0;32mI (412) cpu_start: Pro cpu start user code[0m
15:22:48.238 -> [0;32mI (207) cpu_start: Starting scheduler on PRO CPU.[0m
15:22:48.238 -> [0;32mI (0) cpu_start: Starting scheduler on APP CPU.[0m
15:22:48.238 -> [0;32mI (249) I2S: DMA Malloc info, datalen=blocksize=256, dma_buf_count=8[0m
15:22:48.280 -> [0;32mI (249) I2S: PLL_D2: Req RATE: 78125, real rate: 78125.000, BITS: 16, CLKM: 8, BCK: 8, MCLK: 20000000.000, SCLK: 2500000.000000, diva: 64, divb: 0[0m
15:22:48.280 -> [0;32mI (259) camera_xclk: PIN_CTRL before:3ff[0m
15:22:48.280 -> [0;32mI (259) camera_xclk: PIN_CTRL after:7fff[0m
15:22:52.356 -> [0;32mI (4329) camera_demo: Detected OV2640 camera, using JPEG format[0m
15:22:52.599 -> [0;32mI (4549) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE[0m
15:22:52.599 -> [0;32mI (4549) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE[0m
15:22:52.640 -> [0;32mI (4599) phy: phy_version: 366.0, ba9923d, Dec 29 2017, 14:25:06, 0, 0[0m
`

SD Details

`ssid = "mywifinetwork" (edited)
password = "myownpassword" (edited)
hostname = "watermeter camera"
;hostname is optional

;if you want to use a fixed IP you need to specify the following 3 parameters (ip, gateway, netmask) with IP4-Addresses "123.456.789.012"
;ip = "192.168.1.200"
;gateway = "192.168.1.11"
;netmask = "255.255.255.0"

;in some cases you want to specify the DNS server as well (especially, if it is not identical to the gateway - this is optional for a fixed IP
;dns = "IP4-ADDRESS"`

**Comment by Dutchy-79** [comment]
15:32:33.947 -> ets Jun  8 2016 00:22:57
15:32:33.947 -> 
15:32:33.947 -> rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
15:32:33.947 -> configsip: 0, SPIWP:0xee
15:32:33.947 -> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
15:32:33.947 -> mode:DIO, clock div:2
15:32:33.947 -> load:0x3fff0018,len:4
15:32:33.947 -> load:0x3fff001c,len:5656
15:32:33.947 -> load:0x40078000,len:0
15:32:33.947 -> ho 12 tail 0 room 4
15:32:33.947 -> load:0x40078000,len:13920
15:32:33.947 -> entry 0x40078fd8
15:32:33.947 -> [0;32mI (30) boot: ESP-IDF v3.1-dev-463-g77eae33a-dirty 2nd stage bootloader[0m
15:32:33.947 -> [0;32mI (30) boot: compile time 10:52:13[0m
15:32:33.947 -> [0;32mI (31) boot: Enabling RNG early entropy source...[0m
15:32:33.947 -> [0;32mI (37) boot: SPI Speed      : 40MHz[0m
15:32:33.947 -> [0;32mI (41) boot: SPI Mode       : DIO[0m
15:32:33.947 -> [0;32mI (45) boot: SPI Flash Size : 4MB[0m
15:32:33.947 -> [0;32mI (49) boot: Partition Table:[0m
15:32:33.947 -> [0;32mI (53) boot: ## Label            Usage          Type ST Offset   Length[0m
15:32:33.947 -> [0;32mI (60) boot:  0 nvs              WiFi data        01 02 00009000 00004000[0m
15:32:33.947 -> [0;32mI (67) boot:  1 otadata          OTA data         01 00 0000d000 00002000[0m
15:32:33.947 -> [0;32mI (75) boot:  2 phy_init         RF data          01 01 0000f000 00001000[0m
15:32:33.947 -> [0;32mI (82) boot:  3 factory          factory app      00 00 00010000 00100000[0m
15:32:33.947 -> [0;32mI (90) boot:  4 ota_0            OTA app          00 10 00110000 00100000[0m
15:32:33.947 -> [0;32mI (97) boot:  5 ota_1            OTA app          00 11 00210000 00100000[0m
15:32:33.947 -> [0;32mI (105) boot: End of partition table[0m
15:32:33.947 -> [0;32mI (109) boot: Defaulting to factory image[0m
15:32:33.947 -> [0;32mI (114) esp_image: segment 0: paddr=0x00010020 vaddr=0x3f400020 size=0x17178 ( 94584) map[0m
15:32:33.980 -> [0;32mI (156) esp_image: segment 1: paddr=0x000271a0 vaddr=0x3ffb0000 size=0x031d8 ( 12760) load[0m
15:32:33.980 -> [0;32mI (161) esp_image: segment 2: paddr=0x0002a380 vaddr=0x40080000 size=0x00400 (  1024) load[0m
15:32:33.980 -> [0;32mI (163) esp_image: segment 3: paddr=0x0002a788 vaddr=0x40080400 size=0x05888 ( 22664) load[0m
15:32:33.980 -> [0;32mI (181) esp_image: segment 4: paddr=0x00030018 vaddr=0x400d0018 size=0x6fcf0 (457968) map[0m
15:32:34.229 -> [0;32mI (340) esp_image: segment 5: paddr=0x0009fd10 vaddr=0x40085c88 size=0x053e0 ( 21472) load[0m
15:32:34.229 -> [0;32mI (349) esp_image: segment 6: paddr=0x000a50f8 vaddr=0x400c0000 size=0x00000 (     0) load[0m
15:32:34.229 -> [0;32mI (356) boot: Loaded app from partition at offset 0x10000[0m
15:32:34.229 -> [0;32mI (356) boot: Disabling RNG early entropy source...[0m
15:32:34.229 -> [0;32mI (360) cpu_start: Pro cpu up.[0m
15:32:34.229 -> [0;32mI (364) cpu_start: Starting app cpu, entry point is 0x4008122c[0m
15:32:34.229 -> [0;32mI (0) cpu_start: App cpu up.[0m
15:32:34.229 -> [0;32mI (375) heap_init: Initializing. RAM available for dynamic allocation:[0m
15:32:34.229 -> [0;32mI (381) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM[0m
15:32:34.229 -> [0;32mI (387) heap_init: At 3FFB9980 len 00026680 (153 KiB): DRAM[0m
15:32:34.229 -> [0;32mI (394) heap_init: At 3FFE0440 len 00003BC0 (14 KiB): D/IRAM[0m
15:32:34.229 -> [0;32mI (400) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM[0m
15:32:34.229 -> [0;32mI (406) heap_init: At 4008B068 len 00014F98 (83 KiB): IRAM[0m
15:32:34.229 -> [0;32mI (413) cpu_start: Pro cpu start user code[0m
15:32:34.229 -> [0;32mI (207) cpu_start: Starting scheduler on PRO CPU.[0m
15:32:34.229 -> [0;32mI (0) cpu_start: Starting scheduler on APP CPU.[0m
15:32:34.229 -> [0;32mI (249) I2S: DMA Malloc info, datalen=blocksize=256, dma_buf_count=8[0m
15:32:34.271 -> [0;32mI (249) I2S: PLL_D2: Req RATE: 78125, real rate: 78125.000, BITS: 16, CLKM: 8, BCK: 8, MCLK: 20000000.000, SCLK: 2500000.000000, diva: 64, divb: 0[0m
15:32:34.271 -> [0;32mI (259) camera_xclk: PIN_CTRL before:3ff[0m
15:32:34.271 -> [0;32mI (259) camera_xclk: PIN_CTRL after:7fff[0m
15:32:38.352 -> [0;32mI (4329) camera_demo: Detected OV2640 camera, using JPEG format[0m
15:32:38.564 -> [0;32mI (4549) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE[0m
15:32:38.564 -> [0;32mI (4549) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE[0m
15:32:38.607 -> [0;32mI (4599) phy: phy_version: 366.0, ba9923d, Dec 29 2017, 14:25:06, 0, 0[0m

**Comment by jomjol** [comment]
You need to post more of the logfile. Up to this point, the wlan is not initated fully.

**Comment by Dutchy-79** [comment]
Where can I find the log? This is from the serial monitor from Arduino ide

**Comment by jomjol** [comment]
That is looking find, but it should contain just a lot more lines. But to be honest, I'm  not too familiar with the Arduino IDE. You can attach any serial log (e.g. Putty) and need to set the right connection settings:
- Port ?
- Baud Rate 115200

**Comment by Dutchy-79** [comment]
now with putty com10 baud 115200
powered by separate 1A 3.3V 

I (356) boot: Disabling RNG early entropy source...
I (360) cpu_start: Pro cpu up.
I (364) cpu_start: Starting app cpu, entry point is 0x4008122c
I (0) cpu_start: App cpu up.
I (375) heap_init: Initializing. RAM available for dynamic allocation:
I (381) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM
I (387) heap_init: At 3FFB9980 len 00026680 (153 KiB): DRAM
I (394) heap_init: At 3FFE0440 len 00003BC0 (14 KiB): D/IRAM
I (400) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (406) heap_init: At 4008B068 len 00014F98 (83 KiB): IRAM
I (413) cpu_start: Pro cpu start user code
I (207) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
I (249) I2S: DMA Malloc info, datalen=blocksize=256, dma_buf_count=8
I (249) I2S: PLL_D2: Req RATE: 78125, real rate: 78125.000, BITS: 16, CLKM: 8, BCK: 8, MCLK: 20000000.000, SCLK: 2500000.000000, diva: 64, divb: 0
I (259) camera_xclk: PIN_CTRL before:3ff
I (259) camera_xclk: PIN_CTRL after:7fff
I (4549) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE
I (4549) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE
I (4599) phy: phy_version: 366.0, ba9923d, Dec 29 2017, 14:25:06, 0, 0
ets Jun  8 2016 00:22:57

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:5656
load:0x40078000,len:0
ho 12 tail 0 room 4
load:0x40078000,len:13920
entry 0x40078fd8
I (30) boot: ESP-IDF v3.1-dev-463-g77eae33a-dirty 2nd stage bootloader
I (30) boot: compile time 10:52:13
I (31) boot: Enabling RNG early entropy source...
I (37) boot: SPI Speed      : 40MHz
I (41) boot: SPI Mode       : DIO
I (45) boot: SPI Flash Size : 4MB
I (49) boot: Partition Table:
I (53) boot: ## Label            Usage          Type ST Offset   Length
I (60) boot:  0 nvs              WiFi data        01 02 00009000 00004000
I (67) boot:  1 otadata          OTA data         01 00 0000d000 00002000
I (75) boot:  2 phy_init         RF data          01 01 0000f000 00001000
I (82) boot:  3 factory          factory app      00 00 00010000 00100000
I (90) boot:  4 ota_0            OTA app          00 10 00110000 00100000
I (97) boot:  5 ota_1            OTA app          00 11 00210000 00100000
I (105) boot: End of partition table
I (109) boot: Defaulting to factory image
I (114) esp_image: segment 0: paddr=0x00010020 vaddr=0x3f400020 size=0x17178 ( 94584) map
I (155) esp_image: segment 1: paddr=0x000271a0 vaddr=0x3ffb0000 size=0x031d8 ( 12760) load
I (161) esp_image: segment 2: paddr=0x0002a380 vaddr=0x40080000 size=0x00400 (  1024) load
I (163) esp_image: segment 3: paddr=0x0002a788 vaddr=0x40080400 size=0x05888 ( 22664) load
I (180) esp_image: segment 4: paddr=0x00030018 vaddr=0x400d0018 size=0x6fcf0 (457968) map
I (340) esp_image: segment 5: paddr=0x0009fd10 vaddr=0x40085c88 size=0x053e0 ( 21472) load
I (349) esp_image: segment 6: paddr=0x000a50f8 vaddr=0x400c0000 size=0x00000 (     0) load
I (356) boot: Loaded app from partition at offset 0x10000
I (356) boot: Disabling RNG early entropy source...
I (360) cpu_start: Pro cpu up.
I (364) cpu_start: Starting app cpu, entry point is 0x4008122c
I (0) cpu_start: App cpu up.
I (375) heap_init: Initializing. RAM available for dynamic allocation:
I (381) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM
I (387) heap_init: At 3FFB9980 len 00026680 (153 KiB): DRAM
I (394) heap_init: At 3FFE0440 len 00003BC0 (14 KiB): D/IRAM
I (400) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (406) heap_init: At 4008B068 len 00014F98 (83 KiB): IRAM
I (413) cpu_start: Pro cpu start user code
I (207) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
I (249) I2S: DMA Malloc info, datalen=blocksize=256, dma_buf_count=8
I (249) I2S: PLL_D2: Req RATE: 78125, real rate: 78125.000, BITS: 16, CLKM: 8, BCK: 8, MCLK: 20000000.000, SCLK: 2500000.000000, diva: 64, divb: 0
I (259) camera_xclk: PIN_CTRL before:3ff
I (259) camera_xclk: PIN_CTRL after:7fff
I (4329) camera_demo: Detected OV2640 camera, using JPEG format
I (4549) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE
I (4549) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE
I (4629) phy: phy_version: 366.0, ba9923d, Dec 29 2017, 14:25:06, 0, 0

**Comment by jomjol** [comment]
Well, if this is the last entry, then there is something totally wrong with the flashed firmware. But it is also suspicious, that you do not have any PSRAM. Without this it will not work. Which module do you have exactly?

Here is a boot log of a working system:
```
rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:7580
ho 0 tail 12 room 4
load:0x40078000,len:15360
load:0x40080400,len:3744
entry 0x4008067c
␛[0;32mI (28) boot: ESP-IDF 4.3.2 2nd stage bootloader␛[0m
␛[0;32mI (29) boot: compile time 20:10:54␛[0m
␛[0;32mI (29) boot: chip revision: 1␛[0m
␛[0;32mI (31) boot_comm: chip revision: 1, min. bootloader chip revision: 0␛[0m
␛[0;32mI (38) boot.esp32: SPI Speed      : 40MHz␛[0m
␛[0;32mI (43) boot.esp32: SPI Mode       : DIO␛[0m
␛[0;32mI (47) boot.esp32: SPI Flash Size : 4MB␛[0m
␛[0;32mI (52) boot: Enabling RNG early entropy source...␛[0m
␛[0;32mI (57) boot: Partition Table:␛[0m
␛[0;32mI (61) boot: ## Label            Usage          Type ST Offset   Length␛[0m
␛[0;32mI (68) boot:  0 nvs              WiFi data        01 02 00009000 00004000␛[0m
␛[0;32mI (76) boot:  1 otadata          OTA data         01 00 0000d000 00002000␛[0m
␛[0;32mI (83) boot:  2 phy_init         RF data          01 01 0000f000 00001000␛[0m
␛[0;32mI (91) boot:  3 ota_0            OTA app          00 10 00010000 001db000␛[0m
␛[0;32mI (98) boot:  4 ota_1            OTA app          00 11 001f0000 001db000␛[0m
␛[0;32mI (106) boot: End of partition table␛[0m
␛[0;32mI (110) boot_comm: chip revision: 1, min. application chip revision: 0␛[0m
␛[0;32mI (117) esp_image: segment 0: paddr=00010020 vaddr=3f400020 size=4a9d8h (305624) map␛[0m
␛[0;32mI (243) esp_image: segment 1: paddr=0005aa00 vaddr=3ffb0000 size=04a18h ( 18968) load␛[0m
␛[0;32mI (251) esp_image: segment 2: paddr=0005f420 vaddr=40080000 size=00bf8h (  3064) load␛[0m
␛[0;32mI (252) esp_image: segment 3: paddr=00060020 vaddr=400d0020 size=145f58h (1335128) map␛[0m
␛[0;32mI (768) esp_image: segment 4: paddr=001a5f80 vaddr=40080bf8 size=1b084h (110724) load␛[0m
␛[0;32mI (816) esp_image: segment 5: paddr=001c100c vaddr=50000000 size=00010h (    16) load␛[0m
␛[0;32mI (830) boot: Loaded app from partition at offset 0x10000␛[0m
␛[0;32mI (830) boot: Disabling RNG early entropy source...␛[0m
␛[0;32mI (842) psram: This chip is ESP32-D0WD␛[0m
␛[0;32mI (842) spiram: Found 64MBit SPI RAM device␛[0m
␛[0;32mI (842) spiram: SPI RAM mode: flash 40m sram 40m␛[0m
␛[0;32mI (847) spiram: PSRAM initialized, cache is in low/high (2-core) mode.␛[0m
␛[0;32mI (854) cpu_start: Pro cpu up.␛[0m
␛[0;32mI (858) cpu_start: Starting app cpu, entry point is 0x40082c58␛[0m
␛[0;32mI (0) cpu_start: App cpu up.␛[0m
␛[0;32mI (1752) spiram: SPI SRAM memory test OK␛[0m
␛[0;32mI (1760) cpu_start: Pro cpu start user code␛[0m
␛[0;32mI (1760) cpu_start: cpu freq: 160000000␛[0m
␛[0;32mI (1760) cpu_start: Application information:␛[0m
␛[0;32mI (1763) cpu_start: Project name:     esp32cam-server-only␛[0m
␛[0;32mI (1770) cpu_start: App version:      0.0.9.3␛[0m
␛[0;32mI (1775) cpu_start: Compile time:     May  4 2022 20:08:42␛[0m
␛[0;32mI (1781) cpu_start: ELF file SHA256:  3edfe6cd2f38793d...␛[0m
␛[0;32mI (1787) cpu_start: ESP-IDF:          4.3.2␛[0m
␛[0;32mI (1792) heap_init: Initializing. RAM available for dynamic allocation:␛[0m
␛[0;32mI (1799) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM␛[0m
␛[0;32mI (1805) heap_init: At 3FFC0658 len 0001F9A8 (126 KiB): DRAM␛[0m
␛[0;32mI (1812) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM␛[0m
␛[0;32mI (1818) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM␛[0m
␛[0;32mI (1824) heap_init: At 4009BC7C len 00004384 (16 KiB): IRAM␛[0m
␛[0;32mI (1831) spiram: Adding pool of 4096K of external SPI memory to heap allocator␛[0m
␛[0;32mI (1840) spi_flash: detected chip: generic␛[0m
␛[0;32mI (1844) spi_flash: flash io: dio␛[0m
␛[0;32mI (1853) cpu_start: Starting scheduler on PRO CPU.␛[0m
␛[0;32mI (0) cpu_start: Starting scheduler on APP CPU.␛[0m
␛[0;32mI (1858) spiram: Reserving pool of 32K of internal memory for DMA/internal allocations␛[0m
␛[0;32mI (1868) gpio: GPIO[32]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 ␛[0m
Init Camera
␛[0;32mI (3878) gpio: GPIO[25]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:2 ␛[0m
␛[0;32mI (3878) cam_hal: cam init ok␛[0m
␛[0;32mI (3878) sccb: pin_sda 26 pin_scl 27␛[0m
␛[0;32mI (3878) gpio: GPIO[32]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 ␛[0m
␛[0;32mI (3918) camera: Detected camera at address=0x30␛[0m
␛[0;32mI (3918) camera: Detected OV2640 camera␛[0m
␛[0;32mI (3918) camera: Camera PID=0x26 VER=0x42 MIDL=0x7f MIDH=0xa2␛[0m
␛[0;32mI (3998) cam_hal: buffer_size: 32768, half_buffer_size: 4096, node_buffer_size: 2048, node_cnt: 16, total_cnt: 15␛[0m
␛[0;32mI (3998) cam_hal: Allocating 61440 Byte frame buffer in PSRAM␛[0m
␛[0;32mI (4008) cam_hal: cam config ok␛[0m
␛[0;32mI (4008) ov2640: Set PLL: clk_2x: 0, clk_div: 0, pclk_auto: 0, pclk_div: 8␛[0m
Internal Flash-LED turn off PWM
nach init camera: sleep for : 200ms
␛[0;32mI (6118) main: Using SDMMC peripheral␛[0m
Name: APPSD
Type: SDHC/SDXC
Speed: 20 MHz
Size: 7681MB
␛[0;32mI (6168) server_ota: Start CheckOTAUpdateCheck ...␛[0m
Start CheckOTAUpdateCheck ...
␛[0;32mI (6178) server_ota: SHA-256 for the partition table: : 9d4a2809ae90fb20709a8ca3dd3ac3462e1e73286bcd31b689060c91de06fa3a␛[0m
␛[0;32mI (6178) server_ota: SHA-256 for bootloader: : e774534ecd4bdd1f322ce57a35544d33a19eee3df50891140ad473877fb9710e␛[0m
␛[0;32mI (6188) server_ota: SHA-256 for current firmware: : 640913a041ec008a63ec7378ef23ea5faf9047f288fffea4ba59eff945224e18␛[0m
CheckOTAUpdate Partition: ESP_OK
open file /sdcard/wlan.ini in mode r
file loaded

WLan: XXXXXXX, YYYYYYY
Hostename: testtest
I (6248) wifi:wifi driver task: 3ffdb5ec, prio:23, stack:6656, core=0
␛[0;32mI (6248) system_api: Base MAC address is not set␛[0m
␛[0;32mI (6248) system_api: read default base MAC address from EFUSE␛[0m
I (6268) wifi:wifi firmware version: eb52264
I (6268) wifi:wifi certification version: v7.0
I (6268) wifi:config NVS flash: enabled
I (6268) wifi:config nano formating: disabled
I (6268) wifi:Init data frame dynamic rx buffer num: 16
I (6278) wifi:Init management frame dynamic rx buffer num: 16
I (6278) wifi:Init management short buffer num: 32
I (6288) wifi:Init static tx buffer num: 16
I (6288) wifi:Init tx cache buffer num: 16
I (6288) wifi:Init static rx buffer size: 1600
I (6298) wifi:Init static rx buffer num: 10
I (6298) wifi:Init dynamic rx buffer num: 16
␛[0;32mI (6308) wifi_init: rx ba win: 6␛[0m
␛[0;32mI (6308) wifi_init: tcpip mbox: 32␛[0m
␛[0;32mI (6308) wifi_init: udp mbox: 6␛[0m
␛[0;32mI (6318) wifi_init: tcp mbox: 6␛[0m
␛[0;32mI (6318) wifi_init: tcp tx win: 5744␛[0m
␛[0;32mI (6328) wifi_init: tcp rx win: 5744␛[0m
␛[0;32mI (6328) wifi_init: tcp mss: 1440␛[0m
␛[0;32mI (6328) wifi_init: WiFi IRAM OP enabled␛[0m
␛[0;32mI (6338) wifi_init: WiFi RX IRAM OP enabled␛[0m
␛[0;32mI (6348) phy_init: phy_version 4670,719f9f6,Feb 18 2021,17:07:07␛[0m
I (6448) wifi:mode : sta (94:b9:7e:c4:bf:a4)
I (6448) wifi:enable tsf
␛[0;32mI (6448) BLINK: Blinken - start␛[0m
␛[0;31mE (6448) wifi station: Set Hostname to:testtest␛[0m
␛[0;32mI (6448) wifi station: wifi_init_sta finished.␛[0m
I (6468) wifi:new:<1,1>, old:<1,0>, ap:<255,255>, sta:<1,1>, prof:1
I (6468) wifi:state: init -> auth (b0)
I (6478) wifi:state: auth -> assoc (0)
I (6488) wifi:state: assoc -> run (10)
I (6518) wifi:connected with XXXXXXXX, aid = 8, channel 1, 40U, bssid = dc:15:c8:83:8f:fe
I (6518) wifi:security: WPA2-PSK, phy: bgn, rssi: -66
I (6528) wifi:pm start, type: 1

W (6548) wifi:<ba-add>idx:0 (ifx:0, dc:15:c8:83:8f:fe), tid:6, ssn:2, winSize:64
I (6608) wifi:AP's beacon interval = 102400 us, DTIM period = 1
Logfile opened: /sdcard/log/message/log_2022-05-04.txt
Logfile opened: /sdcard/log/message/log_2022-05-04.txt
Logfile opened: /sdcard/log/message/log_2022-05-04.txt
time 20220504-201257
Internal Flash-LED turn off PWM
main: sleep for : 2000ms
starting server
␛[0;32mI (13378) server-main: Starting server on port: '80'␛[0m
␛[0;32mI (13378) server-main: Registering URI handlers␛[0m
␛[0;32mI (13378) server_tflite: server_part_camera - Registering URI handlers␛[0m
␛[0;32mI (13378) server_ota: server_ota - Registering URI handlers␛[0m
␛[0;32mI (13388) server_GPIO: start GpioHandler␛[0m
␛[0;32mI (13388) server_GPIO: register�ets Jun  8 2016 00:22:57

```

**Comment by Dutchy-79** [comment]
So now I bought a new one from a local store and that also doesn't have psram? They both have the psram chip so I don't know where I should buy a esp32 cam from before this would work?

**Comment by Dutchy-79** [comment]
Problem solved by using Linux kali with these commands:

git clone https://github.com/espressif/esptool.git
cd esptool
**-- Save bootloader.bin partitions.bin firmware.bin in esptool folder --**
python3 esptool.py erase_flash
esptool write_flash 0x01000 bootloader.bin 0x08000 partitions.bin 0x10000 firmware.bin
