### ISSUE TITLE
Ista watermeter AI training digits

### ISSUE THREAD

**Issue by oernii** [jomjol/AI-on-the-edge-device#795]
Hi, I have trouble with these digits on my Ista watermeter. Could you please train them. They are named as follows: EXPECTED_digitname.jpg

[ista-watermeter.zip](https://github.com/jomjol/AI-on-the-edge-device/files/8612482/ista-watermeter.zip)
 

Thank you.

**Comment by jomjol** [comment]
@oernii: I can confirm the statement of @JensHoRi. Please first adjust the ROI according to the instructions in the wiki: https://github.com/jomjol/AI-on-the-edge-device/wiki/ROI-Configuration

**Comment by jomjol** [comment]
I assume, that this increases already the detection. Therefore I close the issue. But you can reopen a new one if needed.
