### ISSUE TITLE
Different images reference image and Scan

### ISSUE THREAD

**Issue by schrej-zz** [jomjol/AI-on-the-edge-device#798]
Hi,
I do have the issue, that I make a new reference image and align the digits afterwards.
But when the regular scan starts, it scans a totally different picture.
What can be the issue?

**Comment by jomjol** [comment]
Then I close this issue

**Comment by lkaino** [comment]
I'm having the same issue.

I take a new reference image, align the image and digits perfectly, store the values in the config and reboot.

After reboot the image is not rotated correctly, it is few degrees off from the configured rotation value. The image is rotated, but not the correct amount.
