### ISSUE TITLE
Increase Resolution by last analog ROI

### ISSUE THREAD

**Issue by to-scho** [jomjol/AI-on-the-edge-device#80]
Can you add an option o increase resolution by one digit from last analog reading. My readings are super reliable and in particular the last analog one shows good quality currently not given to MQTT etc.

**Comment by jomjol** [comment]
I'll put it on the list - but it's not straight forward, as it will need extra handling of the last analog number compared to all others at serveral positions within the code.

**Comment by jomjol** [comment]
Implemented in the latest rolling from today - accessible in the expert modus.

**Comment by to-scho** [comment]
Hi, thx for implementation. I flashed 6.1.0 today and can see "ExtendedResolution" in expert mode. Nevertheless it's grayed out. how to enable setting? Regards, Tobias

**Comment by jomjol** [comment]
Just put once manually the following line into the config.ini in the section `[Analog]`:

`ExtendedResolution = true`
