### ISSUE TITLE
Value reading needs adjustment?

### ISSUE THREAD

**Issue by Dutchy-79** [jomjol/AI-on-the-edge-device#803]
Hi,

My value is wrong, How can i setup right? I set up from left to right and turned off analog to check but no luck there.
![watermeter](https://user-images.githubusercontent.com/22749572/168428986-a64df272-ef39-4eaf-a54f-c64f2909dd9b.png)

**Comment by JensHoRi** [comment]
The areas of ROI are to big, easy to see. Those reflections are difficult, but first try to configure ROai some better

**Comment by Dutchy-79** [comment]
Thanks, I thought the number had to be in the inner rectangle. I'll setup again.

**Comment by JensHoRi** [comment]
Yes, sure. But the inner needs to be exact size of the number. If you share the screen of roi I can check and give hints. In the wiki is also a document with examples of correct and incorrect configuration

**Comment by Dutchy-79** [comment]
Raw reeds mostly correct, Maybe I can skip last digit and use analog for that position?
Raw Value:
0245700N
![watermeter](https://user-images.githubusercontent.com/22749572/168474918-e30730e7-0f68-49a5-a478-92ae289efbe2.png)

**Comment by JensHoRi** [comment]
Try with dx 22 and reposition exakt over the numbers.

Mobil gesendet

**Comment by Dutchy-79** [comment]
Thanks, the value becomes better but only raw is about right. Are there settings for the last 3 digits?

![Screenshot_20220515-195410_Chrome](https://user-images.githubusercontent.com/22749572/168486961-53d062ad-77c2-4bbc-a5c9-525a0d496420.png)

**Comment by JensHoRi** [comment]
First you should set in config digits 3 to left, then every value is calculated / 1000

further you should set the prevalue to 2452.078

**Comment by JensHoRi** [comment]
Is your issue solved?

**Comment by Dutchy-79** [comment]
Sorry, yes it's solved for the big part. The readings are failing so I went back to the proximity sensor which was more accurate.
