### ISSUE TITLE
No IPv6 support

### ISSUE THREAD

**Issue by bzfbd** [jomjol/AI-on-the-edge-device#804]
"IOT" things without IPv6 support are destined to not survive the lifetime of their installs.
Does the underlying framework support IPv6?  If so I'd be happy to help implementing it if you can point me to some docs.  I am new to this ESP business but I do know IP and low level programming.

**Comment by jomjol** [comment]
I'm using the standart Espressif esp-idf. Documentation says, that it is in principle compatible with IPv6, but I never took care. Maybe some compiler options needs to be enabled. I don't tend to follow this currently for this reason.

You could make a fork and enable IPv6 for your purposes

**Comment by jomjol** [comment]
No further activities --> closing
