### ISSUE TITLE
Disable digits with checkbox

### ISSUE THREAD

**Issue by AseKarlsson** [jomjol/AI-on-the-edge-device#805]
Hi Jomjol,

Thanks for all the help earlier, sadly 3 days after finishing all the calibration and everything working fine, I received a letter from the water company that they will replace my meter.

This new meter has an air bubble in it that moves around and gives me false readings.
For next release would be a great feature to be able to disable/ignore some digits (with checkbox) even if they are setup as ROI (digital).

The new meter came with 00000.0000 so the digits most to the left are not important for a very long time, and those are the ones giving me issues.

When is the next major release expected?

Thanks,
Ase

**Comment by jomjol** [comment]
Currently I don't know, when the next release is expected. Currently I just don't have time to implement the next features. But it is not planned to disable/enable ROIs via checkbox.

There is a simple work around. You can manually comment them out in the expert mode in the config.ini directly (";")

**Comment by AseKarlsson** [comment]
Thanks Jomjol,
Thats good enough, thanks for the tip!
//Ase
