### ISSUE TITLE
Strange Number jumping +1

### ISSUE THREAD

**Issue by Albretti** [jomjol/AI-on-the-edge-device#807]
Hi,

I observe now over a long time that the interpretation/calculation of the final value calculation adds always +1.
E.g. Raw Value is 00192.21957 but the actual value displayed then is 193.21957.

![Bildschirmfoto 2022-05-17 um 10 05 03](https://user-images.githubusercontent.com/36680021/168761921-29898ebf-f028-4bef-b570-7af2a28f44a6.jpg)

I have installed: master - v10.5.2 - 2022-02-22

Thanks for feedback on this

**Comment by jomjol** [comment]
This comes from the "CheckIncreaseConsitency" algorithm. Details can be found here: https://github.com/jomjol/AI-on-the-edge-device/wiki/Correction-Algorithm

You can en-/disable this in the configuration (extended settings). For one time you need to reset the prevalue
