### ISSUE TITLE
Error reading Numbers

### ISSUE THREAD

**Issue by luisrival** [jomjol/AI-on-the-edge-device#808]
Hi.

Can you help me? I´m new in this. 

I´m trying to read my watter meter but I have some error when trying to read it

![imagen](https://user-images.githubusercontent.com/8862466/169435740-14b92cd1-60d6-4dd8-b235-eb8ad2d294b0.png)

The numbers are clear enough to read it, I try with all the models and still no working.

My config is: 

`[MakeImage]
;LogImageLocation = /log/source
WaitBeforeTakingPicture = 5
;LogfileRetentionInDays = 15
Brightness = 0
Contrast = 2
Saturation = 0
LEDIntensity = 55
ImageQuality = 5
ImageSize = VGA
FixedExposure = false

[Alignment]
InitialRotate = 176
InitialMirror = false
SearchFieldX = 20
SearchFieldY = 20
AlignmentAlgo = default
FlipImageSize = false
/config/ref0.jpg 87 181
/config/ref1.jpg 245 57

[Digits]
Model = /config/ana-s3-q-20220105.tflite
LogImageLocation = /log/digit
LogfileRetentionInDays = 3
ModelInputSize = 20 32
main.1 176 109 30 51
main.2 209 108 30 51
main.3 242 106 30 51
main.4 275 106 30 51
main.5 306 106 30 51

;[Analog]
Model = /config/ana-s3-q-20220105.tflite
;LogImageLocation = /log/analog
;LogfileRetentionInDays = 3
ModelInputSize = 32 32
main.ana1 432 230 92 92
main.ana2 379 332 92 92
main.ana3 283 374 92 92
main.ana4 155 328 92 92

[PostProcessing]
;main.DecimalShift = 1
PreValueUse = true
PreValueAgeStartup = 720
AllowNegativeRates = false
;main.MaxRateValue = 0.2
main.MaxRateType = AbsoluteChange
main.ExtendedResolution = false
main.IgnoreLeadingNaN = true
ErrorMessage = true
CheckDigitIncreaseConsistency = false

[MQTT]
Uri = mqtt://192.168.15.210:1883
MainTopic = LV-Automation/wasserzaehler
ClientID = wasser
user = mqtt
password = *****

;[GPIO]
;IO0 = input disabled 10 false false 
;IO1 = input disabled 10 false false 
;IO3 = input disabled 10 false false 
;IO4 = built-in-led disabled 10 false false 
;IO12 = input-pullup disabled 10 false false 
;IO13 = input-pullup disabled 10 false false 
LEDType = WS2812
LEDNumbers = 2
LEDColor = 150 150 150

[AutoTimer]
AutoStart = true
Intervall = 4

[Debug]
Logfile = false
LogfileRetentionInDays = 3

[System]
TimeZone = CET-1CEST,M3.5.0,M10.5.0/3
;TimeServer = undefined
;AutoAdjustSummertime = false
;Hostname = undefined
SetupMode = false
`

Thanks for the help. :D

**Comment by friedpa** [comment]
Unfortunately with this picture it will never work. Please read the Wiki to improve the picture.
Attached a sample how it should look like:
![grafik](https://user-images.githubusercontent.com/42890695/169464531-a18cfded-3eb3-4be6-8ba3-275de79c19ba.png)

**Comment by pixeldoc2000** [comment]
The Picture is out of focus. **You need to adjust the Focus of the Camera!** The is almost no Change for the AI to use such a bad Image, even if it is still possible for a human ;-)

**Comment by jomjol** [comment]
Please reopen, in case a correct setup is still not working.
