### ISSUE TITLE
Request: extra "delta" field in MQTT

### ISSUE THREAD

**Issue by wokkeltje13** [jomjol/AI-on-the-edge-device#811]
Would it be possible to push an extra field towards MQTT with the delta between the previous and the new value recognised? Just the diffference between the "value" and the previous value sent to MQTT without any extra calculation (so + or - difference)

This would help me with creating 2 sensors in HA for house2grid and grid2house calculation to use in the Energy dashboard. 

The "rate" field is hard to use since it is a calculation based on a timeframe of 1 minute.

thanks

**Comment by jomjol** [comment]
I have implemented an extra field in the MQTT messages in the newest rolling version from today (2022-05-26)

**Comment by jomjol** [comment]
The absolute value is only transmitted in case there is no error, as the value and the rate.

If you want to handle the error case, you can parse the error code, this should contain the wrong value as well.

**Comment by wokkeltje13** [comment]
That is the issue, value and rate are correctand no error, but absolute value remains 0.

**Comment by jomjol** [comment]
I will check for this.

**Comment by wokkeltje13** [comment]
any chance to check why the new absolute value remains zero all the time?

tnx in advance

**Comment by jomjol** [comment]
@wokkeltje13 thx for the reminder. First had not time, than forgott about it. 

Just found the error and it should be working with the just released "Rolling" version.
Mine is now having a non zero value:
![grafik](https://user-images.githubusercontent.com/30766535/172926856-d3016649-4355-493f-8a92-d0b950d89a47.png)

**Comment by wokkeltje13** [comment]
Tnx, this seems to be working now.
