### ISSUE TITLE
Problems with air in the watermeter

### ISSUE THREAD

**Issue by kami83** [jomjol/AI-on-the-edge-device#812]
Hi,

i am trying to get valid values from my watermeter. After a lot of testings i always got problem with the first two values. 

There is air in the watermeter. Is there any way to fix it? 

BG kami
![grafik](https://user-images.githubusercontent.com/930181/170215866-52ead3ea-a6b6-4768-8842-67e01d7dab13.png)

**Comment by jomjol** [comment]
Well, that  is really difficult thing. And as the bubble can look different from time to time, I don't see a change to handle this in general.

**Comment by kami83** [comment]
Hi,

i changed the camera and with this cam it is working much better:

![grafik](https://user-images.githubusercontent.com/930181/170673007-3fa2a313-33cc-4821-80b2-b7af106ae9a2.png)

BR kami
