### ISSUE TITLE
Round or reduce the raw value?

### ISSUE THREAD

**Issue by kami83** [jomjol/AI-on-the-edge-device#813]
Hi,

is it possible to remove the last number? Because it is jumping a little bit and i get this error:

![grafik](https://user-images.githubusercontent.com/930181/170272823-d541f85b-4b91-446f-b1c7-1ac4fd1db350.png)

thanks a lot.

Best regards kami

**Comment by wokkeltje13** [comment]
why not just remove the last ROI so it will not be analyzed

**Comment by jomjol** [comment]
You need to disable the extended resolution:
![grafik](https://user-images.githubusercontent.com/30766535/170351653-c4caaf5a-0200-4f76-a90b-06d48a5158d0.png)
