### ISSUE TITLE
Idea: absolute and relative change

### ISSUE THREAD

**Issue by JensHoRi** [jomjol/AI-on-the-edge-device#821]
Actually only absolut change or change per minute possible. 

Instead of type absolute or relative combination would be helpful. Say 0.3 absolute allowed, and before e.g. 0.4 rate gives error high rate the relative rate like 0.05 per minute could be checked. I beliehe could have better failure correction as actual one or other ways for rate. 

Could be a „fast workaround“ until digits between two values are accepted ;)

**Comment by jomjol** [comment]
Thanks for the idea. Currently sometimes it is for some people even hard to understand the difference between absolut and relative. Making a combination of this will result in more confusion, than solving the problem. You could do that locally on your system.
