### ISSUE TITLE
How can i get N values as an error

### ISSUE THREAD

**Issue by kami83** [jomjol/AI-on-the-edge-device#823]
Hi, 

sometimes i get this picture so the number can be found. I just want to get this as an error.

Thx a lot.

BR kami

![grafik](https://user-images.githubusercontent.com/930181/173087977-fea9515d-3471-4db1-8a67-c1caee7ac94b.png)

**Comment by jomjol** [comment]
There are only two options: disable the "UsePreValue" --> then the "N" will also be reported, but no consistency check is possible
Or do a readout via the JSON string "/json", there you also find the raw value.
I do not plan to extend any feature regarding the "N", as the next bigger release should have another neural network, that can handle inbetween number.
