### ISSUE TITLE
First digit correction?

### ISSUE THREAD

**Issue by liflitz** [jomjol/AI-on-the-edge-device#824]
I have 01419 with a slightly moved but still fully visible 9 on my water meter, but the reading is consistently 01418. I set 01419 manually as prevalue. Is there a combination of settings, that would automatically correct the 01418 to 01419? I guess I don't really understand the exact consequences of the PreValueUse, AllowNegativeRates and CheckDigitIncreaseConsistency settings, but none of the combinations I tried delivered 01419 as value. Below my current PostProcessing settings and a current screen shot.

Thanks for this great project, I love it!!

[PostProcessing]
main.DecimalShift = 0
PreValueUse = true
PreValueAgeStartup = 720
AllowNegativeRates = false
;main.MaxRateValue = 1
;main.MaxRateType = RateChange
main.ExtendedResolution = true
main.IgnoreLeadingNaN = true
ErrorMessage = true
CheckDigitIncreaseConsistency = false  [or true, same outcome]

![image](https://user-images.githubusercontent.com/84687915/173226796-5d53409c-8cec-4d64-8d7f-e8e820bbd528.png)

Side question: for adding new images for training, should we include images with such slightly off yet still fully visible digits?

Super dummy/beginner/egoist question: At this point in time, all I care about are the 10 digits on my water meter. Any chance I can create a model myself locally only for my setup and my images for training? Is this foreseen in this project?

**Comment by jomjol** [comment]
Which tflite files are you using for the digital part (see config.ini)?

Regarding training: currently I need fully centered numbers, but your type is principally already in the training data. There are further developments ongoing, where you later can also recognize a e.g. 8.9 for your last digit

Regarding self training: in principal possible, but not that well documented: https://github.com/jomjol/neural-network-digital-counter-readout

**Comment by liflitz** [comment]
[Digits]
Model = /config/dig-s2-q-20220211.tflite

**Comment by jomjol** [comment]
Then the raw value must be a wrong reading and the "9" has been deteced as an eight.'
You can check this with the menue point Recognition.

How did you setup the ROI? Can you post an image of this.

**Comment by liflitz** [comment]
Yes, this is what happened, the 9 was detected as 8 repeatedly. But by now the 9 has "moved on" - let's see what happens when it comes back. The 4 in the picture above only gets detected about half of the time, but at least it gives NaN otherwise.

Here the GUI figure with the red boxes:

![image](https://user-images.githubusercontent.com/84687915/173416082-7cf0031c-ab13-49d8-b629-1b6747e7ecec.png)

Here from the config.ini:

[MakeImage]
LogImageLocation = /log/source
WaitBeforeTakingPicture = 5
LogfileRetentionInDays = 7
Brightness = 
Contrast = 
Saturation = 
LEDIntensity = 10
ImageQuality = 
ImageSize = VGA
FixedExposure = true

[Alignment]
InitialRotate = 100.6
InitialMirror = false
SearchFieldX = 20
SearchFieldY = 20
AlignmentAlgo = default
FlipImageSize = false
/config/ref0.jpg 284 202
/config/ref1.jpg 326 125

[Digits]
Model = /config/dig-s2-q-20220211.tflite
LogImageLocation = /log/digit
LogfileRetentionInDays = 7
ModelInputSize = 20 32
main.dig1 227 150 22 43
main.dig2 264 150 22 43
main.dig3 302 150 22 43
main.dig4 339 150 22 43
main.dig5 376 150 22 43

[Analog]
Model = /config/ana-s3-q-20220105.tflite
LogImageLocation = /log/analog
LogfileRetentionInDays = 7
ModelInputSize = 32 32
main.ana1 409 233 70 70
main.ana2 367 314 70 70
main.ana3 290 348 70 70
main.ana4 189 311 70 70

[PostProcessing]
main.DecimalShift = 0
PreValueUse = true
PreValueAgeStartup = 720
AllowNegativeRates = false
main.MaxRateValue = 0.5
main.MaxRateType = AbsoluteChange
main.ExtendedResolution = false
main.IgnoreLeadingNaN = true
ErrorMessage = true
CheckDigitIncreaseConsistency = true


After more tweaking with the settings, your program seems to do a pretty good job: 

![image](https://user-images.githubusercontent.com/84687915/173416873-51c22acb-e26a-4b4d-9c5b-a25ae2891d68.png)

What do you think about my image quality? Resolution seems pretty low.

Thanks for your help!!!!!!!!!!!!

**Comment by caco3** [comment]
is this still an issue?
Resolution is ok and its AAIK normal that it is lower as on the setup to make the processing faster/possible.

**Comment by liflitz** [comment]
runs like a charm - still lots of reading errors, but with all the corrections in place the results clearly fit my needs- thanks!!!

**Comment by haverland** [comment]
> runs like a charm - still lots of reading errors, but with all the corrections in place the results clearly fit my needs- thanks!!!

You could try the class100 or cont models. But reduce the height of the ROIs
<img width="455" alt="ROI-setup" src="https://user-images.githubusercontent.com/412645/193111193-19758abc-eb86-42a9-93bd-157277500144.png">

**Comment by jomjol** [comment]
Then I close this issue
