### ISSUE TITLE
Digitizer - AI on the edge - watermeter || Messwerte werden nicht angezeigt / abgelesen

### ISSUE THREAD

**Issue by Takahara2022** [jomjol/AI-on-the-edge-device#825]
Guten Abend,

ich komme gerade aus dem Urlaub zurück und wollte kurz den Wasserverbrauch überprüfen. Ich kann zwar noch die Weboberfläche des watermeter öffnen, eine Ablesung des aktuellen Verbrauchwertes erhalte ich allerdings nicht mehr. Auch kann ich das Menü nicht mehr öffnen. Habe ich bereits in unterschiedlichen Browsern versucht. Allerdings ohne Erfolg.

![2022-06-17 22_26_38-Window](https://user-images.githubusercontent.com/104391155/174397090-d1fe1717-2c1b-4316-8c18-9017c99eaf40.png)

Hatte schon jemand das Problem?

VG
Takahara

**Comment by jomjol** [comment]
Da hat sich irgendwas aufgehangen. Am besten mal neu starten (Strom aus). Wenn das auch nicht hilft ist entweder die SD-Karte defekt oder der ESP32.

**Comment by Takahara2022** [comment]
Hallo jomjol, die Spannungsversorgung hatte ich bereits getrennt, leider hat es nicht geholfen. Ich habe einen neuen ESP32 genommen und kann wieder den Zählerstand ablesen.
Danke hierfür!!!!!!

Aller habe ich noch ein kleines Problem mit der Lichtreflexion des eingebauten Blitzlichtes im ESP32. Wie du auf dem Bild sehen kannst, ist das Blitzlicht an einer "ungünstigen" Stelle für meinen Wasserzähler positioniert. Die Lichtreflexion an der letzten Vorkommastelle führt zu Ablesefehlern (jedenfalls bei meinem Setup).
Hättest du noch Tipps/Ideen was ich versuchen könnte, um die Ablesung zu verbessern?

![2022-06-18 13_09_37-Window](https://user-images.githubusercontent.com/104391155/174435212-8f339d1e-76b4-4609-bcd1-f674885f5c42.png)

VG
Takahara

**Comment by jomjol** [comment]
Die Reflektion sitzt nicht ganz in der Mitte, du könntest deinen Aufsatz leicht drehen, so dass sie nicht mehr in der Ziffer sitzt und dir Drehung dann nachher in der Konfiguration korrigieren.

**Comment by Takahara2022** [comment]
Ich hab am Gehäuse etwas gesägt und gefeilt damit ich es drehen konnte.
Was ich nicht ganz verstehe, ist der Qualitätsunterschied zwischen dem Reference Image und dem tatsächlichen Image.

Reference Image (gut lesbare Ziffern):
![2022-06-18 18_08_21-jomjol - AI on the edge](https://user-images.githubusercontent.com/104391155/174447199-df29d2f3-12e4-40aa-adcb-ce04753c26b0.png)

 Tatsächlichen Image (verschwommene  Ziffern):
![2022-06-18 18_08_49-jomjol - AI on the edge - watermeter](https://user-images.githubusercontent.com/104391155/174447223-6eb2a6d6-8667-4e0d-a612-8f5b81f3f110.png)

Kannst du das erklären?

VG Takahra

**Comment by jomjol** [comment]
Ja klar - das liegt daran, das das Referenzbild im Browser mit Antialising etc. gerenert wird. Auf dem ESP32 läuft nur ein sehr primitiver Algo zur Bildrotation, wodurch sich Kanten ergeben.
