### ISSUE TITLE
increase detection of last digit

### ISSUE THREAD

**Issue by NemoN** [jomjol/AI-on-the-edge-device#83]
The last digit of my watermeter uses a different /smaller font. 
Is there possibly a way to improve the detection?

<img width="670" alt="Bildschirmfoto 2021-01-02 um 11 58 47" src="https://user-images.githubusercontent.com/2212175/103455977-2286fa80-4cf2-11eb-889b-3df31f5e9078.png">

**Comment by jomjol** [comment]
Yes - please collect some examples of you last digit (2-3 for each digt 0..9) put them in a ZIP-file and post them to me. I will incorporate them in the next CNN-training.
**REMARK**: you should make your ROIs a little big bigger - they must not touch the border of the image. This is teached as "NaN", which you actually see.

![grafik](https://user-images.githubusercontent.com/30766535/103456281-e1dcb080-4cf4-11eb-9079-818d52ec6533.png)

This might already improve the results.

I will close this issue - for the time beeing. Please reopen, if you have images.
