### ISSUE TITLE
Error: Rate too high - read difference .2 

### ISSUE THREAD

**Issue by ThoHilde** [jomjol/AI-on-the-edge-device#830]
Hello,

I get this error even though the value has only increased by 0.2 since the last measurement. I only have the first analogue counter, as the counter for 0.01 and 0.001 is difficult to see. Can this be the reason? Attached is a photo of my measurement picture:
![grafik](https://user-images.githubusercontent.com/99014551/174483395-cfd36b0e-310b-4daf-9de8-2fdfc0c6c0c6.png)

**Comment by haverland** [comment]
Could it be the MaxRateValue=0.1? 
The recognition is not 100% so sometimes it can be a small value grows up. In this case the 0.01 analog counter ist on zero. 
Yes >100l is a bit much in 5 minutes. I would set the MaxRateValue to .2 or .3
Otherwise the post process generates this error.

**Comment by Shineson1001** [comment]
I agree with @haverland 
i use 0.5 for MaxRateValue with an interval of 3 minutes.

**Comment by ThoHilde** [comment]
Thank you for your input.
I changed it to 0.5 and it seems to work now.

**Comment by jomjol** [comment]
problem solved --> close the issue
