### ISSUE TITLE
Digit Training Data

### ISSUE THREAD

**Issue by mitch-geht-ab** [jomjol/AI-on-the-edge-device#831]
Hi,
find attached some digit training materials.
[training.zip](https://github.com/jomjol/AI-on-the-edge-device/files/8955984/training.zip)

As you can see, not every digit is rotating in a full way, even if it is relatively close to 8...9...0.
Another special is, that the digits looks diverent after the decimal place (smaller and bit thinner).
![grafik](https://user-images.githubusercontent.com/8008251/174984732-4ea816ca-327a-493c-91c5-aa8209e16e40.png)

And I have also include some N values.

BR
Mitch

**Comment by jomjol** [comment]
Hi - thanks for the images, unfortunatly I cannot use most of them for the training, as the ROI does not fit the criteria: https://github.com/jomjol/AI-on-the-edge-device/wiki/ROI-Configuration

- Some of them are too small
- "N" pictures are not needed anymore. In a future version the "N" will be removed anyway.
- some of them are really at the lower boarder. I don't want to put them to the general training.

Example:
![grafik](https://user-images.githubusercontent.com/30766535/176752352-a1d20b97-ca8a-40a7-bb63-17ef984ed3df.png)
![grafik](https://user-images.githubusercontent.com/30766535/176753226-9afe6771-acff-48bf-9902-08bb61f9dcd5.png)


I will use some of them, but not all.
