### ISSUE TITLE
Idea: Modified clear ESP32 3D printed housing as a diffuser

### ISSUE THREAD

**Issue by ykri** [jomjol/AI-on-the-edge-device#836]
@jomjol thanks for this great project!

Here is a modified 3D printed housing for the ESP32 where the on board LED is covered with clear material that acts as a light diffuser.
[esp_housing_with_diffuser-ykri.zip](https://github.com/jomjol/AI-on-the-edge-device/files/8984824/esp_housing_with_diffuser-ykri.zip)

I used clear flexible TPU-95A that I had at home, but I guess any clear filament will do, PETG, PLA, etc.
I printed with 25% infill and Cubic pattern in CURA so the infill becomes like a prism and diffuses light. Actually as the whole housing is of clear material it even helps more the diffusion. I also covered with black electrician tape the side of the LED cover towards the camera lens.
It most certainly works as you can see from the screenshot, although there is a lot of reflection even above some digits.
As I do not have a Thingiverse account, feel free to uploaded the model as an option along with the rest of the models you have shared with us.

![Screenshot_20220625_162638](https://user-images.githubusercontent.com/16511588/175775820-25b8d526-1314-44b2-bb57-634bea3eed9b.png)

**Comment by jomjol** [comment]
Thanks for the idea - anyway I close it, as it is not really an issue for the software.
