### ISSUE TITLE
Training Data - Sensus digital readout

### ISSUE THREAD

**Issue by pbartko** [jomjol/AI-on-the-edge-device#840]
First, thank you for your software, I love the concept.

I ran through your instructions and installed the software and it is now running.  However, I'm not getting accurate indentification of some numbers.  I think this is primarily due to the bars that the meter placed above each number except for the least significant number.
![image](https://user-images.githubusercontent.com/34517866/176318095-182691d6-571c-479f-a379-b0755562f611.png)
Here is a set of training images I recorded.  I've included one image for each number without the bar above.  Not sure if this will cause an issue or not?  If necessary, I can eliminate that least significant digit from the analysis.

[TrainingData.zip](https://github.com/jomjol/AI-on-the-edge-device/files/9005937/TrainingData.zip)

**Comment by jomjol** [comment]
Trained within the newest rolling: https://github.com/jomjol/AI-on-the-edge-device/raw/rolling/sd-card/config/dig1400s2q.tflite
