### ISSUE TITLE
Powermeter Alternation two values

### ISSUE THREAD

**Issue by pos-ei-don** [jomjol/AI-on-the-edge-device#841]
Hi.
I hope I did not overread the solution.
My Powermeter alternates in the Display
Two seperate values. (Power used and Power sold) 
Is there any concept how can I seperate both values and hinder that they corrupt their values each other?

**Comment by pos-ei-don** [comment]
Here are two Photos. 

![IMG_20220629_060014676](https://user-images.githubusercontent.com/1822533/176349844-383eacb6-4c74-41a0-a077-2b5d693cdb8d.jpg)
![IMG_20220629_060022946](https://user-images.githubusercontent.com/1822533/176349856-1c842911-ab59-4248-ab49-b69f15c68235.jpg)

**Comment by friedpa** [comment]
The problem lies in the sync between the pictures to be taken and the picture taken by the ESP. If you are not able to sync these two events it will not work.

**Comment by pos-ei-don** [comment]
What does it do when the Aligment is not porrible. If I take the 1.8 as Aligment?
If it cannot find this, does it throw away the taken picture and waits for the next run?

**Comment by friedpa** [comment]
This is corrently not forseen in the SW, but maybe you can fork the SW and adapt it.

**Comment by pos-ei-don** [comment]
I Understand.
But the question is still: What does it do when part of the aligment is not existing.

Should i be able to find the  answer in this file?
https://github.com/jomjol/AI-on-the-edge-device/blob/71871016d24079e675a3963e0cc501983f3048cb/code/components/jomjol_flowcontroll/ClassFlowAlignment.cpp

**Comment by savikko** [comment]
You should probably find solution from Shelly 3EM or equivalent.

**Comment by jomjol** [comment]
if the alignment is not working, it will make an arbitrary rotation. In the current network the resut cannot be foreseen.

But I would have another idea: what if you make two numbers: one with the 1.8.0 / 2.8.0 (or only the 1 or 2) and the second with the real number. Than you can distinguish in your system if it is a 1 or a 2. 
But you need to disable all error correction algorithms, as these will not work anymore with jumping readouts.

I will close the issue, but you can still write into this.

**Comment by pos-ei-don** [comment]
Thank you very much for your idea. I tried it and it seems to work perfektly.
