### ISSUE TITLE
Analog training data

### ISSUE THREAD

**Issue by liflitz** [jomjol/AI-on-the-edge-device#842]
Dear jomjol,

Here analog training data for the reader I described here recently:

[ana1-3.zip](https://github.com/jomjol/AI-on-the-edge-device/files/9014834/ana1-3.zip)
[ana4.zip](https://github.com/jomjol/AI-on-the-edge-device/files/9014835/ana4.zip)

Ana4 looks principally different from Ana1-3, so I made two datasets. Ana1, Ana2 and Ana3 also differ from each other in shades and lighting - just let me know if you need more images.

Thanks a lot for your great efforts (just installing a second system!),

liflitz

**Comment by jomjol** [comment]
Trainined within the newest rolling version: https://github.com/jomjol/AI-on-the-edge-device/raw/rolling/sd-card/config/ana1000s2.tflite
