### ISSUE TITLE
Digital training data

### ISSUE THREAD

**Issue by liflitz** [jomjol/AI-on-the-edge-device#844]
Dear jomjol,

Here digits for training from my second device.
[digits.zip](https://github.com/jomjol/AI-on-the-edge-device/files/9023091/digits.zip)

Thanks a lot and best wishes,

liflitz

**Comment by jomjol** [comment]
Training within the new rolling version: https://github.com/jomjol/AI-on-the-edge-device/raw/rolling/sd-card/config/dig1400s2q.tflite
