### ISSUE TITLE
kein richtigen Raw Wert

### ISSUE THREAD

**Issue by bmause** [jomjol/AI-on-the-edge-device#848]
Hallo zusammen, 

ich versuche meinen Gaszähler auszulesen, Konfiguration habe ich auch schon mehrmals gemacht. 
leider bekomme ich keine richten Werte angezeigt.
NNNNNNN00000 
wer kann da einen Frischling weiterhelfen ?
<img width="986" alt="Bildschirmfoto 2022-07-05 um 16 42 45" src="https://user-images.githubusercontent.com/105861086/177355162-655a95da-4b9b-40f6-8436-3f73b6dd678a.png">
<img width="495" alt="Bildschirmfoto 2022-07-05 um 16 43 01" src="https://user-images.githubusercontent.com/105861086/177355186-830776ba-a26a-48e9-af43-93ab60a9a13a.png">

**Comment by jomjol** [comment]
Das sieht danach aus, also ob das tflite-File nicht gelesen werden kann, da keine einzige Ziffer erkannt wird.
Prüfe mal bitte, ob das File in der config.ini auch im Verzeichnis /config vorhanden ist.

**Comment by bmause** [comment]
Danke für deine Unterstützung.
Das tflite liegt im Verzeichnis/config, öffnen kann ich es nicht.
<img width="879" alt="Bildschirmfoto 2022-07-07 um 07 40 48" src="https://user-images.githubusercontent.com/105861086/177700386-7f10a436-6f44-48a7-9738-cf9062dd1d98.png">
<img width="972" alt="Bildschirmfoto 2022-07-07 um 07 43 04" src="https://user-images.githubusercontent.com/105861086/177700396-d4802da6-34bc-4914-ae8b-ccc325cc372c.png">

hoffe du kannst mir da noch weiterhelfen

**Comment by haverland** [comment]
Den Fehler hatte ich gerade auch mit der letzten Rolling Firmware. Die 10.6.0 (master) funktioniert aber.
Ich schreibe den Fehler mal ins Log. Auf der Serial Console sieht den keiner.

**Comment by haverland** [comment]
Sorry ich konnte nicht mehrere Pull requests erstellen. Der mit dem "." ist nur für die neuen Modelle (deren Namen).
Ich konnte die Modelle gar nicht verwenden mit der Firmware aus dem Rolling. Leider konnte ich das auch nicht mit selbst erstellten Build nachstellen. Deshalb nur im Logfile den Fehler vermerkt mit der Output-Shape. Dann kann man darüber herausfinden, woran es liegt - falls es noch einmal auftritt.

**Comment by JensHoRi** [comment]
@bmause : Problem mittlerweile behoben? Durch reboot? Oder andere Firmware?

**Comment by jomjol** [comment]
Bugfix ist erledigt
