### ISSUE TITLE
Can i use this to monitor my gas meter?

### ISSUE THREAD

**Issue by gbdavidx** [jomjol/AI-on-the-edge-device#849]
https://www.mercurynews.com/2011/12/19/pge-offers-to-let-customers-keep-analog-mechanical-meters/
this is what it looks like:
![image](https://user-images.githubusercontent.com/26369204/177463180-88870c13-a96e-41ea-8742-5ce10a0b4d6c.png)

**Comment by jomjol** [comment]
Hi not directly out of 2 reasons:
1) this kind of pointers is not in training data
2) there is no option for counter clockwise rotation.
