### ISSUE TITLE
Feature Request: Option to disable the digital ROIs and use only analog ROIs

### ISSUE THREAD

**Issue by Quantum-cross** [jomjol/AI-on-the-edge-device#85]
Is there a flag somewhere I need to set to use CCW analog dials?

**Comment by jomjol** [comment]
What do you mean with CCW analog dials?

**Comment by Quantum-cross** [comment]
![image](https://user-images.githubusercontent.com/7065792/103534120-46664f80-4e5c-11eb-89aa-344193c43a70.png)

I know my camera position is terrible, I'm still just experimenting :)

**Comment by MMeinhardt1** [comment]
CounterClockWise

**Comment by jomjol** [comment]
Okay - got it.
This is a new task, as this is the first "only analog" device. Not a real problem, but at the moment the internal code is assuming, minimum one digital digit as an input. If you delete all digits, it will not run properly.
Only for the analog counters, there is the option to delete. I will add this, but it might take some time as at the moment I'm working on the alignment algo and some of the other Feature Requests.

**Comment by Quantum-cross** [comment]
Ok, as a note, I am running 4.1.1 right now (5.0.0 is giving me issues with SD card initialization).

4.1.1 seems to work fine with zero digital counters, and I have made some quick changes to allow for CCW analog counters in 4.1.1 and it seems to be working. I'd make a pull request but I can't get v5 working properly to test it.

**Comment by jomjol** [comment]
Implemented in the newest Rolling
