### ISSUE TITLE
No digits recognized

### ISSUE THREAD

**Issue by Plawasan** [jomjol/AI-on-the-edge-device#851]
Hi,

Great project! I've set everything up but I'm having very little luck with the actual recognition of digits (analog seems to works perfectly fine)

![image](https://user-images.githubusercontent.com/73796046/177964221-f8a6f70c-56e8-4f5e-8a8e-b412187fb120.png)

Any pointers? I've tried to adjust the ROIs many different times but I'm not getting any consistent results. If I need to provide more learning data for my typeset I'm happy to do it.

Thanks!

config.ini:
```
[MakeImage]
LogImageLocation = /log/source
WaitBeforeTakingPicture = 1
;LogfileRetentionInDays = 15
Brightness = 0
Contrast = 0
Saturation = 0
LEDIntensity = 5
ImageQuality = 12
ImageSize = VGA
FixedExposure = false

[Alignment]
InitialRotate = -186
InitialMirror = false
SearchFieldX = 20
SearchFieldY = 20
AlignmentAlgo = default
FlipImageSize = false
/config/ref0.jpg 508 167
/config/ref1.jpg 313 264

[Digits]
Model = /config/dig-s2-q-20220211.tflite
LogImageLocation = /log/digit
LogfileRetentionInDays = 3
ModelInputSize = 30 40
main.dig1 221 168 28 53
main.dig2 263 166 27 56
main.dig3 310 164 24 58
main.dig4 355 160 34 63
main.dig5 398 159 35 63
main.dig6 444 156 41 77

[Analog]
Model = /config/ana-s3-q-20220105.tflite
;LogImageLocation = /log/analog
;LogfileRetentionInDays = 3
ModelInputSize = 32 32
main.ana1 451 243 136 136

[PostProcessing]
main.DecimalShift = -3
PreValueUse = false
PreValueAgeStartup = 720
AllowNegativeRates = false
main.MaxRateValue = .100
main.MaxRateType = RateChange
main.ExtendedResolution = true
main.IgnoreLeadingNaN = true
ErrorMessage = true
CheckDigitIncreaseConsistency = false

[MQTT]
Uri = mqtt://192.168.1.3:1883
MainTopic = water-cold
ClientID = water-cold
user = watermeter
password = xxxxxxxxxxxx

;[GPIO]
;IO0 = input disabled 10 false false 
;IO1 = input disabled 10 false false 
;IO3 = input disabled 10 false false 
;IO4 = built-in-led disabled 10 false false 
;IO12 = input-pullup disabled 10 false false 
;IO13 = input-pullup disabled 10 false false 
LEDType = WS2812
LEDNumbers = 2
LEDColor = 150 150 150

[AutoTimer]
AutoStart = true
Intervall = 3

[Debug]
Logfile = true
LogfileRetentionInDays = 3

[System]
TimeZone = CET-1CEST,M3.5.0,M10.5.0/3
;TimeServer = undefined
;AutoAdjustSummertime = false
;Hostname = undefined
SetupMode = false
```

**Comment by friedpa** [comment]
Are you sure, that the rigtht .tflite Files are in the /config folder?

**Comment by Plawasan** [comment]
all the ones that came with the default sd-card folder plus one extra I downloaded as a test...
![image](https://user-images.githubusercontent.com/73796046/178012981-8563aaf7-ce8c-4116-ab15-1a2c30849982.png)

**Comment by friedpa** [comment]
Is the camera in the center straight over the Meter and as per the Wiki instructions all frames should be in the same size.
I am wondering why no digit is recognized, at least the 9 should be good enough.

**Comment by Plawasan** [comment]
So I started from scratch... first by utilizing a highly advanced, self-adjusting (diameter AND rotation!) alignment mechanism (with an integrated flash diffuser) to get the camera in the right position:

![image](https://user-images.githubusercontent.com/73796046/178092883-49514d06-5962-4874-bba6-a897408f6491.png)

and then by deleting my config.ini and replacing it with the stock one... and voila:

![image](https://user-images.githubusercontent.com/73796046/178092827-ab6671e3-a38f-4752-aa5e-d4a18647d1ba.png)

Thanks for the hint!

**Comment by friedpa** [comment]
Looks very good, what did you use for the diffuser?

**Comment by Plawasan** [comment]
> Looks very good, what did you use for the diffuser?

The bottom of the yogurt cup the esp is ziptied to :) I only made a small hole in it for the camera to peek through..

**Comment by friedpa** [comment]
Smart Idea!
