### ISSUE TITLE
Trigger Readout

### ISSUE THREAD

**Issue by zImage-de** [jomjol/AI-on-the-edge-device#852]
Ist es möglich einen Readout manuell anzustossen (MQTT oder RestAPI/Url request...) 
Szenario: AutoTimer 30 Minuten... ab und an will ich aber zwischenwerten (z.B. vor und nachdem die Gartenbewässerung gestartet / beendet wurde ...

**Comment by friedpa** [comment]
Ist möglich, im Wiki stehen die Abfragemöglichkeiten.

**Comment by zImage-de** [comment]
Im Wiki finde ich keine Parameter zum manuellen restart des Prozess ... unter integrated function steht "tbd." 
https://github.com/jomjol/AI-on-the-edge-device/wiki/Integrated-Functions

kann wer helfen???
Vielen Dank
Jochen Christmann

**Comment by jomjol** [comment]
Es gibt aktuell keinen richtig guten Trigger. Du kannst aber tricksen, indem du über "/reboot" einen Neustart triggerst, dann wird auch eine Lesezyklus gestartet, jedoch startet dann der Timer auch von neuem.

**Comment by friedpa** [comment]
Du kannst den Autotimer ja auf 3 bis 5 Minuten stellen, dann erledigt sich doch das Problem, oder?

**Comment by zImage-de** [comment]
Danke für eure Antwort ... 
Vielleicht ein guter "feature request" eine URL als trigger zum neuen Auslesevorgang... immer Reboot ist ja auch nicht so toll ... trotzdem aber vielen Dank !!!

**Comment by SteveWi-291** [comment]
friedpa, also 3-5 min ist für den ESP32 schon weng oberkill, der ist ja dann nur noch am "rumrödeln". Ich selber hab den Wert auf 15 min gestellt.... Ich weiß garnicht wie lang er für einen gesamten Einleseprozess braucht.....
