### ISSUE TITLE
How to handle hole within the watermeter (value prediction)

### ISSUE THREAD

**Issue by electron23** [jomjol/AI-on-the-edge-device#853]
Hey guys,

awesome project - thanks for you work. 

I have a problem with my water meter. The counter is from Ernst Heitland and has a hole over the second analogue display.

![image](https://user-images.githubusercontent.com/5521655/178325858-918b8676-642d-44fb-9f07-f73cf174a82b.png)

Is there a way to avoid the problem of calculating the second value based on the value of the 3rd position or something else? 

Thanks and best regards,
Nico

**Comment by jomjol** [comment]
Hi,
this is not possible with the current version. Technically you could estimate it, but that would be rather inaccurate and would need a strongly modified version (including user interface). This is not planned.

**Comment by electron23** [comment]
Thank you for your quick response. Then I'm still satisfied with 2 decimal places if I only use the first analog display. :-)

**Comment by friedpa** [comment]
Just do give you an idea, no one can stop you to put a second watermeter without any "funny" wholes or other things behind your "official" Watermeter. It took me 4 hours to install a watermeter without any limitations behind the official one.
I ordered my watermeter via Amazon.de

![grafik](https://user-images.githubusercontent.com/42890695/178341106-3e5e15e6-2809-4216-9fc4-93db7c27f2b7.png)
