### ISSUE TITLE
taking a picture adhoc 

### ISSUE THREAD

**Issue by albundy0815** [jomjol/AI-on-the-edge-device#854]
I have some digital power meters and they are switching the display. Would it be possible to get a function like "take a picture now" that this triggers picture, which I can open via URL?
like the URL http://xxx.xxx.xxx.xxx/img_tmp/alg_roi.jpg

**Comment by haverland** [comment]
http://IP-ESP32/capture
http://IP-ESP32/capture_with_flashlight

https://github.com/jomjol/AI-on-the-edge-device/wiki/Integrated-Functions

Do you mean such like this?

**Comment by albundy0815** [comment]
oh oh... yes this was my request - but haven't seen it in the documentation :( - sorry for that and thanks a lot!
