### ISSUE TITLE
Verbesserungsvorschlag

### ISSUE THREAD

**Issue by SteveWi-291** [jomjol/AI-on-the-edge-device#857]
Ist es möglich, dem System beim lernen zu helfen, indem man unbekannte States ihm richtig sagt?

Also ich stell mir das so vor:

Bei wechsel von 7 auf 8 hat ja das System oft schwierigkeiten den Wechsel zu erfassen und schreibt dann ein N ins JSON. Wenn das passiert, könnte man doch dem "System" sagen, dass es jetzt ein wechsel von 7 auf 8 ist. Falls das auf dem System nicht möglich ist, wäre es doch nicht schlecht, wenn man einfach einen button klickt, der dann dieses Bild an einen deiner Server schickt damit du die KI dann gezielt trainieren kannst.

Falls das nicht möglich wäre, dann auch nicht schlimm :)

Ein zweiter Verbesserungsvorschlag.

Man kann ja in den Einstellungen den momentanen Wert ein eingeben, damit er die Differenz anzeigen kann bzw weiß, ob der neue Wert größer ist oder kleiner. Bei mir kommt es oft vor, dass er durch den Wechsel oft was falsches oder nichts einliest und dann den Wert aktualisiert. Dann erscheint im JSON der Fehler, dass der neue Wert kleiner ist als der Alte..... Könnte man das zb auch per MQTT eintragen und der Zähler holt sich dann den Wert über MQTT? Dann müsste man nicht ständig auf Weboberfläche gehen, da das System eh ständig am "rumrödeln" ist.

Dritter Verbesserungsvorschlag. Ist es irgendwie möglich, das aktuelle Bild von der Cam irgendwie in den IoBroker zu bekommen? Das  würde einiges bezüglich handling stark vereinfachen.

Ich hoffe meine Ideen sind nicht zu absurd :) 

VG Steve

**Comment by jomjol** [comment]
> Ist es möglich, dem System beim lernen zu helfen, indem man unbekannte States ihm richtig sagt?
> 
> Also ich stell mir das so vor:
> 
> Bei wechsel von 7 auf 8 hat ja das System oft schwierigkeiten den Wechsel zu erfassen und schreibt dann ein N ins JSON. Wenn das passiert, könnte man doch dem "System" sagen, dass es jetzt ein wechsel von 7 auf 8 ist. Falls das auf dem System nicht möglich ist, wäre es doch nicht schlecht, wenn man einfach einen button klickt, der dann dieses Bild an einen deiner Server schickt damit du die KI dann gezielt trainieren kannst.

Technisch wäre soetwas denkbar. Aber es gibt zwei Gründe die dagegen sprechen:
1) viele wollen nicht, dass ein interes System irgendwelche Bilder an die Cloud schicken --> fehlende Aktzeptanz
Die Diskussion gabe es schonmal bei automatischen Updates direkt vom Server laden
2) Das würde eine Serverinfrastruktur auf meiner Seite voraussetzen, die ich schlicht nicht unterhalten möchte, da ich den Aufwand nicht for free leisten kann.

> 
> Falls das nicht möglich wäre, dann auch nicht schlimm :)
> 
> Ein zweiter Verbesserungsvorschlag.
> 
> Man kann ja in den Einstellungen den momentanen Wert ein eingeben, damit er die Differenz anzeigen kann bzw weiß, ob der neue Wert größer ist oder kleiner. Bei mir kommt es oft vor, dass er durch den Wechsel oft was falsches oder nichts einliest und dann den Wert aktualisiert. Dann erscheint im JSON der Fehler, dass der neue Wert kleiner ist als der Alte..... Könnte man das zb auch per MQTT eintragen und der Zähler holt sich dann den Wert über MQTT? Dann müsste man nicht ständig auf Weboberfläche gehen, da das System eh ständig am "rumrödeln" ist.
> 
Ich habe deine Idee nicht vollständig verstanden. Daher erstmal soviel: aktuell wird MQTT-Kommunikation nur in eine Richtung verwendet (ESP32 --> Server), eine Upload ist nicht implementiert. Technisch möglich, aber aktuell keine eigene Kapa für Aufwand. Ich kann aber gerne eine Erweiterung der Software integrieren.

> Dritter Verbesserungsvorschlag. Ist es irgendwie möglich, das aktuelle Bild von der Cam irgendwie in den IoBroker zu bekommen? Das würde einiges bezüglich handling stark vereinfachen.
> 
Ja, ist möglich. Das aktuell Bild findet sich unter folgendem Link: http://IP-ADRESS/img_tmp/alg_roi.jpg

> Ich hoffe meine Ideen sind nicht zu absurd :)
> 
> VG Steve
