### ISSUE TITLE
Using a single LED flash

### ISSUE THREAD

**Issue by CFenner** [jomjol/AI-on-the-edge-device#859]
I would like to use a simple LED with a resistor to replace the onboard flash as it gives too many reflections. Is there a way I can wire that up to GPIO04 or GPIO12? Readings the docs it's not that obvious to me.

**Comment by jomjol** [comment]
This is currently not possible. You could unsolder the internal LED or switch the internal parallel to GPIO4. 
In order to use PWM on the GPIO12/13 I would need to extend the code. Currently I don't have time to do that.

**Comment by JensHoRi** [comment]
> I would like to use a simple LED with a resistor to replace the onboard flash as it gives too many reflections. Is there a way I can wire that up to GPIO04 or GPIO12? Readings the docs it's not that obvious to me.

Why not using the external led function? Easy to make and explained in wiki. :) 

https://github.com/jomjol/AI-on-the-edge-device/wiki/External-LED

**Comment by CFenner** [comment]
I peeled of the onboard led, but looks like I broke something. 
I now try to use an always on led via 3,3v.

**Comment by dl6dbh** [comment]
What is the best position for an external LED? Where did you mount it?

**Comment by JensHoRi** [comment]
I have two, one left one right at gas and Ferraris, no external at water

**Comment by jomjol** [comment]
There is no "general" perfect position. You really need to test. I have 3 counters and 3 positions :-(
