### ISSUE TITLE
Keine Daten via MQTT zw. 20:30 Uhr und 08:00 Uhr

### ISSUE THREAD

**Issue by tc-maxx** [jomjol/AI-on-the-edge-device#860]
Hallo zus.,

bei mir werden in der Nacht keine Daten gesendet. Jeden Tag 20:30 hört die Übertragung via MQTT auf und fängt erst wieder 8:00 Uhr.
Habe ich vielleicht eine Einstellung übersehen?

Vielen Dank
Max

**Comment by jomjol** [comment]
Hallo Max,
es gibt keine Timereinstellung im Code. Dass muss irgendwo an deinem System liegen.
Gruß,
  jomjol

**Comment by tc-maxx** [comment]
vielen Dank!
