### ISSUE TITLE
Bild bei Recognition nicht wie eingestellt

### ISSUE THREAD

**Issue by 5pl3nd1d** [jomjol/AI-on-the-edge-device#863]
Hallo, ich habe seit kurzem einen digitalen Zähler. Irgendetwas muss beim Umbau auf den neuen Zähler schief gelaufen sein. Ich habe ein neues Referenzbild gemacht und die ROIs neu definiert.
![Ref1](https://user-images.githubusercontent.com/47743834/179371604-0a17d3c3-021c-405e-a6be-76deb03f0d10.jpg)
![ROI1](https://user-images.githubusercontent.com/47743834/179371607-a22a7c2d-1d2e-459b-bc0c-8d880c9b8047.jpg)
Allerdingt schlägt die Erkennung fehl, weil die ROIs nicht mehr dort sind, wo sie sollen. 
![Rec1](https://user-images.githubusercontent.com/47743834/179371674-d450a4c6-24d6-4e95-91f4-741701e96ef6.jpg)

Alles wurde auch gespeichert und auch neugestartet. Ich gehe von einem Layer-8-Fehler aus, aber ich finde ihn nicht.

**Comment by jomjol** [comment]
Ich weiß nicht, was ein Layer-8-Fehler ist!

wenn das Alignment nicht funktioniert, findet er die Referenzmarken nicht. vermutlich zu wenig Kontrast. Ggf. einfach einen hellen Aufkleber mit schwarzem Strich/Punkt draufkleben und verwenden.

**Comment by 5pl3nd1d** [comment]
Sieht gut aus. Ich habe jetzt eine Streuscheibe vor den Blitz geklebt, den Abstand zum Wasserzähler verringert und mit einem dünnen Edding besser lesbare Markierungen gemacht und die Alignments darauf gesetzt. Jetzt scheint es besser zu funktionieren. Du hattest recht, vielen Dank!
![2022-07-17 13_27_55-jomjol - AI on the edge - IoT-watermeter](https://user-images.githubusercontent.com/47743834/179395980-058c70e8-ab55-44e0-aaed-e6be24db532e.png)

Ein Layer-8-Fehler ist die höfliche Bezeichnung dafür, wenn der Fehler vorm Monitor sitzt ;)
