### ISSUE TITLE
Access web-ui via SSH-Tunnel

### ISSUE THREAD

**Issue by meisterlampe** [jomjol/AI-on-the-edge-device#865]
Hi,

I'm accessing port 80 of my ESP32 via a SSH-Tunnel and get some errors, because using e.g. localhost:3123 makes the UI-JavaScript add your Test-Systems-IP to the URLs.
There was already a fix merged in #410 and I guess it was commented out by accident.

**Comment by meisterlampe** [comment]
Just saw that there is the issue #769 that adresses the problem. Sorry, if this is kind of a duplicate.
So checking for port 80 is not sufficient? Are you using a different port for your local debugging?

**Comment by caco3** [comment]
@jomjol can you answer this?

**Comment by jomjol** [comment]
The problem should be solved in the current version, because the port is added.
Should only be a topic, if you use localhost, because that is the trigger for the debugging mode.

**Comment by jomjol** [comment]
Seems to work - no acitivities currently - please reopen in case of further needs.
