### ISSUE TITLE
ESP-32S CAM doesn't work?

### ISSUE THREAD

**Issue by askmurphy** [jomjol/AI-on-the-edge-device#867]
I have followed the instructions, flashed my ESP32S CAM, created a SD-card with the files and changed the WIFI details for our AP.
Also a fixed ip-address, mask and dns..

After restarting: I get no working device and also no 192.168.1.111 available when I do an IP-scan..

I have tested the ESP32CAM device with CameraWebServer (CAMERA_MODEL_AI_THINKER), it worked ;-)

Any ideas?

**Comment by jomjol** [comment]
Well, then you seems to did everything right. For mostly others this is working.

Can you post a little bit more information? E.g. logfile from the sd-card or the serial output.

**Comment by askmurphy** [comment]
First attempt:
Flashed the firmware and created the SD-card with the files and wifi.ini file settings changed (fixed ip)

ssid = "Matrix-WIFI"
password = "secret"
;hostname = "watermeter"
;hostname is optional

;if you want to use a fixed IP you need to specify the following 3 parameters (ip, gateway, netmask) with IP4-Addresses "123.456.789.012"
ip = "192.168.1.111"
gateway = "192.168.1.1"
netmask = "255.255.255.0"

Logfile flasher: [flashlog.txt](https://github.com/jomjol/AI-on-the-edge-device/files/9143675/flashlog.txt)

After rebooting the ESPCAM, the fixed IP not found by the IP-scanner.
Checked the logfiles on the card after some time: all empty?

**Comment by askmurphy** [comment]
serial output (arduino serial monitor):
rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3f400020,len:296188
ets Jun  8 2016 00:22:57

**Comment by askmurphy** [comment]
> something is totally of. 
> 
> If you have done the flashing correctly you will have an extended log file from the arduino serial monitor (several douzend lines). If this is not happening, than something with the flashing or the download is wrong.
> 
> How did you exactly download the firmware?

Downloaded your github archive, extracted it and used the firmware files as described in your wiki..

**Comment by jomjol** [comment]
Then it should work. Either you have a hardware failure, or nor enough PSRAM (would be written in the log (/log/messsage) or in the serial output.

**Comment by askmurphy** [comment]
Tried it today with ESPTOOL, now it works!!!  
Nice software, great job!!!!   Let see it I can read our PRESIKHAAF watermeter ;-)
