### ISSUE TITLE
Negativ Rate - Only for all values

### ISSUE THREAD

**Issue by DerGue69** [jomjol/AI-on-the-edge-device#868]
I have multiple values.
For the 1st one I need NO negative rate.
For the 2nd one I need to allow regative rates.

But I can make the setting only for all values. A classic Bug ;)

**Comment by jomjol** [comment]
This is not a bug. Not all parameters have been transfered to the individual configuration option. I can extend this in a future version.

**Comment by DerGue69** [comment]
Yes please! Thanks.

**Comment by theFeverDog** [comment]
This would be great! That way I could also get the current flow rate (which can decrease back to 0), wihtout allowing negative rates for the actual watermeter.

**Comment by DerGue69** [comment]
I made a workaround. I take only the analog values in a dedicated value. 
Via mqtt I take the RAW value. When going from 9999 to 0000 I have a logic in NodeRed.
And to smooth read errors I take the average of the last 4 values.

This all gives me a precise amount in Liter. And on my dashboard I can do everything I want with that values.

**Comment by jomjol** [comment]
Implemented in current rolling: https://github.com/jomjol/AI-on-the-edge-device/pull/1834
