### ISSUE TITLE
config checkmark <> true/false

### ISSUE THREAD

**Issue by s0170071** [jomjol/AI-on-the-edge-device#869]
The current setting in the config is ambiguous. There is sometimes 

- a checkbox and (!)
- a true/false dropdown menue. 

Why have both ?

![grafik](https://user-images.githubusercontent.com/33855380/179991519-53191f36-654d-4ba7-9e82-6414d49cd090.png)

**Comment by jomjol** [comment]
The checkbox is the option to disable the value (via comment).
Could be ommitted in the next version.
