### ISSUE TITLE
Potential documentation update ?

### ISSUE THREAD

**Issue by nibotg** [jomjol/AI-on-the-edge-device#873]
Firstly thanks for this development!
I'm new to ESP32 and purchased the camera module connected to a ESP32-CAM-MB Micro USB Programmer – CH340G Serial Chip (OV2640 Camera) but struggled to work out how to flash it.
Turns out it's easier than using the USB->UART connector. Simply plug the device in to a PC and press and hold the IO0 button on the MB USB Programmer (which is easily missed) while following the instructions using the flash tool from Espressif.

This may assist others who are new to the board and project.

**Comment by haverland** [comment]
With the programmer and esptool ( https://github.com/jomjol/AI-on-the-edge-device/wiki/Installation ) you don't need to press any button on the programmer. Is the easiest way, but you need python installed.

**Comment by JensHoRi** [comment]
I had some issues flashing too, because the right uart connector was one issue, the second: flash works only with 5V on my esp modules. Seems like depending on hardware. Here my pic how it worked: 
![Uploading 089C0034-DA48-471A-B656-080190E77E58.jpeg…]()

**Comment by JensHoRi** [comment]
![5DFAB648-BB96-4CB8-9544-030543ECA0FF](https://user-images.githubusercontent.com/47488279/181997309-0440e9ad-5b88-402d-ab90-eb96e019090d.jpeg)

**Comment by jomjol** [comment]
ok great, that it worked. I close this issue

**Comment by JensHoRi** [comment]
Did you update the wiki? I tried, but not able to do via GitHub:(

**Comment by jomjol** [comment]
Image has been added
