### ISSUE TITLE
Keine Erkennung des Digital Counters unter 10.5.x

### ISSUE THREAD

**Issue by Sandworm-of-Dune** [jomjol/AI-on-the-edge-device#876]
Hallo,
ich bin wegen Dauerrebootprobleme beim Release 10.6.0 nun wieder zurück auf 10.5.2. (Siehe separt gemeldetes Issue)
Das 10.5.2 hatte ich vorher schon mehrere Monate ohne Probleme im Einsatz.

Nun bekomme ich bei 10.5.2. aber keine Erkennung der Digialwerte.
Daraufhin hab auch den downgrade auf ältere 10er Releases probiert und zuletzt auch das 9.2.0. Nirgend bekomme ich eine Werterkennung. 

Ich bin gerade etwas ratlos, wo der Fehler zu suchen ist.
Irgendeine Empfehlung? 
welche Datei auf der SD Karte ist für diesen Programmteil zuständig. Dann kann ich ggf. diese Daei nochmal ersetzen.
Meine INI Datei ganz unten

![grafik](https://user-images.githubusercontent.com/91150538/180640222-942f088c-cf3b-41e2-ae17-92947215c340.png)

![grafik](https://user-images.githubusercontent.com/91150538/180640227-0f1be731-66d5-4609-a3b9-9079813f0b67.png)

> INI:
[MakeImage]
;LogImageLocation = /log/source
WaitBeforeTakingPicture = 5
;LogfileRetentionInDays = 15
Brightness = -2
Contrast = 0
Saturation = -2
LEDIntensity = 30
ImageQuality = 6    <<- hier habe ich auch schon den Wert 12 probiert
ImageSize = VGA
FixedExposure = false

>[Alignment]
InitialRotate = -92
InitialMirror = true
SearchFieldX = 20
SearchFieldY = 20
AlignmentAlgo = default
FlipImageSize = false
/config/ref0.jpg 121 262
/config/ref1.jpg 413 270

>[Digits]
Model = /config/dig1400s2q.tflite  <<- hier habe ich auch schon ältere tflite probiert
;LogImageLocation = /log/digit
;LogfileRetentionInDays = 2
;ModelInputSize =  
default.ROI1 177 289 40 61
default.ROI2 228 289 40 61
default.ROI3 279 289 40 61
default.ROI4 328 289 40 61
default.ROI5 377 289 40 61
default.ROI6 432 285 35 65

>;[Analog]
Model = /config/ana-s2-q-20220213.tflite
;LogImageLocation = /log/analog
;LogfileRetentionInDays = 3
;ModelInputSize =  
default.analog1 444 225 91 91

>[PostProcessing]
default.DecimalShift = -1
PreValueUse = true
PreValueAgeStartup = 720
AllowNegativeRates = true
default.MaxRateValue = 1
default.MaxRateType = AbsoluteChange
default.ExtendedResolution = false
default.IgnoreLeadingNaN = true
ErrorMessage = true
CheckDigitIncreaseConsistency = false

>[MQTT]
Uri = mqtt://192.168.0.50:1883
MainTopic = stromzaehler
ClientID = strom
user = user
password = password

>[GPIO]
;IO0 = input disabled 10 false false 
;IO1 = input disabled 10 false false 
;IO3 = input disabled 10 false false 
;IO4 = built-in-led disabled 10 false false 
IO12 = external-flash-ws281x disabled 10 false false GPIO12
;IO13 = input-pullup disabled 10 false false 
LEDType = WS2812B
LEDNumbers = 1
LEDColor = 250 250 250

>[AutoTimer]
AutoStart = true
Intervall = 4.85

>[Debug]
Logfile = true
LogfileRetentionInDays = 3

>[System]
TimeZone = CET-1CEST,M3.5.0,M10.5.0/3
TimeServer = 192.168.0.1
;AutoAdjustSummertime = 
;Hostname = mqtt-powermeter
;SetupMode = false

**Comment by jomjol** [comment]
Sind deine ROIs wie vorher (gleiche Größe, gleiche Position)?
Wenn ja, kann es nur an einer andere tflite-Version liegen. Hast du die alte noch? 
Falls nein, einfach mal ein paar aus den alten Releases probieren.

**Comment by Sandworm-of-Dune** [comment]
Ja, ich habe schon mehrere ältere probiert.
Ich probiere jetzt nochmal jedes einzlne tflite und gebe Bescheid.
Lg Tobias

**Comment by Sandworm-of-Dune** [comment]
Hallo @jomjol 

Ich habe nun diverse Digital-tflites probiert (jeweils dannach einen Reboot durchgeführt)
Auch habe ich erneut das Refernzbild und die Referenzpunkte gesetzt.

dig1200s1q.tflite - >keine Erkennung
dig1210s2q.tflite - >keine Erkennung
dig1300s1q.tflite - >keine Erkennung
dig1310s3q.tflite - >keine Erkennung
dig1330s1q.tflite - >keine Erkennung
dig1400s2q.tflite - >keine Erkennung

Er erkennt einfach keine Zahlen mehr.
Mich wundert auch, dass auf der Seite "Recognition" keine Miniaturbilder angezeigt werden.
![grafik](https://user-images.githubusercontent.com/91150538/180642706-97734c1d-45cb-4722-bf43-82a73e7e2a08.png)

Hier vom Gaszähler mit der gleichen Version & wo die Erkennung funktioniert:
![grafik](https://user-images.githubusercontent.com/91150538/180642732-d18f6d71-678c-42e6-89fe-0749e6638281.png)

**Comment by jomjol** [comment]
Das mit den fehlenden Bildern ist in der Tat mehr als merkwürdig. Hast du die SD-Karte mal platt gemacht (vorher natürlich die Dateien sichern)?

**Comment by Sandworm-of-Dune** [comment]
gestern, hab ich die SD Karten schon mal formatiert.
Ich werd gleich nochmal alles zerlegen und nochmal machen.
was ich gerade gesehen habe ist, dass die ROI.bmp  (Referenzbilder) unter \img_tmp\ nur leere schware Bilder sind. (jeweils 58 Byte)
auf dem Gaszähler sind diese 1974 Bytes

![grafik](https://user-images.githubusercontent.com/91150538/180643166-1b20a347-a3eb-4b95-a647-c01b65a71681.png)

Gaszähler: 
![grafik](https://user-images.githubusercontent.com/91150538/180643192-dd11a58f-5d14-4e97-9409-d33edf41d5f5.png)

**Comment by Sandworm-of-Dune** [comment]
also die Aufnahmen (Quelle) scheinen noch richtig zu sein.
Sprich unter /fileserver/log/digit/20220724/12/10_ROI1_20220724-123740.jpg habe ich Bilder mit den richtigen Werten
![grafik](https://user-images.githubusercontent.com/91150538/180643706-c2992535-64fc-4af8-baf5-9922086b0a82.png)

Die nachträge Verarbeitung scheint nicht mehr zu funktionieren.

**Comment by Sandworm-of-Dune** [comment]
@jomjol 
also SD Karte kann ich ausschließen -> formatiert und auch ein weiteres Mal mit einer anderen probiert -> keine Besserung.
Jetzt kommts aber -> erneutes Update auf Release 10.6.0
Jetzt hab ich zwar auch wieder das permanente Rebootproblem (siehe separt gemeldetes Issue), aber die paar wenige Male, wo ich Zugriff aufs System habe, funktioniert auch wieder die Erkennung. (Siehe Screenshot unten)

Jetzt meine Frage: kann es sein, dass Release 10.6.0 einen Bereich /Datei aktualisiert, der beim Rückflashen auf ältere Version dann nicht zurückgesetzt /überschrieben wird und somit dann in einer alten Version diese Probleme macht?

@all: hat vielleicht jemand noch ein Gerät übrig, um das mal gegenzutesten -> Flash auf 10.6.0 -> Downgrade auf 10.5.x -> überprüfen, ob Erkennung noch funktioniert


![grafik](https://user-images.githubusercontent.com/91150538/180644205-296ec186-ef27-4fdb-9785-1f4622b52be7.png)

**Comment by jomjol** [comment]
Ich könnte mal auf Verdacht den Kameratreiber auf die alte Version zurücksetzen. Dauert ein bisschen, scheint sich aber zu lohnen - zumal ich nicht wirklich neue Features benötige.

**Comment by jomjol** [comment]
Es scheint eine Kombination von esp32 Treiber und tflite-Update zu sein. Da ich die Funktionalität in der Version nicht benötige, habe ich gerade eine v.10.6.1, in der diese wieder auf die alten Versionen zurückgestellt wurde.

**Comment by Sandworm-of-Dune** [comment]
Danke. mit der aktuellen Release 10.6.1 gehts, somit brauche ich einen Downgrade nicht mehr.

Nur Interessenshalber: kann es sein, dass Release 10.6.0 einen Bereich /Datei aktualisiert, der beim Rückflashen auf ältere Version dann nicht zurückgesetzt /überschrieben wird und somit dann in einer alten Version diese Probleme macht?

Lg

**Comment by jomjol** [comment]
Nein - lag vermutlich an einem Upgrade der Bibliotheken für das neuronale Netz, welches mit den "alten" tflite-Dateien nicht zurecht kommt.
