### ISSUE TITLE
Einbinden von hochgeladenen tflite über das GUI nicht möglich

### ISSUE THREAD

**Issue by Matzebhv** [jomjol/AI-on-the-edge-device#879]
Moin,

beschäftige mich jetzt seit ein paar Tagen mit diesem klasse Projekt. Ich habe einen Zähler von Zensus mit einem echt windschiefen Zählwerk, meine Erkennungsrate war vermutlich daher eher nicht so vorhanden. Beim testen mit verschiedenen tflite bin ich im Roling-Repo über die Dateien ana_i32s100dr-v1.0-q.tflite und dig-s1d-md-v1.0-q.tflite gestolpert. Was soll ich sagen.

![wasseruhr](https://user-images.githubusercontent.com/20025244/180738522-2cdea4f9-6dba-4a20-adf9-36b568a697cd.png)

Diese Dateien lassen sich nach dem hochladen allerdings nicht über das GUI einbinden. Auch wirft mir das GUI jetzt einen Fehler wenn ich auf die Konfiguration gehe. Und rein aus Interesse, was macht diese Dateien in meinem Fall so viel besser? Anscheinend werden halb eingedrehte Zahlen mit einem Kommawert erkannt.

Gruß
Matze

**Comment by haverland** [comment]
Dass du sie nicht einbinden konntest, liegt an einem Fehler, der erst vor einigen Tagen gefixed wurde. Die aktuelle Rolling und die 10.6.1 müssten sie anzeigen. Alternativ kann man den "." in der Version durch etwas anderes ersetzen.

Was machen die beiden? Das ana_i32s100dr-v1.0-q.tflite ist intern etwas anders aufgebaut und klassifiziert die Zeigerpositionen, während die bisherigen Ana* Netzwerke eine Regression verwenden. Dein Zeiger sieht wirklich etwas anders aus und es könnte zu Ungenauigkeiten führen, da ich keine Bilder kenne, die so aussehen.
Du könntest aber davon Bilder zur Verfügung stellen ( https://github.com/haverland/collectmeteranalog ), um bessere Ergebnisse zu bekommen.

Das dig-s1d-md-v1.0-q.tflite ist eine neue Art von Netzwerk, dass bei der die bisherige NaN entfällt und hoffentlich viel genauer ist, als bisherige Modelle. Ansonsten hast du das schon richtig erkannt, was passiert. 

Aber ich werde aber jetzt Josef nicht vorgreifen. Ein bisschen Geduld noch ;-)

Der Fehler in der Konfiguration könnte kommen, wenn du das html.zip nicht auch aktualisiert hast. Ist aber nur eine Vermutung.

**Comment by Matzebhv** [comment]
->Das dig-s1d-md-v1.0-q.tflite ist eine neue Art von Netzwerk, dass bei der die bisherige NaN entfällt und hoffentlich viel genauer ist, als bisherige Modelle. 

Hoffentlich viel genauer ist eine krasse Untertreibung. Bei meinem Zähler hat es die Erkennungsrate von fast nix auf 99% angehoben. Damit werden komplett verschobene Zahlen einwandfrei erkannt. 
Kann ich das html.zip aus der rolling auf einer Firmware aus dem Master ( master - v10.6.0 - 2022-07-17 ) aufbringen? Wenn nein behelfe ich mir erst einmal mit dem umbenennen der Dateien. Und das Logging des analogen Zeigers läuft auch schon.

Gruß
Matze

**Comment by haverland** [comment]
Freut mich zu hören.

Die beiden html.zips aus rolling und 10.6./10.6.1 dürften identisch sein. Kannst also eine davon nehmen.

**Comment by Matzebhv** [comment]
> Freut mich zu hören.
> 
> Die beiden html.zips aus rolling und 10.6./10.6.1 dürften identisch sein. Kannst also eine davon nehmen.

Ich habe die html 10.6.1 eingespielt, das hat das Problem nicht gelöst. Habe den .  im Namen jetzt erst einmal durch _ ersetzt.

**Comment by haverland** [comment]
Dann hast du vermutlich noch eine "ältere" Rolling eingespielt. Aber danke für den Hinweis, mir ist noch ein kleiner Fehler aufgefallen, wo aber zu viel statt zu wenig angezeigt wird.

**Comment by Matzebhv** [comment]
Ich muss hier noch einmal eine Frage zur dig-s1d-md-v1.0-q.tflite loswerden. Nachdem die Erkennung gestern fast zu 100% erfolgreich war verbeißt sich das System seit heute am 5. Digit und macht gnadenlos aus der 7 eine 6. Erkannt wird das Digit als 6.7, was so ja auch vermutlich sinn macht. Sollte die Stelle dann nicht aufgerundet werden?

Gruß
Matze

![wasseruhr](https://user-images.githubusercontent.com/20025244/181031099-dc02eee1-5457-4357-9282-a6af925527d1.png)

**Comment by haverland** [comment]
Das kommt von der -1.0 (die es so eigentlich nicht geben dürfte) in digit6 und dem post-process, der die Zahl zusammenstellt.
Die ROIs müssen etwas anders ausgerichtet werden. Horizontal wie bisher im inneren Rechteck. Oben/Unten sollte der Rand des Zifferfensters sein (Lock Aspect Ratio ausschalten)
Die -1 ist aber wirklich nicht richtig. Ich habe gerade keine Idee wie das passieren kann.

**Comment by haverland** [comment]
Wie groß ist das ROI bei der 4 (digit6)?

**Comment by jomjol** [comment]
Die -1 kommt vermutlich vom implizit eingestellten Reject Limit, falls dieser Parameter in der 'config.ini' nicht definiert ist.
Das Feature von Nachkommastellen auch bei digitalen Ziffern ist gerade in Entwicklung. Es wird mit der nächsten Hauptversion (11.x) eingeführt und aktuell im Hintergrund implementiert.

Daher macht es auch aktuell auch noch keinen Sinn Fehler oder Auffälligkeiten dazu hier zu diskutieren. Daher würde ich empfehlen, momentan auf ein älteres tflite zu gehen.

**Comment by haverland** [comment]
Ich glaube es liegt am CNNGoodThreshold (Configuration-> CNNGoodThreshold). Das auf 0 setzen. Leider prüft die innere Logik nicht, ob diese Konfiguration überhaupt gesetzt ist. Das macht bei Digital100/Analog100 auch eigentlich keinen Sinn. Da baue ich es mal aus.

**Comment by Matzebhv** [comment]
Moin ihr beiden. Ich habe die ROIS jetzt mal in der Höhe verkleinert, die blaue Umrandung des Sichtfensters ist jetzt nicht mehr mit drin. Vorher war die Größe des Digit4 21x / 40y. CNNGoodThreshold habe ich auf 0 gesetzt. Ein älteres tflite macht für mich keinen Sinn, da war die Erkennungsrate echt übel. So funktioniert das schon echt super und ich bin gespannt auf die neue Version.

![wasser1](https://user-images.githubusercontent.com/20025244/181089466-2e40802f-6ffe-45f2-8585-cc8b8aac8580.png)

![wasser2](https://user-images.githubusercontent.com/20025244/181089488-17690e7c-f1f8-4e96-b35c-aa71e15d3953.png)

Gruß
Matze
