### ISSUE TITLE
Release v10.6.1 - OTA Update - Server closed the connection abruptly!

### ISSUE THREAD

**Issue by ckoeber83** [jomjol/AI-on-the-edge-device#880]
Hi,

When trying to install the new firmware v10.6.1 via OTA update, the browser always displays "_Server closed the connection abruptly!_" after a period of time.

![image](https://user-images.githubusercontent.com/52466072/180748403-a74d521f-f394-4001-ba65-470a1a2e1cb5.png)

Upload of html content and tfl/tflite file is still working.
Coming from v10.5.2.

Can someone help pls.

**Comment by haverland** [comment]
I have the same issue on 2 devices with rolling and 10.6.0. Serial log ends in open firmware (rb).
But 2 other devices working fine.

**Comment by ckoeber83** [comment]
It looks like my space on SD card is full.
I deleted some raw picture files via File Server web gui in path `http://watermeter/fileserver/log/source/` and now i was able to install the firmware via OTA update.

Is there any way to delete all fileserver/log/source/ subdirectory's at one instead of must first delete the raw files to have an empty folder to be able to delete the folder. I have here raw picture files since January :-)

**Comment by haverland** [comment]
Easiest way would be to delete it on PC.

**Comment by jomjol** [comment]
Yes, there is nothing like a "delete all"
