### ISSUE TITLE
additional digital training data

### ISSUE THREAD

**Issue by liflitz** [jomjol/AI-on-the-edge-device#882]
Hi jomjol,

Your training of my digits from issue 844 worked perfectly well. However, now the lighting is slightly off creating some extra effect in the middle of dig1 making these readings close to random. Could you please add these dig1 pictures for another round of training?

[digits_2.zip](https://github.com/jomjol/AI-on-the-edge-device/files/9184756/digits_2.zip)

Thanks a lot and best wishes,

liflitz

**Comment by jomjol** [comment]
Incorporated in newest training data: https://github.com/jomjol/neural-network-digital-counter-readout/raw/master/dig-class11_1411_s2_q.tflite
