### ISSUE TITLE
Training data

### ISSUE THREAD

**Issue by kichkasch** [jomjol/AI-on-the-edge-device#883]
Hi folks,

here is some training data for digital values:
[trainingdata.zip](https://github.com/jomjol/AI-on-the-edge-device/files/9188507/trainingdata.zip)

Thanks very much in advance; best regards
kichkasch

**Comment by jomjol** [comment]
Incorporated in newest model: https://github.com/jomjol/neural-network-digital-counter-readout/raw/master/dig-class11_1411_s2_q.tflite
