### ISSUE TITLE
Keine Erkennung

### ISSUE THREAD

**Issue by gomble** [jomjol/AI-on-the-edge-device#884]
Hallo,

wieso erkennt er die Zahl nicht ? Scharf und deutlich ist das Bild.
![image](https://user-images.githubusercontent.com/6769445/181602449-43a159b2-a7bf-43f1-8186-ce59793c3a60.png)

**Comment by haverland** [comment]
Das letzte Digit ist sehr dunkel. Das könnte ein Grund sein, warum hier falsch erkannt wurde.

Die 7 ist noch in einem Zwischenstatus. Dafür gibt es eine eigene Kategorie. Wenn die 7 voll erscheint, sollte das dann auch erkannt werden. Die Zahl wird dann im post-process vom letzten lesbaren Stand verwendet.

**Comment by gomble** [comment]
Ich hab jede Position vom extern verbundenem LED ausprobiert. Könnt ihr mir Tipps geben wo man die genau am besten positioniert damit es nicht blendet und alle Ziffern erkannt werden ?

**Comment by JensHoRi** [comment]
Bei mir war eine links und eine rechts am besten, also 2 LEDs

**Comment by pos-ei-don** [comment]
Bei mir ging die original  am besten, mit einem Diffusor vom photo Apparat. Dann noch leicht gedreht, dass der hellste Fleck an einer Stelle war wo nichts gelesen werden musste.

**Comment by JensHoRi** [comment]
> Ich hab jede Position vom extern verbundenem LED ausprobiert. Könnt ihr mir Tipps geben wo man die genau am besten positioniert damit es nicht blendet und alle Ziffern erkannt werden ?

Da es kein issue der software ist: magst du den issue schließen?

**Comment by gomble** [comment]
> Bei mir ging die original am besten, mit einem Diffusor vom photo Apparat. Dann noch leicht gedreht, dass der hellste Fleck an einer Stelle war wo nichts gelesen werden musste.

Kannst du ein Bild schicken von deinem ?

**Comment by JensHoRi** [comment]
Zeig doch mal ein Bild von deiner ROI Einstellung der letzten Ziffer. Zieht auch aus als wäre das zu groß eingestellt

**Comment by gomble** [comment]
> Zeig doch mal ein Bild von deiner ROI Einstellung der letzten Ziffer. Zieht auch aus als wäre das zu groß eingestellt

![image](https://user-images.githubusercontent.com/6769445/182048819-c05d7d97-e5a5-4512-beab-d9864687cbea.png)

**Comment by JensHoRi** [comment]
Ist definitiv zu groß. Siehe Wiki: https://github.com/jomjol/AI-on-the-edge-device/wiki/ROI-Configuration

**Comment by gomble** [comment]
![image](https://user-images.githubusercontent.com/6769445/182049610-fe5d1a32-8d69-4fee-9791-264d1102904c.png)
ich habs mal angepasst und schaue jetzt noch einmal

**Comment by JensHoRi** [comment]
Meine Schätzung ist immer noch zwei Pixel zu breit und 4-6 zu hoch. Aber schaue mal.

hier mal zum Vergleich eine Ziffer von mir: 
![20382BAF-6F37-4968-BD38-B07C7D9E5178](https://user-images.githubusercontent.com/47488279/182050212-b036a6d8-7514-47ea-83f0-d2444a4da54a.jpeg)

**Comment by gomble** [comment]
Okay danke ich spiel damit mal ein wenig.
Ich schließe den Fall.
Danke !
