### ISSUE TITLE
Analog digit with mirror not recognized

### ISSUE THREAD

**Issue by georg138** [jomjol/AI-on-the-edge-device#889]
Hi,
I have a water meter where one analog digit has a mirror on it to be used with an optical sensor for flow metering. However, this is not correctly recognised. Is this kind of digit missing or is it some kind of misalignment in my setup?
![image](https://user-images.githubusercontent.com/53263304/181996278-a7d72551-fe71-49eb-be48-528bbebb14b4.png)
![image](https://user-images.githubusercontent.com/53263304/181996356-80ff5ba2-75ad-44e5-ae34-918e5a2ea0e8.png)
Thanks for your help!

**Comment by JensHoRi** [comment]
I believe training data for this one is missing. 

There is an explanation in wiki what’s needed in a zip file for full training data set. Maybe you can save a few hundred pics and rename for training your special counter. Until that my personal proposal would be 
A) to life with it for the meantime or
B) reduce analog counters to two, so it’s less exact (only on 0.01 m3 = 10 liters) meanwhile

**Comment by georg138** [comment]
Thanks for the advice. I tried C) but this didn't help. So now I'm gathering images and will send them in.

**Comment by JensHoRi** [comment]
For the meanwhile I would propose reduce to 2 after , digits. :) for most things usage of 10 l is exact enough

**Comment by jomjol** [comment]
This will not work as this kind of pointer (or a similar one) is not part of the training data. To get this in I need 1-2 images each from the reading (0.1, 0.2, 0.3, ... 9.7, 9.8, 9.9), which means ~200 images with the correct reading value at the beginning of the filename (0.1_xxx.jpg).

**Comment by georg138** [comment]
I'm already collecting images. As soon as I get some free time, I will put together the images as requested. Until then, 10 l resolution will suffice.

**Comment by jomjol** [comment]
Please reopen new issue, when you have your images
