### ISSUE TITLE
Feature Request: Nochmaliger WLAN-Verbindungsversuch bei Nichtverfügbarkeit des WLAN

### ISSUE THREAD

**Issue by friedpa** [jomjol/AI-on-the-edge-device#89]
Ich hätte hier eine Anregung für ein Feature Request.
Vorgeschichte: ich hatte einen Stromausfall und bei Stromaufschaltung haben sich sicher auch meine zwei ESPs versucht sich in das WLAN einzuklinken. Da aber mein Router und die Repeater mindestens zwei Minuten brauchen um hochzufahren, waren die zwei ESPs schon längst im AP Modus (nehme ich an), oder haben aufgegeben sich mit dem WLAN verbinden zu wollen.
Lösungvorschläge: 
- Kann man nun in die SW implementieren, dass im AP Modus alle 30(?) Minuten ein Reset durchgeführt wird? Sollte das WLAN nämlich dann schon wieder da sein, kommt es zum re-connect
- Oder, falls es keinen AP Modus gibt, kann man den ESP es länger versuchen lassen (endlos?) das WLAN zu erreichen

**Comment by jomjol** [comment]
Hallo Paul,

ist eigentlich so implementiert:
```
    case SYSTEM_EVENT_STA_DISCONNECTED:
        blinkstatus(200, 5);
        esp_wifi_connect();
        xEventGroupClearBits(wifi_event_group, CONNECTED_BIT);
```

Verwendest du eine fixe IP oder eine dynamische? In der fixed IP Situation gibt es noch einen kleinen Fehler, so dass er sich vielleicht bei einem Disconnect aufhängt. Korrigiere ich in der nächsten Rolling. Falls du nicht keine fixed IP verwendest, sollte das eigentlich funktionieren.

**Comment by friedpa** [comment]
Ich verwende eine fixe IP Adresse, die ich am FritzBox Router eingestellt habe.
Liebe Grüße
Paul

**Comment by jomjol** [comment]
Und in der wlan.ini eine fixe IP oder dort "variabel"?

**Comment by friedpa** [comment]
Dort keine fixe IP
Liebe Grüße
Paul

**Comment by jomjol** [comment]
Hi Paul,
  
  habe das Thema nicht weiter verfolgt. Bei mir funktioniert eine automatische Verbindung - hatte gerade gestern einen Ausfall der WLan-Verbindung. Ist das nochein Thema oder kann ich den Issue schließen?
  
  Gruß,
    jomjol

**Comment by friedpa** [comment]
Ist nicht mehr weiter bei mir aufgetreten. Issue Closed.
