### ISSUE TITLE
OTA 10.5.2 to 10.6.1 not working

### ISSUE THREAD

**Issue by JensHoRi** [jomjol/AI-on-the-edge-device#892]
I tried OTA Update like explained in the wiki.

with Firefox: after about 60 seconds got message server closed unexpected after click on flash firmware. Device doesn’t came up again, physical reboot (cut energy) started device again, still showing old version

with mobile (safari) about 7s after click on flash firmware a success message. So uploaded and updated html.zip, about 2s later success message. Rebooted with click under OTA Update:

device rebooted, but still shows 10.5.2 build. 

Any idea how to solve? My mistake? Or error in behavior?

**Comment by Caddy-SRX** [comment]
I had the same issue, what I have done:
Go into the fileserver folder "firmware" and delete the firmware.bin
Than upload the new firmware and flash this version

Mine is now on the latest version.

Have fun

**Comment by pos-ei-don** [comment]
There should not be an firmware.bin in the Firmware Folder of the SD-Card?!??
It's not in the ZIP.

**Comment by JensHoRi** [comment]
> 

Tried like you did. Without success. :( which browser did you used?

**Comment by JensHoRi** [comment]
Got it. During download my firmware.bin and html.zip were broken. Downloaded again, now it worked like expected
