### ISSUE TITLE
N nicht per mqtt übertragen

### ISSUE THREAD

**Issue by ritseb1984** [jomjol/AI-on-the-edge-device#895]
Hallo,

wie kann verhindert werden das ein „N“ über mqtt versendet wird.
Ich habe in der config beim Punkt IgnoreLeadingNaN true eingetragen.

![grafik](https://user-images.githubusercontent.com/110028303/182581107-a888050d-b83f-4df4-b294-6b3b99c5b036.png)

Auch wird ab und zu eine 3 mit einer 8 verwechselt. Mein aktueller Zählerstand lautet 392,200m³.
Manchmal wird 892,146m³ erkannt und übertragen.
In der config habe ich bei dem Punkt MaxRateValue 0,05 eingestellt. Sollte diese Einstellung nicht verhindern das ein zu großer „Sprung“ gemacht wird?

Vielen Dank an alle die helfen können

Gruß
Sebastian

**Comment by JensHoRi** [comment]
Da der preValue deaktiviert ist, kann er die Rate auch nicht gegen den prevalue abgleichen. 

Wenn der prevalue aktiv ist, nimmt er im Falle von N den letzten korrekt gelesenen und du bekommst keine N mehr im value. 

Ergo: prevalue aktivieren

**Comment by JensHoRi** [comment]
Bitte danach auch den issue schließen, denn es ist kein Software Problem

**Comment by JanHBade** [comment]
Das Problem ist bei dem N das damit das komplette JSON "kaputt" ist bzw. nicht parsbar ist, das ist halt echt doof...

Ein Prüfung ob man das was man da in die JSON packt eine Nummer ist wäre da super

Bei mir liegt der "Reader" zuz Zeit neben der Wasseruhr (hab einen neuen bekommen) und dann kommt sowas bei raus:

![Screenshot 2022-08-04 215732](https://user-images.githubusercontent.com/3524802/182941414-b0552343-e7a1-467d-9661-fa4ec13f8fe0.png)
![Screenshot 2022-08-04 215704](https://user-images.githubusercontent.com/3524802/182941416-2d62c86a-b8e6-4aa7-ba3e-975349d1d6d7.png)
.

**Comment by JensHoRi** [comment]
Aber nur, weil der prevalue zu alt ist.

**Comment by jomjol** [comment]
bei NNNN geht irgendwas anderes falsch, denn er erkennt nicht eine einzige Zahl.
Vermutlich funktioniert dein Alignment nicht, da der Kontrast echt schwach ist. Dass müsstest du etwas verbessern, z.B: durch eine schware, statt einer weissen Röhre.

**Comment by JensHoRi** [comment]
> bei NNNN geht irgendwas anderes falsch, denn er erkennt nicht eine einzige Zahl.
> Vermutlich funktioniert dein Alignment nicht, da der Kontrast echt schwach ist. Dass müsstest du etwas verbessern, z.B: durch eine schware, statt einer weissen Röhre.

Er hat den esp zur Zeit neben nem Zähler liegen. Ohne Bild kein reading

**Comment by ritseb1984** [comment]
Hallo,

Danke an alle die mir versuchen zu helfen.

ich habe wie vorgeschlagen versucht den Trichter von Innen mit einer schwarzen Gummimatte zu verdunkeln. Das hat leider nichts gebracht, da die Reflexion von der ESP LED kommt.
Ich hab etwas mit der Helligkeit der LED gespielt und zusätzlich habe ich ein Stück Malerkrepp drüber geklebt. Das ist jetzt das Beste Ergebnis was ist hin bekommen habe. 

![grafik](https://user-images.githubusercontent.com/110028303/183086483-5a9e7f7e-522c-4d49-907b-3eecbc288a89.png)


Gibt es etwas, was ich auf den Zähler kleben kann das nicht reflektiert und dennoch durchsichtig ist? Ich habe es mit einem pol Filter von meiner Digicam versucht. Leider verdunkelt der zu sehr und man sieht nichts mehr.

Gruß
Sebastian

**Comment by JensHoRi** [comment]
Wie sind denn deine Einstellungen fürs Image? 

Empfehle: Helligkeit -2
Contrast Ggfs +1 oder +2
Helligkeit der led auf 6-10
Saturation on max. 

Die reflection außerhalb der Zahlen ist unproblematisch. Schwarzes Gehäuse hilft extrem

**Comment by JensHoRi** [comment]
By the way: die Erkennung sieht gut aus. Ich frage mich nur warum du zwei Zähler konfiguriert hast?? 

Einer mit 6 digits und Komma drei nach links wäre sinnvoller. Dann kannst du auch die zählerkorrektur besser nutzen

**Comment by JanHBade** [comment]
Grundsätzlich würde ich aber sagen das die erzeugte JSON immer konform sein muss, worauf soll ich mich sonst verlassen können?

**Comment by jomjol** [comment]
Im Prinzip schon, aber Value ist eigentlich ein String (der kann N enthalten).
Im Ziel sollen diese natürlich alle als Zahlen dargstellt werden, ist aber nicht bei allen Zählern immer möglich (erst in der nächsten Version)

**Comment by ritseb1984** [comment]
Das verschieben vom Komma hat nicht funktioniert. Als dezimal wurden nur 000 angezeigt.

**Comment by JensHoRi** [comment]
Dezimal brauchst du dann ja auch nicht mehr. Nur Main ;)

**Comment by MMeinhardt1** [comment]
Du könntest auch versuchen näher ran zu kommen, dein Bild des Zählers ist ja schon recht klein (weit weg). Und etwas mit dem Fukusring "spielen".

**Comment by jomjol** [comment]
Seit 7 Tagen keine Aktivitäten - bitte neuen Issue im Bedarfsfall öffnen
