### ISSUE TITLE
The captured image rotates. 

### ISSUE THREAD

**Issue by PeterLustig33** [jomjol/AI-on-the-edge-device#896]
I have set the system correctly. All measuring points are configured cleanly. (Picture1) The acquisition works perfectly. After some time, the Esfassung no longer works. If I then look on the Main Page the picture is rotated. (Picture2). Sometimes only a few degrees, sometimes 180 degrees (Image3) I can reproduce the same after each restart. 
The reference image is always correct.

Bild1
![2022-08-03 11_48_34-jomjol - AI on the edge - Zaehlerleser](https://user-images.githubusercontent.com/48348196/182587891-07b660fb-fb40-4b03-a95d-35008f19dee4.png)

Bild2
![2022-08-03 11_59_09-jomjol - AI on the edge - Zaehlerleser](https://user-images.githubusercontent.com/48348196/182588108-8316c2a8-064a-4b77-baf5-a50b9e83f0bf.png)

Bild3
![2022-08-03 12_01_23-jomjol - AI on the edge - 0 HTTP_1 1 200 OK Content-Type_ text_html Transfer-Enc](https://user-images.githubusercontent.com/48348196/182588155-d45c387d-3095-444a-a093-7ba346a7d04b.png)

**Comment by haverland** [comment]
Looks like you use analog ROI on digits? Bild1

sometines it is not Easy to setup alignement. Try other alignement points

**Comment by PeterLustig33** [comment]
Ich habe alle ROI Versionen versucht. Wenn das Bild gerade abgebildet wird werden die Ziffern auch gut erkannt. Das Problem ist, oft dreht sich das neu erfasste Bild. (Bild2 /3) Dann wird auch nichts mehr richtig erfasst.

**Comment by haverland** [comment]
Your alignement is on a digit. Use for alignement something that Not changing and have a good contrast

**Comment by JensHoRi** [comment]
Would assist that. Because my counter also has less marking points, I made good experience with the , between black and red area
![E356AE37-0140-4D51-B707-598F0FB4E0FF](https://user-images.githubusercontent.com/47488279/182670922-61243228-c24f-4bd9-9207-29f6451fdafa.jpeg)

**Comment by pos-ei-don** [comment]
Why not simply Stick something with good contrast somewhere onthe glass?

**Comment by JensHoRi** [comment]
It’s a solution too. In my case (while using mirror case) the area is really small and it just worked with those areas too :) 

but please close issue, because it’s a configuration failure (should discussed in Q&A) and not a software issue

**Comment by PeterLustig33** [comment]
Thank you for the tips. 
Yes it was a configuration error
