### ISSUE TITLE
Einerstelle (10^0) springt nicht von Bsp. "2" auf "3" sondern dreht analog

### ISSUE THREAD

**Issue by ManfMert** [jomjol/AI-on-the-edge-device#897]
Hallo Zusammen,

zunächst vielen Dank an jomol für dieses geniale Projekt!

Leider funktioniert bei mir die Erkennung der rechten Ziffer (10^0) noch nicht richtig. Ursache: bei meiner Wasseruhr der Marke Heitland springt die Einerstelle nicht von Bsp. "2" auf "3" sondern dreht sich während dem Verbrauch von einem Kubikmeter langsam zur nächsten Ziffer.

![grafik](https://user-images.githubusercontent.com/24528404/182837213-3848ae67-a969-4633-a49e-51318553afff.png)

Hat sich das Problem nach dem Erreichen der "3" erledigt und es wird dann immer die letzte erkannte Ziffer angezeigt? Kann/muss hier noch etwas eingestellt werden oder muss ich damit leben?

![grafik](https://user-images.githubusercontent.com/24528404/182838934-18aa4205-9998-4e20-8441-19aa3debf069.png)

Danke und Gruß
Manfred

**Comment by ManfMert** [comment]
Das Zählwerk der Wasseruhr von Heitland scheint von bescheidener Qualität zu sein, weil die Ziffern fast alle auf einer anderen Höhe stehen. Weil die neue Ziffer auf der Einerstelle von unten reindreht, habe ich den Rahmen von dig5 etwas nach unten gesetzt, damit die neue Ziffer möglichst früh erkannt werden kann.

![dig5](https://user-images.githubusercontent.com/24528404/182845830-bfab43aa-06a1-4412-b28e-02558a2be0fb.jpg)

In Verbindung mit "PreValueUse" könnte das die Situation verbessern. "PreValueAgeStartup" steht auf "1 Woche".

![prevalue](https://user-images.githubusercontent.com/24528404/182846043-6026c27e-716f-4716-82c6-07db6e87e583.jpg)

Mal ein paar Tage beobachten ...

**Comment by Nobbynews** [comment]
Ich habe den selben Zähler bei mir verbaut und mit dem Wechsel der einzelnen Stellen keine Probleme. Den Rahmen von dig5 würde ich wieder nach oben schieben. Eigentlich sollen in der config alle digits auf einer Höhe sein.
Ist in der config die Option "CheckDigitIncreaseConsistency" aktiviert?
Zusätzlich habe ich bei mir auch die Option "AllowNegativesRates" aktiviert um ggf. fehlerhafte Werte wieder automatisch zu korrigieren

**Comment by jomjol** [comment]
Nein, dass langsame Zählen ist nicht überall vorhanden. Bei mir dreht er die Ziffer von ca. x.8 bis (x+1).2
Das langsame Drehen bringt die Logik durcheinander, da sie auf das andere Verhalten eingestellt ist. 
Aktuell fällt mir keine gute Lösung ein.

**Comment by Nobbynews** [comment]
So genau habe ich das bei mir nicht angesehen. Mit den o.g. Einstellungen scheint es aber zu funktionieren. Die Abweichung für die 0.0001 Stelle, also 0.1l ist mMn fast schon akademisch.

![Screenshot_20220805-150625](https://user-images.githubusercontent.com/70503167/183085805-ec7f1f71-6cd1-49a7-a1e8-6ffa110deada.png)

**Comment by JensHoRi** [comment]
Wenn die nächste Ziffer erreicht ist springt er weiter. Bitte issue closen, da kein software-problem

**Comment by jomjol** [comment]
Top - dann schließe ich den Issue.

**Comment by ManfMert** [comment]
Vielen Dank für die Hinweise!

"CheckDigitIncreaseConsistency" und "AllowNegativesRates" waren zwar aktiviert, standen aber noch auf "false". 

Lt. "Raw Value" stimmen alle Ziffern, beim "Read" fehlt dann wieder 1 m^3. Bei den Zeigern gibt es noch Probleme: 6349 statt 7449!? Die linke Uhr für 0,1 Liter ist tatsächlich überflüssig. Macht es Sinn die zu entfernen?

![grafik](https://user-images.githubusercontent.com/24528404/183064410-6d7772a1-93de-4b57-9005-f113ade80d67.png)

Ein paar Stunden später passt dann fast alles. Nur die 1. Nachkommastelle ist noch falsch :-(

![grafik](https://user-images.githubusercontent.com/24528404/183115433-27f2e0a6-2441-4427-a92d-a6bd40becbe3.png)

Liegt es an der Bildqualität/schärfe? Vielleicht die Einstellung der Linse noch mal anpacken? Oder kann das über die config-Datei angepasst werden. Wohl eher nicht, weil 3 von 4 Uhren richtig erkannt werden?!

![grafik](https://user-images.githubusercontent.com/24528404/183115618-37b071cf-9400-4594-bb73-6686670718f5.png)

**Comment by Nobbynews** [comment]
Die digits sollten auf einer Höhe liegen und sind mMn zu groß. Siehe hier: https://github.com/jomjol/AI-on-the-edge-device/wiki/ROI-Configuration
Außerdem würde ich mal den Referenzpunkt bei m³ kleiner machen.

**Comment by JensHoRi** [comment]
Zwischen 8 und 9 haben die analogen Zähler leichte Probleme. 

Du solltest Max rate auf absolut 0.5 setzen. Dann meldet er zwar rate to high, springt aber nicht zu hoch (was er jetzt getan hat, du bist bei 2.8 nicht 3.8.)
dass er von x.7 auf x.9 springt und erst etwas später wieder genau ist liegt an dem Training der analogs, das musst du erstmal akzeptieren

und bitte schau nicht auf den raw value. 

Das ist der rohwert. Der value ist der, den du brauchst. Der steht noch bei 322, da du eine zu geringe rate erlaubst

**Comment by JensHoRi** [comment]
CheckDigitIncreaseConsistency" und "AllowNegativesRates" Würde ich beide deaktivieren!

**Comment by JensHoRi** [comment]
> Die digits sollten auf einer Höhe liegen .

da widerspreche ich. Ich habe einige auch tiefer, damit die früher gelesen werden. Das hängt manchmal sehr vom Zähler ab. Bei meinem gaszähler hängt eine Ziffer auch immer etwas tiefer.
