### ISSUE TITLE
Possible to read a linear scale ?

### ISSUE THREAD

**Issue by jmbinette** [jomjol/AI-on-the-edge-device#898]
Hi,

Thank you for the great project share !

I would like to know if I could use this to read a linear scale.
It is a "FlowVis" flow meter with readings looking like this :
![image](https://user-images.githubusercontent.com/24249105/182949993-e76bfa8d-24f7-4113-8f30-1355af039f51.png)

![image](https://user-images.githubusercontent.com/24249105/182949926-cbe2d95b-f347-47ef-b347-6e7a3903efad.png)

Thank you for your help

**Comment by jomjol** [comment]
In principle a algo like this is able to do this, but this would need special training data and most propably some adjustments in the software.

**Comment by jmbinette** [comment]
I would definiely be willing to supply you some training data.

In what form would be the best ? JPEG pictures of various angles and various flow rates ?

**Comment by jomjol** [comment]
I don't have the time to support single special cases in the free version. It would take me several hours of work for the training plus changing and adapting the code for a version, that I don't have for testing at home - I just cannot do this in my free time 

Although I offer commercial versions of this software, this is most propable not a use case, as the effort is much higher than the possible outcome.

Sorry to have not a better option on my side. But if you are a programmer, you can start on your own and I could combine it later with much lower effort into the main branch.

**Comment by jmbinette** [comment]
OK sorry then, I am not a programmer.
If it takes you several hours, it will take me several years lol

**Comment by jomjol** [comment]
ok - thanks for the quick exchange. I will close this issue therefore.
