### ISSUE TITLE
Training images for digit 2 being recognized as 0

### ISSUE THREAD

**Issue by blind-coder** [jomjol/AI-on-the-edge-device#901]
Hello,

as per the subject, the digits attached get recognized as "0" consistently. Pretty annoying as it's the 10-decimal place at the moment and I don't want to wait for 20.000 liters to pass through for updated data ;)

I've tried making the ROI size bigger, smaller, realigning and changing gamma, it always gets recognized as "0" instead :(

[digit_2.zip](https://github.com/jomjol/AI-on-the-edge-device/files/9270775/digit_2.zip)

**Comment by JensHoRi** [comment]
Please show ROI configuration and screen of digitization

**Comment by blind-coder** [comment]
![image](https://user-images.githubusercontent.com/3063912/183260468-bb566be3-23fa-4f88-9fd6-704cf34f4e4d.png)
![image](https://user-images.githubusercontent.com/3063912/183260480-d52740c2-8779-4135-8505-4830be63247d.png)

![image](https://user-images.githubusercontent.com/3063912/183260558-94c3752f-b0f0-4141-8419-3a5beb0a59bb.png)


Are these the ones you mean? Also, the first digit was recently treated as "1" so now I have 1520 m^3 used. Is there a way to set the "current" value to a "correct" reading?

**Comment by blind-coder** [comment]
I didset the max rate config to 0.05 absolute now to prevent this in the future :)

**Comment by jomjol** [comment]
No, I need the data out of the log folder (needs to be activated).

BUT ATTENTION: the size of the ROI must fit to the rules on this documentation: https://github.com/jomjol/AI-on-the-edge-device/wiki/ROI-Configuration
Currently it looks like your ROI is too big.

**Comment by blind-coder** [comment]
The files in the .zip are the images from /log/digit/<date>/<hour> with the leading character renamed from "0" to "2".

I'm not 100% sure what the size of the ROI has to be. I tried dragging the square around the entire area where the number can be as well as just the number, both give me "0" as a value.

**Comment by blind-coder** [comment]
I have gone through the setup about 5, maybe 6 more times now. After changing contrast to 2, LED illumination down to 5 and Brightness to -2, and re-doing the ROIs, I now have a correct reading. I'll observe if it remains.
The analogs are off by 2 on the 1/100th dgit, but I don't care much about that :)

**Comment by blind-coder** [comment]
Okay, seems to be stable now, was only a config issue. Thank you for pointing me in the right direction!
I had to increase the max rate from 0.05 to 0.15 as sometimes I have legitimate higher increases than 0.05 (bath tub), and as mentioned the 1/100th analog digit is off by 2, but that's negligible, really.

Thank you for this wonderful project!
