### ISSUE TITLE
Detect digits with black border? Need help

### ISSUE THREAD

**Issue by ljakob** [jomjol/AI-on-the-edge-device#902]
Hi,

I've got a water meter with black numbers on white with black border:

![image](https://user-images.githubusercontent.com/4210026/183469908-22c8fa2f-47d8-40d3-8125-5e7b6e1bc137.png)

I've tried many combinations of ROI-setup but number recognition is poor.

Do I have to invest in better image quality (LED glare, more pixels - camera closer) or is the poor recognition caused by the black borders around the digits? If I follow the ROI-guide what to select there will be always black pixels around the digits. My guess is that this is confusing the recognition.

Do I have to train my own model or is there an easier/better approach?

Thanks

Leif

**Comment by jomjol** [comment]
First of all the ROIs are not set perfectly - see here: https://github.com/jomjol/AI-on-the-edge-device/wiki/ROI-Configuration

Maybe I would need to train this images as well. You find the info to this in the wiki as well.

**Comment by ljakob** [comment]
Hi jomjol,

thanks for the fast response. I've changed the ROI and created a training-set:

[digits.zip](https://github.com/jomjol/AI-on-the-edge-device/files/9292955/digits.zip)

Thanks Leif

**Comment by jomjol** [comment]
Sorry, I cannot use this training data. They are not sized according to the ROI-configurationi (20% border up/top/bottom/left). 
In the LCD-digits the border is too large in the others it is too small. 

Please send me updated images - Thanks.

**Comment by ljakob** [comment]
Hi,

sorry for the mess. I've mixed my file with one from an other issue. I've created a new learning set:

[digits_corrected.zip](https://github.com/jomjol/AI-on-the-edge-device/files/9331170/digits_corrected.zip)

All new images are 21x55 pixels and all digits are 15x39pixel - so the 20% border rule should be fine.

Thanks for your great work.

Leif

**Comment by jomjol** [comment]
Your welcome - incorporated in newest training: https://github.com/jomjol/neural-network-digital-counter-readout/raw/master/dig-class11_1411_s2_q.tflite
