### ISSUE TITLE
InfluxDB config not saved properly

### ISSUE THREAD

**Issue by florisernst** [jomjol/AI-on-the-edge-device#904]
Hi,

first, let me say that you're doing a fantastic job, great work! I have one little issue with the config file, however: I am using InfluxDB to store the meter readings. Unfortunately, whenever I change something in the config page, the InfluxDB section in the configuration file gets uncommented as

`;[InfluxDB]`

Similarly, when I open the config page, the InfluxDB checkbox is unticked:

![image](https://user-images.githubusercontent.com/8627980/183873363-9a85e571-782f-4671-8366-a79ad325137b.png)

My workaround, at the moment, is to download the modified config file, uncomment the InfluxDB section, and re-upload.

Thanks for looking into this!

**Comment by friedpa** [comment]
If there is a bug, the much faster workaround is: 
- Configuration
- Edit Configuration
- Expert Mode
- Edit Config.sys direct
Don´t forget to save and reboot afterwards

**Comment by jomjol** [comment]
Bug is found and will be corrected in the next version.
