### ISSUE TITLE
ESP32 CAM & ESP32 MailClient

### ISSUE THREAD

**Issue by amanabiev10** [jomjol/AI-on-the-edge-device#905]
Hello everyone, I wanted to have the result by e-mail. Who can help me to get the ergrbmis by e-mail. The camera must send the meter readings by email. How can I link together with ESP32 MailClient

**Comment by reserve85** [comment]
I wrote a small tool in delphi which downloads the log files stored on the esp32 and put the last read of the day it in a *.csv. 
Perhaps this would be an alternative for you?

**Comment by jomjol** [comment]
Cool ideas! Could you write a short description in MarkUp-Language? Then I will add the description into the wiki and the code into the respository!

Thanks for this initiative!

**Comment by reserve85** [comment]
@jomjol: here is the package:
[Gasmeter_Logdownloader.zip](https://github.com/jomjol/AI-on-the-edge-device/files/9331038/Gasmeter_Logdownloader.zip)

**Comment by jomjol** [comment]
Thanks a lot! It will be part of the  next version.
