### ISSUE TITLE
Please add minimum SD card size and form factor to the docs

### ISSUE THREAD

**Issue by microraptor** [jomjol/AI-on-the-edge-device#906]
First of all thank you for your work on this awesome project!

It would be helpful if the docs state the minimum SD card size. I notice the contents for the install are only a few MB, but is there more space needed for generated cache or something similar? Will my ancient 64MB card be enough?

With the ESP32-CAM board and cam being so tiny, I assumed going by the pictures and the docs, that a regular sized SD card was required. Perhaps it would be good to mention that most boards come with a MicroSD card slot.

**Comment by jomjol** [comment]
If you disable ALL logging, less than 10 MB are okay. The question is, if the ancient 64MB can be adressed by the ESP32 firmware.
I don't understand your comment regarding "most boards come with a MicroSD card slot". All ESP32CAM do come with a sd card slot. If not, then this is not an ESP32CAM board, but something different.

**Comment by microraptor** [comment]
I meant it would be good to mention that a MicroSD card is required and not a "regular" sized SD card, since I was surprised to see it has a micro sized SD card slot.

What I am trying to say is that a sentence like this would be helpful in int Installation - SD Card section of the Wiki:
"A  MicroSD card with 1GB to 16GB space is recommended"

**Comment by jomjol** [comment]
Okay - got your point. But if you buy an ESP32CAM, than you see, that  this has only a MicroSD card.

On the installation page in wiki there are some hints regarding the sd card (https://github.com/jomjol/AI-on-the-edge-device/wiki/Installation)
