### ISSUE TITLE
Schlechte Erkennung, Trainigsdaten einschicken?

### ISSUE THREAD

**Issue by Alex-joomla** [jomjol/AI-on-the-edge-device#909]
Hallo Josef,

ich mache jetzt seit Januar mit meinem Projekt rum und ich verzweifle noch. Mein Wasseruhr ist ein absolutes Hassobjekt. ich habe mittlerweile den dritten Aufbau und nachdem ich die Blitzreflexionen einfach nicht in den Griff bekommen habe bin ich nun bei einem einfachen Joghurtbecher angelangt mit eingebautem Diffusor, mit dem jetzt das Bild echt gut ist. Die Recognition ist leider trotzdem sehr unzuverlässig :-(. Da mir nix mehr anderes einfällt wollte ich fragen ob du meine Digits nochmal ins Training schicken könntest?

So sieht mein Bild aktuell aus:
<img width="677" alt="Bildschirmfoto 2022-08-11 um 13 08 16" src="https://user-images.githubusercontent.com/32268233/184123569-cc7d1475-2ff4-4f50-8b33-d4cc5fbb9aea.png">

Ich weiß die Zahlen sind nicht in einer Linie aber das ist dem grottigen Zählwerk geschuldet...

Soll ich nochmal einen Datensatz fertig machen?

Grüße

**Comment by jomjol** [comment]
Richte deine ROIs bitte nach folgender Guideline aus: https://github.com/jomjol/AI-on-the-edge-device/wiki/ROI-Configuration

Wenn auch nicht auf gleicher Höhe, so sollten sie zumindest gleich groß sein. Wenn das auch nicht hilft, dann brauche ich einen Trainingsatz.

**Comment by jomjol** [comment]
Bitte bei Bedarf neuen Issue mit Trainingsdaten
