### ISSUE TITLE
Recursive deletion of log/source/*

### ISSUE THREAD

**Issue by plin2** [jomjol/AI-on-the-edge-device#911]
How can I delete all old directories with files in an easy way?

Right now I have to go into each directory, "delete all" files, go back up and delete the next day/hout files.

**Comment by jomjol** [comment]
This is not possilbe with the implemented file server. Easiest way: switch on retention days and old data will be deleted automatically, or take you your sd-card and do it by hand on the computer.

**Comment by plin2** [comment]
mmhh, and when LogfileRetentionInDays = 3 and there are still old files? Would that be a bug???

**Comment by jomjol** [comment]
I'm not sure, but I think it only checks if now one more day needs to be deleted and not all old. I did not implement that feature. Maybe you need to delete the old ones first manually.

**Comment by plin2** [comment]
Well, we are talking about 1258 directories!!! I'm not navigating into all these directories to delete all files and then the 1258 dirctories. I'd rather write a script like this

`#!/bin/bash
myhost=$1

if [ "x$myhost" = "x" ]
then
        echo "usage: AIoE_dd.sh IP address"
        exit
fi

cd /tmp/
echo "GET list of directories"
curl -s -G http://$myhost/fileserver/log/source/ | grep "fileserver/log" | sed -e 's/.*<tr><td><a href="//g' -e 's/".*//g' > AIoE_dd.days

rm AIoE_dd.hours
while read ddir
do
        echo "### GET $ddir ###"
        curl -s -G http://${myhost}${ddir}| grep "fileserver/log" | sed -e 's/.*<tr><td><a href="//g' -e 's/".*//g' >> AIoE_dd.hours
done<AIoE_dd.days

ls -lrt AIoE_dd.*

while read ddir
do
        echo " "
        echo "### DELETE ALL $ddir ###"
        newddir="${ddir/fileserver/delete}"
        curl -s -X POST http://${myhost}${newddir}?task=deldircontent
done<AIoE_dd.hours

cat AIoE_dd.days >> AIoE_dd.hours

while read ddir
do
        echo " "
        echo "### DELETE $ddir ###"
        wrk="${ddir/fileserver/delete}"
        newddir="${wrk%/}"
        curl -s -X POST http://${myhost}${newddir}
done<AIoE_dd.hours
`
