### ISSUE TITLE
Enhance the InfluxDB connector to use API Tokens for accessing Influx DB cloud

### ISSUE THREAD

**Issue by vialkoje** [jomjol/AI-on-the-edge-device#912]
Hi, I am looking for an easy way to provide a data storage and visualization for friends to easily install the AI on the Edge to read their water meters and then visualize the data on their mobile phone.

So my plan is to use cloud services of Grafana and InfluxDB - where the connection between those two already is nicely integrated.

I think the only thing (according to the documentation: https://docs.influxdata.com/influxdb/cloud/api-guide/api_intro/)  that would be missing is the chance to authenticate via an API token from the AI on the Edge application.

Is there a chance that you might enter this into the newly built influx config ? I'd try on my own also - but have a hard time in getting the initial setup of the project up and running.

regards Jens

**Comment by jomjol** [comment]
Hi, 
I fully understand your request, but unfortunately I have to tell, that I'm not going to support this in the free available version. 
I also offer commercial versions of this approach for clients. Everything, that has to do with encryption, autorization etc. is not going to be implemented in my free version.

I hope for you understanding.

Best regards,
  jomjol

**Comment by vialkoje** [comment]
Sure ! When or where can I find the commercial version ?

Von meinem iPad gesendet

**Comment by jomjol** [comment]
The commercial versions are customized firmwares for dedicated problems. There is no exact commercial version of this. It is completely free.
