### ISSUE TITLE
Config-Punkt "MaxRateType" - Kein Unterschied zwischen AbsoluteChange und RateChange  

### ISSUE THREAD

**Issue by ankulf** [jomjol/AI-on-the-edge-device#917]
Hallo,

über MQTT wird immer der RateChange Wert gesendet unabhängig von der Konfigurationseinstellung.

Kann dies reproduziert werden?

Vielen Dank.
MFG Andreas

**Comment by ankulf** [comment]
Ergänzend der Ausschnitt der Config

[PostProcessing]
;2.DecimalShift = 
PreValueUse = true
PreValueAgeStartup = 1
AllowNegativeRates = false
;2.MaxRateValue = 
2.MaxRateType = AbsoluteChange
2.ExtendedResolution = false
2.IgnoreLeadingNaN = false
ErrorMessage = true
;CheckDigitIncreaseConsistency = false

**Comment by haverland** [comment]
Ja, es ist immer die Flowrate (über die Zeit) und MaxRateType hat hier keinen Einfluss auf die MQTT Ausgabe.

**Comment by jomjol** [comment]
Das ist korrekt, aber im MQTT wird sowohl die relative Rate, wie auch die absolute Veränderung übertragen:
![grafik](https://user-images.githubusercontent.com/30766535/185797540-4d1fb48f-bd8a-48f4-8455-499c7679d878.png)
Zusammen mit der Zeitangabe  müsstest du damit alles auswerten / berechnen können.
