### ISSUE TITLE
False post-process with analog + digital (class100/cont)

### ISSUE THREAD

**Issue by haverland** [jomjol/AI-on-the-edge-device#919]
On water meters with analog and digitals on the new models the lowest digital will be false calculated if the highest analog >=9.5 and the lowest digital ist > x.5

Rate too high - Read: 73.98163 - Pre: 72.95581
in this case the 

2.7 for the 2nd digit and 
9.8 for the highest analog

**Comment by jomjol** [comment]
Implemented in v11.1.0
