### ISSUE TITLE
Digit recognition

### ISSUE THREAD

**Issue by jozsefhabit** [jomjol/AI-on-the-edge-device#92]
Hello,

thanks for this wonderful project, this was exactly what I'm looking for. I have started to play with the latest version on the last weekend. I think I could configure my ESP32-CAM properly, however for some reason the last three digits are always NaN. Analogs are seems fine.

![image](https://user-images.githubusercontent.com/796279/104955762-fe523b80-59ca-11eb-8104-89c783180563.png)

Should I wait for some time, will the recognition improve later?

Thanks in advance!

**Comment by jomjol** [comment]
Hello @jozefhabit,

it looks like your digits are not recognized by the neural network. They look a bit unsharp with low contrast. Maybe you can increase it a bit by sticking something black to the reflections and make your inner walls black. Ususally that works better. Just test it with some black paper on the inner side.
If all this does not help, the training of the neural networks needs some adaption to your digits. Let me know and I will support you.
Best regards,
  jomjol

**Comment by dibi73** [comment]
perhaps it helps if you put 2-3 layers of a transparent plastic bag over the flash (only the flash not the camera :-) ) to distort the flash. This helped in my installation.

**Comment by jomjol** [comment]
Closing for the time beeing.

**Comment by jozsefhabit** [comment]
Just a quick update. Thanks for the tips, i have a little progress here. I have added black matte color to the inside of the tube, and tried to soften and spread more the flash light with added white paper and bag plastic layers on top of the led light.

Here is the new result, this is the source raw image:
![image](https://user-images.githubusercontent.com/796279/105149816-42952700-5b04-11eb-84b9-e006fe4b595d.png)

And here is the last recognised image:
![image](https://user-images.githubusercontent.com/796279/105149952-6b1d2100-5b04-11eb-98bf-b0d1e156c9ac.png)

The image is still blurry a bit, i'll have to increase the contrast. Maybe move the camera back or forth for few cm, hopefully that would help with the sharpness. 

I'll update you with the results.
@jomjol if you could help with the training that would be great. Actually, a short wiki page with the steps needed would be the best :)

**Comment by jomjol** [comment]
@jozsefhabit 
You can find the training details here: https://github.com/jomjol/neural-network-digital-counter-readout

But I could do that, with new image available (not more than 2-3 for each digits are needed).

**Comment by jozsefhabit** [comment]
Thanks @jomjol for the link, i'm going to read it! 
I have enabled logging of digits to the SD card, I think it would take few days to get all the digits. Is it enough if I share the contents of that folder with you?

**Comment by jomjol** [comment]
@jozsefhabit Please do not share the unfiltered folder. Then I will get tousends of images and need to sort them. Please choose just 2-3 image for each digit (0, 1, ... 9) and some more representative NaN (=10) and send only the selected ones. I will incorporate them then in the training.
