### ISSUE TITLE
CNN files description

### ISSUE THREAD

**Issue by caco3** [jomjol/AI-on-the-edge-device#924]
Is there some description which CNN contains which type of digits/pointers? I only found https://github.com/jomjol/AI-on-the-edge-device/wiki/Neural-Network-Types.

**Comment by haverland** [comment]
They trained almost on similar datasets (images). 

You could find digit images here https://github.com/haverland/Tenth-of-step-of-a-meter-digit/tree/master/datasets/meterdigits and analog images https://github.com/jomjol/neural-network-analog-needle-readout/tree/main/data_raw_all 

But it not categorized on types of meters or manufacturer

**Comment by caco3** [comment]
Thanks!

Looking to the analogue pictures, I don't see pointers of my type (see https://github.com/jomjol/AI-on-the-edge-device/issues/923).
Would it make sense to add them fro training? Beside the issue in https://github.com/jomjol/AI-on-the-edge-device/issues/923 it how ever looks already good.

**Comment by haverland** [comment]
More images in dataset makes the models more robust.

For pointers you can use https://github.com/haverland/collectmeteranalog 

For digits you can use https://github.com/haverland/collectmeterdigits

**Comment by caco3** [comment]
@haverland Have you changed something in your repo? Whatever i do, I always get
```
 python3 -m collectermeteranalog --collect=watermeter --days=3
/home/me/venv/bin/python3: No module named collectermeteranalog
```

**Comment by haverland** [comment]
Thanks. I've fixed it in readme and fixed the false imports

**Comment by caco3** [comment]
I still find it very difficult to understand which tflite files I should select.
I am aware of https://github.com/jomjol/AI-on-the-edge-device/wiki/Neural-Network-Types. But it is very technical (which is great). I would wish an overview of the contained files and some brief explanation which wan to use for which purpose/situation.
For example in the following selection, there is a file named `dig-class100_s1d-md-v1.0` but the wiki page does not give any hint what `s2d.md` means.
![grafik](https://user-images.githubusercontent.com/1783586/186016593-005ecc33-c68b-42ab-9d5d-7a97093a83c6.png)

my suggestion:
 - we should either extend the wiki page and explain the networks which are contained by default. The Web UI then could link to that page.
 - Or or we add the description as a meta file to the sdcard and show it directly on the device.

I am happy to help with the implementation, but somebody else needs to provide the descriptions of the files.

@jomjol , @haverland What do you think?

**Comment by caco3** [comment]
There is a starting PR for it: https://github.com/jomjol/AI-on-the-edge-device/pull/939

**Comment by haverland** [comment]
I think most users are not familiar with deep learning. The wiki page of the internals is good, but to much for the most.

We could add a easier to understand description like that:

dig-class11:
- well suited for LCD digits
- with the ExtendedResolution option is not supported. (Only in conjunction with ana-class100 / ana-cont)

dig-class100 / dig-cont:
- suitable for all digit displays. 
- Advantage over dig-class11 that results continue to be calculated in the transition between digits.
- With the ExtendedResolution option, higher accuracy is possible by adding another digit.
- dig-class100 vs dig-cont: The difference is in the internal processing. Take the one that gives you the best results.

ana-class100 / ana-cont:
- for all analogue pointers, especially for water meters.
- With the ExtendedResolution option, higher accuracy is possible by adding another digit.
- ana-class100 vs ana-cont: The difference is in the internal processing. Take the one that gives you the best results. Both models learn from the same data.

**Comment by jomjol** [comment]
Good idea - can you modify the wiki?

You should have the right to do so.

**Comment by caco3** [comment]
How about moving the detailed (technical) wiki page to another page and add here a simplified overview?
maybe we also could add example pictures of the supported digits?

The file names are better, but a normal user still does not understand what 11 or 100 means!
Why not replace 100 eg. with supports transitions?

Are we restricted to a certain file name length?

**Comment by haverland** [comment]
> Good idea - can you modify the wiki?
> 
> You should have the right to do so.

https://github.com/jomjol/AI-on-the-edge-device/wiki/Choosing-the-Model

**Comment by caco3** [comment]
Great!

Can you add the new page to the sidemap in the wiki? It sadly needs to be added manually:
![grafik](https://user-images.githubusercontent.com/1783586/190925185-71c1f356-9529-4368-9f4a-bd5fb6223a7a.png)

And could you update the link in the web UI to this page?
https://github.com/jomjol/AI-on-the-edge-device/blob/master/sd-card/html/edit_config_param.html#L298 resp. https://github.com/jomjol/AI-on-the-edge-device/blob/master/sd-card/html/edit_config_param.html#L374

**Comment by haverland** [comment]
Already added under Configuration. In my opinion the better section.

<img width="289" alt="image" src="https://user-images.githubusercontent.com/412645/190926020-a385ed5a-e179-4d1f-80c9-f93e0e9d6c0f.png">

**Comment by caco3** [comment]
Thanks @haverland for the very nice and helpful explanations in https://github.com/jomjol/AI-on-the-edge-device/wiki/Choosing-the-Model!

just a question: which one should be preferred resp. is the default? I would think `dig-class100 / dig-cont` whould be the first option and only then `dig-class11` which is the older one to my understanding.
Can you add a comment/suggestion about that to the wiki page?

**Comment by caco3** [comment]
@haverland Did you see my suggestion in above comment?

**Comment by haverland** [comment]
> @haverland Did you see my suggestion in above comment?

In my really personal opinion, I would prefer the new Class100 or Cont models as they continue to produce good results within the transition.

For example my power meter has only one percentile digit. But it have almost all readings a good value. So I have a
hundredths accuracy (+/- 0.01).

<img width="812" alt="image" src="https://user-images.githubusercontent.com/412645/192894692-8cd8e8a6-b04f-4b8a-87c1-cbf6fd0334a9.png">

**Comment by jomjol** [comment]
In principle your right @haverland, but as soon as you a slightly different numbering than we (e.g. red on black, blue on ...) the class11 model is much broader. 
But I could change to the newer models and in case it fails, we recommend to choose the class11.
