### ISSUE TITLE
WLAN-Passwort - verbotene zeichen

### ISSUE THREAD

**Issue by dibi73** [jomjol/AI-on-the-edge-device#93]
Hallo, kann es sein, dass es "verbotene" Buchstaben/Zeichen gibt?
ich kam mit einem vorüber installierten Test-WLAN mit dem Passwort Test123 ohne Probleme in mein Netz. Nun mit einem eher langem und komplexen Passwort gibt es Probleme und ich kann nicht mehr ins Netz.
Mein WLAN Passwort der "Produktivumgebung" beinhaltet folgende Zeichen: !?{%&=/-*)+
Eventuell wird der Sting nicht escaped?

**Comment by szabocs** [comment]
Ich habe +_@ in meinem WLAN Passwort. Das geht ohne escape. Das / koennte eher ein Problem sein

**Comment by jomjol** [comment]
Das Problem ist das = Zeichen. Denn es wird momentan auch als Zuweisung verwendet und momentan wird nicht zwischen dem ersten und dem zweiten `=` unterschieden:
`password = "PASS=WORD"`
Ich schaue mal, ob ich es einfach anpassen kann.

**Comment by jomjol** [comment]
@dibi73
Teste mal die neue Rolling. Die müsste nun mit einem `=` im wlan Passwort oder der SSID auch zurechkommen.

**Comment by dibi73** [comment]
jetzt stell ich eine wahrscheinlich blöde Frage: was ist eine "Rolling"? ich habe im Code-Bereich  "Rolling 20210101" gefunden. Ist das gemeint? Vermutlich meinst du, ich soll den Code herunterladen, alles compilen und builden? Das ist vermutlich ein bisschen außerhalb meiner aktuellen Fähigkeiten. Gibt es wo eine allgemeine Anleitung wo ich mich einlesen kann?
Ich habe auch unter "History" gesehen, dass das letzte Update vor 15 Tagen war. Aber vermutlich check ich in meiner Unwissenheit gröber was nicht... Sorry.

**Comment by jomjol** [comment]
@dibi73:
Nein, du must nichts kompilieren oder ähnliches. Es ist wie folgt:
In Github kann man verschiedene Zweige (=branches) machen, um Entwicklungen zu testen. Typischerweise ist die Hauptversion, die "gut" getestet ist, der "master" oder "main" Branch. Ich habe einen "rolling"-Branch eingeführt, in dem ich die neuesten Änderungen veröffentliche. Diese sind nicht so ausführlich getestet und daher mit etwas Vorsicht zu geniesen. Du schaltest zwischen den Branches oben rechts um:

![grafik](https://user-images.githubusercontent.com/30766535/105135553-84b46d80-5af0-11eb-81b2-a900eb6cfd54.png)

Gruß,
  jomjol

**Comment by jomjol** [comment]
Topic is implemented
