### ISSUE TITLE
Image processing on different device?

### ISSUE THREAD

**Issue by copystring** [jomjol/AI-on-the-edge-device#930]
So I recently discovered this project to make my gas meter "smart". Works great!
Now I would like to achieve faster image processing.
My idea was to have image processing on my server which is running 24/7 anyway and would (I assume) be able to process the number recognition in like 1 second I guess.
That way it would be like getting live data. Not so interesting for gas meters but I also want to put this on my water meter. Live data for water meter would make much more sense.
But I guess it would mean a lot of work on this project to make this?

**Comment by jomjol** [comment]
Yes! A lot of work!
It was like this in the beginning with the use of a gas meter. But about 2 years ago I changed, because most people had problems of setting up a system with a image server and a docker server working together.
No chance of making me going back :)

**Comment by b2un0** [comment]
im also interested in this. does anyone know another projects where we can handle the images?

i like to run an docker container which and use a Google Coral TPU.

the main idea is, i would like to use the ESP32cam Module also in esphome for some other stuff.
