### ISSUE TITLE
ESP stucks on booting at wifi connection

### ISSUE THREAD

**Issue by TedSharp** [jomjol/AI-on-the-edge-device#932]
I try to build up this project for my watermeter. ESP stucks on booting at wifi connection. After reading issue #477 and #540 i've tried to set a fix ip address and delete the quotes in wlan.ini. But not works.
My router uses 2,4 & 5 Ghz stations with WPA2 + WPA3 mode. My wifi password is a 32 characters long string without special characters. 

What can i do to get the ESP running ?

[logs.txt](https://github.com/jomjol/AI-on-the-edge-device/files/9394350/logs.txt)

**Comment by jomjol** [comment]
This problem is quite unique. I have never had an issue like this. Can you test it with another device to exclude HW-problems?

**Comment by caco3** [comment]
Maybe your accesspoint is picky or itself not fully conforming the standards. You could try with a different accesspoint.

Or the signal is too weak?

**Comment by TedSharp** [comment]
I just tried it with 3 other ESPs. This behavior can be seen in all of them. Then I set up a new access point (via mobile) and my guest wifi. They all work.

After further testing it was not the weak signal. The devices work with guest wifi on same place. They use the same encryption settings. 

I think its the long wifi password for my standard access point. Has something like this already happened?

**Comment by pos-ei-don** [comment]
Did you restrict your Main Router in Not accepting slower/oder Standards linek -b? (to improve speed?) 
Your mobile Hotspot should accept all of them.

**Comment by TedSharp** [comment]
The settings shouldn't be the problem.
Have the password with a length of 20 characters changed. Now the ESP connects to the wifi.

I think I have to find another solution. Since I don't want to make the password for my standard wifi weaker, i'll probably set up another access point to connect my ESP with my network.

For me it's solved for the first time. Maybe you can check this behavior if it occurs frequently.
Thanks to all for the help.

**Comment by jomjol** [comment]
I checked my code. There is no restriction to the password length. But I alos checked Dr. Google and there seems to be a problem with 32 character long passwords:
https://esp32.com/viewtopic.php?t=13386

This is confirming your observation

**Comment by caco3** [comment]
> i'll probably set up another access point to connect my ESP with my network
Unless you run it on a different VLAN, it brings the same weakness as changing the main wifi password.

best would be to have a separate VLAN with only some specific doors to your main network. but comes with some extra cost on material and electricity.
