### ISSUE TITLE
Dig Value falsch

### ISSUE THREAD

**Issue by bmause** [jomjol/AI-on-the-edge-device#934]
Hallo, 
ich habe nun das neuste Update drauf, als RAW werden die Zahlen auch richtig erkannt glaube ich. A
Aber das Value ist falsch. Auch der Punkt wird nicht schreiben.

Was mache ich falsch ?
<img width="1025" alt="Bildschirmfoto 2022-08-22 um 18 43 20" src="https://user-images.githubusercontent.com/105861086/185974587-6059d211-fc5e-4bee-8009-cf8d6caa1bf8.png">
<img width="1022" alt="Bildschirmfoto 2022-08-22 um 18 45 02" src="https://user-images.githubusercontent.com/105861086/185974868-ee357df9-db6d-4a10-9721-a8067a181c7e.png">

**Comment by haverland** [comment]
Could be you have a positive Decimal shift?

**Comment by bmause** [comment]
> Could be you have a positive Decimal shift?

the Value cam from 03126.54

**Comment by haverland** [comment]
Kann geschlossen werden?

**Comment by bmause** [comment]
Nein, geht bei mir leider nicht so.

**Comment by jomjol** [comment]
Two topics:
1) first update to v11.1.1 (just released today)
2) your illumination is critical and might not be recongized correctly. You can controlll this with the menue "recognition" showing the really detected values (before assembly to a number)

**Comment by haverland** [comment]
Dein DecimalShift ist also -2, richtig?

**Comment by bmause** [comment]
> Dein DecimalShift ist also -2, richtig?
danke vorab für eure Unterstützung. 
Habe jetzt auf 1.11.1 upgedatet, DecimalShift -2 aus einstellt.

es jetzt schon besser, warten wir mal ab wann die Heizung wieder anspringt. Ist ja am Gaszähler installiert.

<img width="941" alt="Bildschirmfoto 2022-08-22 um 21 35 40" src="https://user-images.githubusercontent.com/105861086/186004703-6e4348ad-2a74-46e2-9b07-ded8689cf651.png">
.

**Comment by haverland** [comment]
Schön. Vielleicht noch etwas an den ROIs schrauben, dann sollte die Erkennung auch besser sein.
Wenn du ein class11 model verwendest:

https://github.com/jomjol/AI-on-the-edge-device/wiki/ROI-Configuration

Und bei class100/cont model hier noch zusätzlich eine Beschreibung: 
https://github.com/haverland/collectmeterdigits

**Comment by stefanbode** [comment]
![image](https://user-images.githubusercontent.com/16225290/189337625-cf2b3275-d5b5-44a4-85f7-926e628565f5.png)
master - v11.2.0 - 2022-08-28
This is the last digit. Issue in neural network???

**Comment by stefanbode** [comment]
I use the continuous model. Ok that a 6.7 get rounded to a 7. this might make sense.

**Comment by jomjol** [comment]
no acitivities currently - please reopen in case of further needs.
