### ISSUE TITLE
Testsystem

### ISSUE THREAD

**Issue by caco3** [jomjol/AI-on-the-edge-device#935]
It is very hard to test an algorithm, when there are no reproducible test cases.
I have some experience (pytest) on setting up automated testsystems and would like help to set one up for this great project.
@jomjol , @haverland what do you think?

- Is there a way we can run the system (or the algorithms) on a more powerful system as an ESP32?
- If not, can we run it on an ESP32 and easily replace the camera pictured by pre-selected pictures (inject them)?

**Comment by jomjol** [comment]
The usage of a more powerful hardware is rather complicated, as it would need a partially doubled software. I like the idea of picture injection a bit more, but also there you have the problem, that you also need to inject the complete configuration, as the ROI etc is also needed by the algo.

@haveland has implented testcases in the environment vscode to test the algo

**Comment by haverland** [comment]
Yes. Look at https://github.com/haverland/Tenth-of-step-of-a-meter-digit/blob/master/Compare_all_tflite.ipynb for digits. It uses the final quantized models with the complete imageset to compare all -q.tflite models.

For analog pointers https://github.com/jomjol/neural-network-analog-needle-readout/blob/main/Compare_all_tflite.ipynb it's the same

**Comment by haverland** [comment]
Or do you mean esp32 testing with AI-on-edge?

https://github.com/haverland/AI-on-the-edge-device/wiki/Testing-on-ESP32-cam

**Comment by caco3** [comment]
I was more thinking about regression testing.
On my work we automatically run certain test on a commit or pull request. This way you quickly see if something breaks (eg. regressions due to changes like in https://github.com/jomjol/AI-on-the-edge-device/issues/921).

We could take certain configurations and water meter photos and check if the output is as expected.

If we could run it virtualized, we cold automate it with Github actions.
If we only could run it on an ESP32, it would need to setup at home and run manually.

**Comment by haverland** [comment]
Many test-cases are mockable. So we could use env:native with a GitHub Action and 
run: pio test -e native

But I struggle with the components currently. Components are not accessible with test and I haven't found anything how to access it from test. We could use it from lib-folder as lib.

 But a long dependency list of other classes, I have. I could extract the methods to test.
 
 The benefit would be to test directly from desktop and as add-on a GitHub-Action could run the test on any commit. But it would be not a small change.
 
 Testing on ESP32 directly we can do, but it's not usable as CI.

**Comment by caco3** [comment]
closing it for now as there is no easy way to have it working with Github actions.
See also https://github.com/jomjol/AI-on-the-edge-device/issues/1001

Maybe we can have a look on it in the future.
