### ISSUE TITLE
Option to reduce the lamp brightness

### ISSUE THREAD

**Issue by szabocs** [jomjol/AI-on-the-edge-device#94]
In my case the picture is to bright, resulting in too much light being reflected by the
glass of the watermeter so part of the image is unclear.
The esp32cam demo firmware has the option to change the brightness of the lamp besides turning it on and off.
Is it possible to implement a config.ini option where the lamp's brightness can be set?

**Comment by jomjol** [comment]
Hi @szabocs,
tuning the lamp brightness will not help, as the camera is working in automatic mode, which means, it adjustes the illumination to the average light. If you reduce the light by 50%, the auto mode will increase the illumination time by a factor of two. Only a more general adjustment of the camera would help, this is not implemented in the code currently.

Best regards,
  jomjol
