### ISSUE TITLE
New training data for water gauge 

### ISSUE THREAD

**Issue by caco3** [jomjol/AI-on-the-edge-device#940]
Attached new training data for a GWF MTK3 Water Gauge

![grafik](https://user-images.githubusercontent.com/1783586/186248696-b357ec0a-6efa-4204-a651-24c197d54341.png)

[labeled.zip](https://github.com/jomjol/AI-on-the-edge-device/files/9410126/labeled.zip)

I labeled them with the tool from @haverland.

@haverland, it recoded around 5000 images over 3 days. How ever it only selected 45 out of them. This looks a bit low in my oppion, especially since the 4 pointers look quite different! Would it make sense to create separate training data for each pointer?

**Comment by jomjol** [comment]
Included in the latest pull request by @haverland: https://github.com/jomjol/neural-network-analog-needle-readout
