### ISSUE TITLE
Erkannter Digitwert 3.7 wird als 3 weiterverarbeitet

### ISSUE THREAD

**Issue by Matzebhv** [jomjol/AI-on-the-edge-device#942]
Moin,

habe mich heute mal an das aktuelle rolling herangewagt. Folgendes Problem tritt auf, die Erkennung aller Digits funktioniert einwandfrei. Allerdings wird hier ein Wert 3.7 als 3 weiterverarbeitet. Anscheinend wird erst ab x.8 aufgerundet. Kann man das irgendwie konfigurieren? So habe ich natürlich wegen "negativ rate" grade kein Ergebnis. 
Gruß
Matze

![Screenshot 2022-08-25 103451](https://user-images.githubusercontent.com/20025244/186617855-235752bf-b0f8-4b71-8fde-1005345c9db5.png)

**Comment by wokkeltje13** [comment]
A bit of the same issue. For me the return value was 3333.0 (the counter was running forward)
![image](https://user-images.githubusercontent.com/57153640/186619059-6f9c7888-04fd-4ca4-93ad-e9d0206eb111.png)

Next picture was analyzed correctly as 3334.0 a couple of minutes later
![image](https://user-images.githubusercontent.com/57153640/186619011-dea5f8a8-4245-45ad-b6cd-cc6502c69276.png)

**Comment by Matzebhv** [comment]
> A bit of the same issue. For me the return value was 3333.0 (the counter was running forward) ![image](https://user-images.githubusercontent.com/57153640/186619059-6f9c7888-04fd-4ca4-93ad-e9d0206eb111.png)
> 
> Next picture was analyzed correctly as 3334.0 a couple of minutes later ![image](https://user-images.githubusercontent.com/57153640/186619011-dea5f8a8-4245-45ad-b6cd-cc6502c69276.png)
> 
> running version v11.1.1

That behavior seems pretty o.k. for me. In my case its the 1000l digit. This digit will stay for an relativ long time in this position. And the next problem is, when switching to 5 i have the same problem again, this digit is never 100% in the middle.

**Comment by wokkeltje13** [comment]
I think only the last number should be rounded.
Not sure how this will react if my counter is reversing (solar panels)

**Comment by Matzebhv** [comment]
Ahh, read your post again. Your value jumps from 3333.9 to 3333.0 because you have allowed negative values. Have you tried the setting "CheckDigitIncreaseConsistency" under expert-mode?

**Comment by wokkeltje13** [comment]
> Ahh, read your post again. Your value jumps from 3333.9 to 3333.0 because you have allowed negative values. Have you tried the setting "CheckDigitIncreaseConsistency" under expert-mode?

Was not on, will evaluate right now. will this work with negative values?

**Comment by Matzebhv** [comment]
No, the raw value is absulot perfect. Check your  "MaxRateValue" setting.

**Comment by haverland** [comment]
@Matzebhv Zu deiner Frage. Nein kann man akt. leider nicht konfigurieren. Bis 0.7 wird eine Ungenauigkeit zwischen den Ziffern vermittelt. Bei größerem Bereich hatten wir schon Seiteneffekte mit anderen Zählern.

Ich würde (auch wenn es nicht so in der Anleitung steht) die ROIs 1-2 Pixel nach unten verschieben. 

Alternativ könntest du, wenn du das Projekt bauen kannst in der 
ClassFlowCNNGeneral.h die Variable "DigitalUebergangsbereichVorgaenger" verändern. Das ist +/- der Bereich in dem Ungenauigkeiten erwartet werden. Leider aktuell keine Einstellung in der Config

**Comment by haverland** [comment]
@wokkeltje13 Your picture shows a good recognition. I would lower the top of the ROI 1-2 pixels. Then you get a x.0. 
But the picture does not show the reason for the big gap between 3328.7 and 3335.2. 
As @Matzebhv describes the MaxRateValue can be set. If you use absolut it is the difference between PRE-Value and current raw value. If you use rate change its the difference per minute.
If it is to low you stock in the error a while (PreValueAgeStartup=720 minutes)

**Comment by Matzebhv** [comment]
Moin Frank, ich habe mir jetzt mit dem verschieben des betroffenen Digit nach unten behoben ( da hätte ich ach selber drauf kommen können ).
Ich habe mir zwar die Woche ein Notebook mit Debian fertiggemacht, für das Anflanschen an GIT und das Selberbauen müsste ich jetzt aber erstmal Initialwissen anlesen, und eine eigene Version hier rauszuforken halte ich auch für wenig sinnvoll. Ihr könnt ja im Hinterkopf behalten, dass es bei Zählern mit windschiefen Digits gerade im höheren Bereich ( 1000, 10000 ) zu diesen Problemen kommen kann. Falls ihr einen solchen Zähler zum testen braucht einfach melden.
Gruß
Matze

**Comment by Matzebhv** [comment]
Ich mache hier mal wieder auf, mein Gaszähler hat heute ein identisches Verhalten gezeigt. Die nicht ganz eingedrehte 5 wurde als 4.7 erkannt und mit 4 weiterverarbeitet. Ich habe hier als workaraund die ROIs ebenfalls nach unten verschoben, das scheint ja aber doch eher ein generelles Problem zu sein.

![Screenshot 2022-08-26 124146](https://user-images.githubusercontent.com/20025244/186887255-f8c05d8a-d9bc-426a-8fe0-caa06ec68bd3.png)

**Comment by pos-ei-don** [comment]
Ich hatte den Fall auch schon und hätte mir gewünscht, einen beliebigen Wert zu so einem Wert "addierbar" zu machen, damit es nach dem runden stimmt.
Ich habe zwei Zähler, einen früh drehenden und einen spät drehenden. Beim einen pässe es, beim anderen würde ich gerne ca. +0.4 dazu rechnen.

**Comment by haverland** [comment]
Es scheint mir auch noch nicht der Weisheit letzter Schluß zu sein. 
Hinterlasst ruhig vollständige Beispiele. Ich sammle sie gerade in Testfällen. Und möglichst installierte Version mitsenden. Das hilft bei der Bewertung.

**Comment by Matzebhv** [comment]
Zitat: Bis 0.7 wird eine Ungenauigkeit zwischen den Ziffern vermittelt. Bei größerem Bereich hatten wir schon Seiteneffekte mit anderen Zählern.

Vielleicht kann man dieses Verhalten ja per Konfig änderbar machen. So können die User je nach Qualität des mechanischen Zählwerks das Verhalten anpassen. Version bei beiden Instanzen hier ist die rolling von gestern -> master - v11.1.1 - 2022-08-22

**Comment by jomjol** [comment]
Hi @haverland:
wie kommst du bei dem Testcase auf eine 3.7 für die 4. Stelle?

```
        // https://github.com/jomjol/AI-on-the-edge-device/issues/942#issuecomment-1228343319
        digits = { 0.0, 7.0, 1.1, 4.7, 3.7, 5.9, 9.0, 2.7};
        analogs = {        };
        expected = "7153693";
        result = process_doFlow(analogs, digits);
        TEST_ASSERT_EQUAL_STRING(expected, result.c_str());
```

Müsste doch eher eine 2.7 sein, oder?
Ich glaube, da ging etwas mit dem Testcase davof ("704179") durcheinander und habe mal den Code angepasst:

```
        // https://github.com/jomjol/AI-on-the-edge-device/issues/942
        digits = { 0.0, 9.9, 6.8, 9.9, 3.7, 0.8, 6.9, 8.7};
        analogs = {        };
        expected = "704179";
        result = process_doFlow(analogs, digits);
        TEST_ASSERT_EQUAL_STRING(expected, result.c_str());

        // https://github.com/jomjol/AI-on-the-edge-device/issues/942#issuecomment-1228343319
        digits = { 9.9, 6.8, 1.1, 4.7, 2.7, 6.0, 9.0, 2.8};  // changed 3.7 --> 2.7 (see picture in issue)
        analogs = {        };
        expected = "7153693";
        result = process_doFlow(analogs, digits);
        TEST_ASSERT_EQUAL_STRING(expected, result.c_str());

```

Aber auf Basis dessen habe ich auch den Algo angepasst. Jetzt laufen alle Testcases erstmal durch. Commit kommt gleich.

**Comment by Matzebhv** [comment]
Ich vermute die Änderungen sind in das Rolling eingeflossen, oder? Ich habe heute Vormittag die aktuelle Rolling installiert. Der Gaszähler ist ohne Probleme den ganzen Tag durchgelaufen, hatte aber nur Änderungen durch das kochen am Nachmittag. Der Wasserzähler hatte 4 Fehlmessungen, die alle durch "negative rate" oder "rate to high" abgefangen wurden. Das waren allesamt keine Rundungsfehler sondern Fehlerkennung des 100l Digit. Das war aber immer im nächsten Durchlauf erledigt, absolute Sahne!

**Comment by jomjol** [comment]
Dann mache ich den Issue jetzt mal zu.
