### ISSUE TITLE
Use last digit's extra decimal in class100

### ISSUE THREAD

**Issue by ykri** [jomjol/AI-on-the-edge-device#944]
The latest version and class100 tflite files gave me very accurate readings. 

So I am thinking it would be great if we could use the last digit in its decimal form. For example instead of 55905.5 to get 55905.45

![image](https://user-images.githubusercontent.com/16511588/186727240-6c13d2ed-052c-415f-afbc-c4b16c273326.jpeg)

**Comment by haverland** [comment]
Set ExtendedResolution = True

**Comment by ykri** [comment]
I must be completely blind. 

Thanks!
