### ISSUE TITLE
Needs an undocumented restart required after config change

### ISSUE THREAD

**Issue by caco3** [jomjol/AI-on-the-edge-device#945]
After doing a new a `Reference Image`, `Alignment` and updating the `ROIs`, a restart is required to take the new config into account.
How ever this is nowhere in the WebUI documented.

I would add a note for this to the ROI pages and a button like on the config page:
![grafik](https://user-images.githubusercontent.com/1783586/186751802-f27498f2-c80a-4a06-b3b4-f44e5eddb3aa.png)

Without a restart, it still uses the old settings (I waited for several snapshots):
![grafik](https://user-images.githubusercontent.com/1783586/186751486-14be54de-fd0b-45bd-9b59-707a05373ff2.png)

After a restart it is correct:
![grafik](https://user-images.githubusercontent.com/1783586/186751853-82fe2bc2-a167-422f-b101-fc856b9a3a46.png)

**Comment by jomjol** [comment]
Agree!

**Comment by caco3** [comment]
ok, then I will create a PR.

Just for a better understanding:
Those 3 steps (`Reference Image`, `Alignment`, `Digital/Analog ROIs`), do they always have to happen together?
Or can one of them be done just by itself?

**Comment by caco3** [comment]
@jomjol could you please answer my questions so I can implement it correctly?

**Comment by jomjol** [comment]
No steps do be done together. You can change the Digital/Analg ROIs or the Alignment independet without interference.

**BUT: if you make a new Reference image, then all other steps have to be checked!**

Do you need further information?

**Comment by caco3** [comment]
Thanks, that answers my questions!

**Comment by caco3** [comment]
implemented in https://github.com/jomjol/AI-on-the-edge-device/pull/960
