### ISSUE TITLE
Naming inconsistency "Number" vs. "Meter"

### ISSUE THREAD

**Issue by caco3** [jomjol/AI-on-the-edge-device#946]
In the webpage title we name it a `Meter`:
![grafik](https://user-images.githubusercontent.com/1783586/186752602-9a002f58-c757-46eb-962a-24702a28410a.png)
How ever on the ROI pages we call it `Numbers`:
I would suggest to rename the `Numbers` also to `Meters`.
![grafik](https://user-images.githubusercontent.com/1783586/186752689-63534a9d-98f2-4ded-94dd-975faed9b21a.png)

Let me know if you agree and I will create a PR.

**Comment by jomjol** [comment]
I don't think, this is inconsitent. We digitalize a meter and it has serveral numbers on it. 

What do you think?

**Comment by caco3** [comment]
Ok, I see your point, especially since some meters have more than one "Number".

I tried to think of a better wording, but haven't successed yet :)
