### ISSUE TITLE
Beautify Restart Page and auto reload

### ISSUE THREAD

**Issue by caco3** [jomjol/AI-on-the-edge-device#947]
When doing a restart, the iframe shows a rater ugly non-styled message. `!!! System will restart within 5 sec!!!`.

I know this comes directly from the code (https://github.com/jomjol/AI-on-the-edge-device/blob/master/code/components/jomjol_fileserver_ota/server_ota.cpp#L438).

I would suggest to also show
- a formated message
- Using javascript to automatically reload the page once the ESP32 is up again.

let me know what you think and I will try to create a PR.

**Comment by jomjol** [comment]
Updates to the html page are always welcome - just go ahead!

**Comment by caco3** [comment]
It will also need to embed some html code in the place of https://github.com/jomjol/AI-on-the-edge-device/blob/master/code/components/jomjol_fileserver_ota/server_ota.cpp#L438

Could you explain, what the line `ESP_LOGI(TAGPARTOTA, "!!! System will restart within 5 sec!!!");` does?

For following lines I interpret that thats what gets sent to the Webbrowser:
```c
const char* resp_str = "!!! System will restart within 5 sec!!!";
    httpd_resp_send(req, resp_str, strlen(resp_str)); 
```

**Comment by jomjol** [comment]
Yes, this is true. With this line of code you send the html to the client.

**Comment by caco3** [comment]
Please have a look on https://github.com/jomjol/AI-on-the-edge-device/pull/949
