### ISSUE TITLE
Offset issue ?

### ISSUE THREAD

**Issue by tutu81** [jomjol/AI-on-the-edge-device#954]
Good day,

I'm trying to configure ROI and Alignement Marks without success, After reboot of the devices, I've a kind of offset with my picture.
![image](https://user-images.githubusercontent.com/108122193/187195606-c3a13372-a8d1-4c9a-b174-e0b63a1cd67c.png)

if I try to put a new reference image, then all my ROI and aligment marks are still setted correctly. I also tried to choose different aligment marks. 

Did I miss something ?
I use the latest GIT release

**Comment by tutu81** [comment]
my apologies, 

I found in the "expert mode" that I can extend the alignement Parameter: SearchFieldX / SearchFieldY). All good now.

![image](https://user-images.githubusercontent.com/108122193/187205171-bd439103-3991-44dc-a3d7-e540072ad58d.png)

**Comment by friedpa** [comment]
I would stick a black round sticker instead of the left alignment and a white round sticker instead of the m3 to improve the alignment.
Also a black sticker in the middle of the reflection point (the red wheel) would be good. Take e.g. a black piece of felt, that will also improve the contrast of the image.

**Comment by caco3** [comment]
You had a mark overlapping with a pointer. Not sure if the alignment works reliably when the pointer reaches the red area!

**Comment by jomjol** [comment]
The contrast of your reference structures is way too low. Just follow the suggestion of @friedpa to put a sticker with high contrast on the surface somewhere, where it does not disturb.

**Comment by tutu81** [comment]
Thx for all your advices. I unfortunately don’t manage to improve contraste. 

I will maybe try to remove the small part of the print to reduce distance between the esp32-cam and the watermeter. I keep you posted

**Comment by tutu81** [comment]
Hi All, 

I followed your advices and after some try and (a lot of) errors I managed to have proper alignement.
It is working like a charm for digital counter, butI still have some issues with analog meters. 

As you can see below, some digital counter are interpreted as analog meter. Any advices ? 

![image](https://user-images.githubusercontent.com/108122193/188160226-4768d082-6c5e-4a02-a708-70c1b079d38c.png)

**Comment by haverland** [comment]
you use dig-class11 and not dig-class100 or dig-cont. 
dig-class11 can only recognize the full digits. All other recognized as NaN as you can see.

**Comment by haverland** [comment]
Could it be the analog and digital ROIs have the same name?

**Comment by tutu81** [comment]
> Could it be the analog and digital ROIs have the same name?

It was exaclty the issue. Everything is running fine right now.

**Comment by tutu81** [comment]
If you wish, I can document both my issues (alignement and digit/analog with the same name) in the wiki / troubleshooting session ?

**Comment by caco3** [comment]
@jomjol I also would want to update some parts in the wiki.
could you give write access to it?

**Comment by jomjol** [comment]
In principle yes - how can I do that and can we have also something like the pull request mode for the wiki pages?

(I'm not very expierenced in GitHub as you might realize)

**Comment by jomjol** [comment]
I just found something and changed the settings:
![grafik](https://user-images.githubusercontent.com/30766535/188262340-7030a91e-8d7d-49c9-8e06-d434fb4db7da.png)

Can you test, if you can edit a wiki now?

**Comment by tutu81** [comment]
It works!

**Comment by caco3** [comment]
for me too!

**Comment by caco3** [comment]
Maybe you want restrict it to collaborators so not everyone can modify?
But i don't know how to mark somebody as collaborator :)

**Comment by jomjol** [comment]
I also don't know. The only thing I want to keep is, that only I can accept pull request. Otherwise we will run into a lot of trouble I think:
Need to check, the roles in GitHub - keeps me learning :-)

**Comment by caco3** [comment]
thats good to me

**Comment by jomjol** [comment]
I just made you a collaborator.

**Comment by caco3** [comment]
> I also don't know. The only thing I want to keep is, that only I can accept pull request.

It seems that I how ever now have the right to merge! Maybe that's the default value for collaborators.
On the other hand, in my opinion we simply could agree that only you merge them.

I once tried to get involved in another project. The maintainer was the only one with enough rights, but he did not care anymore about the project, pretty sad as there where a couple of people who where willing to move it on but couldn't (A fork was not an option).
