### ISSUE TITLE
Update - Problem

### ISSUE THREAD

**Issue by DerGue69** [jomjol/AI-on-the-edge-device#956]
I want to install the latest release 11.2.0.
So I download the firmware.bin, klick on OTA Upload, upload the file and then click on flash the firmware.
Normally after ~60 seconds I get the message, update complete. But this time nothing happens.
And when I click "Flash the firmware" the device is not reacting any more. Not even a pingable.

When I power the device back on again, I am still on v10.6.1

![image](https://user-images.githubusercontent.com/96002277/187275661-f6784b66-8f02-4559-89e2-3e5ce6950fb8.png)

Version Info
Git-Branch:	master
Git-Base-Branch:	master - v10.6.1 - 2022-07-24
Build Time:	2022-07-24 18:59
HTML Version: 15.1.0

**Comment by haverland** [comment]
Same on one of my devices. Looks like the firmware is not uploaded correctly. 
Sometimes works: Remove the old firmware -> upload firmware -> look if size is ok -> upload again and flash.
But most times I have to use serial again to upload.

**Comment by cbho** [comment]
Ssme problem here when trying OTA on 11.2.0 (actually also when I tried the "running" branch two days ago), but not when updating OTA before that.
Thought I'd messed up :-)

Also had to flash using serial connection (which I'd of course prefer not to, as it's quite a hassle to get to the meter...)

**Comment by DerGue69** [comment]
I am not alone ;)

**Comment by s0170071** [comment]
confirmed. OTA is not working. I have to flash with the cable.

**Comment by maestrx** [comment]
I had the same problem 2 days ago. I have 2 devices that are runnign 24/7. One one of them the the OTA update worked on first try, on the other it always failed saying server disconnected. When checkign serial console at teh same time, it stated doing OTA update, lister 2 firmwares that were identical but some crazy old ones (somethign like 0.0.9.3?) and eventually died with no further output. Power cycle fo next attempt. I finally did the update over serial.

**Comment by jomjol** [comment]
Newest version should work - at least on my devices it was updating.

**Comment by DerGue69** [comment]
I will test as fast as I can.
