### ISSUE TITLE
If MQTT fails on startup, retry periodically

### ISSUE THREAD

**Issue by caco3** [jomjol/AI-on-the-edge-device#961]
based on https://github.com/jomjol/AI-on-the-edge-device/issues/948#issuecomment-1232006803 and maybe also https://github.com/jomjol/AI-on-the-edge-device/issues/953 we really should consider to periodically retry to connect to the MQTT broker.

Since the ESP32 restarts from time to time, it could happen that (eg due to maintenance) the MQTT broker briefly is not available. if I understand https://github.com/jomjol/AI-on-the-edge-device/issues/948#issuecomment-1232006803 correctly, in such case the ESP32 would not send any MQTT message until its next restart. This is really bad as we might lose data of several hours days...

I would suggest that, whenever new data is supposed to be send over MQTT, but no connection is established, it should retry to connect first. And in any case, please add a messagew to the log if not connected or the sending failed!

**Comment by pos-ei-don** [comment]
+1.

After a Power outache, my esp32 boots faster then the mqtt. So my monitoring is brocken until I come home and Do a manual reboot again.

**Comment by s0170071** [comment]
+1 from me too. Issue appears also in todays rolling. A reboot fixes this temporarily. But only until the wifi fails.

**Comment by caco3** [comment]
Should be fixed in https://github.com/jomjol/AI-on-the-edge-device/pull/971.

But I haven't tested what happens with wifi interruptions.
