### ISSUE TITLE
Sort files in File Server

### ISSUE THREAD

**Issue by caco3** [jomjol/AI-on-the-edge-device#962]
The File Server seems not to order the files in a logic al order:
![grafik](https://user-images.githubusercontent.com/1783586/187767023-53d9a1f2-1d6d-45c1-b611-7731af693d0a.png)

Expectation:
It should sort by name or date.

**Comment by jomjol** [comment]
Your right. This is a very simple Server, that I copied and past from the esp-idf examples. If you like, you can modify.

**Comment by jomjol** [comment]
close for the time beeing
