### ISSUE TITLE
Rate too high?

### ISSUE THREAD

**Issue by Varkzor** [jomjol/AI-on-the-edge-device#963]
After my successful installation, 1 minor issue is that i do keep facing an error which i don't understand :
Rate too high - Read: 1997.031 - Pre: 1996.995

Why does it say too high, it's only a marginal upgrade from 1996,995 to 1997,031 ?
This avoids me getting more frequent and accurate value returns.

If anyone know how to avoid/fix this, input is welcome :-)

**Comment by Shineson1001** [comment]
Hi @Varkzor,
i think MaxRateValue is too small?
.. Try something like 0.5

**Comment by jomjol** [comment]
Yes, this means, that the change is bigger than the limit set by MaxRateValue.

**Comment by Varkzor** [comment]
hey guys, thanks for the update.
I changed the max rate value, how-ever i get no errors now, yet, it doesn't change the value to the new raw value, while the raw value is 100% accurate:

![image](https://user-images.githubusercontent.com/50747528/188264385-81a22a79-5fab-4a23-b104-fef9bc02cd93.png)

**Comment by Varkzor** [comment]
Does it only do that after X reads?
