### ISSUE TITLE
Add command line option python -m esptool to documentation

### ISSUE THREAD

**Issue by s0170071** [jomjol/AI-on-the-edge-device#970]
Espressif says on their [website ](https://docs.espressif.com/projects/esptool/en/latest/esp32/installation.html) that on windows systems the esptool needs to be started with the -m option. If you don't put -m there, it just doesn't find the esptool.py

So in order to start esptool, windows users have to use (using cmd line prompt)
python -m esptool  (... and then the parameters described...) 

Ideally put this program.bat file into the firmware folder: 

```
echo make sure you put the device into programming mode: push prg button while power up (i.e. connecting usb)

python -m esptool erase_flash
python -m esptool write_flash 0x01000 bootloader.bin 0x08000 partitions.bin 0x10000 firmware.bin

```

**Comment by pos-ei-don** [comment]
Ehy not use the esptool.py.exe?

**Comment by s0170071** [comment]
Because there is none.  At least not officially from Espressif.

**Comment by pos-ei-don** [comment]
I installed it from there and I have it... ;-)

**Comment by jomjol** [comment]
Comment in the documentation added
