### ISSUE TITLE
OTA fails - Server closed the connection abruptly!

### ISSUE THREAD

**Issue by caco3** [jomjol/AI-on-the-edge-device#973]
I tried to update form one rolling to another, and ended always with error `Server closed the connection abruptly!`.
Needed to do a reset to get it running again!

This is the log:
```
[20:23:11:374] handler_ota_update␍␊
[20:23:11:374] Query: file=firmware.bin␍␊
[20:23:11:383] File: /sdcard/firmware/firmware.bin␍␊
[20:23:11:383] Handle: xHandleblink_task_doFlow: 0␍␊
[20:23:11:383] Handle: xHandletask_autodoFlow: 1073534304␍␊
[20:23:11:396] Killed: xHandletask_autodoFlow␍␊
[20:23:11:396] <0x1b>[0;32mI (50164) server_ota: Starting OTA update<0x1b>[0m␍␊
[20:23:11:396] <0x1b>[0;33mW (50174) server_ota: Configured OTA boot partition at offset 0x001f0000, but running from offset 0x00010000<0x1b>[0m␍␊
[20:23:11:406] <0x1b>[0;33mW (50174) server_ota: (This can happen if either the OTA boot data or preferred boot image become corrupted somehow.)<0x1b>[0m␍␊
[20:23:11:420] <0x1b>[0;32mI (50184) server_ota: Running partition type 0 subtype 16 (offset 0x00010000)<0x1b>[0m␍␊
[20:23:11:428] <0x1b>[0;32mI (50194) server_ota: Writing to partition subtype 17 at offset 0x1f0000<0x1b>[0m␍␊
[20:23:11:436] open file /sdcard/firmware/firmware.bin in mode rb␍␊
[20:23:11:436] <0x1b>[0;32mI (50214) server_ota: New firmware version: 0.0.9.3<0x1b>[0m␍␊
[20:23:11:448] <0x1b>[0;32mI (50214) server_ota: Running firmware version: 0.0.9.3<0x1b>[0m␍␊
```

@jomjol What could be the reason? the running version was build by myself and flashed with `platformio`. Is it possible that it does not expect a bootloader?

**Comment by caco3** [comment]
I now flashed 11.2.0 through USB.
Then I tried to update it to the the same version OTA. But again it run into the server closed error...

I note: It seems my HTML cleanup (moving inline CSS to a separate file) was not that a great idea, since when you flash the latest release, the WebUI is broken as the release FW does not support the css filetype (introduced in rolling).

**Comment by caco3** [comment]
I now wipped everything from the sdcard and copied the release content onto it + the wlan.ini.
But again same error on an OTA...

**Comment by caco3** [comment]
After I used the Windows GUI tool (See https://github.com/jomjol/AI-on-the-edge-device/wiki/Installation#2-using-the-flash-tool-from-espressif) to erase and flash it once more, I was able to flash 11.2.0 over 11.2.0 **once**:
```
␛[0;32mI (43928) server_ota: Starting OTA update␛[0m
␛[0;32mI (43938) server_ota: Running partition type 0 subtype 16 (offset 0x00010000)␛[0m
␛[0;32mI (43938) server_ota: Writing to partition subtype 17 at offset 0x1f0000␛[0m
open file /sdcard/firmware/firmware.bin in mode rb
␛[0;32mI (43958) server_ota: New firmware version: 0.0.9.3␛[0m
␛[0;32mI (43958) server_ota: Running firmware version: 0.0.9.3␛[0m
␛[0;32mI (44278) server_ota: esp_ota_begin succeeded␛[0m
␛[0;32mI (54838) server_ota: Total Write binary data length: 1802384␛[0m
␛[0;32mI (54838) esp_image: segment 0: paddr=001f0020 vaddr=3f400020 size=4b898h (309400) map␛[0m
␛[0;32mI (54958) esp_image: segment 1: paddr=0023b8c0 vaddr=3ffb0000 size=04758h ( 18264) ␛[0m
␛[0;32mI (54978) esp_image: segment 2: paddr=00240020 vaddr=400d0020 size=14c0f4h (1360116) map␛[0m
␛[0;32mI (55428) esp_image: segment 3: paddr=0038c11c vaddr=3ffb4758 size=002ach (   684) ␛[0m
␛[0;32mI (55438) esp_image: segment 4: paddr=0038c3d0 vaddr=40080000 size=1bc7ch (113788) ␛[0m
␛[0;32mI (55488) esp_image: segment 5: paddr=003a8054 vaddr=50000000 size=00010h (    16) ␛[0m
␛[0;32mI (55498) esp_image: segment 0: paddr=001f0020 vaddr=3f400020 size=4b898h (309400) map␛[0m
␛[0;32mI (55608) esp_image: segment 1: paddr=0023b8c0 vaddr=3ffb0000 size=04758h ( 18264) ␛[0m
␛[0;32mI (55628) esp_image: segment 2: paddr=00240020 vaddr=400d0020 size=14c0f4h (1360116) map␛[0m
␛[0;32mI (56078) esp_image: segment 3: paddr=0038c11c vaddr=3ffb4758 size=002ach (   684) ␛[0m
␛[0;32mI (56098) esp_image: segment 4: paddr=0038c3d0 vaddr=40080000 size=1bc7ch (113788) ␛[0m
␛[0;32mI (56138) esp_image: segment 5: paddr=003a8054 vaddr=50000000 size=00010h (    16) ␛[0m
```

Then I did a reboot and tried it again (flashing 11.2.0 over 11.2.0).
This time it failed (browser shows no error but hangs simply), and the console also hangs for minutes:
```
␛[0;32mI (43328) server_ota: Starting OTA update␛[0m
␛[0;32mI (43338) server_ota: Running partition type 0 subtype 17 (offset 0x001f0000)␛[0m
␛[0;32mI (43348) server_ota: Writing to partition subtype 16 at offset 0x10000␛[0m
open file /sdcard/firmware/firmware.bin in mode rb
␛[0;32mI (43358) server_ota: New firmware version: 0.0.9.3␛[0m
␛[0;32mI (43358) server_ota: Running firmware version: 0.0.9.3␛[0m
```

@jomjol can you reproduce this?

**Comment by maestrx** [comment]
I did erase on linux using the python version of teh command few days ago. It's workign just fine. Problem is somewhere in your setup.

**Comment by caco3** [comment]
@JensHoRi Did you reset it a 2nd time (see my comment above)?

What does the USB log say?

**Comment by JensHoRi** [comment]
Because I used the other flash software, there was no log, just a success.

Very strange: It didn’t start with 5V at uart ttl (only voltage and gnd connected), it didn’t start with the cable it had been working over month…

took another usb cable it directly started. I have no idea why….

the new one is exactly the same I used before, but fresh unpacked…

It works now

**Comment by jomjol** [comment]
@caco3 I cannot confirm this problem. I do not have problem with a manual flash (almost never had) and the update based on the OTA is also working fine. To be precise I always used the current rolling (which is slightly ahead of the 11.2.0).

**Comment by JensHoRi** [comment]
Yes, had 4 ESPs last ota update went fine with 1-3, 4th failed. Because of changes I only have the first 3 one active now… and 1-2 went fine, 3rd failed. So I don’t believe it’s a software problem, maybe something with devices and temperature? Don’t know

**Comment by caco3** [comment]
@jomjol 

But could you explain the warnings in the log?
```
[20:23:11:396] <0x1b>[0;33mW (50174) server_ota: Configured OTA boot partition at offset 0x001f0000, but running from offset 0x00010000<0x1b>[0m␍␊
[20:23:11:406] <0x1b>[0;33mW (50174) server_ota: (This can happen if either the OTA boot data or preferred boot image become corrupted somehow.)<0x1b>[0m␍␊
```

**Comment by jomjol** [comment]
@caco3 : sorry I can't explain. This is a copy and paste part of another OTA example.

But looking into the code this should not be a problem because it is  not interuptiong the update process.

**Comment by caco3** [comment]
I run some more tests today.

I have 2 devices where the firmware OTA fails 9 of 10 times. Both have a build in USB port:
![grafik](https://user-images.githubusercontent.com/1783586/188513203-d3786b1a-0a10-4626-bef5-b68be0502a6f.png)

I have to admit that i don't know if OTA ever worked reliably on those devices  since i only used them in the very beginning for learning how it works.

Then I have 3 devices which need the ESP32-CAM-MB:
![grafik](https://user-images.githubusercontent.com/1783586/188513398-b33748d9-6900-4935-9c90-b1272b1067cc.png)

On all 3 devices I run several OTAs and never had an issue.

So either I have bad luck with the first 2 ones or they have a general issue.

Looking into the code all I can see that it mostly fails in `esp_ota_begin()`. How ever sometimes it also fails on another step. maybe its even related to the timing (in idle or in a flow step).

For me i will keep it as is for now and see how it goes.

**Comment by caco3** [comment]
I close it for now.

@JensHoRi please open a separate issue if you need additional support!
