### ISSUE TITLE
wifi:bcn_timout,ap_probe_send_start

### ISSUE THREAD

**Issue by HennieLP** [jomjol/AI-on-the-edge-device#987]
Every thing works but after some time I only get this Error and nothing works anymore on all my ESP-32 Cams

22:23:37.190 -> I (432141) wifi:bcn_timout,ap_probe_send_start
22:23:46.267 -> I (441201) wifi:bcn_timout,ap_probe_send_start
22:23:55.305 -> I (450251) wifi:bcn_timout,ap_probe_send_start
22:24:04.337 -> I (459301) wifi:bcn_timout,ap_probe_send_start
22:24:13.417 -> I (468351) wifi:bcn_timout,ap_probe_send_start
22:24:22.446 -> I (477411) wifi:bcn_timout,ap_probe_send_start
22:24:31.503 -> I (486461) wifi:bcn_timout,ap_probe_send_start
22:24:40.530 -> I (495501) wifi:bcn_timout,ap_probe_send_start

**Comment by friedpa** [comment]
Did you try a ping like: 
ping -t -l 1024 <IP-Address>
If that doesn´t work your ESPs lost connection to the Router. Unfortunately you have to improve the Signal strenght with e.g. a WiFi-Repeater

**Comment by HennieLP** [comment]
didn´t try a ping but the ESP was 3 meter apart from the AP with direct line of sight it could be that the Router was trying to get the ESP to switch to an other AP

**Comment by HennieLP** [comment]
I think it was just a random bug on my end now working fine
