### ISSUE TITLE
Error message contains an other value as RAW

### ISSUE THREAD

**Issue by Z18Aplha** [jomjol/AI-on-the-edge-device#990]
I really like this project but i had a very hard time to get a clear image where the digits are recognizable. I know my current setup is still not perfect but its the best i can get with the stuff around me. Next to the weird and only sometimes happening recognition of the zero as a one (see previous value) I see sometimes another weird message:
The Error message says: "Rate too high - Read 52.300 - Pre: 52.211". All in all this is correct but unfortunately i dont understand where the read value is coming from. The picture shows that the RAW value is 0052.200 (even this is not correct, but ok 😆)

![InkedScreenshot 2022-09-09 032927](https://user-images.githubusercontent.com/44472284/189255091-deb9ef1e-385d-49d0-b7ce-942696fa3f2e.jpg)

Thanks for your attention and i hope you can help me.
Furthermore i am glad to get some useful tips and tricks to improve my image and of course the recognition.

My config.ini file is attached here.

<details>
<summary>config.ini</summary>
[MakeImage]
LogImageLocation = /log/source
WaitBeforeTakingPicture = 5
LogfileRetentionInDays = 7
Brightness = -2
Contrast = 0
Saturation = 0
LEDIntensity = 100
ImageQuality = 5
ImageSize = VGA
FixedExposure = false

[Alignment]
InitialRotate = 0
InitialMirror = false
SearchFieldX = 20
SearchFieldY = 20
AlignmentAlgo = highAccuracy
FlipImageSize = false
/config/ref0.jpg 52 35
/config/ref1.jpg 504 293

[Digits]
Model = /config/dig-class11_1411_s2_q.tflite
CNNGoodThreshold = 0.5
;LogImageLocation = /log/digit
;LogfileRetentionInDays = 3
main.dig1 89 111 60 108
main.dig2 161 108 60 108
main.dig3 235 111 58 103
main.dig4 304 111 59 105
main.dig5 375 114 60 108
main.dig6 447 110 59 106
main.dig7 521 118 60 110

[Analog]
Model = /config/ana-class100_0120_s1_q.tflite
;LogImageLocation = /log/analog
;LogfileRetentionInDays = 3

[PostProcessing]
main.DecimalShift = -3
PreValueUse = true
PreValueAgeStartup = 720
AllowNegativeRates = false
main.MaxRateValue = 0.05
;main.MaxRateType = AbsoluteChange
;main.ExtendedResolution = false
main.IgnoreLeadingNaN = false
ErrorMessage = true
CheckDigitIncreaseConsistency = true

[MQTT]
Uri = mqtt://192.168.7.10:1883
MainTopic = smartmeter/watermeter_warm
ClientID = watermeter_warm
;user = USERNAME
;password = PASSWORD
;SetRetainFlag = true

;[InfluxDB]
;Uri = undefined
;Database = 
;Measurement = undefined
;user = undefined
;password = undefined

[GPIO]
;IO0 = input disabled 10 false false 
;IO1 = input disabled 10 false false 
;IO3 = input disabled 10 false false 
;IO4 = built-in-led disabled 10 false false 
IO12 = external-flash-ws281x disabled 10 false false 
;IO13 = input-pullup disabled 10 false false 
LEDType = WS2812B
LEDNumbers = 3
LEDColor = 150 150 150

[AutoTimer]
AutoStart = true
Intervall = 4

[Debug]
Logfile = true
LogfileRetentionInDays = 3

[System]
TimeZone = CET-1CEST,M3.5.0,M10.5.0/3
;TimeServer = undefined
;AutoAdjustSummertime = false
;Hostname = undefined
SetupMode = false
</details>

**Comment by dl6dbh** [comment]
same problem 
![grafik](https://user-images.githubusercontent.com/35333262/189594322-e1353e14-d99a-4063-ba66-dca5308983bc.png)

itś go away after setting   | CheckDigitIncreaseConsistency | to false

**Comment by Z18Aplha** [comment]
Yes, i can also confirm that the error disappeared after setting
```CheckDigitIncreaseConsistency``` to ```false```

Never had such an error in the last days again.

**Comment by jomjol** [comment]
Then I can close this issue

**Comment by stheine** [comment]
@jomjol , I find this already closed, but I want to add that I just experienced a very similar issue,
`{"value":"","raw":"181.3745","error":"Rate too high - Read: 362.3745 - Pre: 181.3644","rate":"","timestamp":""}`

the `raw` is correct, but the `Read` in the error message has just doubled the digital part (2*181 = 362).
This went away when I changed the `CheckDigitIncreaseConsistency` to `false`.

so maybe there is something wrong in that consistency check?

**Comment by jomjol** [comment]
Well, that info might really help!
CheckDigitIncreaseConsistency only makes sense with some special kind of Neural-Network configuration. This is not checked yet. Thanks for that very helpful hint!

**Comment by haverland** [comment]
@jomjol: Do you think we still need CheckDigitIncreaseConsistency. I think ZeigerEvalAnalogNeu do the same better.

**Comment by jomjol** [comment]
Yes we need it, there are still people using the "old" Digital (11 Classes classification). But in the new version I integrate a check, that CheckDigitIncreaseConsistency is only applied, if this is given.
Just implemented locally 15 min ago and started testing. Should be  in the rolling by today.

**Comment by Z18Aplha** [comment]
Interesting. I use the "old" 11 class classifcation model. Which one would you recommend to use? And why is  CheckDigitIncreaseConsistency only useful for this model?

**Comment by jomjol** [comment]
Because it takes care, if the last analog has changed the zero already. In the newer models (dig-class100, dig-cont) there is an information about the subposition of the reading (e.g. 7.9), which is then considered in the post processing. I would recommend to try one of this models.
