### ISSUE TITLE
How to avoid wrong readings on "fast" rotating digits?

### ISSUE THREAD

**Issue by Z18Aplha** [jomjol/AI-on-the-edge-device#991]
I use a water meter from Techem, which have the characteristic that the decimal places are also displayed by digital ROIs.
This is on the ine hand great, because the analog ROI of this water meter is trash.
But on the other hand this causes problems, because the last digit (the 0,001 digit) rotates very "fast" because this matches one litre.

The problem:
Inbetween the fully displayed numbers, the ROI is not constantly recognized as "NaN" but sometimes as an other (most of the time higher) number than the next one would be.
The image shows this very good. 

![Screenshot 2022-09-09 143700](https://user-images.githubusercontent.com/44472284/189353673-1dacf21c-8273-473f-8f45-2589a1bad073.png)

The digit is rotating from four to five, but an eight is recognized. In combination with the "AllowNegativeRates false" setting this leads to the effect that the value jumps to an higher value (very often the rotating 1 is recognized as a 7) and stays there for a long time.

For my understanding, this problem has to be for each rotating digit but is filtered for "normal" meters by the MaxRate feature. But because the last digit matches one litre, the rate feature cannot cover such a misreading.  

Is there a way to improve this?
Does it make sense to allow negative rates?

I have already read #765 and thought about splitting the last digit from the rest as he did but i wonder how this should improve the reading.

Thanks in advance!
Z18

**Comment by caco3** [comment]
Which model are you using?
You could try to use another one. I think the default one does currently not yet support partial digits.

**Comment by haverland** [comment]
Could you send a picture of the recognition page?

**Comment by haverland** [comment]
If I remember correctly, none of your digits exist as learnable images yet.
You can use https://github.com/haverland/collectmeterdigits to collect easily the images. But please read the section about configuration the ROIs before. You wide is ok, but the height is not good configured. It makes it easier to label the images after collecting.

**Comment by Z18Aplha** [comment]
> Which model are you using? You could try to use another one. I think the default one does currently not yet support partial digits.

Ah.. i forget to share my config.ini. I am sorry.
I use the class11 model. Thats the only on which seems correct for my case.

**Comment by Z18Aplha** [comment]
> Could you send a picture of the recognition page?

Yes i can. But unfortunately not for the cases already mentioned. But i reviewed them and in some cases (for example from 2 to 3) the recognition of 5 (upper part of 2 is the lower part of five and lower part of 3 is top bar of 5) was kind of understandable. The small picture really looked like a 5 in that special case.

I will post a recognition picture when strange things happen again.

**Comment by Z18Aplha** [comment]
> If I remember correctly, none of your digits exist as learnable images yet. You can use https://github.com/haverland/collectmeterdigits to collect easily the images. But please read the section about configuration the ROIs before. 

Thank you for the tip.
I changed my setup a little bit (swapped from my warm water meter to the cold water meter) to see more "action" on the numbers. Currently the Recognition works quite good but yet i havent noticed that much special cases we are talking about.

> You wide is ok, but the height is not good configured. It makes it easier to label the images after collecting.

hm i was very carefull setting the ROIs. My numbers are perfectly inbetween the inner marks. But i understand your point. It is weird that the boxes are not aligned for the meter. But thats what i get, when setting up.

I also noticed some kind of a lense above my digits, which maybe the cause for the misalignment of the ROIs? But it caused strong reflections at least..

<details>
<summary>ROIs of my setup (click me)</summary>

![Screenshot 2022-09-10 000454](https://user-images.githubusercontent.com/44472284/189452306-a1dbf026-6981-410b-b16c-dd0dda4201b9.png)
![Screenshot 2022-09-10 000519](https://user-images.githubusercontent.com/44472284/189452309-f7f1d838-a031-401c-98f7-fd198d2074ae.png)
![Screenshot 2022-09-10 000543](https://user-images.githubusercontent.com/44472284/189452310-40478b97-48ea-4cbf-b797-1f9c212991ed.png)
![Screenshot 2022-09-10 000559](https://user-images.githubusercontent.com/44472284/189452312-39a8e1e7-5a34-42bc-ab9d-9f2122f68f2a.png)
![Screenshot 2022-09-10 000621](https://user-images.githubusercontent.com/44472284/189452313-916135e0-b64d-482f-a924-26b0f144321b.png)
![Screenshot 2022-09-10 000641](https://user-images.githubusercontent.com/44472284/189452316-3f984e24-c2ae-401e-9c92-c8daa2268c19.png)
![Screenshot 2022-09-10 000658](https://user-images.githubusercontent.com/44472284/189452318-e6f57542-aa2b-4f7c-8fed-7d91c2fc0662.png)
</details>

**Comment by Z18Aplha** [comment]
I think it can be closed. It is not able to completely prevent these wrong readings but accumulating the readings over for example one hour has a positive effect.
