### ISSUE TITLE
Raw value correct, but no update on current value

### ISSUE THREAD

**Issue by nliaudat** [jomjol/AI-on-the-edge-device#994]
Hi,
I have 2 devices and the problem is the same on each : 
The "Raw value" and recognition is correct, but do not update the actual value. It may take 2-3 new flow/digitalization to update.

I have no error displayed.

My config : 
```
    [PostProcessing]
    ;cold.DecimalShift = 1
    PreValueUse = true
    PreValueAgeStartup = 720
    AllowNegativeRates = false
    cold.MaxRateValue = 250
    cold.MaxRateType = AbsoluteChange
    cold.ExtendedResolution = true
    ;cold.IgnoreLeadingNaN = false
    ErrorMessage = true
    CheckDigitIncreaseConsistency = true	
```
[Overview]
![Capture](https://user-images.githubusercontent.com/6782613/189478598-de94a2b6-7ff8-42c7-b10c-60ab680dec21.PNG)

[Recognition]

![value](https://user-images.githubusercontent.com/6782613/189478674-66b6d9ef-7aa9-470d-949a-1e578fd20eda.PNG)

![dig_counter](https://user-images.githubusercontent.com/6782613/189478678-2cff3570-1a9c-4939-bd17-954ae01c6e4c.PNG)
![recognition_dig_counter](https://user-images.githubusercontent.com/6782613/189478680-879e4a46-42bd-4cec-81a4-903c59f80c7a.PNG)

[2 rounds later]
![2nd_round](https://user-images.githubusercontent.com/6782613/189479033-825dfcb6-03e4-43aa-9bb2-35b8089f8117.PNG)

[many rounds later]
The value has grown a bit, but do not match Raw value
![much_later_round](https://user-images.githubusercontent.com/6782613/189483801-3f27f50c-4074-4d15-91f7-9e0d819d2753.PNG)

**Comment by nliaudat** [comment]
Disabling 

```
;cold.ExtendedResolution = true
;CheckDigitIncreaseConsistency = true
```
seems to fix the issue.

**Comment by haverland** [comment]
> Disabling
> 
> ```
> ;cold.ExtendedResolution = true
> ;CheckDigitIncreaseConsistency = true
> ```
> 
> seems to fix the issue.
Thanks for the hint. I'l take a look on it.

**Comment by haverland** [comment]
@jomjol: The NUMBERS->Value is float, means a precision of 7 digits. I think we need to change to double with precision of 15 digits for the value. But could be a bigger change.

I'm wondering if the checkConsistency is really needed any more. Most of the functionality is in ZeigerEval now.
Testcase [123236" ](https://github.com/jomjol/AI-on-the-edge-device/issues/994#issue-1368570945) shows an issue in it.
I would remove it if no one needs it any more.

**Comment by stefanbode** [comment]
already send a PR to change from float to double. Had the same problem. #1011
