### ISSUE TITLE
training digital ROIs

### ISSUE THREAD

**Issue by chuckomania** [jomjol/AI-on-the-edge-device#997]
Dear **jomjol**,

I would be glad if you could upload the figure to the AI. Thank You! Top project!
[digital_roi_training_data.zip](https://github.com/jomjol/AI-on-the-edge-device/files/9541222/digital_roi_training_data.zip)

Thanks a lot and best wishes,

**Comment by jomjol** [comment]
Can you test the following new version: https://github.com/jomjol/neural-network-digital-counter-readout/raw/master/dig-class11_1420_s2.tflite

It has been training including your examples.

**Comment by chuckomania** [comment]
Thank you very much. I will test it and let you know

**Comment by chuckomania** [comment]
Hello **Jomjol**
Here the result. Sometimes the 7 is interpreted as a 2. or the 0 as 8 I added new digits. 
I don't know if the background color of the digits plays a significant role. Contrast should be fine.
Thanks very much!

Example:
![Unbenannt](https://user-images.githubusercontent.com/113260591/190202925-e7a6f3f3-3e39-4c70-990f-6d67e20166ba.JPG)

[digital_roi.zip](https://github.com/jomjol/AI-on-the-edge-device/files/9567914/digital_roi.zip)

**Comment by jomjol** [comment]
The contrast is really difficult and it relly looks totally different, than the other numbers, so it could be more sensitive.
You could collect some more images e.g. with the different illuminations .... Than I could incorporate them to one of the next trainings.

**Comment by chuckomania** [comment]
Hello Jomjol.
I added new digits.
Thanks very much!
[digital_roi.zip](https://github.com/jomjol/AI-on-the-edge-device/files/9640720/digital_roi.zip)

**Comment by jomjol** [comment]
Please try this version: https://github.com/jomjol/neural-network-digital-counter-readout/raw/master/dig-class11_1430_s2.tflite

**Comment by chuckomania** [comment]
Hello  **jomjol**,
I removed the LED and soldered external LEDs. The lighting has gotten much better. I also positioned the camera a little closer. Now I have collected new digits. Many Thanks!

more images:
[digital_roi.zip](https://github.com/jomjol/AI-on-the-edge-device/files/9932827/digital_roi.zip)



![Unbenannt](https://user-images.githubusercontent.com/113260591/199829678-386d7a3c-cef5-4bcf-8afd-7cb39e5e25bb.JPG)

**Comment by jomjol** [comment]
I have trained you images. Please test the following file: https://github.com/jomjol/neural-network-digital-counter-readout/raw/master/dig-class11_1440_s2.tflite

**Comment by chuckomania** [comment]
Hello ***jomjol***
After a week of running with NO errors. Recognized everything correctly. Great work. Thanks very much!

**Comment by jomjol** [comment]
You're welcome!
